// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: ddd (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // modeling (76), design (38), design-principles (31), design-patterns (29), Design (23), ddd (20), Design Patterns (4), DDD (3), oop (2), design_patterns (1)
  { term: 'モジュール境界', description: 'どこからどこまでを一つの部品として扱うかの境目です。曖昧だと責務混在と依存拡大を招きやすいです。' },
  { term: '凝集度', description: '一つの部品の中に、どれだけ関係の深い責務がまとまっているかを示す考え方です。高いほど理解しやすくなります。' },
  { term: '結合度', description: '部品同士がどれだけ強く依存しているかの度合いです。強すぎると、一部変更が全体へ波及しやすくなります。' },
  { term: 'インターフェース境界', description: 'ある部品が外へ何を見せ、何を隠すかの境目です。内部都合を漏らしすぎると変更に弱くなります。' },
  { term: 'カプセル化', description: '内部実装を隠して、必要な操作だけ外へ公開する考え方です。利用側の影響範囲を狭く保ちやすくなります。' },
  { term: '抽象化', description: '本質的な共通点だけを抜き出して扱う考え方です。うまく使えば柔軟性が増しますが、早すぎる抽象化は複雑さを増やします。' },
  { term: '過剰抽象化', description: 'まだ必要ない段階で抽象化しすぎることです。未来に備えたつもりが、現在の理解や変更を難しくすることがあります。' },
  { term: 'アンチパターン', description: '一見よさそうでも、実際には問題を生みやすい設計や進め方です。経験知として知っておくと防ぎやすくなります。' },
  { term: 'テスタブルデザイン', description: 'テストしやすい設計です。依存分離と責務整理ができていると、自然にテスタブルになりやすいです。' },
  { term: '副作用分離', description: '計算処理と外部状態変更を分ける考え方です。理解しやすく、テストしやすいコードにつながります。' },
  { term: '純粋関数', description: '同じ入力に対して常に同じ出力を返し、外部状態を変えない関数です。テストと推論がしやすくなります。' },
  { term: '不変性', description: '一度作った値や構造をそのまま変更しない性質です。状態変化追跡がしやすくなり、バグを減らしやすいです。' },
  { term: '状態爆発', description: '状態の組み合わせが増えすぎて理解やテストが難しくなることです。画面状態やフラグ設計で起こりやすいです。' },
  { term: 'スキーマ駆動実装', description: 'API仕様やデータ定義から実装を起こしていく考え方です。一貫性と自動化の相性がよいです。' },
  { term: 'ドメイン漏れ', description: '業務上重要な概念やルールが設計やコードに十分表現されていない状態です。単なるデータ処理になってしまう原因になります。' },
  { term: 'ユビキタス言語', description: '開発者と業務側が共通で使う統一用語です。DDD文脈で重視され、設計のズレを減らす効果があります。' },
  { term: '境界意識', description: 'どこまでがこの部品の責任かを意識することです。境界が曖昧だと、便利なつもりの横断処理が増えます。' },
  { term: 'インフラリーク', description: '業務ロジックの中へ技術的都合が漏れ出している状態です。DBや外部APIの都合が深く入りすぎると変更しにくくなります。' },
  { term: 'ドメインリーク', description: '本来一部領域だけの業務概念が、他の境界へ不用意に広がる状態です。責務分離が崩れやすくなります。' },
  { term: '技術的関心事', description: 'ログ、トランザクション、認証、通信など横断的な技術課題です。業務ロジックと混在させず扱う工夫が必要です。' },
  { term: '横断関心事', description: '多くの機能に共通して現れる関心事です。認証、監査、例外処理などは代表例です。' },
  { term: 'AOP', aliases: ['aop'], description: '横断関心事を分離して扱う考え方です。便利ですが、使いすぎると実行の流れが追いにくくなることがあります。' },
  { term: 'レイヤー違反', description: '層構造のルールを破って、本来見えないはずの層へ直接依存することです。短期的には速くても、長期的には壊れやすくなります。' },
  { term: '循環参照', description: '部品同士が互いに依存し合っている状態です。理解しにくく、分離もしにくいため避けたい構造です。' },
  { term: '依存逆転適用', description: '高水準の業務ロジックが具体実装へ直接依存しないようにする実践です。テストや差し替えがしやすくなります。' },
  { term: 'アダプタパターン', description: '異なるインターフェース同士をつなぐための変換部品です。外部依存を内部都合から切り離すのに役立ちます。' },
  { term: 'ファクトリパターン', description: 'オブジェクト生成を専用ロジックへ分離する考え方です。生成方法が複雑な場合や差し替え可能性がある場合に有効です。' },
  { term: 'ストラテジーパターン', description: '処理のやり方を切り替え可能な部品として扱う考え方です。条件分岐の塊を整理しやすくなります。' },
  { term: 'テンプレートメソッド', description: '共通処理の骨格を親側に置き、一部だけ差し替える設計です。継承ベースのため、柔軟性より制御された再利用に向きます。' },
  { term: 'コマンドパターン', description: '実行要求をオブジェクトとして扱う考え方です。履歴、再実行、キュー投入と相性がよいです。' },
  { term: 'イベントハンドラ', description: '特定の出来事に応じて処理を行う部品です。イベント駆動設計では、責務の分け方が重要になります。' },
  { term: '非同期境界', description: '同期処理と非同期処理の切れ目になる箇所です。応答設計、再試行、可観測性が大きく変わるポイントです。' },
  { term: '失敗前提設計', description: '失敗は起こるものとして、再試行、代替、補償を最初から考える設計です。分散環境では特に重要です。' },
  { term: 'モジュール境界の定義', aliases: ['module boundary'], description: '単一のコンポーネントに何が属するかを定める分割線です。不明確だと責任の混在や依存関係の拡大につながります。' },
  { term: '結合度の評価', aliases: ['coupling'], description: 'コンポーネント同士がどの程度依存し合っているかの度合いです。強すぎると一部の変更が全体に波及しやすくなります。' },
  { term: 'インタフェース境界', aliases: ['interface boundary'], description: 'コンポーネントが外部に何を公開し何を隠すかの分割線です。内部詳細を漏らしすぎると変更に対して脆弱になります。' },
  { term: 'カプセル化の原則', aliases: ['encapsulation'], description: '内部の実装を隠蔽し、必要な操作だけを外部に公開するコンセプトです。利用者側への変更影響を狭くするのに役立ちます。' },
  { term: '抽象化の適用', aliases: ['abstraction'], description: '本質的な共通点だけを取り出して扱うコンセプトです。うまく使うと柔軟性が増しますが、時期尚早な抽象化は複雑性を増やします。' },
  { term: '過剰な抽象化', aliases: ['over-abstraction'], description: 'まだ必要でない段階で抽象化しすぎることです。将来への備えのつもりが現在の理解と変更を難しくしてしまいます。' },
  { term: 'アンチパターンの回避', aliases: ['anti-pattern'], description: '一見よさそうでも実際には問題を引き起こしがちな設計やアプローチです。経験から知っておくことで問題を防げます。' },
  { term: 'テスタブル設計', aliases: ['testable design'], description: 'テストがしやすい設計です。依存関係の分離と責任の整理ができていると自然とテスト容易性が生まれます。' },
  { term: '副作用分離の設計', aliases: ['side effect separation'], description: '計算処理と外部状態の変更を分けるコンセプトです。理解しやすくテストしやすいコードにつながります。' },
  { term: '純粋関数の活用', aliases: ['pure function'], description: '同じ入力に対して常に同じ出力を返し、外部状態を変更しない関数です。テストや推論が容易になります。' },
  { term: 'イミュータビリティ', aliases: ['immutability'], description: '一度作成した値や構造を変更しない性質です。状態変化の追跡を容易にし、バグの削減に役立ちます。' },
  { term: '状態爆発の問題', aliases: ['state explosion'], description: '状態の組み合わせが多くなりすぎて理解とテストが困難になることです。UI状態やフラグ設計でよく発生します。' },
  { term: 'スキーマ駆動の実装', aliases: ['schema-driven implementation'], description: 'API仕様やデータ定義から実装を導出するアプローチです。一貫性と自動化と相性がよいです。' },
  { term: 'ドメイン漏洩', aliases: ['domain leakage'], description: '重要なビジネス概念やルールが設計やコードに十分表現されていない状態です。ロジックが単なるデータ処理に成り下がります。' },
  { term: 'ユビキタス言語の確立', aliases: ['ubiquitous language'], description: '開発者とビジネス関係者が共有する統一語彙です。DDDで強調されており、設計のズレを減らすのに役立ちます。' },
  { term: '境界意識の設計', aliases: ['boundary awareness'], description: 'コンポーネントの責任がどこで終わるかを意識することです。境界があいまいだと便宜的な越境操作が増えてしまいます。' },
  { term: 'インフラ漏洩', aliases: ['infrastructure leak'], description: '技術的な懸念がビジネスロジックに漏れ出している状態です。DBや外部APIの詳細が深く浸透すると変更容易性が損なわれます。' },
  { term: 'ドメイン境界の逸脱', aliases: ['domain leak'], description: 'ひとつの境界コンテキストに属すべきビジネス概念が他に漏れ出している状態です。関心の分離が崩れる原因になります。' },
  { term: '技術横断的関心事', aliases: ['technical concern'], description: 'ログ・トランザクション・認証・通信などの横断的な技術的課題です。ビジネスロジックに混入させず分離して扱う必要があります。' },
  { term: '横断的関心事の分離', aliases: ['cross-cutting concern'], description: '多くの機能に共通して現れる関心事です。認証・監査・例外処理などが代表例です。' },
  { term: 'レイヤー違反の排除', aliases: ['layer violation'], description: '本来見えないはずのレイヤーに直接依存するレイヤードアーキテクチャのルール違反です。短期的には速くても長期的にシステムを脆弱にします。' },
  { term: '循環依存関係', aliases: ['circular reference'], description: 'コンポーネント同士が互いに依存し合う状態です。理解が難しく分離も困難で避けるべき構造です。' },
  { term: '依存性逆転適用', aliases: ['dependency inversion application'], description: '上位のビジネスロジックが具体実装に直接依存しないようにする実践です。テストや差し替えが容易になります。' },
  { term: 'アダプターパターン', aliases: ['adapter pattern'], description: '異なるインタフェースを繋ぐ変換コンポーネントです。外部依存を内部の関心事から切り離すのに役立ちます。' },
  { term: 'ファクトリーパターン', aliases: ['factory pattern'], description: 'オブジェクトの生成を専用のロジックに分離するコンセプトです。生成ロジックが複雑な場合や差し替えを望む場合に有効です。' },
  { term: 'ストラテジーパターンの活用', aliases: ['strategy pattern'], description: '処理のアプローチを差し替え可能なコンポーネントとして扱うコンセプトです。絡み合った条件分岐を整理するのに役立ちます。' },
  { term: 'コマンドパターンの適用', aliases: ['command pattern'], description: '実行要求をオブジェクトとして扱うコンセプトです。履歴・再生・キュー送信と相性がよいです。' },
  { term: 'イベントハンドラ設計', aliases: ['event handler'], description: '特定のイベントに対して処理を行うコンポーネントです。イベント駆動設計では責任の分割方法が重要です。' },
  { term: '非同期境界の設計', aliases: ['async boundary'], description: '同期処理と非同期処理が交わる地点です。この境界でレスポンス設計・リトライ・オブザーバビリティが大きく変わります。' },
  { term: '障害前提設計', aliases: ['design for failure'], description: '障害が起きることを前提にリトライ・フォールバック・補償を最初から考慮する設計です。分散環境では特に重要です。' },
  { term: 'モックアップ', description: '実装前に画面や帳票の見た目、構成、操作感を確認するために作成する試作品。' },
  { term: '機能一覧', description: 'システムが提供する機能を整理して一覧化した資料。' },
  { term: 'UI', aliases: ['ui', 'user interface', 'web ui'], description: '利用者が目で見て操作する画面や見た目のこと。' },
  { term: 'UX', aliases: ['ux', 'user experience'], description: '使いやすさや体験全体の質を指す。' },
  { term: 'SOLID', aliases: ['solid'], description: 'オブジェクト指向設計の5原則の頭文字：単一責任・オープン/クローズド・リスコフ置換・インターフェース分離・依存性逆転。' },
  { term: 'DRY', aliases: ['dry'], description: 'Don\'t Repeat Yourself。同じ知識・ロジックをコードベースに重複させないという原則。' },
  { term: 'KISS', aliases: ['kiss'], description: 'Keep It Simple, Stupid。シンプルさを最優先にし、不必要な複雑さを避ける設計原則。' },
  { term: 'オープン・クローズドの原則', aliases: ['ocp', 'open-closed principle'], description: 'ソフトウェアは拡張に対して開かれ、変更に対して閉じられているべきという原則（SOLID のO）。' },
  { term: 'インターフェース分離の原則', aliases: ['isp'], description: 'クライアントが使わないメソッドへの依存を強制しないよう、インターフェースを細かく分割すべきという原則（SOLID のI）。' },
  { term: '依存性逆転の原則', aliases: ['dip'], description: '上位モジュールは下位モジュールに依存すべきでなく、双方が抽象に依存すべきという原則（SOLID のD）。' },
  { term: '関心の分離', description: '異なる関心事（UI・ビジネスロジック・データアクセスなど）を独立したモジュールに分割する設計原則。' },
  { term: '情報隠蔽', aliases: ['information hiding'], description: 'モジュールの内部実装を外部から隠し、公開インターフェースのみを通じてアクセスさせる設計原則。' },
  { term: '継承', description: '既存クラスの属性・メソッドを引き継いで新しいクラスを定義するOOPの仕組み。' },
  { term: 'ポリモーフィズム', aliases: ['多態性', 'polymorphism'], description: '同じインターフェースや基底クラスを持つ異なる型が、それぞれの実装で異なる振る舞いをするOOPの仕組み。' },
  { term: 'デメテルの法則', aliases: ['law of demeter'], description: 'オブジェクトは直接の「友人」とのみ通信すべきで、知らないオブジェクトのメソッドを呼び出すべきでないという原則。' },
  { term: '最小知識の原則', aliases: ['principle of least knowledge'], description: 'モジュールは必要最低限の情報だけを知るべきという設計原則。デメテルの法則とも呼ばれる。' },
  { term: '不変オブジェクト', aliases: ['immutable object', 'イミュータブル'], description: '生成後に状態を変更できないオブジェクト。スレッドセーフで副作用がなく、安全に共有できる。' },
  { term: '副作用', aliases: ['side effect'], description: '関数が戻り値以外に外部の状態（グローバル変数・ファイル・DBなど）を変更すること。' },
  { term: '参照透過性', aliases: ['referential transparency'], description: '同じ引数に対して常に同じ結果を返し、外部状態に依存しない関数の性質。純粋関数の条件。' },
  { term: 'デザインパターン', aliases: ['design pattern'], description: 'ソフトウェア設計でよく現れる問題に対する再利用可能な解法のカタログ。GoFの23パターンが有名。' },
  { term: 'GoF', aliases: ['gof', 'gang of four'], description: 'Gang of Four。Gamma・Helm・Johnson・Vlissidesの4人が著した『Design Patterns』で提唱した23の設計パターン集。' },
  { term: 'ファクトリーメソッド', aliases: ['factory method'], description: 'オブジェクト生成をサブクラスに委譲し、インスタンス化する具象クラスをサブクラスが決定するGoF生成パターン。' },
  { term: '抽象ファクトリー', aliases: ['abstract factory'], description: '関連するオブジェクト群を生成するインターフェースを提供し、具象クラスを指定せずにファミリーを作成するGoFパターン。' },
  { term: 'ビルダー', aliases: ['builder'], description: '複雑なオブジェクトを段階的に組み立て、同じ構築プロセスで異なる表現を生成するGoF生成パターン。' },
  { term: 'シングルトン', aliases: ['singleton'], description: 'クラスのインスタンスが1つだけ存在することを保証し、グローバルアクセスポイントを提供するGoFパターン。' },
  { term: 'アダプター', aliases: ['adapter'], description: '互換性のないインターフェースを持つクラスを連携させるためのラッパーを提供するGoF構造パターン。' },
  { term: 'ブリッジ', aliases: ['bridge'], description: '抽象化と実装を分離し、それぞれ独立して変化できるようにするGoF構造パターン。' },
  { term: 'コンポジット', aliases: ['composite'], description: 'オブジェクトをツリー構造に組み合わせ、個々のオブジェクトとその集合を一様に扱えるGoF構造パターン。' },
  { term: 'フライウェイト', aliases: ['flyweight'], description: '多数の細粒度オブジェクトを共有して効率よくサポートするGoF構造パターン。メモリ節約に有効。' },
  { term: 'プロキシ', aliases: ['proxy'], description: '別のオブジェクトへのアクセスを制御する代理オブジェクトを提供するGoF構造パターン。' },
  { term: 'チェイン・オブ・レスポンシビリティ', aliases: ['chain of responsibility'], description: 'リクエストをハンドラーのチェーンに沿って渡し、処理できるオブジェクトが処理するGoF振る舞いパターン。' },
  { term: 'イテレーター', description: 'コレクションの内部表現を公開せずに要素を順次アクセスする方法を提供するGoF振る舞いパターン。' },
  { term: 'メディエーター', aliases: ['mediator'], description: 'オブジェクト間の複雑な相互作用をカプセル化し、疎結合を促進するGoF振る舞いパターン。' },
  { term: 'メメント', aliases: ['memento'], description: 'オブジェクトの内部状態をカプセル化して外部に保存し、後でその状態に復元できるGoF振る舞いパターン。' },
  { term: '監視者パターン', description: 'オブジェクトの状態変化を他の依存オブジェクトに自動通知するGoF振る舞いパターン。オブザーバーとも呼ぶ。' },
  { term: 'オブザーバー', aliases: ['observer'], description: 'あるオブジェクトの状態変化を複数の依存オブジェクトへ通知・更新するGoF振る舞いパターン。監視者パターンとも呼ぶ。' },
  { term: 'ステート', description: 'オブジェクトの内部状態が変わると振る舞いも変わるように見せるGoF振る舞いパターン。' },
  { term: 'ストラテジー', aliases: ['strategy'], description: 'アルゴリズムのファミリーを定義・カプセル化し、相互に交換可能にするGoF振る舞いパターン。' },
  { term: 'ビジター', aliases: ['visitor'], description: 'データ構造の要素に対して実行する操作を、クラスを変えずに追加できるGoF振る舞いパターン。' },
  { term: 'Null Object', aliases: ['null object'], description: 'nullの代わりにデフォルト動作を持つオブジェクトを返すことでnullチェックを排除する設計パターン。' },
  { term: 'Repository Pattern', aliases: ['repository pattern', 'リポジトリパターン'], description: 'データソースへのアクセスをカプセル化し、ドメインオブジェクトとデータマッピングロジックを分離するパターン。' },
  { term: 'Unit of Work', aliases: ['unit of work', '作業単位'], description: '一連のビジネス操作で影響を受けるオブジェクトを記録し、一貫性を保ちながら変更をまとめてコミットするパターン。' },
  { term: 'DIコンテナ', aliases: ['diコンテナ', 'di container'], description: '依存性注入（DI）を自動的に管理するフレームワーク。オブジェクトの生成・ライフサイクル・依存解決を担う。' },
  { term: 'Inversion of Control', aliases: ['inversion of control'], description: 'プログラムの制御フローを開発者からフレームワークへ反転させる設計原則。DIはその実現手段のひとつ。' },
  { term: 'フェイルファスト', aliases: ['fail-fast'], description: 'エラーを早期に検出してシステムを即座に停止させ、障害の伝播を防ぐ設計原則。' },
  { term: 'フェイルセーフ', aliases: ['fail-safe'], description: '障害発生時にシステムが安全な状態へ自動的に移行する設計原則。' },
  { term: 'Idempotency', aliases: ['idempotency'], description: '同じ操作を何度実行しても結果が変わらない性質。APIリトライやメッセージ再送時の安全性を保証する。' },
  { term: '再入可能性', aliases: ['reentrant', '再入可能'], description: '関数が実行中に再度呼び出されても正しく動作する性質。マルチスレッド・シグナルハンドラーで重要。' },
  { term: 'レートリミット', aliases: ['rate limiting', 'レート制限'], description: '一定時間内のリクエスト数を制限し、APIの過負荷・乱用を防ぐ仕組み。' },
  { term: 'サーキットブレーカー', aliases: ['circuit breaker'], description: '依存サービスの障害を検知し、一定時間リクエストを遮断してシステム全体の連鎖障害を防ぐパターン。' },
  { term: 'リトライ', aliases: ['retry'], description: '一時的な障害時に自動的に操作を再試行する仕組み。冪等性が保証されている操作に適用すべき。' },
  { term: 'タイムアウト', aliases: ['timeout'], description: '処理が一定時間内に完了しない場合に強制的に中断する仕組み。スレッド枯渇やリソースリークを防ぐ。' },
  { term: 'スロットリング', aliases: ['throttling'], description: 'リソース使用量やリクエスト速度を意図的に制限し、システムの安定性を保つ仕組み。' },
  { term: 'バルクヘッド', description: 'システムをリソースプールで区画化し、一部の障害が他の部分に波及しないよう隔離するパターン。' },
  { term: '耐障害性', aliases: ['fault tolerance'], description: 'システムが部分的な障害が発生しても機能を維持し続ける能力。冗長化・フェイルオーバーなどで実現。' },
  { term: '回復性', aliases: ['resilience', 'レジリエンス'], description: '障害から自動的に回復し、通常状態に戻る能力。リトライ・サーキットブレーカーなどで実現。' },
  { term: 'Leaky Abstraction', aliases: ['leaky abstraction', '漏れた抽象化'], description: '抽象化が内部の実装詳細をにじみ出させてしまう現象。完全な抽象化は不可能というJoel Spolskyの法則。' },
  { term: 'Premature Optimization', aliases: ['premature optimization', '時期尚早な最適化'], description: '必要性が確認される前にパフォーマンス最適化を行うこと。「時期尚早な最適化は諸悪の根源」という格言で有名。' },
  { term: 'Tight Coupling', aliases: ['tight coupling', '密結合'], description: 'コンポーネント間の依存が強く、一方の変更が他方に影響しやすい設計状態。テストや再利用が困難。' },
  { term: 'Loose Coupling', aliases: ['loose coupling'], description: 'コンポーネント間の依存を最小化し、互いに独立して変更・テスト・再利用できる設計状態。' },
  { term: 'Cohesion', aliases: ['cohesion'], description: 'モジュールやクラス内の要素が同一の目的に向けて強く結びついている度合い。高凝集が望ましい。' },
  { term: '外部設計', aliases: ['概要設計'], description: 'ユーザーから見えるシステムの仕様を定義する設計工程。画面レイアウト、帳票、他システムとの連携などを設計する。基本設計と同義に使われることが多い。' },
  { term: '内部設計', description: 'システムの内部構造・ロジックを詳細に設計する工程。データベース設計、クラス設計、処理フローなどを決める。詳細設計と同義に使われることが多い。' },
  { term: 'レビュー観点', aliases: ['レビューチェックリスト'], description: '設計書やソースコードをレビューする際にチェックすべき項目のリスト。「要件との整合性」「セキュリティ」「パフォーマンス」などの観点で確認する。' },
  { term: '設計標準', aliases: ['設計規約', 'コーディング標準'], description: 'プロジェクト内で設計書を作成する際のルール・フォーマット・命名規則などを定めた標準。統一感を持たせ、品質を均一に保つために使われる。' },
  { term: '図解言語', description: '概念や構造を視覚的に表現するための図・記号・記法の体系。UMLやDFDなどが代表例。' },
  { term: 'ホムンクルス', aliases: ['homunculus'], description: '図解において人間を表す棒人間アイコン。ユースケース図のアクターなどに使用される。' },
  { term: 'マジックナンバー4±1', aliases: ['magic number 4±1'], description: '人間が短期記憶で同時に保持できる情報の数は約4±1であるという認知心理学の知見。図解の情報量設計に活用。' },
  { term: 'マインドマップ', aliases: ['mind map'], description: '中心テーマから放射状に関連アイデアを枝として展開するビジュアル思考ツール。' },
  { term: '自由形式の図', description: '厳密な記法に縛られず概念や構造を自由に表現するための非形式的な図。スケッチとも呼ばれる。' },
  { term: 'UMLスケッチ', aliases: ['umlスケッチ', 'uml sketch'], description: 'UMLの記法を厳密に守らずコミュニケーション目的でラフに描いたUML図。' },
  { term: 'デバイス', description: 'UML配置図においてハードウェアノードを表すステレオタイプ。サーバ・PC・モバイル端末などを示す。' },
  { term: '提供インターフェース', aliases: ['provided interface'], description: 'UMLコンポーネント図においてコンポーネントが外部に提供するインターフェース（ロリポップ記号）。' },
  { term: '要求インターフェース', aliases: ['required interface'], description: 'UMLコンポーネント図においてコンポーネントが外部に要求するインターフェース（ソケット記号）。' },
  { term: 'ロバストネス図', aliases: ['ロバストネス分析図', 'robustness diagram', 'robustness analysis diagram'], description: 'ICONIXプロセスで用いるユースケースをバウンダリ・コントロール・エンティティの3要素で表現した分析図。' },
  { term: 'バウンダリ', aliases: ['boundary'], description: 'ロバストネス図において境界（画面・外部システムなど）を表すオブジェクト種別。' },
  { term: 'コントロール', description: 'ロバストネス図においてビジネスロジック・制御を担うオブジェクト種別。' },
  { term: '属性', description: 'UMLクラス図においてクラスのデータ項目を表す要素。型と可視性を持つ。' },
  { term: '操作', description: 'UMLクラス図においてクラスの振る舞い（メソッド）を表す要素。シグニチャと可視性を持つ。' },
  { term: '可視性', description: 'UMLにおいてクラスのメンバーへのアクセス制御を示す概念。public(+)・protected(#)・private(-)などがある。' },
  { term: '抽象クラス', description: 'インスタンス化できないクラス。サブクラスが実装すべき抽象メソッドを定義する。UMLではクラス名をイタリック体で表記。' },
  { term: '汎化', aliases: ['generalization'], description: 'UMLにおけるクラス間の継承関係を表す関係。サブクラスはスーパークラスを特殊化したもの。' },
  { term: 'ライフライン', aliases: ['lifeline'], description: 'UMLシーケンス図において参加オブジェクト・コンポーネントを表す垂直の破線。' },
  { term: 'アクティベーション', description: 'UMLシーケンス図においてオブジェクトがメッセージを処理している期間を示す薄い矩形。' },
  { term: '同期メッセージ', aliases: ['synchronous message'], description: 'UMLシーケンス図において送信側が応答を待つメッセージ。実線塗りつぶし矢印で表す。' },
  { term: '非同期メッセージ', aliases: ['asynchronous message'], description: 'UMLシーケンス図において送信側が応答を待たないメッセージ。開いた矢印で表す。' },
  { term: '戻り値メッセージ', description: 'UMLシーケンス図において呼び出しの応答として返されるメッセージ。破線矢印で表す。' },
  { term: 'データモデリング', aliases: ['data modeling'], description: '業務で扱うデータの構造・関係・制約を抽象的に表現するモデルを作成する活動。' },
  { term: 'ERモデル', aliases: ['erモデル', 'e-rモデル', '実体関連モデル', 'er model', 'e-r model', 'entity-relationship model'], description: 'エンティティ（実体）とリレーションシップ（関連）を用いてデータ構造を表現するモデル。' },
  { term: 'Peter Chen記法', aliases: ['peter chen記法'], description: 'ERモデルの原典的記法。エンティティを矩形・関連をひし形・属性を楕円で表現する。' },
  { term: 'Crow\'s Foot記法', aliases: ['crow\'s foot記法', '鳥の足記法'], description: 'ERモデルの記法の一つ。関係の多重度をカラスの足に似た記号で表現する。' },
  { term: 'IDEF1X', aliases: ['idef1x'], description: '米国防総省が標準化したERモデリング記法。主にデータ統合・リレーショナルDB設計に使われる。' },
  { term: '概念ER', aliases: ['概念er', '概念erモデル', 'conceptual er', 'conceptual er model'], description: '業務の概念・ルールをエンティティと関連で表現したERモデルの最初の抽象レベル。' },
  { term: '論理ER', aliases: ['論理er', '論理erモデル', 'logical er', 'logical er model'], description: '概念ERをDBMS非依存の形で正規化・詳細化したERモデルの中間レベル。' },
  { term: 'Mermaid', aliases: ['mermaid', 'mermaid.js'], description: 'Markdownライクなテキストからフローチャート、シーケンス図、ER図などを生成できる図表記法・ツールです。' },
  { term: '図式言語', aliases: ['diagramming language'], description: '概念や構造を視覚的に表現するための図・記号・記法体系です。UMLやDFDが代表例です。' },
  { term: 'フリーフォーム図', aliases: ['free-form diagram'], description: '厳密な記法にとらわれず概念や構造を自由に表現したインフォーマルな図です。スケッチとも呼ばれます。' },
  { term: 'デバイス（UML）', aliases: ['デバイス（uml）', 'device'], description: 'UML配置図においてサーバーやPC、モバイル機器などのハードウェアノードを表すステレオタイプです。' },
  { term: '属性（UML）', aliases: ['属性（uml）', 'attribute'], description: 'UMLクラス図においてクラスのデータ項目を表す要素で、型と可視性を持ちます。' },
  { term: 'オペレーション', aliases: ['operation'], description: 'UMLクラス図においてクラスの振る舞い（メソッド）を表す要素で、シグネチャと可視性を持ちます。' },
  { term: '可視性（UML）', aliases: ['可視性（uml）', 'visibility'], description: 'UMLにおけるクラスメンバーのアクセス制御の概念です。public(+)・protected(#)・private(-)などの値があります。' },
  { term: '実行仕様（アクティベーション）', aliases: ['activation'], description: 'UMLシーケンス図においてオブジェクトがメッセージを処理している期間を示す細い矩形です。' },
  { term: '応答メッセージ', aliases: ['return message'], description: 'UMLシーケンス図において呼び出しへの応答として返されるメッセージで、破線矢印で表現されます。' },
  { term: 'クロウズフット記法', aliases: ['crow\'s foot notation', 'bird\'s foot notation'], description: 'リレーションシップのカーディナリティをカラス足記号で表現するER記法です。' },
  { term: '用語分析', description: 'ドメインで使われる用語を収集・整理し共有理解を確立する活動。ユビキタス言語の基礎となる。' },
  { term: 'ドメインモデリング', description: '対象業務の概念・ルール・関係をオブジェクトモデルとして表現する活動。' },
  { term: '分析クラスモデル', description: 'ドメイン分析で得られたクラスとその関連をUMLクラス図で表現したモデル。' },
  { term: '分析クラスモデリング', description: 'ドメイン分析の結果をクラスとその関連として整理するモデリング活動。' },
  { term: 'ビジネスユースケース', description: '組織レベルのビジネスプロセスをアクターとユースケースで表現したモデル。' },
  { term: 'BCEモデル', aliases: ['bceモデル'], description: 'Boundary・Control・Entityの3要素でシステムの責務を分類するモデル。ロバストネス分析の基礎。' },
  { term: '用語定義', aliases: ['term definition'], description: 'システム・ドキュメントで使用する用語の意味・範囲・使い分けを明確化した定義集。' },
  { term: '概念モデル', aliases: ['conceptual model'], description: '業務や問題領域の本質的な概念と関連を表現したモデル。実装やDBMSを意識しない抽象レベル。' },
  { term: '論理モデル', aliases: ['logical model'], description: '概念モデルをDBMS非依存の形で詳細化したモデル。正規化・データ型・関係を定義する。' },
  { term: 'モデリング', aliases: ['modeling'], description: '現実世界の対象を抽象化して表現・分析するための活動。UML・ER図などが手法として使われる。' },
  { term: '表現力', aliases: ['expressive power'], description: 'モデリング言語や記法が持つ概念の表現能力。表現力が高いほど多様な概念を記述できる。' },
  { term: 'UML as sketch', aliases: ['uml as sketch'], description: 'コミュニケーション目的でUMLを軽い手描きレベルで使うアプローチ。厳密さより速さと理解を優先する。' },
  { term: 'Agile Modeling', aliases: ['agile modeling'], description: 'アジャイルプロジェクトにおける軽量なモデリングプラクティス。価値のあるモデルだけを作成する考え方。' },
  { term: 'ロバストネス分析', aliases: ['robustness analysis'], description: 'ユースケースをバウンダリ・コントロール・エンティティに分解してクラス設計へ橋渡しする分析手法。' },
  { term: 'データフロー', description: 'システム内でデータが処理・変換・移動する経路。DFDで可視化される。' },
  { term: '自然なモデル', aliases: ['natural model'], description: '業務の言葉・概念をそのまま反映した直感的に理解しやすいドメインモデル。' },
  { term: 'オブジェクトモデル', description: 'システムをオブジェクトとその関係で表現したモデル。クラス図やシーケンス図で表す。' },
  { term: 'UMLドメインモデル', aliases: ['umlドメインモデル', 'uml domain model'], description: 'UMLクラス図を用いてドメインの概念・関連・制約を表現したモデル。' },
  { term: '分析クラス', aliases: ['analysis class'], description: 'ドメイン分析から導出されたクラス。実装クラスと対応しないことがあり業務概念を優先する。' },
  { term: '所有', description: 'オブジェクト間の関係でAがBのライフサイクルを管理する強い関連（集約・コンポジション）。' },
  { term: '支配', description: 'オブジェクト間の関係でAがBの振る舞いを制御・指示する権限を持つ関係。' },
  { term: 'システムユースケース', aliases: ['system use case'], description: 'システムが外部アクターに提供する機能をユースケースとして定義したもの。' },
  { term: 'ビジネスシーケンス', aliases: ['business sequence'], description: '業務の流れを時系列で表現したシーケンス図またはフロー。ビジネスプロセスを可視化する。' },
  { term: 'システムシーケンス', aliases: ['system sequence'], description: 'システムとアクター間の相互作用を時系列で表現したUMLシーケンス図。' },
  { term: 'DFD記法', aliases: ['dfd記法', 'dfd notation'], description: 'Data Flow Diagramの記法。プロセス・データストア・データフロー・外部エンティティの4要素で表現する。' },
  { term: 'ソフトウェアスタック図', aliases: ['software stack diagram'], description: 'システムが使用するソフトウェア層の構成を視覚化した図。' },
  { term: 'スタック図', aliases: ['stack diagram'], description: 'ソフトウェアスタックや技術要素の階層を示した図の総称。' },
  { term: '組織図', description: '組織の部門・役職・指揮命令系統を示した図。' },
  { term: 'Free Form', aliases: ['free form'], description: '形式を問わない自由記述形式の図や表現スタイル。' },
  { term: 'スケッチ記法', aliases: ['sketch notation'], description: '正確さより速度とコミュニケーションを優先した非形式的な図の描き方。' },
  { term: '厳密記法', aliases: ['formal notation'], description: 'UMLなどの規格に完全に準拠した正確な図の描き方。ツールによる処理・検証を想定する。' },
  { term: 'DFD論理モデル', aliases: ['dfd論理モデル', 'dfd logical model'], description: '実装手段を意識せずビジネスプロセスのデータの流れを表現したDFD。' },
  { term: 'DFD物理モデル', aliases: ['dfd物理モデル', 'dfd physical model'], description: '実際の処理・システム・ファイルの物理的な実装を反映したDFD。' },
  { term: '非依存実体', aliases: ['independent entity'], description: '他のエンティティに依存せず独立して存在できるエンティティ（強実体）。' },
  { term: '依存実体', aliases: ['dependent entity'], description: '他のエンティティの存在に依存する弱実体。親エンティティなしには識別・存在できない。' },
  { term: 'カーディナリティ', aliases: ['cardinality'], description: 'エンティティ間の関係における多重度（1:1・1:N・M:N）。ERモデルの重要な要素。' },
  { term: 'コンポーネント配置図', aliases: ['component deployment diagram'], description: 'システムのコンポーネント・モジュールとその配置関係を表すUML配置図またはシステム構成図。' },
  { term: 'ファクトリ', aliases: ['factory'], description: '複雑なドメインオブジェクトや集約の生成ロジックをカプセル化する設計パターン。生成の複雑さをドメインモデルから切り離し、一貫した状態のオブジェクトを生成する責務を担う。' },
  { term: 'ドメインイベント', aliases: ['domain event'], description: 'ドメイン内で発生した業務的に重要な出来事を表すオブジェクト。過去形で命名され、集約の状態変化を他の集約やサービスに通知するために使われる。' },
  { term: 'コンテキストマップ', aliases: ['context map'], description: '複数の境界づけられたコンテキスト間の関係性と統合パターンを図示したもの。上流・下流の依存関係や、共有カーネル・順応者などの関係を可視化する。' },
  { term: '共有カーネル', aliases: ['shared kernel'], description: '二つの境界づけられたコンテキストが共同で所有・管理するモデルの共通部分。変更には両チームの合意が必要で、密結合を生むため慎重に使う。' },
  { term: '順応者', aliases: ['conformist'], description: '上流の境界づけられたコンテキストのモデルをそのまま受け入れ、自チームのモデルを上流に合わせる関係パターン。腐敗防止層を置かず、上流の変更に追随する。' },
  { term: '公開ホストサービス', aliases: ['open host service', 'ohs'], description: '境界づけられたコンテキストが外部に公開するプロトコルやAPIを定義したもの。複数の下流コンテキストが利用できるよう、安定したインターフェースを提供する。' },
  { term: '発行言語', aliases: ['published language'], description: '公開ホストサービスが使用する共有フォーマット。XMLやJSONなど、コンテキスト間でやり取りするデータの表現形式を標準化する。' },
  { term: '集約設計', aliases: ['aggregate design'], description: '整合性境界としての集約をどのように定義するかの設計判断。集約は小さく保ち、集約内のみトランザクション整合性を保証し、集約間は結果整合性で連携する。' },
  { term: '戦術的設計', aliases: ['tactical design'], description: 'DDDにおけるコード実装レベルの設計パターン群。エンティティ、値オブジェクト、集約、ファクトリ、リポジトリ、ドメインサービスなどのビルディングブロックを用いてドメインモデルを実装する。' },
  { term: '戦略的設計', aliases: ['strategic design'], description: 'DDDにおけるシステム全体の構造を決める高レベルの設計。境界づけられたコンテキスト、ユビキタス言語、コンテキストマップを用いてドメインの全体像を設計する。' },
  { term: 'イベントストーミング', aliases: ['event storming'], description: 'ドメインエキスパートと開発者が付箋を使い、ドメインイベントを中心にビジネスフローを可視化するワークショップ手法。DDDの戦略設計や境界づけられたコンテキストの発見に活用される。' },
  { term: 'サブドメイン', aliases: ['subdomain'], description: '業務ドメインを問題空間で分割した領域。コアドメイン、支持サブドメイン、汎用サブドメインの3種に分類され、投資優先度の判断に使われる。' },
  { term: 'コアドメイン', aliases: ['core domain'], description: '競争優位性を生む最も重要なサブドメイン。ビジネスの本質的な差別化要素であり、最も優秀な開発者と最大のリソースを投入すべき領域。' },
  { term: '支持サブドメイン', aliases: ['supporting subdomain'], description: 'コアドメインを支援するが、汎用ではないサブドメイン。自社固有のロジックを含むが差別化には直結しない。内製するか外注するかを検討する領域。' },
  { term: '汎用サブドメイン', aliases: ['generic subdomain'], description: 'どの企業でも必要だが差別化に関係しないサブドメイン。認証、通知などが該当し、既製品やSaaSの活用が推奨される。' },
  { term: 'ドメインオブジェクト', aliases: ['domain object'], description: 'ドメインモデルを構成するオブジェクトの総称。エンティティ、値オブジェクト、集約ルート、ドメインサービスなどが含まれ、ビジネスロジックを持つ。' },
  { term: '業務ドメイン', aliases: ['business domain'], description: 'ソフトウェアが解決しようとするビジネスの問題領域全体。DDDではこの業務ドメインを深く理解し、ソフトウェアモデルに反映させることを重視する。' },
  { term: 'シングルトンパターン', aliases: ['singleton pattern'], description: 'クラスのインスタンスをアプリケーション全体で1つだけ生成することを保証するデザインパターンです。設定管理やログ管理に広く使用されます。' },
  { term: '責務分離不全', description: '本来分けるべき役割が同じクラスや層に混在し、変更理由が整理されていない状態です。' },
  { term: '貧血ドメインモデル', description: 'データだけを持ち、業務ルールや振る舞いをほとんど持たないドメインモデルです。' },
  { term: '手続き型', description: 'データに対して順番に処理手順を適用していくことを中心にした設計やプログラミングの考え方です。' },
  { term: 'マジックストリング多用', description: '意味のある定数化をせず、同じ文字列リテラルを各所へ直接書き散らしている状態です。' },
  { term: 'God Classの変更影響', aliases: ['god classの変更影響'], description: '責務を抱え込みすぎた巨大クラスを変更したときに、多方面へ波及してしまう影響です。' },
];
