// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: azureServices (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // azure (192), Azure (2)
  { term: 'Azure', aliases: ['azure'], description: 'Microsoftのクラウドサービス群の総称です。企業向け認証基盤や業務システムとの親和性が高いです。' },
  { term: 'Azure Virtual Network', aliases: ['azure virtual network'], description: 'Azure上の論理ネットワークです。略してVNetと呼ばれます。' },
  { term: 'VNet', aliases: ['vnet'], description: 'Azure Virtual Networkの略称です。サブネットやルート、セキュリティを含む基本単位になります。' },
  { term: 'Subnet in Azure', aliases: ['subnet in azure'], description: 'VNet内を分割したネットワーク領域です。役割分離やセキュリティ設計に使います。' },
  { term: 'Network Security Group', aliases: ['network security group'], description: '【Azure】通信許可、拒否を制御するAzureの仕組みです。略してNSGと呼ばれます。 【OCI APEX】リソース単位で適用しやすい通信制御グループ。' },
  { term: 'NSG', aliases: ['nsg'], description: 'Network Security Groupの略称です。サブネットやNIC単位の通信制御に使えます。' },
  { term: 'Azure Load Balancer', aliases: ['azure load balancer'], description: 'Azureの負荷分散サービスです。可用性向上やトラフィック分散に使います。' },
  { term: 'Azure Application Gateway', aliases: ['azure application gateway'], description: 'L7レベルで動作するAzureのアプリケーション向けゲートウェイです。Web系のルーティングや保護に使われます。' },
  { term: 'Azure Front Door', aliases: ['azure front door'], description: 'グローバル配信や入口制御に使うAzureサービスです。複数リージョン配信や高速化で使われます。' },
  { term: 'Azure DNS', aliases: ['azure dns'], description: 'AzureのDNS管理サービスです。名前解決をクラウド側で管理できます。' },
  { term: 'Microsoft Entra ID', aliases: ['microsoft entra id'], description: 'MicrosoftのID管理サービス名称です。旧Azure Active Directoryの系譜にある認証基盤です。' },
  { term: 'Entra ID', aliases: ['entra id'], description: 'Microsoft Entra IDの略称的な呼び方です。SSOや認証連携で重要です。' },
  { term: 'Azure Subscription', aliases: ['azure subscription'], description: 'Azure利用の契約、課金、管理単位です。リソースや権限のまとまりとして使われます。' },
  { term: 'Azure Policy', aliases: ['azure policy'], description: 'リソース作成や設定にルールを適用する仕組みです。統制や標準化に有効です。' },
  { term: 'Azure RBAC', aliases: ['azure rbac'], description: 'Azureのロールベース権限制御です。誰に何を許可するかをロール単位で管理します。' },
  { term: 'Azure Managed Identity', aliases: ['azure managed identity'], description: 'Azureが認証情報管理を肩代わりする仕組みです。秘密情報をコードへ埋め込まない設計に役立ちます。' },
  { term: 'Azure Key Vault', aliases: ['azure key vault'], description: '秘密情報や鍵、証明書を保管するAzureサービスです。セキュアな構成の要になります。' },
  { term: 'Azure App Service', aliases: ['azure app service'], description: 'WebアプリやAPIをホストできるAzureのマネージドサービスです。インフラ管理負担を減らしやすいです。' },
  { term: 'Web App for Azure App Service', aliases: ['web app for azure app service'], description: 'App Service上でWebアプリを動かす形態です。業務Webシステムでもよく使われます。' },
  { term: 'Azure Functions', aliases: ['azure functions'], description: 'イベント駆動でコードを実行するAzureのサーバーレスサービスです。小さな処理単位の自動化に向いています。' },
  { term: 'Function App', aliases: ['function app'], description: 'Azure Functionsをまとめて管理する単位です。関数群の配置や設定に使われます。' },
  { term: 'Azure Container Apps', aliases: ['azure container apps'], description: 'コンテナアプリを実行するAzureのマネージド基盤です。Kubernetesを直接運用せずにコンテナを扱いやすくします。' },
  { term: 'Azure Kubernetes Service', aliases: ['azure kubernetes service'], description: 'AzureのマネージドKubernetesサービスです。略してAKSと呼ばれます。' },
  { term: 'AKS', aliases: ['aks'], description: 'Azure Kubernetes Serviceの略称です。コンテナ基盤としてよく使われます。' },
  { term: 'Azure SQL Database', aliases: ['azure sql database'], description: 'AzureのマネージドSQLデータベースサービスです。SQL Server系の業務資産と相性があります。' },
  { term: 'Azure Cosmos DB', aliases: ['azure cosmos db'], description: 'グローバル分散を特徴とするAzureのデータベースサービスです。高可用性や多モデル対応が特徴です。' },
  { term: 'Azure Storage Account', aliases: ['azure storage account'], description: 'Azureの各種ストレージサービスをまとめる管理単位です。Blob、Queue、Tableなどを扱います。' },
  { term: 'Azure Blob Storage', aliases: ['azure blob storage'], description: 'Azureのオブジェクトストレージサービスです。大容量ファイル保存に向いています。' },
  { term: 'Azure Files', aliases: ['azure files'], description: 'Azureのファイル共有サービスです。既存ファイル共有のクラウド移行先として使われることがあります。' },
  { term: 'Azure Queue Storage', aliases: ['azure queue storage'], description: 'キュー型メッセージを扱うAzureストレージサービスです。非同期処理の簡易実装に使えます。' },
  { term: 'Azure Service Bus', aliases: ['azure service bus'], description: 'Azureの高機能メッセージングサービスです。キューやトピック連携に使われます。' },
  { term: 'Azure Event Grid', aliases: ['azure event grid'], description: 'イベント配信を扱うAzureサービスです。イベント駆動アーキテクチャに向いています。' },
  { term: 'Azure Event Hubs', aliases: ['azure event hubs'], description: '大量イベントやストリームデータを取り込むAzureサービスです。ログ収集やIoT系と相性があります。' },
  { term: 'Azure Monitor', aliases: ['azure monitor'], description: 'Azureの監視基盤です。メトリクス、ログ、アラートを扱えます。' },
  { term: 'Log Analytics', aliases: ['log analytics'], description: 'Azure Monitorと組み合わせてログ分析を行う機能です。クエリベースで運用データを調べやすいです。' },
  { term: 'Application Insights', aliases: ['application insights'], description: 'アプリケーション監視に特化したAzureの機能です。依存関係や例外、応答時間の可視化に使えます。' },
  { term: 'Azure DevOps', aliases: ['azure devops'], description: '開発管理、CI/CD、ボード、リポジトリなどを提供するMicrosoftのサービス群です。開発運用基盤として使われます。' },
  { term: 'Azure Pipelines', aliases: ['azure pipelines'], description: 'Azure DevOpsのCI/CD機能です。ビルド、テスト、デプロイを自動化できます。' },
  { term: 'Azure Repos', aliases: ['azure repos'], description: 'Azure DevOpsのGitリポジトリ機能です。コード管理とレビュー基盤として使われます。' },
  { term: 'Azureリソースグループ', aliases: ['azureリソースグループ', 'azure resource group'], description: 'Azureリソースをまとめて管理する単位です。削除・権限管理・整理の基盤になります。' },
  { term: 'Azure App Service Webアプリ', aliases: ['azure app service webアプリ', 'azure app service web app'], description: 'App Service上でウェブアプリケーションを実行する形態です。業務向けウェブシステムにもよく利用されます。' },
  { term: 'Microsoft Fabric', aliases: ['microsoft fabric'], description: 'データ統合、分析、可視化を一体的に扱うMicrosoftの統合分析基盤。' },
  { term: 'OneLake', aliases: ['onelake'], description: 'Fabricで利用する統合データ保存基盤であり、データを横断的に扱う中心領域。' },
  { term: 'Power BI', aliases: ['power bi'], description: 'データを集計・可視化し、ダッシュボードやレポートとして共有できるBIサービス。' },
  { term: 'Azure Synapse Analytics', aliases: ['azure synapse analytics'], description: 'データ統合と分析を組み合わせて実現する分析基盤サービス。' },
  { term: 'Azure Data Factory', aliases: ['azure data factory'], description: '複数システム間のデータ連携やETL処理を構築・実行するサービス。' },
  { term: 'ExpressRoute', aliases: ['expressroute'], description: 'オンプレミスとAzureを専用線で接続するサービス。' },
  { term: 'Azure Automation', aliases: ['azure automation'], description: '定型運用作業を自動化するためのサービス。' },
  { term: 'Azure OpenAI', aliases: ['azure openai'], description: 'Azure上でOpenAI系モデルを利用するためのサービス。' },
  { term: 'Azure AI Speech', aliases: ['azure ai speech'], description: '音声認識や音声合成を利用できる音声AIサービス。' },
  { term: 'AVD', aliases: ['avd', 'azure virtual desktop'], description: 'Azure Virtual Desktopの略で、仮想デスクトップ環境。' },
  { term: 'HDInsight', aliases: ['hdinsight'], description: 'Azure上でHadoopやSparkなどを扱う分析基盤サービス。' },
  { term: 'Azure Active Directory', aliases: ['azure active directory', 'azure ad', 'aad'], description: 'Microsoftが提供するクラウドベースのIDおよびアクセス管理サービス。シングルサインオン（SSO）、多要素認証（MFA）、条件付きアクセスなどの機能でユーザー認証と認可を管理する。現在はMicrosoft Entra IDに改称されている。' },
  { term: 'Azure AD B2C', aliases: ['azure ad b2c', 'azure active directory b2c', 'aad b2c'], description: '外部向けアプリケーション向けのB2C（Business to Consumer）IDプロバイダーサービス。ソーシャルログイン（Google、Facebook等）や独自のカスタムユーザーフローをサポートし、数百万ユーザーのID管理に対応する。' },
  { term: 'Azure Logic Apps', aliases: ['azure logic apps', 'logic apps'], description: 'ローコードでビジネスプロセスやワークフローを自動化するサービス。200以上のコネクタを介してSaaS・オンプレミスシステムを連携し、定期実行やイベントトリガーで処理フローを構成できる。' },
  { term: 'Azure API Management', aliases: ['azure api management', 'apim', 'azure apim'], description: '複数のAPIをまとめて管理・公開するためのフルマネージドAPIゲートウェイサービス。レート制限、認証、変換、モニタリング、開発者ポータルを一元提供し、APIエコノミー構築を支援する。' },
  { term: 'Azure Table Storage', aliases: ['azure table storage', 'table storage'], description: 'Azureが提供するNoSQL型のキー・バリューストアサービス。スキーマレスで大量の構造化データを低コストで保存でき、パーティションキーと行キーによる高速なデータ参照が可能。' },
  { term: 'Azure Database for PostgreSQL', aliases: ['azure database for postgresql', 'azure postgresql'], description: 'PostgreSQLのフルマネージドサービス。高可用性、自動バックアップ、スケーリング、セキュリティパッチ適用をMicrosoftが管理する。柔軟なサーバーオプションとCitus拡張によるハイパースケール構成もサポート。' },
  { term: 'Azure Database for MySQL', aliases: ['azure database for mysql', 'azure mysql'], description: 'MySQLのフルマネージドサービス。自動バックアップ、自動パッチ適用、高可用性構成をMicrosoftが管理し、開発者がデータベース運用ではなくアプリ開発に集中できる環境を提供する。' },
  { term: 'Azure Cache for Redis', aliases: ['azure cache for redis', 'azure redis cache'], description: 'Redisをベースにしたフルマネージドのインメモリキャッシュサービス。セッション管理、データキャッシュ、メッセージブローカーとして活用でき、アプリケーションの応答速度とスループットを向上させる。' },
  { term: 'Azure Cognitive Services', aliases: ['azure cognitive services', 'cognitive services', 'azure ai services'], description: 'AIと機械学習の機能をAPIとして提供するサービス群。視覚、音声、言語、意思決定などのカテゴリがあり、専門的なMLスキルなしにAI機能をアプリに組み込める。現在はAzure AI Servicesに改称。' },
  { term: 'Azure OpenAI Service', aliases: ['azure openai service', 'aoai'], description: 'OpenAIのGPT-4、DALL-E、Whisperなどのモデルをエンタープライズレベルのセキュリティとコンプライアンスで利用できるAzureサービス。プライベートネットワーク接続や独自データとの連携も可能。' },
  { term: 'Azure Machine Learning', aliases: ['azure machine learning', 'azure ml', 'aml'], description: 'MLモデルの構築、トレーニング、デプロイ、管理を行うためのクラウドプラットフォーム。AutoML、デザイナー（GUI）、Pythonエンドツーエンドのワークフローをサポートし、MLOpsを実現する。' },
  { term: 'Azure Databricks', aliases: ['azure databricks', 'databricks on azure'], description: 'Apacheスパークベースの統合データ分析プラットフォーム。データエンジニアリング、機械学習、データウェアハウスを協調作業環境（ノートブック）で実行でき、Azure Data Factoryやシナプスとも統合される。' },
  { term: 'Azure Stream Analytics', aliases: ['azure stream analytics', 'stream analytics'], description: 'IoTデバイスやアプリケーションからのリアルタイムストリームデータをSQL系クエリで分析するフルマネージドサービス。Event HubsやIoT Hubと連携し、ミリ秒単位の遅延で分析結果を出力する。' },
  { term: 'Azure HDInsight', aliases: ['azure hdinsight'], description: 'Hadoop、Spark、Hive、HBase、Kafkaなどのオープンソースビッグデータフレームワークをフルマネージドで提供するサービス。大規模なバッチ処理や対話型クエリをクラスター単位で実行する。' },
  { term: 'Azure Purview', aliases: ['azure purview', 'microsoft purview', 'azure data catalog'], description: '組織全体のデータ資産を検出、分類、管理するデータガバナンスサービス。データカタログ、データリネージ、秘密度ラベルを統合し、コンプライアンスとデータ品質を維持する。現在はMicrosoft Purviewに統合。' },
  { term: 'Azure Virtual Machines', aliases: ['azure virtual machines', 'azure vm', 'iaas vm'], description: 'AzureのIaaSコンピューティングサービス。Windows・Linuxのさまざまなサイズ（SKU）のVMを数分でプロビジョニングでき、フルコントロールのOSレベルアクセスと豊富なインスタンスタイプを提供する。' },
  { term: 'Azure CDN', aliases: ['azure cdn', 'azure content delivery network'], description: '世界中のPoP（Point of Presence）に静的コンテンツをキャッシュし、ユーザーに最も近いエッジサーバーから配信するコンテンツデリバリーネットワーク。レイテンシ削減とオリジンサーバーの負荷軽減に使われる。' },
  { term: 'Azure Traffic Manager', aliases: ['azure traffic manager', 'traffic manager'], description: 'DNSベースのグローバルロードバランサー。パフォーマンス、地理的、重み付け、優先度などのルーティング方法でトラフィックを複数リージョンのエンドポイントに分散し、可用性を高める。' },
  { term: 'Azure ExpressRoute', aliases: ['azure expressroute'], description: 'オンプレミスとAzureをインターネットを経由せずに専用線で接続するサービス。高帯域・低レイテンシで安定した接続を実現し、セキュリティやコンプライアンス要件が厳しいエンタープライズ向けに利用される。' },
  { term: 'Azure VPN Gateway', aliases: ['azure vpn gateway', 'vpn gateway'], description: 'AzureとオンプレミスネットワークをIPsec/IKEで暗号化したVPNトンネルで接続するゲートウェイサービス。サイト間VPN、ポイント対サイトVPN、VNet間接続の3種類の接続形態をサポートする。' },
  { term: 'Azure Bastion', aliases: ['azure bastion'], description: 'Azureポータルからブラウザ経由で仮想マシンにRDP/SSHアクセスを提供するフルマネージドサービス。パブリックIPアドレスをVMに付与せずに安全な管理アクセスを実現し、踏み台サーバーが不要になる。' },
  { term: 'Azure Firewall', aliases: ['azure firewall', 'azure firewall premium'], description: 'VNetを保護するクラウドネイティブなフルマネージドファイアウォールサービス。ステートフルパケット検査、FQDN フィルタリング、脅威インテリジェンス連携、TLS検査（Premiumエディション）を提供する。' },
  { term: 'Azure DDoS Protection', aliases: ['azure ddos protection', 'ddos protection'], description: 'AzureリソースをDDoS攻撃から保護するサービス。BasicとStandardの2プランがあり、StandardプランはML機械学習ベースの攻撃検知、適応型チューニング、攻撃レポートなどの高度な保護を提供する。' },
  { term: 'Azure Network Security Group', aliases: ['azure network security group', 'ネットワークセキュリティグループ'], description: '仮想マシンやサブネットへの受信・送信ネットワークトラフィックをフィルタリングするアクセス制御リスト。ポート、プロトコル、送受信元IPなどを基にルールを定義しトラフィックを許可または拒否する。' },
  { term: 'Azure Private Endpoint', aliases: ['azure private endpoint', 'private endpoint'], description: '【Azure】AzureサービスへのアクセスをVNet内のプライベートIPアドレス経由で実現するネットワークインターフェース。インターネットを経由せずにストレージ、SQLなどのPaaSサービスにセキュアにアクセスできる。 【OCI APEX】公開せず私設ネットワーク経由で到達させる接続点。' },
  { term: 'Azure Private Link', aliases: ['azure private link', 'private link'], description: 'Azure PaaSサービスや独自サービスをVNetに閉じたプライベートエンドポイント経由でアクセスできるようにするサービス。データがMicrosoftのバックボーンネットワーク上を流れ、インターネット露出を排除する。' },
  { term: 'Azure Service Endpoint', aliases: ['azure service endpoint', 'vnet service endpoint', 'サービスエンドポイント'], description: 'VNetからAzure PaaSサービス（ストレージ、SQLなど）へのルートをMicrosoftバックボーン経由に最適化する機能。トラフィックがパブリックインターネットに出ずに済むが、Private Endpointと異なりサービス側でVNet外からのアクセスを遮断できる。' },
  { term: 'Azure Availability Zones', aliases: ['azure availability zones', 'az'], description: '同一Azureリージョン内の物理的に独立したデータセンターの集合体。電力・冷却・ネットワークが独立しており、ゾーン冗長化によってデータセンター障害に対する高可用性（SLA 99.99%）を実現する。' },
  { term: 'Azure Regions', aliases: ['azure regions', 'azureリージョン'], description: 'Azureのデータセンターが集中する世界各地の地理的エリア。60以上のリージョンが存在し、データ主権や法規制要件に合わせてリソースの配置先を選択する。各リージョンはリージョンペアで構成される。' },
  { term: 'Azure Management Group', aliases: ['azure management group', '管理グループ'], description: '複数のサブスクリプションを階層的にまとめるコンテナ。ポリシーとRBAC（役割ベースのアクセス制御）を管理グループレベルで適用することで、大規模組織でのガバナンスを一元管理できる。' },
  { term: 'Azure Blueprints', aliases: ['azure blueprints', 'blueprints'], description: 'リソースグループ、ポリシー割り当て、RBACロール割り当て、ARMテンプレートなどを組み合わせた環境定義をまとめて管理・展開するサービス。標準的なガバナンス構成を繰り返し適用する際に活用する。' },
  { term: 'Azure Resource Manager', aliases: ['azure resource manager', 'arm', 'azure resource managerレイヤー'], description: 'AzureリソースのデプロイとライフサイクルをAPIレベルで管理するコントロールプレーン。すべてのAzureリソース操作はARMを経由し、一貫した認証・認可・タグ付け・ロック機能を提供する。' },
  { term: 'ARMテンプレート', aliases: ['armテンプレート', 'arm template', 'azure resource manager template'], description: 'Azureリソースの構成をJSONフォーマットで宣言的に記述するInfrastructure as Codeファイル。べき等なデプロイが可能で、インクリメンタル・完全の2モードでリソースを管理する。現在はBicepへの移行も進む。' },
  { term: 'Bicep', aliases: ['bicep', 'azure bicep'], description: 'ARMテンプレートを簡潔に記述するためのAzure専用のドメイン固有言語（DSL）。JSONよりも読みやすいシンタックスで同等のAzureリソース定義を記述でき、コンパイル時にARMテンプレートに変換される。' },
  { term: 'Azure CLI', aliases: ['azure cli', 'az cli'], description: 'Azureリソースを管理するためのクロスプラットフォームのコマンドラインツール。Windows、Mac、Linux上で動作し、スクリプトやCI/CDパイプラインからAzureリソースの作成・変更・削除を自動化できる。' },
  { term: 'Azure PowerShell', aliases: ['azure powershell', 'az powershell'], description: 'PowerShellからAzureリソースを管理するためのモジュール群。`Az`モジュールとして提供され、PowerShellスクリプトやパイプラインでAzure操作を自動化する際に利用する。Windows管理者に親しみやすいインターフェース。' },
  { term: 'Azure Portal', aliases: ['azure portal', 'azureポータル', 'portal.azure.com'], description: 'Webブラウザ経由でAzureリソースを管理できるGUIベースの管理コンソール。リソースの作成・設定・監視・請求確認をビジュアルに操作でき、ダッシュボードのカスタマイズも可能。' },
  { term: 'Azure Cloud Shell', aliases: ['azure cloud shell'], description: 'Azureポータルやブラウザからすぐにアクセスできるクラウドホスティングのインタラクティブシェル。BashとPowerShellをサポートし、Azure CLI・Azure PowerShell・Terraformなどのツールが事前インストール済み。' },
  { term: 'Azure Active Directory Domain Services', aliases: ['azure active directory domain services', 'azure ad ds', 'aad ds'], description: 'Azure ADをベースにしたマネージドのActive Directoryドメインサービス。ドメイン参加、グループポリシー、LDAP、Kerberosなど従来のADと互換性のある機能をクラウドで提供し、オンプレミスADなしに利用できる。' },
  { term: 'Azure AD Connect', aliases: ['azure ad connect', 'aad connect', 'azure active directory connect'], description: 'オンプレミスのActive DirectoryとAzure ADの間でユーザー・グループ・パスワードを同期するツール。ハイブリッドID構成を実現し、オンプレミスとクラウドで統一したSSOを可能にする。' },
  { term: 'Azure Log Analytics', aliases: ['azure log analytics', 'log analytics workspace'], description: 'Azureリソースや他のソースから収集したログとパフォーマンスデータをクエリ・分析するサービス。Kusto Query Language（KQL）で高度なデータ分析が可能で、Azure Monitorの中核コンポーネント。' },
  { term: 'Azure Application Insights', aliases: ['azure application insights', 'app insights'], description: 'Webアプリケーションのパフォーマンスと障害をリアルタイムに監視するAPMサービス。リクエスト、依存関係、例外、パフォーマンスカウンターを自動収集し、Azure Monitorのコンポーネントとして機能する。' },
  { term: 'Azure Security Center', aliases: ['azure security center', 'microsoft defender for cloud'], description: 'Azureとハイブリッドクラウドのセキュリティポスチャーをリアルタイム評価する統合セキュリティ管理サービス。現在はMicrosoft Defender for Cloudに改称され、セキュリティスコアや推奨対策を提示する。' },
  { term: 'Azure Sentinel', aliases: ['azure sentinel', 'microsoft sentinel'], description: 'クラウドネイティブのSIEM（セキュリティ情報およびイベント管理）とSOARプラットフォーム。ログを大規模収集してAIによる脅威検知・調査・対応の自動化を行う。現在はMicrosoft Sentinelに改称。' },
  { term: 'Azure Defender', aliases: ['azure defender', 'azure defender for servers'], description: '仮想マシン、コンテナ、データベースなどAzureリソースを対象とした高度な脅威保護サービス。ランタイムの脅威検知、脆弱性評価、適応型アプリケーション制御などをリソース種別ごとに提供する。' },
  { term: 'Azure Container Registry', aliases: ['azure container registry', 'acr'], description: 'DockerコンテナイメージやHelmチャートをプライベートに保存・管理するフルマネージドのOCIコンテナレジストリ。Azure Kubernetes ServiceやAzure Container Appsとネイティブに統合され、地理的レプリケーションにも対応する。' },
  { term: 'Azure Container Instances', aliases: ['azure container instances', 'aci'], description: '仮想マシンやオーケストレーションシステムなしにコンテナを直接実行できるサーバーレスコンテナサービス。秒単位の課金と高速起動が特徴で、バッチ処理や短命なコンテナワークロードに最適。' },
  { term: 'Azure Static Web Apps', aliases: ['azure static web apps', 'static web apps', 'swa'], description: '静的フロントエンド（HTML/CSS/JS）とサーバーレスAPIバックエンド（Azure Functions）を統合してホスティングするサービス。GitHubやAzure DevOpsとCI/CD連携し、グローバルCDN配信と無料SSLを自動設定する。' },
  { term: 'Azure Spring Apps', aliases: ['azure spring apps', 'azure spring cloud', 'spring apps'], description: 'Spring Bootアプリケーションをフルマネージドで実行するPaaSサービス。サービスディスカバリー、設定管理、スケーリング、Blue/Greenデプロイをサービスとして提供し、Javaエンタープライズアプリの移行を容易にする。' },
  { term: 'Azure SignalR Service', aliases: ['azure signalr service', 'signalr service'], description: 'リアルタイム双方向通信機能をアプリに追加するフルマネージドサービス。WebSocket、Server-Sent Events、Long Pollingを自動管理し、チャット、ライブダッシュボード、ゲームなどの用途で使われる。' },
  { term: 'Azure Notification Hubs', aliases: ['azure notification hubs', 'notification hubs'], description: 'iOS（APNs）、Android（FCM）、Windows（WNS）などのプッシュ通知プラットフォームを統一APIで扱えるスケーラブルなプッシュ通知サービス。タグやテンプレートで対象者を絞り込んで大規模配信が可能。' },
  { term: 'Azure Relay', aliases: ['azure relay', 'relay', 'azure service bus relay'], description: 'ファイアウォールやNATの内側にあるオンプレミスサービスをクラウドから安全に呼び出すためのハイブリッド接続サービス。クライアントが発信した接続をRelayサーバーが橋渡しし、インバウンドのファイアウォール設定変更が不要。' },
  { term: 'Azure Batch', aliases: ['azure batch', 'batch'], description: '大規模な並列バッチコンピューティングジョブを管理するサービス。VMのプール管理、ジョブスケジューリング、タスク依存関係の解決を自動化し、レンダリング、シミュレーション、トランスコードなどの計算集約型処理に最適。' },
  { term: 'Azure Artifacts', aliases: ['azure artifacts', 'artifacts', 'azure devops artifacts'], description: 'npm、NuGet、Maven、Python、Universalパッケージなどを管理するプライベートパッケージレジストリ。Azure DevOpsの一機能として提供され、CI/CDパイプライン内でのパッケージ共有と依存関係管理を支援する。' },
  { term: 'Azure Test Plans', aliases: ['azure test plans', 'test plans'], description: 'Azure DevOpsの手動テスト・探索的テスト管理ツール。テストケースの作成、実行、追跡を管理し、バグを直接作業項目として記録しながらテスト結果とカバレッジレポートを提供する。' },
  { term: 'Azure Boards', aliases: ['azure boards', 'boards', 'azure devops boards'], description: 'スクラム・カンバン・スクラムボードをサポートするアジャイルプロジェクト管理ツール。作業項目（エピック、フィーチャー、ユーザーストーリー、タスク）をバックログやボードで管理し、Azure Pipelinesと統合する。' },
  { term: 'Azure Cognitive Search', aliases: ['azure cognitive search', 'azure ai search', 'cognitive search'], description: 'エンタープライズ向けのフルテキスト検索・AIエンリッチメントサービス。複数データソースからのインデックス構築、セマンティック検索、ベクター検索に対応し、RAGアーキテクチャのナレッジリトリーバルにも活用される。' },
  { term: 'Azure Form Recognizer', aliases: ['azure form recognizer', 'azure ai document intelligence', 'form recognizer'], description: '領収書、請求書、名刺、フォームなどのドキュメントからテキストやキーバリューペアを自動抽出するAIサービス。OCR機能とカスタムモデルのトレーニングにより様々なドキュメント形式に対応する。' },
  { term: 'Azure Text Analytics', aliases: ['azure text analytics', 'azure ai language', 'text analytics'], description: '自然言語処理（NLP）APIを提供するサービス。感情分析、キーフレーズ抽出、エンティティ認識、言語検出、テキスト要約などの機能を備え、テキストデータからインサイトを自動的に得られる。' },
  { term: 'Azure Computer Vision', aliases: ['azure computer vision', 'computer vision', 'azure ai vision'], description: '画像や動画を解析するAPIを提供するコンピュータービジョンサービス。物体検出、画像分類、OCR、顔検出、シーン記述などの機能を提供し、カスタムビジョンモデルのトレーニングも可能。' },
  { term: 'Azure Face API', aliases: ['azure face api', 'face api', 'azure ai face'], description: '顔検出、属性分析（年齢・表情・感情）、顔照合、顔識別の機能を提供するAIサービス。セキュリティゲートやアクセス制御、本人確認ユースケースで利用されるが、プライバシーへの配慮が求められる。' },
  { term: 'Azure Translator', aliases: ['azure translator', 'azure ai translator', 'cognitive services translator'], description: 'リアルタイムのテキスト・ドキュメント翻訳を提供するニューラル機械翻訳サービス。100言語以上に対応し、カスタム用語集による翻訳精度カスタマイズや、カスタムトレーニングモデルの構築も可能。' },
  { term: 'Azure Speech Services', aliases: ['azure speech services', 'speech services'], description: '音声認識（STT）、音声合成（TTS）、音声翻訳、話者認識の機能を提供するAIサービス。ニューラルTTSによる自然な音声合成とリアルタイム会話文字起こしをAPIで利用できる。' },
  { term: 'Azure Bot Service', aliases: ['azure bot service', 'bot service', 'azure bot framework'], description: 'チャットボットやコンバーサルAIを構築・管理・接続するためのサービス。Bot Framework SDKと統合し、Teams、Slack、WebチャットなどのチャンネルへのボットデプロイとAzure OpenAI連携が可能。' },
  { term: 'Azure Maps', aliases: ['azure maps', 'azure location services'], description: '地図表示、ルート案内、ジオコーディング、交通情報、空間分析などの位置情報サービスを提供するAPI群。Webおよびモバイルアプリに地図・位置情報機能を組み込めるエンタープライズグレードのサービス。' },
  { term: 'Azure Time Series Insights', aliases: ['azure time series insights', 'time series insights', 'tsi'], description: 'IoTデバイスからの大規模時系列データの収集・保存・クエリ・可視化を行うサービス。センサーデータや産業機器のテレメトリを長期保存し、パターン分析や異常検知に活用する。' },
  { term: 'Azure Digital Twins', aliases: ['azure digital twins', 'digital twins'], description: '現実世界のデバイス・場所・ビジネスプロセスのデジタルツインモデルをクラウド上に構築するサービス。DTDL（Digital Twins Definition Language）でモデルを定義し、IoT HubやTime Series Insightsと連携する。' },
  { term: 'Azure IoT Central', aliases: ['azure iot central', 'iot central'], description: 'IoTデバイスの接続・監視・管理をノーコード/ローコードで実現するSaaSプラットフォーム。デバイステンプレートによる迅速なデバイスオンボーディングとダッシュボード・アラート設定ができ、IoT Hub上に構築されている。' },
  { term: 'Azure Dedicated Host', aliases: ['azure dedicated host', 'dedicated host'], description: '単一テナント専用の物理ホストサーバーをAzureで提供するサービス。ホスト上のVMはそのサーバーのみが使用し、コンプライアンス要件やライセンス（Windows Server BYOL）の理由でサーバーの占有が必要な場合に利用される。' },
  { term: 'Azure Spot VMs', aliases: ['azure spot vms', 'azure spot virtual machines', 'スポットvm'], description: 'Azureの未使用容量を割引価格（最大90%オフ）で利用できる仮想マシン。容量が必要になればAzureからの強制退去があるため、中断耐性のあるバッチ処理や開発・テスト環境に最適。' },
  { term: 'Azure Reserved Instances', aliases: ['azure reserved instances', 'reserved instances', '予約インスタンス', 'azure reservations'], description: '1年または3年のAzureリソース利用をあらかじめ予約し、従量課金より大幅に割引（最大72%）で利用できるコスト最適化オプション。VMだけでなくSQL Database、Cosmos DBなどにも適用可能。' },
  { term: 'Azure Scale Sets', aliases: ['azure scale sets', 'virtual machine scale sets', 'vmss'], description: '同一構成の仮想マシンを自動でスケールアウト・スケールインできるVMグループ。ロードバランサーと組み合わせてトラフィックに応じたVM数の自動調整を行い、大規模ステートレスアプリのホスティングに使われる。' },
  { term: 'Azure Proximity Placement Groups', aliases: ['azure proximity placement groups', 'proximity placement groups', 'ppg', '近接配置グループ'], description: '複数のAzure VMやVMSSを物理的に近いデータセンターに配置するための制約グループ。VM間のネットワークレイテンシを最小化し、高性能コンピューティングやタイトに連携するアプリ層の低遅延通信を実現する。' },
  { term: 'Azure Arc', aliases: ['azure arc', 'arc'], description: 'オンプレミス、マルチクラウド、エッジ環境のサーバー・Kubernetes・データサービスをAzureのコントロールプレーンで一元管理する拡張サービス。Azure Policy、RBAC、Monitor、Security Centerをハイブリッド環境に適用できる。' },
  { term: 'Azure Stack Hub', aliases: ['azure stack hub', 'stack hub', 'azure stack'], description: 'オンプレミスのデータセンターにAzureサービスを展開できるハイブリッドクラウドプラットフォーム。インターネット接続が制限される環境や規制産業向けに、Azureと一貫したAPIとツールで運用できる。' },
  { term: 'Azure Stack Edge', aliases: ['azure stack edge', 'stack edge', 'azure data box edge'], description: 'エッジコンピューティングとAIアクセラレーション機能を持つハードウェアアプライアンス。現地でデータを処理してからAzureに転送するため、帯域幅が限られる工場・小売・遠隔地でのIoTと機械学習に活用される。' },
  { term: 'Azure Migrate', aliases: ['azure migrate', 'azure migration'], description: 'オンプレミスのVM・データベース・Webアプリを評価・移行するための中央ハブ。移行前の依存関係マッピング、コスト見積り、適切なAzure SKUの推奨、そして移行ツール（レプリケーション）を統合的に提供する。' },
  { term: 'Azure Site Recovery', aliases: ['azure site recovery', 'asr', 'site recovery'], description: 'オンプレミスVM、AzureVMのディザスタリカバリー（DR）と移行を管理するサービス。継続的なレプリケーション、定期テストフェイルオーバー、RPO/RTOのモニタリングでビジネス継続性計画をサポートする。' },
  { term: 'Azure Backup', aliases: ['azure backup', 'azure backup service'], description: 'VM、SQLデータベース、ファイル、SAP HANAなど多様なワークロードをクラウドにバックアップするフルマネージドサービス。増分バックアップ、ソフト削除、長期保存ポリシーをシンプルなUIで設定できる。' },
  { term: 'Azure File Sync', aliases: ['azure file sync', 'file sync'], description: 'オンプレミスのWindowsファイルサーバーとAzure Filesを同期し、クラウドをファイルの一元バックアップとして機能させるサービス。クラウド階層化によりアクセス頻度の低いファイルをクラウドに移動してローカルストレージを節約する。' },
  { term: 'Azure Import/Export', aliases: ['azure import/export', 'azure import export'], description: '大量データをインターネット経由でなく、HDDやSSDをMicrosoftデータセンターに物理的に送付することでAzure Storageにインポート・エクスポートするサービス。数十TBのデータを効率よく転送する際に使用する。' },
  { term: 'Azure Data Box', aliases: ['azure data box', 'data box'], description: '大規模データをAzureに移行するためのオフライン転送デバイス。Data Box（100TB）、Data Box Disk（8TB×5）、Data Box Heavy（1PB）のラインナップがあり、インターネット帯域が不十分な場合のデータ移行に使われる。' },
  { term: 'Azure NetApp Files', aliases: ['azure netapp files', 'netapp files', 'anf'], description: 'Netapp ONTAPをベースにしたエンタープライズグレードのNASファイルストレージサービス。高いIOPS・低レイテンシが求められるSAP HANA、Oracle、高性能コンピューティングなどのワークロードに対応する。' },
  { term: 'Azure Managed Disks', aliases: ['azure managed disks', 'managed disks', 'マネージドディスク'], description: 'Azureが冗長性とスナップショットを管理するVMアタッチ型のブロックストレージ。Ultra Disk、Premium SSD v2、Premium SSD、Standard SSD、Standard HDDの5ラインがあり、ワークロードに合わせて選択する。' },
  { term: 'Azure Shared Disk', aliases: ['azure shared disk', 'shared disk'], description: '複数のVMから同時に共有マウントできるAzure Managed Diskの機能。Windows Server Failover ClusteringやLinux Pacemakerを使ったクラスター化アプリケーションの共有ストレージとして利用される。' },
  { term: 'Azure Ultra Disk', aliases: ['azure ultra disk', 'ultra disk', 'ultra ssd'], description: 'サブミリ秒レイテンシと最大160,000 IOPSを提供するAzureの最高性能ブロックストレージ。SAP HANA、Oracle、SQL Server Tier-1などのI/O集約型ワークロード専用で、実行中のVMからもディスク性能を変更できる。' },
  { term: 'Azure Object Replication', aliases: ['azure object replication', 'オブジェクトレプリケーション', 'blob object replication'], description: 'Azure Blob Storageのコンテナ間でオブジェクトを非同期的にレプリケートする機能。リージョン間のデータ冗長化、読み取りレイテンシ低減、コンプライアンス要件への対応などの目的で使用する。' },
  { term: 'Azure Geo-Redundant Storage', aliases: ['azure geo-redundant storage', 'grs', 'geo-redundant storage', '地理冗長ストレージ'], description: 'プライマリリージョンに3コピー、500マイル以上離れたセカンダリリージョンに3コピーの計6コピーでデータを保存するストレージ冗長性オプション。リージョン障害時もデータを保護し、読み取り専用フェイルオーバーも可能（RA-GRS）。' },
  { term: 'Azure Zone-Redundant Storage', aliases: ['azure zone-redundant storage', 'zrs', 'zone-redundant storage', 'ゾーン冗長ストレージ'], description: '同一リージョン内の複数の可用性ゾーンにデータを分散して3コピーを保存するストレージ冗長性オプション。単一ゾーン障害に対する高い耐久性を提供し、重要なデータのゾーン障害耐性を実現する。' },
  { term: 'Azure Lifecycle Management', aliases: ['azure lifecycle management', 'blob lifecycle management', 'ストレージライフサイクル管理'], description: 'Blob Storageオブジェクトのアクセス頻度に応じてストレージ層（Hot/Cool/Cold/Archive）を自動的に移行するポリシーを設定する機能。コストを最適化しながらデータ保持要件を自動管理する。' },
  { term: 'Azure Cost Management', aliases: ['azure cost management', 'azure cost management and billing', 'コスト管理'], description: 'Azureリソースのコストを可視化・分析・最適化するサービス。コスト分析ダッシュボード、予算アラート、予約とスポットの推奨、コスト配賦タグの活用などでクラウド支出を制御する。' },
  { term: 'Azure Advisor', aliases: ['azure advisor', 'advisor'], description: '【Azure】AzureリソースのコスティングとベストプラクティスをAIが分析し、コスト削減・セキュリティ向上・高可用性・パフォーマンス改善・オペレーショナルエクセレンスの観点で推奨事項を提示するサービス。 【OCI APEX】アプリ定義の改善点を点検する支援機能。' },
  { term: 'Azure Service Health', aliases: ['azure service health', 'service health'], description: 'Azureサービスの稼働状況、メンテナンス情報、障害通知を個人化されたビューで確認できるサービス。影響を受けるリソースを特定し、アラートやアクショングループと連携して障害対応を迅速化する。' },
  { term: 'Azure Resource Health', aliases: ['azure resource health', 'resource health'], description: '個々のAzureリソースの正常性と過去の可用性履歴を確認できるサービス。プラットフォームイベントやユーザー起因の問題を区別し、リソース固有の診断と修復アクションを提案する。' },
  { term: 'Azure Metrics', aliases: ['azure metrics', 'azureメトリクス', 'azure monitor metrics'], description: 'AzureリソースのパフォーマンスデータをリアルタイムにMonitorに保存する時系列データ。CPUやメモリ使用率、リクエスト数、レイテンシなどをグラフ表示・アラート設定・自動スケールトリガーに利用できる。' },
  { term: 'Azure Alerts', aliases: ['azure alerts', 'azureアラート', 'monitor alerts'], description: 'メトリクス、ログ、Activity Logの条件を設定してしきい値違反時に通知やアクションを自動起動するサービス。メール・SMS・Webhook・Logic Appsなど多彩なアクショングループで自動対応フローを構築できる。' },
  { term: 'Azure Workbooks', aliases: ['azure workbooks', 'workbooks', 'azure monitor workbooks'], description: 'メトリクス、ログ、リソースデータを組み合わせたインタラクティブなレポートとダッシュボードを作成するAzure Monitor内の可視化ツール。テンプレートとパラメータ化により複数環境のデータを一画面で比較できる。' },
  { term: 'Azure AD条件付きアクセス', aliases: ['azure ad条件付きアクセス', 'azure ad conditional access', '条件付きアクセス'], description: 'ユーザーの場所・デバイス状態・リスクスコアなどのシグナルを組み合わせてアクセス可否とMFA要求を制御するMicrosoft Entra IDのポリシーエンジン。ゼロトラストセキュリティの中核機能。' },
  { term: 'Azure AD PIM', aliases: ['azure ad pim', 'privileged identity management', 'pim'], description: 'Microsoft Entra IDにおいて特権ロールを必要な時だけ一時的に付与するPAM（特権アクセス管理）サービス。常時管理者権限を排除し、承認ワークフローや監査ログで特権操作を制御する。' },
  { term: 'Azure Information Protection', aliases: ['azure information protection', 'aip', 'microsoft purview information protection'], description: 'ドキュメントやメールに機密ラベルを付与して暗号化・アクセス制御を行うMicrosoftの情報保護ソリューション。組織外への情報漏洩を防ぎコンプライアンスを強化する。' },
  { term: 'Azure Stack HCI', aliases: ['azure stack hci'], description: 'Azure管理機能と統合されたハイパーコンバージドインフラ（HCI）OSソリューション。オンプレミスでVMとコンテナを実行しつつAzure ArcでクラウドサービスをローカルHCIクラスターに展開できる。' },
  { term: 'Azure IoT Edge', aliases: ['azure iot edge', 'iot edge'], description: 'クラウドワークロード（AI推論・Azure Functions・Stream Analytics）をIoTデバイスに展開してエッジで実行するサービス。コンテナモジュールとして配布されオフライン動作にも対応する。' },
  { term: 'Azure Sphere', aliases: ['azure sphere'], description: 'マイクロコントローラー向けのエンドツーエンドセキュリティソリューション。専用OS、カスタムチップ（MT3620）、クラウドセキュリティサービスを組み合わせ接続デバイスをサイバー攻撃から保護する。' },
  { term: 'Azure Communication Services', aliases: ['azure communication services', 'acs'], description: '音声・ビデオ通話、チャット、SMS、電話番号をアプリに組み込むためのクラウドネイティブ通信プラットフォーム。Microsoft Teamsと相互運用可能でWebRTCベースのリアルタイム通信を実現する。' },
  { term: 'Azure Media Services', aliases: ['azure media services', 'ams'], description: '動画の取り込み・エンコード・パッケージング・配信を行うクラウドメディア処理プラットフォーム。ライブストリーミングとオンデマンド配信に対応しContent Delivery NetworkとDRM保護を統合する。' },
  { term: 'Azure Content Moderator', aliases: ['azure content moderator', 'content moderator', 'azure ai content safety'], description: 'テキスト・画像・動画から有害コンテンツ（暴力・ヘイト・成人向けなど）を自動検出・フィルタリングするAIサービス。ユーザー生成コンテンツのモデレーションを自動化しプラットフォームの安全性を維持する。' },
  { term: 'Azure Web PubSub', aliases: ['azure web pubsub', 'web pubsub'], description: 'WebSocketプロトコルをベースにメッセージをパブリッシュ・サブスクライブできるフルマネージドのリアルタイムメッセージングサービス。接続数百万規模のライブ更新・通知・コラボレーション機能を実現する。' },
  { term: 'Azure Durable Functions', aliases: ['azure durable functions', 'durable functions'], description: 'ステートフルなワークフローをサーバーレスコードで記述できるAzure Functionsの拡張機能。オーケストレーター関数・アクティビティ関数・エンティティ関数を組み合わせて長時間実行プロセスを実装する。' },
  { term: 'Durable Entities', aliases: ['durable entities', 'azure durable entities', 'エンティティ関数'], description: 'Azure Durable Functionsのエンティティ関数機能。小さなステート（カウンター・在庫など）をサーバーレス関数として永続化し、メッセージ経由でシリアルに操作するアクターモデルの実装を提供する。' },
  { term: 'Dapr', aliases: ['dapr', 'distributed application runtime'], description: 'マイクロサービスのための分散アプリケーションランタイム。サービス呼び出し、状態管理、パブサブ、バインディングなどの分散システム機能をサイドカーAPIで抽象化しクラウドポータビリティを高める。' },
  { term: 'Azure Red Hat OpenShift', aliases: ['azure red hat openshift', 'aro'], description: 'MicrosoftとRed Hatが共同サポートするAzure上のフルマネージドOpenShiftサービス。エンタープライズKubernetesプラットフォームの運用をクラウドにオフロードし高いセキュリティとコンプライアンスを維持する。' },
  { term: 'Azure HPC', aliases: ['azure hpc', 'azure high performance computing'], description: '流体力学・気候シミュレーション・分子動力学などの科学技術計算をAzure上で実行するためのInfiniBandネットワーク接続HシリーズVM群と関連サービスの総称。' },
  { term: 'Azure Confidential Computing', aliases: ['azure confidential computing', 'confidential computing'], description: 'CPU内のTEE（Trusted Execution Environment）を利用してクラウド上でも処理中のデータを暗号化・保護する技術。Intel SGXやAMD SEVを活用しクラウドプロバイダーからもデータを秘匿できる。' },
  { term: 'Azure Lighthouse', aliases: ['azure lighthouse'], description: 'マネージドサービスプロバイダー（MSP）が複数顧客のAzureテナントをスケーラブルに管理できるサービス。Azure委任リソース管理によって顧客テナントへのアクセス権を一元化し運用効率を向上させる。' },
  { term: 'Azureウェルアーキテクテッドフレームワーク', aliases: ['azureウェルアーキテクテッドフレームワーク', 'azure well-architected framework'], description: '信頼性・セキュリティ・コスト最適化・オペレーショナルエクセレンス・パフォーマンス効率の5つの柱でAzureアーキテクチャを評価・改善するフレームワーク。Well-Architected Reviewで現状分析ができる。' },
  { term: 'Azureランディングゾーン', aliases: ['azureランディングゾーン', 'azure landing zone'], description: 'AzureへのクラウドAdoptionを加速するためのスケーラブルなサブスクリプション設計と管理グループ階層のリファレンスアーキテクチャ。ネットワーク・ID・セキュリティ・ガバナンスの基盤を事前に整備する。' },
  { term: 'Azure CAF', aliases: ['azure caf', 'cloud adoption framework', 'caf'], description: 'MicrosoftがAzure導入プロジェクトを成功に導くために提供するガイダンス・ツール・ベストプラクティスの集合体。戦略・計画・準備・採用・ガバナンス・管理の各フェーズで実践的指針を提供する。' },
  { term: 'Azure Resource Graph', aliases: ['azure resource graph'], description: '数千規模のAzureリソースをKQLクエリで高速に検索・集計できるサービス。変更履歴の追跡やコンプライアンス評価、大規模なリソースインベントリ管理に活用される。' },
  { term: 'Azure Management Groups', aliases: ['azure management groups', 'management groups'], description: '複数のAzureサブスクリプションをツリー階層でグループ化し、ポリシーやRBACを一括適用できる組織管理の仕組み。大企業のAzureガバナンス設計の基盤となるリソース階層の最上位概念。' },
  { term: 'Azure Subscriptions', aliases: ['azure subscriptions', 'subscription', 'azureサブスクリプション'], description: 'Azureリソースを格納し請求の単位となる論理コンテナ。管理グループの下に位置しコスト分離・アクセス制御・ポリシー適用の境界を提供する。ランディングゾーン設計ではワークロードごとに分割することが多い。' },
  { term: 'Azure Virtual WAN', aliases: ['azure virtual wan', 'virtual wan', 'vwan'], description: 'ブランチ拠点・リモートユーザー・Azure VNet・オンプレミスをハブアンドスポーク型で接続するネットワークサービス。SD-WAN統合とExpressRoute・VPN・Azure Firewallを一元管理する。' },
  { term: 'Azure NAT Gateway', aliases: ['azure nat gateway'], description: 'サブネット内のリソースがアウトバウンド接続をスケーラブルに行うためのマネージドNATサービス。静的パブリックIPでのSNATにより接続数増加時のSNATポート枯渇問題を解消する。' },
  { term: 'Azure Virtual Network Peering', aliases: ['azure virtual network peering', 'vnet peering', '仮想ネットワークピアリング'], description: '同一リージョンまたは異なるリージョンのAzure VNet同士をMicrosoftバックボーンを通じて低レイテンシで接続する機能。ゲートウェイトランジットによってオンプレミス接続の共有も可能。' },
  { term: 'Azure Route Table', aliases: ['azure route table', 'route table', 'ユーザー定義ルート'], description: '【Azure】VNet内のサブネットにカスタムルーティングルールを適用するリソース。仮想アプライアンス（Azure FirewallやNVA）経由でトラフィックを強制転送するUDR（User Defined Routes）を定義する。 【OCI APEX】通信の転送先を決めるルール集合。' },
  { term: 'Azureマネージドディスク', aliases: ['azureマネージドディスク'], description: 'Azure VM向けにブロックストレージをマネージドサービスとして提供する機能。Standard HDD・Standard SSD・Premium SSD・Ultra Diskの4ティアがありスナップショットやAzure Backupとの統合でデータ保護も容易。' },
  { term: 'Azure Data Lake Storage', aliases: ['azure data lake storage', 'adls', 'azure data lake storage gen2'], description: 'ビッグデータ分析向けにBlobストレージを拡張したデータレイクサービス。階層型名前空間・ACL・Sparkネイティブ統合によって大規模データパイプラインを効率的に処理する。' },
  { term: 'Azureロールベースアクセス制御', aliases: ['azureロールベースアクセス制御', 'role-based access control'], description: 'Azureリソースへのアクセスをロール割り当てで管理するアクセス制御モデル。組み込みロール（Owner・Contributor・Reader等）とカスタムロールでリソースへの操作権限を最小権限の原則に従い付与する。' },
  { term: 'Azure DevTest Labs', aliases: ['azure devtest labs', 'devtest labs'], description: '開発・テスト環境のVMをポリシーベースで迅速にプロビジョニングし、コストを自動管理するサービス。環境の上限設定・自動シャットダウン・再利用可能なテンプレートで開発者の実験環境を低コストで提供する。' },
  { term: 'Azure Health Data Services', aliases: ['azure health data services', 'ahds'], description: '医療データ（FHIR・DICOM・MedTech）をセキュアに格納・変換・分析するマネージドサービス群。HL7 FHIRおよびDICOMプロトコルに対応し医療機関のデジタルヘルスソリューション構築を支援する。' },
  { term: 'Azureハイブリッド特典', aliases: ['azureハイブリッド特典', 'azure hybrid benefit', 'ahb'], description: '既存のWindows ServerやSQL ServerのオンプレミスソフトウェアライセンスをAzure VM・SQL Database・AKSに適用してコストを削減できるライセンス特典プログラム。最大80%以上のコスト削減効果がある。' },
  { term: 'Azureスポットインスタンス', aliases: ['azureスポットインスタンス', 'spot instances'], description: 'Azureの余剰コンピューティング容量をオンデマンドより最大90%安く利用できる中断可能なVM。Azureが容量を必要とする場合は30秒前通知で削除されるため、耐障害性を持つバッチ処理や開発環境に適する。' },
  { term: 'Azureテナント', aliases: ['azureテナント', 'azure tenant', 'aad tenant'], description: 'Microsoft Entra ID（旧Azure AD）の専用インスタンス。組織が最初にAzureやMicrosoft 365にサインアップした際に作成され、ユーザー・グループ・アプリ登録を管理するID境界となる。複数サブスクリプションを持てる。' },
  { term: 'Azure DevOps Server', aliases: ['azure devops server', 'tfs', 'team foundation server'], description: 'Azure DevOpsをオンプレミスで実行するセルフホスト型の開発プラットフォーム。インターネット接続なしに同等のCI/CD・バックログ・リポジトリ機能を利用でき、クラウドへの移行パスも提供する。' },
  { term: 'Azure Deployment Environments', aliases: ['azure deployment environments', 'deployment environments', 'ade'], description: '開発チームがセルフサービスでアプリケーション環境をプロビジョニングできるAzureサービス。ARMテンプレートやBicepを使った環境カタログをDevCenterで管理し、プロジェクトベースのコスト管理と自動削除ポリシーを提供する。' },
  { term: 'Azure Dev Box', aliases: ['azure dev box', 'microsoft dev box'], description: '開発者向けのクラウドPC（高性能Windows仮想マシン）をセルフサービスで迅速にプロビジョニングできるサービス。プロジェクト固有のイメージとDevCenterプールでオンボーディングを短縮しローカルPC不要の開発環境を実現する。' },
  { term: 'Azure Load Testing', aliases: ['azure load testing'], description: 'Apache JMeterスクリプトをクラウドで大規模実行してアプリケーションのパフォーマンスとスケーラビリティを検証するフルマネージド負荷テストサービス。CI/CDパイプラインへの組み込みとリアルタイム監視ダッシュボードを提供する。' },
  { term: 'Azure Chaos Studio', aliases: ['azure chaos studio', 'chaos studio'], description: 'カオスエンジニアリングの実験をAzureリソースに対して実行するサービス。障害インジェクション（CPU過負荷・ネットワーク遅延・VMシャットダウン等）でシステムの回復力を測定し弱点を発見する。' },
  { term: 'Azure Monitor Alerts', aliases: ['azure monitor alerts'], description: 'メトリクス・ログ・アクティビティログの条件に基づいて通知やアクション（Runbook実行・Webhook呼び出し等）を自動実行するAzure Monitorのアラート機能。アクショングループで通知先を一元管理する。' },
  { term: 'Azure Automanage', aliases: ['azure automanage', 'automanage'], description: 'WindowsおよびLinux VMに対してバックアップ・監視・パッチ管理・セキュリティベースラインなどのベストプラクティスを自動的に有効化・設定するサービス。運用のオーバーヘッドを最小化しベストプラクティスへの準拠を自動維持する。' },
  { term: 'Azureプライベートエンドポイント', aliases: ['azureプライベートエンドポイント', 'プライベートエンドポイント'], description: 'Azure Private LinkによってPaaSサービス（StorageやSQL等）のネットワークインターフェースをVNet内のプライベートIPアドレスでアクセス可能にする機能。インターネットを経由しない閉域通信でセキュリティを強化する。' },
  { term: 'Azure Policy イニシアチブ', aliases: ['azure policy イニシアチブ', 'policy initiative', 'ポリシーイニシアチブ', 'azure initiative'], description: '複数のAzure Policyをひとつのグループにまとめて一括適用するコレクション定義。CISベンチマークやNIST SP 800-53等のコンプライアンス標準を1つのイニシアチブとして管理しスコア評価できる。' },
  { term: 'Azureリソースロック', aliases: ['azureリソースロック', 'resource lock', 'azure lock'], description: 'Azureリソースの誤削除や変更を防ぐためにサブスクリプション・リソースグループ・リソースに適用するロック機能。CanNotDeleteロックとReadOnlyロックの2種類があり重要リソースの保護に用いる。' },
];
