// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: pmbok (2/3)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: '類推見積', description: '過去の似た案件から推測して見積る方法です。早い反面、似ているつもりで本質が違う案件には注意が必要です。' },
  { term: 'トップダウン見積', description: '全体規模から大まかに積み上げる前に見る見積方法です。早期判断には有効ですが、詳細精度は低くなりやすいです。' },
  { term: 'ボトムアップ見積', description: '作業単位まで分解して積み上げる見積方法です。精度は高めやすいですが、前提が固まっていないと逆に精密な錯覚を生みます。' },
  { term: '三点見積', description: '楽観値、通常値、悲観値の三つで見積る方法です。不確実性を前提にした現実的な見方ができます。' },
  { term: 'リスクバッファ', description: '想定外対応に備えて見込む余裕です。何に備えるバッファかを説明できることが大切です。' },
  { term: 'スケジュールバッファ', description: '日程遅延やレビュー待ちなどに備えた時間の余裕です。バッファゼロの計画は、現場ではかなり危険です。' },
  { term: '変更要求票', description: '変更したい内容と理由、影響を整理した申請票です。口頭依頼で済ませず、判断材料を文書化するために使います。' },
  { term: '変更要求管理', description: '変更要求の受付、評価、承認、実施、完了までを管理することです。案件中盤以降ほど重要性が増します。' },
  { term: '変更分類', description: '緊急、通常、標準、軽微など変更を種類分けすることです。種類に応じて審査や手順を変えると運用しやすくなります。' },
  { term: '標準変更', description: '繰り返し実施され、手順とリスクが十分分かっている変更です。毎回重い審査をしないことで運用効率を上げられます。' },
  { term: '通常変更', description: '一般的な承認プロセスを経て実施する変更です。影響とリスクを評価したうえで計画的に進めます。' },
  { term: '緊急変更', description: '障害対応や重大リスク回避のため、通常より速く実施する変更です。速さが必要でも、事後レビューは欠かせません。' },
  { term: '変更諮問', description: '変更内容について関係者へ意見を求めることです。特に他部門影響がある変更では有効です。' },
  { term: '影響分析', description: '変更がどこへ影響するかを事前に整理することです。機能だけでなく、帳票、連携、運用、契約、監査への影響も見る必要があります。' },
  { term: '変更リスク評価', description: '変更の危険度や失敗時影響を見積もることです。作業の難しさより、影響範囲の広さが重要になることもあります。' },
  { term: 'リリースノート', description: '今回何が変わったかを利用者や関係者に伝える文書です。機能追加だけでなく、制限事項や既知課題も明記すると親切です。' },
  { term: '既知課題', description: '現時点で把握している未解決の問題です。隠すより明示したほうが、運用側の判断がしやすくなります。' },
  { term: '周知計画', description: '変更内容を誰へどう伝えるかの計画です。利用者向け、運用向け、経営向けでは伝え方を分ける必要があります。' },
  { term: 'メンテナンス通知', description: '停止や制限を伴う作業について事前案内することです。時間だけでなく、影響範囲と問い合わせ先を示すと実務的です。' },
  { term: '停止計画', description: 'システム停止が必要な場合の時間帯、手順、影響、戻し方を定めた計画です。業務影響の最小化が重要です。' },
  { term: '無停止リリース', description: 'サービス停止なしで変更を反映することです。理想的ですが、仕組みと検証の両方が整っている必要があります。' },
  { term: '段階リリース', description: '一部から順に変更を反映する方法です。問題発見と影響限定に役立ちます。' },
  { term: 'フラグリリース', description: 'コードは先に入れ、機能の有効化を後から切り替える方法です。リリースと公開のタイミングを分離できます。' },
  { term: 'リリース判定会', description: '本番反映してよいか最終判断する会議や判断プロセスです。品質、既知課題、切替準備を総合的に見ます。' },
  { term: 'Go/No-Go判断', aliases: ['go/no-go判断'], description: '進めるか止めるかの最終判断です。勢いで進めず、基準に沿って冷静に判断する必要があります。' },
  { term: '切替条件', description: '新システムや新バージョンへ移るために満たすべき条件です。テスト完了だけでなく、運用準備や周知完了も含まれることがあります。' },
  { term: '切戻条件', description: 'どんな状態になったら戻すかという条件です。曖昧だと現場で迷い、被害が拡大しやすくなります。' },
  { term: '切戻手順', description: '旧状態へ戻すための具体的な操作手順です。書いてあるだけでなく、試してあることが重要です。' },
  { term: '本番確認項目', description: 'リリース後に正常性を確認するためのチェック項目です。最低限の業務動作をすぐ確認できるものを優先します。' },
  { term: 'スモーク確認', description: '本番反映直後に致命的問題がないか素早く確認することです。最初の数分から数十分が勝負になることもあります。' },
  { term: '安定化対応', description: 'リリース後の揺れや細かな不具合へ素早く対応して落ち着かせることです。開発完了と運用安定は別フェーズと考えると整理しやすいです。' },
  { term: '前提条件ドキュメント化', aliases: ['assumption documentation'], description: '見積や提案の前提として何を想定しているかを明示的に文書化する実践です。後の「認識違い」を防ぐための重要なプラクティスです。' },
  { term: '除外スコープ', aliases: ['exclusion scope'], description: '提案や見積の対象外として明示した範囲です。含まれないものを明確にすることが、最終的には信頼を守ることにつながります。' },
  { term: '見積条件シート', aliases: ['estimate conditions sheet'], description: '見積のスコープ・前提・制約・除外を一覧にまとめた表です。営業資料よりも契約準備の材料として機能します。' },
  { term: '値引きマージン', aliases: ['discount margin'], description: '価格交渉に備えて確保しておく調整余地です。計画されていない割引は利益を削るだけでなく、提案の価値認知も低下させる可能性があります。' },
  { term: '変更リクエストフォーム', aliases: ['change request form'], description: '希望する変更・その理由・影響を記載した申請書です。口頭依頼ではなく意思決定の根拠を文書化するために使います。' },
  { term: '変更リクエスト管理', aliases: ['change request management'], description: '変更リクエストを受付・評価・承認・実施・完了まで管理することです。プロジェクトの中盤以降に重要性が増します。' },
  { term: '変更リスクアセスメント', aliases: ['change risk assessment'], description: '変更のリスクレベルと障害時の影響範囲を評価することです。作業の難易度より影響の広さの方が重要な場合もあります。' },
  { term: '既知の問題', aliases: ['known issues'], description: '現在把握されているがまだ解決されていない問題のことです。隠すより開示する方が、運用側が適切な判断をしやすくなります。' },
  { term: '通知計画', aliases: ['notification plan'], description: '変更に関してどの情報を誰にどのように届けるかの計画です。ユーザー・運用担当・経営層では異なるコミュニケーションアプローチが必要です。' },
  { term: '段階的リリース', aliases: ['phased release'], description: '一部のユーザーやシステムから段階的に変更を展開する手法です。問題の早期検出と影響範囲の限定に役立ちます。' },
  { term: 'フィーチャーフラグリリース', aliases: ['feature flag release'], description: 'コードを先にデプロイし、機能の有効化を後から切り替える手法です。リリースと公開のタイミングを分離します。' },
  { term: 'リリース承認会議', aliases: ['release approval meeting'], description: '本番デプロイを進めるかどうかの最終判断を行う会議または意思決定プロセスです。品質・既知の問題・カットオーバー準備を総合的に確認します。' },
  { term: 'カットオーバー基準', aliases: ['cutover criteria'], description: '新しいシステムやバージョンへの切り替えに必要な条件です。テスト完了だけでなく、運用準備や通知完了も含む場合があります。' },
  { term: 'ロールバック基準', aliases: ['rollback criteria'], description: '前の状態に戻すべきタイミングを定義する条件です。曖昧だと現場で躊躇が生まれ、被害が拡大することがあります。' },
  { term: 'ロールバック手順', aliases: ['rollback procedure'], description: '前の状態に戻す具体的な作業手順です。文書化されているだけでなく、テストもされていることが重要です。' },
  { term: 'リリース後確認事項', aliases: ['post-release verification items'], description: 'リリース後の正常稼働を確認するためのチェック項目です。最小限の業務機能をすばやく検証できる項目を優先します。' },
  { term: '完了条件表', description: '作業や工程が完了したと判断する条件を表にしたものです。認識差防止に有効です。' },
  { term: '指摘管理表', description: 'レビュー指摘と対応状況を管理する表です。未対応漏れを防げます。' },
  { term: '残課題一覧', description: 'リリース時点で未解決の課題を整理した一覧です。引継ぎや今後計画に役立ちます。' },
  { term: '保留事項一覧', description: 'まだ決めていない論点を整理した一覧です。決定漏れを防ぐ実務的な資料です。' },
  { term: '前提条件一覧', description: '設計や見積の前提を一覧にしたものです。前提崩れ時の再評価に役立ちます。' },
  { term: '制約条件一覧', description: '予算、納期、技術、法令などの制約を整理した一覧です。判断の背景共有に有効です。' },
  { term: 'スコープ一覧', description: '対象範囲と対象外範囲を整理した一覧です。仕様膨張防止に使えます。' },
  { term: '関係者一覧', description: 'ステークホルダーとその役割を整理した一覧です。レビュー招集や承認経路にも使えます。' },
  { term: '体制図補足表', description: '組織図だけでは伝わらない責任範囲を補足する表です。誰が最終判断者かを明確にできます。' },
  { term: '役割期待値定義', description: '各役割に何が求められるかを定義したものです。曖昧な責任分担を減らします。' },
  { term: '引継ぎ項目一覧', description: '引継ぎ時に渡すべき情報を整理した一覧です。保守移管や担当変更で有効です。' },
  { term: '完了基準表', aliases: ['completion criteria table'], description: 'タスクやフェーズがいつ完了したと判断するかの条件を示す表です。期待値のずれを防ぐのに効果的です。' },
  { term: 'レビュー指摘管理表', aliases: ['review issue tracking table'], description: 'レビュー指摘とその解決状況を管理する表です。未解決の指摘が見落とされるのを防ぎます。' },
  { term: 'オープンイシュー一覧', aliases: ['open issues list'], description: 'リリース時点での未解決課題を整理した一覧です。引き継ぎや今後の計画に役立ちます。' },
  { term: 'ステークホルダー一覧', aliases: ['stakeholder list'], description: 'ステークホルダーとそのロールを整理した一覧です。レビュー招集や承認フローにも活用できます。' },
  { term: '組織図補足表', aliases: ['organization chart supplement table'], description: '組織図だけでは表現できない責任境界を補足した表です。最終決裁権者を明確にするのに役立ちます。' },
  { term: 'ロール期待定義', aliases: ['role expectation definition'], description: '各ロールに何が期待されているかを定義した書類です。曖昧な責任分担を減らします。' },
  { term: 'PM', aliases: ['pm', 'project manager (pm)'], description: 'プロジェクト全体を統括する責任者。' },
  { term: 'PL', aliases: ['pl', 'project lead'], description: 'プロジェクトや開発チームの実行面を主導する役割。' },
  { term: 'TL', aliases: ['tl', 'tech lead (tl)'], description: '技術面または小チーム単位でメンバーをリードする役割。' },
  { term: 'PMO', aliases: ['pmo'], description: 'プロジェクト管理を支援し、標準化や可視化を担う機能。' },
  { term: '品質保証', description: '成果物や運営が品質基準を満たすよう確認・管理する活動。' },
  { term: 'リスクマネジメント', aliases: ['risk management'], description: 'リスクを把握し、評価し、対策すること。' },
  { term: 'アジャイル開発', aliases: ['agile development'], description: '短いサイクルで設計・実装・確認を繰り返す開発手法。' },
  { term: 'ベンダー管理', aliases: ['vendor management (outsourcing)'], description: '外部委託先の進捗、品質、契約、役割を管理すること。' },
  { term: '進捗', aliases: ['progress'], description: '作業がどれだけ進んでいるかの状況。' },
  { term: 'コスト', aliases: ['cost (project)'], description: '業務やプロジェクトにかかる費用。' },
  { term: '要員', aliases: ['personnel'], description: 'プロジェクトに関わる人員。' },
  { term: 'IR', aliases: ['ir', 'investor relations'], description: '株主や投資家に経営状況を説明・発信する活動。' },
  { term: '適時開示', aliases: ['timely disclosure'], description: '投資判断に重要な情報を適切な時点で公開すること。' },
  { term: '人的資本経営', aliases: ['human capital management'], description: '人材を価値創出の源泉として経営戦略に結びつける考え方。' },
  { term: 'タレントマネジメント', aliases: ['talent management'], description: '社員の経験やスキルを可視化し、配置や育成に活かすこと。' },
  { term: 'エンゲージメント', aliases: ['employee engagement'], description: '社員の会社や仕事への愛着、共感、貢献意欲。' },
  { term: 'DE&I', aliases: ['de&i'], description: '多様な人材が公平に尊重され活躍できる状態を目指す考え方。' },
  { term: 'ESG', aliases: ['esg'], description: '環境、社会、ガバナンスの観点で企業価値を見る考え方。' },
  { term: 'SDGs', aliases: ['sdgs'], description: '持続可能な社会の実現に向けた国際目標。' },
  { term: '上場準備', aliases: ['ipo preparation'], description: '株式上場に向けて開示や統制、規程整備などを進めること。' },
  { term: 'パイロット検証', description: '本格導入の前に一部環境や限定利用者で試行し、課題や改善点を洗い出す検証。' },
  { term: '本番稼働', description: 'システムを正式に業務利用へ移行し、実運用を開始した状態。' },
  { term: '初期流動', description: '本番稼働直後に発生しやすい不具合や問い合わせに重点対応し、稼働安定化を図る期間。' },
  { term: 'プロジェクト計画書', description: '目的、範囲、体制、工程、管理方法、成果物など、プロジェクトの進め方を定める文書。' },
  { term: 'マスタスケジュール', description: 'プロジェクト全体の主要工程、マイルストーン、意思決定時点を俯瞰して示す計画表。' },
  { term: '進捗管理', description: '計画に対して作業の進行状況を把握し、遅延や偏りを早期に是正する管理活動。' },
  { term: '課題管理', description: 'すでに顕在化している問題や懸念事項を記録し、対応方針、担当、期限を明確にして管理すること。' },
  { term: '品質管理', description: '成果物や作業プロセスが定めた品質基準を満たすよう確認し、是正する管理活動。' },
  { term: 'コミュニケーション管理', description: '会議、報告、承認、情報共有の方法や頻度を定め、関係者間の認識差を防ぐ管理活動。' },
  { term: '納品物', description: '契約や合意に基づき、顧客へ正式に引き渡す成果物。' },
  { term: 'ステアリングコミッティ', description: '重要な方針、優先順位、課題対応を経営または上位管理層が判断する会議体。' },
  { term: 'Redmine', aliases: ['redmine'], description: '課題管理、Wiki、進捗管理などをまとめて扱えるプロジェクト管理ツール。' },
  { term: 'Backlog', aliases: ['backlog'], description: '課題管理やチーム作業を整理するためのプロジェクト管理ツール。比較的使いやすく、チームで進捗を共有しやすい。' },
  { term: 'パイロット移行', description: '全体移行の前に代表的な対象で試行し、手順や課題を確認してからの横展開に備える進め方。' },
  { term: '画面要件', aliases: ['画面仕様'], description: 'システムの画面（UI）に関する要件。どの画面が必要か、何の項目を表示するか、どのような操作ができるかを定義する。画面一覧や画面遷移図としてまとめられる。' },
  { term: '連携要件', aliases: ['if要件', 'インターフェース要件'], description: '他のシステムやサービスとのデータのやりとりに関する要件。どのシステムと、どのデータを、どの頻度でやりとりするかを定義する。IF要件とも呼ばれる。' },
  { term: '性能要件', aliases: ['パフォーマンス要件', 'performance requirement'], description: 'システムの速度や処理能力に関する要件。「1秒以内にレスポンスを返す」「同時1000ユーザーが利用できる」など数値で定義する非機能要件の一つ。' },
  { term: 'フィジビリティスタディ', aliases: ['feasibility study', 'フィジビリ', 'fs', '実現可能性調査'], description: '実現可能性調査のこと。プロジェクト開始前に、技術的・予算的・スケジュール的に実現できるかを調査・検討する活動。FS（フィジビリ）と略されることもある。' },
  { term: 'RFI', aliases: ['rfi', 'request for information', '情報提供依頼書'], description: 'Request For Informationの略。提案依頼前にベンダーから情報収集するための文書。「どんな技術や製品を持っているか」「費用感は」などを確認するために発行する。' },
  { term: '制約事項', aliases: ['constraints', '制限事項'], description: 'プロジェクトや提案において守らなければならない条件・制限のこと。「既存システムとの互換性を保つ」「予算は○○万円以内」などが制約事項にあたる。' },
  { term: '提案背景', description: '提案書においてなぜこの提案をするに至ったかの背景・状況を記述するセクション。顧客の課題・市場の変化・業務上の問題点などを説明し、提案の必然性を示す。' },
  { term: '課題整理', aliases: ['課題分析', 'issue analysis'], description: '顧客や自社が抱える問題点・課題をまとめ整理すること。提案書の作成や要件定義前に行い、何を解決すべきかを明確にする作業。' },
  { term: 'プロジェクトリーダー', aliases: ['project leader'], description: 'プロジェクトの現場での技術的なリーダー。PMの指示のもと、開発チームをまとめてプログラマーへのタスク割り当て、技術課題の解決、進捗管理を行う。PLと略される。' },
  { term: 'SE', aliases: ['se', 'systems engineer', 'システムエンジニア'], description: 'Systems Engineerの略。システムエンジニアの略称。顧客との要件定義、設計書作成、開発の取りまとめを行う技術者。プログラマーより上位工程を担当することが多い。' },
  { term: 'PG', aliases: ['pg', 'programmer', 'プログラマー'], description: 'Programmerの略。プログラマーの略称。設計書に基づいてプログラムを実際に書く（コーディングする）担当者。SEの設計したものをコードに変換する役割。' },
  { term: 'インフラエンジニア', aliases: ['infrastructure engineer'], description: 'サーバー、ネットワーク、クラウドなどのインフラ（基盤）を設計・構築・運用するエンジニア。AWSやAzureなどのクラウド基盤の管理も担当することが多い。' },
  { term: 'プロダクトオーナー', aliases: ['po'], description: 'アジャイル開発（スクラム）でプロダクトの価値を最大化する責任者。バックログの優先順位付けや要件の最終決定を担当する。顧客・ビジネス側の代表としてチームと連携する。' },
  { term: '改修', aliases: ['修正', 'enhancement', '機能改修'], description: '既存のシステムに対して変更・修正を加えること。バグ修正や機能追加、仕様変更への対応など。「改修依頼」「改修対応」のように使われる。' },
  { term: '追加開発', aliases: ['機能追加', '機能拡張', 'add-on development'], description: '既存システムに新しい機能や画面を追加する開発作業。リリース後に顧客から要望が上がったり、業務拡張に合わせて行う。' },
  { term: '影響調査', aliases: ['影響範囲調査', 'impact analysis'], description: '仕様変更や改修を行う際に、変更内容が他のシステムや機能に与える影響範囲を調査すること。影響範囲が大きいほど変更コストやリスクが高くなる。' },
  { term: '互換性', aliases: ['compatibility'], description: '新旧バージョンや異なるシステム間でデータや機能が問題なく動作すること。後方互換性（新しいバージョンが古いデータを扱える）・前方互換性がある。' },
  { term: 'デグレード', aliases: ['デグレ', 'regression', 'リグレッション', '退行'], description: '改修や変更によって、以前は正常に動作していた機能が壊れてしまうこと。「デグレが発生した」のように使う。リグレッションバグとも言い、リグレッションテストで検出する。' },
  { term: '変更依頼', aliases: ['cr', '仕様変更依頼'], description: '顧客や関係者からシステムの仕様を変更するよう依頼すること。変更依頼書（CR）として正式に提出されることが多い。範囲・コスト・スケジュールへの影響を確認して対応する。' },
  { term: '新規システム導入提案書', description: '新しい業務システム導入を提案する資料。背景・課題・方針・効果・体制・スケジュールで構成される。' },
  { term: 'PowerPoint', aliases: ['powerpoint', 'パワーポイント', 'ppt'], description: 'プレゼン資料作成ソフト。提案書やスライド形式の資料作成に広く使われる。' },
  { term: '表紙', description: '提案書や資料の最初のページ。会社名・提案タイトル・日付・提案先を記載する。' },
  { term: '次世代業務システム', description: 'より高度・効率的な新しい業務システム。現行システムの課題解消と将来拡張性を両立する。' },
  { term: '進捗把握', description: '業務や生産の進み具合を確認すること。遅延検知や意思決定の基礎になる。' },
  { term: '分散', description: '情報や機能が別々に存在すること。分散した情報は一元化によって統合する。' },
  { term: '重複入力', aliases: ['じゅうふくにゅうりょく'], description: '同じ情報を何度も入力すること。二重入力とも呼ばれ、工数増加とミスの原因になる。' },
  { term: '確認作業', description: '内容の正しさや状況を確認する作業。自動化・一元化で削減できることが多い。' },
  { term: '状況把握', description: '現在の状態を理解すること。リアルタイムなデータ共有によって改善できる。' },
  { term: '管理コスト', description: '管理に必要な時間・人件費・運用負荷。システム化により削減できる間接コスト。' },
  { term: '想定課題', description: 'あらかじめ見込まれる問題点。提案書では現状分析から導き出す。' },
  { term: 'リアルタイム', aliases: ['real-time', 'realtime'], description: 'ほぼ即時に情報が反映されること。システム連携や自動更新で実現する。' },
  { term: '紙運用', description: '紙を中心にした業務管理方法。データ化・共有・検索が難しく、デジタル化の対象になりやすい。' },
  { term: '部門間連携', description: '複数部門が情報共有して協力すること。情報一元化によって連携の質が向上する。' },
  { term: '基幹業務', description: '会社の中核となる重要業務。受注・生産・在庫・出荷・会計などがこれにあたる。' },
  { term: '管理部門', description: '管理・統制・集計などを担う部門。現場からの情報を集約して経営へ報告する。' },
  { term: '経営層', aliases: ['経営陣'], description: '経営判断を行う責任者層。提案書では意思決定者として重要なステークホルダー。' },
  { term: '情報の一元管理', aliases: ['情報一元管理'], description: '情報を1か所に集約して管理すること。分散・重複入力の解消に直結する。' },
  { term: '経営判断', description: '経営上の重要な意思決定。リアルタイムデータの可視化が高速化を支援する。' },
  { term: '統合システム', description: '複数機能をまとめたシステム。分散していた業務を一元管理できる。' },
  { term: 'レポート可視化', description: '数字や状況を見やすく表示すること。グラフ・ダッシュボードによる経営判断支援に使う。' },
  { term: '見える化', description: '状況を誰でも分かる形にすること。データの可視化・共有によって現場と経営をつなぐ。' },
  { term: '納期遵守率', description: '納期を守れた割合。導入効果のKPIとしてよく使われる指標。' },
  { term: '適正化', description: '多すぎず少なすぎず適切にすること。在庫最適化・コスト適正化などで使う。' },
  { term: '抑制', description: '増えすぎないように抑えること。コスト抑制・在庫抑制のように使う。' },
  { term: '二重入力', description: '同じ情報を別の場所にも入力すること。重複入力の典型例。工数増加とミスの原因になる。' },
  { term: '省力化', description: '人手や工数を減らすこと。自動化・システム化の主要な導入効果のひとつ。' },
  { term: '間接業務負荷', description: '直接生産ではない周辺業務の負担。集計・転記・確認作業などが該当する。' },
  { term: '導入後の業務イメージ', description: '導入後にどう業務が変わるかの想定。提案書のビフォーアフター比較で使う。' },
  { term: '即時反映', description: '入力内容がすぐにシステムへ反映されること。リアルタイム性の具体的な表現。' },
  { term: '集約されたデータ', description: 'まとめられた情報。一元管理によって実現し、分析や報告の基盤になる。' },
  { term: '稼働支援', description: '本番利用開始時のサポート。システム切り替え直後の混乱を最小化する活動。' },
  { term: '初期支援', description: '稼働直後の立ち上がり支援。利用者の操作習熟と課題対応が中心になる。' },
  { term: '現場定着', description: '現場で継続的に使われる状態。定着化支援の最終目標。' },
  { term: '伴走', description: '相手に寄り添って継続支援すること。導入後の運用支援を表す提案書用語。' },
  { term: '業務の分断', description: '業務や情報がつながっていない状態。部門間・システム間の連携不足で発生する。' },
  { term: '意思決定の高速化', description: '判断をより早く行えるようにすること。リアルタイムデータ可視化が実現手段。' },
  { term: '情報システム部門', aliases: ['情シス', 'is部門'], description: '社内ITを担当する部門。IT導入プロジェクトの社内窓口・推進主体になる。' },
  { term: '現場責任者', description: '現場運用を管理する責任者。IT導入では業務要件のキーパーソンになる。' },
  { term: '役割明確化', description: '誰が何を担当するか明確にすること。プロジェクト推進や定着化に不可欠。' },
  { term: '想定スケジュール', description: '予定している工程の時系列計画。提案書の導入の進め方セクションで示す。' },
  { term: '当社の強み', description: '提案企業の優位性。業務理解・実績・サポート体制などで差別化を示す。' },
  { term: '業務理解', description: '業務内容を深く理解していること。提案の説得力を高める重要な要素。' },
  { term: '一貫して対応', description: '上流から導入後まで通して支援すること。提案企業の強みとして訴求するケースが多い。' },
  { term: 'スコープ固定', aliases: ['fixed scope'], description: 'ウォーターフォール型開発において要件・機能範囲を契約時に確定させ変更しないアプローチ。' },
  { term: 'コスト・タイム固定', description: 'アジャイル開発においてコストと期間を固定しスコープを変動させるアプローチ。' },
  { term: '検収モデル', description: '発注者がシステムを受け入れる際の検査・承認プロセスを定義したモデル。受入基準と手順を規定する。' },
  { term: 'コスト・期間固定', aliases: ['fixed cost and time'], description: 'コストとスケジュールを固定し、スコープを変動させることを許容するアジャイルのアプローチです。' },
  { term: '受入モデル', aliases: ['acceptance model'], description: 'クライアントがシステムを検収・承認する際に使用する検査・承認プロセスを定義したモデルです。' },
  { term: 'フィジビリティ', description: 'プロジェクトや技術的アイデアの実現可能性を評価すること。技術・経済・時間・運用・法的観点から検討する。' },
  { term: '技術的実現可能性', aliases: ['technical feasibility'], description: '提案された技術的解決策が現在の技術・ノウハウで実現できるかを評価する観点。' },
  { term: '経済的実現可能性', aliases: ['economic feasibility'], description: 'プロジェクトのコストと期待効果・ROIを評価し投資が正当化できるかを判断する観点。' },
  { term: '時間的実現可能性', description: '要求された期間内にプロジェクトを完了できるかを評価する観点。スケジュールリスクを含む。' },
  { term: '運用的実現可能性', description: '導入後にシステムが組織の業務プロセス・人材・文化に受け入れられ運用できるかを評価する観点。' },
  { term: '法的実現可能性', aliases: ['legal feasibility'], description: 'プロジェクトが関連法規・規制・契約条件を満たして実施できるかを評価する観点。' },
  { term: '技術調査', aliases: ['technical investigation'], description: '採用候補技術の特性・成熟度・リスクを調査し採用可否を判断するための活動。' },
  { term: '概念実証', aliases: ['proof of concept'], description: 'アイデアや技術の実現可能性を小規模な試作で検証する活動。PoC（Proof of Concept）とも呼ぶ。' },
  { term: 'フィジビリティテスト', description: '実現可能性を検証するために行う小規模な実験・プロトタイプ構築テスト。' },
  { term: '期待値コントロール', description: 'プロジェクトにおいてステークホルダーの期待値を適切に管理・調整するコミュニケーション活動。' },
  { term: 'スケジュール実現可能性', aliases: ['schedule feasibility'], description: '要求された期間内にプロジェクトを完了できるかをスケジュールリスクも含めて評価することです。' },
  { term: '運用実現可能性', aliases: ['operational feasibility'], description: '展開後、システムが組織の業務プロセス・人・文化のなかで運用・受け入れられるかを評価することです。' },
  { term: 'フィージビリティテスト', aliases: ['feasibility test'], description: '実現可能性を検証するために実施する小規模な実験やプロトタイプ構築です。' },
  { term: '規模見積もり', description: 'ソフトウェアのファンクションポイント・ステップ数・ユースケース数などで開発規模を定量化すること。' },
  { term: '生産性数値', description: '単位規模あたりの工数（人月/FPなど）を表す値。組織・プロジェクト特性ごとに異なる。' },
  { term: '材料費', description: 'システム開発で必要なハードウェア・ソフトウェア・クラウドサービスなどの物品・サービス費用。' },
  { term: '作業費用', description: '開発作業に従事する人員の人件費・外注費など労務系のコスト。' },
  { term: '管理費', description: 'プロジェクト管理・品質管理・環境管理などの間接費用。' },
  { term: '超概算見積もり', description: 'プロジェクト初期に最低限の情報で行う粗い見積もり。精度は±50%程度。' },
  { term: '予算見積もり', description: '予算確保のために行う見積もり。精度は±25%程度。' },
  { term: '確定見積もり', description: '契約・実施計画に用いる精度の高い見積もり。精度は±10%程度。' },
  { term: '計画見積もり', description: 'プロジェクト計画策定のために詳細な分析をもとに行う見積もり。' },
  { term: '見積もり期待精度', description: '見積もり手法ごとに期待できる精度の範囲。プロジェクトフェーズや情報量で変わる。' },
  { term: '標準値法', description: '過去の類似プロジェクトの実績データから標準的な工数・期間を算出する見積もり手法。' },
  { term: '標準タスク法', description: 'プロジェクトを標準タスクに分解し各タスクの工数を積み上げて総工数を算出する見積もり手法。' },
  { term: 'COCOMO II', aliases: ['cocomo ii'], description: 'Barry Boehm提唱のコスト見積もりモデル。コードステップ数とコスト係数から工数を算出する。' },
  { term: 'ユースケースポイント法', description: 'ユースケースの複雑度とアクターの複雑度から開発規模・工数を見積もる手法。' },
  { term: 'ファンクションポイント法', description: 'システムの機能的規模をファンクションポイント（FP）で計測する国際標準の規模計測手法。' },
  { term: 'IFPUG法', aliases: ['ifpug法'], description: 'IFPUGが標準化したファンクションポイント計測手法。データファンクションとトランザクションファンクションを計測する。' },
  { term: 'データファンクション', description: 'ファンクションポイント法における内部論理ファイル（ILF）と外部インターフェースファイル（EIF）の総称。' },
  { term: 'トランザクションファンクション', description: 'ファンクションポイント法における外部入力（EI）・外部出力（EO）・外部照会（EQ）の総称。' },
  { term: 'ILF', aliases: ['ilf'], description: 'Internal Logical Fileの略。システム内部で管理・使用するデータの論理的なグループ。FP計測の対象。' },
  { term: 'EIF', aliases: ['eif'], description: 'External Interface Fileの略。他システムが管理するデータをシステムが参照するファイル。FP計測の対象。' },
  { term: 'EI', aliases: ['ei'], description: 'External Inputの略。外部からデータを受け取り内部ファイルを更新するトランザクション。' },
  { term: 'EO', aliases: ['eo'], description: 'External Outputの略。処理結果を外部に出力するトランザクション。' },
  { term: 'EQ', aliases: ['eq'], description: 'External Inquiryの略。外部からの照会に対してデータを取得・表示するトランザクション。' },
  { term: 'DET', aliases: ['det'], description: 'Data Element Typeの略。FP計測においてファイルまたはトランザクション内のデータ項目数。' },
  { term: 'RET', aliases: ['ret'], description: 'Record Element Typeの略。ILF/EIF内の論理的サブグループ数。FP計測に使用。' },
  { term: 'FTR', aliases: ['ftr'], description: 'File Type Referencedの略。トランザクションが参照するファイル（ILF/EIF）の数。FP計測に使用。' },
  { term: 'オブジェクトポイント法', description: 'アプリケーションのオブジェクト（画面・帳票・モジュール）数から規模を見積もる手法。' },
  { term: '工数ものさし', description: 'プロジェクトの難易度・規模に応じた工数の目安を示すリファレンス。見積もりの基準値として使う。' },
  { term: '最適工期', description: 'プロジェクトの工数規模に対して統計的に最適とされる開発期間。' },
  { term: '工期配分', description: 'プロジェクト全体の工期を各工程に割り当てる活動。工程間のバランスを考慮する。' },
  { term: '工数配分', description: '総工数を各工程・作業項目に割り当てる活動。生産性や難易度を考慮して配分する。' },
  { term: 'プロセスフロー設計', description: 'プロジェクトの各工程の順序・インプット・アウトプット・承認条件を設計する活動。' },
  { term: 'JFPUG', aliases: ['jfpug'], description: 'Japan Function Point Users Groupの略。日本でのファンクションポイント普及・研究を行う団体。' },
  { term: 'IFPUG', aliases: ['ifpug'], description: 'International Function Point Users Groupの略。ファンクションポイント計測手法を国際標準化する団体。' },
  { term: 'NESMA', aliases: ['nesma'], description: 'Netherlands Software Metrics Associationの略。ソフトウェア計測の標準化を推進するオランダの団体。' },
  { term: 'ソフトウェア規模', description: 'ソフトウェアの大きさをFP・LOC・ユースケース数などで定量的に表した値。' },
  { term: '工数変換係数', description: 'ファンクションポイントなどの規模指標から人月に変換するための係数。組織・技術スタックで異なる。' },
  { term: '開発期間', aliases: ['development period'], description: 'プロジェクトの開発フェーズにかかる期間。要件定義から製造完了までのカレンダー期間を指す。' },
  { term: '製造期間', aliases: ['construction period'], description: 'コーディング・単体テストを実施するフェーズにかかる期間。' },
  { term: 'タイム', aliases: ['time'], description: 'プロジェクトの時間・期間に関する制約。鉄の三角形の一要素。' },
  { term: '鉄の三角形', aliases: ['iron triangle'], description: 'スコープ・コスト・タイムのトレードオフ関係を表すプロジェクト管理のモデル。どれかを変えると他に影響する。' },
  { term: '仕様凍結', aliases: ['specification freeze'], description: '変更を受け付けない最終仕様の確定状態。これ以降の変更は変更管理プロセスを経る必要がある。' },
  { term: '進捗管理基準', aliases: ['progress management criteria'], description: 'プロジェクトの進捗状況を評価する基準。EVM・出来高・マイルストーン達成率などが使われる。' },
  { term: '定量的プロジェクトマネジメント', aliases: ['quantitative project management'], description: 'メトリクスとデータを活用してプロジェクトの計画・監視・制御を行うアプローチ。CMMIレベル4に対応。' },
  { term: 'リスク評価レベル', aliases: ['risk assessment level'], description: 'リスクの影響度と発生確率から算出したリスクの深刻さを段階で表した評価。' },
  { term: 'リスク値', aliases: ['risk value'], description: 'リスクの影響度×発生確率で算出したリスクの大きさを示す数値。' },
  { term: 'リスク値合計', aliases: ['total risk value'], description: 'プロジェクト全体のリスク値を合算した総合リスク指標。プロジェクト健全性の指標となる。' },
  { term: '危険レベル', aliases: ['danger level'], description: 'リスク評価でリスク値が閾値を超えた最も深刻なリスク段階。即時対応が必要。' },
  { term: '要監視レベル', aliases: ['watch level'], description: 'リスク評価で中程度のリスク段階。定期的な監視と準備が必要。' },
  { term: '通常レベル', aliases: ['normal level'], description: 'リスク評価でリスク値が許容範囲内の通常状態。定期チェックで管理する。' },
  { term: '安全レベル', aliases: ['safe level'], description: 'リスク評価でリスクが十分に低く管理された状態を示す最良の段階。' },
  { term: 'リスク対策', aliases: ['risk countermeasure'], description: '特定されたリスクに対して回避・軽減・転嫁・受容のいずれかの対策を定める活動。' },
  { term: '予防策', aliases: ['preventive measure'], description: 'リスクが実際に発生しないよう事前に講じる対策。リスク回避・軽減が目的。' },
  { term: '継続監視', aliases: ['continuous monitoring'], description: 'リスクや品質指標を定期的に測定・評価し続ける活動。' },
  { term: '体制リスク', aliases: ['organizational risk'], description: 'プロジェクトチームの構成・スキル・経験・ステークホルダー関係に起因するリスク。' },
  { term: '技術リスク', aliases: ['technical risk'], description: '採用技術の成熟度・実績・習熟度・統合複雑性に起因するプロジェクトリスク。' },
  { term: 'プロジェクト失敗', aliases: ['project failure'], description: 'スコープ・品質・コスト・期間のいずれかが目標を大きく外れたプロジェクトの終焉状態。' },
  { term: '炎上', aliases: ['project meltdown'], description: 'プロジェクトが制御を失いトラブル・遅延・品質問題が連鎖的に発生する深刻な状態。' },
  { term: 'SL', aliases: ['sl'], description: 'Service Levelの略。システムやサービスが達成すべき品質・可用性の水準。' },
  { term: '工程表', aliases: ['process schedule'], description: 'プロジェクトの各工程・タスクのスケジュール・担当・マイルストーンを示した表。' },
  { term: 'データ移行ウォーターフォール', aliases: ['data migration waterfall'], description: '既存システムから新システムへのデータ移行を段階的に計画・実行・検証する手順モデル。' },
  { term: '平行稼動', aliases: ['parallel operation'], description: '新旧システムを同時に動かして比較・検証する移行手法。リスクを最小化できるが運用コストが高い。' },
  { term: 'ps', description: '現在実行中のプロセスの情報を表示するコマンド。ps auxで全プロセスをユーザー・CPU・メモリ情報付きで一覧表示できる。' },
  { term: 'nice', description: 'プロセスの実行優先度（ナイス値）を指定してコマンドを起動するコマンド。ナイス値は-20（最高優先）〜19（最低優先）の範囲で指定する。' },
  { term: 'renice', description: '実行中のプロセスのナイス値（優先度）を変更するコマンド。プロセスID、ユーザー、グループを指定して優先度を動的に変更できる。' },
  { term: 'ionice', description: 'プロセスのI/Oスケジューリングクラスと優先度を設定するコマンド。アイドルクラスを指定することでバックグラウンド処理のI/O影響を最小化できる。' },
  { term: 'ulimit', description: 'シェルセッションで利用できるシステムリソース（オープンファイル数、プロセス数、メモリなど）の制限を表示・設定するコマンド。' },
  { term: 'プロセスツリー', aliases: ['process tree', 'pstree'], description: '親子関係を持つプロセスの階層構造。pstreeコマンドで視覚的に確認でき、init/systemdが根（root）プロセスとなる。' },
  { term: 'ゾンビプロセス', aliases: ['zombie process'], description: '実行終了したが親プロセスが終了コードを回収していないためプロセステーブルに残り続けているプロセス状態（Z状態）。' },
  { term: '孤児プロセス', aliases: ['orphan process'], description: '親プロセスが終了してしまった子プロセス。init（PID1）またはsubreaper設定のプロセスに引き取られる。' },
  { term: 'SIGTERM', aliases: ['sigterm', 'signal 15'], description: 'プロセスに正常終了を要求するシグナル（シグナル番号15）。killコマンドのデフォルトシグナルで、プロセスはハンドリングして終了処理を行える。' },
];
