// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: contractLegal (3/3)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_003: ReadonlyArray<GlossaryEntry> = [
  { term: '備品', aliases: ['office equipment', 'furniture and fixtures'], description: '机・椅子・パソコン・プリンターなど、事務所内で使用する物品のうち固定資産に計上するもの。取得価額が一定金額（通常10万円以上）以上の場合に固定資産として計上し、耐用年数に基づき減価償却を行う。' },
  { term: '棚卸資産', aliases: ['inventory assets', 'stock in trade'], description: '販売目的で保有する商品・製品・仕掛品・原材料などの在庫資産。期末に実地棚卸を実施して数量・金額を確定し、貸借対照表の流動資産に計上する。評価方法（先入先出法・移動平均法等）を会計方針として定める必要がある。' },
  { term: '売上高', aliases: ['net sales revenue', 'total sales amount'], description: '企業が商品やサービスを提供して得た収益の合計。損益計算書の最上位に記載され、売上原価を差し引いて売上総利益（粗利益）を算出する。返品・値引き・割戻しを控除した純額で計上するのが原則。' },
  { term: '小口現金', aliases: ['petty cash fund', 'small cash reserve'], description: '切手購入・雑費などの少額経費を支払うために担当者が手元に保管する現金。小口現金係が出納帳を管理し、一定金額を使い切ったタイミングや月末に証憑を添えて補充・精算する。不正防止のため定期的な残高確認が重要。' },
  { term: '出納帳', aliases: ['cash journal book', 'receipt and payment ledger'], description: '現金や預金の入出金を逐次記録する帳簿。日付・相手先・摘要・金額・残高を記入し、帳簿残高と実際残高を照合して過不足を防ぐ。現金出納帳と預金出納帳に分けて管理するのが一般的。' },
  { term: '出金', aliases: ['cash disbursement', 'payment outflow'], description: '現金や銀行口座から金銭が支出されること。経費支払い・仕入代金・給与・税金納付などが含まれる。出金伝票や振込依頼書で管理し、証憑と照合して適切な勘定科目に仕訳する。' },
  { term: '入金', aliases: ['cash receipt', 'payment inflow'], description: '現金や銀行口座に金銭が受け入れられること。売上代金・前受金・保証金の受領・補助金の入金などが含まれる。入金伝票や銀行入金通知書で確認し、売掛金との消込処理を行って残高を管理する。' },
  { term: '預金', aliases: ['bank deposit', 'financial institution deposit'], description: '銀行や信用金庫などの金融機関に預け入れた資金。普通預金・当座預金・定期預金・外貨預金などの種類があり、貸借対照表の流動資産（定期預金は固定資産の場合も）に計上する。期末には残高証明書で帳簿残高を照合する。' },
  { term: '振込', aliases: ['bank wire transfer', 'electronic fund transfer'], description: '銀行口座を通じて相手先の口座へ資金を移動する決済手段。給与の支払い・仕入先への支払い・経費精算などに広く使われる。振込手数料が発生する場合があり、支払手数料として計上する。インターネットバンキングによる振込が一般的。' },
  { term: '領収証', aliases: ['official receipt document', 'payment receipt'], description: '代金を受け取ったことを証明する書類。発行者名・受領日・受領金額・但し書き（品目）・印が必要事項となる。経費精算の際の証憑として使用され、一定金額以上では印紙税の貼付が必要。電子領収証も法令要件を満たせば有効。' },
  { term: '支払申請書', aliases: ['payment request form', 'expenditure approval request'], description: '外部業者への支払いや各種経費の支出を上司・経理部門に申請するための社内書類。支払先・金額・支払目的・支払期日・勘定科目を記載し、所定の承認ルートで決裁を得る。承認後に経理部門が実際の支払いを実行する。' },
  { term: '伝票', aliases: ['accounting slip', 'transaction voucher'], description: '取引の内容を記録する会計書類の総称。入金伝票・出金伝票・振替伝票の3種類が基本であり、仕訳の根拠として会計処理に使用する。仕訳帳の代わりに伝票を使用する「伝票式簿記」も広く採用されている。' },
  { term: '仮払金', aliases: ['temporary advance payment', 'prepaid expense advance'], description: '出張旅費・接待費など業務に必要な費用を事前に概算で支払う制度、またはその金額。支払い後は精算書と証憑（領収証等）を提出し、実費との差額を返金または追加払いして清算する。未精算の仮払金は貸借対照表に流動資産として残る。' },
  { term: '立替', aliases: ['out-of-pocket expense', 'personal expense reimbursement'], description: '業務上の費用を従業員が一時的に個人の資金で支払うこと。後から精算書と証憑を経理部門に提出し、会社から実費の返金を受ける。会社が直接支払うべき費用を立替えているため、立替金は会社への債権として処理される。' },
  { term: '計算書類', aliases: ['financial statements under company law', 'statutory financial documents'], description: '会社法に基づいて作成・開示が義務付けられた財務書類の総称。貸借対照表・損益計算書・株主資本等変動計算書・個別注記表が含まれ、大会社では会計監査人の監査が必要となる。株主総会で承認を受ける。' },
  { term: 'キャッシュフロー計算書', aliases: ['cash flow statement', 'statement of cash flows'], description: '一定期間における会社の現金・現金同等物の増減を示す財務諸表。営業活動・投資活動・財務活動の3つの区分で現金の流れを開示する。損益計算書だけでは把握できない実際の資金の動きを示し、上場企業では作成・開示が義務付けられている。' },
  { term: '連結決算', aliases: ['consolidated financial settlement', 'group consolidation accounting'], description: '親会社と子会社・関連会社を一つの経済単位とみなして作成する決算。グループ内の内部取引を消去し、グループ全体の財務状況・経営成績を把握するために作成する。上場企業では連結財務諸表の開示が義務付けられている。' },
  { term: '連結財務諸表', aliases: ['consolidated financial statements', 'group financial reports'], description: '連結決算に基づいて作成するグループ全体の財務諸表。連結貸借対照表・連結損益計算書・連結包括利益計算書・連結株主資本等変動計算書・連結キャッシュフロー計算書から構成される。上場企業は金融商品取引法に基づき作成・開示が義務付けられる。' },
  { term: '資産除去債務', aliases: ['asset retirement obligation', 'facility removal liability'], description: '有形固定資産の使用後に法的・契約的な義務として発生する除去・原状回復コストを現在価値で計上した負債。オフィスの原状回復費用・解体費用などが該当する。資産除去債務に対応する金額を有形固定資産の取得原価に加算し、耐用年数にわたって費用配分する。' },
  { term: '賞与引当金', aliases: ['accrued bonus reserve', 'employee bonus provision'], description: '決算期末時点で未払いの賞与について、翌期の実際支払いに備えて計上する引当金。支給対象期間に対応する金額を費用として見積もり、当期の費用として計上する。引当金繰入額は人件費に含まれ、実際の支払い時に引当金を取り崩す。' },
  { term: '棚卸資産評価損', aliases: ['inventory write-down loss', 'stock valuation loss'], description: '棚卸資産の正味売却可能価額（時価）が帳簿価額（取得原価）を下回った場合に計上する損失。期末に棚卸資産の評価を行い、低価法（取得原価と時価を比較して低い方を採用）に基づいて帳簿価額を切り下げる。売上原価または特別損失として処理する。' },
  { term: '売上原価', aliases: ['cost of goods sold', 'cost of sales'], description: '売上高に対応する商品・製品を販売するために要したコスト。商品仕入れ・製造にかかる材料費・労務費・製造経費などから構成される。損益計算書において売上高から差し引いて売上総利益（粗利益）を算出する。' },
  { term: '原価要素', aliases: ['cost components', 'elements of manufacturing cost'], description: '原価計算において製品やサービスのコストを構成する基本的な要素。材料費・労務費・経費の3つが主要な原価要素であり、それぞれを製造直接費と製造間接費に分けて管理する。正確な原価要素の把握が原価計算精度の向上につながる。' },
  { term: '費目別管理', aliases: ['cost item classification management', 'expense category control'], description: '費用を勘定科目（材料費・人件費・地代家賃・通信費等）ごとに分類して収集・管理する手法。予算管理・原価計算・コスト削減活動の基礎となり、部門別管理や製品別管理と組み合わせて活用される。月次で予算と実績を対比する際の基本単位。' },
  { term: '稟議規程', aliases: ['internal approval procedure rules', 'ringi process regulations'], description: '稟議書の作成・回覧・承認・保管に関する社内ルールを定めた規程。起案できる権限・承認ルート・決裁権限基準額（金額による承認レベルの区分）・保管期間などを明確にする。ワークフローシステムを活用した電子稟議も普及している。' },
  { term: '予算管理規程', aliases: ['budget management regulations', 'annual budget control policy'], description: '年度予算の策定・配分・実績管理・差異分析に関する社内ルールを定めた規程。予算編成スケジュール・編成手順・部門別の責任者・修正予算の手続きなどを定める。経営目標の達成に向けて会社全体を管理する仕組みの根拠となる。' },
  { term: '年度予算', aliases: ['annual operating budget', 'fiscal year budget plan'], description: '事業年度ごとに策定する収益・費用・投資・資金の計画。経営目標を数値に落とし込み、月次の実績と対比して進捗を管理する。売上予算・費用予算・設備投資予算・人員計画などから構成される。中期経営計画の下位計画として位置づけられる。' },
  { term: '中期経営計画', aliases: ['medium-term business plan', 'three to five year corporate strategy'], description: '通常3〜5年の事業期間にわたる経営目標・事業戦略・財務目標をまとめた計画。年度予算の上位計画として位置づけられ、経営幹部が作成して取締役会で承認される。売上・利益・ROE・投資計画などの数値目標を設定する。' },
  { term: '資金調達', aliases: ['corporate fundraising', 'capital procurement'], description: '事業活動や設備投資に必要な資金を外部から確保すること。銀行借入・社債発行・株式増資・補助金・クラウドファンディングなど複数の手段がある。調達手段によってコスト（金利・配当）や財務への影響が異なるため、最適な手段を選択する。' },
  { term: '借入', aliases: ['bank loan borrowing', 'debt financing'], description: '金融機関や取引先から資金を借りること。1年以内に返済する短期借入金と1年超の長期借入金に分類され、貸借対照表の負債の部に計上する。借入時には金利・返済期間・担保・保証などの条件を金融機関と交渉する。' },
  { term: '社債', aliases: ['corporate bond', 'company issued bond'], description: '会社が資金調達のために発行する債券。投資家（個人・機関投資家）から資金を集め、償還期限に元本を返済し期間中は利息を支払う。普通社債・転換社債・新株予約権付社債などの種類があり、発行時に有価証券届出書の提出が必要な場合がある。' },
  { term: '資金繰り', aliases: ['cash flow management', 'liquidity planning'], description: '日常的な資金の収支を管理し、支払いが滞らないように調整すること。資金繰り表（キャッシュフロー計画表）を作成し、入金タイミングと出金タイミングを把握して資金不足を未然に防ぐ。特に中小企業では黒字倒産を防ぐためにも重要な業務。' },
  { term: '資金管理', aliases: ['treasury management', 'corporate cash management'], description: '会社の資金の調達・運用・回収・決済を総合的に管理する業務。余剰資金の安全な運用・必要資金の確保・外国為替リスク管理・金利リスク管理などを含む。財務部門が中心となり、銀行との関係管理も重要な役割となる。' },
  { term: '印章管理', aliases: ['corporate seal management', 'company stamp control'], description: '会社印・代表者印・銀行印・角印などの印章の保管・使用・廃棄を管理する業務。印章の種類ごとに保管責任者を定め、使用の都度に使用簿へ記録して不正使用を防止する。社内規程（印章管理規程）に基づいて厳格に運用する。' },
  { term: '有価証券管理規程', aliases: ['securities management policy', 'investment securities control rules'], description: '株式・社債・国債・投資信託等の有価証券の取得・保有・処分・評価に関する社内ルールを定めた規程。取得の目的・承認権限・評価方法・保管方法・処分手続きなどを規定し、有価証券の適正管理と不正防止を図る。' },
  { term: '投資有価証券', aliases: ['long-term investment securities', 'non-current investment holdings'], description: '長期保有を目的として保有する株式・社債・投資信託等の有価証券。短期売買目的の流動資産に分類される有価証券と区別し、貸借対照表の固定資産に計上する。その他有価証券は時価評価し、評価差額を純資産の部に計上する。' },
  { term: '法人税', aliases: ['corporate income tax', 'company tax liability'], description: '法人の所得（益金から損金を差し引いた課税所得）に対して課される国税。事業年度終了後2ヶ月以内に申告・納付が必要。税率は会社の規模・所得金額によって異なり、中小企業向けの軽減税率が適用される場合がある。' },
  { term: '消費税', aliases: ['consumption tax', 'value added tax'], description: '商品の販売やサービス提供に対して課される間接税。一定規模以上の課税事業者が消費者から預かり、申告・納付する。課税売上高・非課税売上高の区分・仕入税額控除の計算（一般課税・簡易課税）が経理処理の重要ポイント。' },
  { term: '税務調査', aliases: ['tax authority audit', 'revenue investigation'], description: '税務署（国税局）が企業の税務申告内容の正確性を確認するために行う調査。帳簿・証憑・申告書・取引記録などの検査が実施される。申告漏れや誤りが発見された場合は修正申告や更正が行われ、追徴税額・加算税・延滞税が発生することがある。' },
  { term: '会計監査人', aliases: ['statutory auditor cpa', 'external audit firm'], description: '公認会計士または監査法人が会社の財務諸表の適正性を独立した立場から審査する役割。大会社（資本金5億円以上または負債200億円以上）等では会計監査人の設置が会社法・金融商品取引法で義務付けられている。監査報告書を株主総会に提出する。' },
  { term: '会計方針', aliases: ['accounting policy', 'financial statement preparation policy'], description: '財務諸表の作成において企業が採用する会計処理の基準・方法・手続きの総称。棚卸資産の評価方法・固定資産の減価償却方法・収益認識の方法などが含まれる。一度採用した方針は継続して適用し、変更する場合には注記で開示が必要。' },
  { term: '会計基準', aliases: ['accounting standards', 'financial reporting standards'], description: '財務諸表の作成に際して準拠すべき基準。日本では企業会計基準委員会（ASBJ）が設定する「企業会計基準」が中心で、上場企業向け・中小企業向け・公益法人向けなど複数の基準体系がある。IFRSとの任意適用も認められている。' },
  { term: '配当金', aliases: ['dividend payment', 'shareholder profit distribution'], description: '会社が株主に対して利益の一部を分配するために支払う金銭。定時株主総会の決議または中間配当として支払われる。会社側では純資産（利益剰余金）の減少として処理し、受取側（個人株主）では配当所得として課税される。' },
  { term: '剰余金', aliases: ['retained surplus', 'corporate surplus funds'], description: '資本金を超えて蓄積された純資産の部分。資本剰余金（資本取引から生じたもの）と利益剰余金（利益の蓄積）に区分される。配当の財源・内部留保として活用され、株主総会の決議に基づいて処分される。' },
  { term: '資本準備金', aliases: ['capital reserve fund', 'additional paid-in capital reserve'], description: '株式発行・合併等の資本取引により生じた払込剰余金のうち、資本金として組み入れなかった部分。会社法により資本金の4分の1に達するまで積み立てが義務付けられる（法定準備金）。減資や欠損補填に充当できる。' },
  { term: '登記', aliases: ['corporate registration', 'legal entity filing'], description: '法人の設立・本店所在地・商号・役員・資本金・事業目的などを法務局に申請して公的に記録すること。会社設立時の設立登記のほか、役員変更・増資・本店移転・組織再編時には変更登記を一定期間内（2週間以内が原則）に行う義務がある。' },
  { term: '保険料', aliases: ['insurance premium expense', 'insurance coverage payment'], description: '損害保険・生命保険・賠償責任保険等に加入するために保険会社へ支払う対価。当期に対応する部分は費用（保険料）として計上し、次期以降に対応する長期の前払い分は前払費用として貸借対照表に計上する。期間按分の処理が必要。' },
  { term: '現金管理', aliases: ['cash handling control', 'petty cash administration'], description: '手元現金の収支・残高・保管を適正に管理する業務。現金担当者が日次で出納帳を記帳し、帳簿残高と実際の手持ち現金を照合する。金庫への保管・現金確認の実施・複数名によるチェック体制などで横領や紛失を防止する。' },
  { term: '支店勘定', aliases: ['branch office account', 'head office branch intercompany account'], description: '本店と支店間の取引（資金の移動・費用の立替等）を記録するための内部勘定科目。本店側に「支店勘定」、支店側に「本店勘定」を設け、残高を相互に照合する。決算時には本支店間の内部取引を相殺して合算財務諸表を作成する。' },
  { term: '社外秘', aliases: ['company confidential classification', 'internal use only document'], description: '会社内部でのみ取り扱い、社外へは開示・持ち出しを禁じる情報・文書の機密区分。機密情報管理規程に基づいて設定され、財務データ・人事情報・取引先情報・技術情報などが対象となる。文書への表示・アクセス権限管理・廃棄方法が規程で定められる。' },
  { term: '有価証券', aliases: ['marketable securities', 'negotiable financial instruments'], description: '株式・社債・国債・手形・小切手など、財産権を表示する証券の総称。保有目的によって売買目的有価証券・満期保有目的債券・子会社株式・その他有価証券に分類され、それぞれ異なる評価基準（時価または原価法）が適用される。' },
  { term: '服務規律', aliases: ['workplace conduct rules', 'employee code of conduct'], description: '職場で従業員が守るべき行動規範・勤務態度・行為基準の総称。就業規則に規定され、遅刻・無断欠席・ハラスメント禁止・機密保持義務などを含む。違反した場合は懲戒処分の対象となるため、入社時の説明と周知徹底が重要。' },
  { term: '服務の原則', aliases: ['principles of employee conduct', 'basic service principles'], description: '服務規律の基本的な精神や原則を示す条文。誠実勤務・職務専念・法令遵守・上司指示への従事などが規定される。就業規則の冒頭に置かれることが多く、従業員の行動全般の指針となる。' },
  { term: '勤怠管理', aliases: ['attendance management', 'time and attendance tracking'], description: '従業員の出勤状況・休暇・遅刻・早退・残業などを記録・集計・管理する業務。勤怠システムを活用して正確な勤務実績を把握する。労働時間管理や給与計算の基礎データとなり、労基法の遵守にも直結する。' },
  { term: '勤怠システム', aliases: ['time and attendance system', 'employee time tracking system'], description: 'タイムカード・ICカード・スマートフォン等を利用して出退勤時刻を記録・集計する情報システム。給与計算・労働時間管理と連携する。クラウド型のシステムが普及しており、テレワーク下でも正確な勤怠管理が可能。' },
  { term: '出勤', aliases: ['reporting for work', 'clocking in'], description: '従業員が所定の勤務場所に出て業務を開始すること。始業時刻までの出勤が求められ、出退勤記録システムに記録する。テレワーク環境では業務開始の報告やシステムへのログインをもって出勤と見なす場合がある。' },
  { term: '退勤', aliases: ['clocking out', 'end of work day'], description: '従業員が業務を終えて勤務場所を退出すること。終業時刻・残業の有無・実際の退勤時刻を記録する。残業がある場合は上司の事前承認が必要なケースが多く、退勤打刻後の残業（いわゆるサービス残業）は労基法違反となる。' },
  { term: '半日休暇', aliases: ['half-day leave', 'half-day paid time off'], description: '午前または午後の半日分を有給休暇として取得する制度。就業規則に規定があれば利用でき、0.5日として有給休暇残日数から控除する。育児・通院・手続きなど短時間の用事に対応しやすく、従業員の休暇取得率向上に貢献する。' },
  { term: '育児短時間勤務', aliases: ['reduced working hours for childcare', 'short-time work for child rearing'], description: '育児介護休業法に基づく措置で、3歳未満の子を持つ従業員が所定労働時間を短縮して勤務できる制度。育児と仕事の両立を支援する。1日の所定労働時間を原則6時間に短縮でき、会社は申請を拒否できない。' },
  { term: '労働条件通知書', aliases: ['employment conditions notification document', 'labor conditions notice'], description: '採用時に会社が従業員へ交付する書面で、賃金・労働時間・休日・就業場所・業務内容などの主要な労働条件を明記する。労基法で交付が義務付けられている。2024年4月からは就業場所・業務の変更範囲の明示も必須となった。' },
  { term: '雇用契約書', aliases: ['employment contract document', 'employment agreement'], description: '会社と従業員が雇用条件について合意した内容を記載して双方が署名・捺印する契約書。労働条件通知書と兼用する形式も多い。電子契約での締結も法的に有効であり、クラウドサービスを活用する企業が増えている。' },
  { term: '労働契約法', aliases: ['labor contract act', 'employment contract law'], description: '労働契約の成立・変更・終了に関するルールを定めた法律。有期雇用の無期転換ルールや雇止めの規制も含む。就業規則による労働条件の不利益変更には合理的な理由と周知が求められる。' },
  { term: '賃金', aliases: ['wages', 'employee compensation'], description: '従業員が労働の対価として使用者から受け取る金銭。基本給・各種手当・賞与・退職金を含む広い概念で、労基法で最低限のルールが定められている。賃金支払いの5原則（通貨払い・直接払い・全額払い・毎月払い・一定期日払い）を遵守する必要がある。' },
  { term: '基本給', aliases: ['base salary', 'basic monthly salary'], description: '毎月の給与のうち、個人の職能・職位・年齢等に基づいて支払われる基本的な賃金。各種手当・賞与計算の基礎となることが多い。昇給・降給の対象となり、賃金制度の根幹をなす。' },
  { term: '査定委員会', aliases: ['performance review committee', 'evaluation adjustment committee'], description: '従業員の人事考課（評価）結果を審議・調整するための社内委員会。評価の公平性・一貫性を確保するために設置する。部門間の評価水準のばらつきを調整する調整会議（キャリブレーション）としての機能を果たすことが多い。' },
  { term: '表彰', aliases: ['employee recognition', 'company award'], description: '優れた業績・行動・提案をした従業員を公式に称えること。表彰規程に基づいて実施し、社長賞・部門賞・提案賞などの種類がある。モチベーション向上・組織文化の醸成に寄与し、賞金・賞品を伴う場合もある。' },
  { term: '副業', aliases: ['side job', 'secondary employment'], description: '本業の会社への勤務以外に、別の会社等で就労または個人事業として収入を得ること。就業規則で許可制・届出制を定める会社が多い。過重労働・情報漏洩・利益相反のリスクを踏まえた適切な管理が求められる。' },
  { term: '兼業', aliases: ['concurrent employment', 'dual employment'], description: '本業の業務と並行して、別の業務・職業・役職を兼ねること。利益相反・秘密漏洩・本業への支障がないかを確認した上で許可する。副業と類似概念だが、兼業は複数の業務を同時並行するニュアンスが強い。' },
  { term: 'ハラスメント苦情窓口', aliases: ['harassment grievance window'], description: 'ハラスメントの被害を受けた従業員が相談・申告できる窓口。社内担当者または外部機関（弁護士・EAP等）が対応し、通報者の秘密を守る。ハラスメント防止法に基づき企業は相談体制の整備が義務付けられている。' },
  { term: 'ダイバーシティ', aliases: ['diversity and inclusion', 'workforce diversity'], description: '性別・年齢・国籍・障がい・価値観など多様な属性の人材を組織に取り込み、活躍できる環境を整えること。ダイバーシティ推進規程やD&I方針を策定する企業が増えている。企業競争力の強化やイノベーション創出につながるとされる。' },
  { term: '両立支援', aliases: ['work-life balance support', 'dual responsibility support'], description: '仕事と育児・介護・治療などを両立できるよう支援する取り組み。育児短時間勤務・介護休業・テレワーク活用などを組み合わせて実現する。次世代育成支援対策推進法に基づく行動計画の策定が企業に求められる。' },
  { term: '福利厚生', aliases: ['employee benefits', 'welfare benefits'], description: '賃金以外に会社が従業員とその家族へ提供する経済的・サービス的な給付。法定福利厚生（社会保険等）と法定外福利厚生（住宅補助・健康支援等）に分かれる。人材採用・定着に影響する重要な要素であり、カフェテリアプラン等の選択型も普及している。' },
  { term: 'マイカー通勤規程', aliases: ['personal vehicle commuting policy', 'car commuting rules'], description: '従業員が自家用車で通勤する際のルール（承認手続き・任意保険加入義務・駐車場・事故時の取り扱い等）を定めた規程。通勤途中の交通事故が労災となり得るため、保険加入確認と安全運転指導が不可欠。' },
  { term: '交通費', aliases: ['commuting allowance', 'transportation expense'], description: '通勤または業務上の移動に要する費用。通勤手当として給与に含めて支給するか、実費精算で支給するかを就業規則・旅費規程で定める。所得税法上、一定額まで非課税扱いとなるため課税・非課税の区分管理が必要。' },
  { term: '産業医', aliases: ['industrial physician', 'occupational health doctor'], description: '従業員の健康管理を専門的に担う医師。一定規模以上の事業場への選任が義務付けられ、健康診断・長時間労働者面談・衛生委員会への参加などを行う。常時50名以上の事業場では産業医の選任が義務となり、1,000名以上では専属産業医が必要。' },
  { term: '衛生管理者', aliases: ['workplace health manager', 'occupational health officer'], description: '職場の安全衛生を管理する国家資格者。常時50名以上の従業員がいる事業場では選任が義務付けられ、作業環境・健康管理・教育を担う。業種に応じて第一種・第二種の資格区分があり、定期的に職場巡視を行う義務がある。' },
  { term: '衛生委員会', aliases: ['workplace health committee', 'occupational safety and health committee'], description: '職場の安全衛生に関する重要事項を調査審議するための委員会。常時50名以上の事業場で月1回以上の開催が義務付けられる。産業医・衛生管理者・労働者代表等が参加し、メンタルヘルス対策や過重労働防止策を審議する。' },
  { term: '健康診断', aliases: ['health examination', 'employee medical checkup'], description: '従業員の健康状態を定期的に確認するための医学的検査。雇入時・定期（年1回）・特殊健康診断等があり、実施と記録保存が法律で義務付けられる。結果に基づき産業医が就業判定を行い、必要に応じて就業制限・配慮措置を講じる。' },
  { term: '災害補償', aliases: ['workplace accident compensation', 'occupational injury compensation'], description: '業務上の負傷・疾病・障害・死亡に対して会社が行う補償。労災保険の給付に加えて、就業規則・労働協約に基づく上乗せ補償を定める場合もある。会社が独自の災害補償規程を整備することで従業員の安心感と信頼を高められる。' },
  { term: '労災', aliases: ['industrial accident', 'workers compensation claim'], description: '労働災害の略。業務中または通勤途中に生じた負傷・疾病・障害・死亡を指す。労災保険から治療費・休業補償・障害補償等が給付される。業務起因性・業務遂行性の両要件を満たすかどうかで労災認定の可否が判断される。' },
  { term: '雇用保険', aliases: ['employment insurance', 'unemployment insurance'], description: '失業・育児休業・介護休業・教育訓練等の際に給付を行う社会保険制度。事業主と従業員双方が保険料を負担する。週の所定労働時間が20時間以上で31日以上雇用見込みがある場合は原則加入が必要。' },
  { term: '社会保険', aliases: ['social insurance', 'employee social security'], description: '健康保険・厚生年金保険・介護保険などの総称。一定の要件を満たす従業員とその使用者が加入義務を負い、費用を折半負担する。2022年以降、短時間労働者への適用が段階的に拡大され、加入対象者が増加している。' },
  { term: '労働保険', aliases: ['labor insurance', 'workers insurance'], description: '労災保険と雇用保険の総称。原則として全従業員の加入が義務付けられ、保険料は年度ごとに確定・申告・納付する。毎年6月1日から7月10日に行う年度更新（確定申告と概算申告）が事業主の重要な手続き。' },
  { term: '定期健康診断', aliases: ['annual health checkup', 'periodic medical examination'], description: '常時使用する従業員に対して年1回（一定業務は6ヶ月に1回）実施が義務付けられている健康診断。結果に基づく就業措置・保健指導も必要。所見のある従業員には産業医の意見を聴取し、必要に応じて就業上の配慮を行う。' },
  { term: 'メンタルヘルス', aliases: ['mental health management', 'workplace mental wellness'], description: '精神的な健康状態の維持・増進に関する取り組みの総称。ストレスチェック制度・相談窓口・産業医との連携・職場環境改善が柱となる。4つのケア（セルフケア・ラインによるケア・事業場内産業保健スタッフによるケア・事業場外資源によるケア）が厚生労働省指針で示されている。' },
  { term: '年休管理', aliases: ['annual paid leave management', 'vacation leave tracking'], description: '従業員の年次有給休暇の取得状況・残日数・取得計画を管理すること。年5日の有給休暇取得義務（年休5日付与ルール）を遵守するために重要。会社は年5日の有給休暇を確実に取得させる責任があり、違反には罰則が設けられている。' },
  { term: '休業補償', aliases: ['absence compensation', 'work absence pay'], description: '業務上の傷病や労災により就業できない期間の賃金補償。労災保険の休業給付に加え、会社独自の休業補償を就業規則で定める場合もある。休業4日目以降は労災保険から休業給付（給付基礎日額の60%）が支給される。' },
  { term: '育児介護休業規程', aliases: ['childcare and nursing care leave policy', 'parental leave regulations'], description: '育児・介護休業の申請手続き・対象者・期間・給与取扱い・復職手続き等を定めた社内規程。育児介護休業法に準拠して整備する。2022年の法改正により産後パパ育休の新設・分割取得等が追加され、規程の更新が必要となった企業が多い。' },
  { term: '社員持株会', aliases: ['employee stock ownership plan', 'company stock purchase association'], description: '従業員が自社株式を定期的に購入・積み立てする福利厚生制度。会社が奨励金を上乗せして交付することが多く、財産形成を支援する。奨励金は給与所得として課税対象となるため、税務処理も含めた適正な運用が必要。' },
  { term: '定年後再雇用制度', aliases: ['post-retirement rehire system', 're-employment after retirement'], description: '定年退職した従業員を希望者に限り一定期間再雇用する制度。高年齢者雇用安定法に基づき、65歳までの雇用継続が義務付けられる。嘱託社員として有期雇用契約を結ぶ形式が一般的で、賃金・職務を個別に設定する。' },
  { term: '契約社員用就業規則', aliases: ['fixed-term employee work rules', 'contract staff employment regulations'], description: '有期雇用契約の従業員（契約社員）に適用される就業規則。正社員用と別に作成し、雇用期間・更新基準・待遇を定める。パートタイム・有期雇用労働法により、正社員との不合理な待遇差は禁止されており、規程内容の見直しが求められる。' },
  { term: '嘱託社員', aliases: ['contracted employee', 're-hired contract staff'], description: '定年退職後に有期契約で再雇用された従業員や、専門知識・技術を有して特定業務を担う契約社員の呼称。雇用条件は個別に定める。「嘱託」は法律上の定義がなく、各社が就業規則で定義・運用する。' },
  { term: '身元保証人', aliases: ['personal guarantor', 'employment character reference guarantor'], description: '採用時に従業員の身元を保証し、万一の損害賠償責任を負うことを約束した第三者。身元保証法に基づき期間・効力が制限される。身元保証契約の有効期間は原則5年（更新可）で、使用者は従業員の不適切な行為を知った場合は保証人に通知する義務がある。' },
  { term: '雇用継続', aliases: ['employment continuation', 'continued employment'], description: '雇用契約を更新・延長して従業員の就業を継続させること。有期雇用の雇止め規制・無期転換ルールの観点から適切な更新管理が必要。5年を超えて継続雇用された有期雇用者からの無期転換申込みを拒否することはできない。' },
  { term: '役員報酬', aliases: ['executive compensation', 'director remuneration'], description: '取締役・監査役・執行役員等の役員へ支払う報酬・賞与・退職慰労金の総称。株主総会の決議・役員報酬規程に基づいて支給する。法人税法上の損金算入要件（定期同額給与・事前確定届出給与・業績連動給与）を遵守する必要がある。' },
  { term: '報奨金', aliases: ['incentive pay', 'performance bonus award'], description: '特定の目標達成・成果・行動に対して支払う一時的な金銭。インセンティブ給・成果報酬とも呼ばれ、支給基準は賃金規程・報奨金規程で定める。賃金に該当するため労基法の規制対象となり、支給条件を明確にしておく必要がある。' },
  { term: '配属', aliases: ['department assignment', 'job placement'], description: '採用された従業員を特定の部署・職場に配置すること。また、異動後に新しい部署で勤務を開始することも指す。新卒採用では配属面談やキャリア希望の聴取を経て決定するケースが増えており、ミスマッチ防止が重視されている。' },
  { term: '異動', aliases: ['job transfer', 'internal personnel transfer'], description: '従業員の所属部署・勤務地・職務が変わること。人事異動命令によって正式に発令され、定期異動・臨時異動がある。業務命令としての異動には就業規則の根拠が必要であり、権利濫用にあたる異動命令は無効とされる場合がある。' },
  { term: '人事異動命令', aliases: ['personnel transfer order', 'internal reassignment order'], description: '会社が従業員に対して部署・勤務地・職務の変更を正式に命じる指示。配置転換・出向・転籍・昇格に伴う発令が含まれる。就業規則に異動命令の根拠規定が必要であり、生活上の著しい不利益を与える場合は裁量権の濫用として無効となり得る。' },
  { term: '研修', aliases: ['corporate training program'], description: '業務遂行に必要な知識・スキル・マインドセットを習得するための教育プログラム。入社時研修・階層別研修・専門スキル研修などがある。研修中の賃金取扱いや費用負担（自己負担の有無）を就業規則・研修規程で明確にする必要がある。' },
  { term: '教育訓練', aliases: ['employee education and training', 'vocational training'], description: '従業員の職業能力を高めるための計画的な教育活動の総称。OJT（職場内訓練）とOFF-JT（職場外訓練）を組み合わせて実施する。雇用保険の教育訓練給付制度を活用することで、従業員の自己啓発・スキルアップを支援できる。' },
  { term: '自己啓発', aliases: ['self-development', 'employee self-improvement'], description: '従業員が主体的に業務外の時間を使ってスキル・知識・資格取得に取り組む活動。資格手当・費用補助・通信教育制度で会社が支援することが多い。雇用保険の教育訓練給付（専門実践・特定一般・一般）との組み合わせで費用負担を軽減できる。' },
  { term: '資格手当', aliases: ['qualification allowance', 'professional certification bonus'], description: '業務に関連する特定の資格を取得した従業員に毎月支給する手当。対象資格・手当金額は賃金規程・資格手当規程に定める。資格の有効期限切れや退職時の扱いも明確に規定しておく必要がある。' },
  { term: '定年退職', aliases: ['mandatory retirement age', 'retirement at prescribed age'], description: '就業規則に定めた定年年齢（通常60歳または65歳）に達したことにより自動的に退職となること。退職金・再雇用の手続きが発生する。高年齢者雇用安定法により、65歳までの雇用確保措置（再雇用制度・定年延長・定年廃止のいずれか）が義務付けられている。' },
  { term: '退職金', aliases: ['retirement allowance', 'severance pay'], description: '会社を辞めた際に支給されるまとまったお金。退職金規程に基づき算定され、勤続年数・退職事由・等級が算定基準となる。税務上は退職所得として課税され、勤続年数に応じた退職所得控除が適用されるため税負担が比較的軽くなる。' },
  { term: '退職手当', aliases: ['retirement benefit', 'departure allowance'], description: '退職金と同義で使われることが多いが、特に公務員の退職時給付や退職一時金を指す呼称として用いられる場合もある。国家公務員は退職手当法、地方公務員は各自治体の条例に基づいて算定・支給する。' },
  { term: '確定拠出年金', aliases: ['defined contribution pension', 'dc pension plan'], description: '拠出金額が確定しており、運用実績によって将来の給付額が変わる企業年金制度（DC・401k）。加入者自身が運用指図を行う。企業型DCと個人型DC（iDeCo）があり、マッチング拠出制度を導入する企業も多い。' },
  { term: 'ライフプラン支援金', aliases: ['life plan support benefit', 'financial life planning allowance'], description: '従業員のライフプラン（老後設計・住宅購入・教育資金等）を支援するために会社が提供する金銭的給付や制度の総称。確定拠出年金への上乗せ拠出や住宅取得補助として設計されるケースがある。' },
  { term: 'マイカー業務使用規程', aliases: ['personal vehicle business use policy', 'employee car business use rules'], description: '従業員が業務目的で自家用車を使用する際のルール（事前承認・保険加入・交通費精算・事故責任）を定めた規程。業務中の事故は使用者責任として会社も責任を問われる可能性があるため、任意保険の加入確認が必須。' },
  { term: 'アルムナイ', aliases: ['corporate alumni network', 'former employee network'], description: '会社を退職した元従業員の総称（英：alumni）。アルムナイネットワークを構築し、再入社・協業・採用紹介などに活用する取り組みが広がっている。優秀な人材の呼び戻し（ブーメラン採用）や事業パートナー開拓にも効果がある。' },
  { term: '紹介採用制度', aliases: ['employee referral program', 'referral hiring system'], description: '現役の従業員が知人・友人・元同僚を会社に紹介して採用につなげる採用制度（リファラル採用とも呼ばれる）。紹介者への報奨金制度を設ける場合が多い。採用コストの削減と早期定着率の向上が期待でき、採用難時代に注目されている手法。' },
  { term: 'アルバイト', aliases: ['part-time worker', 'temporary job employee'], description: '本業以外に、短時間・短期間で就労する雇用形態。学生・主婦・副業者が多く、時給制が一般的。雇用契約・就業規則の適用範囲を明確にする必要がある。最低賃金法・労働基準法の適用を受け、正当な理由なく不利益に扱うことは禁じられている。' },
  { term: 'パートタイマー', aliases: ['part-time employee', 'short-hour worker'], description: '正社員と比べて所定労働時間が短い労働者。パートタイム・有期雇用労働法の適用を受け、均等・均衡待遇の確保が求められる。正社員との不合理な待遇差は違法となり、基本給・賞与・各種手当の同一性が問われる。' },
  { term: 'スタッフ職', aliases: ['staff function role', 'specialist support position'], description: 'ライン組織とは独立して、特定の専門業務（法務・財務・人事等）を担当する職位区分。管理職ラインではなく、専門性を発揮する役割を担う。専門職としてのキャリアパスを整備することで、管理職志向のない優秀人材の定着を図ることができる。' },
  { term: 'ライン職', aliases: ['line management role', 'operations line position'], description: '事業の直接的な実行（生産・営業・開発等）を担い、部下を持つ指揮命令系統に属する職位区分。スタッフ職と対比する概念。ライン管理職は部下の育成・業績管理・ハラスメント防止において重要な役割を果たす。' },
  { term: '欠勤', aliases: ['unexcused absence', 'unauthorized work absence'], description: '正当な理由のない（または会社が認めない）休業。就業規則に基づき、欠勤日数分の賃金が控除され、一定日数を超えると懲戒処分の対象となる場合がある。欠勤が続く場合は面談を実施し、背景（メンタルヘルス・家庭問題等）を把握することが重要。' },
  { term: '遅刻', aliases: ['late arrival', 'tardy reporting'], description: '所定の始業時刻後に出勤すること。就業規則に基づき遅刻分の賃金控除や届出義務が生じる。無断遅刻・常習的遅刻は服務違反として扱われる。人事評価への影響・注意指導・懲戒処分の段階的対応を就業規則で定めておくことが望ましい。' },
  { term: '早退', aliases: ['early departure', 'leaving work early'], description: '所定の終業時刻前に職場を離れること。事前に上司の承認を得る必要があり、就業規則に基づき早退分の賃金が控除される場合がある。急病・家族の緊急事態等の場合は事後申請を認める会社も多く、運用ルールを明確化しておく必要がある。' },
  { term: '公民権行使', aliases: ['civil rights exercise', 'civic duty leave'], description: '従業員が選挙・裁判員・公職就任など公民としての権利・義務を行使すること。労基法により、会社は公民権行使を妨げてはならない。公民権行使に必要な時間を与える義務があるが、有給か無給かは就業規則で定めることができる。' },
  { term: '看護休暇', aliases: ['child care leave for illness', 'family nursing leave'], description: '小学校就学前の子どもが病気・けがをした場合に、看護のために取得できる休暇。子の人数に応じて年5〜10日取得でき、無給・有給は会社規程による。2021年の育児介護休業法改正により、1日単位のほか時間単位での取得も可能になった。' },
  { term: '社宅', aliases: ['company housing', 'employer-provided housing'], description: '会社が従業員の居住用に提供する住宅。借上社宅・社有社宅があり、従業員は市場家賃より低い自己負担額で入居できる福利厚生の一つ。税務上は賃貸料相当額の一定割合を従業員から徴収しないと現物給与として課税される可能性がある。' },
  { term: 'Elon Musk', aliases: ['elon musk', 'イーロン・マスク'], description: '南アフリカ出身の起業家・実業家。Tesla（電気自動車）、SpaceX（宇宙開発）、X（旧Twitter）などを創業・率いる。「高尚な概念を語るより、工学的課題を解決することに時間を使いたい」という実務志向の経営哲学で知られる。' },
  { term: 'SpaceX', aliases: ['spacex', 'スペースx'], description: 'Elon Muskが2002年に設立した民間宇宙開発企業。再利用可能なロケット（Falcon 9）や宇宙船（Dragon）を開発し、宇宙輸送コストの劇的な削減を実現した。「工学的課題の解決」を重視するMuskの経営哲学を体現する企業として知られる。' },
  { term: 'Tesla', aliases: ['tesla', 'テスラ'], description: 'Elon Muskが率いるアメリカの電気自動車・エネルギー企業。電気自動車の大衆普及を推進し、ソフトウェアOver-The-Air更新など自動車のソフトウェア化をリードした。' },
  { term: 'ベトナムオフショア', description: 'ベトナムの開発拠点や人材を活用するオフショア開発のことです。日本企業ではコストと人材確保の両面から採用されることが多い形態です。' },
  { term: 'BotDev', aliases: ['botdev', 'borderless oneteam development'], description: 'システムエグゼの開発体制・サービス名称です。日本側主導の管理とベトナム側リソースの活用を組み合わせ、品質・納期・コストのバランスを取る考え方です。' },
  { term: 'ブリッジSE', aliases: ['ブリッジse', 'bse'], description: '日本側と海外側の間に立ち、要件や設計意図、業務背景を橋渡しするエンジニアです。単なる翻訳ではなく、認識のずれを防ぐ役割を担います。' },
  { term: 'コミュニケーター', description: '現地側で意思疎通を支え、チーム間の連絡や理解のずれの解消を助ける役割です。BotDevでは三層コミュニケーションの一部として位置づけられています。' },
  { term: '三層コミュニケーション', description: '日本側PM、日本側ブリッジSE、ベトナム現地コミュニケーターの三層で意思疎通を行う仕組みです。情報の抜け漏れや認識差を早期に発見する狙いがあります。' },
  { term: '固定チーム運用', description: 'できる限り同じメンバーで開発を継続する運用です。業務知識や設計方針がチーム内に蓄積しやすく、品質のばらつきを抑えやすくなります。' },
  { term: '日本側主導', description: '要件定義やレビュー、進行管理を日本側が中心となって進める考え方です。あいまいな仕様のまま実装が進むことを防ぐ意図があります。' },
  { term: 'ベンダー選定', description: '開発パートナーや委託先を選ぶことです。単価だけでなく、品質管理やコミュニケーション能力も重要です。' },
  { term: 'コストメリット', description: '費用面で得られる利点です。オフショア開発では期待されやすい一方、管理負担で打ち消される場合もあります。' },
  { term: '高付加価値', description: '単に機能を満たすだけでなく、利用者や顧客にとって価値の高い成果を提供することです。' },
  { term: 'お客様満足度', description: '顧客が製品やサービスにどれだけ満足しているかを示す考え方です。品質向上の重要な到達点のひとつです。' },
  { term: '企業価値', description: '企業が持つ信頼、収益力、ブランド、将来性などを総合した価値です。品質向上は企業価値向上にもつながるとされています。' },
  { term: '半期', description: '1年を2つに分けた6か月単位の期間です。品質管理では半期ごとの相互チェックが示されています。' },
  { term: 'ライセンスコスト', description: 'ソフトウェアやサービスの利用許諾にかかる費用です。利用者数や機能数に応じて増える場合があります。' },
  { term: 'サステナビリティ', aliases: ['sustainability', '持続可能性'], description: '持続可能性を意味し、企業活動を社会・環境・経済の観点から長期的に成り立たせる考え方です。' },
  { term: 'つくる責任 つかう責任', description: '持続可能な生産と消費に関わる考え方を表す表現です。SDGsの目標12に対応し、企業にも利用者にも責任があることを示しています。' },
  { term: '平和と公正をすべての人に', description: '平和、公正、包摂的な社会の実現を目指す考え方を表す言葉です。SDGsの目標16に対応しています。' },
  { term: '協賛活動', description: '社会的な活動やイベントを支援する取り組みです。企業の社会参加の一形態です。' },
  { term: '人権の取り組み', description: '企業活動において人権を尊重し、侵害を防止するための方針や施策です。' },
  { term: '社会貢献活動', description: '企業が事業以外も含めて社会に価値を還元する活動です。地域支援や教育支援などが含まれます。' },
  { term: 'SystemEXE, Inc.', aliases: ['systemexe, inc.', '株式会社システムエグゼ', 'システムエグゼ', 'systemexe'], description: '日本のITサービス企業。BotDevによるオフショア開発体制やExecTORA開発標準体系を独自に策定し、品質重視のシステム開発を行っている。' },
  { term: 'コラム', description: '特定テーマについて解説や提案をまとめた記事コンテンツです。企業サイトではノウハウ発信の手段として使われます。' },
  { term: '導入事例', aliases: ['case study'], description: '実際の顧客やプロジェクトでどのようにシステムやサービスが使われたかを示す事例です。' },
  { term: '資料ダウンロード', description: '会社案内やサービス資料などを取得できる導線です。企業サイトでリード獲得に使われます。' },
  { term: 'お問い合わせ', description: '相談、見積依頼、質問などを受け付ける窓口です。企業サイトの主要な導線のひとつです。' },
  { term: 'プライバシーポリシー', aliases: ['privacy policy', '個人情報保護方針'], description: '個人情報の取り扱い方針を示した文書です。収集目的、利用範囲、第三者提供の有無などを明記します。' },
  { term: 'アクサ生命保険株式会社', aliases: ['アクサ生命', 'axa life insurance'], description: 'フランスに本拠を置く世界最大級の保険・資産運用グループAXAの日本における生命保険会社です。変額保険や医療保険、就業不能保険など多様な商品を提供しています。' },
  { term: 'アスクル株式会社', aliases: ['askul'], description: 'オフィス用品を中心とした通信販売大手です。「明日届く」が社名の由来で、法人向けのASKULと個人向けのLOHACOを展開しています。' },
  { term: '出光興産株式会社', aliases: ['出光興産', 'idemitsu kosan'], description: '石油精製・販売を主力とするエネルギー企業です。2019年に昭和シェル石油と経営統合し、国内有数の石油元売会社となりました。' },
  { term: 'KDDI株式会社', aliases: ['kddi株式会社', 'kddi', 'au'], description: '「au」ブランドの携帯電話事業を中心とする日本の大手通信事業者です。固定通信、衛星通信、データセンター事業も展開しています。' },
  { term: '工機ホールディングス株式会社', aliases: ['工機ホールディングス', 'koki holdings', 'hikoki'], description: '旧日立工機。「HiKOKI（ハイコーキ）」ブランドの電動工具を製造・販売するグローバルメーカーの持株会社です。95か国以上に販売拠点を持ちます。' },
  { term: '株式会社小松製作所', aliases: ['コマツ', 'komatsu', 'komtrax'], description: '建設機械・鉱山機械の世界的メーカーです。ICT施工やスマートコンストラクションなど建設現場のDXを推進しています。' },
  { term: '株式会社サンシャインシティ', aliases: ['サンシャインシティ', 'sunshine city'], description: '東京・池袋のサンシャインシティ（超高層ビル・商業施設・水族館・展示ホール等の複合施設）を運営する企業です。' },
  { term: '株式会社サンリオ', aliases: ['サンリオ', 'sanrio'], description: 'ハローキティをはじめとするキャラクターの企画・ライセンス・商品販売を行うグローバル企業です。テーマパーク「サンリオピューロランド」も運営しています。' },
  { term: 'スカパーJSAT株式会社', aliases: ['スカパーjsat株式会社', 'スカパーjsat', 'sky perfect jsat'], description: 'アジア最大級の衛星通信事業者であり、有料多チャンネル放送「スカパー！」を運営する企業です。宇宙事業とメディア事業の二本柱で展開しています。' },
  { term: '株式会社SUBARU', aliases: ['株式会社subaru', 'subaru', 'スバル'], description: '「スバル」ブランドの自動車を製造・販売するメーカーです。水平対向エンジンやシンメトリカルAWDを特徴とし、航空宇宙事業も手がけています。旧社名は富士重工業。' },
  { term: '株式会社TMEIC', aliases: ['株式会社tmeic', 'tmeic', '東芝三菱電機産業システム'], description: '東芝と三菱電機の合弁で設立された産業用電機システムメーカーです。旧社名は東芝三菱電機産業システム株式会社。鉄鋼・化学・物流など幅広い産業向けの電気設備・オートメーションシステムを提供しています。' },
  { term: '東京海上日動火災保険株式会社', aliases: ['東京海上日動', 'tokio marine'], description: '東京海上ホールディングス傘下の国内最大級の損害保険会社です。1879年創業の日本初の保険会社の流れを汲みます。' },
  { term: '株式会社東京証券取引所', aliases: ['東証', 'tse', 'tokyo stock exchange'], description: '日本最大の証券取引所です。日本取引所グループ（JPX）の子会社であり、プライム・スタンダード・グロースの3市場区分で有価証券の売買を行っています。' },
  { term: '株式会社東芝', aliases: ['東芝', 'toshiba'], description: '社会インフラ、エネルギー、半導体、デジタルソリューションなどを手がける日本の総合電機メーカーです。1875年創業の長い歴史を持ちます。' },
  { term: '日本KFCホールディングス株式会社', aliases: ['日本kfcホールディングス株式会社', '日本kfc', 'kfc japan'], description: 'ケンタッキーフライドチキン（KFC）やピザハットの日本における事業を統括する持株会社です。' },
  { term: '株式会社博報堂DYホールディングス', aliases: ['株式会社博報堂dyホールディングス', '博報堂dyhd', 'hakuhodo dy'], description: '博報堂、大広、読売広告社などを傘下に持つ国内第2位の広告代理店グループの持株会社です。' },
  { term: '株式会社ファミリーマート', aliases: ['ファミマ', 'familymart'], description: '国内大手のコンビニエンスストアチェーンです。伊藤忠商事の子会社であり、国内外で約24,000店舗を展開しています。' },
  { term: '富士フイルムビジネスイノベーション株式会社', aliases: ['富士フイルムbi', '旧富士ゼロックス'], description: '旧富士ゼロックス。複合機、プリンター、ドキュメントソリューション等を提供する富士フイルムグループのビジネスソリューション企業です。' },
  { term: '株式会社プロテリアル', aliases: ['プロテリアル', 'proterial', '旧日立金属'], description: '旧日立金属。特殊鋼、磁性材料、電線材料など高機能材料に特化したメーカーです。フェライト磁石やリードフレーム材で世界トップシェアの製品群を持ちます。' },
  { term: 'マニュライフ生命保険株式会社', aliases: ['マニュライフ生命', 'manulife'], description: 'カナダに本拠を置くマニュライフ・ファイナンシャルグループの日本における生命保険会社です。外貨建て保険や個人年金保険に強みを持ちます。' },
  { term: '三井住友海上火災保険株式会社', aliases: ['三井住友海上', 'msi'], description: 'MS&ADインシュアランスグループの中核となる損害保険会社です。企業向け・個人向けの幅広い損害保険商品を提供しています。' },
  { term: 'MS&ADインシュアランスグループ', aliases: ['ms&adインシュアランスグループ', 'ms&ad'], description: '三井住友海上やあいおいニッセイ同和損保などを傘下に持つ、国内有数の保険持株会社グループです。' },
  { term: '三井不動産株式会社', aliases: ['三井不動産', 'mitsui fudosan'], description: 'オフィスビル、商業施設、住宅、ホテル、物流施設など幅広い不動産事業を手がける国内最大級の総合不動産会社です。日本橋再開発を推進しています。' },
  { term: 'ほけんの窓口グループ株式会社', aliases: ['ほけんの窓口'], description: '来店型保険ショップ「ほけんの窓口」を全国展開する保険代理店グループです。複数の保険会社の商品を比較・提案するサービスを提供しています。' },
  { term: '株式会社インターネットイニシアティブ', aliases: ['iij', 'internet initiative japan'], description: '日本初の商用インターネット接続サービスを提供した通信事業者です。法人向けネットワーク、クラウド、セキュリティ等のサービスを展開しています。' },
  { term: 'インフォサイエンス株式会社', aliases: ['infoscience', 'logstorage'], description: '統合ログ管理システム「Logstorage」を開発するIT企業です。統合ログ管理ツール部門で18年連続シェアNo.1を達成しています。' },
  { term: 'ウイングアーク1st株式会社', aliases: ['ウイングアーク1st', 'wingarc1st'], description: '帳票基盤ソリューション「SVF」やBI製品「Dr.Sum」「MotionBoard」を提供するソフトウェア企業です。国内帳票ソフト市場でシェア約68%を持ちます。' },
  { term: 'NTTコミュニケーションズ株式会社', aliases: ['nttコミュニケーションズ株式会社', 'ntt com', 'nttコム'], description: 'NTTグループの長距離・国際通信およびICTソリューション事業を担う通信事業者です。データセンター、クラウド、ネットワーク等の法人向けサービスを提供しています。' },
  { term: '日本アイ・ビー・エム株式会社', aliases: ['日本ibm', 'ibm japan'], description: '米IBMの日本法人です。クラウド、AI、コンサルティング、ITインフラ等の幅広いサービスを提供しています。システムエグゼのソリューション・パートナーです。' },
  { term: '日本オラクル株式会社', aliases: ['oracle japan', '日本オラクル'], description: '米Oracleの日本法人です。データベース、クラウドサービス、ERP等のエンタープライズソリューションを提供しています。システムエグゼはGold Partnerです。' },
  { term: '日本マイクロソフト株式会社', aliases: ['microsoft japan', '日本ms'], description: '米Microsoftの日本法人です。Azure、Microsoft 365、Dynamics等のクラウドサービスやOS・生産性ツールを提供しています。' },
];
