// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: contractLegal (2/3)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: '引当金', aliases: ['provision'], description: '将来発生するかもしれない費用や損失に備えて計上するもの。' },
  { term: '貸倒引当金', aliases: ['bad debt provision'], description: '売掛金を回収できない可能性に備えて計上する引当金。' },
  { term: '受注損失引当金', aliases: ['order loss provision'], description: '受注案件で将来赤字が出そうなときに計上する引当金。' },
  { term: '減損', aliases: ['impairment'], description: '資産価値が大きく下がったときに帳簿価額を下げること。' },
  { term: '資本的支出', aliases: ['capital expenditure'], description: '資産の価値を高めたり長持ちさせたりするための支出。' },
  { term: '修繕費', aliases: ['repair expense'], description: '壊れたものを元の状態に戻すための費用。' },
  { term: '税務申告', aliases: ['tax filing'], description: '税金の計算結果を税務署などに届け出ること。' },
  { term: '売上', aliases: ['revenue'], description: '製品やサービス提供によって得られる収益。' },
  { term: '粗利率', aliases: ['gross profit margin'], description: '売上に対する粗利益の割合。' },
  { term: '営業利益', aliases: ['operating profit'], description: '本業によって得られる利益。' },
  { term: '営業利益率', aliases: ['operating profit margin'], description: '売上に対する営業利益の割合。' },
  { term: 'プロジェクト粗利率', aliases: ['project gross margin'], description: '個別案件の売上に対する粗利益の割合。' },
  { term: 'CAGR', aliases: ['cagr'], description: '複数年にわたる年平均成長率。' },
  { term: 'ROE', aliases: ['roe'], description: '自己資本に対してどれだけ利益を生んだかを見る指標。' },
  { term: 'PBR', aliases: ['pbr'], description: '純資産に対する市場評価を示す指標。' },
  { term: 'ROIC', aliases: ['roic'], description: '投下資本に対する収益性を示す指標。' },
  { term: 'WACC', aliases: ['wacc'], description: '資金調達全体にかかる平均コスト。' },
  { term: '配当性向', aliases: ['dividend payout ratio'], description: '利益のうちどれだけを配当に回したかを示す割合。' },
  { term: '資本政策', aliases: ['capital policy'], description: '成長や株主還元を見据えて資本構成を設計すること。' },
  { term: 'クレジット', aliases: ['credit (billing)'], description: 'サービス利用量を管理するための単位。' },
  { term: '付与', aliases: ['grant'], description: '一定量を利用者へ与えること。' },
  { term: '毎月', aliases: ['monthly'], description: '月ごとに繰り返されること。' },
  { term: '利用', aliases: ['usage'], description: 'サービスや機能を使うこと。' },
  { term: '利用上限', aliases: ['usage limit'], description: '基本枠として使える最大量。' },
  { term: '超過', aliases: ['overage'], description: '定められた上限を超えること。' },
  { term: '従量課金', aliases: ['pay-per-use billing'], description: '使った分だけ料金が発生する方式。' },
  { term: '消化ペース', aliases: ['consumption pace'], description: '利用枠や予算がどの速さで使われているか。' },
  { term: 'お知らせ', aliases: ['notification'], description: '状況や変化を相手に伝えること。' },
  { term: '上位プラン', aliases: ['higher plan'], description: '現在より多くの機能や利用枠を持つ料金プラン。' },
  { term: '切り替え', aliases: ['switching'], description: '別の方式やプランへ変更すること。' },
  { term: '検討', aliases: ['consideration'], description: '状況を踏まえて適切かどうか考えること。' },
  { term: '料金体系', aliases: ['pricing structure'], description: '料金が決まる仕組み全体。' },
  { term: '海外子会社', aliases: ['overseas subsidiary'], description: '親会社が海外で経営している会社。' },
  { term: '現地法人', aliases: ['local corporation'], description: '現地の法律にしたがって設立された会社。' },
  { term: '海外支店', aliases: ['overseas branch'], description: '本社の一部として海外に置かれる拠点。' },
  { term: '駐在員事務所', aliases: ['representative office'], description: '海外で市場調査や情報収集を行うための拠点。' },
  { term: '海外赴任', aliases: ['overseas assignment'], description: '日本で採用された社員が海外拠点で働くこと。' },
  { term: '帰任', aliases: ['repatriation'], description: '海外勤務を終えて元の国や本拠地に戻ること。' },
  { term: '赴任地', aliases: ['assignment location'], description: '海外赴任した人が実際に働く場所。' },
  { term: '帯同家族', aliases: ['accompanying family'], description: '海外赴任する社員と一緒に現地で生活する家族。' },
  { term: '単身赴任', aliases: ['unaccompanied assignment'], description: '家族を残して一人で赴任すること。' },
  { term: '海外基本給', aliases: ['overseas base salary'], description: '海外勤務を前提に設定される給与の基本部分。' },
  { term: '単身赴任手当', aliases: ['unaccompanied assignment allowance'], description: '単身赴任に伴う負担を補うための手当。' },
  { term: '海外赴任手当', aliases: ['overseas assignment allowance'], description: '海外勤務に伴う負担や特殊性を考慮して支給する手当。' },
  { term: 'ハードシップ手当', aliases: ['hardship allowance'], description: '生活環境や治安などの条件が厳しい地域で働く負担を補う手当。' },
  { term: '帯同家族手当', aliases: ['accompanying family allowance'], description: '家族を現地に帯同して生活する場合に支給される手当。' },
  { term: '支度金', aliases: ['relocation preparation payment'], description: '赴任や帰任の準備費用を補うためのお金。' },
  { term: '一時帰国', aliases: ['home leave'], description: '海外赴任中に一時的に母国へ戻ること。' },
  { term: '一時帰国休暇', aliases: ['home leave vacation'], description: '海外赴任者が一時帰国のために取得する休暇。' },
  { term: '特別帰国', aliases: ['emergency return'], description: '病気や家族事情など特別な理由で急いで帰国すること。' },
  { term: '呼び寄せ', aliases: ['family joining later'], description: 'あとから家族を赴任地に来てもらうこと。' },
  { term: '海外出張', aliases: ['overseas business trip'], description: '仕事のために国外へ比較的短期間行くこと。' },
  { term: '宿泊料', aliases: ['accommodation fee'], description: '出張先で宿泊するための費用。' },
  { term: '日当', aliases: ['daily allowance'], description: '出張中の食事代や日用品代などを補うために支給されるお金。' },
  { term: '渡航手続費', aliases: ['travel procedure costs'], description: 'パスポートやビザなど渡航手続きにかかる費用。' },
  { term: '旅行雑費', aliases: ['miscellaneous travel expenses'], description: '出張中に必要となる細かな費用。' },
  { term: '支度料', aliases: ['trip preparation allowance'], description: '出張前の準備に必要な費用を補うためのお金。' },
  { term: '出張経路', aliases: ['travel route'], description: '出張のために移動するルート。' },
  { term: '仮払い', aliases: ['advance payment (karibarai)'], description: '出張前に見込み費用を先に受け取ること。' },
  { term: '精算', aliases: ['expense settlement'], description: '実際に使った金額を確認して過不足を調整すること。' },
  { term: '契約締結', aliases: ['contract execution'], description: '契約内容に正式に合意し効力を持たせること。' },
  { term: '先行着手', aliases: ['advance commencement'], description: '正式契約の前に先に作業を始めること。' },
  { term: '先行発注', aliases: ['advance ordering'], description: '正式契約の前に先に発注すること。' },
  { term: '住居上限額', aliases: ['housing allowance limit'], description: '会社が住居費として負担する上限額。' },
  { term: '家具付き住居', aliases: ['furnished housing'], description: '家具や家電が最初から備え付けられている住居。' },
  { term: '移転貨物', aliases: ['relocation cargo'], description: '赴任や帰任のときに運ぶ家財や荷物。' },
  { term: '残置家財', aliases: ['stored household goods'], description: '赴任中に元の住居などへ残しておく家財。' },
  { term: '留守宅費用', aliases: ['home maintenance costs'], description: '海外赴任中に元の住居を維持・管理するための費用。' },
  { term: '予防接種', aliases: ['vaccination'], description: '感染症予防のために受けるワクチン接種。' },
  { term: '海外旅行傷害保険', aliases: ['overseas travel insurance'], description: '海外出張や赴任中の病気、けが、事故などに備える保険。' },
  { term: '医療費補助', aliases: ['medical expense subsidy'], description: '現地でかかった医療費を会社や保険が補助する仕組み。' },
  { term: '教育費補助', aliases: ['education expense subsidy'], description: '帯同した子どもの学校費用などを補助すること。' },
  { term: '通貨レート', aliases: ['currency exchange rate'], description: '通貨を交換するときの比率。給与や経費精算に影響する。' },
  { term: 'Dr.Sum', aliases: ['dr.sum'], description: '集計・分析用途に強みを持つ国産系データベース／分析基盤製品。' },
  { term: 'MotionBoard', aliases: ['motionboard'], description: 'グラフや地図などを使ってデータを可視化するダッシュボード製品。' },
  { term: 'Datalizer', aliases: ['datalizer'], description: 'Dr.Sum上のデータを帳票や分析画面として利用しやすくするツール。' },
  { term: 'Tableau', aliases: ['tableau'], description: 'データの可視化と探索的分析に強いBIツール。' },
  { term: 'ROLAP', aliases: ['rolap'], description: 'リレーショナルデータベース上で集計・分析を行う方式。' },
  { term: 'MOLAP', aliases: ['molap'], description: '事前集計した多次元データ構造を用いて高速に分析する方式。' },
  { term: '業務フロー', description: '業務の手順、担当、分岐、判断を時系列または流れとして整理したもの。' },
  { term: 'マスタ', description: '商品、顧客、組織など、業務の基準となる共通データ。' },
  { term: 'マスタメンテナンス', description: 'マスタデータを登録、変更、削除して最新状態に保つ作業または機能。' },
  { term: '前例検索', description: '過去の似た事例を探して活用する検索。' },
  { term: 'As-Is', aliases: ['as-is', '現状', '現行', 'as is', '現状業務'], description: '現状のビジネスプロセスや業務フローのこと。「現状」とも呼ばれる。業務改善では現状（As-Is）を把握してから、あるべき姿（To-Be）を定義する。' },
  { term: 'To-Be', aliases: ['to-be', 'あるべき姿', 'to be', '改善後'], description: '改善後の目指すべき姿・業務フローのこと。「あるべき姿」とも呼ばれる。現状（As-Is）の課題を解決した理想的な状態を定義する。' },
  { term: '業務改善', aliases: ['業務効率化', 'process improvement', 'bpi'], description: '業務の効率化・品質向上・コスト削減を目的として、現行の業務プロセスを見直し改善する取り組み。システム化、自動化、手順の標準化などが手段として使われる。' },
  { term: 'システム化対象', aliases: ['システム化範囲'], description: '業務改善においてシステムで自動化・効率化する業務の範囲のこと。全ての業務をシステム化するのではなく、費用対効果の高いものを対象として選定する。' },
  { term: '自動化', aliases: ['automation', 'オートメーション'], description: '手作業で行っていた業務をシステムやロボット（RPA）で自動的に処理すること。反復的・定型的な業務を自動化することで、人的ミスの削減と業務効率向上を図る。' },
  { term: '定着化', aliases: ['浸透', '定着', 'change management'], description: '新しいシステムや業務プロセスを導入した後、利用者が継続的に使い続けられるように定着させること。研修・マニュアル整備・サポート体制などにより促進する。' },
  { term: '費用対効果', aliases: ['コスト対効果', 'cost-effectiveness'], description: '投資した費用に対してどれだけの効果・利益が得られるかの比率。「○○万円かけて○○時間削減できる」のように示す。プロジェクト承認の重要な判断材料になる。' },
  { term: '製造業', description: 'モノを生産する産業分野。IT導入の主要対象業界のひとつ。' },
  { term: '現場力', description: '現場で業務を遂行・改善する力。ITシステム導入後の定着にも影響する。' },
  { term: '生産', description: '製品を作る活動。製造業の中核業務であり、生産計画や在庫管理と密接に関わる。' },
  { term: '在庫', description: '保管中の原材料・仕掛品・製品。過剰・欠品どちらもコストやリスクにつながる。' },
  { term: '生産計画', description: '何をいつどれだけ作るかの計画。需要予測と生産能力を踏まえて立案する。' },
  { term: '在庫管理', description: '在庫数量や状態を管理すること。在庫差異や欠品を防ぎ、適正在庫を維持する。' },
  { term: '在庫差異', description: '実在庫と帳簿在庫のずれ。棚卸作業の負担増加や欠品・過剰在庫の原因になる。' },
  { term: '欠品', description: '必要な在庫が不足している状態。納期遅延や機会損失に直結する。' },
  { term: '品質情報', description: '不良・検査結果・原因など品質関連データ。原因分析や再発防止に活用する。' },
  { term: '現場', description: '実際に業務や生産を行う場所・部門。IT導入では現場の使いやすさが定着を左右する。' },
  { term: '現場改善', description: '現場業務をより良くする取り組み。小さな改善の積み重ねが大きな成果になる。' },
  { term: '実績収集', description: '実際の作業結果や数量を集めること。生産・在庫・品質の管理基盤となる。' },
  { term: '出荷', description: '製品を顧客へ発送すること。納期遵守率の管理対象となる業務。' },
  { term: '余剰在庫', description: '必要以上に持っている在庫。資金固定化やスペース圧迫の原因になる。' },
  { term: '不良要因分析', description: '不良が起きた原因を分析すること。品質改善と再発防止の出発点。' },
  { term: '在庫最適化', description: '過不足のない在庫状態にすること。欠品・余剰在庫の両方を抑える取り組み。' },
  { term: '業務システム', description: '受発注、会計、在庫、人事など、組織の業務を支えるために使う情報システムです。正確性、権限管理、監査、運用継続性が重視されます。' },
  { term: 'エコシステム', aliases: ['ecosystem'], description: 'IT業界において相互依存・協力関係にある企業・製品・コミュニティの生態系。プラットフォームを中心に形成される。' },
  { term: 'ニッチ', aliases: ['niche'], description: '市場や生態系における特定の隙間・専門領域。競合が少ない特定セグメントを指す。' },
  { term: '進化論', description: 'IT業界の変化をダーウィン進化論になぞらえて説明する概念。環境適応できる技術・企業が生き残るという考え方。' },
  { term: 'オープンコア', aliases: ['open core'], description: 'コア機能をオープンソースで公開し追加機能を有料提供するビジネスモデル。' },
  { term: 'キャズム理論', aliases: ['chasm theory'], description: 'Geoffrey Mooreが提唱した技術普及モデル。アーリーアダプターとアーリーマジョリティの間に存在する普及の断絶を表す。' },
  { term: '革新者', aliases: ['イノベーター'], description: 'イノベーター理論における技術の最初期採用者。全体の約2.5%を占めリスクを厭わず新技術を試みる。' },
  { term: '早期採用者', aliases: ['アーリーアダプター'], description: 'イノベーター理論における2番目の採用層。全体の約13.5%。オピニオンリーダーとして機能する。' },
  { term: '実利主義者', aliases: ['アーリーマジョリティ'], description: 'キャズム理論におけるアーリーマジョリティ。実用性・実績を重視してから採用する層（約34%）。' },
  { term: '消極的消費者', aliases: ['レイトマジョリティ'], description: 'キャズム理論におけるレイトマジョリティ。周囲に追随して採用する保守的な層（約34%）。' },
  { term: '保守的消費者', aliases: ['ラガード'], description: 'キャズム理論におけるラガード。最後まで新技術を拒否するか採用が極めて遅い層（約16%）。' },
  { term: 'ガートナーハイプサイクル', aliases: ['ハイプサイクル', 'gartner hype cycle', 'hype cycle'], description: 'Gartnerが提唱する新技術の期待と普及の過程を示すモデル。5段階のフェーズで技術成熟度を表す。' },
  { term: '黎明期', description: 'ガートナーハイプサイクルの第1フェーズ。技術が登場し初期の関心が生まれる段階。' },
  { term: '過度な期待のピーク期', description: 'ガートナーハイプサイクルの第2フェーズ。過大な期待が集まりメディア露出が最大化する段階。' },
  { term: '幻滅期', aliases: ['trough of disillusionment'], description: 'ガートナーハイプサイクルの第3フェーズ。期待が外れ関心が急速に失われる段階。' },
  { term: '啓蒙活動期', description: 'ガートナーハイプサイクルの第4フェーズ。技術の実際の価値が理解され始め普及が進む段階。' },
  { term: '生産性の安定期', description: 'ガートナーハイプサイクルの第5フェーズ。技術が主流として定着し生産性が安定する段階。' },
  { term: 'クリティカルマス', aliases: ['critical mass'], description: '技術・製品の普及が自律的に加速し始める臨界点の採用者数または普及率。' },
  { term: '市場調査', aliases: ['market research'], description: '対象市場の規模・競合・顧客ニーズを調査し事業機会を評価する活動。' },
  { term: '事例調査', aliases: ['case study research'], description: '類似プロジェクトや業界の先行事例を収集・分析してベストプラクティスや失敗要因を学ぶ活動。' },
  { term: '顧客満足度', aliases: ['cs', 'csat', 'customer satisfaction'], description: '顧客がサービス・製品に対して感じる満足の度合い。NPS・CSATなどの指標で計測する。' },
  { term: '真なる課題', description: '表面的な要望の背後にある本質的な問題。コンサルティングでは要望の奥にある真の課題を特定することが重要。' },
  { term: '差別化', aliases: ['differentiation'], description: '競合他社との比較において自社・製品・サービスの優位性を明確にすること。' },
  { term: 'ソリューション設計', aliases: ['solution design'], description: '顧客課題を解決するためのシステム・サービス・プロセスの組み合わせを設計する活動。' },
  { term: 'ゼロベース思考', aliases: ['zero-based thinking'], description: '既存の前提や制約を取り払いゼロから問題を再定義・解決策を考える思考法。' },
  { term: 'コンセプト', aliases: ['concept'], description: '製品・サービス・システムの核となる基本的なアイデアや方向性を言語化したもの。' },
  { term: 'ストーリー', aliases: ['story'], description: 'ユーザーの行動・感情・文脈を物語形式で記述し要件やデザインを説明するための手法。' },
  { term: 'コンサルティング', aliases: ['consulting'], description: '専門知識を持つ第三者が組織の課題解決や戦略立案を支援する専門サービス。' },
  { term: 'グレイヘアアプローチ', description: '豊富な経験・実績に基づいてベストプラクティスや定石を提供するコンサルティングスタイル。' },
  { term: 'ファクトアプローチ', description: 'データ・事実・分析に基づいて客観的に課題と解決策を提示するコンサルティングスタイル。' },
  { term: 'コンセプチュアルスキル', aliases: ['conceptual skill'], description: '複雑な状況を抽象化し本質を見抜いて概念化する能力。管理職・コンサルタントに必要なスキル。' },
  { term: 'ロジックツリー', aliases: ['logic tree'], description: '問題や原因を論理的に分解して階層的に整理する思考ツール。MECEで展開することが基本。' },
  { term: 'MECE', aliases: ['mece'], description: 'Mutually Exclusive, Collectively Exhaustiveの略。重複なく漏れなく情報や選択肢を整理する思考原則。' },
  { term: '戦略思考', description: '長期的な目標達成のために資源配分・競合優位・環境変化を考慮して計画する思考法。' },
  { term: '仮説思考', description: '限られた情報で仮説を立て検証しながら問題解決を進める効率的な思考アプローチ。' },
  { term: 'PEST分析', aliases: ['pest分析', 'pest analysis'], description: 'Political・Economic・Social・Technologicalの4要素で外部環境を分析するフレームワーク。' },
  { term: 'SWOT分析', aliases: ['swot分析', 'swot analysis'], description: 'Strengths・Weaknesses・Opportunities・Threatsで組織の内外環境を分析する経営フレームワーク。' },
  { term: '3C分析', aliases: ['3c分析', '3c analysis'], description: 'Customer・Competitor・Companyの3要素で事業環境を分析するフレームワーク。' },
  { term: '4P分析', aliases: ['4p分析', '4p analysis'], description: 'Product・Price・Place・Promotionの4要素でマーケティングミックスを分析するフレームワーク。' },
  { term: '5F分析', aliases: ['5f分析', '5forces分析'], description: 'Porterの5つの競争力（新規参入・代替品・買い手・売り手・競合）で業界構造を分析するフレームワーク。' },
  { term: '4C分析', aliases: ['4c分析', '4c analysis'], description: 'Customer Value・Cost・Convenience・Communicationの4要素で顧客視点のマーケティングを分析するフレームワーク。' },
  { term: 'BSC分析', aliases: ['bsc分析', 'bsc', 'バランスト・スコアカード', 'bsc analysis', 'balanced scorecard'], description: 'Balanced Scorecardの略。財務・顧客・業務プロセス・学習成長の4視点で組織戦略を評価するフレームワーク。' },
  { term: '進化論（IT）', aliases: ['進化論（it）', 'evolutionary theory'], description: 'ダーウィン進化論を類比にIT業界の変化を説明する概念で、環境に適応した技術・企業が生き残ると主張します。' },
  { term: 'プラグマティスト', aliases: ['pragmatists', 'early majority'], description: 'キャズム理論における前期多数派で、実用的価値と実績を確認してから技術を採用する層です（約34%）。' },
  { term: 'スケプティクス', aliases: ['skeptics', 'late majority'], description: 'キャズム理論における後期多数派で、周囲に追随して保守的に採用する層です（約34%）。' },
  { term: 'テクノロジートリガー', aliases: ['technology trigger'], description: 'ガートナーハイプサイクルの第1フェーズで、技術が登場し初期関心が高まる段階です。' },
  { term: '過度な期待のピーク', aliases: ['peak of inflated expectations'], description: 'ガートナーハイプサイクルの第2フェーズで、過剰な期待が集まりメディア露出がピークに達する段階です。' },
  { term: '啓発の坂', aliases: ['slope of enlightenment'], description: 'ガートナーハイプサイクルの第4フェーズで、技術の真の価値が理解され採用が進む段階です。' },
  { term: '生産性の台地', aliases: ['plateau of productivity'], description: 'ガートナーハイプサイクルの第5フェーズで、技術が主流となり生産性が安定する段階です。' },
  { term: '真の問題', aliases: ['true problem'], description: '表面的な要望の背後にある本質的な問題のことです。コンサルティングでは表明された要求の裏にある真の問題を特定することが重要です。' },
  { term: 'グレーヘアアプローチ', aliases: ['gray hair approach'], description: '豊富な経験と実績に基づいてベストプラクティスと確立されたソリューションを提供するコンサルティングスタイルです。' },
  { term: 'ファクトベースアプローチ', aliases: ['fact-based approach'], description: 'データ・事実・分析に基づき問題と解決策を客観的に提示するコンサルティングスタイルです。' },
  { term: '戦略的思考', aliases: ['strategic thinking'], description: 'リソース配分・競争優位・環境変化を考慮しながら長期的な目標達成を計画する思考アプローチです。' },
  { term: '仮説駆動思考', aliases: ['hypothesis-driven thinking'], description: '限られた情報で仮説を立て、検証しながら進める効率的な問題解決アプローチです。' },
  { term: '5フォース分析', aliases: ['5 forces analysis', '5f analysis'], description: '新規参入・代替品・買い手・売り手・業界内競合の5つの競争力で業界構造を分析するポーターのフレームワークです。' },
  { term: '要望', description: 'ステークホルダーが持つ望ましい状態や機能に関する意見・希望。要件定義の入力となる。' },
  { term: '2020年民法改正', description: '2020年施行の民法改正。請負・委任・瑕疵担保責任が見直されソフトウェア開発契約に影響。' },
  { term: 'jargon', description: '特定の専門分野や組織内で使われる専門用語・業界用語。ユーザーとの共通理解形成で重要。' },
  { term: '非機能要求', description: 'システムの品質・性能・信頼性・セキュリティ・保守性など機能以外の要求。' },
  { term: '非機能要件定義', description: '非機能要求を定量的・定性的に定義しシステム要件として確定させる活動。' },
  { term: '非機能要求指標', description: '非機能要求を定量的に表現するための測定可能な指標。応答時間・可用率などが代表例。' },
  { term: '非機能要求グレード', description: '非機能要求をA〜Eなどのグレードで段階的に表現するアプローチ。比較・合意形成を容易にする。' },
  { term: '非機能要求グレード活用シート', description: '非機能要求グレードを記入・共有するための標準的なワークシート。' },
  { term: '複数の非機能要求セット', description: 'システムの機能領域ごとに異なる非機能要求を定義し複数セットとして管理するアプローチ。' },
  { term: 'ITガバナンス要求', aliases: ['itガバナンス要求'], description: '情報システムの統制・管理・方針に関する組織レベルの要求。コンプライアンスやリスク管理を含む。' },
  { term: 'サービスレベル', description: 'ITサービスの品質・可用性・性能などを定量的に定めた合意事項。SLAとして文書化される。' },
  { term: '要件のレベル定義', description: '要件をビジネス・ユーザー・システム・実装などの階層ごとに定義する枠組み。' },
  { term: 'グレード表', description: '非機能要求のグレードをまとめた一覧表。各特性の評価基準と対応するグレードを定義する。' },
  { term: '派遣契約', aliases: ['staffing contract'], description: '労働者派遣法に基づき派遣元が派遣先に労働者を派遣する契約形態。指揮命令権は派遣先が持つ。' },
  { term: 'SES契約', aliases: ['ses契約', 'ses contract'], description: 'System Engineering Serviceの略。エンジニアの技術力を提供する準委任契約の一形態。' },
  { term: '契約不適合', aliases: ['non-conformity'], description: '2020年民法改正後の瑕疵担保責任に替わる概念。給付された成果物が契約内容に適合しない状態。' },
  { term: '検収印', aliases: ['acceptance stamp'], description: '発注者が成果物の検収完了を示す承認印。これにより代金支払い義務が確定する。' },
  { term: 'ビジネスルール', aliases: ['業務ルール', 'business rule'], description: '業務において守るべき制約・計算式・判断基準。ドメインモデルに組み込まれる。' },
  { term: 'ドメイン知識', aliases: ['domain knowledge'], description: '特定の業務領域に関する専門的な知識・ルール・慣習。要件定義やドメインモデリングの基盤となる。' },
  { term: '業務知識', aliases: ['business knowledge'], description: '特定の業界・組織の業務プロセス・ルール・慣習に関する知識。' },
  { term: '事業要求', description: '経営・ビジネス観点からシステムに求める目標・成果。ビジネスケースで定義される。' },
  { term: '業務要求', aliases: ['operational requirements'], description: '業務担当者が業務遂行のためにシステムに期待する機能・サービス。業務要件の源泉となる。' },
  { term: '真なる目的', aliases: ['true goal'], description: 'ステークホルダーの表面的な要望の背後にある本当の達成目標。要件定義で必ず明確化すべき事項。' },
  { term: '顧客組織分析', aliases: ['customer organization analysis'], description: '顧客企業の組織構造・意思決定プロセス・ステークホルダーの影響力を分析する活動。' },
  { term: '少数精鋭', description: '少ない人数でも高いスキルを持つメンバーを集め、効率よく成果を出すチームや組織の考え方。人海戦術と対比される。' },
  { term: '人海戦術', description: '多くの人員を投入することで作業量をこなすアプローチ。品質より速度・量を重視する場合に使われるが、コミュニケーションコストも増大する。' },
  { term: '未経験', description: '特定の業務や技術に対して実務経験がない状態。採用文脈では「未経験歓迎」として使われ、スキルより意欲・適性を重視する場合に多い。' },
  { term: '顧客対応', description: '顧客からの問い合わせ・クレーム・要望に対して適切に回答・調整・対処すること。エンジニアが直接対応する場合は技術的な説明能力も求められる。' },
  { term: '目次', description: '提案書に何をどの順序で記載するかを示した構成一覧。読み手が全体像を把握しやすくするために冒頭に置かれる。' },
  { term: '章', description: '提案書を大きく区切る単位。「背景」「提案内容」「費用」などのテーマごとに設けられ、論理的な流れを作る。' },
  { term: '項目', description: '章の中で扱う内容の単位。章をさらに細分化し、具体的なトピックや詳細を整理するために使われる。' },
  { term: '顧客', aliases: ['クライアント'], description: '提案を受ける企業、組織、または担当者。提案書における「顧客」はすべての記述の主体であり、課題・要望・意思決定の主役となる。' },
  { term: '背景', description: '提案が必要になった事情や経緯。市場環境の変化・業務課題・経営方針など、提案を行う根拠となる文脈を示す。' },
  { term: '現状課題', description: '現在の業務やシステムにある問題点。提案書では背景より具体的に、解決すべき課題を明示するために記載する。' },
  { term: '提案コンセプト', description: '提案全体を貫く基本的な考え方や方向性。個別機能の説明に入る前に、何をめざしてこの提案をしているかを一言で示す。' },
  { term: '要件定義書', description: '要件定義の結果をまとめた文書。機能要件・非機能要件・制約条件などを記述し、開発の基準となる。' },
  { term: '操作マニュアル', aliases: ['利用者マニュアル'], description: '利用者がシステムを使うための手順書。機能ごとの操作手順・注意事項をスクリーンショット付きで説明する。' },
  { term: '問い合わせ対応', aliases: ['サポート対応', 'ヘルプデスク'], description: '利用者からの質問や依頼に対して回答、調査、案内を行うこと。保守契約の範囲として定義され、対応時間・応答時間がSLAに含まれる。' },
  { term: '留意事項', aliases: ['注意事項'], description: '提案を理解するうえで事前に認識しておくべき注意点。前提条件・適用除外・制約などを顧客に明示することで認識齟齬を防ぐ。' },
  { term: '会社概要', description: '提案会社の基本情報をまとめた説明。設立年・資本金・従業員数・事業内容など、信頼性を示す情報が含まれる。' },
  { term: '実績', aliases: ['導入実績', '事例'], description: '過去に実施した類似案件や成果の記録。提案書に実績を記載することで、信頼性や技術力を裏付ける根拠となる。' },
  { term: 'システム開発提案書', aliases: ['rfp対応提案書'], description: 'システムの新規開発、再構築、改修を対象にした提案書。背景・課題・提案内容・スケジュール・費用などを体系的にまとめた正式な提案文書。' },
  { term: '新規テナント契約', aliases: ['new tenant contract', 'new lease agreement'], description: '新しい物件に入居するテナントとの契約業務全体。候補テナントの選定・条件交渉・契約締結・引渡しまでの一連のプロセスを指す。リーシング部門が主導し、契約管理システムで進捗をステータス管理する。' },
  { term: '新規物件', aliases: ['new property', 'new premises'], description: 'これから開業または運営開始する物件。既存物件と異なり区画構成・条件・テナントが未確定の要素を含む。新規物件ではリーシング計画の策定からテナント誘致・契約締結まで一から進める必要がある。' },
  { term: '新規テナント', aliases: ['new tenant', 'prospective tenant'], description: '新たに入居候補となるテナント。既存テナントと区別し、与信確認・条件交渉・契約締結の対象となる。新規テナントの誘致はリーシング活動の核心であり、業種区分・出店条件・区画情報が交渉の基礎となる。' },
  { term: 'リーシング', aliases: ['leasing', 'tenant leasing'], description: 'テナントを誘致し、入居条件を調整する業務。空き区画の埋め戻しを目的に、候補テナントへの物件打診・区画提示・条件交渉・契約締結までを担う。リーシング担当者は物件の魅力を最大化するテナントミックスを設計する。' },
  { term: '物件打診', aliases: ['property inquiry', 'site proposal'], description: '候補テナントに対して物件や入居可能性を打診すること。リーシング活動の初期ステップで、物件の概要・区画・賃貸条件を提示し、テナントの興味・意向を確認する。打診後にテナントの反応に応じて区画提示・条件交渉へ進む。' },
  { term: '区画', aliases: ['tenancy unit'], description: 'テナントが入居する区切られたスペース。区画番号・面積・位置・賃料単価などで管理され、テナントとの契約単位となる。複数区画をまたいで契約する場合は区画またぎとして扱う。' },
  { term: '区画提示', aliases: ['unit proposal', 'space proposal'], description: 'テナント候補に対して入居候補の区画を示すこと。区画図・面積・位置・賃料などの区画情報をまとめて提示し、テナントの意向や交渉の出発点とする。物件打診に続くリーシングプロセスの重要なステップ。' },
  { term: '区画情報', aliases: ['unit information', 'space information'], description: '区画番号、位置、面積など、区画を特定するための情報。テナント提示・契約管理・進捗管理で参照される基礎データ。区画情報は区画情報登録によってシステムに登録され、リーシング・契約業務の基盤となる。' },
  { term: '区画情報登録', aliases: ['unit information registration', 'space registration'], description: '契約対象または候補となる区画情報をシステムへ登録すること。区画番号・面積・位置・賃料などを入力し、リーシング・契約管理の基礎データとして活用できる状態にする。未登録区画は手入力対応で対処する。' },
  { term: '区画変更', aliases: ['unit change', 'space change'], description: '交渉または契約の途中で対象区画が変わること。テナントの要望・物件側の都合・他テナントとの兼ね合いにより契約区画が変更される。区画変更時は契約書・出店条件合意確認書の更新と関連書類の再調整が必要。' },
  { term: '区画またぎ', aliases: ['multi-unit tenancy', 'cross-unit lease'], description: '契約対象が複数の区画にまたがる状態。隣接する複数区画を一つのテナントが借りる場合に発生し、各区画の情報を統合して契約管理する必要がある。手入力対応や特記事項で対応するケースも多い。' },
  { term: '未登録区画', aliases: ['unregistered unit', 'unregistered space'], description: 'まだ基礎データに登録されていない区画。新規物件や増床区画で発生しやすく、契約管理システムに区画情報が存在しない状態。手入力対応でデータを補完するか、区画情報登録を先行して実施する。' },
  { term: '手入力対応', aliases: ['manual entry', 'manual input handling'], description: '標準登録できない区画や条件を個別入力で扱うこと。システムで自動処理できない例外的な区画・条件・書類を担当者が手動で入力・管理する。未登録区画・非定型契約・区画またぎなどで発生する。' },
  { term: '店舗区画契約', aliases: ['store unit contract', 'retail unit lease'], description: '店舗と区画を結び付けて管理する契約単位。テナントである店舗と、入居する区画の組み合わせを一つの契約として管理する。一店舗が複数区画を契約する場合（区画またぎ）も一契約として扱うことが多い。' },
  { term: '出店条件', aliases: ['leasing terms', 'tenancy conditions', 'store opening conditions'], description: 'テナントが入居・営業する際の賃貸条件や営業条件の総称。賃料・保証金（敷金）・売上歩合・業種制限・営業時間・改装条件・原状復旧義務などを含む。出店条件合意確認書にまとめ、テナントとの合意の基礎とする。' },
  { term: '出店条件合意確認書', aliases: ['leasing terms agreement letter', 'store condition confirmation'], description: '出店条件の内容と合意事項を確認するための書類。契約前の条件整理の中心となり、賃料・保証金・業種・原状復旧条件などを記載して双方が確認・署名する。これをもとに正式な契約書が作成される。' },
  { term: '出店条件合意確認書案', aliases: ['leasing terms draft', 'draft condition confirmation'], description: '出店条件合意確認書のドラフト版。条件調整中の確認に用い、交渉過程で内容が修正される。案文合意が得られた後に正式な出店条件合意確認書として仕上げる。' },
  { term: '定期借家事前説明', aliases: ['fixed-term lease pre-explanation', 'fixed-term tenancy disclosure'], description: '定期借家契約に先立って行う法的説明手続き。借地借家法第38条に基づき、契約締結前に定期借家の特性（更新がないこと等）を書面と口頭で説明する義務がある。説明を省略すると定期借家としての効力が失われる場合がある。' },
  { term: '定期借家事前説明書', aliases: ['fixed-term lease disclosure document', 'fixed-term tenancy explanation form'], description: '定期借家契約の事前説明に用いる書類。借地借家法に基づき、定期借家の仕組み・契約期間の満了・更新不可などの重要事項を記載する。テナントへの交付と説明が義務付けられており、説明後にテナントが署名・受領する。' },
  { term: '敷金', aliases: ['security deposit', 'deposit'], description: '賃貸借契約に関連して預け入れる保証金。賃料不払いや原状復旧費用の担保として貸主が受け取る。契約終了時に未払いや損害がなければ返還される。商業施設では保証金・敷金の名称や金額設定が住宅賃貸と異なることが多い。' },
  { term: '敷金等請求書', aliases: ['security deposit invoice', 'deposit request'], description: '敷金や関連費用（礼金・手数料等）を請求するための書類。契約締結後、入居前までに発行してテナントへ送付し、指定期日までの入金を求める。入金確認後に入金伝票を作成して会計処理する。' },
  { term: '取扱いブランド・品目明細表', aliases: ['brand and product list', 'merchandise detail sheet'], description: '店舗で取り扱うブランドや品目を明示する資料。商業施設との契約において、テナントが販売・提供する商品・サービスの範囲を示す。施設側の業種管理・テナントミックス設計のために使用され、契約添付資料となることが多い。' },
  { term: '営業管理規則抜粋', aliases: ['operations rule excerpt', 'facility rules excerpt'], description: '施設運営上の規則のうち、入居者に関係する部分を抜き出した資料。営業時間・ゴミ処理・共用部の使い方・搬入搬出ルールなど、テナントが守るべき施設ルールを示す。契約締結時に出店条件合意確認書と合わせて交付される。' },
  { term: '売上預り金', aliases: ['sales deposit', 'retained sales'], description: '売上金の一部または全部を一定条件のもとで預かる仕組み、またはその金銭。商業施設では売上歩合家賃の清算に使われ、売上報告書に基づいて施設側がテナントから預かり、賃料等との差額を精算する。' },
  { term: '出店料', aliases: ['entry fee', 'tenant fee'], description: '出店に関連して発生する費用。施設への入居に際してテナントが支払う初期費用の一種で、賃貸保証金・内装工事費・申請費用などとは別に定められる。施設によって定義と金額は異なる。' },
  { term: '売上預り金および出店料・経費等の取扱い', aliases: ['sales deposit and fee handling'], description: '売上預り金、出店料、関連経費の扱いを定めた資料。金額の算定方法・支払いタイミング・精算ルール・未払い時の対応などを明示し、テナントとの契約に付属する重要書類として使用される。' },
  { term: '原状復旧', aliases: ['restoration to original condition', 'reinstatement'], description: '退去時に区画や設備を契約上定められた状態へ戻すこと。テナントが施工した内装・設備を撤去し、契約書や原状復旧工事仕様表に定める状態に戻す義務を指す。費用負担の範囲は原状復旧費用定額制の採否によって異なる。' },
  { term: '原状復旧工事仕様表', aliases: ['restoration work specification', 'reinstatement specification sheet'], description: '原状復旧工事の内容や仕様を整理した資料。どの部位をどのような状態に戻すかを詳細に規定し、テナントの退去工事の基準となる。見積り取得・施工確認・完了検査の基準書としても使われる。' },
  { term: '原状復旧費用定額制', aliases: ['fixed restoration cost', 'flat-rate restoration'], description: '原状復旧費用を定額方式で扱う契約条件。実際の工事費に関わらず、契約で定めた定額を退去時に支払うことで原状復旧義務を完結させる。テナント・施設双方にとって費用予測が容易になるメリットがある。' },
  { term: '原状復旧費用定額制適用通知書', aliases: ['fixed restoration cost notice'], description: '原状復旧費用定額制の適用有無を通知する書類。当該テナントの契約に定額制が適用されるかどうかを明記し、退去時の費用精算の前提条件を事前に確認・共有するために使用する。' },
  { term: '条文選択', aliases: ['clause selection', 'article selection'], description: '契約条件に応じて適用する条文を選ぶこと。標準契約書に複数の選択肢条文が設けられており、テナントごとの条件（定期借家か普通借家か、原状復旧の定額制の適否など）に合った条文を選択して適用する。' },
  { term: '特記削除', aliases: ['special note removal', 'clause deletion'], description: '標準条項の一部を特記事項などで削除すること。テナントの条件・物件の特性・交渉結果によって標準条文の一部が不要・不適切となる場合に、対象条文を削除または無効化する処理。契約書加工の一形態。' },
  { term: '引渡日', aliases: ['handover date', 'delivery date', 'possession date'], description: '物件や区画を契約相手へ引き渡す日。テナントへの鍵渡し・内装工事開始の起算日となることが多く、出店条件合意確認書や契約書に明記される。引渡日の変更は引渡日変更通知で関係者へ周知する。' },
  { term: '営業開始日', aliases: ['opening date', 'store opening date', 'commencement date'], description: '店舗が営業を開始する日。引渡日から内装工事・什器搬入・スタッフ採用を経て決定される。施設の共通オープン日やグランドオープンに合わせることも多く、出店条件合意確認書に目標日として記載される。' },
  { term: '引渡日変更通知', aliases: ['handover date change notice'], description: '引渡日の変更を知らせる通知。工事遅延・行政手続きの遅れ・テナント側の事情などにより引渡日が変更される場合、施設側またはテナント側が関係者へ変更内容・変更後日程を正式に通知する。' },
  { term: '営業開始日変更通知', aliases: ['opening date change notice'], description: '営業開始日の変更を知らせる通知。内装工事の遅延・テナントの準備状況・引渡日変更などを受けて営業開始日が変更される場合に発行する。施設の運営計画・他テナントとのスケジュール調整にも影響するため速やかな通知が必要。' },
  { term: '引渡日・営業開始日変更確定通知', aliases: ['handover and opening date confirmation notice'], description: '引渡日や営業開始日に関する変更内容および確定内容を知らせる通知。変更の調整が完了し、新しい日程が確定したことをテナント・施設・関係部署へ正式に通知する書類。' },
  { term: '業種区分', aliases: ['business category', 'tenant category', 'store category'], description: '入居者の事業内容を分類する区分。商業施設ではテナントミックスを管理するために、ファッション・飲食・サービス・食品などの業種区分でテナントを分類する。業種制限は出店条件に含まれ、施設の競合管理に使われる。' },
  { term: '経理規程', aliases: ['accounting regulations', 'internal accounting rules'], description: '会社の経理業務全般に関するルールをまとめた社内規程。経費精算の手続き・決裁権限・帳簿管理・証憑の保存年限などを明文化している。経理部門が適正な会計処理を行うための基礎となる文書であり、定期的な見直しが推奨される。' },
  { term: '会計帳簿', aliases: ['accounting books', 'financial records'], description: '会社の取引・資産・負債を記録するための帳簿の総称。総勘定元帳・補助元帳・現金出納帳・売掛帳・買掛帳などが含まれる。会社法および税法により一定期間（原則10年）の保存が義務付けられている。' },
  { term: '総勘定元帳', aliases: ['general ledger', 'master ledger book'], description: '会社のすべての取引を勘定科目ごとにまとめて記入する中心的な帳簿。仕訳帳に記録された仕訳をすべて転記し、各科目の残高を管理する。決算書作成の基礎資料となり、残高試算表の作成に使用される。' },
  { term: '補助元帳', aliases: ['subsidiary ledger', 'detail ledger book'], description: '総勘定元帳の特定勘定科目（売掛金・買掛金・固定資産など）の明細を管理する帳簿。取引先ごと・品目ごとに詳細情報を把握するために使用する。総勘定元帳の残高と補助元帳の合計が一致しているか定期的に照合する。' },
  { term: '残高試算表', aliases: ['trial balance sheet', 'balance trial table'], description: '全勘定科目の借方合計・貸方合計と残高を一覧にした表。決算前に帳簿の整合性を確認するために作成し、借方合計と貸方合計が一致することで記帳の正確性を検証する。合計試算表・残高試算表・合計残高試算表の3種類がある。' },
  { term: '勘定科目', aliases: ['account item', 'chart of accounts entry'], description: '取引内容を種類ごとに分類するための名称。現金・売上高・買掛金・減価償却費・未払費用など、会計処理を行う際の基本単位となる。会社ごとに勘定科目一覧（科目体系）を定めて使用する。' },
  { term: '仕訳', aliases: ['journal entry', 'double-entry bookkeeping record'], description: '取引を借方・貸方の勘定科目に割り当てて会計帳簿に記録すること。複式簿記の基本的な記録方式であり、借方と貸方の金額は必ず一致する。仕訳帳に記録した後、総勘定元帳に転記して残高を管理する。' },
  { term: '証憑', aliases: ['supporting document', 'source document'], description: '請求書・領収証・契約書・納品書など、取引の事実を証明する書類の総称。仕訳を行う際の根拠資料となり、税法・会社法に基づいて一定期間（原則7〜10年）の保管が義務付けられる。電子帳簿保存法に対応した電子保存も認められている。' },
  { term: '有形固定資産', aliases: ['tangible fixed assets', 'property plant and equipment'], description: '建物・機械設備・車両・土地など、物理的な形を持ち長期にわたって使用する資産。取得価額で計上し、土地を除き法定耐用年数に基づいて減価償却を行う。貸借対照表の固定資産の部に記載される。' },
];
