// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: contractLegal (1/3)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // finance (86), business-analysis (81), hr (70), business (62), business-process (48), international-business (48), sales-engineering (47), labor (38), real-estate (38), accounting (31), legal (23), trading (16), manufacturing (16), Corporate Operations (13), billing (13), Business Strategy (9), Data Analytics (9), business-improvement (7), bi (6), sustainability (6), Sales (4), corporate-management (4), marketing (3), Marketing (2), business-strategy (1)
  { term: '遅延読み込み', description: '【金融】必要になるまでデータや資産の読み込みを後回しにする手法です。 【フロントエンド】画面に必要になるまでデータや画像を読み込まない方法です。初期表示を軽くしやすくなります。 【フロントエンド】今すぐ必要でない機能や資産を後から読み込むことです。初回体験の軽量化に有効です。' },
  { term: 'KGI', aliases: ['kgi'], description: '最終的な目標達成を測る指標です。売上、利益、継続率のような上位成果が該当します。' },
  { term: '導入効果', description: 'システム導入によって得られる価値です。時間削減、ミス削減、売上向上、可視化向上などを定量と定性の両面で捉えます。' },
  { term: 'リーガルホールド', aliases: ['legal hold'], description: '訴訟や監査への備えとしてデータ削除を停止することです。通常の保持ポリシーと衝突する場合があり、ガバナンスが必要です。' },
  { term: '保持期間', aliases: ['retention period'], description: '文書やログをどのくらいの期間保存するかのことです。業務要件・法的義務・監査要件が交差する重要な事項です。' },
  { term: '目的制限', aliases: ['purpose limitation'], description: '収集した情報をどのような目的に使用するかを明確にする原則です。個人データ保護において特に重要であり、明示した目的以外での利用は問題となります。' },
  { term: 'データ主権', aliases: ['data sovereignty'], description: 'データに対して誰が主権と管理権を持つかという概念です。クラウドやAI利用の文脈で特に強調されます。' },
  { term: 'インシデント報告義務', aliases: ['incident reporting obligation'], description: 'データ漏えいやインシデントが発生した際に定められた期間内に報告する義務のことです。契約上も厳格に定められていることが多いです。' },
  { term: '是正措置要求', aliases: ['corrective action request', 'car'], description: '不備や違反に対して相手方に対応を求めることです。監査やベンダー管理の実践に登場します。' },
  { term: '証拠価値', aliases: ['evidentiary value'], description: '記録やログが証拠として信頼される度合いのことです。改ざん防止・時刻同期・保管ルールがすべて関係します。' },
  { term: '契約終了手続き', aliases: ['contract termination procedures'], description: '契約終了時のデータ返還・削除・権限失効・引き継ぎ等の対応のことです。最初に定義しておかないと終了時にトラブルが起きやすいです。' },
  { term: 'データ削除証明', aliases: ['data deletion certification'], description: '不要なデータが適切に削除されたことを証明する書面のことです。委託終了時や情報管理監査で重要になります。' },
  { term: '資産棚卸し', description: '何の資源がどこに存在し、誰が管理しているかを確認することです。クラウドでは放置資源がコストとリスクの温床になりやすいです。' },
  { term: '技術負債返済枠', description: '既存問題の改善に使う時間や予算の枠です。新規開発だけで埋めると、負債が膨らみ続けます。' },
  { term: '多重下請構造', description: '委託が何段にも連なる商流構造です。情報伝達の劣化、責任曖昧化、利益率低下が起きやすいです。' },
  { term: '原価', description: 'その仕事を行うために実際にかかる費用です。売価だけ見ても利益は分からず、原価管理が重要になります。' },
  { term: '粗利', description: '売上から直接原価を引いた利益です。受託開発では工数超過がそのまま粗利悪化につながりやすいです。' },
  { term: '利益率', description: '売上に対してどれだけ利益が残るかの割合です。価格だけでなく、体制、品質、商流構造にも左右されます。' },
  { term: '採算管理', description: '案件ごとの収支を見ながら運営することです。忙しくても赤字案件を放置しないために不可欠です。' },
  { term: '進行基準', description: '進捗に応じて売上や利益を認識する考え方です。長期案件では会計処理上重要です。' },
  { term: 'インボイス対応', description: '適格請求書制度に沿って請求書や番号管理を行う対応です。経理だけでなく、契約先情報管理にも影響します。' },
  { term: '収益認識', description: 'いつ売上として計上するかという会計上の考え方です。契約形態、成果物、検収条件と深く関わります。' },
  { term: '未収金', description: '売上計上済みだが、まだ入金されていない金額です。回収管理が甘いと資金繰りへ影響します。' },
  { term: '回収サイト', description: '請求から入金までの期間です。売上があっても回収が遅いと、経営上は苦しくなることがあります。' },
  { term: '与信管理', description: '取引先の支払い能力や信用度を確認し、取引条件を調整する管理です。営業だけでなく経理や経営判断とも連動します。' },
  { term: '工事進行基準', aliases: ['percentage-of-completion method'], description: '作業の進捗度に応じて売上を按分計上する会計処理の方法です。長期プロジェクトの収益を適切な期間に配分するために使われます。' },
  { term: '工事完成基準', aliases: ['completed-contract method'], description: '成果物の完成・引き渡し時点で一括して売上を計上する会計方法です。短期案件や明確な完了基準がある場合に適用されます。' },
  { term: '検収払い', aliases: ['acceptance-based billing'], description: '発注元の検収完了を条件として代金を支払う方式です。受注者側には入金タイミングが遅れるリスクがあるため、条件を事前に確認することが重要です。' },
  { term: '月末締め翌月末払い', aliases: ['end-of-month billing, end-of-next-month payment'], description: '当月末に請求を締め翌月末に支払う日本のSI業界で一般的な決済サイクルです。キャッシュフロー計画を立てる際の基本前提となります。' },
  { term: '前払い', aliases: ['advance payment'], description: '作業や納品前に代金の一部または全額を受け取る方式です。受注者のキャッシュフロー改善に有効ですが、発注元との信頼関係が前提となります。' },
  { term: '月額固定費', aliases: ['retainer fee'], description: '成果に関わらず毎月一定額を支払う契約形式の費用です。保守・運用・顧問契約などで利用され、双方の収支予測が立てやすくなります。' },
  { term: '源泉徴収税', aliases: ['withholding tax'], description: '報酬の支払時に支払者が差し引いて国に納付する税金です。フリーランスや外部委託取引で発生することがあり、請求書への記載方法も確認が必要です。' },
  { term: '税区分', aliases: ['tax classification'], description: '取引が課税・非課税・免税のいずれに該当するかの区分です。請求書の記載や会計処理に直結するため、正確な判断が求められます。' },
  { term: '適格請求書対応', aliases: ['qualified invoice compliance'], description: 'インボイス制度に基づき、登録番号や税率・税額を明記した適格請求書を発行・管理する対応です。消費税の仕入税額控除に影響します。' },
  { term: '回収サイクル', aliases: ['collection cycle'], description: '売上計上から実際の入金までにかかる期間や流れです。サイクルが長いほどキャッシュフローへの影響が大きくなります。' },
  { term: 'BPM', aliases: ['bpm'], description: 'Business Process Managementの略で、業務プロセスを可視化し、改善し、継続的に運用する考え方です。システム導入だけでなく業務そのものの改善に関わります。' },
  { term: '業務プロセス', aliases: ['business process'], description: '一連の仕事の流れと、その中の役割、判断、入力、出力を含む概念です。システム設計はこの流れの理解から始まります。' },
  { term: '業務フローモデル', aliases: ['business flow model'], description: '業務の流れを図や構造として表したものです。ボトルネックや重複作業を見つけやすくなります。' },
  { term: 'BPMN', aliases: ['bpmn'], description: '業務プロセスを図で表現するための標準記法です。関係者間の認識合わせに役立ちます。' },
  { term: 'タスク', description: 'プロセスの中の個別作業です。誰が行うか、何を入力として何を出力するかを明確にすると設計しやすくなります。' },
  { term: 'ゲートウェイ', aliases: ['gateway'], description: '条件分岐や並行処理を表すプロセス上の分岐点です。業務ルールの明示に役立ちます。' },
  { term: 'イベント', aliases: ['event'], description: 'プロセス開始や進行、終了のきっかけになる出来事です。申請、承認、入金確認などが該当します。' },
  { term: 'スイムレーン', aliases: ['swimlane'], description: 'プロセス図の中で役割や部門ごとに流れを分ける表現です。誰が何を担うか見えやすくなります。' },
  { term: '担当者割当', aliases: ['assignee allocation'], description: '作業を誰が行うか決めることです。役割ベースにするか、個人固定にするかで運用性が変わります。' },
  { term: '責任分担表', aliases: ['responsibility assignment matrix'], description: '各業務や判断を誰が担うか一覧化した表です。組織変更時にも有効な資産になります。' },
  { term: '申請フロー', aliases: ['request flow'], description: '申請から承認、差戻し、完了までの流れです。内部統制や証跡管理と強く結びつきます。' },
  { term: '差戻し', aliases: ['rejection'], description: '内容不備などで前段階へ戻すことです。差戻理由を残せる設計にすると再提出がしやすくなります。' },
  { term: '代理承認', aliases: ['proxy approval'], description: '本来の承認者が不在時に代理で承認する仕組みです。緊急時対応に有効ですが、権限と証跡が重要です。' },
  { term: '業務例外処理', aliases: ['business exception handling'], description: '標準フローでは扱えないケースへの対応です。例外が多い業務ほど、例外設計が品質を左右します。' },
  { term: 'ケース管理', aliases: ['case management'], description: '定型フローに乗り切らない案件ごとの進行管理です。相談、クレーム、審査業務などで使われます。' },
  { term: 'ケースワーク', aliases: ['casework'], description: '一件ごとの事情に応じた個別対応型の業務です。完全自動化より支援設計が向くことが多いです。' },
  { term: 'SOP', aliases: ['sop'], description: 'Standard Operating Procedureの略で、標準作業手順書です。業務品質の平準化に役立ちます。' },
  { term: '業務手順標準化', aliases: ['work procedure standardization'], description: '人によるやり方の差を減らし、一定品質で回せるようにすることです。自動化やAI化の前提として重要です。' },
  { term: 'RPA', aliases: ['rpa'], description: '画面操作や定型作業を自動化する仕組みです。短期導入しやすい反面、画面変更に弱いことがあります。' },
  { term: 'ハイパーオートメーション', aliases: ['hyperautomation'], description: 'RPA、AI、ワークフロー、分析を組み合わせて広範囲に自動化する考え方です。部分最適で終わらせない視点が重要です。' },
  { term: 'ヒューマンタスク', aliases: ['human task'], description: '人の判断や入力が必要な作業です。AIや自動化と組み合わせる場合、この境界を明確にする必要があります。' },
  { term: 'システムタスク', aliases: ['system task'], description: '人手を介さずシステムが自動で行う作業です。条件やエラー時扱いを詳細設計で詰める必要があります。' },
  { term: '手作業残置', aliases: ['manual task retention'], description: 'あえて手作業として残す業務です。自動化しない理由を明確にしておくと、将来の改善判断に役立ちます。' },
  { term: '業務分岐条件', aliases: ['business branching condition'], description: 'フローがどこで、何を基準に分かれるかの条件です。曖昧だと利用者ごとに解釈差が出やすいです。' },
  { term: '業務イベント駆動', aliases: ['business event-driven'], description: '業務上の出来事をトリガーに後続処理を進める設計です。通知、審査、記録更新などに使われます。' },
  { term: 'SLA連動フロー', aliases: ['sla連動フロー', 'sla-linked flow'], description: '期限や対応時間に応じて自動催促やエスカレーションを行うフローです。サービス業務で有効です。' },
  { term: '督促フロー', aliases: ['reminder flow'], description: '未対応や遅延に対して催促する流れです。機械的すぎると反発を招くため、文面や段階設計が重要です。' },
  { term: '期限超過検知', aliases: ['deadline overdue detection'], description: '期限内に終わらなかった案件を見つけることです。放置すると品質や顧客満足へ影響します。' },
  { term: '業務KPI連動', aliases: ['業務kpi連動', 'business kpi linkage'], description: '業務フローと指標をつなげて管理することです。処理件数、滞留時間、差戻率などが対象になります。' },
  { term: 'リードタイム', aliases: ['lead time'], description: '依頼受付から完了までにかかる全体時間です。業務改善では非常に重要な指標になります。' },
  { term: '処理時間', aliases: ['processing time'], description: '実際に作業している時間です。待ち時間と分けて見ると、改善余地が見えやすくなります。' },
  { term: '待ち時間', aliases: ['wait time'], description: '作業はされずに止まっている時間です。多くの業務では、実作業より待ち時間のほうが長いことがあります。' },
  { term: '滞留', description: '案件や申請が途中段階で止まっている状態です。ボトルネック把握に重要です。' },
  { term: '再処理率', aliases: ['rework rate'], description: '一度で終わらず、差戻しや修正でやり直しが発生する割合です。入力品質やルール明確性の問題が見えます。' },
  { term: '直行率', aliases: ['first-pass rate'], description: '一度も差戻しや再処理なく完了した割合です。業務品質を示す指標として使えます。' },
  { term: '受付チャネル', aliases: ['intake channel'], description: '依頼や申請を受け付ける入口です。メール、Webフォーム、電話、APIなど複数あると統合設計が必要になります。' },
  { term: 'チケット起票', aliases: ['ticket creation'], description: '依頼や問題を管理単位として登録することです。記録が残ることで追跡しやすくなります。' },
  { term: '業務棚卸し', aliases: ['business inventory'], description: 'どんな業務があり、誰が、どの頻度で、どれだけ手間をかけているか洗い出すことです。改善の出発点として重要です。' },
  { term: '標準業務', aliases: ['standard business operation'], description: '通常ルールに従って進む代表的な業務です。自動化はここから始めると効果を出しやすいです。' },
  { term: '例外業務', aliases: ['exception business operation'], description: '標準フローから外れる業務です。少数なら手運用でもよいですが、多いなら標準自体を見直す必要があります。' },
  { term: '部門横断業務', aliases: ['cross-departmental process'], description: '複数部門にまたがって進む業務です。責任の受け渡しが多く、滞留しやすい傾向があります。' },
  { term: 'ハンドオフ', aliases: ['handoff'], description: '作業や責任を別担当へ渡すことです。回数が多いほど、待ちや認識差が増えやすくなります。' },
  { term: '業務境界', aliases: ['business boundary'], description: 'どこまでがある部門や役割の責任かという境目です。境界が曖昧だと責任の押し付け合いが起こりやすくなります。' },
  { term: '業務ルールエンジン', aliases: ['business rule engine'], description: '条件判定やルール適用を外部定義で管理する仕組みです。頻繁に変わる業務条件に対応しやすくなります。' },
  { term: 'ケース優先順位付け', aliases: ['case prioritization'], description: '受付案件を重要度や期限で並べ替えることです。処理漏れや重要案件の放置を防げます。' },
  { term: 'サービスカタログ', description: '提供している業務サービスや申請可能メニューを一覧化したものです。利用者が何を頼めるか分かりやすくなります。' },
  { term: 'サービス要求管理', aliases: ['service request management'], description: '利用者からの標準依頼を受付、処理、追跡する管理です。インシデント管理と分けて設計すると整理しやすいです。' },
  { term: '提案活動', description: '顧客課題を整理し、どのような方法で解決するかを示して案件化につなげる活動です。単なる製品紹介ではなく、課題理解と実現方針の提示が本質になります。' },
  { term: '案件化', description: '相談や要望の段階から、実際に見積や契約対象となる案件へ育てることです。課題、予算、時期、意思決定者が見えてくると案件化しやすくなります。' },
  { term: '案件情報', description: '顧客、目的、背景、予算感、体制、競合状況など、その案件に関する基礎情報です。後から振り返っても分かる形で整理しておくと提案の質が上がります。' },
  { term: '商談', description: '顧客と具体的な導入や契約の可能性について話し合う場です。単なる説明会ではなく、課題確認と期待値調整の場として捉えることが重要です。' },
  { term: '初回ヒアリング', description: '最初の対話で、顧客の課題、背景、制約を把握することです。ここで早く提案に飛びつかず、事実を丁寧に聞くことが後工程を楽にします。' },
  { term: '要望整理', description: '顧客から出た希望や不満を、目的や優先度ごとに整理することです。表現どおり受け取るだけでなく、何のためかを補足して整理する必要があります。' },
  { term: '提案機会', description: '自社の価値を提示できる場面やタイミングです。障害、更新時期、法改正、組織変更などが提案機会になることがあります。' },
  { term: '案件温度感', description: 'その案件がどの程度本気度や緊急度を持って進んでいるかという感覚です。温度感を見誤ると、重すぎる提案や軽すぎる提案になりやすいです。' },
  { term: '予算感', description: '顧客が想定している費用感のことです。正確な数字がなくても、おおよそのレンジが見えるだけで提案現実性が高まります。' },
  { term: '導入時期', description: '顧客がいつ頃までに導入したいかという時期感です。予算年度、制度改定、契約更新時期などが背景にあることも多いです。' },
  { term: '意思決定者', description: '最終的に導入や契約の判断をする人です。現場が困っていても、この人の関心軸を外すと前に進みにくくなります。' },
  { term: 'キーパーソン', description: '意思決定に大きな影響を持つ人物です。正式決裁者でなくても、実質的に方向を決めることがあります。' },
  { term: '競合状況', description: '他社提案や既存製品との比較状況です。価格勝負だけでなく、何が比較軸になっているかを把握することが重要です。' },
  { term: '提案仮説', description: '顧客に対して、この方向なら刺さるだろうという仮説です。業界事情、課題、相手の立場を踏まえて立てると提案精度が上がります。' },
  { term: 'テーマ設定', description: '提案全体を一言で貫く主題を定めることです。テーマが明確だと、資料全体に一貫性が出やすくなります。' },
  { term: 'メッセージ設計', description: '何を最も伝えるべきかを整理し、順番や表現を決めることです。提案書の説得力は、情報量よりメッセージの通り方で決まることがあります。' },
  { term: '提案骨子', description: '提案内容の大枠や章立てです。細部を作り込む前に骨子を整えると、全体の筋が通しやすくなります。' },
  { term: 'エグゼクティブサマリー', description: '経営層向けに背景、課題、提案方針、効果を短くまとめた要約です。提案書の中でも特に重要なページになることが多いです。' },
  { term: '提案方針', description: 'どんな考え方で課題を解くかを示す方針です。製品名や技術名より前に、この方針が腹落ちすることが重要です。' },
  { term: '差別化メッセージ', description: 'なぜ自社案が他案より適しているのかを示す核心的な言葉です。単なる機能差ではなく、顧客課題との結びつきが必要です。' },
  { term: '課題訴求', description: '顧客がまだ十分に意識していない課題も含めて、問題の重要性を伝えることです。提案の説得力は、解決策より課題理解に支えられることが多いです。' },
  { term: '効果訴求', description: '導入後に得られる価値や改善効果を伝えることです。機能列挙よりも、何がどう良くなるかを示すほうが伝わりやすいです。' },
  { term: 'ビフォーアフター整理', description: '現状と導入後の違いを分かりやすく示すことです。変化が見えると、提案価値が直感的に理解されやすくなります。' },
  { term: '導入シナリオ', description: '提案した仕組みをどう現場へ入れていくかの流れです。機能だけでなく、移行、教育、定着まで含めると現実的になります。' },
  { term: '提案レビュー', description: '提案内容を第三者視点で確認し、抜け漏れや弱い論点を見つけることです。社内レビューだけでも提案精度は大きく変わります。' },
  { term: '勝ち筋', description: 'その案件で評価されやすいポイントや、自社が優位に立てる要素です。全部を頑張るより、勝ち筋を明確にしたほうが強い提案になります。' },
  { term: '失注分析', description: '案件を取れなかった理由を振り返ることです。価格だけに原因を求めず、課題理解や提案の伝え方も見直す必要があります。' },
  { term: '受注確度', description: 'その案件を受注できる見込みの強さです。楽観で判断すると体制や売上計画が崩れやすくなります。' },
  { term: '案件ランク付け', description: '重要度や受注見込みに応じて案件を分類することです。追うべき案件へ集中するために有効です。' },
  { term: '提案稼働', description: '提案準備にどれだけ人と時間を使うかということです。受注確度に対して過剰に稼働すると、他案件への影響が出やすくなります。' },
  { term: 'プリセールス', description: '営業活動を技術面から支える役割です。提案、デモ、要件整理、技術質問対応など、受注前の実務を担います。' },
  { term: '技術デモ', description: '実際の画面や仕組みを見せて提案の具体像を伝えることです。言葉だけより理解が早い一方、過剰期待を生まない説明も必要です。' },
  { term: 'RFP対応', aliases: ['rfp対応'], description: '提案依頼書に沿って、回答や提案を整理することです。形式に合わせるだけでなく、裏にある本音の課題も読む必要があります。' },
  { term: 'ビッド・ノービッド判断', description: 'その案件に提案するか、見送るかを決める判断です。全部に乗るより、自社が勝てて価値を出せる案件へ集中するほうが健全です。' },
  { term: '案件資格確認', aliases: ['deal qualification'], description: '問い合わせや依頼を見積・契約対象となる実案件へと育てるプロセスです。課題・予算・時期・意思決定者が明確になることで案件が資格を得ます。' },
  { term: 'ビジネス商談', aliases: ['business meeting'], description: '顧客と具体的な採用・契約の可能性を話し合う場です。単なるプレゼンではなく、課題確認と期待値合わせのフォーラムとして扱うことが重要です。' },
  { term: '要件整理', aliases: ['requirements organization'], description: '顧客の要望や不満を目的・優先度別に整理することです。要望をそのまま受け取るだけでなく、背後にある目的を補完することが求められます。' },
  { term: '予算規模感', aliases: ['budget range'], description: '顧客が想定するコストの大まかな範囲です。正確な数字がなくても大まかな規模感があると提案の実現可能性が高まります。' },
  { term: '提案アウトライン', aliases: ['proposal outline'], description: '提案書の全体的な枠組みとチャプター構成です。詳細に入る前にアウトラインを確立することで、論理的な流れを保ちやすくなります。' },
  { term: '提案戦略', aliases: ['proposal strategy'], description: '顧客課題を解決するためのアプローチや方針です。製品名や技術名を前面に出すより、この戦略が共感を得ることの方が重要です。' },
  { term: 'ベネフィット訴求', aliases: ['benefit appeal'], description: '採用後に得られる価値や改善効果を伝えることです。機能列挙より、どのように改善されるかを見せる方が効果的です。' },
  { term: 'ビフォーアフター比較', aliases: ['before-and-after comparison'], description: '現状と採用後の状態の差を明示することです。変化が可視化されると、提案の価値が直感的に伝わりやすくなります。' },
  { term: '受注戦略', aliases: ['winning strategy'], description: '案件で評価されやすいポイント、または自社が優位に立てる要素のことです。全てを網羅しようとするより、明確な勝利戦略に絞った提案の方が強くなります。' },
  { term: '案件ランク', aliases: ['deal ranking'], description: '重要度と受注確度に応じて案件を分類することです。注力すべき案件にリソースを集中させるために活用します。' },
  { term: '提案工数', aliases: ['proposal effort'], description: '提案準備に投入する人数と時間の量です。受注確度に対して過大な工数投入は、他案件にも悪影響を与えかねません。' },
  { term: 'テクニカルデモ', aliases: ['technical demo'], description: '実際の画面や仕組みを見せて提案の具体的なイメージを伝えることです。言葉よりも早く理解が進む一方、過剰な期待を生まないよう注意が必要です。' },
  { term: '入札判断', aliases: ['bid/no-bid decision'], description: '提案を出すか見送るかの判断です。全てに参加するより、自社が勝てて価値を提供できる案件に絞る方が健全です。' },
  { term: 'DX', aliases: ['dx', 'digital transformation'], description: 'デジタル技術で業務や事業、顧客価値を変革すること。' },
  { term: 'モダナイゼーション', aliases: ['modernization'], description: '既存システムや業務を現在の技術や要件に合わせて刷新すること。' },
  { term: 'アライアンス', aliases: ['alliance'], description: '他社やパートナーと連携して提案力や事業力を高めること。' },
  { term: '共創', aliases: ['co-creation'], description: '顧客やパートナーと一緒に価値や事業を作ること。' },
  { term: 'R&D', aliases: ['r&d'], description: '新技術や新サービスのための研究開発活動。' },
  { term: 'インバウンドマーケティング', aliases: ['inbound marketing'], description: '情報発信によって見込み顧客からの接点を得る手法。' },
  { term: 'アウトバウンドマーケティング', aliases: ['outbound marketing'], description: '企業側から顧客へ働きかけて接点を作る手法。' },
  { term: 'ストックビジネス', aliases: ['stock business'], description: '継続契約などで収益が積み上がる事業モデル。' },
  { term: 'オフショア開発', aliases: ['offshore development'], description: '海外拠点や海外人材を活用して行う開発体制。' },
  { term: 'サービス化', aliases: ['productization'], description: '個別案件の知見や強みを再利用可能な形で提供すること。' },
  { term: '重点顧客深耕', aliases: ['key account development'], description: '重要顧客との関係を深め、取引領域を広げること。' },
  { term: '新規顧客開拓', aliases: ['new customer acquisition'], description: '新たな顧客との取引を生み出す営業活動。' },
  { term: '内製化', aliases: ['in-house development'], description: '外部委託ではなく、自社や顧客自身で開発・運用機能を持つこと。' },
  { term: '見込み顧客', aliases: ['prospect'], description: '将来顧客になる可能性がある相手。' },
  { term: '提案', aliases: ['proposal (sales)'], description: '相手の課題に対して解決策や条件を示すこと。' },
  { term: '事業計画', aliases: ['business plan'], description: '事業の目標、戦略、数値計画などをまとめた計画。' },
  { term: 'BA', aliases: ['ba', 'business analytics'], description: '予測や最適化まで含めて課題発見につなげる分析領域。' },
  { term: 'DWH', aliases: ['dwh', 'data warehouse (dwh)'], description: '分析しやすい形に整理・統合されたデータの蓄積基盤。' },
  { term: 'データマネジメント', aliases: ['data management'], description: 'データの収集、整備、品質管理、活用まで含めた管理。' },
  { term: 'データ分析基盤', aliases: ['data analytics platform'], description: 'データの収集、保管、加工、分析、可視化を担う基盤全体。' },
  { term: 'データマイニング', aliases: ['data mining'], description: '大量データから傾向や相関などの知見を見つける手法。' },
  { term: 'OLAP分析', aliases: ['olap分析', 'olap analysis'], description: '多次元的に集計・分析して傾向を確認する手法。' },
  { term: '可視化', aliases: ['visualization'], description: '数字や状態をグラフや図などでわかりやすく見せること。' },
  { term: '予測', aliases: ['forecasting'], description: '過去や現在のデータをもとに将来を見通すこと。' },
  { term: '最適化', aliases: ['optimization'], description: '条件の中で最もよい状態に近づけること。' },
  { term: '会社', aliases: ['company'], description: '事業活動を行うための組織。' },
  { term: '組織', aliases: ['organization (corporate)'], description: '仕事を分担して進めるためのまとまり。' },
  { term: '職位', aliases: ['job grade'], description: '会社の中での立場や役職。' },
  { term: '役員', aliases: ['executive officer'], description: '会社の経営に責任を持つ立場の人。' },
  { term: '取締役', aliases: ['director'], description: '会社の経営方針を決め、業務の実行を監督する人。' },
  { term: '取締役会', aliases: ['board of directors'], description: '会社の重要事項を決める会議。' },
  { term: '株主総会', aliases: ['general shareholders meeting'], description: '株主が集まり、会社の重要事項を決める場。' },
  { term: '監査役', aliases: ['statutory auditor'], description: '取締役や会社の業務に問題がないかを監督する人。' },
  { term: '執行役員', aliases: ['managing officer'], description: '決められた方針に基づいて実際の業務を進める立場の人。' },
  { term: '職務権限', aliases: ['job authority'], description: '誰がどこまで決めてよいかを示す権限範囲。' },
  { term: '決裁', aliases: ['approval (kessai)'], description: '責任者が申請や案を正式に認めること。' },
  { term: '承認', aliases: ['approval'], description: '内容を確認し、問題ないと認めること。' },
  { term: '起案', aliases: ['drafting'], description: '申請書や提案書を作って正式に出すこと。' },
  { term: '予算', aliases: ['budget'], description: '収入や支出の計画として定める金額。' },
  { term: '組織変更', aliases: ['organizational change'], description: '部署や役割の構成を変えること。' },
  { term: '人事', aliases: ['human resources'], description: '人の配置、評価、採用、育成などに関する活動。' },
  { term: '人事考課', aliases: ['performance review'], description: '社員の仕事ぶりや成果を評価すること。' },
  { term: '契約', aliases: ['contract'], description: '当事者どうしが条件や責任を合意すること。' },
  { term: '解除', aliases: ['termination'], description: '結んだ契約を途中で終わらせること。' },
  { term: '懲戒', description: '重大なルール違反に対して会社が行う処分。' },
  { term: '諭旨退職', aliases: ['advised resignation'], description: '会社が退職を求め、本人が応じて退職する形の処分。' },
  { term: '懲戒解雇', aliases: ['dismissal for cause'], description: '重大な問題行為があったときの最も重い解雇処分。' },
  { term: '就業規則', aliases: ['employment regulations'], description: '働くうえでの基本ルールをまとめたもの。' },
  { term: '規程', aliases: ['company regulations'], description: '会社の業務や運用について定めたルール。' },
  { term: '服務', aliases: ['service discipline'], description: '社員として守るべき行動や勤務上の規律。' },
  { term: '法務', aliases: ['legal affairs'], description: '契約や法令対応など法律に関する業務。' },
  { term: '会社法', aliases: ['companies act'], description: '会社の設立や運営などを定める法律。' },
  { term: '法令遵守', aliases: ['legal compliance'], description: '法令を守って業務を行うこと。' },
  { term: '違反', aliases: ['violation'], description: 'ルールや法令に反すること。' },
  { term: '相談窓口', aliases: ['consultation desk'], description: '問題や不安を相談できる受付先。' },
  { term: '労働条件', aliases: ['employment conditions'], description: '給料、勤務時間、休日、仕事内容、勤務地など働く条件。' },
  { term: '試用期間', aliases: ['probationary period'], description: '正式採用前に適性を見るための期間。' },
  { term: '配置転換', aliases: ['relocation'], description: '同じ会社の中で仕事や所属を変えること。' },
  { term: '転勤', description: '勤務地を変えて働くこと。' },
  { term: '出向', aliases: ['secondment'], description: '元の会社に籍を置いたまま別の会社などで働くこと。' },
  { term: '転籍', aliases: ['permanent transfer'], description: '元の会社との雇用関係を終えて別の会社へ移ること。' },
  { term: '休職', aliases: ['leave of absence'], description: '病気などの理由でしばらく仕事を休むこと。' },
  { term: '復職', aliases: ['return to work'], description: '休職していた人が職場に戻ること。' },
  { term: '退職', aliases: ['resignation'], description: '社員が会社を辞めること。' },
  { term: '解雇', aliases: ['dismissal'], description: '会社の判断で雇用を終了させること。' },
  { term: '定年', aliases: ['mandatory retirement'], description: '一定年齢で原則退職となる制度。' },
  { term: '再雇用', aliases: ['re-employment'], description: '定年後にあらためて雇用契約を結んで働くこと。' },
  { term: '勤続年数', aliases: ['years of service'], description: 'その会社で働き続けている年数。' },
  { term: '昇給', aliases: ['pay raise'], description: '給料が上がること。' },
  { term: '降給', aliases: ['pay cut'], description: '給料が下がること。' },
  { term: '昇格', aliases: ['promotion'], description: 'より上の等級や役職になること。' },
  { term: '降格', aliases: ['demotion'], description: '等級や役職が下がること。' },
  { term: '賞与', aliases: ['bonus'], description: '毎月の給料とは別に支給されるお金。' },
  { term: '手当', aliases: ['allowance'], description: '特定条件に応じて基本給とは別に支給されるお金。' },
  { term: '通勤手当', description: '通勤費を補助するために支給されるお金。' },
  { term: '住宅手当', aliases: ['housing allowance'], description: '住居費を補助するために支給されるお金。' },
  { term: '固定残業手当', aliases: ['fixed overtime allowance'], description: 'あらかじめ一定時間分の残業代を含めて支給する手当。' },
  { term: '超過手当', aliases: ['excess work allowance'], description: '固定分を超えた残業や深夜勤務などに対する手当。' },
  { term: '年次有給休暇', aliases: ['annual paid leave'], description: '給料が出る休暇。' },
  { term: '特別休暇', aliases: ['special leave'], description: '特別な事情があるときに認められる休暇。' },
  { term: '産前産後休暇', aliases: ['maternity leave'], description: '出産の前後に取得できる休暇。' },
  { term: '育児休業', aliases: ['childcare leave'], description: '子どもを育てるために一定期間休む制度。' },
  { term: '介護休業', aliases: ['nursing care leave'], description: '家族を介護するために一定期間休む制度。' },
  { term: '短時間勤務', aliases: ['reduced working hours'], description: '通常より短い時間で働く制度。' },
  { term: 'テレワーク', aliases: ['telework'], description: '会社以外の場所でパソコンなどを使って働くこと。' },
  { term: '所定労働時間', aliases: ['scheduled working hours'], description: '会社があらかじめ決めている通常の勤務時間。' },
  { term: '所定外労働', aliases: ['overtime work'], description: '決められた勤務時間を超えて働くこと。' },
  { term: '休日出勤', aliases: ['holiday work'], description: '会社の休日に働くこと。' },
  { term: '深夜業', aliases: ['late-night work'], description: '夜10時から朝5時までの時間帯に働くこと。' },
  { term: '代休', aliases: ['compensatory day off'], description: '休日勤務の代わりに別の日に休むこと。' },
  { term: '振替休日', aliases: ['substituted holiday'], description: 'あらかじめ勤務日と休日を入れ替えること。' },
  { term: '勤務地', aliases: ['work location'], description: '働く場所。' },
  { term: '給料', aliases: ['salary'], description: '労働の対価として支払われるお金。' },
  { term: '見積書', aliases: ['quotation'], description: '商品やサービスの内容、金額、条件を事前に示す書類。' },
  { term: '受注', aliases: ['receiving an order'], description: '顧客から正式に注文を受けること。' },
  { term: '発注', aliases: ['placing an order'], description: '外部の相手に仕事や物品を注文すること。' },
  { term: '納品', description: '商品や成果物を相手に渡すこと。' },
  { term: '売掛金', aliases: ['accounts receivable (urikakekin)'], description: '先に提供した商品やサービスの代金を後で受け取る権利。' },
  { term: '買掛金', aliases: ['accounts payable'], description: '先に受け取った商品やサービスの代金を後で支払う義務。' },
  { term: '債権', aliases: ['receivable'], description: '相手にお金を払ってもらう権利。' },
  { term: '債務', aliases: ['payable'], description: '相手にお金を払う義務。' },
  { term: '与信', aliases: ['credit assessment'], description: '相手にあと払いを認めること、またはその信用力を見ること。' },
  { term: '与信限度額', aliases: ['credit limit'], description: 'あと払いで取引してよい上限額。' },
  { term: '信用調査', aliases: ['credit investigation'], description: '取引先の支払い能力や経営状態を調べること。' },
  { term: '値引き', aliases: ['discount'], description: '本来の価格より安くすること。' },
  { term: '返品', description: '売った商品などを相手から返してもらうこと。' },
  { term: '苦情', aliases: ['complaint'], description: '商品やサービスに対して相手から寄せられる不満や指摘。' },
  { term: 'クレーム', aliases: ['formal complaint'], description: '会社として正式な対応が必要な苦情。' },
  { term: '取引先', description: '商品やサービスの売買や契約を行う相手。' },
  { term: '会計年度', aliases: ['fiscal year'], description: '会社がお金や業績をまとめる1年間の区切り。' },
  { term: '決算', aliases: ['financial closing'], description: '一定期間の売上、費用、利益、財産の状況をまとめること。' },
  { term: '月次決算', aliases: ['monthly closing'], description: '1か月ごとに業績や財務状況をまとめること。' },
  { term: '四半期決算', aliases: ['quarterly closing'], description: '3か月ごとに行う決算。' },
  { term: '期末決算', aliases: ['year-end closing'], description: '1年の終わりに行う正式な決算。' },
  { term: '財務諸表', aliases: ['financial statements'], description: '会社のお金の状態や経営成績を示す書類の総称。' },
  { term: '貸借対照表', aliases: ['balance sheet'], description: 'ある時点の資産、負債、純資産を示す表。' },
  { term: '損益計算書', aliases: ['income statement'], description: '一定期間の売上、費用、利益や損失を示す表。' },
  { term: 'キャッシュ・フロー', aliases: ['cash flow'], description: '実際のお金の出入りの流れ。' },
  { term: '減価償却', aliases: ['depreciation'], description: '長く使う資産の購入費用を複数年に分けて費用化すること。' },
  { term: '固定資産', aliases: ['fixed asset'], description: '長期間使う前提で持つ資産。' },
  { term: '無形固定資産', aliases: ['intangible fixed asset'], description: '形はないが価値があり長く使う資産。' },
];
