// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: performanceCache (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // performance (87), Performance (3), capacity (2), Capacity (2)
  { term: '性能', aliases: ['performance'], description: '応答速度、処理件数、同時利用への強さなど、システムの処理能力を表す言葉です。設計段階で考えないと、後からの改善は高コストになりやすいです。' },
  { term: 'キャッシュ', aliases: ['cache'], description: 'よく使うデータを一時的に保存して、再利用しやすくする仕組みです。高速化に有効ですが、古い情報を返さないよう更新設計が重要です。' },
  { term: 'スケールアップ', description: '一台あたりの性能を高めて処理能力を上げる方法です。単純ですが、上限やコスト上昇が問題になることがあります。' },
  { term: 'メトリクス収集', description: '状態や性能を数値として継続的に集めることです。感覚ではなくデータで判断できる土台になります。' },
  { term: 'ボトルネック', description: '全体性能を制限している最も細い部分です。CPUなのか、DBなのか、外部APIなのかを特定しないと効果的な改善はできません。' },
  { term: 'キャッシュ無効化', description: '古くなったキャッシュを捨てて最新状態へ追従させることです。キャッシュ自体より、この無効化設計のほうが難しいことも多いです。' },
  { term: 'ISR', aliases: ['isr'], description: 'Incremental Static Regenerationの略で、静的生成と再生成を組み合わせる方式です。性能と更新性のバランスを取りたいときに有効です。' },
  { term: 'モデルドリフト', description: '時間経過や環境変化で期待した性能がずれていくことです。入力傾向や対象業務の変化でも起こります。' },
  { term: '推論キャッシュ', description: '同じ問い合わせへの回答を再利用してコストや遅延を下げる仕組みです。鮮度が必要な質問では注意して使う必要があります。' },
  { term: '本番相当環境', description: '本番にできるだけ近い構成で用意した検証環境です。性能や連携の確認では特に重要です。' },
  { term: '性能要件検証', description: '要件で定めた応答時間や処理件数を満たせるか確認することです。単に速いかどうかではなく、約束した水準に届くかが重要です。' },
  { term: '容量予測', description: '今後どれだけのリソースが必要になるかを予測することです。利用増加やイベント時負荷を見越して準備するために必要です。' },
  { term: 'トラフィック予測', description: '通信量やアクセス数の将来変化を予測することです。平時ではなくピーク時をどう見るかが重要になります。' },
  { term: 'レイテンシ分布', description: '応答時間のばらつきを分布で見る考え方です。平均値だけでは、遅い一部利用者の苦しさを見落としやすいです。' },
  { term: 'パーセンタイル指標', description: '応答時間の上位何パーセントがどれだけ遅いかを見る指標です。P95やP99がよく使われます。' },
  { term: 'P95応答時間', aliases: ['p95応答時間'], description: '95パーセントのリクエストがこの時間以内に終わるという指標です。平均より利用者体感に近い品質を見やすくなります。' },
  { term: 'キャパシティ予測', aliases: ['capacity forecasting'], description: '将来的にどれだけのリソースが必要かを予測することです。利用増加やイベント駆動の負荷増大に先んじて準備するために必要です。' },
  { term: 'トラフィック量予測', aliases: ['traffic forecasting'], description: '将来のトラフィック量やアクセス数の変化を予測することです。平常時ではなくピーク時の対応方針が最も重要です。' },
  { term: 'レイテンシ分布特性', aliases: ['latency distribution'], description: '応答時間のばらつきを分布として捉えるコンセプトです。平均だけでは一部の遅いユーザーの苦しみを見落としがちです。' },
  { term: 'パーセンタイルメトリクス', aliases: ['percentile metrics'], description: '上位何パーセントの応答時間がどれだけ遅いかを示す指標です。P95・P99が一般的に使われます。' },
  { term: 'P95レスポンスタイム', aliases: ['p95レスポンスタイム', 'p95 response time'], description: '95%のリクエストがこの時間以内に完了することを示す指標です。平均よりもユーザー体験に近い品質を把握できます。' },
  { term: 'CLS', aliases: ['cls'], description: 'Content Layout Shiftの略で、表示後に要素がずれてしまう度合いです。見た目の不快感や誤操作の原因になります。' },
  { term: 'LCP', aliases: ['lcp'], description: 'Largest Contentful Paintの略で、主要コンテンツが表示されるまでの時間指標です。初期体感速度の重要指標として使われます。' },
  { term: 'INP', aliases: ['inp'], description: 'Interaction to Next Paintの略で、操作に対する画面反応の遅れを見る指標です。体感操作性に近い品質を測りやすいです。' },
  { term: 'Core Web Vitals', aliases: ['core web vitals'], description: 'Web体験の重要品質指標群です。性能を「速い気がする」ではなく、共通指標で議論しやすくなります。' },
  { term: 'リクエストウォーターフォール', description: '通信が直列につながり、表示や処理が遅くなる状態です。画面設計やAPI分割が原因になることがあります。' },
  { term: 'プリフェッチ', description: '近いうちに必要になりそうなデータや資産を先読みすることです。体感向上に役立ちますが、無駄読みとのバランスが必要です。' },
  { term: 'プリロード', description: '必要性の高い資産を優先して読み込ませる指示です。重要資産の到着を早めるのに有効です。' },
  { term: 'Largest Contentful Paint', aliases: ['largest contentful paint'], description: 'ページの主要コンテンツが画面に描画されるまでの時間を示すCore Web Vitalsの指標。画像やテキストブロックなど最大の要素の描画完了時点を計測し、2.5秒以内が良好とされる。' },
  { term: 'First Input Delay', aliases: ['first input delay', 'fid'], description: 'ユーザーが最初にページを操作した瞬間からブラウザが実際に応答を開始するまでの遅延時間。メインスレッドの処理が長いとFIDが増大し、100ms以内が良好とされる。' },
  { term: 'Interaction to Next Paint', aliases: ['interaction to next paint'], description: 'ユーザーのすべてのインタラクションに対する応答時間の99パーセンタイルを計測するCore Web Vitals指標。FIDの後継として導入され、200ms以内が良好とされる。' },
  { term: 'Cumulative Layout Shift', aliases: ['cumulative layout shift'], description: 'ページ表示中に発生する予期しないレイアウトのズレの累積量を計測するCore Web Vitals指標。広告や遅延読み込み画像の挿入などが原因で発生し、0.1以下が良好とされる。' },
  { term: 'First Contentful Paint', aliases: ['first contentful paint', 'fcp'], description: 'ページがブラウザに読み込まれてから最初のテキストや画像が描画されるまでの時間を計測する指標。ユーザーがページの読み込みを知覚する最初の瞬間を示し、1.8秒以内が良好とされる。Core Web Vitalsの関連指標。' },
  { term: 'Time to First Byte', aliases: ['time to first byte', 'ttfb'], description: 'ブラウザがリクエストを送信してからサーバーから最初の1バイトを受信するまでの時間を示す指標。サーバー処理速度・ネットワーク遅延・CDNの効果を総合的に評価でき、800ms以内が良好とされる。' },
  { term: 'Total Blocking Time', aliases: ['total blocking time', 'tbt'], description: 'FCPからTime to Interactiveまでの間にメインスレッドが50ms以上ブロックされた時間の合計。Long Taskの影響を計測し、インタラクティビティの遅延を示す指標。' },
  { term: 'Speed Index', aliases: ['speed index'], description: 'ページの表示コンテンツが視覚的にどれだけ速く埋まるかを数値化した指標。Lighthouseで計測され、数値が小さいほど素早くコンテンツが描画されており、3.4秒以内が良好とされる。' },
  { term: 'Lighthouse', aliases: ['lighthouse'], description: 'Googleが提供するオープンソースのWebページ品質自動計測ツール。パフォーマンス・アクセシビリティ・SEO・ベストプラクティスを100点満点でスコアリングし、改善提案も提示する。' },
  { term: 'PageSpeed Insights', aliases: ['pagespeed insights', 'psi'], description: 'GoogleのPageSpeed Insightsサービス。URLを入力すると実際のユーザーデータ（CrUX）とLighthouseによるラボデータの両方でパフォーマンスを分析し、改善提案を表示する。' },
  { term: 'WebPageTest', aliases: ['webpagetest'], description: '様々な地域・ブラウザ・ネットワーク環境でWebページのパフォーマンスを詳細計測できる無料ツール。ウォーターフォールチャートやフィルムストリップで読み込みプロセスを可視化する。' },
  { term: 'Performance Budget', aliases: ['performance budget', 'パフォーマンスバジェット'], description: 'Webパフォーマンス指標に設ける上限値の制約。バンドルサイズ・読み込み時間・Lighthouseスコアなどに閾値を設け、CI/CDで自動検証することで品質劣化を防ぐ。' },
  { term: 'Preconnect', aliases: ['preconnect', 'プリコネクト'], description: '外部オリジンへの接続をリソース取得前に事前に確立しておくResource Hints。DNSルックアップ・TCPハンドシェイク・TLSネゴシエーションを先行して実行し、クロスオリジンリソースの取得を高速化する。' },
  { term: 'Priority Hints', aliases: ['priority hints', '優先度ヒント'], description: 'ブラウザのリソース取得優先度を明示的に制御するWeb標準機能。`fetchpriority`属性でhigh/low/autoを指定し、LCPに影響する重要リソースの優先取得やスクリプトの優先度下げに使用する。' },
  { term: 'fetchpriority', aliases: ['fetchpriority属性'], description: '画像・スクリプト・スタイルシートなどのリソース取得優先度を`high`・`low`・`auto`で指定するHTML属性。特にLCPとなるヒーロー画像に`fetchpriority="high"`を付与することで表示を高速化できる。' },
  { term: 'レンダーブロッキング', aliases: ['render blocking', 'レンダリングブロック'], description: 'スタイルシートや同期スクリプトがブラウザの描画処理を停止させる現象。CSSは常にレンダーブロッキングだがメディアクエリで回避可能。スクリプトはasync/defer属性でブロッキングを回避できる。' },
  { term: '非同期スクリプト', aliases: ['async script', 'defer script'], description: 'HTMLのパースをブロックせずにJavaScriptを読み込む仕組み。`async`属性は読み込み完了次第即時実行、`defer`属性はHTML解析完了後に順序を保って実行する。レンダーブロッキングの排除に使用する。' },
  { term: 'GPU Acceleration', aliases: ['gpu acceleration', 'gpu加速', 'ハードウェアアクセラレーション'], description: 'ブラウザのレンダリング処理の一部をGPUに委譲し、CPUの負荷を下げてスムーズなアニメーションを実現する技術。CSS transformやopacityをアニメーションさせることでComposite段階のみで処理しGPUを活用できる。' },
  { term: 'requestIdleCallback', aliases: ['requestidlecallback', 'ric'], description: 'ブラウザのメインスレッドがアイドル状態になったタイミングで非優先タスクを実行するAPIv。分析処理やログ送信など重要度の低い処理をアイドル時間に後回しにすることでユーザー操作への応答性を維持する。' },
  { term: 'Long Task', aliases: ['long task', 'ロングタスク'], description: 'メインスレッドを50ms以上占有するJavaScript処理のこと。Long Taskが発生するとユーザーのインタラクションに対する応答が遅延し、FIDやINPなどCore Web Vitals指標を悪化させる。' },
  { term: 'Main Thread', aliases: ['main thread', 'メインスレッド'], description: 'ブラウザのJavaScript実行・DOM操作・レイアウト・ペイントなどを担う単一のスレッド。JavaScriptはシングルスレッドで動作するため、重い処理がメインスレッドをブロックするとUIが応答不能になる。' },
  { term: 'Web Worker', aliases: ['web worker', 'webworker'], description: 'メインスレッドとは独立したバックグラウンドスレッドでJavaScriptを実行するAPI。重い計算処理をWeb Workerに移すことでメインスレッドのブロッキングを防ぎ、UIの応答性を維持できる。DOMへのアクセスはできない。' },
  { term: 'OffscreenCanvas', aliases: ['offscreencanvas'], description: 'メインスレッド外（Web Worker内）でCanvas描画処理を実行するAPI。グラフィック処理やゲームのレンダリングをバックグラウンドで行うことでメインスレッドの負荷を軽減し、UIのスムーズさを維持する。' },
  { term: 'Virtual Scrolling', aliases: ['virtual scrolling', '仮想スクロール', 'virtualization'], description: '大量のリストアイテムのうち画面に表示される部分のみをDOMに保持し、スクロールに合わせて動的に入れ替えるレンダリング最適化技術。数万件のデータでも高速にスクロールできる。' },
  { term: '再レンダリング最適化', aliases: ['unnecessary rerender prevention'], description: 'Reactアプリで不要なコンポーネントの再レンダリングを防ぐための手法の総称。React.memo・useMemo・useCallback・コンポーネント分割・状態の局所化などを組み合わせてパフォーマンスを改善する。' },
  { term: 'Chrome DevTools Performance', aliases: ['chrome devtools performance', 'パフォーマンスパネル', 'performance panel'], description: 'Chrome DevToolsのパフォーマンスパネル。ページの動作を記録してメインスレッドの処理・レイアウト・ペイント・JavaScript実行を時系列で可視化し、パフォーマンスボトルネックの特定に使用する。' },
  { term: 'Memory Profiling', aliases: ['memory profiling', 'メモリプロファイリング'], description: 'アプリケーションのメモリ使用量を経時的に記録・分析するパフォーマンス調査手法。Chrome DevToolsのMemoryパネルでHeap Snapshotや割り当てタイムラインを取得し、メモリリークや過剰な消費を特定する。' },
  { term: 'Heap Snapshot', aliases: ['heap snapshot', 'ヒープスナップショット'], description: '特定の時点でJavaScriptのヒープメモリの内容を丸ごとキャプチャしたもの。Chrome DevToolsのMemoryパネルで取得でき、どのオブジェクトがどれだけメモリを占有しているかを分析してメモリリーク調査に使う。' },
  { term: 'バンドルサイズ分析', aliases: ['bundle size analysis'], description: 'WebアプリのJavaScriptバンドルの内訳をモジュールごとに可視化し、サイズ削減の対象を特定する作業。webpack-bundle-analyzerやvite-bundle-visualizerなどのツールを使用する。' },
  { term: 'webpack-bundle-analyzer', aliases: ['bundle-analyzer'], description: 'webpackのバンドル内容をインタラクティブなツリーマップで可視化するツール。各モジュールが占めるサイズを一目で把握でき、大きな依存関係や重複モジュールを発見してバンドルサイズ削減に活用する。' },
  { term: 'WebP', aliases: ['webp'], description: 'Googleが開発した次世代Web向け画像フォーマット。JPEG比で同等品質を25〜34%小さいファイルサイズで実現し、可逆圧縮・非可逆圧縮・アルファチャンネルをサポートする。主要ブラウザで広くサポートされている。' },
  { term: 'AVIF', aliases: ['avif'], description: 'AV1コーデックをベースにした次世代画像フォーマット。WebPよりさらに高い圧縮率を持ち、同等品質でJPEGの約半分のファイルサイズを実現する。HDR・広色域にも対応し普及が進んでいる。' },
  { term: 'Responsive Images', aliases: ['responsive images', 'レスポンシブ画像'], description: 'デバイスのViewportサイズや解像度に応じて最適な画像を配信する技術。`<picture>`要素やsrcset・sizes属性を使い、モバイル端末に過大なサイズの画像を送らず帯域とレンダリング時間を節約する。' },
  { term: 'srcset', aliases: ['srcset属性'], description: 'img要素でブラウザに複数の画像候補とその幅・密度情報を提供するHTML属性。ブラウザがデバイスのDPRや表示サイズに合わせて最適な画像を自動選択し、不要な大きさの画像を読み込まずに済む。' },
  { term: 'sizes属性', aliases: ['sizes'], description: 'img要素でViewportの幅に応じた画像の表示サイズをブラウザに伝えるHTML属性。srcsetと組み合わせてブラウザが最適な画像を選択できるよう助け、レスポンシブ画像の精度を高める。' },
  { term: 'CrUX', aliases: ['crux', 'chrome user experience report'], description: '実際のChromeユーザーのCore Web Vitals計測データを集約したGoogleのデータセット。PageSpeed InsightsやSearch ConsoleでフィールドデータとしてCrUXが参照され、実環境でのパフォーマンス評価に使用される。' },
  { term: 'Time to Interactive', aliases: ['time to interactive', 'tti'], description: 'ページが完全にインタラクティブになるまでの時間。メインスレッドが少なくとも5秒間アイドル状態になり、Long Taskがなくなった時点を計測する指標。JavaScriptの実行量が多いとTTIが増大する。' },
  { term: 'Layout Thrashing', aliases: ['layout thrashing', 'レイアウトスラッシング', 'forced synchronous layout'], description: 'JavaScriptからレイアウト情報を読み取る操作と変更操作を交互に繰り返すことで、ブラウザが強制的に同期的なレイアウト再計算を何度も実行してしまうパフォーマンス問題。offsetHeightやgetBoundingClientRectの多用が原因となる。' },
  { term: 'Throttle', aliases: ['throttle', 'スロットル'], description: '一定時間内に関数が呼び出される頻度を制限するパフォーマンス最適化テクニック。スクロールやマウス移動イベントなど高頻度で発生するイベントの処理回数を間引き、過剰な処理を防ぐ。Debounceと使い分ける。' },
  { term: 'Jank', aliases: ['jank', 'ジャンク'], description: 'フレームレートが60fps（16.67ms/frame）を下回ることで発生するアニメーションやスクロールのカクつき現象。Long TaskやLayout Thrashingが原因で発生し、ユーザー体験を大きく損なう。' },
  { term: 'Navigation Timing', aliases: ['navigation timing'], description: 'ページナビゲーション（リダイレクト・DNS・TCP接続・リクエスト・レスポンス・DOMパース）の各段階の時刻を取得するブラウザAPI。TTFB・DOMContentLoadedなどの指標算出の基盤となる。' },
  { term: 'Resource Timing', aliases: ['resource timing', 'resource timing api'], description: 'ページが読み込む各リソース（画像・スクリプト・スタイルシートなど）の取得に要した時間の詳細を取得するブラウザAPI。ネットワーク遅延やTTFBをリソースごとに計測し、ボトルネックを特定できる。' },
  { term: 'Paint Timing', aliases: ['paint timing', 'paint timing api'], description: 'FCPなどのペイント系パフォーマンス指標の時刻を取得するブラウザAPI。`performance.getEntriesByType(\'paint\')`でfirst-paintとfirst-contentful-paintのタイムスタンプを取得でき、RUM実装の基盤となる。' },
  { term: 'Font Loading', aliases: ['font loading', 'フォント読み込み', 'web font loading'], description: 'Webフォントのダウンロードと適用のプロセス。フォントの読み込み戦略（font-display: swap/optional/blockなど）の選択がFCPやCLS、FOIT/FOUTに大きく影響するため、適切な指定が必要。' },
  { term: 'Static Site Generation', aliases: ['static site generation', '静的サイト生成'], description: 'ビルド時にHTMLを事前生成してCDNから配信するレンダリング方式。サーバー処理が不要でTTFBが極めて短く、パフォーマンスと可用性が高い。頻繁に更新されないコンテンツに最適。' },
  { term: 'Partial Hydration', aliases: ['partial hydration', '部分的ハイドレーション'], description: 'ページ全体ではなくインタラクティブな部分のみをHydrationするレンダリング最適化手法。静的なコンテンツ部分のJavaScriptを送信せず、インタラクティブコンポーネントのみをクライアントで活性化してTTIを改善する。' },
  { term: 'Islands Architecture', aliases: ['islands architecture', 'アイランドアーキテクチャ', 'コンポーネントアイランド'], description: '静的HTMLの海に「インタラクティブなコンポーネントの島」を配置するWebアーキテクチャ。各アイランドは独立してHydrationされ、静的部分はJavaScriptを送信しない。AstroやFreshなどが採用する。' },
  { term: 'Speculation Rules', aliases: ['speculation rules', 'speculation rules api', '投機的ルール'], description: 'ユーザーが次に訪問しそうなページをブラウザが予め先読みまたは先レンダリングするためのJSON形式のルールを記述するAPI。prefetchやprerenderをコードで制御し、ナビゲーション体験を大幅に高速化する。' },
  { term: 'Workbox', aliases: ['workbox'], description: 'GoogleのService Workerツールキット。キャッシュ戦略（StaleWhileRevalidate・NetworkFirst・CacheFirstなど）の実装を簡素化し、PWAのオフライン対応とリソースキャッシュをシンプルに構築できる。' },
  { term: 'Prerender', aliases: ['prerender', 'プリレンダリング', '事前レンダリング'], description: 'ユーザーが訪問する前にページ全体をバックグラウンドでレンダリングしておく技術。Speculation Rules APIやrel="prerender"で指示でき、リンクをクリックした瞬間にレンダリング済みのページを即時表示できる。' },
  { term: 'Module Preload', aliases: ['module preload', 'modulepreload', 'モジュールプリロード'], description: 'ES Modulesとその依存関係を事前にダウンロード・パース・コンパイルするResource Hints。`<link rel="modulepreload">`で指定し、通常のpreloadとは異なりモジュールグラフ全体を先行処理するため動的インポートの待機時間を削減する。' },
  { term: 'Unused JavaScript', aliases: ['unused javascript', '不要なjavascript', 'dead javascript'], description: 'ページの初期表示に不要なJavaScriptコードがバンドルに含まれ読み込まれる問題。Lighthouseの「Remove unused JavaScript」監査で検出でき、Code SplittingやDynamic Importで遅延読み込みすることで改善する。' },
  { term: 'Frame Rate', aliases: ['frame rate', 'フレームレート', 'fps'], description: '1秒間に描画されるフレーム数（Frames Per Second）。Web UIでは60fps（1フレーム16.67ms）が滑らかさの基準とされ、これを下回るとJankとして知覚される。アニメーション最適化の目標値として使用する。' },
  { term: 'Benchmarking', aliases: ['benchmarking', 'ベンチマーキング'], description: 'コードやシステムの処理速度を定量的に計測・比較する行為。ブラウザAPIのperformance.now()やVitest・Jest・benchmark.jsなどのツールを使って実装の高速化効果を客観的に評価する。' },
  { term: 'Memoize', aliases: ['memoize'], description: '関数の計算結果を引数をキーとしてキャッシュし、同じ引数での再呼び出し時にキャッシュ済みの結果を返す最適化技術。ReactのuseMemo・useCallbackはこの原理を応用し、不要な再計算と再レンダリングを防ぐ。' },
  { term: 'Scope Hoisting', aliases: ['scope hoisting', 'モジュール結合', 'スコープホイスティング'], description: '複数のES Moduleを単一の関数スコープにまとめてバンドルする最適化。モジュールごとのクロージャをなくすことでコードサイズを削減し、実行時のパース速度とランタイムパフォーマンスを向上させる。Rollupが先行実装した。' },
  { term: 'Network Throttling', aliases: ['network throttling', 'ネットワーク制限', '帯域制限'], description: 'Chrome DevToolsなどでネットワーク速度を意図的に制限してページのパフォーマンスをテストする手法。3G・4G・低速回線などを模擬し、実際のモバイルユーザーが体験するパフォーマンスを開発環境で再現できる。' },
  { term: 'Font Subsetting', aliases: ['font subsetting', 'フォントサブセット化', 'フォントサブセッティング'], description: '使用する文字のみをWebフォントに含める最適化手法。日本語フォントは数万文字を含むため非常に大きいが、ページで実際に使用する文字だけに絞ることでダウンロードサイズを劇的に削減し、Font Loadingを高速化する。' },
  { term: 'Image Lazy Loading', aliases: ['image lazy loading', 'ネイティブ遅延読み込み', 'native lazy loading'], description: 'img要素に`loading="lazy"`属性を付与することでブラウザが標準サポートするネイティブの遅延読み込み。Viewportに近づいたタイミングで画像を取得し、初期ページロード時のネットワーク消費とリソース優先度を最適化する。' },
  { term: 'Dead Code Elimination', aliases: ['dead code elimination', 'デッドコード除去', 'dce'], description: 'ビルド時に実行されることのないコード（到達不能コード・未使用エクスポートなど）を除去する最適化技術。Tree Shakingとセットで使われ、JavaScriptやTypeScriptのバンドルサイズを削減してダウンロードとパース時間を短縮する。' },
  { term: 'Content Delivery Network', aliases: ['content delivery network'], description: '世界各地にサーバーを配置し、ユーザーに地理的に最も近いサーバーからコンテンツを配信するインフラ。物理的なネットワーク距離を短縮してTTFBを削減し、静的アセットの配信速度を大幅に改善する。' },
  { term: 'Render Pipeline', aliases: ['render pipeline', 'レンダリングパイプライン', 'ブラウザレンダリングパイプライン'], description: 'ブラウザがHTMLから画面を描画するまでの処理段階の全体像。Parse→Style→Layout→Paint→Compositeの各フェーズからなる。各フェーズのコストを理解し、Compositeのみで完結するアニメーションを選択することがパフォーマンス最適化の基本となる。' },
  { term: 'PurgeCSS', aliases: ['purgecss', 'css purging', '未使用css除去'], description: 'HTMLやJavaScriptファイルを解析して実際に使用されているCSSセレクターのみを残し、未使用のCSSを除去するツール。Tailwind CSSと組み合わせて使われることが多く、CSSバンドルサイズを大幅に削減する。' },
  { term: 'Above the Fold', aliases: ['above the fold', 'ファーストビュー', 'atf'], description: 'ページを開いた際にスクロールなしで表示されるコンテンツ領域。このエリアのリソースは優先的に読み込む必要があり、LCP・FCP改善の最重要対象となる。Critical CSSの対象やPriority Hintsのhigh指定はAbove the Foldのコンテンツに適用する。' },
  { term: 'Performance Timeline', aliases: ['performance timeline', 'パフォーマンスタイムライン'], description: 'ブラウザが収集する各種パフォーマンスエントリ（ナビゲーション・リソース・ペイント・ユーザータイミングなど）を時系列で管理するフレームワーク。performance.getEntries()で取得でき、RUM実装やパフォーマンス分析の基盤となる。' },
  { term: '性能を維持', description: '負荷や構成変更があっても必要な性能を保つことです。' },
];
