// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: agileProduct (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // methodology (51), agile (25), Agile (1), culture (1)
  { term: 'アジャイル', description: '小さく作って早く確認しながら進める開発の考え方です。変化に強い一方で、目的や優先順位が曖昧だと迷走しやすくなります。' },
  { term: 'スクラム', description: 'アジャイル実践の代表的な枠組みです。役割、イベント、成果物を明確にして継続的に改善します。' },
  { term: 'スプリント', description: '短い期間で区切って開発と確認を行う単位です。通常は数週間で回し、毎回価値ある成果物を出すことを目指します。' },
  { term: 'プロダクトバックログ', description: '実現したい項目を優先順に並べた一覧です。要求を一気に確定させず、価値に応じて順序づける考え方と相性がよいです。' },
  { term: 'スプリントバックログ', description: 'そのスプリントで実施する作業一覧です。目標との結びつきが見えるように整理すると管理しやすいです。' },
  { term: 'ユーザーストーリー', description: 'ある利用者が、ある目的のために、何をしたいかを短く表したものです。機能中心ではなく、価値中心に話を整理しやすくなります。' },
  { term: 'バックログ精緻化', description: '要求項目の内容、粒度、優先度、完了条件を整えていく作業です。曖昧なまま実装へ進まないための重要な活動です。' },
  { term: 'ベロシティ', description: '一定期間でこなせる仕事量の実績指標です。絶対値で競うものではなく、自チームの計画精度向上に使うのが本来の姿です。' },
  { term: 'スクラムマスター', description: 'チームが円滑に動けるよう障害除去や進め方支援を行う役割です。管理者ではなく、進め方を整える支援役としての性格が強いです。' },
  { term: '振り返り項目', aliases: ['retrospective items'], description: 'スプリントやプロジェクトの振り返りで議論する課題・改善点・良かった点のリストです。アクションアイテムに落とし込むことで改善を継続します。' },
  { term: 'スクラム開発', description: '役割とイベントを定め、反復的に価値提供するアジャイル開発の代表的なフレームワーク。' },
  { term: 'バックログ', description: '実施候補の作業、要求、改善項目を優先順位付きで管理した一覧。' },
  { term: 'スプリントプランニング', description: '次のスプリントで何を実施するか、どう進めるかを決める計画会議。' },
  { term: 'デイリースクラム', description: '日々の進捗、障害、予定を短時間で共有し、認識を揃える定例会。' },
  { term: 'スプリントレビュー', description: 'スプリント成果を関係者へ共有し、フィードバックを得る会議。' },
  { term: 'スプリント計画', aliases: ['sprint planning'], description: 'スプリントの目標と実施するバックログアイテムをチームで決定する会議です。' },
  { term: '開発モデル', aliases: ['development model'], description: 'ソフトウェア開発の進め方を体系化したフレームワーク。ウォーターフォール、アジャイルなど多数が存在する。' },
  { term: 'ウォーターフォールモデル', aliases: ['waterfall model'], description: '要件定義から設計・製造・テスト・リリースまでを順番に進める線形の開発モデル。前工程の成果物を次工程の入力とする。' },
  { term: 'カスケードウォーターフォールモデル', aliases: ['cascade waterfall model'], description: 'ウォーターフォールモデルの変形で各工程間にフィードバックループを持たせ前工程への差し戻しを許容する開発モデル。' },
  { term: 'プロトタイピングモデル', aliases: ['prototyping model'], description: '開発初期にプロトタイプを作成しユーザーのフィードバックを得ながら要件を確定させる開発モデル。' },
  { term: 'SDLC', aliases: ['sdlc'], description: 'Software Development Life Cycleの略。ソフトウェア開発の全工程を定義したライフサイクルモデル。' },
  { term: 'インクリメンタルモデル', aliases: ['incremental model'], description: 'システムを小さな増分に分割して段階的に開発・リリースしていく開発モデル。' },
  { term: 'スパイラル開発', aliases: ['スパイラルモデル', 'spiral development', 'spiral model'], description: 'リスク分析を軸に計画・設計・実装・評価を繰り返すBoehm提唱の開発モデル。リスク駆動型反復開発。' },
  { term: 'アジャイル開発モデル', aliases: ['agile development model'], description: '短い反復サイクルで動作するソフトウェアを継続的に提供するアジャイル宣言に基づく開発モデル群の総称。' },
  { term: 'アジリティ', aliases: ['agility'], description: '変化に素早く適応する組織・チームの能力。アジャイル開発において重要な概念。' },
  { term: 'ICONIX', aliases: ['iconix'], description: 'ユースケース駆動でロバストネス分析を中心に据えた軽量オブジェクト指向開発プロセス。' },
  { term: 'コンテキスト中心モデル', aliases: ['context-centered model'], description: 'システムの使われる文脈・状況を中心に分析・設計を進める開発アプローチ。' },
  { term: 'コンテンツ中心モデル', aliases: ['content-centered model'], description: '扱うデータやコンテンツの構造を中心に据えて開発を進めるモデル。データ中心アプローチとも関連する。' },
  { term: 'EXE標準工程モデル', aliases: ['exe標準工程モデル'], description: '特定組織が定義した標準的な開発工程モデル。各フェーズの成果物と検証基準を規定する。' },
  { term: '共通フレーム', aliases: ['slcp-jcf'], description: '日本のソフトウェア開発・取引における共通の枠組み。SLCP-JCF（共通フレーム）として標準化されている。' },
  { term: '要件定義工程', description: 'システムが実現すべき機能・性能・制約を明確化する工程。利害関係者の要望を要件として文書化する。' },
  { term: '基本設計工程', description: '要件定義をもとにシステムの外部仕様・アーキテクチャを設計する工程。画面・帳票・DB概要設計を含む。' },
  { term: '詳細設計工程', description: '基本設計を受けてモジュール単位の内部仕様・ロジックを設計する工程。プログラム仕様書を作成する。' },
  { term: '製造＋UT工程', aliases: ['製造＋ut工程'], description: 'ソースコードのコーディングとユニットテスト（単体テスト）を合わせて実施する開発工程。' },
  { term: 'テーラリング', aliases: ['tailoring'], description: '標準プロセスをプロジェクトの特性に合わせてカスタマイズすること。工程・成果物・レビュー基準などを調整する。' },
  { term: '開発プロセス設計', aliases: ['development process design'], description: 'プロジェクトに適した開発手法・工程・成果物・品質基準を定義しプロセスを設計する活動。' },
  { term: '開発と製造', aliases: ['development and construction'], description: 'ソフトウェア開発における設計（開発）とコーディング（製造）の二つのフェーズを区別した概念。' },
  { term: '成果物フロー', aliases: ['deliverable flow'], description: '各開発工程で作成される成果物の入出力関係を示したフロー。工程間のドキュメント依存関係を明示する。' },
  { term: '構造化手法', aliases: ['sa/sd', 'structured method'], description: 'DFD・ERDなどの記法を用いてシステムを機能・データ構造から分析・設計する伝統的な手法。' },
  { term: 'POA', aliases: ['poa'], description: 'Process-Oriented Approachの略。業務プロセスを中心に据えてシステムを分析・設計する手法。' },
  { term: 'DOA', aliases: ['doa'], description: 'Data-Oriented Approachの略。データ構造を中心に据えてシステムを分析・設計する手法。' },
  { term: 'OOA', aliases: ['ooa'], description: 'Object-Oriented Analysisの略。オブジェクトの概念を用いてシステムを分析する手法。クラス・関連・振る舞いを定義する。' },
  { term: 'EXE標準プロセスモデル', aliases: ['exe標準プロセスモデル', 'exe standard process model'], description: '特定組織が定義した標準開発プロセスモデルで、各フェーズの成果物と検証基準を明示したものです。' },
  { term: '要件定義フェーズ', aliases: ['requirements definition phase'], description: 'ステークホルダーのニーズに基づき、システムが満たすべき機能・性能・制約を明確化してドキュメント化するフェーズです。' },
  { term: '基本設計フェーズ', aliases: ['basic design phase'], description: '要件を基にシステムの外部仕様とアーキテクチャを設計するフェーズで、画面・帳票・データベース概要の設計を含みます。' },
  { term: '詳細設計フェーズ', aliases: ['detailed design phase'], description: '基本設計に続き、モジュール単位で内部仕様とロジックを設計し、プログラム仕様書を作成するフェーズです。' },
  { term: '製造・単体テストフェーズ', aliases: ['construction and unit testing phase'], description: 'ソースコードを記述し、単体テストを実施する開発フェーズです。' },
  { term: '要件トレーサビリティ', description: '要望から設計・実装・テストまで各要件がどのように反映されているかを追跡できる性質。' },
  { term: 'JIS X 0129-1', aliases: ['jis x 0129-1'], description: 'ソフトウェア品質特性と副特性を定義したJIS規格。ISO/IEC 9126の日本語版。' },
  { term: 'ソフトウェア品質特性モデル', description: 'ソフトウェアの品質を体系的に定義するモデル。JIS X 0129-1やISO 25010が代表例。' },
  { term: '機能性', description: 'JIS X 0129-1における品質特性の一つ。規定された要求を満足する機能を持つ度合い。' },
  { term: '使用性', description: 'JIS X 0129-1における品質特性の一つ。特定の利用状況でユーザーが目標を達成できる度合い。' },
  { term: '効率性', description: 'JIS X 0129-1における品質特性の一つ。性能と資源使用量のバランスに関する品質特性。' },
  { term: '移植性', description: 'JIS X 0129-1における品質特性の一つ。異なる環境へ移行できる度合い。' },
  { term: '有効性', description: 'JIS X 0129-1における利用時品質の一つ。ユーザーが目標を達成できる正確さと完全さ。' },
  { term: '満足度', description: '利用時品質の一つ。ユーザーがシステム利用時に感じる肯定的な感情の度合い。' },
  { term: 'JUASガイドライン', aliases: ['juasガイドライン'], description: 'JUAS（日本情報システム・ユーザー協会）が公開する情報システム開発に関するガイドライン群。' },
  { term: 'IPA', aliases: ['ipa'], description: '情報処理推進機構の略。日本のIT人材育成・情報セキュリティ・ソフトウェア品質向上を推進する独立行政法人。' },
  { term: 'JUAS', aliases: ['juas'], description: '日本情報システム・ユーザー協会の略。ユーザー企業のIT活用を支援する日本の業界団体。' },
  { term: '分析', aliases: ['analysis'], description: '要求・問題・ドメインを理解するためにデータや情報を詳細に調査・整理する活動。' },
  { term: '分析力', aliases: ['analytical capability'], description: '問題や要件を正確に理解し本質を見抜く能力。システム開発において要件定義の品質を左右する。' },
  { term: 'ドキュメントフレームワーク', aliases: ['document framework'], description: 'プロジェクトで作成するドキュメントの種類・構造・命名規則を定めた枠組み。' },
  { term: '品質特性', aliases: ['quality characteristic'], description: 'ソフトウェアの品質を構成する特性の集合。JIS X 0129-1やISO 25010で定義される。' },
  { term: '外部品質', aliases: ['external quality'], description: 'ユーザーや外部から観測できるソフトウェアの品質。機能性・使用性・性能などが含まれる。' },
  { term: '内部品質', aliases: ['internal quality'], description: 'ソースコードや設計書の品質。可読性・保守性・テスタビリティが主な特性。' },
  { term: '利用時品質', aliases: ['quality in use'], description: '実際の利用状況における有効性・効率性・満足度などを含む品質の観点。' },
  { term: '企画品質', aliases: ['planning quality'], description: 'プロジェクト企画・要件定義フェーズの成果物の品質。上流品質とも呼ばれ後工程の品質を左右する。' },
  { term: '凡人', description: '特別な才能や突出したスキルを持たない普通の人。エンジニアリングの文脈では「天才ではない普通のエンジニアが継続的に成果を出すには仕組みや習慣が重要」という議論で使われる。' },
  { term: '完了の定義', aliases: ['dod'], description: 'スクラムにおいてアイテムやスプリントが完了したとみなすための共有された基準。コードレビュー、テスト合格、ドキュメント更新などの条件を明文化する。' },
  { term: 'リファインメント', aliases: ['backlog refinement', 'バックログリファインメント'], description: 'スクラムのプロダクトバックログの内容を詳細化・見積もり・優先順位付けする継続的な活動。バックログリファインメントとも呼ばれ、スプリントプランニングの準備となる。' },
  { term: 'スプリントレトロスペクティブ', aliases: ['sprint retrospective'], description: 'スプリント終了後にチームがプロセス・協力・ツールを振り返り、継続的改善のアクションを特定するスクラムイベント。Keep/Problem/Tryなどのフォーマットが使われる。' },
  { term: 'インセプションデッキ', aliases: ['inception deck'], description: 'プロジェクト開始時にチームとステークホルダーが共通認識を持つための10の問いからなるアジャイルプラクティス。プロジェクトの目的、制約、リスクを共有する。' },
  { term: 'エレベーターピッチ', aliases: ['elevator pitch'], description: '製品や機能のコアバリューを短時間（エレベーターに乗っている程度）で伝えるための簡潔な説明フォーマット。インセプションデッキの一要素としても使われる。' },
  { term: 'カンバン', aliases: ['kanban'], description: '作業の流れを可視化し、WIP制限によってフロー効率を最大化するリーン由来の開発手法。タスクをカードとして視覚化したボードで進捗を管理する。' },
  { term: 'サイクルタイム', aliases: ['cycle time'], description: '作業開始から完了までにかかる実際の時間。カンバンやリーンで重要な指標であり、サイクルタイムを短縮することでフロー効率を改善する。' },
  { term: 'フロー効率', aliases: ['flow efficiency'], description: '作業の全体時間に占める付加価値活動（実際の作業）の割合。待ち時間や手戻りを排除してフロー効率を高めることがリーン思考の目標。' },
  { term: 'リソース効率', aliases: ['resource efficiency'], description: '人や設備などのリソースをどれだけ活用できているかの指標。リソース効率を最大化しようとするとWIPが増えフロー効率が低下するトレードオフが存在する。' },
  { term: '小さく作って改善', aliases: ['iterate and improve', '小さく始める', '漸進的改善'], description: '初期実装を最小限に留めてリリースし、フィードバックをもとに継続的に改善するアプローチ。MVPやアジャイル開発の核となる考え方で、過剰設計を防ぎユーザーニーズへの対応速度を高める。完璧を待たずに小さく動くものを作って学ぶリーン開発の哲学。' },
];
