// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: linux (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // shell (145), linux (80)
  { term: 'Unix', aliases: ['unix'], description: '1969年にAT&Tベル研究所で開発されたマルチタスク・マルチユーザー対応のオペレーティングシステム。現代のLinuxやmacOSの設計思想の源流となった。' },
  { term: 'POSIX', aliases: ['posix', 'portable operating system interface'], description: 'IEEEが策定したUnix系OSの移植性を高めるための標準規格群。システムコール、シェル、ユーティリティのAPIを定義する。' },
  { term: 'GNU', aliases: ['gnu', 'gnu\'s not unix'], description: 'Richard Stallmanが1983年に立ち上げたフリーソフトウェアプロジェクト。GCCやglibcなどLinuxシステムの基盤となるツールを提供する。' },
  { term: 'RHEL', aliases: ['rhel', 'red hat enterprise linux'], description: 'Red Hatが提供するエンタープライズ向けLinuxディストリビューション。長期サポートと商用サポートが特徴で、企業環境に広く採用される。' },
  { term: 'Oracle Linux', aliases: ['oracle linux'], description: 'OracleがRHELをベースに提供するLinuxディストリビューション。RHELと完全バイナリ互換を持ち、Oracle製品との親和性が高い。' },
  { term: 'Ubuntu', aliases: ['ubuntu'], description: 'Canonicalが支援するDebianベースのLinuxディストリビューション。使いやすさと定期的なLTSリリースで世界的に人気が高い。' },
  { term: 'Debian', aliases: ['debian'], description: 'コミュニティ主導で開発されるLinuxディストリビューション。安定性と自由ソフトウェアの原則を重視し、多くのディストリビューションの派生元となっている。' },
  { term: 'CentOS', aliases: ['centos'], description: 'RHELのソースコードをベースにしたコミュニティ版Linuxディストリビューション。2021年末にCentOS Streamへ移行が決定された。' },
  { term: 'CentOS Stream', aliases: ['centos stream'], description: 'RHELの開発上流として位置づけられるローリングリリース型のLinuxディストリビューション。CentOSの後継として提供される。' },
  { term: 'AlmaLinux', aliases: ['almalinux'], description: 'CentOS 8の後継として開発されたRHEL互換のLinuxディストリビューション。CloudLinuxが主導するコミュニティプロジェクト。' },
  { term: 'Rocky Linux', aliases: ['rocky linux'], description: 'CentOSの共同創設者Gregory Kurtzerが主導するRHEL互換Linuxディストリビューション。エンタープライズ環境向けに設計されている。' },
  { term: 'Fedora', aliases: ['fedora'], description: 'Red Hatが支援するコミュニティ主導のLinuxディストリビューション。最新技術を積極的に取り入れRHELの上流として機能する。' },
  { term: 'openSUSE', aliases: ['opensuse'], description: 'SUSEが支援するオープンソースのLinuxディストリビューション。安定版のLeapとローリングリリースのTumbleweedの2系統がある。' },
  { term: 'SUSE Linux', aliases: ['suse linux', 'suse'], description: 'ドイツのSUSEが提供するLinuxディストリビューション群の総称。エンタープライズ向けSLES（SUSE Linux Enterprise Server）が主力製品。' },
  { term: 'Linux Mint', aliases: ['linux mint'], description: 'Ubuntuベースの使いやすさを重視したLinuxディストリビューション。Windows移行ユーザーに人気で、Cinnamonデスクトップが特徴的。' },
  { term: 'Arch Linux', aliases: ['arch linux'], description: 'シンプルさと最新性を重視したローリングリリース型Linuxディストリビューション。pacmanパッケージマネージャとAURリポジトリが特徴。' },
  { term: 'Gentoo', aliases: ['gentoo'], description: 'ソースからコンパイルしてインストールするLinuxディストリビューション。Portageパッケージシステムで細かいビルドオプション最適化が可能。' },
  { term: 'FreeBSD', aliases: ['freebsd'], description: 'BSDライセンスで配布されるUnix系オペレーティングシステム。安定性とネットワーク性能に優れ、サーバー用途に広く利用される。' },
  { term: 'OpenBSD', aliases: ['openbsd'], description: 'セキュリティを最優先に設計されたBSD系オペレーティングシステム。コード監査を徹底し、SSHなど多くのセキュリティツールの発祥地。' },
  { term: 'NetBSD', aliases: ['netbsd'], description: '高い移植性を特徴とするBSD系オペレーティングシステム。多様なCPUアーキテクチャをサポートし「どんなハードウェアでも動く」がモットー。' },
  { term: 'WSL', aliases: ['wsl', 'windows subsystem for linux'], description: 'Windows上でLinuxバイナリをネイティブ実行できるWindows Subsystem for Linux。WSL2ではLinuxカーネルを内包し完全な互換性を持つ。' },
  { term: 'WSL2', aliases: ['wsl2', 'windows subsystem for linux 2'], description: '仮想化技術を用いてWindows上に本物のLinuxカーネルを実行するWSLの第2世代。完全なシステムコール互換とDockerサポートが特徴。' },
  { term: 'ディストリビューション', aliases: ['ディストロ', 'distro'], description: 'Linuxカーネルに各種ソフトウェアやパッケージ管理システムを組み合わせて配布されるOSパッケージ。UbuntuやRHELなど多数存在する。' },
  { term: 'LTS', aliases: ['lts', 'long term support', '長期サポート'], description: 'Long Term Supportの略。通常より長期間（5年程度）のセキュリティアップデートとバグ修正が提供されるリリースバージョン。' },
  { term: 'サポートライフサイクル', description: 'OSやソフトウェアのバージョンがセキュリティパッチやバグ修正のサポートを受けられる期間。EOL（End of Life）でサポートが終了する。' },
  { term: 'アップストリーム', aliases: ['upstream'], description: 'ソフトウェアの開発元や上流プロジェクトを指す。ディストリビューションはアップストリームのコードを取り込んでパッケージ化する。' },
  { term: 'ダウンストリーム', aliases: ['downstream'], description: '上流（アップストリーム）プロジェクトを取り込んで配布する下流プロジェクトを指す。ディストリビューションはLinuxカーネルのダウンストリームにあたる。' },
  { term: 'BIOS', aliases: ['bios', 'basic input/output system'], description: 'PCのマザーボードに搭載されたファームウェア。コンピュータ起動時にハードウェアを初期化しブートローダーを起動する役割を持つ。' },
  { term: 'UEFI', aliases: ['uefi', 'unified extensible firmware interface'], description: 'BIOSの後継となる現代的なファームウェアインターフェース。GPTパーティション、Secure Boot、グラフィカルなセットアップ画面などをサポートする。' },
  { term: 'GRUB', aliases: ['grub', 'grand unified bootloader', 'gnu grub'], description: 'GNU GRand Unified Bootloaderの略。Linuxシステムで広く使われるブートローダー。複数のOSやカーネルバージョンを選択して起動できる。' },
  { term: 'GRUB2', aliases: ['grub2', 'grand unified bootloader 2', 'gnu grub 2'], description: 'GRUBの第2世代。モジュール式設計により多様なファイルシステムやアーキテクチャをサポートし、現在のLinuxディストリビューションの標準ブートローダー。' },
  { term: 'ブートローダー', aliases: ['bootloader'], description: 'コンピュータの電源投入後にファームウェアから制御を受け取り、OSカーネルをメモリに読み込んで実行するプログラム。GRUBが代表的。' },
  { term: 'initramfs', aliases: ['initial ram filesystem'], description: 'カーネル起動直後にメモリ上に展開される初期RAMファイルシステム。実際のルートファイルシステムをマウントするために必要なドライバやツールを含む。' },
  { term: 'initrd', aliases: ['initial ram disk'], description: 'カーネル起動時に使用される初期RAMディスクイメージ。initramfsの旧称・旧形式で、現在のLinuxでは主にinitramfsが使われる。' },
  { term: 'MBR', aliases: ['mbr', 'master boot record'], description: 'ディスクの先頭512バイトに格納されるマスターブートレコード。ブートコードとパーティションテーブルを含み、最大4つのプライマリパーティションをサポートする。' },
  { term: 'GPT', aliases: ['gpt', 'guid partition table'], description: 'GUIDパーティションテーブルの略。MBRの後継として設計された現代的なパーティション方式。2TB超のディスクや128以上のパーティションをサポートする。' },
  { term: 'EFI System Partition', aliases: ['efi system partition', 'esp', 'efiシステムパーティション'], description: 'UEFIファームウェアがブートローダーやEFIアプリケーションを格納・実行するために使用する特殊なFATパーティション。' },
  { term: 'カーネルパラメータ', aliases: ['kernel parameter', 'カーネルコマンドライン'], description: 'Linuxカーネルにブート時や実行時に渡す設定値。GRUBのカーネルコマンドラインやsysctlで指定し、起動オプションやカーネル動作を制御する。' },
  { term: 'runlevel', aliases: ['ランレベル'], description: 'SysVinitにおけるシステムの動作状態を表す数値（0〜6）。例えば0は電源オフ、3はマルチユーザーモード、5はグラフィカルモードを示す。' },
  { term: 'ターゲット', aliases: ['target', 'systemd target'], description: 'systemdにおけるrunlevelの相当概念。multi-user.targetやgraphical.targetなど、システムの動作状態をユニット群として定義する。' },
  { term: 'SysVinit', aliases: ['sysvinit', 'system v init', 'sysv init'], description: '伝統的なUnix/Linuxの初期化システム。/etc/inittabとランレベルに基づいてサービスを起動するinitプロセスを使用する。systemdに置き換えられつつある。' },
  { term: 'Upstart', aliases: ['upstart'], description: 'UbuntuなどでSysVinitの代替として採用されたイベント駆動型のinitシステム。現在はほとんどのディストリビューションでsystemdに置き換えられている。' },
  { term: 'ブートプロセス', aliases: ['boot process'], description: '電源投入からOSが使用可能になるまでの一連の起動手順。BIOS/UEFI→ブートローダー→カーネル→init/systemdの順で処理が進む。' },
  { term: 'multi-user.target', description: 'systemdのターゲットユニットの一つ。ネットワークが有効でGUIなしのマルチユーザー環境を表し、SysVinitのrunlevel 3に相当する。' },
  { term: 'graphical.target', description: 'systemdのターゲットユニットの一つ。グラフィカルデスクトップ環境が起動した状態を表し、SysVinitのrunlevel 5に相当する。' },
  { term: 'rescue.target', description: 'systemdのシングルユーザーレスキューモードを表すターゲット。root権限で最小限のサービスのみ起動し、システム修復に使用する。' },
  { term: 'emergency.target', description: 'systemdの緊急モードターゲット。rescue.targetよりさらに最小限の環境で起動し、重大なシステム障害時の診断・修復に使用する。' },
  { term: 'カーネルモジュール', aliases: ['kernel module'], description: 'Linuxカーネルに動的にロード・アンロードできる機能拡張単位。デバイスドライバやファイルシステムなどを必要時のみカーネルに組み込める。' },
  { term: 'lsmod', description: '現在Linuxカーネルにロードされているモジュールの一覧を表示するコマンド。モジュール名、サイズ、使用数を確認できる。' },
  { term: 'modprobe', description: 'Linuxカーネルモジュールをロードまたはアンロードするコマンド。依存関係を自動解決してモジュールをロードする点でinsmodより高機能。' },
  { term: 'insmod', description: '指定したカーネルモジュールファイルをLinuxカーネルに直接ロードするコマンド。依存関係の解決は行わない低レベルコマンド。' },
  { term: 'rmmod', description: 'Linuxカーネルからモジュールをアンロードするコマンド。使用中のモジュールはアンロードできない。' },
  { term: 'modinfo', description: 'カーネルモジュールの詳細情報（作者、バージョン、パラメータ、依存関係など）を表示するコマンド。' },
  { term: 'カーネルパニック', aliases: ['kernel panic'], description: 'Linuxカーネルが回復不能なエラーを検出した際に発生するシステムクラッシュ状態。エラーメッセージを出力してシステムを停止または再起動する。' },
  { term: 'uname', description: 'システムのカーネルバージョン、OS名、ホスト名などのシステム情報を表示するコマンド。uname -aですべての情報を一括表示できる。' },
  { term: '/proc', aliases: ['proc filesystem', 'procfs'], description: 'Linuxカーネルが提供する仮想ファイルシステム。実行中のプロセス情報やカーネルパラメータをファイルとして公開し、sysctlでも参照される。' },
  { term: '/sys', aliases: ['sysfs'], description: 'カーネルのデバイス・ドライバ情報を公開する仮想ファイルシステム（sysfs）。/procよりも整理された構造でデバイス管理情報を提供する。' },
  { term: 'sysctl', description: '実行中のLinuxカーネルパラメータを読み書きするコマンドおよびインターフェース。/proc/sys以下のパラメータを操作し、ネットワーク設定などに利用する。' },
  { term: 'dmesg', description: 'Linuxカーネルのリングバッファに記録されたメッセージを表示するコマンド。起動時のハードウェア検出やドライバエラーの確認に使用する。' },
  { term: 'OOMキラー', aliases: ['oomキラー', 'oom killer', 'out-of-memory killer'], description: 'システムのメモリが枯渇した際にLinuxカーネルが動作させるメモリ回収機構。使用メモリ量などに基づいてプロセスを強制終了させる。' },
  { term: 'シェル', aliases: ['shell'], description: 'ユーザーとOSカーネルの間に介在するコマンドインタプリタ。コマンドの入力受付、パイプ処理、スクリプト実行などを担う。bash・zshが代表的。' },
  { term: 'bash', aliases: ['bourne again shell'], description: 'GNU Projectが開発したBourne-Againシェル。LinuxのデフォルトシェルとしてWindowsやmacOSでも広く利用される高機能シェル。' },
  { term: 'zsh', aliases: ['z shell'], description: 'bash互換の高機能シェル。タブ補完、プラグイン機能、テーマカスタマイズが優れ、macOSのデフォルトシェルとしても採用されている。' },
  { term: 'ksh', aliases: ['korn shell'], description: 'AT&TのDavid Kornが開発したKornシェル。スクリプト互換性が高く、商用Unixシステムで広く利用される。' },
  { term: 'tcsh', aliases: ['tenex c shell'], description: 'cshを拡張したシェル。コマンド補完やコマンドラインの編集機能を追加したC Shell互換シェル。' },
  { term: 'fish', aliases: ['fish shell', 'friendly interactive shell'], description: 'ユーザーフレンドリーを重視したモダンなシェル。自動補完、構文ハイライト、豊富なドキュメントが特徴で設定なしで使いやすい。' },
  { term: 'シェルスクリプト', aliases: ['shell script'], description: 'シェルコマンドをファイルに記述して自動実行できるようにしたスクリプト。システム管理の自動化やバッチ処理に広く利用される。' },
  { term: 'シェバン', aliases: ['shebang', 'sha-bang', '#!/'], description: 'スクリプトファイルの先頭に記述する「#!」で始まる行。実行するインタプリタのパス（例：#!/bin/bash）を指定する。' },
  { term: 'エクスポート', aliases: ['export'], description: '【シェル】シェル変数を子プロセスに引き継ぐ環境変数として設定するexportコマンドの操作。exportコマンドで変数を環境変数化する。 【OCI APEX】アプリや設定を外部へ書き出す操作。' },
  { term: 'エイリアス', aliases: ['alias'], description: 'シェルで長いコマンドや頻繁に使うコマンドに短い名前を付ける機能。aliasコマンドで定義し、ドットファイルに記述して永続化する。' },
  { term: 'ヒアドキュメント', aliases: ['here document', 'heredoc'], description: 'シェルスクリプト内で複数行の入力を標準入力として渡す構文（<<EOF…EOF）。設定ファイル生成やコマンドへの複数行データ入力に使用する。' },
  { term: 'コマンド置換', aliases: ['command substitution'], description: 'シェルスクリプトでコマンドの出力結果を変数や別のコマンドの引数として使用する構文。$(command)またはバッククォート記法を使う。' },
  { term: 'サブシェル', aliases: ['subshell'], description: '親シェルから独立して実行されるシェルプロセス。丸括弧()でコマンドを囲むと生成され、環境変数の変更が親シェルに影響しない。' },
  { term: '標準入力', aliases: ['stdin'], description: 'プログラムがデータを受け取るデフォルトの入力ストリーム（ファイルディスクリプタ0）。通常はキーボード入力で、<リダイレクトやパイプで変更できる。' },
  { term: '標準出力', aliases: ['stdout'], description: 'プログラムが通常の結果を出力するデフォルトのストリーム（ファイルディスクリプタ1）。通常は端末に表示され、>リダイレクトやパイプで変更できる。' },
  { term: '標準エラー出力', aliases: ['stderr'], description: 'プログラムがエラーメッセージを出力するデフォルトのストリーム（ファイルディスクリプタ2）。2>でリダイレクトでき、標準出力と独立して扱える。' },
  { term: 'ジョブ制御', aliases: ['job control'], description: 'シェルにおいてプロセスをフォアグラウンド・バックグラウンドで管理する仕組み。jobs、fg、bgコマンドでジョブを操作できる。' },
  { term: 'フォアグラウンド', aliases: ['foreground'], description: '端末を占有して対話的に実行されているプロセスの実行状態。Ctrl+Zでバックグラウンドに送り、fgで前面に戻せる。' },
  { term: 'バックグラウンド', aliases: ['background'], description: '端末を占有せずに別タスクとして実行されているプロセスの実行状態。コマンドの末尾に&を付けることでバックグラウンド実行できる。' },
  { term: 'nohup', description: 'コマンドをSIGHUP（端末切断シグナル）を無視して実行するコマンド。SSHセッションが切れても処理を継続させるために使用する。' },
  { term: 'screen', aliases: ['gnu screen'], description: '端末マルチプレクサソフトウェア。複数の仮想端末セッションを管理でき、SSH切断後も処理を継続させるデタッチ機能を持つ。' },
  { term: 'tmux', description: 'screenの後継として広く使われる端末マルチプレクサ。ウィンドウ分割、セッション管理、設定の柔軟性に優れる。' },
  { term: 'コマンドヒストリ', aliases: ['command history', 'ヒストリ'], description: 'シェルが過去に実行したコマンドを記録する機能。historyコマンドで参照でき、Ctrl+Rで検索、!!で直前コマンド再実行などができる。' },
  { term: 'タブ補完', aliases: ['tab completion', 'コマンド補完'], description: 'コマンドやファイル名の入力途中にTabキーを押すと候補を自動補完するシェルの機能。作業効率を大幅に向上させる。' },
  { term: 'ドットファイル', aliases: ['dotfile', '.bashrc', '.profile'], description: 'Unixシステムでファイル名がドット（.）で始まる隠しファイル。~/.bashrc、~/.vimrcなどアプリケーションの設定ファイルに広く使われる。' },
  { term: 'パーミッション', aliases: ['permission', 'ファイルパーミッション'], description: 'Unixファイルシステムにおけるファイル・ディレクトリへのアクセス権限。所有者・グループ・その他ユーザーに対して読み取り/書き込み/実行権を設定する。' },
  { term: 'chmod', description: 'ファイルやディレクトリのパーミッション（アクセス権限）を変更するコマンド。数値表記（755など）またはシンボル表記（u+xなど）で指定する。' },
  { term: 'chown', description: 'ファイルやディレクトリの所有者とグループを変更するコマンド。root権限が必要で、chown user:group fileの形式で使用する。' },
  { term: 'chgrp', description: 'ファイルやディレクトリの所有グループを変更するコマンド。chownでも同様の操作が可能だが、グループのみ変更する専用コマンド。' },
  { term: 'umask', description: '新規作成ファイル・ディレクトリのデフォルトパーミッションを制限するマスク値。指定したビットに対応するパーミッションが除外される。' },
  { term: 'スティッキービット', aliases: ['sticky bit'], description: 'ディレクトリに設定するとそのディレクトリ内のファイルをファイル所有者のみが削除できるようにするパーミッションフラグ。/tmpに設定されている。' },
  { term: '隠しファイル', aliases: ['hidden file', '.ファイル'], description: 'Unixシステムでファイル名がドット（.）で始まるファイル。ls -aオプションを使わなければ通常は一覧に表示されない。' },
  { term: '/etc', description: 'Linuxシステムの設定ファイルを格納する標準ディレクトリ。/etc/passwd、/etc/fstab、/etc/hostsなどシステム全体の設定が集約される。' },
  { term: '/var', description: 'システムの可変データ（ログ、スプール、キャッシュ、PIDファイルなど）を格納する標準ディレクトリ。/var/logや/var/spoolが代表的なサブディレクトリ。' },
  { term: '/tmp', description: 'システム一時ファイルを格納するディレクトリ。再起動時に削除されるため一時的なデータのみを置き、スティッキービットが設定されている。' },
  { term: '/opt', description: 'オプションの追加ソフトウェアパッケージをインストールするための標準ディレクトリ。パッケージマネージャを使わないソフトウェアをインストールする際に使用される。' },
  { term: '/usr', description: 'ユーザー向けのコマンド、ライブラリ、ドキュメントが格納される大規模ディレクトリ。/usr/bin、/usr/lib、/usr/shareなど多くのサブディレクトリを持つ。' },
  { term: '/home', description: '各ユーザーのホームディレクトリが格納される標準ディレクトリ。個人の設定ファイル、ドキュメント、ダウンロードなどが保存される。' },
  { term: '/boot', description: 'カーネルイメージ、initramfs、GRUBの設定ファイルなどブートに必要なファイルを格納するディレクトリ。' },
  { term: '/dev', description: 'デバイスファイルが格納される仮想ディレクトリ。/dev/sda（ディスク）、/dev/null、/dev/randomなどハードウェアをファイルとして表現する。' },
  { term: '/run', description: '起動中のシステムランタイム情報（PIDファイル、ソケット、ロックファイルなど）を格納するtmpfsマウントのディレクトリ。再起動時に内容が消える。' },
  { term: 'FHS', aliases: ['fhs', 'filesystem hierarchy standard'], description: 'Filesystem Hierarchy Standardの略。Linuxのディレクトリ構造と各ディレクトリの用途を定めた標準規格。/usr、/var、/etcなどの役割を定義する。' },
  { term: '/etc/fstab', aliases: ['fstab'], description: 'システム起動時に自動マウントするファイルシステムの設定ファイル。デバイス、マウントポイント、ファイルシステムタイプ、オプションを記述する。' },
  { term: 'devtmpfs', description: 'カーネルがデバイスファイルを動的に管理するための仮想ファイルシステム。/devにマウントされudevと連携してデバイスファイルを自動作成する。' },
  { term: 'CLI', aliases: ['cli', 'command line interface', 'コマンドラインインターフェース'], description: 'コマンドを文字で入力して操作するインターフェースです。自動化、スクリプト化、大量操作と相性がよく、GUIより再現性を高めやすいです。' },
  { term: 'namespace', aliases: ['linux namespace', '名前空間'], description: '【Linux】Linuxカーネルのリソース分離機能。PID、ネットワーク、ファイルシステムなど各種リソースを独立した名前空間に隔離し、コンテナの基盤技術となっている。 【OCI APEX】Object Storageの論理的な名前空間。' },
  { term: 'rm', aliases: ['remove'], description: 'Linuxのファイルやディレクトリを削除するコマンド。`-rf`オプションで再帰削除できるが取り消しが効かないため、実行前に必ず対象を確認することが重要。' },
  { term: 'ls', description: 'カレントディレクトリまたは指定ディレクトリのファイル・ディレクトリ一覧を表示するコマンド。`-la`で隠しファイルや詳細情報も確認できる。' },
  { term: 'pwd', aliases: ['print working directory'], description: '現在の作業ディレクトリの絶対パスを表示するコマンド。スクリプト内でカレントディレクトリを確認する際に使われる。' },
  { term: 'mkdir', aliases: ['make directory'], description: '新しいディレクトリを作成するコマンド。`-p`オプションで中間ディレクトリも一括作成できる。' },
  { term: 'cp', aliases: ['copy'], description: 'ファイルやディレクトリをコピーするコマンド。`-r`オプションでディレクトリを再帰的にコピーできる。' },
  { term: 'mv', aliases: ['move'], description: 'ファイルやディレクトリを移動またはリネームするコマンド。移動先が同一ファイルシステム内であれば実体の移動は発生しない。' },
  { term: 'touch', description: '空ファイルを新規作成するか、既存ファイルのタイムスタンプを更新するコマンド。ビルドシステムで依存関係を強制更新する際にも使われる。' },
  { term: 'cat', aliases: ['concatenate'], description: 'ファイルの内容を標準出力に表示するコマンド。複数ファイルを結合して出力する用途にも使われる。' },
  { term: 'less', description: 'ファイルの内容をページ単位でスクロール表示するコマンド。`more`と異なり上方向にもスクロールできる。' },
  { term: 'more', description: 'ファイルの内容を1画面ずつ表示するページャーコマンド。`less`より機能が少ないが広く普及している。' },
  { term: 'tail', description: 'ファイルの末尾を表示するコマンド。`-f`オプションでログファイルをリアルタイムに監視できる。' },
  { term: 'grep', aliases: ['global regular expression print'], description: 'ファイルや標準入力からパターンに一致する行を検索して出力するコマンド。正規表現に対応し、ログ解析やコード検索に広く使われる。' },
  { term: 'find', description: 'ディレクトリツリーを再帰的に検索してファイルやディレクトリを探すコマンド。名前・種別・更新日時など多様な条件で絞り込める。' },
  { term: 'sed', aliases: ['stream editor'], description: 'ストリームエディタ。テキストの置換・削除・挿入をパイプライン上で行うコマンド。正規表現を使った一括置換に多用される。' },
  { term: 'awk', description: 'テキストを列単位で処理するパターンスキャン言語。CSVやログの集計・整形に使われる。' },
  { term: 'sort', description: 'テキストの各行をソートして出力するコマンド。`-n`で数値順、`-r`で逆順など多様なオプションがある。' },
  { term: 'uniq', description: '連続する重複行を削除または集計するコマンド。`sort`と組み合わせて重複排除に使われる。' },
  { term: 'wc', aliases: ['word count'], description: 'ファイルや標準入力の行数・単語数・バイト数を数えるコマンド。`-l`で行数のみ取得するのが一般的。' },
  { term: 'cut', description: '各行から指定したフィールドや文字位置を切り出して出力するコマンド。CSVやTSVの特定列を取得する際に使われる。' },
  { term: 'echo', description: '引数として渡した文字列を標準出力に表示するコマンド。変数展開やスクリプト内のメッセージ出力に広く使われる。' },
  { term: 'printf', description: '書式指定に従って文字列を出力するコマンド。`echo`より厳密な書式制御が可能で、改行の扱いも明示的に指定できる。' },
  { term: 'read', description: '標準入力から1行を読み込み、変数に格納するシェル組み込みコマンド。インタラクティブなスクリプトで入力待ちに使われる。' },
  { term: 'test', aliases: ['['], description: '条件式を評価してtrue/falseを返すシェル組み込みコマンド。`[`と等価で、ファイルの存在確認や数値・文字列の比較に使われる。' },
  { term: 'if', description: '条件分岐を記述するシェルの制御構文。`then`/`else`/`fi`とセットで使い、コマンドの終了コードで分岐する。' },
  { term: 'for', description: 'リストや数値範囲の各要素を順に処理するシェルのループ構文。ファイルの一括処理などに使われる。' },
  { term: 'while', description: '条件が真の間、処理を繰り返すシェルのループ構文。無限ループやストリーム処理に使われる。' },
  { term: 'case', description: '値をパターンと照合して分岐するシェルの制御構文。複数の条件をシンプルに書ける。' },
  { term: 'function', description: '【シェル】シェルスクリプト内で再利用可能な処理をまとめるための定義キーワード。`function name {}` または `name(){}` の形式で記述する。 【OCI APEX】イベントに応じて実行される小さな処理単位。' },
  { term: 'source', aliases: ['.'], description: '指定したスクリプトファイルを現在のシェルセッション内で実行するコマンド。変数や関数の定義を現在のシェルに読み込む際に使われる。' },
  { term: 'unset', description: 'シェル変数や関数を削除するコマンド。設定を初期化したり、不要な変数をクリーンアップする際に使われる。' },
  { term: 'declare', aliases: ['typeset'], description: 'シェル変数の属性（整数・配列・読み取り専用など）を宣言するbash組み込みコマンド。型付き変数を定義する際に使われる。' },
  { term: 'local', description: '関数内でローカルスコープの変数を定義するbash組み込みコマンド。関数外に影響を与えない変数を作るために使われる。' },
  { term: 'return', description: 'シェル関数から抜けて呼び出し元に戻るコマンド。引数として終了コードを指定できる。' },
  { term: 'exit', description: 'シェルスクリプトまたはシェルセッションを終了するコマンド。引数として終了コード（0=成功、非0=失敗）を渡せる。' },
  { term: 'which', description: '指定したコマンドの実行ファイルのフルパスを表示するコマンド。コマンドがどのパスにあるか確認する際に使われる。' },
  { term: 'type', description: 'コマンドの種類（組み込み・エイリアス・外部コマンドなど）を表示するbash組み込みコマンド。' },
  { term: 'man', aliases: ['manual'], description: 'コマンドやシステムコールのマニュアルページを表示するコマンド。詳細なオプションや使い方を確認できる。' },
  { term: 'help', description: '【シェル】bash組み込みコマンドの使い方を表示するコマンド。外部コマンドには`man`を使う。 【OCI APEX】属性説明やヘルプを見るタブ。' },
  { term: 'history', description: '過去に実行したコマンドの履歴を表示するbash組み込みコマンド。`!番号`で履歴から再実行できる。' },
  { term: 'unalias', description: '設定されたエイリアスを削除するコマンド。`-a`ですべてのエイリアスを一括削除できる。' },
  { term: 'jobs', description: '現在のシェルで実行中または停止中のジョブ一覧を表示するbash組み込みコマンド。バックグラウンドジョブの管理に使われる。' },
  { term: 'fg', description: 'バックグラウンドまたは停止中のジョブをフォアグラウンドに戻すコマンド。`jobs`で確認したジョブ番号を指定する。' },
  { term: 'bg', description: '停止中のジョブをバックグラウンドで実行再開するコマンド。Ctrl+Zで停止したプロセスを再開する際に使われる。' },
  { term: 'wait', description: '指定したバックグラウンドプロセスまたはすべてのバックグラウンドジョブが終了するまで待機するコマンド。' },
  { term: 'trap', description: 'シグナルやシェルイベントを受け取ったときに実行する処理を登録するbash組み込みコマンド。スクリプトの終了時クリーンアップに使われる。' },
  { term: 'kill', description: 'プロセスにシグナルを送信するコマンド。デフォルトはSIGTERM（15）で、`-9`（SIGKILL）で強制終了できる。' },
  { term: 'df', aliases: ['disk free'], description: 'ファイルシステムのディスク使用量を表示するコマンド。`-h`で人が読みやすい単位で表示できる。' },
  { term: 'du', aliases: ['disk usage'], description: 'ディレクトリやファイルのディスク使用量を表示するコマンド。`-sh *`でサブディレクトリごとのサイズを把握できる。' },
  { term: 'free', description: 'システムのメモリ使用状況を表示するコマンド。`-h`で人が読みやすい単位で表示できる。' },
  { term: 'ln', aliases: ['link'], description: 'ファイルやディレクトリへのリンクを作成するコマンド。`-s`でシンボリックリンクを作成する。' },
  { term: 'tee', description: '標準入力をファイルと標準出力の両方に同時に書き出すコマンド。パイプラインの途中でファイルに保存しながら処理を続けられる。' },
  { term: 'xargs', description: '標準入力から受け取った値をコマンドの引数として渡すコマンド。`find`や`grep`の結果を別のコマンドに渡す際に使われる。' },
  { term: 'date', description: '現在の日時を表示またはシステム日時を設定するコマンド。`+%Y-%m-%d`などの書式指定でフォーマットできる。' },
  { term: 'sleep', description: '指定した秒数だけ処理を一時停止するコマンド。スクリプト内のポーリングや待機処理に使われる。' },
  { term: 'watch', description: '指定したコマンドを一定間隔で繰り返し実行し、結果を画面に更新表示するコマンド。リソース監視に使われる。' },
  { term: 'curl', description: 'HTTPやFTPなど各種プロトコルでデータを転送するコマンド。APIの動作確認やファイルダウンロードに広く使われる。' },
  { term: 'wget', description: 'HTTPやFTPでファイルをダウンロードするコマンド。非対話的なダウンロードに適しており、ミラーリングにも使われる。' },
  { term: 'ssh', aliases: ['secure shell'], description: '暗号化されたSSHプロトコルでリモートサーバに接続するコマンド。リモート操作やポートフォワーディングにも使われる。' },
  { term: 'scp', aliases: ['secure copy'], description: 'SSH経由でファイルをリモートサーバとの間でコピーするコマンド。暗号化されたファイル転送が行える。' },
  { term: 'zip', description: 'ファイルやディレクトリをZIP形式で圧縮するコマンド。`-r`で再帰的にディレクトリを圧縮できる。' },
  { term: 'unzip', description: 'ZIPアーカイブを解凍するコマンド。`-d`で展開先ディレクトリを指定できる。' },
  { term: 'env', description: '現在の環境変数の一覧を表示するコマンド。また、特定の環境変数を設定してコマンドを実行する際にも使われる。' },
  { term: 'printenv', description: '環境変数の値を表示するコマンド。引数なしで全環境変数、引数指定で特定の変数を表示する。' },
  { term: 'スクリプト', description: 'シェルコマンドを複数行に記述して自動実行できるようにしたテキストファイル。bashスクリプトは`.sh`拡張子を持ち、繰り返し作業の自動化に使われる。' },
  { term: 'コマンドレット', aliases: ['cmdlet'], description: 'PowerShellで使われる軽量コマンドの単位。`動詞-名詞`の命名規則（例: Get-Item）に従い、.NETオブジェクトを入出力する。' },
  { term: 'PSオブジェクト', aliases: ['psオブジェクト', 'psobject', 'powershellオブジェクト'], description: 'PowerShellのパイプラインで流通する.NETオブジェクト。テキストではなく構造化データを受け渡しできるため、bashのテキストパイプより型安全な処理が行える。' },
  { term: 'プロファイル', aliases: ['profile'], description: 'PowerShellの起動時に自動的に読み込まれる設定スクリプト。関数・エイリアス・環境変数などをセッション開始時に設定するために使われる。' },
  { term: 'Get-ChildItem', aliases: ['get-childitem', 'gci', 'dir'], description: 'PowerShellでファイルやディレクトリの一覧を取得するコマンドレット。bashの`ls`に相当し、`gci`や`dir`のエイリアスでも呼び出せる。' },
  { term: 'Set-Location', aliases: ['set-location'], description: 'PowerShellでカレントディレクトリを変更するコマンドレット。bashの`cd`に相当し、`sl`や`cd`のエイリアスでも使える。' },
  { term: 'Get-Content', aliases: ['get-content'], description: 'PowerShellでファイルの内容を読み込み表示するコマンドレット。bashの`cat`に相当し、`-Wait`オプションでログのリアルタイム監視もできる。' },
  { term: 'Set-Content', aliases: ['set-content', 'sc'], description: 'PowerShellでファイルに内容を書き込むコマンドレット。既存のファイルを上書きする。' },
  { term: 'New-Item', aliases: ['new-item', 'ni'], description: 'PowerShellでファイル・ディレクトリ・レジストリキーなど新しいアイテムを作成するコマンドレット。`-ItemType`で種別を指定する。' },
  { term: 'Remove-Item', aliases: ['remove-item', 'ri', 'del'], description: 'PowerShellでファイルやディレクトリを削除するコマンドレット。`-Recurse -Force`で再帰的に強制削除できる。' },
  { term: 'Copy-Item', aliases: ['copy-item', 'cpi'], description: 'PowerShellでファイルやディレクトリをコピーするコマンドレット。`-Recurse`でディレクトリを再帰コピーできる。' },
  { term: 'Move-Item', aliases: ['move-item', 'mi'], description: 'PowerShellでファイルやディレクトリを移動するコマンドレット。bashの`mv`に相当する。' },
  { term: 'Rename-Item', aliases: ['rename-item', 'rni'], description: 'PowerShellでファイルやディレクトリの名前を変更するコマンドレット。' },
  { term: 'Get-Process', aliases: ['get-process', 'gps'], description: 'PowerShellで実行中のプロセス一覧を取得するコマンドレット。bashの`ps`に相当し、CPU・メモリ使用量も確認できる。' },
  { term: 'Stop-Process', aliases: ['stop-process', 'spps'], description: 'PowerShellで実行中のプロセスを停止するコマンドレット。`-Force`で強制終了できる。' },
  { term: 'Start-Process', aliases: ['start-process', 'saps'], description: 'PowerShellで新しいプロセスを起動するコマンドレット。管理者権限での実行や非表示実行も指定できる。' },
  { term: 'Get-Service', aliases: ['get-service', 'gsv'], description: 'PowerShellでWindowsサービスの一覧と状態を取得するコマンドレット。特定のサービスをフィルタして確認できる。' },
  { term: 'Set-Service', aliases: ['set-service', 'ssv'], description: 'PowerShellでWindowsサービスのスタートアップの種別や説明を変更するコマンドレット。' },
  { term: 'Start-Service', aliases: ['start-service', 'sasv'], description: 'PowerShellで停止中のWindowsサービスを起動するコマンドレット。' },
  { term: 'Stop-Service', aliases: ['stop-service', 'spsv'], description: 'PowerShellで実行中のWindowsサービスを停止するコマンドレット。' },
  { term: 'Restart-Service', aliases: ['restart-service'], description: 'PowerShellでWindowsサービスを再起動するコマンドレット。設定変更後の反映などに使われる。' },
  { term: 'Get-EventLog', aliases: ['get-eventlog'], description: 'PowerShellでWindowsイベントログを取得するコマンドレット。エラーや警告の調査に使われる。' },
  { term: 'Write-Host', aliases: ['write-host'], description: 'PowerShellでコンソールに直接メッセージを表示するコマンドレット。パイプラインには出力されないため、ログ表示に限定して使う。' },
  { term: 'Write-Output', aliases: ['write-output'], description: 'PowerShellでオブジェクトをパイプラインに出力するコマンドレット。次のコマンドレットに値を渡すために使われる。' },
  { term: 'Read-Host', aliases: ['read-host'], description: 'PowerShellでコンソールからユーザー入力を受け取るコマンドレット。インタラクティブなスクリプトで使われる。' },
  { term: 'Write-Error', aliases: ['write-error'], description: 'PowerShellでエラーメッセージをエラーストリームに出力するコマンドレット。エラーハンドリングのデバッグに使われる。' },
  { term: 'Write-Warning', aliases: ['write-warning'], description: 'PowerShellで警告メッセージを警告ストリームに出力するコマンドレット。非致命的な問題をユーザーに通知する際に使われる。' },
  { term: 'Get-Variable', aliases: ['get-variable', 'gv'], description: 'PowerShellでシェル変数の一覧または特定変数の値を取得するコマンドレット。' },
  { term: 'Set-Variable', aliases: ['set-variable', 'sv'], description: 'PowerShellで変数の値や属性を設定するコマンドレット。読み取り専用属性も指定できる。' },
  { term: 'Remove-Variable', aliases: ['remove-variable', 'rv'], description: 'PowerShellで変数を削除するコマンドレット。変数のクリーンアップに使われる。' },
  { term: 'Get-Command', aliases: ['get-command', 'gcm'], description: 'PowerShellで利用可能なコマンドレット・関数・エイリアスを一覧取得するコマンドレット。コマンド名の探索に使われる。' },
  { term: 'Get-Help', aliases: ['get-help'], description: 'PowerShellでコマンドレットや関数のヘルプ情報を表示するコマンドレット。`-Examples`オプションで使用例を確認できる。' },
  { term: 'Get-Member', aliases: ['get-member', 'gm'], description: 'PowerShellでオブジェクトのプロパティとメソッドの一覧を表示するコマンドレット。オブジェクトの構造を調べる際に使われる。' },
  { term: 'Select-Object', aliases: ['select-object'], description: 'PowerShellでパイプラインオブジェクトから特定のプロパティを選択して出力するコマンドレット。' },
  { term: 'Where-Object', aliases: ['where-object', '?'], description: 'PowerShellでパイプラインオブジェクトを条件でフィルタリングするコマンドレット。bashの`grep`に相当する。' },
  { term: 'ForEach-Object', aliases: ['foreach-object', 'foreach', '%'], description: 'PowerShellでパイプラインの各オブジェクトに対して処理を繰り返すコマンドレット。bashの`xargs`に近い使い方ができる。' },
  { term: 'Sort-Object', aliases: ['sort-object'], description: 'PowerShellでパイプラインオブジェクトをプロパティ値でソートするコマンドレット。' },
  { term: 'Group-Object', aliases: ['group-object', 'group'], description: 'PowerShellでパイプラインオブジェクトを特定のプロパティ値でグループ化するコマンドレット。集計や分類に使われる。' },
  { term: 'Measure-Object', aliases: ['measure-object', 'measure'], description: 'PowerShellでパイプラインオブジェクトの数値プロパティの合計・平均・最大・最小などを計算するコマンドレット。' },
  { term: 'Format-Table', aliases: ['format-table', 'ft'], description: 'PowerShellでオブジェクトをテーブル形式でコンソールに表示するコマンドレット。列のカスタマイズが可能。' },
  { term: 'Format-List', aliases: ['format-list', 'fl'], description: 'PowerShellでオブジェクトをプロパティ名と値のリスト形式で表示するコマンドレット。詳細情報の確認に使われる。' },
  { term: 'Export-Csv', aliases: ['export-csv', 'epcsv'], description: 'PowerShellでオブジェクトをCSVファイルに書き出すコマンドレット。Excelなどで開けるデータとして出力できる。' },
  { term: 'Import-Csv', aliases: ['import-csv', 'ipcsv'], description: 'PowerShellでCSVファイルを読み込みオブジェクトとして返すコマンドレット。列名がプロパティ名になる。' },
  { term: 'ConvertTo-Json', aliases: ['convertto-json'], description: 'PowerShellでオブジェクトをJSON文字列に変換するコマンドレット。APIレスポンスの整形や設定ファイルの生成に使われる。' },
  { term: 'ConvertFrom-Json', aliases: ['convertfrom-json'], description: 'PowerShellでJSON文字列をPowerShellオブジェクトに変換するコマンドレット。APIレスポンスの解析に使われる。' },
  { term: 'Invoke-WebRequest', aliases: ['invoke-webrequest', 'iwr'], description: 'PowerShellでHTTPリクエストを送信してWebコンテンツを取得するコマンドレット。bashの`curl`に相当する。' },
  { term: 'Invoke-RestMethod', aliases: ['invoke-restmethod', 'irm'], description: 'PowerShellでREST APIにHTTPリクエストを送り、レスポンスを自動でパースして返すコマンドレット。JSON/XMLを直接オブジェクトとして扱える。' },
  { term: 'Test-Path', aliases: ['test-path'], description: 'PowerShellでファイルやディレクトリ・レジストリキーが存在するか確認してtrue/falseを返すコマンドレット。' },
  { term: 'Test-Connection', aliases: ['test-connection'], description: 'PowerShellでネットワーク接続を確認するコマンドレット。bashの`ping`に相当する。' },
  { term: 'Get-Date', aliases: ['get-date'], description: 'PowerShellで現在の日時を取得するコマンドレット。書式指定で任意のフォーマットに変換できる。' },
  { term: 'Start-Sleep', aliases: ['start-sleep'], description: 'PowerShellでスクリプトの実行を指定秒数またはミリ秒だけ一時停止するコマンドレット。' },
  { term: 'Get-History', aliases: ['get-history', 'h'], description: 'PowerShellで現在のセッションで実行したコマンドの履歴を取得するコマンドレット。' },
  { term: 'Clear-Host', aliases: ['clear-host', 'clear'], description: 'PowerShellのコンソール画面をクリアするコマンドレット。bashの`clear`に相当する。' },
  { term: 'terminal', aliases: ['ターミナル', '端末'], description: 'コマンドをテキストで入力してコンピュータを操作するインターフェースです。' },
  { term: 'directory', description: 'ファイルを整理して格納するための階層構造の入れ物です。Windowsではフォルダと呼ばれます。' },
  { term: 'path', aliases: ['パス'], description: 'ファイルやディレクトリの場所を階層的に示す文字列です。/home/user/file.txtのように表記します。' },
];
