// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: containersK8s (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // container (92), kubernetes (26)
  { term: 'HPA', aliases: ['hpa'], description: 'Horizontal Pod Autoscalerの略で、負荷に応じてPod数を増減する仕組みです。Kubernetes運用の基本的な自動拡張手段です。' },
  { term: 'VPA', aliases: ['vpa'], description: 'Vertical Pod Autoscalerの略で、PodごとのCPUやメモリ割当を見直す仕組みです。水平スケールと使い分けが必要です。' },
  { term: 'Cluster Autoscaler', aliases: ['cluster autoscaler'], description: 'ノード台数自体を増減させる仕組みです。Pod増減だけで足りない場合に重要になります。' },
  { term: 'Pod Disruption Budget', aliases: ['pod disruption budget'], description: 'メンテナンス時などに同時停止してよいPod数を制御する仕組みです。可用性維持に役立ちます。' },
  { term: 'Taint and Toleration', aliases: ['taint and toleration'], description: '特定ノードに特定ワークロードだけを載せるための仕組みです。高負荷系や専用処理の隔離に使えます。' },
  { term: 'Node Affinity', aliases: ['node affinity'], description: 'Podを特定条件のノードへ配置しやすくする仕組みです。性能特性やゾーン分散を意識した配置に使われます。' },
  { term: 'Pod Anti-Affinity', aliases: ['pod anti-affinity'], description: '同種Podを同じ場所へ集めすぎないための仕組みです。単一障害点を減らすのに役立ちます。' },
  { term: 'Init Container', aliases: ['init container'], description: '本体起動前に一度だけ動く補助コンテナです。初期化や依存確認に使われます。' },
  { term: 'Sidecar Container', aliases: ['sidecar container'], description: '本体と並んで動く補助コンテナです。ログ転送、プロキシ、監視などを本体から分離して担えます。' },
  { term: 'DaemonSet', aliases: ['daemonset'], description: '各ノードに一つずつPodを配置する仕組みです。監視エージェントやログ収集などで使われます。' },
  { term: 'StatefulSet', aliases: ['statefulset'], description: '状態を持つワークロード向けに、安定した名前や保存領域を持たせる仕組みです。DBやメッセージ基盤で使われます。' },
  { term: 'Deployment Rollout', aliases: ['deployment rollout'], description: '新しいPod群へ段階的に切り替える仕組みです。更新進行状況を管理しやすくなります。' },
  { term: 'Rollback Revision', aliases: ['rollback revision'], description: '以前のデプロイ版へ戻すための記録です。失敗時の迅速な切り戻しに役立ちます。' },
  { term: 'CrashLoopBackOff', aliases: ['crashloopbackoff'], description: 'コンテナ起動失敗が続き、再試行間隔が伸びている状態です。設定不備や依存障害の典型的なサインです。' },
  { term: 'Eviction', aliases: ['eviction'], description: 'リソース不足などでPodがノードから退去させられることです。想定外に起きると可用性へ影響します。' },
  { term: 'Resource Request', aliases: ['resource request'], description: 'Podが最低限必要とするCPUやメモリ量の宣言です。スケジューリングや安定性に影響します。' },
  { term: 'Resource Limit', aliases: ['resource limit'], description: 'Podが使える上限資源量です。暴走防止には有効ですが、厳しすぎると正常系も落ちやすくなります。' },
  { term: 'Overcommit', aliases: ['overcommit'], description: '実際の余裕を見込んで、物理資源以上の要求を載せる考え方です。効率は上がりますが、ピーク時の競合に注意が必要です。' },
  { term: 'Bin Packing', aliases: ['bin packing'], description: 'ノードへワークロードを効率よく詰める考え方です。コスト効率向上に役立ちますが、集中しすぎると障害影響が大きくなることがあります。' },
  { term: 'Image Pull Policy', aliases: ['image pull policy'], description: 'イメージを毎回取得するか、ローカルを使うかを決める設定です。更新反映と起動速度のバランスに関わります。' },
  { term: 'Immutable Tag', aliases: ['immutable tag'], description: '一度付けたら中身を変えないイメージタグ運用です。再現性と監査性を高めやすくなります。' },
  { term: 'Digest Pinning', aliases: ['digest pinning'], description: 'タグではなく内容ハッシュでイメージを固定することです。想定外更新を防ぎやすくなります。' },
  { term: 'ConfigMap', aliases: ['configmap'], description: '設定値をコンテナ本体と分離して管理する仕組みです。環境差分や設定変更を扱いやすくします。' },
  { term: 'Service Mesh Control Plane', aliases: ['service mesh control plane'], description: '通信制御ルールや証明書管理を一元的に担う中枢です。便利ですが、運用理解が浅いと逆に複雑化します。' },
  { term: 'Ingress Controller', aliases: ['ingress controller'], description: '外部からのHTTP系アクセスをKubernetes内へ振り分ける制御機構です。公開経路の標準化に役立ちます。' },
  { term: 'Egress Gateway', aliases: ['egress gateway'], description: '外向き通信を特定経路へ集約する仕組みです。外部通信制御や監査性向上に役立ちます。' },
  { term: 'Pod Security Standard', aliases: ['pod security standard'], description: 'Podに許される権限や危険設定を制限する基準です。コンテナ実行安全性の土台になります。' },
  { term: 'Admission Controller', aliases: ['admission controller'], description: 'リソース作成時に検査や変更を行う仕組みです。危険設定を事前に防ぐのに役立ちます。' },
  { term: 'Pod', aliases: ['pod', 'ポッド'], description: 'Kubernetesにおけるデプロイの最小単位。1つ以上のコンテナを同じネットワーク名前空間とストレージを共有してまとめたグループであり、スケジューリングの基本単位となる。' },
  { term: 'ReplicaSet', aliases: ['replicaset'], description: '指定した数のPodレプリカが常に稼働していることを保証するKubernetesリソース。セレクタで管理対象Podを特定し、不足・過剰があれば自動的にPodを作成・削除する。' },
  { term: 'Deployment', aliases: ['deployment', 'デプロイメント'], description: 'KubernetesでReplicaSetを管理し、ローリングアップデートやロールバックを宣言的に制御するリソース。アプリケーションのバージョン管理とゼロダウンタイムデプロイを実現する。' },
  { term: 'CronJob', aliases: ['cronjob', 'cronjob(k8s)'], description: 'cron形式のスケジュールに従ってJobを定期実行するKubernetesリソース。バッチ処理やレポート生成など定時実行が必要なタスクを宣言的に定義・管理できる。' },
  { term: 'Service', aliases: ['service', 'service(k8s)'], description: '【コンテナ】複数のPodへの安定したネットワークアクセスを提供するKubernetesリソース。PodのIPアドレスが変動してもServiceのDNS名と仮想IPで透過的にアクセスでき、負荷分散も行う。 【アーキテクチャ】ControllerやRepositoryの間でユースケースや業務処理の流れをまとめるアプリケーション層の部品。入力検証の後段で処理を組み立て、トランザクション境界や外部連携を担うことが多い。' },
  { term: 'ClusterIP', aliases: ['clusterip'], description: 'KubernetesのServiceタイプの一つで、クラスター内部からのみアクセス可能な仮想IPを割り当てるデフォルトタイプ。クラスター外部には公開されず、内部サービス間通信に使用される。' },
  { term: 'NodePort', aliases: ['nodeport'], description: 'KubernetesのServiceタイプの一つで、クラスター内の全ノードの特定ポートにServiceを公開する方式。外部から<NodeIP>:<NodePort>でアクセス可能になるが、本番では通常LoadBalancerを使う。' },
  { term: 'LoadBalancer', aliases: ['loadbalancer', 'loadbalancer(k8s)'], description: 'クラウドプロバイダーの外部ロードバランサーをプロビジョニングしてServiceを公開するKubernetesのServiceタイプ。クラウド環境でアプリケーションを外部に安全に公開する際に使用される。' },
  { term: 'Gateway API', aliases: ['gateway api'], description: 'Ingressを発展させたKubernetesのネットワーキングAPIセット。Gateway、HTTPRoute、TCPRouteなどのリソースで高度なトラフィック管理を表現でき、役割分担による管理が可能。' },
  { term: 'Secret', aliases: ['secret', 'secret(k8s)'], description: 'パスワード、トークン、TLS証明書などの機密データをBase64エンコードして保存するKubernetesリソース。Podに環境変数やボリュームとして注入でき、ConfigMapとは異なり暗号化保存が推奨される。' },
  { term: 'PersistentVolume', aliases: ['persistentvolume'], description: 'クラスター管理者がプロビジョニングしたストレージリソースを表すKubernetesオブジェクト。NFS、クラウドディスク、ローカルストレージなどをPodから切り離した形で管理し、ライフサイクルをPodに依存させない。' },
  { term: 'PersistentVolumeClaim', aliases: ['persistentvolumeclaim', 'pvc'], description: 'PodがPersistentVolumeに対してストレージを要求するためのKubernetesリソース。必要なストレージ容量やアクセスモードを指定し、条件を満たすPVに動的または静的にバインドされる。' },
  { term: 'StorageClass', aliases: ['storageclass'], description: 'PersistentVolumeを動的にプロビジョニングするためのKubernetesリソース。ストレージの種類（SSD/HDD）、プロビジョナー、再利用ポリシーなどを定義し、PVCから参照することで自動的にPVを作成する。' },
  { term: 'Selector', aliases: ['selector'], description: 'Kubernetesでラベルによってリソースのグループをフィルタリングするためのメカニズム。ServiceがルーティングするPodの集合や、ReplicaSetが管理するPodを特定する際に使用される。' },
  { term: 'Annotation', aliases: ['annotation'], description: 'Kubernetesリソースに任意のメタデータを付与するキーと値のペア。ラベルと異なりセレクタには使えないが、ツールや外部システムが読み取るための情報（デプロイ担当者、ビルドバージョンなど）を保存するのに使う。' },
  { term: 'Taint', aliases: ['taint', 'テイント'], description: 'Kubernetesのノードに設定するマーカーで、特定のTolerationを持たないPodのスケジューリングを拒否・回避させる仕組み。専用ノードや特殊ハードウェアを持つノードへの意図しないPod配置を防ぐ。' },
  { term: 'Toleration', aliases: ['toleration', 'トレレーション'], description: 'PodがノードのTaintを許容することを宣言するKubernetesの設定。対応するTaintがあるノードにもスケジューリングを許可することで、専用ノードへのPod配置を制御する。' },
  { term: 'Pod Affinity', aliases: ['pod affinity', 'ポッドアフィニティ'], description: 'Podをどのノードにスケジュールするかをラベルが一致する他のPodの存在に基づいて制御するKubernetes機能。同じノードへの配置（アフィニティ）や異なるノードへの分散（アンチアフィニティ）を指定できる。' },
  { term: 'KEDA', aliases: ['keda', 'kubernetes event-driven autoscaling'], description: 'Kubernetesにおいてイベントドリブンなオートスケーリングを実現するOSSコンポーネント。メッセージキューの深さ、HTTPリクエスト数、外部メトリクスなど様々なイベントソースに基づいてPodスケールを制御する。' },
  { term: 'Operator', aliases: ['operator', 'operator(k8s)', 'kubernetesオペレーター'], description: 'カスタムリソースとカスタムコントローラーを組み合わせ、アプリケーションの運用ノウハウをコードで表現するKubernetesのパターン。データベースのスケールアウトやバックアップなど複雑な運用を自動化する。' },
  { term: 'CRD', aliases: ['crd', 'customresourcedefinition', 'カスタムリソース定義'], description: 'Kubernetes APIを拡張してユーザー定義のリソース型を追加するためのリソース。CRDを登録することで独自のオブジェクトをKubernetes APIで管理でき、Operatorパターンの基盤となる。' },
  { term: 'Custom Controller', aliases: ['custom controller', 'カスタムコントローラー'], description: '独自のKubernetesリソース（CRD）の状態を監視し、宣言的に定義された望ましい状態と現在の状態の差分を解消するコントローラーループを実装したコンポーネント。' },
  { term: 'Admission Webhook', aliases: ['admission webhook'], description: 'KubernetesのAPI Serverがリソースを永続化する前後にカスタム検証・変換処理を注入できる拡張ポイント。Mutating Admission WebhookとValidating Admission Webhookの2種類があり、ポリシー適用に使われる。' },
  { term: 'Network Policy', aliases: ['network policy', 'ネットワークポリシー'], description: 'Pod間の通信を制限するKubernetesリソース。ラベルセレクタとポートを使ってIngress/Egressトラフィックを許可または拒否する。デフォルトは全通信許可のため、最小権限原則には明示的な設定が必要。' },
  { term: 'Istio', aliases: ['istio'], description: 'Envoyをサイドカープロキシとして使用するオープンソースのService Mesh実装。トラフィック管理、セキュリティ（mTLS）、テレメトリー収集をKubernetesクラスター上のマイクロサービスに提供する。' },
  { term: 'Envoy', aliases: ['envoy'], description: 'Lyft社が開発したL7プロキシで、Service Meshのデータプレーンとして広く採用されているOSS。動的な設定変更（xDS API）、高度なロードバランシング、可観測性に対応し、IstioやLinkerdのサイドカーとしても使われる。' },
  { term: 'Linkerd', aliases: ['linkerd'], description: '軽量さとシンプルさを重視したKubernetes向けオープンソースService Mesh。Rustで書かれた専用マイクロプロキシを使い、IstioよりもリソースフットプリントとOperational complexityが小さい。' },
  { term: 'Startup Probe', aliases: ['startup probe', 'スタートアッププローブ'], description: '起動に時間がかかるコンテナの初期化完了を確認するKubernetesのヘルスチェック機構。Startup Probeが成功するまでLiveness/Readiness Probeは実行されず、起動タイムアウトによる誤再起動を防ぐ。' },
  { term: 'Container Runtime', aliases: ['container runtime', 'コンテナランタイム'], description: 'コンテナイメージを実際のプロセスとして起動・管理するソフトウェア。KubernetesはCRI（Container Runtime Interface）を通じてランタイムと通信し、containerd、CRI-Oなどが代表的な実装。' },
  { term: 'containerd', description: 'DockerやKubernetesが採用するCNCFのコンテナランタイム。イメージの取得・保存・コンテナ実行をシンプルなAPIで提供し、元はDockerのデーモンから切り出されてスタンドアロンプロジェクトとなった。' },
  { term: 'CRI-O', aliases: ['cri-o'], description: 'Kubernetes専用に設計されたCRI（Container Runtime Interface）準拠の軽量コンテナランタイム。OCI互換イメージを実行でき、Red Hat/OpenShiftで採用されている。containerdと同様のCRIを実装する。' },
  { term: 'Dockerfile', aliases: ['dockerfile'], description: 'Dockerコンテナイメージをビルドするための命令を記述したテキストファイル。FROM、RUN、COPY、CMDなどのディレクティブを使い、ベースイメージからアプリケーション実行環境を層状に構築する。' },
  { term: 'multi-stage build', aliases: ['マルチステージビルド'], description: '1つのDockerfileに複数のFROMステートメントを使い、ビルド環境と実行環境を分離するDockerのビルド手法。コンパイラや開発ツールを最終イメージに含めず、イメージサイズを大幅に削減できる。' },
  { term: 'Docker Compose', aliases: ['docker compose'], description: '複数のコンテナから構成されるアプリケーションをYAMLファイル（docker-compose.yml）で定義し、一括管理するツール。ローカル開発環境やCI環境でマイクロサービスの依存関係を手軽に再現するのに使われる。' },
  { term: 'Registry', aliases: ['registry', 'レジストリ'], description: 'コンテナイメージを保存・配布するためのリポジトリサービス。Docker Hub、Amazon ECR、Google Artifact Registryなどが代表例で、イメージのバージョン管理とアクセス制御を提供する。' },
  { term: 'Image Tag', aliases: ['image tag', 'イメージタグ'], description: 'コンテナイメージの特定バージョンを識別するラベル。`image:tag`の形式で参照し、`latest`タグは最新ビルドを示すが内容が変わるため、本番環境では具体的なバージョンタグかダイジェストを使うべきとされる。' },
  { term: 'Image Digest', aliases: ['image digest', 'イメージダイジェスト'], description: 'コンテナイメージの内容から算出したSHA256ハッシュ値による不変の識別子。タグと異なりダイジェストは内容が変わると変化するため、再現性が重要な本番デプロイでイメージを正確に固定できる。' },
  { term: 'Layer Cache', aliases: ['layer cache', 'レイヤーキャッシュ'], description: 'Dockerイメージビルド時に変更のない中間レイヤーを再利用する仕組み。Dockerfileの命令順を工夫して変更頻度の低いレイヤーを上位に置くことでキャッシュヒット率を高め、ビルド時間を短縮できる。' },
  { term: 'distroless', description: 'シェル・パッケージマネージャー・OSユーティリティを含まず、アプリケーションと最低限のランタイムのみを持つコンテナイメージの種類。攻撃面を最小化しイメージサイズを削減できるが、デバッグには追加工夫が必要。' },
  { term: 'alpine', aliases: ['alpine linux'], description: 'musl libcとBusyBoxをベースにした非常に小さなLinuxディストリビューションで、コンテナのベースイメージとして広く使われる。数MBのサイズでセキュリティリスクを抑えつつ、apkパッケージマネージャーを使ったパッケージ追加が可能。' },
  { term: 'scratch', description: 'Dockerの空のベースイメージ。ファイルシステムが完全に空で、静的バイナリやGoの実行ファイルを直接配置することで最小サイズのコンテナイメージを作成できる。OSライブラリへの依存がないアプリケーション向け。' },
  { term: 'etcd', description: 'Kubernetesのクラスター状態（Pod定義、Secret、ConfigMapなど）をすべて保存する分散キーバリューストア。Raftアルゴリズムで強整合性を保証し、etcdの可用性がクラスター全体の可用性に直結する。' },
  { term: 'kubelet', description: '各ノードで稼働するKubernetesのノードエージェント。API Serverからスケジュールされたマニフェストを受け取り、コンテナランタイムを通じてPodを起動・監視・終了する。ノードの状態をAPI Serverに定期的に報告する役割も持つ。' },
  { term: 'kube-proxy', description: '各ノードで稼働し、KubernetesのServiceに対するネットワークルール（iptables/ipvsルール）を管理するコンポーネント。ServiceのClusterIPへのトラフィックを適切なPodにルーティングする機能を担う。' },
  { term: 'kube-scheduler', description: '新たに作成されたPodをどのノードで実行するかを決定するKubernetesのControl Planeコンポーネント。ノードのリソース空き状況、Affinity/Anti-Affinity、Taint/Tolerationなどを考慮してスケジューリングを行う。' },
  { term: 'kube-apiserver', description: 'Kubernetesクラスターの全操作のエントリポイントとなるRESTful APIサーバー。kubectlや他のコンポーネントはすべてAPIサーバーを通じてetcdとやり取りし、認証・認可・Admission制御も担う。' },
  { term: 'Control Plane', aliases: ['control plane', 'コントロールプレーン'], description: 'Kubernetesクラスターの管理を担うコンポーネント群の総称。kube-apiserver、etcd、kube-scheduler、kube-controller-managerで構成され、クラスターの望ましい状態を維持する。' },
  { term: 'Worker Node', aliases: ['worker node', 'ワーカーノード'], description: '実際のアプリケーションコンテナ（Pod）を実行するKubernetesのノード。kubelet、kube-proxy、コンテナランタイムが稼働し、Control Planeからの指示に従ってワークロードを処理する。' },
  { term: 'kubectl', description: 'Kubernetesクラスターを操作するためのCLIツール。リソースの作成・取得・更新・削除、ログ確認、Podへのexecなど日常的なクラスター管理操作を提供する。' },
  { term: 'kubeconfig', description: 'kubectlがどのKubernetesクラスターに接続するかを定義する設定ファイル（通常~/.kube/config）。クラスターのAPIサーバーアドレス、認証情報、コンテキスト（クラスター+ユーザー+名前空間の組み合わせ）を管理する。' },
  { term: 'CNI', aliases: ['cni', 'container network interface'], description: 'コンテナのネットワーク設定を行うプラグインのインターフェース仕様。Kubernetesはこの仕様に準拠したプラグイン（Calico、Flannel、Weave等）を使ってPodネットワークを実装し、クラスター間通信を実現する。' },
  { term: 'Flannel', aliases: ['flannel'], description: 'CoreOS（現Red Hat）が開発したシンプルなKubernetes向けCNIプラグイン。オーバーレイネットワークを使ってノード間でPodのルーティングを実現し、設定が簡単なためシンプルなクラスター構成に向く。' },
  { term: 'Calico', aliases: ['calico'], description: 'BGPを使ってネイティブIPルーティングを実現するKubernetes向けの高性能CNIプラグイン。Network Policyの強力な実装でも知られ、オーバーレイ不要で高速なPod間通信と細かいセキュリティ制御を提供する。' },
  { term: 'Volume Mount', aliases: ['volume mount', 'ボリュームマウント'], description: 'KubernetesのPodにボリュームをファイルシステムの特定パスとして接続する設定。ConfigMap、Secret、PVC、emptyDirなど様々なボリュームタイプをコンテナのディレクトリにマウントできる。' },
  { term: 'emptyDir', aliases: ['emptydir'], description: '同じPod内の複数コンテナがデータを共有するための一時ボリューム。Podが起動する際に空で作成され、Pod削除時にデータは消えるため永続化には適さないが、サイドカー間のデータ共有に使われる。' },
  { term: 'CSI Driver', aliases: ['csi driver', 'container storage interface driver'], description: 'ストレージシステムをKubernetesに接続するためのContainer Storage Interface仕様準拠のプラグイン。クラウドプロバイダーやストレージベンダーが独自のCSIドライバーを実装することでPVの動的プロビジョニングを実現する。' },
  { term: 'Resource Quota', aliases: ['resource quota', 'リソースクォータ'], description: 'Kubernetesの名前空間ごとにCPU、メモリ、オブジェクト数などの総使用量に上限を設けるリソース。複数チームが同一クラスターを共有するマルチテナント環境での公平なリソース分配に使われる。' },
  { term: 'Limit Range', aliases: ['limit range', 'リミットレンジ'], description: '名前空間内のコンテナやPodに対するCPU・メモリのリクエスト/リミットのデフォルト値と許容範囲を設定するKubernetesリソース。指定なしのPodに自動でリソース設定を付与し、ノードの過負荷を防ぐ。' },
  { term: 'Priority Class', aliases: ['priority class', 'プライオリティクラス'], description: 'KubernetesでPodの優先度を定義するリソース。ノードのリソースが不足した場合、優先度が低いPodが退去（プリエンプション）させられ、優先度が高いPodがスケジューリングされるよう制御する。' },
  { term: 'Pod Security Admission', aliases: ['pod security admission', 'psa'], description: 'KubernetesのビルトインAdmission ControllerでPodのセキュリティ設定をポリシーに基づき検証する機能。Privileged・Baseline・Restrictedの3つのプロファイルを名前空間単位で適用し、特権コンテナなどを制限する。' },
  { term: 'Cluster Role', aliases: ['cluster role', 'クラスターロール'], description: 'KubernetesのRBACでクラスター全体に適用される権限セットを定義するリソース。名前空間に限定されないRoleと異なり、クラスター全体のリソース（Node、PV等）やすべての名前空間のリソースに対する権限を定義できる。' },
  { term: 'Role Binding', aliases: ['role binding', 'ロールバインディング'], description: 'KubernetesのRBACでRoleまたはClusterRoleをユーザー・グループ・ServiceAccountに紐付けるリソース。RoleBindingは名前空間内、ClusterRoleBindingはクラスター全体に権限を付与する。' },
  { term: 'Image Pull Secret', aliases: ['image pull secret', 'イメージプルシークレット'], description: 'プライベートコンテナレジストリからイメージをプルするための認証情報を保持するKubernetesのSecret。PodのspecやServiceAccountに設定することで、非公開レジストリのイメージをノードが取得できるようにする。' },
  { term: 'Pod Phase', aliases: ['pod phase', 'podフェーズ'], description: 'KubernetesにおけるPodのライフサイクルの現在の状態を表す高レベルな要約。Pending、Running、Succeeded、Failed、Unknownの5つの状態があり、kubectl get podsのSTATUSで確認できる。' },
  { term: 'Termination Grace Period', aliases: ['termination grace period', '終了猶予期間'], description: 'Podが削除要求を受けてからコンテナに強制終了（SIGKILL）が送られるまでの猶予時間（デフォルト30秒）。この間にSIGTERMを受けたアプリケーションはコネクションを安全にクローズし、グレースフルシャットダウンを完了できる。' },
  { term: 'Preemption', aliases: ['preemption', 'プリエンプション'], description: 'ノードのリソースが不足している場合に、優先度の低いPodを退去させることで高優先度のPodをスケジューリングできるようにするKubernetesの機能。Priority Classと組み合わせて使われる。' },
  { term: 'Dry Run', aliases: ['dry run', 'ドライラン'], description: '実際にリソースを変更せずにkubectlコマンドやAPIリクエストの結果をシミュレートする機能。`--dry-run=client`または`--dry-run=server`フラグで使い、マニフェストの検証やAdmission Webhookのテストに活用する。' },
  { term: 'Manifest', aliases: ['manifest', 'マニフェスト', 'kubernetesマニフェスト'], description: 'Kubernetesリソースの望ましい状態をYAMLまたはJSONで記述した設定ファイル。apiVersion、kind、metadata、specの4つのフィールドを基本構造として持ち、GitOpsではこれをバージョン管理する。' },
  { term: 'Container Layer', aliases: ['container layer', 'コンテナレイヤー'], description: 'コンテナイメージを構成するUnion Filesystemの各層。Dockerfileの各命令が1つのレイヤーを作り、書き込み可能なコンテナレイヤーが最上位に追加される。レイヤーは共有・再利用されストレージ効率を高める。' },
  { term: 'Base Image', aliases: ['base image', 'ベースイメージ'], description: 'Dockerfileの`FROM`命令で指定する、コンテナイメージのビルドの出発点となるイメージ。OSの基盤環境（ubuntu、alpine等）やランタイム（node、python等）を含む公式イメージが利用される。' },
  { term: 'BuildKit', aliases: ['buildkit'], description: 'Docker社が開発したDockerイメージのビルドエンジン。並列ビルド、キャッシュマウント、マルチプラットフォームビルド、シークレットマウントなど、従来のdocker buildを大幅に高速化・強化した機能を持つ。' },
  { term: 'Kaniko', aliases: ['kaniko'], description: 'Dockerデーモンなしにコンテナ内でDockerfileからイメージをビルドできるツール。Kubernetesクラスター上でDockerデーモンなしにイメージをビルドしてレジストリにプッシュするCI/CDパイプラインで使われる。' },
  { term: 'Cloud Native Buildpacks', aliases: ['cloud native buildpacks', 'buildpacks', 'cnb'], description: 'Dockerfileなしにアプリケーションのソースコードから自動的にコンテナイメージを生成するOSSのビルドシステム。言語・フレームワークを自動検出してベストプラクティスに沿ったイメージを作成する。' },
  { term: 'Helm Release', aliases: ['helm release', 'helmリリース'], description: 'Helm ChartをKubernetesクラスターにデプロイした個々のインスタンス。同じChartから異なる設定で複数のReleaseを作成でき、それぞれ独立してアップグレード・ロールバック・削除が可能。' },
  { term: 'Helm Repository', aliases: ['helm repository', 'helmリポジトリ'], description: 'Helm Chartを配布・保存するHTTPサーバーまたはOCIレジストリ。`helm repo add`でリポジトリを追加し、`helm search repo`で利用可能なChartを検索できる。Artifact Hubでパブリックリポジトリを検索できる。' },
  { term: 'values.yaml', aliases: ['helmバリュー'], description: 'Helm Chartのデフォルト設定値を定義するYAMLファイル。デプロイ時に`--set`フラグや別ファイルで上書きでき、環境ごとの差分（開発/本番の違いなど）をChartのテンプレートから分離して管理する。' },
  { term: 'Kustomization', aliases: ['kustomization'], description: 'Kustomizeが処理するリソース定義ファイル（kustomization.yaml）またはその設定の概念。bases（ベースマニフェスト）、resources、patches、generatorsなどを宣言してカスタマイズの内容を記述する。' },
  { term: 'Overlay', aliases: ['overlay', 'オーバーレイ'], description: 'Kustomizeにおいてベースのマニフェストに環境固有の差分を重ね合わせるレイヤー。dev/staging/productionなど環境ごとのオーバーレイディレクトリを作り、ベースに最小限の変更だけを記述できる。' },
  { term: 'kubectl rollout', aliases: ['kubectl rollout コマンド'], description: 'KubernetesのDeploymentやDaemonSetなどのロールアウト状態を管理するkubectlのサブコマンド。`rollout status`で進捗確認、`rollout history`で履歴表示、`rollout undo`で以前のリビジョンへのロールバックを行う。' },
  { term: 'Metrics Server', aliases: ['metrics server', 'メトリクスサーバー'], description: 'KubernetesクラスターのPodとノードのリソース使用率（CPU・メモリ）をリアルタイムに収集するクラスターアドオン。HPAやVPA、`kubectl top`コマンドのメトリクスソースとして機能する。' },
  { term: 'Custom Metrics', aliases: ['custom metrics', 'カスタムメトリクス'], description: 'CPU・メモリ以外のアプリケーション固有のメトリクス（リクエスト数、キュー深さ等）をHPAのスケーリング基準として使えるようにするKubernetesの拡張機構。custom.metrics.k8s.io APIを通じてPrometheusアダプターなどと連携する。' },
  { term: 'Headless Service', aliases: ['headless service', 'ヘッドレスサービス'], description: 'ClusterIPを持たず、Podの個別IPをDNSレコードで直接返すKubernetesのServiceタイプ（spec.clusterIP: None）。StatefulSetで各Podに固定DNSを与えたり、サービスディスカバリーでPod一覧を取得したい場合に使う。' },
  { term: 'Topology Spread Constraints', aliases: ['topology spread constraints', 'トポロジー分散制約'], description: 'Podをゾーン・ノードなどのトポロジードメイン全体に均等に分散させるためのKubernetes機能。特定ゾーンへの集中を防ぎ、可用性を高める。maxSkewパラメータで許容する不均衡度を制御できる。' },
  { term: 'Grafana', aliases: ['grafana'], description: 'Prometheusなどのデータソースからメトリクスをビジュアライズするオープンソースのダッシュボードツール。Kubernetesのリソース使用状況やアプリケーションのパフォーマンスを直感的なグラフで可視化できる。' },
  { term: 'OCI Image', aliases: ['oci image', 'ociイメージ'], description: 'Open Container Initiative（OCI）が定める標準仕様に準拠したコンテナイメージ形式。DockerイメージもOCI仕様を満たすよう進化しており、コンテナランタイムやレジストリ間の相互運用性を保証する。' },
  { term: 'ExternalName Service', aliases: ['externalname service', 'externalname'], description: 'クラスター外の外部DNSホスト名へのエイリアスを提供するKubernetesのServiceタイプ。CNAMEレコードとして機能し、クラスター内のPodが外部サービスに統一したDNS名でアクセスできるようにする。' },
  { term: 'Inter-Pod Anti-Affinity', aliases: ['inter-pod anti-affinity', 'pod間アンチアフィニティ'], description: '特定ラベルを持つPodと同じノードまたはゾーンへのスケジューリングを避けるようKubernetesに指示する設定。同一コンポーネントのレプリカを異なるノードに分散させて可用性を高める際に使われる。' },
  { term: 'Pod Template', aliases: ['pod template', 'podテンプレート'], description: 'DeploymentやStatefulSetなどのワークロードリソースが新しいPodを作成する際に使用するPodの設計図。spec.templateフィールドに記述され、コンテナ定義・ラベル・リソース設定などが含まれる。' },
  { term: 'Container Lifecycle', aliases: ['container lifecycle', 'コンテナライフサイクル'], description: 'コンテナの起動（PostStart）から終了（PreStop）までの状態遷移とフックイベントの総称。PostStart/PreStopフックを使ってコンテナ起動後・終了前に独自の処理を実行でき、グレースフルな管理が可能になる。' },
  { term: 'Node Exporter', aliases: ['node exporter'], description: 'PrometheusエコシステムのエージェントでLinuxノードのCPU・メモリ・ディスク・ネットワークなどハードウェアレベルのメトリクスを収集してHTTPエンドポイントで公開するOSS。Kubernetesクラスターのノード監視に使われる。' },
];
