// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: iotEmbedded (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // embedded (97), iot (54)
  { term: 'MQTT', aliases: ['mqtt', 'message queuing telemetry transport'], description: 'IoT向けの軽量パブリッシュ/サブスクライブ型メッセージプロトコル。TCP/IP上で動作し、ブローカーを介してデバイス間でメッセージをやり取りする。帯域幅が限られたセンサーネットワークや電力制約のある組込みデバイスで広く使われる。' },
  { term: 'CoAP', aliases: ['coap', 'constrained application protocol'], description: 'リソース制約のあるIoTデバイス向けに設計された軽量なRESTfulプロトコル。UDP上で動作しHTTPと類似のリクエスト/レスポンスモデルを持ち、低電力センサーネットワークやM2M通信に適している。' },
  { term: 'AMQP', aliases: ['amqp', 'advanced message queuing protocol'], description: 'エンタープライズメッセージングのための標準プロトコル。信頼性の高いメッセージキューイング、柔軟なルーティング、トランザクション機能を提供し、RabbitMQなどのブローカーが実装する。' },
  { term: 'フォグコンピューティング', aliases: ['fog computing'], description: 'クラウドとエッジデバイスの中間層でデータ処理を行うアーキテクチャ。ゲートウェイやローカルサーバーで処理することでクラウドへの通信量を削減し、レイテンシを低減してリアルタイム性を高める。' },
  { term: 'RTOS', aliases: ['rtos', 'real-time operating system', 'リアルタイムos'], description: '厳密なタイミング要件を満たすことを保証するオペレーティングシステム。タスクの実行時間に上限を設け決定論的な応答を提供する。組込みシステムや産業制御装置、航空宇宙機器で使われる。' },
  { term: 'FreeRTOS', aliases: ['freertos'], description: 'マイクロコントローラ向けのオープンソースリアルタイムOSカーネル。小フットプリントで多くのMCUアーキテクチャに移植されており、AWSがサポートするIoTデバイス向けの標準的な選択肢の一つ。' },
  { term: 'マイクロコントローラ', aliases: ['mcu', 'microcontroller'], description: 'CPU、メモリ、I/Oペリフェラルを1チップに集積した小型コンピュータ。低コスト・低消費電力で組込み制御に特化しており、ArduinoやSTM32、ESP32などのファミリーが代表例として挙げられる。' },
  { term: 'FPGA', aliases: ['fpga', 'field-programmable gate array'], description: '製造後にユーザーが論理回路を書き換え可能なプログラマブル半導体デバイス。ハードウェア並列処理に優れ、信号処理や機械学習推論の高速化、ASICのプロトタイプ設計などに活用される。' },
  { term: 'GPIO', aliases: ['gpio', 'general purpose input/output'], description: 'マイクロコントローラやSBCが持つ汎用デジタル入出力ピン。センサーの読み取り、LEDやリレーの制御、外部デバイスとの信号通信など多様な用途に対応する基本的なインターフェース。' },
  { term: 'I2C', aliases: ['i2c', 'inter-integrated circuit'], description: '2本の信号線（SDA、SCL）で複数のデバイスを接続できるシリアル通信プロトコル。センサーやEEPROMなどの短距離通信に広く使われ、アドレス指定により同一バスで複数スレーブを管理できる。' },
  { term: 'SPI', aliases: ['spi', 'serial peripheral interface'], description: '4本の信号線を使うフル二重シリアル通信プロトコル。I2Cより高速で、ディスプレイ・SDカード・ADCなどとの通信に使われる。マスター/スレーブ構成で複数デバイスをチップセレクトで切り替える。' },
  { term: 'UART', aliases: ['uart', 'universal asynchronous receiver/transmitter'], description: 'クロック信号なしに非同期でシリアル通信を行うハードウェアインターフェース。GPSモジュールやBluetooth機器、デバッグコンソールとの通信に広く使われ、ボーレートで通信速度を設定する。' },
  { term: 'PWM', aliases: ['pwm', 'pulse width modulation', 'パルス幅変調'], description: 'デジタル信号のパルス幅（デューティ比）を変化させてアナログ量を模擬する技術。DCモーターの速度制御、LEDの輝度調整、サーボモーター制御など組込みシステムで幅広く使われる。' },
  { term: 'センサーフュージョン', aliases: ['sensor fusion'], description: '複数のセンサーデータを統合して単一センサーでは得られない精度や情報を導き出す技術。加速度計・ジャイロスコープ・磁気センサーを組み合わせたカルマンフィルタによる姿勢推定が代表例。' },
  { term: 'デジタルツイン', aliases: ['digital twin'], description: '物理的なオブジェクトや環境をリアルタイムにデジタル空間に再現した仮想モデル。センサーデータを継続的に受け取りシミュレーションや予知保全、最適化に活用されるIoT基盤技術。' },
  { term: 'OTAアップデート', aliases: ['otaアップデート', 'over-the-air update', 'ota'], description: 'デバイスのファームウェアやソフトウェアを無線通信経由でリモートから更新する仕組み。物理アクセスなしにセキュリティパッチや機能追加を大量デバイスに一斉展開できる重要な運用機能。' },
  { term: 'ファームウェア', aliases: ['firmware'], description: 'ハードウェアに組み込まれた低レベルのソフトウェア。ROMやフラッシュメモリに格納されデバイスの基本動作を制御する。マイクロコントローラ、ルーター、IoTデバイスの動作の核となる。' },
  { term: 'ウォッチドッグタイマー', aliases: ['watchdog timer', 'wdt'], description: 'システムのハングアップやフリーズを検出して自動リセットをかけるハードウェアタイマー。ソフトウェアが定期的にタイマーをクリアしない場合にリセット信号を発生させ、デバイスの自律回復を実現する。' },
  { term: '割り込み', aliases: ['interrupt', 'irq'], description: '外部イベントや内部条件に応じてCPUが現在の処理を中断し、割り込みハンドラを実行する仕組み。リアルタイム応答を実現するための基本メカニズムで、RTOS設計の中核をなす概念。' },
  { term: 'DMA', aliases: ['dma', 'direct memory access'], description: 'CPUを介さずに周辺デバイスとメモリ間でデータを直接転送するコントローラ。大量データの転送中にCPUを他の処理に使えるため、システム全体のスループットとエネルギー効率が向上する。' },
  { term: 'メモリマップドI/O', aliases: ['メモリマップドi/o', 'memory-mapped i/o', 'mmio'], description: '周辺デバイスのレジスタをメモリアドレス空間にマッピングし、通常のメモリ読み書き命令でデバイスを制御する方式。多くのマイクロコントローラとSoCで採用されているハードウェア設計手法。' },
  { term: '組込みLinux', aliases: ['組込みlinux', 'embedded linux'], description: 'Linuxカーネルを組込みデバイス向けにカスタマイズしたOS。Raspberry PiやルーターなどのSBC、産業機器で使われ、豊富なドライバと開発ツールを活用できる。' },
  { term: 'Yocto', aliases: ['yocto'], description: '組込みLinuxディストリビューションをカスタムビルドするためのオープンソースプロジェクト。BitBakeビルドシステムとレシピを使い、特定のハードウェア向けに最小限かつ最適化されたLinuxイメージを生成できる。' },
  { term: 'Buildroot', aliases: ['buildroot'], description: 'クロスコンパイルツールチェーンと組込みLinuxシステムイメージを生成するシンプルなビルドシステム。Yoctoより学習コストが低く、中小規模の組込みLinuxプロジェクトに適している。' },
  { term: 'Device Tree', aliases: ['device tree', 'デバイスツリー', 'dtb'], description: 'Linuxカーネルに対してハードウェア構成（CPU・メモリ・ペリフェラルのアドレスなど）を記述するデータ構造。ハードコードされたハードウェア情報をカーネルから分離し移植性を高める。' },
  { term: 'BLE', aliases: ['ble', 'bluetooth low energy', 'bluetooth le'], description: '低電力消費のBluetoothプロトコル。ウェアラブルデバイス、医療機器、スマートホームデバイスとスマートフォンの通信に広く使われ、コイン電池でも年単位で動作できる省電力規格。' },
  { term: 'Zigbee', aliases: ['zigbee'], description: '低電力・低速・低コストなメッシュネットワーク対応の無線通信規格。IEEE 802.15.4ベースでスマートホームデバイスや産業用センサーネットワークに使われ、数十ノードのメッシュ構成が可能。' },
  { term: 'Z-Wave', aliases: ['z-wave'], description: 'スマートホーム向けの低電力メッシュ無線通信プロトコル。868/908MHz帯を使いWi-Fiと干渉しにくく、スイッチ、電子錠、センサーなどのホームオートメーション機器で幅広く採用される。' },
  { term: 'LoRaWAN', aliases: ['lorawan', 'long range wide area network'], description: 'LoRa無線変調技術を使った長距離・省電力なIoT向けWAN規格。数kmから数十kmの通信範囲を持ち、農業センサー、スマートメーター、資産追跡などのLPWANユースケースに適する。' },
  { term: 'NB-IoT', aliases: ['nb-iot', 'narrowband iot'], description: 'LTEインフラを活用したIoT向けのナローバンド通信規格。セルラーネットワーク上で動作し、地下や建物内など電波が届きにくい環境でも通信できる低コスト・省電力なLPWAN技術。' },
  { term: 'LTE-M', aliases: ['lte-m', 'lte-mtc', 'emtc'], description: 'LTEネットワーク上で動作するIoT向けの通信規格。NB-IoTより高いデータレートと移動体対応を持ち、ウェアラブルや資産追跡など移動するデバイスへの接続に適している。' },
  { term: 'LPWAN', aliases: ['lpwan', 'low power wide area network'], description: '低電力で広範囲をカバーするIoT向け無線ネットワーク技術のカテゴリー。LoRaWAN、NB-IoT、Sigfoxなどが含まれ、電池駆動センサーの長距離通信を低コストで実現する。' },
  { term: 'Matter', aliases: ['matter'], description: 'Apple、Google、Amazonなど主要企業が支持するスマートホーム向けの相互接続標準プロトコル。Wi-Fi、Ethernet、ThreadをトランスポートとしてCSA（接続標準同盟）が策定し普及を推進している。' },
  { term: 'HomeKit', aliases: ['homekit'], description: 'AppleのスマートホームフレームワークでiOSデバイスから対応デバイスを制御できる。Siriを使った音声操作やオートメーションを実現し、HomeKit Accessory Protocolでセキュアに端末間連携する。' },
  { term: 'AWS IoT Core', aliases: ['aws iot core', 'aws iot'], description: 'AmazonのマネージドIoTサービス。MQTTやHTTPSでデバイスをクラウドに接続し、デバイスシャドウ、ルールエンジン、Device Defenderなどの機能を提供してIoTソリューション構築を支援する。' },
  { term: 'Azure IoT Hub', aliases: ['azure iot hub', 'azure iot'], description: 'MicrosoftのマネージドIoTサービス。デバイスとクラウドの双方向通信、デバイス管理、OTAアップデートを提供し、Azure Stream AnalyticsやAzure MLと連携してエッジ-クラウド統合を実現する。' },
  { term: 'Google Cloud IoT', aliases: ['google cloud iot', 'cloud iot core'], description: 'GoogleのIoTデバイス管理サービス（2023年廃止）。MQTTとHTTPでデバイスをCloud Pub/Subに接続し、BigQueryやDataflowでリアルタイム分析するアーキテクチャパターンで使われていた。' },
  { term: 'TinyML', aliases: ['tinyml'], description: 'マイクロコントローラなどの超小型・低電力デバイス上で機械学習モデルを実行する技術分野。TensorFlow LiteやEdge Impulseを使い、クラウド接続なしでのリアルタイム推論を実現する。' },
  { term: 'ONNX Runtime', aliases: ['onnx runtime', 'onnx', 'open neural network exchange'], description: '様々なフレームワークで訓練した機械学習モデルを統一フォーマット（ONNX）で表現し高速に推論するランタイム。エッジデバイスからクラウドまで幅広いプラットフォームで動作し最適化が施される。' },
  { term: 'TensorFlow Lite', aliases: ['tensorflow lite', 'tflite'], description: 'Googleが開発したモバイル・組込みデバイス向けの機械学習推論フレームワーク。モデルを量子化・最適化してフットプリントを削減し、AndroidやiOS、マイクロコントローラで動作させられる。' },
  { term: 'DAC', aliases: ['dac', 'digital-to-analog converter', 'デジタルアナログ変換器'], description: 'デジタル数値信号をアナログ電圧・電流に変換する回路または集積回路。音声出力、波形生成、サーボモーター制御などの用途でマイクロコントローラと組み合わせて幅広く使われる。' },
  { term: '5G IoT', aliases: ['5g iot', '5g', 'nr iot'], description: '第5世代移動通信システムをIoTに活用する技術。超低遅延・超高密度接続・高帯域を活かし、自動運転、スマートファクトリー、遠隔医療など高度なユースケースを実現する通信基盤。' },
  { term: 'フラッシュメモリ', aliases: ['flash memory', 'nand flash'], description: '電気的に書き換え可能な不揮発性半導体メモリ。組込みデバイスのファームウェア格納、SSD、USBメモリ、スマートフォンのストレージとして広く使われ、書き込み回数に上限がある。' },
  { term: 'JTAG', aliases: ['jtag'], description: 'IEEE 1149.1に規定されたシリアルデバッグ・テストインターフェース。マイクロコントローラやFPGAのオンチップデバッグ、境界スキャンテスト、フラッシュへの書き込みに広く利用される。' },
  { term: 'SWD', aliases: ['swd', 'serial wire debug'], description: 'ARM CoreSight技術の一部であるARMデバイス用の2ピンシリアルデバッグプロトコル。JTAGより少ないピン数でデバッグ・フラッシュ書き込みができSTM32などのARM Cortexデバイスで広く使われる。' },
  { term: 'CAN', aliases: ['can', 'controller area network'], description: '自動車や産業機器向けの堅牢なシリアル通信バスプロトコル。マルチマスター構成でノイズ耐性が高く、ECU（エンジン制御ユニット）間通信や産業用ロボット制御に広く使われる。' },
  { term: 'Modbus', aliases: ['modbus'], description: '産業用機器向けのシリアル通信プロトコル。RTU・ASCII・TCPの3モードがあり、PLC・センサー・インバーターとSCADAシステムを接続するために長年にわたり広く使われているレガシー規格。' },
  { term: 'OBD-II', aliases: ['obd-ii', 'on-board diagnostics'], description: '自動車の故障診断用標準インターフェースとプロトコルセット。エンジンの状態・センサー値・エラーコードを読み出せ、スマートフォンアプリやテレマティクス機器と連携して活用される。' },
  { term: 'SCADA', aliases: ['scada', 'supervisory control and data acquisition'], description: '産業プロセスをリモートから監視・制御するシステム。センサーやPLCからデータを収集して中央コンソールで可視化・操作する。水処理、電力インフラ、製造ラインで長年使われる制御システム。' },
  { term: 'PLC', aliases: ['plc', 'programmable logic controller'], description: '工場や産業設備の制御に使われる堅牢なコンピュータ。ラダー図などの専用言語でプログラムしセンサー入力に応じてアクチュエータを制御する。高い信頼性と長期サポートが特徴。' },
  { term: 'TPM', aliases: ['tpm', 'trusted platform module'], description: '暗号鍵の生成・保管と機器の完全性測定を行う専用セキュリティチップ。IoTデバイスの安全なブート、デバイス認証、セキュアストレージに使われデバイス信頼の根幹（Root of Trust）を担う。' },
  { term: 'TrustZone', aliases: ['trustzone'], description: 'ARMプロセッサのハードウェアセキュリティ拡張機能。通常ワールドとセキュアワールドをハードウェアで分離し、暗号鍵・生体認証データ・DRM資産などをセキュアワールドで保護する仕組み。' },
  { term: 'Sigfox', aliases: ['sigfox'], description: '超狭帯域（UNB）無線技術を使った低電力・長距離のIoT向けLPWANサービス。専用基地局ネットワークでグローバルカバレッジを提供し、スマートメーターや環境センサーの通信に使われる。' },
  { term: 'Zephyr RTOS', aliases: ['zephyr rtos', 'zephyr'], description: 'Linux Foundation傘下のオープンソースリアルタイムOS。IoTデバイス向けに設計されBLE・IEEE 802.15.4・IPネットワークスタックを統合し、多くのマイクロコントローラアーキテクチャをサポートする。' },
  { term: 'マイコン', description: 'CPU・メモリ・I/Oペリフェラルを1チップに集積した小型コンピュータ。家電・自動車・産業機器・IoT機器に組み込まれ、センサー入力の処理やモーター制御など専用の制御タスクを担う。Arduino・Raspberry Pi Pico・M5Stack等の開発ボードに搭載される。' },
  { term: 'Arduino', aliases: ['arduino', 'arduino platform'], description: 'オープンソースの電子工作プラットフォーム。AVRやARM系マイコンを搭載した開発ボードと、C/C++ベースのArduino IDEを提供する。初心者から上級者まで幅広く使われ、豊富なライブラリとシールド（拡張基板）のエコシステムを持つ。' },
  { term: 'Arduino UNO R4 WiFi', aliases: ['arduino uno r4 wifi', 'uno r4 wifi'], description: 'Renesas RA4M1（Arm Cortex-M4/48MHz）搭載のArduino UNO最新モデル。ESP32-S3によるWi-Fi/BLE接続、12x8 LEDマトリクス、USB-C、CAN対応を備え、IoTプロジェクトに適した入門ボード。' },
  { term: 'Arduino Nano R4', aliases: ['arduino nano r4', 'nano r4'], description: 'Arduino Nanoフォームファクタを採用したRenesas RA4M1搭載のコンパクト開発ボード。ブレッドボードに直接挿せるサイズでありながら、UNO R4同等の処理性能を持つ小型プロジェクト向けボード。' },
  { term: 'Arduino Nano ESP32', aliases: ['arduino nano esp32', 'nano esp32'], description: 'ESP32-S3を搭載したArduino Nanoフォームファクタの開発ボード。Wi-Fi/BLE接続、MicroPython対応、Arduino Cloud統合が特徴で、Nanoサイズで無線IoTプロジェクトを実現できる。u-blox NORA-W106モジュールを採用。' },
  { term: 'Arduino Plug and Make Kit', aliases: ['arduino plug and make kit', 'plug and make kit'], description: 'Arduino UNO R4 WiFiとModulinoセンサーモジュール群をセットにしたスターターキット。配線不要のQwiic接続でセンサーを接続でき、Arduino Cloudとの連携でIoTプロジェクトを簡単に始められる教育・入門向けパッケージ。' },
  { term: 'Arduino UNO Rev3', aliases: ['arduino uno rev3', 'uno rev3', 'arduino uno r3'], description: 'ATmega328Pを搭載したArduinoの代表的な開発ボード。14本のデジタルI/O・6本のアナログ入力・16MHz動作で、電子工作の入門ボードとして世界中で最も普及したマイコンボードの一つ。5V動作。' },
  { term: 'Raspberry Pi Pico', aliases: ['raspberry pi pico', 'pi pico'], description: 'Raspberry Pi財団が設計したRP2040搭載の小型マイコンボード。デュアルコアArm Cortex-M0+/133MHz、264KB SRAM、2MB Flash、26本のGPIOを備え、低価格ながら高いI/O性能を持つ。MicroPythonとC/C++ SDKで開発可能。' },
  { term: 'Raspberry Pi Pico 2', aliases: ['raspberry pi pico 2', 'pi pico 2'], description: 'RP2350搭載のRaspberry Pi Picoの後継ボード。デュアルコアArm Cortex-M33/150MHzとRISC-V Hazard3コアのデュアルアーキテクチャ、520KB SRAM、4MB Flash、セキュリティ機能（Arm TrustZone）を備え、性能とセキュリティが大幅に向上。' },
  { term: 'Raspberry Pi Pico 2 W', aliases: ['raspberry pi pico 2 w', 'pi pico 2 w'], description: 'Raspberry Pi Pico 2にCYW43439無線モジュールを追加し、2.4GHz Wi-FiとBluetooth 5.2（BLE）に対応した無線通信付きマイコンボード。IoTプロジェクトや無線センサーノードに最適。' },
  { term: 'M5Stack', aliases: ['m5stack', 'm5stack platform'], description: 'ESP32を中心としたモジュール式IoT開発プラットフォーム。ケース付きのスタッカブルな筐体に液晶・ボタン・バッテリーを内蔵し、Grove/I2C対応の豊富なセンサーユニットとUiFlowビジュアルプログラミングで迅速なプロトタイピングを実現する。' },
  { term: 'M5Stack Basic v2.7', aliases: ['m5stack basic v2.7', 'm5stack basic'], description: 'ESP32-D0WDQ6-V3搭載のM5Stackの基本モデル（v2.7）。2インチIPS液晶・3ボタン・スピーカー・microSDスロット・110mAhバッテリーを内蔵し、16MB Flash/8MB PSRAMで余裕のあるメモリ構成を持つ。' },
  { term: 'M5StickC', aliases: ['m5stickc', 'm5stickc plus'], description: 'ESP32-PICO搭載のスティック型超小型M5Stack開発ボード。0.96インチTFT液晶・6軸IMU・赤外線LED・80mAhバッテリーを内蔵し、帽子型のHATモジュールで機能拡張できるウェアラブル・小型IoT向けデバイス。' },
  { term: 'M5StickC Plus2', aliases: ['m5stickc plus2', 'm5stickc plus 2'], description: 'M5StickCの後継モデル。1.14インチTFT液晶に大型化し、200mAhバッテリー・ブザー・6軸IMU・赤外線LED・マイクを搭載。ESP32-PICO-V3-02による安定した無線性能と、Grove/HATポートによる拡張性を持つ。' },
  { term: 'M5Atom', aliases: ['m5atom', 'atom lite', 'atom matrix'], description: '24×24mmの超小型ESP32搭載M5Stack開発ボード。ATOM Liteは1個のRGB LED、ATOM Matrixは5×5 RGB LEDマトリクスとIMUを搭載。Grove対応で小型IoTノードやスマートホームの制御ユニットに適する。' },
  { term: 'Core2', aliases: ['core2', 'm5stack core2', 'm5stack core2 v1.1'], description: 'ESP32-D0WDQ6-V3搭載のM5Stackタッチスクリーン対応モデル。2インチIPS静電容量式タッチパネル・振動モーター・マイク・スピーカー・IMU・390mAhバッテリーを内蔵し、AWSやAzure IoT連携にも対応する上位モデル。' },
  { term: 'STM32', aliases: ['stm32', 'stm32ファミリ'], description: 'STMicroelectronics社が提供するArm Cortex-Mコア搭載32bitマイコンファミリの総称。Cortex-M0/M3/M4/M7/M33など多数のシリーズがあり、産業用・民生用・自動車用まで幅広い組み込み市場で使用される。STM32CubeIDEやHALライブラリで開発する。' },
  { term: 'STM32 Nucleo-F411RE', aliases: ['stm32 nucleo-f411re', 'nucleo-f411re'], description: 'STM32F411RE（Arm Cortex-M4/100MHz/512KB Flash/128KB SRAM）搭載のST公式評価ボード。Arduino互換ピンヘッダとST Morphoコネクタを備え、ST-LINK/V2-1デバッガ内蔵でUSB給電・デバッグが可能。' },
  { term: 'STM32 Nucleo-U575ZI', aliases: ['stm32 nucleo-u575zi', 'nucleo-u575zi', 'nucleo-u575zi-q'], description: 'STM32U575ZIT6Q（Arm Cortex-M33/160MHz/2MB Flash/786KB SRAM）搭載の超低消費電力Nucleoボード。TrustZoneセキュリティ対応、ST Zio/Morphoコネクタ搭載で、セキュアIoTや省電力アプリケーションの開発・評価に使用される。' },
  { term: 'RP2040', aliases: ['rp2040', 'raspberry pi rp2040'], description: 'Raspberry Pi財団が独自設計したデュアルコアArm Cortex-M0+マイコン。133MHz動作・264KB SRAM・30本のGPIO・PIOステートマシンを搭載し、Raspberry Pi Picoに採用された。低価格（1ドル台）と高いI/O柔軟性が特徴。' },
  { term: 'RP2350', aliases: ['rp2350', 'raspberry pi rp2350'], description: 'RP2040の後継となるRaspberry Pi財団設計のマイコン。Arm Cortex-M33×2とRISC-V Hazard3×2のデュアルアーキテクチャを持ち、150MHz動作・520KB SRAM・TrustZone対応。Raspberry Pi Pico 2に搭載され、セキュリティと性能が大幅に向上。' },
  { term: 'CYW43439', aliases: ['cyw43439', 'infineon cyw43439'], description: 'Infineon（旧Cypress）製の無線コンボチップ。2.4GHz Wi-Fi（802.11n）とBluetooth 5.2（BLE/BR/EDR）を1チップで提供し、Raspberry Pi Pico WおよびPico 2 Wに搭載されている。低消費電力設計でIoTデバイスに適する。' },
  { term: 'ATmega', aliases: ['atmega', 'atmega328p', 'atmega2560', 'avrマイコン'], description: 'Microchip（旧Atmel）社のAVRアーキテクチャ8bitマイコンファミリ。ATmega328PはArduino UNO、ATmega2560はArduino Megaに搭載され、Arduino文化の基盤となった。Flash/SRAM/EEPROMを内蔵しC/C++で開発する。' },
  { term: 'AVR', aliases: ['avr', 'avrアーキテクチャ'], description: 'Atmel（現Microchip）が開発した8bitRISCマイコンアーキテクチャ。tinyAVR・megaAVR・AVR Dxシリーズがあり、Arduino UNOのATmega328Pが代表例。ハーバードアーキテクチャで1クロック1命令実行が特徴。' },
  { term: 'tinyAVR 1シリーズ', aliases: ['tinyavr 1シリーズ', 'tinyavr 1-series', 'attiny1シリーズ'], description: 'Microchip社のtinyAVRファミリのモダンシリーズ。ATTINY816/1616/3216等が含まれ、従来のATtinyから大幅に機能強化されたペリフェラル（CCL・DAC・イベントシステム等）を搭載。UPDI単線プログラミングで書き込む。' },
  { term: 'ATTINY1616 DIP化キット', aliases: ['attiny1616 dip化キット', 'attiny1616 dip化基板'], description: '表面実装パッケージ（SOIC20/VQFN20）のATTINY1616をDIP20ピン変換基板に実装したキット。ブレッドボードに直接挿せるため、tinyAVR 1シリーズの学習や試作に便利。秋月電子等で入手可能。' },
  { term: 'PIC16F', aliases: ['pic16f', 'pic16f18313-i/p', 'pic16fシリーズ', 'picマイコン'], description: 'Microchip社の8bit PICマイコンファミリ。PIC16F18313は8ピンDIPで入手しやすく、CLC・DAC・PWM等の豊富なペリフェラルを搭載する。MPLAB X IDEとXCコンパイラで開発し、低価格・低消費電力が特徴。' },
  { term: 'CH32V203K8T6', aliases: ['ch32v203k8t6', 'ch32v203', 'wch ch32v'], description: 'WCH（南京沁恒）社のRISC-Vコア搭載32bitマイコン。144MHz動作・64KB Flash・20KB SRAM・USB/CAN/I2C/SPI搭載で、STM32互換のペリフェラル構成を持つ。低価格なRISC-Vマイコンとして注目されている。' },
  { term: 'Arm Cortex-M33', aliases: ['arm cortex-m33', 'cortex-m33'], description: 'Arm社が設計したARMv8-Mアーキテクチャの高性能組み込みプロセッサコア。DSP拡張・FPU・TrustZoneセキュリティを標準搭載し、RP2350やSTM32U5シリーズ等の次世代マイコンに採用される。Cortex-M4の後継として位置づけられる。' },
  { term: 'Cortex-M4', aliases: ['cortex-m4', 'arm cortex-m4'], description: 'Arm社設計のARMv7-Mアーキテクチャ中〜高性能組み込みプロセッサコア。DSP命令とオプションのFPUを搭載し、STM32F4シリーズやRenesas RA4M1等に広く採用される。信号処理と制御の両立が可能なバランスの良いコア。' },
  { term: 'RISC-V', aliases: ['risc-v', 'risc-v isa'], description: 'カリフォルニア大学バークレー校で開発されたオープンソースの命令セットアーキテクチャ。ライセンスフリーでカスタマイズ可能なため、WCH CH32VシリーズやRP2350のHazard3コア等、組み込みからサーバーまで幅広く採用が進む。' },
  { term: 'Hazard3', aliases: ['hazard3', 'hazard3 risc-vコア'], description: 'Raspberry Pi財団がRP2350向けに設計した2ステージRISC-Vプロセッサコア。RV32IMAZbkb_Zbs_Zcb_Zcmp拡張に対応し、Arm Cortex-M33との切り替え実行が可能なデュアルアーキテクチャ構成で動作する。' },
  { term: 'RA4M1', aliases: ['ra4m1', 'renesas ra4m1', 'r7fa4m1ab3cfm'], description: 'Renesas社のRAファミリに属するArm Cortex-M4搭載32bitマイコン。48MHz動作・256KB Flash・32KB SRAM・USB 2.0 Full Speed・CAN・14bit ADC搭載。Arduino UNO R4 WiFi/Minima等に採用されている。' },
  { term: 'NORA-W106', aliases: ['nora-w106', 'u-blox nora-w106'], description: 'u-blox社のESP32-S3搭載Wi-Fi/Bluetoothモジュール。2.4GHz Wi-Fi（802.11b/g/n）とBluetooth LE 5.0に対応し、Arduino Nano ESP32に採用されている。技適取得済みで日本国内でも使用可能な無線モジュール。' },
  { term: 'Espressif', aliases: ['espressif', 'espressif systems', '乐鑫科技'], description: 'ESP32/ESP8266シリーズのWi-Fi/Bluetooth内蔵マイコンを開発する上海の半導体メーカー。IoT向けSoCで圧倒的シェアを持ち、M5Stack・Arduino Nano ESP32等多くの開発ボードに採用される。ESP-IDFとArduinoコアを提供。' },
  { term: 'Atmel', aliases: ['atmel', 'atmel corporation'], description: 'AVRマイコンとSAM（ARM）マイコンを開発した米国の半導体メーカー。2016年にMicrochip Technology社に買収された。Arduino UNOのATmega328PやATtinyシリーズの設計元として電子工作文化に大きく貢献した。' },
  { term: 'Microchip', aliases: ['microchip', 'microchip technology', 'mchp'], description: 'PICマイコン・AVRマイコン・SAMマイコンを擁する米国の大手半導体メーカー。2016年のAtmel買収でAVR/SAMファミリを取得し、8bit〜32bitの広範なマイコン製品群とMPLAB X開発環境を提供する。' },
  { term: 'Raspberry Pi', aliases: ['raspberry pi', 'raspberry pi foundation', 'ラズパイ'], description: '英国のRaspberry Pi財団が開発する教育・ホビー向けシングルボードコンピュータおよびマイコンのブランド。Linux搭載のRaspberry Pi 5等のSBCと、RP2040/RP2350搭載のPicoシリーズのマイコンボードを展開する。' },
  { term: 'Renesas', aliases: ['renesas', 'renesas electronics', 'ルネサスエレクトロニクス'], description: '日立・三菱電機・NEC系の半導体事業を統合した日本最大のマイコンメーカー。RA（Arm）・RX・RL78ファミリを展開し、自動車・産業機器で高いシェアを持つ。Arduino UNO R4にRA4M1が採用されたことで組み込み教育分野にも進出。' },
  { term: 'u-blox', aliases: ['u-blox ag'], description: 'スイスの半導体メーカー。GNSS（GPS）モジュール・セルラーモジュール・Wi-Fi/Bluetoothモジュールを提供し、IoTやM2M通信分野で高いシェアを持つ。Arduino Nano ESP32にはu-blox NORA-W106モジュールが搭載されている。' },
  { term: '秋月電子', aliases: ['秋月電子通商', 'akizuki denshi'], description: '東京・秋葉原に本店を持つ電子部品・マイコンボード・計測器の専門通販・小売店。ATTINY1616 DIP化キットやPICマイコン等の組み込み部品を個人向けに販売し、日本の電子工作・ホビー開発者に広く利用されている。' },
  { term: '開発ボード', aliases: ['development board', '評価基板', '評価ボード'], description: 'マイコンやSoCを搭載し、プログラミング・デバッグ・ペリフェラル接続のためのコネクタやインターフェースを備えた基板。Arduino UNO・Raspberry Pi Pico・STM32 Nucleo・M5Stack等がある。プロトタイピングや学習に使用される。' },
  { term: '電子工作', aliases: ['electronics hobby', 'diy electronics', 'diy projects'], description: '電子部品やマイコンを使って回路やデバイスを自作する趣味・教育活動。LEDの点灯からIoTデバイスの製作まで幅広く、Arduino・Raspberry Pi・M5Stackなどのプラットフォームの普及で参入障壁が下がっている。' },
  { term: '組み込み開発', aliases: ['embedded development', '組み込みシステム開発', '組み込み'], description: 'マイコンやSoCを使用して専用機器に搭載するソフトウェアを開発すること。リアルタイム制御・省メモリ・低消費電力が求められ、C/C++・RTOS・ベアメタルプログラミングが主な手法。自動車・家電・医療機器・IoT機器で不可欠な分野。' },
  { term: 'IoT', aliases: ['iot', 'internet of things', 'モノのインターネット', 'iot機器', 'iotセンサー'], description: 'センサーやアクチュエーターを内蔵した機器がインターネットに接続し、データの収集・分析・制御を行う技術概念。温湿度監視・スマートホーム・工場の予知保全等に応用され、ESP32やRaspberry Pi Pico W等のWi-Fi対応マイコンが基盤となる。' },
  { term: 'スマートホーム', aliases: ['smart home', 'smart home control', 'ホームオートメーション'], description: '照明・空調・家電・セキュリティ等を自動化・遠隔制御する住宅技術。ESP32やM5Stack等のマイコンでセンサー入力やリレー制御を行い、Wi-Fi/MQTT/Bluetooth経由でスマホや音声アシスタントから操作するDIYプロジェクトも盛ん。' },
  { term: 'ロボット', aliases: ['robot', 'ロボティクス'], description: 'センサー・アクチュエーター・マイコンを組み合わせて自律動作や遠隔操作を行う機械システム。サーボモーター制御・距離センサーによる障害物回避・ライントレースなどをArduinoやRaspberry Piで実装する電子工作の人気テーマ。' },
  { term: 'リモコン', aliases: ['remote controller', '赤外線リモコン', 'irリモコン'], description: '赤外線（IR）やBluetooth/Wi-Fiを使って機器を無線で遠隔操作する送受信デバイス。マイコンで赤外線LEDを制御してテレビやエアコンのリモコン信号を送信・学習・再生するプロジェクトが電子工作で人気。M5StickCは赤外線LED内蔵で便利。' },
  { term: 'Arduino IDE', aliases: ['arduino ide', 'arduino ide 2.0'], description: 'Arduinoボード向けの公式統合開発環境。C/C++ベースのスケッチを記述・コンパイル・書き込みでき、ライブラリマネージャやボードマネージャで多数のボードに対応する。IDE 2.0ではVSCode由来のコード補完・デバッグ機能が追加された。' },
  { term: 'ESP-IDF', aliases: ['esp-idf', 'espressif iot development framework'], description: 'Espressif公式のESP32/ESP32-S3/ESP32-C3向けC/C++開発フレームワーク。FreeRTOS・Wi-Fi/BTスタック・暗号化・OTA更新等を含む本格的な組み込み開発環境で、Arduino環境では不十分な低レベル制御やパフォーマンスが必要な場合に使用する。' },
  { term: 'PlatformIO', aliases: ['platformio', 'platformio ide', 'pio'], description: 'VSCode拡張として動作するクロスプラットフォーム組み込み開発環境。Arduino・ESP-IDF・STM32 HAL・Mbed等の複数フレームワークに対応し、ライブラリ管理・ユニットテスト・リモートデバッグを統合した開発ワークフローを提供する。' },
  { term: 'STM32CubeIDE', aliases: ['stm32cubeide', 'cubeide', 'stm32cubemx'], description: 'STMicroelectronics公式のSTM32向け統合開発環境。Eclipse/CDTベースのIDEにCubeMXのグラフィカルピン・クロック設定ツールを統合し、HAL/LLドライバのコード生成・コンパイル・ST-LINKデバッグを一貫して行える。' },
  { term: 'MicroPython', aliases: ['micropython', 'micropython firmware', 'μpython'], description: 'マイコン上で動作するPython 3のサブセット実装。REPL対話環境でハードウェアを即座に制御でき、Raspberry Pi Pico・ESP32・M5Stackで公式サポートされる。C/C++に比べ開発速度が速く、教育やプロトタイピングに適する。' },
  { term: 'C/C++', aliases: ['c/c++', 'c言語', 'c++'], description: '組み込み開発で最も広く使用されるプログラミング言語。C言語はハードウェア直接制御と省メモリが強みで、C++はクラス・テンプレートによる抽象化を追加する。Arduino・ESP-IDF・STM32 HAL等の主要フレームワークがC/C++で記述されている。' },
  { term: 'UiFlow1', aliases: ['uiflow1', 'uiflow', 'uiflow v1'], description: 'M5Stack向けのBlockly（ブロックプログラミング）＋MicroPythonベースの視覚的開発環境。Webブラウザ上でブロックを組み合わせてプログラムを作成し、Wi-Fi経由でM5Stackに転送・実行できる。プログラミング初心者やSTEAM教育に適する。' },
  { term: 'UiFlow2', aliases: ['uiflow2', 'uiflow v2'], description: 'UiFlow1の後継となるM5Stack向け開発環境。Blockly+MicroPythonに加えPython直接編集モードを強化し、UI改善・新デバイスサポート・クラウド連携機能を追加。M5Stack Core2やATOM系デバイスにも対応する次世代版。' },
  { term: 'M5Unified', aliases: ['m5unified', 'm5unified library'], description: 'M5Stack全製品（Basic/Core2/StickC/Atom等）を統一APIで扱えるArduinoライブラリ。ディスプレイ・IMU・ボタン・スピーカー等のペリフェラルをデバイス種別を問わず共通コードで制御でき、機種間のコード移植が容易になる。' },
  { term: 'Arduino Cloud', aliases: ['arduino cloud', 'arduino iot cloud'], description: 'Arduino公式のIoTクラウドプラットフォーム。Wi-Fi対応ボード（UNO R4 WiFi・Nano ESP32等）からセンサーデータを送信し、ダッシュボードで可視化・遠隔制御が可能。OTA更新・Webhook連携・Alexa/Google Home統合もサポートする。' },
  { term: 'Wi-Fi', aliases: ['wi-fi', 'wifi', '無線lan', '802.11', '2.4ghz wi-fi'], description: 'IEEE 802.11規格に基づく無線LAN技術。組み込み開発では2.4GHz帯（802.11b/g/n）が主流で、ESP32・CYW43439等のモジュールでマイコンにWi-Fi接続を追加する。IoTデバイスのクラウド通信やWebサーバ機能の実現に不可欠。' },
  { term: 'Bluetooth', aliases: ['bluetooth', 'bt', 'br/edr'], description: '近距離無線通信規格。Classic Bluetooth（BR/EDR）は音声・データ通信、Bluetooth Low Energy（BLE）は低消費電力のセンサー・ビーコン通信に使用される。ESP32・CYW43439・NORA-W106等がBLE対応し、スマホ連携やウェアラブル機器に活用される。' },
  { term: 'USB', aliases: ['usb', 'universal serial bus', 'usb type-c', 'usb micro b', 'usbデバイス'], description: 'コンピュータと周辺機器を接続するシリアル通信規格。組み込み開発ではマイコンへの電源供給・プログラム書き込み・シリアルモニタ通信に使用する。最新ボードはUSB Type-Cを採用し、旧モデルはUSB micro Bを使用する。USB 2.0 Full Speed対応が一般的。' },
  { term: 'HID', aliases: ['hid', 'human interface device', 'hidエミュレーション', 'usbキーボードエミュレーション'], description: 'USB規格でキーボード・マウス・ゲームパッド等の入力デバイスを定義するデバイスクラス。マイコンをHIDデバイスとして認識させると、PCにキー入力やマウス操作を送信できる。Arduino Leonardo/Pro MicroやRP2040がネイティブUSB HIDに対応。' },
  { term: 'RTC', aliases: ['rtc', 'real-time clock', 'リアルタイムクロック'], description: 'バッテリーバックアップで時刻を保持し続ける専用ICまたはマイコン内蔵の時計機能。DS3231等の外付けRTCモジュールや、STM32内蔵RTCで日時管理を行い、データロガーやスケジュール制御に使用する。' },
  { term: 'IMU', aliases: ['imu', 'inertial measurement unit', '慣性計測装置', '6軸imu'], description: '加速度センサーとジャイロスコープを組み合わせた慣性計測ユニット。3軸加速度＋3軸ジャイロの6軸IMUが一般的で、M5StickC（MPU6886）やM5Atom等に内蔵される。姿勢検出・ジェスチャー認識・振動監視に使用する。' },
  { term: 'CCL', aliases: ['ccl', 'configurable custom logic', 'カスタムロジック'], description: 'tinyAVR/megaAVR/AVR Dxシリーズに搭載されたプログラマブルロジックブロック。AND/OR/NOT等の論理演算をハードウェアで実行し、CPUを介さずにGPIO信号の組み合わせやフィルタリングを行える省電力・低遅延の機能。' },
  { term: 'タッチ入力', aliases: ['touch input', '静電容量タッチ', 'タッチセンサー'], description: '指の接触を静電容量の変化で検出する入力方式。ESP32は内蔵タッチセンサーピンで物理ボタンなしのタッチ入力を実現でき、M5Stack Core2は静電容量式タッチパネルを搭載する。ボタン代替やジェスチャーUIに使用。' },
  { term: 'タイマ', aliases: ['timer', 'ハードウェアタイマ', 'タイマ割り込み'], description: 'マイコン内蔵のカウンタ回路で、一定間隔での割り込み発生・PWM信号生成・パルス幅計測等に使用する。タイマ割り込みにより正確な周期処理を実現し、モーター制御やセンサーの定期読み取りに不可欠なペリフェラル。' },
  { term: '赤外線送信', aliases: ['ir transmitter', '赤外線led', 'ir送信'], description: '赤外線LEDから変調した赤外光を発射してリモコン信号を送信する技術。NECプロトコル等の変調方式でテレビ・エアコン等の家電を制御する。M5StickCは赤外線LED内蔵で、マイコンとIRライブラリで学習リモコンを自作できる。' },
  { term: 'スリープ', aliases: ['sleep mode', '深いスリープ', 'deep sleep', 'スリープモード'], description: 'マイコンの消費電力を削減するために動作を一時停止する省電力モード。浅いスリープ（Idle/Standby）と深いスリープ（Deep Sleep）があり、Deep Sleepでは数μAまで消費電力が低下する。タイマや外部割り込みで復帰し、バッテリー駆動IoTデバイスで重要。' },
  { term: '低消費電力', aliases: ['low power', '省電力設計', 'ultra-low power'], description: 'バッテリー駆動やエナジーハーベスティングで長期間動作するための設計手法。スリープモード活用・クロック低減・ペリフェラル個別停止・間欠動作等の技術を組み合わせる。STM32U5シリーズやtinyAVRは低消費電力設計に優れたマイコンファミリ。' },
  { term: 'プログラマ', aliases: ['書き込み器', 'ライター'], description: 'マイコンにファームウェアを書き込むための専用デバイスまたは機能。ST-LINK（STM32用）・PICkit（PIC用）・UPDI対応ライター（tinyAVR用）等がある。多くの開発ボードはUSB経由のオンボードプログラマを内蔵している。' },
  { term: 'データシート', aliases: ['datasheet', 'データシート（電子部品）'], description: 'マイコンや電子部品の電気的特性・ピン配置・動作条件・レジスタマップ・タイミング仕様等を記載した技術文書。組み込み開発では必ず参照する文書で、メーカーのWebサイトからPDFで入手する。レジスタ直接操作時に特に重要。' },
  { term: 'Flash', aliases: ['flash', 'プログラムメモリ'], description: 'マイコンに搭載される不揮発性メモリで、プログラムコードや定数データを格納する。書き換え可能だが書き込み回数に制限がある（数万〜数十万回）。RP2040は外付け2MB Flash、STM32F411REは512KB内蔵Flashを搭載する。' },
  { term: 'SRAM', aliases: ['sram', 'static ram', 'スタティックram'], description: 'マイコン内蔵の高速揮発性メモリで、プログラム実行中の変数・スタック・ヒープを格納する。DRAMと異なりリフレッシュ不要で高速だが容量は小さい。RP2040は264KB、RP2350は520KBのSRAMを搭載する。' },
  { term: 'EEPROM', aliases: ['eeprom', 'electrically erasable programmable rom'], description: 'バイト単位で電気的に書き換え可能な不揮発性メモリ。設定値・キャリブレーションデータ等の少量データの保存に使用する。ATmega328Pは1KB、PIC16Fシリーズは256Bの内蔵EEPROMを持つ。書き込み回数は10万回程度が目安。' },
  { term: 'ROM', aliases: ['rom', 'read-only memory'], description: '読み出し専用の不揮発性メモリ。マスクROM（工場書き込み）やOTP（1回書き込み）がある。現代のマイコンではFlashメモリがROMの役割を担うことが多いが、ブートローダーや固定データの格納にROM領域が使われる場合がある。' },
  { term: 'PSRAM', aliases: ['psram', 'pseudo-sram', '擬似sram'], description: 'DRAMセルをSRAMインターフェースで使用できるようにしたメモリ。ESP32-WROVER・M5Stack Basic v2.7等に外付け4〜8MBが搭載され、画像処理や大きなバッファが必要なアプリケーションでSRAMを補完する。' },
  { term: 'ブレッドボード', aliases: ['breadboard', '試作基板'], description: 'はんだ付けなしで電子部品やジャンパー線を差し込んで回路を組める穴あき基板。内部の金属クリップで接触接続するため、回路の試作や実験が容易。DIPパッケージのICやピンヘッダー付き開発ボードと組み合わせて使用する。' },
  { term: 'ピンヘッダー', aliases: ['pin header', 'ヘッダーピン'], description: '2.54mmピッチの金属ピンが一列または二列に並んだコネクタ。開発ボードの端に実装され、ブレッドボードへの挿入やジャンパーワイヤでの接続に使用する。オス・メス・L字型があり、GPIO・電源・GNDの信号を取り出す。' },
  { term: '拡張コネクタ', aliases: ['expansion connector', 'st morpho', 'st zio'], description: '開発ボードに搭載される追加のI/Oピン接続用コネクタ。STM32 NucleoのST Morpho（72ピン/114ピン）やST Zio（Arduino Mega互換拡張）が代表例で、Arduino互換ピンヘッダーでカバーしきれないGPIOやペリフェラルにアクセスする。' },
  { term: 'ST-LINK', aliases: ['st-link', 'st-link/v2-1', 'st-link/v3', 'stリンク'], description: 'STMicroelectronics社のSTM32マイコン向けオンチップデバッガ/プログラマ。SWD/JTAG接続でFlash書き込み・ブレークポイント・変数ウォッチ等のデバッグ機能を提供する。Nucleoボードには ST-LINK/V2-1が内蔵されており、USB接続のみで開発できる。' },
  { term: 'Qwiic', aliases: ['qwiic', 'qwiicコネクタ', 'qwiicケーブル', 'sparkfun qwiic', 'stemma qt'], description: 'SparkFun社が策定したI2C接続の標準化コネクタシステム。4ピンJST SHコネクタでI2Cデバイスをデイジーチェーン接続でき、はんだ付け不要でセンサーモジュールを追加できる。Adafruit STEMMA QTと互換性があり、Arduino Plug and Make Kit等で採用。' },
  { term: 'HAT', aliases: ['hat', 'hardware attached on top', 'm5stack hat'], description: '開発ボードの上に重ねて装着する拡張モジュール。Raspberry Pi向けのHAT規格（40ピンGPIO接続）と、M5StickC向けの8ピンHAT規格がある。センサー・ディスプレイ・通信モジュール等を簡単に追加できる。' },
  { term: 'Unit', aliases: ['unit', 'm5stack unit', 'm5 unit'], description: 'M5Stackシリーズ向けの小型センサー・アクチュエーターモジュール群。Grove/I2C/UART接続で温湿度・距離・光・環境・モーター等の機能を追加する。ケーブル1本で接続でき、UiFlowやM5Unifiedで簡単にプログラミングできる。' },
  { term: 'SOIC', aliases: ['soic', 'small outline ic', 'sop20', 'lqfp32'], description: '表面実装（SMD）ICの標準的なパッケージ形式。SOICは2列ガルウィングリード、LQFPは4辺フラットリード。DIPより小型だがはんだ付けには技術が必要で、ブレッドボード使用にはDIP変換基板が必要。ATTINY1616はSOIC20/VQFN20で提供される。' },
  { term: 'スルーホール', aliases: ['through-hole', 'tht', 'スルーホール実装'], description: '電子部品のリード線を基板の穴に通してはんだ付けする実装方式。DIPパッケージのIC・抵抗・コンデンサ等が対象で、手はんだで作業しやすい。表面実装（SMT）に比べ基板面積は大きいが、ブレッドボードや手作業の試作に適する。' },
  { term: '表面実装', aliases: ['surface mount', 'smt', 'smd', '表面実装技術'], description: '電子部品を基板表面のランド（パッド）に直接はんだ付けする実装方式。スルーホールより小型・高密度で量産に適するが、手はんだには高い技術が必要。SOIC・QFP・QFN・BGA等のパッケージ形式がある。リフロー炉で量産はんだ付けする。' },
  { term: 'バッテリー', aliases: ['battery', 'リチウムポリマー', 'lipo', '電池'], description: 'マイコンボードに電源を供給する蓄電池。M5Stack系はLiPoバッテリーを内蔵し、USB充電しながら動作可能。IoTセンサーノードではCR2032コイン電池やAA電池も使用される。Deep Sleepと組み合わせて長期間のバッテリー駆動を実現する。' },
  { term: 'LED', aliases: ['led', 'light emitting diode', '発光ダイオード', 'rgb led', 'ledマトリクス'], description: '電流を流すと発光する半導体素子。マイコン開発では動作確認用のLチカ（LED点滅）が最初のプログラムとして定番。RGB LEDは赤緑青の3色で任意の色を表現し、NeoPixel（WS2812B）等のアドレサブルLEDやLEDマトリクスも広く使用される。' },
  { term: 'センサー', aliases: ['sensor', '温湿度センサー', '距離センサー'], description: '物理量（温度・湿度・距離・光・加速度等）を電気信号に変換する素子。DHT11/22（温湿度）・HC-SR04（超音波距離）・BMP280（気圧）等がI2C/SPIでマイコンに接続される。IoTやスマートホームの入力デバイスとして不可欠。' },
  { term: 'スピーカー', aliases: ['speaker', 'ブザー', '圧電ブザー'], description: '電気信号を音に変換する出力デバイス。圧電ブザーはPWM信号で単純なビープ音を鳴らし、M5Stack内蔵スピーカーはDACやI2Sで音声・効果音を再生する。アラーム通知やユーザーフィードバック等のUI要素として使用。' },
  { term: '液晶', aliases: ['lcd', 'tft液晶', 'ips画面', 'ディスプレイ'], description: 'マイコンに接続して文字・グラフィック・UIを表示する画面デバイス。M5Stack Basic v2.7は2インチIPS液晶（320×240）、M5StickC Plus2は1.14インチTFTを搭載する。SPI接続のST7789やILI9341ドライバICが一般的。' },
  { term: 'ロータリーエンコーダ', aliases: ['rotary encoder', '回転エンコーダ'], description: '軸の回転量と方向を検出する入力デバイス。A/B相の2信号で回転方向を判別し、ノブ型UIや音量調整・メニュー選択に使用する。マイコンのGPIOに接続し、割り込みやポーリングで回転パルスを読み取る。' },
  { term: 'マイク', aliases: ['microphone', 'mems マイク', 'マイクロフォン'], description: '音声を電気信号に変換する入力デバイス。M5StickC Plus2やCore2にMEMSマイクが内蔵され、音声レベル検出・録音・FFT周波数解析等に使用する。PDMやI2S接続のデジタルマイクが組み込み機器で主流。' },
  { term: 'モーター', aliases: ['motor', 'dcモーター', 'サーボモーター', 'ステッピングモーター'], description: '電力を回転運動に変換する電気機械デバイス。DCモーター（PWMで速度制御）・サーボモーター（角度制御）・ステッピングモーター（ステップ制御）があり、ロボット・CNCマシン・自動化装置の駆動に使用する。モータードライバICで制御する。' },
  { term: 'ボタン', aliases: ['button', 'タクトスイッチ', '押しボタン'], description: '【組み込み】押下で電気的に導通するメカニカル入力デバイス。マイコンのGPIOにプルアップ/プルダウン接続し、デジタル入力として読み取る。チャタリング対策（デバウンス）が必要。M5Stack系は物理ボタンを搭載しユーザーインタラクションに使用する。 【OCI APEX】ユーザー操作を起点にするボタン部品。' },
  { term: 'microSDカードスロット', aliases: ['microsdカードスロット', 'microsd slot', 'tfカードスロット'], description: 'microSDカードを挿入してマイコンから読み書きするためのスロット。SPI接続でFATファイルシステムにアクセスし、データロギング・設定ファイル読み込み・画像/音声データの格納に使用する。M5Stack BasicやESP32-CAM等に搭載。' },
];
