// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: security (3/3)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_003: ReadonlyArray<GlossaryEntry> = [
  { term: 'ネットワークセグメンテーション', aliases: ['network segmentation', 'ネットワーク分割'], description: 'ネットワークをVLAN・ファイアウォール・マイクロセグメンテーションで論理的・物理的に分割し、侵害されたセグメントから他への横断移動（ラテラルムーブメント）を制限するセキュリティ設計。ゼロトラストの主要な実装技術の一つ。' },
  { term: 'セキュア開発ライフサイクル', aliases: ['secure development lifecycle'], description: 'ソフトウェア開発プロセスの全フェーズにセキュリティ活動を統合したフレームワーク。マイクロソフトのSDLが有名で、要件定義での脅威モデリング・設計レビュー・実装時のSASTツール・テスト時のペネトレーション・運用時の脆弱性管理を含む。' },
  { term: '中間者攻撃', aliases: ['mitm', 'man-in-the-middle attack', 'mitm攻撃'], description: '通信の途中に割り込み、送受信者が直接通信していると思わせながら内容を盗聴・改ざんする攻撃。公衆Wi-Fiを利用したARP毒化や偽の証明書を用いたSSLインターセプトが典型例。TLSの適切な実装と証明書検証が対策の基本。' },
  { term: 'エクスプロイト', aliases: ['exploit', 'エクスプロイトコード', '脆弱性悪用コード'], description: '脆弱性を実際に悪用するためのコード・手法・ツールの総称。PoC（概念実証）エクスプロイトはセキュリティ研究で使われ、実際の攻撃に使用されるものをExploit kitと呼ぶ。CVEエントリには既知エクスプロイトの有無が記載される。' },
  { term: 'ラテラルムーブメント', aliases: ['lateral movement', '水平移動', '横断移動'], description: '侵害した端末を足がかりに内部ネットワークを横断して他のシステムへ感染・侵入を広げる攻撃者の行動。パスザハッシュ・パスザチケット・ワームによる自動拡散などが手法として知られる。セグメンテーションとEDRで検知・制限する。' },
  { term: '権限昇格', aliases: ['privilege escalation', '特権昇格', 'eop'], description: '低権限のアカウントやプロセスが管理者・rootレベルの権限を不正に取得する攻撃。カーネルの脆弱性悪用・SUIDビットの誤設定・ sudo設定ミスなどが経路となる。垂直権限昇格（一般→管理者）と水平権限昇格（別ユーザーへのなりすまし）がある。' },
  { term: 'C2', aliases: ['c2', 'command and control', 'c&c', 'コマンドアンドコントロール'], description: 'Command and Control（指揮統制）の略。攻撃者がマルウェアに感染したシステムを遠隔操作するためのインフラ。HTTP/HTTPS・DNS・IRC・Slack APIなど正規プロトコルに偽装して通信しファイアウォールを回避することが多い。' },
  { term: 'フィッシング', aliases: ['phishing', 'フィッシング詐欺', 'スピアフィッシング'], description: '銀行・企業・政府機関などを装った偽メールやWebサイトでユーザーを騙し、認証情報やクレジットカード番号を詐取する攻撃。スピアフィッシング（標的型）・スミッシング（SMS）・ビッシング（音声）などの変種がある。MFAとセキュリティ教育が主要な対策。' },
  { term: 'ランサムウェア', aliases: ['ransomware', 'ランサム攻撃'], description: '感染した端末・ファイルサーバーのデータを暗号化しロックし、復号鍵と引き換えに身代金（ランサム）を要求する悪意あるソフトウェア。二重脅迫型（暗号化＋データ公開脅迫）が主流。オフラインバックアップ・EDR・MFAが主要な対策。' },
  { term: 'マルウェア分析', aliases: ['malware analysis', 'マルウェア解析'], description: '悪意あるソフトウェアの動作・目的・感染手法を明らかにするための技術的調査。静的分析（逆アセンブル・文字列抽出）と動的分析（サンドボックス実行・ネットワーク監視）を組み合わせる。C2ドメインやIOCを特定して防御に活用する。' },
  { term: '脆弱性管理', aliases: ['vulnerability management', '脆弱性管理プログラム'], description: 'システム・アプリケーション・ライブラリの脆弱性を継続的に特定・評価・修正・報告するプロセス。脆弱性スキャナーによる定期検査・CVSSを用いた優先度付け・パッチ管理・SLAに基づく修正期限設定が主要な活動。' },
  { term: 'セキュリティ監査', aliases: ['security audit', '情報セキュリティ監査'], description: '組織のセキュリティポリシー・手順・実装が適切に機能しているかを体系的に評価するプロセス。内部監査と外部監査があり、ISO 27001・SOC 2・PCI DSSなどのコンプライアンス認証取得の根拠にもなる。発見された不備は是正計画を策定して改善する。' },
  { term: 'リスクアセスメント', aliases: ['risk assessment', 'セキュリティリスク評価'], description: '組織の情報資産に対する脅威・脆弱性・影響を体系的に識別・評価し、リスクの大きさと許容可能かどうかを判断するプロセス。ISO 27001・NIST SP 800-30などのフレームワークを参照し、リスク受容・軽減・移転・回避の処理策を決定する。' },
  { term: '暗号スイート', aliases: ['cipher suite', 'tls暗号スイート'], description: 'TLS通信で使用する鍵交換・認証・暗号・ハッシュアルゴリズムの組み合わせ。TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384のように表記される。脆弱な暗号スイート（RC4・3DES・NULLなど）を無効化し、前方秘匿性を持つECDHEを使うことが推奨される。' },
  { term: '完全転送秘密', aliases: ['pfs', 'perfect forward secrecy', '前方秘匿性'], description: 'TLSセッションごとに一時鍵ペアを生成し、長期秘密鍵が後から漏洩しても過去のセッションを復号できないようにする性質。ECDHE（楕円曲線ディフィー・ヘルマン鍵交換）で実現する。録音済みトラフィックの後日解読攻撃に対して有効。' },
  { term: 'TLSバージョン管理', aliases: ['tlsバージョン管理', 'tls version', 'tlsバージョン'], description: 'TLS 1.0・1.1は既知の脆弱性（BEAST・POODLEなど）があり非推奨。TLS 1.2が広く使われ、TLS 1.3は古い機能を削除しハンドシェイクを高速化した最新版。サーバーでは1.2以上を強制し1.3を優先する設定が推奨される。' },
  { term: 'セキュリティテスト', aliases: ['security testing', 'application security testing'], description: 'アプリケーションやインフラの脆弱性を体系的に発見するためのテスト活動の総称。SAST・DAST・IAST・ペネトレーションテスト・脅威モデリング・コードレビューなどを組み合わせてSDLCの各フェーズで実施する。' },
  { term: 'コンテナセキュリティ', aliases: ['container security', 'kubernetes security'], description: 'Dockerコンテナ・Kubernetesクラスターを安全に運用するためのセキュリティ対策の総称。ベースイメージの脆弱性スキャン・最小権限のコンテナ実行・ネットワークポリシー・Secretsの外部管理・実行時の異常検知などが主要な要素。' },
  { term: 'クラウドセキュリティ', aliases: ['cloud security', 'クラウドセキュリティ態勢管理'], description: 'クラウド環境（AWS・Azure・GCP）特有のセキュリティ課題に対応する実践の総称。責任共有モデルに基づき、IAMの最小権限設定・セキュリティグループの適切な設定・ストレージの公開設定ミス防止・CloudTrail等による監査ログ取得が基本となる。' },
  { term: 'CSPM', aliases: ['cspm', 'cloud security posture management'], description: 'Cloud Security Posture Managementの略。クラウドインフラの設定を継続的にスキャンし、S3バケット公開設定・過剰IAM権限などのセキュリティミスコンフィギュレーションを自動検出・修正するツール・プラクティス。' },
  { term: 'インフラストラクチャーアズコード セキュリティ', aliases: ['iac security', 'infrastructure as code security'], description: 'Terraform・CloudFormationなどのIaCテンプレートに対してセキュリティスキャンを実施し、デプロイ前に設定ミスや脆弱性を検出するアプローチ。tfsec・Checkov・CFN-Nag等のツールをCIパイプラインに組み込んで使用する。' },
  { term: 'セキュリティチャンピオン', aliases: ['security champion', 'セキュリティエバンジェリスト'], description: '開発チームにセキュリティの窓口・推進役として組み込まれた開発者。セキュリティチームの代わりに各チームでセキュリティ意識向上・脅威モデリング支援・コードレビューを担う。スケーラブルなセキュリティ文化の構築に有効なアプローチ。' },
  { term: 'ゼロトラストネットワークアクセス', aliases: ['ztna', 'zero trust network access'], description: 'ユーザーとデバイスのアイデンティティ・ヘルス状態をリアルタイムに検証したうえで最小権限のアクセスを動的に付与するネットワークアクセス制御アーキテクチャ。従来のVPNによる境界防御に代わり、場所に依存しないセキュアアクセスを実現する。' },
  { term: '特権アクセス管理', aliases: ['privileged access management'], description: '管理者アカウントや特権クレデンシャルの使用を厳格に管理・監査するセキュリティプラクティス。特権セッションの記録・一時的な特権付与・just-in-timeアクセス・多要素認証の強制などを通じて内部不正やクレデンシャル窃取のリスクを低減する。' },
  { term: '暗号化アルゴリズム', aliases: ['cryptographic algorithm', '暗号アルゴリズム'], description: 'データを読めない形式に変換するための数学的手法の総称。対称暗号（AES-256-GCM）・非対称暗号（RSA-2048・ECDSA）・ハッシュ関数（SHA-256・SHA-3）・鍵導出関数（bcrypt・PBKDF2・Argon2）などがある。用途に応じて適切なアルゴリズムを選択することが重要。' },
  { term: 'ハッシュ関数', aliases: ['hash function', '暗号ハッシュ関数'], description: '任意長のデータを固定長のダイジェスト値に変換する一方向性関数。MD5・SHA-1は衝突耐性の脆弱性から非推奨。セキュリティ用途ではSHA-256以上を使用する。パスワード保存にはbcrypt・Argon2などの低速ハッシュ（key stretching）が必須。' },
  { term: 'CORSセキュリティ', aliases: ['corsセキュリティ', 'cors security', 'corsセキュリティ設定'], description: 'CORSは同一オリジンポリシーを安全に緩和する仕組みだが、Access-Control-Allow-Origin: *の設定やOriginの無検証反射はデータ漏洩リスクを生む。許可オリジンを許可リストで厳格に管理しcredentials付きリクエストに注意が必要。' },
  { term: 'HSTSプリロード', aliases: ['hstsプリロード', 'hstsプリロードリスト', 'http strict transport security詳細'], description: 'HSTSはWebサーバーがHTTPS接続を強制するポリシーをブラウザにキャッシュさせる仕組み。プリロードはブラウザ管理リストへのドメイン登録で初回からHTTPSを強制する。max-ageを長く設定しincludeSubDomainsとpreloadの指定が推奨。' },
  { term: 'コンプライアンス規程', aliases: ['compliance policy', 'corporate compliance regulations', 'code of conduct policy'], description: '法令遵守・倫理行動の基本方針と具体的なルールを定めた社内規程。役職員が守るべき行為基準・通報手続き・教育体制を包括的に定める。違反した場合の懲戒処分や是正手続きも規程内に組み込まれる。' },
  { term: '内部統制報告書', aliases: ['internal control report', 'management assessment report on internal controls', 'j-sox report'], description: 'J-SOX（金融商品取引法）に基づき、経営者が財務報告に関わる内部統制の有効性を評価・報告する文書。有価証券報告書に添付して開示し、公認会計士または監査法人による監査証明も受ける必要がある。' },
  { term: '内部通報規程', aliases: ['internal whistleblowing policy', 'internal reporting regulations', 'whistleblower protection policy'], description: '社内の不正・法令違反・倫理違反を従業員が通報するための手続きを定めた規程。通報者保護・調査手続き・対応措置を規定し、公益通報者保護法に準拠して整備されることが多い。' },
  { term: 'リスク管理規程', aliases: ['risk management policy', 'enterprise risk management regulations', 'risk control policy'], description: '事業活動上のリスク（財務・法務・情報・災害等）の特定・評価・対応・モニタリングに関するルールを定めた社内規程。リスクオーナーの明確化と定期的なリスク評価プロセスを規定する。' },
  { term: 'リスクコンプライアンス委員会', aliases: ['risk and compliance committee', 'risk compliance oversight committee', 'enterprise risk committee'], description: 'リスク管理とコンプライアンスを横断的に監督・推進するための委員会。全社のリスク状況を把握し、対策の優先順位付けと是正を行い、取締役会または経営会議への報告を担う。' },
  { term: '倫理規程', aliases: ['ethics policy', 'code of ethics', 'corporate ethics regulations'], description: '役職員が業務上で守るべき倫理的行動基準を定めた規程。誠実さ・公正さ・法令遵守・利益相反回避などの原則を示し、コンプライアンス規程と一体で運用されることも多い。' },
  { term: '廃止', aliases: ['abolishment', 'policy abolition', 'regulation termination'], description: '規程・制度・業務手続き等を正式に終了させること。廃止の際は関係者への周知・文書の処理・引き継ぎが必要となり、規程等管理規程に定める権限者の承認を要する。' },
  { term: '改廃', aliases: ['amendment and abolishment', 'revision and abolition', 'policy amendment or abolition'], description: '規程・文書・制度の改正（変更）または廃止の総称。改廃の権限者・手続き・施行日を規程等管理規程で定め、変更履歴の管理と関係者への周知を行う。' },
  { term: 'セグリゲーションオブデューティー', aliases: ['segregation of duties', 'duty separation control', 'sod control'], description: '一人の担当者が承認・実行・記録を同時に行えないよう職務を分離する内部統制の原則。不正や誤りの発生を防止するための基本的な管理策であり、IT統制や業務プロセス設計の基盤となる。' },
  { term: '職務分掌規程', aliases: ['duties and responsibilities policy', 'work allocation regulations', 'division of duties policy'], description: '各部門・各役職の担当業務と責任範囲を明確に定めた規程。業務の重複・抜け漏れを防ぎ、内部統制の基盤となるとともに、職務分離（SoD）の実現にも貢献する。' },
  { term: '職務権限規程', aliases: ['authority and authorization policy', 'delegated authority regulations', 'approval authority policy'], description: '各職位・部門が持つ決裁・承認・契約等の権限の範囲を定めた規程。権限の委譲範囲・代理承認の条件も定め、不正な意思決定や権限逸脱を防止する内部統制の要となる。' },
  { term: '業務分掌', aliases: ['division of business duties', 'work responsibilities allocation', 'business function assignment'], description: '各部門や役職員の業務範囲と担当領域の分担を決めること。職務分掌規程に基づき、業務の重複や責任の曖昧さを排除することで内部統制の実効性を高める。' },
  { term: '標的型攻撃メール', aliases: ['spear phishing email', 'targeted attack email', 'targeted phishing attack'], description: '特定の組織・個人を狙って送りつけられる不正メール。マルウェアへの誘導や情報窃取を目的とし、社内規程やセキュリティ教育で対策を定めるとともに、インシデント発生時の報告体制を整備する。' },
  { term: 'インサイダー取引', aliases: ['insider trading', 'insider securities trading', 'trading on material non-public information'], description: '上場企業の内部者が未公開の重要情報を利用して株式等を売買すること。金融商品取引法で禁止されており、違反すると刑事罰の対象となるため、コンプライアンス管理の重点項目として取り扱う。' },
  { term: 'インサイダー取引防止規程', aliases: ['insider trading prevention policy', 'insider trading prohibition regulations', 'securities trading compliance policy'], description: '役職員が未公開情報を利用した有価証券取引を行わないための禁止行為・管理手続き・教育を定めた社内規程。情報管理部門の役割・取引申告制度・違反時の処罰も規定する。' },
  { term: '関連当事者等管理規程', aliases: ['related party transaction policy', 'related party management regulations', 'conflict of interest transaction policy'], description: '役員・主要株主・子会社等の関連当事者との取引を適正に管理・開示するための社内規程。利益相反防止と透明性確保を目的とし、取引の事前承認・記録・開示手続きを定める。' },
  { term: '反社会的勢力排除', aliases: ['exclusion of anti-social forces', 'anti-organized crime measures', 'organized crime exclusion policy'], description: '暴力団・反社会的勢力との関係を排除する取り組みの総称。取引開始時の審査・契約書への排除条項追加・定期的なチェックを含み、全社的な体制整備が求められる。' },
  { term: '反社会的勢力等排除規程', aliases: ['anti-social forces exclusion policy', 'organized crime exclusion regulations', 'anti-gang policy'], description: '反社会的勢力との取引・関係を一切排除するための基準・審査手続き・発覚時の対応を定めた社内規程。暴力団排除条例や警察との連携指針を含め、実効ある体制を構築する。' },
  { term: '誓約書', aliases: ['pledge letter', 'compliance undertaking letter', 'confidentiality and compliance pledge'], description: '特定の事項（情報守秘・利益相反回避・反社排除等）を守ることを約束する文書。入社時・取引開始時・退職時などに取得し、コンプライアンス義務の確認と証拠保全を目的とする。' },
  { term: '情報セキュリティ管理規程', aliases: ['information security management policy', 'information security regulations', 'isms policy'], description: '情報資産の分類・アクセス管理・漏洩防止・インシデント対応などを定めた社内規程。ISMS等の国際規格に準拠して策定することも多く、情報セキュリティ委員会が整備・運用を主導する。' },
  { term: '個人情報保護規程', aliases: ['personal information protection policy', 'privacy protection regulations', 'personal data management policy'], description: '個人情報保護法に基づき、個人情報の取得・利用・保管・提供・廃棄に関するルールを定めた社内規程。利用目的の明示・本人同意・安全管理措置・苦情対応を含む包括的な規定を設ける。' },
  { term: '個人情報保護マネジメントシステム', aliases: ['personal information protection management system', 'privacy management system', 'pms for personal data'], description: '個人情報を適切に管理するための組織的な仕組み（方針・体制・手続き・内部監査・改善）の総称。プライバシーマーク取得の基盤となり、JIS Q 15001に準拠して整備する。' },
  { term: 'プライバシーマーク', aliases: ['privacy mark', 'p-mark certification', 'jis q 15001 certification'], description: '個人情報を適切に扱っている事業者であることを認定する第三者認証制度（JIS Q 15001準拠）。Pマークとも呼ばれ、取得により取引先や顧客への信頼性アピールと個人情報管理体制の強化が図られる。' },
  { term: '特定個人情報取扱規程', aliases: ['my number information handling policy', 'specific personal information management regulations', 'individual number data handling policy'], description: 'マイナンバー（個人番号）の収集・保管・利用・廃棄に関する特別なルールを定めた社内規程。番号法の要件に従い厳格な管理を求め、利用目的の限定・アクセス制御・廃棄手続きを詳細に規定する。' },
  { term: '苦情処理規程', aliases: ['complaint handling policy', 'grievance management regulations', 'customer complaint processing policy'], description: '顧客・取引先・従業員からの苦情を受け付けて適切に処理するための手続き・担当者・対応期限を定めた社内規程。苦情の記録・原因分析・再発防止策の策定と、通報者保護も含む。' },
  { term: 'クレーム管理規程', aliases: ['complaint management policy', 'customer claim handling regulations', 'customer complaint management policy'], description: '顧客からの苦情やトラブルをどう受け付けて処理するかの社内ルール。受付窓口・記録方法・エスカレーション基準・再発防止策を定め、顧客満足の向上と法的リスクの低減を図る。' },
  { term: '不正取引', aliases: ['fraudulent transaction', 'improper trading activity', 'irregular transaction'], description: '法令・社内規程・倫理基準に反した取引行為。架空取引・循環取引・利益相反取引などを指し、コンプライアンス管理の重点監視対象となるとともに、発覚時は調査・報告・是正が必要となる。' },
  { term: '横領', aliases: ['embezzlement', 'misappropriation of funds', 'business embezzlement'], description: '業務上預かっている会社の資金や財物を不正に自己の利益のために使用すること。刑法上の業務上横領罪に該当し、発覚次第即時対応・刑事告訴・社内懲戒処分が行われる。' },
  { term: '贈収賄', aliases: ['bribery and corruption', 'bribery offense', 'corrupt payment'], description: '公務員等への贈賄（金品の提供）および公務員等による収賄（金品の受領）の行為。刑法・不正競争防止法等で禁止されており、コンプライアンス上の重大リスクとして接待・贈答の管理規程で予防措置を講じる。' },
  { term: '接待交際費等管理規程', aliases: ['entertainment expense management policy', 'business entertainment regulations', 'hospitality and gift management policy'], description: '接待・贈答・交際費の支出基準・上限額・承認フロー・記録方法を定めた社内規程。贈収賄リスクの管理と適正な経費利用を目的とし、外国公務員への提供禁止条項も含む。' },
  { term: '贈答規程', aliases: ['gift policy', 'gift giving regulations', 'business gift management policy'], description: '取引先等への贈り物（贈答品・商品券等）の取り扱い基準・金額上限・禁止ケースを定めた社内規程。社会通念の範囲内での贈答に限定し、利益誘導や贈収賄への抵触を防止する。' },
  { term: '懲戒処分', aliases: ['disciplinary action', 'disciplinary measures', 'employee disciplinary sanction'], description: '就業規則・懲戒規程に基づき、規律違反・不正行為を行った従業員に対して会社が下す制裁。けん責・減給・出勤停止・懲戒解雇等の種類があり、適正手続き（弁明の機会付与等）を踏む必要がある。' },
  { term: '賞罰規程', aliases: ['awards and disciplinary regulations', 'reward and punishment policy', 'recognition and discipline policy'], description: '良い業績や行動をした従業員への表彰と、規則違反への処罰の両方を定めた社内規則。表彰基準・懲戒の種類・手続きを規定し、公平・公正な人事管理の基盤となる。' },
  { term: 'ハラスメント防止規程', aliases: ['harassment prevention policy', 'anti-harassment regulations', 'workplace harassment policy'], description: 'セクシャルハラスメント・パワーハラスメント等の防止方針・禁止行為・相談・調査・処分手続きを定めた社内規程。労働施策総合推進法等の法令要件に対応し、安全な職場環境の維持を目的とする。' },
  { term: 'ハラスメント通報窓口', aliases: ['harassment reporting hotline', 'harassment complaint desk', 'harassment reporting channel'], description: 'ハラスメント被害を申告・相談するための社内外の窓口。匿名通報を受け付けることも多く、通報者の保護を規程で保証し、受け付けた案件は速やかに調査・対処するプロセスを整備する。' },
  { term: '内部監査規程', aliases: ['internal audit policy', 'internal audit regulations', 'internal audit charter'], description: '内部監査の目的・組織・権限・手続き・報告・フォローアップを定めた社内規程。内部監査部門の独立性と客観性を担保し、経営陣・取締役会への直接報告ラインを確保する。' },
  { term: '監査役会', aliases: ['board of auditors', 'statutory auditor board', 'corporate auditor committee'], description: '監査役で構成される合議体。取締役の職務執行の監査・会計監査・内部統制の監視を担い、大会社では設置が義務付けられる。監査役会は独立した立場から経営監視機能を果たす。' },
  { term: '監査役監査基準', aliases: ['auditor audit standards', 'statutory auditor audit criteria', 'board of auditors audit standards'], description: '監査役が監査を実施する際の基準・手続き・判断指針をまとめた文書。監査役会が制定し、実効ある監査の基盤とするとともに、日本監査役協会の指針を参考に策定されることが多い。' },
  { term: '監査役会規則', aliases: ['board of auditors regulations', 'auditor committee rules', 'statutory auditor board operating rules'], description: '監査役会の運営（招集・決議・記録・報告等）に関する手続きを定めた内規。監査役会の実効性を確保するために整備し、議事録の作成・保管・取締役会への報告方法も含む。' },
  { term: '監査法人', aliases: ['audit corporation', 'certified public accountant firm', 'statutory audit firm'], description: '公認会計士5名以上で設立された法人で、大会社等の財務諸表の法定監査を実施する。会計監査人として選任され、独立した立場から財務報告の適正性を検証する機能を担う。' },
  { term: '財務報告内部統制', aliases: ['internal control over financial reporting', 'financial reporting controls', 'icfr'], description: '財務報告の信頼性を確保するために整備・運用する内部統制の仕組み。J-SOXの評価対象となり、経営者が有効性を評価・報告し、監査法人による監査証明を受ける必要がある。' },
  { term: '監査報告', aliases: ['audit report', 'internal audit report', 'audit finding report'], description: '内部監査または外部監査の実施結果をまとめた報告書。指摘事項・改善勧告・経営者へのフォローアップ要請などを記載し、被監査部門および取締役会・経営陣に提出される。' },
  { term: '定期監査', aliases: ['periodic audit', 'scheduled audit', 'regular audit'], description: '監査計画に基づいて定期的に実施する監査。内部監査・会計監査・監査役監査のいずれにおいても年間計画の下で行われ、リスクベースアプローチにより重点領域を選定する。' },
  { term: '臨時監査', aliases: ['special audit', 'unscheduled audit', 'ad hoc audit'], description: '不正の疑い・重大なリスク発生・経営層の要請などにより、定期監査とは別に臨時で実施する監査。迅速な対応が求められ、調査結果は速やかに経営陣・監査役へ報告される。' },
  { term: '証憑管理', aliases: ['evidence document management', 'source document management', 'transaction evidence management'], description: '取引の証拠となる書類（請求書・領収証・契約書等）を適切に収集・保管・管理する業務。法定保存期間・アクセス管理・廃棄ルールを定め、会計監査・内部監査への対応も含む。' },
  { term: '社会的信用', aliases: ['corporate social credibility', 'social reputation', 'corporate trustworthiness'], description: '企業や個人が社会から得る信頼と評判。コンプライアンス違反・不祥事・情報漏洩などは社会的信用の失墜につながり、事業継続・採用・取引関係に深刻な影響を与える。' },
  { term: '遵守義務', aliases: ['compliance obligation', 'legal compliance duty', 'regulatory compliance requirement'], description: '法令・社内規程・業界ルール等を守る義務のこと。役職員全員に課される基本的な義務で、コンプライアンス規程の根幹をなし、違反した場合は懲戒処分や法的責任の対象となる。' },
  { term: '社会倫理', aliases: ['social ethics', 'business social ethics', 'societal ethical standards'], description: '社会一般に共有されている倫理的な価値観や行動規範。法令を遵守するだけでなく、社会倫理に沿った行動が企業には求められ、CSR・ESGの観点からも重要視される。' },
  { term: '損失危険管理体制', aliases: ['loss risk management system', 'risk loss management framework', 'business risk management structure'], description: 'リスクが顕在化した際の損失を最小化するための管理体制。リスクの早期検知・初動対応・事業継続計画（BCP）を含み、会社法上の内部統制システムの一要素として整備が求められる。' },
  { term: '情報漏洩', aliases: ['confidential data leak'], description: '機密情報・個人情報・営業秘密が不正または過失によって社外に流出すること。発生時は速やかな報告・調査・被害拡大防止が求められ、個人情報漏洩の場合は個人情報保護法に基づく通知・報告義務が生じる。' },
  { term: '反社対応マニュアル', aliases: ['anti-social forces response manual', 'organized crime response procedures', 'anti-gang response guidelines'], description: '反社会的勢力からの接触・要求があった場合の対応手順を定めたマニュアル。警察・弁護士との連携方法・対応フロー・記録方法を示し、組織的かつ毅然とした対応を担保する。' },
  { term: 'KYC', aliases: ['kyc', 'know your customer', 'customer identity verification', 'customer due diligence'], description: 'Know Your Customer の略。顧客の実在性・身元・取引目的を確認するプロセス。マネーロンダリング・反社対応のために金融機関等で義務付けられ、犯罪収益移転防止法への対応として実施される。' },
  { term: '顧客管理', aliases: ['customer relationship management', 'client account management', 'customer data management'], description: '顧客の情報・取引履歴・与信状況等を適切に管理すること。CRMシステムや顧客管理規程に基づき、個人情報保護・反社チェック・与信管理を含む包括的な管理体制を整備する。' },
  { term: '反社通報', aliases: ['anti-social forces reporting', 'organized crime connection reporting', 'anti-gang incident reporting'], description: '取引先や関係者が反社会的勢力との関係を有することを発見した際に社内の担当部門へ通報すること。通報後は調査・関係解消の手続きに進み、通報者の保護を規程で保証する。' },
  { term: 'コンプライアンス教育', aliases: ['compliance training', 'ethics and compliance education', 'regulatory compliance training'], description: '役職員がコンプライアンスの重要性・具体的なルール・違反事例を学ぶための研修。定期的・階層別に実施し、理解度確認テストや e-learning を活用して実効性を高める。' },
  { term: '社外監査', aliases: ['external audit', 'third-party audit', 'independent external audit'], description: '第三者機関・外部監査法人・規制当局による監査。独立した視点での検証が行われ、指摘事項は社内の改善活動に活用するとともに、規制対応・認証維持のために重要な役割を担う。' },
  { term: '不正アクセス', description: '許可されていない利用者や経路によるシステムへのアクセスです。' },
  { term: 'ログイン画面', description: '利用者が認証情報を入力してログインする画面です。' },
  { term: '秘密情報管理', aliases: ['secrets管理'], description: 'パスワードや鍵などの秘密情報を安全に保管し制御することです。' },
  { term: '証明書更新', description: '期限切れや切替に備えて証明書を新しいものへ更新することです。' },
  { term: '証明書', description: '通信相手や公開鍵の正当性を示す電子的な証明情報です。' },
  { term: '認証方式', description: '利用者やシステムの正当性を確認する方法です。' },
  { term: '個人情報保護', description: '個人情報を適切に取得し利用し保護することです。' },
  { term: '業界規制', description: '業界ごとに求められる規制や基準です。' },
  { term: '法令順守', description: '法律や規則に従って運用や開発を行うことです。' },
  { term: '監査証跡', description: '誰がいつ何をしたかを追跡できる記録です。' },
  { term: '時刻がずれると', description: '機器間の時刻差が原因で認証や記録に不整合が起きる条件です。' },
  { term: '命名確認', description: '名前が意味や規約に沿っているかを確認することです。' },
  { term: '認証情報のハードコード', description: 'パスワードやAPIキーなどの認証情報をソースコードや設定値に固定で埋め込むことです。' },
  { term: '個人情報漏洩', description: '氏名や連絡先など個人を識別できる情報が、本来許可されていない相手へ流出することです。' },
  { term: '機密ログ', description: '認証情報や個人情報など、秘匿すべき内容を含んでしまっているログです。' },
  { term: 'シークレット', description: 'パスワード、APIキー、秘密鍵のように厳格な管理が必要な秘密情報です。' },
  { term: 'ローテーション', description: '鍵やトークンや証明書を定期的または緊急時に新しいものへ切り替える運用です。' },
  { term: '総合評価', description: '複数の観点や証拠を踏まえて、全体としてどう判断するかを示した評価です。' },
  { term: '報告書', description: '調査結果、根拠、評価、提案を整理して関係者へ共有する文書です。' },
  { term: '技術監査', description: 'システム、コード、運用、開発プロセスを技術面から点検し、問題点や改善点を評価することです。' },
  { term: '重大問題', description: '放置した場合の影響が大きく、優先的な対処が必要な問題です。' },
  { term: '是正済み', description: '指摘された問題に対する修正や対策が、すでに完了している状態です。' },
  { term: '失効済み', description: 'トークン、証明書、認証情報などが有効期限切れや無効化により使えなくなっている状態です。' },
  { term: '時系列', description: '出来事を発生した順番に並べた時間の流れです。' },
  { term: '実施状況', description: '対象施策や作業がどこまで行われているかという実行状況です。' },
  { term: '現在進行形', description: '過去に終わった事象ではなく、現在も継続して発生または未解決の状態を示す表現です。' },
  { term: '改善余地', description: '現状でも動作はしているが、より良くできる余地が残っている状態です。' },
  { term: '是正必須', description: '放置不可であり、必ず修正や対策を実施すべきと判断された状態です。' },
  { term: '突然', description: '十分な事前兆候や予告がないまま、急に起きる様子を表す言葉です。' },
  { term: 'マスキング', description: '個人情報や認証情報の一部を伏せて、そのまま見えないように加工することです。' },
  { term: '未適用', description: '必要と判断された修正、設定変更、パッチがまだ反映されていない状態です。' },
  { term: '情報セキュリティ基本方針', description: '情報資産をどのように保護するかについての基本方針です。組織としてのセキュリティ姿勢を対外的に示します。' },
  { term: 'password', aliases: ['パスワード'], description: 'ユーザー本人であることを確認するための秘密の文字列です。ハッシュ化して保存するのが安全な取り扱いです。' },
  { term: 'hash', aliases: ['ハッシュ', 'ハッシュ値'], description: '任意のデータを固定長の値に変換する処理、またはその結果の値です。元のデータへ戻すことは困難で、パスワード保存やデータ検証に使われます。' },
  { term: 'decryption', aliases: ['復号', '復号化'], description: '暗号化されたデータを正しい鍵を使って元の読める形に戻す処理です。' },
  { term: 'sanitization', aliases: ['無害化'], description: 'ユーザー入力から危険な文字やスクリプトを除去・無効化して安全にする処理です。XSSやSQLインジェクション対策の基本です。' },
];
