// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: security (2/3)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: 'インシデント自動封じ込め', aliases: ['automated incident containment'], description: '異常検知時に通信を自動遮断したり権限を停止したりするしくみです。誤検知対策と人手確認ポイントの設計が重要です。' },
  { term: '監査ログ整合性', aliases: ['audit trail integrity'], description: '監査ログが完全で改ざんされておらず、時系列として信頼できる状態です。記録があるだけでは不十分です。' },
  { term: '証拠保全管理', aliases: ['evidence preservation'], description: '調査や監査に必要な記録を失わずに保持することです。インシデントや攻撃時に証拠が最も失われやすいため特別な注意が必要です。' },
  { term: '証拠連鎖管理', aliases: ['chain of custody'], description: '証拠がいつ誰の手にあったかを追跡できる状態です。法的手続きや正式な調査で重要になります。' },
  { term: 'セキュリティ例外一覧台帳', aliases: ['security exception register'], description: '例外承認を受けた項目を一覧管理する台帳です。有効期限の見落としや放置を防ぐのに役立ちます。' },
  { term: 'リスク受容判断', aliases: ['risk acceptance'], description: 'リスクを低減するのではなく、十分な理解のうえで受け入れる決定です。受容する場合は誰が責任を負うかを明確にする必要があります。' },
  { term: 'リスク軽減対策', aliases: ['risk mitigation'], description: 'リスクの発生確率や影響を低減する施策です。完全な排除が不可能な場合でも現実的な妥協点として機能します。' },
  { term: 'リスク回避戦略', aliases: ['risk avoidance'], description: 'リスクのある活動や設定を最初から行わない決定です。最も確実なアプローチですが機会損失が生じる場合もあり、選択は慎重に行う必要があります。' },
  { term: 'リスク移転手段', aliases: ['risk transfer'], description: '保険や契約によって一部のリスクを外部に移すコンセプトです。管理責任は通常残るため責任が完全になくなるわけではありません。' },
  { term: 'セキュリティ運用規程', aliases: ['security operations standard'], description: 'パッチ適用・権限管理・ログ確認などの標準的な手順です。アドホックな判断を減らし、運用品質を安定させます。' },
  { term: 'セキュリティ教育プログラム', aliases: ['security training plan'], description: 'ユーザー・開発者・運用者に必要なセキュリティ知識をどう身につけてもらうかの計画です。技術的な対策だけでは全てのインシデントを防ぎきれません。' },
  { term: 'フィッシング対策訓練', aliases: ['phishing training'], description: '偽装メールやメッセージを見分けるための訓練です。人間の注意力だけに頼るのは不十分で、教育と仕組みの両面が必要です。' },
  { term: 'セキュリティ文化醸成', aliases: ['security culture'], description: '安全意識がルールとしてではなく日常の行動に埋め込まれた組織状態です。最終的にはこの文化が最も強い防御になります。' },
  { term: 'ITガバナンス体制', aliases: ['itガバナンス体制', 'it governance'], description: 'IT投資と運用を組織目標に沿って管理するコンセプトです。技術だけでなく意思決定と説明責任の構造も含みます。' },
  { term: '意思決定フレームワーク', aliases: ['decision-making framework'], description: '誰が何をどのように決めるかを定義する構造です。アドホックな意思決定より判断の一貫性が保たれます。' },
  { term: '意思決定の権限委譲', aliases: ['authority delegation'], description: '上位から下位へ一定範囲の意思決定権限を移すことです。速度は上がりますが基準が不明確だと混乱が生じます。' },
  { term: '承認権限', aliases: ['approval authority'], description: '契約・支出・変更などを正式に承認する権限です。担当者と承認者を混同しないことが実務上重要です。' },
  { term: '承認判断基準', aliases: ['approval criteria'], description: 'どのような条件で承認し、どのような場合に差し戻すかを定める基準です。担当者によって判断がばらつかないようにします。' },
  { term: 'コントロール設計', aliases: ['control design'], description: '不正や事故を防ぎながら業務を動かすためのルールとしくみを設計することです。厳しすぎると業務が止まり、緩すぎると危険です。' },
  { term: 'IT標準化委員会', aliases: ['it標準化委員会', 'standards committee'], description: '共有ルールや標準を作成・更新する組織体です。形式だけでなく現場にとって実効性のあるしくみとして機能することが重要です。' },
  { term: 'アーキテクチャレビュー', aliases: ['architecture review'], description: '重要な取り組みの設計や技術方針を事前にレビューするしくみです。自由を制限するより大きな問題を防ぐサポートとして機能すべきです。' },
  { term: '技術標準の策定', aliases: ['technology standards'], description: '推奨技術・禁止技術・採用基準を定める標準です。無秩序な技術選択を防ぎ保守性を向上させます。' },
  { term: '標準逸脱の例外管理', aliases: ['exception management'], description: '標準から逸脱したケースや設定を記録・承認・レビューすることです。例外自体は悪ではありませんが放置は危険です。' },
  { term: '監査範囲', aliases: ['audit scope'], description: '監査でチェックすべき資産・手順・記録・設定の範囲です。範囲が曖昧だと監査の実効性が下がります。' },
  { term: '監査実施計画', aliases: ['audit plan'], description: '何を・いつ・誰が・どのようにチェックするかを定めた計画です。定期監査とアドホック監査では目的が異なります。' },
  { term: '内部監査の実施', aliases: ['internal audit'], description: '組織内部で行う監査です。規制遵守だけでなく内部ルールの確認と改善機会の発見にも役立ちます。' },
  { term: '監査エビデンス', aliases: ['audit evidence'], description: '監査で証拠として提示する材料です。ログ・承認履歴・契約書・設定一覧などが典型例です。' },
  { term: '基準適合性評価', aliases: ['conformity assessment'], description: 'ルールや標準にどの程度適合しているかを評価することです。完全準拠だけでなくギャップとその関連リスクを理解することも重要です。' },
  { term: '是正指摘事項', aliases: ['corrective action notice'], description: '監査やレビューの結果として出る改善要求です。指摘で終わらず期限と担当者を設定することが重要です。' },
  { term: 'フォローアップ監査の実施', aliases: ['follow-up audit'], description: '指摘事項が実際に対応されたかを後日確認する監査です。完遂まで追うことで監査を生きたプロセスにできます。' },
  { term: 'コントロール有効性', aliases: ['control effectiveness'], description: '確立されたルールやしくみが実際に成果を出しているかの度合いです。存在しているだけでは有効とはいえません。' },
  { term: '運用有効性', aliases: ['operational effectiveness'], description: '手順や標準が現場で実際に守られて機能しているかの観点です。現実に合わないルールは形骸化しがちです。' },
  { term: 'KPI定期レビュー', aliases: ['kpi定期レビュー', 'kpi review'], description: '指標が依然として意味を持つかを定期的に見直すことです。計測すること自体が目的になることを防ぐ必要があります。' },
  { term: 'ガードレール違反対応', aliases: ['guardrail violation'], description: '組織標準が禁止または要承認とする境界を無断で超えることです。小さな違反の積み重ねが大きなインシデントにつながる可能性があります。' },
  { term: '是正措置計画', aliases: ['corrective action plan'], description: '問題をいつまでに誰がどう解決するかを定めた計画です。改善の実現可能性が肝心です。' },
  { term: '改善実施ロードマップ', aliases: ['improvement roadmap'], description: 'どの順番で改善を行うかを示す中長期計画です。即時対応と時間がかかる項目を分けて整理できます。' },
  { term: '優先改善事項', aliases: ['priority improvement items'], description: '多くの改善提案の中で最初に取り組むべき項目です。効果・リスク水準・実現可能性のバランスで決定されます。' },
  { term: '改善課題バックログ', aliases: ['improvement backlog'], description: '優先順位をつけた改善提案の一覧です。アドホックなアイデアをアクション可能な項目に変えるのに役立ちます。' },
  { term: '改善課題オーナー', aliases: ['improvement owner'], description: '改善を最後まで推進する責任者です。提案者と実行責任者が同一とは限らないため、明確にすることが重要です。' },
  { term: '現場裁量の範囲', aliases: ['field discretion'], description: '現場が自律的に判断できる範囲です。狭すぎると速度が落ち、広すぎるとガバナンスが崩れるため慎重な設計が重要です。' },
  { term: '集中運用体制', aliases: ['centralized operations'], description: '標準と意思決定を中央組織が強く握る運用形態です。一貫性を確保しやすい一方でスピードが犠牲になることがあります。' },
  { term: '分散型運用体制', aliases: ['distributed operations'], description: '各チームや部門がある程度の自律性を持って運用する形態です。速度は出やすい一方でルールの不整合が生じやすいです。' },
  { term: 'フェデレーテッド運用モデル', aliases: ['federated model'], description: '中央の標準を維持しながら実行を各チームに分散する運用モデルです。標準化と自律性のバランスを取りやすくします。' },
  { term: '意思決定ログの見直し', aliases: ['decision log review'], description: '過去の重要な意思決定が現在も有効かどうかをレビューすることです。前提が変わったのに古い決定が残る状況を防ぎます。' },
  { term: '例外期限管理', aliases: ['exception expiration management'], description: '期限付き例外が期限後も放置されないよう管理することです。例外は増えるのではなく減っていくことが重要です。' },
  { term: '現場フィードバックの反映', aliases: ['field feedback absorption'], description: '現場の懸念や改善アイデアを標準に取り込むことです。トップダウンのルールだけでは継続的な標準にはなりにくいです。' },
  { term: '成熟度評価', aliases: ['maturity assessment'], description: '組織やプロセスが現在どの段階にあるかを診断することです。理想状態とのギャップを可視化し改善計画につなげます。' },
  { term: '運用品質監査の実施', aliases: ['operational quality audit'], description: 'インシデント対応・監視・変更管理などの運用品質を検査する監査です。システム品質は運用の影響を大きく受けます。' },
  { term: 'ガバナンスメトリクス', aliases: ['governance metrics'], description: 'ガバナンスが機能しているかを評価するための指標です。承認遅延・例外件数・監査指摘件数などが典型例です。' },
  { term: '標準遵守率の計測', aliases: ['standards compliance rate'], description: '定めたルールがどの程度守られているかを示す指標です。遵守率が低い場合、現場だけでなく標準そのものに問題があることもあります。' },
  { term: '改善効果の測定', aliases: ['improvement impact measurement'], description: '施策の結果として何がどれだけ改善したかを計測することです。成果の確認なしに改善活動が放置されることを防ぐために必要です。' },
  { term: 'ポリシー準拠検査', aliases: ['policy check'], description: 'コード・IaC・設定・権限などが定義されたポリシーに違反していないかを自動または半自動で確認する検査です。CIやデプロイ前のゲートとしてよく使われます。' },
  { term: 'Secret Injection', aliases: ['secret injection'], description: '実行時に秘密情報を安全に注入する仕組みです。イメージやコードへ埋め込まない設計が基本です。' },
  { term: 'Policy Enforcement', aliases: ['policy enforcement'], description: '定めたルールを実際の作成、変更、実行時に強制することです。文書だけのルールより実効性が高くなります。' },
  { term: 'PII検知', aliases: ['pii検知'], description: '個人識別につながる情報を自動で見つけることです。AI利用前の入力審査やログ保護で使われます。' },
  { term: '機密操作承認', description: '重要なデータ送信や更新を行う前に承認を必須とする仕組みです。AI実行系では特に重要です。' },
  { term: 'PII検出', aliases: ['pii検出', 'pii detection'], description: '個人を特定できる情報を自動識別する手法です。AI処理前の入力スクリーニングやログ保護に使用されます。' },
  { term: 'セキュリティ設計書', description: '認証、認可、暗号化、監査などを整理した設計書です。業務系では非常に重要です。' },
  { term: '認証方式定義', description: 'どの認証方式を採用し、どう使うかを定義したものです。SSO、多要素認証などの整理に使えます。' },
  { term: '認可ルール定義', description: 'どの役割に何を許可するかを明文化した定義です。設計と監査の両方で役立ちます。' },
  { term: '暗号化方針', description: '保存時、通信時の暗号化対象と方式を整理した方針です。セキュリティ設計の中核になります。' },
  { term: '秘密情報管理方針', description: 'パスワード、鍵、トークンをどう扱うかの方針です。運用事故防止に直結します。' },
  { term: 'データ分類表', description: 'データを機密度や重要度ごとに分類した表です。保存場所、共有範囲、AI入力可否などの基準になります。' },
  { term: '暗号化ポリシー', aliases: ['encryption policy'], description: '保存時と通信時に何をどのように暗号化するかを整理したポリシーです。セキュリティ設計の核になります。' },
  { term: '秘密情報管理ポリシー', aliases: ['secret information management policy'], description: 'パスワード・鍵・トークンの扱い方を定めたポリシーです。運用上のインシデント防止に直結します。' },
  { term: '完璧なセキュリティ', aliases: ['perfect security'], description: 'すべての事故や攻撃を防げるという理想状態。' },
  { term: 'リスク管理', aliases: ['risk control'], description: '被害の可能性と影響を見積もり、優先的に下げていくこと。' },
  { term: '理想論', aliases: ['idealism'], description: '現実の制約を十分に考慮しない考え方。' },
  { term: '現実', aliases: ['reality'], description: '予算、時間、人材、運用条件などの制約がある実務の状態。' },
  { term: '弱点', aliases: ['vulnerability (security)'], description: '攻撃や障害のきっかけになりうる不足。' },
  { term: '利便性', description: '使いやすさや業務のしやすさ。' },
  { term: '侵害', aliases: ['breach'], description: '不正アクセスや漏えいなどで守るべきものが破られること。' },
  { term: '優先順位', aliases: ['prioritization (security)'], description: 'どの課題や対策を先に扱うかの順番。' },
  { term: '防御', aliases: ['defense'], description: '攻撃や被害を防ぐための対策。' },
  { term: '改善', description: '状態を段階的によくしていくこと。' },
  { term: '検知', aliases: ['detection'], description: '異常や攻撃の発生を見つけること。' },
  { term: '復旧', aliases: ['recovery'], description: '障害や事故の後に元の状態へ戻すこと。' },
  { term: '復旧手順', aliases: ['recovery procedure'], description: '障害や事故から戻すための具体的な手順。' },
  { term: 'リカバリー', aliases: ['system recovery'], description: '障害発生後にシステムやデータを回復させること。' },
  { term: '総合的な意思決定', aliases: ['holistic decision making'], description: '技術、運用、監査、復旧まで含めて判断すること。' },
  { term: '悪用可能性', aliases: ['exploitability'], description: '弱点が実際に攻撃へ使われる見込みの高さ。' },
  { term: '影響度', aliases: ['impact severity'], description: '問題が起きたときの被害の大きさ。' },
  { term: '統制', aliases: ['control'], description: '重要な操作や情報を管理・制限する仕組み。' },
  { term: '特権操作', aliases: ['privileged operation'], description: '強い権限で行う重要な操作。' },
  { term: '高リスク領域', aliases: ['high-risk area'], description: '被害が大きくなりやすい対象や業務範囲。' },
  { term: '重要データアクセス', aliases: ['sensitive data access'], description: '機密性の高い情報へ接触・閲覧・変更すること。' },
  { term: 'ログ監視', aliases: ['log monitoring'], description: '操作やイベントの記録を継続的に確認すること。' },
  { term: '権限分離', aliases: ['separation of privileges'], description: '役割ごとに権限を分け、被害や不正を抑えること。' },
  { term: '安心感の演出', aliases: ['security theater'], description: '実効性よりも、対策しているように見せることを優先する状態。' },
  { term: '被害期待値', aliases: ['expected loss'], description: '被害の起こりやすさと大きさを合わせて見た損失の見込み。' },
  { term: '投資判断', aliases: ['investment decision'], description: 'どこに資源を配分するか決めること。' },
  { term: '受容できるリスク', aliases: ['acceptable risk'], description: '対策せずに受け入れると判断したリスク。' },
  { term: '監査', aliases: ['audit'], description: 'ルールどおりに仕事や会計が行われているか確認すること。' },
  { term: '教育', aliases: ['training'], description: '知識や行動を身につけ、ミスや事故を減らすこと。' },
  { term: 'ガバナンス', aliases: ['governance'], description: '組織として適切に管理し、責任ある判断を行う仕組み。' },
  { term: '被害確率', aliases: ['damage probability'], description: '事故や侵害が起こる可能性。' },
  { term: '被害規模', aliases: ['damage scale'], description: '事故や侵害が起こったときの損失の大きさ。' },
  { term: '無事故の約束', aliases: ['zero-incident promise'], description: '事故が絶対に起きないとする非現実的な考え方。' },
  { term: '信頼性', aliases: ['reliability'], description: '安定して期待どおりに動く度合い。' },
  { term: '倫理', aliases: ['ethics'], description: '社会的・道徳的に適切かを考える基準。' },
  { term: '社会との整合', aliases: ['social alignment'], description: '技術や判断が社会のルールや期待と合っていること。' },
  { term: '法令', aliases: ['legislation'], description: '法律や政令、省令など守るべき決まり。' },
  { term: '通報', aliases: ['whistleblowing'], description: '不正や問題行為を窓口などへ知らせること。' },
  { term: '内部通報', aliases: ['internal whistleblowing'], description: '会社内の不正や違反を定められた窓口へ知らせる仕組み。' },
  { term: '通報窓口', aliases: ['reporting channel'], description: '通報や相談を受け付ける窓口。' },
  { term: '是正措置', aliases: ['corrective action (governance)'], description: '問題を直すために行う対応。' },
  { term: '利益相反', aliases: ['conflict of interest'], description: '個人や別の立場の利益が会社の利益とぶつかること。' },
  { term: '反社会的勢力', aliases: ['antisocial forces'], description: '社会のルールに反する活動をする集団や個人。' },
  { term: '安全管理措置', aliases: ['security safeguards'], description: '情報漏えいなどを防ぐための組織的・人的・物理的・技術的対策。' },
  { term: 'アクセス権限', aliases: ['access permissions'], description: '誰がどの情報を見たり使ったりできるかという権限。' },
  { term: 'アクセスログ', aliases: ['access log'], description: '誰がいつどの情報にアクセスしたかの記録。' },
  { term: '情報漏えい', aliases: ['information leakage'], description: '本来見てはいけない人に情報が渡ってしまうこと。' },
  { term: 'インシデント', aliases: ['incident'], description: '情報漏えいや障害など問題や事故につながる出来事。' },
  { term: '個人データ', aliases: ['personal data'], description: '検索しやすい形で整理された個人情報。' },
  { term: '保有個人データ', aliases: ['retained personal data'], description: '会社が開示や訂正などに対応できる形で保有している個人データ。' },
  { term: '要配慮個人情報', aliases: ['sensitive personal information'], description: '特に慎重に扱うべき個人情報。' },
  { term: '特定個人情報', aliases: ['specific personal information'], description: '個人番号を含む個人情報。' },
  { term: '個人番号', aliases: ['individual number'], description: '税や社会保険の手続きなどに使う個人ごとの番号。' },
  { term: '利用目的', aliases: ['purpose of use'], description: '集めた情報を何のために使うかという目的。' },
  { term: '目的外利用', aliases: ['use beyond purpose'], description: '定めた利用目的の範囲を超えて情報を使うこと。' },
  { term: '第三者提供', aliases: ['third-party provision'], description: '本人や会社以外の相手に個人情報などを渡すこと。' },
  { term: '開示', aliases: ['disclosure'], description: '本人が自分の情報の提示を求めること、またはそれに応じて見せること。' },
  { term: '訂正', aliases: ['correction'], description: '間違っている情報を直すこと。' },
  { term: '利用停止', aliases: ['suspension of use'], description: '本人の求めなどに応じて情報の利用をやめること。' },
  { term: '削除', aliases: ['deletion'], description: '情報を消すこと。' },
  { term: '廃棄', aliases: ['disposal'], description: '書類や記録媒体を処分して使えないようにすること。' },
  { term: '機密保持', aliases: ['confidentiality (information management)'], description: '外部に漏らしてはいけない情報を守ること。' },
  { term: '入退室管理', aliases: ['entry and exit management'], description: '誰がいつ部屋や設備に出入りしたかを管理すること。' },
  { term: 'パスワード管理', aliases: ['password management'], description: 'パスワードを適切に設定・保管・更新すること。' },
  { term: '会計監査', aliases: ['financial audit'], description: '会計処理や財務諸表が正しく作られているか確認する監査。' },
  { term: '監査報告書', description: '監査結果や改善点をまとめた報告書。' },
  { term: '全社的な内部統制', aliases: ['company-wide internal controls'], description: '会社全体に共通する内部統制。' },
  { term: '評価', aliases: ['evaluation (audit)'], description: '仕組みや運用が機能しているか確認すること。' },
  { term: '是正', aliases: ['remediation'], description: '見つかった問題点を修正すること。' },
  { term: 'フォローアップ', aliases: ['follow-up'], description: '改善後に実際うまく機能しているか再確認すること。' },
  { term: 'J-SOX', aliases: ['j-sox'], description: '財務報告に関する内部統制の整備・運用・評価の枠組み。' },
  { term: 'コーポレートガバナンス', aliases: ['corporate governance'], description: '企業が健全かつ透明性高く経営されるための統治の仕組み。' },
  { term: '踏み台サーバ', description: '管理対象サーバへ直接入らず、中継点として経由するための管理用サーバ。' },
  { term: 'ISMAP', aliases: ['ismap'], description: '政府情報システムで利用するクラウドサービスの安全性を評価・登録する制度。' },
  { term: 'ゼロトラスト', description: '社内外を問わず無条件に信頼せず、常に認証・認可・検証を行う考え方。' },
  { term: 'SSO', aliases: ['sso'], description: '一度の認証で複数システムへ連携して利用できる仕組み。' },
  { term: 'LDAP', aliases: ['ldap', 'lightweight directory access protocol'], description: '利用者情報や組織情報を階層的に管理・参照するための標準プロトコル。' },
  { term: 'DDoS', aliases: ['ddos'], description: '大量の通信を送りつけ、サービス停止や遅延を引き起こす攻撃。' },
  { term: 'OpenVPN', aliases: ['openvpn'], description: '安全な遠隔接続を実現するVPNソフトウェア。' },
  { term: 'Sophos', aliases: ['sophos'], description: 'エンドポイント保護やネットワーク防御を提供するセキュリティ製品群。' },
  { term: 'MFA', aliases: ['mfa', 'multi-factor authentication'], description: '【セキュリティ】多要素認証のことで、複数手段で本人確認する方式。 【OCI APEX】複数要素で本人確認する認証方式。' },
  { term: 'DKIM', aliases: ['dkim', 'domainkeys identified mail'], description: '送信メールの正当性を検証する署名技術。' },
  { term: 'SPF', aliases: ['spf', 'sender policy framework'], description: '送信元メールサーバーの正当性を判定する仕組み。' },
  { term: 'DMARC', aliases: ['dmarc'], description: 'SPFやDKIMの結果を基にメールなりすまし対策を行う仕組み。' },
  { term: '入力検証', description: 'ユーザーや外部システムから受け取ったデータの形式・型・範囲を検証し、不正な値を拒否するセキュリティプラクティス。' },
  { term: 'サニタイズ', aliases: ['sanitize', 'サニタイゼーション'], description: '入力データから危険な文字や構造を除去・無害化し、インジェクション攻撃を防ぐ処理。' },
  { term: 'エスケープ', aliases: ['escape', 'エスケープ処理'], description: '特殊文字を無害な表現に変換してインジェクション攻撃を防ぐ処理。HTMLエスケープ・SQLエスケープなどがある。' },
  { term: 'クロスサイトスクリプティング', description: '悪意あるスクリプトをWebページに埋め込み、閲覧者のブラウザで実行させる攻撃手法。' },
  { term: '安全性', description: 'JIS X 0129-1における品質特性の一つ。人・財産・環境へのリスクを許容レベルに抑える度合い。' },
  { term: 'L7ファイアウォール', aliases: ['l7ファイアウォール'], description: 'HTTPSや通信内容まで検査できるアプリケーション層のファイアウォール。' },
  { term: 'UTM', aliases: ['utm'], description: 'Unified Threat Managementの略。ファイアウォール・IDS・アンチウイルスなど複数のセキュリティ機能を統合した機器。' },
  { term: 'NGFW', aliases: ['ngfw'], description: 'Next Generation Firewallの略。アプリケーション認識・ユーザーID・侵入防止（IPS）を統合した次世代ファイアウォール。' },
  { term: 'セキュリティポリシー', aliases: ['security policy'], description: '組織の情報セキュリティに関する方針・ルールを文書化したもの。基本方針・対策基準・実施手順の3階層で構成される。' },
  { term: '基本方針', aliases: ['basic policy'], description: 'セキュリティポリシーの最上位文書。経営層が宣言する情報セキュリティへの取り組み姿勢。' },
  { term: '対策基準', aliases: ['security standards'], description: '基本方針を受けて各部門が遵守すべきセキュリティルールを定めた文書。' },
  { term: '実施手順', aliases: ['implementation procedures'], description: '対策基準を具体的な操作・手順レベルで記述したドキュメント。運用マニュアルに相当する。' },
  { term: 'Secure Boot', aliases: ['secure boot', 'セキュアブート'], description: 'UEFIの機能の一つ。デジタル署名されたブートローダーのみ起動を許可し、マルウェアによるブートプロセスへの侵害を防ぐ仕組み。' },
  { term: 'SUID', aliases: ['suid', 'set user id', 'setuid'], description: 'Set User IDの略。実行ファイルに設定するとファイル所有者の権限でプログラムが実行される特殊パーミッション。passwdコマンドなどに使用される。' },
  { term: 'SGID', aliases: ['sgid', 'set group id', 'setgid'], description: 'Set Group IDの略。ファイルに設定すると所有グループ権限で実行、ディレクトリに設定すると作成ファイルが同じグループを継承する特殊パーミッション。' },
  { term: 'LUKS', aliases: ['luks', 'linux unified key setup'], description: 'Linuxの標準的なディスク暗号化仕様。dm-cryptの上に構築され、暗号化コンテナのヘッダ管理と複数キースロットをサポートする。' },
  { term: 'dm-crypt', description: 'Linuxカーネルのデバイスマッパー機能を使ったブロックデバイス暗号化サブシステム。LUKSの基盤となる暗号化レイヤー。' },
  { term: 'SELinux', aliases: ['selinux', 'security-enhanced linux'], description: 'Linuxカーネルに組み込まれた強制アクセス制御（MAC）の仕組み。ファイルやプロセスへのアクセスをポリシーで細かく制御する。' },
  { term: 'SELinuxコンテキスト', aliases: ['selinuxコンテキスト', 'selinux context', 'セキュリティコンテキスト'], description: 'SELinuxがファイル・プロセス・ポートなどのリソースに付与するセキュリティラベル。user:role:type:levelの形式で表現され、アクセス制御判断に使用される。' },
  { term: 'getenforce', description: 'SELinuxの現在の動作モード（Enforcing/Permissive/Disabled）を確認するコマンド。' },
  { term: 'setenforce', description: 'SELinuxの動作モードをEnforcingとPermissiveの間で切り替えるコマンド。setenforce 0でPermissive、1でEnforcingモードに設定する。' },
  { term: 'restorecon', description: 'SELinuxのファイルコンテキストをポリシーで定義されたデフォルト値に復元するコマンド。ファイル移動後のコンテキスト修正に使用する。' },
  { term: 'audit2allow', description: 'SELinuxのauditログに記録された拒否ログから、必要なアクセスを許可するSELinuxポリシーモジュールを生成するコマンド。' },
  { term: 'AppArmor', aliases: ['apparmor'], description: 'Linuxカーネルの強制アクセス制御（MAC）モジュール。SELinuxよりシンプルなプロファイルベースの設計で、Ubuntu系ディストリビューションで採用されている。' },
  { term: 'useradd', description: 'Linuxシステムに新規ユーザーアカウントを作成するコマンド。ホームディレクトリ、シェル、グループなどのオプションを指定できる。' },
  { term: 'usermod', description: '既存ユーザーアカウントの属性（グループ、シェル、ホームディレクトリ等）を変更するコマンド。usermod -aG groupname usernameでグループ追加が代表的用途。' },
  { term: 'userdel', description: 'Linuxシステムからユーザーアカウントを削除するコマンド。-rオプションでホームディレクトリとメールスプールも同時に削除できる。' },
  { term: 'groupadd', description: 'Linuxシステムに新規グループを作成するコマンド。グループID（GID）を指定したり、システムグループとして作成するオプションがある。' },
  { term: 'passwd', description: 'ユーザーのパスワードを設定・変更するコマンド。root権限で他ユーザーのパスワードも変更でき、/etc/shadowに暗号化して保存される。' },
  { term: '/etc/passwd', aliases: ['passwd file'], description: 'Linuxのユーザーアカウント情報（ユーザー名、UID、GID、ホームディレクトリ、シェル）を格納するテキストファイル。' },
  { term: '/etc/shadow', aliases: ['shadow file'], description: '暗号化されたパスワードとパスワードポリシー情報を格納するファイル。rootのみ読み取り可能で、/etc/passwdからパスワード情報を分離したもの。' },
  { term: '/etc/group', aliases: ['group file'], description: 'システムのグループ定義（グループ名、GID、メンバー一覧）を格納するテキストファイル。' },
  { term: 'visudo', description: 'sudoの設定ファイル（/etc/sudoers）を安全に編集するコマンド。構文チェックを行いエラーがあれば保存を拒否し設定破損を防ぐ。' },
  { term: 'PAM', aliases: ['pam', 'pluggable authentication modules'], description: 'Pluggable Authentication Modulesの略。認証・アカウント管理・セッション管理をモジュール化し、アプリケーションを変更せずに認証方式を変更できる仕組み。' },
  { term: 'NSS', aliases: ['nss', 'name service switch'], description: 'Name Service Switchの略。ユーザー名・グループ名・ホスト名などの名前解決をどのソース（files、LDAP、SSSDなど）から行うかを/etc/nsswitch.confで設定する仕組み。' },
  { term: 'SSSD', aliases: ['sssd', 'system security services daemon'], description: 'System Security Services Daemonの略。LDAPやActive DirectoryなどのリモートIDプロバイダと連携してLinuxの認証・認可を提供するデーモン。' },
  { term: 'Kerberos', aliases: ['kerberos'], description: 'MITが開発したネットワーク認証プロトコル。チケットベースの認証でパスワードをネットワーク上に流さずシングルサインオンを実現する。' },
  { term: 'sshd_config', aliases: ['/etc/ssh/sshd_config'], description: 'SSHサーバー（sshd）の設定ファイル（/etc/ssh/sshd_config）。ポート番号、root loginの許可、パスワード認証の有効化などを設定する。' },
  { term: 'authorized_keys', aliases: ['~/.ssh/authorized_keys'], description: 'SSHの公開鍵認証で使用するファイル（~/.ssh/authorized_keys）。接続を許可するクライアントの公開鍵を1行ずつ記述する。' },
  { term: 'known_hosts', aliases: ['~/.ssh/known_hosts'], description: 'SSHクライアントが接続先サーバーの公開鍵を記録するファイル（~/.ssh/known_hosts）。初回接続時にホスト鍵が追加され、次回以降の接続時に検証される。' },
  { term: 'su', description: '別のユーザー（デフォルトはroot）の権限でシェルを起動するコマンド。su - でそのユーザーの完全な環境も引き継ぐ。' },
  { term: '公開鍵認証', aliases: ['public key authentication'], description: '秘密鍵と公開鍵のペアを使用したSSH認証方式。パスワード認証より安全でブルートフォース攻撃に強く、自動化スクリプトにも利用される。' },
  { term: '権限設計', description: 'システムやリソースへのアクセス可否を役割・職責に基づいて設計すること。最小権限の原則に従い、不要な権限を与えない設計が重要。' },
  { term: 'SAST', aliases: ['sast', 'static application security testing', '静的アプリケーションセキュリティテスト'], description: '静的アプリケーションセキュリティテストの略。ソースコードやバイトコードをコンパイル・実行せずに解析し、SQLインジェクションやバッファオーバーフローなどの脆弱性パターンを検出する手法。CIパイプラインに組み込んで早期発見に活用する。' },
  { term: 'DAST', aliases: ['dast', 'dynamic application security testing', '動的アプリケーションセキュリティテスト'], description: '動的アプリケーションセキュリティテストの略。実際に動作しているアプリケーションに対してリクエストを送信し、レスポンスを解析して脆弱性を発見する手法。実行時の動作を検査するためSASTでは検出できない問題も発見できる。' },
  { term: 'IAST', aliases: ['iast', 'interactive application security testing', 'インタラクティブアプリケーションセキュリティテスト'], description: 'インタラクティブアプリケーションセキュリティテストの略。アプリケーションにエージェントを組み込み、実行中に内部の処理フローを監視して脆弱性を検出する手法。SASTとDASTの利点を組み合わせた中間的アプローチ。' },
  { term: 'RASP', aliases: ['rasp', 'runtime application self-protection', 'ランタイムアプリケーション自己防御'], description: 'ランタイムアプリケーション自己防御の略。アプリケーション自体にセキュリティ制御を組み込み、実行時に攻撃を検知・ブロックする技術。インジェクション攻撃やパストラバーサルなどをリアルタイムで防御できる。' },
  { term: 'STRIDE', aliases: ['stride', 'stride脅威モデル'], description: 'マイクロソフトが開発した脅威モデリングフレームワーク。Spoofing・Tampering・Repudiation・Information Disclosure・Denial of Service・Elevation of Privilegeの6カテゴリで脅威を分類する設計段階向けの手法。' },
  { term: 'DREAD', aliases: ['dread', 'dreadリスクモデル'], description: '脆弱性のリスクを定量化するスコアリングモデル。Damage（被害）・Reproducibility（再現性）・Exploitability（悪用可能性）・Affected Users（影響ユーザー数）・Discoverability（発見容易性）の各軸で1〜10点を付け合計点でリスクを評価する。' },
  { term: 'OWASP ASVS', aliases: ['owasp asvs', 'application security verification standard'], description: 'OWASPが定めるアプリケーションセキュリティ検証標準。Webアプリケーションのセキュリティ要件を3段階のレベルで体系化した標準仕様で、設計・開発・テスト・調達の各フェーズで参照される。ASVS はApplication Security Verification Standardの略。' },
  { term: 'CWE', aliases: ['cwe', 'common weakness enumeration'], description: 'Common Weakness Enumerationの略。ソフトウェアのセキュリティ上の弱点（脆弱性の根本原因となる設計・実装上の欠陥）を体系的に分類した辞書。MITREが管理しており、SASTツールの検出カテゴリや脆弱性報告の共通言語として使われる。' },
  { term: 'NVD', aliases: ['nvd', 'national vulnerability database', '米国国立脆弱性データベース'], description: 'National Vulnerability Databaseの略。米国国立標準技術研究所（NIST）が管理する脆弱性データベース。CVE番号ごとにCVSSスコア・参照情報・パッチ情報を提供しており、脆弱性管理や優先度付けの基盤として広く利用される。' },
  { term: 'X-Content-Type-Options', aliases: ['x-content-type-options', 'nosniff', 'mimeタイプスニッフィング防止'], description: 'HTTPレスポンスヘッダーの一つ。`nosniff`を指定することで、ブラウザがContent-Typeを無視してレスポンスのコンテンツ種別を推測（MIMEスニッフィング）する動作を防止する。スクリプトとして不正に解釈されるリスクを軽減するセキュリティヘッダー。' },
  { term: 'X-Frame-Options', aliases: ['x-frame-options', 'フレームオプション', 'クリックジャッキング防止ヘッダ'], description: 'HTTPレスポンスヘッダーの一つ。ページをiframe内に埋め込むことを制限しクリックジャッキング攻撃を防ぐ。DENY・SAMEORIGIN・ALLOW-FROMの値を指定する。現代ではCSPのframe-ancestorsが推奨される。' },
  { term: 'Referrer-Policy', aliases: ['referrer-policy', 'リファラーポリシー', '参照元ポリシー'], description: 'HTTPレスポンスヘッダーの一つ。リンクやリダイレクトの際にRefererヘッダーでどの程度の情報を送信するかを制御する。`strict-origin-when-cross-origin`や`no-referrer`などのポリシーで機密URLの漏洩やプライバシー侵害を防ぐ。' },
  { term: 'Permissions-Policy', aliases: ['permissions-policy', 'feature-policy', 'パーミッションポリシー'], description: 'HTTPレスポンスヘッダーの一つ（旧Feature-Policy）。カメラ・マイク・位置情報・全画面表示などブラウザ機能へのアクセス権限をオリジンごとに制御する。埋め込みコンテンツや第三者スクリプトによる不正なデバイスアクセスを防止する。' },
  { term: 'SRI', aliases: ['sri', 'subresource integrity', 'サブリソース完全性'], description: 'Subresource Integrityの略。CDNなど外部から読み込むスクリプトやスタイルシートのハッシュ値をHTML内に記述し、取得したリソースが改ざんされていないことをブラウザが検証する仕組み。サプライチェーン攻撃対策として有効。' },
  { term: 'SSRF', aliases: ['ssrf', 'server-side request forgery', 'サーバーサイドリクエストフォージェリ'], description: 'Server-Side Request Forgeryの略。攻撃者がサーバーに細工したURLを送りつけ、サーバー自身に内部ネットワークやクラウドのメタデータエンドポイントへのリクエストを発行させる脆弱性。AWSメタデータサービスへのアクセスによるクレデンシャル窃取が典型例。' },
  { term: 'XXE', aliases: ['xxe', 'xml external entity', 'xmlエクスターナルエンティティ攻撃'], description: 'XML External Entity Injectionの略。XMLパーサーが外部エンティティ参照を処理する際、攻撃者が細工したXMLを送ることでサーバー上のファイル読み込みやSSRF、DoSを引き起こす脆弱性。外部エンティティ処理を無効化することで防止できる。' },
  { term: 'デシリアライゼーション攻撃', aliases: ['insecure deserialization', '安全でないデシリアライゼーション'], description: '信頼できないデータをデシリアライズ（復元）する際に任意コード実行やオブジェクト操作を引き起こす脆弱性を悪用した攻撃。JavaのネイティブシリアライゼーションやPHPのunserialize()が標的になりやすく、入力検証と型検証が対策の基本。' },
  { term: 'パストラバーサル', aliases: ['path traversal', 'directory traversal', 'ディレクトリトラバーサル'], description: 'ファイルパスに`../`などのディレクトリ移動シーケンスを挿入し、Webサーバーのドキュメントルート外の任意ファイルにアクセスする攻撃。設定ファイルやパスワードファイルの読み取りに悪用される。パス正規化と絶対パス検証で防ぐ。' },
  { term: 'コマンドインジェクション', aliases: ['command injection', 'osコマンドインジェクション'], description: 'ユーザー入力がOSコマンドの一部として実行される脆弱性。セミコロンやパイプなどのシェルメタキャラクタを混入させ任意コマンドを実行させる。パラメータ化コマンド実行APIや入力の厳格なサニタイズで防止する。' },
  { term: 'LDAPインジェクション', aliases: ['ldapインジェクション', 'ldap injection'], description: 'LDAPクエリに悪意ある入力を挿入し、認証バイパスや不正なディレクトリ情報取得を引き起こす脆弱性。SQLインジェクションのLDAP版。特殊文字をエスケープしたパラメータ化LDAPクエリで防止する。' },
  { term: 'ログインジェクション', aliases: ['log injection', 'ログ偽装'], description: 'ログファイルに改行文字などを含む悪意ある文字列を挿入し、ログ記録を改ざんしたり解析ツールを誤動作させる攻撃。フォレンジックの妨害や不正操作の隠蔽に使われる。ログ出力前に改行・制御文字をサニタイズすることで防ぐ。' },
  { term: 'レースコンディション攻撃', aliases: ['time-of-check time-of-use', 'toctou'], description: '並行処理における時間的競合（TOCTOU: Time-Of-Check to Time-Of-Use）を悪用した攻撃。チェックと使用の間に状態を改変することで権限昇格や二重処理を引き起こす。適切なロック機構やアトミック操作で防止する。' },
  { term: 'オープンリダイレクト', aliases: ['open redirect', 'オープンリダイレクト脆弱性'], description: 'Webアプリケーションがユーザー指定のURLにリダイレクトする機能を悪用し、フィッシングサイトや悪意あるページへ誘導する攻撃。信頼できるドメインのURLに見せかけて被害者を騙す。リダイレクト先URLを許可リストで厳格に制限することが対策。' },
  { term: 'マスアサインメント', aliases: ['mass assignment', '一括代入脆弱性'], description: 'HTTPリクエストのパラメータをモデルのフィールドに一括代入する機能が悪用され、本来変更不可な属性（管理者フラグ・ロールなど）を書き換えられる脆弱性。許可するフィールドを明示的に指定する許可リスト方式で対策する。' },
  { term: 'IDOR', aliases: ['idor', 'insecure direct object reference', '安全でない直接オブジェクト参照'], description: 'Insecure Direct Object Referenceの略。URLやパラメータに含まれるオブジェクトID（ユーザーID・注文番号など）を変更することで、認可チェックなしに他ユーザーのリソースへアクセスできる脆弱性。アクセスごとに認可を検証することで防止する。' },
  { term: 'アクセス制御不備', aliases: ['broken access control', '壊れたアクセス制御'], description: '認証済みユーザーが本来アクセスできないリソースや機能にアクセスできる脆弱性カテゴリ。OWASP Top 10で常に上位を占める。水平・垂直権限昇格、IDOR、強制ブラウジングなどが含まれ、すべてのリクエストで認可チェックを実施することが基本対策。' },
  { term: 'セキュリティ設定ミス', aliases: ['security misconfiguration', 'セキュリティミスコンフィグレーション'], description: 'クラウド・サーバー・フレームワークのデフォルト設定の放置、不要なサービスの有効化、エラー詳細の露出など、不適切な設定に起因するセキュリティリスク。OWASP Top 10に含まれ、インフラをコード化（IaC）して設定のレビューと自動チェックを行うことが対策。' },
  { term: '暗号化の失敗', aliases: ['cryptographic failures', '機密データの露出'], description: '機密データの平文保存・送信、弱い暗号アルゴリズムの使用、鍵管理の不備など、暗号化に関する設計・実装上の欠陥の総称。OWASP Top 10に含まれ（旧称: 機密データの露出）。TLSの適切な利用とAES-256・bcryptなどの強固なアルゴリズム選択が対策の基本。' },
  { term: 'サーバーサイドテンプレートインジェクション', aliases: ['ssti', 'server-side template injection'], description: 'ユーザー入力がサーバー側のテンプレートエンジン（Jinja2・Twig・Freemarkerなど）に直接埋め込まれ、任意のテンプレート式を実行させる脆弱性。リモートコード実行に発展することが多く、入力をテンプレートに直接結合しないことが対策。' },
  { term: 'プロトタイプ汚染', aliases: ['prototype pollution', 'プロトタイプポリューション'], description: 'JavaScriptのプロトタイプチェーンを悪用し、Object.prototypeなど基底オブジェクトのプロパティを変更することで、アプリケーション全体の動作を改ざんする脆弱性。ライブラリのオブジェクトマージ処理が攻撃ベクターになりやすい。' },
  { term: 'ReDoS', aliases: ['redos', 'regular expression denial of service', '正規表現dos'], description: 'Regular Expression Denial of Serviceの略。バックトラッキングが爆発的に増加する正規表現（カタストロフィックバックトラッキング）に悪意ある入力を与え、CPUを枯渇させるDoS攻撃。複雑な繰り返しパターンを避け、入力長を制限することで対策する。' },
  { term: 'サプライチェーン攻撃', aliases: ['supply chain attack', 'ソフトウェアサプライチェーン攻撃'], description: 'ソフトウェアの開発・配布プロセスに侵入し、依存ライブラリ・ビルドツール・更新システムを通じてマルウェアを配布する攻撃。SolarWinds事件やEvent-Stream事件が著名な例。SBOMの整備、依存関係の固定、SRI検証が対策の基本。' },
  { term: '依存関係の混乱', aliases: ['dependency confusion', '依存関係混乱攻撃'], description: 'プライベートパッケージと同名のパブリックパッケージを高いバージョン番号でnpmなど公開リポジトリに登録し、ビルドシステムが誤って悪意あるパッケージをインストールするサプライチェーン攻撃の一種。' },
  { term: 'タイポスクワッティング', aliases: ['typosquatting', 'タイポスクワット攻撃'], description: '正規パッケージ名のタイプミスを狙い、類似した名前の悪意あるパッケージを公開リポジトリに登録してインストールを誘導するサプライチェーン攻撃。`cros`（cross）、`reuqest`（request）などの変名が使われる。パッケージ名を慎重に確認し固定バージョンを使用することが対策。' },
  { term: 'IDS', aliases: ['ids', 'intrusion detection system', '侵入検知システム'], description: 'Intrusion Detection Systemの略。ネットワークトラフィックやシステムのログを監視し、不正アクセスや攻撃の兆候を検知してアラートを生成するシステム。IPSとは異なりトラフィックの遮断は行わない。シグネチャベースと異常検知ベースの2方式がある。' },
  { term: 'IPS', aliases: ['ips', 'intrusion prevention system', '侵入防止システム'], description: 'Intrusion Prevention Systemの略。IDSの検知機能に加えて、不正なトラフィックをリアルタイムで自動的に遮断・ブロックする機能を持つシステム。インラインで動作しネットワーク境界での多層防御を実現するが、誤検知による正常通信のブロックリスクもある。' },
  { term: 'XDR', aliases: ['xdr', 'extended detection and response', '拡張型検知対応'], description: 'Extended Detection and Responseの略。エンドポイント・ネットワーク・クラウド・メールなど複数のセキュリティレイヤーからデータを統合収集し、相関分析によって高精度な脅威検知と対応を実現するセキュリティプラットフォーム。EDRを発展させたアプローチ。' },
  { term: 'SOAR', aliases: ['soar', 'security orchestration automation and response', 'セキュリティオーケストレーション自動化対応'], description: 'SIEMなどからアラートを受け取り、定義済みプレイブックに従ってインシデント対応を自動化・オーケストレーションするプラットフォーム。Security Orchestration, Automation and Responseの略。アナリスト工数を削減しMTTRを短縮する。' },
  { term: 'MITRE ATT&CK', aliases: ['mitre att&ck', 'att&ck', 'mitre att and ck', 'mitreアタック'], description: '実際の攻撃者の戦術・技術・手順（TTP）を体系化したナレッジベース。MITREが管理し、偵察からデータ窃取・影響工作まで14の戦術カテゴリに攻撃技術を分類する。脅威ハンティング・レッドチーム演習・インシデント対応の共通言語として使われる。' },
  { term: 'キルチェーン', aliases: ['cyber kill chain', 'サイバーキルチェーン'], description: 'ロッキード・マーティンが提唱したサイバー攻撃の段階モデル。偵察・武器化・デリバリー・エクスプロイト・インストール・C2（指揮統制）・目的実行の7段階で構成され、各フェーズで防御策を講じることでキルチェーンを断ち切る概念。' },
  { term: 'バグバウンティ', aliases: ['bug bounty', 'バグバウンティプログラム'], description: '企業が外部のセキュリティ研究者に自社サービスの脆弱性発見を依頼し、報告された脆弱性の深刻度に応じて報奨金（バウンティ）を支払うプログラム。HackerOneやBugcrowdなどのプラットフォームが仲介し、内部のみでは見つけられない脆弱性を発見する手段として普及している。' },
  { term: '責任ある脆弱性開示', aliases: ['responsible disclosure', 'coordinated vulnerability disclosure', 'cvd', '協調的脆弱性開示'], description: 'セキュリティ研究者が発見した脆弱性を即時公開せず、まず影響を受けるベンダーに報告し修正の猶予（通常90日）を与えた後に公開するプロセス。Coordinated Vulnerability Disclosureとも呼ばれ、修正前の悪用を防ぎながら情報共有を実現するバランスを取る。' },
  { term: 'ISO 27001', aliases: ['iso 27001', 'iso/iec 27001', 'isms', '情報セキュリティマネジメントシステム'], description: '情報セキュリティマネジメントシステム（ISMS）の要求事項を定めた国際標準。リスクベースのアプローチでリスクアセスメント・管理策の実施・継続的改善のサイクルを回すことを要求する。取得認証は取引先への信頼性証明として広く活用される。' },
  { term: 'SOC 2', aliases: ['soc 2', 'soc2', 'service organization control 2'], description: '米国公認会計士協会（AICPA）が定めるサービス組織のセキュリティ・可用性・処理の完全性・機密性・プライバシーに関する監査基準。SaaS企業が顧客に対してセキュリティ態勢を証明するために取得し、Type IとType IIがある。' },
  { term: 'NIST CSF', aliases: ['nist csf', 'nist cybersecurity framework', 'cybersecurity framework', 'csf'], description: '米国国立標準技術研究所（NIST）が策定したサイバーセキュリティフレームワーク。識別・防御・検知・対応・復旧の5機能で組織のサイバーセキュリティリスク管理を体系化するガイドライン。重要インフラ保護を起源に持ち、業界横断で活用される。' },
  { term: 'GDPR', aliases: ['gdpr', 'general data protection regulation', 'eu一般データ保護規則'], description: 'EU一般データ保護規則の略。EU域内の個人データを処理するすべての組織に適用されるプライバシー法規制。忘れられる権利・データポータビリティ・プライバシーバイデザインを要求し、違反時は全世界売上高の4%相当の制裁金が科される。' },
  { term: 'PCI DSS', aliases: ['pci dss', 'pci-dss', 'payment card industry data security standard', 'ペイメントカード業界データセキュリティ標準'], description: 'クレジットカード情報を取り扱う事業者が準拠すべきセキュリティ標準。Payment Card Industry Data Security Standardの略。カード会員データ保護・ネットワーク分離・脆弱性管理・アクセス制御など12の要件から構成される。' },
  { term: 'HIPAA', aliases: ['hipaa', '医療情報ポータビリティ・説明責任法', 'health insurance portability and accountability act'], description: '米国の医療情報プライバシー法。保護対象医療情報（PHI）の取り扱い・アクセス制御・監査・暗号化を要求する。クラウドサービスプロバイダーも医療機関と締結するBAA（Business Associate Agreement）の締結により対象となる。' },
  { term: 'リフレクトXSS', aliases: ['リフレクトxss', 'reflected xss', '反射型xss'], description: '攻撃スクリプトがURLパラメータ等に含まれ、サーバーがその内容をそのままHTMLに出力する形のXSS（クロスサイトスクリプティング）。悪意あるリンクを踏んだユーザーのブラウザ上でスクリプトが実行される。出力時のエスケープとCSPで防止する。' },
  { term: 'ストアドXSS', aliases: ['ストアドxss', 'stored xss', '蓄積型xss', '永続型xss'], description: '攻撃スクリプトがデータベースやサーバーに保存され、ページを閲覧したすべてのユーザーに対してスクリプトが実行されるXSSの一形態。掲示板やコメント欄が典型的な攻撃対象。永続型XSSとも呼ばれ、影響範囲が広い。' },
  { term: 'DOMベースXSS', aliases: ['domベースxss', 'dom-based xss', 'dom型xss'], description: 'サーバーを介さず、クライアントサイドのJavaScriptがURLフラグメントやlocation.hashなどを読み取りDOMを動的に書き換える際に発生するXSS。サーバーのレスポンスには攻撃コードが含まれないため従来のサーバーサイドフィルタでは検出できない。' },
  { term: '脅威ハンティング', aliases: ['threat hunting', 'プロアクティブ脅威検出'], description: 'SIEMやEDRのアラートに頼らず、仮説を立てて積極的に環境内の未検知脅威を探索するプロアクティブなセキュリティ活動。MITRE ATT&CKのTTPを参照しつつアナリストが手動・半自動でログやエンドポイントを調査する。' },
  { term: 'ハニーポット', aliases: ['honeypot', 'おとりシステム'], description: '攻撃者を意図的に誘い込むために設置された囮システム。実際の被害なく攻撃者の手法や目的を観察・分析でき、早期警戒やTTP収集に活用される。ハニーネット・ハニートークンなどの派生形もある。' },
  { term: 'FIDO2', aliases: ['fido2', 'webauthn', 'パスキー', 'passkey', 'fido', 'fast identity online'], description: 'Fast Identity Onlineアライアンスが策定したパスワードレス認証標準。WebAuthn（W3C標準）とCTAP（デバイス通信プロトコル）で構成され、生体認証や物理セキュリティキーを使ってフィッシング耐性の高い認証を実現する。' },
  { term: '最小権限の原則', aliases: ['polp', '最小特権の原則'], description: 'ユーザー・プロセス・サービスに対して業務遂行に必要な最小限の権限のみを付与するセキュリティ原則。権限の過剰付与を防ぎ、侵害された場合の被害範囲を限定する。ゼロトラストアーキテクチャの基本原則の一つ。' },
  { term: '多層防御', aliases: ['defense in depth', 'did', '縦深防御'], description: '単一の防御策への依存を避け、ネットワーク・ホスト・アプリケーション・データなど複数レイヤーに独立したセキュリティ制御を配置する防御戦略。1つの防御が突破されても次の層が攻撃を阻止できるよう設計する。' },
  { term: 'ゼロデイ脆弱性', aliases: ['zero-day vulnerability', '0-day', 'ゼロデイ攻撃'], description: 'ベンダーが把握する前または修正パッチが提供される前に悪用可能な未知の脆弱性。発見から修正まで防御側の対策が困難なため非常に危険。仮想パッチ（WAFルールなど）や振る舞い検知で被害を軽減する。' },
  { term: 'CVSSスコア', aliases: ['cvssスコア', 'common vulnerability scoring system', '脆弱性深刻度スコア'], description: 'Common Vulnerability Scoring Systemによる脆弱性の深刻度を0.0〜10.0で数値化したスコア。攻撃経路・攻撃の複雑さ・必要権限・ユーザー操作・影響範囲・機密性/完全性/可用性への影響を元にベーススコアを計算し、パッチ適用の優先順位付けに使う。' },
];
