// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: enterpriseArch (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // enterprise (57), migration (18), integration (17), Migration (2)
  { term: '他システム連携', description: '外部または別システムとデータや処理をやり取りすることです。自システムだけ見て設計すると連携部で問題が起きやすいため、相手側仕様の理解が欠かせません。' },
  { term: 'データ移行', aliases: ['data migration'], description: '旧システムから新システムへデータを移す作業です。単純コピーでは済まず、形式変換、重複除去、欠損補完が必要になることが多いです。' },
  { term: 'マイグレーション', description: 'システムやデータ構造を計画的に変更していくことです。DBのスキーマ変更やクラウド移行など、段階的に行う場面でよく使われます。' },
  { term: '仮想マシン', aliases: ['virtual machine', 'vm'], description: '1台の物理サーバー上に複数の仮想的なコンピューターを作る仕組みです。従来型の業務システム移行でもよく使われます。' },
  { term: 'メッセージブローカー', description: 'システム間のメッセージ受け渡しを仲介する仕組みです。送信側と受信側をゆるくつなぎ、大量処理や非同期連携を支えます。' },
  { term: 'インターフェース分離原則', description: '利用者に不要な機能まで押しつけるような大きすぎる契約を避ける考え方です。小さく焦点の合ったインターフェースは変更にも強いです。' },
  { term: '専用線接続', description: 'クラウドやデータセンターへ安定した専用回線で接続する方式です。高品質ですが、コストや準備期間は大きくなります。' },
  { term: 'フェデレーション', description: '組織やシステムをまたいで認証情報を連携する仕組みです。グループ会社間やSaaS連携で重要になる考え方です。' },
  { term: '切替計画', description: '新旧システムをどう切り替えるかを定めた計画です。停止時間、データ移行、周知、切り戻し条件まで整理する必要があります。' },
  { term: '受入移行', description: '発注者側が新システムや成果物を実運用へ取り込む工程です。納品完了と業務定着は別物であることを意識する必要があります。' },
  { term: '空打ち防止', description: '何度も送信や登録が走らないようにする工夫です。二重送信防止だけでなく、利用者の不安軽減にもつながります。' },
  { term: 'セルフヒーリング', description: 'システム自身が異常を検知し、自動で回復に向かう性質や仕組みです。単なる再起動だけでなく、退避や切替も含むことがあります。' },
  { term: '接続プール枯渇', description: 'DBや外部接続の利用枠が使い切られる状態です。アプリは動いていても、実質的に応答不能になることがあります。' },
  { term: 'モデル切替戦略', description: '用途に応じて高速モデルと高精度モデルを使い分ける考え方です。全件を高性能モデルにするより、コストと品質のバランスを取りやすくなります。' },
  { term: 'デプリケーション', description: '将来廃止予定であることを示す状態です。突然止めるのではなく、利用者へ移行期間を与える考え方です。' },
  { term: '受信確認', description: '相手が確かに受け取ったか確認する仕組みです。送信しただけで安心せず、相手側到達を見届ける必要がある場面で使います。' },
  { term: 'オフライン連携', description: '常時接続ではなく、ファイルやバッチなどで後追い連携する方式です。リアルタイム性は低いですが、安定性を取りやすいことがあります。' },
  { term: 'オンライン連携', description: 'その場で即時にデータや処理をやり取りする方式です。利用体験はよいですが、依存先障害の影響を受けやすいです。' },
  { term: '疎通試験', description: '接続、認証、簡易リクエストなどを使って連携基盤が動くか確認する試験です。本格的な連携テストの前段になります。' },
  { term: 'ESB', aliases: ['esb'], description: 'Enterprise Service Busの略で、複数システム間の連携を仲介、変換する基盤です。集中管理しやすい反面、中央集権化しすぎると重くなることがあります。' },
  { term: 'ERP', aliases: ['erp'], description: 'Enterprise Resource Planningの略で、会計、人事、購買、生産などを統合管理する仕組みです。全体最適を目指しやすい一方、Fit to Standardの発想が重要です。' },
  { term: 'CRM', aliases: ['crm'], description: '顧客との関係や接点を管理する仕組みです。営業活動だけでなく、問い合わせや継続率改善にも関わります。' },
  { term: 'SFA', aliases: ['sfa'], description: '営業活動支援のための仕組みです。案件管理、商談履歴、見込管理などを通じて営業の可視化に役立ちます。' },
  { term: 'SCM', aliases: ['scm'], description: 'Supply Chain Managementの略で、調達、生産、在庫、配送の流れを管理する考え方です。部門横断で最適化が必要になります。' },
  { term: 'WMS', aliases: ['wms'], description: '倉庫管理システムです。入庫、出庫、棚卸し、在庫配置など物流現場に深く関わります。' },
  { term: 'TMS', aliases: ['tms'], description: '輸配送管理システムとして使われることが多い言葉です。配送計画や実績管理に関わります。' },
  { term: '会計システム', aliases: ['accounting system'], description: '仕訳、帳簿、決算、税務関連処理を支えるシステムです。内部統制と法令対応の観点が特に強く求められます。' },
  { term: '販売管理システム', aliases: ['sales management system'], description: '見積、受注、売上、請求、入金など販売業務を管理するシステムです。商流や契約条件との整合が重要です。' },
  { term: '購買管理システム', aliases: ['procurement management system'], description: '発注、検収、支払など購買業務を管理するシステムです。契約管理や予算統制と結びつくことが多いです。' },
  { term: '在庫管理システム', aliases: ['inventory management system'], description: '在庫数量、場所、入出庫履歴を管理するシステムです。リアルタイム性と整合性のバランスが重要です。' },
  { term: '生産管理システム', aliases: ['production management system'], description: '生産計画、工程、実績、在庫、原価を管理するシステムです。現場実態と標準化の折り合いが設計ポイントになります。' },
  { term: '人事システム', aliases: ['hr system'], description: '組織、人員、異動、評価、給与前提情報などを管理するシステムです。個人情報保護要件が強くなります。' },
  { term: '勤怠管理システム', aliases: ['attendance management system'], description: '出退勤、休暇、残業など勤務実績を管理するシステムです。労務ルールや法令対応が重要です。' },
  { term: '経費精算システム', aliases: ['expense reimbursement system'], description: '交通費や立替経費の申請、承認、支払を管理するシステムです。ワークフローと会計連携が中心になります。' },
  { term: '原価計算', aliases: ['cost accounting'], description: '商品や案件にどれだけ費用がかかったかを計算することです。価格戦略や採算管理の基礎になります。' },
  { term: '部門別採算', aliases: ['departmental profitability'], description: '部門ごとの収益やコストを把握する考え方です。全社数字だけでは見えない改善余地が見えます。' },
  { term: '配賦', aliases: ['cost allocation'], description: '共通費用を一定ルールで各部門や案件へ割り振ることです。公平性と説明可能性が重要になります。' },
  { term: '共通費', aliases: ['shared cost'], description: '個別案件へ直接ひもづけにくい費用です。配賦方法しだいで採算の見え方が変わります。' },
  { term: '変動費', aliases: ['variable cost'], description: '量や活動に応じて増減する費用です。クラウド利用料や配送費などが典型です。' },
  { term: '固定費', aliases: ['fixed cost'], description: '利用量に関係なく一定でかかる費用です。人件費や契約基本料などが該当することがあります。' },
  { term: '損益分岐点', aliases: ['break-even point'], description: '赤字でも黒字でもない境目となる売上水準です。価格や原価構造の見直しに役立ちます。' },
  { term: '収支計画', aliases: ['revenue and expense plan'], description: '売上と費用の見込みを整理した計画です。案件単位でも部門単位でも重要です。' },
  { term: '予実管理', aliases: ['budget vs. actual management'], description: '予算や計画と実績を比較し、差を管理することです。差異理由を分析して次の判断へつなげる必要があります。' },
  { term: '差異分析', aliases: ['variance analysis'], description: '計画と実績の差をなぜ生んだか調べることです。数字の差だけ見ても、改善にはつながりにくいです。' },
  { term: '月次締め', aliases: ['monthly close'], description: '月単位で取引や実績を確定させる処理です。早く正確に締められるかは業務基盤の重要品質です。' },
  { term: '年次決算', aliases: ['annual settlement'], description: '年度単位で財務数値を確定し報告する作業です。システムはこの正確性と証跡性を支える必要があります。' },
  { term: '内部取引消去', aliases: ['intercompany elimination'], description: 'グループ内取引を連結上相殺する処理です。複数法人をまたぐシステムでは設計上重要になることがあります。' },
  { term: '連結会計', aliases: ['consolidated accounting'], description: 'グループ会社全体を一つとして財務状況を把握する考え方です。単体会計と粒度が異なるため、データ設計も工夫が必要です。' },
  { term: '予算統制', aliases: ['budget control'], description: '予算超過を防ぐため、申請や支出を制御することです。購買や稟議フローと組み合わせて設計されることがあります。' },
  { term: '購買稟議', aliases: ['purchase approval'], description: '購入や契約前に必要な内部承認です。金額や内容に応じた承認経路設計が必要になります。' },
  { term: '支払依頼', aliases: ['payment reconciliation'], description: '経理や財務へ支払実行を依頼する処理です。請求書、検収、契約条件との整合が求められます。' },
  { term: '入金消込', description: '入金実績を売掛や請求データへひもづけることです。自動化しにくい例外も多く、設計の工夫が必要です。' },
  { term: '売掛管理', aliases: ['accounts receivable management'], description: '請求済みでまだ回収していない金額を管理することです。営業、経理、契約管理の接点になります。' },
  { term: '買掛管理', aliases: ['accounts payable management'], description: '仕入や外注費など、まだ支払っていない債務を管理することです。支払サイトや検収条件と連動します。' },
  { term: '案件台帳', aliases: ['project ledger'], description: '案件ごとの契約、売上、進捗、採算を一覧管理する台帳です。営業と現場と経理をつなぐ重要資産になります。' },
  { term: '顧客台帳', aliases: ['customer master'], description: '顧客情報や契約状況をまとめた基礎台帳です。営業、請求、サポートなど多くの業務の起点になります。' },
  { term: 'ベンダー台帳', aliases: ['vendor master'], description: '取引先ベンダーの情報、契約、評価などを管理する台帳です。委託先管理や購買統制に役立ちます。' },
  { term: '保守更新', aliases: ['maintenance renewal'], description: '保守契約やサポート契約を継続更新することです。切れると障害時に大きな支障が出ることがあります。' },
  { term: 'ライセンス更新', aliases: ['license renewal'], description: 'ソフトウェア利用権を更新することです。期限切れによる機能停止や監査指摘を防ぐ必要があります。' },
  { term: '資産管理台帳', aliases: ['asset management ledger'], description: 'ハードウェア、ソフトウェア、クラウド資源などを一覧管理する台帳です。費用管理と統制の基盤になります。' },
  { term: '構成品目', aliases: ['configuration item'], description: 'システムや資産を構成する個々の要素です。構成管理では、この単位をどう定義するかが重要です。' },
  { term: 'CMDB', aliases: ['cmdb'], description: '構成管理データベースの略で、資産と関係性を管理する基盤です。障害影響や変更影響の把握に役立ちます。' },
  { term: 'サービス資産', aliases: ['service asset'], description: 'システム、文書、人材、契約など、サービス提供に必要な資産全体です。物理資産だけでなく無形要素も含まれます。' },
  { term: '事業継続要件', aliases: ['business continuity requirement'], description: '業務を止めないために必要な条件です。RTOやRPOだけでなく、代替手順や人員確保も含みます。' },
  { term: '重要業務識別', aliases: ['critical business identification'], description: '何が止まると最も困る業務かを見極めることです。BCPや優先復旧順序の前提になります。' },
  { term: '復旧優先順位', aliases: ['recovery priority'], description: '障害時にどこから戻すかの順番です。全部同時に戻すより、重要業務優先が現実的です。' },
  { term: '組織体制図', aliases: ['organizational structure chart'], description: '組織と役割、指揮系統を図で表したものです。承認経路や責任分担の理解に役立ちます。' },
  { term: '経営レポートライン', aliases: ['management reporting line'], description: '誰が誰へ報告責任を持つかの系統です。障害報告や案件エスカレーションでも重要です。' },
  { term: '業務基盤整備', aliases: ['business infrastructure development'], description: '個別システムではなく、組織全体の業務を支える基盤を整えることです。台帳、ワークフロー、契約、会計、知識管理がつながると、全体最適が進みやすくなります。' },
  { term: 'データ移行定義', description: '旧システムから新システムへどのデータをどう移すか定義したものです。マッピング、変換、除外条件が重要です。' },
  { term: '移行対象一覧', description: '移行するデータ、文書、設定、資産を一覧化した資料です。範囲漏れ防止に役立ちます。' },
  { term: '移行方針', description: '一括移行か段階移行かなど、移行の基本考え方です。移行リスクと業務影響を左右します。' },
  { term: '切替手順', description: '新旧システムを切り替えるための具体手順です。リハーサルを前提に作ることが重要です。' },
  { term: '切戻手順書', description: '問題発生時に旧状態へ戻すための手順書です。実際に戻せるかまで確認しておく必要があります。' },
  { term: 'リハーサル計画', description: '移行や切替の事前訓練をどう行うか定めた計画です。本番前に弱い部分を見つける機会になります。' },
  { term: 'カットオーバー手順', aliases: ['cutover procedure'], description: '旧システムと新システムを切り替えるための具体的な手順です。リハーサルを想定して作成することが重要です。' },
  { term: 'カットバック手順書', aliases: ['cutback procedure document'], description: 'システム切り替え時に問題が発生した場合に元の状態へ戻すための手順書です。実際にロールバックできることの確認が必要です。' },
  { term: 'インターフェース', description: '他システムとのデータ授受や連携方法を定めた接続仕様。' },
  { term: 'authors.txt', description: 'git-svnでSVNのユーザー名をGitの著者情報に対応付けるためのマッピングファイル。' },
  { term: 'エンタープライズ製品互換性', aliases: ['enterprise product compatibility'], description: '企業向け製品間の互換性・相互運用性を示す指標です。異なるベンダー製品やバージョン間でのデータ交換や共同動作を保証します。' },
  { term: '同時接続ユーザー数', description: '同じ時点で同時に接続している利用者数です。' },
  { term: 'SaaS連携', aliases: ['saas連携'], description: '外部のSaaSとデータや処理を連携することです。' },
  { term: '並行稼働', description: '旧環境と新環境を同時に動かして比較や移行を行う状態です。' },
  { term: '切戻し', description: '切替後に問題があれば元の状態へ戻すことです。' },
  { term: '本番切替', description: '新しい環境や構成を本番利用へ切り替える作業です。' },
  { term: '外部API通信', aliases: ['外部api通信'], description: '自システムの外にあるサービスとAPI経由でデータや処理をやり取りすることです。' },
  { term: 'IF仕様', aliases: ['if仕様'], description: 'Interface仕様の略で、他システムとのデータ連携方法や項目、形式、タイミングなどを定めた仕様です。' },
  { term: '材料発注DXシステム', aliases: ['材料発注dxシステム'], description: '現場からの材料発注をデジタル化し、履歴蓄積や購買計画につなげるためのシステムです。' },
  { term: '発注履歴', description: 'いつ、何を、どこへ、どれだけ発注したかの記録です。分析や再発注防止に役立ちます。' },
  { term: '購買計画', description: '必要な資材や商品を、いつ、どのくらい、どの条件で調達するかを計画することです。' },
  { term: 'マスタ管理最適化', description: '品目や取引先などの基礎データを、正確かつ効率的に管理できるよう見直すことです。' },
  { term: 'グローバルERP', aliases: ['グローバルerp'], description: '海外拠点を含めて利用される企業基幹システムです。会計、購買、在庫などの基幹業務を統合管理します。' },
  { term: '品目マスタ', description: '商品や部材などの基本情報をまとめた基礎データです。名称、コード、分類、単位などが含まれます。' },
  { term: 'マスタ管理支援システム', description: 'マスタデータの登録・修正・確認を効率化し、精度向上や運用負荷軽減を支援するシステムです。' },
];
