// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: networkHttp (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // network (158)
  { term: 'ネットワーク', aliases: ['network'], description: 'コンピューター同士をつなぎ、通信できるようにする仕組みです。クラウド設計でも、アプリだけでなく通信経路の設計が非常に重要です。' },
  { term: 'IPアドレス', aliases: ['ipアドレス', 'ip address'], description: 'ネットワーク上で機器を識別するための番号です。住所のような役割を持ち、通信の基礎になります。' },
  { term: 'DNS', aliases: ['dns'], description: 'ドメイン名とIPアドレスを対応付ける仕組みです。利用者は名前でアクセスし、裏側ではDNSが行き先を解決しています。' },
  { term: 'ポート', aliases: ['port'], description: '同じサーバー内でどのサービスに接続するかを識別する番号です。ネットワーク設計やセキュリティ設定で必ず出てきます。' },
  { term: 'VPC', aliases: ['vpc'], description: 'クラウド上で論理的に分離されたネットワーク空間です。システムごとに安全な通信範囲を設計する土台になります。' },
  { term: 'VPN', aliases: ['vpn'], description: '離れた拠点や端末を安全に接続するための仮想的な専用線です。社内環境とクラウドをつなぐときにも使われます。' },
  { term: 'Nuxt', aliases: ['nuxt'], description: 'VueベースでSSRやルーティング機能を提供するフレームワークです。Vueを中心に本格的なWebアプリを作る際の有力候補です。' },
  { term: 'ロングポーリング', description: '新情報が来るまで接続を保ち、来たら返す通信方法です。古い構成でも使いやすい反面、効率では新しい方式に劣る場合があります。' },
  { term: 'ルーティング定義', description: 'どのURLやメソッドが、どの処理に対応するかを定めるものです。API設計の入口として非常に重要です。' },
  { term: 'HSTS', aliases: ['hsts'], description: '常にHTTPSで接続させるようブラウザへ指示する仕組みです。平文通信へのダウングレードを防ぐ効果があります。' },
  { term: '封じ込め', description: '被害拡大を防ぐために通信遮断やアカウント停止などを行うことです。原因究明より前に優先されることもあります。' },
  { term: 'ネットワークACL', aliases: ['ネットワークacl'], description: 'サブネット単位で通信制御する仕組みです。セキュリティグループとの役割分担を理解すると設計しやすくなります。' },
  { term: 'イングレス', description: '外部から内側への通信経路やルールを指すことがあります。Web公開やロードバランサー設定でよく出てきます。' },
  { term: 'エグレス', description: '内側から外部への通信です。外に出る通信も制御対象として考えると、情報漏えい対策が強くなります。' },
  { term: '帯域', description: '一定時間に流せるデータ量の大きさです。大量ファイル転送や高頻度APIでは、CPU以上に帯域がボトルネックになることがあります。' },
  { term: 'パケットロス', description: '通信データの一部が途中で失われることです。断続的な遅延や再送増加の原因になり、見えにくい不具合を生むことがあります。' },
  { term: 'プロトコル変換', description: '片方の通信方式を別の方式へ変換することです。古いシステムと新しいシステムをつなぐときに必要になることがあります。' },
  { term: '閉域網', description: 'インターネットから分離または制限された専用ネットワーク。' },
  { term: 'ドメイン名', description: 'インターネット上のアドレスを人間が読みやすい文字列で表したもの。「example.com」のような形式。DNSによってIPアドレスに変換される。' },
  { term: 'HTTP', aliases: ['http', 'hypertext transfer protocol'], description: 'HyperText Transfer Protocolの略。WebブラウザとWebサーバーがデータをやりとりするためのプロトコル。URLが「http://」で始まるサイトで使われている。' },
  { term: 'HTTPS', aliases: ['https', 'http secure'], description: 'HTTPにSSL/TLS暗号化を加えた安全な通信プロトコル。URLが「https://」で始まる。個人情報やパスワードを送受信するサイトでは必須。ブラウザに鍵マークが表示される。' },
  { term: 'TCP/IP', aliases: ['tcp/ip', 'tcp', 'ip'], description: 'インターネット通信の基本となる2つのプロトコルの組み合わせ。TCP（信頼性のある通信）とIP（アドレス指定）が組み合わさって、インターネットの土台を作っている。' },
  { term: 'ルーター', aliases: ['router'], description: 'ネットワーク間でデータを転送する機器。家庭や会社のインターネット接続に使われ、データを正しい宛先に届ける「道案内」の役割を持つ。' },
  { term: 'スイッチ', aliases: ['network switch', 'lanスイッチ', 'switching hub'], description: '同じネットワーク内の複数の機器を接続する機器。データを必要なポートだけに送ることで効率的な通信を実現する。LANスイッチとも呼ぶ。' },
  { term: 'ポート番号', aliases: ['port number'], description: 'コンピューター上で複数の通信を区別するための番号。Webは80番（HTTP）や443番（HTTPS）、メールは25番など、サービスごとに番号が決まっている。' },
  { term: 'パケット', aliases: ['packet'], description: 'ネットワーク上でデータを送受信するときの小さな単位。大きなデータを複数のパケットに分割して送り、受信側で組み立て直す。手紙を複数の封筒に分けて送るイメージ。' },
  { term: 'プロトコル', aliases: ['protocol'], description: 'コンピューター同士が通信するための取り決め・規則。話す言語を合わせるように、通信する機器が同じプロトコルに従うことでデータをやりとりできる。' },
  { term: 'LAN', aliases: ['lan', 'local area network', 'ローカルエリアネットワーク'], description: 'Local Area Networkの略。会社や家庭など限られた範囲内のネットワーク。有線LANと無線LAN（Wi-Fi）がある。インターネットに接続するためにはルーターが必要。' },
  { term: 'WAN', aliases: ['wan', 'wide area network', '広域エリアネットワーク'], description: 'Wide Area Networkの型。地理的に離れた場所のネットワーク同士を接続した広域ネットワーク。インターネット自体がWANの一つ。企業の拠点間接続にも使われる。' },
  { term: '帯域幅', aliases: ['bandwidth', 'バンド幅'], description: 'ネットワークで一度に転送できるデータ量の上限。道路の車線数に例えられる。帯域幅が広いほど速く大量のデータを転送できる。単位はbps（ビット毎秒）。' },
  { term: 'OSI参照モデル', aliases: ['osi参照モデル'], description: 'ネットワーク通信を7層に分けて定義したISO標準モデル。各層が独立した役割を担う。' },
  { term: 'TCP/IPモデル', aliases: ['tcp/ipモデル'], description: 'インターネットの基盤プロトコル群をアプリケーション・トランスポート・インターネット・リンクの4層で定義したモデル。' },
  { term: 'セッション層', description: 'OSI参照モデルの第5層。通信セッションの確立・維持・終了を管理する。' },
  { term: 'トランスポート層', description: 'OSI参照モデルの第4層。エンドツーエンドの信頼性ある通信（TCP）や軽量通信（UDP）を提供する。' },
  { term: 'ネットワーク層', description: 'OSI参照モデルの第3層。IPアドレスを用いたルーティングとパケット転送を担う。' },
  { term: 'データリンク層', description: 'OSI参照モデルの第2層。MACアドレスを用いた同一ネットワーク内の通信とエラー検出を担う。' },
  { term: '物理層', description: 'OSI参照モデルの第1層。電気信号・光信号・無線などの物理的な伝送を担う。' },
  { term: 'プロトコルスタック', description: '複数の通信プロトコルを階層的に組み合わせた実装の集合体。TCP/IPスタックが代表例。' },
  { term: 'Ethernet', aliases: ['ethernet'], description: 'IEEE 802.3で規格化されたLAN技術。MACアドレスを用いてフレームをやり取りする。' },
  { term: 'MACアドレス', aliases: ['macアドレス'], description: 'ネットワークインターフェースに割り当てられた48ビットのハードウェアアドレス。' },
  { term: 'L2スイッチ', aliases: ['l2スイッチ'], description: 'MACアドレステーブルをもとにフレームを転送するデータリンク層のネットワーク機器。' },
  { term: 'フラッディング', description: 'L2スイッチが宛先MACアドレスを学習していない場合にすべてのポートへフレームを送出する動作。' },
  { term: 'Spanning Tree Protocol', aliases: ['spanning tree protocol', 'stp'], description: 'L2ネットワークのループを防ぎ冗長パスを論理的にブロックするプロトコル（IEEE 802.1D）。' },
  { term: 'ルートブリッジ', description: 'Spanning Tree Protocolでネットワークの基準点となるスイッチ。最小のブリッジIDが選ばれる。' },
  { term: 'ブロックポート', description: 'Spanning Tree Protocolでループ防止のために通信を遮断しているポート。' },
  { term: 'VLAN', aliases: ['vlan'], description: 'Virtual LANの略。物理的なネットワークを論理的に分割する技術。セキュリティと管理性を向上させる。' },
  { term: 'スタティックVLAN', aliases: ['スタティックvlan'], description: '管理者がスイッチポートに手動でVLANを割り当てる方式。' },
  { term: 'ダイナミックVLAN', aliases: ['ダイナミックvlan'], description: '接続端末のMACアドレスや認証情報をもとに自動的にVLANを割り当てる方式。' },
  { term: 'グローバルIPアドレス', aliases: ['グローバルipアドレス'], description: 'インターネット上で一意に識別できるIPアドレス。ISPから割り当てられる。' },
  { term: 'プライベートIPアドレス', aliases: ['プライベートipアドレス'], description: '組織内のプライベートネットワークで使用するIPアドレス。10.x・172.16.x・192.168.xの範囲。' },
  { term: 'L3スイッチ', aliases: ['l3スイッチ'], description: 'IPアドレスに基づいたルーティング機能を持つスイッチ。ルータとL2スイッチの機能を統合した機器。' },
  { term: 'ルータ', description: '異なるネットワーク間でパケットをルーティングするネットワーク機器。' },
  { term: 'ARPテーブル', aliases: ['arpテーブル'], description: 'IPアドレスとMACアドレスの対応を記録したテーブル。ARP（Address Resolution Protocol）で更新される。' },
  { term: 'ルーティングテーブル', description: 'ルータがパケットを転送する際に参照するネットワーク宛先と次ホップのマッピング表。' },
  { term: 'スタティックルーティング', description: '管理者が手動でルーティングテーブルを設定する方式。シンプルだが変化に弱い。' },
  { term: 'ダイナミックルーティング', description: 'ルーティングプロトコル（OSPF・BGPなど）を使ってルーティングテーブルを自動更新する方式。' },
  { term: 'L7スイッチ', aliases: ['l7スイッチ'], description: 'HTTPヘッダ・URLなどアプリケーション層の情報を基に通信を振り分けるスイッチ。ロードバランサとも呼ばれる。' },
  { term: 'ADC', aliases: ['adc'], description: 'Application Delivery Controllerの略。L7スイッチ機能を持ちアプリケーション配信を最適化する機器。' },
  { term: 'リバースプロキシ', description: 'クライアントとサーバの間でサーバ側に代理動作するプロキシ。SSLオフロード・ロードバランシング・キャッシュを提供する。' },
  { term: 'ロードバランシング', description: '複数サーバに負荷を分散してシステムの可用性と性能を向上させる技術。' },
  { term: 'nmcli', description: 'NetworkManagerをコマンドラインから操作するツール。ネットワーク接続の作成・変更・削除をスクリプトからも扱いやすい形式で提供する。' },
  { term: 'nmtui', description: 'NetworkManagerのTUIベース（テキストUI）設定ツール。コンソール環境でグラフィカルに近い感覚でネットワーク設定を行える。' },
  { term: 'NetworkManager', aliases: ['networkmanager'], description: 'Linuxシステムのネットワーク接続を自動管理するデーモン。有線・無線・VPN・ブリッジなど多様な接続タイプを統合管理する。' },
  { term: 'ボンディング', aliases: ['bonding', 'nicボンディング', 'link aggregation'], description: '複数のネットワークインターフェースを束ねて帯域幅増加や冗長化を実現するLinuxの機能。アクティブ-バックアップなど複数モードがある。' },
  { term: 'チーミング', aliases: ['teaming', 'nicチーミング'], description: 'ボンディングのより新しい代替として導入されたLinuxのNIC束ね技術。libteamdを使用してボンディングより柔軟な設定が可能。' },
  { term: 'VLAN設定', aliases: ['vlan設定', '仮想lan設定'], description: '1つの物理ネットワークインターフェース上に複数の仮想LAN（VLAN）を設定する構成。8021qカーネルモジュールを使用しVLAN IDでトラフィックを分離する。' },
  { term: 'ss', aliases: ['socket statistics'], description: 'ソケット統計情報を表示するコマンド。netstatの後継として設計され高速で詳細なTCP/UDPソケット・UNIXソケットの一覧を表示できる。' },
  { term: 'tcpdump', description: 'ネットワークパケットをキャプチャして表示するコマンドラインツール。フィルタ条件でパケットを絞り込み、ファイルへの保存もできる。' },
  { term: 'nmap', aliases: ['network mapper'], description: 'ネットワークのホスト発見とポートスキャンを行うセキュリティツール。開いているポート、OS情報、サービスバージョンなどを調査できる。' },
  { term: 'traceroute', aliases: ['tracert'], description: 'パケットがターゲットホストに到達するまでの経路（ルーター）を表示するネットワーク診断コマンド。各ホップのIPアドレスと遅延時間を確認できる。' },
  { term: 'iptables', description: 'Linuxカーネルのnetfilterフレームワークを操作するファイアウォール・パケットフィルタリングコマンド。テーブルとチェーンでパケットルールを管理する。' },
  { term: 'nftables', description: 'iptablesの後継として開発されたLinuxのパケットフィルタリングフレームワーク。より統一された構文と高性能が特徴で、RHEL 8以降で採用。' },
  { term: 'firewalld', description: 'RHEL/CentOS系で使用されるゾーンベースのダイナミックファイアウォール管理デーモン。nftablesまたはiptablesのフロントエンドとして動作する。' },
  { term: 'ファイアウォールゾーン', aliases: ['firewall zone'], description: 'firewalldにおけるネットワーク信頼レベルの区分。public、trusted、internal、dmzなど定義済みゾーンにインターフェースを割り当ててルールを適用する。' },
  { term: 'UDP', aliases: ['udp', 'user datagram protocol'], description: 'コネクションレス型のトランスポートプロトコル。信頼性や順序保証はないが、ヘッダが小さくオーバーヘッドが低いため、リアルタイム通信（音声・動画）やDNS、QUICなどの基盤として使われる。' },
  { term: 'HTTP/1.1', aliases: ['http/1.1', 'hypertext transfer protocol 1.1'], description: '1997年に標準化されたHTTPのバージョン。Keep-Aliveによるコネクション再利用、チャンク転送エンコーディング、ホストヘッダ必須化などを導入した。1コネクションで1リクエストしか同時に処理できないHead-of-Line Blockingが課題だった。' },
  { term: 'QUIC', aliases: ['quic', 'quick udp internet connections'], description: 'Googleが開発しRFC9000で標準化されたUDPベースのトランスポートプロトコル。TCPとTLSの機能を統合し、接続確立を1-RTTまたは0-RTTで完了できる。HTTP/3の基盤として採用されており、モバイル環境でのネットワーク切り替えにも強い。' },
  { term: 'TLS', aliases: ['tls', 'transport layer security', 'ssl/tls'], description: '【ネットワーク】通信の暗号化・認証・完全性保護を提供するプロトコル。SSLの後継で、現在はTLS 1.2とTLS 1.3が主流。HTTPSやSMTPS、IMAPSなど多くのプロトコルの安全な通信基盤として使われる。 【OCI APEX】通信を暗号化する標準プロトコル。' },
  { term: 'TLS 1.3', aliases: ['tls 1.3', 'rfc 8446'], description: '2018年に標準化されたTLSの最新メジャーバージョン。ハンドシェイクを1-RTTに短縮し、0-RTT再開も可能。古い暗号アルゴリズムを廃止してセキュリティを強化し、前方秘匿性を必須とした。TLS 1.0/1.1は非推奨とされている。' },
  { term: 'X.509', aliases: ['x.509', 'x.509証明書', 'pki証明書'], description: 'ITU-Tが標準化したデジタル証明書のフォーマット。公開鍵・サブジェクト・有効期限・発行CAの署名などを含み、TLSやコードサイニングなど幅広く使われるPKIの基盤。PEMやDER形式でエンコードされる。' },
  { term: 'CA', aliases: ['ca', 'certificate authority', '認証局'], description: '【ネットワーク】デジタル証明書を発行・管理する信頼された第三者機関。ルートCA・中間CAの階層構造を持ち、クライアントはOSやブラウザに組み込まれたルートCAを信頼の起点とする。証明書の失効管理もCAの責務。 【OCI APEX】証明書を発行署名する認証局。' },
  { term: 'Let\'s Encrypt', aliases: ['let\'s encrypt', 'isrg', '無料ssl'], description: '非営利団体ISRGが運営する無料の自動化されたCA。ACMEプロトコルを使って証明書発行・更新を自動化でき、90日間有効な証明書を無料で取得できる。HTTPSの普及に大きく貢献した。' },
  { term: 'OCSP', aliases: ['ocsp', 'online certificate status protocol'], description: '証明書の失効状態をリアルタイムで確認するプロトコル。CAのOCSPレスポンダにクエリを送り、証明書が有効か失効かを確認する。OCSP Staplingにより、サーバが事前にOCSP応答をキャッシュしてクライアントに提供できる。' },
  { term: 'CRL', aliases: ['crl', 'certificate revocation list', '証明書失効リスト'], description: 'CAが失効させた証明書のシリアル番号を一覧にしたリスト。定期的に公開・配布され、クライアントはTLS接続時にCRLを参照して証明書の有効性を確認する。OCSPに比べてリアルタイム性に劣るが、オフラインでも参照可能。' },
  { term: '証明書チェーン', aliases: ['certificate chain', '証明書の連鎖'], description: 'エンドエンティティ証明書から中間CA、ルートCAまでの証明書の連鎖。各証明書は上位CAの署名で信頼を継承する。TLSハンドシェイク時にサーバが証明書チェーンを送り、クライアントが信頼できるルートCAまで検証する。' },
  { term: 'SNI', aliases: ['sni', 'server name indication'], description: 'TLSハンドシェイクのClientHelloにホスト名を含める拡張。1つのIPアドレスで複数のドメインの証明書を使い分けるために使われる。ほぼ全モダンブラウザが対応しており、共有ホスティング環境でHTTPSを実現する基盤技術。' },
  { term: 'ALPN', aliases: ['alpn', 'application-layer protocol negotiation'], description: 'TLSハンドシェイク時にアプリケーション層プロトコルを交渉するTLS拡張。クライアントとサーバがHTTP/2やHTTP/3などを選択する際に使われ、プロトコルのネゴシエーションを追加ラウンドトリップなしに実現できる。' },
  { term: 'TLSハンドシェイク', aliases: ['tlsハンドシェイク', 'tls handshake'], description: 'TLS接続確立時に行われる暗号パラメータのネゴシエーション手順。クライアントとサーバが暗号スイートを選択し、証明書を交換して認証を行い、セッション鍵を安全に共有する。TLS 1.3では1-RTTで完了する。' },
  { term: 'STUN', aliases: ['stun', 'session traversal utilities for nat'], description: 'NATの外側から見たクライアントのパブリックIPアドレスとポートを調べるためのプロトコル。WebRTCのICEフレームワークで利用され、P2P接続の候補アドレス収集に使う。STUNサーバはシンプルでリレーは行わない。' },
  { term: 'TURN', aliases: ['turn', 'traversal using relays around nat'], description: '直接P2P接続できない場合にトラフィックをリレーするNAT越えプロトコル。STUNで解決できない対称NAT環境などで使われる。WebRTCのフォールバック手段として重要だが、リレーサーバのコストが高い。' },
  { term: 'ICE', aliases: ['ice', 'interactive connectivity establishment'], description: 'WebRTCでP2P接続を確立するためのフレームワーク。STUN・TURN候補を収集しSDPで交換し、優先度順に接続を試みる。ホスト候補・サーバリフレクシブ候補・リレー候補の3種を扱い最適なパスを選択する。' },
  { term: 'SDP', aliases: ['sdp', 'session description protocol'], description: 'WebRTCや音声・映像セッションのメディア情報（コーデック、IPアドレス、ポートなど）を記述するテキスト形式のプロトコル。WebRTCではOfferとAnswerの交換（シグナリング）に使われ、ICE候補もSDPに含まれる。' },
  { term: 'NAT traversal', aliases: ['nat traversal', 'natトラバーサル'], description: 'NATルータの内側にいるノード同士がP2P通信を確立するための技術群。STUN・TURN・ICE・UDPホールパンチングなどが含まれる。WebRTCやVoIPで不可欠な技術で、NAT種別（フルコーン・対称型など）によって難易度が異なる。' },
  { term: 'DHCP', aliases: ['dhcp', 'dynamic host configuration protocol'], description: 'ネットワークに接続したホストにIPアドレス・サブネットマスク・デフォルトゲートウェイ・DNSサーバを動的に割り当てるプロトコル。DISCOVER→OFFER→REQUEST→ACKの4ステップで動作し、リース期間で管理する。' },
  { term: 'ARP', aliases: ['arp', 'address resolution protocol'], description: 'IPアドレスからMACアドレスを解決するリンク層プロトコル。送信ホストはブロードキャストでARP Requestを送り、対象ホストがUnicastでARP Replyを返す。結果はARPキャッシュに保存される。ARP Poisoningはセキュリティ攻撃に悪用される。' },
  { term: 'ICMP', aliases: ['icmp', 'internet control message protocol'], description: 'ネットワーク診断やエラー報告のためのIPプロトコル上の制御プロトコル。pingはICMP Echo Request/Replyを使い、tracerouteはICMP Time Exceededを利用する。ICMPv6はIPv6で近隣探索にも使われる。' },
  { term: 'ping', description: 'ICMP Echo RequestとEcho Replyを使って、ホストの到達可能性とラウンドトリップ時間を計測するネットワーク診断コマンド。最も基本的なネットワーク疎通確認手段で、パケットロス率やRTTの統計も表示する。' },
  { term: 'MTU', aliases: ['mtu', 'maximum transmission unit', '最大転送単位'], description: 'ネットワークインターフェースが1フレームで送信できる最大データサイズ。イーサネットの標準MTUは1500バイト。MTUを超えるパケットはIPフラグメンテーションされるか、DF（Don\'t Fragment）ビットが立っている場合は破棄される。' },
  { term: 'TCP輻輳制御', aliases: ['tcp輻輳制御', 'tcp congestion control'], description: 'TCPがネットワークの輻輳を検出して送信レートを自動調整するメカニズム。スロースタート・輻輳回避・高速再転送・高速回復のフェーズがあり、CUBICやBBRなどのアルゴリズムで実装される。' },
  { term: 'TCPウィンドウ', aliases: ['tcpウィンドウ', 'tcp window', '受信ウィンドウ', '送信ウィンドウ'], description: 'TCPの受信バッファサイズを示す値。受信側が確認応答なしに受け入れられるデータ量を制御し、フロー制御に使われる。ウィンドウスケーリング拡張によりサイズを65535バイト以上に拡大できる。' },
  { term: 'Nagleアルゴリズム', aliases: ['nagleアルゴリズム', 'nagle\'s algorithm'], description: '小さなTCPパケットを結合して送信効率を上げるアルゴリズム。未確認応答データがある間は小パケットを蓄積してから送信する。インタラクティブアプリ（SSH、ゲームなど）ではTCP_NODELAYで無効化することが多い。' },
  { term: 'TCP Keep-Alive', aliases: ['tcp keep-alive', 'tcpキープアライブ'], description: 'アイドル状態のTCP接続が生きているかを確認する仕組み。一定時間データがない場合にプローブパケットを送り、応答がなければ接続を切断する。NAT経路のタイムアウトを防いだりゾンビ接続を検出するために使われる。' },
  { term: 'SO_REUSEPORT', aliases: ['so_reuseport', 'so_reuseaddr'], description: '複数のソケットを同じポートにバインドできるソケットオプション。マルチプロセス・マルチスレッドサーバで各ワーカーが同じポートをリッスンしてカーネルレベルで負荷分散できる。Linuxのnginxやnodejsのクラスタモードで使われる。' },
  { term: 'epoll', description: 'Linuxのスケーラブルなイベント通知インターフェース。監視するファイルディスクリプタをカーネルに登録しておき、準備完了イベントのみを効率的に取得できる。select/pollと異なりO(1)でイベント通知でき、大規模接続サーバの基盤となる。' },
  { term: 'kqueue', description: 'BSD系OS（macOS、FreeBSDなど）のスケーラブルなカーネルイベント通知機構。ファイルディスクリプタの読み書き・タイマー・プロセスイベントなどを統一的に監視できる。LinuxのepollやWindowsのIOCPに相当する。' },
  { term: 'io_uring', description: 'Linux 5.1で導入されたカーネルとユーザ空間の間でリングバッファを共有する非同期I/Oインターフェース。システムコールのオーバーヘッドを削減し、ネットワーク・ディスクI/Oを高スループットで処理できる。epollより低レイテンシ。' },
  { term: 'select/poll', aliases: ['selectシステムコール', 'pollシステムコール'], description: 'POSIX標準の同期的な多重化I/Oシステムコール。複数のファイルディスクリプタを一括監視し、いずれかが準備完了になったら返る。selectはFD_SETSIZEの制限があり、pollはそれを解消するが、どちらもO(n)のスキャンが必要でスケールしにくい。' },
  { term: '非同期I/O', aliases: ['非同期i/o', 'asynchronous i/o', 'aio'], description: 'I/O操作の完了を待たずに他の処理を続け、完了時にコールバックやイベントで通知を受けるI/Oモデル。Node.jsのイベントループやPythonのasyncio、Rustのtokioなどが非同期I/Oを活用して高スループットなサーバを実現する。' },
  { term: 'マルチプレクシング', aliases: ['multiplexing', '多重化'], description: '1つの通信路で複数の独立したデータストリームを同時に送受信する技術。HTTP/2は1TCP接続上で複数ストリームを多重化し、HTTP/1.1のリクエストキューイングによる遅延を解消する。TDM・FDM・OFDM等の方式がある。' },
  { term: 'HTTP/2フレーム', aliases: ['http/2フレーム', 'http/2 frame'], description: 'HTTP/2通信の最小単位。DATAフレーム（ボディ）、HEADERSフレーム（ヘッダ）、SETTINGSフレーム（設定交換）、WINDOW_UPDATEフレームなど10種類以上が定義されている。各フレームはストリームIDで多重化される。' },
  { term: 'HTTP/2ストリーム', aliases: ['http/2ストリーム', 'http/2 stream'], description: 'HTTP/2接続内の独立した双方向バイトシーケンス。各ストリームは整数のIDを持ち、HEADERSとDATAフレームで構成される。1接続内で並行して複数のリクエスト/レスポンスを処理でき、優先度（Priority）も設定可能。' },
  { term: 'Server Push', aliases: ['server push', 'http/2 server push'], description: 'HTTP/2でサーバがクライアントのリクエストを待たずにリソースをプッシュする機能。HTMLレスポンスと同時にCSSやJSをプッシュすることでラウンドトリップを削減できるが、キャッシュ済みリソースの無駄送信が問題となりHTTP/3で廃止の方向。' },
  { term: 'HPACK', aliases: ['hpack', 'http/2 header compression'], description: 'HTTP/2で使われるヘッダ圧縮仕様（RFC 7541）。静的テーブル（共通ヘッダの定義済み一覧）と動的テーブルを組み合わせてヘッダをインデックス参照し、ハフマン符号化も使って圧縮する。HTTP/3ではQPACKに進化した。' },
  { term: 'gzip圧縮', aliases: ['deflate圧縮'], description: 'DEFLATEアルゴリズムを使ったデータ圧縮形式。HTTPレスポンスのContent-Encoding: gzipとして広く使われ、テキストコンテンツを70-90%圧縮できる。ブラウザはAccept-Encodingヘッダで対応を宣言し、サーバが圧縮して送信する。' },
  { term: 'Content-Encoding', aliases: ['content-encoding', 'コンテンツエンコーディング'], description: 'HTTPレスポンスボディに適用されたエンコーディング（圧縮）を示すヘッダ。gzip・br（Brotli）・deflate・zstdなどの値をとる。クライアントはAccept-Encodingで対応エンコーディングを通知し、デコード後にボディを処理する。' },
  { term: 'Transfer-Encoding', aliases: ['transfer-encoding', '転送エンコーディング'], description: 'HTTPメッセージのボディをネットワーク越しに転送する際のエンコーディング形式を指定するヘッダ。chunkedが最もよく使われ、ボディを複数チャンクに分割してサイズ不明のままストリーム送信できる。Content-Encodingとは異なりホップバイホップのヘッダ。' },
  { term: 'chunked encoding', aliases: ['チャンク転送'], description: 'HTTPでレスポンスボディを可変長のチャンクに分割して送信するエンコーディング。コンテンツ全体のサイズが事前にわからない場合（動的生成、ストリーミングなど）に使われる。各チャンクにはサイズが付き、空チャンクで終端を示す。' },
  { term: 'Range Request', aliases: ['range request', 'レンジリクエスト', '部分取得', 'http range'], description: 'HTTPでリソースの一部分のみを取得するリクエスト。RangeヘッダでバイトレンジをしてHTTP 206 Partial Contentが返る。大容量ファイルのダウンロード再開、動画のシーク、並列ダウンロードなどに使われる。' },
  { term: '304 Not Modified', aliases: ['304 not modified', 'httpキャッシュ検証'], description: 'HTTPの条件付きリクエスト（If-None-Match・If-Modified-Since）でリソースが変更されていない場合に返るステータスコード。ボディなしで返り、クライアントはキャッシュを再利用する。帯域節約とレスポンス高速化に貢献する。' },
  { term: 'リダイレクト', aliases: ['httpリダイレクト', '301/302/307/308'], description: 'HTTPでクライアントを別のURLに転送するレスポンス群。301（恒久移動）・302（一時移動）・307（一時リダイレクト、メソッド保持）・308（恒久リダイレクト、メソッド保持）の種類があり、SEOや正規URL統一に使われる。' },
  { term: 'フォワードプロキシ', aliases: ['forward proxy', '透過プロキシ'], description: 'クライアントの代わりにインターネットへリクエストを送るプロキシ。クライアントIPを隠したり、企業ネットワークでの通信制御・キャッシュ・ログ取得に使われる。クライアント側で設定が必要な明示プロキシと、設定不要の透過プロキシがある。' },
  { term: 'SOCKS', aliases: ['socks', 'socks5', 'socks4'], description: '任意のTCP/UDP接続をプロキシ経由でルーティングするプロキシプロトコル。SOCKS5は認証とUDPをサポートし、HTTPプロキシより汎用的。SSH動的転送やTorがSOCKSプロトコルを使って通信を中継する。' },
  { term: 'TCP三方向ハンドシェイク', aliases: ['tcp三方向ハンドシェイク', 'tcp 3-way handshake', 'syn-syn/ack-ack'], description: 'TCP接続確立のプロセス。クライアントがSYNを送り、サーバがSYN/ACKで応答し、クライアントがACKを返して接続が確立する。この3ステップに1RTTかかるため、TLS 1.3やQUICではこのオーバーヘッドを削減する仕組みが導入された。' },
  { term: 'TCPフラグ', aliases: ['tcpフラグ', 'tcp flags', 'syn/ack/fin/rst'], description: 'TCPセグメントのコントロールビット群。SYN（接続開始）、ACK（確認応答）、FIN（接続終了）、RST（接続リセット）、PSH（即時転送）、URG（緊急）などがあり、接続状態のフェーズ制御に使われる。' },
  { term: 'TCPシーケンス番号', aliases: ['tcpシーケンス番号', 'tcp sequence number'], description: 'TCPセグメントのデータバイト位置を示す32ビットの番号。受信側はシーケンス番号を使ってパケットの順序を復元し、欠落を検出する。初期シーケンス番号（ISN）はランダム値から始まり、TCPスプーフィング攻撃を防ぐ。' },
  { term: 'TCP確認応答', aliases: ['tcp確認応答', 'tcp ack', 'tcp acknowledgment'], description: 'TCPで受信したデータバイト数の累積確認を行うACKセグメント。ACK番号は次に期待するシーケンス番号を示す。遅延ACK（200ms待ってまとめてACK）はパフォーマンス最適化だが、Nagleアルゴリズムと組み合わさると遅延を引き起こすことがある。' },
  { term: '輻輳制御', aliases: ['congestion control'], description: 'ネットワーク全体の輻輳を防ぐためにTCPが送信レートを自動調整する仕組み。パケットロスや遅延増加を輻輳の兆候と見なし、輻輳ウィンドウ（CWND）を削減する。CUBIC・BBR・VENOなど多くのアルゴリズムが存在する。' },
  { term: '輻輳ウィンドウ', aliases: ['cwnd', 'congestion window'], description: 'TCP送信者が輻輳制御アルゴリズムで管理する内部的な送信制限値。受信ウィンドウとCWNDの小さい方が実際の送信ウィンドウサイズになる。パケットロスで削減され、スロースタートや輻輳回避フェーズで増加する。' },
  { term: 'スロースタート', aliases: ['slow start'], description: 'TCP接続開始時または輻輳後の輻輳ウィンドウを指数的に増加させるフェーズ。ACKを受信するたびにCWNDを1MSS増やし、閾値（ssthresh）に達するまで指数的に成長する。名前とは裏腹に急速に拡大するため大容量転送では有利。' },
  { term: '再送タイムアウト', aliases: ['retransmission timeout'], description: 'TCPがACKを受信できない場合にパケット再送を行うまでの待機時間。RTTとその分散（Jacobsonアルゴリズム）から動的に計算される。RTOが発生するとCWNDが1MSSにリセットされスロースタートから再開するため、接続品質への影響が大きい。' },
  { term: 'CUBIC', aliases: ['cubic'], description: 'LinuxカーネルのデフォルトTCP輻輳制御アルゴリズム。3次関数のウィンドウ増加カーブを使って、高帯域・高遅延ネットワーク（HBDP）でも効率的にスループットを引き出す。3重重複ACKで輻輳を検出し、ウィンドウを削減して回復する。' },
  { term: 'BBR', aliases: ['bbr', 'bottleneck bandwidth and rtt'], description: 'Googleが開発したTCP輻輳制御アルゴリズム。パケットロスではなく帯域幅とRTTの計測値を使って最適な送信レートを決定する。高帯域・高遅延・パケットロスがある環境でCUBICより優れたスループットを発揮する。' },
  { term: 'IPsec', aliases: ['ipsec', 'ip security'], description: 'IP層でパケットを暗号化・認証するプロトコルスイート。AHプロトコル（認証のみ）とESPプロトコル（暗号化+認証）があり、トンネルモードとトランスポートモードを持つ。企業VPNの基盤技術として広く使われている。' },
  { term: 'WireGuard', aliases: ['wireguard'], description: 'シンプルで高性能なオープンソースVPNプロトコル。Linuxカーネルに統合済みで、ChaCha20で暗号化しCurve25519で鍵交換する。OpenVPNやIPsecより設定が簡単でコードが少なく、セキュリティ監査がしやすい。' },
  { term: 'DTLS', aliases: ['dtls', 'datagram transport layer security'], description: 'UDPなどのデータグラムプロトコル上でTLSに相当する暗号化・認証を提供するプロトコル。WebRTCのメディア暗号化に使われるSRTPと組み合わせて利用される。パケットの並べ替えやロスを前提とした設計になっている。' },
  { term: 'SRTP', aliases: ['srtp', 'secure real-time transport protocol'], description: 'RTPに暗号化と認証を追加した安全なリアルタイム転送プロトコル。WebRTCでは音声・映像データの暗号化にSRTPが使われ、鍵交換にはDTLSが使われる。AES-128-CTRで暗号化しHMAC-SHA1で認証するのが標準的な構成。' },
  { term: 'RTP', aliases: ['rtp', 'real-time transport protocol'], description: '音声・映像データをリアルタイムでUDP上に転送するプロトコル。シーケンス番号とタイムスタンプでジッタバッファの同期に使われる。制御情報はRTCPで別に送られ、セキュリティ版はSRTPを使う。VoIPやWebRTCの基盤。' },
  { term: 'RTCP', aliases: ['rtcp', 'rtp control protocol'], description: 'RTPセッションの品質制御情報を伝えるプロトコル。パケットロス率・ジッタ・遅延などの統計をSenderReport/ReceiverReportで定期的に交換し、コーデックのビットレート適応などに使われる。RTPと同じセッションで別ポートを使う。' },
  { term: '長持続接続', aliases: ['long-lived connection', '持続的接続', 'パーシステント接続'], description: '1つのTCP接続を複数のHTTPリクエスト/レスポンスに再利用する仕組み。HTTP/1.1ではデフォルトで有効（Keep-Alive）で、接続確立のオーバーヘッドを削減する。ただし同時接続数の制限（通常6本/ドメイン）がボトルネックになる。' },
  { term: 'Keep-Aliveヘッダ', aliases: ['keep-aliveヘッダ', 'connection: keep-alive', 'keepaliveヘッダ'], description: 'HTTPの接続持続化を制御するヘッダ。HTTP/1.0ではデフォルト非持続なので明示的に指定が必要だった。HTTP/1.1ではデフォルト持続接続だがConnection: keep-aliveで明示することも多い。タイムアウトと最大リクエスト数を交渉できる。' },
  { term: 'HTTP/1.0', aliases: ['http/1.0', 'http 1.0'], description: '1996年に公開された初期のHTTP仕様（RFC 1945）。デフォルトで非持続接続（リクエストごとにTCP接続を確立・切断）で、ホストヘッダが必須でなかった。HTTP/1.1への移行で持続接続・仮想ホスト・チャンク転送が標準化された。' },
  { term: 'HTTPパイプライン', aliases: ['httpパイプライン', 'http pipelining'], description: 'HTTP/1.1でACKを待たずに複数のリクエストを連続送信する機能。Head-of-Line Blockingの問題（最初のレスポンスが遅れると後続が詰まる）があり、多くのブラウザでデフォルト無効。HTTP/2の多重化がこの問題を根本解決した。' },
  { term: '接続多重化', aliases: ['connection multiplexing', '多重化接続'], description: '1つのTCP接続上で複数の独立したリクエスト/レスポンスを同時に処理する技術。HTTP/2とHTTP/3がこれを実現し、ブラウザが1ドメインあたり6接続を張っていたHTTP/1.1の制約を解消した。HOLブロッキングの解消にも貢献する。' },
  { term: 'ドメインシャーディング', aliases: ['domain sharding'], description: 'HTTP/1.1時代に複数のサブドメインを使ってブラウザの1ドメインあたり接続数制限（通常6本）を回避するパフォーマンス最適化手法。HTTP/2では多重化により不要となり、むしろTLS接続増加でパフォーマンスが悪化する場合がある。' },
  { term: 'DNS Prefetch', aliases: ['dns prefetch', 'dns-prefetch', 'dnsプリフェッチ'], description: 'ブラウザがページ上のリンク先ドメインのDNS解決を事前に行うリソースヒント。<link rel="dns-prefetch" href="//example.com">で指定する。ユーザがリンクをクリックした際の接続遅延を削減するが、preconnectより軽量でDNS解決のみ行う。' },
  { term: 'HTTP早期ヒント', aliases: ['http早期ヒント', 'http 103 early hints', '103 early hints'], description: 'サーバが最終レスポンスを生成する前にLink: preloadヘッダを含む103ステータスを先行送信するHTTP機能。ブラウザはこのヒントを受け取り次第、CSSやJSのプリロードを開始できる。サーバサイドの処理時間を活用してページロードを高速化する。' },
  { term: 'Cookie属性', aliases: ['cookie属性', 'cookie attributes', 'クッキー属性'], description: 'HTTPクッキーの動作を制御するオプション群。Secure（HTTPS必須）・HttpOnly（JSからアクセス不可）・SameSite（クロスサイト制御）・Domain・Path・Expires/Max-Ageなどがある。適切な属性設定がXSSやCSRF対策の基本となる。' },
  { term: 'Secure Cookie', aliases: ['secure cookie', 'secureフラグ', 'secure属性'], description: 'HTTPSの暗号化通信上でのみ送信されるCookieを指定するSecure属性。平文HTTP通信ではCookieが送られないため、ネットワーク盗聴によるセッションハイジャックを防ぐ。本番環境のセッションCookieには必須の属性。' },
  { term: 'HttpOnly Cookie', aliases: ['httponly cookie', 'httponlyフラグ', 'httponly属性'], description: 'JavaScriptのdocument.cookieからアクセスできないよう保護するCookieのHttpOnly属性。XSS攻撃でスクリプトが実行されてもCookieを窃取できなくなる。セッションCookieに必ず設定すべき重要なセキュリティ属性。' },
  { term: 'XSS対策', aliases: ['xss対策', 'xss protection', 'cross-site scripting対策'], description: 'クロスサイトスクリプティング攻撃を防ぐセキュリティ施策。出力時のHTMLエスケープ、Content Security Policy（CSP）の設定、HttpOnly Cookie、入力値のサニタイズなどが含まれる。モダンフレームワークはデフォルトでエスケープ処理を行う。' },
  { term: 'CSRF対策', aliases: ['csrf対策', 'csrf protection', 'cross-site request forgery対策'], description: 'ユーザが意図しないリクエストを第三者サイトから送らせる攻撃への防御策。CSRFトークンの埋め込み・検証、SameSite Cookie属性の設定、Origin/Refererヘッダの検証が主な対策。モダンフレームワークではCSRFトークンが自動生成される。' },
  { term: 'Expect-CT', aliases: ['expect-ct', 'certificate transparency'], description: 'Certificate Transparency（CT）ログへの証明書記録を要求するHTTPヘッダ。不正発行された証明書の検出を強制し、enforce指定時はCT未記録の証明書接続をブロックする。2024年現在、ほぼ廃止方向にあり主要ブラウザはCTをデフォルト強制している。' },
  { term: 'HPKP', aliases: ['hpkp', 'http public key pinning'], description: 'サーバ証明書の公開鍵ハッシュをHTTPヘッダでブラウザに記憶させ、次回から異なる証明書を拒否させるセキュリティ機能。不正証明書によるMITM攻撃を防ぐが、設定ミスで正規サイトも接続不能になるリスクが高く、現在は非推奨・廃止方向。' },
  { term: 'Last-Modified', aliases: ['last-modified', '最終更新日時'], description: 'リソースの最終変更日時を示すHTTPレスポンスヘッダ。クライアントはIf-Modified-Sinceヘッダで条件付きリクエストを送り、変更がなければ304 Not Modifiedが返る。ETagより精度が低い（秒単位）がシンプルな実装で広く使われる。' },
  { term: 'Vary', aliases: ['vary', 'varyヘッダ'], description: 'レスポンスのキャッシュキーに含めるリクエストヘッダ名を指定するHTTPヘッダ。例えばVary: Accept-Encodingを指定するとgzip版とbr版が別々にキャッシュされる。Vary: Cookieはキャッシュ効率を著しく低下させるため注意が必要。' },
  { term: 'TCPスリーウェイハンドシェイク', aliases: ['tcpスリーウェイハンドシェイク', 'tcp three-way handshake', '3-way handshake'], description: 'TCP接続確立時にSYN・SYN-ACK・ACKの3段階のやり取りで行う接続確立プロセスです。信頼性のある通信チャネルを開設します。' },
  { term: 'ネットワーク分離', description: '通信経路や接続範囲を分けて影響や侵入を抑える設計です。' },
  { term: '全通信', description: '対象システムで発生するすべての通信です。' },
];
