// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: ociServices (2/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: 'OCI Resource Scheduler', aliases: ['oci resource scheduler', 'oracle cloud infrastructure resource scheduler'], description: 'OCI上のコンピュートインスタンスなどのリソースを時刻ベースで自動的に起動・停止するスケジューリングサービス。開発環境の夜間停止など稼働時間を制限してコストを削減するためのFinOpsツール。' },
  { term: 'OCI Vulnerability Scanning Service', aliases: ['oci vulnerability scanning service', 'oci vss'], description: 'OCI上のコンピュートインスタンスとコンテナイメージの脆弱性を定期スキャンして報告するセキュリティサービス。CVEベースの検出結果をCloud Guardと連携して管理し、推奨対処策とリスクスコアを提供する。' },
  { term: 'OCI Bastion Session', aliases: ['oci bastion session', 'bastion session'], description: 'OCI Bastionサービスが作成する時間制限付きのSSH/RDPトンネルセッション。セッションは最大3時間で自動終了し、プライベートサブネットのリソースへの安全な一時アクセスを提供して踏み台サーバーを不要にする。' },
  { term: 'OCIインフラストラクチャリソース', aliases: ['ociインフラストラクチャリソース', 'oci infrastructure resources'], description: 'OCI上で管理されるコンピュート・ストレージ・ネットワーク・データベースなどの全サービスリソースの総称。OCID（Oracle Cloud ID）で一意に識別され、コンパートメントとタグで分類・管理される。' },
  { term: 'OCI GoldenGate Trail', aliases: ['oci goldengate trail', 'goldengate trail file'], description: 'Oracle GoldenGateがソースデータベースの変更データキャプチャ（CDC）ログから抽出したトランザクションレコードを格納する中間ファイル。Trailファイルを介してソースとターゲット間の非同期レプリケーションを実現する。' },
  { term: 'OCI Integration Adapters', aliases: ['oci integration adapters', 'oic adapters'], description: 'Oracle Integration Cloud（OIC）が提供するSalesforce・SAP・ServiceNow・Twitter等のSaaS/オンプレミスアプリとの接続コンポーネント。400以上のアダプターを使いノーコードで異種システム間のデータ連携を実現する。' },
  { term: 'OCI OAC Data Sets', aliases: ['oci oac data sets', 'oac dataset', 'oracle analytics cloud dataset'], description: 'Oracle Analytics Cloud（OAC）でビジュアライゼーションの元データとなる論理データセット。Autonomous DB・Object Storage・スプレッドシートなど複数ソースを結合して定義し、ビジネスユーザーが自己サービスで分析できる単位。' },
  { term: 'OCI DevOpsコードリポジトリ', aliases: ['oci devopsコードリポジトリ', 'oci devops code repository'], description: 'OCI DevOpsサービスに組み込まれたGit互換のソースコードリポジトリ。ビルドパイプラインのトリガーと統合されており、プッシュ時に自動的にCI/CDパイプラインを起動できる。' },
  { term: 'OCI Logging Analytics ML異常検知', aliases: ['oci logging analytics ml異常検知', 'oci logging analytics ml anomaly detection'], description: 'OCI Logging Analyticsが機械学習アルゴリズムを使ってログの正常パターンを学習し、通常とは異なるログパターンや急激なカウント変化を自動検出する機能。インシデント予兆検知に活用できる。' },
  { term: 'OCI APM合成モニタリング', aliases: ['oci apm合成モニタリング', 'apm synthetic monitoring'], description: 'OCI APMが世界中の拠点から定期的にスクリプトベースのWebトランザクションを実行し、エンドユーザー視点でのサービス可用性とレスポンスタイムを監視する機能。エラー発生前の予防的検知に使う。' },
  { term: 'OCIコンソールWebUI', aliases: ['ociコンソールwebui', 'oracle cloud management console'], description: 'ブラウザからOCIリソースを管理するWebベースのグラフィカル管理インターフェース。リソースの作成・設定・監視・コスト確認をGUIで行え、Cloud Shellや診断ツールとの統合も提供する。' },
  { term: 'OCI Data Science Job', aliases: ['oci data science job', 'oci ds job'], description: 'OCI Data Scienceプラットフォームで機械学習のトレーニングやデータ処理スクリプトをバッチ実行するジョブ機能。コンピュートシェイプとOCPU数を指定してジョブを定義し、スケジュール実行や並列実行に対応する。' },
  { term: 'Oracle APEX Application Development', aliases: ['oracle apex application development'], description: 'OCIでOracle APEXを利用するためのマネージドサービス。' },
  { term: 'APEX Service', aliases: ['apex service'], description: 'OCI上のAPEX向けサービスの通称。' },
  { term: 'APEXインスタンス', aliases: ['apexインスタンス'], description: 'OCI上で管理されるAPEX利用環境の実体。' },
  { term: 'Autonomous AI Database', aliases: ['autonomous ai database'], description: 'Oracleのフルマネージド自律型データベース。' },
  { term: 'Autonomous AI Transaction Processing', aliases: ['autonomous ai transaction processing'], description: 'トランザクション処理向けに最適化されたAutonomous Database系ワークロード。' },
  { term: 'ワークスペース', description: 'APEXでユーザーやアプリを分けて管理する作業領域。' },
  { term: 'APEXユーザー', aliases: ['apexユーザー'], description: 'APEXへサインインするための利用者アカウント。' },
  { term: 'ワークスペース管理者', description: 'ワークスペース内の設定や利用者を管理する役割。' },
  { term: 'インスタンス管理者', description: 'APEXインスタンス全体を管理する役割。' },
  { term: 'ADMIN', aliases: ['admin'], description: 'Administration Servicesへ入る管理者アカウント名。' },
  { term: 'Administration Services', aliases: ['administration services'], description: 'APEXインスタンス管理用の画面。' },
  { term: 'App Builder', aliases: ['app builder'], description: 'APEXアプリを作成編集する中心画面。' },
  { term: 'SQL Workshop', aliases: ['sql workshop'], description: 'SQLやDBオブジェクトを扱う開発メニュー。' },
  { term: 'Team Development', aliases: ['team development'], description: 'タスクやマイルストーンを管理する機能。' },
  { term: 'Gallery', aliases: ['gallery'], description: 'サンプルやスターターアプリを取得する入口。' },
  { term: 'Workspace Home Page', aliases: ['workspace home page'], description: 'サインイン直後に表示されるホーム画面。' },
  { term: 'App Builder Home Page', aliases: ['app builder home page'], description: 'CreateやImportなどの入口がある画面。' },
  { term: 'Application Home Page', aliases: ['application home page'], description: '個別アプリの設定や操作を行う画面。' },
  { term: 'APEX Instances Page', aliases: ['apex instances page'], description: 'OCI ConsoleでAPEXインスタンス一覧を見る画面。' },
  { term: 'APEX Instance Details Page', aliases: ['apex instance details page'], description: 'APEXインスタンスの詳細や操作を行う画面。' },
  { term: 'Launch APEX', aliases: ['launch apex'], description: 'OCI ConsoleからAPEXを開く操作。' },
  { term: 'Launch Database Actions', aliases: ['launch database actions'], description: 'OCI ConsoleからDatabase Actionsを開く操作。' },
  { term: 'Database Actions', aliases: ['database actions'], description: 'ブラウザベースでDB操作や管理を行うツール群。' },
  { term: 'SQL Developer Web', aliases: ['sql developer web'], description: 'Database Actionsの旧称。' },
  { term: 'APEX Version', aliases: ['apex version'], description: 'その環境で動作しているAPEXの版情報。' },
  { term: 'ORDS Version', aliases: ['ords version'], description: 'その環境で動作しているORDSの版情報。' },
  { term: 'Workload Type', aliases: ['workload type'], description: 'データベースやサービスの用途分類。' },
  { term: 'ECPU', aliases: ['ecpu'], description: 'Oracleの計算リソースの割当単位。' },
  { term: 'Auto Scaling', aliases: ['auto scaling'], description: '負荷に応じて計算資源を自動で拡張する仕組み。' },
  { term: 'Start', aliases: ['start'], description: '停止中のサービスを起動する操作。' },
  { term: 'Stop', aliases: ['stop'], description: '稼働中のサービスを停止する操作。' },
  { term: 'Restart', aliases: ['restart'], description: 'サービスや基盤DBを再起動する操作。' },
  { term: 'Terminate', aliases: ['terminate'], description: 'リソースを終了削除する操作。' },
  { term: 'Move Resource', aliases: ['move resource'], description: 'リソースの所属Compartmentを変更する操作。' },
  { term: 'Configure Document Generator', aliases: ['configure document generator'], description: '文書生成機能を使うための設定。' },
  { term: 'Compartment', aliases: ['compartment'], description: 'OCIリソースを整理分離する論理区画。' },
  { term: 'Subnet', aliases: ['subnet'], description: '仮想ネットワーク内を分割したIPアドレス範囲。' },
  { term: 'Public Subnet', aliases: ['public subnet'], description: '外部公開向けの到達性を持たせやすいサブネット。' },
  { term: 'Private Subnet', aliases: ['private subnet'], description: '外部へ直接公開しない内部向けサブネット。' },
  { term: 'Region', aliases: ['region'], description: 'クラウドリソースを配置する地理的な領域。' },
  { term: 'Ingress Rule', aliases: ['ingress rule'], description: '外部から入る通信を許可または制限するルール。' },
  { term: 'Egress Rule', aliases: ['egress rule'], description: '外部へ出る通信を許可または制限するルール。' },
  { term: 'DNS Label', aliases: ['dns label'], description: 'DNS名生成に使う短い識別文字列。' },
  { term: 'Load Balancer', aliases: ['load balancer'], description: '複数の接続先に通信を振り分ける仕組み。' },
  { term: 'Listener', aliases: ['listener'], description: '特定ポートやプロトコルで接続を受ける待受設定。' },
  { term: 'Backend Set', aliases: ['backend set'], description: '負荷分散先とルーティング条件のまとまり。' },
  { term: 'Backend Server', aliases: ['backend server'], description: '実際に処理を受け持つ転送先サーバ。' },
  { term: 'Health Check', aliases: ['health check'], description: '接続先の生死や応答可否を確認する監視。' },
  { term: 'SSL Certificate', aliases: ['ssl certificate'], description: 'HTTPSなどで使うサーバ証明書。' },
  { term: 'CA Bundle', aliases: ['ca bundle'], description: '信頼するCA証明書をまとめた束。' },
  { term: 'Vanity URL', aliases: ['vanity url'], description: '既定URLではなく独自ドメインで公開するURL。' },
  { term: 'Custom Domain', aliases: ['custom domain'], description: 'サービス公開時に使う独自ドメイン名。' },
  { term: 'Identity Domain', aliases: ['identity domain'], description: 'ユーザーやグループ、認証設定を管理する境界。' },
  { term: 'Tag', aliases: ['tag'], description: 'リソース整理や追跡のために付けるキー値情報。' },
  { term: 'Bucket', aliases: ['bucket'], description: 'オブジェクトを格納するコンテナ。' },
  { term: 'Function Application', aliases: ['function application'], description: '関数群をまとめる論理単位。' },
  { term: 'Fn Project CLI', aliases: ['fn project cli'], description: 'OCI Functionsを作成配備するCLI。' },
  { term: 'Connection', aliases: ['connection'], description: 'サービス間接続のための設定オブジェクト。' },
  { term: 'Policy Name', aliases: ['policy name'], description: 'ポリシーを識別する名前。' },
  { term: 'Policy Compartment', aliases: ['policy compartment'], description: 'IAMポリシーを配置するCompartment。' },
  { term: 'Object Storage Bucket Compartment', aliases: ['object storage bucket compartment'], description: 'Bucketが属するCompartment。' },
  { term: 'Web Credential', aliases: ['web credential'], description: '外部サービス接続用の資格情報オブジェクト。' },
  { term: 'Remote Server', aliases: ['remote server'], description: 'REST接続先の基底URLや認証をまとめる設定。' },
  { term: 'REST Data Source', aliases: ['rest data source'], description: '外部REST APIをAPEXで扱うためのデータソース定義。' },
  { term: 'REST Data Source Type', aliases: ['rest data source type'], description: 'REST Data Sourceの利用方式や特性の種別。' },
  { term: 'Simple HTTP', aliases: ['simple http'], description: '単純なHTTP取得型のデータ利用方式。' },
  { term: 'APEXサービス用ロードバランサー', aliases: ['apexサービス用ロードバランサー', 'load balancer for apex service'], description: 'Oracle APEX環境へのトラフィックを複数のサーバーに分散するロードバランサーです。高可用性とスケーラビリティを提供します。' },
  { term: 'OCIリソースタグ', aliases: ['ociリソースタグ', 'oci resource tag', 'resource tag'], description: 'OCIリソースにメタデータとして付与できるキーと値のペアです。コスト管理・アクセス制御・リソース検索を効率化するために使用します。' },
  { term: 'APEXサービス用オブジェクトストレージバケット', aliases: ['apexサービス用オブジェクトストレージバケット', 'object storage bucket for apex service'], description: 'Oracle APEX環境でファイルや静的アセットを格納するOCIオブジェクトストレージのバケットです。APEXアプリケーションのリソース管理に利用します。' },
  { term: 'OpenAPI URL', aliases: ['openapi url'], description: 'OpenAPI定義を取得するURL。' },
  { term: 'URL Endpoint', aliases: ['url endpoint'], description: 'APIやサービスの個別エンドポイントURL。' },
  { term: 'HTTPS Host Name', aliases: ['https host name'], description: 'TLS証明書検証時に使うホスト名。' },
  { term: 'Base URL', aliases: ['base url'], description: 'API共通部分となるURLの前半。' },
  { term: 'Service URL Path', aliases: ['service url path'], description: 'Base URLに追加するサービスごとのパス。' },
  { term: 'Pagination Type', aliases: ['pagination type'], description: 'API結果のページ分割方式。' },
  { term: 'Data Profile', aliases: ['data profile'], description: '受信データの項目構造や型のメタ情報。' },
  { term: 'Discovery', aliases: ['discovery'], description: 'API定義を読み取り自動推定する処理。' },
  { term: 'Create REST Source Manually', aliases: ['create rest source manually'], description: '手動でRESTソースを作る方法。' },
  { term: 'Root Resource Name', aliases: ['root resource name'], description: 'REST定義内で使う最上位リソース名。' },
  { term: 'Batch DML', aliases: ['batch dml'], description: '複数の更新をまとめて送るデータ更新方式。' },
  { term: 'REST Source Catalog', aliases: ['rest source catalog'], description: '再利用可能なRESTソース定義のカタログ。' },
  { term: 'Internal Name', aliases: ['internal name'], description: '内部識別に使う論理名。' },
  { term: 'Refresh Endpoint URL', aliases: ['refresh endpoint url'], description: 'カタログ再取得に使う更新元URL。' },
  { term: 'REST Enabled SQL', aliases: ['rest enabled sql'], description: 'REST経由でSQL実行や参照を可能にする仕組み。' },
  { term: 'REST Enabled SQL Service Reference', aliases: ['rest enabled sql service reference'], description: 'REST Enabled SQL先を指す接続定義。' },
  { term: 'Static ID', aliases: ['static id'], description: 'コードや設定から安定参照する固定識別子。' },
  { term: 'Prompt on Install', aliases: ['prompt on install'], description: 'インポート時に入力を促すかを決める設定。' },
  { term: 'Utilization Report', aliases: ['utilization report'], description: 'オブジェクトの利用箇所を一覧化するレポート。' },
  { term: 'History Report', aliases: ['history report'], description: 'オブジェクト変更履歴を確認するレポート。' },
  { term: 'Generative AI Service', aliases: ['generative ai service'], description: 'APEXで生成AIを使うための接続定義オブジェクト。' },
  { term: 'AI Provider', aliases: ['ai provider'], description: '利用する生成AI提供元。' },
  { term: 'OCI Generative AI Service', aliases: ['oci generative ai service'], description: 'OCI上の生成AIサービスをAPEXから使う選択肢。' },
  { term: 'Cohere', aliases: ['cohere'], description: 'APEXで設定可能な生成AI提供元の一つ。' },
  { term: 'APEX Assistant', aliases: ['apex assistant'], description: 'App Builderのコード編集支援AI。' },
  { term: 'APEX_AI', aliases: ['apex_ai'], description: 'APEXから生成AIを呼ぶAPIパッケージ。' },
  { term: 'APEX_AI.CHAT', aliases: ['apex_ai.chat'], description: 'APEX_AI経由でチャット実行する手続き。' },
  { term: 'Test Connection', aliases: ['test connection'], description: 'AI接続設定を事前検証する操作。' },
  { term: 'Additional Attributes', aliases: ['additional attributes'], description: 'AIリクエストに付与する追加パラメータ。' },
  { term: 'HTTP Headers', aliases: ['http headers'], description: 'AI呼び出し時に付加するHTTPヘッダ。' },
  { term: 'Used by App Builder', aliases: ['used by app builder'], description: 'App Builder側のAI機能で使うサービスとして有効化する設定。' },
  { term: 'AI Page', aliases: ['ai page'], description: 'アプリ属性内でAI関連設定を扱う画面領域。' },
  { term: 'AI Assistant Dynamic Action', aliases: ['ai assistant dynamic action'], description: 'アプリ実行時にAI支援を呼び出す動的アクション。' },
  { term: 'Workspace Utilities', aliases: ['workspace utilities'], description: 'ワークスペース共通ユーティリティの一覧画面。' },
  { term: 'Application Groups', aliases: ['application groups'], description: 'アプリを論理的にグループ分けする機能。' },
  { term: 'Workspace Themes', aliases: ['workspace themes'], description: 'ワークスペースで使うテーマ設定。' },
  { term: 'Oracle APEX Views', aliases: ['oracle apex views'], description: 'APEXメタデータ参照用のビュー群。' },
  { term: 'Manage Backups', aliases: ['manage backups'], description: 'アプリのバックアップ管理機能。' },
  { term: 'Cross Application Reports', aliases: ['cross application reports'], description: '複数アプリを横断して見るレポート。' },
  { term: 'Import', aliases: ['import'], description: 'アプリや設定を取り込む操作。' },
  { term: 'Application Export', aliases: ['application export'], description: 'アプリ全体を移送用ファイルとして出力すること。' },
  { term: 'Page Export', aliases: ['page export'], description: 'ページ単位で定義を書き出すこと。' },
  { term: 'App Gallery', aliases: ['app gallery'], description: 'アプリひな形の選択画面。' },
  { term: 'Sample App', aliases: ['sample app'], description: '学習用に用意されたサンプルアプリ。' },
  { term: 'Starter App', aliases: ['starter app'], description: '実装の出発点として使うひな形アプリ。' },
  { term: 'Custom App', aliases: ['custom app'], description: 'ユーザー独自に用意したアプリ定義。' },
  { term: 'Utility App', aliases: ['utility app'], description: '補助用途向けの実用アプリ。' },
  { term: 'Oracle APEX GitHub Repository', aliases: ['oracle apex github repository'], description: 'サンプルや拡張部品の公開配布元。' },
  { term: 'Shared Components', aliases: ['shared components'], description: 'アプリ共通部品をまとめて管理する画面。' },
  { term: 'Static Application Files', aliases: ['static application files'], description: 'アプリ内で使う静的ファイル置き場。' },
  { term: '#APP_FILES#', aliases: ['#app_files#'], description: '静的アプリファイル参照に使う置換記法。' },
  { term: 'Component Groups', aliases: ['component groups'], description: '共通部品をまとめて再利用する単位。' },
  { term: 'Plug-ins', aliases: ['plug-ins'], description: '標準以外の宣言的コンポーネント拡張。' },
  { term: 'Component Settings', aliases: ['component settings'], description: 'コンポーネントのアプリ共通設定。' },
  { term: 'Shortcuts', aliases: ['shortcuts'], description: 'HTMLやPL/SQL断片を再利用する仕組み。' },
  { term: 'Session State Protection', aliases: ['session state protection'], description: 'URL改ざんなどを防ぐ保護機能。' },
  { term: 'Map Backgrounds', aliases: ['map backgrounds'], description: '地図表示用の背景マップ定義。' },
  { term: 'Page Designer', aliases: ['page designer'], description: 'ページを統合的に編集する開発画面。' },
  { term: 'Rendering', aliases: ['rendering'], description: '画面描画系コンポーネントを扱う領域。' },
  { term: 'Dynamic Actions', aliases: ['dynamic actions'], description: 'クライアント側イベント処理を定義する領域。' },
  { term: 'Property Editor', aliases: ['property editor'], description: '選択部品の属性を編集するペイン。' },
  { term: 'Component View', aliases: ['component view'], description: 'コンポーネント種別ごとに見るタブ。' },
  { term: 'Page Search', aliases: ['page search'], description: 'ページ内の構成要素を検索する機能。' },
  { term: 'Item', aliases: ['item'], description: '入力や表示に使うページ部品。' },
  { term: 'Computation', aliases: ['computation'], description: '値を計算してセットする定義。' },
  { term: 'Copy Page', aliases: ['copy page'], description: '既存ページを複製する操作。' },
  { term: 'Comment Out', aliases: ['comment out'], description: '一時的に無効化して残す操作。' },
  { term: 'Uncomment', aliases: ['uncomment'], description: '無効化状態を解除する操作。' },
  { term: 'Quick SQL', aliases: ['quick sql'], description: '簡易記法からDDLを自動生成する機能。' },
  { term: 'Data Workshop', aliases: ['data workshop'], description: 'データのロードやアンロードを行う機能。' },
  { term: 'Data Generator', aliases: ['data generator'], description: 'サンプルデータを生成する機能。' },
  { term: 'Sample Datasets', aliases: ['sample datasets'], description: '学習や検証用に用意されたサンプルデータ集合。' },
  { term: 'Object Browser', aliases: ['object browser'], description: 'DBオブジェクトを閲覧作成する画面。' },
  { term: 'SQL Commands', aliases: ['sql commands'], description: 'その場で単発SQLを実行する画面。' },
  { term: 'SQL Scripts', aliases: ['sql scripts'], description: 'SQLスクリプトを保存実行する機能。' },
  { term: 'Schema Comparison', aliases: ['schema comparison'], description: '2つのスキーマ差分を比較する機能。' },
  { term: 'Monitor Database', aliases: ['monitor database'], description: 'DBの状態や性能を監視すること。' },
  { term: 'Database Dashboard', aliases: ['database dashboard'], description: 'DBの状態を要約表示するダッシュボード。' },
  { term: 'Database Accounts Authentication', aliases: ['database accounts authentication'], description: 'DBユーザー名とパスワードによる認証方式。' },
  { term: 'Schema-based Authentication', aliases: ['schema-based authentication'], description: 'スキーマ利用前提で接続可否を決める方式。' },
  { term: 'Database Connection', aliases: ['database connection'], description: 'DBへ接続するための設定情報全般。' },
  { term: 'Wallet', aliases: ['wallet'], description: 'DB接続用の証明書や設定をまとめた資格情報一式。' },
  { term: 'tnsnames.ora', description: 'Oracle接続先名を定義する設定ファイル。' },
  { term: 'APEXレンダリング', aliases: ['apexレンダリング', 'apex rendering'], description: 'Oracle APEXがページや各コンポーネントをHTMLとして生成・表示するプロセスです。テンプレートやプラグインによって出力を制御できます。' },
  { term: 'APEXアイテム', aliases: ['apexアイテム', 'apex item'], description: 'Oracle APEXのページ上に配置される入力フィールドや表示要素などのUIコンポーネントです。セッション変数として値を管理します。' },
  { term: 'APEXバリデーション', aliases: ['apexバリデーション', 'apex validation'], description: 'Oracle APEXでページ送信時にアイテムの値を検証するルールです。必須チェック・書式チェック・カスタムPL/SQLによる検証が可能です。' },
];
