// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: ociServices (1/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // oci (263), oci-apex (149), apex (3), oracle-apex (2)
  { term: 'Oracle Cloud Infrastructure', aliases: ['oracle cloud infrastructure'], description: 'Oracleのクラウド基盤サービス群です。略してOCIと呼ばれます。' },
  { term: 'Tenancy', aliases: ['tenancy'], description: '【OCI】OCI利用の契約、管理の最上位単位です。 【OCI APEX】OCI契約全体を表す最上位の管理単位。' },
  { term: 'OCID', aliases: ['ocid'], description: '【OCI】OCIリソースを一意に識別するIDです。 【OCI APEX】OCIリソースを一意に識別するID。' },
  { term: 'Virtual Cloud Network', aliases: ['virtual cloud network'], description: 'OCIの論理ネットワークです。略してVCNと呼ばれます。' },
  { term: 'VCN', aliases: ['vcn'], description: '【OCI】Virtual Cloud Networkの略称です。 【OCI APEX】OCIにおける仮想クラウドネットワーク。' },
  { term: 'Subnet in OCI', aliases: ['subnet in oci'], description: 'VCN内で分けるネットワーク領域です。' },
  { term: 'VNIC', aliases: ['vnic'], description: '【OCI】Computeインスタンスへ接続する仮想ネットワークインターフェースです。 【OCI APEX】仮想マシンやサービスに割り当てる仮想NIC。' },
  { term: 'DRG', aliases: ['drg'], description: '【OCI】Dynamic Routing Gatewayの略で、VCNと外部接続をつなぐゲートウェイです。 【OCI APEX】OCIでVCNと外部ネットワークを中継するルータ機能。' },
  { term: 'Internet Gateway (OCI)', aliases: ['internet gateway (oci)'], description: 'VCNをインターネット接続するためのゲートウェイです。' },
  { term: 'NAT Gateway (OCI)', aliases: ['nat gateway (oci)'], description: 'プライベートサブネットから外向き通信するためのゲートウェイです。' },
  { term: 'Service Gateway', aliases: ['service gateway'], description: '【OCI】VCNからObject StorageなどOCIサービスへプライベート接続する仕組みです。 【OCI APEX】クラウド内の特定サービスへ私設経路で接続する仕組み。' },
  { term: 'Local Peering Gateway', aliases: ['local peering gateway'], description: '同一リージョン内のVCN同士を私設接続するためのゲートウェイです。' },
  { term: 'Security List', aliases: ['security list'], description: '【OCI】サブネット単位で適用する通信制御ルールです。 【OCI APEX】サブネット単位に適用する通信制御ルール。' },
  { term: 'Network Security Group in OCI', aliases: ['network security group in oci'], description: 'リソース単位で使える仮想ファイアウォールです。' },
  { term: 'Network Load Balancer (OCI)', aliases: ['network load balancer (oci)'], description: 'OCIのネットワーク負荷分散サービスです。' },
  { term: 'FastConnect', aliases: ['fastconnect'], description: 'オンプレミスとOCIを専用線でつなぐサービスです。' },
  { term: 'Site-to-Site VPN', aliases: ['site-to-site vpn'], description: 'オンプレミスとOCIをVPN接続する仕組みです。' },
  { term: 'Compute', aliases: ['compute'], description: '仮想マシンやベアメタルを提供するOCIのコンピュートサービスです。' },
  { term: 'Shape', aliases: ['shape'], description: 'OCIでCPUやメモリ構成を表すリソース定義です。' },
  { term: 'Block Volume', aliases: ['block volume'], description: 'Compute向けのブロックストレージです。' },
  { term: 'Archive Storage', aliases: ['archive storage'], description: '長期保管向けのストレージ階層です。' },
  { term: 'Autonomous Database', aliases: ['autonomous database'], description: 'フルマネージドで自動運用を特徴とするデータベースサービスです。' },
  { term: 'Base Database Service', aliases: ['base database service'], description: 'OCI上でOracle Databaseを管理するデータベースサービス群です。' },
  { term: 'Database System', aliases: ['database system'], description: 'OCI上で提供されるOracle Database実行基盤の一形態です。' },
  { term: 'Exadata Database Service', aliases: ['exadata database service'], description: 'Exadata基盤上でOracle Databaseを提供するサービスです。' },
  { term: 'MySQL HeatWave', aliases: ['mysql heatwave'], description: 'OCI上で使えるMySQL系のサービスです。' },
  { term: 'Container Instances', aliases: ['container instances'], description: 'サーバーレス的にコンテナを実行できるOCIサービスです。' },
  { term: 'Oracle Kubernetes Engine', aliases: ['oracle kubernetes engine'], description: 'OCIのマネージドKubernetesサービスです。略してOKEと呼ばれます。' },
  { term: 'OKE', aliases: ['oke'], description: 'Oracle Kubernetes Engineの略称です。' },
  { term: 'OCIR', aliases: ['ocir'], description: 'OCIのコンテナレジストリサービスです。' },
  { term: 'Functions', aliases: ['functions'], description: 'OCIのサーバーレス関数実行サービスです。' },
  { term: 'Streaming', aliases: ['streaming'], description: 'イベントやストリームデータを扱うサービスです。' },
  { term: 'Queue', aliases: ['queue'], description: '非同期メッセージ処理向けのキューサービスです。' },
  { term: 'Notifications', aliases: ['notifications'], description: 'アラートやイベント通知を配信するサービスです。' },
  { term: 'Events', aliases: ['events'], description: 'OCIサービスのイベントをトリガーとして扱う仕組みです。' },
  { term: 'Logging', aliases: ['logging'], description: 'ログを収集、保存するOCIサービスです。' },
  { term: 'Monitoring', aliases: ['monitoring'], description: 'メトリクスとアラートを扱う監視サービスです。' },
  { term: 'Logging Analytics', aliases: ['logging analytics'], description: 'ログ分析を高度化するOCIのサービスです。' },
  { term: 'Application Performance Monitoring', aliases: ['application performance monitoring'], description: 'アプリケーション性能を可視化するサービスです。' },
  { term: 'IAM with Identity Domains', aliases: ['iam with identity domains'], description: 'OCIの認証、認可管理基盤です。' },
  { term: 'Dynamic Group', aliases: ['dynamic group'], description: '【OCI】OCIリソースを条件でまとめて権限付与に使う仕組みです。 【OCI APEX】リソースを主語にして権限付与するためのグループ。' },
  { term: 'Policy in OCI', aliases: ['policy in oci'], description: '誰に何を許可するかを記述するルールです。' },
  { term: 'Vault', aliases: ['vault'], description: '鍵や秘密情報を保管するOCIサービスです。' },
  { term: 'Key Management', aliases: ['key management'], description: '暗号鍵の作成、管理を扱うOCI機能です。' },
  { term: 'Certificates', aliases: ['certificates'], description: '証明書を管理するOCIサービスです。' },
  { term: 'Bastion', aliases: ['bastion'], description: '安全な踏み台接続を支援するOCIサービスです。' },
  { term: 'Resource Manager', aliases: ['resource manager'], description: 'Terraformベースでインフラをするサービスです。' },
  { term: 'DevOps Service', aliases: ['devops service'], description: 'ビルドやデプロイを支援するOCIのDevOpsサービスです。' },
  { term: 'Data Flow', aliases: ['data flow'], description: 'サーバーレスでSpark処理を実行するサービスです。' },
  { term: 'Data Integration', aliases: ['data integration'], description: 'データ統合やETLを支援するサービスです。' },
  { term: 'Data Safe', aliases: ['data safe'], description: 'データベースセキュリティを支援するサービスです。' },
  { term: 'Cloud Guard', aliases: ['cloud guard'], description: 'セキュリティ姿勢管理を支援するOCIサービスです。' },
  { term: 'Security Zones', aliases: ['security zones'], description: '高セキュリティな構成制約を適用する仕組みです。' },
  { term: 'Service Connector Hub', aliases: ['service connector hub'], description: 'ログやイベントを別サービスへつなぐ仕組みです。' },
  { term: 'Search', aliases: ['search'], description: 'OCIリソースを横断検索する機能です。' },
  { term: 'Tagging in OCI', aliases: ['tagging in oci'], description: 'OCIリソースへ管理用タグを付ける仕組みです。' },
  { term: 'Availability Domain', aliases: ['availability domain'], description: '【OCI】OCIでの可用性分散単位です。 【OCI APEX】同一リージョン内で障害分離されたデータセンター単位。' },
  { term: 'Fault Domain', aliases: ['fault domain'], description: '【OCI】同一Availability Domain内で障害分離を意識する配置単位です。 【OCI APEX】物理障害の影響を分散するための区分。' },
  { term: 'Region in OCI', aliases: ['region in oci'], description: 'OCIがサービス提供する地理的単位です。' },
  { term: 'Autonomous Linux', aliases: ['autonomous linux'], description: 'OCIで提供される自動運用支援付きLinux管理サービスです。' },
  { term: 'Health Checks', aliases: ['health checks'], description: 'エンドポイントの疎通や状態を確認するOCIサービスです。' },
  { term: 'Interconnect for Microsoft Azure', aliases: ['interconnect for microsoft azure'], description: 'OCIとMicrosoft Azureをインターネットを介さず接続する仕組みです。' },
  { term: 'モニタリング（OCI）', aliases: ['モニタリング（oci）', 'monitoring (oci)', 'oci monitoring'], description: 'OCIが提供するメトリクス収集・アラーム設定のためのモニタリングサービスです。リソースのパフォーマンスや状態を継続的に監視できます。' },
  { term: 'キー管理（OCI）', aliases: ['キー管理（oci）', 'key management (oci)', 'oci kms'], description: 'OCIが提供する暗号化キーのライフサイクル管理サービスです。データの暗号化・復号に使用するキーを安全に保管・管理します。' },
  { term: 'OCVS', aliases: ['ocvs', 'oracle cloud vmware solution'], description: 'Oracle Cloud上でVMware環境を専有的に利用できるサービス。' },
  { term: 'AD', aliases: ['ad'], description: '電源や設備の障害影響を分離するための、OCI内の物理的または論理的な区画。' },
  { term: 'BaseDB', aliases: ['basedb'], description: 'OCI上で提供されるOracle Databaseのマネージドサービス群の総称的な呼び方。' },
  { term: 'OAC', aliases: ['oac', 'oracle analytics cloud'], description: 'Oracleが提供するクラウド型の分析・可視化サービス。' },
  { term: 'ADW', aliases: ['adw', 'autonomous data warehouse'], description: '分析用途に最適化されたAutonomous Databaseの一種。' },
  { term: 'Object Storage', aliases: ['object storage', 'オブジェクトストレージ（oci）', 'oci object storage'], description: '【OCI】OCIでファイルやバックアップデータを大容量かつ柔軟に保存できるストレージサービス。 【OCI APEX】オブジェクト単位でデータを保存するストレージ。' },
  { term: '対話型グリッド', aliases: ['interactive grid'], description: '表形式で編集や検索ができる高機能な一覧UI。' },
  { term: 'LOV', aliases: ['lov', 'list of values'], description: '【Oracle APEX】選択肢一覧を持つ項目定義で、APEXなどでよく使われる。 【OCI APEX】選択肢表示に使う静的または動的な値一覧。' },
  { term: 'OCI Compute', aliases: ['oci compute', 'oracle cloud infrastructure compute', 'ociコンピュート'], description: 'Oracle Cloud Infrastructure上で仮想マシンやベアメタルサーバーを提供するIaaSサービス。多様なシェイプ（インスタンスタイプ）から用途に応じたスペックを選択でき、オンデマンドや予約購入などの課金モデルが用意されている。' },
  { term: 'OCIシェイプ', aliases: ['ociシェイプ', 'oci shape', 'インスタンスシェイプ'], description: 'OCI Computeインスタンスに割り当てるCPU数・メモリ量・ネットワーク帯域などのリソース構成テンプレート。Standard、DenseIO、GPU、HPC向けなど用途別シェイプが用意されており、フレキシブルシェイプでは値を柔軟に指定できる。' },
  { term: 'フレキシブルシェイプ', aliases: ['flexible shape', 'flex shape'], description: 'OCIで提供されるシェイプの一種で、CPUコア数とメモリ容量を個別に指定できる。事前定義シェイプとは異なり、必要なリソースだけを選択することでコストを最適化できる。' },
  { term: 'ベアメタルインスタンス', aliases: ['bare metal instance', 'bm instance'], description: 'ハイパーバイザーを介さず物理サーバーを占有して利用するOCIのコンピューティングオプション。仮想化のオーバーヘッドがなく最高レベルのパフォーマンスと分離性を提供するため、HPC・データベース・セキュリティ要件の高いワークロードに適する。' },
  { term: '専用VMホスト', aliases: ['専用vmホスト', 'dedicated vm host', '専用仮想マシンホスト'], description: 'OCIで特定のテナント専用の物理ホスト上に仮想マシンを展開できるサービス。他テナントとの物理的な分離を保証するため、コンプライアンス要件の厳しいワークロードやライセンス持ち込み（BYOL）シナリオに対応する。' },
  { term: 'OCIインスタンスプール', aliases: ['ociインスタンスプール', 'oci instance pool', 'インスタンスプール'], description: '同一設定の複数OCI Computeインスタンスをグループとして管理する機能。インスタンス構成をテンプレートに定め、スケーリングや管理を一元化できる。Autoscalingと組み合わせて弾力的な水平スケールを実現する。' },
  { term: 'OCI Autoscaling', aliases: ['oci autoscaling', 'ociオートスケーリング', 'autoscaling'], description: 'インスタンスプールのサイズをCPU使用率などのメトリクスやスケジュールに基づいて自動調整するOCIの機能。需要の増減に応じてインスタンス数を増減させ、コストとパフォーマンスのバランスを維持する。' },
  { term: 'OCI Container Instances', aliases: ['oci container instances', 'ociコンテナインスタンス', 'コンテナインスタンス'], description: 'Kubernetesクラスターを管理せずにコンテナをサーバーレスで実行できるOCIサービス。インフラの管理が不要で、バッチジョブや短期タスクなど軽量なコンテナワークロードを素早くデプロイするのに適している。' },
  { term: 'OCI Container Engine for Kubernetes', aliases: ['oci container engine for kubernetes', 'oracle container engine for kubernetes'], description: 'OCIが提供するマネージドKubernetesサービス。コントロールプレーンはOracleが管理し、ユーザーはワーカーノードとアプリケーションの管理に集中できる。OCIのネイティブサービスと深く統合されている。' },
  { term: 'OCI Functions', aliases: ['oci functions', 'oracle functions', 'ociファンクションズ'], description: '【OCI】Oracle Cloud上のサーバーレスFaaS（Function as a Service）プラットフォーム。オープンソースのFnプロジェクトをベースとし、イベント駆動で関数を実行する。コードの実行時間分のみ課金されるため小規模・非同期処理に適する。 【OCI APEX】OCIのサーバレス関数実行サービス。' },
  { term: 'OCI API Gateway', aliases: ['oci api gateway', 'ociapiゲートウェイ'], description: 'REST APIを公開・管理するOCIのマネージドサービス。認証、レート制限、リクエスト変換などの機能を提供し、バックエンドにOCI Functionsや外部HTTPエンドポイントを接続できる。' },
  { term: 'OCI Block Volume', aliases: ['oci block volume', 'ociブロックボリューム'], description: 'OCI Computeインスタンスにアタッチして使用するブロックストレージサービス。高いIOPSと低レイテンシを提供し、データベースやOS以外の追加ディスクとして利用される。インスタンスとは独立して存在し、デタッチ・再アタッチが可能。' },
  { term: 'OCI Boot Volume', aliases: ['oci boot volume', 'ociブートボリューム', 'ブートボリューム'], description: 'OCIインスタンスの起動ディスクとなるブロックボリューム。インスタンスとは独立して管理でき、インスタンス終了後もデータが保持される。ブートボリュームのバックアップやクローンからインスタンスを復元することも可能。' },
  { term: 'ブロックボリュームバックアップ', aliases: ['block volume backup', 'ボリュームバックアップ'], description: 'OCI Block VolumeおよびBoot Volumeのポイントインタイムスナップショットを取得する機能。手動または自動ポリシーでバックアップをスケジュールでき、取得したバックアップからボリュームを復元・クローン可能。' },
  { term: 'Object Storageバケット', aliases: ['object storageバケット', 'object storage bucket', 'バケット'], description: 'OCI Object Storageでオブジェクトを格納する論理コンテナ。コンパートメント内に作成され、アクセスポリシー・暗号化・バージョニング設定などをバケット単位で管理する。' },
  { term: 'Object Storageティア', aliases: ['object storageティア', 'object storage tier', 'ストレージティア'], description: 'OCI Object Storageでオブジェクトに設定できるアクセス頻度に応じたストレージクラス。Standardティア（高頻度アクセス）、Inferrequent Access（低頻度）があり、ライフサイクルポリシーで自動移行も可能。' },
  { term: 'OCI Archive Storage', aliases: ['oci archive storage', 'ociアーカイブストレージ'], description: '長期保管・低コストを目的としたOCIのオブジェクトストレージサービス。アクセス頻度が極めて低いデータのコールドアーカイブ用途に最適で、リストア要求から実際のデータ取得まで時間がかかる。' },
  { term: 'OCI File Storage', aliases: ['oci file storage', 'ociファイルストレージ'], description: '複数のComputeインスタンスから同時マウントできるNFSv3対応のフルマネージドファイルシステムサービス。共有ストレージが必要なアプリケーションや、従来のファイルサーバーの移行先として利用される。' },
  { term: 'OCI Data Transfer', aliases: ['oci data transfer', 'ociデータ転送', 'data transfer service'], description: '大量データをインターネット経由ではなく物理ストレージアプライアンス（Data Transfer Disk/Appliance）を使ってOCIのObject Storageへ転送するサービス。ネットワーク帯域が制限される場合やペタバイト規模の初期移行に適する。' },
  { term: 'Oracle Database Cloud Service', aliases: ['oracle database cloud service', 'dbcs', 'oracle dbcs'], description: 'Oracle DatabaseをOCIのVM上で実行するマネージドデータベースサービス。フルマネージドのAutonomous Databaseとは異なり、DBインスタンスへのOSレベルのアクセスや細かい設定変更が可能。' },
  { term: 'Oracle Autonomous Database', aliases: ['oracle autonomous database', '自律型データベース'], description: '機械学習を活用してチューニング、セキュリティパッチ適用、バックアップ、スケーリングを自動化するOracleのクラウドデータベースサービス。DBAの運用負担を大幅に削減し、ATPとADWの2種類が提供される。' },
  { term: 'Autonomous Transaction Processing', aliases: ['autonomous transaction processing', 'atp', 'autonomous transaction processing (atp)'], description: 'OLTPワークロード向けに最適化されたOracle Autonomous Databaseのサービスタイプ。混合ワークロードにも対応し、高頻度の短いトランザクション処理をミリ秒レベルのレイテンシで処理できる。' },
  { term: 'Oracle Exadata Cloud Service', aliases: ['oracle exadata cloud service', 'exacs', 'exadata cloud service'], description: 'Exadataハードウェアをクラウドで利用できるOracleのデータベースサービス。超高速なフラッシュストレージとSmart Scan技術により、最大規模のOLTP/分析ワークロードを処理できる。' },
  { term: 'Oracle NoSQL Database Cloud', aliases: ['oracle nosql database cloud', 'oracle nosql cloud', 'nosql database cloud service'], description: 'ドキュメント・キー/バリュー・テーブルデータモデルをサポートするOracleのフルマネージドNoSQLデータベースクラウドサービス。予測可能な低レイテンシとオンデマンドのスループットスケーリングを提供する。' },
  { term: 'OCI Virtual Cloud Network', aliases: ['oci virtual cloud network'], description: 'OCIで定義するソフトウェアベースのプライベートネットワーク。CIDRブロックを指定して作成し、サブネット・ルートテーブル・セキュリティリスト・ゲートウェイなどのネットワーク構成要素を包含するネットワークの基本単位。' },
  { term: 'VCNサブネット', aliases: ['vcnサブネット', 'vcn subnet', 'ociサブネット'], description: 'OCI VCN内に作成するIPアドレス範囲の区画。パブリックサブネットとプライベートサブネットに分類され、それぞれのサブネットにルートテーブルとセキュリティリストを関連付けてトラフィック制御を行う。' },
  { term: 'OCI Load Balancer', aliases: ['oci load balancer', 'ociロードバランサ', 'oci lbaas'], description: 'HTTP/HTTPS/TCPトラフィックを複数のバックエンドサーバーに分散するOCIのマネージドL7ロードバランササービス。SSL終端、セッション維持、ヘルスチェック、WAF連携などの機能を持つ。' },
  { term: 'OCI Network Load Balancer', aliases: ['oci network load balancer'], description: '超低レイテンシでTCP/UDP/ICMPトラフィックを処理するOCIのL4ロードバランササービス。パケット変換なしのパススルー構成もサポートし、高スループットなネットワーク系ワークロードに適する。' },
  { term: 'OCI Flexible Load Balancer', aliases: ['oci flexible load balancer', 'フレキシブルロードバランサ', 'flexible lb'], description: '帯域幅を10Mbpsから8Gbpsまで柔軟に指定できるOCI Load Balancerの形態。使用帯域に応じた課金形式ではなくプロビジョニング帯域に基づく課金となり、予測可能なコスト管理が可能。' },
  { term: 'Dynamic Routing Gateway', aliases: ['dynamic routing gateway', '仮想ルーター'], description: 'OCIのVCNに接続する仮想ルーティングコンポーネントで、オンプレミスネットワーク・他VCN・Oracleサービスとの通信を一元的に管理する。DRGv2では複数VCNのルーティングテーブルを柔軟に制御できる。' },
  { term: 'OCI FastConnect', aliases: ['oci fastconnect', 'oracle fastconnect'], description: 'オンプレミスネットワークとOCIをインターネットを経由せずに専用回線で接続するサービス。低レイテンシ・高帯域・安定したスループットを提供し、1Gbps〜100Gbpsの帯域幅オプションがある。' },
  { term: 'OCI VPN Connect', aliases: ['oci vpn connect', 'vpn connect'], description: 'OCIとオンプレミスネットワークをIPSec VPNトンネルで接続するサービス。DRGを介してサイト間のセキュアな通信を確立し、FastConnectの代替または補完として利用される。' },
  { term: 'OCI NAT Gateway', aliases: ['oci nat gateway', 'natゲートウェイ'], description: 'プライベートサブネット内のリソースがパブリックIPを持たずにインターネットへ発信通信できるようにするOCIのゲートウェイ。インバウンド接続は許可しないため、セキュアなアウトバウンド通信を実現する。' },
  { term: 'OCI Service Gateway', aliases: ['oci service gateway', 'サービスゲートウェイ'], description: 'OCIのVCN内リソースがインターネットやNATゲートウェイを経由せずにOracle Servicesネットワーク（Object StorageやATPなど）へアクセスできるゲートウェイ。通信はOracleのバックボーンネットワーク内に閉じる。' },
  { term: 'OCI Internet Gateway', aliases: ['oci internet gateway', 'インターネットゲートウェイ'], description: 'OCI VCNのパブリックサブネット内リソースとインターネット間の双方向通信を可能にするゲートウェイコンポーネント。パブリックIPが割り当てられたインスタンスがインターネットと直接通信する際に使用する。' },
  { term: 'OCI Local Peering Gateway', aliases: ['oci local peering gateway', 'lpg'], description: '同一リージョン内の異なるOCI VCN同士をプライベートに接続するためのゲートウェイコンポーネント。ローカルVCNピアリングを確立し、インターネットを経由せずにVCN間トラフィックをルーティングする。' },
  { term: 'OCI Remote Peering', aliases: ['oci remote peering', 'remote vcn peering', 'リモートピアリング'], description: '異なるリージョン間のOCI VCNをDRGを介してプライベートに接続するリモートVCNピアリング。クロスリージョンのプライベート通信を実現し、ディザスタリカバリや地理的に分散した構成に使われる。' },
  { term: 'OCI DNS', aliases: ['oci dns', 'oracle dns', 'oci dnsサービス'], description: 'パブリックおよびプライベートDNSゾーンを管理するOCIのDNSサービス。インターネット向けドメイン名解決のほか、VCN内のプライベートDNSゾーン管理やトラフィック管理（Traffic Management）機能も提供する。' },
  { term: 'OCI WAF', aliases: ['oci waf', 'web application firewall', 'wafサービス'], description: 'Webアプリケーションへの悪意あるHTTPトラフィック（SQLインジェクション、XSSなど）をフィルタリングするOCIのマネージドWAFサービス。OWASPトップ10への対策ルール、ボット管理、アクセス制御機能を持つ。' },
  { term: 'OCI DDoS Protection', aliases: ['oci ddos protection', 'ddos保護'], description: '分散型サービス妨害（DDoS）攻撃からOCIリソースを守る保護機能。ボリューム攻撃や接続フラッド攻撃を検知・緩和し、Always-On型の保護をパブリックIPに自動適用する。' },
  { term: 'OCIコンパートメント', aliases: ['ociコンパートメント', 'oci compartment'], description: 'OCIリソースを論理的にグループ化し、アクセス制御・コスト管理・ポリシー適用の単位とする組織構造。階層的にネストでき、本番・開発環境の分離やチーム別権限管理に活用される。' },
  { term: 'OCIテナンシ', aliases: ['ociテナンシ', 'oci tenancy', 'テナンシ'], description: 'OCIアカウントに対応するルートコンパートメント。すべてのリソースとコンパートメントはテナンシ配下に存在する。テナンシ管理者はすべてのリソースへのフルアクセスを持つ最上位のIAMエンティティ。' },
  { term: 'OCI Identity and Access Management', aliases: ['oci identity and access management', 'oci iam', 'oracle iam'], description: 'OCIリソースへのアクセスを制御するID管理サービス。ユーザー・グループ・動的グループ・ポリシーを使ってWho Can Do What on Which Resourcesを定義し、最小権限の原則を実現する。' },
  { term: 'OCIグループ', aliases: ['ociグループ', 'oci group'], description: 'OCI IAMでユーザーをまとめる論理単位。グループにポリシーを適用することで、メンバーユーザー全員に同じ権限を付与できる。ユーザーは複数のグループに所属可能。' },
  { term: 'OCI動的グループ', aliases: ['oci動的グループ', '動的グループ'], description: 'Computeインスタンスなどのクラウドリソースを属性（コンパートメントやタグ）に基づいて動的に含めるIAMグループ。リソースが自律的にAPIを呼び出す際に使用するインスタンスプリンシパルに必要。' },
  { term: 'インスタンスプリンシパル', aliases: ['instance principal'], description: 'OCIのComputeインスタンスがAPIキーなしに他のOCIサービスへアクセスできる仕組み。インスタンスを動的グループに追加し、そのグループへのポリシーを設定することで実現する。' },
  { term: 'OCIコンソール', aliases: ['ociコンソール', 'oci console', 'oracle cloud console'], description: '【OCI】WebブラウザからOCIリソースの作成・管理・監視を行うためのグラフィカルUIポータル。コンパートメント・リージョン切り替えや、リソースのプロビジョニング・設定変更をGUIで操作できる。 【OCI APEX】OCI全体を管理するブラウザ画面。' },
  { term: 'OCI CLI', aliases: ['oci cli', 'oracle cloud cli', 'oci-cli'], description: 'コマンドラインからOCIリソースを操作するためのPython製CLIツール。スクリプト自動化・CI/CDパイプラインへの組み込みが可能で、OCIコンソールのほぼすべての操作をコマンドで実行できる。' },
  { term: 'OCI Logging', aliases: ['oci logging', 'ociログ', 'oracle logging'], description: 'OCIサービスのログ（監査ログ・サービスログ・カスタムログ）を一元管理するサービス。ログの保存・検索・分析が可能で、Service Connectorを使ってObject StorageやOSS（Streaming）に転送できる。' },
  { term: 'OCI Audit', aliases: ['oci audit', 'audit service', 'ociオーディット'], description: 'OCIで行われたすべてのAPI呼び出しを記録するガバナンスサービス。誰がいつどのリソースにどのような操作を行ったかを追跡でき、コンプライアンス要件への対応やセキュリティインシデント調査に使われる。' },
  { term: 'OCI Notifications', aliases: ['oci notifications', 'notifications service', 'ociノーティフィケーション'], description: 'OCI内のイベントやアラームのメッセージをEメール・SMS・PagerDuty・Slackなどのエンドポイントに配信するPub/Subメッセージングサービス。トピックとサブスクリプションの概念で配信先を管理する。' },
  { term: 'OCI Events', aliases: ['oci events', 'events service', 'ociイベント'], description: 'OCIリソースの状態変化（インスタンス起動、オブジェクトアップロードなど）を検知してルールに基づきアクションを起動するイベント駆動サービス。OCI FunctionsやNotificationsと組み合わせて自動化パイプラインを構築する。' },
  { term: 'OCI Resource Manager', aliases: ['oci resource manager', 'ociリソースマネージャ'], description: 'Terraformを用いてOCIリソースをコードとして管理（IaC）するマネージドサービス。スタック単位でTerraformコードを管理し、プラン・適用・破棄の操作をコンソールやAPIから実行できる。' },
  { term: 'OCI Vault', aliases: ['oci vault', 'oracle vault', 'key vault'], description: '暗号化キーとシークレット（パスワード、APIキーなど）を安全に管理するOCIのマネージドサービス。HSMまたはソフトウェア保護のキーを作成・ローテーション・廃棄でき、他OCIサービスとのネイティブ統合を持つ。' },
  { term: 'OCI Bastion', aliases: ['oci bastion', 'bastion service', 'ociバスティオン'], description: 'パブリックIPを持たないプライベートリソースへの一時的なSSHアクセスを提供するOCIのマネージドサービス。踏み台サーバーの運用が不要になり、セッションの時間制限や監査機能でセキュアなアクセス管理を実現する。' },
  { term: 'OCI Cloud Shell', aliases: ['oci cloud shell', 'ociクラウドシェル'], description: 'Webブラウザ上で利用できるOCI管理用の無料マネージドBashシェル。OCI CLIやTerraformなど主要ツールがプリインストールされており、インスタンスやキーの設定なしにOCI操作を始められる。' },
  { term: 'Oracle ORDS', aliases: ['oracle ords', 'ords', 'oracle rest data services'], description: '【OCI】Oracle DatabaseのテーブルやプロシージャをREST APIとして公開するミドルウェア。Autonomous Databaseに標準搭載されており、データベースをバックエンドとするAPIをコーディング不要で作成できる。 【OCI APEX】HTTPとOracle DatabaseをつなぐOracleのREST基盤。' },
  { term: 'OCI Streaming', aliases: ['oci streaming', 'oracle streaming', 'streaming service'], description: '大規模なリアルタイムデータストリームを処理するApache Kafka互換のOCIマネージドサービス。IoTデータ収集・ログ集約・イベントソーシングなどのユースケースで使われ、KafkaクライアントをそのままOCIに移行できる。' },
  { term: 'OCI Queue', aliases: ['oci queue', 'queue service', 'ociキュー'], description: '生産者と消費者を非同期に接続するOCIのマネージドメッセージキューサービス。At-least-once配信を保証し、可視タイムアウトやデッドレターキューを備えるためワークロードの分離・バッファリングに適する。' },
  { term: 'OCI Search with OpenSearch', aliases: ['oci search with opensearch', 'oracle opensearch'], description: 'OpenSearchをベースにしたOCIのマネージド全文検索・分析サービス。クラスターのプロビジョニング・パッチ・スケーリングをOracleが管理し、アプリケーションへの全文検索・ログ分析機能を容易に統合できる。' },
  { term: 'OCI Data Flow', aliases: ['oci data flow', 'oracle data flow'], description: 'Apache Sparkのコードをサーバーレスで実行するOCIのフルマネージドビッグデータサービス。クラスターのセットアップなしにSparkジョブをサブミットでき、Object Storageとネイティブに連携する。' },
  { term: 'OCI Data Integration', aliases: ['oci data integration', 'oracle data integration', 'odi cloud'], description: 'GUIベースのETL/ELTパイプラインを構築・実行するOCIのデータ統合サービス。データソース間の変換・ロードを視覚的に設計でき、Autonomous Database・Object Storageなど複数のOCIサービスと連携する。' },
  { term: 'OCI GoldenGate', aliases: ['oci goldengate', 'oracle goldengate cloud'], description: '異種データベース間のリアルタイムデータレプリケーションと変更データキャプチャ（CDC）を提供するOCIのマネージドサービス。移行・ゼロダウンタイムアップグレード・リアルタイム分析のデータ同期に使われる。' },
  { term: 'OCI Data Science', aliases: ['oci data science', 'oracle data science', 'data science platform'], description: '機械学習モデルの開発・学習・デプロイを一元管理するOCIのデータサイエンスプラットフォーム。JupyterLabベースのノートブックセッション、モデルカタログ、モデルデプロイ機能を持つ。' },
  { term: 'OCI Language', aliases: ['oci language', 'oracle language service', 'language ai'], description: 'テキストの感情分析・言語検出・キーフレーズ抽出・固有表現認識などの自然言語処理機能をAPIで提供するOCIのAIサービス。モデルのトレーニング不要で事前学習済みモデルをすぐに利用できる。' },
  { term: 'OCI Vision', aliases: ['oci vision', 'oracle vision service', 'vision ai'], description: '画像分類・物体検出・テキスト認識（OCR）などのコンピュータビジョン機能をAPIで提供するOCIのAIサービス。カスタムモデルのトレーニングにも対応し、製造・小売・文書処理など幅広い業種で活用できる。' },
  { term: 'OCI Speech', aliases: ['oci speech', 'oracle speech service', 'speech ai'], description: '音声をテキストに変換する自動音声認識（ASR）機能を提供するOCIのAIサービス。日本語を含む複数言語に対応し、バッチ処理とリアルタイムの両モードで文字起こしを行えるため、コールセンターや動画字幕生成などに活用される。' },
  { term: 'OCIコスト分析', aliases: ['ociコスト分析', 'cost analysis', 'oci cost analysis'], description: 'OCIの利用コストをサービス・コンパートメント・タグなどの軸で可視化・分析するコスト管理ツール。過去の利用実績の確認や予算設定、コスト予測に使い、クラウド支出の最適化を支援する。' },
  { term: 'OCI予算', aliases: ['oci予算', 'oci budget'], description: 'OCIの月次支出に対してアラートしきい値を設定し、予算超過を事前に通知する機能。コンパートメント・タグ・テナンシ全体を対象に複数の予算を定義でき、財務ガバナンスを強化する。' },
  { term: 'Bring Your Own License', aliases: ['bring your own license', 'byol', 'ライセンス持ち込み'], description: 'オンプレミスで保有するOracleソフトウェアライセンスをOCIに持ち込んで利用するライセンスモデル。新規ライセンス購入不要でライセンスコストを削減でき、専用VMホストや特定のDBサービスで利用可能。' },
  { term: 'OCIユニバーサルクレジット', aliases: ['ociユニバーサルクレジット', 'universal credits', 'oci universal credits'], description: 'あらかじめ購入したクレジットをOCIの任意のサービス消費に充当できる料金モデル。コミット量に応じた割引が適用され、年間・月間契約で事前購入するとオンデマンド料金より安価になる。' },
  { term: 'Free Tier', aliases: ['free tier', 'oci free tier', 'always free'], description: 'OCIが無期限で無料提供するAlways Freeリソースと、30日間の試用クレジットを組み合わせたプログラム。Always FreeにはAMD・Arm型Computeインスタンス、Block Volume、Object Storage、Autonomous Databaseなどが含まれる。' },
  { term: 'OCIマーケットプレイス', aliases: ['ociマーケットプレイス', 'oci marketplace', 'oracle marketplace'], description: 'サードパーティベンダーやOracleが提供するソフトウェアイメージ・スタック・サービスをOCI上に簡単にデプロイできるカタログ。商用ライセンス付きと無償のオファリングが混在し、数クリックでインスタンスを起動できる。' },
  { term: 'Oracle Integration Cloud', aliases: ['oracle integration cloud', 'oic', 'oracle integration'], description: 'SaaSアプリケーションやオンプレミスシステム間のインテグレーションをノーコード/ローコードで構築するOCIのiPaaSサービス。事前構築済みアダプターを多数持ち、プロセス自動化やAPI管理機能も統合する。' },
  { term: 'OCI Container Registry', aliases: ['oci container registry', 'oracle container registry'], description: '【OCI】Dockerコンテナイメージをプライベートまたはパブリックで管理するOCIのフルマネージドコンテナレジストリ。OKEやCI/CDパイプラインと統合し、脆弱性スキャン機能も提供する。 【OCI APEX】コンテナイメージを保存するレジストリ。' },
  { term: 'OCI DevOps', aliases: ['oci devops', 'oracle devops'], description: 'OCI上でCI/CDパイプラインを構築・管理するDevOpsプラットフォーム。ビルドパイプライン・デプロイパイプライン・コードリポジトリ・アーティファクトレジストリを一元管理し、Kubernetesや関数へのデプロイを自動化する。' },
  { term: 'OCI Interconnect', aliases: ['oci interconnect', 'oracle interconnect', 'リージョン間接続'], description: 'OCI内の異なるリージョン間をプライベートに高速接続するOracleのバックボーンネットワーク。リモートVCNピアリングやクロスリージョンDRG接続の通信経路として機能し、インターネットを経由しない低レイテンシ通信を保証する。' },
  { term: 'OCIリザーブドキャパシティ', aliases: ['ociリザーブドキャパシティ', 'reserved capacity', 'capacity reservation'], description: '特定の可用性ドメインやフォルトドメインにComputeインスタンス起動のためのキャパシティを事前に確保する機能。需要ひっ迫時でも確実にインスタンスを起動できる保証を得られ、ミッションクリティカルな用途に使われる。' },
  { term: 'OCIプリエンプティブルインスタンス', aliases: ['ociプリエンプティブルインスタンス', 'preemptible instance', 'プリエンプティブルインスタンス'], description: '通常の低コストで利用できるが、クラウド側の都合でいつでも停止される可能性があるOCIのComputeインスタンス形態。スポットインスタンスに相当し、バッチ処理や耐障害性のある非同期ワークロードに最適。' },
  { term: 'OCI GPU インスタンス', aliases: ['oci gpu インスタンス', 'gpu instance', 'gpu shape'], description: 'NVIDIA GPUを搭載したOCI Computeインスタンス。機械学習トレーニング・推論・HPC・レンダリングなどGPU並列計算が必要なワークロード向けに提供される。A10・A100・H100など複数のGPUモデルが選択可能。' },
  { term: 'OCPU', aliases: ['ocpu', 'oracle cpu', 'ocpuコア'], description: '【OCI】Oracleクラウドのコア数単位。1 OCPUは物理コア1つ（ハイパースレッディング有効時は2つの仮想CPU）に相当する。OCI Compute・Autonomous Databaseなど多くのサービスでリソース量の基本単位として使われる。 【OCI APEX】Oracle系サービスで使われるCPU容量の単位。' },
  { term: 'OCI Exadata Cloud@Customer', aliases: ['oci exadata cloud@customer', 'exacc', 'exadata cloud@customer'], description: 'Exadataインフラをオンプレミスのデータセンターに設置しながらOracle Cloudとして管理・課金するサービス。データをクラウドに移動できない規制要件がある場合でもExadataの性能とクラウドの管理性を両立できる。' },
  { term: 'OCI Zero Trust Packet Routing', aliases: ['oci zero trust packet routing', 'zpr', 'zero trust packet routing'], description: 'ネットワークレイヤーとセキュリティポリシーを分離し、セキュリティ属性タグに基づいてパケットを制御するOCIのゼロトラストセキュリティ機能。ネットワーク設定変更なしに細かなセキュリティポリシーを適用できる。' },
  { term: 'OCI Security Zones', aliases: ['oci security zones', 'セキュリティゾーン'], description: '特定のコンパートメントにセキュリティレシピを適用し、インターネット公開やパブリックバケット作成などの危険な操作を防止するOCIのガードレール機能。クラウドセキュリティの構造的強制を実現する。' },
  { term: 'OCI Cloud Guard', aliases: ['oci cloud guard', 'クラウドガード'], description: 'OCIリソースの設定ミスや脅威を継続的に検知・報告・修正するCNAPP（Cloud Native Application Protection Platform）サービス。検出器がリスクを発見するとレスポンダーが自動的に修正アクションを実行する。' },
  { term: 'OCI Vulnerability Scanning', aliases: ['oci vulnerability scanning', 'vulnerability scanning'], description: 'OCIのComputeインスタンスとコンテナイメージの脆弱性を定期的にスキャンするセキュリティサービス。CVEデータベースと照合した結果を重大度別に報告し、Cloud Guardと連携してリスクを管理する。' },
  { term: 'OCI Certificates', aliases: ['oci certificates', 'certificates service', 'ociサーティフィケーツ'], description: '【OCI】TLS/SSL証明書のプロビジョニング・更新・デプロイを一元管理するOCIのマネージド証明書サービス。Let\'s Encryptや独自CAからの証明書を管理でき、OCI Load BalancerへのSSL終端設定と統合する。 【OCI APEX】OCIで証明書やCAを管理するサービス。' },
  { term: 'OCI Web Application Firewall Policy', aliases: ['oci web application firewall policy', 'waf policy', 'wafポリシー'], description: 'OCI WAFで適用するセキュリティルールセットを定義するオブジェクト。保護ルール・アクセス制御・レート制限・ボット管理の設定を含み、ロードバランサやCDN配信エンドポイントに関連付けて適用する。' },
  { term: 'OCI Email Delivery', aliases: ['oci email delivery', 'email delivery', 'ociメール配信'], description: 'アプリケーションから大量メールを送信するためのマネージドSMTPリレーサービス。SPF・DKIMによる送信ドメイン認証設定、バウンスや苦情の管理機能を持ち、高いメール到達率を実現する。' },
  { term: 'OCIダイナミックグループ', aliases: ['ociダイナミックグループ', 'oci dynamic group'], description: 'OCI上のコンピュートインスタンスなどのリソースを動的にグループ化し、IAMポリシーを適用できる仕組みです。リソースへの権限管理を柔軟に行えます。' },
  { term: 'OCI予約済みキャパシティ', aliases: ['oci予約済みキャパシティ', 'oci reserved capacity'], description: '特定のOCIアベイラビリティドメインでコンピュートキャパシティを事前予約する機能です。必要な時に確実にリソースを確保できます。' },
  { term: 'OCI Logging Analytics', aliases: ['oci logging analytics', 'oracle cloud infrastructure logging analytics'], description: '機械学習を活用してOCIおよびオンプレミスのログを分析し、異常検知やパターン抽出を行うサービス。ログエクスプローラによる視覚的分析とカスタムアラートの設定ができる。' },
  { term: 'OCI Application Performance Monitoring', aliases: ['oci application performance monitoring', 'apm', 'oci apm'], description: '分散トレーシング・合成モニタリング・リアルユーザーモニタリングを統合してアプリケーションのパフォーマンスを可視化するOCIサービス。レイテンシのボトルネック特定に役立つ。' },
  { term: 'OCI Connector Hub', aliases: ['oci connector hub', 'oracle cloud infrastructure connector hub'], description: 'OCIサービス間のデータ移動とイベント連携を設定ベースで構築するマネージドサービス。LoggingからObject StorageへのアーカイブやStreamingからFunctionsへのルーティングを簡単に設定できる。' },
  { term: 'OCIスタック', aliases: ['ociスタック', 'oci stack', 'resource manager stack'], description: 'OCI Resource Manager上でTerraform設定ファイルを管理する単位。スタックを適用することでOCIリソースが作成され、Destroyで削除できるライフサイクル管理の基本単位。' },
  { term: 'Terraform on OCI', aliases: ['terraform on oci', 'oci terraform provider'], description: 'HashiCorp TerraformのOCIプロバイダを使ってOracle Cloud Infrastructureのリソースをコードで管理する手法。OCI Resource Manager上でも動作し、CI/CDとの統合が可能。' },
  { term: 'OCI Data Safe', aliases: ['oci data safe', 'oracle cloud infrastructure data safe'], description: 'Oracle Databaseのセキュリティを管理するサービス。センシティブデータの検出・マスキング、セキュリティアセスメント、アクティビティ監査、ユーザーリスク管理機能を提供する。' },
  { term: 'OCI Data Catalog', aliases: ['oci data catalog', 'oracle cloud infrastructure data catalog'], description: 'データ資産のメタデータを収集・管理するサービス。テクニカルメタデータとビジネスメタデータを統合し、データの検索・分類・系譜追跡を可能にしてデータガバナンスを支援する。' },
  { term: 'OCI AI Services', aliases: ['oci ai services', 'oracle cloud infrastructure ai services'], description: '事前トレーニング済みモデルを利用した各種AI機能をREST APIで提供するOCIサービス群の総称。Language・Vision・Speech・Anomaly DetectionなどのドメインAIを含む。' },
  { term: 'OCI Anomaly Detection', aliases: ['oci anomaly detection', 'oracle cloud infrastructure anomaly detection'], description: '時系列データの異常をAIで自動検出するマネージドサービス。独自データでモデルをトレーニングし、IoTセンサーや運用メトリクスの外れ値検知に利用できるOCIのAIサービス。' },
  { term: 'OCI Document Understanding', aliases: ['oci document understanding', 'oracle cloud infrastructure document understanding'], description: '請求書・レシート・運転免許証などのドキュメントからテキスト・表・フォームデータをAIで抽出するサービス。事前構築モデルとカスタムモデルによる処理をサポートする。' },
  { term: 'OCI Generative AI', aliases: ['oci generative ai', 'oracle cloud infrastructure generative ai', 'oci gen ai'], description: 'LLMを活用したテキスト生成・要約・埋め込みをAPI経由で提供するOCIのジェネレーティブAIサービス。Meta LlamaやCohereなどの基盤モデルをホストし、プライベートエンドポイントでのアクセスが可能。' },
  { term: 'OCI Digital Assistant', aliases: ['oci digital assistant', 'oracle digital assistant'], description: 'チャットボットと音声ボットを構築・デプロイするOCIのAIプラットフォーム。NLPエンジン・スキルとフロー設計・Slack/Teamsなど複数チャネルへの統合機能を提供する。' },
  { term: 'OCI Artifact Registry', aliases: ['oci artifact registry', 'oracle cloud infrastructure artifact registry'], description: 'コンテナイメージ以外のビルド成果物（Helmチャート・汎用アーティファクトなど）をバージョン管理付きで保存・配布するOCIのリポジトリサービス。DevOpsパイプラインと統合して使う。' },
  { term: 'OCI Build Pipeline', aliases: ['oci build pipeline', 'oracle cloud infrastructure build pipeline'], description: 'OCI DevOpsサービスのCI機能。コードのビルド・テスト・アーティファクト生成を自動化するステージを定義し、コードリポジトリへのプッシュをトリガーにして実行できる。' },
  { term: 'OCI Deployment Pipeline', aliases: ['oci deployment pipeline', 'oracle cloud infrastructure deployment pipeline'], description: 'OCI DevOpsサービスのCD機能。OKEやFunctionsなどのターゲット環境にアーティファクトをデプロイするステージを定義し、カナリアやブルーグリーンなどのデプロイ戦略を設定できる。' },
  { term: 'OCI Visual Builder', aliases: ['oci visual builder', 'oracle visual builder'], description: 'WebアプリケーションとモバイルアプリをローコードGUIで構築するOCIのプラットフォーム。REST APIとの統合・ページデザイン・ビジネスロジックをビジュアルに設定できる。' },
  { term: 'OCI Content Management', aliases: ['oci content management', 'oracle content management'], description: 'デジタルコンテンツとアセットを一元管理するOCIのクラウドCMSサービス。ヘッドレスCMS・ドキュメント管理・デジタルアセット管理を統合し、マルチチャネルへのコンテンツ配信を支援する。' },
  { term: 'Oracle Blockchain Platform', aliases: ['oracle blockchain platform', 'obp'], description: 'Hyperledger Fabricベースのエンタープライズブロックチェーンネットワークを構築・管理するOCIのマネージドサービス。スマートコントラクトのデプロイとネットワーク参加者の管理を簡素化する。' },
  { term: 'OCI Health Checks', aliases: ['oci health checks', 'oracle cloud infrastructure health checks'], description: 'グローバルな複数拠点からHTTP・TCPのヘルスチェックを実行してエンドポイントの可用性を監視するサービス。レスポンスタイムとアップタイムを記録し、障害時にアラートを送信できる。' },
  { term: 'OCI Network Visualizer', aliases: ['oci network visualizer', 'oracle cloud infrastructure network visualizer'], description: 'OCIテナンシのネットワークリソースとその接続関係をグラフィカルに可視化するツール。VCN・サブネット・ゲートウェイ・ピアリングの構成をダイアグラムとして表示し、設計確認に役立つ。' },
  { term: 'OCI Network Path Analyzer', aliases: ['oci network path analyzer', 'oracle cloud infrastructure network path analyzer'], description: 'OCIネットワーク上の送信元から宛先へのトラフィック経路を分析し、セキュリティリスト・NSG・ルートテーブルによる通信可否を視覚的に確認するトラブルシューティングツール。' },
  { term: 'OCIクォータ', aliases: ['ociクォータ', 'oci quota', 'oci service quota'], description: 'OCIリソースの使用量を制限するポリシー。テナンシまたはコンパートメントレベルでリソース数の上限を設定し、特定のチームやプロジェクトが過剰にリソースを消費しないよう制御する。' },
  { term: 'OCI Dedicated Region', aliases: ['oci dedicated region', 'oracle dedicated region cloud@customer'], description: '顧客のデータセンターにOracle Cloud全サービスをプライベートに提供するデプロイメントオプション。パブリッククラウドと同一のAPIと価格で、データレジデンシ要件が厳格な業界に対応する。' },
  { term: 'OCI Roving Edge Infrastructure', aliases: ['oci roving edge infrastructure', 'oci roving edge device'], description: 'ネットワーク接続のない遠隔地や移動中の環境でOCIワークロードを実行するハードウェアアプライアンス。船舶・軍事施設・石油掘削基地などで使用し、後でOCIにデータを同期する。' },
  { term: 'Oracle Database@Azure', aliases: ['oracle database@azure', 'oracledb@azure'], description: 'Microsoft AzureのデータセンターにOracle Exadataインフラを直接配置し、AzureネイティブサービスとOracle Databaseを超低レイテンシで統合するマルチクラウドソリューション。' },
  { term: 'OCIマルチクラウド', aliases: ['ociマルチクラウド', 'oci multicloud'], description: 'OCIをAzure・AWSなど他クラウドプロバイダと組み合わせて使うアーキテクチャ戦略。Oracle Interconnectを通じた高速プライベート接続でクラウド間のネットワーク遅延を最小化する。' },
  { term: 'OCI NoSQL Database', aliases: ['oci nosql database', 'oracle nosql database cloud service'], description: '予測可能な低レイテンシで動作するフルマネージドのスキーマレスNoSQLサービス。テーブル・JSON・Key-Valueデータモデルをサポートし、読み取り・書き込みキャパシティユニットで課金される。' },
  { term: 'OCI Cache', aliases: ['oci cache', 'oci cache with redis'], description: 'Redis互換のフルマネージドインメモリキャッシュサービス。アプリケーションのレスポンスタイム改善やDBの負荷軽減に使用し、クラスター構成による高可用性をサポートする。' },
  { term: 'OCI Auto Scaling', aliases: ['oci auto scaling', 'oracle cloud infrastructure autoscaling'], description: 'CPU使用率などのメトリクスやスケジュールに基づいてインスタンスプールのサイズを自動調整するOCIの機能。需要のピーク時に自動でスケールアウトし、コスト最適化のためにスケールインする。' },
  { term: 'OCI SDK', aliases: ['oci sdk', 'oci software development kit'], description: 'Java・Python・TypeScript/JavaScript・Go・Ruby・.NETなど複数言語向けに提供されるOCI操作用ライブラリ。署名認証・ページネーション・リトライ処理などを組み込みで提供する。' },
  { term: 'OCI Resource Principal', aliases: ['oci resource principal', 'resource principal'], description: '【OCI】OCI FunctionsやコンピュートインスタンスなどのOCIリソース自身にIAMポリシーを付与し、APIキーなしでOCIサービスにアクセスできるようにする認証メカニズム。インスタンスプリンシパルを一般化したもの。 【OCI APEX】リソース自身にAPI呼び出し権限を持たせる仕組み。' },
  { term: 'OCI Tag Namespace', aliases: ['oci tag namespace', 'tag namespace', 'oci defined tags'], description: 'OCIリソースに定義済みタグを付与するためのスキーマ。タグ名前空間・タグキー・バリデータを定義し、コスト配賦・アクセス制御・リソース検索に活用する構造化されたメタデータ管理基盤。' },
  { term: 'OCI Work Request', aliases: ['oci work request', 'work request'], description: 'OCIの非同期API操作の進捗状態を追跡するための仕組み。長時間かかるリソース作成・削除などのオペレーションは即座にWork Request IDを返し、ポーリングで完了状態を確認できる。' },
  { term: 'OCI Disaster Recovery', aliases: ['oci disaster recovery', 'oci full stack dr', 'full stack disaster recovery'], description: 'アプリケーション全体のDR計画と自動フェイルオーバーをオーケストレーションするOCIサービス。DR保護グループとDRプランを定義し、リージョン間フェイルオーバーをワンクリックで実行できる。' },
  { term: 'OCI Data Transfer Service', aliases: ['oci data transfer service', 'oracle cloud infrastructure data transfer service'], description: '大容量データを物理的なアプライアンスデバイスを使ってOCIに移行するサービス。インターネット経由では時間がかかる数TB以上のデータ移行に適し、暗号化されたデバイスを郵送してOCIにアップロードする。' },
  { term: 'OCI Storage Gateway', aliases: ['oci storage gateway', 'oracle cloud infrastructure storage gateway'], description: 'オンプレミスのNFS/SMBクライアントからOCI Object Storageをファイルシステムとして使えるようにするソフトウェアアプライアンス。データのキャッシュとライフサイクル管理を透過的に提供する。' },
  { term: 'OCI Operations Insights', aliases: ['oci operations insights', 'oracle cloud infrastructure operations insights', 'opsi'], description: 'データベースとホストの長期的なリソース使用率・キャパシティ・SQLパフォーマンスを分析するOCIサービス。機械学習で将来のリソース不足を予測し、データベースのワークロード最適化を支援する。' },
  { term: 'OCI Database Management', aliases: ['oci database management', 'oracle cloud infrastructure database management'], description: 'Oracle DatabaseのフリートをOCIコンソールから一元管理するサービス。パフォーマンスハブ・SQLチューニングアドバイザ・ユーザー管理・メモリ管理をOCI上のDBとオンプレミスDBに統合して提供する。' },
  { term: 'OCI Service Mesh', aliases: ['oci service mesh', 'oracle cloud infrastructure service mesh'], description: 'Envoyサイドカープロキシに基づくマネージドサービスメッシュ。OKE上のマイクロサービス間通信のmTLS暗号化・トラフィック管理・可観測性を実現し、Kubernetesネイティブな設定APIで管理する。' },
  { term: 'OCI Managed Access', aliases: ['oci managed access', 'oracle cloud infrastructure managed access'], description: '外部パートナーやサードパーティベンダーにOCIリソースへの時限付きアクセスを許可するガバナンスサービス。アクセスリクエスト・承認ワークフロー・監査記録を管理し最小権限の外部アクセスを実現する。' },
  { term: 'OCI GoldenGate Microservices', aliases: ['oci goldengate microservices', 'goldengate microservices architecture'], description: 'Oracle GoldenGateをREST APIとWebUIで管理するマイクロサービスアーキテクチャ版。Service Manager・Admin Server・Distribution Server・Receiver Serverを独立プロセスとして分離しスケール管理しやすくした設計。' },
  { term: 'OCI Big Data Service', aliases: ['oci big data service', 'oracle cloud infrastructure big data service', 'oci bds'], description: 'フルマネージドのHadoopおよびSparkクラスターをOCI上で展開するサービス。HDFS・YARN・Hive・SparkをOCIコンピュート上に自動構築し、Object Storageとの連携とHA構成をサポートする。' },
  { term: 'OCI Search Service', aliases: ['oci search service', 'oci search service with opensearch'], description: 'OpenSearch（Elasticsearch互換）をフルマネージドで提供するOCIのサービス。ログ分析・全文検索・ダッシュボードをマネージドクラスターで利用でき、インデックス管理を簡素化する。' },
  { term: 'OCI Media Services', aliases: ['oci media services', 'oracle cloud infrastructure media services'], description: '動画ファイルのトランスコーディング・配信・ストリーミングをマネージドで提供するOCIサービス。Media Flow（ワークフロー管理）とMedia Streams（HLS/DASHライブ配信）で構成される。' },
  { term: 'OCI Kubernetes Cluster Autoscaler', aliases: ['oci kubernetes cluster autoscaler', 'oke cluster autoscaler'], description: 'OKEのノードプールをPodのリソース要求に応じて自動的に増減するKubernetesのクラスターオートスケーラー。スケジュール不可なPod発生時にノードを追加し、不要なノードを削除してコストを最適化する。' },
  { term: 'OCI BYOI', aliases: ['oci byoi', 'bring your own image', 'oci custom image'], description: 'オンプレミスや他クラウドの仮想マシンイメージ（VMDK・VHD・Qcow2）をOCIにインポートしてカスタムイメージとして使う機能。既存環境のクラウドリフト移行を容易にする。' },
  { term: 'OCI Shielded Instances', aliases: ['oci shielded instances', 'shielded instances'], description: 'セキュアブート・TPMチップ・Measured Bootを活用してブートプロセスの完全性を検証するOCIのセキュアコンピュートインスタンス機能。ルートキットやブートキットによる改ざんを防止する。' },
  { term: 'OCI Confidential Computing', aliases: ['oci confidential computing', 'confidential instances'], description: 'AMD SEV-SNPまたはIntel TDX技術を使って、実行中のデータをメモリ上で暗号化し管理者やクラウドプロバイダからも保護するOCIのセキュアエンクレーブコンピュート機能。' },
  { term: 'OCI Process Automation', aliases: ['oci process automation', 'oracle cloud infrastructure process automation'], description: 'ローコードでビジネスプロセスを設計・自動化するOCIのワークフローサービス。承認フロー・タスク割り当て・SLA管理をビジュアルなプロセスデザイナーで構築し、Oracle Integration Cloudと補完関係にある。' },
  { term: 'OCIアラーム', aliases: ['ociアラーム', 'oci alarm', 'oci monitoring alarm'], description: 'OCI Monitoringでメトリクスの閾値条件を定義し、条件が満たされたときにOCI Notificationsを通じてアラートを送信するリソース。アラーム状態の遷移ごとに通知を制御できる。' },
  { term: 'OCIメトリクス', aliases: ['ociメトリクス', 'oci monitoring metrics'], description: 'OCI Monitoringサービスが収集するリソースの定量的なパフォーマンス指標。CPUUtilizationなどの組み込みメトリクスと、エージェントやSDK経由で送信するカスタムメトリクスがある。' },
  { term: 'OCI Loggingサービスログ', aliases: ['oci loggingサービスログ', 'oci service log', 'oci log category'], description: 'OCI Loggingが各OCIサービスから自動収集するリソース固有のログカテゴリ。VCNフローログ・API GatewayアクセスログなどOCIサービスが生成するログをロギングサービスが直接収集する仕組み。' },
  { term: 'OCI Ampere A1', aliases: ['oci ampere a1', 'ampere a1 compute'], description: 'Ampere Altra ARMプロセッサを使用したOCIのコンピュートシェイプ。x86相当以上のパフォーマンスをコスト効率よく提供し、Free Tier枠でも4 OCPUと24GBメモリを利用できる。' },
  { term: 'OCI Bare Metal', aliases: ['oci bare metal', 'bare metal compute'], description: 'ハイパーバイザを介さず物理サーバーを専有するOCIのコンピュートオプション。NVMeローカルディスクや100Gbpsネットワークを直接利用できるため、データベース・HPC・VMwareワークロードに適する。' },
  { term: 'OCI Cloud@Customer', aliases: ['oci cloud@customer', 'cloud@customer'], description: 'Oracle ExadataまたはOCIサービスを顧客のオンプレミスデータセンターに設置するプライベートクラウドサービス。OCIコンソールと同一UXで管理でき、データをクラウドに送らないコンプライアンス要件を満たす。' },
  { term: 'OCI Security Advisor', aliases: ['oci security advisor', 'oracle cloud infrastructure security advisor'], description: 'OCI Vaultとセキュリティゾーンをガイドするセキュリティベストプラクティスのウィザード型ツール。暗号鍵ポリシーやセキュリティゾーン設定の推奨事項を対話形式で提示し、安全な環境構築を支援する。' },
  { term: 'OCI Announcements', aliases: ['oci announcements', 'oracle cloud infrastructure announcements'], description: 'OCI側からメンテナンス・障害・新機能リリースなどの重要なお知らせをテナンシ単位で配信するサービス。フィルタリングしたアナウンスをOCI Notificationsや電子メールで受け取ることができる。' },
  { term: 'OCIサブスクリプション', aliases: ['ociサブスクリプション', 'oci universal credit', 'oci subscription'], description: 'OCI サービスを利用するための契約形態の総称。Pay-as-you-go・Annual Universal Credit・Monthly Flexibleなどがあり、コミット量や期間に応じた割引とクレジット利用ルールが異なる。' },
  { term: 'OCIサービス上限', aliases: ['ociサービス上限', 'oci service limits', 'oci limits'], description: 'テナンシが利用できる各OCIサービスリソースの最大数を定めたデフォルト上限。インスタンス数・IPアドレス数などの上限はOCIコンソールから確認でき、増加リクエストをOracleサポートに申請できる。' },
  { term: 'Oracleサポート', aliases: ['oracleサポート', 'my oracle support', 'oracle cloud support'], description: 'OCIおよびOracle製品に関する技術サポートを提供するOracleの公式サポート体制。Basic・Developer・Business CriticalなどのSLAプランがあり、My Oracle Supportポータルからサービスリクエストを起票できる。' },
  { term: 'OCI Well-Architected Framework', aliases: ['oci well-architected framework', 'oracle well-architected framework'], description: 'OCI上で信頼性・セキュリティ・パフォーマンス・コスト最適化・運用効率の5つの柱に沿ったシステムを設計するためのベストプラクティスフレームワーク。AWSのWell-Architectedに相当するOracleの指針。' },
  { term: 'OCI Landing Zone', aliases: ['oci landing zone', 'oracle landing zone', 'oci landing zone accelerator'], description: 'OCI上に安全でスケーラブルなマルチアカウント環境を素早く構築するためのTerraformテンプレートとアーキテクチャガイドの総称。コンパートメント構造・IAMポリシー・ネットワーク基盤を標準化する。' },
  { term: 'OCI Generative AI Agents', aliases: ['oci generative ai agents', 'oci gen ai agents'], description: 'LLMを使ったRAG（Retrieval-Augmented Generation）エージェントをフルマネージドで構築・デプロイするOCIサービス。OCI Object StorageやOpenSearchを知識ベースとして接続し、自然言語での質疑応答を実現する。' },
  { term: 'OCI Data Labeling', aliases: ['oci data labeling', 'oracle cloud infrastructure data labeling'], description: '機械学習モデルのトレーニングに使うデータセットにラベルを付与・管理するOCIサービス。画像分類・物体検出・テキスト分類のアノテーションをUIまたはAPIで行い、OCI Data Scienceと統合できる。' },
  { term: 'OCI Model Deployment', aliases: ['oci model deployment', 'oci data science model deployment'], description: 'OCI Data ScienceでトレーニングしたモデルをスケーラブルなHTTPエンドポイントとして公開する機能。AutoScalingとロードバランシングで本番推論を高可用性で提供し、ログとメトリクスを統合監視できる。' },
  { term: 'OCI Language Translation', aliases: ['oci language translation', 'oci translation'], description: 'OCI Languageサービスが提供する機械翻訳機能。英語・日本語・スペイン語など複数言語間のテキスト翻訳をREST APIで利用でき、ドキュメント翻訳バッチ処理にも対応する。' },
  { term: 'OCIロググループ', aliases: ['ociロググループ', 'oci log group'], description: 'OCI Loggingでログオブジェクトを論理的にグループ化する管理単位。アクセス制御をロググループ単位で設定でき、Connector HubでロググループごとにObject Storageや外部SIEMへのエクスポートを構成できる。' },
  { term: 'OCIストリーミングコンシューマグループ', aliases: ['ociストリーミングコンシューマグループ', 'streaming consumer group', 'oci streaming consumer group'], description: 'OCI Streamingでメッセージを消費する複数のコンシューマをグループ化し、パーティションを分担させて並列処理を実現する仕組み。Kafkaのコンシューマグループと同等の概念でオフセット管理が自動化される。' },
  { term: 'OCI APM Trace Explorer', aliases: ['oci apm trace explorer', 'apm trace explorer'], description: 'OCI APMが収集した分散トレーシングデータを視覚的に探索するツール。サービス間の呼び出し連鎖をウォーターフォール図で表示し、レイテンシの大きいスパンを特定してパフォーマンス問題を診断できる。' },
  { term: 'OCIコスト管理', aliases: ['ociコスト管理', 'oci cost and usage reports'], description: 'OCIの詳細な使用量と費用を日次・月次でCSVレポートとして自動的にObject Storageに出力する機能。Cost AnalysisやBudgetと組み合わせることで包括的なFinOpsの基盤を構築できる。' },
  { term: 'OCIホームリージョン', aliases: ['ociホームリージョン', 'oci home region'], description: 'OCIテナンシ作成時に指定するプライマリリージョン。IAMリソース（ユーザー・グループ・ポリシー）はホームリージョンに作成され、他リージョンに自動レプリケーションされる。変更は不可能な重要な設定。' },
  { term: 'OCIアクセスポリシー', aliases: ['ociアクセスポリシー', 'oci iam policy statement'], description: 'OCI IAMでグループやリソースプリンシパルがどのOCIリソースに対してどの操作を実行できるかを宣言する文。「Allow group X to manage all-resources in compartment Y」のような構文でアクセス権を付与する。' },
  { term: 'OCI DRGルートテーブル', aliases: ['oci drgルートテーブル', 'drg route table', 'oci drg route distribution'], description: 'OCI Dynamic Routing Gateway内でVCN間や外部接続の経路を細かく制御するルーティングテーブル。インポート・エクスポートルート配布を設定することでハブアンドスポーク型のネットワーク設計を実現する。' },
  { term: 'OCI VCNローカルピアリング', aliases: ['oci vcnローカルピアリング', 'oci lpg peering'], description: '同一リージョン内の2つのVCNをLocal Peering Gateway経由でプライベートに接続する手法。異なるコンパートメントやテナンシのVCN間でもプライベートIPで通信できるよう構成できる。' },
  { term: 'OCI VCNリモートピアリング', aliases: ['oci vcnリモートピアリング', 'oci cross-region vcn peering'], description: '異なるリージョン間のVCNをRemote Peering ConnectionとDRGを経由してプライベートに接続するVCNピアリング手法。マルチリージョンDR構成やグローバルアーキテクチャの拠点間接続に使われる。' },
  { term: 'OCI WAFカスタムルール', aliases: ['oci wafカスタムルール', 'oci waf custom protection rule'], description: 'OCI Web Application Firewallで管理者が独自のHTTPリクエスト条件（ヘッダ・URI・IPアドレスなど）を定義してブロックや許可を行うカスタムルール機能。OWASPルールを補完し特定アプリの要件に対応する。' },
  { term: 'OCI Objectストレージ階層化', aliases: ['oci objectストレージ階層化', 'oci object storage lifecycle', 'oci storage tiering'], description: 'OCI Object Storageのオブジェクトをアクセス頻度に応じてStandard・Infrequent Access・Archiveの3階層間でライフサイクルルールにより自動移行するコスト最適化機能。' },
  { term: 'Autonomous Data Warehouseサービス', aliases: ['autonomous data warehouseサービス', 'oracle adw service'], description: 'OCI Autonomous Databaseのデータウェアハウス特化型サービス。OLAP・バッチ分析クエリ向けに自動チューニングされ、Oracle Analytics Cloudやサードパーティ分析ツールと連携して大規模分析を行う。' },
  { term: 'Autonomous Transaction Processingサービス', aliases: ['autonomous transaction processingサービス', 'oracle atp service'], description: 'OCI Autonomous DatabaseのOLTP特化型サービス。高頻度の短時間トランザクション向けに自動チューニングされ、ERP・モバイルアプリ・Webサービスのバックエンドデータベースとして広く使われる。' },
  { term: 'OCI ExaDB-D', aliases: ['oci exadb-d', 'exadata database service on dedicated infrastructure'], description: 'Exadataハードウェアを顧客専有で利用するOCIのデータベースサービス形態。共有インフラと異なり物理マシンを占有するため最大のパフォーマンスと高度なカスタマイズが可能で、金融系大規模DBに使われる。' },
  { term: 'OCIフローログ', aliases: ['ociフローログ', 'oci vcn flow log', 'vcn flow logs'], description: 'VCNのサブネットを流れるIPトラフィックのメタデータ（送信元・宛先IP・ポート・プロトコル・送受信バイト数）を記録するOCI Loggingの機能。セキュリティ分析やネットワークトラブルシューティングに活用する。' },
  { term: 'OCI Dedicated VM Host', aliases: ['oci dedicated vm host', 'oci dedicated host'], description: '単一テナント専用の物理サーバーを確保してVMを起動するOCIの機能。ハードウェアを他テナントと共有しないため、コンプライアンス要件やBYOLライセンス条件を満たす必要がある場合に使用する。' },
  { term: 'OCI Capacity Reservation', aliases: ['oci capacity reservation', 'oci compute capacity reservation'], description: '特定のAvailability DomainとFault Domainにコンピュートキャパシティを事前予約するOCIの機能。災害復旧シナリオや急なスケールアウトに備えて、必要なときにインスタンスを確実に起動できるよう保証する。' },
  { term: 'OCIコンピュートインスタンスプール', aliases: ['ociコンピュートインスタンスプール', 'oci compute instance pool'], description: '同一構成のコンピュートインスタンスをグループとして管理するOCIの機能。OCI Auto Scalingと組み合わせることで、負荷に応じてインスタンス数を自動的に増減させる水平スケーリングを実現する。' },
  { term: 'OCI Marketplace Publisher', aliases: ['oci marketplace publisher', 'oci marketplace publisher portal'], description: 'ISVやOracleパートナーがOCI Marketplaceにソフトウェア製品を登録・販売するためのポータル。イメージの審査プロセス・ライセンス管理・利用状況レポートを提供しパートナーエコシステムを支援する。' },
  { term: 'OCI Network Firewall', aliases: ['oci network firewall', 'oracle cloud infrastructure network firewall'], description: 'Palo Alto NetworksのNGFWエンジンをベースにしたOCIのマネージドネットワークファイアウォールサービス。URLフィルタリング・IDS/IPS・TLSインスペクションをVCN内に配置してゼロトラストネットワークを実現する。' },
  { term: 'OCI Private DNS', aliases: ['oci private dns', 'oci private dns zone'], description: 'VCN内部のリソース名前解決をカスタムドメインで行うOCIのプライベートDNSゾーン機能。ハイブリッドクラウド環境でオンプレミスとOCIが同一ドメイン体系を共有し、スプリットホライゾンDNSも設定できる。' },
];
