// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: dbSqlTx (1/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // database (206), data-engineering (98), data-store (90), sql (10), Database (3)
  { term: 'DB', aliases: ['db'], description: 'データベースの略で、情報を保存、検索、更新する仕組みです。多くの業務システムでは、画面やAPIの裏側で中心となる存在です。' },
  { term: 'テーブル', aliases: ['table'], description: 'DBの中でデータを表形式で保存する単位です。顧客、注文、申請など、業務上の対象ごとに分けて管理されることが多いです。' },
  { term: 'カラム', aliases: ['column'], description: 'テーブルの列のことです。名前、金額、登録日など、1件のデータが持つ属性を表します。' },
  { term: 'レコード', description: 'テーブルの1行分のデータです。1人の顧客情報や1件の申請情報など、実体を表す単位として使われます。' },
  { term: '主キー', description: 'レコードを一意に識別するための項目です。同じ値が重複しないため、DBの整合性を保つ土台になります。' },
  { term: '外部キー', description: '他のテーブルの主キーを参照することで、関連を表す項目です。親子関係や明細構造を表現するときによく使います。' },
  { term: 'ER図', aliases: ['er図', 'er diagram', 'entity-relationship diagram'], description: 'データ同士の関係を図で表したものです。テーブル設計の前段で、業務上どの情報がどう結びつくかを整理するのに役立ちます。' },
  { term: '論理設計', aliases: ['logical design'], description: '業務上必要なデータ構造や関係を、製品依存を抑えて整理する設計です。まず意味の正しさを整え、その後で物理設計へ落とし込む流れが一般的です。' },
  { term: '物理設計', aliases: ['physical design'], description: '実際のDB製品や実行環境に合わせて、型や長さ、制約、索引などを決める設計です。論理的に正しいだけでなく、性能や運用性も考慮します。' },
  { term: '制約', description: 'データに守らせる条件やルールです。重複禁止、未入力禁止、参照整合性などを制約として定義することで、アプリだけに頼らず品質を保ちます。' },
  { term: 'インデックス', aliases: ['index'], description: 'データ検索を速くするための仕組みです。ただ増やせばよいわけではなく、更新性能や容量への影響もあるため、よく使う検索条件を見て設計します。' },
  { term: 'トランザクション', aliases: ['transaction'], description: '一連の処理をひとまとまりとして扱い、全部成功するか全部失敗するかを保証する仕組みです。途中でエラーが起きたら元に戻すことで、データの整合性を守ります。' },
  { term: 'トランザクション境界', aliases: ['transaction boundary'], description: 'どこからどこまでを1つのトランザクションとするかの範囲です。広すぎると性能や競合に不利になり、狭すぎると整合性が崩れやすくなります。' },
  { term: 'SQLインジェクション', aliases: ['sqlインジェクション', 'sql injection'], description: '入力値を悪用して不正なSQLを実行させる攻撃です。入力値の埋め込み方を誤ると、情報漏えいや破壊につながることがあります。' },
  { term: 'エンティティ', description: '同じ属性値でも識別子で区別される業務対象です。顧客、注文、契約などが代表例で、IDを軸に継続的に追跡されます。' },
  { term: '集約', description: '関連するエンティティや値オブジェクトを、整合性を保つ単位としてまとめたものです。更新ルールやトランザクション境界を考えるうえで重要です。' },
  { term: '集約ルート', description: '集約全体への入口となる代表エンティティです。外部からは原則このルートを通して操作することで、内部整合性を守りやすくします。' },
  { term: 'ルートテーブル', description: 'どの通信をどこへ流すかを決める設定です。外部接続、内部接続、NAT経由など、通信の道筋を明確にします。' },
  { term: 'スロークエリ', description: '実行に時間がかかりすぎるSQLです。インデックス不足やデータ量増加、書き方の問題が原因になることが多いです。' },
  { term: 'ORM', aliases: ['orm'], description: 'DBの表とプログラム上のオブジェクトを対応付けて扱う仕組みです。便利ですが、SQLの実際の動きを理解しないと性能問題に気づきにくくなります。' },
  { term: '自己整合性', description: '同じ条件に対して出力がぶれすぎない性質です。業務利用では創造性より、この一貫性が重要になることが多いです。' },
  { term: 'モデルカード', description: 'モデルの用途、制約、学習背景、注意点などを整理した説明資料です。適材適所で使うための判断材料になります。' },
  { term: 'データ基盤', description: '業務データを収集、保存、加工、分析できるように整える仕組みです。個別システム最適ではなく、全社活用を視野に入れると設計が変わります。' },
  { term: 'データレイク', description: 'さまざまな形式の生データを大きく保存する場所です。柔軟性は高いですが、整理されないと使いにくい沼になりやすいです。' },
  { term: 'データウェアハウス', description: '分析向けに整理、統合されたデータ保管基盤です。参照しやすさや履歴管理を重視した構造になります。' },
  { term: 'ファクトテーブル', description: '売上、数量、金額など分析の中心となる事実データを持つテーブルです。集計軸と数値の関係が重要になります。' },
  { term: 'ディメンションテーブル', description: '商品、顧客、日付、店舗など分析の切り口を持つテーブルです。ファクトと組み合わせて多面的に分析します。' },
  { term: 'スター型スキーマ', description: '中央にファクト、その周囲にディメンションを置く分析向け構造です。集計しやすく、BIとの相性がよいです。' },
  { term: 'スノーフレーク型スキーマ', description: 'ディメンションをさらに正規化して細分化した分析構造です。整然としやすい一方、理解やクエリがやや複雑になります。' },
  { term: 'データ品質', description: 'データが正確で、欠損が少なく、使いやすい状態にあることです。分析基盤は量より質が重要になる場面が多いです。' },
  { term: 'メタデータ管理', description: 'データの意味、作成元、更新頻度、責任者などを管理することです。データの所在だけでなく、信頼性判断にも役立ちます。' },
  { term: 'データスチュワード', description: 'データ品質や定義の維持を支援する役割です。実務上は現場と基盤の橋渡しを担うことが多いです。' },
  { term: 'マスタ統合', description: '複数システムでばらばらな基準データをまとめて整えることです。顧客マスタや商品マスタで特に重要になります。' },
  { term: 'トランザクションログ', description: 'DB更新や業務処理の履歴を記録するログです。障害復旧や監査にも使われます。' },
  { term: '分析基盤コスト', description: 'データ保存、クエリ、転送、BI利用などにかかる費用です。便利だからと無制限に使うと想定以上に増えやすいです。' },
  { term: 'クエリ最適化', description: '集計や検索のSQLを速く、安く、安定して動くよう改善することです。分析基盤ではコスト最適化にも直結します。' },
  { term: 'インタビュー調査', description: '利用者へ直接話を聞き、背景や判断理由を深く理解する方法です。数字では見えない本音や例外運用を発見しやすいです。' },
  { term: '認知的整合性', description: '利用者の期待と画面の振る舞いが一致している状態です。自然な理解ができるUIは学習コストが低くなります。' },
  { term: 'デュアルライセンス', description: '同じソフトウェアが複数のライセンス形態で提供される方式です。商用版で制約を緩和するモデルもあります。' },
  { term: '法務レビュー', description: '契約、利用規約、ライセンス、データ利用条件などを法務観点で確認することです。技術的に可能でも契約上難しいことは少なくありません。' },
  { term: '制約理論', description: '全体最適は最も弱い部分の改善から始まるという考え方です。あちこち少しずつ改善するより、最重要制約を特定するほうが効果的なことがあります。' },
  { term: 'デシジョンテーブル', description: '条件の組み合わせと結果を表形式で整理する方法です。条件分岐が多い業務ルールのテスト設計に向いています。' },
  { term: 'プライベートサブネット', description: '外部から直接到達させない内部用ネットワーク領域です。アプリやDBなど重要資産を置く基本的な場所になります。' },
  { term: '変更サマリー', description: 'どのファイルに、どんな意図で、何を変えたかを要約したものです。レビュー効率を大きく左右します。' },
  { term: '差分レビュー', description: '変更前後の差を見て妥当性を確認するレビューです。AI変更は量が多くなりがちなため、特に重要です。' },
  { term: '正規化', description: 'データの重複を減らし、不整合を起こしにくくするためにデータ構造を整理する考え方です。更新時の矛盾を防ぎやすくなりますが、読み取り時の結合が増えて複雑になることもあります。' },
  { term: '第一正規形', description: '一つの項目に繰り返しの値や複数値を入れず、原子的な値に分ける形です。たとえば電話番号を一つのセルに複数入れるのを避ける考え方がこれに当たります。' },
  { term: '第二正規形', description: '複合主キーの一部にだけ依存する項目を分離した形です。部分依存を取り除くことで、重複や更新不整合を減らします。' },
  { term: '第三正規形', description: '主キー以外の項目同士の依存をなくし、主キーにだけ依存させた形です。設計の基本形としてよく使われます。' },
  { term: 'ボイスコッド正規形', description: 'より厳密に関数従属性を整理した正規化の形です。通常業務では第三正規形までで十分なことも多いですが、複雑な整合性では有効です。' },
  { term: '関数従属性', description: 'ある項目の値が決まると、別の項目の値が一意に決まる関係です。正規化の判断基準として重要です。' },
  { term: '非正規化', description: '性能や使いやすさのために、あえて正規化を崩すことです。設計思想を持って行えば有効ですが、無秩序な非正規化は危険です。' },
  { term: '参照専用テーブル', description: '主に読み取り用途で利用するテーブルです。更新頻度が低いマスタや集計結果格納で使われることがあります。' },
  { term: '集計テーブル', description: '毎回重い計算をせずに済むよう、あらかじめ集計値を持つテーブルです。性能改善に効きますが、更新タイミング設計が重要です。' },
  { term: 'サロゲートキー', description: '業務上の意味を持たない人工的な識別子です。変更されやすい業務コードを主キーにしないために使われることがあります。' },
  { term: '複合キー', description: '複数項目の組み合わせで一意性を表すキーです。中間テーブルや明細系でよく使われます。' },
  { term: '業務キー', description: '業務ルール上、一意に扱いたい識別子です。内部の主キーとは別に設けることで、業務上の追跡がしやすくなります。' },
  { term: '一意性保証', description: '同じ値や組み合わせが重複しないよう保証することです。アプリ側だけでなくDB制約でも守るのが基本です。' },
  { term: '参照整合性制約', description: '親子関係のあるデータが矛盾しないよう守る制約です。親がないのに子だけ存在する、といった状態を防げます。' },
  { term: 'トランザクション分離レベル', description: '同時実行時に他トランザクションの影響をどの程度見せるかを決める設定です。整合性と性能のトレードオフに深く関わります。' },
  { term: 'ダーティリード', description: 'まだ確定していない他トランザクションの変更を読んでしまう現象です。後で取り消される可能性があるため危険です。' },
  { term: '整合性モデル', description: 'データがどの程度即時に一致することを期待するかという考え方です。強整合性と結果整合性の違いを意識すると設計判断しやすくなります。' },
  { term: '強整合性', description: '更新後すぐに全体で同じ状態が見える性質です。分かりやすいですが、分散環境ではコストや遅延が増えやすいです。' },
  { term: '結果整合性', description: '直後はズレがあっても、最終的には一致するという考え方です。分散環境で現実的な選択になることが多いです。' },
  { term: 'リードレプリカ', description: '主に参照専用として使う複製DBです。読み取り負荷分散に有効ですが、更新遅延との付き合い方が重要です。' },
  { term: 'プライマリDB', aliases: ['プライマリdb'], description: '更新の正本となるDBです。可用性設計では、この正本をどう守るかが中心課題になります。' },
  { term: 'フェイルオーバーDB', aliases: ['フェイルオーバーdb'], description: '主系障害時に切り替わる待機DBです。切替速度だけでなく、切替時の整合性確認も重要です。' },
  { term: 'マルチマスター', description: '複数ノードで更新可能な構成です。可用性は高めやすいですが、競合解決が難しくなります。' },
  { term: 'データガバナンス', description: 'データの定義、品質、責任、利用ルールを組織として管理する考え方です。システムごとに勝手に扱う状態を防ぎます。' },
  { term: 'スキーマ検証', description: '送受信データが定義された構造に合っているかを確認することです。早い段階で不正データを弾くことで障害を減らせます。' },
  { term: 'レビュー観点表', description: '何を確認するかを整理したレビュー用の観点一覧です。属人的レビューを減らし、品質を安定させます。' },
  { term: 'ペアレビュー', description: '二人で文書やコードを確認するレビューです。短時間でも気づきが増えやすく、実務で取り入れやすい形式です。' },
  { term: 'ウォークスルー', description: '作成者が内容を説明しながら確認を受けるレビューです。設計意図の共有には向きますが、甘くなりすぎない工夫が必要です。' },
  { term: '関数従属', aliases: ['functional dependency'], description: 'ある属性の値が決まると別の属性の値が一意に決まる関係性です。正規化の判断基準となる基本概念です。' },
  { term: '読み取り専用テーブル', aliases: ['read-only table'], description: '読み取り操作に特化して使われるテーブルです。更新頻度の低いマスタデータや集計済み結果を格納するために使われることが多いです。' },
  { term: 'サマリーテーブル', aliases: ['summary table'], description: '集計済みの値を事前に保存しておくテーブルです。毎回の集計コストを回避しパフォーマンスを改善しますが、更新タイミングの設計が重要です。' },
  { term: 'ナチュラルキー', aliases: ['natural key'], description: 'ビジネス上の意味を持つ属性をそのままキーとして使うアプローチです。直感的ですが、業務値が変わると壊れやすいという欠点があります。' },
  { term: 'ビジネスキー', aliases: ['business key'], description: 'ビジネスルール上で一意に扱うべき識別子です。内部的な主キーとは別に定義することで、業務視点でのトレーサビリティが高まります。' },
  { term: '論理削除', aliases: ['soft delete'], description: 'レコードを物理的に消さずフラグで削除済みとする方法です。復元や監査に有利な一方、クエリのフィルタリングやパフォーマンス劣化に注意が必要です。' },
  { term: '反復不能読み取り', aliases: ['non-repeatable read'], description: '同一トランザクション内で同じデータを2回読むと異なる値が返る現象です。他のトランザクションがコミットした更新が割り込むことで発生します。' },
  { term: 'プライマリデータベース', aliases: ['primary database'], description: '書き込み操作を受け付けるメインのデータベースです。レプリカへのデータ配信の起点となります。' },
  { term: 'プライマリ・レプリカレプリケーション', aliases: ['primary-replica replication'], description: '1台のプライマリから複数のレプリカへデータを複製する構成です。読み取り分散やフェイルオーバー対応に使われます。' },
  { term: 'スキーマ移行戦略', description: 'DB構造変更をどう安全に進めるかの考え方です。アプリ互換性と運用停止時間を意識して設計します。' },
  { term: 'ブルーグリーンDB移行', aliases: ['ブルーグリーンdb移行'], description: '新旧DB系統を用意して切り替える移行方式です。リスクは下げやすいですが、同期設計が難しくなります。' },
  { term: '無停止マイグレーション', description: 'サービスを止めずに構造変更や移行を行うことです。互換期間を持たせる設計が重要になります。' },
  { term: 'バックフィル', description: '過去データへ新項目値や新形式を埋め直す処理です。負荷や整合性への影響を考えて計画する必要があります。' },
  { term: 'コンパクション', description: '分散ストレージやログを整理して効率化する処理です。保存効率や読み取り性能に影響します。' },
  { term: 'スキーママイグレーション戦略', aliases: ['schema migration strategy'], description: 'データベースの構造変更を安全に進めるためのアプローチです。アプリケーション互換性と運用ダウンタイムを考慮して設計します。' },
  { term: 'ブルーグリーンDBマイグレーション', aliases: ['ブルーグリーンdbマイグレーション', 'blue-green db migration'], description: '新旧両DBシステムを用意して切り替えるマイグレーション手法です。リスクは低いですが同期設計が難しくなります。' },
  { term: 'ゼロダウンタイムマイグレーション', aliases: ['zero-downtime migration'], description: 'サービスを停止せずに構造変更や移行を行う手法です。互換性期間の設計が鍵となります。' },
  { term: 'Oracle Database', aliases: ['oracle database'], description: '大規模業務システムで広く使われる商用リレーショナルデータベース製品。' },
  { term: 'SQL Server', aliases: ['sql server'], description: 'Microsoftが提供する商用データベース製品。' },
  { term: 'PostgreSQL', aliases: ['postgresql'], description: '機能性と拡張性に優れたオープンソースのリレーショナルデータベース。' },
  { term: 'MySQL', aliases: ['mysql'], description: 'Web系を中心に広く利用されるオープンソースデータベース。' },
  { term: 'Snowflake', aliases: ['snowflake'], description: 'データ分析に特化したクラウド型データプラットフォーム。' },
  { term: 'ビュー', description: 'SQLで定義した仮想的な表であり、参照や集計を簡潔にするために使う。' },
  { term: 'Snowpark', aliases: ['snowpark'], description: 'Snowflake上でアプリケーションやデータ処理を実行できる開発基盤。' },
  { term: 'SQLite', aliases: ['sqlite'], description: '組み込み用途にも強い軽量データベース。' },
  { term: 'PRIMARY KEY', aliases: ['primary key'], description: '表の中で1行を一意に識別する主キー。' },
  { term: 'CONSTRAINT', aliases: ['constraint'], description: 'データの整合性を守るための制約条件。' },
  { term: 'ストアドプロシージャ', description: 'DB内に保存して実行する手続き型プログラム。' },
  { term: 'VIEW', aliases: ['view'], description: 'SELECT結果を仮想表として扱う仕組み。' },
  { term: 'CLOB', aliases: ['clob', 'character large object'], description: '長文テキストを保存するためのデータ型。' },
  { term: 'ACID', aliases: ['acid'], description: 'トランザクションが持つべき4つの性質：原子性（Atomicity）・一貫性（Consistency）・独立性（Isolation）・永続性（Durability）。' },
  { term: 'BASE', aliases: ['base'], description: '分散システムで採用される一貫性モデル：Basically Available・Soft state・Eventually consistentの略。ACIDの対比概念。' },
  { term: 'RDBMS', aliases: ['rdbms', 'relational database management system', 'リレーショナルデータベース管理システム'], description: 'Relational Database Management Systemの略。表（テーブル）形式でデータを管理するデータベースシステム。MySQL、PostgreSQL、Oracle、SQL Serverが代表的。' },
  { term: 'NoSQL', aliases: ['nosql', 'not only sql'], description: '従来のSQL（リレーショナルDB）以外のデータベースの総称。キー・バリュー型、ドキュメント型、グラフ型などがある。MongoDBやRedisが有名。柔軟なデータ構造を扱える。' },
  { term: 'トリガー', aliases: ['trigger', 'データベーストリガー'], description: 'データベースで特定の操作（INSERT、UPDATE、DELETEなど）が実行されたとき、自動的に別の処理を起動する仕組み。「データ更新時に更新日時を自動記録する」などに使われる。' },
  { term: 'スキーマ', aliases: ['schema', 'データベーススキーマ'], description: 'データベースの構造定義。テーブルの一覧、各テーブルのカラム名やデータ型、制約などを定義したもの全体をスキーマと呼ぶ。設計時にスキーマ設計を行う。' },
  { term: 'SELECT', aliases: ['select', 'select文'], description: 'SQLでデータを検索・取得する命令。「SELECT * FROM テーブル名」のように使う。CRUD操作のR（Read）にあたる。最もよく使われるSQL命令。' },
  { term: 'INSERT', aliases: ['insert', 'insert文'], description: 'SQLでテーブルに新しいレコードを追加する命令。「INSERT INTO テーブル名 VALUES(...)」のように使う。CRUD操作のC（Create）にあたる。' },
  { term: 'UPDATE', aliases: ['update', 'update文'], description: 'SQLで既存のレコードを更新する命令。「UPDATE テーブル名 SET カラム名=値 WHERE 条件」のように使う。CRUD操作のU（Update）にあたる。' },
  { term: 'DELETE', aliases: ['delete', 'delete文'], description: 'SQLでレコードを削除する命令。「DELETE FROM テーブル名 WHERE 条件」のように使う。CRUD操作のD（Delete）にあたる。WHERE句を忘れると全件削除になるので注意。' },
  { term: 'JOIN', aliases: ['join', 'テーブル結合', 'inner join', 'left join'], description: 'SQLで複数のテーブルを結合して検索する操作。INNER JOIN（両方に一致するもの）、LEFT JOIN（左テーブルを全件含む）などの種類がある。' },
  { term: 'WHERE', aliases: ['where', 'where句'], description: 'SQLで検索条件を指定するキーワード。「WHERE 年齢 >= 20」のように、特定の条件に一致するレコードだけを対象にする。' },
  { term: 'GROUP BY', aliases: ['group by', 'group by句'], description: 'SQLで特定のカラムでレコードをグループ化する命令。「GROUP BY 部署」で部署ごとに集計できる。COUNT、SUM、AVGなどの集計関数と組み合わせて使う。' },
  { term: 'ORDER BY', aliases: ['order by', 'order by句', 'ソート'], description: 'SQLで検索結果を並び替える命令。「ORDER BY 日付 DESC」で日付の新しい順に並べる。ASC（昇順）とDESC（降順）が指定できる。' },
  { term: 'HAVING', aliases: ['having', 'having句'], description: 'GROUP BYでグループ化した後の結果に条件を指定するSQLキーワード。「HAVING COUNT(*) > 10」のように集計後の値で絞り込む。WHEREとの違いは集計後に使う点。' },
  { term: 'サブクエリ', aliases: ['subquery', '副問合せ', '副問い合わせ'], description: 'SQLの中に別のSQLを入れ子にした構造。「SELECT * FROM テーブル WHERE id IN (SELECT id FROM ...)」のように使う。複雑な検索条件を表現できる。' },
  { term: '物理ER', aliases: ['物理er', '物理erモデル', 'physical er', 'physical er model'], description: '特定DBMSの制約・実装を考慮した最終的なERモデル。テーブル定義書と対応する。' },
  { term: 'Data Design', aliases: ['data design'], description: 'データ構造・スキーマ・アクセスパターンを設計する工程。DB設計と密接に関連する。' },
  { term: 'DBMS', aliases: ['dbms'], description: 'Database Management Systemの略。データを永続的に管理・検索・更新するソフトウェアシステム。' },
  { term: 'ODBMS', aliases: ['odbms'], description: 'Object Database Management Systemの略。オブジェクトを直接格納・管理するデータベース管理システム。' },
  { term: 'ORDBMS', aliases: ['ordbms'], description: 'Object-Relational DBMSの略。リレーショナルモデルにオブジェクト指向機能を追加したDBMS。' },
  { term: 'インメモリDBMS', aliases: ['インメモリdbms'], description: 'データをディスクではなくメモリ上に格納するDBMS。高速な読み書きが可能。' },
  { term: '分散KVS', aliases: ['分散kvs'], description: 'キーと値でデータを管理し複数ノードに分散して高可用性・高スループットを実現するデータストア。' },
  { term: 'データベース物理設計', description: 'インデックス・パーティション・テーブルスペースなどDBMSの実装詳細を設計する工程。' },
  { term: '物理モデル', aliases: ['physical model'], description: '特定DBMSの制約・インデックス・パーティションを考慮した実装レベルのデータモデル。' },
  { term: 'データドメイン', aliases: ['data domain'], description: '特定の属性が取り得る値の範囲・型・制約。データモデリングにおいてデータ品質を保証する。' },
  { term: 'ORマッピング', aliases: ['orマッピング', 'or mapping'], description: 'Object-Relational Mappingの略。オブジェクトとリレーショナルDBのレコードを対応付ける技術。' },
  { term: '非正規形', aliases: ['unnormalized form'], description: 'データが正規化されていない状態。繰り返し項目・冗長データを含むテーブル構造。' },
  { term: 'ロングトランザクション', aliases: ['long transaction'], description: '完了まで長時間かかるトランザクション。ロック競合や整合性問題を引き起こしやすい。' },
  { term: '物理名', aliases: ['physical name'], description: 'データベースのテーブル名・カラム名など実装上の英数字の名前。' },
  { term: '論理名', aliases: ['logical name'], description: '物理名に対応する日本語や業務用語での名前。設計書・ドキュメントで使う。' },
  { term: 'JDBC', aliases: ['jdbc'], description: 'Java Database Connectivityの略。JavaアプリケーションからRDBMSに接続するための標準APIとドライバ仕様。' },
  { term: 'SQLCheck', aliases: ['sqlcheck'], description: 'SQLクエリの構文・セキュリティ・パフォーマンス問題を検出する静的解析ツールの総称。' },
  { term: 'ウィンドウ関数', aliases: ['window function', '分析関数'], description: 'OVER句で定義したウィンドウ（行の集合）に対して集計・順位付け・移動平均などを計算するSQL関数。GROUP BYと異なり行を集約せずに各行へ結果を付与できる。ROW_NUMBER・RANK・LAG・LEAD・SUM OVERなどが代表例。' },
  { term: 'CTE', aliases: ['cte', '共通テーブル式', 'common table expression', 'with句'], description: 'WITH句を使って一時的な名前付き結果セットを定義するSQL構文。複雑なクエリを読みやすいサブ式に分割でき、同一クエリ内で複数回参照可能。再帰CTEも実現できる。' },
  { term: '再帰CTE', aliases: ['再帰cte', 'recursive cte', '再帰with句'], description: 'WITH RECURSIVEを使い自己参照することで階層構造やグラフを再帰的に走査するCTE。アンカー部と再帰部を UNION ALL でつなぎ、終了条件を満たすまで繰り返す。組織図やツリー構造の処理に有効。' },
  { term: '相関サブクエリ', aliases: ['correlated subquery', '相関副問い合わせ'], description: '外側クエリの各行を参照しながら実行されるサブクエリ。外側クエリの列値をサブクエリ内で使用するため行ごとに再評価される。EXISTSと組み合わせた存在確認や行ごとの集計計算に使われる。' },
  { term: 'EXISTS', aliases: ['exists', 'existsサブクエリ', 'exists述語'], description: 'サブクエリが1行以上返すかどうかを真偽値で評価するSQL述語。IN句より大きな結果セットで効率的なことが多く、相関サブクエリと組み合わせた存在確認パターンで広く使われる。' },
  { term: 'LATERAL JOIN', aliases: ['lateral join', 'lateral結合', 'lateral句'], description: 'FROMリスト内の前の項目を参照できるサブクエリやテーブル関数を結合するSQL構文。PostgreSQL等が対応し、行ごとに異なるパラメータでサブクエリを評価できるため相関サブクエリを結合形式で書き直す際に有効。' },
  { term: 'CROSS APPLY', aliases: ['cross apply', 'cross apply演算子'], description: 'SQL Serverで使われるLATERAL JOINに相当する構文。テーブル値関数や行セットを返すサブクエリを各行に適用し結合する。結果が空の行はAPPLY後から除外される点でOUTER APPLYと異なる。' },
  { term: 'PIVOT', aliases: ['pivot', 'pivot演算子', 'ピボット'], description: '行データを列に転換するSQL操作。縦持ちデータを横持ち（クロス集計表）形式に変換する。SQL ServerはPIVOT構文を持ち、標準SQLでは条件付き集計（CASE SUM）で代替する。' },
  { term: 'UNPIVOT', aliases: ['unpivot', 'unpivot演算子', 'アンピボット'], description: 'PIVOTの逆操作で列データを行に変換するSQL操作。横持ちデータを縦持ち形式に正規化する際に使用する。SQL ServerはUNPIVOT構文を、標準SQLではUNION ALLで代替する。' },
  { term: 'MERGE文', aliases: ['merge文', 'merge into', 'upsertのsql標準形'], description: '1つのSQL文でソースとターゲットを照合しINSERT・UPDATE・DELETEを条件分岐して実行するSQL標準構文。ETLや差分同期に便利だが、実装は方言が多くロック動作に注意が必要。' },
  { term: 'UPSERT', aliases: ['upsert', 'on conflict do update', 'insert or replace', '競合時更新'], description: 'レコードが存在すればUPDATE、なければINSERTを一操作で行うデータ書き込みパターン。PostgreSQLはINSERT … ON CONFLICT DO UPDATE、MySQLはINSERT … ON DUPLICATE KEY UPDATEで実現する。' },
  { term: 'RETURNING句', aliases: ['returning句', 'returning', 'output句'], description: 'INSERT・UPDATE・DELETEの実行結果として変更された行のデータを返すSQL拡張。PostgreSQLが対応し、採番されたIDや更新後の値を追加SELECTなしに取得できる。SQL ServerではOUTPUT句が同等機能を持つ。' },
  { term: '実行計画', aliases: ['query plan', 'クエリプラン', 'execution plan'], description: 'データベースがSQLを実行する際に選択したアクセス経路・結合アルゴリズム・演算子の組み合わせを木構造で表したもの。EXPLAIN/EXPLAIN ANALYZEで確認し、パフォーマンスチューニングの出発点となる。' },
  { term: 'EXPLAIN ANALYZE', aliases: ['explain analyze', 'explain analyze実行', '実行計画詳細'], description: 'PostgreSQL等でSQLを実際に実行しながら各ノードの推定コスト・実測行数・実測時間を計画ツリーに付加して表示するコマンド。推定と実測の乖離がボトルネック特定に役立つ。' },
  { term: 'クエリオプティマイザ', aliases: ['query optimizer', 'クエリ最適化器'], description: 'SQLを受け取り統計情報を基に最も効率的な実行計画を選択するデータベースエンジンの中核コンポーネント。ルールベースとコストベースの2方式があり、現代のDBMSは主にコストベースを採用する。' },
  { term: 'コストベース最適化', aliases: ['cbo', 'cost-based optimization'], description: 'テーブルの統計情報（行数・カーディナリティ・ヒストグラム）を用いて各実行計画のコストを推定し、最小コストの計画を選ぶクエリ最適化手法。統計情報の精度が最適化品質を左右する。' },
  { term: '統計情報', aliases: ['statistics', 'テーブル統計'], description: 'オプティマイザがコストを推定するために収集するテーブル・列・インデックスに関するメタデータ。行数・平均行長・カーディナリティ・ヒストグラムなどを含み、ANALYZEコマンドで更新する。' },
  { term: 'ヒストグラム', aliases: ['histogram', '列ヒストグラム'], description: '列の値分布をバケットに分けて集計した統計情報の一種。オプティマイザが選択率を推定するために使用し、偏ったデータ分布でも精度の高いコスト推定を可能にする。' },
  { term: 'テーブルスキャン', aliases: ['full table scan', 'sequential scan', 'seq scan'], description: 'テーブルの全行を先頭から順に読み取るアクセス方式。インデックスが使われない場合や大部分の行を取得する際に選択される。行数が多いと遅くなるため、適切なインデックス設計が重要。' },
  { term: 'インデックススキャン', aliases: ['index scan', 'インデックス走査'], description: 'B-Treeなどのインデックス構造を辿って対象行を特定しテーブルから取得するアクセス方式。テーブルスキャンより少ない読み込みで絞り込める場合に選択され、選択率が低いほど効果的。' },
  { term: 'カバリングインデックス', aliases: ['covering index', 'index only scan', 'インデックスオンリースキャン'], description: 'クエリが必要とするすべての列をインデックスが含むため、テーブル本体にアクセスせずインデックスのみで結果を返せる最適化。ランダムI/Oを排除し大幅な高速化が可能。' },
  { term: '複合インデックス', aliases: ['composite index', 'multi-column index', '多列インデックス'], description: '複数列を組み合わせて作成するインデックス。先頭列から順に有効で、列順序・選択率・カバリングを考慮した設計が重要。左端プレフィックス原則により使える条件が限定される。' },
  { term: '部分インデックス', aliases: ['partial index', 'filtered index'], description: 'WHERE句の条件を満たす行のみを対象とした絞り込みインデックス。インデックスサイズを削減し、特定条件のクエリに特化した高速化が可能。PostgreSQL・SQL Serverが対応する。' },
  { term: '関数インデックス', aliases: ['function-based index', 'expression index', '式インデックス'], description: '列値そのものではなく列に関数や式を適用した結果に対して作成するインデックス。大文字小文字を無視した検索（LOWER(name)）や計算列の高速化に使われる。' },
  { term: 'B-Treeインデックス', aliases: ['b-treeインデックス', 'b-tree index', 'バランスドツリーインデックス'], description: 'バランスド木構造でキーを格納するRDBMSの標準インデックス形式。等値・範囲・ORDER BYに対応しほぼすべてのRDBMSのデフォルト。挿入時のツリーバランス維持により均一な検索性能を提供する。' },
  { term: 'GINインデックス', aliases: ['ginインデックス', 'gin index', 'generalized inverted index'], description: '配列・JSONB・全文検索など複数値を含む列に対応したPostgreSQLのインデックス種類。転置インデックス構造を持ち、配列要素の包含検索やtsvectorの全文検索で高速化に使われる。' },
  { term: 'GiSTインデックス', aliases: ['gistインデックス', 'gist index', 'generalized search tree'], description: '汎用検索木（Generalized Search Tree）に基づくPostgreSQLのインデックス。地理座標（PostGIS）・範囲型・全文検索など多様なデータ型と演算子に対応し、拡張可能なインデックス基盤として機能する。' },
  { term: 'BRIN', aliases: ['brin', 'block range index', 'ブロックレンジインデックス'], description: 'テーブルの物理ブロック範囲ごとに最小値・最大値を記録する軽量なPostgreSQLインデックス。タイムスタンプのような物理順と論理順が一致する列に有効で、非常に小さなインデックスサイズを実現する。' },
  { term: 'ハッシュインデックス', aliases: ['hash index'], description: 'キーのハッシュ値でバケットを特定する等値検索専用のインデックス。B-Treeより等値検索が高速な場合があるが範囲検索には使えない。PostgreSQL 10以降でWAL対応となりクラッシュ安全になった。' },
  { term: 'VACUUM', aliases: ['vacuum', 'vacuumコマンド', 'バキューム'], description: 'PostgreSQLのMVCCで生じる不要な旧バージョン行（デッドタプル）を物理的に回収しディスクスペースを解放するメンテナンス操作。トランザクションIDの周回問題（XIDラップアラウンド）防止にも不可欠。' },
  { term: 'ANALYZE', aliases: ['analyze', 'analyzeコマンド', '統計更新'], description: 'テーブルの列値をサンプリングして統計情報を更新するPostgreSQLコマンド。オプティマイザが正確なコスト推定を行うために必要で、大量データ変更後に実行することで実行計画の品質を維持する。' },
  { term: 'autovacuum', aliases: ['自動バキューム', 'autovacuum daemon'], description: 'PostgreSQLがVACUUMとANALYZEを自動実行するバックグラウンドデーモン。設定した閾値を超えたデッドタプル数や変更行数に応じて起動し、手動管理不要で統計と空き領域を維持する。' },
  { term: 'WAL', aliases: ['wal', 'write-ahead logging', '先行書き込みログ'], description: 'データ変更をデータファイルに書き込む前にログに記録することでクラッシュ後の回復を保証するRDBMSの基本技術。PostgreSQLのWALはレプリケーションのデータ転送にも使われ、チェックポイントとともにACIDの耐久性を実現する。' },
  { term: 'ストリーミングレプリケーション', aliases: ['streaming replication', 'walストリーミング'], description: 'PostgreSQLでWALレコードをリアルタイムにスタンバイサーバへ送信し続ける物理レプリケーション方式。同期・非同期を選択でき、バイト単位のWAL転送のためスタンバイはプライマリと同じPostgreSQLバージョンが必要。' },
  { term: '論理レプリケーション', aliases: ['logical replication', '論理デコーディング'], description: '行レベルの変更（INSERT/UPDATE/DELETE）をパブリッシャーからサブスクライバーへ論理的に転送するレプリケーション方式。バージョンやプラットフォームを跨いだ複製・特定テーブルのみの複製・データ移行に使われる。' },
  { term: 'マテリアライズドビュー', aliases: ['materialized view', '具体化ビュー'], description: 'ビューのクエリ結果をディスクに実体化した特殊なビュー。通常ビューとは異なり参照時に再計算せず高速に読み取れる。REFRESHコマンドで内容を更新する必要があり、更新頻度とクエリ速度のトレードオフがある。' },
  { term: 'PgBouncer', aliases: ['pgbouncer', 'pgbouncer接続プーラー'], description: 'PostgreSQL向けの軽量な接続プーラー。セッション・トランザクション・ステートメントの3モードで接続を管理し、数千クライアントを少数のデータベース接続に多重化することでスケールを実現する。' },
  { term: 'CHECK制約', aliases: ['check制約', 'check constraint', 'チェック制約'], description: '列に格納できる値を任意のブール式で制限するテーブル制約。たとえばage > 0やstatus IN (\'active\',\'inactive\')のような業務ルールをデータベースレベルで強制し、アプリ側のバリデーション漏れを防ぐ。' },
  { term: 'UNIQUE制約', aliases: ['unique制約', 'unique constraint', '一意制約'], description: '列または列の組み合わせに重複値を許可しない制約。NULLの扱いはRDBMSによって異なり、PostgreSQLはNULL同士を別値とみなす。UNIQUEインデックスが自動作成されることが多い。' },
  { term: 'NOT NULL制約', aliases: ['not null制約', 'not null constraint', '非null制約'], description: '列にNULLを格納することを禁止する制約。必須項目の強制適用に使われ、オプティマイザもNOT NULLを利用して最適化を行う場合がある。DEFAULT値とセットで使うことが多い。' },
  { term: 'DEFAULT制約', aliases: ['default制約', 'default constraint', 'デフォルト値'], description: 'INSERT時に値が指定されなかった列に自動で設定するデフォルト値を定義する制約。定数・関数（NOW()・gen_random_uuid()など）を指定でき、アプリケーション側の省略可能な値を一元管理できる。' },
  { term: '集計関数', aliases: ['aggregate function', '集約関数'], description: 'GROUP BYと組み合わせてグループ内の複数行を集約し1つの値を返すSQL関数。SUM・COUNT・AVG・MAX・MINが基本で、STRING_AGG・ARRAY_AGGなど拡張集計関数もある。ウィンドウ関数としても利用可能。' },
  { term: 'GROUPING SETS', aliases: ['grouping sets', 'グルーピングセット', 'cube'], description: '複数のGROUP BY条件をまとめて記述し小計・合計・ピボットを単一クエリで算出するSQL構文。ROLLUP（階層小計）・CUBE（全組み合わせ）・GROUPING SETSの3形式があり、UNIONより可読性と効率が高い。' },
  { term: 'ロールアップ', aliases: ['階層集計'], description: 'GROUP BY ROLLUPで指定した列の階層に沿って小計・合計を一度に算出するSQL構文。(a,b,c)を指定するとab→a→総計の順に集計した結果を含む。レポートや分析クエリで活用される。' },
  { term: 'JSONB', aliases: ['jsonb', 'jsonb型', 'バイナリjson'], description: 'PostgreSQLがJSONデータをバイナリ形式に変換して格納する列型。テキストJSON型より解析済みのため検索が高速で、GIN/GiSTインデックスが利用でき、@>・?などの豊富な演算子で半構造データを扱える。' },
  { term: 'フルテキスト検索', aliases: ['full-text search', '全文検索', 'fts'], description: '文書全体を形態素解析・トークナイズしてインデックス化し、単語や句の含有を高速に検索する機能。PostgreSQLはtsvector・tsqueryとGINインデックスで実現し、ROUNDしたランキング算出も可能。' },
  { term: 'ロック', aliases: ['lock', 'データベースロック', '行ロック', 'テーブルロック'], description: '複数のトランザクションが同じデータを同時変更する際の整合性を保つために一方の操作を待機させる仕組み。行レベル・テーブルレベル・ページレベルがあり、共有ロックと排他ロックの2種類が基本。' },
  { term: '行レベルロック', aliases: ['row-level lock'], description: 'テーブル全体ではなく変更対象の行だけにロックをかける粒度の細かいロック方式。テーブルロックより並行性が高く、PostgreSQL・InnoDBはデフォルトで行レベルロックを採用している。' },
  { term: '選択率', aliases: ['selectivity', 'フィルタ率'], description: 'WHERE条件が全行のうちどの割合を返すかを表す0〜1の値。選択率が低い（絞り込みが強い）ほどインデックスが有効で、オプティマイザがインデックススキャンとフルスキャンを選択する基準となる。' },
  { term: 'ネステッドループ結合', aliases: ['nested loop join', 'nl結合'], description: '外側テーブルの各行に対して内側テーブルを順次走査する結合アルゴリズム。内側テーブルにインデックスがあれば高速で少量データに強いが、大量データ間ではマージ結合やハッシュ結合より遅い。' },
  { term: 'ハッシュ結合', aliases: ['hash join', 'hash結合'], description: '小さい方のテーブルをハッシュテーブルに構築してから大きいテーブルを走査する結合アルゴリズム。等値結合かつインデックスがない大規模テーブル間に有効で、メモリに収まらない場合はディスクスピルが発生する。' },
  { term: 'マージ結合', aliases: ['merge join', 'sort merge join'], description: '両テーブルを結合キーでソート済みの状態にしてからポインタを進めながらマージする結合アルゴリズム。ソート済みインデックスがある場合や範囲条件での結合で効率的。' },
  { term: 'ワークメモリ', aliases: ['work memory', 'work_mem', 'ソートメモリ'], description: 'PostgreSQLでソートや結合のハッシュテーブルに使う一時メモリ量を制御するパラメータ。不足するとディスクへのスピルが発生し速度低下する。クエリの演算ノードごとに割り当てられるため過大設定はメモリ枯渇を招く。' },
  { term: 'セーブポイント', aliases: ['savepoint'], description: 'トランザクション内の特定地点に名前を付けて保存し、その地点まで部分ロールバックできるSQL機能。長いトランザクションの途中エラーを全体ロールバックせずに復旧する際に使われる。' },
  { term: 'DDL', aliases: ['ddl', 'data definition language', 'データ定義言語'], description: '【データベース】データベースのスキーマ（テーブル・インデックス・ビュー・スキーマ・ドメインなど）を定義・変更・削除するSQLの分類。CREATE・ALTER・DROPがDDLに属し、多くのRDBMSでDDLは自動コミットされる。 【OCI APEX】データベース定義文の総称。' },
  { term: 'DML', aliases: ['dml', 'data manipulation language', 'データ操作言語'], description: 'テーブルのデータを操作するSQLの分類。SELECT・INSERT・UPDATE・DELETEがDMLに属し、トランザクション制御下で実行されてロールバックが可能。' },
  { term: 'DCL', aliases: ['dcl', 'data control language', 'データ制御言語'], description: 'データベースのアクセス権限を制御するSQLの分類。GRANT（権限付与）・REVOKE（権限剥奪）がDCLに属し、セキュリティポリシーの実装に使われる。' },
  { term: 'TCL', aliases: ['tcl', 'transaction control language', 'トランザクション制御言語'], description: 'トランザクションを制御するSQLコマンドの分類。COMMIT・ROLLBACK・SAVEPOINTがTCLに属し、DML操作の確定または取り消しを管理する。' },
  { term: 'シーケンス', aliases: ['sequence', '自動採番'], description: '連番を自動生成するデータベースオブジェクト。PostgreSQLのSERIAL/BIGSERIALの内部実装であり、NEXTVAL関数で採番する。トランザクションをロールバックしても番号は戻らない（ギャップが発生する）。' },
  { term: 'UUID', aliases: ['uuid', 'universally unique identifier', 'guid', '一意識別子'], description: '128ビットのランダムまたは時刻ベースの一意識別子。分散システムで採番サーバなしに重複しないIDを生成でき、PostgreSQLではgen_random_uuid()（v4）で生成する。インデックスの断片化に注意が必要。' },
  { term: '外部キー制約', aliases: ['foreign key constraint', 'foreign key'], description: '子テーブルの列値が必ず親テーブルの主キーまたはユニークキーに存在することを強制する制約。ON DELETE CASCADE・SET NULLなどのアクション指定でカスケード処理を定義でき、参照整合性を保証する。' },
  { term: 'テーブル継承', aliases: ['table inheritance', 'postgresql継承', 'inherits'], description: 'PostgreSQL固有の機能で、子テーブルが親テーブルの列定義を継承し親テーブルへのクエリで子テーブルの行も取得できる。パーティショニング前身の仕組みとして使われたが、現在は宣言的パーティショニングが推奨される。' },
  { term: '宣言的パーティショニング', aliases: ['declarative partitioning', 'postgresql 10パーティショニング'], description: 'PostgreSQL 10以降のPARTITION BY構文を用いてDDLレベルでテーブルを範囲・リスト・ハッシュに分割する仕組み。オプティマイザがパーティションプルーニングを自動適用し、古いトリガーベースの実装より管理が容易。' },
  { term: 'パーティションプルーニング', aliases: ['partition pruning', 'パーティション刈り込み'], description: 'WHERE条件から不要なパーティションをスキャン対象外にするオプティマイザの最適化。パーティショニングの最大の恩恵であり、月別パーティションに対して特定月だけを検索する場合に効果を発揮する。' },
  { term: '行セキュリティポリシー', aliases: ['row-level security', 'row security policy'], description: 'テーブルの各行に対してユーザーやロールごとにアクセスできる行を制限するPostgreSQLのセキュリティ機能。SaaSのマルチテナントでテナントIDで行を絞り込む実装に活用される。' },
  { term: 'pglogical', aliases: ['pglogical拡張', '論理レプリケーション拡張'], description: 'PostgreSQLの論理レプリケーションを拡張し、テーブル単位・行フィルタ・双方向レプリケーション・バージョン間移行を可能にするサードパーティ拡張。Citus等の分散DB基盤に使われる。' },
  { term: 'ストアドファンクション', aliases: ['stored function', 'ユーザー定義関数', 'udf'], description: 'データベース内に保存して再利用可能なSQL・PL/pgSQL等で書かれた関数。値を返す点でプロシージャと異なり、SELECT文のなかで呼び出せる。ロジックのDB側集約とネットワーク往復削減に使われる。' },
  { term: 'トリガー関数', aliases: ['trigger function', 'トリガー定義関数'], description: 'PostgreSQLでトリガーが実行するPL/pgSQL等で書かれた特殊な関数。BEFORE/AFTER/INSTEAD OF × INSERT/UPDATE/DELETE/TRUNCATEの組み合わせで起動タイミングを設定し、監査ログや派生列更新に使われる。' },
  { term: 'PL/pgSQL', aliases: ['pl/pgsql', '手続き型拡張sql'], description: 'PostgreSQLの標準手続き型言語。変数・条件分岐・ループ・例外処理をSQLと組み合わせて使える。ストアドファンクション・ストアドプロシージャ・トリガー関数の実装に広く用いられる。' },
  { term: 'OLAP', aliases: ['olap', 'online analytical processing', 'オンライン分析処理'], description: '大量の履歴データに対して複雑な集計・ドリルダウン・スライシングを高速実行するデータ処理パラダイム。OLTPと対比される。列指向DBやキューブエンジンが用いられDWHの分析ワークロードを担う。' },
  { term: 'コネクション数上限', aliases: ['max connections', 'max_connections', '接続数制限'], description: 'データベースサーバが同時に受け入れられるクライアント接続数の上限設定。PostgreSQLではmax_connectionsパラメータで制御し、接続ごとにメモリを消費するため無制限には増やせず接続プーラーで管理する。' },
  { term: 'オンラインDDL', aliases: ['オンラインddl', 'online ddl', '無停止ddl', 'pt-online-schema-change'], description: '本番サービスを停止せずにALTER TABLEなどのDDLを適用する手法やDB機能。MySQLのOnline DDL・pg_repack・gh-ostなどが代表的で、大規模テーブルのカラム追加・インデックス作成時のロック時間を最小化する。' },
  { term: 'インデックスの再構築', aliases: ['reindex', 'インデックス再構築', 'index rebuild'], description: '断片化や破損したインデックスを作り直すメンテナンス操作。PostgreSQLはREINDEX CONCURRENTLY（10以降）でサービスを止めずに再構築できる。定期的な再構築で書き込みが多いテーブルのインデックス肥大化を解消する。' },
  { term: 'テーブルスペース', aliases: ['tablespace', '格納先指定'], description: 'テーブルやインデックスを格納する物理ディレクトリをデータベース上で抽象化したオブジェクト。高速SSDに頻繁アクセステーブルを配置するなど、ストレージ配置戦略を実装するために使われる。' },
  { term: '接続文字列', aliases: ['connection string', 'dsn', 'database url'], description: '【データベース】データベースへの接続に必要なホスト・ポート・データベース名・ユーザー・パスワードをまとめた文字列。 【OCI APEX】接続先やサービス名を表す接続記述。' },
  { term: 'pgAdmin', aliases: ['pgadmin', 'pgadmin4', 'postgresql管理gui'], description: 'PostgreSQLのオープンソースGUI管理ツール。クエリエディタ・テーブル閲覧・実行計画の可視化・バックアップ・ユーザー管理をWebブラウザ上で提供し、コマンドラインを使わずにDBを操作できる。' },
  { term: 'pg_stat_statements', aliases: ['pg_stat_statementsビュー', 'クエリ統計'], description: 'PostgreSQLの組み込み拡張で、実行されたSQLの総実行時間・コール数・平均時間・行数を集計する。スロークエリの特定やワークロード分析の主要ツールとして、DBチューニングの第一歩となる。' },
  { term: 'スロークエリログ', aliases: ['slow query log', '遅延クエリログ'], description: '設定した閾値（例：1秒）を超えた実行時間のSQLを記録するデータベースのログ機能。MySQLのslow_query_log・PostgreSQLのlog_min_duration_statementで有効化でき、ボトルネッククエリを発見する出発点となる。' },
  { term: 'ホットスタンバイ', aliases: ['hot standby', '読み取り可能スタンバイ'], description: 'スタンバイサーバをリードオンリーとして読み取りクエリに使いながらレプリケーションも受け取り続けるモード。PostgreSQLはhot_standbyパラメータで有効化でき、リードレプリカとして読み取りスケールアウトを実現する。' },
  { term: 'レプリケーション遅延', aliases: ['replication lag', '複製遅延'], description: 'プライマリでコミットされた変更がスタンバイに反映されるまでの時間的なずれ。非同期レプリケーションで発生し、重い書き込みやネットワーク帯域不足で増大する。監視し読み取り先の選択に考慮する必要がある。' },
  { term: 'WALアーカイブ', aliases: ['walアーカイブ', 'wal archive', 'pitr'], description: 'PostgreSQLでWALファイルを継続的に外部ストレージに保存し任意の時点へのリストアを可能にする仕組み。archive_commandで転送先を指定し、pg_basebackup＋WALアーカイブでPITR（時点回復）を構成する。' },
  { term: 'pg_basebackup', aliases: ['pg_basebackupコマンド', 'ベースバックアップ'], description: 'PostgreSQLのデータクラスタをオンラインでストリーミングコピーするバックアップコマンド。WALアーカイブと組み合わせてPITRを構成し、レプリケーションのスタンバイ初期化にも使われる。' },
  { term: 'pg_dump', aliases: ['pg_dumpコマンド', '論理バックアップ'], description: 'PostgreSQLのデータベースをSQLスクリプトまたはカスタム形式でダンプする論理バックアップコマンド。pg_restoreで復元し、クロスバージョン移行や特定スキーマのエクスポートに使われる。pg_dumpallでクラスタ全体を対象にできる。' },
  { term: 'データベースクラスタ', aliases: ['database cluster', 'postgresqlクラスタ'], description: 'PostgreSQLにおいて単一のpostgresプロセスが管理するデータベース群の集合体。物理ディレクトリ（PGDATA）に対応し複数のデータベースを内包する。MySQLの「クラスタ」とは意味が異なる。' },
  { term: 'Citus', aliases: ['citus', 'citus拡張', 'postgresql分散db'], description: 'PostgreSQLをシャーディングで水平スケールさせるオープンソース拡張。分散テーブル・参照テーブル・コロケーションを管理し、マルチテナントSaaSや時系列大規模分析に使われる。Microsoft Azure Cosmos for PostgreSQLとして提供されている。' },
  { term: 'TimescaleDB', aliases: ['timescaledb', 'timescale', '時系列db拡張'], description: 'PostgreSQLを拡張した時系列データ専用の列指向ハイパーテーブルを提供するOSS拡張。自動パーティショニング・連続集計・データ圧縮・データ保持ポリシーを提供し、IoT・監視・ログ分析に使われる。' },
  { term: 'PostGIS', aliases: ['postgis', 'postgis拡張', '地理情報db'], description: 'PostgreSQLに地理空間データ型（GEOMETRY・GEOGRAPHY）とGISクエリ（ST_Within・ST_Distance等）を追加するオープンソース拡張。GiSTインデックスと組み合わせて近傍検索・経路計算・ポリゴン演算を高速実行する。' },
  { term: 'ドキュメントDB', aliases: ['ドキュメントdb', 'document database', 'ドキュメント指向データベース'], description: 'データをJSON・BSONなどの半構造化ドキュメントとして格納するNoSQLデータベースの分類。スキーマが柔軟で階層的なデータを自然に表現でき、MongoDB・CouchDBが代表例。' },
  { term: 'MongoDB', aliases: ['mongodb', 'mongo'], description: 'BSONフォーマットでドキュメントを格納する代表的なオープンソースドキュメントDBMS。スキーマレスな柔軟性、Aggregation Pipelineによる集計、レプリカセット・シャーディングによる水平スケールを特徴とする。' },
  { term: 'キーバリューストア', aliases: ['key-value store', 'kvs'], description: 'キーと値のペアのみを格納する最もシンプルなNoSQLデータモデル。単純なルックアップに特化して超低レイテンシを実現し、Redis・Memcached・DynamoDBなどが代表例。' },
  { term: 'Memcached', aliases: ['memcached'], description: 'シンプルな分散インメモリキャッシュシステム。文字列のみを格納でき、Redisより機能は少ないが軽量で水平スケールが容易。Webアプリのオブジェクトキャッシュとして広く利用されてきた。' },
  { term: 'カラムファミリー', aliases: ['column family', 'ワイドカラムストア', 'wide-column store'], description: '行キーと複数のカラムグループ（カラムファミリー）でデータを管理するNoSQLデータモデル。スパースなデータを効率的に扱え、CassandraやHBaseが採用。カラム指向DBとは区別される。' },
  { term: 'Cassandra', aliases: ['cassandra', 'apache cassandra'], description: 'Facebookが開発したオープンソースの分散ワイドカラムストア。マスターレスなリング型アーキテクチャで単一障害点がなく、書き込みスループットに優れ、地理分散レプリケーションをサポートする。' },
  { term: 'グラフDB', aliases: ['グラフdb', 'graph database', 'グラフデータベース'], description: 'データをノード（頂点）とエッジ（辺）およびプロパティで表現するデータベース。関係性を主体としたクエリが得意で、ソーシャルネットワーク・推薦エンジン・不正検出に適する。Neo4jが代表例。' },
  { term: 'Neo4j', aliases: ['neo4j'], description: '最も普及したオープンソースのグラフデータベース。プロパティグラフモデルを採用し、Cypherクエリ言語でグラフトラバーサルを直感的に記述できる。レコメンデーションや知識グラフ構築に広く使われる。' },
  { term: '時系列DB', aliases: ['時系列db', 'time-series database', 'tsdb'], description: 'タイムスタンプ付きの計測値を効率的に格納・クエリするために最適化されたデータベース。メトリクス・ログ・センサーデータなど時系列データの圧縮・集計・保持ポリシー管理が得意。' },
  { term: 'InfluxDB', aliases: ['influxdb'], description: '時系列データに特化したオープンソースデータベース。Measurement・Tag・Fieldの構造でデータを格納し、Flux言語で集計クエリを記述する。監視・IoT・金融データの蓄積に広く使われる。' },
  { term: 'ベクトルデータベース', aliases: ['vector database', 'ベクトルdb'], description: '高次元の埋め込みベクトルを格納し、コサイン類似度や内積などで近傍ベクトルを高速検索するデータベース。LLMと組み合わせたRAGシステムや意味検索の基盤として注目される。' },
  { term: 'Pinecone', aliases: ['pinecone'], description: 'フルマネージドのクラウドネイティブベクトルデータベース。インデックスの作成・スケーリングをサービスとして提供し、大規模な意味検索やRAGアプリケーションの構築を容易にする。' },
  { term: 'Chroma', aliases: ['chroma', 'chromadb'], description: 'オープンソースの埋め込みデータベース。LangChainなどのLLMフレームワークと統合しやすく、ローカル環境での開発やプロトタイピングに適したベクトルストアとして広く利用される。' },
  { term: 'Weaviate', aliases: ['weaviate'], description: 'GraphQLインターフェースを持つオープンソースのベクトル検索エンジン。モジュールシステムで各種埋め込みモデルをプラグインでき、ハイブリッド検索（ベクトル＋キーワード）をサポートする。' },
  { term: '線形化可能性', aliases: ['linearizability', '強整合モデル'], description: '分散システムにおける最強の整合性モデル。各操作がある瞬間にアトミックに実行されたように見える保証を与え、システム全体として単一の一貫したコピーが存在するように振る舞う。' },
  { term: 'PACELC', aliases: ['pacelc'], description: 'CAP定理を拡張したフレームワーク。分断時（P）はAとCのトレードオフ、通常時（E）はLatency（レイテンシ）とConsistency（整合性）のトレードオフが存在するという理論。' },
  { term: 'コンセンサスアルゴリズム', aliases: ['consensus algorithm'], description: '分散システム内の複数ノードが障害やネットワーク分断があっても単一の合意値に到達するための手続き。RaftやPaxosが代表例で、分散DBやetcdなどの基盤を支える。' },
  { term: 'Raft', aliases: ['raft'], description: '分散コンセンサスを実現するアルゴリズム。Paxosより理解しやすく設計され、リーダー選出・ログレプリケーション・スナップショットの3フェーズで動作する。etcdやCockroachDBが採用している。' },
  { term: 'Paxos', aliases: ['paxos'], description: 'Lamportが提案した分散コンセンサスアルゴリズムの古典的基盤。Proposer・Acceptor・Learnerの役割でフォールトトレラントな合意形成を実現するが、実装の複雑さからRaftへ移行するケースも多い。' },
  { term: 'ゴシッププロトコル', aliases: ['gossip protocol', 'epidemic protocol'], description: '各ノードがランダムに隣接ノードへ情報を伝搬し続けることでクラスタ全体に情報を広める分散通信プロトコル。Cassandraのノード死活管理やリングメンバーシップ管理に使われる。' },
  { term: '分散ハッシュテーブル', aliases: ['dht', 'distributed hash table'], description: 'キーを複数ノードに分散して格納するP2P的なデータ構造。ルックアップをO(log N)で実現し、ノード追加・削除に対して最小限のキー移動で対応できる。Chord・Kademliaが代表実装。' },
  { term: 'コンシステントハッシング', aliases: ['consistent hashing'], description: 'ハッシュリング上にノードとキーを配置し、ノード増減時に再分散するキーを最小限に抑える手法。分散キャッシュや分散DBのデータ配置で広く使われる。仮想ノードと組み合わせて負荷均等化を図る。' },
  { term: '仮想ノード', aliases: ['virtual node', 'vnode'], description: 'コンシステントハッシングで各物理ノードをハッシュリング上の複数の仮想的な位置にマッピングする手法。ノード間の負荷均等化とノード追加・削除時のデータ再分散の平準化に役立つ。' },
  { term: 'レプリカセット', aliases: ['replica set'], description: 'MongoDBにおける高可用性構成の単位。プライマリ1台と複数のセカンダリからなり、プライマリ障害時にセカンダリの中から自動的に新プライマリを選出するフェイルオーバー機能を持つ。' },
  { term: 'パーティションキー', aliases: ['partition key'], description: '分散DBでデータをどのノード（パーティション）に配置するかを決定するキー。CassandraやDynamoDBでは値のハッシュ値でデータ配置が決まり、選定次第でホットスポットが生じるため慎重な設計が必要。' },
  { term: 'ソートキー', aliases: ['sort key', 'range key', 'クラスタリングキー'], description: 'DynamoDBやCassandraでパーティション内のデータ順序を決定するキー。同一パーティションキー内でのレンジクエリを効率化し、複合プライマリキーの第2要素として定義される。' },
  { term: 'セカンダリインデックス(NoSQL)', aliases: ['セカンダリインデックス(nosql)', 'secondary index', 'gsi', 'lsi'], description: 'プライマリキー以外の属性でのクエリを可能にするNoSQLデータベースのインデックス。DynamoDBのGSI/LSI、CassandraのSAIなどがあり、書き込みコストとのトレードオフを考慮して設計する。' },
];
