// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: dbSqlTx (2/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: '埋め込みドキュメント', aliases: ['embedded document', 'サブドキュメント'], description: 'MongoDBなどのドキュメントDBで、関連データを別コレクションに分けず親ドキュメントの中に入れ子で格納するパターン。単一ドキュメント取得で完結するためJOIN不要だが、ドキュメントサイズ上限に注意が必要。' },
  { term: '参照パターン', aliases: ['reference pattern', 'ドキュメント参照'], description: 'ドキュメントDBで関連データのIDのみを格納し、必要時にアプリケーション側でルックアップして結合する設計手法。埋め込みに比べデータ量は増えないが、複数回のクエリが必要になる。' },
  { term: 'Aggregation Pipeline', aliases: ['aggregation pipeline', '集計パイプライン'], description: 'MongoDBで複数のステージ（$match・$group・$lookup等）を連結してドキュメントを段階的に変換・集計する処理フレームワーク。SQLのGROUP BY・JOINに相当する操作を宣言的に記述できる。' },
  { term: 'MapReduce', aliases: ['mapreduce', 'map-reduce'], description: '大量データを分散処理する計算モデル。Map関数でデータを中間キーバリューに変換し、Reduce関数で集約する。Hadoopの基盤として普及し、MongoDBも初期から集計手段として採用していたが現在はAggregation Pipelineが主流。' },
  { term: '全文検索エンジン', aliases: ['full-text search engine'], description: 'テキストの全内容に対してキーワード検索を行うソフトウェア。形態素解析・転置インデックス・TF-IDFなどの技術でドキュメントの関連度をスコアリングし、高速な検索結果を返す。' },
  { term: 'Elasticsearch', aliases: ['elasticsearch', 'es'], description: 'Apache Luceneを基盤としたオープンソースの分散全文検索・分析エンジン。RESTful APIで操作し、ログ分析（ELKスタック）・サイト内検索・ビジネスインテリジェンスに幅広く利用される。' },
  { term: 'Solr', aliases: ['solr', 'apache solr'], description: 'Apache Luceneを利用したオープンソースの全文検索プラットフォーム。ファセット検索・ハイライト・リッチドキュメント解析に強く、企業向けコンテンツ検索基盤として長年使われてきた。' },
  { term: '転置インデックス', aliases: ['inverted index'], description: '全文検索エンジンの核となるデータ構造。単語（トークン）をキー、その単語を含むドキュメントIDのリストを値として格納し、キーワード検索をO(1)に近い速度で実現する。' },
  { term: 'アナライザー', aliases: ['analyzer'], description: 'Elasticsearchなどの検索エンジンでテキストをインデックス・クエリ可能なトークン列に変換するコンポーネント。Character Filter・Tokenizer・Token Filterの3段階で構成される。' },
  { term: 'トークナイザー', aliases: ['tokenizer'], description: 'テキストをトークン（単語や文字）のシーケンスに分割するコンポーネント。アナライザーの中核として機能し、空白分割・形態素解析・N-gram分割など様々な戦略がある。' },
  { term: 'スコアリング', aliases: ['relevance scoring', '関連度スコアリング'], description: '全文検索エンジンがクエリとドキュメントの関連度を数値化するプロセス。TF-IDF・BM25などのアルゴリズムを用い、スコアの高い順に検索結果を返す。ブーストやカスタムスコアで調整可能。' },
  { term: 'ファセット検索', aliases: ['faceted search', 'ファセットナビゲーション'], description: '検索結果をカテゴリ・価格帯・ブランドなどの属性（ファセット）で絞り込む機能。ECサイトや求人サービスのサイドバーフィルターとして広く使われ、Elasticsearchのアグリゲーション機能で実装する。' },
  { term: '近傍検索', aliases: ['nearest neighbor search', 'ann', '近似最近傍探索'], description: '高次元空間で与えられたクエリベクトルに最も近いベクトルを見つける検索手法。ベクトルデータベースの中核機能であり、HNSWやIVF-PQなどのANNアルゴリズムで大規模データでも高速に処理する。' },
  { term: 'CouchDB', aliases: ['couchdb', 'apache couchdb'], description: 'JSONドキュメントをHTTP/REST APIで操作するオープンソースのドキュメントDB。MapReduceベースのビュー定義と、ピアツーピアでの双方向レプリケーション（マルチマスター）が特徴。' },
  { term: 'RocksDB', aliases: ['rocksdb'], description: 'FacebookがLevelDBをフォークしたLSMツリーベースの組み込みキーバリューストア。高い書き込みスループット・圧縮・カラムファミリーをサポートし、TiKV・CockroachDB・MyRocksなど多くの分散DBの内部ストレージエンジンとして採用される。' },
  { term: 'LevelDB', aliases: ['leveldb'], description: 'GoogleがC++で開発したLSMツリーベースの組み込みキーバリューライブラリ。シーケンシャルな書き込みに最適化されており、ChromeのIndexedDB実装やビットコインノードの内部ストレージとして使われてきた。' },
  { term: 'LMDB', aliases: ['lmdb', 'lightning memory-mapped database'], description: 'メモリマップドファイルを用いたB+ツリーベースのMVCC対応組み込みキーバリューストア。読み取りに優れたゼロコピー設計で、OpenLDAPやMDB-LOADERなどに採用される。' },
  { term: 'LSMツリー', aliases: ['lsmツリー', 'lsm-tree', 'log-structured merge-tree'], description: '書き込みをまずメモリのMemtableに受け、一定量でSSTファイルとしてディスクにフラッシュし、バックグラウンドでマージ（Compaction）する書き込み最適化データ構造。RocksDB・Cassandraが採用する。' },
  { term: 'SSTable', aliases: ['sstable', 'sorted string table'], description: 'LSMツリーにおいてキーが昇順にソートされたイミュータブルなディスクファイル。効率的なバイナリサーチとブルームフィルタによる存在確認を組み合わせ、読み取りを最適化する。' },
  { term: 'ブルームフィルタ', aliases: ['bloom filter'], description: 'あるキーがデータセットに存在しないことを高速に判定できる確率的データ構造。偽陽性（誤ってありと判定）は起きるが偽陰性はなく、LSMツリーの不要なディスクアクセス削減に広く使われる。' },
  { term: 'HBase', aliases: ['hbase', 'apache hbase'], description: 'HadoopのHDFS上に構築されたオープンソースの分散ワイドカラムストア。BigTableの設計を実装し、数十億行・数百万列規模のスパースなデータを格納・検索できる。' },
  { term: 'タイムスタンプ順序付け', aliases: ['timestamp ordering', 'to'], description: '各トランザクションに開始時刻をタイムスタンプとして付与し、その順序にしたがって直列化可能性を保証する同時実行制御方式。スプーラブルなスケジュールを物理的時刻またはロジカルカウンタで管理する。' },
  { term: 'ハイブリッド論理クロック', aliases: ['hlc', 'hybrid logical clock'], description: '物理クロックと論理クロック（Lamportタイムスタンプ）を組み合わせた分散時刻管理方式。物理時刻の単調増加性を維持しつつ因果関係を捕捉でき、CockroachDBやYugaByteDBが採用する。' },
  { term: 'Dynamo論文', aliases: ['dynamo論文', 'amazon dynamo paper', 'dynamo paper'], description: '2007年AmazonがSOSPで発表したキーバリューストアの設計論文。コンシステントハッシング・ベクタークロック・ゴシップ・Merkleツリーを組み合わせた高可用設計を示し、多くのNoSQLに影響を与えた。' },
  { term: 'ベクタークロック', aliases: ['vector clock'], description: '分散システムで各ノードの論理時刻をベクトルとして管理し、イベント間の因果関係（hapend-before）を追跡するメカニズム。Dynamo論文で採用され、競合検出と解消に使われる。' },
  { term: 'Merkleツリー', aliases: ['merkleツリー', 'merkle tree', 'ハッシュツリー'], description: '各リーフがデータのハッシュで、内部ノードは子ノードのハッシュのハッシュであるツリー構造。分散DBのレプリカ間差分検出・ブロックチェーンのトランザクション検証・Gitのオブジェクト管理に利用される。' },
  { term: 'チェンジデータキャプチャ', aliases: ['change data capture'], description: 'データベースのレコード変更（INSERT/UPDATE/DELETE）をリアルタイムに捕捉してストリームとして配信する仕組み。デバウジングなしにイベント駆動アーキテクチャ・ETL・サーチインデックス同期に利用される。' },
  { term: 'シングルテーブル設計', aliases: ['single table design', 'std'], description: 'DynamoDBで複数のエンティティタイプを1つのテーブルにまとめて格納するベストプラクティス。アクセスパターンを事前定義し、パーティションキー・ソートキーを複合的に設計してJOINなしで複数エンティティを効率よく取得する。' },
  { term: 'アクセスパターン駆動設計', aliases: ['access pattern driven design', 'アクセスパターン設計'], description: 'NoSQLデータベースではクエリ要件を先に定義し、そのアクセスパターンに最適化されたデータモデルを設計するアプローチ。RDBの正規化から始める手法とは逆の考え方。' },
  { term: 'Prometheus', aliases: ['prometheus'], description: 'SoundCloudが開発したオープンソースの時系列メトリクス収集・監視システム。Pull型のスクレイピングとPromQL（Prometheus Query Language）によるクエリ、Alertmanagerとの連携で多くのサービスの監視基盤として採用される。' },
  { term: 'QdrantDB', aliases: ['qdrantdb', 'qdrant'], description: 'Rustで実装されたオープンソースのベクトル検索エンジン。Payload（メタデータ）フィルタリングと高精度なHNSWインデックスを組み合わせたフィルタリング付き近傍検索が強みで、RAGシステムのバックエンドとして人気が高い。' },
  { term: 'Milvus', aliases: ['milvus'], description: 'スケーラビリティに優れたオープンソースのベクトルデータベース。SaaS型Zilliz Cloudの基盤でもあり、IVF・HNSW・DiskANNなど多様なインデックスとGPUアクセラレーションをサポートする。' },
  { term: 'pgvector', description: 'PostgreSQLに対してベクトル型とL2・内積・コサイン類似度検索を追加するオープンソース拡張。既存のPostgreSQLインフラに近傍検索機能を追加でき、専用ベクトルDBへの移行コストをかけずにRAGを構築できる。' },
  { term: 'HNSWアルゴリズム', aliases: ['hnswアルゴリズム', 'hnsw', 'hierarchical navigable small world'], description: '複数の層からなるグラフを構築し、上位層から下位層へグリーディに探索することで近似最近傍検索を高速化するアルゴリズム。高い再現率と低レイテンシを両立し、ベクトルDBで標準的なインデックス手法となっている。' },
  { term: 'IVF-PQ', aliases: ['ivf-pq', 'inverted file with product quantization'], description: '転置ファイル（IVF）でベクトルをクラスタリングし、積量子化（PQ）でベクトルを圧縮することで大規模ベクトルの近似最近傍探索を省メモリ・高速に実現するインデックス手法。' },
  { term: 'グラフクエリ言語', aliases: ['graph query language', 'gql'], description: 'グラフデータベースを操作するための問い合わせ言語の総称。ISO/IEC標準化されたGQL・CypherはNeo4jで採用・GremlinはAmazon Neptuneなどで使われ、ノードやエッジのトラバーサルを宣言的に記述する。' },
  { term: 'Cypher', aliases: ['cypher', 'cypher query language', 'opencypher'], description: 'Neo4jが開発したグラフデータベース用のパターンマッチングクエリ言語。ASCII-artでノードとリレーションシップのパターンを直感的に表現でき、openCypherとしてオープン化されている。' },
  { term: 'トゥームストーン', aliases: ['tombstone', '削除マーカー'], description: 'LSMツリーやCassandraで論理削除を表すための特殊マーカーレコード。物理的な削除を即時行わずトゥームストーンを書き込み、Compaction時に古い版と一緒に実際に消去する。多数のトゥームストーンは読み取りコストを増加させる。' },
  { term: '書き込みオペレーション単位', aliases: ['wcu', 'write capacity unit'], description: 'DynamoDBで1秒あたりの書き込みスループットを表す単位。1WCUは最大1KBのアイテムを1秒に1回書き込む能力を表し、プロビジョンドモードでの課金・スロットリング管理に使われる。' },
  { term: '読み込みオペレーション単位', aliases: ['rcu', 'read capacity unit'], description: 'DynamoDBで1秒あたりの読み取りスループットを表す単位。1RCUは強整合読み取りで最大4KBのアイテムを1秒に1回読み込む能力を表す。最終整合性読み取りは半分のRCUで実行できる。' },
  { term: 'DynamoDB Streams', aliases: ['dynamodb streams'], description: 'DynamoDBテーブルの変更（書き込み・更新・削除）を順序付きストリームとして配信するCDC機能。AWS LambdaやKinesisと連携してイベント駆動処理・クロスリージョンレプリケーション・変更通知を実装できる。' },
  { term: 'CockroachDB', aliases: ['cockroachdb'], description: 'PostgreSQL互換の分散SQLデータベース。Raftコンセンサスで強整合性を保ちながらシャーディングによる水平スケールを実現し、マルチリージョン配置・自動フェイルオーバーで高可用性を確保する。' },
  { term: 'YugabyteDB', aliases: ['yugabytedb'], description: 'PostgreSQL互換かつCassandra互換のオープンソース分散NewSQLデータベース。DocDBストレージエンジン上でYSQL（PostgreSQL互換）とYCQL（CQL互換）の両APIを提供し、分散ACID対応を実現する。' },
  { term: 'TiDB', aliases: ['tidb'], description: 'PingCAPが開発したオープンソースのHTAP対応分散NewSQLデータベース。TiKV（Raft対応KVストレージ）とTiFlash（カラム型）を組み合わせ、MySQL互換APIでOLTPとOLAPを同一クラスタで処理する。' },
  { term: 'NewSQL', aliases: ['newsql'], description: 'RDBのACIDトランザクションとNoSQLの水平スケール可能性を両立させることを目指したデータベースカテゴリ。Google Spanner・CockroachDB・TiDBなどが代表例で、分散SQLとも呼ばれる。' },
  { term: '整合性レベル', aliases: ['consistency level', 'consistency tuning'], description: '分散DBで読み書き操作ごとに指定できる整合性の強さの設定。CassandraではONE・QUORUM・ALL、CosmosDBでは5段階（Strong〜Eventual）などがあり、レイテンシ・可用性とのトレードオフを調整する。' },
  { term: '読み修復', aliases: ['read repair'], description: '分散DBで読み取り時にレプリカ間の不整合を検出し、最新版で他レプリカを修復するメカニズム。Cassandraのデフォルト機能であり、バックグラウンドで整合性を自動的に回復する。' },
  { term: 'アンチエントロピー', aliases: ['anti-entropy', 'anti-entropy repair'], description: 'Merkleツリーを使ってレプリカ間の差分を定期的に検出・同期するCassandraの修復機能。Read Repairを補完し、長期間アクセスのないデータも整合性を保つ。' },
  { term: 'BM25', aliases: ['bm25', 'best match 25', 'okapi bm25'], description: 'TF-IDFを改良した確率的全文検索ランキングアルゴリズム。単語頻度の飽和と文書長の正規化を組み込み、Elasticsearchのデフォルトスコアリング関数として採用されている。' },
  { term: 'スパースベクトル', aliases: ['sparse vector'], description: 'ほとんどの次元の値がゼロで少数の次元だけに値を持つベクトル。BM25やTF-IDFによる語彙サイズ次元のキーワード表現が典型例で、ハイブリッド検索でデンスベクトルと組み合わせることが多い。' },
  { term: 'デンスベクトル', aliases: ['dense vector'], description: 'ほとんどの次元に値を持つ低次元（数百〜数千次元）の埋め込みベクトル。Transformerモデルが生成し意味情報を圧縮して表現する。スパースベクトルとは対概念でセマンティック検索の基盤。' },
  { term: 'キャッシュウォームアップ', aliases: ['cache warm-up', 'cache preloading'], description: 'キャッシュが空の状態（コールドスタート）から初期のキャッシュミス多発を防ぐため、事前に頻繁にアクセスされるデータをキャッシュに投入しておく戦略。Redisでのバッチ事前ロードなどで実装する。' },
  { term: 'キャッシュ貫通', aliases: ['cache penetration', 'キャッシュペネトレーション'], description: '存在しないキーへのリクエストがキャッシュミスしてDB直撃を繰り返す攻撃的アクセスパターン。ブルームフィルタで存在確認を事前に行うか、nullをキャッシュすることで防御する。' },
  { term: 'キャッシュ雪崩', aliases: ['cache avalanche', 'キャッシュアバランシェ'], description: '大量のキャッシュが同時に期限切れになりDBへのリクエストが殺到する障害パターン。TTLをランダムにばらつかせる・ミューテックスロックで同時再構築を防ぐなどの対策をとる。' },
  { term: 'Redis Cluster', aliases: ['redis cluster'], description: 'Redisのネイティブシャーディングソリューション。16384スロットをノード間で分割し、ゴシッププロトコルでクラスタ状態を管理する。キーはスロットにハッシュされ、マルチキー操作は同一スロット内のキーのみサポート。' },
  { term: 'Redis Sentinel', aliases: ['redis sentinel'], description: 'Redisの監視・自動フェイルオーバー・設定管理を担うプロセス群。複数のSentinelが投票（クォーラム）によりプライマリ障害を検出し、自動的にレプリカをプライマリへ昇格させる高可用性ソリューション。' },
  { term: 'フルテキストインデックス', aliases: ['full-text index', 'fulltext index'], description: 'テキストカラム全体を対象とした全文検索を高速化するインデックス。MySQLやPostgreSQLでも組み込みの全文検索インデックスを提供するが、専用の全文検索エンジン（Elasticsearch等）に比べ機能は限定的。' },
  { term: 'ドキュメントスコープトランザクション', aliases: ['single-document transaction', 'ドキュメント内アトミック操作'], description: 'MongoDBで単一ドキュメントへの操作はネイティブにアトミックが保証される性質。埋め込みドキュメントをうまく使うことで複数コレクションをまたぐトランザクションを避け、パフォーマンスを維持できる設計指針。' },
  { term: 'マルチドキュメントトランザクション', aliases: ['multi-document transaction'], description: 'MongoDBがv4.0から提供する複数コレクション・複数ドキュメントをまたぐACIDトランザクション機能。リレーショナルDBと同様のセマンティクスを提供するが、パフォーマンスオーバーヘッドがあるため使用は最小限にとどめるべきとされる。' },
  { term: '$lookup', aliases: ['mongodb $lookup', '左外部結合'], description: 'MongoDBのAggregation Pipelineで別コレクションのドキュメントを結合するステージ。SQLのLEFT OUTER JOINに相当し、埋め込みドキュメントで対応できないリレーション取得に使用するが、パフォーマンスへの影響を考慮する必要がある。' },
  { term: 'インデックスヒント', aliases: ['index hint', 'query hint'], description: 'クエリオプティマイザが選択するインデックスをユーザーが明示的に指定するクエリ修飾子。MongoDBの`hint()`やSQLの`USE INDEX`が該当し、オプティマイザの選択が最適でない場合に手動で最適なインデックスを指示する。' },
  { term: 'インメモリデータグリッド', aliases: ['imdg', 'in-memory data grid'], description: '複数ノードのメモリ上にデータを分散して格納し、高速なデータアクセスと計算を提供するミドルウェア。Hazelcast・Apache Igniteが代表例で、キャッシュとしての用途に加え分散計算やイベント処理にも使われる。' },
  { term: 'OLAPキューブ', aliases: ['olapキューブ', 'olap cube', '多次元olap'], description: '多次元の集計済みデータを事前計算して格納するデータ構造。ディメンション（時間・地域・製品）とメジャー（売上・数量）の組み合わせで定義され、BI・DWHでのスライス・ダイス・ドリルダウン操作を高速化する。' },
  { term: 'ELT', aliases: ['elt', 'extract load transform'], description: 'データをソースから抽出してそのままデータウェアハウスやデータレイクにロードし、その後変換処理を行うデータ統合パターン。BigQueryやSnowflakeなど処理能力の高いクラウドDWHの普及により、従来のETLに代わる手法として広く採用されている。' },
  { term: 'データパイプライン', aliases: ['data pipeline'], description: 'データをソースから目的地まで一連のステップで自動的に移動・変換・処理する仕組みの総称。取り込み・変換・検証・ロードの各ステージで構成され、スケジュール実行やイベントドリブンで動作する。' },
  { term: 'データレイクハウス', aliases: ['data lakehouse', 'lakehouse'], description: 'データレイクの低コスト・高スケーラビリティとデータウェアハウスのトランザクション管理・クエリ最適化を統合したアーキテクチャ。Delta LakeやApache Icebergなどのオープンテーブルフォーマットが基盤となる。' },
  { term: 'OLTP', aliases: ['oltp', 'online transaction processing', 'オンライントランザクション処理'], description: '銀行振込やECサイト注文など日常的なトランザクション処理を高速に行うためのデータベースシステム。大量の短い読み書き操作に最適化されており、正規化されたスキーマを持つ。OLAPと対をなす概念。' },
  { term: 'Slowly Changing Dimension', aliases: ['slowly changing dimension', 'scd', '緩やかに変化するディメンション'], description: 'データウェアハウスにおいてディメンションテーブルの属性が時間とともに変化する場合の管理手法。型1（上書き）、型2（履歴保持）、型3（前回値保持）など複数のアプローチがある。' },
  { term: 'データプロファイリング', aliases: ['data profiling'], description: 'データセットの品質・構造・分布・統計を体系的に分析する活動。NULL率、重複率、値の分布、データ型の整合性などを検査し、データ品質問題を早期発見するために用いられる。' },
  { term: 'dbt', aliases: ['data build tool'], description: 'データウェアハウス内でSQLベースのデータ変換を管理するオープンソースのELTツール。SELECT文を書くだけでモデル依存関係の管理・テスト・ドキュメント生成が可能で、アナリティクスエンジニアリングを加速する。' },
  { term: 'Apache Airflow', aliases: ['apache airflow', 'airflow'], description: 'Python製のオープンソースワークフローオーケストレーションプラットフォーム。DAG（有向非巡回グラフ）でパイプラインを定義し、スケジューリング・モニタリング・リトライなどの処理を管理する。データエンジニアリングで最も広く使われるオーケストレーターの一つ。' },
  { term: 'Dagster', aliases: ['dagster'], description: 'データパイプラインとデータアセットを中心に設計されたPython製のオープンソースオーケストレーションプラットフォーム。ソフトウェアエンジニアリングのベストプラクティス（テスト・型安全性）をデータパイプラインに持ち込むことを重視する。' },
  { term: 'Prefect', aliases: ['prefect'], description: 'Pythonネイティブのワークフローオーケストレーションツール。コードファースト設計で、既存のPythonコードにデコレータを付けるだけでパイプライン化できる。マネージドサービスのPrefect Cloudも提供。' },
  { term: 'Apache Spark', aliases: ['apache spark', 'spark'], description: '大規模データをメモリ内で分散処理するオープンソースのビッグデータ処理フレームワーク。バッチ・ストリーミング・機械学習・グラフ処理をサポートし、HadoopのMapReduceに比べて大幅に高速。' },
  { term: 'PySpark', aliases: ['pyspark'], description: 'Apache SparkのPython APIインターフェース。PythonからSparkの分散処理機能を利用でき、DataFrameやSQLを使ったデータ処理、MLlibを使った機械学習を実現する。データエンジニアリングの現場で広く使われる。' },
  { term: 'Apache Flink', aliases: ['apache flink', 'flink'], description: 'ステートフルなストリーム処理に特化したオープンソースの分散処理フレームワーク。イベント時刻・ウォーターマーク・チェックポイントなどの機能を持ち、低レイテンシの連続データ処理に優れる。' },
  { term: 'Apache Kafka', aliases: ['apache kafka', 'kafka'], description: '高スループット・低レイテンシを実現する分散型イベントストリーミングプラットフォーム。プロデューサーとコンシューマーを疎結合にし、トピックへのメッセージをログとして永続化する。マイクロサービス間通信やリアルタイムデータパイプラインの基盤として広く利用される。' },
  { term: 'Kafka Connect', aliases: ['kafka connect'], description: 'Apache KafkaとデータソースやシンクをSQLデータベース、S3、Elasticsearchなどと接続するためのフレームワーク。コネクタプラグインを設定するだけでノーコードのデータ統合パイプラインを構築できる。' },
  { term: 'Kafka Streams', aliases: ['kafka streams'], description: 'Apache Kafkaに組み込まれたクライアントライブラリ型のストリーム処理フレームワーク。別途クラスターを構築せずJavaアプリケーション内でKafkaトピックのリアルタイム変換・集計・ジョインが可能。' },
  { term: 'ksqlDB', aliases: ['ksqldb', 'ksql'], description: 'Apache Kafka上でSQLライクな構文を使ってリアルタイムストリーム処理クエリを実行できるデータベース。マテリアライズドビューの定義やフィルタリング・集計をSQL文で記述でき、ストリーム処理のハードルを下げる。' },
  { term: 'Debezium', aliases: ['debezium'], description: 'データベースの変更履歴をキャプチャしてKafkaトピックなどにストリーミングするオープンソースのCDCプラットフォーム。MySQL・PostgreSQL・MongoDBなどのWALやbinlogを監視し、行レベルの変更をリアルタイムに伝播する。' },
  { term: 'Apache Beam', aliases: ['apache beam', 'beam'], description: 'バッチとストリームの両方をポータブルに記述できるオープンソースのデータ処理統合モデル。Spark・Flink・Google Dataflowなど複数のランナーで同一コードを実行でき、クラウド依存を排除する。' },
  { term: 'Databricks', aliases: ['databricks'], description: 'Apache Sparkをベースにしたクラウドデータプラットフォーム。Lakehouse架構を採用しDelta LakeによるACIDトランザクションを提供し、データエンジニアリング・データサイエンス・機械学習を統合環境で実行できる。' },
  { term: 'Delta Lake', aliases: ['delta lake'], description: 'データレイク上でACIDトランザクション・スキーマ強制・タイムトラベルを実現するオープンソースのストレージレイヤー。Parquetをベースにトランザクションログを追加し、Lakehouseアーキテクチャの基盤として採用される。' },
  { term: 'Apache Iceberg', aliases: ['apache iceberg', 'iceberg'], description: '大規模分析テーブル向けのオープンテーブルフォーマット仕様。スキーマ進化・パーティション進化・タイムトラベル・ACIDトランザクションを実現し、Trino・Spark・Flinkなど複数のエンジンから同一テーブルへアクセスできる。' },
  { term: 'Apache Hudi', aliases: ['apache hudi', 'hudi'], description: 'データレイク上でUPDATE/DELETE・インクリメンタル処理・タイムトラベルを実現するオープンソースのテーブルフォーマット。Copy-on-WriteとMerge-on-Readの2種類のテーブルタイプを提供し、ストリーミング取り込みに強い。' },
  { term: 'Parquet', aliases: ['parquet', 'apache parquet'], description: '列指向の圧縮バイナリファイルフォーマット。必要な列のみを読み込むため大規模分析クエリに高効率で、Snappy・Zstdなどの圧縮と組み合わせてストレージコストを削減する。Spark・Hive・BigQueryで標準的に使われる。' },
  { term: 'Avro', aliases: ['avro', 'apache avro'], description: 'Hadoopエコシステム向けの行指向バイナリシリアライゼーションフォーマット。スキーマをJSONで定義しデータと一緒に格納でき、スキーマ進化をサポートする。Kafkaのメッセージシリアライゼーションで広く使われる。' },
  { term: 'ORC', aliases: ['orc', 'optimized row columnar'], description: 'Hive向けに設計された最適化列指向ファイルフォーマット。ストライプ構造・統計情報・ブルームフィルタにより高速なクエリと高圧縮を実現し、Apache Spark・Hiveのバッチ処理で使われる。' },
  { term: 'Apache Arrow', aliases: ['apache arrow', 'arrow'], description: '言語間のゼロコピーデータ共有を実現するメモリ内列指向データフォーマット。PythonのPandasやR・Java・Rust間でメモリコピーなしにデータを渡せるため、データ処理のボトルネックを解消する。' },
  { term: 'データメッシュ', aliases: ['data mesh'], description: 'データを中央集権的に管理するのではなく、ドメインチームがデータプロダクトとして所有・提供する分散型データアーキテクチャ。データプロダクト・ドメイン所有・セルフサービス基盤・フェデレーテッドガバナンスの4原則から成る。' },
  { term: 'データプロダクト', aliases: ['data product'], description: 'データメッシュにおいてドメインチームが提供するデータの単位。発見可能・アドレス可能・信頼性・自己記述的・相互運用可能・ネイティブにアクセス可能・安全という特性を備えるべきとされる。' },
  { term: 'データコントラクト', aliases: ['data contract'], description: 'データプロデューサーとコンシューマー間でデータのスキーマ・品質・SLA・セマンティクスを明文化した合意文書。破壊的変更を防ぎ、データパイプラインの信頼性を向上させる。' },
  { term: 'セルフサービスデータプラットフォーム', aliases: ['self-service data platform'], description: 'データメッシュの4原則の一つ。ドメインチームが中央プラットフォームチームに依存せずデータパイプラインの構築・テスト・デプロイ・監視を自律的に行えるインフラを提供するコンセプト。' },
  { term: 'フェデレーテッドコンピュテーショナルガバナンス', aliases: ['federated computational governance'], description: 'データメッシュの4原則の一つ。全ドメインが共通のガバナンスポリシー（セキュリティ・プライバシー・品質基準）をコードとして実装し、プラットフォームレベルで自動的に適用する分散型ガバナンスモデル。' },
  { term: 'データオブザーバビリティ', aliases: ['data observability'], description: 'データパイプラインの健全性をリアルタイムに監視し、データ品質の劣化や障害を早期検出・根本原因分析できる状態。鮮度・ボリューム・分布・スキーマ・リネージの5要素で評価する。' },
  { term: 'Great Expectations', aliases: ['great expectations'], description: 'Pythonベースのオープンソースデータバリデーションフレームワーク。データに対する期待値（Expectation）をコードで定義し、パイプラインの各ステージで自動的にデータ品質チェックを実行してHTMLレポートを生成する。' },
  { term: 'データバリデーション', aliases: ['data validation'], description: 'データが定義されたルール・制約・期待値を満たしているかを検証するプロセス。パイプラインの各ステージで型チェック・範囲チェック・参照整合性・統計的異常検知などを実施し、不正データの伝播を防ぐ。' },
  { term: 'マイクロバッチ', aliases: ['micro-batch'], description: 'ストリーム処理を数秒間隔の小さなバッチの連続として実装するアプローチ。Spark Streamingが採用しており、純粋なストリーム処理より実装が容易だがレイテンシは高くなる。' },
  { term: 'リアルタイム処理', aliases: ['real-time processing'], description: 'データを受信後ミリ秒から秒単位の遅延でほぼ即座に処理・応答するデータ処理方式。詐欺検知・株式売買・IoTアラートなどのユースケースで必須であり、ストリーム処理フレームワークで実現する。' },
  { term: 'ディメンショナルモデリング', aliases: ['dimensional modeling'], description: 'Ralph Kimballが提唱したデータウェアハウス設計手法。ビジネスプロセスをファクトテーブルとディメンションテーブルの組み合わせで表現し、直感的なクエリとBIツールとの親和性を高める。' },
  { term: 'データオーケストレーション', aliases: ['data orchestration'], description: '複数のデータパイプラインタスクの実行順序・依存関係・スケジュール・リトライを中央管理する仕組み。AirflowやDagsterなどのオーケストレーターが担い、パイプラインの可観測性と運用性を高める。' },
  { term: 'ワークフローオーケストレーション', aliases: ['workflow orchestration'], description: '複数のタスクや処理ステップを依存関係・実行順・スケジュールに従って自動的に調整・実行管理する仕組みの総称。データエンジニアリング分野ではAirflow・Dagster・Prefectが代表的なツール。' },
  { term: 'データスチュワードシップ', aliases: ['data stewardship'], description: '組織のデータ品質・整合性・セキュリティ・可用性を継続的に管理・改善する責任と活動。データスチュワードが担い、ビジネスとITの橋渡しをしながらデータガバナンスポリシーを実行に移す。' },
  { term: 'データ変換', aliases: ['data transformation'], description: 'ソースシステムのデータを分析や下流システムが必要とする形式・構造・粒度に変換するプロセス。型変換・集計・正規化・エンリッチメント・ピボットなどの操作を含み、パイプラインのTフェーズを担う。' },
  { term: 'ステージングレイヤー', aliases: ['staging layer', 'staging'], description: 'ソースシステムからデータをそのまま取り込む最初のデータウェアハウスレイヤー。変換を加えず生データを保持し、変換の再実行やデバッグを可能にする。dbtではstagingモデルがこれに対応する。' },
  { term: 'データエンジニアリング', aliases: ['data engineering'], description: 'データを収集・格納・変換・配信するパイプラインとインフラを設計・構築・運用するエンジニアリング領域。データサイエンティストや分析者が利用できる信頼性の高いデータ基盤を提供することを目的とする。' },
  { term: 'データエンジニア', aliases: ['data engineer'], description: 'データパイプライン・データウェアハウス・データレイクなどのデータ基盤を設計・構築・運用する職種。SQL・Python・Spark・クラウドサービスの知識を持ち、データサイエンティストやアナリストが分析できる環境を整備する。' },
  { term: 'データアーキテクト', aliases: ['data architect'], description: '企業のデータ戦略・データモデル・データプラットフォームのアーキテクチャを設計・策定する役割。ビジネス要件をデータ構造に落とし込み、データガバナンスの枠組みを定義してデータエンジニアや分析者をリードする。' },
  { term: 'データアーキテクチャ', aliases: ['data architecture'], description: '組織のデータ収集・格納・変換・消費の全体構造を規定する設計思想と仕様の総体。モダンデータスタック・Lakehouse・データメッシュなど複数のアーキテクチャパターンが存在し、ビジネス要件に応じて選択する。' },
  { term: 'モダンデータスタック', aliases: ['modern data stack', 'mds'], description: 'クラウドネイティブなSaaSツールを組み合わせてデータパイプラインを構築するアプローチ。Fivetran（取り込み）・BigQuery/Snowflake（DWH）・dbt（変換）・Looker（BI）などのベストオブブリードツールを接続して構成する。' },
  { term: 'データエクストラクション', aliases: ['data extraction'], description: 'ETL/ELTの最初のステップであるソースシステムからのデータ取り出しフェーズ。フルロードと差分（インクリメンタル）ロードの方式があり、APIポーリング・CDCベース・ファイルベースなど方法は様々。' },
  { term: 'インクリメンタルロード', aliases: ['incremental load'], description: '前回の取り込み以降に追加・変更されたデータのみを差分でロードする方式。フルロードに比べ処理時間とコストを削減でき、大規模テーブルのパイプラインで必須となる。ウォーターマークやCDCで変更を検出する。' },
  { term: 'フルロード', aliases: ['full load'], description: 'ソーステーブルの全データを毎回洗い替えでロードする方式。実装がシンプルでデータ整合性が保ちやすいが、大規模テーブルでは処理時間・コスト・ソースへの負荷が大きくなるため用途を選ぶ。' },
  { term: 'データウェアハウジング', aliases: ['data warehousing'], description: 'ビジネス分析・レポーティング・意思決定支援のために複数ソースからデータを統合・格納・管理する一連の技術・プロセス・実践の総称。ETL設計・ディメンショナルモデリング・DWH運用を含む広義の概念。' },
  { term: 'データロード', aliases: ['data loading', 'data load'], description: '変換済みデータをデータウェアハウス・データマート・データレイクなどの最終目的地に書き込むETL/ELTの最終ステップ。バルクロード・ストリーミングインサート・COPY命令など手法が複数あり、スループットと整合性のバランスを考慮する。' },
  { term: 'データ品質スコア', aliases: ['data quality score', 'dq score'], description: 'データセットの品質を定量的な数値で表したもの。完全性・正確性・一貫性・鮮度などの次元ごとにルールを設定してスコアリングし、データカタログやモニタリングダッシュボードで可視化する。' },
  { term: 'データ鮮度', aliases: ['data freshness'], description: 'データが最後に更新されてからの経過時間を表す品質指標。パイプラインのSLA要件として定義され、データオブザーバビリティツールがリアルタイムに監視する。データが古すぎると意思決定の質が低下する。' },
  { term: 'データカタログツール', aliases: ['data catalog tool'], description: 'データアセットのメタデータを収集・管理・検索可能にするプラットフォームソフトウェア。Amundsen・DataHub・Apache Atlas・Collibra・Alationが代表例で、リネージの可視化・ビジネス用語集・データオーナー管理機能を提供する。' },
  { term: 'DataHub', aliases: ['datahub'], description: 'LinkedInがオープンソースで公開したメタデータ管理・データカタログプラットフォーム。グラフDBベースのメタデータストアを持ち、データリネージ・データ品質・アクセス制御を統合管理する。' },
  { term: 'Amundsen', aliases: ['amundsen'], description: 'Lyftがオープンソースで公開したデータ発見・メタデータ管理プラットフォーム。グラフDBとElasticsearchを組み合わせてデータアセットの検索性を高め、人気度・オーナー・サンプルデータを表示する。' },
  { term: 'ゴールデンレコード', aliases: ['golden record'], description: 'マスターデータ管理において複数ソースの重複データを突合・統合した後の、唯一の信頼できるエンティティレコード。エンティティ解決（名寄せ）処理を経て生成され、全システムでこれを正とする。' },
  { term: 'エンティティ解決', aliases: ['entity resolution', 'record linkage', '名寄せ'], description: '異なるソースや表記ゆれのある複数レコードが同一エンティティを指すかを判定・統合するプロセス。MDMのゴールデンレコード作成に不可欠で、確定的マッチングと確率的マッチングのアプローチがある。' },
  { term: 'データドリブン意思決定', aliases: ['data-driven decision making', 'dddm'], description: '感覚や経験ではなくデータと分析結果に基づいて意思決定を行うアプローチ。信頼性の高いデータ基盤・BI・実験プラットフォーム（A/Bテスト）が前提となり、データエンジニアリングの最終目的の一つ。' },
  { term: 'スキーマオンリード', aliases: ['schema on read'], description: 'データを格納する際にスキーマを強制せず、読み込む時点でスキーマを適用するアプローチ。データレイクで採用されており、多様なデータを柔軟に取り込める反面、データ品質管理が複雑になる。' },
  { term: 'スキーマオンライト', aliases: ['schema on write'], description: 'データを書き込む時点でスキーマを強制・検証するアプローチ。データウェアハウスで採用されており、データ品質が保証されクエリが高速だが、スキーマ変更には手間がかかる。' },
  { term: 'カラムナーストレージ', aliases: ['columnar storage', '列指向ストレージ'], description: 'データを行単位でなく列単位でディスクに格納するストレージ方式。特定列のみを読み込む分析クエリで高い圧縮率とI/O削減を実現し、Parquet・ORC・RedshiftなどのDWH・分析DBが採用する。' },
  { term: '大規模並列処理', aliases: ['mpp', 'massively parallel processing'], description: 'クエリを多数のノードに分散して同時実行することで大規模データの高速処理を実現するアーキテクチャ。RedshiftやSnowflakeなどクラウドDWHが採用し、スケールアウトによってペタバイト規模の分析を可能にする。' },
  { term: 'データボルト', aliases: ['data vault'], description: 'ハブ・リンク・サテライトの3テーブル種別でデータウェアハウスを設計するモデリング手法。ビジネスキーを中心に構造化するためスキーマ変更への柔軟性が高く、監査とトレーサビリティに優れる。' },
  { term: 'データマスキング', aliases: ['data masking', 'データ匿名化'], description: '個人情報や機密データを本番環境から取り出す際に、元のデータ形式を保ちながら実際の値を隠蔽・置換する技術。開発・テスト環境でのデータ利用やGDPR準拠のためにデータパイプラインに組み込まれる。' },
  { term: 'データ民主化', aliases: ['data democratization'], description: '組織内のすべての意思決定者が専門知識なしにデータへアクセス・活用できる状態を目指す考え方。セルフサービスBIやデータカタログの整備によって実現し、データチームへの依存を減らす。' },
  { term: 'アナリティクスエンジニアリング', aliases: ['analytics engineering'], description: 'データエンジニアとデータアナリストの中間領域。dbtを活用してSQLベースでデータ変換・テスト・ドキュメントを管理し、ビジネスロジックをコードとして表現してBIツールに高品質なデータモデルを提供する。' },
  { term: 'ELTパターン', aliases: ['eltパターン', 'elt pattern'], description: 'データをまずDWHやデータレイクにそのままロードし、その中でクラウドのコンピューティングリソースを活用して変換するデータ統合パターン。dbt・BigQuery・Snowflakeの組み合わせが典型的なモダンデータスタックの形。' },
  { term: 'データエンリッチメント', aliases: ['data enrichment'], description: '既存のデータに外部ソースや参照データを結合して情報の価値を高める変換処理。IPアドレスから地理情報を付与したり、会社名から業種コードを付加するなどが例として挙げられる。' },
  { term: 'データ品質ルール', aliases: ['data quality rule', 'dq rule'], description: 'データが満たすべき条件を明示的に定義した規則。「売上金額は0以上」「顧客IDはNULLでない」など具体的な制約として記述され、Great Expectationsなどのバリデーションフレームワークで自動チェックされる。' },
  { term: 'タイムトラベル', aliases: ['time travel'], description: 'Delta Lake・Apache Iceberg・Snowflakeなどが提供する過去の任意の時点のデータを参照できる機能。誤った変換やDELETEからのリカバリ・監査・再現性確保に活用され、Lakehouseの重要な特性の一つ。' },
  { term: 'スキーマ進化', aliases: ['schema evolution'], description: '既存データを壊さずにテーブルやファイルのスキーマ（列の追加・削除・型変更など）を変更できる能力。Avro・Iceberg・Delta Lakeがサポートし、下流への影響を最小化しながらデータ構造を変更できる。' },
  { term: 'ブロンズシルバーゴールドアーキテクチャ', aliases: ['bronze silver gold', 'medallion architecture', 'メダリオンアーキテクチャ'], description: 'Databricksが提唱するLakehouseの多層データアーキテクチャ。ブロンズ（生データ）・シルバー（クレンジング済み）・ゴールド（集計・ビジネスロジック適用済み）の3レイヤーでデータ品質を段階的に高める。' },
  { term: 'ウォーターマーク', aliases: ['watermark', 'event-time watermark'], description: 'ストリーム処理においてイベント時刻の進行を追跡し、遅延到着データの許容範囲を定義するメカニズム。FlinkやSpark Streamingでウィンドウ集計の完了タイミングを制御し、遅延データの取り扱いポリシーを実装する。' },
  { term: 'ウィンドウ集計', aliases: ['windowing', 'window aggregation'], description: 'ストリームデータを時間的な窓（ウィンドウ）で区切って集計する処理。タンブリングウィンドウ・スライディングウィンドウ・セッションウィンドウの3種類が主要で、FlinkやKafka Streamsで実装する。' },
  { term: '逆ETL', aliases: ['逆etl', 'reverse etl'], description: 'データウェアハウスに蓄積・整備されたデータをCRMやMAなど業務ツール（オペレーショナルシステム）に書き戻すプロセス。CensusやHightouch等のツールが担い、分析結果を施策実行に直結させる。' },
  { term: 'Fivetran', aliases: ['fivetran'], description: 'ソースデータベース・SaaS・クラウドストレージからデータウェアハウスへのデータ取り込みを自動化するマネージドELTサービス。300以上のコネクタを提供し、スキーマドリフト検出・自動マイグレーションなどを備える。' },
  { term: 'Airbyte', aliases: ['airbyte'], description: 'オープンソースのデータ統合（ELT）プラットフォーム。300以上のコネクタをコミュニティで開発・提供し、セルフホストとクラウドマネージドの両方で利用できる。コネクタ開発キットでカスタムコネクタも作成可能。' },
  { term: 'データ系統グラフ', aliases: ['data lineage graph', 'lineage graph'], description: 'データアセット間の依存関係と変換の流れを有向グラフで可視化したもの。dbtやDataHubが生成し、特定テーブルの上流ソースや下流への影響範囲を素早く把握するためのデバッグ・影響分析に使用する。' },
  { term: 'SLAモニタリング', aliases: ['slaモニタリング', 'sla monitoring', 'pipeline sla'], description: 'データパイプラインが定めた完了時刻・鮮度・品質などのSLA（サービスレベル契約）を満たしているかを継続的に監視する仕組み。違反時にアラートを発して対応を促し、ダウンストリームの影響を最小化する。' },
  { term: 'データスキューイング', aliases: ['data skew', 'skew'], description: '分散処理において一部のパーティションやノードにデータが偏る現象。Sparkなどでジョインキーに偏りがあるとホットパーティションが生じ、処理全体がボトルネックになる。スキュー対策としてサルティングなどを用いる。' },
  { term: 'クラスター化テーブル', aliases: ['clustered table', 'clustering'], description: 'データを特定の列の値でソートして格納することでクエリ時のブロックスキップを最適化するテーブル構成。BigQueryのクラスタリングやSnowflakeのクラスタリングキーが代表例で、パーティショニングと組み合わせて効果を発揮する。' },
  { term: 'コスト最適化', aliases: ['cost optimization', 'query cost optimization'], description: 'クラウドDWHにおけるクエリコストを削減するための設計・運用の取り組み。パーティショニング・マテリアライズドビュー・列選択の最適化・クラスタリングを組み合わせてスキャン量を減らすことが基本戦略。' },
  { term: 'ラムダアーキテクチャ', aliases: ['lambda architecture'], description: 'バッチレイヤー（高精度・高レイテンシ）とスピードレイヤー（低レイテンシ・近似値）を並行稼働させ、サービングレイヤーで統合するビッグデータアーキテクチャ。実装の複雑さが課題で、後にカッパアーキテクチャが提案された。' },
  { term: 'カッパアーキテクチャ', aliases: ['kappa architecture'], description: 'バッチレイヤーを排除しストリーム処理のみで全データ処理を統一するビッグデータアーキテクチャ。ラムダアーキテクチャの複雑性を解消し、Kafkaに全ログを保持して再処理を可能にする設計思想。' },
  { term: 'Apache NiFi', aliases: ['apache nifi', 'nifi'], description: 'NASAが開発しApache財団に寄贈したビジュアルなデータフロー管理ツール。GUIでプロセッサをつないでデータのルーティング・変換・フィルタリングを定義でき、IoTデータ収集やリアルタイムデータ取り込みに使われる。' },
  { term: 'ストリーミング取り込み', aliases: ['streaming ingestion'], description: 'データが生成されるたびに継続的にデータプラットフォームへ取り込む方式。KafkaやKinesis経由でDelta LakeやBigQueryにリアルタイム書き込みを行い、バッチ取り込みより鮮度の高いデータを提供する。' },
  { term: 'Z-Ordering', aliases: ['z-ordering', 'z-order clustering', 'z-オーダリング'], description: 'Delta LakeやDatabricksで提供されるデータ局所性最適化技術。複数の列の値を空間充填曲線でクラスタリングし、フィルタ条件に合うデータが同一ファイルに集まるようにすることでスキップ効率を高める。' },
  { term: 'DB冗長化', aliases: ['db冗長化'], description: 'データベースを冗長構成にして障害耐性を高めることです。' },
  { term: 'テーブル構造', aliases: ['テーブル設計'], description: 'データベース内でデータをどのような表構成で持つかを示す設計です。後からの見直しコストが大きくなりやすい部分です。' },
  { term: 'row', aliases: ['行'], description: 'データベーステーブルにおける1件分のデータの横方向のまとまりです。' },
  { term: 'SQL', aliases: ['sql', 'structured query language'], description: 'リレーショナルデータベースを操作するための標準的な問い合わせ言語です。SELECT、INSERT、UPDATE、DELETEなどの命令があります。' },
];
