// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: frontend (3/5)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_003: ReadonlyArray<GlossaryEntry> = [
  { term: 'React DevTools', aliases: ['react devtools'], description: 'Reactアプリのコンポーネントツリー・state・props・パフォーマンスを検査するブラウザ拡張機能。プロファイラーで再レンダーの原因を特定し、コンポーネント間のデータフローを可視化する。' },
  { term: 'React Query', aliases: ['react query', '@tanstack/react-query'], description: 'サーバー状態の取得・キャッシュ・同期・更新を管理するReact向けのデータフェッチングライブラリ。TanStack QueryのReact版。キャッシュ戦略・背景再フェッチ・楽観的更新などを宣言的に扱える。' },
  { term: 'SWR', aliases: ['swr', 'stale-while-revalidate'], description: 'VercelのReact向けデータフェッチングフック。stale-while-revalidate戦略を用い、まずキャッシュからデータを返しつつバックグラウンドで再検証する。シンプルなAPIでREST・GraphQL双方に対応。' },
  { term: 'Tailwind CSS', aliases: ['tailwind css', 'tailwindcss'], description: 'ユーティリティクラスを組み合わせてスタイリングするCSSフレームワーク。クラス名をHTMLに直接記述し、JITコンパイルで使用したクラスのみを出力する。カスタマイズ性が高くNext.jsと相性が良い。' },
  { term: 'CSSモジュール', aliases: ['cssモジュール', 'css modules'], description: 'CSSクラス名をコンポーネントにスコープするビルドツール機能。.module.cssファイルを使い、クラス名がハッシュ化されグローバルな名前衝突を防ぐ。Next.jsがデフォルトでサポートする。' },
  { term: 'CSS-in-JS', aliases: ['css-in-js', 'cssinjs'], description: 'JavaScriptコード内にCSSを記述するスタイリング手法の総称。コンポーネントと密結合したスタイル定義・動的スタイリング・TypeScript補完が特徴。styled-componentsやEmotionが代表例。' },
  { term: 'styled-components', aliases: ['styled components'], description: 'テンプレートリテラルを使ってReactコンポーネントに直接CSSを記述するCSS-in-JSライブラリ。コンポーネント名付きのスタイルを定義でき、propsに基づく動的スタイリングが可能。' },
  { term: 'Emotion', aliases: ['emotion', '@emotion/react', '@emotion/styled'], description: '高パフォーマンスなCSS-in-JSライブラリ。css prop記法とstyled API両方をサポートし、サーバーサイドレンダリングにも対応。MUIなど多くのコンポーネントライブラリの基盤として採用されている。' },
  { term: 'Radix UI', aliases: ['radix ui', 'radix primitives'], description: 'アクセシビリティとカスタマイズ性を重視したReact向けヘッドレスUIコンポーネントライブラリ。スタイルは持たずWAI-ARIAに準拠した振る舞いを提供する。shadcn/uiの基盤として広く使われる。' },
  { term: 'shadcn/ui', aliases: ['shadcn'], description: 'Radix UIとTailwind CSSをベースにしたコンポーネント集。npmパッケージとしてインストールするのではなくコードを直接コピーするアプローチを取り、完全なカスタマイズ性を提供する。' },
  { term: 'Headless UI', aliases: ['headless ui', 'headlessui'], description: 'Tailwind Labsが開発したアクセシビリティ対応の完全スタイルなしUIコンポーネントライブラリ。React・Vueに対応し、Tailwind CSSとの組み合わせを前提に設計されている。' },
  { term: 'Storybook', aliases: ['storybook'], description: 'UIコンポーネントを独立して開発・テスト・ドキュメント化するツール。コンポーネントをisolated環境でレンダリングし、ビジュアルリグレッションテストやデザインシステムの構築に使われる。' },
  { term: 'Framer Motion', aliases: ['framer motion', 'framer-motion'], description: 'Reactアプリケーション向けの宣言的アニメーションライブラリ。シンプルなAPIでジェスチャー・レイアウトアニメーション・共有レイアウトトランジションを実現し、高品質なUIを構築できる。' },
  { term: 'React Router', aliases: ['react router', 'react-router', 'react router dom'], description: 'Reactアプリケーション向けのクライアントサイドルーティングライブラリ。URLとコンポーネントのマッピングを宣言的に定義し、SPA内のナビゲーションを実現する。v6でフック中心のAPIに刷新された。' },
  { term: 'TanStack Router', aliases: ['tanstack router', '@tanstack/router'], description: '型安全性を重視したReact向けの完全型付きルーティングライブラリ。URLパラメータ・検索パラメータの型推論、コード分割との統合、データローディングをサポートする。' },
  { term: 'Redux Toolkit', aliases: ['redux toolkit', 'rtk', '@reduxjs/toolkit'], description: 'Reduxの公式推奨ツールセット。ボイラープレートを大幅に削減するcreateSlice・configureStore・createAsyncThunkなどを提供し、Immerによるイミュータブルな状態更新を簡潔に記述できる。' },
  { term: 'Recoil', aliases: ['recoil'], description: 'Metaが開発したReact向けアトムベースの状態管理ライブラリ。atom（状態の単位）とselector（派生値）で状態を細粒度に管理し、必要なコンポーネントのみ再レンダーする。' },
  { term: 'Jotai', aliases: ['jotai'], description: 'Reactアプリ向けのシンプルなアトムベース状態管理ライブラリ。Recoilに触発されつつよりミニマルなAPIを提供する。atomとuseAtomフックで状態を定義・購読し、不要なプロバイダーを排除する。' },
  { term: 'MobX', aliases: ['mobx'], description: 'オブザーバブルパターンに基づくReact/Vue対応の状態管理ライブラリ。状態をオブザーバブルとして定義し変更を自動追跡、リアクションが自動実行される。型付きクラスとデコレータが特徴。' },
  { term: 'XState', aliases: ['xstate', 'state machine'], description: 'JavaScript/TypeScript向けの状態機械とステートチャートのライブラリ。有限状態機械を使いUIの状態遷移を明示的にモデル化する。複雑なUI状態管理やビジネスロジックのモデリングに有効。' },
  { term: 'React Hook Form', aliases: ['react hook form', 'rhf', 'react-hook-form'], description: 'パフォーマンスに優れたReact向けフォーム管理ライブラリ。非制御コンポーネントとrefベースのアプローチで再レンダーを最小化し、バリデーションはZodやYupと組み合わせることが多い。' },
  { term: 'Zod', aliases: ['zod'], description: 'TypeScript向けのスキーマ宣言とバリデーションライブラリ。スキーマ定義から型推論が自動生成され、ランタイムとコンパイル時の両方でデータ検証ができる。React Hook FormやServer Actionsとの統合が一般的。' },
  { term: 'Yup', aliases: ['yup'], description: 'JavaScript/TypeScript向けのスキーマバリデーションライブラリ。Formikと組み合わせて使われることが多く、連鎖メソッドで直感的なバリデーションルールを記述できる。' },
  { term: 'React Testing Library', aliases: ['react testing library', 'rtl', '@testing-library/react'], description: 'ユーザーの操作視点でReactコンポーネントをテストするライブラリ。実装の詳細ではなくDOMの振る舞いをテストする方針を持ち、アクセシビリティロールなどで要素を検索する。Vitestやjestと組み合わせる。' },
  { term: 'Vitest', aliases: ['vitest'], description: 'Viteを基盤とした高速なユニットテストフレームワーク。Jestと互換性のあるAPIを持ちながら、ESMネイティブで動作しViteの設定を共有できる。React・Vue・SvelteなどのUIテストに対応。' },
  { term: 'Jest', aliases: ['jest'], description: 'Metaが開発したJavaScript向けのテスティングフレームワーク。自動モック、スナップショットテスト、コードカバレッジを内蔵し、React Testing Libraryと組み合わせたコンポーネントテストが一般的。' },
  { term: 'Cypress', aliases: ['cypress'], description: 'ブラウザで実行されるE2Eテストフレームワーク。実際のブラウザ内でテストが動作し、タイムトラベルデバッグ・自動スクリーンショット・ネットワーク傍受などの機能を持つ。コンポーネントテストにも対応。' },
  { term: 'revalidatePath', aliases: ['revalidatepath'], description: 'Next.js App Routerが提供するキャッシュ無効化関数。Server ActionsやRoute Handlersで特定パスのキャッシュをオンデマンドで破棄し、ページを最新データで再生成する。' },
  { term: 'revalidateTag', aliases: ['revalidatetag'], description: 'Next.js App Routerでfetchにタグを付け、Server ActionsやRoute Handlersからタグ単位でキャッシュを無効化する関数。関連するデータをまとめて再検証する際に使われる。' },
  { term: 'エッジランタイム', aliases: ['edge runtime'], description: 'Next.jsのMiddlewareやRoute Handlersで利用できるランタイム環境。CDNエッジに近い場所でV8エンジンベースで実行され低レイテンシを実現するが、Node.js APIへのアクセスは制限される。' },
  { term: 'useFormState', aliases: ['useformstate', 'useformstate hook'], description: 'React DOM（React 19以前）が提供するフック。フォームのServer Actionの戻り値を状態として管理し、送信後のサーバーレスポンスをUIに反映する。React 19でuseActionStateに統合された。' },
  { term: 'flushSync', aliases: ['flushsync'], description: 'ReactのDOM更新を同期的に強制実行するAPI。通常Reactはバッチ処理で更新するが、flushSyncでラップした更新は即座にDOMに反映される。サードパーティライブラリとの統合やアニメーション同期に使う。' },
  { term: 'Strict Mode', aliases: ['strict mode', 'strictmode', 'react.strictmode', 'reactストリクトモード'], description: 'ReactのStrictModeコンポーネントで有効化される開発専用チェック。副作用の重複実行・非推奨APIの検出・意図しない状態の共有検出を行い、将来の機能との互換性問題を早期発見する。' },
  { term: 'Reactプロファイラー', aliases: ['reactプロファイラー', 'profiler', 'react profiler', 'devtools profiler'], description: 'ReactのProfilerコンポーネントとDevToolsのProfilerタブを使ってコンポーネントのレンダリング時間・頻度を計測する機能。パフォーマンスボトルネックの特定と最適化に使われる。' },
  { term: '自動バッチング', aliases: ['automatic batching'], description: 'React 18で強化された機能。イベントハンドラ内に限らずPromise・setTimeout・ネイティブイベントハンドラ内でも複数のstate更新を自動的に1回のレンダーにまとめる最適化。' },
  { term: '合成イベント', aliases: ['synthetic event', 'syntheticevent'], description: 'Reactがブラウザのネイティブイベントをラップした仮想イベントシステム。クロスブラウザ互換性を保証しイベントのプロパティを正規化する。React 17以降はイベントのプーリングは廃止された。' },
  { term: 'コールバックref', aliases: ['callback ref'], description: 'refにコールバック関数を渡すReactの手法。DOMノードがマウント・アンマウントされるときに呼び出され、ref.currentへの代入以上の柔軟な処理が可能。IntersectionObserverの設定などに使われる。' },
  { term: 'React Fragment', aliases: ['react fragment', 'fragment', '<>', 'react.fragment'], description: '余分なDOMノードを追加せずに複数の要素をグループ化するReactコンポーネント。<Fragment>または短縮記法の<>...</>で使用する。テーブル行やリストアイテムのグループ化に便利。' },
  { term: '条件付きレンダリング', aliases: ['conditional rendering'], description: '条件に応じて異なるコンポーネントやJSX要素を表示するReactのパターン。&&演算子・三項演算子・if文などを使い、stateやpropsの値に基づいてUIを動的に切り替える。' },
  { term: 'React 19', aliases: ['react 19', 'react v19'], description: '2024年末にリリースされたReactのメジャーバージョン。useOptimistic・useActionState・use・React Compilerの安定版が含まれる。Server Actionsのネイティブサポートとformアクション統合が主な新機能。' },
  { term: 'use clientディレクティブ', aliases: ['\'use client\'', 'use client'], description: 'Next.js App RouterとReact Server Componentsにおいてファイルの先頭に記述することでそのモジュールをクライアントコンポーネントとしてマークするディレクティブ。state・イベントハンドラ・ブラウザAPIを使う場合に必要。' },
  { term: 'use serverディレクティブ', aliases: ['\'use server\'', 'use server'], description: 'Next.jsのServer Actionsを定義する際にファイルまたは関数の先頭に記述するディレクティブ。クライアントから呼び出せるサーバー側の非同期関数としてマークし、RPC的な呼び出しを可能にする。' },
  { term: 'ティアリング', aliases: ['tearing', 'ui tearing'], description: 'Concurrent Renderingにおいて同一のグローバル状態が一回のレンダー中に複数の値を返し、UIが引き裂かれたような不一致状態になる問題。useSyncExternalStoreを使うことで防止できる。' },
  { term: '時間分割', aliases: ['time slicing'], description: 'Concurrent Renderingの仕組みで、長時間のレンダリング作業を小さなタイムスライスに分割してブラウザのメインスレッドを占有しないようにする技術。ユーザー操作への応答性を維持する。' },
  { term: 'React Server Components', aliases: ['react server components', 'rsc'], description: 'サーバー上でのみレンダリングされるReactコンポーネント。クライアントバンドルに含まれずDBや外部APIへ直接アクセスできる。Next.js App RouterではデフォルトがRSCとなる。' },
  { term: 'Next.js Route Handler', aliases: ['next.js route handler', 'route handler', 'route.ts'], description: 'Next.js App RouterのAPIエンドポイントを定義するファイル。appディレクトリのroute.tsファイルにGET・POST等のHTTPメソッドをエクスポートして実装する。Pages RouterのAPI Routesに相当する。' },
  { term: 'Next.js Middleware', aliases: ['next.js middleware', 'middleware.ts'], description: 'リクエストが完了する前にエッジランタイムで実行されるNext.jsの機能。認証チェック・リダイレクト・リクエストヘッダー操作などをCDNエッジで行いレスポンスを高速化する。' },
  { term: 'Next.js Font', aliases: ['next.js font', 'next/font', 'font optimization'], description: 'Next.jsが提供するフォント最適化機能。Google FontsなどのWebフォントをビルド時にダウンロードしセルフホストすることでプライバシー保護とCLS削減を実現する。' },
  { term: 'createRef', aliases: ['createref', 'react.createref'], description: 'ReactがクラスコンポーネントでDOMノードやコンポーネントインスタンスへの参照を作成するAPI。関数コンポーネントではuseRefが推奨され、createRefは主にクラスコンポーネントで使われる。' },
  { term: 'オンデマンド再検証', aliases: ['on-demand revalidation'], description: 'Next.jsでrevalidatePathやrevalidateTagを使い特定パスやタグに紐づくキャッシュを任意のタイミングで無効化する機能。CMSのコンテンツ更新やデータ変更後に即座にページを最新化する際に使われる。' },
  { term: 'リストレンダリング', aliases: ['list rendering'], description: '配列データをmap()でJSX要素の配列に変換してReactで表示するパターン。各要素に一意のkeyプロパティを指定することが必須で、keyにより差分検出の効率化と不必要なDOM再構築を防ぐ。' },
  { term: 'コンポーネントのライフサイクル', aliases: ['component lifecycle', 'ライフサイクル'], description: 'Reactコンポーネントがマウント・更新・アンマウントされる一連の過程。クラスコンポーネントではライフサイクルメソッドで制御し、関数コンポーネントではuseEffectが同等の処理を担う。' },
  { term: 'Next.js Script', aliases: ['next.js script', 'next/script', 'script component'], description: 'Next.jsが提供するサードパーティスクリプトの読み込みを最適化するコンポーネント。strategyプロパティでbeforeInteractive・afterInteractive・lazyOnloadを指定しスクリプトの読み込みタイミングを制御してパフォーマンスを改善する。' },
  { term: 'Flexbox', aliases: ['flexbox', 'css flexbox', 'flexible box layout'], description: 'CSS3で導入された一次元レイアウトモデル。フレックスコンテナ内のアイテムを主軸・交差軸に沿って柔軟に配置・伸縮させる。ナビゲーションバーやカード列など方向性のある要素配置に最適。' },
  { term: 'CSS Grid', aliases: ['css grid', 'css grid layout', 'grid layout'], description: '行と列の二次元グリッド上に要素を配置するCSSレイアウトシステム。`grid-template-columns`や`grid-template-rows`で領域を定義し、複雑なページレイアウトを宣言的に実現できる。' },
  { term: 'CSS変数', aliases: ['css変数', 'cssカスタムプロパティ', 'css custom properties'], description: 'CSSで`--name: value`の形式で定義し`var(--name)`で参照できるカスタムプロパティ。テーマカラーやスペーシングなど設計トークンを一元管理し、JavaScriptからも動的に変更可能。' },
  { term: 'カスケードレイヤー', aliases: ['@layer', 'cascade layers'], description: 'CSSの`@layer`ルールで宣言する明示的なカスケード優先順位の仕組み。リセット・ベース・コンポーネント・ユーティリティといったレイヤーを定義し、詳細度に依存しない予測可能なスタイル管理を実現する。' },
  { term: 'コンテナクエリ', aliases: ['container query', '@container'], description: '親コンテナのサイズに基づいてスタイルを適用するCSSの仕組み。`container-type`で計測対象を宣言し`@container`ルール内でブレークポイントを指定する。コンポーネントを真に再利用可能にする。' },
  { term: 'メディアクエリ', aliases: ['media query', '@media'], description: '画面幅・解像度・向き・入力手段などの端末特性に応じて異なるスタイルを適用するCSSの仕組み。`@media (max-width: 768px)`のように条件を記述し、レスポンシブデザインの基盤となる。' },
  { term: 'CSS Nesting', aliases: ['css nesting', 'cssネスティング', 'ネイティブcss nesting'], description: 'CSS標準として2023年に主要ブラウザが対応したネスト記法。セレクタの中に子セレクタを直接記述でき、Sassなどのプリプロセッサなしに構造を整理したCSSを書ける。' },
  { term: ':has()セレクタ', aliases: [':has()', 'css :has pseudo-class'], description: '指定した子孫要素を持つ親要素にスタイルを適用する疑似クラス。「親セレクタ」とも呼ばれ、入力が空かどうかでラベルスタイルを変えるなど条件付き親スタイリングを純CSSで実現する。' },
  { term: ':is()疑似クラス', aliases: [':is()', ':is() pseudo-class'], description: '引数に渡したセレクタリストのいずれかに一致する要素を選択する疑似クラス。グループ化により冗長なセレクタを短縮でき、詳細度はリスト中で最も高いセレクタに準じるため注意が必要。' },
  { term: ':where()疑似クラス', aliases: [':where()', ':where() pseudo-class'], description: ':is()と同様にセレクタリストで要素を選択するが、詳細度が常に0になる疑似クラス。ベーススタイルのリセットやライブラリのデフォルトスタイルに適しており、後からの上書きが容易。' },
  { term: 'subgrid', aliases: ['css subgrid', 'grid subgrid'], description: 'CSS Gridの子グリッドが親グリッドのトラック定義を継承する機能。`grid-template-columns: subgrid`と指定することで、ネストされた要素を親グリッドの列に揃えて整列させることができる。' },
  { term: 'aspect-ratio', aliases: ['アスペクト比プロパティ', 'css aspect-ratio'], description: '要素の幅高さの比率を`aspect-ratio: 16 / 9`のように指定するCSSプロパティ。画像・動画・カードなどを固定比率で表示する際にpadding hackを使わずシンプルに実装できる。' },
  { term: 'clamp()', aliases: ['css clamp', 'clamp関数'], description: '最小値・推奨値・最大値の3引数を取りその範囲内の値を返すCSS数学関数。`clamp(1rem, 2.5vw, 2rem)`のようにフォントサイズやスペーシングを流体的にスケールさせるフルード・タイポグラフィに多用。' },
  { term: 'min()関数', aliases: ['css min()', 'min関数'], description: '渡した値のリストから最小値を選んで返すCSS数学関数。`width: min(50%, 400px)`のように、画面幅に応じてコンテンツ幅を上限付きで制限する用途に使われる。' },
  { term: 'max()関数', aliases: ['css max()', 'max関数'], description: '渡した値のリストから最大値を選んで返すCSS数学関数。`font-size: max(1rem, 2vw)`のように最小フォントサイズを保証しつつビューポートに応じて拡大するなど下限保証に使われる。' },
  { term: 'calc()', aliases: ['css calc', 'calc関数'], description: '異なる単位同士の四則演算をCSSで記述できる関数。`width: calc(100% - 2rem)`のように静的値と動的値を組み合わせた計算が可能で、グリッドやスペーシングの精密な制御に利用される。' },
  { term: 'CSS論理プロパティ', aliases: ['css論理プロパティ', 'css logical properties', '論理プロパティ'], description: '物理的な方向（left/right/top/bottom）ではなく書字方向に相対的な論理方向（inline-start/block-end等）でマージン・パディング・ボーダーを指定するCSSプロパティ群。多言語レイアウトを容易にする。' },
  { term: 'writing-mode', aliases: ['css writing-mode', '縦書きcss'], description: 'テキストの流れる方向と行の積み重なり方を制御するCSSプロパティ。`vertical-rl`で日本語縦書きレイアウトを実現でき、論理プロパティと組み合わせることで多言語組版に対応する。' },
  { term: 'gap', aliases: ['css gap', 'row-gap', 'column-gap'], description: 'FlexboxおよびCSS Gridのアイテム間隔を指定するCSSプロパティ。`gap: 1rem 2rem`で行列の間隔を一括指定でき、marginを使ったハック不要でクリーンな間隔管理が可能になる。' },
  { term: 'place-items', aliases: ['css place-items', 'align-items shorthand'], description: 'CSS Gridで`align-items`と`justify-items`を一括指定するショートハンドプロパティ。`place-items: center`で要素を縦横中央揃えにする最短の記述として頻繁に使われる。' },
  { term: 'PostCSS', aliases: ['postcss', 'css後処理ツール'], description: 'プラグインシステムでCSSを変換するJavaScriptベースのツール。Autoprefixerでベンダープレフィックスを付与したり、cssnanoで圧縮したり、未来のCSS構文を現在のブラウザ向けに変換するなど多用途。' },
  { term: 'Sass/SCSS', aliases: ['sass/scss', 'sass', 'scss', 'css プリプロセッサ'], description: '変数・ネスト・ミックスイン・継承などの機能をCSSに追加するプリプロセッサ。SCSS構文はCSSのスーパーセットで既存CSSと互換性があり、大規模プロジェクトのスタイル管理を効率化する。' },
  { term: 'BEM', aliases: ['bem', 'block element modifier', 'bem記法'], description: 'Block__Element--Modifierのパターンでクラス名を構造化するCSS命名規則。コンポーネントの構造と状態をクラス名から読み取れるようにし、大規模チームでの一貫性とスタイルの再利用を促進する。' },
  { term: 'OOCSS', aliases: ['oocss', 'object-oriented css', 'オブジェクト指向css'], description: 'CSSをコンテナとコンテンツを分離した「オブジェクト」として設計する方法論。再利用可能な視覚的パターンをクラスとして定義しスタイルの重複を排除することで、保守性と一貫性を高める。' },
  { term: 'SMACSS', aliases: ['smacss', 'scalable and modular architecture for css'], description: 'CSS設計をBase・Layout・Module・State・Themeの5カテゴリに分類するアーキテクチャガイドライン。カテゴリごとに命名規則と責務を明確にし、大規模なCSSのスケーラビリティを保つ。' },
  { term: 'CSS詳細度', aliases: ['css詳細度', 'css specificity', '詳細度', 'セレクタ詳細度'], description: 'CSSの競合するルールのどちらが優先されるかを決めるスコア体系。インラインスタイル>IDセレクタ>クラス・属性>要素の順に高く、詳細度の予測困難さがカスケードレイヤー導入の背景にある。' },
  { term: 'カスケード', aliases: ['css cascade', 'カスケードアルゴリズム'], description: '複数のCSSルールが同一要素に適用される場合にどのスタイルを採用するか決定するアルゴリズム。起源（ブラウザ/ユーザー/作者）・カスケードレイヤー・詳細度・記述順の優先順位で解決される。' },
  { term: '継承（CSS）', aliases: ['継承（css）', 'css inheritance', 'css継承'], description: '親要素に指定したCSSプロパティが子孫要素に自動的に引き継がれる仕組み。`color`や`font-family`は既定で継承されるが`width`や`border`は継承されない。`inherit`値で明示的に継承を強制できる。' },
  { term: 'ボックスモデル', aliases: ['css box model', 'box model'], description: 'CSSでHTML要素の占める空間をcontent・padding・border・marginの4層で表現するモデル。`box-sizing: border-box`にするとpadding・borderを含めたサイズを指定幅に収められるため現代的な実装の標準。' },
  { term: 'マージン相殺', aliases: ['margin collapse', 'マージンの折り畳み'], description: '縦方向に隣接するブロック要素のmarginが合計ではなく大きい方の値のみ適用される現象。Flexbox・Gridのコンテナ内やfloat要素では発生しない。意図しないスペーシングの原因になりやすい。' },
  { term: '重ね合わせコンテキスト', aliases: ['stacking context', 'スタッキングコンテキスト'], description: 'z-indexが適用される独立した三次元の積み重なり空間。`position`+`z-index`指定、`opacity<1`、`transform`、`filter`、`isolation: isolate`などが新しいスタッキングコンテキストを生成する。' },
  { term: 'z-index', aliases: ['css z-index', '重なり順'], description: '重ね合わせコンテキスト内で要素の前後の重なり順を制御するCSSプロパティ。値が大きいほど手前に表示される。`position`が`static`以外の場合に有効で、スタッキングコンテキストを理解しないと意図通りに機能しない。' },
  { term: 'position: sticky', aliases: ['css sticky', 'sticky positioning'], description: '通常フローに従いながらスクロールで閾値に達するとビューポートに固定されるCSSの配置モード。`position: sticky`+`top`等の閾値で動作し、スクロールが閾値内に戻ると元の位置に戻る。' },
  { term: 'position: fixed', aliases: ['css fixed', 'fixed positioning'], description: 'ビューポート（または直近のtransform/filterを持つ祖先）に対して固定された位置に配置されるCSSの配置モード。スクロールしても動かないナビゲーションバーやトーストUI、モーダルオーバーレイに使われる。' },
  { term: 'position: absolute', aliases: ['css absolute', 'absolute positioning'], description: '最も近い`position: static`以外の祖先を基準に絶対座標で配置されるCSSの配置モード。通常フローから外れるため周囲の要素に影響を与えず、ドロップダウンメニューやツールチップの実装に多用される。' },
  { term: 'overflow', aliases: ['css overflow', 'overflow hidden'], description: 'コンテンツがコンテナのサイズを超えた場合の表示方法を制御するCSSプロパティ。`hidden`で切り取り・`scroll`でスクロールバー表示・`auto`で必要時のみ表示。新しいブロック整形コンテキストも生成する。' },
  { term: 'clip-path', aliases: ['css clip-path', 'クリッピングパス'], description: '要素の表示領域を任意の形状にクリップするCSSプロパティ。`circle()`・`polygon()`・`inset()`・SVGのclipPathPathを参照可能で、アニメーションとの組み合わせで複雑な形状変化エフェクトも実現できる。' },
  { term: 'CSSフィルター', aliases: ['cssフィルター', 'css filter', 'filter', 'css filter property'], description: '要素にぼかし・色変換・彩度・コントラストなどのグラフィカル効果を適用するCSSプロパティ。`filter: blur(4px) grayscale(50%)`のように複数の関数を重ねられ、ホバーエフェクトや画像加工UIに利用される。' },
  { term: 'backdrop-filter', aliases: ['css backdrop-filter', '背景ぼかし'], description: '要素の後ろに描画されたコンテンツにフィルター効果を適用するCSSプロパティ。`backdrop-filter: blur(10px)`でガラスモーフィズムUI（すりガラス効果）を実現する際に使われ、ヘッダーやモーダル背景に多用される。' },
  { term: 'mix-blend-mode', aliases: ['cssブレンドモード', 'blend mode'], description: '要素と背景の色をどのように合成するかを指定するCSSプロパティ。Photoshopの描画モードに相当し、`multiply`・`screen`・`overlay`などの値でデザイン上の重ね合わせ表現を純CSSで実現できる。' },
  { term: 'CSS Transform', aliases: ['css transform', 'transformプロパティ'], description: '要素を移動・回転・拡縮・傾斜させるCSSプロパティ。`translate`・`rotate`・`scale`・`skew`関数の組み合わせが可能で、GPU合成レイヤーに昇格しアニメーションを高速化する効果もある。' },
  { term: 'CSS Transition', aliases: ['css transition', 'transitionプロパティ', 'css遷移'], description: 'プロパティ値の変化を指定した時間と緩急で滑らかに補間するCSSの仕組み。`transition: opacity 0.3s ease`のように対象プロパティ・時間・イージング関数を指定し、ホバーや状態変化にアニメーションを付ける。' },
  { term: 'CSS Animation', aliases: ['css animation', 'animationプロパティ', 'cssアニメーション'], description: '`@keyframes`で定義したアニメーションシーケンスを要素に適用するCSSプロパティ。繰り返し回数・方向・遅延・充填モードを細かく制御でき、トランジションと異なりJavaScriptなしで複雑な多段アニメーションを表現できる。' },
  { term: '@keyframes', aliases: ['css @keyframes', 'キーフレーム'], description: 'CSSアニメーションの各中間状態（キーフレーム）を`from`/`to`またはパーセンテージで定義するアットルール。`@keyframes slidein { from { transform: translateX(-100%) } to { transform: translateX(0) } }`のように記述する。' },
  { term: 'will-change', aliases: ['css will-change', '合成レイヤー昇格'], description: '要素のどのプロパティが変化するかブラウザに事前通知するCSSプロパティ。`will-change: transform`で要素をGPU合成レイヤーに昇格させアニメーションのちらつきを防ぐが、過剰使用はメモリを消費するため必要な場合のみ使う。' },
  { term: 'contain', aliases: ['css contain', 'コンテナ分離'], description: '要素のレイアウト・ペイント・スタイルの影響範囲をその要素に閉じ込めるCSSプロパティ。`contain: layout paint`でブラウザが再計算するスコープを限定し、大規模なUIのレンダリングパフォーマンスを向上させる。' },
  { term: 'content-visibility', aliases: ['css content-visibility', '仮想化css'], description: '要素がビューポート外にある場合のレンダリングをスキップするCSSプロパティ。`content-visibility: auto`で長いページの初期表示を大幅に高速化でき、ブラウザが表示領域のみをレンダリングする「CSS仮想化」を実現する。' },
  { term: 'font-display', aliases: ['css font-display', 'webフォント表示戦略'], description: 'Webフォントのロード中にフォールバックフォントの表示を制御する`@font-face`内のディスクリプタ。`swap`でFOITを防ぎテキストを即表示・`optional`で帯域を節約するなどパフォーマンスと視覚安定性のトレードオフを調整する。' },
  { term: '@font-face', aliases: ['cssカスタムフォント', 'webフォント定義'], description: 'カスタムフォントファイルをWebページで使用するためのCSSアットルール。フォントの名前・ソース（woff2など）・スタイル・ウェイト・Unicodeレンジを定義し、ブラウザが必要なフォントサブセットのみをダウンロードできる。' },
  { term: 'CSS Scroll Snap', aliases: ['css scroll snap', 'scroll snap', 'scroll-snap-type'], description: 'スクロール終了時に特定のスナップポイントに吸着する動作を実現するCSSプロパティ群。コンテナに`scroll-snap-type`・子要素に`scroll-snap-align`を指定しカルーセルや縦スクロールギャラリーをJSなしで実装できる。' },
  { term: 'scroll-behavior', aliases: ['css scroll-behavior', 'スムーススクロール'], description: 'アンカーリンクなどによるプログラムスクロールの動作を制御するCSSプロパティ。`scroll-behavior: smooth`でページ内リンクを滑らかにスクロールさせられ、`prefers-reduced-motion`と組み合わせてアクセシビリティにも配慮する。' },
  { term: 'overscroll-behavior', aliases: ['css overscroll-behavior', 'スクロール連鎖防止'], description: 'スクロールがコンテンツの端に達したときの動作を制御するCSSプロパティ。`overscroll-behavior: contain`でモーダルや引き出しUIのスクロールが親要素に連鎖するのを防ぎ、スクロール境界でのバウンスエフェクトも制御できる。' },
  { term: 'touch-action', aliases: ['css touch-action', 'タッチ操作制御'], description: '要素でのタッチ操作（パン・ピンチズームなど）をブラウザとJSのどちらが処理するかを指定するCSSプロパティ。`touch-action: pan-y`でY方向のみブラウザネイティブスクロールを許可し、カスタムスワイプ実装との干渉を防ぐ。' },
  { term: 'pointer-events', aliases: ['css pointer-events', 'マウスイベント制御'], description: '要素がマウス・タッチ・ペンなどのポインターイベントのターゲットになれるかどうかを制御するCSSプロパティ。`pointer-events: none`で透明なオーバーレイや無効化されたUIコントロールをクリックスルー可能にする。' },
  { term: 'accent-color', aliases: ['css accent-color', 'フォームアクセントカラー'], description: 'チェックボックス・ラジオボタン・レンジスライダーなどのネイティブUIコントロールのテーマ色を指定するCSSプロパティ。複雑なカスタムスタイルなしでフォームコントロールをブランドカラーに統一できる。' },
  { term: 'color-scheme', aliases: ['css color-scheme', 'カラースキーム'], description: 'ページや要素が対応するカラーモード（light/dark）をブラウザに通知するCSSプロパティ。`color-scheme: light dark`と指定すると、スクロールバーやフォームコントロールなどのシステムUIも自動的にダークモードに適応する。' },
  { term: 'prefers-color-scheme', aliases: ['css prefers-color-scheme', 'ダークモードメディアクエリ'], description: 'ユーザーのOSカラーモード設定（light/dark）を検出するCSSメディア特性。`@media (prefers-color-scheme: dark)`でダークモード用のスタイルを定義し、システム設定に自動追従するテーマ切り替えを実装できる。' },
  { term: 'prefers-reduced-motion', aliases: ['css prefers-reduced-motion', 'モーション軽減設定'], description: 'OSの「視差効果を減らす」設定を検出するCSSメディア特性。`@media (prefers-reduced-motion: reduce)`でアニメーションを無効化または簡略化することで、前庭障害などを持つユーザーへのアクセシビリティを確保する。' },
  { term: '@supports', aliases: ['css @supports', '機能クエリ'], description: 'ブラウザが特定のCSSプロパティや値をサポートするかどうかを条件にスタイルを適用するアットルール。`@supports (display: grid)`でGrid未対応ブラウザのフォールバックを提供するプログレッシブエンハンスメントに使う。' },
  { term: 'ブロック整形コンテキスト', aliases: ['bfc', 'block formatting context'], description: 'ブロックレベル要素が独立してレイアウトされる独自の空間。`overflow: hidden`・`float`・`display: flow-root`などで生成され、内部のfloatを包含したりマージン相殺を防いだりする効果がある。' },
  { term: 'インライン整形コンテキスト', aliases: ['ifc', 'inline formatting context'], description: 'テキストや`display: inline`要素が行ボックス内に並べられるレイアウトの仕組み。行の高さは`line-height`と各インライン要素の高さから計算され、`vertical-align`で要素の縦位置を制御する。' },
  { term: 'フレックスコンテナ', aliases: ['flex container', 'flexコンテナ'], description: '`display: flex`または`display: inline-flex`を指定した要素。直接の子要素がフレックスアイテムとなり、`flex-direction`・`justify-content`・`align-items`・`flex-wrap`などのプロパティで子の配置を制御する。' },
  { term: 'フレックスアイテム', aliases: ['flex item', 'flexアイテム'], description: 'フレックスコンテナの直接の子要素。`flex-grow`・`flex-shrink`・`flex-basis`の3値をショートハンドの`flex`で制御し、利用可能なスペースへの伸縮と初期サイズを設定する。' },
  { term: 'グリッドトラック', aliases: ['grid track', 'グリッド列・行'], description: 'CSS Gridの行または列の一区画。`grid-template-columns: repeat(3, 1fr)`のように`fr`単位や`minmax()`関数でサイズを指定し、グリッドラインに囲まれた帯状の空間としてレイアウトを構成する。' },
  { term: 'グリッドエリア', aliases: ['grid area', 'grid-template-areas'], description: 'CSS Gridで名前付き領域を定義し、セルを結合したレイアウトを宣言的に記述する仕組み。`grid-template-areas`で「header」「sidebar」「main」などの名前付き領域を視覚的に配置し、各要素を`grid-area`で割り当てる。' },
  { term: 'fr単位', aliases: ['fr unit', 'css fr', 'フレクシブルトラック'], description: 'CSS Gridのトラックサイズ指定に使う割合単位。使用可能な空間を分数（fraction）で分配し、`grid-template-columns: 1fr 2fr`で右列が左列の2倍幅になる。`minmax()`と組み合わせて最小幅を保証しつつ均等分割できる。' },
  { term: '論理的プロパティ（inline/block）', aliases: ['inline-start', 'block-end', 'css logical'], description: 'CSSの物理的方向（left/top）に対して書字方向に相対的な方向（inline-start/block-end等）でスタイルを指定するプロパティ。`margin-inline-start`は左から右書きでは`margin-left`に相当し、RTLや縦書きに自動適応する。' },
  { term: 'CSS変数のフォールバック', aliases: ['css変数のフォールバック', 'var() fallback', 'css変数デフォルト値'], description: '`var(--color, blue)`のようにCSS変数が未定義の場合に使うデフォルト値を指定する構文。コンポーネントが外部から変数を受け取りつつ独自のデフォルトスタイルを持つ設計を可能にし、テーマ対応UIの実装に役立つ。' },
  { term: 'カスタムプロパティの継承', aliases: ['css custom property inheritance', 'css変数スコープ'], description: 'CSS変数（カスタムプロパティ）は通常のCSSプロパティと同様に継承される。`:root`で定義した変数はページ全体に、特定のコンポーネントで上書きした変数はその子孫にのみ適用されるスコープを形成する。' },
  { term: 'ユーティリティファーストCSS', aliases: ['ユーティリティファーストcss', 'utility-first css', 'アトミックcss'], description: '単一の視覚的機能を持つ小さなクラスを組み合わせてUIを構築するCSS手法。Tailwind CSSが代表的で、カスタムCSSの記述を最小限にしながらデザインの一貫性を保ちHTMLのクラス属性でスタイルを表現する。' },
  { term: 'box-shadow', aliases: ['css box-shadow', 'ボックスシャドウ'], description: '要素のボックスにドロップシャドウを付与するCSSプロパティ。水平・垂直オフセット・ぼかし半径・拡散半径・色を指定でき、カンマ区切りで複数のシャドウを重ねられる。キーワードで内側シャドウも表現可能。' },
  { term: 'text-shadow', aliases: ['css text-shadow', 'テキストシャドウ'], description: 'テキストにシャドウ効果を付与するCSSプロパティ。水平・垂直オフセット・ぼかし半径・色を指定し、複数のシャドウをカンマ区切りで重ねることでグロー効果やエンボス効果などのタイポグラフィ表現を実現できる。' },
  { term: 'フルードタイポグラフィ', aliases: ['fluid typography', '流体タイポグラフィ', '可変フォントサイズ'], description: 'ビューポート幅に応じてフォントサイズが連続的に変化するタイポグラフィ手法。`clamp()`・`vw`単位・CSS計算を組み合わせ、特定のブレークポイントなしに最小・最大サイズの範囲で滑らかにスケールする。' },
  { term: 'CSSグリッドの暗黙的グリッド', aliases: ['cssグリッドの暗黙的グリッド', 'implicit grid', 'css implicit tracks'], description: 'CSS Gridで`grid-template-columns/rows`に明示しなかった行・列が自動生成される領域。`grid-auto-rows`や`grid-auto-columns`でサイズを制御し、`grid-auto-flow`で自動配置の方向を指定する。' },
  { term: 'CSS変数とJavaScript連携', aliases: ['css変数とjavascript連携', 'css variables js interop', 'setproperty', 'getcomputedstyle'], description: 'JavaScriptから`element.style.setProperty(\'--color\', \'red\')`でCSS変数を動的に変更する連携手法。テーマ切り替えやインタラクティブなアニメーション値の更新をJSとCSSが協調して処理するパターン。' },
  { term: 'ベンダープレフィックス', aliases: ['vendor prefix', '-webkit-', '-moz-'], description: '実験的CSSプロパティをブラウザ固有の接頭辞（`-webkit-`・`-moz-`・`-ms-`）付きで実装した歴史的な仕組み。現在は標準化が進みPostCSS+Autoprefixerで自動付与するのが一般的で、新規にプレフィックスを手書きする機会は減少している。' },
  { term: 'アダプティブデザイン', aliases: ['adaptive design', '適応型デザイン'], description: '特定のブレークポイントで異なる固定レイアウトを切り替えるデザイン手法。レスポンシブデザインが流体的に変化するのに対し、アダプティブは段階的にデザインを切り替える。デバイス別に最適化された体験を提供する。' },
  { term: 'カラーシステム', aliases: ['design color system', 'カラートークン'], description: 'デザインシステムにおけるカラーの命名・階層・適用ルールの体系。プリミティブカラー（具体的な色値）・セマンティックカラー（用途別の意味）・コンポーネントカラーの3層構造でCSS変数と組み合わせてテーマ管理する。' },
  { term: 'CSSリセット', aliases: ['cssリセット', 'css reset', 'normalize.css', 'modern css reset'], description: 'ブラウザ間のデフォルトスタイルの差異を均一化するCSSファイル。古典的なEric Meyerリセット・差異のみを補正するNormalize.css・現代的なAndy Bellリセットなどがあり、スタイルの一貫性を確保する出発点となる。' },
  { term: 'CSSスペーシングシステム', aliases: ['cssスペーシングシステム', 'css spacing scale', 'スペーシングスケール', 'スペースシステム'], description: '余白・パディング・ギャップに一貫した数値スケール（4px・8px・16px等）を適用するデザインシステムの一要素。CSS変数やTailwindのスペーシング設定として実装し、視覚的なリズムと整合性を確保する。' },
  { term: 'display: grid vs flex', aliases: ['grid vs flexbox', 'レイアウト選択'], description: 'CSS GridとFlexboxの使い分け指針。Gridは二次元レイアウト（ページ全体・カード格子など）に、Flexboxは一次元の整列（ナビゲーション・ボタン行など）に向く。両者を組み合わせて使うことも多い。' },
  { term: 'CSSアーキテクチャ', aliases: ['cssアーキテクチャ', 'css architecture', 'css設計'], description: '大規模プロジェクトでCSSをスケーラブルかつ保守可能に管理するための設計方針の総称。BEM・OOCSS・SMACSSといった命名規則・CSS Modules・CSS-in-JSなどのスコープ管理手法・カスケードレイヤーによる優先順位管理を組み合わせる。' },
  { term: 'セレクタパフォーマンス', aliases: ['css selector performance', 'セレクタ効率'], description: 'CSSセレクタがブラウザによって右から左に評価されることを理解した上でパフォーマンスを考慮した書き方をすること。ユニバーサルセレクタや過度に深いネストは避け、クラスセレクタを主体にする。現代ブラウザでは実用上の差は小さい。' },
  { term: 'ペイントとレイアウト', aliases: ['css paint layout', 'レイアウト再計算', 'リペイント'], description: 'ブラウザのレンダリングパイプラインの工程。Layoutはサイズ・位置を計算しPaintはピクセルを描画する。`transform`・`opacity`の変化はLayoutをスキップしCompositeのみで処理されるため高パフォーマンスなアニメーションになる。' },
  { term: 'CSSグラデーション', aliases: ['cssグラデーション', 'css gradient', 'linear-gradient', 'radial-gradient'], description: '2色以上の色を滑らかに遷移させる背景画像を生成するCSS関数。`linear-gradient`で線形・`radial-gradient`で放射状・`conic-gradient`で円錐状のグラデーションを作成でき、ベクター的なカラーパターン生成にも使われる。' },
  { term: 'CSSシェイプ', aliases: ['cssシェイプ', 'css shapes', 'shape-outside', 'css shape-outside'], description: 'フロートした要素の周囲に画像や多角形に沿ったテキスト回り込みを実現するCSSプロパティ。`shape-outside: circle()`や`shape-outside: url(image.png)`で非矩形のレイアウトを実装でき、雑誌風デザインに使われる。' },
  { term: 'object-fit', aliases: ['css object-fit', '画像フィット'], description: 'imgやvideoなどのコンテンツが要素ボックスに収まる方法を指定するCSSプロパティ。`object-fit: cover`でアスペクト比を保ちながら要素全体を埋め、`contain`では全体が収まるよう縮小する。`object-position`で焦点位置も制御できる。' },
  { term: 'CSSカスタムメディア', aliases: ['cssカスタムメディア', '@custom-media', 'css custom media'], description: 'メディアクエリに名前付きエイリアスを定義するCSS仕様（Level 5）。`@custom-media --mobile (max-width: 768px)`と定義し`@media (--mobile)`で参照することで、ブレークポイントをCSS変数のように一元管理できる。' },
  { term: 'CSSパフォーマンス最適化', aliases: ['cssパフォーマンス最適化', 'css performance', 'css optimization'], description: 'CSSのロード・パース・計算・レンダリングを最適化する手法の総称。クリティカルCSSのインライン化・未使用CSS削除（PurgeCSS）・`contain`・`content-visibility`の活用・レンダリングブロックの回避などが含まれる。' },
  { term: 'CSS環境変数', aliases: ['css環境変数', 'env()', 'css environment variables', 'safe-area-inset'], description: 'ブラウザや端末が提供する値を参照する`env()`関数。`env(safe-area-inset-bottom)`でiPhoneのホームインジケーター領域を取得し、コンテンツがノッチやセーフエリアに重ならないレイアウトを実装できる。' },
  { term: 'CSSハイライト疑似要素', aliases: ['cssハイライト疑似要素', '::selection', '::highlight', 'cssカスタムハイライト'], description: 'テキスト選択（`::selection`）やブラウザのテキストハイライト（`::highlight()`）のスタイルを制御するCSS疑似要素。選択時の背景色・文字色をブランドカラーに合わせたり、検索ハイライトのスタイルをカスタマイズできる。' },
  { term: 'CSSスクロールバースタイリング', aliases: ['cssスクロールバースタイリング', '::-webkit-scrollbar', 'scrollbar-width', 'scrollbar-color'], description: 'スクロールバーの外観をCSSでカスタマイズする手法。標準化された`scrollbar-width`・`scrollbar-color`（Firefox・Chrome 121+対応）と、Webkit固有の`::-webkit-scrollbar`疑似要素による詳細カスタマイズがある。' },
  { term: 'カラーP3', aliases: ['カラーp3', 'p3 color space', 'display-p3', 'wide gamut'], description: 'sRGBより広い色域を持つDisplay P3カラースペースをCSSで指定する方法。`color(display-p3 1 0 0)`やHDR対応の`oklch()`・`lch()`関数で鮮やかな色を表現でき、対応ディスプレイで豊かな色彩を提供できる。' },
  { term: 'CSSレイヤーと詳細度', aliases: ['cssレイヤーと詳細度', '@layer specificity', 'レイヤー詳細度', 'cascade layer specificity'], description: '`@layer`で宣言したスタイルは、同じ詳細度でも後から宣言したレイヤーが優先される。レイヤー外のスタイルは常にレイヤー内のスタイルより優先され、`!important`はレイヤーの優先順位を逆転させる。' },
  { term: 'CSSマスキング', aliases: ['cssマスキング', 'css mask', 'mask-image', 'mask-composite'], description: '要素の表示領域を画像やグラデーションで定義するCSSプロパティ群。`mask-image`でSVGや画像をマスクとして使用し、`clip-path`より柔軟な透過表現が可能。グラデーションフェードアウト効果に多用される。' },
  { term: 'CSSカウンター', aliases: ['cssカウンター', 'css counters', 'counter-increment', 'counter()'], description: 'CSSだけで要素の番号付けを自動化する仕組み。`counter-reset`で初期化し`counter-increment`でカウントし`counter()`関数で`::before`疑似要素に表示する。目次の章番号や順序付きリストのカスタムスタイルに使われる。' },
  { term: 'CSS比較セレクタ', aliases: ['css比較セレクタ', 'css quantity queries', 'nth-child', 'nth-of-type'], description: '要素数や位置に基づいてスタイルを適用する疑似クラスの総称。`:nth-child(2n+1)`・`:nth-of-type()`・`:nth-last-child()`などを使い、グリッドの最終行のみ下線を外すなど条件付きスタイリングを実現する。' },
  { term: 'HTTPキャッシュコントロール', aliases: ['httpキャッシュコントロール', 'http cache control', 'cache-control'], description: 'HTTPのCache-Controlヘッダーを用いてレスポンスのキャッシュ動作を制御する仕組みです。max-ageやno-cacheなどのディレクティブで挙動を指定します。' },
  { term: 'WCAG', aliases: ['wcag', 'web content accessibility guidelines', 'ウェブコンテンツアクセシビリティガイドライン'], description: 'Web Content Accessibility Guidelinesの略。W3CのWAIが策定したウェブアクセシビリティの国際ガイドライン。知覚可能・操作可能・理解可能・堅牢の4原則を軸に、A/AA/AAAの3段階の達成基準を定義する。' },
  { term: 'aria-label', aliases: ['aria-label属性'], description: 'ARIA属性の一つ。視覚的なテキストラベルがない要素（アイコンボタンなど）にアクセシブルな名前を直接文字列として付与する。スクリーンリーダーはこの値を読み上げてユーザーに要素の目的を伝える。' },
  { term: 'aria-describedby', aliases: ['aria-describedby属性'], description: 'ARIA属性の一つ。対象要素の補足説明テキストを持つ別要素のIDを参照することで、スクリーンリーダーがその説明を読み上げられるようにする。フォームフィールドのエラーメッセージやヒントテキストの関連付けによく使われる。' },
  { term: 'aria-live', aliases: ['aria-live属性', 'ライブリージョン属性'], description: 'ARIA属性の一つ。ページを再読み込みせずに動的に更新されるコンテンツ領域をスクリーンリーダーに通知するために使う。off・polite・assertiveの値によってアナウンスの優先度を制御する。' },
  { term: 'role属性', aliases: ['role attribute', 'ariaロール'], description: 'HTML要素がどのようなUI部品であるかを支援技術に伝えるためのARIA属性。ネイティブのHTMLセマンティクスで表現できない場合に補完的に使用し、button・dialog・alertなどの値を持つ。誤用するとアクセシビリティを損なうリスクがある。' },
  { term: 'スクリーンリーダー', aliases: ['screen reader', '音声読み上げソフト'], description: '視覚障害者などが画面上のテキストやUI要素を音声で聴けるようにする支援技術ソフトウェア。NVDA・JAWS・VoiceOver・TalkBackなどが代表例。ARIA属性やセマンティックHTMLを活用してアクセシブルな体験を提供する必要がある。' },
  { term: 'タブ順序', aliases: ['tab order', 'フォーカス順序'], description: 'キーボードのTabキーを押したときにフォーカスが移動する順序。視覚的なレイアウトと一致した論理的な順序であることが重要で、tabindex属性で明示的に制御できる。不適切なタブ順序はキーボードユーザーの操作性を著しく損なう。' },
  { term: 'tabindex', aliases: ['tab index', 'tabindex属性'], description: 'HTML要素がキーボードフォーカスを受け取れるかどうかと、タブ順序上の位置を制御するHTML属性。0は自然なDOM順に組み込み、-1はプログラム的フォーカスのみ許可、正の値は順序を明示指定（非推奨）という使い分けが基本。' },
  { term: 'カラーコントラスト比', aliases: ['color contrast ratio', 'コントラスト比'], description: '前景色と背景色の明度差を数値化した比率。WCAGではAA達成基準として通常テキストは4.5:1以上、大きなテキストは3:1以上を要求する。コントラスト不足は弱視や色覚異常のユーザーに深刻な読み取り困難をもたらす。' },
  { term: '代替テキスト', aliases: ['alt text', 'alt属性', 'オルトテキスト'], description: '画像が表示できない場合や、スクリーンリーダーを使用するユーザーに画像の内容を伝えるためのテキスト。imgタグのalt属性で指定する。装飾的な画像はalt=""と空にし、意味のある画像には内容を簡潔に記述する。' },
  { term: 'ランドマーク', aliases: ['landmark', 'ariaランドマーク', 'ランドマークロール'], description: 'ページのコンテンツを大きな領域に分類し、スクリーンリーダーユーザーがページ内を素早くナビゲートできるようにするARIAの仕組み。header・main・nav・footer・aside・sectionなどのHTML要素や対応するARIAロールで定義する。' },
  { term: 'ライブリージョン', aliases: ['live region', 'aria-live領域'], description: 'ページ読み込み後に動的に変化するコンテンツ領域で、スクリーンリーダーに変更を自動通知する仕組み。aria-live属性で設定し、チャット更新・エラーメッセージ・プログレス通知などに活用される。' },
  { term: 'フォーカスリング', aliases: ['focus ring', 'フォーカスインジケーター', 'focus indicator'], description: 'キーボードやその他の入力デバイスでフォーカスされた要素を視覚的に示すアウトライン表示。CSSのoutlineプロパティで実装される。WCAGではフォーカスの可視性を要求しており、outline: noneで非表示にすることはアクセシビリティ上の問題を招く。' },
  { term: 'ヘディング構造', aliases: ['heading structure', '見出し階層'], description: 'h1からh6までの見出し要素を論理的な階層で使用するページ構造。スクリーンリーダーユーザーは見出しジャンプでページをナビゲートするため、レベルを飛ばさず意味的に正しい階層を保つことがアクセシビリティの基礎となる。' },
  { term: 'フォームアクセシビリティ', aliases: ['form accessibility', 'アクセシブルフォーム'], description: 'フォームコントロールとそのラベルを正しく関連付け、エラーメッセージを適切に通知し、送信状態や必須項目を明示するアクセシブルなフォーム設計の実践。label要素・aria-required・aria-invalid・aria-describedbyなどを組み合わせて実現する。' },
  { term: 'Figma', aliases: ['figma'], description: 'ブラウザベースのUIデザイン・プロトタイピングツール。リアルタイムコラボレーション、コンポーネント管理、デザイントークン、プラグインエコシステムを備え、デザイナーと開発者の共同作業を支援するデファクトスタンダードとなっている。' },
  { term: 'コンポーネントライブラリ', aliases: ['component library'], description: '再利用可能なUIコンポーネント（ボタン、フォーム、カードなど）をまとめたコレクション。デザインシステムの実装の中核をなし、開発の効率化・UIの一貫性・品質の均一化を実現する。Material UI・Ant Design・shadcn/uiなどが代表例。' },
  { term: 'アトミックデザイン', aliases: ['atomic design'], description: 'Brad Frost が提唱したUIデザイン手法。原子（Atoms）→分子（Molecules）→有機体（Organisms）→テンプレート（Templates）→ページ（Pages）の5段階の階層でUIを構築し、コンポーネントの再利用性と一貫性を高める。' },
  { term: 'Atoms', aliases: ['atoms', '原子', 'アトム'], description: 'アトミックデザインにおける最小単位のUIコンポーネント。ボタン・入力フィールド・ラベル・アイコンなど、それ以上分解できない基本的なHTML要素やコンポーネントを指す。他の全コンポーネントの構成要素となる。' },
  { term: 'Molecules', aliases: ['molecules', '分子', 'モレキュール'], description: 'アトミックデザインにおいて、Atomsを組み合わせた機能的なUIコンポーネント。検索ボックス（ラベル＋入力フィールド＋ボタン）のように、複数のAtomが連携して単一の目的を果たす中間的な構成単位。' },
  { term: 'Organisms', aliases: ['organisms', '有機体', 'オーガニズム'], description: 'アトミックデザインにおいて、AtomsとMoleculesを組み合わせた比較的複雑なUIセクション。ナビゲーションバー・商品カードグリッド・フッターなど、ページを構成する独立した意味のある領域を指す。' },
  { term: 'ブランドガイドライン', aliases: ['brand guidelines', 'ブランドマニュアル'], description: '企業やプロダクトのブランドを一貫して表現するための規則集。ロゴの使用方法、カラーパレット、タイポグラフィ、トーン＆マナーなどを定義し、あらゆるタッチポイントでのブランド体験の統一を図る。' },
  { term: 'カードソーティング', aliases: ['card sorting'], description: 'ユーザーがコンテンツをどのようにカテゴリ分けするかを理解するためのUXリサーチ手法。参加者に情報をカードに書いて分類・グループ化してもらうことで、ナビゲーション設計や情報アーキテクチャの改善に活用する。' },
  { term: 'ヒューリスティック評価', aliases: ['heuristic evaluation', 'ニールセンの10原則'], description: 'Jakob Nielsenが提唱した10のユーザビリティ原則（ヒューリスティクス）に基づき、専門家がUIを評価する検査手法。ユーザーテストより低コストで実施でき、システムの可視性・フィードバック・エラー防止などの観点から問題を発見する。' },
  { term: 'ユーザージャーニーマップ', aliases: ['user journey map', 'カスタマージャーニーマップ', 'customer journey map'], description: 'ユーザーが目標を達成するまでの一連の行動・感情・思考・タッチポイントを時系列で可視化した図。ユーザーの体験全体を俯瞰し、痛点（ペインポイント）や改善機会を特定するUXデザインツール。' },
  { term: 'エンパシーマップ', aliases: ['empathy map'], description: 'ユーザーが「言う・考える・行動する・感じる」の4象限でユーザーの内面を可視化するUXツール。ユーザーへの共感を深め、真のニーズや課題を理解するためのワークショップでよく使われる。' },
  { term: 'タスク分析', aliases: ['task analysis'], description: 'ユーザーが特定の目標を達成するために行う一連の操作・判断・手順を詳細に分析する手法。UIの設計や改善、マニュアル作成、ワークフロー最適化に活用され、ユーザーの実際の行動モデルを構築する。' },
  { term: 'パンくずリスト', aliases: ['breadcrumb', 'パンくずナビ', 'breadcrumb navigation'], description: 'ユーザーが現在サイト内のどの階層にいるかを示すナビゲーション要素。「ホーム > カテゴリ > 製品名」のように現在位置への経路を表示し、上位階層へ素早く戻ることを可能にする。WAI-ARIAではnav要素にaria-label="breadcrumb"を付けることが推奨される。' },
  { term: 'サイトマップ', aliases: ['site map', 'sitemap'], description: 'ウェブサイトのページ構造と階層関係を図式化したもの。情報アーキテクチャの設計・レビューに使用するUX成果物としてのサイトマップと、検索エンジンにサイト構造を通知するXMLサイトマップの2種類がある。' },
  { term: 'インタラクションデザイン', aliases: ['ixd', 'interaction design'], description: 'ユーザーとシステムが対話する方法を設計する分野。ボタンのクリック動作・フォームの入力フロー・アニメーション・マイクロインタラクションなど、製品の振る舞いと応答を定義し、直感的で満足度の高い体験を生み出す。' },
  { term: 'マイクロインタラクション', aliases: ['micro-interaction', 'マイクロアニメーション'], description: 'ボタンを押したときのアニメーション・スワイプの反応・いいねのハートアニメーションなど、単一のタスクを実行する小さなインタラクション。適切に設計されたマイクロインタラクションはフィードバックを伝え、使用感を豊かにしユーザーの満足度を高める。' },
  { term: 'アフォーダンス', aliases: ['affordance'], description: '物や環境がその使い方を示す特性。ドアノブは回す・押すを、ボタンは押すことを、スクロールバーはドラッグを示唆するように、UIデザインにおけるアフォーダンスはユーザーに操作方法を直感的に伝える視覚的・物理的手がかりを指す。' },
  { term: 'シグニファイア', aliases: ['signifier'], description: 'Donald Normanが提唱したアフォーダンスを補完する概念。UIにおいてユーザーに操作方法を明示的に伝えるシグナル（アイコン・ラベル・下線リンクなど）を指す。アフォーダンスが潜在的な使用可能性を示すのに対し、シグニファイアはそれを明示的に伝達する。' },
  { term: 'メンタルモデル', aliases: ['mental model'], description: 'ユーザーがシステムの動作についてどのようなイメージ・期待・理解を持っているかの内的表現。UIデザインではユーザーのメンタルモデルと一致したシステムモデルを作ることで、学習コストを下げ直感的な操作を実現できる。' },
  { term: 'ユーザーリサーチ', aliases: ['user research'], description: '製品設計の意思決定を裏付けるため、実際のユーザーを対象にインタビュー・アンケート・観察・ユーザビリティテストなどを通じてニーズ・行動・痛点を調査する活動。定性調査と定量調査の両手法を状況に応じて選択する。' },
  { term: 'タッチターゲット', aliases: ['touch target', 'タップターゲット'], description: 'タッチスクリーンデバイスでユーザーがタップできる領域のサイズ。WCAGおよびApple・Googleのガイドラインでは最低44×44px（CSS px）以上を推奨しており、小さすぎるターゲットは操作ミスやフラストレーションの原因となる。' },
  { term: 'グリッドシステム', aliases: ['grid system', 'グリッドレイアウト'], description: 'ページを均等な列・行・ガターで分割し、コンテンツの配置を規則化するレイアウト設計の基盤。12カラムグリッドが広く採用され、デザインの一貫性とレスポンシブ対応を効率化する。CSSグリッドやBootstrapグリッドが代表実装。' },
  { term: 'スペーシング', aliases: ['spacing', '余白設計'], description: 'UI要素間の余白・間隔を体系化したデザイントークンの一部。4・8・16・24・32pxなどの倍数スケールを定義し、デザインの視覚的リズムと一貫性を保つ。paddin・marginのサイズはデザインシステムのスペーシングスケールを参照する。' },
  { term: 'タイポグラフィ', aliases: ['typography', 'タイプグラフィ'], description: 'フォントファミリー・ウェイト・サイズ・行間・文字間隔などの文字組みに関する設計の総称。UIにおけるタイポグラフィはコンテンツの可読性・情報階層・ブランド表現に直結し、デザインシステムではタイプスケールとして体系化される。' },
  { term: 'カラーパレット', aliases: ['color palette'], description: 'デザインシステムで定義された使用可能な色の集合。プライマリ・セカンダリ・ニュートラル・セマンティック（エラー赤・成功緑など）の各カラーグループからなり、デザイントークンとして管理される。ブランド一貫性とアクセシビリティを同時に担保する。' },
  { term: 'アニメーション', aliases: ['animation', 'uiアニメーション'], description: 'UI要素が時間軸に沿って変化する視覚的な動き。フォーカス・ローディング・状態遷移・フィードバックなどを伝える手段として機能する。適切なアニメーションはユーザーの認知を助けるが、過剰な動きはprefers-reduced-motionメディアクエリで抑制できる配慮が必要。' },
  { term: 'イージング', aliases: ['easing', 'タイミング関数'], description: 'アニメーションの速度変化パターン。ease-in-outは自然な動き、ease-inは去る動き、ease-outは到着する動きに適し、CSSのtransition-timing-functionで指定する。' },
  { term: '空状態', aliases: ['empty state', 'ゼロ状態', 'エンプティステート'], description: 'データやコンテンツが存在しない場合に表示されるUI状態。初回ユーザーへの案内・フィルタ結果ゼロ件・エラー後のリセットなどで遭遇する。適切な空状態デザインは次のアクションを明示し、ユーザーの迷子感を防ぐ重要なUX要素。' },
  { term: '成功状態', aliases: ['success state', '完了状態'], description: '操作が正常に完了したことをユーザーに伝えるUI状態。フォーム送信完了・ファイルアップロード成功・支払い完了など、ユーザーのアクション達成を確認しポジティブな感情を生む重要なフィードバックポイント。' },
  { term: 'インラインバリデーション', aliases: ['inline validation', 'リアルタイムバリデーション'], description: 'フォームフィールドへの入力中または離脱時（onBlurイベント）に、フォーム送信を待たずに即座にエラーや成功メッセージを表示するバリデーション手法。ユーザーがミスを早期に発見・修正でき、フォーム完了率の向上に貢献する。' },
  { term: 'フォームデザイン', aliases: ['form design', 'フォームux'], description: 'ユーザーがデータを入力するフォームのUXを最適化する設計実践。ラベルの配置・必須項目の明示・入力ヒント・エラーメッセージ・送信フィードバック・フィールド数の最小化などを考慮し、完了率とアクセシビリティを高める。' },
  { term: 'デザインスペック', aliases: ['design spec', 'design specification', 'デザイン仕様'], description: 'デザイナーから開発者へ実装情報を伝えるための仕様書。要素のサイズ・間隔・カラー値・フォント・インタラクション・状態変化などを詳細に記載し、デザインの意図を正確に実装に橋渡しする。FigmaのInspect機能などで自動生成される。' },
  { term: 'コンポーネント設計', aliases: ['component design', 'コンポーネント駆動開発'], description: 'UIをどのような粒度・境界でコンポーネントに分割し、どのようなprops・状態・イベントを持たせるかを定義する設計活動。再利用性・テスト容易性・変更容易性のバランスを取りながら、アプリケーション全体のUI構造を決定する。' },
  { term: 'グリッド', aliases: ['grid', 'cssグリッド'], description: 'UIレイアウトを規則的な格子状に分割する設計ユニット。CSSグリッド（CSS Grid）はgrid-templateやgap指定で柔軟な2次元レイアウトを実現し、デザインシステムのグリッド定義と組み合わせてページ構造の一貫性を保つ。' },
  { term: 'キャプション', aliases: ['caption', '字幕', 'クローズドキャプション'], description: '動画・画像・テーブルなどに付ける説明テキスト。動画の字幕（クローズドキャプション）はWCAGが要求するアクセシビリティ要件で、音声情報を文字で提供することで聴覚障害者のアクセスを保証する。HTMLではcaptionタグやtrack要素で実装する。' },
  { term: 'アクセシビリティ監査', aliases: ['accessibility audit', 'アクセシビリティ評価'], description: 'ウェブサイトやアプリがWCAGなどのアクセシビリティ基準を満たしているかを評価するプロセス。自動ツール（axe・Lighthouse）によるチェックと、支援技術を使った手動テスト・専門家によるコードレビューを組み合わせて実施する。' },
  { term: 'プレースホルダー', aliases: ['placeholder', 'プレースホルダーテキスト'], description: 'フォーム入力フィールドの中に、入力例やヒントを示すために表示される薄い色のテキスト。入力時に消えるため、ラベルの代替として使用するとアクセシビリティ上の問題が生じる。ラベルとは別に補足情報としてのみ使用することがベストプラクティス。' },
  { term: 'ローディング', aliases: ['loading'], description: '非同期処理やデータ取得の待機中にユーザーに進行中であることを伝えるUI状態・パターン。スピナー・プログレスバー・スケルトンスクリーン・ローディングオーバーレイなどの手法があり、知覚速度と体験品質に大きく影響する。' },
  { term: 'プログレッシブウェブアプリ', aliases: ['progressive web app'], description: 'ウェブ技術で構築しながらネイティブアプリに近い体験を提供するウェブアプリケーション。オフライン動作（Service Worker）・ホーム画面への追加（Manifest）・プッシュ通知などの特性を持ち、インストール不要で高い使いやすさを実現する。' },
  { term: 'デザインレビュー', aliases: ['design review'], description: 'デザイン案を関係者（デザイナー・開発者・PM・ステークホルダー）で確認し、ブランド一貫性・ユーザビリティ・技術的実現性・アクセシビリティなどの観点からフィードバックを収集するプロセス。実装前の問題発見コストを最小化する。' },
  { term: 'ユーザビリティテスト', aliases: ['usability test'], description: '実際のユーザーにタスクを実行してもらいながら操作の様子を観察・記録するUXリサーチ手法。課題の発見・インターフェースの問題点の特定に有効で、モデレートあり・なし（リモートアンモデレート）の形式で実施する。' },
  { term: 'インタラクティブプロトタイプ', aliases: ['interactive prototype', '高忠実度プロトタイプ'], description: 'クリックやタップで画面遷移し、実際の操作感を模擬できる高忠実度のプロトタイプ。Figmaのプロトタイプ機能やFramer・ProtoPieなどで作成し、ユーザーテストやステークホルダーへのデモに使用する。コーディング前に体験検証できる。' },
  { term: '知覚速度', aliases: ['perceived performance', 'perceived speed'], description: '実際の処理時間ではなく、ユーザーが体感する速さの感覚。スケルトンスクリーン・オプティミスティックUI・アニメーションなどを使うことで、実際のレスポンスタイムが変わらなくても知覚速度を改善できる。UXにおけるパフォーマンス設計の重要概念。' },
  { term: 'ダブルダイヤモンド', aliases: ['double diamond', 'ダブルダイアモンド'], description: '英国デザインカウンシルが提唱したデザインプロセスモデル。発見→定義（問題発散・収束）→開発→提供（解決策発散・収束）の4フェーズで構成され、正しい問題を定義してから正しい解決策を作るというデザイン思考の流れを表す。' },
  { term: 'デザイン思考', aliases: ['design thinking', 'hcd', 'human-centered design'], description: '人間中心のイノベーションアプローチ。共感→問題定義→アイデア創出→プロトタイピング→テストの5フェーズを反復し、ユーザーの本質的なニーズから出発して創造的な解決策を導く。Stanford d.schoolが普及に大きく貢献した。' },
  { term: 'コンテンツファースト', aliases: ['content first', 'コンテンツ優先'], description: 'デザインの意思決定をレイアウトより前にコンテンツの内容・量・優先順位から出発する設計アプローチ。ダミーテキスト（Loremテキスト）でデザインを作らず、実際のコンテンツで検証することで、コンテンツに適したレイアウトを実現する。' },
  { term: 'モーションデザイン', aliases: ['motion design', 'uiモーション'], description: 'UIにおけるアニメーションと動きを設計する専門分野。要素の登場・退場・状態変化・トランジションを時間軸で設計し、ユーザーの注意誘導・コンテキスト維持・フィードバック伝達の役割を果たす。Lottieなどのツールで複雑なアニメーションを実装する。' },
  { term: 'ゼロUI', aliases: ['ゼロui', 'zero ui', 'no ui'], description: '画面・ボタン・ビジュアルインターフェースを最小化または排除し、音声・ジェスチャー・センサー・AI予測などによって操作するインターフェースパラダイム。スマートスピーカー・ARグラス・ウェアラブルデバイスなどが代表例。' },
  { term: '認知的ウォークスルー', aliases: ['cognitive walkthrough'], description: '専門家がユーザーの立場でタスクを段階的にたどりながら、各ステップで「ユーザーが何をすべきかを知っているか」「操作の結果が期待通りか」を評価するユーザビリティ検査手法。ヒューリスティック評価より具体的なタスクに焦点を当てる。' },
  { term: '支援技術', aliases: ['assistive technology', 'at'], description: '障害のあるユーザーがデジタルコンテンツを使用・操作するのを補助するソフトウェアやハードウェアの総称。スクリーンリーダー・点字ディスプレイ・スイッチアクセス・音声制御・拡大鏡などが含まれる。アクセシブルな設計はこれらの技術が正しく機能することを前提とする。' },
  { term: 'ツールチップ', aliases: ['tooltip'], description: 'UI要素にカーソルをホバーまたはフォーカスしたときに表示される小さな説明テキスト。アイコンや省略ラベルの意味を補足するが、タッチデバイスではホバーが存在しないため、重要な情報はツールチップに頼らない設計が必要。アクセシビリティのためにaria-describedbyとの組み合わせを推奨する。' },
  { term: 'トースト通知', aliases: ['toast', 'toast notification', 'スナックバー'], description: '画面の隅に一時的に表示され、操作の結果（成功・エラー・情報）を短時間で伝えるUI通知パターン。非侵入的で自動消去されるが、重要な情報を含む場合は手動で閉じられる手段も提供する。アクセシビリティのためにaria-live="polite"での通知が推奨される。' },
  { term: 'ドロップダウン', aliases: ['dropdown', 'ドロップダウンメニュー'], description: 'クリックまたはキーボード操作でリストを開き、選択肢を選ぶUIコンポーネント。セレクトボックス（ネイティブHTML）とカスタムドロップダウン（JS実装）があり、後者はWAI-ARIAのlistbox/comboboxパターンで完全なキーボード操作とスクリーンリーダー対応を実装する必要がある。' },
  { term: 'アコーディオン', aliases: ['accordion', 'ディスクロージャーウィジェット'], description: 'クリックで展開・折りたたみができるコンテンツパネルのUIコンポーネント。限られたスペースに多くの情報を収める際に使用する。アクセシビリティのためにaria-expanded・aria-controls・ボタン要素による実装が必要で、WAI-ARIAのDisclosureパターンが参照される。' },
  { term: 'タブUI', aliases: ['タブui', 'tab', 'tabs', 'タブコンポーネント'], description: '関連コンテンツパネルをタブで切り替えるUIコンポーネント。WAI-ARIAのTablistパターンでrole="tablist"・role="tab"・role="tabpanel"と矢印キーナビゲーションを実装する。' },
  { term: 'ブレッドファーストデザイン', aliases: ['content-first design', 'real content design'], description: 'コンテンツをワイヤーフレームの段階から実際のテキスト・画像で埋めてデザインを進めるアプローチ。Lorem Ipsumのようなダミーコンテンツを使わず、実コンテンツに沿ったレイアウトを設計することで、現実に即したデザイン判断ができる。コンテンツファーストとも密接に関連する。' },
  { term: 'UIインベントリ', aliases: ['uiインベントリ', 'ui inventory', 'uiオーディット', 'ui audit'], description: '既存のUIを全画面・全コンポーネントにわたってキャプチャし、類似要素の重複・不一致・矛盾を可視化する監査手法。デザインシステムの構築や既存UIの統一化プロジェクトの出発点として、改善すべき対象とその規模を把握するために使う。' },
  { term: 'レスポンシブタイポグラフィ', aliases: ['responsive typography'], description: '画面サイズやビューポート幅に応じてフォントサイズ・行間・文字間隔を動的に調整するタイポグラフィ設計。CSSのclamp()関数やfluidタイポグラフィスケールを使い、小さな画面でも大きな画面でも最適な可読性を保つ。' },
  { term: 'カラーモード', aliases: ['color mode', 'ダークモード', 'dark mode', 'カラーテーマ'], description: 'ライトモードとダークモードのように、アプリケーションが提供する配色テーマの切り替え機能。CSSのprefers-color-schemeメディアクエリでOSの設定を検出し自動適用できる。デザインシステムではカラーモードに対応したセマンティックカラートークンを使って実装する。' },
  { term: 'Figmaバリアブル', aliases: ['figmaバリアブル', 'figma variables', 'figmaバリアブルズ'], description: 'Figma上でデザイントークンを直接定義・管理できる機能。色・数値・文字列・ブール値の変数を作成し、コレクション（ライトモード／ダークモード、ブランド切り替えなど）として管理できる。コードのCSS変数と一対一でマッピングしやすく、デザインと実装の乖離を減らす。' },
  { term: 'ユーザーフロー', aliases: ['user flow', 'タスクフロー', '画面フロー'], description: 'ユーザーが特定の目標を達成するためにアプリ内を移動する画面遷移の経路図。エントリーポイント・分岐・終端を示し、UXデザイナーが設計の整合性を確認したり、ステークホルダーと体験を共有したりするために作成する。タスクフロー・画面フローとも呼ばれる。' },
  { term: 'コンテンツガイドライン', aliases: ['content guidelines', 'uxライティングガイドライン', 'voice & tone'], description: 'UIで使用するテキスト（ラベル・ボタン名・エラーメッセージ・ヘルプテキストなど）の文体・トーン・語彙・長さを規定するドキュメント。デザインシステムのUXライティング仕様として、プロダクト全体での言葉の一貫性とユーザビリティを保証する。' },
  { term: 'セマンティックカラー', aliases: ['semantic color', 'セマンティックカラートークン'], description: 'primary・secondary・success・warning・errorなど、色の具体的な値ではなく用途・意味で命名したカラートークン。実際の色値をプリミティブトークンとして別管理し、セマンティックトークンが参照する構造で、テーマ切り替えやブランド変更を柔軟に行える。' },
  { term: 'インクルーシブデザイン', aliases: ['inclusive design', 'ユニバーサルデザイン'], description: '年齢・障害・言語・文化・リテラシーなど多様な人々が排除されないよう、最初から幅広いユーザーを念頭に置いて設計するアプローチ。アクセシビリティを含む広い概念で、特定のユーザー向けに設計した解決策が他のユーザーにも恩恵をもたらすことが多い（コンセプト：エクスクルージョン）。' },
  { term: 'エクスペリエンスマップ', aliases: ['experience map'], description: 'ユーザーが特定の体験全体（特定の製品に限らない）を通じて感じる行動・感情・思考を可視化した図。ユーザージャーニーマップより広い視野でユーザーの体験世界を捉え、新製品機会の発見や既存サービスのギャップ特定に活用する。' },
  { term: 'UXライティング', aliases: ['uxライティング', 'ux writing', 'microcopy'], description: 'ユーザーインターフェース上のテキスト（ボタンラベル・エラーメッセージ・オンボーディングコピーなど）を、ユーザーが迷わず目標を達成できるよう設計する専門分野。明確さ・簡潔さ・ブランドボイスの一貫性を追求し、コンバージョン率やユーザー満足度に直結する。' },
  { term: 'サービスデザイン', aliases: ['service design'], description: 'ユーザーと組織の双方の視点からサービス全体の体験を設計する分野。サービスブループリント・カスタマージャーニー・ステークホルダーマップなどのツールを使い、フロントステージ（顧客接点）とバックステージ（組織内プロセス）を統合的に設計する。' },
  { term: 'プロトタイプ忠実度', aliases: ['prototype fidelity', 'lofi', 'hifi', '低忠実度', '高忠実度'], description: 'プロトタイプが最終製品をどれだけ詳細に再現しているかの度合い。低忠実度（LoFi）は紙・スケッチ・ワイヤーフレームで構造を素早く検証し、高忠実度（HiFi）はFigmaプロトタイプや動作コードで詳細なインタラクションを検証する。目的に応じて使い分けが重要。' },
  { term: 'コンバージョン率最適化', aliases: ['cro', 'conversion rate optimization'], description: 'ウェブサイトやアプリにおいて、訪問者が購入・登録・問い合わせなどの目標行動（コンバージョン）を達成する割合を高めるための改善活動。A/Bテスト・ヒートマップ・ユーザビリティテストなどのデータを組み合わせ、UIとUXを継続的に改善する。' },
  { term: 'ヒートマップ', aliases: ['heatmap', 'クリックマップ'], description: 'ウェブページ上でユーザーがクリック・タップ・スクロール・視線を向けた場所を色の濃淡で可視化した分析ツール。Hotjar・Microsoft Clarityなどで取得でき、ユーザーの実際の行動パターンを把握しUX改善の仮説構築に活用する。' },
  { term: 'セッション録画', aliases: ['session recording', 'session replay'], description: '実際のユーザーのブラウジングセッションを匿名化して録画し、どのように操作しているかを再生して確認できる分析手法。Hotjar・FullStory・Microsoft Clarityなどのツールで収集し、バグの再現・UX問題の発見・定性的なユーザー行動理解に活用する。' },
  { term: 'アイトラッキング', aliases: ['eye tracking', '視線追跡'], description: 'ユーザーが画面のどこを見ているかを計測する視線追跡技術。専用ハードウェアまたはカメラでガゼ（視線固定点）とサッカード（視線移動）を記録し、UIのどの要素が注目されているかを可視化する。デザインの視覚的階層の検証やUIの改善に使われる。' },
  { term: 'サービスブループリント', aliases: ['service blueprint'], description: 'サービスの提供プロセスを顧客視点のフロントステージと組織内のバックステージに分けて可視化する図。サービスデザインの主要ツールで、顧客接点・従業員の行動・支援プロセス・IT基盤を一枚の図に整理し、ボトルネックや改善機会を特定する。' },
  { term: 'Keep-Aliveヘッダー', aliases: ['keep-aliveヘッダー', 'keep-alive header', 'keep-alive'], description: 'HTTPの持続的接続を制御するヘッダーです。同一TCP接続上で複数のHTTPリクエストを処理できるようにし、接続のオーバーヘッドを削減します。' },
  { term: 'SwiftUI', aliases: ['swiftui'], description: 'Appleが提供する宣言的UIフレームワーク。Swiftで記述しiOS、macOS、watchOS、tvOSに対応したUIを単一コードベースで構築できる。リアクティブなデータバインディングを標準サポートする。' },
  { term: 'Jetpack Compose', aliases: ['jetpack compose'], description: 'GoogleのAndroid向け宣言的UIフレームワーク。KotlinのDSLでUIを記述し従来のXMLレイアウトを置き換える。状態駆動のリコンポジションモデルを採用し宣言的にUIを構築できる。' },
  { term: 'Xcode', aliases: ['xcode'], description: 'AppleのiOS・macOSアプリ開発用統合開発環境。シミュレータ、パフォーマンス計測ツール（Instruments）、コード署名、App Store Connect連携を提供する公式IDEで開発に必須。' },
  { term: 'Android Studio', aliases: ['android studio'], description: 'GoogleのAndroidアプリ公式IDE。IntelliJ IDEAベースでコードエディタ、エミュレータ、Gradle統合、プロファイラ、Layout Inspectorなどの開発・デバッグツールを統合提供する。' },
  { term: 'App Store', aliases: ['app store'], description: 'AppleのiOS・macOSアプリ配信プラットフォーム。アプリはAppleの審査プロセスを経て公開され、In-App Purchase・サブスクリプション・TestFlightによるベータ配信を管理できる。' },
  { term: 'Google Play', aliases: ['google play', 'google play store'], description: 'GoogleのAndroidアプリ配信プラットフォーム。アプリのアップロード・審査・公開、クラッシュ分析、A/Bテスト、段階的ロールアウトをPlay Consoleで一元管理できる。' },
  { term: 'APNs', aliases: ['apns', 'apple push notification service'], description: 'Appleが運営するiOSデバイスへのプッシュ通知配信インフラ。サーバーからAPNsにHTTP/2でリクエストを送ると、Appleのサーバーがデバイストークンに基づき対象デバイスに通知を届ける。' },
  { term: 'FCM', aliases: ['fcm', 'firebase cloud messaging'], description: 'GoogleのクロスプラットフォームメッセージングサービスでAndroid・iOS・Webにプッシュ通知やデータメッセージを送信できる。旧GCMの後継でFirebaseエコシステムの主要コンポーネント。' },
  { term: 'Universal Links', aliases: ['universal links'], description: 'iOSのディープリンク機能でウェブURLをネイティブアプリの特定画面に直接遷移させる仕組み。サーバーにapple-app-site-associationファイルを配置してドメインとアプリを紐付ける公式推奨方式。' },
  { term: 'App Links', aliases: ['app links'], description: 'AndroidのディープリンクでウェブURLをネイティブアプリの特定画面に遷移させる公式の仕組み。サーバーにassetlinks.jsonを配置しDigital Asset Linksでドメイン所有を証明して機能させる。' },
];
