// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: frontend (2/5)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: '画面ID', aliases: ['画面id', 'スクリーンid', 'scr'], description: '各画面に付与される一意の識別子。「SCR-001」などの形式でプロジェクト内の画面を識別する。設計書、仕様書、テストケースで画面を参照するときに使う。' },
  { term: '連携仕様書', aliases: ['if仕様書', '外部連携仕様書'], description: 'システム間のデータ連携を詳細に記述したドキュメント。連携の方向、データフォーマット、エラー処理、タイムアウト設定などを記載する。' },
  { term: 'モーダル', aliases: ['modal', 'モーダルダイアログ', 'ダイアログ'], description: '現在の画面の上に重ねて表示されるポップアップウィンドウ。確認ダイアログ、フォーム入力など。操作するまでは元の画面に戻れない。' },
  { term: 'レスポンシブデザイン', aliases: ['responsive design', 'レスポンシブ', 'スマホ対応'], description: 'PC、タブレット、スマートフォンなど画面サイズの違いに応じて自動的にレイアウトを切り替えるWebデザイン手法。一つのHTMLで複数のデバイスに対応できる。' },
  { term: 'アクセシビリティ', aliases: ['accessibility', 'a11y', 'アクセシ'], description: '障害のある人を含むすべての人がWebサイトやシステムを利用できるようにすること。音声読み上げ対応、色覚配慮、キーボード操作対応などが含まれる。a11yとも書く。' },
  { term: 'ユーザビリティ', aliases: ['usability'], description: 'システムやWebサイトがどれだけ使いやすいかの度合い。直感的な操作、わかりやすいメニュー構成、エラーメッセージの明確さなどが評価される。UXの一部。' },
  { term: 'HTML5', aliases: ['html5', 'html 5', 'html living standard'], description: 'HTMLの第5版仕様。セマンティック要素、マルチメディア対応、Canvas・SVG・Web Storageなどの新APIを標準化し、プラグインなしでリッチなWebアプリを構築できる基盤を整えた。' },
  { term: 'セマンティックマークアップ', aliases: ['semantic markup'], description: 'HTMLタグが持つ意味（セマンティクス）に従って文書構造を記述する手法。header・main・article・sectionなどの要素を適切に使うことでアクセシビリティとSEOを向上させる。' },
  { term: 'Web Components', aliases: ['web components', 'ウェブコンポーネント'], description: 'Custom Elements・Shadow DOM・HTMLテンプレートを組み合わせて再利用可能なカスタムUI要素をネイティブブラウザ機能で実装する標準仕様の総称。フレームワーク非依存で動作する。' },
  { term: 'Shadow DOM', aliases: ['shadow dom', 'シャドウdom', 'shadow root'], description: 'DOM要素に付属するカプセル化されたサブツリー。スタイルとマークアップを外部のCSSやJavaScriptから隔離し、Web Componentsの実装で内部実装を隠蔽するために使用する。' },
  { term: 'SVG', aliases: ['svg', 'scalable vector graphics', 'スケーラブルベクターグラフィックス'], description: 'Scalable Vector Graphicsの略。XMLベースのベクター画像フォーマットで、解像度に依存せず拡大縮小できる。HTMLに埋め込んでCSSやJavaScriptで操作でき、アイコンやチャートに利用される。' },
  { term: 'Custom Elements', aliases: ['custom elements', 'カスタム要素', 'custom element registry'], description: 'Web Components仕様の一部で、独自のHTMLタグを定義し登録する機能。`customElements.define()`でクラスをタグ名に紐付け、ブラウザネイティブのコンポーネントとして動作させる。' },
  { term: 'dialog要素', aliases: ['<dialog>', 'htmldialogelement'], description: 'HTMLネイティブのモーダルおよびノンモーダルダイアログを表す要素。`showModal()`でモーダル表示・フォーカストラップを実現し、`::backdrop`疑似要素で背景のスタイリングも可能。' },
  { term: 'details要素', aliases: ['<details>', '詳細要素'], description: '開閉可能なディスクロージャーウィジェットを実装するHTML要素。`<summary>`子要素がクリックラベルになり、JavaScriptなしでアコーディオンUIを実現できる。`open`属性で初期展開状態を設定する。' },
  { term: 'summary要素', aliases: ['<summary>'], description: '`<details>`要素の見出し・トグルボタンとして機能するHTML要素。クリックで詳細コンテンツの表示・非表示を切り替える。`details`の最初の子要素として配置する必要がある。' },
  { term: 'picture要素', aliases: ['<picture>', 'ピクチャー要素'], description: 'ブラウザが最適な画像ソースを選択できるようにする`<img>`のラッパーHTML要素。`<source>`子要素でメディアクエリやフォーマット(WebP/AVIFなど)ごとに代替画像を指定し、レスポンシブ画像を実現する。' },
  { term: 'source要素', aliases: ['<source>'], description: '`<picture>`・`<video>`・`<audio>`要素内で複数のメディアリソースを指定するHTML要素。ブラウザはサポートするフォーマットや条件に合う最初の`<source>`を選択する。' },
  { term: 'meta viewport', aliases: ['viewport meta tag', 'ビューポートメタタグ'], description: '`<meta name="viewport">`タグでブラウザのビューポートの幅やスケールを制御する設定。`width=device-width, initial-scale=1`を指定することでレスポンシブデザインの前提となるピクセル比を合わせる。' },
  { term: 'Content Security Policy', aliases: ['content security policy', 'コンテンツセキュリティポリシー'], description: 'Webページが読み込むリソースのソースを制限するブラウザのセキュリティ機構。HTTPヘッダーまたはmeta要素で設定し、XSS攻撃やデータインジェクションのリスクを低減する。' },
  { term: 'iframe sandboxing', aliases: ['iframe sandbox', 'サンドボックス'], description: '`<iframe>`の`sandbox`属性を使って埋め込みコンテンツの権限を制限するセキュリティ機能。スクリプト実行・フォーム送信・ポップアップなどを個別に許可または禁止できる。' },
  { term: 'template要素', aliases: ['<template>', 'htmltemplateelement'], description: 'DOMに挿入されず描画もされないHTMLのコンテンツを宣言的に定義するHTML要素。`content`プロパティから取得したDocumentFragmentをクローンして動的にDOMへ挿入する。Web Componentsで多用される。' },
  { term: 'slot要素', aliases: ['<slot>', 'スロット'], description: 'Shadow DOM内でホスト要素から渡されたコンテンツを受け取るプレースホルダーHTML要素。名前付きスロット（`name`属性）と匿名スロットがあり、Web Componentsのコンテンツ挿入ポイントとして機能する。' },
  { term: 'Server-Sent Events', aliases: ['server-sent events', 'サーバー送信イベント'], description: 'HTTPを使ってサーバーからクライアントへ一方向のリアルタイムイベントストリームを送るWeb標準技術。WebSocketより軽量でHTTPキャッシュや再接続が自動化されており、通知・ログ配信に適する。' },
  { term: 'WebRTC', aliases: ['webrtc', 'web real-time communication', 'ウェブrtc'], description: 'ブラウザ間でプラグインなしにリアルタイムの音声・映像・データ通信を実現するWeb標準技術。P2PのピアコネクションとNAT越えのためのICE/STUNプロトコルを使用する。' },
  { term: 'contenteditable', aliases: ['contenteditable属性', 'content editable'], description: 'HTML要素をブラウザネイティブの編集可能コンテンツ領域にする属性。`contenteditable="true"`を設定するとキーボード入力・ペーストが可能になり、WYSIWYGエディタの土台として利用される。' },
  { term: 'Web App Manifest', aliases: ['web app manifest', 'webアプリマニフェスト', 'manifest.json'], description: 'PWAのメタデータ（名前・アイコン・テーマカラー・起動URLなど）を記述するJSONファイル。ブラウザがこれを読みホーム画面への追加やスタンドアロン表示の設定に利用する。' },
  { term: 'DOM', aliases: ['dom', 'document object model', 'ドキュメントオブジェクトモデル'], description: 'Document Object Modelの略。HTMLやXMLドキュメントをツリー状のオブジェクト構造で表現するブラウザのプログラミングインターフェース。JavaScriptからノードを取得・変更・追加・削除して動的なWebページを実現する。' },
  { term: 'クリティカルレンダリングパス', aliases: ['critical rendering path', 'crp'], description: 'ブラウザがHTMLを受信してから画面に表示するまでの一連の処理フロー。HTML解析・DOM構築・CSSOM構築・レンダリングツリー生成・レイアウト・ペイントの各ステップで構成され、最適化がページ表示速度に直結する。' },
  { term: 'Reflow', aliases: ['reflow', 'リフロー'], description: 'DOM要素のサイズや位置を再計算するブラウザのレイアウト処理。要素のサイズ変更・DOM挿入・ウィンドウリサイズなどがトリガーになる。Reflowは高コストなためバッチ化や読み取りの一括化でパフォーマンスを改善する。' },
  { term: 'Compositing', aliases: ['compositing', 'コンポジティング', 'layer compositing'], description: 'ブラウザがレイヤーを合成して最終的な画面表示を生成するレンダリングフェーズ。`transform`や`opacity`によるアニメーションはメインスレッドを使わずGPUでコンポジットされるためパフォーマンスが高い。' },
  { term: 'Cross-Origin Isolation', aliases: ['cross-origin isolation', 'クロスオリジン分離', 'coop/coep'], description: 'SharedArrayBufferなどの強力なAPIを有効にするためにオリジンを分離するセキュリティモデル。`Cross-Origin-Opener-Policy`と`Cross-Origin-Embedder-Policy`ヘッダーを設定して適用する。' },
  { term: 'Same-Origin Policy', aliases: ['same-origin policy', '同一オリジンポリシー'], description: 'スクリプトが読み込まれたオリジン以外のリソースへのアクセスをブラウザが制限するセキュリティポリシー。プロトコル・ホスト・ポートがすべて一致する場合のみ同一オリジンとみなされる。' },
  { term: 'Resource Hints', aliases: ['resource hints', 'リソースヒント'], description: 'ブラウザにリソース取得のタイミングや優先度を事前に伝えるHTMLの仕組みの総称。preload・prefetch・preconnect・dns-prefetchなどがあり、ページパフォーマンスを改善するための宣言的な最適化手段。' },
  { term: 'Web Vitals', aliases: ['web vitals', 'ウェブバイタル'], description: 'GoogleがWebページのユーザー体験を定量化するために定めた指標群。LCP（最大コンテンツの描画）・INP（次のペイントへの応答性）・CLS（累積レイアウトシフト）がCore Web Vitalsとして検索ランキングにも影響する。' },
  { term: 'HTTP/2', aliases: ['http/2', 'http 2.0', 'h2'], description: 'HTTP/1.1の後継プロトコル。多重化・ヘッダー圧縮（HPACK）・サーバープッシュ・優先度制御により、単一TCP接続で複数リクエストを並列処理してWebページの読み込みを高速化する。' },
  { term: 'HTTP/3', aliases: ['http/3', 'http 3.0', 'h3'], description: 'QUICプロトコル（UDP上に実装されたTLS暗号化コネクション）をベースにしたHTTPの最新版。TCP HoLブロッキングを解消し、不安定なモバイルネットワークでも高速な通信を実現する。' },
  { term: 'OpenGraph', aliases: ['opengraph', 'open graph protocol', 'ogp'], description: 'WebページのメタデータをSNSシェア時に正しく表示するためのプロトコル。`<meta property="og:title">`などのタグでタイトル・説明・画像を定義し、TwitterカードやLINEプレビューなどに利用される。' },
  { term: 'WAI-ARIA', aliases: ['wai-aria', 'accessible rich internet applications'], description: 'W3Cが策定したスクリーンリーダーなどの支援技術向けにDOMのセマンティクスを補足するHTML属性仕様。`role`・`aria-label`・`aria-expanded`などでHTMLが意味を伝えられない場合にアクセシビリティを向上させる。' },
  { term: 'クロージャ', aliases: ['closure'], description: '関数がその定義時のレキシカルスコープを記憶し、スコープ外から呼び出された後もそのスコープ内の変数にアクセスできる仕組み。データのカプセル化やコールバック、モジュールパターンに広く使われる。' },
  { term: 'プロトタイプチェーン', aliases: ['prototype chain'], description: 'JavaScriptオブジェクトが持つ__proto__リンクを辿って親オブジェクトのプロパティやメソッドを継承する仕組み。プロパティ参照時にチェーンをObject.prototypeまで遡って検索する。' },
  { term: 'イベントループ', aliases: ['event loop'], description: 'JavaScriptのシングルスレッド非同期処理を実現する仕組み。コールスタックが空になったときにキューからコールバックを取り出して実行するループ処理で、ブラウザやNode.jsの非同期モデルの根幹をなす。' },
  { term: 'コールスタック', aliases: ['call stack'], description: '関数呼び出しの順序を追跡するLIFO構造のスタック。関数が呼ばれるとフレームが積まれ、返ると取り出される。スタックオーバーフローは再帰が深くなりすぎたときに発生する。' },
  { term: 'マイクロタスク', aliases: ['microtask'], description: 'イベントループにおいてマクロタスク完了後、次のマクロタスク実行前に優先的に処理されるタスク。Promise解決コールバックやqueueMicrotask、MutationObserverが該当し、UIレンダリングより先に実行される。' },
  { term: 'マクロタスク', aliases: ['macrotask', 'task'], description: 'イベントループの通常タスクキューに積まれる処理単位。setTimeout、setInterval、I/Oコールバックなどが該当し、マイクロタスクキューが空になった後に1件ずつ実行される。' },
  { term: 'ホイスティング', aliases: ['hoisting'], description: 'JavaScriptで変数宣言・関数宣言がスコープの先頭に巻き上げられる動作。varはundefinedで初期化されて巻き上げられるが、let/constは宣言のみ巻き上げられ初期化前にアクセスするとTDZエラーとなる。' },
  { term: 'テンポラルデッドゾーン', aliases: ['temporal dead zone', 'tdz'], description: 'let/constで宣言された変数がスコープの先頭から宣言文に達するまでの期間。この期間中に変数を参照するとReferenceErrorが発生する。ホイスティングは起きているが初期化されていない状態。' },
  { term: 'WeakRef', aliases: ['weakref', 'weakreference'], description: 'ガベージコレクタによるオブジェクト回収を妨げない弱い参照を保持するES2021の組み込みクラス。参照先オブジェクトがGCされると.deref()がundefinedを返す。キャッシュ実装に利用される。' },
  { term: 'FinalizationRegistry', aliases: ['finalizationregistry', 'finalization registry'], description: 'ガベージコレクトされたオブジェクトのクリーンアップコールバックを登録できるES2021のクラス。WeakRefと組み合わせてリソース解放処理を自動化するが、実行タイミングは保証されない。' },
  { term: 'Reflect', aliases: ['reflect', 'reflect api'], description: '言語組み込みの操作（プロパティアクセス、関数呼び出しなど）をメソッドとして提供するES2015の静的オブジェクト。Proxyハンドラ内でデフォルト動作を呼び出す際に使われることが多い。' },
  { term: 'Symbol', aliases: ['symbol', 'javascript symbol'], description: 'ES2015で導入されたプリミティブ型。毎回一意の値を生成し、オブジェクトの非公開プロパティキーや既知のシンボル（Symbol.iteratorなど）を通じて言語の組み込み動作をカスタマイズできる。' },
  { term: 'イテレータプロトコル', aliases: ['iterator protocol'], description: 'nextメソッドを持ち、呼び出すたびに{value, done}オブジェクトを返すオブジェクトを定義するJavaScriptのプロトコル。for...ofやスプレッド構文はこのプロトコルを利用して反復処理を行う。' },
  { term: 'ジェネレータ', aliases: ['generator', 'generator function'], description: 'function*構文で定義され、yieldで実行を一時停止・再開できる特殊な関数。呼び出すとイテレータを返し、遅延評価や無限シーケンス、非同期フロー制御（co等）に利用される。' },
  { term: '非同期イテレータ', aliases: ['async iterator', 'async generator'], description: 'Symbol.asyncIteratorを実装し、nextメソッドがPromiseを返すオブジェクト。for await...of構文で非同期なデータストリーム（ファイル読み取り、WebSocketなど）を順次処理できる。' },
  { term: 'オプショナルチェイニング', aliases: ['optional chaining'], description: '?.演算子を使い、チェーン中の値がnullまたはundefinedの場合にエラーを投げずundefinedを返す構文。ネストしたオブジェクトへの安全なアクセスを簡潔に記述できるES2020の機能。' },
  { term: 'Null合体演算子', aliases: ['null合体演算子', 'nullish coalescing operator'], description: '??演算子で、左辺がnullまたはundefinedの場合のみ右辺を返す演算子。||演算子と異なり0や空文字列などfalsyな値は通過させるため、デフォルト値の設定に適している。' },
  { term: '論理代入演算子', aliases: ['logical assignment operators'], description: '&&=、||=、??=の3つの演算子で、論理演算と代入を組み合わせたES2021の機能。例えばa ??= bはaがnullish場合のみbを代入する。条件付き初期化を簡潔に書ける。' },
  { term: '分割代入', aliases: ['destructuring assignment'], description: '配列やオブジェクトの値を個別の変数に一度に割り当てるES2015の構文。デフォルト値の設定、リネーム、ネストしたパターンなどに対応し、関数の引数や戻り値の展開に広く使われる。' },
  { term: 'スプレッド構文', aliases: ['spread syntax'], description: '...演算子を使い、配列・オブジェクト・反復可能オブジェクトを個々の要素に展開する構文。配列の結合、オブジェクトのシャローコピー・マージ、関数への可変引数渡しに利用される。' },
  { term: 'レスト構文', aliases: ['rest syntax', 'rest parameters'], description: '...演算子を関数パラメータや分割代入の末尾に使い、残りの要素を配列としてまとめる構文。引数の数が不定な関数の実装や、オブジェクトから一部プロパティを除いた残りを収集する際に使う。' },
  { term: 'タグ付きテンプレートリテラル', aliases: ['tagged template literal'], description: 'テンプレートリテラルの前に関数名（タグ）を付けることで、文字列部分と式を個別の引数として受け取り加工できる高度な構文。GraphQLクエリ構築（gql`...`）やCSSテンプレート（css`...`）に活用される。' },
  { term: '動的インポート', aliases: ['dynamic import'], description: 'import()関数を使い実行時に非同期でモジュールを読み込む機能。静的importと異なり条件分岐やユーザー操作に応じた遅延ローディングが可能で、バンドルサイズのコード分割に広く活用される。' },
  { term: 'トップレベルawait', aliases: ['top-level await'], description: 'ESモジュールのトップレベルでasync関数なしにawaitを使える機能。モジュールの初期化処理で非同期API呼び出しや動的インポートを直接awaitでき、初期化ロジックを簡潔に記述できる。' },
  { term: 'プライベートクラスフィールド', aliases: ['private class fields'], description: '#プレフィックスで宣言するクラスのプライベートプロパティ。クラス外部からのアクセスを言語レベルで禁止し、真のカプセル化を実現するES2022の機能。プライベートメソッドやstatic privateにも対応する。' },
  { term: '静的初期化ブロック', aliases: ['static initialization block'], description: 'クラス定義内にstatic { }ブロックを書き、クラスが評価される際に一度だけ実行される初期化コードを記述できるES2022の機能。複数のstaticフィールドの初期化ロジックや例外処理をまとめて書ける。' },
  { term: '正規表現名前付きグループ', aliases: ['named capture groups'], description: '正規表現で(?<name>...)の形式を使い、キャプチャグループに名前を付ける機能。マッチ結果のgroups.nameで取得でき、インデックスに依存しない可読性の高いパターン解析ができる。' },
  { term: 'Array.from', aliases: ['array.from', 'array from'], description: '反復可能オブジェクトや配列様オブジェクト（NodeListなど）を新しい配列に変換する静的メソッド。第2引数にマップ関数を受け付けるため、Array.from({length: n}, (_, i) => i)で連番生成にも使われる。' },
  { term: 'Array.at', aliases: ['array.at', 'array at method'], description: '配列の指定インデックスの要素を返すメソッドで、負のインデックスで末尾から数えた要素を取得できる。arr[arr.length - 1]の代わりにarr.at(-1)と書けてコードが簡潔になる。' },
  { term: 'Object.groupBy', aliases: ['object.groupby', 'array.prototype.groupby'], description: 'コールバック関数の戻り値をキーとして配列要素をグループ化するES2024の静的メソッド。ループとreduce/pushの組み合わせを不要にし、データのグルーピングを宣言的に記述できる。' },
  { term: 'WeakMap', aliases: ['weakmap', 'javascript weakmap'], description: 'キーがオブジェクトのみ使えるマップ構造で、キーへの参照が弱参照であるためGCを妨げない。プライベートデータの関連付けやメモ化など、オブジェクトへのメタデータ付与に使われる。' },
  { term: 'WeakSet', aliases: ['weakset', 'javascript weakset'], description: 'オブジェクトのみを要素として保持するセット構造で、要素への参照が弱参照のためGCを妨げない。オブジェクトが訪問済みかどうかのフラグ管理など、オブジェクトのタグ付けに利用される。' },
  { term: 'Promise.allSettled', aliases: ['promise.allsettled', 'allsettled'], description: '渡した全Promiseが解決または拒否された後に、各Promiseの結果（fulfilled/rejected）を配列で返すメソッド。Promise.allと異なり途中でrejectされても残りを待ち全結果を収集するES2020の機能。' },
  { term: 'Promise.any', aliases: ['promise.any', 'promise any'], description: '渡した複数のPromiseのうち最初にresolvedになったものの値を返すES2021のメソッド。全てrejectされた場合はAggregateErrorを投げる。Promise.raceと異なりrejectedは無視する。' },
  { term: 'Promise.race', aliases: ['promise.race', 'promise race'], description: '渡した複数のPromiseのうち最初に確定した（resolve・reject問わず）ものの結果を返すメソッド。タイムアウト処理の実装（タイムアウトPromiseとの競争）などに利用される。' },
  { term: 'Intl API', aliases: ['intl api', 'internationalization api', 'ecmascript internationalization api'], description: '日付・数値・リスト・相対時刻などのロケール対応フォーマットを提供するJavaScriptの組み込み名前空間。Intl.DateTimeFormat、Intl.NumberFormat、Intl.RelativeTimeFormatなどのクラスを含む。' },
  { term: 'Temporal API', aliases: ['temporal api', 'tc39 temporal'], description: 'DateオブジェクトのAPIの欠陥を解消するために設計されたTC39プロポーザル（Stage 3）。タイムゾーン対応のZonedDateTime、PlainDate、PlainTimeなどの型を提供し、日付演算・比較・フォーマットを直感的に行える。' },
  { term: '即時実行関数式', aliases: ['iife', 'immediately invoked function expression'], description: '定義と同時に呼び出される関数式のパターン。(function(){})()の形式でスコープを作り変数汚染を防ぐ。ES2015以降はブロックスコープのletやconstでも同様の目的を達成できるが依然として利用される。' },
  { term: 'アロー関数', aliases: ['arrow function'], description: '=>構文で定義する関数の省略記法。自身のthisを持たず定義時の外側のthisをレキシカルに参照する。引数が1つなら括弧を、本体が1式なら波括弧とreturnを省略できる。' },
  { term: 'this束縛', aliases: ['this binding'], description: 'JavaScriptでthisが何を指すかを決定するルール。呼び出し方法（メソッド呼び出し・関数呼び出し・コンストラクタ・apply/call/bind・アロー関数）によって異なる値に束縛される。' },
  { term: 'bind/call/apply', aliases: ['function.prototype.bind', 'function.prototype.call', 'function.prototype.apply'], description: '関数のthisと引数を明示的に指定するメソッド。callは引数をカンマ区切りで渡し即時実行、applyは引数を配列で渡し即時実行、bindはthisを固定した新しい関数を返す。' },
  { term: 'プロトタイプ継承', aliases: ['prototypal inheritance'], description: 'JavaScriptがクラスベースではなくプロトタイプチェーンを通じてオブジェクトからオブジェクトへ振る舞いを委譲する仕組み。Object.create()でプロトタイプを指定した新しいオブジェクトを生成できる。' },
  { term: 'クラス構文', aliases: ['class syntax'], description: 'ES2015で導入されたclassキーワードによるオブジェクト指向プログラミングの記述形式。内部的にはプロトタイプ継承のシンタックスシュガーだが、constructor・extends・super・static・#private等の機能を提供する。' },
  { term: 'getter/setter', aliases: ['accessor properties', 'get/set'], description: 'オブジェクトのプロパティアクセス時に自動的に呼び出される関数をgetとsetキーワードで定義する機能。バリデーション、計算プロパティ、変更検知などを実装でき、クラスやオブジェクトリテラルで使える。' },
  { term: 'computed property', aliases: ['computed property names', '計算プロパティ'], description: 'オブジェクトリテラルやクラス定義で[expression]の形式を使い、動的に決まる値をプロパティキーとして使う機能。変数やSymbolをキーとするオブジェクトの生成を簡潔に記述できる。' },
  { term: 'レキシカルスコープ', aliases: ['lexical scope', 'static scope'], description: '関数がどこで定義されたかによってスコープが決まる規則。JavaScriptはレキシカルスコープを採用しており、関数を別の場所で呼び出しても定義時のスコープの変数を参照する。クロージャの基礎となる概念。' },
  { term: 'スコープチェーン', aliases: ['scope chain'], description: '変数を参照する際に現在のスコープから外側のスコープへ順に探索する仕組み。グローバルスコープに達するまでチェーンを辿る。レキシカルスコープとクロージャの動作を支える基盤。' },
  { term: 'Promise連鎖', aliases: ['promise連鎖', 'promise chain', 'promise chaining'], description: '.then()と.catch()を連続して繋ぎ、非同期処理を順序よく記述するパターン。各.then()は新しいPromiseを返すため連鎖できる。async/awaitの登場以降は可読性の観点から書き換えられることも多い。' },
  { term: 'async/await', aliases: ['async await'], description: 'Promiseを同期的なコードのように記述できるES2017の構文糖衣。async関数内でawaitを使うとPromiseの解決まで関数の実行を一時停止し、エラーはtry/catchで捕捉できる。' },
  { term: 'コールバック地獄', aliases: ['callback hell', 'pyramid of doom'], description: '非同期処理のコールバックが多段ネストして可読性・保守性が著しく低下するアンチパターン。ピラミッド型のインデントが特徴でPromiseやasync/awaitへの移行で解消できる。' },
  { term: 'カリー化', aliases: ['currying'], description: '複数の引数を取る関数を、引数を1つずつ受け取る関数の連鎖に変換する関数型プログラミングの技法。部分適用と組み合わせて再利用可能な関数を作成でき、RamdaやLodash/fpが代表ライブラリ。' },
  { term: '部分適用', aliases: ['partial application'], description: '関数の一部の引数を事前に固定して新しい関数を作る技法。bind()やクロージャで実装できる。カリー化と似ているが、部分適用は任意の数の引数を固定できる点が異なる。' },
  { term: '関数合成', aliases: ['function composition'], description: '複数の関数を組み合わせて新しい関数を作るプログラミング技法。compose(f, g)(x) = f(g(x))の形で関数をパイプライン化し、データ変換ロジックを宣言的に組み立てる。' },
  { term: '型強制', aliases: ['type coercion', 'implicit coercion'], description: 'JavaScriptが演算子や比較において自動的に値の型を変換する動作。==演算子による緩い等価比較や文字列連結演算での数値の文字列化などが代表例。予期しない挙動の原因になりやすい。' },
  { term: 'トランスパイル', aliases: ['transpile', 'transpilation'], description: '新しいJavaScript構文を古いブラウザでも動作するコードに変換する処理。BabelやTypeScript等のツールが担う。ソース間コンパイルとも呼ばれ、コードの最適化とポリフィルの注入も行う。' },
  { term: 'ポリフィル', aliases: ['polyfill'], description: 'ブラウザがネイティブにサポートしていないWebAPIやJavaScriptの機能を、JavaScriptコードで代替実装するライブラリ。core-jsやpolyfill.ioが代表的で、古い環境での動作互換性を保つために使われる。' },
  { term: 'イベント伝播', aliases: ['event propagation', 'event bubbling', 'event capturing'], description: 'DOMイベントがキャプチャ→ターゲット→バブリングの3フェーズで伝播する仕組み。stopPropagation()で伝播を止め、preventDefault()でデフォルト動作を抑止できる。イベント委譲のベースとなる概念。' },
  { term: 'Atomics', aliases: ['atomics', 'javascript atomics'], description: 'SharedArrayBuffer上のデータへのアトミック操作を提供する静的オブジェクト。add・sub・and・or・xor・load・store・wait・notifyなどのメソッドを持ち、スレッドセーフな低レベル並行処理を実現する。' },
  { term: 'ESモジュール', aliases: ['esモジュール', 'es modules', 'esm'], description: 'import/export構文によるJavaScript標準のモジュールシステム。静的解析可能な依存関係グラフを持ち、ツリーシェイキングが可能。CommonJS（require）と異なりブラウザとNode.jsの両方でネイティブサポートされる。' },
  { term: 'CommonJS', aliases: ['commonjs', 'cjs', 'require/module.exports'], description: 'Node.jsで長年使われてきたモジュールシステム。require()で同期的にモジュールを読み込みmodule.exportsで公開する。動的なrequireが可能な反面、静的解析が難しくツリーシェイキングに不向きでESMへの移行が進む。' },
  { term: 'V8エンジン', aliases: ['v8エンジン', 'v8', 'v8 javascript engine'], description: 'GoogleがChromeとNode.js向けに開発したオープンソースのJavaScriptエンジン。JITコンパイル、隠れクラス最適化、インラインキャッシュなどの技術で高速実行を実現し、現代のJavaScriptパフォーマンスの基盤をなす。' },
  { term: 'JITコンパイル', aliases: ['jitコンパイル', 'jit compilation', 'just-in-time compilation'], description: 'プログラムの実行中にホットパス（頻繁に実行されるコード）を機械語にコンパイルして高速化する技術。V8のTurboFanはこれを担い、インタープリタとコンパイラの中間的なアプローチで実行速度を向上させる。' },
  { term: 'プロミス化', aliases: ['promisification'], description: 'コールバックスタイルの非同期関数をPromiseを返す関数に変換する操作。Node.jsのutil.promisify()が代表的。古いAPIとモダンなasync/awaitコードを橋渡しするために使われる。' },
  { term: 'Object.assign', aliases: ['object.assign', 'object assign'], description: '1つ以上のソースオブジェクトの列挙可能な自身のプロパティをターゲットオブジェクトへシャローコピーするメソッド。オブジェクトのマージや浅いクローンに使われるが、ネストしたオブジェクトは参照コピーとなる点に注意。' },
  { term: 'Object.entries', aliases: ['object.entries', 'object entries', 'object.keys', 'object.values'], description: 'オブジェクトの列挙可能な自身のプロパティの[key, value]ペア配列を返す静的メソッド。Object.keysとObject.valuesと合わせてオブジェクトの反復処理を配列メソッド（map/filter/reduce）と組み合わせて使う。' },
  { term: 'Array.prototype.flat', aliases: ['array.prototype.flat', 'flat', 'flatmap'], description: 'ネストした配列を指定した深さまで平坦化する配列メソッド。flatMap()はmap()の後にflat(1)を行う省略形で、各要素を配列にマップして連結する処理を一度で行える。' },
  { term: 'for...of', aliases: ['for-of loop'], description: 'Symbol.iteratorを実装したオブジェクト（配列、文字列、Map、Set、ジェネレータ等）を反復するES2015のループ構文。for...inがキーを反復するのに対し、for...ofは値を直接取得できる。' },
  { term: 'Symbol.iterator', aliases: ['symbol.iterator', '@@iterator'], description: 'オブジェクトにイテレータプロトコルを実装するための既知のシンボル。このプロパティにイテレータを返す関数を定義することでfor...of、スプレッド構文、分割代入が使えるカスタムイテラブルを作成できる。' },
  { term: 'Promise.all', aliases: ['promise.all', 'promise all'], description: '渡した全Promiseが全て解決されると、その結果の配列で解決するメソッド。1つでもrejectされるとそこで全体がrejectされる。複数の非同期処理を並列に実行して全結果を待つ際に使われる。' },
  { term: 'コンストラクタ関数', aliases: ['constructor function'], description: 'newキーワードと共に呼び出し新しいオブジェクトを生成する関数。thisが新しいオブジェクトに束縛され、prototypeプロパティが新オブジェクトの__proto__に設定される。ES2015以降はclass構文が代替として使われる。' },
  { term: 'タスクキュー', aliases: ['task queue', 'callback queue'], description: 'イベントループが実行するマクロタスクを順番に蓄えるキュー。タイマー・I/Oコールバック・UIイベントハンドラなどが追加される。コールスタックが空になったときにイベントループがキューから取り出して実行する。' },
  { term: 'シンタックスシュガー', aliases: ['syntactic sugar'], description: '既存の機能をより簡潔・直感的に書けるようにした言語構文。JavaScriptではclassキーワード（プロトタイプ継承のシュガー）、async/await（Promiseのシュガー）などが代表例。機能は変わらず可読性を向上させる。' },
  { term: '隠れクラス', aliases: ['hidden class'], description: 'V8エンジンがオブジェクトのプロパティ構造を追跡するために内部的に生成するクラス。同じ順序で同じプロパティを持つオブジェクトは隠れクラスを共有でき、プロパティアクセスを高速化する。' },
  { term: 'インラインキャッシュ', aliases: ['inline cache', 'ic'], description: 'プロパティアクセスの解決結果をキャッシュしてオブジェクト操作を高速化するV8の最適化技術。同じ隠れクラスのオブジェクトへのアクセスはキャッシュから解決され、型が単型（モノモーフィック）のほど効率が良い。' },
  { term: '参照渡しと値渡し', aliases: ['pass by reference vs pass by value'], description: 'JavaScriptでは基本型（プリミティブ）は値のコピーが渡され、オブジェクト・配列は参照（メモリアドレス）が渡される。参照渡しでは関数内の変更が元のオブジェクトに影響するため注意が必要。' },
  { term: 'Number.isNaN', aliases: ['number.isnan', 'isnan', 'number.isfinite'], description: '値がNaN（非数）であるかを判定するメソッド。グローバルのisNaN()が型強制を行うのと異なり、Number.isNaN()は厳密に型チェックを行いNaN型かつNaN値の場合のみtrueを返す。' },
  { term: 'for...in', aliases: ['for-in loop'], description: 'オブジェクトの列挙可能なプロパティキー（継承されたものを含む）を反復するループ構文。プロトタイプチェーン上のプロパティも含まれるためhasOwnProperty()チェックが推奨される。配列への使用は非推奨で、for...ofを使うべき。' },
  { term: 'Object.freeze', aliases: ['object.freeze', 'object.seal'], description: 'オブジェクトのプロパティの追加・削除・変更を禁止するメソッド。シャローなフリーズのため深くネストしたオブジェクトには再帰適用が必要。Object.seal()はプロパティの追加・削除を禁止するが変更は許可する。' },
  { term: '条件型', aliases: ['conditional types'], description: '型レベルの三項演算子`T extends U ? X : Y`で表される型。型Tが型Uに代入可能な場合はX、そうでなければYを返す。`infer`と組み合わせて型から内部の型を抽出する高度な型プログラミングに使われる。' },
  { term: 'マップ型', aliases: ['mapped types'], description: '既存の型のプロパティを反復処理して新しい型を生成するTypeScriptの機能。`{ [K in keyof T]: ... }`構文を使い、`Partial<T>`や`Readonly<T>`などのユーティリティ型の基盤となる。' },
  { term: 'テンプレートリテラル型', aliases: ['template literal types'], description: '文字列テンプレートリテラルの構文を型レベルで使用できるTypeScript 4.1以降の機能。`type EventName = `on${string}``のように文字列パターンを型として表現し、APIの命名規則などを型で強制できる。' },
  { term: 'ユニオン型', aliases: ['union types'], description: '複数の型のいずれかであることを表す型。`string | number`のように`|`で連結する。型の絞り込みと組み合わせて安全に各型固有の操作が行え、判別共用体パターンの基盤にもなる。' },
  { term: '交差型', aliases: ['intersection types'], description: '複数の型すべてのプロパティを同時に持つ型を表す。`A & B`と書き、Aの全プロパティとBの全プロパティを合わせた型になる。ミックスインパターンやオブジェクトの拡張に使われるが、プリミティブ型への適用では`never`になることがある。' },
  { term: '型ガード', aliases: ['type guard'], description: 'ランタイムで型チェックを行い、その後のスコープで型を絞り込むTypeScriptの仕組み。`typeof`、`instanceof`、`in`演算子による組み込みガードや、型述語を返すユーザー定義型ガードがある。' },
  { term: '型述語', aliases: ['type predicates'], description: '関数の戻り値型として`param is Type`の形式で記述するTypeScriptの構文。真を返した場合に引数の型が特定の型であることをコンパイラに伝え、呼び出し元で型の絞り込みを実現するユーザー定義型ガードの仕組み。' },
  { term: '型の絞り込み', aliases: ['type narrowing'], description: '条件分岐内でTypeScriptコンパイラが変数の型をより具体的な型に自動的に限定する機能。`typeof`チェック、`instanceof`、nullチェック、判別共用体のswitch文などによって自動で型が絞り込まれる。' },
  { term: '判別共用体', aliases: ['discriminated union', 'tagged union'], description: '共通のリテラル型プロパティ（判別子）を持つ複数の型をユニオンで結合したパターン。`switch`文や`if`文で判別子をチェックすると型が自動的に絞り込まれ、各ケースを型安全に処理できる。' },
  { term: 'ブランド型', aliases: ['branded types', 'opaque types'], description: '構造的型システムに名義的な制約を加えるパターン。交差型を使い`type UserId = string & { __brand: \'UserId\' }`のように実際には存在しないプロパティを付与して、同じ基底型でも異なる型として扱えるようにする。' },
  { term: 'ファントム型', aliases: ['phantom types'], description: '型パラメータを値の表現には使わず、コンパイル時のメタ情報として型に付随させるパターン。`type Tagged<T, Tag> = T & { _tag?: Tag }`のように状態や権限を型レベルで追跡し、不正な操作をコンパイル時に防ぐ。' },
  { term: '共変性', aliases: ['covariance'], description: '型のサブタイプ関係が型引数のサブタイプ関係と同方向に保たれる性質。`Cat`が`Animal`のサブタイプなら`Array<Cat>`は`Array<Animal>`のサブタイプになる。TypeScriptでは戻り値の型や読み取り専用プロパティが共変。' },
  { term: '反変性', aliases: ['contravariance'], description: '型のサブタイプ関係が型引数のサブタイプ関係と逆方向になる性質。`Animal`を受け取る関数は`Cat`を受け取る関数のサブタイプになる。TypeScriptでは`strictFunctionTypes`有効時に関数引数が反変として扱われる。' },
  { term: 'satisfies演算子', aliases: ['satisfies operator'], description: 'TypeScript 4.9で追加された演算子。値が指定した型を満たすことを検証しつつ、変数の型を広い型ではなく推論された具体的な型として保持できる。`as`による型アサーションとは異なり型安全性を犠牲にしない。' },
  { term: 'const assertion', aliases: ['as const'], description: 'オブジェクトや配列リテラルに`as const`を付けると全プロパティが`readonly`かつリテラル型として推論されるTypeScriptの機能。型の一般化を防ぎ、定数オブジェクトやタプルとして扱いたい場合に使う。' },
  { term: 'enum', aliases: ['enumeration', '列挙型'], description: '名前付き定数の集合を定義するTypeScriptの機能。数値enum・文字列enum・const enumがある。ただし通常のenumはランタイムオブジェクトを生成するため、バンドルサイズや型安全性の観点からユニオン型やconst assertionで代替することも多い。' },
  { term: '宣言マージ', aliases: ['declaration merging'], description: '同名の宣言が複数ある場合にTypeScriptコンパイラが自動的に一つの定義へ統合する仕組み。インターフェースの拡張やnamespaceとクラスの結合などで使われ、型定義ファイルでライブラリを拡張する際に重要。' },
  { term: 'モジュール拡張', aliases: ['module augmentation'], description: '既存モジュールの型定義に対して新しいプロパティやメソッドを追加する仕組み。`declare module \'express\'`などで外部ライブラリの型を拡張でき、宣言マージと組み合わせてグローバルな型を安全に拡張できる。' },
  { term: 'アンビエント宣言', aliases: ['ambient declaration'], description: 'TypeScriptに実装を持たず型情報だけを宣言するための構文。`declare`キーワードを使い、JavaScriptライブラリのグローバル変数やモジュールの型情報を.d.tsファイルで提供する際に用いる。' },
  { term: '型定義ファイル', aliases: ['.d.ts', 'declaration file'], description: 'TypeScriptの型情報のみを含む`.d.ts`拡張子のファイル。JavaScriptライブラリに型情報を付与するためや、モジュールのパブリックAPIを宣言するために使われる。DefinitelyTypedでサードパーティライブラリの型定義が公開されている。' },
  { term: 'プロジェクト参照', aliases: ['project references'], description: 'TypeScript 3.0以降で複数のtsconfig間に依存関係を定義できる機能。`composite`フラグと組み合わせてインクリメンタルビルドを実現し、モノレポや大規模プロジェクトでビルド時間を大幅に削減できる。' },
  { term: 'パスエイリアス', aliases: ['path aliases', 'path mapping'], description: 'tsconfig.jsonの`paths`オプションで相対インポートに代わる短縮エイリアスを定義する機能。`@/components`のように書けるようになり、深いディレクトリ構造でのimport文を簡潔にする。バンドラー側でも同様の設定が必要な場合がある。' },
  { term: 'バレルファイル', aliases: ['barrel file', 'index.ts'], description: 'ディレクトリ内の複数モジュールをre-exportする`index.ts`ファイル。`import { A, B } from \'./components\'`のようにディレクトリ単位でimportできるが、ツリーシェイキングを妨げたり循環依存を生みやすいため使用に注意が必要。' },
  { term: 'ESM/CJS相互運用', aliases: ['esm/cjs相互運用', 'esm/cjs interop', 'esmoduleinterop'], description: 'ECMAScript ModulesとCommonJSの間で互換性を保ちながらモジュールをimport/exportする仕組み。`esModuleInterop`フラグにより`import fs from \'fs\'`のようなdefaultインポートが可能になる。デュアルパッケージハザードなど複雑な問題も存在する。' },
  { term: 'isolatedModules', aliases: ['isolatedmodules', 'isolatedmodules flag'], description: 'tsconfig.jsonのフラグ。各ファイルを独立したモジュールとしてトランスパイルできることを保証し、型のみのexportにエラーを出す。esbuildやSWCなどの単一ファイルトランスパイラとの互換性確保に必須。' },
  { term: 'verbatimModuleSyntax', aliases: ['verbatimmodulesyntax', 'verbatimmodulesyntax flag'], description: 'TypeScript 5.0で導入されたtsconfig.jsonフラグ。型のみのimport/exportには`import type`/`export type`を強制し、モジュール構文をそのまま出力することを保証する。`isolatedModules`の後継として推奨される設定。' },
  { term: 'tsc', description: 'TypeScriptの公式コンパイラCLIコマンド。`.ts`ファイルをJavaScriptに変換するほか、型チェックのみを行う`--noEmit`オプションも持つ。`tsconfig.json`を読み込み、プロジェクト全体のコンパイルを担う。' },
  { term: 'ts-node', description: 'TypeScriptファイルをNode.js上で直接実行するためのランタイム。コンパイルステップを省略して`.ts`ファイルを実行でき、スクリプト実行や開発時のREPLに使われる。ESM対応の`ts-node/esm`やより高速な`tsx`が代替として台頭している。' },
  { term: 'tsx', description: 'esbuildを内部で使用してTypeScriptとJSXを高速にトランスパイルするNode.js実行ツール。`ts-node`の代替として普及しており、ESMとCJSの両方をサポートしつつ型チェックなしで非常に高速に動作する。' },
  { term: 'esbuild', description: 'GoLanguageで書かれた超高速なJavaScript/TypeScriptバンドラー兼トランスパイラ。型チェックは行わないが変換速度が従来のwebpackより数十倍速く、Viteやtsxなどのビルドツールのコアとして広く採用されている。' },
  { term: 'swc', description: 'RustLanguageで書かれた高速なJavaScript/TypeScriptコンパイラ。Next.jsやJestがデフォルトのトランスパイラとして採用しており、Babelと互換性のあるプラグイン変換を提供しながら大幅に高速化する。' },
  { term: 'TypeScriptコンパイラAPI', aliases: ['typescriptコンパイラapi', 'typescript compiler api'], description: 'TypeScriptが公開するプログラム的にASTの解析・変換・型チェックを行うためのNodeJS API。コードジェネレーターやlintツール、IDEプラグインなどの開発に使われ、`ts.createProgram`や`ts.createSourceFile`が主要エントリポイント。' },
  { term: 'リテラル型', aliases: ['literal types'], description: '特定の値そのものを型として表現するTypeScriptの機能。`\'red\'`、`42`、`true`などの具体的な値を型として使え、`\'left\' | \'right\'`のようにユニオンと組み合わせて有限の選択肢を型で表現できる。' },
  { term: 'タプル型', aliases: ['tuple types'], description: '各要素の型と数を固定した配列型。`[string, number]`のように宣言し、位置ごとに型が決まる。残余要素`...T[]`や省略可能要素`T?`もサポートする。React hooksの戻り値型やCSVパースなどで活用される。' },
  { term: 'インデックスシグネチャ', aliases: ['index signature'], description: 'オブジェクト型において任意のキーに対する値の型を定義する構文。`{ [key: string]: number }`のように記述する。`noUncheckedIndexedAccess`を有効にすると値の型に`undefined`が付与され、アクセス時の安全性が高まる。' },
  { term: 'keyof演算子', aliases: ['keyof operator'], description: 'オブジェクト型の全プロパティ名をユニオン型として取得するTypeScriptの型演算子。`keyof User`が`\'id\' | \'name\' | \'email\'`となるように型から安全にキーの集合を得られ、汎用的なアクセサー関数の型付けに不可欠。' },
  { term: 'typeof演算子（型）', aliases: ['typeof operator (type level)'], description: '型の文脈で使う`typeof`演算子。変数や関数から型を抽出して再利用できる。`typeof someObj`で値の型を取得したり、`ReturnType<typeof fn>`のように関数の戻り値型を得るなど、型定義の重複を避けるために活用される。' },
  { term: 'inferキーワード', aliases: ['infer keyword'], description: '条件型の`extends`節内で型を推論・キャプチャするためのキーワード。`T extends Promise<infer U> ? U : never`のように関数の引数や戻り値、配列の要素型などをパターンマッチングで取り出す型プログラミングの中核をなす。' },
  { term: 'never型', aliases: ['never type'], description: '到達不能なコードや空のユニオン型を表す底型（Bottom Type）。例外のみをthrowする関数の戻り値型や、すべての条件を網羅したswitch文のdefaultブロックの型になる。型の絞り込みで使い切ったユニオンが`never`になることを利用した網羅性チェックにも使われる。' },
  { term: 'unknown型', aliases: ['unknown type'], description: '任意の値を受け取れるが使用前に型チェックを強制するTypeScriptの型。`any`と異なり操作前に型ガードが必要で、外部からのデータ（APIレスポンスやJSONパース結果）の受け取りに`any`より安全な代替として推奨される。' },
  { term: 'any型', aliases: ['any type'], description: '型チェックを無効にするTypeScriptの脱出ハッチ型。あらゆる操作が許容されコンパイルエラーが出ないが、型安全性が失われる。JavaScriptからの段階的移行や型が複雑すぎて記述が困難な場合に限定的に使うべきで、可能なら`unknown`で代替する。' },
  { term: 'void型', aliases: ['void type'], description: '値を返さない関数の戻り値型を表すTypeScriptの型。`undefined`に似ているが戻り値を無視することを明示的に表し、コールバック関数の戻り値型として`void`を使うと実際には値を返す関数でも代入可能になる特殊な互換性ルールがある。' },
  { term: 'Utility Types', aliases: ['utility types', '組み込みユーティリティ型'], description: 'TypeScriptが標準で提供する型変換ユーティリティの総称。`Partial<T>`、`Required<T>`、`Readonly<T>`、`Pick<T,K>`、`Omit<T,K>`、`ReturnType<T>`などがある。マップ型・条件型・inferを組み合わせて実装されており、型プログラミングの参考にもなる。' },
  { term: 'Partial', aliases: ['partial'], description: 'オブジェクト型の全プロパティをオプショナルにするTypeScript組み込みユーティリティ型。`Partial<User>`とすると全フィールドが`?`付きになり、更新操作のリクエスト型や段階的なオブジェクト構築パターンで活用される。' },
  { term: 'Readonly', aliases: ['readonly'], description: 'オブジェクト型の全プロパティを読み取り専用にするTypeScript組み込みユーティリティ型。`Readonly<Config>`とすると全フィールドが`readonly`になり、設定オブジェクトや不変データの型表現に使う。深いネストには`DeepReadonly`などの拡張が必要。' },
  { term: 'Pick', aliases: ['pick'], description: 'オブジェクト型から指定したプロパティのみを抽出して新しい型を作るTypeScript組み込みユーティリティ型。`Pick<User, \'id\' | \'name\'>`で必要なフィールドだけを持つ型を得られ、APIのレスポンス型やコンポーネントのProps型の定義に役立つ。' },
  { term: 'Omit', aliases: ['omit'], description: 'オブジェクト型から指定したプロパティを除いた新しい型を作るTypeScript組み込みユーティリティ型。`Omit<User, \'password\'>`でパスワードを除外した安全な型が得られる。`Pick`の逆操作で、除外するプロパティが少ない場合に有効。' },
  { term: 'Exclude', aliases: ['exclude'], description: 'ユニオン型から特定の型メンバーを除外するTypeScript組み込みユーティリティ型。`Exclude<\'a\' | \'b\' | \'c\', \'a\'>`は`\'b\' | \'c\'`になる。オブジェクトの`Omit`とは異なりユニオン型に作用する。' },
  { term: 'Extract', aliases: ['extract'], description: 'ユニオン型から特定の型メンバーのみを抽出するTypeScript組み込みユーティリティ型。`Extract<string | number | boolean, string | number>`は`string | number`になる。`Exclude`の逆操作。' },
  { term: 'ReturnType', aliases: ['returntype'], description: '関数型から戻り値の型を取得するTypeScript組み込みユーティリティ型。`ReturnType<typeof fetchUser>`のように関数の戻り値型を型定義から分離して再利用でき、関数の実装を変更したときに戻り値型が自動で追従する。' },
  { term: 'Parameters', aliases: ['parameters'], description: '関数型の引数型をタプル型として取得するTypeScript組み込みユーティリティ型。`Parameters<typeof fn>`で引数の型リストが得られ、ラッパー関数の引数型定義や高階関数の型付けに活用される。' },
  { term: 'Awaited', aliases: ['awaited'], description: 'Promiseの解決値の型を取得するTypeScript 4.5以降の組み込みユーティリティ型。`Awaited<Promise<string>>`は`string`になる。ネストしたPromiseも再帰的に解決し、非同期関数の戻り値型から実際のデータ型を得るのに使う。' },
  { term: 'NonNullable', aliases: ['nonnullable'], description: '型から`null`と`undefined`を除外するTypeScript組み込みユーティリティ型。`NonNullable<string | null | undefined>`は`string`になる。nullチェック後の型として使ったり、厳格なnull安全性が保証されるコンテキストで活用される。' },
  { term: 'InstanceType', aliases: ['instancetype'], description: 'コンストラクタ型からインスタンスの型を取得するTypeScript組み込みユーティリティ型。`InstanceType<typeof MyClass>`でクラスのインスタンス型が得られ、クラスを値として渡す汎用的なファクトリ関数の型付けに使う。' },
  { term: 'readonly修飾子', aliases: ['readonly modifier'], description: 'プロパティや配列要素に再代入を禁止するTypeScriptのキーワード。`readonly`プロパティは宣言時またはコンストラクタでのみ代入可能で、`ReadonlyArray<T>`や`readonly T[]`で配列の変更も防げる。コンパイル時のチェックで不変性を保証する。' },
  { term: '型引数', aliases: ['type arguments'], description: 'ジェネリック型や関数を使用する際に具体的な型を指定する部分。`Array<string>`の`string`や`Promise<number>`の`number`が型引数にあたる。型推論により省略できる場合が多く、明示的に指定することで意図を明確にできる。' },
  { term: '型パラメータ', aliases: ['type parameters'], description: 'ジェネリック型や関数の定義側で宣言する型の変数。`function identity<T>(arg: T): T`における`T`が型パラメータ。`extends`で制約を加えたり`=`でデフォルト型を設定できる。呼び出し時に型引数が渡されるか推論で決定される。' },
  { term: '型制約', aliases: ['type constraints', 'extends constraint'], description: 'ジェネリクスの型パラメータに`extends`キーワードで課す条件。`<T extends object>`とすることで型パラメータTにプリミティブ以外しか渡せなくなる。型パラメータ内で特定のプロパティへのアクセスを安全に行うために必要。' },
  { term: 'デフォルト型引数', aliases: ['default type arguments'], description: 'ジェネリクスの型パラメータに`= Type`でデフォルト値を設定する機能。`<T = string>`とすると型引数を省略したときに`string`が使われる。ライブラリAPIで後方互換性を維持しながら型パラメータを追加する際に有用。' },
  { term: '再帰的型', aliases: ['recursive types'], description: '型定義の中に自分自身を参照する型。ツリー構造`type Tree<T> = { value: T; children: Tree<T>[] }`やJSONのような再帰的データ構造を型で正確に表現できる。TypeScript 3.7以降で条件型や配列型でも再帰が安定して動作するようになった。' },
  { term: '型レベルプログラミング', aliases: ['type-level programming'], description: '条件型、マップ型、inferキーワードなどを駆使してコンパイル時に複雑な型計算を行うTypeScript技術。型で文字列操作、型の検証、型の変換を行えるが可読性・保守性との兼ね合いが重要で、複雑すぎる型はコンパイラパフォーマンスを低下させることもある。' },
  { term: 'overload', aliases: ['function overload', 'オーバーロード宣言'], description: '同じ関数名で引数の型や数が異なる複数のシグネチャを定義するTypeScriptの機能。実装シグネチャはオーバーロードシグネチャよりも広い型を持つ必要があり、ユーザーは実装シグネチャを直接呼び出せない。引数によって戻り値型が変わる関数を正確に型付けできる。' },
  { term: '型互換性', aliases: ['type compatibility'], description: 'TypeScriptの構造的型システムにおいて型Aが型Bに代入可能かどうかを決定するルール。必要なプロパティを持っていれば代入可能（構造的サブタイピング）であり、関数型については引数と戻り値の共変・反変ルールに従う。' },
  { term: '型アサーション', aliases: ['type assertion', 'as型アサーション'], description: 'コンパイラの型推論を上書きして特定の型として扱うTypeScriptの構文。`value as string`または旧スタイルの`<string>value`で記述する。型チェックを部分的に迂回するため誤用するとランタイムエラーの原因になり、型ガードや`unknown`との組み合わせで代替することが推奨される。' },
  { term: 'non-null assertion', aliases: ['non-null assertion operator', '!演算子'], description: '値が`null`や`undefined`でないことをコンパイラに宣言する`!`後置演算子。`document.getElementById(\'app\')!`のように使うが、実際にnullであればランタイムエラーになる。nullチェックが面倒なときの安易な使用は避け、明確な根拠がある場合に限定すべき。' },
  { term: 'strict', description: 'tsconfig.jsonで型チェックを最も厳格にする`compilerOptions.strict`フラグ。`strictNullChecks`、`strictFunctionTypes`、`noImplicitAny`、`strictPropertyInitialization`など複数のフラグをまとめて有効にする。新規プロジェクトでは必ず有効にすることが推奨される。' },
  { term: 'strictNullChecks', aliases: ['strictnullchecks'], description: 'tsconfig.jsonのフラグ。有効にすると`null`と`undefined`が他の型に代入できなくなり、nullに起因するランタイムエラーをコンパイル時に検出できる。`strict`に含まれており、TypeScript開発で最も重要な設定のひとつ。' },
  { term: 'noUncheckedIndexedAccess', aliases: ['nouncheckedindexedaccess'], description: 'tsconfig.jsonのフラグ。有効にするとインデックスシグネチャや配列の添字アクセスで返される型に`undefined`が自動的に付与される。配列の範囲外アクセスやキーが存在しないオブジェクトへのアクセスを型レベルで安全に扱えるようになる。' },
  { term: 'exactOptionalPropertyTypes', aliases: ['exactoptionalpropertytypes'], description: 'tsconfig.jsonのフラグ。有効にすると`{ prop?: string }`のオプショナルプロパティに明示的に`undefined`を代入することが禁止される。プロパティが「存在する」ことと「undefinedである」ことを区別して型で正確に表現できる。' },
  { term: 'noImplicitAny', aliases: ['noimplicitany'], description: 'tsconfig.jsonのフラグ。型推論で`any`型が暗黙的に付与される場合にエラーを発生させる。`strict`に含まれており、型のない変数や引数を明示的に型付けすることを強制してコードベース全体の型安全性を保つ。' },
  { term: 'sourceMap', aliases: ['sourcemap'], description: 'TypeScriptコンパイル時に生成される`.js.map`ファイル。コンパイル後のJavaScriptと元の`.ts`ソースを対応付けるマッピング情報を含み、ブラウザやNode.jsのデバッガでTypeScriptソースを直接デバッグできるようにする。' },
  { term: 'declaration', aliases: ['declaration flag'], description: 'tsconfig.jsonのフラグ。有効にするとコンパイル時に`.d.ts`型定義ファイルを自動生成する。ライブラリを公開する際に必須で、利用者がTypeScriptで型情報付きでライブラリを使えるようになる。`composite`を有効にすると暗黙的に有効になる。' },
  { term: 'incremental', aliases: ['incremental compilation'], description: 'tsconfig.jsonのフラグ。有効にすると前回のビルド情報を`.tsbuildinfo`ファイルに保存し、変更があったファイルのみ再コンパイルするインクリメンタルビルドを実現する。大規模プロジェクトでコンパイル時間を大幅に削減できる。' },
  { term: 'moduleResolution', aliases: ['moduleresolution'], description: 'tsconfig.jsonでモジュール解決アルゴリズムを指定するオプション。`node`（CommonJS）、`node16`/`nodenext`（ESMサポート）、`bundler`（Vite/esbuildなどのバンドラー向け）などがある。設定を間違えるとimportが正しく解決されないエラーが発生する。' },
  { term: 'allowSyntheticDefaultImports', aliases: ['allowsyntheticdefaultimports'], description: 'tsconfig.jsonのフラグ。defaultエクスポートを持たないモジュールへのdefaultインポートを型エラーなしに許可する。`esModuleInterop`を有効にすると自動的に有効になる。型チェック上の許可のみでランタイムの変換は行わない。' },
  { term: 'skipLibCheck', aliases: ['skiplibcheck'], description: 'tsconfig.jsonのフラグ。`.d.ts`ファイル内の型エラーをスキップする。サードパーティライブラリの型定義に不整合がある場合のエラー回避に使われるが、本来の型エラーも見逃す可能性があるため、依存関係の型定義が整備されている場合は無効が望ましい。' },
  { term: 'baseUrl', aliases: ['baseurl'], description: 'tsconfig.jsonのコンパイラオプション。モジュール解決の基点となるディレクトリを指定する。`paths`オプションのエイリアス解決の起点にもなる。バンドラーが`bundler`モードの場合は`baseUrl`が不要になることが多く、設定の重複に注意が必要。' },
  { term: 'lib', description: 'tsconfig.jsonのコンパイラオプション。コンパイラに含める組み込み型定義ライブラリを指定する。`DOM`、`ES2022`、`WebWorker`などが選べ、対象実行環境で利用できるAPIだけを型として含めることでブラウザとNode.jsで型の混在を防ぐ。' },
  { term: 'experimentalDecorators', aliases: ['experimentaldecorators'], description: 'tsconfig.jsonのフラグ。ステージ2のデコレータ仕様を有効にする。Angular、NestJSなどのフレームワークで使用されてきたが、TC39でステージ3のデコレータ仕様（動作が異なる）が確定したため、新規プロジェクトでは最新仕様への移行が推奨される。' },
  { term: 'emitDecoratorMetadata', aliases: ['emitdecoratormetadata'], description: 'tsconfig.jsonのフラグ。デコレータを使ったクラスのプロパティや引数の型情報をランタイムに`Reflect.metadata`として出力する。NestJSの依存性注入などで型情報を利用するフレームワークに必要で、`experimentalDecorators`と合わせて設定する。' },
  { term: 'デコレータ（TypeScript）', aliases: ['デコレータ（typescript）', 'クラスデコレータ'], description: 'クラス、メソッド、プロパティ、引数に付加できる`@expression`形式のメタプログラミング構文。AOPやDIコンテナの実装に使われる。TypeScript 5.0でTC39ステージ3デコレータが実装され、`experimentalDecorators`とは別の仕様として共存している。' },
  { term: '名前空間（TypeScript）', aliases: ['名前空間（typescript）', 'namespace（typescript）'], description: 'TypeScript固有のモジュール整理機能。`namespace`キーワードで関連する型や関数をグループ化する。ESモジュールが普及した現在は非推奨とされることが多く、主に`.d.ts`型定義ファイルでのグローバル型整理やアンビエント宣言で使われる。' },
  { term: 'トリプルスラッシュ指令', aliases: ['triple-slash directives', '/// <reference>'], description: 'ファイル先頭に記述する`/// <reference types="..."/>`などのXML形式のコメント。型定義ファイルへの参照、グローバル型の追加、`lib`ライブラリのインクルードに使われる。モジュールシステムが使える環境ではimportが推奨される。' },
  { term: '型の広がり', aliases: ['type widening'], description: '変数に値を代入した際に型が具体的なリテラル型から広い型に自動的に変換されるTypeScriptの動作。`let x = \'hello\'`はstringに広がるが`const x = \'hello\'`はリテラル型`\'hello\'`のまま保持される。`as const`でリテラル型を維持できる。' },
  { term: '型の縮小', aliases: ['type narrowing（縮小）', 'type reduction'], description: 'ユニオン型などの広い型が特定のスコープ内でより具体的な型に絞り込まれること。制御フロー解析によって`typeof`チェックや`instanceof`、nullチェックの後に型が自動的に縮小される。TypeScriptのコントロールフロー解析（CFA）が担う。' },
  { term: 'コントロールフロー解析', aliases: ['control flow analysis', 'cfa'], description: 'TypeScriptコンパイラが条件分岐・ループ・例外処理などの制御フローを追跡し、各コードポイントで変数の型を精密に決定する機能。型の絞り込みや`never`型の検出、到達不能コードの判定などに活用される。' },
  { term: '型ユーティリティ設計', aliases: ['type utility design'], description: '再利用可能な型変換・型検証のユーティリティ型をプロジェクト内で設計・整備する実践。DeepPartial、Nullable、Promisify、ValuesOfなど標準ライブラリにない型を自前で定義し、型安全なコードベースの基盤を作る。' },
  { term: 'const enum', description: 'コンパイル時にインライン展開されるTypeScriptの列挙型。通常のenumと異なりランタイムオブジェクトを生成せず、使用箇所にリテラル値が直接埋め込まれるためバンドルサイズが小さい。ただし`isolatedModules`環境やdeclare const enumの扱いに制約がある。' },
  { term: '型のインポート', aliases: ['import type'], description: '型情報のみをインポートし、JavaScriptのバンドルに含めないことを明示する`import type`構文。ランタイムには不要な型定義をimportする際に使い、循環依存の解消やバンドルサイズ削減に効果がある。`isolatedModules`環境では型のみのexportに必須。' },
  { term: '型の再利用', aliases: ['type reuse'], description: '既存の型定義からユーティリティ型や型演算子を使って新しい型を導出し、同じ情報を複数箇所で定義しないようにする実践。DRY原則を型レベルで適用し、型変更時に漏れが生じにくいコードベースを作る。' },
  { term: 'Discriminant Property', aliases: ['discriminant property', 'discriminant', '判別子プロパティ'], description: '判別共用体において各メンバーを識別するためのリテラル型プロパティ。`type: \'success\'`や`kind: \'circle\'`のように固有のリテラル値を持ち、TypeScriptの制御フロー解析がこれを利用して型を自動絞り込みする。' },
  { term: 'Mapped Type Modifier', aliases: ['mapped type modifier', 'mapped type modifiers'], description: 'マップ型においてプロパティの`readonly`や`?`（オプショナル）を制御する修飾子。`-readonly`や`-?`で既存の修飾子を除去でき、`Mutable<T>`（readonly除去）や`Required<T>`（?除去）などのユーティリティ型の実装に使われる。' },
  { term: 'Template Literal Type Manipulation', aliases: ['template literal type manipulation', 'uppercase', 'lowercase', 'capitalize', 'uncapitalize'], description: 'テンプレートリテラル型と組み合わせて使用するTypeScript組み込みの文字列操作ユーティリティ型。`Uppercase<\'hello\'>`は`\'HELLO\'`になる。APIのイベント名生成やCSSプロパティの型付けなど文字列パターンの型表現に活用される。' },
  { term: 'Opaque Type', aliases: ['opaque type', '不透明型'], description: '内部構造を隠蔽し、専用のコンストラクタ関数を通じてのみ生成できる型パターン。TypeScriptにはネイティブサポートがないが、ブランド型や`unique symbol`を使って同等の効果を得られる。ドメイン駆動設計の値オブジェクトを型レベルで強制するのに使われる。' },
  { term: 'デコレーター（TypeScript）', aliases: ['デコレーター（typescript）', 'decorator (typescript)', 'typescript decorator'], description: 'TypeScriptにおいてクラス・メソッド・プロパティに付加的な機能を追加するための構文です。@記号を使ってメタプログラミングを実現します。' },
  { term: 'useRef', aliases: ['useref', 'useref hook'], description: 'Reactが提供するフック。レンダー間で値を保持するミュータブルなrefオブジェクトを返す。DOMノードへの直接参照やレンダーをトリガーしない値の保存に使われ、currentプロパティで値にアクセスする。' },
  { term: 'useReducer', aliases: ['usereducer', 'usereducer hook'], description: 'Reactが提供するフック。reduxのようなreducer関数とdispatchを用いた状態管理パターンを実現する。複雑な状態ロジックや次の状態が前の状態に依存する場合にuseStateより適している。' },
  { term: 'useId', aliases: ['useid', 'useid hook'], description: 'Reactが提供するフック。アクセシビリティ属性（aria-labelledbyなど）向けにサーバーとクライアントで一致する一意なIDを生成する。ハイドレーションの不一致を防ぎつつ安定したIDを提供する。' },
  { term: 'useDeferredValue', aliases: ['usedeferredvalue', 'usedeferredvalue hook'], description: 'Reactが提供するフック。値の更新を遅延させ、UIの緊急な更新（入力など）を優先させる。重いレンダリングをバックグラウンドに回すConcurrentモードの機能で、検索フィルタリング等に有効。' },
  { term: 'useTransition', aliases: ['usetransition', 'usetransition hook'], description: 'Reactが提供するフック。状態更新を非緊急のトランジションとしてマークし、UIの応答性を維持しながら重い更新を遅延実行する。isPendingフラグとstartTransition関数を返す。' },
  { term: 'useSyncExternalStore', aliases: ['usesyncexternalstore', 'usesyncexternalstore hook'], description: 'Reactが提供するフック。React外部のストア（Redux、ブラウザAPIなど）をサブスクライブし、ティアリングなしに値を読み取るための低レベルAPI。ライブラリ作者向けの設計となっている。' },
  { term: 'useOptimistic', aliases: ['useoptimistic', 'useoptimistic hook'], description: 'React 19が提供するフック。非同期操作（Server Actionsなど）の完了を待たずに楽観的に更新後のUIを先行表示する。エラー時には自動的に元の状態に戻るため整合性を保ちやすい。' },
  { term: 'useImperativeHandle', aliases: ['useimperativehandle', 'useimperativehandle hook'], description: 'Reactが提供するフック。forwardRefと組み合わせて、親コンポーネントに公開するrefオブジェクトのインターフェースをカスタマイズする。子の内部実装を隠蔽しつつ必要な操作だけを公開できる。' },
  { term: 'useLayoutEffect', aliases: ['uselayouteffect', 'uselayouteffect hook'], description: 'Reactが提供するフック。useEffectと同様だがDOM更新後・ブラウザ描画前に同期的に実行される。スクロール位置取得やツールチップ位置計算など描画前にDOMを計測・変更する場合に使う。' },
  { term: 'useDebugValue', aliases: ['usedebugvalue', 'usedebugvalue hook'], description: 'Reactが提供するフック。React DevToolsにカスタムフックのラベルを表示するためのデバッグ用API。ライブラリ作者がカスタムフックの内部状態をわかりやすく可視化するために使う。' },
  { term: 'Fiberアーキテクチャ', aliases: ['fiberアーキテクチャ', 'react fiber', 'fiber'], description: 'React 16で導入された再設計されたコアアルゴリズム。レンダリング作業を小さな単位（Fiber）に分割し、優先度に基づいて中断・再開・破棄が可能。Concurrent Renderingの基盤となる。' },
  { term: 'React Compiler', aliases: ['react compiler', 'react forget'], description: 'Reactのコードを静的解析して自動的にメモ化を適用するコンパイラ。React 19で安定版リリース。useMemo/useCallbackを手動で書かずともパフォーマンス最適化を実現し、コードの冗長さを削減する。' },
  { term: 'ErrorBoundary', aliases: ['errorboundary', 'error boundary', 'エラー境界'], description: 'Reactのクラスコンポーネントで実装するエラーキャッチ機構。子コンポーネントツリーのレンダリング・ライフサイクル中に発生したJavaScriptエラーをキャッチしフォールバックUIを表示する。' },
  { term: 'React.lazy', aliases: ['react.lazy', 'react lazy loading'], description: 'Reactが提供するコード分割のためのAPI。動的importを使ってコンポーネントを遅延読み込みし、バンドルサイズを削減する。Suspenseと組み合わせてローディング状態を表示する。' },
  { term: 'Concurrent Rendering', aliases: ['concurrent rendering', 'concurrent mode', '並行レンダリング'], description: 'React 18で導入された並行レンダリング機能。レンダリング作業を中断可能にし、ユーザー操作などの緊急な更新を優先処理することでUIの応答性を維持する。useTransitionなどのAPIで活用する。' },
  { term: '選択的ハイドレーション', aliases: ['selective hydration'], description: 'React 18のConcurrent SSRで実現した機能。ページ全体のハイドレーション完了を待たず、ユーザーがインタラクションした部分を優先的にハイドレーションする。TTIの改善に貢献する。' },
  { term: '制御コンポーネント', aliases: ['controlled component', '制御されたコンポーネント'], description: 'フォーム要素の値をReactのstateで管理するパターン。入力のたびにonChangeでstateを更新し、valueとしてstateを渡すことで単一の信頼できる情報源を実現する。' },
  { term: '非制御コンポーネント', aliases: ['uncontrolled component', '非制御されたコンポーネント'], description: 'フォーム要素の値をReactのstateではなくDOMに直接管理させるパターン。refを使って値を読み取り、シンプルなフォームや外部ライブラリとの統合に適している。' },
  { term: 'forwardRef', aliases: ['forwardref', 'react.forwardref', 'ref forwarding', 'refフォワーディング'], description: 'Reactが提供するAPI。親コンポーネントからrefをコンポーネントの内部DOM要素や子コンポーネントに転送する。ライブラリのUIコンポーネントがDOMアクセスを外部に公開する際に使われる。' },
  { term: 'React.memo', aliases: ['react.memo', 'react memo'], description: 'Reactが提供する高階コンポーネント。propsが変わらない限り再レンダーをスキップするメモ化を行う。不必要な子コンポーネントの再レンダーを防ぎパフォーマンスを最適化する。' },
  { term: 'keyプロパティ', aliases: ['key prop', 'key', 'keyプロップ'], description: 'Reactがリストのレンダリング時に各要素を識別するための特別なプロパティ。兄弟要素間でユニークな値を指定することで、追加・削除・並び替え時のDOM更新を最小化する。' },
  { term: 'ポータル', aliases: ['portal', 'createportal', 'react portal'], description: 'ReactのcreatePortal APIを使い、親コンポーネントのDOM階層外の任意のDOMノードに子をレンダーする機能。モーダル・トースト・ツールチップなどDOMの最上位に配置したいUIに使う。' },
  { term: 'propsのバケツリレー', aliases: ['props drilling', 'prop drilling', 'プロップドリリング'], description: '必要なコンポーネントに届けるために中間のコンポーネント群を経由してpropsを渡し続けるアンチパターン。コードの冗長化とメンテナンス性の低下を招く。Contextやstate管理ライブラリで解決する。' },
  { term: '複合コンポーネント', aliases: ['compound component', 'compound components'], description: '複数の関連コンポーネントをContextで内部状態を共有しながら組み合わせるReactの設計パターン。Select/Option、Tabs/Tab等のUIライブラリで使われ、高い柔軟性と表現力を提供する。' },
  { term: 'レンダープロップ', aliases: ['render props', 'render props pattern'], description: 'コンポーネントがレンダリング内容を決定するためにpropとして関数を受け取るReactのパターン。ロジックを再利用しながら表示の柔軟性を持たせる。カスタムフックの登場で代替されることも多い。' },
  { term: '高階コンポーネント', aliases: ['hoc', 'higher-order component', 'higher order component'], description: 'コンポーネントを受け取り新しいコンポーネントを返すReactの設計パターン。共通の振る舞い（認証、ロギング等）を横断的に追加するために使われる。カスタムフックで代替されることが多い。' },
  { term: 'Server Actions', aliases: ['server actions', 'サーバーアクション', 'server action'], description: 'Next.js App Routerで導入されたサーバー側で実行される非同期関数。\'use server\'ディレクティブでマークしフォームやクライアントコードから直接呼び出せる。APIルートを別途作成せずにデータ変更を行える。' },
  { term: '部分的プリレンダリング', aliases: ['ppr', 'partial prerendering'], description: 'Next.jsのPPR（Partial Prerendering）機能。ページの静的な外枠を事前生成しSuspenseで囲んだ動的コンテンツをストリーミングで配信する。SSGとSSRの利点を組み合わせたハイブリッド手法。' },
  { term: '並列ルート', aliases: ['parallel routes'], description: 'Next.js App Routerの機能。@slotの命名規則で同一レイアウト内に複数のページを同時にレンダリングできる。ダッシュボードのタブ表示やモーダルの実装に活用される。' },
  { term: 'インターセプトルート', aliases: ['intercepting routes'], description: 'Next.js App Routerの機能。(..)記法で現在のレイアウトを保ちつつ別URLのルートをキャプチャし、モーダルやソフトナビゲーションを実現する。画像ギャラリーのモーダルプレビュー等で活用される。' },
  { term: 'ルートグループ', aliases: ['route groups'], description: 'Next.js App Routerの(folderName)記法によるフォルダ構造整理の仕組み。URLパスに影響せずルートを論理的にグループ化し、グループごとに異なるレイアウトを適用できる。' },
  { term: 'layout.tsx', aliases: ['レイアウトファイル', 'next.js layout'], description: 'Next.js App Routerで特定のルートセグメントとその子で共有されるUIを定義するファイル。ナビゲーション時に状態を保持したまま再レンダーせず、入れ子にして複数レイアウトを実現できる。' },
  { term: 'template.tsx', aliases: ['テンプレートファイル', 'next.js template'], description: 'Next.js App Routerでlayout.tsxに似た共有UIを定義するファイル。ナビゲーションのたびにコンポーネントの新しいインスタンスが生成されstateはリセットされる。アニメーションやページビューログに使われる。' },
  { term: 'Metadata API', aliases: ['metadata api', 'next.js metadata', 'generatemetadata'], description: 'Next.js App Routerが提供するHTMLメタデータ（title、OGP、canonical等）を型安全に生成するAPI。layout.tsxやpage.tsxからmetadataオブジェクトまたはgenerateMetadata関数をエクスポートして使用する。' },
  { term: 'Next.js App Router', aliases: ['next.js app router', 'appディレクトリ'], description: 'Next.js 13で導入されたappディレクトリベースの新しいルーティングシステム。React Server Components、Server Actions、Streaming SSRをネイティブサポートし、従来のPages Routerを置き換える。' },
  { term: 'バンドル分割', aliases: ['bundle splitting'], description: 'アプリケーションのJavaScriptバンドルを複数のファイルに分け、並列ダウンロードやキャッシュ効率を高める手法。ベンダーバンドルとアプリバンドルの分離が代表例。' },
  { term: 'Turbopack', aliases: ['turbopack'], description: 'Vercelが開発したRustベースの高速バンドラー。Next.js 13以降の開発サーバーで採用。webpackと比べてコールドスタートや変更検出が大幅に高速化され、大規模プロジェクトの開発体験を改善する。' },
  { term: 'webpack', description: 'JavaScriptエコシステムで長年標準として使われてきたモジュールバンドラー。JS・CSS・画像などあらゆるアセットを依存グラフとして解析しバンドルする。プラグインとローダーで高度にカスタマイズ可能。' },
  { term: 'Vite', aliases: ['vite'], description: 'ESモジュールのネイティブブラウザサポートを活用した高速な開発サーバーとビルドツール。開発時はバンドルレスで動作し、本番ビルドにはRollupを使用する。Vue・React・Svelteなど幅広いフレームワークに対応。' },
];
