// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: frontend (1/5)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // frontend (198), ux-design (101), css (97), typescript (95), mobile (91), javascript (84), fe-dev-management (52), fe-fundamentals (50), fe-architecture-os (50), fe-database (50), fe-network (50), fe-security (50), react (49), web (34), ui-design (18), ux (17), html (13), web-analytics (9), accessibility (6), UX (3), Frontend (2), Accessibility (2), ui_design (2)
  { term: '画面設計', aliases: ['screen design'], description: '画面の構成、表示項目、入力項目、操作方法などを定める設計です。基本設計では概略、詳細設計では項目単位の動きまで落とし込むことが多いです。' },
  { term: '画面遷移', aliases: ['screen transition'], description: 'どの画面からどの画面へ移るか、その操作条件は何かを整理したものです。利用者の操作導線を理解するうえで重要です。' },
  { term: '項目定義', aliases: ['field definition'], description: '項目名、意味、型、桁数、必須かどうか、入力制約などを定義したものです。画面項目やAPI項目の解釈ズレを防ぐ役割があります。' },
  { term: 'プロトタイプ', description: '実現性や使い勝手を早く確かめるための試作品です。仕様確定前の不確実性を下げるのに非常に有効です。' },
  { term: 'イミュータブルインフラ', description: '稼働中のサーバーを直接変更せず、新しい環境を作って置き換える考え方です。再現性と安全性が高まりやすくなります。' },
  { term: 'フロントエンド', description: '利用者が直接見る画面や、その動きを担う部分です。基本設計では画面要件として、詳細設計では具体挙動として扱われます。' },
  { term: 'フルスタック', description: 'フロントエンドからバックエンド、インフラまで広く扱えることを指します。範囲が広い分、設計のつながりを理解しやすい強みがあります。' },
  { term: 'HTML', aliases: ['html'], description: 'Webページの構造を表現するための言語です。見た目そのものではなく、見出しや段落、入力欄などの意味づけを担います。' },
  { term: 'CSS', aliases: ['css'], description: '見た目や配置、色、余白などを制御するための仕組みです。HTMLの構造と分離することで保守しやすくなります。' },
  { term: 'JavaScript', aliases: ['javascript'], description: 'Web画面に動きをつける代表的な言語です。入力制御、非同期通信、画面更新など多くの役割を担います。' },
  { term: 'React', aliases: ['react'], description: 'コンポーネント指向で画面を組み立てるための代表的なライブラリです。部品化しやすく、再利用性と状態管理が重要なテーマになります。' },
  { term: 'Vue', aliases: ['vue'], description: '比較的学びやすく、宣言的に画面を扱いやすいフレームワークです。小規模から中規模の業務画面でもよく使われます。' },
  { term: 'Angular', aliases: ['angular'], description: 'フル機能型のフロントエンドフレームワークです。規約が比較的強く、大規模で統一感を保ちたい場面に向きます。' },
  { term: 'Next.js', aliases: ['next.js'], description: 'Reactベースで、SSRやルーティングなどを扱いやすくしたフレームワークです。SEOや高速表示が必要なWebでよく使われます。' },
  { term: 'コンポーネント', description: '画面を構成する再利用可能な部品です。ボタン、入力欄、一覧、ダイアログなどを部品化すると保守しやすくなります。' },
  { term: 'Props', aliases: ['props'], description: '親コンポーネントから子コンポーネントへ渡すデータです。入力専用の性質を持つことで、画面の流れを理解しやすくなります。' },
  { term: 'レンダリング', description: 'データや状態を画面として描画することです。何が変わると再描画されるかを理解すると性能改善に役立ちます。' },
  { term: 'SSR', aliases: ['ssr'], description: 'Server Side Renderingの略で、サーバー側でHTMLを生成して返す方式です。初期表示やSEOに有利なことが多いです。' },
  { term: 'CSR', aliases: ['csr'], description: 'Client Side Renderingの略で、ブラウザ側で画面を組み立てる方式です。操作感がよい反面、初期表示やSEOでは工夫が必要です。' },
  { term: 'ハイドレーション', description: 'サーバーで描画された画面に、クライアント側の動きを結びつける処理です。SSR系フレームワークでは重要な概念です。' },
  { term: 'フォーム', description: '利用者が情報を入力して送信するための画面単位です。入力チェック、エラー表示、確認画面、二重送信防止など多くの設計要素が集まります。' },
  { term: '状態管理', description: '画面全体や複数部品で共有する状態をどう持つかという設計です。小さく保てば単純ですが、大きくなるほど方針が重要になります。' },
  { term: 'Redux', aliases: ['redux'], description: '状態管理の代表的なライブラリです。明示的で追跡しやすい一方、単純な画面では少し重く感じることもあります。' },
  { term: '楽観的更新', description: 'サーバーの成功を待たず、先に画面を更新して体感を良くする手法です。失敗時の巻き戻し設計が必要になります。' },
  { term: '悲観的更新', description: 'サーバー成功を確認してから画面へ反映する方法です。安全ですが、体感速度は落ちやすくなります。' },
  { term: 'WebSocket', aliases: ['websocket'], description: 'クライアントとサーバーが双方向で継続接続できる通信方式です。リアルタイム更新やチャット、監視画面と相性がよいです。' },
  { term: 'マルチパートフォーム', description: 'ファイルと通常項目を一緒に送るための送信形式です。アップロード実装ではよく使われます。' },
  { term: '画像最適化', description: '表示品質を保ちつつ、容量を減らすための工夫です。表示速度や通信量、モバイル体験に直結します。' },
  { term: 'アセット', description: '画像、CSS、JavaScript、フォントなど、画面を構成する静的資源です。配信方法やキャッシュ設計が表示性能に影響します。' },
  { term: 'アクセシビリティ対応', description: '多様な利用者が使いやすいように配慮することです。色だけに頼らない表示やキーボード操作対応などが代表例です。' },
  { term: 'レスポンシブ対応', description: '画面サイズに応じて表示を最適化することです。PC前提の業務画面でも、タブレットや高解像度端末を考慮すると役立ちます。' },
  { term: 'Swagger', aliases: ['swagger'], description: 'OpenAPI仕様を閲覧、試行しやすくするための周辺ツール群やUIを指すことが多いです。API利用者との認識合わせに役立ちます。' },
  { term: 'DTO', aliases: ['dto'], description: 'Data Transfer Objectの略で、画面やAPIとの受け渡し専用データ構造です。内部モデルと分けることで責務が整理しやすくなります。' },
  { term: '入力サニタイズ', description: '入力値から危険な内容や不要な形式を除去、整形することです。セキュリティと扱いやすさの両面で有効です。' },
  { term: 'ページング', description: '一覧データを分割して取得、表示する方法です。大量データでの応答性能や画面使い勝手に直結します。' },
  { term: 'ミニフィケーション', aliases: ['minification'], description: '不要な空白や名前を短縮してファイルサイズを削減する手法です。転送量の削減に役立ちます。' },
  { term: 'BI', aliases: ['bi'], description: 'Business Intelligenceの略で、データを見える化して意思決定に生かす仕組みや活動です。単なるグラフ表示ではなく、判断に使えることが重要です。' },
  { term: 'ダッシュボード', description: '重要指標を一覧できる画面です。見やすいだけでなく、何を判断するための画面かが明確である必要があります。' },
  { term: 'ペルソナ', description: '代表的な利用者像を具体的に描いた仮想人物です。極端に作り込みすぎると逆効果ですが、対象の理解をそろえるには有効です。' },
  { term: 'カスタマージャーニー', description: '利用者がサービスと接する流れを時系列で整理したものです。画面単位ではなく、体験全体で見ることで課題が見つかりやすくなります。' },
  { term: 'タッチポイント', description: '利用者とシステムやサービスが接触する場面です。Web画面だけでなく、メール、電話、店舗、帳票なども含まれます。' },
  { term: 'UXリサーチ', aliases: ['uxリサーチ'], description: '利用者の行動、感情、困りごとを調べる活動です。思い込みで設計せず、実態に基づいて改善するための基盤になります。' },
  { term: 'ファーストクリック分析', description: '利用者が最初にどこを押すかを見ることで、UIの分かりやすさを確かめる考え方です。最初の一歩がずれると、その後の操作も崩れやすくなります。' },
  { term: '誤操作率', description: '意図しない操作や間違った手順に入る割合です。UI改善の必要性を示す重要なヒントになります。' },
  { term: 'ナビゲーション設計', description: '利用者が迷わず目的の場所へたどり着けるようにする設計です。階層、メニュー名、導線の一貫性が重要になります。' },
  { term: '用語一貫性', description: '画面内や文書内で同じ意味を同じ言葉で表すことです。意味が同じなのに呼び方が違うと、利用者は強く混乱します。' },
  { term: 'プログレス表示', description: '処理の進み具合を見せる表示です。長い処理では、終わりが見えるだけで利用者の不安を大きく減らせます。' },
  { term: '確認ダイアログ', description: '削除や確定など重要操作の前に本当に実行するか確認する仕組みです。多すぎると逆に機械的に押されるだけになるため、使いどころが重要です。' },
  { term: '視線誘導', description: '利用者にどこから見てほしいかをレイアウトや強調で導くことです。重要情報が埋もれるのを防ぎます。' },
  { term: 'ホワイトスペース', description: '余白のことです。詰め込みすぎた画面より、適切な余白がある画面のほうが理解しやすいことが多いです。' },
  { term: 'フォーム最適化', description: '入力項目や順番、補助表示を改善して入力しやすくすることです。項目削減は最も効果の高い改善のひとつです。' },
  { term: '入力マスク', description: '電話番号や日付など、決まった形式の入力を支援する仕組みです。便利ですが、例外的な入力を阻害しない設計も必要です。' },
  { term: '全体エラー表示', description: '画面上部などでまとめてエラーを知らせる方式です。複数項目にまたがる問題や重大な問題を伝えるのに向いています。' },
  { term: 'フォーカス管理', description: 'キーボード操作時にどこへ移動するかを制御することです。ダイアログや動的更新画面では特に重要になります。' },
  { term: 'キーボードナビゲーション', description: 'マウスを使わずに操作できるようにする設計です。アクセシビリティだけでなく、効率的な業務操作にも役立ちます。' },
  { term: 'UIコンポーネントライブラリ', aliases: ['uiコンポーネントライブラリ'], description: '共通部品をまとめた再利用基盤です。各画面ごとに作り直さず、品質と速度を両立しやすくなります。' },
  { term: 'インタビューリサーチ', aliases: ['interview research'], description: 'ユーザーに直接話を聞いて文脈や理由を深く理解する手法です。数字では見えない本音や例外ケースを発見するのに効果的です。' },
  { term: 'サーベイリサーチ', aliases: ['survey research'], description: '多くの人から回答を収集してトレンドを把握する手法です。広く集めやすいですが、深い理由まで明らかになりにくいです。' },
  { term: 'エラー率', aliases: ['error rate'], description: '意図しない操作や誤ったパスをたどった割合のことです。UI改善の必要箇所を特定するための重要な指標です。' },
  { term: '情報アーキテクチャ', aliases: ['information architecture', 'ia'], description: '情報の整理・分類・見つけやすさをどう設計するかのことです。見た目より構造の明確さのほうが重要です。' },
  { term: 'エンプティステートデザイン', aliases: ['empty state design'], description: 'まだデータが存在しない状態での画面表示とユーザー誘導のデザインです。空画面こそ次に何をすればよいかを示す価値が最も高い場面です。' },
  { term: 'ローディングステート', aliases: ['loading state'], description: 'データ取得や処理中の表示状態のことです。何が起きているかわからない状態は、待つこと自体よりも大きなストレスを生みます。' },
  { term: 'プログレスインジケーター', aliases: ['progress indicator'], description: '処理がどこまで進んでいるかを示す表示のことです。長い処理でも、進捗が表示されるだけでユーザーの不安が大きく軽減されます。' },
  { term: 'インタラクション感覚', aliases: ['interaction feel'], description: 'ユーザーが操作する際に感じる満足感や自然さのことです。処理速度・応答性・文言・フローすべてが影響します。' },
  { term: '視覚的誘導', aliases: ['visual guidance'], description: 'レイアウトや強調によってユーザーの視線を誘導することです。重要な情報が埋もれることを防ぎます。' },
  { term: 'ヒックの法則', aliases: ['hick\'s law'], description: '選択肢が多いほど意思決定に時間がかかるという法則です。メニューや設定の過多を避けるのに役立ちます。' },
  { term: '視覚的階層', aliases: ['visual hierarchy'], description: '視覚的な重みで重要度を示すことです。フォントサイズ・色・余白・位置が主なツールです。' },
  { term: 'インプットマスク', aliases: ['input mask'], description: '電話番号や日付など固定フォーマットの入力を補助する仕組みです。便利ですが、正当なエッジケースの入力を阻害しないよう注意が必要です。' },
  { term: 'オートコンプリート', aliases: ['autocomplete'], description: '入力中に候補を提示して入力を補助する機能のことです。速度向上に役立ちますが、誤選択のリスクにも注意が必要です。' },
  { term: 'エラーサマリー表示', aliases: ['summary error display'], description: '画面上部にエラーをまとめて表示する方式のことです。複数フィールドにまたがる問題や重大な問題を伝えるのに適しています。' },
  { term: '二重送信防止', aliases: ['double submit prevention'], description: '複数回の送信が発火しないようにする仕組みのことです。データ整合性だけでなくユーザーの不安軽減にも役立ちます。' },
  { term: '認知的一貫性', aliases: ['cognitive consistency'], description: 'ユーザーの期待と画面の振る舞いが一致している状態のことです。自然に理解できるUIは学習コストが低くなります。' },
  { term: 'プログレッシブディスクロージャー', aliases: ['progressive disclosure'], description: '初心者が段階的に習熟できるようにする技法のことです。ガイド・ヒント・段階的な機能露出などが含まれます。' },
  { term: 'スタブデータ', description: 'テスト用に準備した固定応答や簡易データです。外部依存を減らして検証しやすくするために使われます。' },
  { term: 'ユーザビリティ評価', description: '使いやすさや理解しやすさを確認する評価です。仕様どおりでも使いにくいシステムは業務定着しにくくなります。' },
  { term: '入力禁止情報', description: 'AIへ送ってはいけない情報です。個人情報、未公開情報、秘密情報、認証情報などを明確に線引きする必要があります。' },
  { term: 'リスクレジスター', aliases: ['risk register'], description: '予想されるリスクとその対策・発生時対応を整理した一覧です。問題が起きてから慌てるのではなく、事前に備えるための実践的なツールです。' },
  { term: 'テスト自動化戦略', aliases: ['test automation strategy'], description: '何を自動化し何を手動のままにするかを定める方針です。自動化の対象・ツール・維持方法まで含めて計画することで信頼性が高まります。' },
  { term: 'ノンリピータブルリード', description: '同じ条件で読み直したのに、途中で他更新が入って結果が変わる現象です。画面表示と確定処理のズレにつながることがあります。' },
  { term: 'プラットフォームエンジニア', description: '開発者が安全かつ速く作業できる共通基盤を整える役割です。CI/CD、IaC、開発環境、運用基盤などを支えます。' },
  { term: 'プログレッシブエンハンスメント', description: 'まず基本機能を確実に動かし、その上で高度な体験を追加していく考え方です。環境差や端末差に強く、壊れにくい画面設計につながります。' },
  { term: 'モバイルファースト', description: '小さな画面を起点にUIを考え、必要に応じて大きな画面へ広げる設計思想です。情報の優先順位が明確になりやすい利点があります。' },
  { term: 'セマンティックHTML', aliases: ['セマンティックhtml'], description: '見た目ではなく意味に合ったHTML要素を使う考え方です。アクセシビリティ、保守性、検索性の面で大きな効果があります。' },
  { term: 'ARIA', aliases: ['aria'], description: '補助技術に意味や状態を正しく伝えるための属性群です。HTMLだけでは意味が足りない場面で補助的に使います。' },
  { term: 'ランドマーク領域', description: 'ヘッダー、メイン、ナビゲーションなど、ページの大きな意味的区画です。スクリーンリーダー利用者が素早く移動しやすくなります。' },
  { term: 'スキップリンク', description: '繰り返し表示されるメニューを飛ばして本文へ移動できるリンクです。キーボード操作や読み上げ利用者に有効です。' },
  { term: 'フォーカストラップ', description: 'ダイアログ内などで、フォーカス移動をその領域に閉じ込める制御です。モーダル操作時の迷子を防ぐために重要です。' },
  { term: 'キーボードショートカット', description: 'キーボード操作で素早く機能実行できる仕組みです。高頻度業務では、生産性向上に大きく効くことがあります。' },
  { term: 'デバウンス', description: '入力が落ち着くまで処理実行を待つ制御です。検索候補表示やリアルタイム入力検証で、無駄な処理を減らすのに役立ちます。' },
  { term: 'イベントデリゲーション', description: '個々の要素ではなく親要素でイベントを受ける設計です。大量要素がある画面でも管理しやすくなります。' },
  { term: '仮想DOM', aliases: ['仮想dom'], description: '画面変更を効率化するため、実DOMの前に仮想的な構造を使う考え方です。差分更新をしやすくし、描画効率向上に寄与します。' },
  { term: 'ハイドレーションミスマッチ', description: 'サーバー描画結果とクライアント描画結果が一致せず、警告や表示不整合が出る状態です。SSR利用時の重要な注意点です。' },
  { term: 'コード分割', description: '必要な部分だけ読み込むようにコードを分けることです。初期表示を軽くしやすくなります。' },
  { term: 'クリティカルCSS', aliases: ['クリティカルcss'], description: '初期表示に必要な最小限のCSSだけを先に適用する考え方です。描画開始を早めるのに役立ちます。' },
  { term: 'キャッシュバスティング', description: '更新後に古い資産が使われないよう、URLや識別子を変えて再取得させる方法です。静的ファイル更新で重要です。' },
  { term: '静的資産フィンガープリント', description: 'ファイル内容に応じたハッシュ値を名前へ付ける方式です。キャッシュ制御と更新反映を両立しやすくなります。' },
  { term: 'サービスワーカー', description: 'ブラウザ外側で動き、キャッシュやオフライン制御を支援する仕組みです。PWAや高速化で重要な役割を持ちます。' },
  { term: 'PWA', aliases: ['pwa'], description: 'Progressive Web Appの略で、Webでありながらアプリのような体験を提供する考え方です。オフライン利用やホーム画面追加と相性があります。' },
  { term: 'オフラインファースト', description: '通信できない前提でも一定利用できるよう設計する考え方です。現場利用や不安定回線の業務で有効です。' },
  { term: 'バックグラウンド同期', description: 'オフライン時に保留した処理を、通信回復後に送信する仕組みです。利用者体験を損なわずに整合を取りやすくします。' },
  { term: 'Webマニフェスト', aliases: ['webマニフェスト'], description: 'アプリ名、アイコン、起動設定などを定義するファイルです。PWA体験の基盤として使われます。' },
  { term: 'ローカルストレージ', description: 'ブラウザに永続的に保存できる簡易保存領域です。便利ですが、機密情報の保存先としては慎重な判断が必要です。' },
  { term: 'セッションストレージ', description: 'タブ単位で一時保存される領域です。画面遷移中の一時保持には便利ですが、長期保存には向きません。' },
  { term: 'IndexedDB', aliases: ['indexeddb'], description: 'ブラウザ内で比較的大きな構造化データを保存できる仕組みです。オフライン対応やローカルキャッシュで力を発揮します。' },
  { term: 'アクセシビリティツリー', description: '補助技術向けに構築される、意味ベースの画面構造です。見た目では問題なくても、このツリーが壊れていると使いにくくなります。' },
  { term: '読み上げ意味付け', description: 'スクリーンリーダーに正しい意味で伝わるよう要素を設計することです。見出し、ボタン、ラベルの正確さが重要になります。' },
  { term: 'autocomplete属性', description: 'ブラウザへ入力内容の種類を伝える属性です。自動入力の精度向上や、入力負荷軽減に役立ちます。' },
  { term: 'inputmode属性', description: '数字やメールなど、入力に適したキーボードを出しやすくする属性です。スマートフォン入力体験に大きく効きます。' },
  { term: 'フォーム保持', description: '入力途中の内容を失わないよう保存しておく考え方です。長い申請画面や不安定通信下で有効です。' },
  { term: 'クライアントサイドルーティング', description: 'ブラウザ側で画面遷移を制御する方式です。体感速度は上がりやすいですが、URL設計や初期読込設計が重要になります。' },
  { term: 'サーバーコンポーネント', description: '一部のUI構築をサーバー側で行う考え方です。表示効率やデータ取得の責務分離に役立つことがあります。' },
  { term: 'エッジレンダリング', description: '利用者に近い拠点で画面生成や処理を行う方式です。遅延低減に有効ですが、状態管理との整合が課題になります。' },
  { term: 'ストリーミングSSR', aliases: ['ストリーミングssr'], description: 'サーバー描画結果を完成待ちせず、順次返す方式です。初期表示体感を改善しやすくなります。' },
  { term: '空状態CTA', aliases: ['空状態cta'], description: 'データがない初期状態で、次に取るべき行動を案内する設計です。空画面を放置しないことが利用定着に効きます。' },
  { term: '機能発見性', description: '利用者が必要な機能を自然に見つけられる度合いです。高機能でも見つからなければ存在しないのと同じです。' },
  { term: 'エラー回復UX', aliases: ['エラー回復ux'], description: '問題発生時に、利用者が迷わず元の流れへ戻れるようにする設計です。失敗時こそ体験品質の差が出ます。' },
  { term: 'Undoスナックバー', aliases: ['undoスナックバー'], description: '操作後に短時間だけ取り消し機会を与える通知UIです。誤操作対策として確認ダイアログの代替になることがあります。' },
  { term: '楽観的UI', aliases: ['楽観的ui'], description: 'サーバー完了を待たず、先に成功したように見せるUI設計です。速度感は上がりますが、失敗時の巻き戻しが要ります。' },
  { term: '悲観的UI', aliases: ['悲観的ui'], description: '実際の成功確認後にのみ画面反映する設計です。安全ですが、待ち時間をどう見せるかが課題になります。' },
  { term: '遅延ハイドレーション', description: '画面の一部について、必要になるまでクライアント側の動作付与を遅らせる考え方です。初期表示軽量化に使われます。' },
  { term: 'ランドマークリージョン', aliases: ['landmark regions'], description: 'ヘッダー・メイン・ナビゲーションなど、ページの主要なセマンティックセクションです。スクリーンリーダーユーザーがセクション間を素早く移動できるようにします。' },
  { term: '静的アセットフィンガープリンティング', aliases: ['static asset fingerprinting'], description: 'コンテンツに基づくハッシュ値をファイル名に付加する仕組みです。キャッシュ制御と更新伝播のバランスを取りやすくします。' },
  { term: 'スクリーンリーダーセマンティクス', aliases: ['screen reader semantics'], description: 'スクリーンリーダーが正しい意味を伝えられるよう要素を設計することです。見出し・ボタン・ラベルの正確さが重要です。' },
  { term: 'フォームパーシスタンス', aliases: ['form persistence'], description: '入力中のデータを保存してデータ損失を防ぐ実践です。長い申請フォームや不安定なネットワーク環境で効果的です。' },
  { term: '機能の発見可能性', aliases: ['feature discoverability'], description: 'ユーザーが必要な機能を自然に見つけられる度合いです。どれだけ強力な機能でも、ユーザーが見つけられなければ存在しないも同然です。' },
  { term: 'エラーリカバリーUX', aliases: ['エラーリカバリーux', 'error recovery ux'], description: '問題が起きたときにユーザーが混乱せず通常フローへ戻れるよう支援するデザインです。障害発生時に体験品質の差が最も現れます。' },
  { term: 'モバイルアプリ', aliases: ['mobile app'], description: 'スマートフォンやタブレットで動くアプリケーションです。Webより端末機能に近く、現場利用や外出先利用との相性が高いです。' },
  { term: 'ネイティブアプリ', aliases: ['native app'], description: 'iOSやAndroid向けにそれぞれ専用実装されたアプリです。性能や端末連携に強い一方、開発と保守が二重化しやすいです。' },
  { term: 'ハイブリッドアプリ', aliases: ['hybrid app'], description: 'Web技術を土台にしつつ、アプリとして配布する形式です。共通化しやすい反面、複雑な端末機能では制約が出ることがあります。' },
  { term: 'クロスプラットフォーム開発', aliases: ['cross-platform development'], description: '一つのコードベースから複数OS向けアプリを作る考え方です。速度と共通化に強いですが、OS差異の吸収設計が重要です。' },
  { term: 'React Native', aliases: ['react native'], description: 'JavaScriptやTypeScriptでモバイルアプリを作るための代表的な基盤です。Web知識を活かしやすい一方、ネイティブ理解も必要になります。' },
  { term: 'Flutter', aliases: ['flutter'], description: 'Google系のクロスプラットフォーム開発基盤です。描画一貫性に強く、UI表現の自由度も高いです。' },
  { term: 'Swift', aliases: ['swift'], description: 'Apple系アプリ開発で主に使われる言語です。iOSネイティブ開発の中心的な選択肢です。' },
  { term: 'Kotlin', aliases: ['kotlin'], description: 'Android開発で主に使われる言語です。簡潔で安全性の高い記法が特徴です。' },
  { term: '端末最適化', aliases: ['device optimization'], description: '画面サイズ、性能、通信環境、操作方法に応じて体験を整えることです。PC向け前提の設計をそのまま移すと使いにくくなりやすいです。' },
  { term: '端末機能連携', aliases: ['device feature integration'], description: 'カメラ、GPS、通知、ストレージ、指紋認証などをアプリから利用することです。便利ですが、権限管理とプライバシー配慮が必要です。' },
  { term: 'プッシュ通知', aliases: ['push notification'], description: 'アプリを開いていなくても利用者へ通知を届ける仕組みです。即時性に強いですが、出しすぎると無視されやすくなります。' },
  { term: 'ローカル通知', aliases: ['local notification'], description: '端末内でスケジュールや条件に応じて出す通知です。サーバー依存を減らせますが、端末側の状態に左右されます。' },
  { term: '通知許諾', aliases: ['notification permission'], description: '利用者が通知を受け取ることに同意した状態です。通知の価値を感じてもらえないと、初回で拒否されやすいです。' },
  { term: 'バックグラウンド実行', aliases: ['background execution'], description: 'アプリが前面にない状態でも一定処理を続けることです。便利ですが、OS制約とバッテリー消費に注意が必要です。' },
  { term: 'フォアグラウンド処理', aliases: ['foreground processing'], description: '利用者がアプリを見て操作している前面状態での処理です。応答性や体感速度が強く求められます。' },
  { term: 'バッテリー最適化', aliases: ['battery optimization'], description: '端末の電力消費を抑えながら必要機能を維持する設計です。バックグラウンド処理や位置情報利用で特に重要です。' },
  { term: 'オフラインキャッシュ', aliases: ['offline cache'], description: '通信できないときにも一定情報を使えるよう端末に保持する仕組みです。現場作業や移動中利用で有効です。' },
  { term: '同期競合', aliases: ['sync conflict'], description: 'オフライン中の変更とサーバー側変更がぶつかる状態です。どちらを優先するかの設計が必要です。' },
  { term: 'ローカルファースト', aliases: ['local-first'], description: 'まず端末側で素早く扱い、その後で同期を考える設計思想です。体感はよくなりますが、整合性設計が難しくなります。' },
  { term: 'デバイスバインディング', aliases: ['device binding'], description: '特定利用者と特定端末を結びつけて管理することです。不正利用防止や本人性強化に使われます。' },
  { term: 'MAM', aliases: ['mam'], description: 'Mobile Application Managementの略で、端末全体ではなくアプリ単位で管理する考え方です。BYOD環境でも使いやすいことがあります。' },
  { term: 'BYOD', aliases: ['byod'], description: '個人所有端末を業務利用することです。利便性は高い一方、データ分離と統制設計が重要になります。' },
  { term: '端末暗号化', aliases: ['device encryption'], description: '端末内保存データを暗号化することです。紛失や盗難時の被害軽減に有効です。' },
  { term: 'アプリサンドボックス', aliases: ['app sandbox'], description: 'アプリごとにアクセス範囲を分離する仕組みです。他アプリやシステム全体への影響を抑えやすくなります。' },
  { term: 'ディープリンク', aliases: ['deep link'], description: 'アプリ内の特定画面や状態へ直接遷移させるリンクです。通知やメールから目的画面へすぐ移動させたいときに役立ちます。' },
  { term: 'ユニバーサルリンク', aliases: ['universal link'], description: 'Webリンクから適切にアプリ起動やWeb表示へつなぐ仕組みです。体験と導線を統一しやすくなります。' },
  { term: 'アプリ内ブラウザ', aliases: ['in-app browser'], description: 'アプリの中でWebページを表示する機能です。素早く導入しやすい一方、認証や操作感には注意が必要です。' },
  { term: 'ネイティブブリッジ', aliases: ['native bridge'], description: 'Web側と端末ネイティブ機能をつなぐ仕組みです。ハイブリッド構成で重要な接点になります。' },
  { term: 'ストア配布', aliases: ['store distribution'], description: 'App StoreやGoogle Play経由でアプリを配布することです。審査や公開手順を考慮したリリース運用が必要です。' },
  { term: '企業内配布', aliases: ['enterprise distribution'], description: 'ストアではなく組織内向けにアプリを配布する方法です。業務専用アプリで使われることがあります。' },
  { term: 'アプリ審査', aliases: ['app review'], description: 'ストア側がアプリ内容やポリシー適合性を確認する手続きです。技術品質だけでなく、規約理解も重要です。' },
  { term: 'バージョン審査待ち', aliases: ['version review pending'], description: '申請後に公開待ちとなっている状態です。緊急修正でも即公開できるとは限らない点に注意が必要です。' },
  { term: '段階公開', aliases: ['staged rollout'], description: '一部利用者から順に新バージョンを配る方式です。問題を限定範囲で見つけやすくなります。' },
  { term: '強制アップデート', aliases: ['forced update'], description: '古い版の利用を止め、新版更新を必須にする運用です。重大バグやセキュリティ対応で使われます。' },
  { term: '互換版維持', aliases: ['backward compatibility maintenance'], description: '旧版利用者のため、しばらく後方互換を保つことです。更新率が低い現場アプリで重要になることがあります。' },
  { term: 'クラッシュレポート', aliases: ['crash report'], description: 'アプリ異常終了時の状況を収集する仕組みです。端末依存の不具合解析に有効です。' },
  { term: 'ANR', aliases: ['anr'], description: 'Androidで応答なし状態になる問題です。見た目は落ちていなくても、利用者体験は大きく悪化します。' },
  { term: 'アプリフリーズ', aliases: ['app freeze'], description: 'アプリが操作不能になる状態です。クラッシュより原因が見えにくいこともあり、監視設計が重要です。' },
  { term: 'クラッシュフリー率', aliases: ['crash-free rate'], description: '異常終了せずに使えたセッション割合です。モバイル品質を見る代表指標の一つです。' },
  { term: '端末断片化', aliases: ['device fragmentation'], description: 'OS版、画面サイズ、メーカー差異が多く、挙動がばらつきやすい状態です。テスト戦略へ大きく影響します。' },
  { term: 'サポートOS範囲', aliases: ['サポートos範囲', 'supported os range'], description: '対応するOSバージョン範囲です。広げるほど利用者は増えますが、開発と検証負荷も増えます。' },
  { term: '端末テストマトリクス', aliases: ['device test matrix'], description: 'どの端末、OS、画面サイズで確認するかを整理した表です。闇雲に増やさず、利用実態に沿って絞ることが重要です。' },
  { term: 'エミュレータ検証', aliases: ['emulator testing'], description: '仮想端末上で行う確認です。初期検証には便利ですが、実機特有の問題は見落としやすいです。' },
  { term: '実機検証', aliases: ['real device testing'], description: '実際の端末で行う確認です。性能、通知、カメラ、センサー周りでは特に重要です。' },
  { term: 'リッチインタラクション', aliases: ['rich interaction'], description: 'アニメーションやジェスチャーを含む高密度な操作体験です。見た目のよさだけでなく、誤操作防止との両立が必要です。' },
  { term: 'ジェスチャーナビゲーション', aliases: ['gesture navigation'], description: 'スワイプやピンチなどの操作で画面移動や機能実行する設計です。自然ですが、発見性が低くなりやすいです。' },
  { term: 'ハプティクス', aliases: ['haptics'], description: '振動など触覚フィードバックを使う表現です。操作結果の即時理解を助けることがあります。' },
  { term: 'コンテキスト保持', aliases: ['context preservation'], description: '画面遷移や再起動後も、作業途中の状態を失わないようにすることです。業務中断の多い現場では特に価値があります。' },
  { term: 'モバイル利用分析', aliases: ['mobile usage analytics'], description: '端末種別、通信状況、利用時間帯、操作傾向を分析することです。PCとは異なる使われ方を前提に改善しやすくなります。' },
  { term: 'React (library)', aliases: ['react (library)'], description: 'コンポーネントで UI を構築するためのライブラリです。Hooks や Components を中心に構成されています。' },
  { term: 'component', description: 'React で UI を構成する再利用可能な単位です。関数コンポーネントが中心です。' },
  { term: 'props (React)', aliases: ['props (react)'], description: '親コンポーネントから子コンポーネントへ渡す読み取り専用の入力です。' },
  { term: 'children prop', description: 'JSX をネストしたときに渡される特別な props です。' },
  { term: 'state (React)', aliases: ['state (react)'], description: 'コンポーネントがレンダー間で覚えておく内部データです。props と違いコンポーネント自身に属します。' },
  { term: 'Hook (React)', aliases: ['hook (react)'], description: 'React の状態や副作用などの機能を関数コンポーネントへ持ち込むための仕組みです。通常 use で始まる名前を持ちます。' },
  { term: 'Rules of Hooks', aliases: ['rules of hooks'], description: 'Hooks はトップレベルで、React 関数の中からだけ呼ぶべきというルールです。' },
  { term: 'top-level Hook call', aliases: ['top-level hook call'], description: 'Hook を条件分岐やループ内ではなく、コンポーネント本体のトップレベルで呼ぶことです。' },
  { term: 'custom Hook', aliases: ['custom hook'], description: '複数コンポーネントで再利用したい Hook ロジックを関数化したものです。' },
  { term: 'useState', aliases: ['usestate'], description: 'コンポーネントへ state 変数を追加する React Hook です。' },
  { term: 'state setter', description: 'useState が返す、state を更新して再レンダーを起こす関数です。' },
  { term: 'state is private to the component', description: 'React の state は、その state を宣言したコンポーネントに属し、親から直接変更はできません。' },
  { term: 'lifting state up', description: '複数コンポーネントで状態を共有したいとき、共通の親へ state を持ち上げる設計です。' },
  { term: 'useEffect', aliases: ['useeffect'], description: '外部システムとの同期や副作用処理を記述する React Hook です。' },
  { term: 'effect setup', description: 'useEffect 内で行う初期化や接続処理です。必要に応じて cleanup を返せます。' },
  { term: 'effect cleanup', description: 'useEffect が返す後始末関数です。接続解除やイベント解除などに使います。' },
  { term: 'dependency array', description: 'useEffect、useMemo、useCallback などで依存値を指定する配列です。' },
  { term: 'external system synchronization', description: 'useEffect の代表用途で、React 外のシステムと状態を合わせることです。' },
  { term: 'useMemo', aliases: ['usememo'], description: '再レンダー間で計算結果をキャッシュする React Hook です。主に性能最適化に使います。' },
  { term: 'useCallback', aliases: ['usecallback'], description: '再レンダー間で関数自体をキャッシュする React Hook です。性能最適化目的で使います。' },
  { term: 'memoization', description: '同じ条件なら前回結果を再利用する最適化手法です。useMemo と useCallback が代表です。' },
  { term: 'performance optimization', description: 'React 公式では useMemo や useCallback を意味論ではなく最適化のために使うと説明しています。' },
  { term: 'createContext', aliases: ['createcontext'], description: 'コンポーネントツリーへ深く値を渡すための context を作る React API です。' },
  { term: 'context object', description: 'createContext が返す、提供と参照のためのコンテキスト表現です。' },
  { term: 'provider', description: 'context 値を子孫へ配るためのコンポーネントです。React 19 では SomeContext 自体を provider として使えます。' },
  { term: 'consumer', description: 'Hook 登場前からある、context 値を読むための古い方式です。新規コードでは useContext が推奨されます。' },
  { term: 'useContext', aliases: ['usecontext'], description: '最も近い provider の context 値を読み取り、変化へ追従する React Hook です。' },
  { term: 'defaultValue in context', aliases: ['defaultvalue in context'], description: '対応する provider が存在しない場合にだけ使われる context の既定値です。' },
  { term: 'context re-render propagation', description: 'provider の value が変わると、それを読む子コンポーネント群が再レンダーされる挙動です。' },
  { term: 'memo', description: '同じ props なら再レンダーを省略できる React API です。useMemo や useCallback と組み合わせて使うことがあります。' },
  { term: 'lazy', description: 'コンポーネントコードを初回レンダー時まで遅延読み込みする React API です。' },
  { term: 'Suspense', aliases: ['suspense'], description: '非同期な読み込み待ちの間に fallback UI を出すための React 機能です。Next.js App Router とも深く関わります。' },
  { term: 'startTransition', aliases: ['starttransition'], description: '非緊急な state 更新としてマークする React API です。UI 応答性改善に使われます。' },
  { term: 'use', description: 'Promise や context のような resource をレンダー中に読むための React API です。React 19 文脈で重要です。' },
  { term: 'resource reading', description: 'use を使って Promise や context などの resource を読むことです。' },
  { term: 'useActionState', aliases: ['useactionstate'], description: '副作用を伴う Action と state 更新を組み合わせて扱う React Hook です。' },
  { term: 'useFormStatus', aliases: ['useformstatus'], description: '直近の form submit 状態を取得する React DOM Hook です。送信中表示などに使います。' },
  { term: 'JSX', aliases: ['jsx'], description: 'React コンポーネントの UI を記述するための構文です。props や children の扱いと密接です。' },
  { term: 'props are read-only', description: 'React 公式では props は読み取り専用のスナップショットとして扱うべきと説明されています。' },
  { term: 'component memory', description: 'React 公式で state を説明するときに使われる比喩で、コンポーネントがレンダー間で覚える情報を指します。' },
  { term: 'state updater function', description: '前の state をもとに次の state を計算するために setState へ渡せる関数形式です。' },
  { term: 'Strict Mode behavior', aliases: ['strict mode behavior'], description: 'React 開発時には useState 初期化関数や useEffect setup/cleanup が追加実行されることがあります。' },
  { term: 'effect dependency correctness', description: 'Effect が依存値を正しく宣言していることです。React では dependencies を省略しすぎると不整合が起きやすいです。' },
  { term: 'unnecessary effect', description: '外部システムと同期していないのに useEffect を使うことです。React 公式では不要な Effect を避けるよう案内しています。' },
  { term: 'context fallback', description: 'provider が存在しないときに defaultValue を使う挙動です。' },
  { term: 'custom Hook composition', aliases: ['custom hook composition'], description: 'custom Hook の中から別の Hook を呼んでロジックを組み立てることです。' },
  { term: 'React Compiler note', aliases: ['react compiler note'], description: 'React 公式では useMemo の説明で React Compiler が値や関数を自動メモ化できる旨に触れています。' },
  { term: 'component identity', description: 'React が Hook state を対応づける際に重要な概念で、同じ tree 上の位置関係に結びつきます。' },
  { term: 'state sharing via common parent', description: '複数子の state を同期したいとき、最も近い共通親へ state を持たせるやり方です。' },
  { term: 'SPA', aliases: ['spa', 'single page application'], description: '画面遷移のたびに全面再読込せず、動的に表示更新するWebアプリ方式。' },
  { term: 'ページタイトル', description: 'ページや画面に付けられた名称。' },
  { term: '画面クラス', description: 'どの画面種類に属するかを表す分類情報。' },
  { term: '閲覧数', description: 'ページや画面が表示された回数。' },
  { term: 'アクティブユーザー', description: '実際に利用行動があった利用者数。' },
  { term: 'アクティブユーザーあたりの閲覧数', description: '1人の利用者が平均して何回見たかを表す指標。' },
  { term: '平均エンゲージメント時間', description: '1人あたり平均でどれくらい操作・滞在したかの時間。' },
  { term: 'イベント数', description: 'クリックや送信などの操作発生数。' },
  { term: '重要イベント', description: '成果として特に重要と定義されたイベント。' },
  { term: '総収益', description: 'その期間に発生した売上や収益の合計。' },
  { term: 'Cookie', aliases: ['cookie'], description: 'ブラウザ側に保存される小さな状態情報。' },
  { term: 'sessionStorage', aliases: ['sessionstorage'], description: 'ブラウザのタブ単位で保持される一時保存領域。' },
  { term: 'URL', aliases: ['url', 'uniform resource locator', 'ウェブアドレス'], description: 'Uniform Resource Locatorの略。インターネット上のWebページやファイルの場所を示す文字列。「https://www.example.com/page」のような形式。' },
  { term: 'URI', aliases: ['uri', 'uniform resource identifier'], description: 'Uniform Resource Identifierの略。インターネット上のリソースを一意に識別する文字列。URLはURIの一種。APIでリソースの場所を示す際に使う。' },
  { term: 'Webサイト', aliases: ['webサイト', 'website', 'ウェブサイト', 'ホームページ'], description: 'インターネット上で公開されているWebページの集まり。企業の公式サイト、ニュースサイト、ECサイトなどがある。ブラウザでURLを入力してアクセスする。' },
  { term: 'Webアプリ', aliases: ['webアプリ', 'web application', 'webアプリケーション', 'ウェブアプリ'], description: 'Webブラウザ上で動作するアプリケーション。インストール不要でURLにアクセスするだけで使える。GoogleスプレッドシートやSlackなどが代表例。' },
  { term: 'ブラウザ', aliases: ['browser', 'webブラウザ', 'web browser'], description: 'Webページを閲覧するためのソフトウェア。ChromeやSafari、Firefoxが代表的。URLを入力してWebサーバーにアクセスし、受け取ったHTMLを画面に表示する。' },
  { term: 'セッション', aliases: ['session'], description: 'ユーザーがWebサイトにアクセスしてから離れるまでの一連のやりとり。ログイン状態の維持などに使われる。セッションIDというIDで管理される。' },
  { term: 'Webサーバー', aliases: ['webサーバー', 'web server', 'webサーバ', 'apache'], description: 'Webページのデータを保存し、ブラウザからのリクエストに応じてHTMLやファイルを返すコンピューター（またはソフトウェア）。ApacheやNginxが有名。' },
  { term: 'ワイヤーフレーム', aliases: ['wireframe'], description: '画面レイアウトをシンプルな線や図形で表した設計図。色やデザインを省き、どこに何の要素を置くかを示す。Webサイトやアプリの設計初期段階で作成する。' },
  { term: '帳票', aliases: ['form', 'report', '帳票設計'], description: '業務で使用する書類や印刷物の総称。請求書、注文書、報告書など。システムから自動生成される帳票をシステム帳票と呼ぶ。帳票設計書で定義する。' },
  { term: 'バッチ処理', aliases: ['batch processing', 'バッチ', '一括処理'], description: '大量のデータを一括して処理する方式。夜間や定時に自動実行されることが多い。「毎日深夜2時に売上データを集計する」などがバッチ処理の例。' },
  { term: 'IF設計書', aliases: ['if設計書', 'インターフェース設計書', '連携設計書'], description: 'システム間のインターフェース（連携）を定義した設計書。連携するシステム名、データ形式、ファイルレイアウト、タイミングなどを記載する。' },
  { term: '項目定義書', aliases: ['フィールド定義書', '項目仕様書'], description: '画面や帳票、DBの各項目（フィールド）の定義を記載したドキュメント。項目名、データ型、桁数、必須/任意、入力チェックルールなどを定義する。' },
  { term: 'レイアウト', description: '画面や帳票上で要素をどこにどのように配置するかの設計。「ヘッダーは上部、フッターは下部、メニューは左側」のように、位置・大きさ・並びを定義する。' },
  { term: '入力チェック仕様', aliases: ['入力バリデーション仕様', 'チェック仕様'], description: 'ユーザーが入力するデータの正しさを検証するルールを定義したもの。「電話番号は数字のみ10〜11桁」「必須項目が空白の場合はエラー」などを定義する。' },
];
