// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: frontend (4/5)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_004: ReadonlyArray<GlossaryEntry> = [
  { term: 'WebView', aliases: ['webview'], description: 'ネイティブアプリ内でウェブコンテンツ（HTML/CSS/JS）を表示する組み込みブラウザコンポーネント。iOSはWKWebView、AndroidはAndroid WebViewを提供し、ハイブリッドアプリの基盤となる。' },
  { term: 'Capacitor', aliases: ['capacitor'], description: 'IonicチームがApache Cordovaの後継として開発したクロスプラットフォームアプリ構築ツール。WebViewベースでiOS・Android・Webアプリを一つのコードベースから生成しネイティブAPIにアクセスできる。' },
  { term: 'Ionic', aliases: ['ionic'], description: 'Angular・React・Vueと組み合わせて使えるモバイルアプリUIコンポーネントライブラリ兼フレームワーク。Capacitorと連携しiOS・Android向けのネイティブアプリをWeb技術で構築できる。' },
  { term: 'Expo', aliases: ['expo'], description: 'React Nativeの開発を簡素化するプラットフォームとツールセット。開発サーバー、OTAアップデート、EAS Build（クラウドビルド）を提供し、ネイティブ設定なしに始められる開発環境。' },
  { term: 'アプリ内課金', aliases: ['in-app purchase', 'iap'], description: 'モバイルアプリ内でユーザーが追加コンテンツや機能、サブスクリプションを購入できる仕組み。App StoreやGoogle Playが提供するAPIを通じて決済し、プラットフォームが手数料を徴収する。' },
  { term: 'コードサイニング', aliases: ['code signing'], description: 'アプリの開発者を証明し改ざんを検知するためにデジタル証明書で署名する仕組み。iOSではProvisioning Profileと証明書、AndroidではKeystoreを使い、配布・公開に必須のプロセス。' },
  { term: 'TestFlight', aliases: ['testflight'], description: 'AppleのiOSアプリベータテストサービス。App Store Connect経由で最大10,000人のテスターにベータ版を配信でき、本番リリース前のフィードバック収集とクラッシュ確認に広く使われる。' },
  { term: 'Crashlytics', aliases: ['crashlytics'], description: 'Firebase（旧Fabric）のモバイルクラッシュレポートサービス。アプリのクラッシュをリアルタイムに収集・分類し、スタックトレースとデバイス情報を提供して問題の特定と解決を支援する。' },
  { term: 'ビルドフレーバー', aliases: ['build flavor', 'product flavor'], description: '同一コードベースから開発版・ステージング版・本番版など異なる設定のアプリバリアントを生成する仕組み。AndroidのGradle設定やiOSのXcode Schemeで管理される開発プラクティス。' },
  { term: 'Swift Concurrency', aliases: ['swift concurrency', 'async/await swift', 'structured concurrency'], description: 'Swift 5.5で導入された構造化並行処理モデル。asyncキーワードで非同期関数を定義しawaitで呼び出すことでコールバックネストなしに非同期処理を直線的に記述できる公式機能。' },
  { term: 'ARKit', aliases: ['arkit'], description: 'AppleのiOS向け拡張現実フレームワーク。カメラとモーションセンサーで現実空間を認識し、3Dオブジェクトの配置、顔トラッキング、LiDARスキャンなど高度なAR体験を構築できる。' },
  { term: 'ARCore', aliases: ['arcore'], description: 'GoogleのAndroid向け拡張現実プラットフォーム。環境認識（平面・光源）、モーショントラッキング、オクルージョンをサポートし、SceneformやWebARでARアプリを構築できる。' },
  { term: 'ML Kit', aliases: ['ml kit', 'mlkit', 'firebase ml'], description: 'Googleのモバイル向け機械学習SDKでFirebaseの一部。テキスト認識、顔検出、バーコードスキャン、翻訳、ポーズ検出などの機能をAndroid・iOS上でオンデバイス実行できる。' },
  { term: 'Create ML', aliases: ['create ml'], description: 'Appleが提供するmacOS向け機械学習モデル作成ツール。コードなしのGUIでも画像分類・テキスト分類・物体検出のモデルを学習でき、Core MLフォーマットで出力しiOSアプリに組み込める。' },
  { term: 'Core ML', aliases: ['core ml'], description: 'AppleのiOS・macOS向けオンデバイス機械学習フレームワーク。ONNX・TensorFlow・PyTorchモデルをCore MLフォーマットに変換してiOSデバイス上でGPUやNeural Engine活用し効率的に推論する。' },
  { term: 'WidgetKit', aliases: ['widgetkit'], description: 'AppleのiOSホーム画面ウィジェット構築フレームワーク。SwiftUIで記述したウィジェットをタイムラインエントリで更新し、ホーム画面やLock Screenでユーザーが情報を素早く確認できる。' },
  { term: 'WorkManager', aliases: ['workmanager'], description: 'AndroidのバックグラウンドタスクスケジューリングAPI。制約条件（ネットワーク・充電状態など）を設定してバックグラウンド処理を信頼性高く実行でき、Dozeモード下でも動作する。' },
  { term: 'Room', aliases: ['room', 'room persistence library'], description: 'AndroidのSQLiteラッパーライブラリでJetpackの一部。アノテーションでエンティティ・DAO・データベースを定義し、コンパイル時に検証されたSQL操作を型安全に実行できる永続化ライブラリ。' },
  { term: 'Hilt', aliases: ['hilt'], description: 'AndroidのDagger2ベースの依存性注入フレームワークでJetpackの一部。コンポーネントのスコープとライフサイクル管理を簡素化し、ViewModelやRepositoryへのインジェクションを容易にする。' },
  { term: 'Navigation Component', aliases: ['navigation component', 'jetpack navigation'], description: 'AndroidのJetpackライブラリで画面遷移を宣言的に管理する。ナビゲーショングラフでルートを定義し、バックスタック管理、ディープリンク処理、SafeArgsで型安全な引数渡しを実現する。' },
  { term: 'Combine', aliases: ['combine'], description: 'Appleが提供するSwift向けリアクティブプログラミングフレームワーク。PublisherとSubscriberの概念でイベントストリームや非同期データフローを宣言的に扱い、SwiftUIと高い親和性を持つ。' },
  { term: 'SwiftData', aliases: ['swiftdata'], description: 'iOS 17でAppleが導入したSwift向けデータ永続化フレームワーク。Swiftマクロで@Modelを定義するだけでCore Dataバックエンドによる永続化が実現でき、SwiftUIとの統合も優れている。' },
  { term: 'HealthKit', aliases: ['healthkit'], description: 'AppleのiOS向け健康データ管理フレームワーク。歩数・心拍数・睡眠データなどをHealth Appと共有し、ユーザーの許可のもとでフィットネスアプリが健康データを読み書きできる仕組み。' },
  { term: 'CoreLocation', aliases: ['corelocation'], description: 'AppleのiOS・macOSで位置情報・方位・高度を取得するフレームワーク。GPS・Wi-Fi・セルラー測位を組み合わせてデバイスの位置を取得し、ジオフェンシングや地域モニタリングにも対応する。' },
  { term: 'ジオフェンシング', aliases: ['geofencing'], description: '仮想的な地理的境界を設定しデバイスが境界を越えたときにイベントを発生させる技術。入店通知、配送追跡、ペアレンタルコントロールなどiOS・Androidのロケーションサービスで活用される。' },
  { term: 'バックグラウンドフェッチ', aliases: ['background fetch', 'bgapprefreshtask'], description: 'iOSアプリがバックグラウンドで定期的にデータを更新するためのAPI。システムが適切なタイミングでアプリを起動しコンテンツを更新することで、ユーザーに最新情報を表示できるようにする。' },
  { term: 'ProGuard', aliases: ['proguard'], description: 'Androidアプリのコード圧縮・最適化・難読化ツール。使われていないコードを除去しクラスや変数名を短縮してAPKサイズを削減する。現在はR8に置き換えられつつある難読化ツール。' },
  { term: 'R8', aliases: ['r8'], description: 'AndroidのProGuard後継コード縮小・最適化ツール。Dexコンパイラと統合されてビルド時間が短縮され、デッドコード除去と難読化をProGuardより効率的に実行するAndroidビルドツール。' },
  { term: 'AAB', aliases: ['aab', 'android app bundle'], description: 'Googleが推奨するAndroidアプリの配布形式。Google PlayがユーザーのデバイスとOSに合わせた最適なAPKを動的に生成し、不要なリソースを除外してダウンロードサイズを最大65%削減できる。' },
  { term: 'デザイナー', aliases: ['designer', 'uiデザイナー', 'uxデザイナー', 'プロダクトデザイナー'], description: 'UIのビジュアルデザイン・UXの設計・プロトタイピングを担当する職種。プロダクトデザイナー・UIデザイナー・UXデザイナー等があり、エンジニアと連携してFigmaやSketchでデザインデータを作成し、コンポーネント定義やデザインシステムを管理する。' },
  { term: '画面', aliases: ['ui screen', 'スクリーン'], description: 'アプリケーションのユーザーが操作する個々のUIビューまたはページ。ナビゲーション・フォーム・リスト・詳細・モーダル等の画面タイプがあり、ワイヤーフレームやモックアップで事前に設計する。スクリーン・ページとも呼び、画面数がUX設計の規模感を表す指標となる。' },
  { term: '角丸', aliases: ['rounded corners', 'border radius', '丸角', 'border-radius'], description: 'UIコンポーネントの角を丸くするデザイン要素。CSSの`border-radius`プロパティで制御し、カード・ボタン・入力フィールド・モーダルに適用される。角丸の大きさはデザインシステムで統一し、ブランドの柔らかさや親しみやすさを表現する。大きな角丸は現代的でフレンドリーな印象を与える。' },
  { term: '余白', aliases: ['whitespace', 'space', 'マージン', 'パディング'], description: 'UI要素間の空間。CSSではmargin（外側の余白）・padding（内側の余白）・gap（フレックス/グリッドの間隔）で表現する。適切な余白はコンテンツの可読性・グループ化・視線誘導を改善し、デザインシステムでは8ptグリッド等の一定スペーシングスケールで管理される。' },
  { term: '文字サイズ', aliases: ['font size', 'フォントサイズ', 'テキストサイズ'], description: 'テキストの大きさを指定するデザイン要素。CSSの`font-size`プロパティで制御し、本文・見出し・キャプション等の役割別にタイポグラフィスケールを定義する。デザインシステムでは相対単位（rem）を用いてアクセシビリティと可読性を確保し、最小でも本文14px/見出し18px以上が推奨される。' },
  { term: '一覧詳細', aliases: ['list detail', 'master detail', 'リスト詳細', '一覧・詳細'], description: 'アイテムの一覧（リスト/グリッド）と選択したアイテムの詳細情報を組み合わせた代表的なUIパターン。モバイルではマスター→ディテールの画面遷移、デスクトップではサイドバイサイドレイアウトを取ることが多い。メール・SNS・ECサイトの商品一覧など広く使われる基本パターン。' },
  { term: '検索画面', aliases: ['search screen', 'search page', '検索ページ', '検索ui'], description: 'ユーザーがキーワードや条件を入力してコンテンツや機能を探すUIページ。検索バー・フィルター・ソート・結果リスト・ページネーション等で構成される。UX設計では空状態・ゼロ件結果・ローディング状態のハンドリングも重要で、インクリメンタルサーチやファセット検索で使いやすさを高める。' },
  { term: 'アプリ画面', aliases: ['app screen'], description: 'モバイルアプリやWebアプリにおけるユーザーインターフェースの各画面を指します。UI設計における基本単位です。' },
  { term: 'UIホワイトスペース', aliases: ['uiホワイトスペース', 'ui whitespace'], description: 'UIデザインにおける要素間の余白や空白領域です。視認性を高め、デザインに余裕と整理感をもたらします。' },
  { term: '命題論理', aliases: ['propositional logic'], description: '命題論理は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '述語論理', aliases: ['predicate logic'], description: '述語論理は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '真理値表', aliases: ['truth table'], description: '真理値表は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ド・モルガンの法則', aliases: ['de morgan\'s laws'], description: 'ド・モルガンの法則は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '排他的論理和', aliases: ['exclusive or'], description: '排他的論理和は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '論理回路簡単化', aliases: ['logic circuit simplification'], description: '論理回路簡単化は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'カルノー図', aliases: ['karnaugh map'], description: 'カルノー図は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ベン図', aliases: ['venn diagram'], description: 'ベン図は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '集合演算', aliases: ['set operations'], description: '集合演算は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '順列', aliases: ['permutation'], description: '順列は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '組合せ', aliases: ['combination'], description: '組合せは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '確率分布', aliases: ['probability distribution'], description: '確率分布は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '期待値', aliases: ['expected value'], description: '期待値は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '四分位範囲', aliases: ['interquartile range'], description: '四分位範囲は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '標準偏差', aliases: ['standard deviation'], description: '標準偏差は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '相関係数', aliases: ['correlation coefficient'], description: '相関係数は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '回帰分析', aliases: ['regression analysis'], description: '回帰分析は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '指数関数', aliases: ['exponential function'], description: '指数関数は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '対数関数', aliases: ['logarithmic function'], description: '対数関数は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '数列', description: '数列は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '漸化式', aliases: ['recurrence relation'], description: '漸化式は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '再帰的定義', aliases: ['recursive definition'], description: '再帰的定義は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '漸近解析', aliases: ['asymptotic analysis'], description: '漸近解析は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'マスター定理', aliases: ['master theorem'], description: 'マスター定理は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '最悪計算量', aliases: ['worst-case complexity'], description: '最悪計算量は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '平均計算量', aliases: ['average-case complexity'], description: '平均計算量は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '最良計算量', aliases: ['best-case complexity'], description: '最良計算量は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '安定ソート', aliases: ['stable sort'], description: '安定ソートは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '内部ソート', aliases: ['internal sort'], description: '内部ソートは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '外部ソート', aliases: ['external sort'], description: '外部ソートは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '分割統治法', aliases: ['divide and conquer'], description: '分割統治法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '貪欲法', aliases: ['greedy method'], description: '貪欲法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '動的計画法', aliases: ['dynamic programming'], description: '動的計画法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'バックトラック法', description: 'バックトラック法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '枝刈り', description: '枝刈りは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ヒューリスティック探索', aliases: ['heuristic search'], description: 'ヒューリスティック探索は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '二分探索法', aliases: ['binary search'], description: '二分探索法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '線形探索法', aliases: ['linear search'], description: '線形探索法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ハッシュ探索', aliases: ['hash search'], description: 'ハッシュ探索は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'オープンアドレス法', aliases: ['open addressing'], description: 'オープンアドレス法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '連鎖法', aliases: ['chaining'], description: '連鎖法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '優先度付きキュー', aliases: ['priority queue'], description: '優先度付きキューは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '完全二分木', aliases: ['complete binary tree'], description: '完全二分木は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '平衡木', aliases: ['balanced tree'], description: '平衡木は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '最小全域木', aliases: ['minimum spanning tree'], description: '最小全域木は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'トポロジカルソート', aliases: ['topological sort'], description: 'トポロジカルソートは基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '強連結成分', aliases: ['strongly connected component'], description: '強連結成分は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '最短経路問題', aliases: ['shortest path problem'], description: '最短経路問題は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '乱数生成', aliases: ['random number generation'], description: '乱数生成は基礎理論・アルゴリズムで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'モンテカルロ法', aliases: ['monte carlo method'], description: 'モンテカルロ法は基礎理論・アルゴリズムで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ノイマン型コンピュータ', aliases: ['von neumann computer'], description: 'ノイマン型コンピュータは、命令とデータを同じメモリ空間に格納し順次処理するアーキテクチャです。現代のコンピュータの多くがこの方式を基本としています。' },
  { term: 'フェッチデコード実行サイクル', aliases: ['fetch-decode-execute cycle'], description: 'フェッチデコード実行サイクルは、CPUが命令を読み出し・解析・実行することを繰り返す基本動作循環です。' },
  { term: 'マイクロプログラム制御', aliases: ['microprogrammed control'], description: 'マイクロプログラム制御は、CPUの制御信号をコントロールメモリに格納したマイクロ命令によって実装する方式です。' },
  { term: 'ハーバードアーキテクチャ', aliases: ['harvard architecture'], description: 'ハーバードアーキテクチャは、命令メモリとデータメモリを分離し並行アクセスパスを実現するアーキテクチャです。マイコントローラ等に採用されています。' },
  { term: 'RISC設計', aliases: ['risc設計', 'risc design'], description: 'RISC設計は、小規模でシンプルな命令セットを用いて高速かつ均一なパイプライン実行に最適化されたCPU設計手法です。' },
  { term: 'CISC設計', aliases: ['cisc設計', 'cisc design'], description: 'CISC設計は、多数の複雑な命令を提供することでプログラムサイズを削減し多様な操作を直接サポートするCPU設計手法です。' },
  { term: '命令パイプライン', aliases: ['instruction pipeline'], description: '命令パイプラインは、複数の命令の各ステージを重ね合わせて同時に処理しCPUのスループットを向上する技術です。' },
  { term: 'ハザード制御', aliases: ['hazard control'], description: 'ハザード制御は、データハザード・構造的ハザード・制御ハザードなどのパイプライン競合を防ぎ正しい実行を保証する仕組みです。' },
  { term: '静的分岐予測', aliases: ['static branch prediction'], description: '静的分岐予測は、コンパイル時または設計時に知られた固定ルールに基づいて分岐結果を予測する手法です。' },
  { term: 'VLIWアーキテクチャ', aliases: ['vliwアーキテクチャ', 'vliw architecture'], description: 'VLIWアーキテクチャは、複数の独立した命令を長い命令ワードにまとめて並行実行するアーキテクチャです。コンパイラが並行性を抽出します。' },
  { term: 'アウトオブオーダ実行', description: 'アウトオブオーダ実行は、依存関係がない命令をプログラム順と異なる順序で実行しCPUの利用率を高める技術です。' },
  { term: 'レジスタ割付', aliases: ['register allocation'], description: 'レジスタ割付は、プログラム変数を限られたCPUレジスタに割り当て、メモリアクセスを削減するコンパイラの最適化処理です。' },
  { term: 'メモリマップトI/O', aliases: ['メモリマップトi/o'], description: 'メモリマップトI/Oは、入出力デバイスのレジスタをメモリアドレス空間にマッピングし通常のメモリ命令でアクセスできるようにするI/O方式です。' },
  { term: 'DMA転送', aliases: ['dma転送', 'dma transfer'], description: 'DMA転送は、周辺機器がCPUの介在なしにメモリとの間で直接データを転送できる仕組みです。CPUの負荷を軽減し高速転送を実現します。' },
  { term: '割込みベクタ', aliases: ['interrupt vector'], description: '割込みベクタとは、特定の割込みに対応するハンドラのアドレスを格納したテーブルエントリまたはアドレスです。' },
  { term: '優先割込み', aliases: ['priority interrupt'], description: '優先割込み処理は、優先度の高い割込み要求を低い要求より先に処理する仕組みです。リアルタイムシステムで重要です。' },
  { term: 'メモリ階層', aliases: ['memory hierarchy'], description: 'メモリ階層は、データアクセスの速度と容量のトレードオフを最適化するため、レジスタ・キャッシュ・主記憶・ストレージを階層的に組み合わせたメモリ構成です。' },
  { term: '連想メモリ', aliases: ['associative memory'], description: '連想メモリ（コンテンツアドレサブルメモリ）は、アドレスではなく内容をキーに検索を行うメモリです。TLB等に使われます。' },
  { term: 'キャッシュ一貫性', description: 'キャッシュ一貫性とは、マルチプロセッサ環境で各CPUキャッシュの内容を一致させるプロトコル・仕組みの総称です。MESIプロトコルが代表例です。' },
  { term: '書込みバック', aliases: ['write-back'], description: '書込みバック（ライトバック）キャッシュは、キャッシュからページをエビクトするまで主メモリへの更新を遅らせ書込みトラフィックを削減するキャッシュ戦略です。' },
  { term: '仮想記憶方式', aliases: ['virtual memory system'], description: '仮想記憶方式は、仮想アドレスを物理メモリおよびディスクにマッピングし各プロセスに大きな論理空間を提供するメモリ管理方式です。' },
  { term: 'ページ置換アルゴリズム', aliases: ['page replacement algorithm'], description: 'ページ置換アルゴリズムは、新しいページをRAMに読み込む際にどのメモリページを追い出すかを決定するアルゴリズムです。' },
  { term: 'LRU方式', aliases: ['lru方式', 'lru policy'], description: 'LRU（Least Recently Used）は、最も長い間参照されていないページを置換する方式です。局所性に基づく効率的な戦略です。' },
  { term: 'FIFO方式', aliases: ['fifo方式', 'fifo policy'], description: 'FIFO置換は、最も古く読み込まれたページを最初に置換する方式です。最近の使用状況に関係なく適用されます。' },
  { term: 'スラッシング', aliases: ['thrashing'], description: 'スラッシングとは、過度なページングによりシステムが実行よりスワッピングに大部分の時間を費やしてしまうパフォーマンス劣化現象です。' },
  { term: 'ワーキングセット', aliases: ['working set'], description: 'ワーキングセットとは、プロセスが一定時間内に効率的に実行するために必要なページの集合です。局所性の原理に基づいています。' },
  { term: 'セグメンテーション方式', aliases: ['segmentation scheme'], description: 'セグメンテーション方式は、メモリをコード・データ・スタックなどの論理的な領域に分割し、各セグメントに独自の境界を設けるメモリ管理方式です。' },
  { term: 'メモリ保護', aliases: ['memory protection'], description: 'メモリ保護は、プロセスが他のプロセスの保護されたメモリ領域を不正に読み書きできないようアクセス権限を強制する仕組みです。' },
  { term: 'プロセス制御ブロック', aliases: ['process control block'], description: 'プロセス制御ブロック（PCB）は、プロセスの状態・スケジューリング情報・リソース参照をコンテキストスイッチ用に格納したデータ構造です。' },
  { term: 'スレッドスケジューリング', aliases: ['thread scheduling'], description: 'スレッドスケジューリングは、実行待機中のスレッドのうちどれがCPU時間を割り当てられるか、どの順序で実行するかを決定します。' },
  { term: 'ラウンドロビン方式', aliases: ['round-robin scheduling'], description: 'ラウンドロビン方式は、各タスクに一定のタイムスライスを循環的に割り当てる公平なスケジューリング方式です。' },
  { term: '多段フィードバックキュー', aliases: ['multilevel feedback queue'], description: '多段フィードバックキューは、プロセスの振る舞いと待機時間に基づいて優先度を動的に調整するスケジューリングアルゴリズムです。' },
  { term: 'デッドロック回避', aliases: ['deadlock avoidance'], description: 'デッドロック回避は、リソース割り当てを安全な状態に保つことで循環待ち条件を未然に防ぐ仕組みです。' },
  { term: '銀行家アルゴリズム', aliases: ['banker\'s algorithm'], description: '銀行家アルゴリズムは、リソース要求を許可することでシステムが安全な状態を維持できるかを検査するデッドロック回避アルゴリズムです。' },
  { term: 'クリティカルセクション', aliases: ['critical section'], description: 'クリティカルセクションとは、共有リソースにアクセスするコード領域であり、相互排他的に実行されなければなりません。' },
  { term: 'セマフォ同期', aliases: ['semaphore synchronization'], description: 'セマフォ同期は、カウンタエントリのwait/signal操作を使って並行アクセスを制御する同期機構です。OSの核で広く使われます。' },
  { term: 'モニタ同期', aliases: ['monitor synchronization'], description: 'モニタ同期は、共有データと同期メソッドを条件変数による待機機構とともにカプセル化する同期機構です。' },
  { term: 'メッセージパッシング', aliases: ['message passing'], description: 'メッセージパッシングは、プロセスがメモリを共有せずメッセージの送受信で通信するプロセス間通信手法です。' },
  { term: 'システムコール', aliases: ['system call'], description: 'システムコールは、ユーザプログラムがカーネルサービスを要求するための制御されたインターフェースです。トラップ命令でCPUを特権モードに切り替えます。' },
  { term: 'カーネルモード', aliases: ['kernel mode'], description: 'カーネルモードは、すべてのハードウェアとメモリにフルアクセスできるCPU特権実行モードです。OSカーネルがこのモードで動作します。' },
  { term: 'ユーザモード', aliases: ['user mode'], description: 'ユーザモードは、アプリケーションが直接的な特権ハードウェアアクセスなしに実行される制限されたモードです。' },
  { term: 'ブートローダ', aliases: ['boot loader'], description: 'ブートローダは、コンピュータ起動時に最初に実行されるソフトウェアで、ハードウェア初期化とOSロードを担当します。' },
  { term: 'デバイスドライバ', description: 'デバイスドライバは、カーネルとハードウェアデバイスの間を仲介するソフトウェアモジュールで、デバイスを抽象化するインターフェースを提供します。' },
  { term: 'ファイルディスクリプタ', aliases: ['file descriptor'], description: 'ファイルディスクリプタは、OSがオープン中のファイルやI/Oストリームを参照するために使用する小さな整数のハンドルです。' },
  { term: 'ジャーナリングファイルシステム', aliases: ['journaling file system'], description: 'ジャーナリングファイルシステムは、メタデータの更新をジャーナルに記録してクラッシュ後の復元性を向上させるファイルシステムです。ext4が代表例です。' },
  { term: 'スワップ領域', aliases: ['swap area'], description: 'スワップ領域は、物理RAMが不足しているときにメモリページを一時的に格納するために使用されるディスク領域です。' },
  { term: '仮想化支援機能', aliases: ['hardware virtualization support'], description: '仮想化支援機能は、仮想マシンの実行を高速化・隔離するCPUのハードウェア拡張機能です。Intel VT-xやAMD-Vが代表例です。' },
  { term: 'ハイパーバイザ型', aliases: ['hypervisor-based virtualization'], description: 'ハイパーバイザ型仮想化は、ハイパーバイザレイヤを通じてホスト上で複数の仮想マシンを実行する仮想化方式です。VMwareやKVMが代表例です。' },
  { term: 'コンテナ仮想化', aliases: ['container virtualization'], description: 'コンテナ仮想化は、同じOSカーネルを共有しながらアプリケーションをOSレベルで隔離する仮想化技術です。Dockerが代表例です。' },
  { term: 'リアルタイムスケジューリング', aliases: ['real-time scheduling'], description: 'リアルタイムスケジューリングは、時間的に決定論的なシステムでデッドラインを確実に守るため、タスクの優先度を決定するスケジューリング技術です。' },
  { term: '多値従属性', aliases: ['multivalued dependency'], description: '多値従属性とは、ひとつの属性が複数の独立した値の集合を決定するリレーション内の従属の一種です。第4正規化で除去対象となります。' },
  { term: '部分関数従属性', aliases: ['partial functional dependency'], description: '部分関数従属性とは、複合キーの一部にのみ非キー属性が依存している状態です。第2正規形への変換で除去します。' },
  { term: '推移的関数従属性', aliases: ['transitive functional dependency'], description: '推移的関数従属性とは、非キー属性が別の非キー属性を経由してキーに依存している状態です。第3正規形への変換で除去します。' },
  { term: '候補キー', aliases: ['candidate key'], description: '候補キーとは、テーブルの各行を一意に識別できる最小限の属性集合です。複数存在する場合がありその中から主キーが選ばれます。' },
  { term: '主キー制約', aliases: ['primary key constraint'], description: '主キー制約とは、選択された行識別子に対して一意性とNULL禁止を強制するデータベース制約です。テーブルに必ず1つ設定します。' },
  { term: 'ドメイン制約', aliases: ['domain constraint'], description: 'ドメイン制約とは、属性値を有効なデータ型・範囲・許容値の集合に限定するデータベース制約です。データの正確性を保証します。' },
  { term: '参照アクション', aliases: ['referential action'], description: '参照アクションとは、参照先レコードが更新・削除された際に参照元レコードに対して実行される動作（CASCADE・RESTRICTなど）を定義したものです。' },
  { term: 'エンティティ整合性', aliases: ['entity integrity'], description: 'エンティティ整合性とは、テーブルの各行が一意かつNULLでない主キーを持つことを要求するデータ整合性のルールです。' },
  { term: '第1正規化', aliases: ['first normal form'], description: '第1正規形（1NF）は、各列がアトミックな値を持ち繰り返しグループを含まないことを要求する正規化の第1段階です。' },
  { term: '第2正規化', aliases: ['second normal form'], description: '第2正規形（2NF）は、部分関数従属性を除去し非キー属性がキー全体に依存するよう変換した正規化の第2段階です。' },
  { term: '第3正規化', aliases: ['third normal form'], description: '第3正規形（3NF）は、推移的関数従属性を除去し非キー属性同士の依存関係をなくした正規化の第3段階です。' },
  { term: 'BCNF', aliases: ['bcnf', 'boyce-codd normal form'], description: 'BCNF（ボイスコッド正規形）は、すべての関数従属の決定項が候補キーである第3正規形より厳格な正規形です。' },
  { term: '逆正規化戦略', aliases: ['denormalization strategy'], description: '逆正規化戦略とは、読み取りパフォーマンス向上やクエリ簡素化のために意図的に冗長性を導入するデータベース設計手法です。' },
  { term: 'IDEF1Xモデル', aliases: ['idef1xモデル', 'idef1x model'], description: 'IDEF1Xはエンティティ・キー・関連を形式的に表現するデータモデリング手法で、データベース設計に使用される標準表記法です。' },
  { term: '実体関連図', description: 'ER図（実体関連図）はエンティティ・属性・関連を視覚的に表現した図で、データベース設計の出発点として広く使われます。' },
  { term: '参加制約', aliases: ['participation constraint'], description: '参加制約とは、エンティティがリレーションシップへの参加が必須か任意かを指定するERモデルの制約です。全参加と部分参加に分類されます。' },
  { term: '多対多関連', aliases: ['many-to-many relationship'], description: '多対多関連（M:N）とは、両側のエンティティが複数の相手と対応できる関係で、通常は中間テーブル（交差テーブル）を使って解消します。' },
  { term: 'スーパータイプ', aliases: ['supertype'], description: 'スーパータイプとは、サブタイプに共通する属性を保持する汎化されたエンティティです。継承関係の上位に位置します。' },
  { term: 'サブタイプ', aliases: ['subtype'], description: 'サブタイプとは、スーパータイプから共通属性を継承しながら固有の属性を追加した特化されたエンティティです。' },
  { term: '論理データ設計', aliases: ['logical data design'], description: '論理データ設計は、特定のDBMS実装に依存しないエンティティと関係を定義する設計活動です。' },
  { term: '物理データ設計', aliases: ['physical data design'], description: '物理データ設計は、論理モデルを実際のテーブル・インデックス・ストレージ・DBMS固有の設定にマッピングする設計活動です。' },
  { term: 'インデックス選択性', aliases: ['index selectivity'], description: 'インデックス選択性とは、インデックス値が行を一意に識別できる度合いを表す指標です。選択性が高いほどインデックスが有効に機能します。' },
  { term: 'クラスタ化インデックス', aliases: ['clustered index'], description: 'クラスタ化インデックスとは、テーブルの行をインデックスキーの順序と同じ物理順序で格納するインデックスです。テーブルに1つのみ作成できます。' },
  { term: '非クラスタ化インデックス', aliases: ['nonclustered index'], description: '非クラスタ化インデックスとは、キーの順序と行の物理順序を別々に保持し行の場所をポインタで参照するインデックスです。複数作成できます。' },
  { term: '前方一致検索最適化', aliases: ['prefix search optimization'], description: '前方一致検索最適化は、文字列の先頭一致クエリをインデックスを活用したパターンで効率化する手法です。' },
  { term: 'INCLUDE列インデックス', aliases: ['include列インデックス', 'included-column index'], description: 'INCLUDE列インデックスとは、非キー列をインデックスに付加しテーブルへの追加ルックアップなしにクエリを満たせるカバリングインデックスです。' },
  { term: '実行計画解析', aliases: ['execution plan analysis'], description: '実行計画解析は、データベースエンジンがクエリに対してデータアクセスとジョイン処理をどのように行うかを調査する活動です。' },
  { term: '統計情報更新', aliases: ['statistics update'], description: '統計情報更新とは、データベースオプティマイザ向けにテーブルのデータ分布・行数などの統計情報を最新化する操作です。クエリ実行計画の精度維持に重要です。' },
  { term: 'ビュー定義', aliases: ['view definition'], description: 'ビュー定義とは、基底テーブルに対して保存されたクエリをもとに仮想テーブルを作成する仕組みです。クエリの再利用やアクセス制御に活用されます。' },
  { term: 'インクリメンタルビュー更新', aliases: ['incremental view maintenance'], description: 'インクリメンタルビュー更新とは、マテリアライズドビューの全体を再計算せず変更された部分のみを更新することで効率的にビューを最新化する手法です。' },
  { term: 'ストアドファンクション（拡張1）', aliases: ['stored function (extended 1)'], description: 'ストアドファンクションはデータベース内に保存された再利用可能なルーチンであり、SQL文の中で呼び出して値を返します。ロジックをDB側に集約することでコード重複を削減できます。' },
  { term: 'トリガ処理', aliases: ['trigger processing'], description: 'トリガ処理とは、INSERT・UPDATE・DELETEなどのイベント発生時に自動的に定義済みのロジックを実行するデータベースの仕組みです。' },
  { term: '分離レベル調整', aliases: ['isolation level tuning'], description: '分離レベル調整とは、トランザクションの並行処理における一貫性と競合のバランスを取るために適切なアイソレーションレベルを選択する作業です。' },
  { term: 'ダーティライト', aliases: ['dirty write'], description: 'ダーティライトとは、あるトランザクションが別のトランザクションによるコミット前のデータを上書きしてしまう並行処理異常です。' },
  { term: '読取り一貫性', aliases: ['read consistency'], description: '読取り一貫性とは、トランザクションが実行中に参照するデータが一貫した時点のスナップショットとして見える性質です。MVCCで実現されます。' },
  { term: 'ギャップロック', aliases: ['gap lock'], description: 'ギャップロックとは、インデックスレコード間の範囲をロックしてトランザクション中のファントム挿入を防ぐロック機構です。' },
  { term: 'ロックエスカレーション', aliases: ['lock escalation'], description: 'ロックエスカレーションとは、多数の細粒度ロックをより粗粒度のロックに昇格させることでロック管理のオーバーヘッドを削減する仕組みです。' },
  { term: '行共有ロック', aliases: ['row share lock'], description: '行共有ロックとは、更新候補の行に対して制御された同時読取りを許可しながら潜在的な更新をマークするロックです。' },
  { term: 'バージョン列制御', aliases: ['version column control'], description: 'バージョン列制御とは、更新競合を検知するためにバージョン番号列のインクリメントを利用する楽観的並行性制御の手法です。' },
  { term: '2相ロック', aliases: ['two-phase locking'], description: '2相ロック（2PL）とは、拡張フェーズでロックを取得し収縮フェーズで解放することで直列可能性を保証するトランザクション管理プロトコルです。' },
  { term: 'コミットログ', aliases: ['commit log'], description: 'コミットログとは、コミット済みの変更を耐久的に記録するログファイルです。クラッシュリカバリやレプリケーションの基盤となります。' },
  { term: 'チェックポイント処理', aliases: ['checkpoint processing'], description: 'チェックポイント処理とは、定期的に一貫した状態マーカーをディスクに書き込むことでクラッシュリカバリを高速化する仕組みです。' },
  { term: 'レプリケーション構成', aliases: ['replication configuration'], description: 'レプリケーション構成とは、可用性とスケールのためにプライマリとレプリカ間でデータをコピーする方式・設定を定義したものです。' },
  { term: 'シャーディング設計', aliases: ['sharding design'], description: 'シャーディング設計は、シャードキーに基づいてデータを複数ノードに分散し水平スケーリングを実現する設計手法です。' },
  { term: 'PACELC定理', aliases: ['pacelc定理', 'pacelc theorem'], description: 'PACELC定理とは、分散システムがパーティション時のCAトレードオフに加え平常時の待ち時間と一貫性のトレードオフも持つことを説明する定理です。' },
  { term: 'ドキュメントストア', aliases: ['document store'], description: 'ドキュメントストアとは、JSONに類似した半構造化レコードを格納するNoSQLデータベースです。スキーマの柔軟性が高がMongoDBが代表例です。' },
  { term: '列指向データベース', aliases: ['column-oriented database'], description: '列指向データベースとは、値を列単位で格納するデータベースです。大規模データセットの圧縮と分析クエリに優れており，DWHで広く使われます。' },
  { term: '時系列圧縮', aliases: ['time-series compression'], description: '時系列圧縮とは、タイムスタンプ付きメトリクスデータを時間的パターンを利用して圧縮しストレージと転送コストを削減する手法です。' },
  { term: 'プロパティグラフモデル', aliases: ['property graph model'], description: 'プロパティグラフモデルとは、ノードとエッジにキーバリューのプロパティを付与してデータを表現するグラフデータベースのデータモデルです。' },
  { term: 'メダリオンアーキテクチャ（拡張1）', aliases: ['medallion architecture (extended 1)'], description: 'メダリオンアーキテクチャはデータパイプラインをブロンズ・シルバー・ゴールドなどの段階的なゾーンに整理し、データ品質を段階的に高める設計パターンです。データレイクハウスで広く採用されています。' },
  { term: 'OSIサービスプリミティブ', aliases: ['osiサービスプリミティブ', 'osi service primitive'], description: 'OSIサービスプリミティブはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'TCP/IP階層設計', aliases: ['tcp/ip階層設計', 'tcp/ip layered design'], description: 'TCP/IP階層設計はネットワークの構造や責務分割を説明するための基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '物理層符号化', aliases: ['physical layer encoding'], description: '物理層符号化はネットワークの構造や責務分割を説明するための基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'データリンク制御', aliases: ['data link control'], description: 'データリンク制御はネットワークで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ネットワーク層ルーティング', aliases: ['network-layer routing'], description: 'ネットワーク層ルーティングはネットワークの構造や責務分割を説明するための基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'トランスポートポート設計', aliases: ['transport port design'], description: 'トランスポートポート設計はネットワークを計画・管理・評価するための基本概念。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'セッション再開', aliases: ['session resumption'], description: 'セッション再開はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'データ表現変換', aliases: ['data representation conversion'], description: 'データ表現変換はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'アプリケーションゲートウェイ', aliases: ['application gateway'], description: 'アプリケーションゲートウェイはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'フレーム中継', aliases: ['frame relay'], description: 'フレーム中継はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'VLANタグ', aliases: ['vlanタグ', 'vlan tag'], description: 'VLANタグはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'STPプロトコル', aliases: ['stpプロトコル', 'spanning tree protocol (stp)'], description: 'STPプロトコルはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'FIBテーブル', aliases: ['fibテーブル', 'fib table'], description: 'FIBテーブルはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ポリシーベースルーティング', aliases: ['policy-based routing'], description: 'ポリシーベースルーティングはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ルート再配布', aliases: ['route redistribution'], description: 'ルート再配布はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'リンクステート型', aliases: ['link-state routing'], description: 'リンクステート型はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ディスタンスベクタ型', aliases: ['distance-vector routing'], description: 'ディスタンスベクタ型はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'CIDR表記', aliases: ['cidr表記', 'cidr notation'], description: 'CIDR表記はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'サブネット分割', aliases: ['subnetting'], description: 'サブネット分割はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'デフォルトゲートウェイ', aliases: ['default gateway'], description: 'デフォルトゲートウェイはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'NAT変換', aliases: ['nat変換', 'nat translation'], description: 'NAT変換はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'PAT変換', aliases: ['pat変換', 'pat translation'], description: 'PAT変換はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'DHCPリース', aliases: ['dhcpリース', 'dhcp lease'], description: 'DHCPリースはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'DNS再帰問い合わせ', aliases: ['dns再帰問い合わせ', 'dns recursive query'], description: 'DNS再帰問い合わせはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'DNSキャッシュポイズニング', aliases: ['dnsキャッシュポイズニング', 'dns cache poisoning'], description: 'DNSキャッシュポイズニングはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ARP解決', aliases: ['arp解決', 'arp resolution'], description: 'ARP解決はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'ICMP制御', aliases: ['icmp制御', 'icmp control'], description: 'ICMP制御はネットワークで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'MTUサイズ', aliases: ['mtuサイズ', 'mtu size'], description: 'MTUサイズはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'フラグメンテーション', aliases: ['fragmentation'], description: 'フラグメンテーションはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'アクティブキュー管理', aliases: ['active queue management'], description: 'アクティブキュー管理はネットワークを計画・管理・評価するための基本概念。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'フロー制御', description: 'フロー制御はネットワークで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '3ウェイハンドシェイク', aliases: ['three-way handshake'], description: '3ウェイハンドシェイクはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '選択再送方式', aliases: ['selective repeat arq'], description: '選択再送方式はネットワークで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'RTT推定', aliases: ['rtt推定', 'rtt estimation'], description: 'RTT推定はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '相互TLS認証', aliases: ['相互tls認証', 'mutual tls authentication'], description: '相互TLS認証はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'SNI拡張', aliases: ['sni拡張', 'sni extension'], description: 'SNI拡張はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'HTTP永続接続', aliases: ['http永続接続', 'http persistent connection'], description: 'HTTP永続接続はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'HTTP/2多重化', aliases: ['http/2多重化', 'http/2 multiplexing'], description: 'HTTP/2多重化はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'QUICプロトコル', aliases: ['quicプロトコル', 'quic protocol'], description: 'QUICプロトコルはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'WebSocket通信', aliases: ['websocket通信', 'websocket communication'], description: 'WebSocket通信はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'CDN配信', aliases: ['cdn配信', 'cdn delivery'], description: 'CDN配信はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '負荷分散装置', description: '負荷分散装置はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'L7リバースプロキシ', aliases: ['l7リバースプロキシ', 'layer 7 reverse proxy'], description: 'L7リバースプロキシはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '明示プロキシ', aliases: ['explicit proxy'], description: '明示プロキシはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'マイクロセグメンテーション', aliases: ['microsegmentation'], description: 'マイクロセグメンテーションはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'SDN制御', aliases: ['sdn制御', 'sdn control'], description: 'SDN制御はネットワークで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'NFV基盤', aliases: ['nfv基盤', 'nfv infrastructure'], description: 'NFV基盤はネットワークの構造や責務分割を説明するための基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'VPNトンネリング', aliases: ['vpnトンネリング', 'vpn tunneling'], description: 'VPNトンネリングはネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'MPLS網', aliases: ['mpls網', 'mpls network'], description: 'MPLS網はネットワークで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'BGP経路制御', aliases: ['bgp経路制御', 'bgp route control'], description: 'BGP経路制御はネットワークで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'STRIDE分析', aliases: ['stride分析'], description: 'STRIDE分析はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '攻撃経路分析', description: '攻撃経路分析はセキュリティで想定される代表的な攻撃・脅威を示す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'セキュリティ要求分析', description: 'セキュリティ要求分析はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '最小権限原則', description: '最小権限原則はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '相互牽制統制', description: '相互牽制統制はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '適応型認証', description: '適応型認証はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'パスワードレス認証', description: 'パスワードレス認証はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '生体検知', description: '生体検知はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '認証連携', description: '認証連携はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: 'フェデレーション認証', description: 'フェデレーション認証はセキュリティで頻出する基本情報技術者試験レベルの基礎用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '認可制御', description: '認可制御はセキュリティで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
  { term: '属性ベースアクセス制御', description: '属性ベースアクセス制御はセキュリティで用いられる代表的な手法を表す用語。試験対策では、用語の定義だけでなく前提条件と適用場面の違いまで整理して理解する。' },
];
