// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: aiLlm (2/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: '人間の方向づけ', aliases: ['human direction'], description: 'AIが進む目的や方針を人が与えること。' },
  { term: '不可逆な行為', aliases: ['irreversible action'], description: '取り消しややり直しが難しい操作。' },
  { term: '実装量', aliases: ['implementation volume'], description: 'どれだけ多くのコードや機能を作ったかという量。' },
  { term: '一次出典', aliases: ['primary source'], description: '情報の最初の発信元となる資料。' },
  { term: '趣旨に基づく解釈', aliases: ['spirit-based interpretation'], description: '厳密な文言より意味の中心をもとに理解すること。' },
  { term: 'ベクトル化', description: '文章や画像を検索しやすい数値表現に変換すること。' },
  { term: '類似検索', description: '入力内容に意味が近い情報を探す検索方法。' },
  { term: '要約', description: '長い文書や会話を短く整理すること。' },
  { term: '翻訳', description: 'ある言語の内容を別の言語へ変換すること。' },
  { term: '文字起こし', description: '音声や画像中の文字をテキストにすること。' },
  { term: 'OCR', aliases: ['ocr', 'optical character recognition'], description: '画像やPDFの文字を認識してテキスト化する技術。' },
  { term: 'AI Foundry', aliases: ['ai foundry'], description: 'AIモデルやエージェントを構築・管理する基盤やサービスを指す語。' },
  { term: 'Claude Code', aliases: ['claude code'], description: 'コーディング支援に強いAI系開発ツール名。' },
  { term: 'Codex', aliases: ['codex'], description: 'コード生成・修正・理解を支援するAI系ツールやモデル群を指す。' },
  { term: 'Kiro', aliases: ['kiro'], description: '仕様駆動型の開発補助に使われるAI開発ツール名。' },
  { term: 'Gemini', aliases: ['gemini'], description: 'Google系の生成AIモデル群の名称。' },
  { term: 'OpenAI', aliases: ['openai'], description: '【AI】ChatGPTやGPT系モデル、埋め込みモデル、API、関連ツールを提供するAI企業・プラットフォーム名。 【OCI APEX】APEXで設定可能な生成AI提供元の一つ。' },
  { term: 'AI統合', aliases: ['ai統合'], description: '既存のシステムや業務フローにAIモデルやエージェントを組み込み、検索、要約、判断支援、自動化などに活用できるようにすること。' },
  { term: 'Anthropic', aliases: ['anthropic'], description: 'Claude系モデルを提供する企業名。' },
  { term: '教師あり学習', aliases: ['supervised learning'], description: '入力と正解ラベルのペアからなる訓練データを用いてモデルを学習させる機械学習のパラダイム。分類・回帰・系列ラベリングなど幅広いタスクに適用され、予測精度の評価が容易である。' },
  { term: '教師なし学習', aliases: ['unsupervised learning'], description: '正解ラベルを使わずにデータの構造・パターン・分布を学習する機械学習のパラダイム。クラスタリング・次元削減・密度推定・生成モデルなどが含まれ、ラベル付きデータが少ない場面で有効。' },
  { term: '半教師あり学習', aliases: ['semi-supervised learning'], description: '少量のラベルありデータと大量のラベルなしデータを組み合わせて学習する手法。ラベル付けコストを抑えながら教師あり学習に近い性能を達成することを目指す。' },
  { term: '強化学習', aliases: ['reinforcement learning', 'rl'], description: 'エージェントが環境と相互作用しながら報酬を最大化する方策を学習するフレームワーク。ゲームのプレイ・ロボット制御・対話システムなどに応用され、Q学習やPolicy Gradientが代表的手法。' },
  { term: 'ニューラルネットワーク', aliases: ['neural network', 'nn', '人工ニューラルネットワーク'], description: '人間の脳のニューロン結合を模倣した計算モデル。入力層・隠れ層・出力層からなり、重みとバイアスを誤差逆伝播法で最適化する。多様なアーキテクチャが画像・音声・言語タスクで高精度を達成している。' },
  { term: 'ディープラーニング', aliases: ['deep learning', '深層学習'], description: '多数の隠れ層を持つニューラルネットワークを用いた表現学習の手法。大量データとGPUの普及により飛躍的に発展し、画像認識・音声認識・自然言語処理などで人間の精度を超えた結果をもたらした。' },
  { term: 'CNN', aliases: ['cnn', '畳み込みニューラルネットワーク', 'convolutional neural network'], description: '畳み込み層とプーリング層を組み合わせた画像処理に特化したニューラルネットワーク。局所的な特徴の抽出と空間的な不変性により、画像分類・物体検出・セグメンテーションで高性能を発揮する。' },
  { term: 'RNN', aliases: ['rnn', '再帰型ニューラルネットワーク', 'recurrent neural network'], description: '系列データを処理するために過去の隠れ状態を次のステップに引き継ぐアーキテクチャ。時系列・テキスト・音声などのシーケンシャルなデータに適するが、長期依存関係の学習が困難な勾配消失問題を抱える。' },
  { term: 'LSTM', aliases: ['lstm', 'long short-term memory', '長短期記憶'], description: 'RNNの勾配消失問題を解決するために入力・出力・忘却の3つのゲート機構を持つアーキテクチャ。長期依存関係の学習が可能で、機械翻訳・音声認識・文章生成に広く利用された。' },
  { term: 'GRU', aliases: ['gru', 'gated recurrent unit', 'ゲート付き再帰ユニット'], description: 'LSTMを簡略化したゲート付きRNNの一種。リセットゲートと更新ゲートの2つで長期・短期の情報を制御し、LSTMと同等の性能をより少ないパラメータで実現することが多い。' },
  { term: 'Transformer', aliases: ['transformer'], description: 'Self-Attentionを中核とするエンコーダ・デコーダアーキテクチャ。系列全体を並列処理できるためRNNより学習効率が高く、BERTやGPTなどの大規模言語モデルの基盤となっている。' },
  { term: 'Attention機構', aliases: ['attention機構', 'attention mechanism', '注意機構'], description: '系列内の各要素が他の要素に対してどれだけ注目するかを重み付けして文脈を捉える機構。翻訳のAlignment問題を解決するために提案され、Transformerの核となった。' },
  { term: 'Self-Attention', aliases: ['self-attention', '自己注意機構', 'intra-attention'], description: '同一系列内の全要素間で注意重みを計算するAttention機構の特殊形。クエリ・キー・バリューをすべて同一入力から生成し、系列内の長距離依存を効率的に捉える。' },
  { term: 'Multi-Head Attention', aliases: ['multi-head attention', 'マルチヘッドアテンション'], description: 'Self-Attentionを複数のヘッドで並列に実行し、異なる部分空間での依存関係を同時に捉える手法。各ヘッドの出力を結合することで表現力を高め、Transformerの性能の鍵を握る。' },
  { term: 'Positional Encoding', aliases: ['positional encoding', '位置符号化', 'ポジショナルエンコーディング'], description: 'Transformerが系列内の位置情報を扱えるよう埋め込みに加算する符号。サイン・コサインの周波数を使う固定式と学習可能な相対位置符号化がある。' },
  { term: 'Encoder-Decoder', aliases: ['encoder-decoder', 'エンコーダ・デコーダ', 'seq2seq'], description: '入力系列をエンコーダで潜在表現に圧縮し、デコーダで出力系列を生成するアーキテクチャ。機械翻訳・要約・質問応答など系列変換タスクに適し、Attention機構と組み合わせて高性能を達成する。' },
  { term: 'BERT', aliases: ['bert', 'bidirectional encoder representations from transformers'], description: 'Transformerのエンコーダを双方向にマスク言語モデルと次文予測で事前学習したモデル。文分類・固有表現抽出・質問応答など多様なNLPタスクへのファインチューニングで顕著な性能向上をもたらした。' },
  { term: 'Vision Transformer', aliases: ['vision transformer', 'vit'], description: '画像をパッチに分割してTransformerに入力する画像認識アーキテクチャ。大規模データによる事前学習でCNNと同等以上の性能を達成し、画像とテキストのマルチモーダル研究を加速させた。' },
  { term: '拡散モデル', aliases: ['diffusion model', 'ddpm', 'score-based model'], description: 'データにノイズを段階的に加えるフォワードプロセスとノイズ除去を学習するリバースプロセスからなる生成モデル。画像・音声・動画の生成で高品質な結果を出し、Stable DiffusionやDALL-Eの基盤技術となっている。' },
  { term: 'GAN', aliases: ['gan', 'generative adversarial network', '敵対的生成ネットワーク'], description: 'データを生成するGeneratorと本物か偽物かを判別するDiscriminatorが競い合うことで高品質な生成を実現するモデル。画像生成・スタイル変換・データ拡張などに応用される。' },
  { term: 'VAE', aliases: ['vae', 'variational autoencoder', '変分オートエンコーダ'], description: '入力を確率的潜在空間に符号化し、その潜在変数から元データを再構成する生成モデル。潜在空間が滑らかな構造を持つため補間や生成が容易で、変分推論に基づく理論的枠組みを持つ。' },
  { term: '損失関数', aliases: ['loss function', 'コスト関数', 'objective function'], description: 'モデルの予測と正解ラベルのズレを定量化するスカラー関数。学習は損失を最小化するようパラメータを更新することで進む。タスクによって平均二乗誤差・交差エントロピーなどが選択される。' },
  { term: '勾配降下法', aliases: ['gradient descent', 'gd'], description: '損失関数の勾配の反方向にパラメータを繰り返し更新してモデルを最適化するアルゴリズム。学習率・バッチサイズによってバリエーションがあり、確率的勾配降下法やミニバッチ法が実用的に使われる。' },
  { term: 'SGD', aliases: ['sgd', '確率的勾配降下法', 'stochastic gradient descent'], description: 'バッチ全体ではなくランダムにサンプリングした1件または少数サンプルで勾配を推定してパラメータを更新する最適化アルゴリズム。ノイズによる局所最小回避が期待でき、大規模データへのスケールが容易。' },
  { term: 'Adam', aliases: ['adam', 'adaptive moment estimation'], description: '一次・二次モーメントの移動平均を用いてパラメータごとに学習率を適応的に調整する最適化アルゴリズム。SGDより収束が速く安定しやすいため、ディープラーニングで最も広く使われている。' },
  { term: '学習率', aliases: ['learning rate', 'lr'], description: '勾配降下法で1ステップあたりにパラメータを更新する大きさを制御するハイパーパラメータ。大きすぎると収束が不安定になり、小さすぎると学習が遅くなるため、適切なスケジューリングが重要。' },
  { term: 'バッチサイズ', aliases: ['batch size', 'ミニバッチサイズ'], description: '1回のパラメータ更新に使うサンプル数。大きいほど勾配推定が安定するがメモリ消費も増大し、小さいほど正則化効果が生まれるが収束が遅くなる。GPU並列効率とも深く関わるハイパーパラメータ。' },
  { term: 'エポック', aliases: ['epoch'], description: '訓練データセット全体を1回スキャンする学習の単位。エポック数はハイパーパラメータであり、少なすぎると未学習、多すぎると過学習が起きる。早期停止でエポックを自動決定することが多い。' },
  { term: '過学習', aliases: ['overfitting', '過適合'], description: 'モデルが訓練データに過剰に適合し、未見データへの汎化性能が低下した状態。バリデーション損失が訓練損失より大幅に高い場合に検出され、正則化・ドロップアウト・早期停止などで対処する。' },
  { term: 'ドロップアウト', aliases: ['dropout'], description: '学習中にランダムにニューロンを確率pで無効化する正則化手法。アンサンブル的な効果をもたらし過学習を抑制する。推論時は全ニューロンを有効にして出力をスケールする。' },
  { term: 'バッチ正規化', aliases: ['batch normalization', 'batchnorm'], description: 'ミニバッチ単位で各層の活性化を平均0・分散1に正規化した後、スケールとシフトを学習する手法。内部共変量シフトを緩和し、学習率を大きくしても安定した学習を可能にする。' },
  { term: '活性化関数', aliases: ['activation function'], description: 'ニューラルネットワークの各ニューロンに非線形性を与える関数。線形変換のみでは表現できない複雑なパターンを学習可能にする。ReLU・Sigmoid・Softmax・GELUなどが代表的。' },
  { term: 'ReLU', aliases: ['relu', 'rectified linear unit', '正規化線形ユニット'], description: '入力が正であればそのまま出力し、負であれば0にする活性化関数。計算が単純で勾配消失が起きにくく、現在のディープラーニングで最も広く使われる。Leaky ReLU・ELU・GELUなど変種も多い。' },
  { term: 'Softmax', aliases: ['softmax', 'ソフトマックス関数'], description: '実数値のベクトルを確率分布に変換する活性化関数。多クラス分類の出力層で使われ、全要素の合計が1になるよう指数関数と正規化を組み合わせる。交差エントロピー損失と組み合わせて使用される。' },
  { term: '交差エントロピー', aliases: ['cross entropy', 'cross-entropy loss'], description: '真の確率分布とモデルの予測分布の乖離を測る損失関数。分類タスクで標準的に使われ、正解クラスの対数確率の負値の期待値として定義される。Softmax出力と組み合わせるのが一般的。' },
  { term: '混同行列', aliases: ['confusion matrix'], description: '二値・多クラス分類の結果をTP・FP・TN・FNに分けて表形式で整理した評価ツール。精度・再現率・F1スコアなどの指標の計算基盤となり、モデルの誤り傾向を把握するのに有効。' },
  { term: '適合率', aliases: ['precision', '精度（適合率）'], description: '正と予測したサンプルのうち実際に正であった割合（TP/(TP+FP)）。偽陽性のコストが高い場面（スパム検出など）で重視される指標。再現率とのトレードオフを考慮して閾値を調整する。' },
  { term: '再現率', aliases: ['recall', 'sensitivity', '真陽性率'], description: '実際に正であるサンプルのうち正と予測できた割合（TP/(TP+FN)）。見落としのコストが高い場面（病気の診断など）で重視される指標。適合率とのトレードオフを考慮して閾値を選択する。' },
  { term: 'F1スコア', aliases: ['f1スコア', 'f1 score', 'f-measure'], description: '適合率と再現率の調和平均で計算される分類評価指標。クラス不均衡なデータセットでAccuracyより適切な評価ができる。マクロ・マイクロ・加重平均など集計方法も複数ある。' },
  { term: 'ROC曲線', aliases: ['roc曲線', 'roc curve', 'receiver operating characteristic'], description: '二値分類で閾値を変化させたときの真陽性率（再現率）と偽陽性率の関係を示す曲線。モデルの識別能力を閾値に依存せず評価でき、AUCと組み合わせてモデル比較に使われる。' },
  { term: 'AUC', aliases: ['auc', 'area under the curve', 'auc-roc'], description: 'ROC曲線の下の面積で表される分類性能指標。0.5がランダム、1.0が完全な識別能力を意味し、クラス不均衡でも安定した評価ができる。PR曲線のAUCと使い分けることが重要。' },
  { term: '交差検証', aliases: ['cross validation', 'cv', 'k-fold cv'], description: 'データをk分割してk-1折を訓練・1折を検証に使い、k回繰り返すモデル評価手法。汎化性能を安定して推定でき、データが少ない場合に特に有効。層化・グループ・時系列対応の亜種がある。' },
  { term: 'ハイパーパラメータチューニング', aliases: ['hyperparameter tuning', 'hpo', 'ハイパーパラメータ最適化'], description: '学習率・バッチサイズ・層の数などモデルの構造や学習を制御するハイパーパラメータを最適化するプロセス。Grid Search・Random Search・Bayesian OptimizationなどがありAutoMLで自動化できる。' },
  { term: 'Grid Search', aliases: ['grid search', 'グリッドサーチ', 'グリッド探索'], description: 'ハイパーパラメータの候補値の全組み合わせを網羅的に評価する探索手法。確実に最良の組み合わせを見つけられる一方、候補数が増えると計算コストが指数的に増大する。' },
  { term: 'Random Search', aliases: ['random search', 'ランダムサーチ', 'ランダム探索'], description: 'ハイパーパラメータの組み合わせをランダムにサンプリングして評価する探索手法。Grid Searchより効率よく広い空間を探索でき、多くの場面でGrid Searchより優れることが示されている。' },
  { term: 'Bayesian Optimization', aliases: ['bayesian optimization', 'ベイズ最適化'], description: 'ガウス過程などの代理モデルでこれまでの評価結果を利用して次に試すハイパーパラメータを選択する最適化手法。評価コストの高い関数に少ない試行で効率的に最良値を見つけられる。' },
  { term: 'AutoML', aliases: ['automl', '自動機械学習', 'automated machine learning'], description: '特徴量エンジニアリング・モデル選択・ハイパーパラメータ調整など機械学習パイプラインを自動化する技術の総称。AutoSklearn・H2O・NASなどが代表例で、専門知識なしに高性能モデルを構築できる。' },
  { term: '転移学習', aliases: ['transfer learning'], description: 'あるタスクで事前学習したモデルの知識を別のタスクに転用する学習パラダイム。少ないデータ・計算資源でも高性能を達成でき、BERTやVGGなどの事前学習モデルのファインチューニングが典型例。' },
  { term: 'ドメイン適応', aliases: ['domain adaptation'], description: 'ソースドメインで学習したモデルを異なる分布を持つターゲットドメインに適応させる技術。ラベルなしターゲットデータを使う教師なしドメイン適応と少量ラベルを使う方法がある。' },
  { term: 'データ拡張', aliases: ['data augmentation'], description: '既存の訓練データに変換（回転・フリップ・色変換など）を加えて人工的にデータを増やす手法。過学習を抑え汎化性能を向上させる効果があり、画像・音声・テキストで広く利用される。' },
  { term: '特徴量エンジニアリング', aliases: ['feature engineering'], description: '生データからモデルの予測性能を高めるための特徴量を設計・作成・選択するプロセス。ドメイン知識を活用した手動の特徴量設計とAutoMLによる自動化の両方がある。' },
  { term: '次元削減', aliases: ['dimensionality reduction'], description: '高次元データの情報を保ちながら低次元空間に写像する手法の総称。次元の呪いを緩和し可視化・計算効率化・ノイズ除去を目的とする。PCA・t-SNE・UMAPなどが代表的。' },
  { term: 'PCA', aliases: ['pca', '主成分分析', 'principal component analysis'], description: 'データの分散が最大となる直交基底（主成分）に射影することで次元を削減する手法。共分散行列の固有値分解によって導出され、寄与率を基準に次元数を選択する。' },
  { term: 't-SNE', aliases: ['t-sne', 't-distributed stochastic neighbor embedding'], description: '高次元データを2次元・3次元に可視化するための非線形次元削減手法。近い点は近く・遠い点は遠くなるよう確率的に配置を最適化し、クラスタ構造の視覚的把握に優れる。' },
  { term: 'UMAP', aliases: ['umap', 'uniform manifold approximation and projection'], description: 'トポロジー理論に基づく高速・スケーラブルな次元削減・可視化手法。t-SNEより計算が速くグローバル構造も保持しやすいとされ、大規模データの探索的分析に活用される。' },
  { term: 'k-means', aliases: ['k平均法', 'k-means clustering'], description: 'k個のクラスタ中心を繰り返し更新しデータを最近接クラスタに割り当てる教師なし分割クラスタリング手法。実装が簡単で高速だが、クラスタ数kの事前指定と球形クラスタの仮定が制限となる。' },
  { term: 'DBSCAN', aliases: ['dbscan', 'density-based spatial clustering of applications with noise'], description: '密度が高い領域を連結してクラスタを形成する密度ベースクラスタリング手法。クラスタ数の事前指定が不要で任意形状のクラスタを検出でき、外れ値をノイズとして明示的に扱う。' },
  { term: '決定木', aliases: ['decision tree'], description: '特徴量の閾値でデータを再帰的に分岐させてリーフに分類・回帰値を割り当てる木構造モデル。解釈性が高く前処理が少なくて済む一方、深い木は過学習しやすく剪定や最大深さ制限が必要。' },
  { term: 'ランダムフォレスト', aliases: ['random forest'], description: '多数の決定木をブートストラップサンプルと特徴量の無作為選択で構築し、多数決・平均で予測するアンサンブル手法。過学習が少なく特徴量重要度も得られ、実用的な性能と解釈性を兼ね備える。' },
  { term: '勾配ブースティング', aliases: ['gradient boosting', 'gbdt', 'gradient boosted decision trees'], description: '前の木の残差（勾配）を次の木が学習するように弱学習器を逐次追加するアンサンブル手法。表形式データで非常に高い性能を発揮し、XGBoostやLightGBMの実装で広く使われる。' },
  { term: 'XGBoost', aliases: ['xgboost', 'extreme gradient boosting'], description: '正則化・並列化・スパース対応・欠損値処理を備えた高速・高精度な勾配ブースティング実装。Kaggleなどデータコンペで多数の優勝解法に使われ、表形式データのデファクトスタンダードとなった。' },
  { term: 'LightGBM', aliases: ['lightgbm', 'light gradient boosting machine'], description: 'Microsoftが開発した葉優先成長とGOSS・EFBによる高速化技術を持つ勾配ブースティング実装。大規模データセットでXGBoostより学習が速く、カテゴリカル特徴量を直接扱える。' },
  { term: 'モデルレジストリ', aliases: ['model registry'], description: '訓練済みモデルのバージョン・メタデータ・評価指標を一元管理するMLOpsコンポーネント。MLflowやSageMaker Model Registryが代表例で、モデルのライフサイクル管理とデプロイの自動化を支援する。' },
  { term: 'Shadow Deployment', aliases: ['shadow deployment', 'シャドウデプロイ', 'shadow mode'], description: '新モデルを本番トラフィックのコピーに対して静かに実行し、実際の予測には影響を与えずパフォーマンスを測定する展開戦略。リスクなく新モデルの本番挙動を検証できる。' },
  { term: 'アンサンブル学習', aliases: ['ensemble learning'], description: '複数のモデルの予測を組み合わせて単一モデルより高い汎化性能を得る手法の総称。バギング・ブースティング・スタッキングが三大手法で、多様性のある弱学習器を組み合わせることで誤りを補完し合う。' },
  { term: 'バギング', aliases: ['bagging', 'bootstrap aggregating'], description: 'ブートストラップサンプリングで作った複数の訓練セットで独立に学習した複数モデルの予測を多数決・平均で集計するアンサンブル手法。分散を低減し過学習を抑制する効果がある。' },
  { term: 'サポートベクターマシン', aliases: ['svm', 'support vector machine'], description: 'クラス間のマージンを最大化する超平面を求める分類・回帰アルゴリズム。カーネルトリックによって非線形分類も可能で、汎化性能が高く小規模データや高次元データに強い。' },
  { term: 'ロジスティック回帰', aliases: ['logistic regression'], description: '線形結合にシグモイド関数を適用して二値分類確率を推定する統計的手法。解釈性が高く計算が軽量で、機械学習の基礎モデルとして広く使われる。L1/L2正則化と組み合わせて使うことが多い。' },
  { term: '多層パーセプトロン', aliases: ['mlp', 'multi-layer perceptron', '全結合ネットワーク'], description: '入力層・複数の全結合隠れ層・出力層からなる最も基本的なニューラルネットワーク。誤差逆伝播法で学習し、非線形活性化関数によって任意の関数を近似できる普遍近似定理が成り立つ。' },
  { term: '異常検知', aliases: ['anomaly detection', '外れ値検出', 'outlier detection'], description: '通常パターンから逸脱したデータポイントを検出するタスク。不正検知・製造ライン監視・ネットワーク侵入検知に利用される。Isolation Forest・Autoencoder・統計的手法などが使われる。' },
  { term: 'オートエンコーダ', aliases: ['autoencoder', 'ae'], description: '入力を低次元の潜在表現に圧縮するエンコーダと元のデータに復元するデコーダからなる自己教師あり学習モデル。次元削減・異常検知・ノイズ除去・特徴学習に活用される。' },
  { term: '対照学習', aliases: ['contrastive learning', 'simclr'], description: '類似サンプルを近く・異なるサンプルを遠くなるよう表現空間を学習する自己教師あり学習アプローチ。ラベルなしで汎用的な表現を獲得でき、SimCLR・MoCo・CLIPなどが代表的。' },
  { term: '連合学習', aliases: ['federated learning'], description: 'データを中央サーバーに集めず各クライアント端末でローカルに学習し、モデルのパラメータ更新のみを集約する分散機械学習手法。プライバシー保護と通信効率を両立する。' },
  { term: 'モデル蒸留', aliases: ['knowledge distillation', '知識蒸留'], description: '大きな教師モデルの知識を小さな生徒モデルに転移させてモデルを軽量化する手法。生徒モデルはハードラベルではなく教師モデルのソフトな確率分布を学習することで汎化性能を継承する。' },
  { term: '量子化', aliases: ['quantization', 'モデル量子化', 'int8量子化'], description: 'モデルの重みや活性化を32ビット浮動小数点より低いビット幅（INT8・FP16・4bitなど）で表現することで推論速度向上とメモリ削減を実現する圧縮技術。精度とのトレードオフを管理しながら適用する。' },
  { term: 'プルーニング', aliases: ['pruning', 'モデル剪定'], description: 'ニューラルネットワークの重要度の低いパラメータや構造を除去してモデルを軽量化する技術。マグニチュードベース剪定・構造的剪定などがあり、量子化とともにモデル圧縮の主要手法の一つ。' },
  { term: 'エッジAI', aliases: ['エッジai', 'edge ai', 'エッジ推論', 'on-device ai'], description: 'クラウドではなくスマートフォン・IoTデバイス・組み込みシステムなどエッジ端末上でAIモデルを推論させるアプローチ。低レイテンシ・プライバシー保護・オフライン動作が利点で、量子化・蒸留で実現される。' },
  { term: 'データドリフト', aliases: ['data drift', 'feature drift'], description: '本番環境での入力データの統計的特性が学習時と乖離していく現象。モデル性能の劣化につながるため継続的なモニタリングが必要で、MLOpsの重要な監視対象。' },
  { term: 'コンセプトドリフト', aliases: ['concept drift'], description: '入力特徴量の分布ではなく、入力と出力ラベルの関係（コンセプト）が時間とともに変化する現象。スパムフィルタなどで顕著で、継続的な再学習や適応型学習が必要となる。' },
  { term: 'SHAP', aliases: ['shap', 'shapley additive explanations', 'シャップ'], description: 'ゲーム理論のShapley値に基づいて各特徴量の予測への貢献度を算出する説明可能AIフレームワーク。モデル非依存でグローバル・ローカル両方の解釈が可能で、特徴量重要度の解析に広く使われる。' },
  { term: '説明可能AI', aliases: ['説明可能ai', 'xai', 'explainable ai', '解釈可能なai'], description: 'AIモデルの予測根拠を人間が理解できる形で提示する技術領域。規制対応・信頼構築・デバッグに不可欠で、SHAP・LIME・Grad-CAMなど多様な手法が研究・実用化されている。' },
  { term: 'オンライン学習', aliases: ['online learning', '逐次学習'], description: '新しいデータが来るたびにモデルを逐次更新し続ける学習パラダイム。バッチ学習に比べ最新データへの適応が速く、推薦システムや株価予測のような動的環境に適する。' },
  { term: 'モメンタム', aliases: ['momentum', 'sgd with momentum'], description: 'SGDに過去の勾配の移動平均を加えることで更新方向を安定化させる最適化技術。局所最小値を脱出しやすくなるとともに収束を加速させ、Adamなど高度な最適化手法の前身となった。' },
  { term: '残差接続', aliases: ['residual connection', 'skip connection', 'resnet'], description: '層の入力をその出力に直接足し合わせるショートカット接続。勾配の流れを改善して非常に深いネットワークの学習を可能にし、ResNetで導入されてTransformerにも採用されている。' },
  { term: '早期停止', aliases: ['early stopping'], description: 'バリデーション損失が一定エポック以上改善しなくなった時点で学習を打ち切る正則化技術。最適なエポック数を自動的に決定し過学習を防ぐシンプルかつ効果的な手法。' },
  { term: 'L1正則化', aliases: ['l1正則化', 'l1 regularization', 'lasso', 'l1ペナルティ'], description: '損失関数に重みの絶対値和を加えるペナルティ項。不要な特徴量の重みをゼロにするスパース性を誘導する効果があり、特徴量選択と正則化を同時に行えるLasso回帰が代表的応用。' },
  { term: 'L2正則化', aliases: ['l2正則化', 'l2 regularization', 'ridge', '重み減衰', 'weight decay'], description: '損失関数に重みの二乗和を加えるペナルティ項。全体的に重みを小さく保つことで過学習を抑制し、Ridge回帰が代表的。L1と組み合わせたElastic Netも使われる。' },
  { term: 'クラス不均衡', aliases: ['class imbalance', '不均衡データ'], description: '訓練データ内のクラス間のサンプル数に大きな偏りがある状態。不正検知・医療診断など少数クラスが重要な場面で問題となる。オーバーサンプリング・アンダーサンプリング・コスト感応学習で対処する。' },
  { term: 'SMOTE', aliases: ['smote', 'synthetic minority over-sampling technique'], description: '少数クラスのサンプル間を線形補間して人工的なサンプルを生成するオーバーサンプリング手法。単純な複製より多様性があり過学習を抑えながらクラス不均衡を緩和できる。' },
  { term: 'RLHF', aliases: ['rlhf', 'reinforcement learning from human feedback', '人間のフィードバックによる強化学習'], description: '人間の選好フィードバックから報酬モデルを学習し、それを使って言語モデルをPPOで微調整する技術。InstructGPTやChatGPTなどの高品質な対話AIの実現に中核的な役割を果たした。' },
  { term: 'DPO', aliases: ['dpo', 'direct preference optimization', '直接選好最適化'], description: 'RLHFの報酬モデル学習と強化学習を一体化し、選好ペアデータから直接言語モデルを最適化する手法。報酬モデルの学習が不要で実装がシンプルかつ安定し、RLHFの代替として急速に普及している。' },
  { term: 'LoRA', aliases: ['lora', 'low-rank adaptation', 'ローラ'], description: '大規模言語モデルの重みを凍結したまま低ランク行列の積からなる小さなアダプタ層だけを学習するパラメータ効率的なファインチューニング手法。計算コストと必要VRAMを大幅に削減できる。' },
  { term: '事前学習', aliases: ['pre-training', 'pretraining'], description: '大規模データで汎用的な表現を学習するフェーズ。言語モデルではマスク言語モデルや自己回帰タスクが使われ、その後のファインチューニングの土台となる。計算コストが非常に高く、学習済みモデルの公開が普及を促した。' },
  { term: 'Instruction Tuning', aliases: ['instruction tuning', 'インストラクションチューニング', '指示チューニング'], description: '指示文と回答のペアで事前学習済み言語モデルをファインチューニングし、ユーザーの指示に従った回答を生成できるよう訓練する手法。InstructGPT・Alpaca・Flanが代表的。' },
  { term: 'プロンプトエンジニアリング', aliases: ['prompt engineering'], description: '大規模言語モデルから望ましい出力を引き出すためにプロンプト（入力テキスト）を設計・最適化する技術。Few-shot Prompting・Chain-of-Thought・Role Promptingなど多様な技法がある。' },
  { term: '線形回帰', aliases: ['linear regression'], description: '入力特徴量の線形結合で連続値ターゲットを予測する最も基本的な回帰モデル。最小二乗法で閉形式解が得られ、係数の解釈性が高い。L1/L2正則化を加えたLasso/Ridge回帰に発展する。' },
  { term: 'Gemini 2.5', aliases: ['gemini 2.5', 'google gemini 2.5'], description: 'GoogleのGemini 2.5系モデル群。' },
  { term: 'Gemini 2.5 Pro', aliases: ['gemini 2.5 pro', 'google gemini 2.5 pro'], description: '複雑な推論や長文コンテキスト処理向けのGemini 2.5上位モデル。' },
  { term: 'Gemini 2.5 Flash', aliases: ['gemini 2.5 flash', 'google gemini 2.5 flash'], description: '速度とコスト効率を重視したGemini 2.5モデル。' },
  { term: 'Gemini 2.5 Flash-Lite', aliases: ['gemini 2.5 flash-lite', 'google gemini 2.5 flash-lite'], description: '低遅延ワークロード向けの軽量なGemini 2.5 Flash派生モデル。' },
  { term: 'Gemini 2.5 Pro/Flash/Flash-Lite', aliases: ['gemini 2.5 pro/flash/flash-lite', 'gemini 2.5 pro / flash / flash-lite', 'google gemini 2.5 pro/flash/flash-lite', 'google gemini 2.5 pro / flash / flash-lite'], description: 'Gemini 2.5系主要モデルをまとめて表す短縮表記。' },
  { term: 'Cohere Command A', aliases: ['cohere command a'], description: 'Cohereの対話・テキスト生成向けモデル。' },
  { term: 'Llama 4 Maverick', aliases: ['llama 4 maverick', 'meta llama 4 maverick'], description: 'Meta Llama 4系モデルの一つ。' },
  { term: 'Llama 4 Scout', aliases: ['llama 4 scout', 'meta llama 4 scout'], description: 'Meta Llama 4系モデルの一つ。' },
  { term: 'Meta Llama 4 Maverick/Scout', aliases: ['meta llama 4 maverick/scout', 'meta llama 4 maverick / scout'], description: 'Meta Llama 4の主要モデルをまとめて表す短縮表記。' },
  { term: 'gpt-oss', aliases: ['openai gpt-oss'], description: 'OpenAIのgpt-oss系オープンウェイトモデル群。' },
  { term: 'gpt-oss-120b', aliases: ['openai gpt-oss-120b'], description: 'gpt-oss系の120Bパラメータモデル。' },
  { term: 'gpt-oss-20b', aliases: ['openai gpt-oss-20b'], description: 'gpt-oss系の20Bパラメータモデル。' },
  { term: 'OpenAI gpt-oss-120b/20b', aliases: ['openai gpt-oss-120b/20b', 'gpt-oss-120b/20b', 'openai gpt-oss-120b / 20b'], description: 'OpenAI gpt-oss系主要モデルをまとめて表す短縮表記。' },
  { term: 'Grok 4', aliases: ['grok 4', 'xai grok 4'], description: 'xAIのGrok 4系モデル。' },
  { term: 'Grok 4.1 Fast', aliases: ['grok 4.1 fast', 'xai grok 4.1 fast'], description: '応答速度を重視したGrok 4.1系モデル。' },
  { term: 'Grok Code Fast 1', aliases: ['grok code fast 1', 'xai grok code fast 1'], description: 'コード生成やコーディング支援向けのxAI高速モデル。' },
  { term: 'Grok 4/4.1 Fast/Code Fast 1', aliases: ['grok 4/4.1 fast/code fast 1', 'grok 4 / 4.1 fast / code fast 1', 'grok 4/4.1/grok code fast 1', 'xai grok 4/4.1/grok code fast 1'], description: 'Grok系主要モデルをまとめて表す短縮表記。' },
  { term: 'Cohere Embed 4', aliases: ['cohere embed 4'], description: 'テキストや画像から埋め込みベクトルを生成するCohereのモデル。' },
  { term: 'Embed English 3', aliases: ['embed english 3', 'cohere embed english 3'], description: '英語テキスト向けに最適化された埋め込みモデル。' },
  { term: 'Embed Multilingual 3', aliases: ['embed multilingual 3', 'cohere embed multilingual 3'], description: '多言語テキスト向けに最適化された埋め込みモデル。' },
  { term: 'Cohere Rerank 3.5', aliases: ['cohere rerank 3.5'], description: '検索や取得結果の再順位付けに使うCohereのrerankモデル。' },
  { term: '高精度', description: '誤差が小さく正確さが高い状態です。' },
];
