// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: dotnet (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // dotnet (70), visual-studio (30)
  { term: 'Visual Studio', aliases: ['visual studio'], description: 'Microsoft が提供する統合開発環境です。.NET、C++、各種デスクトップ、Web、クラウド開発を幅広く支援します。' },
  { term: 'Integrated Development Environment', aliases: ['integrated development environment'], description: 'コード編集、ビルド、デバッグ、テストなどを一体的に行える開発環境です。Visual Studio はその代表的な IDE の一つです。' },
  { term: 'Solution', aliases: ['solution'], description: 'Visual Studio で複数プロジェクトをまとめるコンテナです。.sln ファイルで表され、プロジェクト群や構成情報をまとめます。' },
  { term: 'Project', aliases: ['project'], description: 'アプリやライブラリなど、ビルド可能な単位です。ソリューションの中に含まれます。' },
  { term: '.sln file', description: 'Visual Studio の solution ファイルです。ソリューション内のプロジェクト構成などを整理するために使われます。' },
  { term: '.suo file', description: 'Visual Studio のユーザー単位設定などを保持する solution user options ファイルです。ブレークポイントなどユーザー依存情報を含みます。' },
  { term: 'Solution Explorer', aliases: ['solution explorer'], description: 'ソリューション、プロジェクト、ファイルを階層的に表示するビューです。開発中の資産を俯瞰しやすくなります。' },
  { term: 'Solution Folder', aliases: ['solution folder'], description: 'Visual Studio 内だけで使う仮想フォルダで、プロジェクトを論理的にグループ化するために使います。実際のフォルダ構造とは別です。' },
  { term: 'Solution Filter', aliases: ['solution filter'], description: '大きな solution のうち必要な一部 project だけを読み込むための仕組みです。読み込み時間や操作性の改善に役立ちます。' },
  { term: 'Project Properties', aliases: ['project properties'], description: '対象プロジェクトのビルド設定、デバッグ設定、参照などを定義するプロパティ群です。ビルド挙動や出力結果に大きく影響します。' },
  { term: 'Build Configuration', aliases: ['build configuration'], description: 'Debug や Release など、ビルド時の構成を切り替える設定です。最適化やデバッグ情報の有無が変わります。' },
  { term: 'Debug Configuration in Visual Studio', aliases: ['debug configuration in visual studio'], description: 'デバッグ実行時に使う設定群です。起動対象、引数、シンボル情報などが関わります。' },
  { term: 'Debugger', aliases: ['debugger'], description: '実行中のプログラムを停止、追跡、変数確認するための機能です。Visual Studio の代表的な生産性機能の一つです。' },
  { term: 'Breakpoint', aliases: ['breakpoint'], description: '指定した行で実行を停止させる印です。Visual Studio のデバッガーで最も基本的な機能です。' },
  { term: 'Conditional Breakpoint', aliases: ['conditional breakpoint'], description: '特定条件を満たしたときだけ停止するブレークポイントです。不要な停止を減らし、狙ったケースを追いやすくなります。' },
  { term: 'Hit Count Breakpoint', aliases: ['hit count breakpoint'], description: '何回目の通過で停止するかを指定できるブレークポイントです。繰り返し処理の調査に便利です。' },
  { term: 'Solid Red Circle', aliases: ['solid red circle'], description: 'Visual Studio のデバッガーで、正しく設定されたブレークポイントを示す状態です。' },
  { term: 'Hollow Circle', aliases: ['hollow circle'], description: '無効、または警告付きで設定されたブレークポイントを示す状態です。シンボル未読込などの問題がある場合に見られます。' },
  { term: 'Symbols', aliases: ['symbols'], description: 'デバッグ時にソースコードと実行コードを対応づけるための情報です。ブレークポイントが効かない原因としてよく登場します。' },
  { term: 'Watch Window', aliases: ['watch window'], description: '特定式や変数を監視するためのデバッグウィンドウです。Visual Studio ではデバッグ中に表示されます。' },
  { term: 'Locals Window', aliases: ['locals window'], description: '現在スコープ内のローカル変数を表示するデバッグウィンドウです。Visual Studio の変数調査でよく使われます。' },
  { term: 'Autos Window', aliases: ['autos window'], description: '現在行や直前行に関係する変数を自動で表示するデバッグウィンドウです。調査の導入として便利です。' },
  { term: 'Break Mode', aliases: ['break mode'], description: 'Visual Studio デバッガーが実行を停止している状態です。Watch など一部ウィンドウはこのとき利用可能になります。' },
  { term: 'Immediate Window', aliases: ['immediate window'], description: 'デバッグ中に式評価や簡単な命令実行を行えるウィンドウです。変数確認や一時的な操作に使われます。' },
  { term: 'IntelliSense', aliases: ['intellisense'], description: 'コード補完、候補提示、シグネチャ表示などを行う支援機能です。Visual Studio の生産性を支える代表機能です。' },
  { term: 'Code Completion', aliases: ['code completion'], description: '入力途中の識別子や構文候補を補完する機能です。IntelliSense の中心機能の一つです。' },
  { term: 'Design Surface', aliases: ['design surface'], description: 'XAML やフォームを視覚的に編集できるデザイナ画面です。Visual Studio で UI を視覚的に調整するときに使われます。' },
  { term: 'XAML Designer', aliases: ['xaml designer'], description: 'XAML ベース UI を Visual Studio 上で視覚的に編集するための機能です。WPF などで利用されます。' },
  { term: 'Developer Command Prompt', aliases: ['developer command prompt'], description: 'Visual Studio や .NET の開発用コマンドを実行しやすいコマンド環境です。ビルドや設定初期化で使うことがあります。' },
  { term: 'Visual Studio Extensibility SDK', aliases: ['visual studio extensibility sdk'], description: 'Visual Studio 拡張開発向けの SDK です。近年は IDE のメインプロセス外で動く拡張の方向も案内されています。' },
  { term: '.NET', aliases: ['.net'], description: '無料、クロスプラットフォーム、オープンソースの開発プラットフォームです。Web、デスクトップ、モバイル、クラウド、IoT など多様な用途に使えます。' },
  { term: '.NET Platform', aliases: ['.net platform'], description: 'C#、F#、Visual Basic など複数言語とライブラリ、ランタイムを含む .NET の全体を指す言い方です。' },
  { term: 'Cross-platform', aliases: ['cross-platform'], description: 'Windows、Linux、macOS など複数 OS で動かせる性質です。.NET の大きな特徴の一つです。' },
  { term: 'Open Source', aliases: ['open source'], description: 'ソースコードが公開され、開発へ参加できる性質です。.NET と WPF、WinForms なども現代ではオープンソース実装が案内されています。' },
  { term: '.NET SDK', aliases: ['.net sdk'], description: 'アプリの開発、ビルド、実行、公開に必要なツール一式です。CLI も含まれます。' },
  { term: 'SDK-style project', aliases: ['sdk-style project'], description: '現代の .NET で使われる簡潔な project 記述形式です。PackageReference や target framework を csproj に直接書く流れと相性がよいです。' },
  { term: 'dotnet CLI', aliases: ['dotnet cli'], description: 'dotnet コマンドでビルド、実行、パッケージ操作などを行う CLI です。.NET 開発の基本ツールです。' },
  { term: 'dotnet restore', description: 'NuGet パッケージ依存を復元するコマンドです。クローン直後やビルド前に重要になります。' },
  { term: 'dotnet build', description: '.NET プロジェクトをビルドする CLI コマンドです。MSBuild ベースで動作します。' },
  { term: 'dotnet run', description: 'ビルドと実行をまとめて行える CLI コマンドです。サンプルや検証でよく使われます。' },
  { term: 'dotnet publish', description: '配布用成果物を生成する CLI コマンドです。デプロイや配布準備で使います。' },
  { term: 'MSBuild', aliases: ['msbuild'], description: '.NET や Visual Studio プロジェクトをビルドするための基盤です。NuGet パッケージ生成でも利用されます。' },
  { term: 'Runtime', aliases: ['runtime'], description: 'アプリを実行するための基盤部分です。.NET では SDK とランタイムを分けて考えることがあります。' },
  { term: 'Target Framework', aliases: ['target framework'], description: 'アプリがどの .NET 実行環境向けに作られているかを示す指定です。互換性や利用可能 API に影響します。' },
  { term: 'Multi-targeting', aliases: ['multi-targeting'], description: '一つのプロジェクトやパッケージで複数 target framework に対応することです。再利用ライブラリでよく使われます。' },
  { term: 'NuGet', aliases: ['nuget'], description: '.NET のパッケージマネージャーです。ライブラリの作成、共有、利用を支えます。' },
  { term: 'NuGet Package', aliases: ['nuget package'], description: '.nupkg 形式で配布される .NET ライブラリや関連資産の単位です。DLL やメタデータなどを含みます。' },
  { term: 'NuGet Package Manager', aliases: ['nuget package manager'], description: 'Visual Studio 上で NuGet パッケージを追加、更新、削除するための UI や機能群です。' },
  { term: 'Package Manager Console', aliases: ['package manager console'], description: 'Visual Studio on Windows に組み込まれた PowerShell ベースの NuGet 管理コンソールです。VS Code には含まれません。' },
  { term: 'PackageReference', aliases: ['packagereference'], description: 'プロジェクトファイルに直接パッケージ依存を書く現代的な NuGet 管理方式です。.NET Core 系では基本的にこちらが使われます。' },
  { term: 'packages.config', description: 'NuGet の旧来の依存管理形式です。現在は legacy 向けで、積極的な新規推奨はされていません。' },
  { term: 'project.assets.json', description: 'NuGet の依存グラフ解決結果を保持する中間ファイルです。PackageReference 利用時に生成されます。' },
  { term: 'C#', aliases: ['c#'], description: '.NET の代表的な言語で、オブジェクト指向を土台にしつつ関数型的要素や高効率な機能も持つクロスプラットフォーム言語です。' },
  { term: 'Object-oriented programming in C#', aliases: ['object-oriented programming in c#'], description: 'C# はオブジェクト指向言語であり、抽象化、カプセル化、継承、ポリモーフィズムが基本原則として説明されています。' },
  { term: 'Visual Basic on .NET', aliases: ['visual basic on .net'], description: '.NET で使える Visual Basic 言語です。Microsoft Learn では .NET が C#、F#、Visual Basic など複数言語を支えると案内されています。' },
  { term: 'F#', aliases: ['f#'], description: '.NET 上で動く関数型寄りの言語です。.NET プラットフォームの多言語性を示す代表例です。' },
  { term: 'Common Language Infrastructure', aliases: ['common language infrastructure'], description: 'CLI は C# と .NET の標準化文脈で登場する共通実行基盤概念です。.NET の標準仕様とも関係します。' },
  { term: 'ECMA standard for C#', aliases: ['ecma standard for c#'], description: 'C# 言語仕様は Ecma International を通じて標準化されています。.NET の標準化理解で重要です。' },
  { term: 'ASP.NET Core', aliases: ['asp.net core'], description: '高速、安全、クロスプラットフォーム、クラウド向けの Web アプリとサービスを作るための .NET フレームワークです。' },
  { term: 'ASP.NET', aliases: ['asp.net'], description: 'ASP.NET Core より前からある Microsoft の Web 開発基盤です。公式 overview では ASP.NET Core をその代替として位置づけています。' },
  { term: 'Web API', aliases: ['web api'], description: 'ASP.NET 系で HTTP ベースの API を作る考え方や機能群です。Web サービス構築の中心になります。' },
  { term: 'Razor Pages', aliases: ['razor pages'], description: 'ASP.NET Core でページ中心に Web アプリを構築する方式です。簡潔なページ単位実装に向きます。' },
  { term: 'MVC in ASP.NET Core', aliases: ['mvc in asp.net core'], description: 'Model-View-Controller パターンで ASP.NET Core アプリを作る方式です。画面分離や責務整理に向きます。' },
  { term: 'Middleware', aliases: ['middleware'], description: 'ASP.NET Core リクエストパイプラインを構成する処理単位です。認証、ログ、例外処理などを組み込みます。' },
  { term: 'Routing in ASP.NET Core', aliases: ['routing in asp.net core'], description: 'URL と処理を結びつける仕組みです。Web アプリや API の入口設計を担います。' },
  { term: 'Dependency Injection in .NET', aliases: ['dependency injection in .net'], description: 'ASP.NET Core を含む .NET アプリでは DI を前提に構成することが多く、サービス登録や注入が基本になります。' },
  { term: 'Configuration in .NET', aliases: ['configuration in .net'], description: 'JSON、環境変数など複数ソースから設定を読み込む考え方です。ASP.NET Core で特に重要です。' },
  { term: 'Entity Framework Core', aliases: ['entity framework core'], description: '.NET 向けの ORM です。LINQ、変更追跡、更新、スキーマ migration をサポートします。' },
  { term: 'EF Core', aliases: ['ef core'], description: 'Entity Framework Core の略称です。.NET データアクセスの代表的技術です。' },
  { term: 'DbContext', aliases: ['dbcontext'], description: 'EF Core でデータアクセスや変更追跡の中心になるクラスです。エンティティ集合とデータベースを結びつけます。' },
  { term: 'DbSet', aliases: ['dbset'], description: 'EF Core でエンティティ集合を表すプロパティです。どの C# エンティティが DB に対応するかを知らせます。' },
  { term: 'Change Tracking', aliases: ['change tracking'], description: 'EF Core がエンティティ変更を追跡する機能です。SaveChanges() 時に必要な INSERT、UPDATE、DELETE を判断します。' },
  { term: 'SaveChanges', aliases: ['savechanges'], description: 'EF Core で追跡中の変更をデータベースへ反映するメソッドです。変更追跡と対になる中心操作です。' },
  { term: 'Schema Migrations', aliases: ['schema migrations'], description: 'EF Core がサポートするスキーマ変更管理機能です。コードから DB 変更履歴を扱いやすくします。' },
  { term: 'Database Provider', aliases: ['database provider'], description: 'EF Core で使う DB 種別ごとのパッケージです。SQL Server や SQLite などの provider を選んで追加します。' },
  { term: 'Microsoft.EntityFrameworkCore.SqlServer', aliases: ['microsoft.entityframeworkcore.sqlserver'], description: 'SQL Server 用の EF Core provider パッケージです。dotnet add package で追加する例が公式にあります。' },
  { term: 'Microsoft.EntityFrameworkCore.Sqlite', aliases: ['microsoft.entityframeworkcore.sqlite'], description: 'SQLite 用の EF Core provider パッケージです。WPF や小規模アプリのサンプルでもよく登場します。' },
  { term: 'Microsoft.EntityFrameworkCore.Tools', aliases: ['microsoft.entityframeworkcore.tools'], description: 'EF Core の Package Manager Console ツールを取得するためのパッケージです。' },
  { term: 'Lazy Loading', aliases: ['lazy loading'], description: '必要になるまで関連データを読み込まない考え方です。EF Core の Proxies パッケージで支援されることがあります。' },
  { term: 'LINQ', aliases: ['linq'], description: 'Language Integrated Query の略で、C# 言語から統合的に問い合わせを書ける仕組みです。複雑な IQueryable provider は SQL などへ翻訳できます。' },
  { term: 'IQueryable', aliases: ['iqueryable'], description: 'LINQ クエリを式として外部 provider へ渡せる仕組みです。EF Core はこれを SQL へ翻訳できます。' },
  { term: 'Object Initializer', aliases: ['object initializer'], description: 'オブジェクト生成と同時にプロパティ初期化を書く C# の構文です。C# how-to の代表例として紹介されています。' },
  { term: 'Extension Member', aliases: ['extension member'], description: '既存型へ機能を追加する C# の拡張メンバーです。C# how-to で一般的手法として案内されています。' },
  { term: 'Enum Extension Method', aliases: ['enum extension method'], description: 'enum 型へ新しい振る舞いを追加する拡張メンバーの使い方です。C# how-to に例があります。' },
  { term: 'Record', aliases: ['record'], description: 'データ中心の型定義に向いた C# の型概念です。class や struct と並んで how-to の分類に登場します。' },
  { term: 'Struct', aliases: ['struct'], description: '値型として扱う C# の型です。class や record と並ぶ主要型です。' },
  { term: 'Property', aliases: ['property'], description: 'C# でデータの get、set を抽象化して扱うメンバーです。自動実装プロパティなどが一般的です。' },
  { term: 'Constant in C#', aliases: ['constant in c#'], description: '固定値を定義する const などの考え方です。How-to セクションでも取り上げられています。' },
  { term: 'ToString override', aliases: ['tostring override'], description: 'オブジェクトの文字列表現を提供する一般的な C# 実践です。How-to でも代表例として紹介されています。' },
  { term: 'WPF', aliases: ['wpf'], description: 'Windows Presentation Foundation の略で、.NET 向けのデスクトップ UI フレームワークです。XAML、データバインディング、アニメーションなどを備えます。' },
  { term: 'Windows Presentation Foundation', aliases: ['windows presentation foundation'], description: '解像度非依存でベクターベース描画を使う .NET デスクトップ UI フレームワークです。' },
  { term: 'WinForms', aliases: ['winforms'], description: 'Windows Forms の略で、.NET デスクトップアプリ向けの UI フレームワークです。WPF と並んで .NET デスクトップの主要選択肢です。' },
  { term: 'Windows Forms', aliases: ['windows forms'], description: 'イベント駆動の Windows デスクトップ UI フレームワークです。現在はオープンソース実装としても案内されています。' },
  { term: 'XAML', aliases: ['xaml'], description: 'Extensible Application Markup Language の略で、宣言的に UI オブジェクトやプロパティを定義できる言語です。WPF や各種 XAML 系 UI 技術で使われます。' },
  { term: 'Declarative Language', aliases: ['declarative language'], description: 'XAML のように、手順よりも構造や宣言を表現する言語の性質です。UI 定義で特に有効です。' },
  { term: 'Code-behind', aliases: ['code-behind'], description: 'XAML で宣言した UI に対してイベント処理や制御ロジックを書くコード側ファイルです。XAML とペアで使われます。' },
  { term: 'Data Binding', aliases: ['data binding'], description: 'UI とデータを結びつける仕組みです。WPF の中核機能の一つです。' },
  { term: 'Styles and Templates', aliases: ['styles and templates'], description: 'WPF で見た目や再利用可能な UI 表現を管理する仕組みです。UI 一貫性や再利用に役立ちます。' },
  { term: 'Device-independent Pixel', aliases: ['device-independent pixel'], description: 'WPF の描画基準単位で、解像度に依存しない表示を支える考え方です。1/96 インチを基準に説明されています。' },
  { term: '.NET Desktop Workload', aliases: ['.net desktop workload'], description: 'Visual Studio で WPF や WinForms を扱うために必要なワークロードです。EF Core の WPF チュートリアルでも前提として示されています。' },
];
