// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: it (5/6)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_005: ReadonlyArray<GlossaryEntry> = [
  { term: 'ピアレビュー', aliases: ['peer review'], description: '同じ立場の開発者同士が互いのコード・ドキュメントを確認するレビュー活動。' },
  { term: '機能単体テスト', aliases: ['functional unit test'], description: '機能単位でインプット・アウトプットを検証するテスト。モジュール外の依存はモックで代替する。' },
  { term: 'UI境界', aliases: ['ui境界', 'ui boundary'], description: 'UIとビジネスロジックの境界。テスト時にUI境界でモック化することでロジックを独立してテストできる。' },
  { term: 'テストカバレッジ', aliases: ['test coverage'], description: 'テストがソースコードをどれだけ網羅しているかを示す指標。C0・C1・C2などがある。' },
  { term: 'C0基準', aliases: ['c0基準', 'c0 criterion'], description: 'ステートメントカバレッジとも呼ばれる。すべての命令文を少なくとも1回実行するテスト基準。' },
  { term: 'C1基準', aliases: ['c1基準', 'c1 criterion'], description: 'ブランチカバレッジとも呼ばれる。すべての分岐（T/F）を少なくとも1回実行するテスト基準。' },
  { term: 'C2基準', aliases: ['c2基準', 'c2 criterion'], description: '条件カバレッジとも呼ばれる。すべての条件式のT/Fの組み合わせを網羅するテスト基準。' },
  { term: 'ラインカバレッジ', aliases: ['line coverage'], description: '実行されたソースコードの行数の割合。C0基準と対応する最も基本的なカバレッジ指標。' },
  { term: 'ブランチカバレッジ', aliases: ['branch coverage'], description: '分岐の各パス（真・偽）が実行された割合。C1基準と対応するカバレッジ指標。' },
  { term: 'コンディションカバレッジ', aliases: ['condition coverage'], description: '条件式内の個々の条件のT/Fが実行された割合。C2基準と対応するカバレッジ指標。' },
  { term: 'xUnit', aliases: ['xunit'], description: 'JUnit・NUnit・PyTestなどのユニットテストフレームワーク群の総称。' },
  { term: 'GUIテスト', aliases: ['guiテスト', 'gui testing'], description: 'グラフィカルユーザーインターフェースを自動的に操作して検証するテスト。Selenium・Playwrightが代表例。' },
  { term: 'Nスイッチカバレッジ', aliases: ['nスイッチカバレッジ', 'n-switch coverage'], description: '状態遷移テストにおいてN回の状態遷移シーケンスを網羅する基準。' },
  { term: '組合せ爆発', aliases: ['combinatorial explosion'], description: 'テスト条件の組み合わせが指数関数的に増加する問題。直交表やオールペア法で緩和する。' },
  { term: '直交表', aliases: ['orthogonal array'], description: '統計的直交性を保ちながらテストケースを最小化するための実験計画法由来の表。' },
  { term: 'オールペア法', aliases: ['all-pairs method'], description: 'すべての2つの入力パラメータの組み合わせを網羅するテスト設計技法。Pairwise Testingとも呼ばれる。' },
  { term: 'サイクロマティック数', aliases: ['cyclomatic complexity'], description: 'プログラムの制御フローグラフの複雑度を示す指標。分岐数+1で算出しテスト数の目安となる。' },
  { term: '品質/テスト計画書', aliases: ['quality and test plan'], description: 'テストの目的・範囲・スケジュール・品質基準・役割を定義した計画ドキュメント。' },
  { term: 'レビュー密度', aliases: ['review density'], description: 'レビューしたドキュメント・コードに対して発見した指摘事項数の比率。品質指標として使用する。' },
  { term: 'バグ密度', aliases: ['bug density'], description: 'コード規模（LOCやFP）に対するバグ数の比率。品質水準を評価する指標。' },
  { term: '仕様バグ', aliases: ['specification bug'], description: '要件定義・設計書に起因するバグ。実装は仕様通りだがその仕様自体が誤っている問題。' },
  { term: '冗長表現', aliases: ['redundant expression'], description: '不必要な繰り返しや重複のある表現。コードやドキュメントでDRY原則に反する状態。' },
  { term: 'リアクティブプログラミング', aliases: ['reactive programming'], description: '非同期データストリームとそれに対する宣言的な処理を中心とするプログラミングパラダイム。' },
  { term: 'ソフトウェアコンポーネント', aliases: ['software component'], description: '再利用可能な機能単位として設計されたソフトウェアの構成要素。' },
  { term: 'ソフトウェアフレームワーク', aliases: ['software framework'], description: 'アプリケーション開発の骨格・共通機能・規約を提供するライブラリの集合体。Springなどが代表例。' },
  { term: '共通部品', aliases: ['common components'], description: '複数の機能・モジュールで再利用される共有コンポーネント・ライブラリ。' },
  { term: '頑健性', aliases: ['ロバストネス', 'robustness'], description: 'システムが異常入力・障害・予期しない状況に対して適切に振る舞う性質。ロバストネスとも呼ぶ。' },
  { term: '保守性向上', aliases: ['maintainability improvement'], description: 'コードの可読性・変更容易性・テスト容易性を高めてメンテナンスコストを削減する取り組み。' },
  { term: '品質ロスコスト', aliases: ['quality loss cost'], description: '品質問題（バグ修正・手戻り・顧客対応）によって発生するコスト。予防コストと対比される概念。' },
  { term: 'コーディング', aliases: ['coding'], description: '設計仕様に基づいてソースコードを記述する作業。製造工程の中心となる活動。' },
  { term: 'スケルトン実装', aliases: ['skeleton implementation'], description: 'クラス・メソッドの骨格だけを先に実装し後でロジックを埋める手法。TDDや設計確認に有効。' },
  { term: 'クラスコメント', aliases: ['class comment'], description: 'クラスの目的・責務・利用方法を記述したソースコードのコメント。JavadocやJSDocで文書化する。' },
  { term: 'メソッドコメント', aliases: ['method comment'], description: 'メソッドのパラメータ・戻り値・副作用・例外を記述したソースコードのコメント。' },
  { term: 'シグニチャ', aliases: ['signature'], description: 'メソッド・関数の名前・パラメータ型・戻り値型を示すインターフェース定義。' },
  { term: 'TODOコメント', aliases: ['todoコメント', 'todo comment'], description: '後で対応が必要な箇所をコードに残すコメント。技術的負債の記録や追跡に使われる。' },
  { term: '名前空間設計', aliases: ['namespace design'], description: 'パッケージ・モジュール・クラスなどの名前空間を体系的に設計する活動。' },
  { term: 'URL設計', aliases: ['url設計', 'url design'], description: 'Webアプリケーションのエンドポイントを意味のある一貫した体系で設計すること。' },
  { term: 'Lintツール', aliases: ['lintツール', 'lint tool'], description: 'ソースコードの文法エラー・スタイル違反・潜在的バグを静的解析で検出するツールの総称。' },
  { term: 'コード解析ツール', aliases: ['code analysis tool'], description: 'ソースコードを静的または動的に解析して品質・セキュリティ・複雑度を評価するツール群。' },
  { term: 'Checkstyle', aliases: ['checkstyle'], description: 'Javaコードのコーディング規約違反を自動検出する静的解析ツール。' },
  { term: 'FindBugs', aliases: ['findbugs'], description: 'Javaコードのバグパターンを静的解析で検出するツール。SpotBugsとして後継が続いている。' },
  { term: 'PMD', aliases: ['pmd'], description: 'Javaなど複数言語のコードの問題（冗長・未使用変数・複雑度）を検出する静的解析ツール。' },
  { term: 'StyleCop', aliases: ['stylecop'], description: 'C#/.NETコードのスタイル・一貫性をチェックするMicrosoftの静的解析ツール。' },
  { term: 'FxCop', aliases: ['fxcop'], description: '.NETアセンブリのデザイン・セキュリティ・パフォーマンス問題を検出するMicrosoftの静的解析ツール。' },
  { term: 'コードメトリクス', aliases: ['code metrics'], description: 'ソースコードの複雑度・結合度・凝集度などを定量化した品質指標の集合。' },
  { term: 'メソッド数', aliases: ['method count'], description: 'クラス・モジュールが持つメソッドの総数。過多はSRP違反や設計問題の兆候となる。' },
  { term: '行数', aliases: ['line count'], description: 'ソースコードの物理的な行数。規模の粗い指標だが保守性の参考になる。' },
  { term: 'テストドライバ', aliases: ['test driver'], description: 'テスト対象モジュールを呼び出して実行するテスト用の上位プログラム。' },
  { term: 'モックサーバ', description: 'APIや外部サービスの代わりにテスト用の擬似レスポンスを返すサーバ。' },
  { term: 'テストデータ', aliases: ['test data'], description: 'テスト実行に使用するサンプル入力データ・DBデータ。正常・異常・境界値を網羅する。' },
  { term: 'テストシナリオ', aliases: ['test scenario'], description: 'テストの流れ・条件・期待結果を記述したドキュメント。テストケースの集合体。' },
  { term: '障害管理フロー', aliases: ['defect management flow'], description: '発見されたバグ・障害を記録・分析・修正・確認・クローズするプロセスのフロー。' },
  { term: '品質管理計画', aliases: ['quality management plan'], description: 'プロジェクトにおける品質目標・測定指標・レビュー基準・テスト計画を定めた計画書。' },
  { term: 'レビュー実施計画', aliases: ['review execution plan'], description: 'いつ・誰が・何を・どの基準でレビューするかを定めた計画。' },
  { term: '障害分析方法', aliases: ['defect analysis method'], description: '発見したバグ・障害の根本原因を特定するための分析手法。5Whys・魚の骨図などが使われる。' },
  { term: '内部レビュー', aliases: ['internal review'], description: '開発チーム内部でコード・ドキュメントを確認するレビュー活動。' },
  { term: 'ユーザーレビュー', aliases: ['user review'], description: '実際のユーザーや顧客代表が成果物を確認するレビュー活動。要件の確認や使用性の検証を目的とする。' },
  { term: '査読', aliases: ['peer inspection'], description: 'ドキュメントやコードを専門家が詳細に確認する公式なレビュー活動。' },
  { term: 'Type Safe Enumパターン', aliases: ['type safe enumパターン', 'type safe enum pattern'], description: '型安全な列挙型をクラスで実装するパターン。Javaの旧enumに替わるアプローチとして使われた。' },
  { term: '変数再利用', aliases: ['variable reuse'], description: '一つの変数を異なる目的で再利用すること。可読性・保守性を下げるアンチパターン。' },
  { term: '実行円滑性', aliases: ['execution smoothness'], description: 'コードや処理が滑らかに・途切れなく実行される性質。' },
  { term: '分解容易性', aliases: ['decomposability'], description: 'システムをコンポーネント・モジュールに分割しやすい設計上の性質。テスタビリティとも関連する。' },
  { term: '単純性', aliases: ['simplicity'], description: 'システム・コードが不必要な複雑さを持たないシンプルな設計の性質。KISS原則と関連する。' },
  { term: '理解容易性', aliases: ['understandability'], description: 'コード・設計・ドキュメントが他者に理解しやすい性質。可読性とも関連する品質特性。' },
  { term: '安定性', aliases: ['高い安定性'], description: 'システムや運用が大きく揺れず、同じ条件で継続して期待どおりに動く性質です。高い安定性は障害やばらつきを減らし、運用負荷を抑えます。' },
  { term: '複雑さ', description: '構造や依存関係、ルール、例外が多く、理解、変更、運用が難しくなっている度合いです。複雑さが増すほどバグ、手戻り、教育コストが増えやすくなります。' },
  { term: '美しさ', aliases: ['美しい'], description: '設計やコード、UIが無理なく整い、筋が通っていて、余計な複雑さが少ないと感じられる性質です。見た目だけでなく、構造の自然さや一貫性も含みます。' },
  { term: 'スケール', aliases: ['scale', 'スケーラビリティ'], description: 'システムや組織が規模の増大に対応できる能力。水平スケール（サーバ追加）と垂直スケール（サーバ強化）があり、成長戦略に応じて選択する。' },
  { term: '安定供給', description: 'システムやサービスを中断なく継続的に提供し続けること。SLAや可用性目標を達成するための運用・設計が求められる。' },
  { term: '良いコード', description: '可読性・保守性・テスト容易性・拡張性を兼ね備えたコード。チームの共通認識によって基準は異なるが、SOLID原則やDRYなどが指針となる。' },
  { term: '既存機能', description: 'すでにシステムに実装されている機能。新機能開発の際には既存機能との整合性や影響範囲を確認することが重要。' },
  { term: '標準機能', description: 'プラットフォームやフレームワークがデフォルトで提供する機能。独自実装より標準機能を活用することで保守コストを下げられる。' },
  { term: 'エンジニアリング', aliases: ['engineering'], description: '技術的な問題を体系的に解決する営み全般。ソフトウェア開発に限らず、設計・運用・品質保証を包括する概念として使われる。' },
  { term: '実現方法', description: '提案した内容を実際にどのような仕組みや構成で形にするかの説明。技術選定・アーキテクチャ・開発フローなどを含む。' },
  { term: '機能', description: 'システムが利用者に提供する具体的な働き。ログイン・検索・帳票出力など、利用者視点で定義される。' },
  { term: '機能概要', description: '提案対象システムが持つ機能を要約した説明。詳細仕様に入る前に、どんな機能がありどう使われるかを端的にまとめる。' },
  { term: '運用性', aliases: ['運用容易性'], description: 'システムを日々安定して回しやすい性質。監視・バックアップ・障害対応・メンテナンスのしやすさが評価軸となる。' },
  { term: 'アーキテクチャ', aliases: ['architecture'], description: 'システム全体の構成、役割分担、連携方式を定める設計の骨格。変更のしやすさ・スケーラビリティ・セキュリティに影響する。' },
  { term: '利用技術', aliases: ['技術スタック'], description: 'システムの実現に使用する言語、製品、基盤、サービス。提案書では選定理由と合わせて記載することで説得力が増す。' },
  { term: 'テスト結果', description: 'テストの実施内容と結果を記録した情報。導入前の品質確認や顧客への受け入れ確認として提出される。' },
  { term: '帳票出力', aliases: ['レポート出力', '帳票印刷'], description: 'システム内のデータを帳票や一覧として出力すること。PDF・Excel・CSV形式での出力が一般的で、業務レポートや請求書発行に使われる。' },
  { term: 'ログイン', aliases: ['サインイン'], description: '利用者が本人確認を経てシステム利用を開始すること。ID・パスワードや多要素認証により本人性を確認するシステムの基本機能。' },
  { term: '登録', aliases: ['新規登録', '作成'], description: '新しいデータをシステムに保存すること。ユーザー登録・商品登録・申請登録など、システムの基本的なCRUD操作のひとつ。' },
  { term: 'Tell Don\'t Ask', aliases: ['tell don\'t ask', 'tda', 'tell-don\'t-ask原則'], description: 'オブジェクトに状態を問い合わせて外部でロジックを実行するのではなく、オブジェクト自身に処理を命令する設計原則。カプセル化を強化し、手続き的なコードを防ぐ。' },
  { term: '最小驚きの原則', aliases: ['pola', 'principle of least astonishment'], description: 'システムやAPIは、ユーザーや開発者が驚かないよう予測可能な振る舞いをすべきという原則。既存の慣習や期待に沿った設計を促す。' },
  { term: '開放閉鎖原則', aliases: ['open/closed principle'], description: 'クラスや関数は拡張に対して開かれており、変更に対して閉じているべきというSOLID原則の一つ。新機能の追加に際し既存コードを変更しなくて済む設計を促す。' },
  { term: 'リスコフ置換原則', aliases: ['lsp', 'liskov substitution principle'], description: 'サブタイプはスーパータイプと置換可能でなければならないというSOLID原則の一つ。継承関係が正しく設計されているかを検証する基準として使われる。' },
  { term: '構造的サブタイピング', aliases: ['structural subtyping', 'ダックタイピング'], description: 'オブジェクトの型互換性を名前ではなく構造（プロパティやメソッドの形状）で判定する型システムのアプローチ。TypeScriptがこれを採用しており、ダックタイピングと関係が深い。' },
  { term: '型エイリアス', aliases: ['type alias'], description: '既存の型に別名を付ける機能。TypeScriptでは`type`キーワードで定義し、複雑な型表現に名前を付けて可読性を高めたり、ドメインの概念を型として表現する際に使う。' },
  { term: '契約による設計', aliases: ['dbc', 'design by contract'], description: '関数やメソッドに事前条件、事後条件、不変条件を明示的に定義する設計手法。呼び出し元と実装者の責務を明確にし、信頼性の高いソフトウェアを構築する。' },
  { term: 'ガード節', description: 'メソッドの冒頭で無効な条件を早期にチェックし、条件を満たさない場合は即座に返す処理パターン。ネストを減らしコードの可読性を高める。' },
  { term: '早期リターン', aliases: ['early return'], description: 'メソッドや関数の中で条件を満たさない場合に早い段階でreturnすることで、ネストを浅くし主要なロジックを見やすくするコーディングパターン。' },
  { term: '命令クエリ分離', aliases: ['cqs', 'command query separation'], description: 'メソッドは副作用を持つコマンド（命令）か値を返すクエリのどちらか一方のみを行うべきという原則。テスト容易性と可読性を高める。' },
  { term: 'テレスコープコンストラクタ', aliases: ['telescoping constructor'], description: 'パラメータが多いコンストラクタの問題を解消するため、オプションパラメータごとにオーバーロードしたコンストラクタを多数定義してしまうアンチパターン。ビルダーパターンや設定オブジェクトで解消する。' },
  { term: 'ヌルオブジェクトパターン', aliases: ['null object pattern'], description: 'nullの代わりに何もしない振る舞いを持つオブジェクトを返すデザインパターン。null チェックを排除してコードをシンプルにし、NullPointerExceptionを防ぐ。' },
  { term: 'スペシャルケースパターン', aliases: ['special case pattern'], description: '特殊な状況（null、未認証ユーザーなど）に対して専用のオブジェクトを用意し、条件分岐なしに一貫したインターフェースで扱えるようにするパターン。ヌルオブジェクトを一般化したもの。' },
  { term: 'テストスイート', aliases: ['test suite'], description: '関連するテストケースをグループ化したもの。特定の機能やモジュールに対するテストをまとめて管理し、一括して実行できる単位。' },
  { term: 'フィクスチャ', aliases: ['fixture', 'テストフィクスチャ'], description: 'テスト実行前に準備するテストデータや環境の初期状態。セットアップとティアダウンで管理され、テストの再現性と独立性を保証する。' },
  { term: 'テストハーネス', aliases: ['test harness'], description: 'テスト対象システムを実行・制御するためのインフラの総称。テストフレームワーク、モックライブラリ、テストデータ管理ツールなどを含む。' },
  { term: '継続的テスト', aliases: ['continuous testing'], description: 'コード変更のたびに自動的にテストスイートを実行し、即座にフィードバックを得る開発プラクティス。CI/CDパイプラインの中核をなす。' },
  { term: '変異テスト', aliases: ['mutation testing'], description: 'ソースコードに意図的な小さな変更（変異体）を加え、テストがその変異体を検出できるかを測定するテスト品質評価手法。テストスイートの網羅性を客観的に評価する。' },
  { term: 'プロパティベーステスト', aliases: ['pbt'], description: '具体的なテストケースではなく、入力に対して常に成り立つべき性質（プロパティ）を定義し、ランダムな入力を自動生成して検証するテスト手法。QuickCheckが先駆け。' },
  { term: 'コントラクトテスト', aliases: ['contract testing'], description: 'サービス間のAPIインターフェース契約を検証するテスト。消費者側が期待するインターフェースと提供者側の実装が一致しているかをCI上で継続的に確認する。' },
  { term: 'テスト境界', aliases: ['test boundary'], description: 'どこをモックし、どこまでを実際のコンポーネントでテストするかの境界線。テスト戦略の重要な設計決定であり、テストの信頼性とメンテナンスコストに影響する。' },
  { term: 'テスト粒度', aliases: ['test granularity'], description: 'テストが対象とするコードの範囲の細かさ。ユニット・統合・E2Eの各レベルでテストを適切に分散させ、テストピラミッドに沿ったバランスを保つことが重要。' },
  { term: '永続データ構造', aliases: ['persistent data structure'], description: '更新操作を行っても以前のバージョンが保持される不変データ構造。変更された部分だけを共有（構造共有）することでメモリ効率を保ちながら履歴管理や並行アクセスを実現する。Clojureのコアデータ構造が代表例。' },
  { term: 'ポイントフリースタイル', aliases: ['point-free style', 'tacit programming'], description: '関数の定義において引数（ポイント）を明示せず、関数合成や高階関数の組み合わせだけで処理を記述するプログラミングスタイル。簡潔で数学的な表現が可能だが、過度に使うと可読性が低下する場合もある。' },
  { term: 'モナド', aliases: ['monad'], description: '値をコンテキスト（計算の文脈）に包み、`bind`（`>>=`）と`return`（`unit`）の2つの操作を持つ代数的構造。Maybe/IO/Stateなど副作用や失敗を型安全に表現するために用いられ、Haskellやその他関数型言語で重要な役割を持つ。' },
  { term: 'ファンクタ', aliases: ['functor'], description: '値を保持するコンテナ型に対して`map`操作を定義した型クラスまたはインターフェース。コンテナ内の値に関数を適用し、同じコンテナ構造を保った結果を返す。モナドやアプリカティブの基礎となる概念。' },
  { term: 'アプリカティブ', aliases: ['applicative', 'applicative functor'], description: 'ファンクタを拡張し、コンテキストに包まれた関数をコンテキストに包まれた値に適用できる型クラス。`pure`と`<*>`（apply）を持ち、ファンクタとモナドの中間に位置する抽象。フォーム検証などの独立した計算の組み合わせに有用。' },
  { term: '代数的データ型', aliases: ['adt', 'algebraic data type'], description: '直和型と直積型を組み合わせて定義されるデータ型の総称。型理論に基づきデータの構造を正確に表現でき、パターンマッチングと組み合わせることで型安全な分岐処理を実現する。HaskellやRust、Elmなどで採用。' },
  { term: 'パターンマッチ', aliases: ['pattern matching'], description: '値の構造や内容を照合して対応する処理を選択する言語機能。switch文を拡張したもので、代数的データ型の各コンストラクタに対して網羅的に処理を記述でき、コンパイラが未処理ケースを警告する。Rustの`match`、Haskellのパターンマッチなどが代表。' },
  { term: '直和型', aliases: ['sum type', 'variant'], description: '複数の異なる型のうちいずれか1つをとりうる型。Rustの`enum`やHaskellのデータ型がこれに相当し、値がどの「場合」に属するかをタグで区別する。Option型やResult型の実装基盤。' },
  { term: '直積型', aliases: ['product type'], description: '複数のフィールドを同時に持つ型。構造体（struct）やタプルがこれに相当し、フィールド数の積だけ可能な値の組み合わせが存在する。代数的データ型の一方の構成要素で直和型と組み合わせて複雑なデータを表現する。' },
  { term: 'Option型', aliases: ['option型', 'option', 'maybe'], description: '値が存在するかもしれないし存在しないかもしれない状況を型安全に表現する直和型。`Some(value)`または`None`の2つの状態を持ち、nullポインタ例外を防ぐ。Rustでは`Option<T>`、Haskellでは`Maybe`として提供される。' },
  { term: '末尾呼び出し最適化', aliases: ['tail call optimization'], description: '関数の末尾に位置する再帰呼び出しをループに変換することでスタックオーバーフローを防ぐコンパイラ最適化。これにより再帰を使っても定数空間で実行できる。Scheme規格では必須とされ、多くの関数型言語が対応している。' },
  { term: '遅延評価', aliases: ['lazy evaluation', 'call-by-need'], description: '式の値が実際に必要になるまで計算を遅らせる評価戦略。無限リストの扱いやコストの高い計算の回避が可能になる。HaskellはデフォルトでLazyを採用。PythonのジェネレータやJavaScriptのイテレータも遅延評価の一形態。' },
  { term: '先行評価', aliases: ['eager evaluation', 'strict evaluation', 'call-by-value'], description: '式を評価するタイミングで即座に値を計算する評価戦略。ほとんどのプログラミング言語のデフォルト。遅延評価と対比され、副作用の発生タイミングが予測しやすいが、不必要な計算も行われる場合がある。' },
  { term: 'トランポリン', aliases: ['trampoline'], description: '末尾呼び出し最適化をサポートしない言語で相互再帰や深い再帰を安全に実行するための技法。関数を直接呼び出す代わりに「次に実行すべき処理を返すサンク」を返し、ループで繰り返し評価することでスタックを消費しない。' },
  { term: '継続渡しスタイル', aliases: ['cps', 'continuation-passing style'], description: '関数が結果を返す代わりに「次に実行する処理（継続）」をコールバックとして受け取り、それに結果を渡すプログラミングスタイル。制御フローを明示的に扱え、非同期処理や例外処理の実装基盤となる。コンパイラの中間表現にも使われる。' },
  { term: '並列処理', aliases: ['parallelism'], description: '複数のプロセッサコアを活用して複数の計算を物理的に同時に実行する処理モデル。並行処理が「同時に扱う」概念であるのに対し、並列処理は「同時に実行する」概念。データ並列とタスク並列が主な種別。' },
  { term: 'マルチプロセス', aliases: ['multiprocessing', 'multi-process'], description: '複数のOSプロセスを起動して並行・並列処理を実現するモデル。プロセス間はメモリ空間が独立しているため安全性が高いが、プロセス間通信（IPC）のコストが大きい。Pythonはこれを使ってGILを回避する。' },
  { term: 'コルーチン', aliases: ['coroutine'], description: '実行を途中で一時停止し、後から再開できる協調型の軽量スレッド。OSスレッドより低コストで大量に生成でき、非同期I/Oや複雑な状態機械の実装に適する。Pythonの`asyncio`コルーチン、Kotlinのコルーチンが代表例。' },
  { term: 'Goroutine', aliases: ['goroutine'], description: 'Go言語が提供する軽量な並行実行単位。OSスレッドより少ないメモリ（初期2KB程度）で動作し、Goランタイムがスケジューリングを管理する。ChannelやWaitGroupと組み合わせて安全な並行処理を構築する。' },
  { term: 'Channel', aliases: ['channel', 'チャネル'], description: 'Go言語で採用される、Goroutine間でデータを安全に送受信するための通信機構。「共有メモリで通信するのではなく、通信によって共有する」というCSPの哲学を体現する。バッファなし・バッファありの2種類がある。' },
  { term: 'Actorモデル', aliases: ['actorモデル', 'actor model'], description: '並行処理のための計算モデルで、各アクターが独立した状態とメールボックスを持ち、メッセージ交換によってのみ通信する。共有メモリが不要なためデッドロックが発生しにくい。ErlangやAkkaが代表的な実装。' },
  { term: 'Future', aliases: ['future', 'completablefuture'], description: '非同期計算の結果を表すオブジェクト。計算が完了していなくても参照を保持でき、完了時に値を取り出すかコールバックを登録できる。JavaのCompletableFuture、ScalaのFutureなどが代表例。Promiseとほぼ同義で使われることも多い。' },
  { term: 'Promise', aliases: ['promise'], description: '非同期操作の最終的な結果（成功または失敗）を表すオブジェクト。JavaScriptで広く普及し、コールバック地獄を解消する手段として登場した。`then`と`catch`でチェーン処理が可能でasync/awaitの基盤となる。' },
  { term: 'Reactorパターン', aliases: ['reactorパターン', 'reactor pattern'], description: 'イベント駆動の非同期I/Oを処理するデザインパターン。多重化されたI/Oイベントを1つのスレッドで待機し、発生したイベントを対応するハンドラにディスパッチする。Node.jsやNginxの内部実装に使われる。' },
  { term: '同期処理', aliases: ['synchronous processing'], description: '操作が完了するまで呼び出し元がブロックされる処理方式。コードの実行順序が直感的でデバッグしやすい一方、I/O待ちでCPUが無駄になりやすい。非同期処理と対比される。' },
  { term: 'ライブロック', aliases: ['livelock'], description: '複数のスレッドやプロセスが互いの状態変化に反応し続け、作業が全く進まない状態。デッドロックと異なり各スレッドは実行中だが有意な進捗がない。礼儀正しすぎるスレッドが互いに譲り合い続ける例が有名。' },
  { term: '飢餓状態', aliases: ['starvation', 'resource starvation'], description: 'あるスレッドやプロセスが必要なリソースを長期間取得できず処理が進まない状態。優先度の高いスレッドが常にCPUを占有する場合などに発生する。公平なスケジューリングアルゴリズムで緩和できる。' },
  { term: 'セマフォ', aliases: ['semaphore'], description: '共有リソースへのアクセスを制限するための非負整数カウンタを持つ同期プリミティブ。P操作（取得）でカウンタを減らしV操作（解放）で増やす。バイナリセマフォはミューテックスに相当し、カウンティングセマフォは最大同時アクセス数を制御する。' },
  { term: 'ミューテックス', aliases: ['mutex', 'mutual exclusion'], description: 'クリティカルセクションへの相互排他アクセスを保証する同期プリミティブ。ロックを取得したスレッドのみが保護されたコードを実行でき、終了後ロックを解放する。RustはMutex<T>型でデータと所有権を結びつけた安全な実装を提供する。' },
  { term: '条件変数', aliases: ['condition variable'], description: 'スレッドが特定の条件が満たされるまで待機し、別のスレッドから通知を受けて再開する同期機構。ミューテックスと組み合わせて使い、プロデューサー・コンシューマーパターンなどの実装に用いられる。' },
  { term: 'CAS', aliases: ['cas', 'compare-and-exchange', 'cas操作'], description: '「メモリの値が期待値と等しければ新しい値に書き換える」という操作をアトミックに行うCPU命令。ロックフリーデータ構造の基本操作で、楽観的ロックの実装に広く使われる。ABA問題に注意が必要。' },
  { term: 'ロックフリー', aliases: ['lock-free'], description: 'ミューテックスなどのロック機構を使わずに並行アクセスの安全性を保証するアルゴリズム設計。CASなどのアトミック操作を使い、少なくとも1つのスレッドが常に進捗する性質（lock-freedom）を保証する。デッドロックが発生しない。' },
  { term: 'Wait-Free', aliases: ['wait-free', 'wait-free algorithm'], description: 'すべてのスレッドが有限ステップ以内に操作を完了できることを保証する並行アルゴリズムの性質。ロックフリーより強い保証で飢餓が発生しない。実装が困難なため実用的なデータ構造は限られる。' },
  { term: 'メモリモデル', aliases: ['memory model'], description: 'マルチスレッド環境において各スレッドがメモリの読み書きをどの順序で観測できるかを定義した仕様。CPUやコンパイラの最適化による命令の並び替えの範囲を規定し、happens-before関係に基づいてスレッド間の可視性を保証する。' },
  { term: 'happens-before', aliases: ['happens-before関係', 'happened-before'], description: '並行処理において「操作AはBより前に起きた」という因果関係を定義する概念。Javaメモリモデルや各種メモリモデルで採用され、スレッド間でのメモリ可視性の保証範囲を規定する。同期プリミティブは通常このhappens-before関係を生成する。' },
  { term: 'volatile', aliases: ['volatile変数'], description: 'コンパイラやCPUがキャッシュや命令並び替えの最適化を行わないようにするための変数修飾子。Javaのvolatileはhappens-before関係を提供し可視性を保証するが、複合操作のアトミック性は保証しない。C/C++では主に外部からの変更を通知するために使う。' },
  { term: 'Atomic操作', aliases: ['atomic操作', 'atomic operation', 'アトミック操作'], description: '他のスレッドから見て分割不可能な単一操作として実行されることが保証される操作。読み取り・変更・書き込みが一体となってCPU命令レベルで保証される。java.util.concurrent.atomic、C++のstd::atomicなどが提供するプリミティブ。' },
  { term: 'スレッドプール', aliases: ['thread pool'], description: 'あらかじめ一定数のスレッドを生成してプールしておき、タスク投入のたびにスレッドを再利用する並行処理パターン。スレッド生成・破棄のオーバーヘッドを削減し、リソースを制御しながらタスクを並列実行できる。Executors.newFixedThreadPoolが典型例。' },
  { term: 'Fork/Join', aliases: ['fork/join', 'fork/join framework', 'フォーク/ジョイン'], description: '分割統治アルゴリズムを並列実行するためのフレームワーク。タスクをサブタスクに再帰的に分割し（fork）、完了後に結果をマージ（join）する。JavaのForkJoinPoolはWork-Stealingスケジューラを使い効率的に実行する。' },
  { term: 'Observable', aliases: ['observable', 'オブザーバブル'], description: '時間とともに0個以上の値を非同期に発行し、完了またはエラーで終了するデータストリームを表す抽象。ReactiveXの中心概念でsubscribeにより購読する。単一値のPromiseを一般化したもので、イベント・APIレスポンス・ユーザー入力などに適用できる。' },
  { term: 'ReactiveX', aliases: ['reactivex', 'rx', 'rxjs', 'rxjava', 'reactiveextensions'], description: 'Observableパターンを中心に非同期・イベントベースのプログラムを構成するライブラリ群。RxJS（JavaScript）、RxJava（Java）、RxSwift（Swift）など多言語で実装されている。map/filter/mergeなどの演算子でストリームを宣言的に変換する。' },
  { term: 'λ計算', aliases: ['lambda calculus', 'ラムダ計算'], description: '変数・関数抽象・関数適用の3要素のみから成る形式的な計算体系。1930年代にAlonzo Churchが考案し、チューリング計算と同等の計算能力を持つ。関数型プログラミングの理論的基盤であり、型理論や証明論とも深く関係する。' },
  { term: 'ダイナミックスコープ', aliases: ['dynamic scope', '動的スコープ'], description: '変数の参照が実行時のコールスタックによって決まるスコープ規則。関数の呼び出し元の変数を参照できるため柔軟だが、動作の予測が難しくなる。Emacs Lispや古いLisp方言で採用。Perlの`local`変数が部分的に動的スコープを使う。' },
  { term: 'レコード型', description: '名前付きフィールドを持つ直積型。構造体（struct）と同義で使われることが多く、フィールドへのアクセスに名前を使う。HaskellのRecord構文、Elmのレコード、TypeScriptのオブジェクト型などが代表例。' },
  { term: '多相型', aliases: ['polymorphic type'], description: '型パラメータを持ち複数の異なる型に対して統一的に動作できる型。パラメトリック多相（Generics）とアドホック多相（型クラス/オーバーロード）の2種類が主要。コードの再利用性と型安全性を両立する。' },
  { term: 'パラメトリック多相', aliases: ['parametric polymorphism'], description: '型パラメータを持つ関数やデータ型が、どの具体的な型に対しても同一のコードで動作する多相性。Javaのジェネリクス、HaskellやRustの型パラメータが代表例。型パラメータに対して均一な振る舞いをする（パラメトリシティ）。' },
  { term: 'アドホック多相', aliases: ['ad-hoc polymorphism', 'overloading'], description: '同じ関数名を異なる型に対して異なる実装で動作させる多相性。オーバーロード（静的ディスパッチ）と型クラス/インターフェースによる動的ディスパッチが含まれる。パラメトリック多相と対比される。' },
  { term: '型クラス', aliases: ['type class'], description: '特定の操作を実装することを型に要求するHaskell由来の抽象化機構。インターフェースに似るが、既存の型に後から実装（インスタンス）を追加できる点が異なる（オープンワールド仮定）。RustのtraitやScalaの型クラスパターンが類似。' },
  { term: 'エフェクトシステム', aliases: ['effect system', '側効果システム'], description: '関数が持つ副作用（I/O、例外、状態変更など）を型として明示的に追跡する型システムの拡張。コンパイル時に副作用の伝播を制御でき、純粋性を型レベルで保証する。Haskellのモナドトランスフォーマーや代数的エフェクトが実現手段。' },
  { term: '代数的エフェクト', aliases: ['algebraic effects', 'algebraic effects and handlers'], description: '副作用を宣言的に定義・処理する言語機能。副作用の操作（エフェクト）とその解釈（ハンドラ）を分離し、依存性注入や例外・非同期・コルーチンを統一的に扱える。OCamlのEffect、Koka言語などが実装している。' },
  { term: '継続', aliases: ['continuation'], description: 'プログラムのある時点での「残りの計算全体」を表す第一級の値。継続を操作することで例外、バックトラッキング、コルーチン、async/awaitなど多様な制御フローを統一的に実装できる。SchemeのcallccがContinuationを直接扱う代表例。' },
  { term: 'スレッドセーフ', aliases: ['thread-safe', 'thread safety'], description: '複数のスレッドから同時にアクセスされても正しく動作することが保証されたコードやデータ構造の性質。ロック・アトミック操作・不変データなどの手法でスレッドセーフ性を実現する。スレッドセーフでないコードを並行使用すると競合状態が発生する。' },
  { term: 'メモリバリア', aliases: ['memory barrier', 'memory fence', 'フェンス命令'], description: 'CPUやコンパイラが命令を最適化で並び替える際の境界を設けるCPU命令またはコンパイラ指令。バリアの前後で読み書きが適切な順序で見えることを保証し、マルチコア環境でのメモリ可視性を確立する。' },
  { term: 'キャッシュコヒーレンス', aliases: ['cache coherence', 'キャッシュ整合性'], description: 'マルチプロセッサシステムで各コアのキャッシュが共有メモリの最新の値を適切に反映するための一貫性保証。MESIプロトコルなどのハードウェア機構が実装する。False sharingはキャッシュコヒーレンストラフィックを増加させるパフォーマンス問題。' },
  { term: '線形型', aliases: ['linear type'], description: '値がプログラム中でちょうど1回だけ使用されることを型システムが強制する型。使い捨てリソース（ファイルハンドル、ネットワーク接続など）の管理に適し、二重解放などのリソースリークをコンパイル時に防ぐ。Rustの所有権システムの理論的背景。' },
  { term: 'アフィン型', aliases: ['affine type'], description: '値が高々1回しか使用されないことを保証する型。線形型は「ちょうど1回」であるのに対しアフィン型は「0回または1回」。Rustの所有権システムはアフィン型に近い意味論を持ち、値のmoveによる消費を型システムで追跡する。' },
  { term: '所有権システム', aliases: ['ownership system', 'ownership model'], description: 'Rust言語が採用するメモリ管理モデル。各値は1つの所有者を持ち、所有者がスコープを抜けると自動解放される。借用チェッカと組み合わせてGCなしにメモリ安全性とスレッド安全性をコンパイル時に保証する。' },
  { term: '借用チェッカ', aliases: ['borrow checker'], description: 'Rustコンパイラに組み込まれた、参照（借用）のライフタイムと可変性を検証する機構。「同時に複数の不変参照、または1つの可変参照のみ許可」というルールを強制し、データ競合をコンパイル時に排除する。' },
  { term: 'ライフタイム', aliases: ['lifetime'], description: 'Rustにおいて参照が有効なスコープの範囲を表すアノテーション。借用チェッカがライフタイムを解析し、ダングリング参照を防ぐ。多くの場合ライフタイムは推論されるが、関数シグネチャや構造体で明示が必要な場合は`\'a`などの記法で表す。' },
  { term: '依存型', aliases: ['dependent type'], description: '型が値に依存できる型システム。たとえば「長さnの配列型」のように実行時の値を型の一部として使える。定理証明と同等の表現力を持ちCoq、Agda、Idrisなどの証明支援系で採用される。型安全性の究極形ともいわれる。' },
  { term: 'GADT', aliases: ['gadt', 'generalized algebraic data type', '一般化代数的データ型'], description: '代数的データ型を拡張し、各コンストラクタが異なる型パラメータの具体化を返せるようにした型。型安全な式評価器やDSLの実装に使われ、型レベルで不変条件を表現できる。HaskellとOCamlが対応している。' },
  { term: 'データ並列', aliases: ['data parallelism'], description: '同一の操作を大量のデータ要素に対して並列に適用する並列処理スタイル。GPU演算やSIMD命令、MapReduceなどが典型例。データを分割して各プロセッサが独立して処理するためスケールしやすい。' },
  { term: 'タスク並列', aliases: ['task parallelism'], description: '異なる処理（タスク）を複数のスレッドや計算資源が並列に実行する並列処理スタイル。各タスクは独立していても依存関係を持っていてもよい。データ並列と対比され、Fork/Joinフレームワークで実装されることが多い。' },
  { term: 'SIMD', aliases: ['simd', 'single instruction multiple data'], description: '1つの命令で複数のデータ要素を同時に処理するCPUアーキテクチャ拡張。x86のSSE/AVX、ARMのNEONが代表。画像処理・音声処理・機械学習推論の高速化に活用される。RustやC++のautovectorizationによって自動的に利用されることもある。' },
  { term: 'STM', aliases: ['stm', 'software transactional memory', 'ソフトウェアトランザクショナルメモリ'], description: 'データベーストランザクションの概念を共有メモリの並行アクセスに適用するプログラミングモデル。コードブロックをトランザクションとして実行し、競合時は自動的にリトライする。デッドロックが発生せず宣言的に書けるがオーバーヘッドがある。HaskellのSTMが著名。' },
  { term: '純粋関数型言語', aliases: ['pure functional language'], description: '言語全体が純粋関数と参照透過性に基づいて設計されたプログラミング言語。副作用はモナドや代数的エフェクトによって型システムで管理される。HaskellやElmが代表で、不変性・遅延評価・強力な型推論が特徴。' },
  { term: 'エフェクトハンドラ', aliases: ['effect handler'], description: '代数的エフェクトシステムにおいて、宣言されたエフェクト操作の具体的な解釈・実装を提供する構造。エフェクトの呼び出しと処理を分離することで、同じコードを異なる文脈（テスト用スタブなど）で実行できる。' },
  { term: 'バックトラッキング', aliases: ['backtracking'], description: '問題解決において行き詰まったら直前の選択に戻って別の選択肢を試す探索アルゴリズムの戦略。論理プログラミング（Prolog）の基本的な実行モデルで、継続を使って関数型言語でも実装できる。パズルや組み合わせ最適化に使われる。' },
  { term: '非決定性計算', aliases: ['nondeterministic computation'], description: '1つの入力に対して複数の実行経路や結果が存在しうる計算モデル。リスト/Maybeモナドを使うと「すべての可能な結果」を計算する非決定性をエミュレートできる。バックトラッキングや論理プログラミングと密接に関係する。' },
  { term: 'モナドトランスフォーマー', aliases: ['monad transformer'], description: '複数のモナドの効果を合成するための型クラス。例えばMaybeTはMaybeの失敗処理とIOなど別のモナドを組み合わせる。StateT、ReaderT、WriterTなどがあり、モナドスタックとして積み重ねて複合エフェクトを表現する。' },
  { term: '遅延初期化', aliases: ['lazy initialization'], description: 'オブジェクトや値をプログラム起動時ではなく初めて必要とされた時点で初期化するパターン。起動時間の短縮・メモリ効率の向上に有効。マルチスレッド環境では二重チェックロッキングなどのパターンで安全に実装する必要がある。' },
  { term: 'デルミテッド継続', aliases: ['delimited continuation', '区切り継続'], description: 'プログラムの残りの計算全体ではなく、特定のマーカー（プロンプト）までの部分的な継続を第一級の値として扱う機能。代数的エフェクトやジェネレータのより一般的な実装基盤となる。Racket、OCaml 5.xなどが提供する。' },
  { term: 'ストランド', aliases: ['strand', 'green thread'], description: 'OSスレッドの上に実装されたユーザー空間の軽量スレッド。グリーンスレッドとも呼ばれ、ランタイムが協調スケジューリングを管理する。GoのGoroutine、Erlangのプロセスが代表例。OSスレッドより少ないリソースで大量に生成できる。' },
  { term: 'プロデューサー・コンシューマー', aliases: ['producer-consumer pattern', '生産者消費者パターン'], description: 'データを生成するプロデューサーと消費するコンシューマーを分離し、バッファ（キュー）を介して疎結合に連携する並行処理パターン。生産・消費速度の差を吸収しスループットを向上させる。BlockingQueueやChannelを使って実装される。' },
  { term: '読み書きロック', aliases: ['read-write lock', 'rwlock', 'readerwriterlock'], description: '複数の読み取り操作は同時に許可しつつ、書き込み操作は排他的に行う同期プリミティブ。読み取りが多く書き込みが少ないデータ構造で、ミューテックスよりも高いスループットを実現する。' },
  { term: 'バリア同期', aliases: ['barrier synchronization', 'barrier'], description: '並列処理において全スレッドが特定の地点に到達するまで先に進んだスレッドを待機させる同期メカニズム。フェーズに分かれた並列アルゴリズムや並列ループの終端同期に使われる。CyclicBarrierやCountDownLatchが実装例。' },
  { term: 'アクターシステム', aliases: ['actor system'], description: 'Actorモデルを実装したランタイムシステム。アクターの生成・終了・監視、メッセージルーティング、障害回復（supervision）を管理する。AkkaやErlang/OTPの「supervision tree」が代表的で、フォールトトレラントな分散システムの構築に使われる。' },
  { term: 'イベント駆動プログラミング', aliases: ['event-driven programming', 'edp'], description: 'プログラムの実行フローをイベントの発生によって制御するプログラミングパラダイム。GUIアプリ、ゲーム、非同期サーバーで広く採用される。イベントリスナーやハンドラを登録し、イベントループがイベントを検出してディスパッチする。' },
  { term: '副作用管理', aliases: ['effect management', 'side effect management'], description: 'プログラムの副作用（I/O、状態変更、例外など）を型システムや設計パターンを使って制御・分離する取り組み。モナド、代数的エフェクト、Dependency Injectionなどが手段として使われ、テスト容易性と保守性を高める。' },
  { term: 'ゼロコスト抽象化', aliases: ['zero-cost abstraction'], description: '高レベルな抽象化を使っても実行時オーバーヘッドが生じない言語設計原則。C++やRustが掲げるコンセプトで、イテレータ・クロージャ・ジェネリクスなどのコストは手書きの低レベルコードと同等にコンパイルされる。' },
  { term: 'プログラミングパラダイム', aliases: ['programming paradigm'], description: 'プログラムの構造と実行に関する根本的なスタイルや考え方の枠組み。命令型・オブジェクト指向・関数型・論理型・宣言型などがあり、多くの現代言語は複数のパラダイムをサポートするマルチパラダイム言語である。' },
  { term: 'マイクロアーキテクチャ', aliases: ['microarchitecture', 'μarch'], description: 'CPUが命令セットアーキテクチャ（ISA）を実際にどのように実装しているかを表す内部設計。パイプライン段数・実行幅・分岐予測・キャッシュ構成・Out-of-Order実行の有無などが含まれ、同じISA対応でもメーカーや世代により大きく異なる。性能・消費電力・発熱に直結する。' },
  { term: '命令セットアーキテクチャ', aliases: ['isa', 'instruction set architecture'], description: 'ソフトウェアから見えるCPUの仕様を定義した抽象層。命令の種類・レジスタ構成・アドレッシングモード・例外処理・メモリモデルなどのルールを規定する。プログラム互換性はISAで決まり、性能特性はマイクロアーキテクチャで変わる。' },
  { term: '命令セット', aliases: ['instruction set', '命令体系'], description: 'CPUが実行できる機械語命令の集合。算術演算・論理演算・データ転送・分岐・制御命令などで構成される。CISC（複雑命令セット）とRISC（縮小命令セット）の設計哲学があり、x86-64はCISC系、ARMはRISC系に分類される。' },
  { term: '分岐予測', aliases: ['branch prediction', 'ブランチプレディクション'], description: '条件分岐命令の結果を事前に予測してパイプラインの停止を回避する技術。静的予測（常に分岐する/しないと仮定）と動的予測（過去の履歴に基づく予測）があり、現代CPUでは95%以上の精度を達成する。予測ミスはパイプラインフラッシュを引き起こす。' },
  { term: 'Out-of-Order実行', aliases: ['out-of-order実行', 'ooo実行', 'アウトオブオーダー実行', 'out-of-order execution'], description: 'プログラム順序に関わらず、データ依存関係のない命令を先に実行する技術。リオーダバッファで元の順序を管理しつつ、実行ユニットの空きを最大限活用して性能を向上させる。高性能CPUの中核技術の一つ。' },
  { term: 'レジスタリネーミング', aliases: ['register renaming', 'レジスタ改名'], description: '命令間の見かけ上のレジスタ依存（WAR・WAW依存）を解消するため、論理レジスタを物理レジスタに動的に割り当てる技術。Out-of-Order実行と組み合わせて使用され、命令レベル並列性を高める。' },
  { term: '命令フェッチ', aliases: ['instruction fetch'], description: 'メモリやキャッシュからCPUが実行すべき命令を取り出すパイプラインの最初の段階。命令キャッシュ（L1I）からの読み出し速度がスループットに直結し、分岐予測と連携して次に実行する命令のアドレスを決定する。' },
  { term: '命令デコード', aliases: ['instruction decode', 'id', 'デコード'], description: 'フェッチした命令を内部で処理可能な形式（マイクロオペレーション等）に分解するパイプライン段階。CISCアーキテクチャでは可変長命令を固定長の内部命令に変換する必要があり、デコーダの複雑さがボトルネックになりうる。' },
  { term: '実行ユニット', aliases: ['execution unit', '機能ユニット'], description: 'CPU内部で実際に演算やメモリアクセスを行うハードウェアブロックの総称。ALU・FPU・ロードストアユニット・SIMDユニット・分岐ユニットなどが含まれ、スーパースカラCPUでは複数の実行ユニットが並列に動作する。' },
  { term: 'ALU', aliases: ['alu', '算術論理演算装置', 'arithmetic logic unit'], description: '整数の加減算・論理演算（AND・OR・NOT・XOR）・シフト演算・比較演算を行うCPUの基本演算ユニット。現代CPUには複数のALUが搭載され、1クロックで複数の整数演算を同時実行できる。' },
  { term: 'FPU', aliases: ['fpu', '浮動小数点演算装置', 'floating point unit'], description: '浮動小数点数の加減乗除・平方根・型変換などを行う専用演算ユニット。科学技術計算・3Dグラフィックス・機械学習で重要。IEEE 754規格に準拠した単精度（32bit）・倍精度（64bit）演算を処理する。' },
  { term: 'ロードストアユニット', aliases: ['load/store unit', 'lsu', 'ロード・ストアユニット'], description: 'メモリからデータを読み込む（ロード）操作とメモリへデータを書き込む（ストア）操作を担当するCPUの実行ユニット。キャッシュとの連携・メモリ順序の保証・ストアバッファの管理を行う。' },
  { term: 'キャッシュ階層', aliases: ['cache hierarchy', 'キャッシュレベル'], description: 'L1・L2・L3と段階的に容量と遅延が増加するキャッシュメモリの多層構造。主記憶（DRAM）の遅さを隠蔽するために不可欠で、空間的局所性と時間的局所性を利用してデータアクセスを高速化する。' },
  { term: 'L1キャッシュ', aliases: ['l1キャッシュ', 'l1 cache', '一次キャッシュ'], description: 'CPUコアに最も近い最小・最高速のキャッシュメモリ。命令キャッシュ（L1I）とデータキャッシュ（L1D）に分離されることが多く、典型的な容量は32KB〜64KB、アクセス遅延は1〜4クロック程度。' },
  { term: 'L2キャッシュ', aliases: ['l2キャッシュ', 'l2 cache', '二次キャッシュ'], description: 'L1キャッシュの次に参照される中間層のキャッシュメモリ。通常はコアごとに専用で256KB〜1MB程度の容量を持ち、アクセス遅延は10〜20クロック程度。L1ミス時のバックアップとして機能する。' },
  { term: 'L3キャッシュ', aliases: ['l3キャッシュ', 'l3 cache', '三次キャッシュ', 'llc'], description: '複数のCPUコアで共有される最大容量のキャッシュメモリ。数MB〜数十MBの容量を持ち、コア間のデータ共有やL2ミス時のバックアップとして機能する。Last Level Cache（LLC）とも呼ばれる。' },
  { term: 'リオーダバッファ', aliases: ['rob', 'reorder buffer'], description: 'Out-of-Order実行されたCPU命令の結果をプログラム順序通りにコミット（確定）するためのバッファ。命令の投機実行結果を一時保持し、例外や分岐ミス予測時にロールバックを可能にする。容量が性能の上限を決める重要な構造。' },
  { term: '投機実行', aliases: ['speculative execution', '投機的実行'], description: '分岐の結果が確定する前に予測された経路の命令を先行実行する技術。予測が正しければ性能が向上し、誤りの場合は結果を破棄する。SpectreやMeltdownなどのサイドチャネル攻撃の原因として注目された。' },
  { term: 'サイドチャネル攻撃', aliases: ['side-channel attack', 'サイドチャネル'], description: '暗号処理やCPU実行の副作用（実行時間・消費電力・電磁波・キャッシュ状態等）を観測して秘密情報を推定する攻撃手法。Spectre・Meltdownはキャッシュタイミングを利用した投機実行ベースのサイドチャネル攻撃として知られる。' },
  { term: 'クロック周波数', aliases: ['clock frequency', '動作周波数', 'clock speed'], description: 'CPUが1秒間に繰り返す基本動作サイクルの回数。GHz（ギガヘルツ）で表され、周波数が高いほど単位時間あたりの処理能力が上がる。ただし消費電力と発熱も増大するため、IPC（クロックあたり命令実行数）との兼ね合いが重要。' },
  { term: '消費電力', aliases: ['power consumption', 'tdp', '電力消費'], description: 'CPUやシステムが動作時に消費する電力。TDP（熱設計電力）として公表されることが多い。クロック周波数・電圧・トランジスタ数に比例して増加し、モバイルやデータセンターでは電力効率（ワットあたり性能）が重要な設計指標となる。' },
  { term: 'アドレス空間', aliases: ['address space', 'メモリ空間'], description: 'プロセスやCPUがアクセスできるメモリアドレスの範囲。物理アドレス空間はハードウェアの実際のメモリ、仮想アドレス空間はOSが各プロセスに提供する論理的なメモリ範囲を指す。64bitCPUでは理論上16EBまでの空間を扱える。' },
  { term: 'コンパイラ最適化', aliases: ['compiler optimization', '最適化パス'], description: 'コンパイラがソースコードから生成する機械語をより高速・省メモリにする変換処理。ループ展開・関数インライン化・定数畳み込み・デッドコード除去・命令スケジューリングなどの技法があり、マイクロアーキテクチャに合わせた最適化が性能に大きく影響する。' },
  { term: 'x86-64', aliases: ['x64', 'amd64', 'intel 64', 'x86_64'], description: 'AMDが設計しIntelが採用した64bitのCISC系命令セットアーキテクチャ。32bitのx86を64bitに拡張したもので、PCやサーバーの主流CPU（Intel Core・AMD Ryzen等）で広く使用される。後方互換性により32bitアプリケーションも実行可能。' },
  { term: 'パイプラインハザード', aliases: ['pipeline hazard', 'ハザード'], description: 'パイプライン処理で命令の正常な流れが妨げられる状況。データハザード（前の命令の結果を次が必要）・制御ハザード（分岐による経路不確定）・構造ハザード（ハードウェア資源の競合）の3種類がある。フォワーディングや分岐予測で対策する。' },
  { term: 'スーパースカラ', aliases: ['superscalar', 'スーパースカラプロセッサ'], description: '1クロックサイクルで複数の命令を同時にフェッチ・デコード・実行できるCPUアーキテクチャ。命令レベル並列性を活用し、複数の実行ユニットに命令を同時投入してスループットを向上させる。現代の高性能CPUの標準的な設計手法。' },
  { term: 'VLIW', aliases: ['vliw', 'very long instruction word', '超長命令語'], description: '1つの長い命令語に複数の演算操作を詰め込み、コンパイラが並列性を静的にスケジュールするCPUアーキテクチャ。ハードウェアを単純化できる利点がある一方、コンパイラ依存度が高く汎用CPUより信号処理・組込み向けで使われる。' },
  { term: 'メモリアクセス', aliases: ['memory access', 'メモリ参照'], description: 'CPUがメインメモリ（DRAM）からデータを読み書きする操作。キャッシュミス時のメモリアクセスはCPU演算の数百倍の遅延がありボトルネックとなりやすい。プリフェッチ・キャッシュ最適化・メモリアクセスパターンの工夫で性能改善できる。' },
  { term: '並列実行', aliases: ['parallel execution'], description: '複数の命令やタスクを同時に実行して処理速度を向上させる手法。CPU内部の命令レベル並列性（ILP）、マルチコアによるスレッドレベル並列性（TLP）、SIMDによるデータレベル並列性（DLP）の3つのレベルがある。' },
  { term: 'クロックサイクル', aliases: ['clock cycle', 'クロック', 'サイクル'], description: 'CPUの基本動作単位となる時間間隔。クロック信号の立ち上がりから次の立ち上がりまでの1周期を指す。命令の実行にかかるクロック数（CPI: Cycles Per Instruction）はマイクロアーキテクチャによって異なり、性能指標の基本となる。' },
  { term: '高性能コンピューティング', aliases: ['hpc', 'high performance computing', 'ハイパフォーマンスコンピューティング'], description: '科学技術計算・気象予測・分子シミュレーション・AI学習など大規模な計算処理を高速に実行するための技術分野。スーパーコンピュータ・GPUクラスタ・並列プログラミング（MPI・OpenMP）を活用し、FLOPS（1秒あたりの浮動小数点演算数）で性能を測る。' },
  { term: 'ATTINY1616 DIPアダプターキット', aliases: ['attiny1616 dipアダプターキット', 'attiny1616 dip adapter kit'], description: 'ATTiny1616マイコンをブレッドボードで使用可能にするDIPパッケージ変換アダプターキットです。実験・プロトタイプ開発に利用されます。' },
  { term: 'デバイスプログラマー', aliases: ['device programmer'], description: 'マイコンやROMなどのデバイスにファームウェアやプログラムを書き込むためのハードウェアツールです。UPDI・ISP・JTAGなどのインターフェースを使用します。' },
  { term: '要件', aliases: ['requirements', '仕様要件'], description: 'システムや機能が満たすべき条件・仕様。機能要件（何をするか）と非機能要件（性能・セキュリティ・可用性等）に分類される。要件定義書として文書化し、設計・実装・テストの基準となる。曖昧な要件は手戻りの原因となるため早期の明確化が重要。' },
  { term: '外部システムとの連携', aliases: ['system integration', 'external integration', '外部連携', 'api連携'], description: '自社システムと外部のAPIやSaaS・レガシーシステムを接続してデータや機能を共有する統合。REST API・Webhook・メッセージキュー・ETLなどの手法を用い、認証・エラーハンドリング・バージョン管理・タイムアウト設計が重要な課題となる。' },
  { term: '開発', aliases: ['development', 'ソフトウェア開発'], description: 'ソフトウェアを要件に基づいて設計・コーディング・テスト・デプロイするプロセス全体。フロントエンド開発・バックエンド開発・インフラ構築などを含み、アジャイルやウォーターフォール等の開発手法に従って進められる。チームの協働とCI/CDパイプラインが現代の開発を支える。' },
  { term: '処理の流れ', aliases: ['process flow', 'フロー'], description: 'システムやAPIが受け取った入力をどのように処理して出力を生成するかを順序立てて示したフロー。シーケンス図・フローチャート・箇条書きで表現し、実装前の仕様確認・コードレビュー・障害調査で参照される。処理の分岐・エラーケース・非同期処理も含めて記述する。' },
  { term: 'データ保存方法', aliases: ['data storage', 'storage strategy', '永続化方法', 'データストレージ'], description: 'アプリケーションがデータを永続化するための手段と設計方針。リレーショナルDB・NoSQL・ファイルストレージ・IndexedDB・LocalStorageなどの選択と、スキーマ設計・データ整合性・バックアップ戦略・スケーラビリティを含む。要件に応じた適切なストレージの選択が性能と運用コストに直結する。' },
  { term: '命名', aliases: ['naming', '命名規則', 'naming convention'], description: '変数・関数・クラス・ファイル・テーブル等に適切な名前を付ける行為および規則。可読性・保守性に直結し、チームでの命名規則（camelCase・snake_case・PascalCase等）の統一が重要。「コードは書く時間より読む時間の方が長い」という原則のもと、意図を明確に伝える名前が優先される。' },
  { term: '構造', aliases: ['structure', 'コード構造', 'system structure', 'code structure'], description: 'ソフトウェアシステムの構成要素の配置・依存関係・相互作用の全体的な組み立て方。ディレクトリ構造・レイヤー分割・モジュール境界等を指し、適切な構造はコードの可読性・再利用性・テスト容易性を高める。コンポーネント間の依存方向を整理することが保守性向上の鍵となる。' },
  { term: '負債', aliases: ['technical debt', 'debt'], description: '技術的負債の略称。短期的な利益のために取った設計上の妥協や未整理のコードが蓄積した将来の追加コスト。リファクタリング不足・テスト欠如・古い依存ライブラリ等が原因で、放置すると開発速度の低下・バグ増加・人材定着率の悪化を招く。定期的な返済（リファクタリング）が必要。' },
  { term: 'プロダクト', aliases: ['product', '製品', 'プロダクト開発'], description: '開発チームが作成・改善を続けるソフトウェア製品またはサービス。プロダクトオーナー・プロダクトマネージャーがビジョン・ロードマップ・優先順位を管理し、ユーザー価値と事業価値の両立を目指す。エンジニア・デザイナー・ビジネス側の三者が協働してプロダクトを育てる。' },
  { term: '同期', aliases: ['sync', 'synchronization', 'データ同期'], description: '複数のシステム・コンポーネント・データソース間でデータの整合性を保つために状態を一致させる処理。リアルタイム同期・バッチ同期・双方向同期等の方式があり、競合解決・冪等性・オフライン対応・通信の信頼性が設計上の課題となる。' },
  { term: '開発速度', aliases: ['development velocity', 'velocity', '開発ペース'], description: 'チームが一定期間（スプリント等）に完了できる開発作業量の指標。ベロシティとも呼ばれ、ストーリーポイントや機能数で測定する。技術的負債・コードレビュー効率・テスト自動化・開発環境の整備・コンテキストスイッチの削減が開発速度に大きく影響する。' },
  { term: '共通基盤', aliases: ['shared platform', 'common infrastructure', '共通サービス', '横断基盤'], description: '複数のサービスやチームが共用する認証・ロギング・通知・決済・APIゲートウェイ等の横断的なインフラとサービス群。共通化により重複実装を削減し品質を均一化するが、過剰な共通化はサービス間の密結合を招くため適切なスコープ設定が重要。' },
  { term: 'エンジニア', aliases: ['engineer', 'developer', 'ソフトウェアエンジニア', '開発者'], description: '【ソフトウェアエンジニアリング】ソフトウェアの設計・開発・運用に携わる技術職。フロントエンドエンジニア・バックエンドエンジニア・インフラエンジニア・SRE等のスペシャリストに分類される。プロダクトチームではデザイナーやプロダクトマネージャーと協働し、技術的な実現手段を担う。 【OCI APEX】アプリ作成や編集を行う利用者。' },
  { term: 'スモールスタートと反復', aliases: ['build small and iterate'], description: '小規模から始めて段階的に改善を繰り返す開発アプローチです。アジャイル開発やリーンスタートアップの基本原則です。' },
  { term: '飲食', aliases: ['food and beverage', 'f&b', 'restaurant'], description: '【一般】食べること・飲むことの総称。食事・摂食・水分補給などの行為を広く指す日常語。「飲食禁止」「飲食店」「飲食物」など複合語としても広く使われる。 【不動産】業種区分の一つで、飲食物の提供を行う業態。レストラン・カフェ・テイクアウト・フードコートなどを含む。商業施設では飲食ゾーンの構成・換気設備・排水設備などの出店条件が他業種と異なり、テナント誘致・条件交渉で特別な考慮が必要となる。' },
  { term: '変数名', aliases: ['variable name'], description: 'プログラム中で変数を識別するための名前。意味が伝わる具体的な名前をつけることが保守性向上の基本。スコープや型の特性を反映した命名が推奨され、xやtmpのような汎用的すぎる名前は避けるべきとされる。' },
  { term: '関数名', aliases: ['function name'], description: '関数・メソッドに付ける識別子。「何をする関数か」が一目でわかるよう動詞を先頭に置くことが多い（例：getUserById、sendEmail）。命名から責務の範囲が明確になることが良い設計の指標となる。' },
  { term: 'クラス名', aliases: ['class name'], description: 'クラスに付ける識別子。一般的に名詞・PascalCaseで表記し、そのクラスが表すエンティティや概念を表す（例：UserRepository、OrderService）。名前がクラスの責務を過不足なく表していることが重要。' },
  { term: 'メソッド名', aliases: ['method name'], description: 'クラスやオブジェクトに属するメソッドに付ける識別子。関数名と同様に動詞から始めることが多く、そのオブジェクトに対する操作を表す（例：user.save()、order.cancel()）。命名の一貫性がAPIの使いやすさに直結する。' },
  { term: 'テーブル名', aliases: ['table name', 'テーブル識別子'], description: 'データベースのテーブルに付ける名前。格納するエンティティを複数形の名詞で表すことが多い（例：users、orders）。テーブル名はSQLや各種ORMを通じてアプリケーション全体に影響するため、変更コストが高く最初の命名が重要。' },
  { term: 'API名', aliases: ['api名', 'api name', 'エンドポイント名'], description: 'APIのエンドポイントやインターフェースに付ける名前。RESTful APIではリソースを名詞で表し（例：/users、/orders/{id}）、HTTPメソッドで操作を表現する。命名がそのままドキュメントになるため、直感的で一貫したAPI設計が重要。' },
  { term: '変数', aliases: ['variable', '変数宣言'], description: 'プログラム中でデータを格納する名前付きの記憶領域。値を保持し、後から参照・変更できる。宣言時にデータ型を指定する静的型付け言語と、実行時に型が決まる動的型付け言語がある。スコープによってアクセス可能な範囲が決まる。' },
  { term: '関数', aliases: ['サブルーチン', 'プロシージャ'], description: '特定の処理をまとめた再利用可能なコードブロック。引数を受け取り、処理を行い、戻り値を返す。DRY原則（繰り返しを避ける）の基本単位であり、適切な粒度でコードを分割することで保守性と再利用性が高まる。' },
  { term: 'クラス', aliases: ['クラス定義'], description: 'オブジェクト指向プログラミングの基本単位。データ（フィールド）と振る舞い（メソッド）をひとまとめにした設計図。インスタンス化することでオブジェクトが生成される。継承・カプセル化・ポリモーフィズムの基盤となる。' },
  { term: 'メソッド', aliases: ['メンバ関数'], description: 'クラスやオブジェクトに属する関数。そのオブジェクトが持つデータに対して操作を行う。インスタンスメソッド・クラスメソッド・静的メソッドなど種別があり、それぞれアクセス可能な状態の範囲が異なる。' },
  { term: 'パラメータ', aliases: ['parameter', '仮引数', 'パラム'], description: '関数やメソッドの定義側で宣言される変数名のこと。呼び出し元から渡される値（引数）を受け取るための「型枠」。引数（実引数）とは対になる概念で、関数定義に書かれるのがパラメータ、呼び出し側に書かれるのが引数。' },
  { term: '引数', aliases: ['argument', '実引数'], description: '関数やメソッドを呼び出す際に渡す実際の値。パラメータ（仮引数）に対する実引数。例えばsort(list)のlistが引数。引数の型・個数・順序は関数のシグネチャと一致させる必要がある。' },
  { term: 'フレームワーク', aliases: ['framework', 'アプリケーションフレームワーク'], description: 'アプリケーション開発の骨格となるソフトウェア基盤。開発者はフレームワークのルールに従って必要な部分を実装することで、共通機能（ルーティング、DB接続、認証など）を再実装せずに利用できる。ライブラリとの違いは「制御の逆転」にあり、フレームワークがコードを呼び出す。' },
  { term: 'ライブラリ', aliases: ['library', 'ソフトウェアライブラリ'], description: '特定の機能を実装した再利用可能なコード集。開発者が必要に応じて呼び出して使う。フレームワークとの違いは制御の方向で、ライブラリはアプリケーションコードから呼び出される。npm、PyPI、Mavenなどパッケージマネージャで配布される。' },
  { term: 'ランタイム', aliases: ['ランタイム環境'], description: 'プログラムが実行される環境・時間帯のこと。「ランタイムエラー」は実行中に発生するエラーを指す。また「Node.jsランタイム」のようにプログラムを実行するための基盤ソフトウェアを指す場合もある。コンパイル時・設計時と対比して使われる。' },
  { term: 'パッケージ', aliases: ['モジュールパッケージ'], description: '関連するモジュールや機能をまとめた配布単位。npm（JavaScript）、pip（Python）、Maven（Java）などのパッケージマネージャを通じてインストールし依存関係を管理する。バージョン管理と依存解決がパッケージシステムの核心的役割。' },
];
