// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: it (3/6)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_003: ReadonlyArray<GlossaryEntry> = [
  { term: '文書統制', description: '文書の作成、更新、承認、配布、保管を統制することです。品質、監査、ナレッジ活用の基盤になります。' },
  { term: 'ドキュメント分類体系', aliases: ['document taxonomy'], description: 'ドキュメントの役割と階層を整理した構造です。設計書・議事録・手順書・FAQが混在していると必要なものを見つけにくくなります。' },
  { term: 'バージョン番号管理', aliases: ['version number management'], description: 'バージョン番号と変更履歴を管理することです。最新版がわからない状況を防ぐための基本的なプラクティスです。' },
  { term: 'ドキュメントオーナー', aliases: ['document owner'], description: 'ドキュメントの内容と更新に責任を持つ担当者です。オーナーがいないドキュメントは急速に陳腐化する傾向があります。' },
  { term: 'ドキュメント区分', aliases: ['document classification'], description: 'ドキュメントを目的・機密レベル・更新頻度などの基準で整理することです。区分があると検索やガバナンスが容易になります。' },
  { term: '機密レベル', aliases: ['confidentiality level'], description: 'ドキュメントやデータの機密度を分類する基準です。共有範囲・保存場所・AI入力可否の判断根拠にもなります。' },
  { term: '相互参照', aliases: ['cross-references'], description: 'ドキュメント同士が参照し合う関係性です。重複記述を減らしつつ必要な情報へ誘導できる設計が重要です。' },
  { term: 'マスタードキュメント', aliases: ['master document'], description: '他のドキュメントの拠り所となる権威ある原典文書です。同じ内容を複数箇所で管理する状況を避けるための有効なアプローチです。' },
  { term: '派生ドキュメント', aliases: ['derived document'], description: '別の権威あるドキュメントをベースに作成した文書です。元文書との同期ルールがないと、すぐに乖離して陳腐化します。' },
  { term: 'タギング', aliases: ['tagging'], description: 'ドキュメントに分類ラベルを付与することです。自由度が高すぎると乱立し、厳しすぎると使われなくなるため、バランスが必要です。' },
  { term: 'メタデータ', aliases: ['metadata'], description: 'ドキュメントの内容ではなく、作成者・更新日・区分・関連プロジェクトなどの付属情報です。発見性とガバナンスを支援します。' },
  { term: '文書台帳', aliases: ['document inventory'], description: 'ドキュメントや資産を一覧化して必要性と状態を確認するものです。定期的な棚卸しは陳腐化した資料の蓄積を防ぐのに有効です。' },
  { term: '廃版', aliases: ['obsolescence'], description: 'ドキュメントや知識が現状と合わなくなった状態です。古い情報が残存していることは、情報がない状態より危険な場合もあります。' },
  { term: 'FAQ管理', aliases: ['faq管理', 'faq maintenance'], description: 'よくある質問と回答を整理して再利用可能にすることです。問い合わせ量だけでなく教育コストの削減にも寄与します。' },
  { term: '業務ノウハウ', aliases: ['operational know-how'], description: '日常業務から得られるコツや注意点のことです。設計書には載っていない実践的な知識として高い価値を持ちます。' },
  { term: 'インシデントナレッジ', aliases: ['incident knowledge'], description: '過去インシデントの原因・症状・対処法・再発防止策を記録したものです。同じインシデントの再発防止に向けた基盤となります。' },
  { term: '定型回答', aliases: ['standard response'], description: '問い合わせや確認に対する統一された回答です。担当者によって説明が変わるのを防ぎます。' },
  { term: 'インストール手順', aliases: ['installation procedure'], description: 'インストールと設定のステップをまとめた文書です。再現性のある環境構築に不可欠です。' },
  { term: 'ビルド手順', aliases: ['build procedure'], description: '環境構築作業を具体的に実施するための文書です。IaCがあっても周辺タスクや前提説明に必要になる場合があります。' },
  { term: '構成一覧', aliases: ['configuration list'], description: 'システムの設定値をまとめたリストです。値だけでなく意味や変更責任者も含めると使いやすさが増します。' },
  { term: '未解決事項', aliases: ['open items'], description: 'まだ結論が出ていない課題のことです。設計書に残す場合は何が未決で、いつ解消されるかを明記することで実用性が高まります。' },
  { term: 'QAレコード', aliases: ['qaレコード', 'q&a record'], description: '質問と回答の記録です。同じ問い合わせが後で出たときに再利用できる資産となります。' },
  { term: '会議メモ', aliases: ['meeting memo'], description: '会議中に取ったその場のメモです。正式な議事録が作成されるまでの橋渡し役にもなります。' },
  { term: 'エビデンストレイル', aliases: ['evidence trail'], description: 'コミュニケーションや意思決定を後から検証できる形で保存することです。監査だけでなく、日常の認識齟齬防止にも役立ちます。' },
  { term: 'バージョンフリーズ', aliases: ['version freeze'], description: '特定バージョンをベースラインとして固定し、それ以上の変更を止めることです。レビュー・承認・リリース前の安定化に使われます。' },
  { term: '廃止バージョン', aliases: ['deprecated version'], description: '参照すべきでなくなった古いドキュメントバージョンです。削除できない場合でも明示的にマーキングすることでインシデントを防げます。' },
  { term: '文書ガバナンス', aliases: ['document governance'], description: '文書の作成・更新・承認・配布・保存を統治することです。品質・監査・知識活用の基盤となります。' },
  { term: '受入項目一覧', description: '利用者や発注者が確認する項目をまとめた一覧です。受入テストの抜け漏れを減らせます。' },
  { term: 'テスト観点表', description: '何をどう確認するかの観点を整理した表です。テストケース設計の質を上げます。' },
  { term: 'テストケース一覧', description: '個別テストケースをまとめた一覧です。進捗管理や網羅確認に向いています。' },
  { term: 'テストデータ一覧', description: 'テストで使う入力や前提データをまとめた一覧です。再現性ある検証に必要です。' },
  { term: 'テスト証跡', description: 'テスト実施結果を示す記録です。監査や受入説明に使われます。' },
  { term: '品質基準表', description: '何をもって品質良好と判断するかの基準表です。主観的判断を減らせます。' },
  { term: '受入基準表', description: '利用者や発注者が受け入れるための基準です。請負契約や受入テストと相性がよいです。' },
  { term: '非機能試験項目表', description: '性能、障害、監視などの確認項目をまとめた表です。機能テストに埋もれがちな観点を拾えます。' },
  { term: 'Visual Studio Code', aliases: ['visual studio code'], description: 'Microsoft が提供する、拡張性を重視した軽量コードエディタです。拡張機能によって言語、デバッガー、各種ツールを追加できます。' },
  { term: 'VS Code', aliases: ['vs code'], description: 'Visual Studio Code の略称です。日常実務ではこの略称で呼ばれることがほとんどです。' },
  { term: 'Extension Marketplace', aliases: ['extension marketplace'], description: 'VS Code の拡張機能を検索、導入するための配布基盤です。Visual Studio Marketplace から直接インストールできます。' },
  { term: 'Extension', aliases: ['extension'], description: 'VS Code に機能を追加する拡張機能です。言語サポート、デバッガー、ツール連携などを後から足せます。' },
  { term: 'Extension API', aliases: ['extension api'], description: 'VS Code を拡張するための公式 API 群です。多くのコア機能自体も拡張として実装されていると説明されています。' },
  { term: 'VSIX', aliases: ['vsix'], description: 'VS Code 拡張機能の配布パッケージ形式です。Marketplace を使わずに配布するときにも使えます。' },
  { term: 'vsce', description: 'VS Code 拡張機能を package、publish、unpublish するための CLI ツールです。拡張機能公開時の中心ツールです。' },
  { term: 'Workspace', aliases: ['workspace'], description: 'VS Code で開いている作業対象のフォルダ、またはそのまとまりです。複数フォルダを扱うワークスペースにも対応します。' },
  { term: 'Workspace Trust', aliases: ['workspace trust'], description: '開いているフォルダを信頼するかどうかで、タスク実行やデバッグなど危険な操作を制御する仕組みです。Restricted Mode と深く関係します。' },
  { term: 'Restricted Mode', aliases: ['restricted mode'], description: '信頼していないワークスペースを制限付きで開くモードです。タスク実行やデバッグは制限されます。' },
  { term: 'Activity Bar', aliases: ['activity bar'], description: 'エクスプローラーや拡張機能ビューなどを開くサイドバー上の主要ナビゲーション領域です。Extensions ビューもここから開けます。' },
  { term: 'Command Palette', aliases: ['command palette'], description: 'VS Code のコマンドをキーボード中心で呼び出せる UI です。拡張機能が追加したコマンドもここに集約されます。' },
  { term: 'Settings', aliases: ['settings'], description: 'VS Code のエディタや拡張機能の設定です。GUI でも JSON でも管理できます。' },
  { term: 'settings.json', description: 'VS Code の設定を JSON 形式で記述するファイルです。ユーザー設定とワークスペース設定の両方で使えます。' },
  { term: 'launch.json', description: 'デバッグ構成を定義するファイルです。通常はワークスペース配下の .vscode フォルダに置かれます。' },
  { term: 'tasks.json', description: 'ビルドやテストなどのタスク定義を記述するファイルです。ワークスペースの .vscode フォルダで共有されます。' },
  { term: '.vscode folder', description: 'ワークスペース固有の設定やデバッグ構成、タスク定義などを置くフォルダです。launch.json と tasks.json も通常ここに置かれます。' },
  { term: 'Debug Configuration', aliases: ['debug configuration'], description: 'VS Code でどのプログラムをどうデバッグ起動するかを定義する設定です。launch.json に書かれます。' },
  { term: 'Debugger Extension', aliases: ['debugger extension'], description: '特定言語やランタイムのデバッグ機能を提供する拡張です。インストールされたデバッグ拡張が type を導入します。' },
  { term: 'preLaunchTask', aliases: ['prelaunchtask'], description: 'デバッグ開始前に実行するタスクを指定する設定です。tasks.json のタスクと組み合わせて使います。' },
  { term: 'Variable Substitution', aliases: ['variable substitution'], description: 'launch.json や tasks.json 内で ${workspaceFolder} などの変数展開を行う仕組みです。設定の再利用性を高めます。' },
  { term: 'Extensions View', aliases: ['extensions view'], description: '拡張機能を検索、インストール、無効化するための VS Code 画面です。Activity Bar の拡張機能アイコンから開けます。' },
  { term: 'Publisher Trust', aliases: ['publisher trust'], description: 'サードパーティ拡張機能の発行元を信頼するかを確認する仕組みです。VS Code は拡張機能の実行リスクを明示しています。' },
  { term: 'Extension Runtime Security', aliases: ['extension runtime security'], description: '拡張機能がローカルファイル操作やネットワーク通信、外部プロセス実行などを行える点を前提に、安全に扱う考え方です。' },
  { term: 'Allowed Extensions Policy', aliases: ['allowed extensions policy'], description: 'エンタープライズ環境で、インストール可能な拡張機能を制限するための VS Code ポリシーです。extensions.allowed などで制御できます。' },
  { term: 'Private Marketplace', aliases: ['private marketplace'], description: '組織内で拡張機能を自己ホスト配布できる VS Code の企業向け機能です。許可済み拡張の配布統制に使えます。' },
  { term: 'Bootstrap Extensions', aliases: ['bootstrap extensions'], description: '初回起動時にあらかじめインストールさせる拡張機能群です。エンタープライズ環境での標準配布に使えます。' },
  { term: 'Task Provider', aliases: ['task provider'], description: 'ワークスペース内容を見て自動的に VS Code タスクを提供できる拡張機能 API です。手書き tasks.json を減らせることがあります。' },
  { term: 'Virtual Workspace', aliases: ['virtual workspace'], description: 'ローカルファイルシステム前提ではない作業環境です。制約があり、対応していない拡張機能ではデバッグ不可な場合があります。' },
  { term: 'Profiles', aliases: ['profiles'], description: '用途ごとに拡張機能や設定を切り替えるための仕組みです。技術スタックごとの環境分離に役立ちます。' },
  { term: 'ドキュメント', description: '仕様、手順、設計などを記録した文書。' },
  { term: 'ETL', aliases: ['etl'], description: 'データの抽出、変換、格納を行う処理。' },
  { term: '集計', description: 'データをまとめて数値化すること。' },
  { term: '校閲', aliases: ['proofreading'], description: '文章の誤りや不自然さを確認し、整えること。' },
  { term: '自然な表現', aliases: ['natural expression'], description: '日本語として無理がなく読みやすい言い方。' },
  { term: '伝わりやすい表現', aliases: ['clear expression'], description: '意味が明確で、誤解されにくい表現。' },
  { term: '文言', aliases: ['wording'], description: '文書や案内で使う言い回し。' },
  { term: '適切', aliases: ['appropriate'], description: '文脈や目的に合っていること。' },
  { term: '誤記', aliases: ['typographical error'], description: '書き間違いや不適切な表記。' },
  { term: '定義', aliases: ['definition'], description: '用語や概念の意味を明確に示したもの。' },
  { term: '製造', aliases: ['apex'], description: '設計書に基づいてプログラムを実装し、動作する資材として作り上げる工程。' },
  { term: '総合テスト', description: 'システム全体を通して、業務シナリオや利用手順に沿って期待どおりに動くかを確認するテスト。' },
  { term: '受入テスト', description: '利用部門や発注側が、成果物が要件や業務運用に適合しているかを確認し受け入れ可否を判断するテスト。' },
  { term: '運用テスト', description: '監視、バックアップ、障害対応、ジョブ実行など、運用手順が実際に成立するかを確認するテスト。' },
  { term: 'Python', aliases: ['python'], description: 'AI、データ分析、Web API、自動化など幅広い用途で使われる言語。' },
  { term: 'CI/CD', aliases: ['ci/cd'], description: 'ビルド、テスト、配備を継続的に自動化し、変更を素早く安全に反映する仕組み。' },
  { term: 'DevOps', aliases: ['devops'], description: '開発と運用が連携し、継続的改善と迅速な提供を目指す考え方。' },
  { term: 'CRUD', aliases: ['crud'], description: 'データの登録、参照、更新、削除という基本操作の総称。' },
  { term: 'SVF', aliases: ['svf'], description: '帳票レイアウト設計や印刷出力に広く使われる帳票基盤製品。' },
  { term: 'JasperReports', aliases: ['jasperreports'], description: 'Java系システムで利用される帳票出力ライブラリ。' },
  { term: 'HULFT Square', aliases: ['hulft square'], description: 'システム間データ連携や変換処理をクラウド上で実現するサービス。' },
  { term: 'SmileCHAT', aliases: ['smilechat'], description: 'SystemEXE R&D開発のAgentic AIプラットフォーム。マルチターン対話、Artifacts、RAG Files、GitHub連携、MCP、リアルタイムWeb検索などを備え、ユーザーとAIエージェントの協働を支援する。' },
  { term: '新規会話', description: '新しいチャットセッションを開始する機能や状態。' },
  { term: 'Playwright', aliases: ['playwright'], description: 'Web画面を自動操作してテストするツール。' },
  { term: 'PowerShell', aliases: ['powershell'], description: 'Windowsやクラウド操作を自動化するコマンド環境。' },
  { term: 'JSON', aliases: ['json', 'javascript object notation'], description: 'データをやりとりするための軽量な記述形式。' },
  { term: 'REST API', aliases: ['rest api'], description: 'HTTPを使ってデータ連携する一般的なAPI形式。' },
  { term: 'シナリオテスト', description: '実際の業務の流れに沿って確認するテスト。' },
  { term: 'テストケース', description: '何をどう確認するかを定義した個別の試験項目。' },
  { term: 'E2Eテスト', aliases: ['e2eテスト'], description: '画面から裏側処理まで一連で確認するテスト。' },
  { term: '負荷テスト', description: '高いアクセスや大量処理に耐えられるか確認するテスト。' },
  { term: 'リグレッションテスト', description: '修正による別機能への悪影響がないか確認するテスト。' },
  { term: 'テストエビデンス', description: 'テストを実施した証拠となる記録や画面キャプチャ。' },
  { term: 'デバッグ', description: '不具合の原因を特定して修正する作業。' },
  { term: 'デプロイ', description: 'アプリや設定を実行環境へ反映すること。' },
  { term: 'リリース', description: '利用者が使う環境へ正式に公開すること。' },
  { term: 'GitHub', aliases: ['github'], description: 'ソースコードのバージョン管理とチーム開発を支援するプラットフォーム。Issue、Pull Request、Actions、Codespacesなどの機能を備える。' },
  { term: 'レビュー駆動', description: 'Pull Requestを中心にコードレビューを必須とし、品質と知識共有を高める開発運用の考え方。' },
  { term: 'TDD', aliases: ['tdd'], description: 'テストを先に書いて、実装と設計を導く開発技法。' },
  { term: 'Test-Driven Development', aliases: ['test-driven development'], description: 'TDDの正式名称。' },
  { term: 'property-based testing', description: '個別例ではなく、成り立つべき性質そのものを検証するテスト手法。' },
  { term: '第一級関数', aliases: ['first-class function'], description: '関数を変数に代入したり引数や戻り値として扱える言語機能。関数型プログラミングの基盤。' },
  { term: '高階関数', aliases: ['higher-order function'], description: '関数を引数に取るか、または関数を返す関数。map, filter, reduce などが代表例。' },
  { term: '関数型プログラミング', aliases: ['functional programming'], description: '副作用を排除し、純粋関数・不変データ・高階関数を中心に据えるプログラミングパラダイム。' },
  { term: 'オブジェクト指向', aliases: ['oop', 'object-oriented programming'], description: 'データと振る舞いをオブジェクトとしてまとめ、継承・カプセル化・ポリモーフィズムを活用するプログラミングパラダイム。' },
  { term: '手続き型プログラミング', aliases: ['procedural programming'], description: '命令の手順（プロシージャ）を順番に記述するプログラミングパラダイム。C言語が代表例。' },
  { term: '宣言的プログラミング', aliases: ['declarative programming'], description: '「何をするか」を記述し「どのようにするか」は実行系に任せるパラダイム。SQL・HTMLが代表例。' },
  { term: '命令型プログラミング', aliases: ['imperative programming'], description: '「どのようにするか」の手順を明示的に記述するパラダイム。宣言的プログラミングの対義語。' },
  { term: 'Consumer Driven Contract', aliases: ['consumer driven contract', 'cdc', 'コンシューマー駆動契約'], description: 'APIコンシューマーがプロバイダーとの契約（期待する通信仕様）を定義し、その契約をテストで検証する手法。' },
  { term: 'SemVer', aliases: ['semver'], description: 'Semantic Versioning。MAJOR.MINOR.PATCHの形式でバージョンを管理し、変更の種類を明示する規約。' },
  { term: 'Branch by Abstraction', aliases: ['branch by abstraction'], description: '大規模な変更をフィーチャーブランチなしに行うため、抽象化レイヤーで新旧実装を切り替えるテクニック。' },
  { term: 'Parallel Change', aliases: ['parallel change', 'expand and contract', 'パラレルチェンジ'], description: '既存実装を壊さずに新実装を並行して追加し、移行後に旧実装を削除する段階的変更テクニック。' },
  { term: 'BDD', aliases: ['bdd', '振る舞い駆動開発', 'behavior-driven development'], description: 'Behavior-Driven Development。Given-When-Then形式でビジネス仕様をシナリオとして記述し、テストと仕様を一致させる開発手法。' },
  { term: 'ATDD', aliases: ['atdd', '受け入れテスト駆動開発', 'acceptance test-driven development'], description: 'Acceptance Test-Driven Development。受け入れテストを先に作成し、それをパスする実装を行う開発手法。' },
  { term: 'Given-When-Then', aliases: ['given-when-then'], description: 'テストシナリオを「前提条件（Given）・操作（When）・期待結果（Then）」の3段階で記述するBDDの構造テンプレート。' },
  { term: 'ユニットテスト', description: '関数やクラスなどの最小単位を個別に検証するテスト。高速で独立性が高く、テストピラミッドの底辺を担う。' },
  { term: '統合テスト', aliases: ['integration test'], description: '複数コンポーネントやモジュールを組み合わせ、相互作用が正しく機能するかを検証するテスト。' },
  { term: '受け入れテスト', aliases: ['acceptance test'], description: 'ビジネス要件や仕様を満たすかをステークホルダー視点で検証するテスト。ATDDの核心。' },
  { term: '回帰テスト', description: '変更によって既存機能が壊れていないかを確認するテスト。CI/CDパイプラインで自動実行されることが多い。' },
  { term: 'スナップショットテスト', aliases: ['snapshot test'], description: 'UIや関数の出力を「スナップショット」として保存し、変更時に差分を検出するテスト手法。Jestが有名。' },
  { term: 'テストダブル', aliases: ['test double'], description: 'テスト対象が依存するコンポーネントの代替品の総称。モック・スタブ・スパイ・フェイクなどが含まれる。' },
  { term: 'モック', aliases: ['mock'], description: '依存オブジェクトの代替品で、呼び出し検証（振る舞い確認）を主目的とするテストダブル。' },
  { term: 'スタブ', aliases: ['stub'], description: 'テスト中に依存オブジェクトの代わりに固定値を返すテストダブル。状態確認テストで使われる。' },
  { term: 'スパイ', aliases: ['spy', 'test spy'], description: '実際のオブジェクトに呼び出し記録機能を追加したテストダブル。本物の処理も実行しつつ呼び出しを検証する。' },
  { term: 'フェイク', aliases: ['fake'], description: '実際の依存コンポーネントの軽量代替実装（インメモリDBなど）。本物に近い動作をするテストダブル。' },
  { term: 'リファクタリング', aliases: ['refactoring'], description: '外部から見た振る舞いを変えずにコードの内部構造を改善すること。技術的負債の解消やコード品質向上が目的。' },
  { term: 'リライト', aliases: ['rewrite'], description: '既存システムをゼロから書き直すこと。リファクタリングと異なり既存コードを使わず全面的に再実装する。' },
  { term: 'Trunk-Based Development', aliases: ['trunk-based development'], description: '長命ブランチを避け、全開発者が頻繁にmain/trunkブランチへ統合する開発スタイル。Feature Flagと組み合わせることが多い。' },
  { term: 'Feature Flag', aliases: ['feature flag', 'feature toggle', 'フィーチャーフラグ', 'フィーチャートグル'], description: 'コードを変更せずに機能のON/OFFを切り替える仕組み。未完成機能のデプロイや段階的リリースに使う。' },
  { term: '静的解析', aliases: ['static analysis', '静的コード解析'], description: 'コードを実行せずに文法・型・セキュリティ・コーディング規約などの問題を検出するツール・手法。' },
  { term: 'リンター', aliases: ['linter'], description: 'コードのスタイル・構文エラー・アンチパターンを自動検出するツール。ESLint・Pylintが代表例。' },
  { term: 'フォーマッター', aliases: ['formatter', 'コードフォーマッター'], description: 'コードを決められたスタイル規約に従って自動整形するツール。Prettier・gofmtが代表例。' },
  { term: '型安全性', aliases: ['type safety'], description: '型システムによって型の不一致エラーをコンパイル時に検出し、ランタイムエラーを防ぐ性質。' },
  { term: '型推論', description: 'コンパイラが変数や式の型を文脈から自動的に推定する機能。明示的な型注釈を省略できる。' },
  { term: 'コンパイル時検査', aliases: ['compile-time check'], description: 'コードのビルド時に型・構文・依存関係などのエラーを検出する仕組み。ランタイムエラーを事前に防ぐ。' },
  { term: 'ランタイムエラー', aliases: ['runtime error', '実行時エラー'], description: 'プログラムの実行中に発生するエラー。ヌルポインター・配列境界外アクセスなどがある。' },
  { term: 'ヌル安全', aliases: ['null safety', 'null安全'], description: 'null参照によるエラーをコンパイル時に防ぐ言語・型システムの機能。KotlinやSwiftに採用されている。' },
  { term: 'Optional', aliases: ['optional', 'optional型'], description: '値が存在しない可能性を型で表現する仕組み。Javaのjava.util.Optional、SwiftのOptional型などが代表例。' },
  { term: 'Result型', aliases: ['result型', 'result', 'result type'], description: '成功値またはエラー値のいずれかを保持する型。例外に代わるエラー処理手段として関数型言語で多用される。' },
  { term: 'Either型', aliases: ['either型', 'either', 'either type'], description: '2つの異なる型のいずれかを保持できる型。Left（エラー）/Right（成功）の慣習でエラー処理に使われる。' },
  { term: '例外安全', aliases: ['exception safety'], description: '例外が発生してもリソースリークやデータ破損が起きないよう保証されているコードの性質。' },
  { term: 'ガベージコレクション', aliases: ['gc', 'garbage collection'], description: 'プログラムが使用しなくなったメモリを自動的に回収する仕組み。GCとも略される。' },
  { term: 'メモリリーク', aliases: ['memory leak'], description: '確保したメモリが解放されず累積し続けるバグ。長時間稼働するプロセスでメモリ不足を引き起こす。' },
  { term: 'オフバイワンエラー', aliases: ['off-by-one error', '一つずれ'], description: 'ループや配列のインデックス計算で境界値を1つ誤るバグ。「一つずれ」とも呼ばれる。' },
  { term: 'デッドロック', aliases: ['deadlock'], description: '複数のスレッドまたはプロセスが互いにリソースの解放を待ち、永久に処理が進まなくなる状態。' },
  { term: 'レースコンディション', aliases: ['race condition', '競合状態'], description: '複数スレッドが共有リソースへ競合してアクセスし、実行順序によって異なる結果をもたらすバグ。' },
  { term: 'ドキュメンテーション', aliases: ['documentation'], description: 'コード・API・アーキテクチャ・使い方などを文書化したもの。保守性・チームの知識共有に不可欠。' },
  { term: 'アーキテクチャ決定記録', description: '重要な設計判断・採用理由・代替案・結果を記録するドキュメント。チームの知識継承に役立つ。' },
  { term: 'ボーイスカウト・ルール', aliases: ['boy scout rule'], description: 'コードを触るたびに見つけた箇所を以前より少し改善して去るという開発プラクティス。技術的負債の漸進的解消を促す。' },
  { term: 'Broken Windows Theory', aliases: ['broken windows theory', '割れ窓理論'], description: '小さな問題（壊れた窓）を放置するとさらなる劣化を招くという理論。コード品質維持の比喩として使われる。' },
  { term: 'Cargo Cult Programming', aliases: ['cargo cult programming', 'カーゴカルトプログラミング'], description: '理解せずにコードやパターンを模倣するプログラミング慣行。本質を理解せずに形式だけを真似すること。' },
  { term: 'Spaghetti Code', aliases: ['spaghetti code', 'スパゲッティコード'], description: '制御フローが複雑に絡み合い読み解くのが困難なコード。適切なモジュール化・関数分割がないまま成長したコードベース。' },
  { term: 'God Object', aliases: ['god object', 'god class', '神クラス'], description: '過剰な責任と知識を持ち、多数の他クラスと結合した巨大なクラス。単一責任原則の違反。' },
  { term: 'Big Ball of Mud', aliases: ['big ball of mud', '大きな泥団子'], description: '構造が欠如し、場当たり的に成長した混沌としたシステム。最も一般的なアーキテクチャアンチパターン。' },
  { term: 'Shotgun Surgery', aliases: ['shotgun surgery', 'ショットガンサージャリー'], description: '1つの変更を行うために多数のクラスや場所を修正しなければならないアンチパターン。高凝集・疎結合の欠如。' },
  { term: 'Feature Envy', aliases: ['feature envy', 'フィーチャーエンビー'], description: 'メソッドが自分のクラスよりも他クラスのデータや機能を多用するコードの臭い。責任の誤配置を示す。' },
  { term: 'Primitive Obsession', aliases: ['primitive obsession', '基本型への執着'], description: '小さなオブジェクト（金額・日付・座標など）にプリミティブ型を多用するコードの臭い。Value Objectで解消する。' },
  { term: 'Long Method', aliases: ['long method', '長いメソッド'], description: '長くなりすぎて理解・テスト・再利用が難しくなったメソッドのコードの臭い。小さなメソッドに分割すべき。' },
  { term: 'Long Parameter List', aliases: ['long parameter list', '長いパラメータリスト'], description: '引数が多すぎて使いにくいメソッドのコードの臭い。パラメータオブジェクトや設定クラスに置き換える。' },
  { term: 'Duplicated Code', aliases: ['duplicated code', '重複コード'], description: '同じまたは類似のコードが複数箇所に存在するコードの臭い。DRY原則違反の典型。' },
  { term: 'Magic Number', aliases: ['magic number', 'マジックナンバー', 'マジックストリング'], description: '意味が不明な数値・文字列リテラルがコード中に直接書かれているコードの臭い。定数・列挙型に置き換える。' },
  { term: 'Temporal Coupling', aliases: ['temporal coupling', '時間的結合'], description: 'メソッドや操作が特定の順序で呼ばれることを暗黙的に前提とする設計上の問題。' },
  { term: 'Seam', aliases: ['seam', '継ぎ目'], description: 'コードを変更せずにプログラムの振る舞いを変更できる箇所。テスト容易性を高めるための設計上の「継ぎ目」。' },
  { term: 'Legacy Code', aliases: ['legacy code', 'レガシーコード'], description: 'テストがなく変更が困難な既存コード。Michael Feathersの定義では「テストのないコード」。' },
  { term: 'システム', aliases: ['system'], description: '複数の要素が組み合わさって一つの目的を達成する仕組み。IT分野ではコンピューターやソフトウェア、ネットワークを組み合わせた構成体を指す。' },
  { term: 'ソフトウェア', aliases: ['software', 'sw'], description: 'コンピューター上で動作するプログラムやデータの総称。OSやアプリなど、形のないものをソフトウェアと呼ぶ。ハードウェアと対になる概念。' },
  { term: 'ハードウェア', aliases: ['hardware', 'hw'], description: 'コンピューターの物理的な部品の総称。本体、画面、キーボード、マウスなど実際に触れることができる機器を指す。' },
  { term: 'データ', aliases: ['data'], description: 'コンピューターが処理する情報の基本単位。文字、数値、画像、音声などあらゆる情報をデータと呼ぶ。' },
  { term: '情報', aliases: ['information'], description: '何らかの意味を持つデータのこと。コンピューターは情報を処理・保存・伝達する。情報システムは業務上の情報を管理するシステム。' },
  { term: 'アルゴリズム', aliases: ['algorithm'], description: '問題を解くための手順や手続きを明確に定義したもの。料理のレシピのように、何をどの順番でやるかを決めたもの。プログラムはアルゴリズムを実装したもの。' },
  { term: 'プログラム', aliases: ['program'], description: 'コンピューターに実行させる命令を記述したもの。Java、Pythonなどの言語で書かれており、コンピューターはプログラムの指示に従って動作する。' },
  { term: 'アプリケーション', aliases: ['アプリ', 'application', 'app'], description: '特定の目的のために作られたソフトウェア。メール、表計算、チャットなど、ユーザーが直接使う用途向けのプログラムをアプリケーションと呼ぶ。' },
  { term: 'ユーザー', aliases: ['user', '利用者', 'エンドユーザー'], description: '【IT基礎】システムやサービスを利用する人。エンドユーザーとも言い、実際に画面を操作する利用者を指す。開発者・管理者と区別するために使われることが多い。 【OCI APEX】作成済みアプリを利用する人。' },
  { term: 'デジタル', aliases: ['digital'], description: '情報を0と1（二進数）で表す方式。現代のコンピューターはすべてデジタル方式で動作する。アナログと対比して使われる。' },
  { term: 'アナログ', aliases: ['analog'], description: '情報を連続した量（電圧や波形など）で表す方式。デジタルと対比して使われる。昔の電話やテレビはアナログ方式だった。' },
  { term: 'バイナリ', aliases: ['binary', '二進数'], description: '0と1の二進数で表されたデータ。コンピューターはすべての情報をバイナリで処理する。テキストでないファイル（画像、動画など）もバイナリファイルと呼ぶ。' },
  { term: 'ビット', aliases: ['bit'], description: 'コンピューターが扱う最小のデータ単位。0か1のどちらかの値を持つ。8ビットで1バイトになる。' },
  { term: 'バイト', aliases: ['byte', 'b'], description: '8ビットをまとめた情報量の単位。1バイトで英字1文字を表せる。1,024バイト＝1KB、1,024KB＝1MBというように大きな単位になる。' },
  { term: '処理', aliases: ['processing'], description: '【IT基礎】コンピューターがデータに対して計算・変換・判断などの操作を行うこと。「入力→処理→出力」がコンピューターの基本的な動作パターン。 【OCI APEX】サーバ側処理や保存処理を扱う領域。' },
  { term: '入力', aliases: ['input', 'インプット'], description: 'コンピューターに対してデータや命令を与えること。キーボードやマウスで操作したり、ファイルを読み込んだりすることが入力にあたる。' },
  { term: '出力', aliases: ['output', 'アウトプット'], description: 'コンピューターが処理結果を外部に送り出すこと。画面表示、印刷、ファイル書き込みなどが出力にあたる。' },
  { term: 'ファイル', aliases: ['file'], description: 'コンピューター上でデータをひとまとめにして保存したもの。文書ファイル、画像ファイル、プログラムファイルなどがある。ファイル名と拡張子で区別される。' },
  { term: 'フォルダ', aliases: ['ディレクトリ'], description: '複数のファイルをまとめて管理するための入れ物。ディレクトリとも呼ばれる。フォルダの中にさらにフォルダを作ることができる。' },
  { term: 'CPU', aliases: ['cpu', 'central processing unit', 'プロセッサ', 'processor'], description: 'コンピューターの「頭脳」にあたる部品。Central Processing Unitの略。プログラムの命令を読み取り計算・実行する。処理速度はGHzという単位で表される。' },
  { term: 'メモリ', aliases: ['memory'], description: 'CPUが処理中のデータを一時的に保存する場所。作業台に例えられる。容量が大きいほど多くのアプリを同時に動かせる。電源を切るとデータは消える。' },
  { term: 'RAM', aliases: ['ram', 'random access memory'], description: 'Random Access Memoryの略。コンピューターのメモリの正式名称。作業中のデータを高速に読み書きできる揮発性メモリ。電源を切るとデータが消える。' },
  { term: 'ストレージ', aliases: ['storage', '記憶装置'], description: 'データを長期間保存するための記憶装置。HDDやSSDが代表的。電源を切ってもデータが消えない不揮発性メモリ。容量はGBやTBで表される。' },
  { term: 'HDD', aliases: ['hdd', 'hard disk drive', 'ハードディスク', 'hard disk'], description: 'Hard Disk Driveの略。磁気ディスクを使ってデータを保存する記憶装置。SSDより安価だが読み書き速度は遅い。大容量のデータ保存に使われる。' },
  { term: 'SSD', aliases: ['ssd', 'solid state drive'], description: 'Solid State Driveの略。フラッシュメモリを使ってデータを保存する記憶装置。HDDより高速で衝撃に強い。最近のPCではSSDが主流。' },
  { term: 'OS', aliases: ['os', 'operating system', 'オペレーティングシステム', '基本ソフト'], description: 'Operating Systemの略。コンピューターの基本的な動作を管理するソフトウェア。ハードウェアとアプリの橋渡し役で、WindowsやmacOS、Linuxが代表的。' },
  { term: 'Windows', aliases: ['windows', 'ウィンドウズ'], description: 'Microsoft社が開発したOS。世界で最も広く使われているOS。会社のPCのほとんどはWindowsが使われている。バージョンはWindows 10、11などがある。' },
  { term: 'macOS', aliases: ['macos', 'mac os', 'マック'], description: 'Apple社が開発したOS。MacBook・iMacなどApple製パソコンに搭載。デザイン職やクリエイター向けに人気。MacOSとも書く。' },
  { term: 'Linux', aliases: ['linux', 'リナックス', 'gnu/linux'], description: 'オープンソースのOS。サーバーや開発環境で広く使われる。無料で使えて安定性が高い。UbuntuやCentOSなど多くのディストリビューションがある。' },
  { term: 'プロセス', aliases: ['process'], description: '【コンピュータ基礎】コンピューター上で実行中のプログラムのこと。同じプログラムでも複数起動すると複数のプロセスになる。タスクマネージャーで確認できる。 【OCI APEX】送信時などに実行するサーバ処理。' },
  { term: 'スレッド', aliases: ['thread', 'マルチスレッド'], description: 'プロセスの中で実行される処理の単位。一つのプロセスが複数のスレッドを持つことで、並行して複数の処理を行える（マルチスレッド処理）。' },
  { term: 'タスクマネージャー', aliases: ['task manager'], description: 'Windowsで実行中のプロセスやCPU・メモリの使用状況を確認・管理するツール。Ctrl+Alt+Deleteで起動できる。応答しないアプリを強制終了することもできる。' },
  { term: 'ドライバー', aliases: ['device driver', 'デバイスドライバー'], description: 'ハードウェアをOSが制御するためのソフトウェア。プリンターやマウスなど周辺機器をPCに接続したとき、ドライバーをインストールすることで使えるようになる。' },
  { term: 'ブート', aliases: ['boot', '起動', 'ブートアップ'], description: 'コンピューターの電源を入れてOSが起動するまでの過程。「ブートする」「ブートアップ」とも言う。ブートに時間がかかる場合はSSDへの交換などが有効。' },
  { term: 'カーネル', aliases: ['kernel'], description: 'OSの中核となるプログラム。ハードウェアの管理やプロセスの制御など、最も基本的な機能を担う。ユーザーは直接触れないが、すべての動作の基盤となる。' },
  { term: 'ファイルシステム', aliases: ['file system', 'ntfs', 'apfs'], description: 'ストレージにファイルを保存・管理する仕組み。Windowsでは「NTFS」、MacではAPFS、LinuxではExt4が使われる。ファイルの読み書きや検索を管理する。' },
  { term: 'V字モデル', aliases: ['v字モデル', 'v-model', 'vモデル'], description: 'システム開発の各工程とテスト工程を対応させたモデル。要件定義→基本設計→詳細設計→製造→単体テスト→結合テスト→システムテスト→受入テストとV字形に対応する。' },
  { term: '正常系', aliases: ['正常ケース', 'happy path'], description: 'システムが期待どおりに動作する正しい入力・条件でのテスト。「正しいIDとパスワードでログインできる」がその例。異常系と対で考える。' },
  { term: '異常系', aliases: ['異常ケース', 'エラーケース', 'unhappy path'], description: '不正な入力や想定外の操作でシステムがどう振る舞うかをテストする。「空のパスワードでログインしようとするとエラーが表示される」などを確認する。' },
  { term: '境界値', aliases: ['boundary value', 'boundary value analysis'], description: 'テストの重要な手法の一つ。有効範囲の端の値をテストする。「年齢は1〜120」なら0、1、120、121をテストする。境界でバグが多く発見される。' },
  { term: 'テスト計画', aliases: ['test plan'], description: 'テストの範囲、スケジュール、担当者、環境、合格基準などを定めた計画書。テスト開始前に作成し、プロジェクト全体のテスト活動を管理する。' },
  { term: 'バグ報告', aliases: ['bug report', '不具合報告', 'バグチケット'], description: 'テストで発見した不具合の内容を記録・報告すること。再現手順、期待する動作、実際の動作、スクリーンショットなどを含める。バグチケット、不具合票とも呼ぶ。' },
  { term: '再現手順', aliases: ['再現ステップ', 'steps to reproduce'], description: 'バグや不具合を再現させるための操作手順。「1.ログインする 2.○○ボタンを押す 3.エラーが発生する」のように具体的に書く。開発者がバグを修正するために必要。' },
  { term: '設計書', aliases: ['設計ドキュメント', 'design document'], description: 'システムの設計内容を記述した文書の総称。基本設計書・詳細設計書・DB設計書・画面設計書など様々な種類がある。要件を実装に変換するための重要な成果物。' },
  { term: 'テーブル定義書', aliases: ['テーブル定義', 'テーブル仕様書', 'table definition'], description: 'データベースの各テーブルの構造を定義したドキュメント。テーブル名、カラム名、データ型、桁数、NULL可否、デフォルト値、主キーなどを記載する。' },
  { term: '画面設計書', aliases: ['画面仕様書', 'screen design document'], description: '各画面のレイアウト・項目・動作を詳細に定義したドキュメント。画面の項目一覧、入力チェック、画面遷移、ボタン動作などを記載する。' },
  { term: '変更管理表', aliases: ['変更管理台帳', 'change log', '変更履歴'], description: 'プロジェクト中に発生した仕様変更や要件変更を管理する一覧表。変更内容、変更理由、影響範囲、担当者、対応状況などを記録する。' },
  { term: '整合性', aliases: ['consistency', '一貫性'], description: 'データや処理の内容が矛盾なく一致していること。「データの整合性を保つ」「設計書と実装の整合性を確認する」のように使われる。DBのトランザクションは整合性を守るための仕組み。' },
  { term: '権限管理', aliases: ['access control', 'アクセス制御', 'ロール管理'], description: 'システムの機能やデータにアクセスできる権限を管理すること。「管理者のみ削除できる」「一般ユーザーは閲覧のみ」のように、役割ごとにできることを制限する。' },
  { term: '再利用', aliases: ['reuse', 'コンポーネント再利用', '共通化'], description: '既存のコードやコンポーネントを別の場所でも使い回すこと。共通部品化・ライブラリ化により、開発効率の向上とバグの削減が期待できる。' },
  { term: 'ディザスタリカバリ', aliases: ['disaster recovery', '事業継続計画'], description: '自然災害・システム障害などの重大な事象が発生した際に、業務を復旧させるための計画・手順・仕組み。DRとも略す。バックアップサイトへの切り替えやデータ復旧が含まれる。' },
  { term: '一言', description: '内容全体をひと言で要約した短い表現です。まず要点だけを先に示したいときに役立ちます。' },
  { term: '言う', description: '言葉で内容を伝える行為です。書き言葉でも広く使える基本的な語です。' },
  { term: '良い', aliases: ['いい'], description: '望ましい、評価できる、または適切であることです。文脈によって品質、印象、判断を表します。' },
  { term: '言葉', description: '意味や考えを伝えるための表現です。単語、文、発話などを広く含みます。' },
  { term: '多く', description: '数や量が少なくないことです。何かと比較して語る場面でよく使われます。' },
  { term: '難しい', description: '理解、実行、判断が容易ではない状態です。技術文脈では複雑さや学習コストも含みます。' },
  { term: 'そのもの', description: '対象それ自体を強く指し示す言い方です。物事の本質や中核を強調するときに使います。' },
  { term: '不要', description: '価値が低い、または不要であることです。設計では取り除くべきものを示します。' },
  { term: '生まれる', description: '新しい状態や問題が発生することです。原因から結果への流れを自然に表せます。' },
  { term: '本質', description: '表面ではなく中心にある重要な性質です。議論の核心を指すときに使います。' },
  { term: '単なる', description: 'それ以上の意味を持たないことを示します。「単なる気合論」のように限定的に使います。' },
  { term: '精神論', description: '仕組みや根拠よりも気合いや姿勢に頼る考え方です。再現性が低いときに批判的に使われます。' },
  { term: '実務', description: '理論ではなく現場の実際の仕事です。運用、開発、報告などの現実感も含みます。' },
  { term: '状態', description: 'ある時点での様子や置かれた状況です。システムにも人にも広く使える基本語です。' },
  { term: 'つまり', description: '前の内容を言い換えたり要約したりする接続表現です。説明を整理して伝えるのに便利です。' },
  { term: 'さらに', description: 'さらに一段深く進めることを示す表現です。補足や展開の説明に向いています。' },
  { term: '意味', description: '言葉や事柄が持つ内容、価値、意図です。同じ語でも文脈で意味が変わります。' },
  { term: '端的', description: '無駄なく要点をまっすぐ示すことです。説明や結論でよく使われます。' },
  { term: 'まとめ', description: '複数の内容を整理して一つにまとめたものです。学習や報告で重要な役割を持ちます。' },
  { term: '単純さ', description: '構造や考え方が理解しやすい性質です。ソフトウェアでは品質や保守性と強く結びつきます。' },
  { term: 'Complexity', aliases: ['complexity'], description: '多くの要素が絡み合って理解しにくい状態です。バグや手戻りの原因としてよく議論されます。' },
  { term: '理解', description: '内容を把握して意味が分かることです。読み手、利用者、保守者のいずれにも必要です。' },
  { term: '理解ミス', description: '内容を誤って受け取ることです。設計や命名が悪いと起こりやすくなります。' },
  { term: '誤解', description: '意図したものと異なる意味で受け取ることです。会話でも仕様でもよく起こる問題です。' },
  { term: '曖昧', description: '一つの解釈に定まりにくいことです。要件や命名の曖昧さは不具合につながります。' },
  { term: '明確', description: 'はっきりしていて誤解されにくいことです。説明、仕様、責任範囲で重要です。' },
  { term: '整理', description: '情報や構造を分かりやすく整えることです。複雑さを減らす基本動作です。' },
  { term: '混在', description: '異なる種類のものが混ざっていることです。責務の混在は設計劣化の典型です。' },
  { term: '乱立', description: '多くの要素が制御なく増えていることです。ルールや例外が無秩序に増えると見通しが悪くなります。' },
  { term: '特別扱い', description: '一部だけを通常と違う扱いにすることです。必要な場合もありますが、増えすぎると危険です。' },
];
