// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: it (6/6)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_006: ReadonlyArray<GlossaryEntry> = [
  { term: 'プロミス', aliases: ['promiseオブジェクト'], description: '非同期処理の結果を表すオブジェクト。pending（待機）・fulfilled（成功）・rejected（失敗）の3状態を持つ。コールバック地獄を解消するために導入され、async/awaitと組み合わせることで同期的なコードに近い形で非同期処理を記述できる。' },
  { term: '構文', aliases: ['syntax', 'シンタックス', '文法'], description: 'プログラミング言語における「書き方のルール」。コンパイラやインタプリタが解析できるよう、キーワードや記号の並び方が決められている。構文エラー（シンタックスエラー）は記述ルール違反により発生し、実行前に検出される。セマンティクス（意味論）と対比して使われる。' },
  { term: 'セマンティクス', aliases: ['semantics', '意味論', 'セマンティック'], description: 'プログラムや言語の「意味」を扱う領域。構文（シンタックス）が書き方のルールであるのに対し、セマンティクスはその書き方が何を意味するかを定義する。セマンティックHTMLのように「タグが持つ意味」を重視する文脈でも使われる。' },
  { term: 'ミュータブル', aliases: ['mutable', '可変', '可変オブジェクト'], description: '作成後に内容を変更できるオブジェクトや値のこと。多くのデフォルトオブジェクトはミュータブルだが、共有された状態を複数箇所から変更するとバグの原因になりやすい。イミュータブルと対比して、変更可能性（mutability）の設計判断はコードの安全性に影響する。' },
  { term: 'データ型', aliases: ['data type', '型', 'プリミティブ型'], description: 'データが持つ種類と取り得る値の範囲を定義したもの。整数・浮動小数点数・文字列・真偽値などのプリミティブ型と、クラス・配列などの複合型がある。静的型付け言語では宣言時に型を指定し、型安全性を保証する。型によって使用できる操作や消費メモリが決まる。' },
  { term: 'データ構造', aliases: ['data structure', 'データ構造体'], description: 'データを効率的に格納・操作するための仕組みと形式。配列・連結リスト・スタック・キュー・ツリー・グラフ・ハッシュテーブルなどが代表例。適切なデータ構造の選択が処理速度とメモリ効率に直結する。アルゴリズムと一体で設計を考える。' },
  { term: '連結リスト', aliases: ['linked list', 'リンクドリスト', '線形リスト'], description: '各要素（ノード）がデータと次のノードへのポインタを持つデータ構造。先頭・末尾への挿入・削除がO(1)で高速だが、任意位置へのランダムアクセスはO(n)。双方向連結リストは前後両方にポインタを持つ。配列と比較して挿入・削除は得意、ランダムアクセスは苦手。' },
  { term: 'ツリー', aliases: ['tree', '木構造', 'ツリー構造'], description: '親子関係の階層でノードを繋いだデータ構造。根（ルート）ノードから始まり枝分かれする。二分探索木（BST）は効率的な検索を実現し、DOMツリーはHTMLの階層構造を表す。深さ優先探索（DFS）と幅優先探索（BFS）が代表的な走査アルゴリズム。' },
  { term: 'グラフ', aliases: ['graph', 'グラフ構造', 'ネットワーク構造'], description: 'ノード（頂点）とエッジ（辺）で構成されるデータ構造。ツリーと異なりサイクル（閉路）を持てる。有向グラフ・無向グラフ・重み付きグラフなどの種類がある。SNSの友人関係・ルート探索・依存関係解析などに利用される。最短経路問題にはダイクストラ法を用いる。' },
  { term: '計算量', aliases: ['computational complexity', '時間計算量', '空間計算量', '複雑度'], description: 'アルゴリズムが必要とする時間（時間計算量）とメモリ（空間計算量）の量。入力サイズnに対してどう増加するかをビッグO記法で表す。O(1)が最も効率よく、O(n²)になると入力が増えると急激に遅くなる。アルゴリズムや適切なデータ構造選択の判断基準となる。' },
  { term: 'ビッグO記法', aliases: ['ビッグo記法', 'big o notation', 'o記法', '漸近記法'], description: 'アルゴリズムの計算量を数学的に表記する方法。入力サイズnが大きくなったときの最悪ケースの増加率を示す。O(1)定数・O(log n)対数・O(n)線形・O(n log n)・O(n²)二乗・O(2ⁿ)指数などが代表例。定数倍は無視し、増加のオーダーで評価する。' },
  { term: '再帰', aliases: ['recursion', '再帰呼び出し', '再帰関数'], description: '関数が自分自身を呼び出すプログラミング手法。問題を同じ形の小さな部分問題に分割して解く。終了条件（ベースケース）を必ず定義しないと無限ループになる。ツリー走査・フィボナッチ数列・クイックソートなどに多用される。スタックオーバーフローのリスクがある。' },
  { term: 'SOLID原則', aliases: ['solid原則', 'solid principle', 'オブジェクト指向設計原則'], description: 'オブジェクト指向設計の5つの原則の頭文字。S（単一責任原則）・O（開放閉鎖原則）・L（リスコフ置換原則）・I（インターフェース分離原則）・D（依存関係逆転原則）。これらに従うことで変更に強く拡張しやすい設計になる。' },
  { term: 'オブザーバパターン', aliases: ['observer pattern', 'pub/subパターン'], description: 'オブジェクトの状態変化を他の複数オブジェクトに自動的に通知するデザインパターン。通知元（Subject/Publisher）と受信側（Observer/Subscriber）が疎結合に連携する。イベントリスナー・Reactのコンテキスト・RxJSなどが具体例。変更の影響範囲を動的に増減できる。' },
  { term: 'クリーンコード', aliases: ['clean code', '読みやすいコード'], description: '他者（将来の自分も含む）が読んで理解しやすいコードの総称。Robert C. Martinの同名書籍で体系化された。意図が明確な命名・小さな関数・適切なコメント・テスタブルな設計が主な要素。速く書くことより、変更・保守のコストを下げることを重視する考え方。' },
  { term: 'デッドコード', aliases: ['dead code', '到達不能コード', '未使用コード'], description: '実行フロー上で絶対に到達しない、または呼び出されない使われていないコード。if文のelseブロックが常にtrueの場合や、削除されたはずの古い関数が残っているケースなどが該当する。デッドコードはコードの可読性を下げ誤解を招くため、定期的に削除することが推奨される。' },
  { term: 'データ整合性', aliases: ['data consistency', 'データ一貫性'], description: 'データベースやシステム全体でデータが矛盾なく一貫した状態に保たれていること。外部キー制約・トランザクション・ACIDプロパティによって保証される。分散システムでは強整合性か結果整合性かのトレードオフが設計上の重要な判断事項となる。' },
  { term: 'スタックオーバーフロー', aliases: ['stack overflow', 'スタック溢れ'], description: '関数の呼び出しスタックがメモリ上限を超えて溢れるエラー。最も多い原因は終了条件のない再帰呼び出し。再帰の深さが設定を超えると発生する。末尾再帰最適化やループへの書き換えで回避できる。プログラマーのQ&Aサイト「Stack Overflow」名前の由来でもある。' },
  { term: '仮想化基盤', description: '仮想マシン、仮想ネットワーク、ストレージなどをまとめて提供・管理する基盤です。ハイパーバイザ、管理ツール、クラスタ機能などで構成されます。' },
  { term: '仮想化プラットフォーム', aliases: ['virtualization platform'], description: '仮想マシン・仮想ネットワーク・ストレージをまとめて提供・管理するプラットフォームです。ハイパーバイザ、管理ツール、クラスタリング機能などで構成されます。' },
  { term: '処理能力', description: '一定時間内に処理できる仕事量や性能の大きさです。' },
  { term: '1秒あたりの処理件数', description: '1秒間に処理できる件数を表す指標です。' },
  { term: '通常時', description: 'ピークではない平常時の利用状況です。' },
  { term: 'サービス全体', description: '個別部品ではなく利用者から見たサービスの全体範囲です。' },
  { term: '途中失敗', description: '処理の完了前に一部の段階で失敗することです。' },
  { term: '再実行', description: '失敗や中断の後に同じ処理をもう一度実行することです。' },
  { term: '再試行時', description: '処理や通信を再試行する場面やタイミングです。' },
  { term: '新機能追加', description: '既存システムに新しい機能を加えることです。' },
  { term: '地域展開', description: 'サービス提供範囲を複数の地域へ広げることです。' },
  { term: '管理操作', description: '設定変更や権限付与など管理者向けの操作です。' },
  { term: '設定変更', description: 'システムやサービスの設定値を変更することです。' },
  { term: 'コード修正', description: '不具合対応や改善のためにソースコードを直すことです。' },
  { term: 'コード管理', description: 'ソースコードの版管理や変更履歴を扱う運用です。' },
  { term: 'ログ出力', description: '処理状況や異常情報を記録として残すことです。' },
  { term: '分散構成', description: '処理や役割を複数のノードに分けて動かす構成です。' },
  { term: 'データ形式', description: 'データをどのような構造や表現で扱うかの形式です。' },
  { term: '文字コード', description: '文字を数値として表現するための符号化方式です。' },
  { term: '停止時間', description: 'サービスが利用できない停止中の時間です。' },
  { term: '設計段階', description: '実装前に構成や仕様を決める工程です。' },
  { term: '業務停止許容', description: '業務が停止しても許容できる時間や条件の範囲です。' },
  { term: '日本時間', description: '日本標準時を基準にした時刻です。' },
  { term: '効期限判定', description: '証明書やトークンが有効期限内かを判定することです。' },
  { term: '基盤技術', description: 'システム全体を支える共通の技術要素です。' },
  { term: '思考速度', description: '状況を理解して判断や発想を進める速さです。' },
  { term: '実装方針', description: 'どの方法や構成で実装するかの基本方針です。' },
  { term: 'テスト期待値', description: 'テストで正しい結果として期待する値や状態です。' },
  { term: 'Agent', aliases: ['agent'], description: '指示や状況に応じて処理を進める実行主体です。' },
  { term: 'Spec駆動', aliases: ['spec駆動'], description: '仕様を起点に設計や実装や検証を進める考え方です。' },
  { term: '自動テスト', description: '人手ではなくツールで自動実行するテストです。' },
  { term: '組織設計', description: '役割分担や責任範囲や意思決定の構造を設計することです。' },
  { term: 'FP法', aliases: ['fp法', 'function point法'], description: 'システムの大きさを、画面や帳票、入出力などの機能の量で見積もる方法です。人の作業量ではなく、まず機能の大きさを数える考え方です。' },
  { term: '人時', aliases: ['時間工数'], description: '1人が1時間働いた作業量です。工数を細かく表すときに使います。' },
  { term: '標準工期', description: '過去の実績データから見た、同規模プロジェクトの標準的な工期です。' },
  { term: '計画工期', aliases: ['予定工期'], description: 'プロジェクト開始前に計画として定めた工期です。予定している期間を表します。' },
  { term: '実績工期', description: 'プロジェクト完了後に実際にかかった工期です。' },
  { term: '工期遅延', aliases: ['納期遅延'], description: '計画していた工期より、実際の完了が遅れることです。' },
  { term: '開発費用', aliases: ['開発コスト'], description: 'システムを開発するためにかかる費用です。人件費や外注費などを含みます。' },
  { term: '人月単価', description: '1人月あたりの費用です。工数から開発費用を計算するときの基準になります。' },
  { term: '回帰式', aliases: ['回帰モデル'], description: '過去データの傾向をもとに、ある値から別の値を予測するための式です。' },
  { term: '決定係数', aliases: ['r2', 'r^2'], description: '回帰式が実際のデータにどれだけよく当てはまっているかを表す指標です。1に近いほど当てはまりが良いです。' },
  { term: '自由度調整済み決定係数', aliases: ['adjusted r2', 'adj. r2', '調整済み決定係数'], description: '決定係数を補正した指標です。説明変数の数の影響をならして、回帰式の当てはまりをより適切に見ます。' },
  { term: 'ユーザー総合テスト', description: '利用者の視点で、実際の業務に近い形でシステム全体を確認するテストです。' },
  { term: '初期フォロー', aliases: ['稼働後フォロー'], description: '本番稼働の直後に、利用開始時の問い合わせや不具合対応を行う期間です。' },
  { term: '換算欠陥数', aliases: ['重み付け欠陥数'], description: '重大度に応じて重み付けして数え直した欠陥数です。重い障害をより大きく評価します。' },
  { term: '換算欠陥率', aliases: ['重み付け欠陥率'], description: '換算欠陥数を工数で割った指標です。作業量に対してどれだけ欠陥が出たかを見ます。' },
  { term: '品質目標', description: 'プロジェクトで達成を目指す品質の基準値です。欠陥率やテスト基準などで設定します。' },
  { term: 'スクラッチ開発', aliases: ['フルスクラッチ'], description: '既製品に頼らず、必要なシステムを最初から個別に作る開発方式です。' },
  { term: 'パッケージ利用開発', aliases: ['パッケージ開発'], description: '既存の業務パッケージを利用し、設定や追加開発を行ってシステムを実現する方式です。' },
  { term: 'SaaS利用開発', aliases: ['saas利用開発', 'saas開発'], description: 'クラウド上の既存サービスを利用して業務システムを構成する開発方式です。' },
  { term: 'テスト基盤', description: '自動テストの実行、テストデータ準備、結果収集を支える共通の仕組みや環境です。' },
  { term: '改修速度', description: '不具合修正や機能改善を実装して反映するまでの速さです。' },
  { term: 'ローカル', description: '各開発者の手元の端末や、その端末上で動かす開発環境を指します。' },
  { term: '継続開発可能性', description: '現状の設計や運用のままで、今後も安全かつ効率的に開発を続けられる見込みです。' },
  { term: 'テスト実態', description: '計画書上の記載ではなく、実際にどのテストが存在し、実行され、維持されているかという現状です。' },
  { term: '開発フロー', description: '要件整理から実装、レビュー、テスト、リリースまでの作業手順やルールです。' },
  { term: 'TODO', aliases: ['todo'], description: '未実装や後で対応すべき作業が残っていることを示すコメントや印です。' },
  { term: 'FIXMEコメント', aliases: ['fixmeコメント'], description: '既知の問題があり、修正が必要だと示すためにコードへ残すコメントです。' },
  { term: 'カバレッジツール', description: 'どのコードがテストで実行されたかを計測し、網羅率を集計するツールです。' },
  { term: '変更影響の把握', description: 'ある変更がどの機能、クラス、モジュール、運用に波及するかを見極めることです。' },
  { term: 'リファクタリング不能', description: '構造の結合が強すぎるなどの理由で、安全に内部改善を進めにくい状態です。' },
  { term: 'テストレポート', description: 'テストの実行件数、成功・失敗、エラー詳細などをまとめた結果報告です。' },
  { term: 'カバレッジ計測', description: 'テストでどのコードが実行されたかを測定し、網羅率として可視化することです。' },
  { term: 'カバレッジ計測なし', description: 'テスト網羅率を測定する仕組みがなく、実行範囲を把握できていない状態です。' },
  { term: 'テストゼロ', description: '対象機能や対象モジュールに自動テストが1件も存在しない状態です。' },
  { term: 'テストなし', description: '確認すべき対象に対して、作成済みまたは実行中のテストが存在しない状態です。' },
  { term: 'Testcontainers', aliases: ['testcontainers'], description: 'テスト実行時にデータベースなどの依存サービスを使い捨てコンテナで起動するためのライブラリです。' },
  { term: 'JaCoCo', aliases: ['jacoco'], description: 'Java向けのテストカバレッジ計測ツールです。' },
  { term: 'Vladimir Khorikov', aliases: ['vladimir khorikov', 'ウラジミール・コリコフ'], description: 'ロシア出身のソフトウェアエンジニア・著述家。著書『Unit Testing: Principles, Practices, and Patterns』でテスト設計の原則を体系化し、「テストスイートへの信頼は100%カバレッジより価値がある」という思想で知られる。' },
  { term: 'Martin Fowler', aliases: ['martin fowler', 'マーティン・ファウラー'], description: 'イギリス出身のソフトウェアエンジニア・著述家。リファクタリング、アジャイル開発、ドメイン駆動設計などの普及に大きく貢献した。著書に『Refactoring』『Patterns of Enterprise Application Architecture』など多数。' },
  { term: 'Edward Yourdon', aliases: ['edward yourdon', 'エドワード・ヨードン'], description: 'アメリカのソフトウェアエンジニア・著述家。構造化設計・構造化分析の先駆者として知られる。「バグはコードの欠陥ではなくプロセスの失敗を語る物語だ」という思想でソフトウェア品質管理に大きな影響を与えた。' },
  { term: 'Linus Torvalds', aliases: ['linus torvalds', 'リーナス・トーバルズ'], description: 'フィンランド出身のソフトウェアエンジニア。LinuxカーネルおよびGit（分散型バージョン管理システム）の作者。2005年にBitKeeperの代替として約2週間でGitの初版を実装した。' },
  { term: 'コードカバレッジ', aliases: ['code coverage'], description: 'テスト実行中にソースコードのどの行・分岐・条件が実行されたかを示す指標。100%カバレッジがあっても検証（assert）が不十分であればバグは残り、品質を直接保証するものではない。テスト密度やバグ密度と組み合わせて評価することが重要。' },
  { term: '可視性問題', aliases: ['memory visibility', 'メモリ可視性'], description: 'あるスレッドが書き込んだ値が、他のスレッドから適切なタイミングで見えない現象。CPUキャッシュや命令の並べ替え（リオーダリング）によって発生し、Javaではvolatileキーワードやメモリバリアを用いて対処する。' },
  { term: '非決定性バグ', aliases: ['nondeterministic bug', 'ハイゼンバグ'], description: '同じ条件下でも再現したりしなかったりする不具合。並行処理の競合状態やタイミング依存が主な原因で、通常のロジックバグより検出・修正が著しく困難。並行処理の難しさを象徴する問題のひとつ。' },
  { term: 'テスト密度', description: 'ソースコードの規模に対してテストがどれだけ存在するかを示す指標。行数やステートメント数に対するテストケース数などで表す。バグ密度と組み合わせてテスト品質の充実度を評価するために用いる。' },
  { term: '回帰バグ', aliases: ['regression bug'], description: 'コード変更や機能追加により、以前は正常に動作していた機能が壊れてしまう不具合。継続的な自動テスト（リグレッションテスト）によって早期に検出することが重要で、CI/CDパイプラインの主要な目的のひとつ。' },
  { term: '並行性', description: '複数のタスクが同時に、または交互に実行されることを扱う性質や概念。並列性（同時物理実行）と異なり、シングルコアでも時分割により実現できる。スレッド、非同期I/O、アクターモデルなどのアプローチがある。人間の思考が直列的なため、並行性の理解と設計は困難とされる。' },
  { term: '並列性', description: '複数のタスクが物理的に同時に実行される性質。マルチコアCPUなどの複数プロセッサを活用して実現する。並行性（論理的な同時実行）と混同されやすいが、並行性は構造の問題、並列性は実行の問題として区別される。' },
  { term: 'ExecTORA', aliases: ['exectora'], description: 'システムエグゼが策定した開発標準体系の名称。SDD（仕様駆動開発）を中核に、AIエージェントによるテスト自動生成・検証、アプリプロフィール管理、局面レビュー、品質向上サイクルを定義する。開発成熟度をL1〜L5で評価する体系を持つ。' },
  { term: '意図を表す名前', aliases: ['intention-revealing names'], description: '変数・関数・クラスの名前に、何をするか・何を表すかの意図を明示する命名原則。Martin FowlerやRobert C. Martinが強調するクリーンコードの基本原則のひとつで、コメントなしでも意味が伝わる自己文書化コードの実現に直結する。' },
  { term: 'アプリプロフィール', description: 'ExecTORAにおいて各プロジェクトの特性・構成・品質状況・リスクを記録・管理するドキュメント。バグや障害から得た知見をナレッジとして蓄積し、次のプロジェクトの設計・開発方針に反映させるための組織資産として機能する。' },
  { term: 'ドキュメント整備', description: '仕様書、業務フロー図、画面モック、定義書などを分かりやすく整理し、共有可能な状態にすることです。品質安定に直結します。' },
  { term: '開発標準体系', description: '開発の進め方、レビュー、品質管理、評価などを組織として統一するための標準のまとまりです。' },
  { term: 'プロジェクトガイドライン', description: 'プロジェクトの進め方や品質指標などを示す指針です。現場ごとの進め方のばらつきを抑えます。' },
  { term: '開発標準', description: '組織として共通に守るべき開発のルールや手順、考え方のことです。' },
  { term: 'ガイドライン', description: '具体的な行動や判断のよりどころとなる指針です。標準より柔軟ですが、運用の方向性をそろえる役割があります。' },
  { term: '全体イメージ', description: '仕組み全体の構造や関係性を俯瞰して示す図や説明のことです。' },
  { term: '各工程', description: '要件定義、設計、実装、テストなど、開発を構成するそれぞれの段階を指します。' },
  { term: 'else', description: 'ifの条件に当てはまらなかったときに実行される処理です。' },
  { term: 'else if', aliases: ['elif'], description: '最初のif条件が偽のとき、別の条件を続けて確認する構文です。' },
  { term: 'switch', description: '値によって処理を分けるときに使う制御構文です。複数のcaseを持ちます。' },
  { term: 'default', description: 'switchでどのcaseにも当てはまらないときの処理です。また、初期設定の意味でも使われます。' },
  { term: 'do while', aliases: ['do...while'], description: 'まず1回処理を実行してから条件を確認し、条件が真の間繰り返すループ構文です。' },
  { term: 'break', description: '繰り返し処理やswitch文を途中で抜け出すための文です。' },
  { term: 'continue', description: '現在の繰り返しの残り処理をスキップし、次の繰り返しへ進む文です。' },
  { term: 'try', description: 'エラーが起きるかもしれない処理を囲み、例外を安全に扱うための構文です。' },
  { term: 'catch', description: 'tryブロックで発生した例外を受け取って処理する構文です。' },
  { term: 'finally', description: 'try-catchの後にエラーの有無に関係なく必ず実行される処理ブロックです。' },
  { term: 'throw', description: '意図的に例外を発生させる文です。エラー状態を呼び出し元に伝えるために使います。' },
  { term: 'statement', aliases: ['文'], description: 'プログラムにおける1つの命令や動作の単位です。代入文、条件文、ループ文などがあります。' },
  { term: 'expression', aliases: ['式'], description: '評価されて値を生み出すコードの断片です。1+2やa>bなどが式にあたります。' },
  { term: 'block', aliases: ['ブロック'], description: '波括弧{}などで囲まれた複数の文のまとまりです。if文やfor文の本体として使われます。' },
  { term: 'constant', aliases: ['const'], description: '一度代入したら変更できない値です。JavaScriptではconst、Javaではfinalなどで宣言します。' },
  { term: 'initialization', aliases: ['初期化'], description: '変数やオブジェクトに最初の値を設定することです。宣言と同時に行うことが多いです。' },
  { term: 'assignment', aliases: ['代入'], description: '変数に値を格納する操作です。多くの言語で=記号を使います。' },
  { term: 'string', description: '文字の並びを表すデータ型です。ダブルクォートやシングルクォートで囲んで記述します。' },
  { term: 'character', aliases: ['文字', 'char'], description: '1文字分のデータを表す型です。Javaのchar型などが代表例です。' },
  { term: 'number', description: '数を表すデータ型の総称です。整数と浮動小数点数を含みます。' },
  { term: 'integer', aliases: ['整数', 'int'], description: '小数部分を持たない数値型です。Javaではint、Pythonではintで扱います。' },
  { term: 'float', aliases: ['浮動小数点数'], description: '小数を含む数値を扱うデータ型です。精度に限りがあるため、金額計算には注意が必要です。' },
  { term: 'double', description: 'floatより高い精度で小数を扱える数値型です。64ビットの浮動小数点数を表します。' },
  { term: 'true', aliases: ['真'], description: '真偽値（boolean）における「真」を表す値です。条件式が成立するときに返されます。' },
  { term: 'false', aliases: ['偽'], description: '真偽値（boolean）における「偽」を表す値です。条件式が成立しないときに返されます。' },
  { term: 'null', aliases: ['ナル'], description: '値が存在しないことを明示的に表す特別な値です。undefinedとは異なり、意図的に「空」を設定した状態です。' },
  { term: 'array', description: '複数の値を順番に並べて格納するデータ構造です。インデックス（番号）で各要素にアクセスします。' },
  { term: 'value', description: '変数や式が保持・返却する具体的なデータそのものです。数値、文字列、オブジェクトなどがあります。' },
  { term: 'literal', aliases: ['リテラル'], description: 'ソースコード中に直接記述された値です。42、"hello"、trueなどがリテラルにあたります。' },
  { term: '==', aliases: ['等価演算子'], description: '左右の値が等しいかを比較する演算子です。JavaScriptでは型変換を行ってから比較します。' },
  { term: '!=', aliases: ['不等価演算子'], description: '左右の値が等しくないかを比較する演算子です。' },
  { term: '++', aliases: ['インクリメント'], description: '変数の値を1だけ増やす演算子です。i++やi+=1と同等です。' },
  { term: '--', aliases: ['デクリメント'], description: '変数の値を1だけ減らす演算子です。' },
  { term: '&&', aliases: ['論理and'], description: '両方の条件が真のときに真を返す論理演算子です。' },
  { term: '||', aliases: ['論理or'], description: 'どちらか一方の条件が真であれば真を返す論理演算子です。' },
  { term: '!', aliases: ['論理not'], description: '真偽値を反転させる論理演算子です。trueをfalseに、falseをtrueにします。' },
  { term: '?:', aliases: ['三項演算子', 'ternary operator'], description: '条件 ? 真の値 : 偽の値の形式で、条件により2つの値を使い分ける演算子です。' },
  { term: '+=', aliases: ['加算代入'], description: '現在の値に右辺を加算してそのまま代入する複合代入演算子です。a+=bはa=a+bと同等です。' },
  { term: 'return value', description: '関数が処理を終えて呼び出し元に返す値です。return文で指定します。' },
  { term: 'callback', aliases: ['コールバック関数'], description: '別の関数に引数として渡され、特定のタイミングで呼び出される関数です。非同期処理やイベント処理で頻繁に使われます。' },
  { term: 'anonymous function', aliases: ['無名関数'], description: '名前を持たずにその場で定義する関数です。コールバックや即時実行関数として使われます。' },
  { term: 'module', description: '機能ごとに分割されたコードのまとまりです。importやexportで他のファイルと連携します。' },
  { term: 'dependency', description: 'あるコードやモジュールが動作するために必要とする外部のライブラリやパッケージのことです。' },
  { term: 'instance', description: 'クラスという設計図から実際に生成された具体的なオブジェクトです。new演算子などで作成します。' },
  { term: 'constructor', aliases: ['コンストラクタ'], description: 'クラスからインスタンスを生成するときに最初に呼び出される特別なメソッドです。初期化処理を記述します。' },
  { term: 'public', description: 'クラスの外部からアクセスできることを示すアクセス修飾子です。' },
  { term: 'private', description: 'クラスの内部からのみアクセスできることを示すアクセス修飾子です。外部から直接操作できません。' },
  { term: 'protected', description: '同じクラスとその子クラスからアクセスできることを示すアクセス修飾子です。' },
  { term: 'static', aliases: ['静的'], description: 'インスタンスではなくクラス自体に属するメンバーを示すキーワードです。インスタンスを作らずに使えます。' },
  { term: 'override', aliases: ['オーバーライド'], description: '親クラスで定義されたメソッドを子クラスで上書きして、異なる振る舞いを実装することです。' },
  { term: 'composition', aliases: ['合成', 'コンポジション'], description: '継承ではなく、オブジェクトを部品として組み合わせて機能を構成する設計手法です。「has-a」の関係を表します。' },
  { term: 'association', aliases: ['関連'], description: 'オブジェクト同士が何らかの関係を持つことを表すオブジェクト指向の概念です。' },
  { term: 'tuple', aliases: ['タプル'], description: '複数の値を順序付きでまとめた、原則として変更不可のデータ構造です。Pythonなどで使われます。' },
  { term: 'binary tree', aliases: ['二分木'], description: '各ノードが最大2つの子ノードを持つ木構造です。探索や整列の基礎として重要です。' },
  { term: 'hash table', aliases: ['ハッシュテーブル'], description: 'キーをハッシュ関数で変換し、対応する値へ高速にアクセスできるデータ構造です。平均O(1)で検索できます。' },
  { term: 'heap', aliases: ['ヒープ'], description: '最大値または最小値を効率よく取り出せる木構造のデータ構造です。優先度付きキューの実装に使われます。' },
  { term: 'iteration', aliases: ['反復', 'イテレーション'], description: '同じ処理を条件が満たされるまで繰り返すことです。for文やwhile文で実現します。再帰と対比される概念です。' },
  { term: 'time complexity', description: '入力サイズに対して処理時間がどのように増加するかを示す指標です。Big O記法で表現します。' },
  { term: 'space complexity', description: 'アルゴリズムが必要とするメモリ量の増加傾向を示す指標です。' },
  { term: 'Big O', aliases: ['big o'], description: 'アルゴリズムの処理量やメモリ量の増え方を最悪ケースで表す記法です。O(n)、O(log n)、O(n²)などと書きます。' },
  { term: 'full stack', description: 'フロントエンドとバックエンドの両方を扱える開発者やスキルセットのことです。' },
  { term: 'IDE', aliases: ['ide', '統合開発環境'], description: 'エディタ、デバッガ、ビルドツールなどを統合した開発環境です。VS Code、IntelliJ IDEA、Eclipseなどが代表例です。' },
  { term: 'editor', aliases: ['エディタ', 'テキストエディタ'], description: 'ソースコードやテキストを編集するためのソフトウェアです。VS CodeやVimが代表例です。' },
  { term: 'compile', aliases: ['コンパイル'], description: '人間が読めるソースコードを、コンピュータが実行できる形式に変換する処理です。' },
  { term: 'interpret', aliases: ['インタプリタ', '解釈実行'], description: 'ソースコードを1行ずつ読み取りながら逐次実行する方式です。PythonやJavaScriptが代表例です。' },
  { term: 'install', aliases: ['インストール'], description: 'ソフトウェアやライブラリを使用可能な状態にセットアップすることです。' },
  { term: 'virtual environment', aliases: ['仮想環境', 'venv'], description: 'プロジェクトごとに独立したライブラリ環境を作る仕組みです。Python の venv や Node.js の node_modules が該当します。' },
  { term: 'script', description: 'コンパイルなしにインタプリタで逐次実行される比較的短いプログラムです。自動化によく使われます。' },
  { term: 'bug', description: 'プログラムが意図した通りに動作しない不具合のことです。デバッグによって原因を特定し修正します。' },
  { term: 'error', aliases: ['エラー'], description: 'プログラムの実行中や記述において何かが正しく動作していない状態や原因です。構文エラー、実行時エラーなどの種類があります。' },
  { term: 'syntax error', aliases: ['構文エラー'], description: 'プログラミング言語の文法規則に違反した記述により発生するエラーです。括弧の閉じ忘れやスペルミスが典型例です。' },
  { term: 'logic error', aliases: ['論理エラー'], description: '文法は正しいがプログラムの論理が誤っているため、期待と異なる結果になる不具合です。エラーメッセージが出ないため発見しにくいです。' },
  { term: 'stack trace', aliases: ['スタックトレース'], description: 'エラー発生時に、どの関数からどの関数へ呼び出しが連鎖したかを表示する情報です。原因箇所の特定に使います。' },
  { term: 'unit test', description: '関数やメソッドなど最小単位の部品が正しく動作するかを個別に確認するテストです。JestやJUnitなどのフレームワークで実行します。' },
  { term: 'E2E test', aliases: ['e2e test', 'end-to-end test', 'エンドツーエンドテスト'], description: 'ユーザーの操作を模倣して、システム全体が最初から最後まで正しく動くかを確認するテストです。' },
  { term: 'regression test', description: 'コード変更後に既存の機能が壊れていないかを確認するテストです。CI/CDで自動実行されることが多いです。' },
  { term: 'test case', description: '何をどのような条件で確認し、どんな結果を期待するかを定義した1つのテスト項目です。' },
  { term: 'coverage', description: 'テストがソースコードのどの範囲を実行したかの割合を示す指標です。行カバレッジや分岐カバレッジがあります。' },
  { term: 'lint', aliases: ['リント'], description: 'コードの書き方の問題や潜在的なバグを静的に検出するツールまたはその検査です。ESLintやPylintが代表例です。' },
  { term: 'refactor', aliases: ['リファクタ'], description: '外部から見た振る舞いを変えずに、コードの内部構造を改善する作業です。可読性や保守性の向上が目的です。' },
  { term: 'synchronous', description: '処理を上から順番に1つずつ実行し、前の処理が終わるまで次へ進まない方式です。' },
  { term: 'asynchronous', description: '処理の完了を待たずに次の処理へ進む方式です。APIコールやファイル読込など時間のかかる処理で使われます。' },
  { term: 'delay', description: '処理の実行を意図的に一定時間遅らせることです。setTimeout等で実現します。' },
  { term: 'parallel', aliases: ['並列'], description: '複数の処理を物理的に同時に実行することです。マルチコアCPUを活用して高速化できます。' },
  { term: 'logic', description: 'プログラムにおける条件判断や処理の流れの組み立て方です。ビジネスロジックは業務ルールの実装を指します。' },
  { term: 'condition', aliases: ['条件'], description: '真か偽かを判定するための式や内容です。if文やwhile文の判断基準として使われます。' },
  { term: 'comparison', aliases: ['比較'], description: '2つの値を比べて大小や等しさを判定する操作です。==、!=、<、>などの比較演算子を使います。' },
  { term: 'equal', aliases: ['等しい'], description: '【プログラミング】2つの値が同じであることです。プログラミングでは==や===で比較します。 【プログラミング】代入を表す=記号そのものを指す場合もあります。' },
  { term: 'not equal', aliases: ['等しくない'], description: '2つの値が異なることを表します。!=や!==で比較します。' },
  { term: 'greater than', aliases: ['大なり', 'より大きい'], description: '左辺が右辺より大きいことを表す比較です。>記号で表します。' },
  { term: 'less than', aliases: ['小なり', 'より小さい'], description: '左辺が右辺より小さいことを表す比較です。<記号で表します。' },
  { term: 'and', aliases: ['論理積'], description: 'すべての条件が真のときに真となる論理演算です。&&演算子で表されることが多いです。' },
  { term: 'or', aliases: ['論理和'], description: 'いずれかの条件が真であれば真となる論理演算です。||演算子で表されることが多いです。' },
  { term: 'not', aliases: ['否定', '論理否定'], description: '真偽値を反転させる論理演算です。!演算子で表されます。' },
  { term: 'random', aliases: ['ランダム', '乱数'], description: '規則性なく選ばれる値、またはそのような値を生成することです。Math.random()などで取得します。' },
  { term: 'seed', aliases: ['乱数シード'], description: '擬似乱数生成器の出力を決定する初期値です。同じシードを与えると同じ乱数列が再現されます。' },
  { term: 'CSV', aliases: ['csv', 'comma-separated values'], description: 'カンマで区切って表形式のデータを表すテキスト形式です。Excelやデータベースとの連携でよく使われます。' },
  { term: 'TXT', aliases: ['txt', 'テキストファイル'], description: '書式情報を含まないプレーンテキストのファイル形式です。' },
  { term: 'XML', aliases: ['xml', 'extensible markup language'], description: 'タグで構造化されたデータを表現するマークアップ言語です。設定ファイルやデータ交換に使われます。' },
  { term: 'Markdown', aliases: ['markdown', 'md'], description: '見出し、リスト、リンクなどを簡単な記号で記述できる軽量マークアップ言語です。READMEやドキュメントで広く使われます。' },
  { term: 'encoding', aliases: ['エンコーディング'], description: '文字をコンピュータが扱える数値に変換するルールです。UTF-8、Shift_JIS、ASCIIなどの種類があります。' },
  { term: 'UTF-8', aliases: ['utf-8'], description: '世界中の文字を扱える可変長の文字コードです。Webや多くのプログラミング環境で標準として使われています。' },
  { term: 'parse', aliases: ['パース', '構文解析'], description: '文字列やデータを読み取り、プログラムが扱える構造に分解・変換する処理です。JSON.parse()が代表例です。' },
  { term: 'serialize', aliases: ['シリアライズ', '直列化'], description: 'オブジェクトやデータ構造を保存や送信しやすい文字列・バイト列に変換する処理です。' },
  { term: 'deserialize', aliases: ['デシリアライズ'], description: 'シリアライズされた文字列・バイト列を元のデータ構造に復元する処理です。' },
  { term: 'programming language', aliases: ['プログラミング言語'], description: 'コンピュータに命令を伝えるための人工言語です。JavaScript、Python、Java、C#など多くの種類があります。' },
  { term: 'source code', description: '人間が読み書きできるテキスト形式で記述されたプログラムの原本です。' },
  { term: 'run', aliases: ['実行'], description: '書いたプログラムを動作させることです。コンパイル後の実行やスクリプトの直接実行があります。' },
  { term: 'sample code', aliases: ['サンプルコード'], description: '使い方や動作を説明するために示される例示用のコードです。ドキュメントやチュートリアルで使われます。' },
  { term: 'comment', description: 'プログラム中に書く人間向けの説明文です。実行時には無視されます。//や/* */で記述します。' },
  { term: 'indent', aliases: ['インデント', '字下げ'], description: 'コードの行頭にスペースやタブを入れて階層構造を視覚的に分かりやすくすることです。' },
  { term: 'semicolon', aliases: ['セミコロン'], description: '文の終わりを示す記号（;）です。Java、C、JavaScriptなどの言語で使われます。' },
  { term: 'debugging', aliases: ['デバッギング'], description: 'バグの原因を調査・特定し、修正する一連の作業です。ログ出力、ブレークポイント、ステップ実行などの手法があります。' },
  { term: 'practice', aliases: ['プラクティス'], description: '実際にコードを書いて動かしながら理解を深める学習方法です。プログラミングは手を動かすことが上達の近道です。' },
  { term: '{}', aliases: ['{', '}', '波括弧', 'ブレース', 'curly braces'], description: 'ブロックやオブジェクトの範囲を囲む記号です。関数本体、if文、オブジェクトリテラルなどで使われます。' },
  { term: '()', aliases: ['(', ')', '丸括弧', 'パーレン', 'parentheses'], description: '関数呼び出し、条件式の囲み、演算の優先順位指定などに使う記号です。' },
  { term: '[]', aliases: [']', '角括弧', 'ブラケット', 'square brackets'], description: '配列のリテラルや要素アクセスに使う記号です。array[0]のようにインデックスを指定します。' },
  { term: ';', description: '文の終わりを示す区切り記号です。Java、C、C#などでは必須、JavaScriptでは省略可能な場合があります。' },
  { term: ':', aliases: ['コロン', 'colon'], description: 'キーと値の区切り、型注釈、三項演算子の一部などに使われる記号です。JSONやPythonの辞書で頻出します。' },
  { term: ',', aliases: ['カンマ', 'コンマ', 'comma'], description: '配列の要素、関数の引数、オブジェクトのプロパティなどを区切る記号です。' },
  { term: 'ダブルクォート', aliases: ['二重引用符', 'double quote'], description: '文字列リテラルを囲む記号（"）です。多くの言語でシングルクォートと同等に使えますが、JSONではダブルクォートのみ有効です。' },
  { term: 'シングルクォート', aliases: ['一重引用符', 'single quote'], description: '文字列リテラルを囲む記号（\'）です。JavaScriptやPythonで使われます。Javaでは1文字（char型）専用です。' },
  { term: 'バックスラッシュ', aliases: ['逆斜線', 'backslash'], description: 'エスケープ文字として使われる記号（\\）です。\\nで改行、\\tでタブなど特殊文字を表現します。Windowsのパス区切りでもあります。' },
  { term: 'アットマーク', aliases: ['@', 'at sign'], description: 'メールアドレスの区切り、デコレータ（Python）、アノテーション（Java）、メンション（SNS）などに使われる記号です。' },
  { term: 'ドル記号', aliases: ['$', 'dollar sign'], description: '変数名のプレフィックス（PHP、jQuery）やテンプレートリテラルの埋め込み式（${...}）に使われる記号です。' },
  { term: 'アンパサンド', aliases: ['&', 'ampersand'], description: '論理AND（&&）、ビットAND（&）、HTMLエンティティ（&amp;）、URLパラメータの区切りなどに使われる記号です。' },
  { term: 'パイプ', aliases: ['|', 'pipe'], description: '論理OR（||）、ビットOR（|）、シェルのパイプライン、TypeScriptのユニオン型（A | B）などに使われる記号です。' },
  { term: 'チルダ', aliases: ['~', 'tilde'], description: 'ビットNOT演算子、ホームディレクトリの省略表記（Unix系）、バージョン範囲指定（~1.2.3）などに使われる記号です。' },
  { term: 'キャレット', aliases: ['^', 'caret'], description: 'ビットXOR演算子、正規表現の行頭一致、バージョン範囲指定（^1.2.3）などに使われる記号です。' },
  { term: 'アンダースコア', aliases: ['_', 'アンダーバー', 'underscore'], description: '変数名やファイル名でスペースの代わりに使われる記号（_）です。snake_caseの区切りやプライベートメンバーの慣習的接頭辞として使われます。' },
];
