/**
 * Gradle用語集
 * Gradleコマンド・タスク・DSLの説明
 */

import { CliGlossaryEntry } from './gitGlossary';

export const GRADLE_GLOSSARY: ReadonlyArray<CliGlossaryEntry> = [
  // === 基本コマンド ===
  { term: 'gradle', description: 'Gradle。柔軟なビルド自動化ツール。Groovy/Kotlin DSLで設定。' },
  { term: 'gradle --version', description: 'Gradleのバージョンを表示。', aliases: ['gradle -v'] },
  { term: 'gradle --help', description: 'ヘルプを表示。', aliases: ['gradle -h', 'gradle -?'] },

  // === Gradle Wrapper ===
  { term: 'gradlew', description: 'Gradle Wrapper。プロジェクトにバンドルされたGradle。', aliases: ['./gradlew'] },
  { term: 'gradlew.bat', description: 'Gradle Wrapper（Windows）。' },
  { term: 'gradle wrapper', description: 'Gradle Wrapperを生成。' },
  { term: 'gradle wrapper --gradle-version', description: '指定バージョンのWrapperを生成。' },
  { term: 'gradle wrapper --distribution-type', description: 'ディストリビューションタイプを指定（bin/all）。' },
  { term: 'gradle-wrapper.properties', description: 'Wrapperの設定ファイル。' },

  // === よく使うタスク ===
  { term: 'gradle build', description: 'プロジェクトをビルド。' },
  { term: 'gradle clean', description: 'ビルド成果物を削除。' },
  { term: 'gradle clean build', description: 'クリーンしてビルド。' },
  { term: 'gradle assemble', description: 'アーティファクトをアセンブル（テストなし）。' },
  { term: 'gradle check', description: 'テストと検査を実行。' },
  { term: 'gradle test', description: 'ユニットテストを実行。' },
  { term: 'gradle integrationTest', description: '統合テストを実行。' },
  { term: 'gradle jar', description: 'JARファイルを作成。' },
  { term: 'gradle war', description: 'WARファイルを作成。' },
  { term: 'gradle bootJar', description: 'Spring Boot実行可能JARを作成。' },
  { term: 'gradle bootRun', description: 'Spring Bootアプリケーションを実行。' },
  { term: 'gradle bootBuildImage', description: 'Spring BootのDockerイメージを作成。' },
  { term: 'gradle javadoc', description: 'Javadocを生成。' },
  { term: 'gradle publish', description: 'アーティファクトを公開。' },
  { term: 'gradle publishToMavenLocal', description: 'ローカルMavenリポジトリに公開。' },
  { term: 'gradle install', description: 'ローカルMavenリポジトリにインストール（非推奨）。' },

  // === タスク情報 ===
  { term: 'gradle tasks', description: '利用可能なタスク一覧を表示。' },
  { term: 'gradle tasks --all', description: '全タスクを表示。' },
  { term: 'gradle tasks --group', description: '指定グループのタスクを表示。' },
  { term: 'gradle help --task', description: 'タスクのヘルプを表示。' },
  { term: 'gradle properties', description: 'プロジェクトプロパティを表示。' },
  { term: 'gradle projects', description: 'サブプロジェクト一覧を表示。' },
  { term: 'gradle dependencies', description: '依存関係ツリーを表示。' },
  { term: 'gradle dependencies --configuration', description: '指定コンフィグレーションの依存を表示。' },
  { term: 'gradle dependencyInsight', description: '特定依存の詳細を表示。' },
  { term: 'gradle dependencyInsight --dependency', description: '依存名を指定。' },
  { term: 'gradle buildEnvironment', description: 'ビルド環境の依存を表示。' },
  { term: 'gradle components', description: 'コンポーネント一覧を表示。' },
  { term: 'gradle model', description: 'ソフトウェアモデルを表示。' },
  { term: 'gradle outgoingVariants', description: '公開バリアントを表示。' },
  { term: 'gradle resolvableConfigurations', description: '解決可能なコンフィグレーションを表示。' },

  // === コマンドオプション ===
  { term: 'gradle -x', description: 'タスクをスキップ。', aliases: ['gradle --exclude-task'] },
  { term: 'gradle -x test', description: 'テストをスキップ。' },
  { term: 'gradle --continue', description: '失敗しても続行。' },
  { term: 'gradle --parallel', description: '並列ビルド。' },
  { term: 'gradle --max-workers', description: 'ワーカー数を指定。' },
  { term: 'gradle --no-parallel', description: '並列ビルドを無効化。' },
  { term: 'gradle --build-cache', description: 'ビルドキャッシュを有効化。' },
  { term: 'gradle --no-build-cache', description: 'ビルドキャッシュを無効化。' },
  { term: 'gradle --configuration-cache', description: '設定キャッシュを有効化。' },
  { term: 'gradle --no-configuration-cache', description: '設定キャッシュを無効化。' },
  { term: 'gradle -q', description: '静かモード。', aliases: ['gradle --quiet'] },
  { term: 'gradle -i', description: '情報ログを表示。', aliases: ['gradle --info'] },
  { term: 'gradle -d', description: 'デバッグログを表示。', aliases: ['gradle --debug'] },
  { term: 'gradle -w', description: '警告ログを表示。', aliases: ['gradle --warn'] },
  { term: 'gradle --stacktrace', description: 'スタックトレースを表示。', aliases: ['gradle -s'] },
  { term: 'gradle --full-stacktrace', description: '完全なスタックトレースを表示。', aliases: ['gradle -S'] },
  { term: 'gradle --scan', description: 'ビルドスキャンを作成。' },
  { term: 'gradle --offline', description: 'オフラインモード。' },
  { term: 'gradle --refresh-dependencies', description: '依存を強制リフレッシュ。' },
  { term: 'gradle --rerun-tasks', description: 'キャッシュを無視してタスクを再実行。' },
  { term: 'gradle --no-daemon', description: 'デーモンを使用しない。' },
  { term: 'gradle --daemon', description: 'デーモンを使用。' },
  { term: 'gradle --stop', description: 'デーモンを停止。' },
  { term: 'gradle --status', description: 'デーモンの状態を表示。' },
  { term: 'gradle -b', description: 'ビルドファイルを指定。', aliases: ['gradle --build-file'] },
  { term: 'gradle -c', description: '設定ファイルを指定。', aliases: ['gradle --settings-file'] },
  { term: 'gradle -p', description: 'プロジェクトディレクトリを指定。', aliases: ['gradle --project-dir'] },
  { term: 'gradle -g', description: 'Gradleユーザーホームを指定。', aliases: ['gradle --gradle-user-home'] },
  { term: 'gradle -P', description: 'プロジェクトプロパティを設定。', aliases: ['gradle --project-prop'] },
  { term: 'gradle -D', description: 'システムプロパティを設定。', aliases: ['gradle --system-prop'] },
  { term: 'gradle -I', description: '初期化スクリプトを指定。', aliases: ['gradle --init-script'] },
  { term: 'gradle --console', description: 'コンソール出力タイプを指定（plain/auto/rich/verbose）。' },
  { term: 'gradle --warning-mode', description: '警告モードを指定（all/fail/summary/none）。' },
  { term: 'gradle -m', description: 'ドライラン（実行しない）。', aliases: ['gradle --dry-run'] },
  { term: 'gradle --profile', description: 'ビルドプロファイルを生成。' },
  { term: 'gradle --write-locks', description: '依存ロックファイルを更新。' },
  { term: 'gradle --update-locks', description: '指定依存のロックを更新。' },

  // === init タスク ===
  { term: 'gradle init', description: '新しいGradleプロジェクトを初期化。' },
  { term: 'gradle init --type', description: 'プロジェクトタイプを指定。' },
  { term: 'gradle init --type java-application', description: 'Javaアプリケーションを初期化。' },
  { term: 'gradle init --type java-library', description: 'Javaライブラリを初期化。' },
  { term: 'gradle init --type kotlin-application', description: 'Kotlinアプリケーションを初期化。' },
  { term: 'gradle init --type kotlin-library', description: 'Kotlinライブラリを初期化。' },
  { term: 'gradle init --dsl', description: 'DSLを指定（groovy/kotlin）。' },
  { term: 'gradle init --test-framework', description: 'テストフレームワークを指定。' },
  { term: 'gradle init --package', description: 'パッケージ名を指定。' },
  { term: 'gradle init --project-name', description: 'プロジェクト名を指定。' },

  // === ビルドファイル（Groovy DSL） ===
  { term: 'build.gradle', description: 'ビルド設定ファイル（Groovy DSL）。' },
  { term: 'settings.gradle', description: 'プロジェクト設定ファイル（Groovy DSL）。' },
  { term: 'gradle.properties', description: 'Gradleプロパティファイル。' },

  // === ビルドファイル（Kotlin DSL） ===
  { term: 'build.gradle.kts', description: 'ビルド設定ファイル（Kotlin DSL）。' },
  { term: 'settings.gradle.kts', description: 'プロジェクト設定ファイル（Kotlin DSL）。' },

  // === プラグイン ===
  { term: 'plugins', description: 'プラグインの適用。' },
  { term: 'plugins { }', description: 'プラグインブロック。' },
  { term: 'id', description: 'プラグインIDを指定。' },
  { term: 'version', description: 'プラグインバージョンを指定。' },
  { term: 'apply', description: 'プラグインを適用。' },
  { term: 'apply plugin:', description: 'プラグインを適用（レガシー）。' },
  { term: 'java', description: 'Javaプラグイン。Javaプロジェクト用。' },
  { term: 'java-library', description: 'Javaライブラリプラグイン。' },
  { term: 'application', description: 'アプリケーションプラグイン。' },
  { term: 'war', description: 'WARプラグイン。' },
  { term: 'ear', description: 'EARプラグイン。' },
  { term: 'maven-publish', description: 'Maven公開プラグイン。' },
  { term: 'signing', description: '署名プラグイン。' },
  { term: 'jacoco', description: 'JaCoCoカバレッジプラグイン。' },
  { term: 'checkstyle', description: 'Checkstyleプラグイン。' },
  { term: 'pmd', description: 'PMDプラグイン。' },
  { term: 'spotbugs', description: 'SpotBugsプラグイン。' },
  { term: 'idea', description: 'IntelliJ IDEAプラグイン。' },
  { term: 'eclipse', description: 'Eclipseプラグイン。' },
  { term: 'org.springframework.boot', description: 'Spring Bootプラグイン。' },
  { term: 'io.spring.dependency-management', description: 'Spring依存管理プラグイン。' },
  { term: 'com.github.johnrengelman.shadow', description: 'Shadowプラグイン（uber-JAR作成）。' },
  { term: 'org.jetbrains.kotlin.jvm', description: 'Kotlin JVMプラグイン。' },
  { term: 'com.android.application', description: 'Androidアプリケーションプラグイン。' },
  { term: 'com.android.library', description: 'Androidライブラリプラグイン。' },

  // === 依存関係 ===
  { term: 'dependencies', description: '依存関係の定義。' },
  { term: 'dependencies { }', description: '依存関係ブロック。' },
  { term: 'implementation', description: '実装依存（API非公開）。' },
  { term: 'api', description: 'API依存（推移的に公開）。' },
  { term: 'compileOnly', description: 'コンパイル時のみ必要。' },
  { term: 'runtimeOnly', description: '実行時のみ必要。' },
  { term: 'testImplementation', description: 'テスト実装依存。' },
  { term: 'testCompileOnly', description: 'テストコンパイル時のみ必要。' },
  { term: 'testRuntimeOnly', description: 'テスト実行時のみ必要。' },
  { term: 'annotationProcessor', description: 'アノテーションプロセッサ。' },
  { term: 'kapt', description: 'Kotlinアノテーションプロセッサ。' },
  { term: 'providedCompile', description: 'WAR用のコンパイル時依存。' },
  { term: 'providedRuntime', description: 'WAR用の実行時依存。' },
  { term: 'compile', description: 'コンパイル依存（非推奨、implementationを使用）。' },
  { term: 'runtime', description: '実行時依存（非推奨、runtimeOnlyを使用）。' },
  { term: 'testCompile', description: 'テストコンパイル依存（非推奨）。' },
  { term: 'testRuntime', description: 'テスト実行時依存（非推奨）。' },
  { term: 'project', description: 'プロジェクト依存。' },
  { term: 'project(":")', description: 'ルートプロジェクトへの依存。' },
  { term: 'project(":subproject")', description: 'サブプロジェクトへの依存。' },
  { term: 'files', description: 'ファイル依存。' },
  { term: 'fileTree', description: 'ファイルツリー依存。' },
  { term: 'platform', description: 'BOM/プラットフォーム依存。' },
  { term: 'enforcedPlatform', description: '強制プラットフォーム依存。' },
  { term: 'exclude', description: '推移的依存の除外。' },
  { term: 'exclude group:', description: 'グループを除外。' },
  { term: 'exclude module:', description: 'モジュールを除外。' },
  { term: 'force', description: 'バージョンを強制。' },
  { term: 'strictly', description: '厳格なバージョン制約。' },
  { term: 'prefer', description: '優先バージョン。' },
  { term: 'reject', description: '拒否するバージョン。' },
  { term: 'because', description: 'バージョン選択の理由を記述。' },
  { term: 'changing', description: '変更可能な依存としてマーク。' },
  { term: 'transitive', description: '推移的依存の有効/無効。' },

  // === リポジトリ ===
  { term: 'repositories', description: 'リポジトリの定義。' },
  { term: 'repositories { }', description: 'リポジトリブロック。' },
  { term: 'mavenCentral()', description: 'Maven Central Repository。' },
  { term: 'mavenLocal()', description: 'ローカルMavenリポジトリ。' },
  { term: 'google()', description: 'Google Maven Repository。' },
  { term: 'gradlePluginPortal()', description: 'Gradle Plugin Portal。' },
  { term: 'jcenter()', description: 'JCenter（非推奨）。' },
  { term: 'maven { }', description: 'カスタムMavenリポジトリ。' },
  { term: 'maven { url }', description: 'MavenリポジトリURLを指定。' },
  { term: 'maven { credentials { } }', description: 'Maven認証情報を指定。' },
  { term: 'ivy { }', description: 'Ivyリポジトリ。' },
  { term: 'flatDir', description: 'フラットディレクトリリポジトリ。' },

  // === タスク定義 ===
  { term: 'task', description: 'タスクを定義。' },
  { term: 'tasks.register', description: 'タスクを遅延登録。' },
  { term: 'tasks.named', description: '既存タスクを参照。' },
  { term: 'doFirst', description: 'タスク実行前のアクション。' },
  { term: 'doLast', description: 'タスク実行後のアクション。' },
  { term: 'dependsOn', description: 'タスクの依存関係。' },
  { term: 'finalizedBy', description: 'タスク完了後に実行。' },
  { term: 'mustRunAfter', description: '実行順序を指定（依存ではない）。' },
  { term: 'shouldRunAfter', description: '推奨実行順序を指定。' },
  { term: 'onlyIf', description: '条件付き実行。' },
  { term: 'enabled', description: 'タスクの有効/無効。' },
  { term: 'inputs', description: 'タスク入力。' },
  { term: 'outputs', description: 'タスク出力。' },
  { term: 'group', description: 'タスクグループ。' },
  { term: 'description', description: 'タスクの説明。' },

  // === タスクタイプ ===
  { term: 'Copy', description: 'ファイルコピータスク。' },
  { term: 'Delete', description: 'ファイル削除タスク。' },
  { term: 'Zip', description: 'ZIP作成タスク。' },
  { term: 'Tar', description: 'TAR作成タスク。' },
  { term: 'Jar', description: 'JAR作成タスク。' },
  { term: 'War', description: 'WAR作成タスク。' },
  { term: 'JavaCompile', description: 'Javaコンパイルタスク。' },
  { term: 'Test', description: 'テスト実行タスク。' },
  { term: 'Javadoc', description: 'Javadoc生成タスク。' },
  { term: 'Exec', description: '外部コマンド実行タスク。' },
  { term: 'JavaExec', description: 'Java実行タスク。' },
  { term: 'GradleBuild', description: '別ビルドを実行するタスク。' },

  // === Java設定 ===
  { term: 'java { }', description: 'Java設定ブロック。' },
  { term: 'sourceCompatibility', description: 'ソース互換性バージョン。' },
  { term: 'targetCompatibility', description: 'ターゲット互換性バージョン。' },
  { term: 'toolchain', description: 'Javaツールチェーン設定。' },
  { term: 'toolchain { languageVersion }', description: 'Java言語バージョンを指定。' },
  { term: 'withJavadocJar()', description: 'Javadoc JARを生成。' },
  { term: 'withSourcesJar()', description: 'ソースJARを生成。' },
  { term: 'sourceSets', description: 'ソースセットの定義。' },
  { term: 'sourceSets { main { } }', description: 'メインソースセット。' },
  { term: 'sourceSets { test { } }', description: 'テストソースセット。' },
  { term: 'srcDirs', description: 'ソースディレクトリ。' },
  { term: 'resources', description: 'リソースディレクトリ。' },

  // === テスト設定 ===
  { term: 'test { }', description: 'テスト設定ブロック。' },
  { term: 'useJUnitPlatform()', description: 'JUnit 5を使用。' },
  { term: 'useJUnit()', description: 'JUnit 4を使用。' },
  { term: 'useTestNG()', description: 'TestNGを使用。' },
  { term: 'testLogging', description: 'テストログ設定。' },
  { term: 'testLogging { events }', description: 'ログイベントを設定。' },
  { term: 'maxParallelForks', description: '並列テストフォーク数。' },
  { term: 'forkEvery', description: 'フォーク頻度。' },
  { term: 'jvmArgs', description: 'テストJVMの引数。' },
  { term: 'systemProperty', description: 'システムプロパティを設定。' },
  { term: 'environment', description: '環境変数を設定。' },
  { term: 'filter', description: 'テストフィルタ。' },
  { term: 'include', description: '含めるテスト。' },
  { term: 'exclude', description: '除外するテスト。' },

  // === 公開設定 ===
  { term: 'publishing { }', description: '公開設定ブロック。' },
  { term: 'publications { }', description: '公開物の定義。' },
  { term: 'repositories { }', description: '公開先リポジトリ。' },
  { term: 'MavenPublication', description: 'Maven公開物。' },
  { term: 'from components.java', description: 'Javaコンポーネントを公開。' },
  { term: 'artifact', description: '追加アーティファクト。' },
  { term: 'pom { }', description: 'POM情報の設定。' },
  { term: 'pom.withXml { }', description: 'POM XMLを直接編集。' },

  // === プロパティ・環境変数 ===
  { term: 'ext', description: '追加プロパティ。' },
  { term: 'ext { }', description: '追加プロパティブロック。' },
  { term: 'project.property', description: 'プロジェクトプロパティを取得。' },
  { term: 'findProperty', description: 'プロパティを検索（nullならnull）。' },
  { term: 'hasProperty', description: 'プロパティの存在確認。' },
  { term: 'System.getenv', description: '環境変数を取得。' },
  { term: 'providers.gradleProperty', description: 'プロパティプロバイダ。' },
  { term: 'providers.environmentVariable', description: '環境変数プロバイダ。' },
  { term: 'providers.systemProperty', description: 'システムプロパティプロバイダ。' },

  // === マルチプロジェクト ===
  { term: 'rootProject', description: 'ルートプロジェクト。' },
  { term: 'subprojects', description: '全サブプロジェクトに設定を適用。' },
  { term: 'allprojects', description: '全プロジェクトに設定を適用。' },
  { term: 'project(":")', description: 'プロジェクトを参照。' },
  { term: 'include', description: 'サブプロジェクトを含める。' },
  { term: 'includeBuild', description: '複合ビルドを含める。' },
  { term: 'buildSrc', description: 'ビルドロジック用の特別なプロジェクト。' },

  // === バージョンカタログ ===
  { term: 'libs.versions.toml', description: 'バージョンカタログファイル。' },
  { term: 'versionCatalogs', description: 'バージョンカタログ設定。' },
  { term: 'libs', description: 'デフォルトのバージョンカタログ参照。' },
  { term: '[versions]', description: 'バージョン定義セクション。' },
  { term: '[libraries]', description: 'ライブラリ定義セクション。' },
  { term: '[plugins]', description: 'プラグイン定義セクション。' },
  { term: '[bundles]', description: 'バンドル定義セクション。' },

  // === キャッシュ・デーモン ===
  { term: 'buildCache', description: 'ビルドキャッシュ設定。' },
  { term: 'local { }', description: 'ローカルキャッシュ設定。' },
  { term: 'remote { }', description: 'リモートキャッシュ設定。' },
  { term: 'GRADLE_USER_HOME', description: 'Gradleユーザーホームディレクトリ。' },
  { term: '~/.gradle', description: 'Gradleユーザーホーム（デフォルト）。' },
  { term: '~/.gradle/caches', description: 'Gradleキャッシュディレクトリ。' },
  { term: 'daemon', description: 'Gradleデーモン。バックグラウンドプロセス。' },
  { term: 'org.gradle.daemon', description: 'デーモンの有効/無効設定。' },
  { term: 'org.gradle.parallel', description: '並列ビルドの有効/無効設定。' },
  { term: 'org.gradle.caching', description: 'ビルドキャッシュの有効/無効設定。' },
  { term: 'org.gradle.jvmargs', description: 'Gradle JVMの引数。' },
  { term: 'org.gradle.java.home', description: 'Gradle用Javaホーム。' },
  { term: 'org.gradle.workers.max', description: '最大ワーカー数。' },
  { term: 'org.gradle.configuration-cache', description: '設定キャッシュの有効/無効。' },

  // === 概念・用語 ===
  { term: 'configuration', description: '依存関係のグループ化単位。' },
  { term: 'artifact', description: 'ビルド成果物。' },
  { term: 'variant', description: 'ライブラリの異なるバージョン/形式。' },
  { term: 'capability', description: '依存が提供する機能。' },
  { term: 'attribute', description: 'バリアント選択の属性。' },
  { term: 'composite build', description: '複合ビルド。複数プロジェクトを統合。' },
  { term: 'included build', description: '複合ビルドに含まれるビルド。' },
  { term: 'lazy configuration', description: '遅延設定。必要時に評価。' },
  { term: 'provider', description: '遅延評価値のラッパー。' },
  { term: 'property', description: '設定可能なプロパティ。' },
  { term: 'convention', description: 'プラグインのデフォルト設定。' },
  { term: 'extension', description: 'プラグインの設定拡張。' },
  { term: 'DSL', description: 'Domain Specific Language。' },
  { term: 'Groovy DSL', description: 'Groovyベースの設定記法。' },
  { term: 'Kotlin DSL', description: 'Kotlinベースの設定記法。' },
  { term: 'incremental build', description: 'インクリメンタルビルド。変更部分のみ再ビルド。' },
  { term: 'up-to-date check', description: '最新状態チェック。再実行不要か判定。' },
  { term: 'build scan', description: 'ビルド分析レポート。' },
];
