/**
 * Java CLI用語集
 * Java開発ツール（JDK）コマンド・オプションの説明
 */

import { CliGlossaryEntry } from './gitGlossary';

export const JAVA_CLI_GLOSSARY: ReadonlyArray<CliGlossaryEntry> = [
  // === java ===
  { term: 'java', description: 'Javaアプリケーションを実行するランチャー。' },
  { term: 'java -version', description: 'Javaのバージョンを表示。' },
  { term: 'java -jar', description: 'JARファイルを実行する。' },
  { term: 'java -cp', description: 'クラスパスを指定。', aliases: ['java -classpath', 'java --class-path'] },
  { term: 'java -D', description: 'システムプロパティを設定。' },
  { term: 'java -Xms', description: '初期ヒープサイズを設定。' },
  { term: 'java -Xmx', description: '最大ヒープサイズを設定。' },
  { term: 'java -Xss', description: 'スタックサイズを設定。' },
  { term: 'java -Xmn', description: 'Young世代のサイズを設定。' },
  { term: 'java -XX:+UseG1GC', description: 'G1ガベージコレクタを使用。' },
  { term: 'java -XX:+UseZGC', description: 'ZGCガベージコレクタを使用。' },
  { term: 'java -XX:+UseShenandoahGC', description: 'ShenandoahGCを使用。' },
  { term: 'java -XX:+UseParallelGC', description: 'パラレルGCを使用。' },
  { term: 'java -XX:+UseConcMarkSweepGC', description: 'CMS GCを使用（非推奨）。' },
  { term: 'java -XX:MaxGCPauseMillis', description: 'GC停止時間の目標を設定。' },
  { term: 'java -XX:+HeapDumpOnOutOfMemoryError', description: 'OOM時にヒープダンプを出力。' },
  { term: 'java -XX:HeapDumpPath', description: 'ヒープダンプの出力先を指定。' },
  { term: 'java -XX:+PrintGCDetails', description: 'GCの詳細を出力。' },
  { term: 'java -XX:+PrintGCDateStamps', description: 'GCログに日時を追加。' },
  { term: 'java -Xlog:gc', description: 'GCログを出力（Java 9+）。' },
  { term: 'java -XX:MetaspaceSize', description: 'Metaspace初期サイズを設定。' },
  { term: 'java -XX:MaxMetaspaceSize', description: 'Metaspace最大サイズを設定。' },
  { term: 'java -XX:+UseStringDeduplication', description: '文字列重複排除を有効化。' },
  { term: 'java -XX:+UseCompressedOops', description: '圧縮オブジェクトポインタを使用。' },
  { term: 'java -XX:MaxDirectMemorySize', description: 'ダイレクトメモリの最大サイズを設定。' },
  { term: 'java -XX:+UnlockExperimentalVMOptions', description: '実験的オプションを有効化。' },
  { term: 'java -XX:+UnlockDiagnosticVMOptions', description: '診断オプションを有効化。' },
  { term: 'java -verbose:gc', description: 'GC情報を出力。' },
  { term: 'java -verbose:class', description: 'クラスロード情報を出力。' },
  { term: 'java -ea', description: 'アサーションを有効化。', aliases: ['java -enableassertions'] },
  { term: 'java -da', description: 'アサーションを無効化。', aliases: ['java -disableassertions'] },
  { term: 'java -server', description: 'サーバーVMを使用。' },
  { term: 'java -client', description: 'クライアントVMを使用。' },
  { term: 'java --add-modules', description: 'モジュールを追加。' },
  { term: 'java --add-opens', description: 'パッケージを開放（リフレクション用）。' },
  { term: 'java --add-exports', description: 'パッケージをエクスポート。' },
  { term: 'java --add-reads', description: 'モジュールの読み取りを追加。' },
  { term: 'java --module', description: 'メインモジュールを指定。', aliases: ['java -m'] },
  { term: 'java --module-path', description: 'モジュールパスを指定。', aliases: ['java -p'] },
  { term: 'java -agentlib', description: 'ネイティブエージェントをロード。' },
  { term: 'java -javaagent', description: 'Javaエージェントをロード。' },
  { term: 'java --enable-preview', description: 'プレビュー機能を有効化。' },
  { term: 'java --source', description: 'ソースファイルを直接実行（Java 11+）。' },
  { term: 'java -XshowSettings', description: 'VM設定を表示。' },
  { term: 'java -XshowSettings:all', description: '全ての設定を表示。' },

  // === javac ===
  { term: 'javac', description: 'Javaソースをコンパイルするコンパイラ。' },
  { term: 'javac -d', description: '出力ディレクトリを指定。' },
  { term: 'javac -cp', description: 'クラスパスを指定。', aliases: ['javac -classpath', 'javac --class-path'] },
  { term: 'javac -sourcepath', description: 'ソースパスを指定。' },
  { term: 'javac -source', description: 'ソースバージョンを指定。', aliases: ['javac --release'] },
  { term: 'javac -target', description: 'ターゲットバージョンを指定。' },
  { term: 'javac --release', description: 'リリースバージョンを指定。' },
  { term: 'javac -encoding', description: 'ソースファイルのエンコーディングを指定。' },
  { term: 'javac -g', description: 'デバッグ情報を生成。' },
  { term: 'javac -g:none', description: 'デバッグ情報を生成しない。' },
  { term: 'javac -O', description: '最適化を有効化（非推奨）。' },
  { term: 'javac -nowarn', description: '警告を抑制。' },
  { term: 'javac -deprecation', description: '非推奨の使用を警告。' },
  { term: 'javac -Xlint', description: '追加の警告を有効化。' },
  { term: 'javac -Xlint:unchecked', description: '未チェック警告を表示。' },
  { term: 'javac -Xlint:deprecation', description: '非推奨警告を表示。' },
  { term: 'javac -Xlint:all', description: '全ての警告を表示。' },
  { term: 'javac -Werror', description: '警告をエラーとして扱う。' },
  { term: 'javac -verbose', description: '詳細な出力。' },
  { term: 'javac -version', description: 'バージョンを表示。' },
  { term: 'javac -help', description: 'ヘルプを表示。' },
  { term: 'javac -parameters', description: 'パラメータ名をクラスファイルに保持。' },
  { term: 'javac -proc:none', description: 'アノテーション処理を無効化。' },
  { term: 'javac -processor', description: 'アノテーションプロセッサを指定。' },
  { term: 'javac --module', description: 'コンパイルするモジュールを指定。', aliases: ['javac -m'] },
  { term: 'javac --module-path', description: 'モジュールパスを指定。', aliases: ['javac -p'] },
  { term: 'javac --module-source-path', description: 'モジュールソースパスを指定。' },
  { term: 'javac --enable-preview', description: 'プレビュー機能を有効化。' },
  { term: 'javac @argfile', description: '引数ファイルを読み込み。' },

  // === jar ===
  { term: 'jar', description: 'JARファイルを作成・操作するツール。' },
  { term: 'jar -c', description: 'JARファイルを作成。', aliases: ['jar --create'] },
  { term: 'jar -t', description: 'JARファイルの内容を一覧表示。', aliases: ['jar --list'] },
  { term: 'jar -x', description: 'JARファイルを展開。', aliases: ['jar --extract'] },
  { term: 'jar -u', description: 'JARファイルを更新。', aliases: ['jar --update'] },
  { term: 'jar -f', description: 'JARファイル名を指定。', aliases: ['jar --file'] },
  { term: 'jar -v', description: '詳細な出力。', aliases: ['jar --verbose'] },
  { term: 'jar -m', description: 'マニフェストファイルを指定。', aliases: ['jar --manifest'] },
  { term: 'jar -M', description: 'マニフェストを生成しない。', aliases: ['jar --no-manifest'] },
  { term: 'jar -e', description: 'エントリーポイント（Main-Class）を指定。', aliases: ['jar --main-class'] },
  { term: 'jar -C', description: 'ディレクトリを変更してファイルを追加。' },
  { term: 'jar -0', description: '圧縮しない（store only）。', aliases: ['jar --no-compress'] },
  { term: 'jar -i', description: 'インデックスを生成。', aliases: ['jar --generate-index'] },
  { term: 'jar --describe-module', description: 'モジュール情報を表示。', aliases: ['jar -d'] },
  { term: 'jar --module-version', description: 'モジュールバージョンを指定。' },
  { term: 'MANIFEST.MF', description: 'JARのマニフェストファイル。' },
  { term: 'Main-Class', description: 'マニフェストのエントリーポイント指定。' },
  { term: 'Class-Path', description: 'マニフェストのクラスパス指定。' },

  // === javadoc ===
  { term: 'javadoc', description: 'JavaドキュメントをHTML生成するツール。' },
  { term: 'javadoc -d', description: '出力ディレクトリを指定。' },
  { term: 'javadoc -sourcepath', description: 'ソースパスを指定。' },
  { term: 'javadoc -subpackages', description: 'サブパッケージも含める。' },
  { term: 'javadoc -private', description: 'privateメンバも含める。' },
  { term: 'javadoc -protected', description: 'protectedメンバまで含める。' },
  { term: 'javadoc -public', description: 'publicメンバのみ。' },
  { term: 'javadoc -author', description: '@authorタグを含める。' },
  { term: 'javadoc -version', description: '@versionタグを含める。' },
  { term: 'javadoc -encoding', description: 'ソースのエンコーディングを指定。' },
  { term: 'javadoc -charset', description: '出力の文字セットを指定。' },
  { term: 'javadoc -docencoding', description: '出力のエンコーディングを指定。' },
  { term: 'javadoc -link', description: '外部APIドキュメントへのリンク。' },
  { term: 'javadoc -linkoffline', description: 'オフラインリンク。' },
  { term: 'javadoc -tag', description: 'カスタムタグを定義。' },
  { term: 'javadoc -doclet', description: 'カスタムDocletを指定。' },

  // === jshell ===
  { term: 'jshell', description: 'Java REPL（対話型シェル）。' },
  { term: '/help', description: 'jshellヘルプを表示。' },
  { term: '/exit', description: 'jshellを終了。' },
  { term: '/list', description: '入力したスニペットを一覧表示。' },
  { term: '/vars', description: '変数を一覧表示。' },
  { term: '/methods', description: 'メソッドを一覧表示。' },
  { term: '/types', description: '型を一覧表示。' },
  { term: '/imports', description: 'インポートを一覧表示。' },
  { term: '/edit', description: 'スニペットを編集。' },
  { term: '/drop', description: 'スニペットを削除。' },
  { term: '/save', description: 'スニペットをファイルに保存。' },
  { term: '/open', description: 'ファイルからスニペットを読み込み。' },
  { term: '/reset', description: 'jshellをリセット。' },
  { term: '/reload', description: 'スニペットを再読み込み。' },
  { term: '/set', description: 'jshell設定を変更。' },
  { term: '/env', description: '環境設定を表示・変更。' },

  // === jlink ===
  { term: 'jlink', description: 'カスタムランタイムイメージを作成するツール。' },
  { term: 'jlink --module-path', description: 'モジュールパスを指定。', aliases: ['jlink -p'] },
  { term: 'jlink --add-modules', description: 'モジュールを追加。' },
  { term: 'jlink --output', description: '出力ディレクトリを指定。' },
  { term: 'jlink --compress', description: '圧縮レベルを指定。' },
  { term: 'jlink --strip-debug', description: 'デバッグ情報を削除。' },
  { term: 'jlink --no-header-files', description: 'ヘッダーファイルを除外。' },
  { term: 'jlink --no-man-pages', description: 'manページを除外。' },
  { term: 'jlink --launcher', description: 'ランチャースクリプトを作成。' },

  // === jpackage ===
  { term: 'jpackage', description: 'ネイティブインストーラを作成するツール（Java 14+）。' },
  { term: 'jpackage --type', description: 'パッケージタイプを指定（exe/msi/dmg/pkg/deb/rpm）。', aliases: ['jpackage -t'] },
  { term: 'jpackage --input', description: '入力ディレクトリを指定。', aliases: ['jpackage -i'] },
  { term: 'jpackage --dest', description: '出力ディレクトリを指定。', aliases: ['jpackage -d'] },
  { term: 'jpackage --name', description: 'アプリケーション名を指定。', aliases: ['jpackage -n'] },
  { term: 'jpackage --main-jar', description: 'メインJARを指定。' },
  { term: 'jpackage --main-class', description: 'メインクラスを指定。' },
  { term: 'jpackage --module', description: 'メインモジュールを指定。', aliases: ['jpackage -m'] },
  { term: 'jpackage --runtime-image', description: 'ランタイムイメージを指定。' },
  { term: 'jpackage --icon', description: 'アイコンを指定。' },
  { term: 'jpackage --app-version', description: 'バージョンを指定。' },
  { term: 'jpackage --vendor', description: 'ベンダー名を指定。' },

  // === デバッグ・監視ツール ===
  { term: 'jdb', description: 'Javaデバッガ。' },
  { term: 'jdb -attach', description: '実行中のJVMにアタッチ。' },
  { term: 'jdb -connect', description: '接続方法を指定。' },
  { term: 'jdb -sourcepath', description: 'ソースパスを指定。' },

  { term: 'jconsole', description: 'JVMモニタリングツール（GUI）。' },
  { term: 'jvisualvm', description: 'JVMビジュアルツール（GUI）。', aliases: ['visualvm'] },

  { term: 'jps', description: 'Javaプロセスを一覧表示。' },
  { term: 'jps -l', description: 'メインクラスのフルネームを表示。' },
  { term: 'jps -v', description: 'JVM引数を表示。' },
  { term: 'jps -m', description: 'main()への引数を表示。' },
  { term: 'jps -q', description: 'PIDのみ表示。' },

  { term: 'jstat', description: 'JVM統計を表示。' },
  { term: 'jstat -gc', description: 'GC統計を表示。' },
  { term: 'jstat -gcutil', description: 'GC使用率を表示。' },
  { term: 'jstat -gccapacity', description: 'GC容量を表示。' },
  { term: 'jstat -gccause', description: 'GC発生原因を表示。' },
  { term: 'jstat -class', description: 'クラスローダー統計を表示。' },
  { term: 'jstat -compiler', description: 'JITコンパイラ統計を表示。' },

  { term: 'jstack', description: 'スレッドダンプを取得。' },
  { term: 'jstack -l', description: 'ロック情報を含めて出力。' },
  { term: 'jstack -F', description: '強制的にダンプを取得。' },
  { term: 'jstack -m', description: 'ネイティブフレームも表示。' },

  { term: 'jmap', description: 'ヒープマップを取得。' },
  { term: 'jmap -heap', description: 'ヒープ情報を表示。' },
  { term: 'jmap -histo', description: 'ヒストグラムを表示。' },
  { term: 'jmap -histo:live', description: 'ライブオブジェクトのみのヒストグラム。' },
  { term: 'jmap -dump', description: 'ヒープダンプを取得。' },
  { term: 'jmap -dump:format=b,file=heap.hprof', description: 'バイナリ形式でヒープダンプを出力。' },
  { term: 'jmap -F', description: '強制的にダンプを取得。' },

  { term: 'jhat', description: 'ヒープダンプを分析（非推奨、JDK 9で削除）。' },

  { term: 'jinfo', description: 'JVM設定情報を表示・変更。' },
  { term: 'jinfo -flags', description: 'JVMフラグを表示。' },
  { term: 'jinfo -sysprops', description: 'システムプロパティを表示。' },
  { term: 'jinfo -flag', description: '特定のフラグを表示・変更。' },

  { term: 'jcmd', description: 'JVMに診断コマンドを送信。' },
  { term: 'jcmd <pid> help', description: '利用可能なコマンドを表示。' },
  { term: 'jcmd <pid> VM.flags', description: 'VMフラグを表示。' },
  { term: 'jcmd <pid> VM.system_properties', description: 'システムプロパティを表示。' },
  { term: 'jcmd <pid> VM.version', description: 'VMバージョンを表示。' },
  { term: 'jcmd <pid> VM.uptime', description: '稼働時間を表示。' },
  { term: 'jcmd <pid> Thread.print', description: 'スレッドダンプを取得。' },
  { term: 'jcmd <pid> GC.heap_dump', description: 'ヒープダンプを取得。' },
  { term: 'jcmd <pid> GC.heap_info', description: 'ヒープ情報を表示。' },
  { term: 'jcmd <pid> GC.run', description: 'GCを実行。' },
  { term: 'jcmd <pid> GC.class_histogram', description: 'クラスヒストグラムを表示。' },
  { term: 'jcmd <pid> JFR.start', description: 'Flight Recorderを開始。' },
  { term: 'jcmd <pid> JFR.stop', description: 'Flight Recorderを停止。' },
  { term: 'jcmd <pid> JFR.dump', description: 'Flight Recorderデータをダンプ。' },

  { term: 'jfr', description: 'Java Flight Recorderデータを操作（Java 13+）。' },
  { term: 'jfr print', description: 'JFRファイルを表示。' },
  { term: 'jfr summary', description: 'JFRサマリーを表示。' },
  { term: 'jfr metadata', description: 'JFRメタデータを表示。' },

  // === その他のツール ===
  { term: 'keytool', description: '鍵と証明書を管理するツール。' },
  { term: 'keytool -genkeypair', description: '鍵ペアを生成。', aliases: ['keytool -genkey'] },
  { term: 'keytool -list', description: 'キーストアの内容を一覧表示。' },
  { term: 'keytool -import', description: '証明書をインポート。', aliases: ['keytool -importcert'] },
  { term: 'keytool -export', description: '証明書をエクスポート。', aliases: ['keytool -exportcert'] },
  { term: 'keytool -delete', description: 'エントリを削除。' },
  { term: 'keytool -storepasswd', description: 'キーストアのパスワードを変更。' },
  { term: 'keytool -keypasswd', description: '鍵のパスワードを変更。' },
  { term: 'keytool -alias', description: 'エイリアスを指定。' },
  { term: 'keytool -keystore', description: 'キーストアを指定。' },
  { term: 'keytool -storetype', description: 'キーストアタイプを指定（JKS/PKCS12）。' },
  { term: 'keytool -v', description: '詳細出力。' },

  { term: 'jarsigner', description: 'JARファイルに署名するツール。' },
  { term: 'jarsigner -verify', description: '署名を検証。' },
  { term: 'jarsigner -keystore', description: 'キーストアを指定。' },
  { term: 'jarsigner -storepass', description: 'キーストアのパスワード。' },
  { term: 'jarsigner -keypass', description: '鍵のパスワード。' },
  { term: 'jarsigner -tsa', description: 'タイムスタンプサーバーを指定。' },

  { term: 'serialver', description: 'シリアルバージョンUIDを取得。' },

  { term: 'native2ascii', description: 'ネイティブ文字をASCIIに変換（非推奨）。' },

  { term: 'rmic', description: 'RMIスタブを生成（非推奨）。' },
  { term: 'rmiregistry', description: 'RMIレジストリを起動。' },
  { term: 'rmid', description: 'RMI活性化デーモンを起動。' },

  { term: 'jhsdb', description: 'Serviceability Agentベースのデバッグツール。' },
  { term: 'jhsdb hsdb', description: 'HotSpotデバッガ（GUI）。' },
  { term: 'jhsdb clhsdb', description: 'コマンドラインHotSpotデバッガ。' },
  { term: 'jhsdb jstack', description: 'jstackを実行。' },
  { term: 'jhsdb jmap', description: 'jmapを実行。' },
  { term: 'jhsdb jinfo', description: 'jinfoを実行。' },

  { term: 'jdeps', description: '依存関係を分析するツール。' },
  { term: 'jdeps -s', description: 'サマリーを表示。', aliases: ['jdeps --summary'] },
  { term: 'jdeps -v', description: '詳細を表示。', aliases: ['jdeps --verbose'] },
  { term: 'jdeps --jdk-internals', description: 'JDK内部APIの使用を検出。' },
  { term: 'jdeps --multi-release', description: 'マルチリリースJARのバージョンを指定。' },
  { term: 'jdeps --generate-module-info', description: 'module-info.javaを生成。' },
  { term: 'jdeps --generate-open-module', description: 'オープンモジュールを生成。' },
  { term: 'jdeps --list-deps', description: '依存モジュールを一覧表示。' },
  { term: 'jdeps --list-reduced-deps', description: '縮小された依存モジュールを表示。' },

  { term: 'jdeprscan', description: '非推奨APIの使用を検出するツール。' },
  { term: 'jdeprscan --list', description: '非推奨APIを一覧表示。' },
  { term: 'jdeprscan --release', description: 'リリースバージョンを指定。' },

  { term: 'jmod', description: 'JMODファイルを作成・操作するツール。' },
  { term: 'jmod create', description: 'JMODファイルを作成。' },
  { term: 'jmod extract', description: 'JMODファイルを展開。' },
  { term: 'jmod list', description: 'JMODの内容を一覧表示。' },
  { term: 'jmod describe', description: 'JMODの説明を表示。' },
  { term: 'jmod hash', description: 'JMODのハッシュを記録。' },

  { term: 'jrunscript', description: 'スクリプトシェル（非推奨）。' },
  { term: 'jjs', description: 'NashornJavaScriptエンジン（削除）。' },

  // === 概念・用語 ===
  { term: 'JVM', description: 'Java Virtual Machine。Javaバイトコードを実行する仮想マシン。' },
  { term: 'JRE', description: 'Java Runtime Environment。Java実行環境。' },
  { term: 'JDK', description: 'Java Development Kit。Java開発キット。' },
  { term: 'GC', description: 'Garbage Collection。自動メモリ管理。' },
  { term: 'JIT', description: 'Just-In-Time コンパイラ。実行時にネイティブコードに変換。' },
  { term: 'AOT', description: 'Ahead-Of-Time コンパイル。事前にネイティブコードに変換。' },
  { term: 'JPMS', description: 'Java Platform Module System。モジュールシステム（Java 9+）。' },
  { term: 'classpath', description: 'クラスファイルを検索するパス。' },
  { term: 'modulepath', description: 'モジュールを検索するパス。' },
  { term: 'JAVA_HOME', description: 'JDKインストールディレクトリを指す環境変数。' },
  { term: 'CLASSPATH', description: 'クラスパスを指定する環境変数。' },
  { term: '.class', description: 'コンパイル済みJavaバイトコードファイル。' },
  { term: '.jar', description: 'Java ARchive。複数のクラスをまとめたファイル。' },
  { term: '.jmod', description: 'Javaモジュールファイル。' },
  { term: '.war', description: 'Web Application Archive。Webアプリのパッケージ。' },
  { term: '.ear', description: 'Enterprise Application Archive。エンタープライズアプリのパッケージ。' },
  { term: 'module-info.java', description: 'モジュール定義ファイル。' },
  { term: 'heap', description: 'ヒープ領域。オブジェクトが格納されるメモリ。' },
  { term: 'stack', description: 'スタック領域。メソッド呼び出し情報を格納。' },
  { term: 'metaspace', description: 'Metaspace。クラスメタデータを格納（Java 8+）。' },
  { term: 'permgen', description: 'Permanent Generation。クラスメタデータ領域（Java 7以前）。' },
  { term: 'hprof', description: 'ヒープダンプのファイル形式。' },
  { term: 'JFR', description: 'Java Flight Recorder。低オーバーヘッドの診断ツール。' },
];
