/**
 * Maven用語集
 * Apache Mavenコマンド・ライフサイクル・プラグインの説明
 */

import { CliGlossaryEntry } from './gitGlossary';

export const MAVEN_GLOSSARY: ReadonlyArray<CliGlossaryEntry> = [
  // === 基本コマンド ===
  { term: 'mvn', description: 'Apache Maven。Javaプロジェクトのビルド・依存関係管理ツール。' },
  { term: 'mvn --version', description: 'Mavenのバージョンを表示。', aliases: ['mvn -v'] },
  { term: 'mvn --help', description: 'ヘルプを表示。', aliases: ['mvn -h'] },

  // === ライフサイクルフェーズ ===
  { term: 'mvn clean', description: 'targetディレクトリを削除してビルド成果物をクリーン。' },
  { term: 'mvn validate', description: 'プロジェクト情報が正しいか検証。' },
  { term: 'mvn compile', description: 'ソースコードをコンパイル。' },
  { term: 'mvn test-compile', description: 'テストソースをコンパイル。' },
  { term: 'mvn test', description: 'ユニットテストを実行。' },
  { term: 'mvn package', description: 'コンパイル済みコードをJAR/WAR等にパッケージング。' },
  { term: 'mvn verify', description: '統合テストを実行して結果を検証。' },
  { term: 'mvn install', description: 'パッケージをローカルリポジトリにインストール。' },
  { term: 'mvn deploy', description: 'パッケージをリモートリポジトリにデプロイ。' },
  { term: 'mvn site', description: 'プロジェクトサイト（ドキュメント）を生成。' },
  { term: 'mvn site-deploy', description: 'サイトをデプロイ。' },

  // === よく使うコマンド組み合わせ ===
  { term: 'mvn clean install', description: 'クリーンしてビルド・インストール。' },
  { term: 'mvn clean package', description: 'クリーンしてパッケージング。' },
  { term: 'mvn clean test', description: 'クリーンしてテスト実行。' },
  { term: 'mvn clean deploy', description: 'クリーンしてデプロイ。' },
  { term: 'mvn clean verify', description: 'クリーンして検証。' },

  // === オプション ===
  { term: 'mvn -DskipTests', description: 'テストの実行をスキップ（コンパイルはする）。' },
  { term: 'mvn -Dmaven.test.skip=true', description: 'テストのコンパイル・実行をスキップ。' },
  { term: 'mvn -Dmaven.test.failure.ignore=true', description: 'テスト失敗を無視して続行。' },
  { term: 'mvn -DskipITs', description: '統合テストをスキップ。' },
  { term: 'mvn -U', description: 'スナップショットを強制更新。', aliases: ['mvn --update-snapshots'] },
  { term: 'mvn -o', description: 'オフラインモードで実行。', aliases: ['mvn --offline'] },
  { term: 'mvn -X', description: 'デバッグ出力を有効化。', aliases: ['mvn --debug'] },
  { term: 'mvn -e', description: 'エラーのスタックトレースを表示。', aliases: ['mvn --errors'] },
  { term: 'mvn -q', description: '静かモード（エラーのみ表示）。', aliases: ['mvn --quiet'] },
  { term: 'mvn -B', description: 'バッチモード（対話なし）。', aliases: ['mvn --batch-mode'] },
  { term: 'mvn -N', description: '子モジュールを処理しない。', aliases: ['mvn --non-recursive'] },
  { term: 'mvn -T', description: '並列ビルドのスレッド数を指定。', aliases: ['mvn --threads'] },
  { term: 'mvn -T 1C', description: 'CPUコア数に応じた並列ビルド。' },
  { term: 'mvn -T 4', description: '4スレッドで並列ビルド。' },
  { term: 'mvn -P', description: 'プロファイルを有効化。', aliases: ['mvn --activate-profiles'] },
  { term: 'mvn -P dev', description: 'devプロファイルを有効化。' },
  { term: 'mvn -P !default', description: 'defaultプロファイルを無効化。' },
  { term: 'mvn -f', description: 'pomファイルを指定。', aliases: ['mvn --file'] },
  { term: 'mvn -pl', description: '特定モジュールのみビルド。', aliases: ['mvn --projects'] },
  { term: 'mvn -am', description: '依存モジュールも一緒にビルド。', aliases: ['mvn --also-make'] },
  { term: 'mvn -amd', description: '依存されているモジュールも一緒にビルド。', aliases: ['mvn --also-make-dependents'] },
  { term: 'mvn -rf', description: '指定モジュールから再開。', aliases: ['mvn --resume-from'] },
  { term: 'mvn -s', description: '設定ファイルを指定。', aliases: ['mvn --settings'] },
  { term: 'mvn -gs', description: 'グローバル設定ファイルを指定。', aliases: ['mvn --global-settings'] },
  { term: 'mvn -D', description: 'システムプロパティを設定。', aliases: ['mvn --define'] },
  { term: 'mvn -l', description: 'ログファイルを指定。', aliases: ['mvn --log-file'] },
  { term: 'mvn -nsu', description: 'スナップショット更新をスキップ。', aliases: ['mvn --no-snapshot-updates'] },
  { term: 'mvn -fae', description: '失敗しても最後までビルド続行。', aliases: ['mvn --fail-at-end'] },
  { term: 'mvn -ff', description: '最初の失敗で停止。', aliases: ['mvn --fail-fast'] },
  { term: 'mvn -fn', description: '失敗しても停止しない。', aliases: ['mvn --fail-never'] },
  { term: 'mvn -C', description: 'pomの整合性を厳格にチェック。', aliases: ['mvn --strict-checksums'] },
  { term: 'mvn -c', description: 'pomのチェックサムを緩くチェック。', aliases: ['mvn --lax-checksums'] },

  // === プラグインゴール ===
  { term: 'mvn archetype:generate', description: 'プロジェクトの雛形を生成。' },
  { term: 'mvn archetype:create-from-project', description: '既存プロジェクトからアーキタイプを作成。' },

  { term: 'mvn compiler:compile', description: 'メインソースをコンパイル。' },
  { term: 'mvn compiler:testCompile', description: 'テストソースをコンパイル。' },

  { term: 'mvn surefire:test', description: 'Surefireでユニットテストを実行。' },
  { term: 'mvn failsafe:integration-test', description: 'Failsafeで統合テストを実行。' },
  { term: 'mvn failsafe:verify', description: '統合テスト結果を検証。' },

  { term: 'mvn jar:jar', description: 'JARファイルを作成。' },
  { term: 'mvn war:war', description: 'WARファイルを作成。' },
  { term: 'mvn war:exploded', description: '展開済みWARを作成。' },
  { term: 'mvn ear:ear', description: 'EARファイルを作成。' },

  { term: 'mvn shade:shade', description: 'uber-JAR（fat JAR）を作成。' },
  { term: 'mvn assembly:single', description: 'カスタムアセンブリを作成。' },

  { term: 'mvn dependency:tree', description: '依存関係ツリーを表示。' },
  { term: 'mvn dependency:list', description: '依存関係一覧を表示。' },
  { term: 'mvn dependency:analyze', description: '依存関係を分析。' },
  { term: 'mvn dependency:resolve', description: '依存関係を解決。' },
  { term: 'mvn dependency:copy-dependencies', description: '依存JARをコピー。' },
  { term: 'mvn dependency:go-offline', description: 'オフライン用に依存をダウンロード。' },
  { term: 'mvn dependency:purge-local-repository', description: 'ローカルリポジトリから依存を削除。' },
  { term: 'mvn dependency:sources', description: 'ソースJARをダウンロード。' },

  { term: 'mvn versions:display-dependency-updates', description: '更新可能な依存を表示。' },
  { term: 'mvn versions:display-plugin-updates', description: '更新可能なプラグインを表示。' },
  { term: 'mvn versions:display-property-updates', description: '更新可能なプロパティを表示。' },
  { term: 'mvn versions:use-latest-releases', description: '依存を最新リリースに更新。' },
  { term: 'mvn versions:use-latest-versions', description: '依存を最新バージョンに更新。' },
  { term: 'mvn versions:set', description: 'プロジェクトバージョンを設定。' },
  { term: 'mvn versions:set -DnewVersion=', description: '新しいバージョンを指定。' },
  { term: 'mvn versions:commit', description: 'バージョン変更を確定。' },
  { term: 'mvn versions:revert', description: 'バージョン変更を取り消し。' },

  { term: 'mvn release:prepare', description: 'リリース準備（タグ作成等）。' },
  { term: 'mvn release:perform', description: 'リリース実行（デプロイ）。' },
  { term: 'mvn release:rollback', description: 'リリース準備をロールバック。' },
  { term: 'mvn release:clean', description: 'リリース作業ファイルを削除。' },

  { term: 'mvn exec:java', description: 'Javaアプリケーションを実行。' },
  { term: 'mvn exec:exec', description: '外部コマンドを実行。' },
  { term: 'mvn exec:java -Dexec.mainClass=', description: 'メインクラスを指定して実行。' },

  { term: 'mvn spring-boot:run', description: 'Spring Bootアプリケーションを実行。' },
  { term: 'mvn spring-boot:repackage', description: 'Spring Boot実行可能JARを作成。' },
  { term: 'mvn spring-boot:build-image', description: 'Dockerイメージを作成。' },

  { term: 'mvn jetty:run', description: 'Jettyサーバーでアプリを実行。' },
  { term: 'mvn tomcat7:run', description: 'Tomcatでアプリを実行。' },

  { term: 'mvn javadoc:javadoc', description: 'Javadocを生成。' },
  { term: 'mvn javadoc:jar', description: 'Javadoc JARを作成。' },
  { term: 'mvn source:jar', description: 'ソースJARを作成。' },
  { term: 'mvn source:jar-no-fork', description: 'ソースJARを作成（forkなし）。' },

  { term: 'mvn checkstyle:check', description: 'Checkstyleでコードスタイルをチェック。' },
  { term: 'mvn pmd:pmd', description: 'PMDで静的解析。' },
  { term: 'mvn pmd:cpd', description: 'PMDでコード重複を検出。' },
  { term: 'mvn spotbugs:check', description: 'SpotBugsでバグを検出。' },
  { term: 'mvn findbugs:findbugs', description: 'FindBugsでバグを検出（非推奨）。' },

  { term: 'mvn jacoco:prepare-agent', description: 'JaCoCoエージェントを準備。' },
  { term: 'mvn jacoco:report', description: 'JaCoCoカバレッジレポートを生成。' },
  { term: 'mvn jacoco:check', description: 'カバレッジ閾値をチェック。' },

  { term: 'mvn sonar:sonar', description: 'SonarQubeに分析結果を送信。' },

  { term: 'mvn help:effective-pom', description: '有効なPOMを表示。' },
  { term: 'mvn help:effective-settings', description: '有効な設定を表示。' },
  { term: 'mvn help:describe', description: 'プラグイン情報を表示。' },
  { term: 'mvn help:describe -Dplugin=', description: '指定プラグインの情報を表示。' },
  { term: 'mvn help:describe -Dcmd=', description: '指定ゴールの情報を表示。' },
  { term: 'mvn help:active-profiles', description: 'アクティブなプロファイルを表示。' },
  { term: 'mvn help:all-profiles', description: '全プロファイルを表示。' },
  { term: 'mvn help:system', description: 'システムプロパティと環境変数を表示。' },
  { term: 'mvn help:evaluate', description: '式を評価。' },
  { term: 'mvn help:evaluate -Dexpression=', description: '指定式を評価。' },

  { term: 'mvn enforcer:enforce', description: 'ビルド条件を強制。' },

  { term: 'mvn wrapper:wrapper', description: 'Maven Wrapperを生成。' },
  { term: './mvnw', description: 'Maven Wrapper（Unix）。' },
  { term: 'mvnw.cmd', description: 'Maven Wrapper（Windows）。' },

  // === pom.xml要素 ===
  { term: 'pom.xml', description: 'Project Object Model。Mavenプロジェクト設定ファイル。' },
  { term: 'groupId', description: 'プロジェクトのグループ識別子。' },
  { term: 'artifactId', description: 'プロジェクトのアーティファクト識別子。' },
  { term: 'version', description: 'プロジェクトのバージョン。' },
  { term: 'packaging', description: 'パッケージング形式（jar/war/pom/ear等）。' },
  { term: 'name', description: 'プロジェクト名。' },
  { term: 'description', description: 'プロジェクトの説明。' },
  { term: 'url', description: 'プロジェクトのURL。' },
  { term: 'parent', description: '親POMの指定。' },
  { term: 'modules', description: 'サブモジュールの定義。' },
  { term: 'properties', description: 'プロパティの定義。' },
  { term: 'dependencies', description: '依存関係の定義。' },
  { term: 'dependency', description: '個々の依存関係。' },
  { term: 'dependencyManagement', description: '依存関係バージョンの一元管理。' },
  { term: 'scope', description: '依存のスコープ（compile/provided/runtime/test/system/import）。' },
  { term: 'scope compile', description: 'コンパイル・実行時に必要。デフォルト。' },
  { term: 'scope provided', description: 'コンパイル時に必要だが実行時は提供される。' },
  { term: 'scope runtime', description: '実行時のみ必要。' },
  { term: 'scope test', description: 'テスト時のみ必要。' },
  { term: 'scope system', description: 'システムパスから参照。非推奨。' },
  { term: 'scope import', description: 'dependencyManagementをインポート。' },
  { term: 'optional', description: 'オプショナル依存。推移的依存に含まれない。' },
  { term: 'exclusions', description: '推移的依存の除外。' },
  { term: 'exclusion', description: '個々の除外設定。' },
  { term: 'type', description: '依存のタイプ（jar/pom/war等）。' },
  { term: 'classifier', description: '依存の分類子（sources/javadoc等）。' },
  { term: 'build', description: 'ビルド設定。' },
  { term: 'plugins', description: 'プラグインの定義。' },
  { term: 'plugin', description: '個々のプラグイン設定。' },
  { term: 'pluginManagement', description: 'プラグイン設定の一元管理。' },
  { term: 'executions', description: 'プラグイン実行の定義。' },
  { term: 'execution', description: '個々の実行設定。' },
  { term: 'goals', description: '実行するゴール。' },
  { term: 'phase', description: '実行するフェーズ。' },
  { term: 'configuration', description: 'プラグイン設定。' },
  { term: 'resources', description: 'リソースディレクトリの設定。' },
  { term: 'testResources', description: 'テストリソースディレクトリの設定。' },
  { term: 'sourceDirectory', description: 'ソースディレクトリ。' },
  { term: 'testSourceDirectory', description: 'テストソースディレクトリ。' },
  { term: 'outputDirectory', description: '出力ディレクトリ。' },
  { term: 'testOutputDirectory', description: 'テスト出力ディレクトリ。' },
  { term: 'finalName', description: '最終成果物の名前。' },
  { term: 'filters', description: 'フィルタファイル。' },
  { term: 'profiles', description: 'プロファイルの定義。' },
  { term: 'profile', description: '個々のプロファイル。' },
  { term: 'activation', description: 'プロファイルの有効化条件。' },
  { term: 'activeByDefault', description: 'デフォルトで有効化。' },
  { term: 'repositories', description: 'リポジトリの定義。' },
  { term: 'repository', description: '個々のリポジトリ。' },
  { term: 'pluginRepositories', description: 'プラグインリポジトリの定義。' },
  { term: 'distributionManagement', description: 'デプロイ先の設定。' },
  { term: 'snapshotRepository', description: 'スナップショットのデプロイ先。' },
  { term: 'scm', description: 'ソース管理の設定。' },
  { term: 'issueManagement', description: '課題管理の設定。' },
  { term: 'ciManagement', description: 'CI管理の設定。' },
  { term: 'developers', description: '開発者情報。' },
  { term: 'contributors', description: 'コントリビューター情報。' },
  { term: 'licenses', description: 'ライセンス情報。' },
  { term: 'organization', description: '組織情報。' },
  { term: 'reporting', description: 'レポート設定。' },

  // === 設定ファイル ===
  { term: 'settings.xml', description: 'Maven設定ファイル。' },
  { term: '~/.m2/settings.xml', description: 'ユーザー設定ファイル。' },
  { term: '$MAVEN_HOME/conf/settings.xml', description: 'グローバル設定ファイル。' },
  { term: '~/.m2/repository', description: 'ローカルリポジトリ。' },
  { term: 'mirrors', description: 'ミラーリポジトリの設定。' },
  { term: 'servers', description: 'サーバー認証情報の設定。' },
  { term: 'proxies', description: 'プロキシの設定。' },
  { term: 'localRepository', description: 'ローカルリポジトリのパス。' },

  // === バージョン表記 ===
  { term: 'SNAPSHOT', description: '開発中の不安定なバージョン。' },
  { term: 'RELEASE', description: 'リリース版。' },
  { term: 'LATEST', description: '最新バージョン（非推奨）。' },
  { term: '[1.0,)', description: '1.0以上の任意のバージョン。' },
  { term: '[1.0,2.0)', description: '1.0以上2.0未満。' },
  { term: '[1.0,2.0]', description: '1.0以上2.0以下。' },
  { term: '(,1.0]', description: '1.0以下の任意のバージョン。' },

  // === 概念・用語 ===
  { term: 'artifact', description: 'ビルド成果物（JAR/WAR等）。' },
  { term: 'repository', description: 'アーティファクトを格納するリポジトリ。' },
  { term: 'local repository', description: 'ローカルのアーティファクトキャッシュ。' },
  { term: 'remote repository', description: 'リモートのアーティファクト保管庫。' },
  { term: 'central repository', description: 'Maven Central Repository。' },
  { term: 'transitive dependency', description: '推移的依存。依存の依存。' },
  { term: 'lifecycle', description: 'ビルドライフサイクル。' },
  { term: 'phase', description: 'ライフサイクルの各フェーズ。' },
  { term: 'goal', description: 'プラグインが実行する個々のタスク。' },
  { term: 'plugin', description: 'ビルド処理を実行する拡張機能。' },
  { term: 'archetype', description: 'プロジェクトの雛形。' },
  { term: 'multi-module', description: '複数モジュールプロジェクト。' },
  { term: 'BOM', description: 'Bill of Materials。依存バージョンの一元管理。' },
  { term: 'reactor', description: 'マルチモジュールビルドの実行エンジン。' },
  { term: 'effective POM', description: '継承・補完後の最終的なPOM。' },
  { term: 'super POM', description: '全POMの親となるデフォルトPOM。' },
  { term: 'M2_HOME', description: 'Mavenインストールディレクトリを指す環境変数。', aliases: ['MAVEN_HOME'] },
  { term: 'MAVEN_OPTS', description: 'Maven実行時のJVMオプションを指定する環境変数。' },
];
