/**
 * MySQL用語集
 * MySQL SQL・管理コマンドの説明
 */

import { CliGlossaryEntry } from './gitGlossary';

export const MYSQL_GLOSSARY: ReadonlyArray<CliGlossaryEntry> = [
  // === クライアント ===
  { term: 'mysql', description: 'MySQLコマンドラインクライアント。' },
  { term: 'mysql -u', description: 'ユーザー名を指定。', aliases: ['mysql --user'] },
  { term: 'mysql -p', description: 'パスワード入力を促す。', aliases: ['mysql --password'] },
  { term: 'mysql -h', description: 'ホストを指定。', aliases: ['mysql --host'] },
  { term: 'mysql -P', description: 'ポートを指定。', aliases: ['mysql --port'] },
  { term: 'mysql -D', description: 'データベースを指定。', aliases: ['mysql --database'] },
  { term: 'mysql -e', description: 'SQLを実行して終了。', aliases: ['mysql --execute'] },
  { term: 'mysql -N', description: '列名を表示しない。', aliases: ['mysql --skip-column-names'] },
  { term: 'mysql -B', description: 'バッチモード（タブ区切り）。', aliases: ['mysql --batch'] },
  { term: 'mysql --ssl-mode', description: 'SSL接続モードを指定。' },
  { term: 'mysql --default-character-set', description: '文字セットを指定。' },

  { term: 'mysqladmin', description: 'MySQL管理コマンド。' },
  { term: 'mysqladmin create', description: 'データベースを作成。' },
  { term: 'mysqladmin drop', description: 'データベースを削除。' },
  { term: 'mysqladmin status', description: 'サーバー状態を表示。' },
  { term: 'mysqladmin processlist', description: 'プロセス一覧を表示。' },
  { term: 'mysqladmin kill', description: 'プロセスを終了。' },
  { term: 'mysqladmin flush-privileges', description: '権限をリロード。' },
  { term: 'mysqladmin flush-tables', description: 'テーブルキャッシュをフラッシュ。' },
  { term: 'mysqladmin flush-logs', description: 'ログをフラッシュ。' },
  { term: 'mysqladmin shutdown', description: 'サーバーを停止。' },
  { term: 'mysqladmin variables', description: 'サーバー変数を表示。' },
  { term: 'mysqladmin extended-status', description: '拡張ステータスを表示。' },
  { term: 'mysqladmin ping', description: 'サーバーの応答を確認。' },
  { term: 'mysqladmin password', description: 'パスワードを変更。' },

  { term: 'mysqldump', description: 'データベースをダンプ（バックアップ）。' },
  { term: 'mysqldump -u', description: 'ユーザー名を指定。' },
  { term: 'mysqldump --all-databases', description: '全データベースをダンプ。', aliases: ['-A'] },
  { term: 'mysqldump --databases', description: '複数データベースをダンプ。', aliases: ['-B'] },
  { term: 'mysqldump --tables', description: 'テーブルを指定。' },
  { term: 'mysqldump --no-data', description: 'データなし（スキーマのみ）。', aliases: ['-d'] },
  { term: 'mysqldump --no-create-info', description: 'CREATE TABLEなし。', aliases: ['-t'] },
  { term: 'mysqldump --single-transaction', description: '一貫性のあるダンプ（InnoDB）。' },
  { term: 'mysqldump --lock-tables', description: 'テーブルをロック。' },
  { term: 'mysqldump --quick', description: 'メモリ使用を抑える。', aliases: ['-q'] },
  { term: 'mysqldump --routines', description: 'ストアドプロシージャを含める。', aliases: ['-R'] },
  { term: 'mysqldump --triggers', description: 'トリガーを含める。' },
  { term: 'mysqldump --events', description: 'イベントを含める。', aliases: ['-E'] },
  { term: 'mysqldump --add-drop-table', description: 'DROP TABLE文を追加。' },
  { term: 'mysqldump --add-drop-database', description: 'DROP DATABASE文を追加。' },
  { term: 'mysqldump --complete-insert', description: '完全なINSERT文を生成。' },
  { term: 'mysqldump --extended-insert', description: '複数行INSERTを生成。' },
  { term: 'mysqldump --where', description: 'WHERE条件を指定。', aliases: ['-w'] },
  { term: 'mysqldump --result-file', description: '出力ファイルを指定。' },
  { term: 'mysqldump --compress', description: '圧縮転送を使用。', aliases: ['-C'] },

  { term: 'mysqlimport', description: 'データをインポート。' },
  { term: 'mysqlbinlog', description: 'バイナリログを表示。' },
  { term: 'mysqlcheck', description: 'テーブルをチェック・修復。' },
  { term: 'mysqlcheck --repair', description: 'テーブルを修復。', aliases: ['-r'] },
  { term: 'mysqlcheck --analyze', description: 'テーブルを分析。', aliases: ['-a'] },
  { term: 'mysqlcheck --optimize', description: 'テーブルを最適化。', aliases: ['-o'] },
  { term: 'mysqlcheck --check', description: 'テーブルをチェック。', aliases: ['-c'] },
  { term: 'mysqlshow', description: 'データベース/テーブル情報を表示。' },
  { term: 'mysqlslap', description: '負荷テストツール。' },

  { term: 'mysql_secure_installation', description: 'セキュリティ初期設定スクリプト。' },
  { term: 'mysql_upgrade', description: 'アップグレード後のテーブル更新。' },
  { term: 'mysql_config_editor', description: '認証情報を安全に保存。' },

  // === SQL*Plus風コマンド ===
  { term: 'source', description: 'SQLファイルを実行。', aliases: ['\\.'] },
  { term: 'status', description: 'サーバー状態を表示。', aliases: ['\\s'] },
  { term: 'use', description: 'データベースを選択。', aliases: ['\\u'] },
  { term: 'quit', description: 'mysqlを終了。', aliases: ['exit', '\\q'] },
  { term: 'help', description: 'ヘルプを表示。', aliases: ['\\h', '\\?'] },
  { term: 'clear', description: '入力をクリア。', aliases: ['\\c'] },
  { term: 'delimiter', description: '区切り文字を変更。', aliases: ['\\d'] },
  { term: 'ego', description: '縦形式で表示。', aliases: ['\\G'] },
  { term: 'pager', description: 'ページャーを設定。', aliases: ['\\P'] },
  { term: 'nopager', description: 'ページャーを解除。', aliases: ['\\n'] },
  { term: 'tee', description: '出力をファイルに保存。', aliases: ['\\T'] },
  { term: 'notee', description: 'teeを解除。', aliases: ['\\t'] },
  { term: 'system', description: 'シェルコマンドを実行。', aliases: ['\\!'] },
  { term: 'warnings', description: '警告を表示。', aliases: ['\\W'] },
  { term: 'nowarning', description: '警告を非表示。', aliases: ['\\w'] },

  // === DDL ===
  { term: 'CREATE DATABASE', description: 'データベースを作成。', aliases: ['CREATE SCHEMA'] },
  { term: 'CREATE DATABASE IF NOT EXISTS', description: '存在しない場合のみ作成。' },
  { term: 'DROP DATABASE', description: 'データベースを削除。', aliases: ['DROP SCHEMA'] },
  { term: 'DROP DATABASE IF EXISTS', description: '存在する場合のみ削除。' },
  { term: 'ALTER DATABASE', description: 'データベースを変更。' },

  { term: 'CREATE TABLE', description: 'テーブルを作成。' },
  { term: 'CREATE TABLE IF NOT EXISTS', description: '存在しない場合のみ作成。' },
  { term: 'CREATE TABLE LIKE', description: '既存テーブルと同じ構造で作成。' },
  { term: 'CREATE TABLE AS SELECT', description: 'SELECTの結果からテーブルを作成。' },
  { term: 'CREATE TEMPORARY TABLE', description: '一時テーブルを作成。' },
  { term: 'ALTER TABLE', description: 'テーブルを変更。' },
  { term: 'ALTER TABLE ADD', description: '列を追加。' },
  { term: 'ALTER TABLE ADD COLUMN', description: '列を追加。' },
  { term: 'ALTER TABLE MODIFY', description: '列の定義を変更。' },
  { term: 'ALTER TABLE MODIFY COLUMN', description: '列の定義を変更。' },
  { term: 'ALTER TABLE CHANGE', description: '列名と定義を変更。' },
  { term: 'ALTER TABLE CHANGE COLUMN', description: '列名と定義を変更。' },
  { term: 'ALTER TABLE DROP', description: '列を削除。' },
  { term: 'ALTER TABLE DROP COLUMN', description: '列を削除。' },
  { term: 'ALTER TABLE RENAME', description: 'テーブル名を変更。' },
  { term: 'ALTER TABLE RENAME TO', description: 'テーブル名を変更。' },
  { term: 'ALTER TABLE RENAME COLUMN', description: '列名を変更。' },
  { term: 'ALTER TABLE ADD INDEX', description: 'インデックスを追加。' },
  { term: 'ALTER TABLE ADD PRIMARY KEY', description: '主キーを追加。' },
  { term: 'ALTER TABLE ADD FOREIGN KEY', description: '外部キーを追加。' },
  { term: 'ALTER TABLE ADD UNIQUE', description: '一意制約を追加。' },
  { term: 'ALTER TABLE DROP INDEX', description: 'インデックスを削除。' },
  { term: 'ALTER TABLE DROP PRIMARY KEY', description: '主キーを削除。' },
  { term: 'ALTER TABLE DROP FOREIGN KEY', description: '外部キーを削除。' },
  { term: 'ALTER TABLE ENGINE', description: 'ストレージエンジンを変更。' },
  { term: 'ALTER TABLE CONVERT TO CHARACTER SET', description: '文字セットを変換。' },
  { term: 'ALTER TABLE AUTO_INCREMENT', description: 'AUTO_INCREMENTの値を設定。' },
  { term: 'DROP TABLE', description: 'テーブルを削除。' },
  { term: 'DROP TABLE IF EXISTS', description: '存在する場合のみ削除。' },
  { term: 'TRUNCATE TABLE', description: '全行を高速削除。' },
  { term: 'RENAME TABLE', description: 'テーブル名を変更。' },

  { term: 'CREATE INDEX', description: 'インデックスを作成。' },
  { term: 'CREATE UNIQUE INDEX', description: '一意インデックスを作成。' },
  { term: 'CREATE FULLTEXT INDEX', description: '全文検索インデックスを作成。' },
  { term: 'CREATE SPATIAL INDEX', description: '空間インデックスを作成。' },
  { term: 'DROP INDEX', description: 'インデックスを削除。' },
  { term: 'SHOW INDEX', description: 'インデックス情報を表示。' },

  { term: 'CREATE VIEW', description: 'ビューを作成。' },
  { term: 'CREATE OR REPLACE VIEW', description: 'ビューを作成または置換。' },
  { term: 'ALTER VIEW', description: 'ビューを変更。' },
  { term: 'DROP VIEW', description: 'ビューを削除。' },

  { term: 'CREATE TRIGGER', description: 'トリガーを作成。' },
  { term: 'DROP TRIGGER', description: 'トリガーを削除。' },
  { term: 'SHOW TRIGGERS', description: 'トリガー一覧を表示。' },

  { term: 'CREATE PROCEDURE', description: 'ストアドプロシージャを作成。' },
  { term: 'CREATE FUNCTION', description: 'ストアドファンクションを作成。' },
  { term: 'DROP PROCEDURE', description: 'プロシージャを削除。' },
  { term: 'DROP FUNCTION', description: 'ファンクションを削除。' },
  { term: 'CALL', description: 'プロシージャを呼び出す。' },
  { term: 'SHOW PROCEDURE STATUS', description: 'プロシージャ一覧を表示。' },
  { term: 'SHOW FUNCTION STATUS', description: 'ファンクション一覧を表示。' },
  { term: 'SHOW CREATE PROCEDURE', description: 'プロシージャ定義を表示。' },
  { term: 'SHOW CREATE FUNCTION', description: 'ファンクション定義を表示。' },

  { term: 'CREATE EVENT', description: 'イベントを作成。' },
  { term: 'ALTER EVENT', description: 'イベントを変更。' },
  { term: 'DROP EVENT', description: 'イベントを削除。' },
  { term: 'SHOW EVENTS', description: 'イベント一覧を表示。' },

  // === DML ===
  { term: 'SELECT', description: 'データを取得。' },
  { term: 'SELECT DISTINCT', description: '重複を除いて取得。' },
  { term: 'SELECT INTO', description: '変数に代入。' },
  { term: 'SELECT FOR UPDATE', description: '行をロックして取得。' },
  { term: 'SELECT FOR SHARE', description: '共有ロックで取得。' },
  { term: 'INSERT INTO', description: 'データを挿入。' },
  { term: 'INSERT INTO ... VALUES', description: '値を指定して挿入。' },
  { term: 'INSERT INTO ... SELECT', description: 'SELECTの結果を挿入。' },
  { term: 'INSERT INTO ... SET', description: '列を指定して挿入。' },
  { term: 'INSERT IGNORE', description: '重複エラーを無視して挿入。' },
  { term: 'INSERT ... ON DUPLICATE KEY UPDATE', description: '重複時は更新。' },
  { term: 'REPLACE INTO', description: '存在すれば削除して挿入。' },
  { term: 'UPDATE', description: 'データを更新。' },
  { term: 'UPDATE ... SET', description: '列の値を更新。' },
  { term: 'UPDATE ... JOIN', description: '結合して更新。' },
  { term: 'DELETE', description: 'データを削除。' },
  { term: 'DELETE FROM', description: 'テーブルから削除。' },
  { term: 'DELETE ... JOIN', description: '結合して削除。' },
  { term: 'LOAD DATA INFILE', description: 'ファイルからデータをロード。' },
  { term: 'LOAD DATA LOCAL INFILE', description: 'クライアント側ファイルからロード。' },

  // === トランザクション ===
  { term: 'START TRANSACTION', description: 'トランザクションを開始。', aliases: ['BEGIN'] },
  { term: 'COMMIT', description: 'トランザクションを確定。' },
  { term: 'ROLLBACK', description: 'トランザクションを取り消し。' },
  { term: 'SAVEPOINT', description: 'セーブポイントを設定。' },
  { term: 'ROLLBACK TO SAVEPOINT', description: 'セーブポイントまで戻す。' },
  { term: 'RELEASE SAVEPOINT', description: 'セーブポイントを解放。' },
  { term: 'SET autocommit', description: '自動コミットを設定。' },
  { term: 'SET TRANSACTION ISOLATION LEVEL', description: '分離レベルを設定。' },
  { term: 'READ UNCOMMITTED', description: '分離レベル：ダーティリード許可。' },
  { term: 'READ COMMITTED', description: '分離レベル：コミット済みのみ読む。' },
  { term: 'REPEATABLE READ', description: '分離レベル：繰り返し読み取り可能。' },
  { term: 'SERIALIZABLE', description: '分離レベル：直列化可能。' },
  { term: 'LOCK TABLES', description: 'テーブルをロック。' },
  { term: 'LOCK TABLES ... READ', description: '読み取りロック。' },
  { term: 'LOCK TABLES ... WRITE', description: '書き込みロック。' },
  { term: 'UNLOCK TABLES', description: 'テーブルロックを解放。' },

  // === ユーザー・権限 ===
  { term: 'CREATE USER', description: 'ユーザーを作成。' },
  { term: 'CREATE USER IF NOT EXISTS', description: '存在しない場合のみ作成。' },
  { term: 'ALTER USER', description: 'ユーザーを変更。' },
  { term: 'DROP USER', description: 'ユーザーを削除。' },
  { term: 'DROP USER IF EXISTS', description: '存在する場合のみ削除。' },
  { term: 'RENAME USER', description: 'ユーザー名を変更。' },
  { term: 'SET PASSWORD', description: 'パスワードを設定。' },
  { term: 'GRANT', description: '権限を付与。' },
  { term: 'GRANT ALL PRIVILEGES', description: '全権限を付与。' },
  { term: 'GRANT SELECT', description: 'SELECT権限を付与。' },
  { term: 'GRANT WITH GRANT OPTION', description: '権限付与権限も付与。' },
  { term: 'REVOKE', description: '権限を取り消し。' },
  { term: 'REVOKE ALL PRIVILEGES', description: '全権限を取り消し。' },
  { term: 'FLUSH PRIVILEGES', description: '権限テーブルをリロード。' },
  { term: 'SHOW GRANTS', description: 'ユーザーの権限を表示。' },
  { term: 'CREATE ROLE', description: 'ロールを作成。' },
  { term: 'DROP ROLE', description: 'ロールを削除。' },
  { term: 'SET ROLE', description: 'ロールを有効化。' },

  // === SHOW文 ===
  { term: 'SHOW DATABASES', description: 'データベース一覧を表示。', aliases: ['SHOW SCHEMAS'] },
  { term: 'SHOW TABLES', description: 'テーブル一覧を表示。' },
  { term: 'SHOW FULL TABLES', description: 'テーブル一覧（タイプ付き）を表示。' },
  { term: 'SHOW COLUMNS', description: '列情報を表示。', aliases: ['SHOW FIELDS'] },
  { term: 'SHOW FULL COLUMNS', description: '詳細な列情報を表示。' },
  { term: 'SHOW CREATE TABLE', description: 'テーブル定義を表示。' },
  { term: 'SHOW CREATE DATABASE', description: 'データベース定義を表示。' },
  { term: 'SHOW CREATE VIEW', description: 'ビュー定義を表示。' },
  { term: 'SHOW TABLE STATUS', description: 'テーブル状態を表示。' },
  { term: 'SHOW PROCESSLIST', description: 'プロセス一覧を表示。' },
  { term: 'SHOW FULL PROCESSLIST', description: '詳細なプロセス一覧を表示。' },
  { term: 'SHOW STATUS', description: 'サーバー状態を表示。' },
  { term: 'SHOW GLOBAL STATUS', description: 'グローバル状態を表示。' },
  { term: 'SHOW SESSION STATUS', description: 'セッション状態を表示。' },
  { term: 'SHOW VARIABLES', description: 'サーバー変数を表示。' },
  { term: 'SHOW GLOBAL VARIABLES', description: 'グローバル変数を表示。' },
  { term: 'SHOW SESSION VARIABLES', description: 'セッション変数を表示。' },
  { term: 'SHOW WARNINGS', description: '警告を表示。' },
  { term: 'SHOW ERRORS', description: 'エラーを表示。' },
  { term: 'SHOW ENGINE', description: 'ストレージエンジン情報を表示。' },
  { term: 'SHOW ENGINE INNODB STATUS', description: 'InnoDBの状態を表示。' },
  { term: 'SHOW ENGINES', description: '利用可能なエンジンを表示。' },
  { term: 'SHOW BINARY LOGS', description: 'バイナリログ一覧を表示。' },
  { term: 'SHOW MASTER STATUS', description: 'マスター状態を表示。' },
  { term: 'SHOW SLAVE STATUS', description: 'スレーブ状態を表示。', aliases: ['SHOW REPLICA STATUS'] },
  { term: 'SHOW GRANTS FOR', description: '指定ユーザーの権限を表示。' },
  { term: 'SHOW PLUGINS', description: 'プラグイン一覧を表示。' },
  { term: 'SHOW CHARSET', description: '文字セット一覧を表示。' },
  { term: 'SHOW COLLATION', description: '照合順序一覧を表示。' },

  // === 管理コマンド ===
  { term: 'DESCRIBE', description: 'テーブル構造を表示。', aliases: ['DESC', 'EXPLAIN'] },
  { term: 'EXPLAIN', description: '実行計画を表示。' },
  { term: 'EXPLAIN ANALYZE', description: '実行計画と実行統計を表示。' },
  { term: 'EXPLAIN FORMAT=JSON', description: 'JSON形式で実行計画を表示。' },
  { term: 'EXPLAIN FORMAT=TREE', description: 'ツリー形式で実行計画を表示。' },
  { term: 'ANALYZE TABLE', description: 'テーブル統計を更新。' },
  { term: 'OPTIMIZE TABLE', description: 'テーブルを最適化。' },
  { term: 'REPAIR TABLE', description: 'テーブルを修復。' },
  { term: 'CHECK TABLE', description: 'テーブルをチェック。' },
  { term: 'CHECKSUM TABLE', description: 'テーブルのチェックサムを取得。' },
  { term: 'FLUSH', description: 'キャッシュをフラッシュ。' },
  { term: 'FLUSH TABLES', description: 'テーブルキャッシュをフラッシュ。' },
  { term: 'FLUSH TABLES WITH READ LOCK', description: 'テーブルをフラッシュしてロック。' },
  { term: 'FLUSH LOGS', description: 'ログをフラッシュ。' },
  { term: 'FLUSH BINARY LOGS', description: 'バイナリログをローテート。' },
  { term: 'FLUSH STATUS', description: 'ステータスカウンタをリセット。' },
  { term: 'FLUSH HOSTS', description: 'ホストキャッシュをクリア。' },
  { term: 'RESET MASTER', description: 'バイナリログを削除。' },
  { term: 'RESET SLAVE', description: 'スレーブ情報をリセット。', aliases: ['RESET REPLICA'] },
  { term: 'PURGE BINARY LOGS', description: '古いバイナリログを削除。' },
  { term: 'KILL', description: 'プロセスを終了。' },
  { term: 'KILL QUERY', description: 'クエリのみ終了。' },
  { term: 'KILL CONNECTION', description: '接続を終了。' },
  { term: 'SET', description: '変数を設定。' },
  { term: 'SET GLOBAL', description: 'グローバル変数を設定。' },
  { term: 'SET SESSION', description: 'セッション変数を設定。' },
  { term: 'SET NAMES', description: '文字セットを設定。' },
  { term: 'SET CHARACTER SET', description: '文字セットを設定。' },

  // === レプリケーション ===
  { term: 'CHANGE MASTER TO', description: 'マスター情報を設定。', aliases: ['CHANGE REPLICATION SOURCE TO'] },
  { term: 'START SLAVE', description: 'レプリケーションを開始。', aliases: ['START REPLICA'] },
  { term: 'STOP SLAVE', description: 'レプリケーションを停止。', aliases: ['STOP REPLICA'] },
  { term: 'RESET SLAVE ALL', description: 'スレーブ情報を完全リセット。', aliases: ['RESET REPLICA ALL'] },

  // === 関数 ===
  { term: 'IFNULL', description: 'NULLを代替値に置換。' },
  { term: 'NULLIF', description: '同値ならNULLを返す。' },
  { term: 'COALESCE', description: '最初の非NULL値を返す。' },
  { term: 'IF', description: '条件分岐関数。' },
  { term: 'CASE WHEN', description: '条件分岐式。' },
  { term: 'CONCAT', description: '文字列を連結。' },
  { term: 'CONCAT_WS', description: '区切り文字付きで連結。' },
  { term: 'SUBSTRING', description: '部分文字列を取得。', aliases: ['SUBSTR', 'MID'] },
  { term: 'LEFT', description: '左からn文字を取得。' },
  { term: 'RIGHT', description: '右からn文字を取得。' },
  { term: 'LENGTH', description: 'バイト長を取得。' },
  { term: 'CHAR_LENGTH', description: '文字数を取得。', aliases: ['CHARACTER_LENGTH'] },
  { term: 'LOCATE', description: '文字列の位置を検索。', aliases: ['POSITION', 'INSTR'] },
  { term: 'REPLACE', description: '文字列を置換。' },
  { term: 'TRIM', description: '前後の空白を削除。' },
  { term: 'LTRIM', description: '左側の空白を削除。' },
  { term: 'RTRIM', description: '右側の空白を削除。' },
  { term: 'LPAD', description: '左側を埋める。' },
  { term: 'RPAD', description: '右側を埋める。' },
  { term: 'UPPER', description: '大文字に変換。', aliases: ['UCASE'] },
  { term: 'LOWER', description: '小文字に変換。', aliases: ['LCASE'] },
  { term: 'REVERSE', description: '文字列を反転。' },
  { term: 'REPEAT', description: '文字列を繰り返す。' },
  { term: 'SPACE', description: 'スペースを生成。' },
  { term: 'FORMAT', description: '数値をフォーマット。' },
  { term: 'ROUND', description: '四捨五入。' },
  { term: 'TRUNCATE', description: '切り捨て。' },
  { term: 'CEIL', description: '切り上げ。', aliases: ['CEILING'] },
  { term: 'FLOOR', description: '切り捨て（整数）。' },
  { term: 'MOD', description: '剰余を取得。' },
  { term: 'ABS', description: '絶対値。' },
  { term: 'POW', description: 'べき乗。', aliases: ['POWER'] },
  { term: 'SQRT', description: '平方根。' },
  { term: 'RAND', description: '乱数を生成。' },
  { term: 'NOW', description: '現在日時を取得。' },
  { term: 'CURDATE', description: '現在日付を取得。', aliases: ['CURRENT_DATE'] },
  { term: 'CURTIME', description: '現在時刻を取得。', aliases: ['CURRENT_TIME'] },
  { term: 'CURRENT_TIMESTAMP', description: '現在タイムスタンプを取得。' },
  { term: 'UNIX_TIMESTAMP', description: 'UNIXタイムスタンプを取得。' },
  { term: 'FROM_UNIXTIME', description: 'UNIXタイムスタンプから日時に変換。' },
  { term: 'DATE', description: '日付部分を取得。' },
  { term: 'TIME', description: '時刻部分を取得。' },
  { term: 'YEAR', description: '年を取得。' },
  { term: 'MONTH', description: '月を取得。' },
  { term: 'DAY', description: '日を取得。', aliases: ['DAYOFMONTH'] },
  { term: 'HOUR', description: '時を取得。' },
  { term: 'MINUTE', description: '分を取得。' },
  { term: 'SECOND', description: '秒を取得。' },
  { term: 'DAYOFWEEK', description: '曜日番号を取得。' },
  { term: 'DAYOFYEAR', description: '年内の日番号を取得。' },
  { term: 'WEEK', description: '週番号を取得。' },
  { term: 'DATE_FORMAT', description: '日付をフォーマット。' },
  { term: 'STR_TO_DATE', description: '文字列を日付に変換。' },
  { term: 'DATE_ADD', description: '日付を加算。', aliases: ['ADDDATE'] },
  { term: 'DATE_SUB', description: '日付を減算。', aliases: ['SUBDATE'] },
  { term: 'DATEDIFF', description: '日数の差を取得。' },
  { term: 'TIMEDIFF', description: '時刻の差を取得。' },
  { term: 'TIMESTAMPDIFF', description: 'タイムスタンプの差を取得。' },
  { term: 'LAST_DAY', description: '月末日を取得。' },
  { term: 'CAST', description: 'データ型を変換。' },
  { term: 'CONVERT', description: 'データ型または文字セットを変換。' },
  { term: 'GROUP_CONCAT', description: '行を連結して文字列化。' },
  { term: 'JSON_EXTRACT', description: 'JSONから値を抽出。' },
  { term: 'JSON_SET', description: 'JSON値を設定。' },
  { term: 'JSON_INSERT', description: 'JSON値を挿入。' },
  { term: 'JSON_REPLACE', description: 'JSON値を置換。' },
  { term: 'JSON_REMOVE', description: 'JSON値を削除。' },
  { term: 'JSON_ARRAY', description: 'JSON配列を作成。' },
  { term: 'JSON_OBJECT', description: 'JSONオブジェクトを作成。' },
  { term: 'ROW_NUMBER', description: '連番を付与（ウィンドウ関数）。' },
  { term: 'RANK', description: '順位を付与（同順位あり）。' },
  { term: 'DENSE_RANK', description: '順位を付与（連続）。' },
  { term: 'NTILE', description: 'グループに分割。' },
  { term: 'LAG', description: '前の行の値を取得。' },
  { term: 'LEAD', description: '後の行の値を取得。' },
  { term: 'FIRST_VALUE', description: '最初の値を取得。' },
  { term: 'LAST_VALUE', description: '最後の値を取得。' },
  { term: 'OVER', description: 'ウィンドウ関数の範囲指定。' },
  { term: 'PARTITION BY', description: 'ウィンドウのパーティション。' },

  // === 制約 ===
  { term: 'PRIMARY KEY', description: '主キー制約。' },
  { term: 'FOREIGN KEY', description: '外部キー制約。' },
  { term: 'REFERENCES', description: '外部キーの参照先。' },
  { term: 'ON DELETE CASCADE', description: '親削除時に連鎖削除。' },
  { term: 'ON DELETE SET NULL', description: '親削除時にNULL設定。' },
  { term: 'ON UPDATE CASCADE', description: '親更新時に連鎖更新。' },
  { term: 'UNIQUE', description: '一意制約。' },
  { term: 'NOT NULL', description: 'NOT NULL制約。' },
  { term: 'DEFAULT', description: 'デフォルト値。' },
  { term: 'CHECK', description: 'CHECK制約（MySQL 8.0.16+）。' },
  { term: 'AUTO_INCREMENT', description: '自動増分。' },

  // === ストレージエンジン ===
  { term: 'InnoDB', description: 'トランザクション対応のデフォルトエンジン。' },
  { term: 'MyISAM', description: 'トランザクション非対応の旧エンジン。' },
  { term: 'MEMORY', description: 'メモリ上に格納するエンジン。', aliases: ['HEAP'] },
  { term: 'ARCHIVE', description: '圧縮アーカイブ用エンジン。' },
  { term: 'CSV', description: 'CSV形式で格納するエンジン。' },
  { term: 'BLACKHOLE', description: '書き込みを破棄するエンジン。' },

  // === 概念・用語 ===
  { term: 'binlog', description: 'バイナリログ。変更履歴を記録。' },
  { term: 'relay log', description: 'リレーログ。レプリケーション用。' },
  { term: 'slow query log', description: 'スロークエリログ。遅いクエリを記録。' },
  { term: 'general log', description: '一般クエリログ。全クエリを記録。' },
  { term: 'error log', description: 'エラーログ。' },
  { term: 'redo log', description: 'REDOログ（InnoDB）。' },
  { term: 'undo log', description: 'UNDOログ（InnoDB）。' },
  { term: 'buffer pool', description: 'バッファプール（InnoDB）。' },
  { term: 'query cache', description: 'クエリキャッシュ（MySQL 8.0で廃止）。' },
  { term: 'thread pool', description: 'スレッドプール。' },
  { term: 'tablespace', description: 'テーブルスペース（InnoDB）。' },
  { term: 'ibdata', description: 'システムテーブルスペースファイル。' },
  { term: '.ibd', description: 'テーブルごとのテーブルスペースファイル。' },
  { term: '.frm', description: 'テーブル定義ファイル（MySQL 5.7以前）。' },
  { term: 'GTID', description: 'グローバルトランザクションID。' },
  { term: 'my.cnf', description: 'MySQL設定ファイル（Linux）。', aliases: ['my.ini'] },
];
