/**
 * Oracle Database用語集
 * Oracle DB SQL・PL/SQL・管理コマンドの説明
 */

import { CliGlossaryEntry } from './gitGlossary';

export const ORACLE_GLOSSARY: ReadonlyArray<CliGlossaryEntry> = [
  // === SQL*Plus ===
  { term: 'sqlplus', description: 'Oracle Databaseの対話型SQL実行ツール。' },
  { term: 'sqlplus / as sysdba', description: 'SYSDBA権限でOS認証ログイン。' },
  { term: 'sqlplus user/pass@db', description: '指定ユーザー・DB接続文字列でログイン。' },
  { term: 'CONNECT', description: 'データベースに接続する。' },
  { term: 'DISCONNECT', description: 'データベースから切断する。' },
  { term: 'EXIT', description: 'SQL*Plusを終了する。', aliases: ['QUIT'] },
  { term: 'DESCRIBE', description: 'テーブルや関数の構造を表示する。', aliases: ['DESC'] },
  { term: 'SHOW USER', description: '現在のユーザーを表示。' },
  { term: 'SHOW ERRORS', description: '直前のコンパイルエラーを表示。' },
  { term: 'SHOW PARAMETER', description: '初期化パラメータを表示。' },
  { term: 'SHOW SGA', description: 'System Global Areaの情報を表示。' },
  { term: 'SET SERVEROUTPUT ON', description: 'DBMS_OUTPUT.PUT_LINEの出力を有効化。' },
  { term: 'SET LINESIZE', description: '1行の表示幅を設定。' },
  { term: 'SET PAGESIZE', description: '1ページの行数を設定。' },
  { term: 'SET TIMING ON', description: '実行時間を表示。' },
  { term: 'SET AUTOTRACE ON', description: '実行計画と統計を表示。' },
  { term: 'SET FEEDBACK ON', description: '処理行数を表示。' },
  { term: 'SPOOL', description: '出力をファイルに保存する。' },
  { term: 'SPOOL OFF', description: 'SPOOLを終了する。' },
  { term: '@', description: 'SQLスクリプトファイルを実行。', aliases: ['START'] },
  { term: '@@', description: '相対パスでスクリプトを実行。' },
  { term: 'DEFINE', description: '置換変数を定義する。' },
  { term: 'UNDEFINE', description: '置換変数を削除する。' },
  { term: '&', description: '置換変数（入力プロンプト）。' },
  { term: '&&', description: '置換変数（一度だけ入力）。' },
  { term: 'ACCEPT', description: 'ユーザー入力を変数に格納。' },
  { term: 'PROMPT', description: 'メッセージを表示する。' },
  { term: 'COLUMN', description: '列の書式を設定する。' },
  { term: 'BREAK', description: 'レポートの区切りを設定。' },
  { term: 'COMPUTE', description: '小計や合計を計算。' },
  { term: 'TTITLE', description: 'レポートのヘッダーを設定。' },
  { term: 'BTITLE', description: 'レポートのフッターを設定。' },
  { term: 'WHENEVER SQLERROR', description: 'SQLエラー時の動作を設定。' },
  { term: 'WHENEVER OSERROR', description: 'OSエラー時の動作を設定。' },

  // === DDL ===
  { term: 'CREATE TABLE', description: 'テーブルを作成する。' },
  { term: 'CREATE TABLE AS SELECT', description: 'SELECTの結果からテーブルを作成。', aliases: ['CTAS'] },
  { term: 'ALTER TABLE', description: 'テーブルの構造を変更する。' },
  { term: 'ALTER TABLE ADD', description: '列を追加する。' },
  { term: 'ALTER TABLE MODIFY', description: '列の定義を変更する。' },
  { term: 'ALTER TABLE DROP COLUMN', description: '列を削除する。' },
  { term: 'ALTER TABLE RENAME', description: 'テーブルまたは列の名前を変更。' },
  { term: 'ALTER TABLE ADD CONSTRAINT', description: '制約を追加する。' },
  { term: 'ALTER TABLE DROP CONSTRAINT', description: '制約を削除する。' },
  { term: 'ALTER TABLE ENABLE CONSTRAINT', description: '制約を有効化する。' },
  { term: 'ALTER TABLE DISABLE CONSTRAINT', description: '制約を無効化する。' },
  { term: 'DROP TABLE', description: 'テーブルを削除する。' },
  { term: 'DROP TABLE PURGE', description: 'テーブルをごみ箱に入れず完全削除。' },
  { term: 'TRUNCATE TABLE', description: 'テーブルの全行を高速削除（ロールバック不可）。' },
  { term: 'RENAME', description: 'オブジェクト名を変更する。' },
  { term: 'COMMENT ON', description: 'オブジェクトにコメントを追加。' },

  { term: 'CREATE INDEX', description: 'インデックスを作成する。' },
  { term: 'CREATE UNIQUE INDEX', description: '一意インデックスを作成。' },
  { term: 'CREATE BITMAP INDEX', description: 'ビットマップインデックスを作成。' },
  { term: 'CREATE INDEX ONLINE', description: 'オンラインでインデックスを作成。' },
  { term: 'ALTER INDEX REBUILD', description: 'インデックスを再構築する。' },
  { term: 'ALTER INDEX REBUILD ONLINE', description: 'オンラインでインデックスを再構築。' },
  { term: 'DROP INDEX', description: 'インデックスを削除する。' },

  { term: 'CREATE VIEW', description: 'ビューを作成する。' },
  { term: 'CREATE OR REPLACE VIEW', description: 'ビューを作成または置換。' },
  { term: 'CREATE MATERIALIZED VIEW', description: 'マテリアライズドビューを作成。' },
  { term: 'ALTER MATERIALIZED VIEW', description: 'マテビューを変更する。' },
  { term: 'REFRESH MATERIALIZED VIEW', description: 'マテビューをリフレッシュ。' },
  { term: 'DROP VIEW', description: 'ビューを削除する。' },
  { term: 'DROP MATERIALIZED VIEW', description: 'マテビューを削除する。' },

  { term: 'CREATE SEQUENCE', description: 'シーケンスを作成する。' },
  { term: 'ALTER SEQUENCE', description: 'シーケンスを変更する。' },
  { term: 'DROP SEQUENCE', description: 'シーケンスを削除する。' },
  { term: 'NEXTVAL', description: 'シーケンスの次の値を取得。' },
  { term: 'CURRVAL', description: 'シーケンスの現在の値を取得。' },

  { term: 'CREATE SYNONYM', description: 'シノニムを作成する。' },
  { term: 'CREATE PUBLIC SYNONYM', description: 'パブリックシノニムを作成。' },
  { term: 'DROP SYNONYM', description: 'シノニムを削除する。' },

  { term: 'CREATE TABLESPACE', description: '表領域を作成する。' },
  { term: 'ALTER TABLESPACE', description: '表領域を変更する。' },
  { term: 'DROP TABLESPACE', description: '表領域を削除する。' },

  { term: 'CREATE USER', description: 'ユーザーを作成する。' },
  { term: 'ALTER USER', description: 'ユーザーを変更する。' },
  { term: 'DROP USER', description: 'ユーザーを削除する。' },
  { term: 'DROP USER CASCADE', description: 'ユーザーとそのオブジェクトを削除。' },

  { term: 'CREATE ROLE', description: 'ロールを作成する。' },
  { term: 'DROP ROLE', description: 'ロールを削除する。' },

  { term: 'CREATE PROFILE', description: 'プロファイルを作成する。' },
  { term: 'ALTER PROFILE', description: 'プロファイルを変更する。' },
  { term: 'DROP PROFILE', description: 'プロファイルを削除する。' },

  // === DML ===
  { term: 'SELECT', description: 'データを取得する。' },
  { term: 'SELECT DISTINCT', description: '重複を除いて取得。' },
  { term: 'SELECT FOR UPDATE', description: '行をロックして取得。' },
  { term: 'SELECT FOR UPDATE NOWAIT', description: '待機せずにロック取得を試みる。' },
  { term: 'SELECT FOR UPDATE SKIP LOCKED', description: 'ロック済み行をスキップ。' },
  { term: 'INSERT INTO', description: 'データを挿入する。' },
  { term: 'INSERT ALL', description: '複数テーブルに挿入する。' },
  { term: 'INSERT FIRST', description: '条件に応じて最初にマッチしたテーブルに挿入。' },
  { term: 'UPDATE', description: 'データを更新する。' },
  { term: 'DELETE', description: 'データを削除する。' },
  { term: 'MERGE', description: 'INSERT/UPDATE/DELETEを条件に応じて実行。' },
  { term: 'MERGE INTO', description: 'マージ先テーブルを指定。' },
  { term: 'MERGE USING', description: 'マージ元を指定。' },
  { term: 'WHEN MATCHED', description: 'マッチ時の処理を定義。' },
  { term: 'WHEN NOT MATCHED', description: '非マッチ時の処理を定義。' },

  // === トランザクション ===
  { term: 'COMMIT', description: 'トランザクションを確定する。' },
  { term: 'ROLLBACK', description: 'トランザクションを取り消す。' },
  { term: 'ROLLBACK TO SAVEPOINT', description: 'セーブポイントまでロールバック。' },
  { term: 'SAVEPOINT', description: 'セーブポイントを設定する。' },
  { term: 'SET TRANSACTION', description: 'トランザクション属性を設定。' },
  { term: 'SET TRANSACTION READ ONLY', description: '読み取り専用トランザクション。' },
  { term: 'SET TRANSACTION ISOLATION LEVEL', description: '分離レベルを設定。' },
  { term: 'LOCK TABLE', description: 'テーブルを明示的にロック。' },
  { term: 'LOCK TABLE IN EXCLUSIVE MODE', description: '排他ロック。' },
  { term: 'LOCK TABLE IN SHARE MODE', description: '共有ロック。' },

  // === 権限 ===
  { term: 'GRANT', description: '権限を付与する。' },
  { term: 'GRANT SELECT ON', description: 'SELECT権限を付与。' },
  { term: 'GRANT ALL ON', description: '全権限を付与。' },
  { term: 'GRANT WITH GRANT OPTION', description: '権限付与権限も付与。' },
  { term: 'GRANT ROLE TO', description: 'ロールを付与する。' },
  { term: 'REVOKE', description: '権限を取り消す。' },

  // === PL/SQL ===
  { term: 'CREATE PROCEDURE', description: 'ストアドプロシージャを作成。' },
  { term: 'CREATE OR REPLACE PROCEDURE', description: 'プロシージャを作成または置換。' },
  { term: 'CREATE FUNCTION', description: 'ファンクションを作成。' },
  { term: 'CREATE OR REPLACE FUNCTION', description: 'ファンクションを作成または置換。' },
  { term: 'CREATE PACKAGE', description: 'パッケージ仕様部を作成。' },
  { term: 'CREATE PACKAGE BODY', description: 'パッケージ本体を作成。' },
  { term: 'CREATE TRIGGER', description: 'トリガーを作成。' },
  { term: 'CREATE OR REPLACE TRIGGER', description: 'トリガーを作成または置換。' },
  { term: 'ALTER TRIGGER ENABLE', description: 'トリガーを有効化。' },
  { term: 'ALTER TRIGGER DISABLE', description: 'トリガーを無効化。' },
  { term: 'CREATE TYPE', description: 'オブジェクト型を作成。' },
  { term: 'DROP PROCEDURE', description: 'プロシージャを削除。' },
  { term: 'DROP FUNCTION', description: 'ファンクションを削除。' },
  { term: 'DROP PACKAGE', description: 'パッケージを削除。' },
  { term: 'DROP TRIGGER', description: 'トリガーを削除。' },
  { term: 'DROP TYPE', description: 'オブジェクト型を削除。' },

  { term: 'DECLARE', description: 'PL/SQL変数宣言ブロック。' },
  { term: 'BEGIN', description: 'PL/SQL実行ブロック開始。' },
  { term: 'END', description: 'PL/SQLブロック終了。' },
  { term: 'EXCEPTION', description: '例外処理ブロック。' },
  { term: 'WHEN OTHERS', description: '全ての例外をキャッチ。' },
  { term: 'RAISE', description: '例外を発生させる。' },
  { term: 'RAISE_APPLICATION_ERROR', description: 'カスタムエラーを発生。' },

  { term: 'IF THEN', description: '条件分岐。' },
  { term: 'ELSIF', description: '追加条件分岐。' },
  { term: 'ELSE', description: '条件分岐のデフォルト。' },
  { term: 'END IF', description: 'IF文の終了。' },
  { term: 'CASE', description: 'CASE式/文。' },
  { term: 'END CASE', description: 'CASE文の終了。' },
  { term: 'LOOP', description: '無限ループ。' },
  { term: 'END LOOP', description: 'ループの終了。' },
  { term: 'EXIT', description: 'ループを抜ける。' },
  { term: 'EXIT WHEN', description: '条件付きでループを抜ける。' },
  { term: 'CONTINUE', description: '次のループ繰り返しへ。' },
  { term: 'WHILE LOOP', description: '条件付きループ。' },
  { term: 'FOR LOOP', description: 'カウンタループ。' },
  { term: 'FORALL', description: '一括DML実行。' },
  { term: 'BULK COLLECT', description: '一括データ取得。' },

  { term: 'CURSOR', description: 'カーソルを宣言。' },
  { term: 'OPEN', description: 'カーソルを開く。' },
  { term: 'FETCH', description: 'カーソルからデータ取得。' },
  { term: 'CLOSE', description: 'カーソルを閉じる。' },
  { term: '%FOUND', description: 'カーソル属性：データあり。' },
  { term: '%NOTFOUND', description: 'カーソル属性：データなし。' },
  { term: '%ROWCOUNT', description: 'カーソル属性：処理行数。' },
  { term: '%ISOPEN', description: 'カーソル属性：オープン状態。' },
  { term: '%TYPE', description: '列のデータ型を参照。' },
  { term: '%ROWTYPE', description: '行の型を参照。' },
  { term: 'REF CURSOR', description: '参照カーソル型。' },
  { term: 'SYS_REFCURSOR', description: 'システム参照カーソル型。' },

  { term: 'DBMS_OUTPUT.PUT_LINE', description: 'コンソールに出力。' },
  { term: 'DBMS_SQL', description: '動的SQLパッケージ。' },
  { term: 'EXECUTE IMMEDIATE', description: '動的SQLを実行。' },
  { term: 'DBMS_LOCK', description: 'ロック管理パッケージ。' },
  { term: 'DBMS_JOB', description: 'ジョブスケジューリング（旧）。' },
  { term: 'DBMS_SCHEDULER', description: 'ジョブスケジューリング。' },
  { term: 'DBMS_STATS', description: '統計情報管理パッケージ。' },
  { term: 'DBMS_STATS.GATHER_TABLE_STATS', description: 'テーブル統計を収集。' },
  { term: 'DBMS_STATS.GATHER_SCHEMA_STATS', description: 'スキーマ統計を収集。' },
  { term: 'DBMS_METADATA', description: 'DDL抽出パッケージ。' },
  { term: 'DBMS_XPLAN', description: '実行計画表示パッケージ。' },
  { term: 'DBMS_XPLAN.DISPLAY', description: 'EXPLAIN PLANの結果を表示。' },
  { term: 'DBMS_XPLAN.DISPLAY_CURSOR', description: 'カーソルの実行計画を表示。' },
  { term: 'UTL_FILE', description: 'ファイルI/Oパッケージ。' },
  { term: 'UTL_HTTP', description: 'HTTPリクエストパッケージ。' },
  { term: 'UTL_MAIL', description: 'メール送信パッケージ。' },

  // === 関数 ===
  { term: 'NVL', description: 'NULLを代替値に置換。' },
  { term: 'NVL2', description: 'NULL/非NULLで異なる値を返す。' },
  { term: 'COALESCE', description: '最初の非NULL値を返す。' },
  { term: 'NULLIF', description: '同値ならNULLを返す。' },
  { term: 'DECODE', description: '条件分岐関数（Oracle独自）。' },
  { term: 'CASE WHEN', description: '条件分岐式。' },
  { term: 'TO_CHAR', description: '文字列に変換。' },
  { term: 'TO_NUMBER', description: '数値に変換。' },
  { term: 'TO_DATE', description: '日付に変換。' },
  { term: 'TO_TIMESTAMP', description: 'タイムスタンプに変換。' },
  { term: 'CAST', description: 'データ型を変換。' },
  { term: 'SUBSTR', description: '部分文字列を取得。' },
  { term: 'INSTR', description: '文字列の位置を検索。' },
  { term: 'LENGTH', description: '文字列の長さを取得。' },
  { term: 'REPLACE', description: '文字列を置換。' },
  { term: 'TRANSLATE', description: '文字を変換。' },
  { term: 'TRIM', description: '前後の空白を削除。' },
  { term: 'LTRIM', description: '左側の空白を削除。' },
  { term: 'RTRIM', description: '右側の空白を削除。' },
  { term: 'LPAD', description: '左側を埋める。' },
  { term: 'RPAD', description: '右側を埋める。' },
  { term: 'UPPER', description: '大文字に変換。' },
  { term: 'LOWER', description: '小文字に変換。' },
  { term: 'INITCAP', description: '先頭を大文字に。' },
  { term: 'CONCAT', description: '文字列を連結。' },
  { term: '||', description: '文字列連結演算子。' },
  { term: 'ROUND', description: '四捨五入。' },
  { term: 'TRUNC', description: '切り捨て。' },
  { term: 'CEIL', description: '切り上げ。' },
  { term: 'FLOOR', description: '切り捨て（整数）。' },
  { term: 'MOD', description: '剰余を取得。' },
  { term: 'ABS', description: '絶対値。' },
  { term: 'POWER', description: 'べき乗。' },
  { term: 'SQRT', description: '平方根。' },
  { term: 'SYSDATE', description: '現在日時を取得。' },
  { term: 'SYSTIMESTAMP', description: '現在タイムスタンプを取得。' },
  { term: 'CURRENT_DATE', description: 'セッションタイムゾーンの現在日時。' },
  { term: 'CURRENT_TIMESTAMP', description: 'セッションタイムゾーンの現在タイムスタンプ。' },
  { term: 'ADD_MONTHS', description: '月を加算。' },
  { term: 'MONTHS_BETWEEN', description: '月数の差を取得。' },
  { term: 'LAST_DAY', description: '月末日を取得。' },
  { term: 'NEXT_DAY', description: '次の指定曜日を取得。' },
  { term: 'EXTRACT', description: '日付要素を抽出。' },
  { term: 'ROW_NUMBER', description: '連番を付与（分析関数）。' },
  { term: 'RANK', description: '順位を付与（同順位あり）。' },
  { term: 'DENSE_RANK', description: '順位を付与（連続）。' },
  { term: 'NTILE', description: 'グループに分割。' },
  { term: 'LAG', description: '前の行の値を取得。' },
  { term: 'LEAD', description: '後の行の値を取得。' },
  { term: 'FIRST_VALUE', description: '最初の値を取得。' },
  { term: 'LAST_VALUE', description: '最後の値を取得。' },
  { term: 'OVER', description: '分析関数のウィンドウ指定。' },
  { term: 'PARTITION BY', description: '分析関数のパーティション。' },
  { term: 'ORDER BY', description: 'ソート順序を指定。' },
  { term: 'LISTAGG', description: '行を連結して文字列化。' },
  { term: 'PIVOT', description: '行を列に変換。' },
  { term: 'UNPIVOT', description: '列を行に変換。' },
  { term: 'CONNECT BY', description: '階層問い合わせ。' },
  { term: 'START WITH', description: '階層問い合わせの起点。' },
  { term: 'PRIOR', description: '親行を参照。' },
  { term: 'LEVEL', description: '階層レベル。' },
  { term: 'SYS_CONNECT_BY_PATH', description: 'パスを取得。' },
  { term: 'CONNECT_BY_ROOT', description: 'ルート行の値を取得。' },
  { term: 'ROWNUM', description: '行番号（取得順）。' },
  { term: 'ROWID', description: '行の物理アドレス。' },

  // === ヒント ===
  { term: '/*+ FULL */', description: 'フルテーブルスキャンを強制。' },
  { term: '/*+ INDEX */', description: 'インデックススキャンを強制。' },
  { term: '/*+ INDEX_FFS */', description: '高速フルインデックススキャン。' },
  { term: '/*+ PARALLEL */', description: 'パラレル実行を指定。' },
  { term: '/*+ ORDERED */', description: 'FROM句の順序で結合。' },
  { term: '/*+ LEADING */', description: '結合順序を指定。' },
  { term: '/*+ USE_NL */', description: 'ネステッドループ結合を指定。' },
  { term: '/*+ USE_HASH */', description: 'ハッシュ結合を指定。' },
  { term: '/*+ USE_MERGE */', description: 'ソートマージ結合を指定。' },
  { term: '/*+ FIRST_ROWS */', description: '最初の行を優先。' },
  { term: '/*+ ALL_ROWS */', description: 'スループットを優先。' },
  { term: '/*+ APPEND */', description: 'ダイレクトパスインサート。' },
  { term: '/*+ NO_APPEND */', description: '通常インサート。' },
  { term: '/*+ RESULT_CACHE */', description: '結果キャッシュを使用。' },

  // === 管理コマンド ===
  { term: 'STARTUP', description: 'データベースを起動。' },
  { term: 'STARTUP MOUNT', description: 'マウント状態で起動。' },
  { term: 'STARTUP NOMOUNT', description: 'インスタンスのみ起動。' },
  { term: 'STARTUP RESTRICT', description: '制限モードで起動。' },
  { term: 'SHUTDOWN', description: 'データベースを停止。' },
  { term: 'SHUTDOWN NORMAL', description: '通常停止（接続終了を待機）。' },
  { term: 'SHUTDOWN IMMEDIATE', description: '即時停止（トランザクションロールバック）。' },
  { term: 'SHUTDOWN ABORT', description: '強制停止（復旧が必要）。' },
  { term: 'SHUTDOWN TRANSACTIONAL', description: 'トランザクション完了後に停止。' },
  { term: 'ALTER DATABASE', description: 'データベースを変更。' },
  { term: 'ALTER DATABASE OPEN', description: 'データベースをオープン。' },
  { term: 'ALTER DATABASE MOUNT', description: 'データベースをマウント。' },
  { term: 'ALTER SYSTEM', description: 'システム設定を変更。' },
  { term: 'ALTER SYSTEM FLUSH SHARED_POOL', description: '共有プールをフラッシュ。' },
  { term: 'ALTER SYSTEM FLUSH BUFFER_CACHE', description: 'バッファキャッシュをフラッシュ。' },
  { term: 'ALTER SYSTEM KILL SESSION', description: 'セッションを強制終了。' },
  { term: 'ALTER SYSTEM SWITCH LOGFILE', description: 'REDOログを切り替え。' },
  { term: 'ALTER SYSTEM CHECKPOINT', description: 'チェックポイントを実行。' },
  { term: 'ALTER SYSTEM ARCHIVE LOG', description: 'アーカイブログを作成。' },
  { term: 'ALTER SESSION', description: 'セッション設定を変更。' },
  { term: 'ALTER SESSION SET NLS_DATE_FORMAT', description: '日付書式を設定。' },

  // === Data Pump ===
  { term: 'expdp', description: 'Data Pumpエクスポート。' },
  { term: 'impdp', description: 'Data Pumpインポート。' },
  { term: 'expdp schemas', description: 'スキーマ単位でエクスポート。' },
  { term: 'expdp tables', description: 'テーブル単位でエクスポート。' },
  { term: 'expdp full', description: '全データベースをエクスポート。' },
  { term: 'impdp remap_schema', description: 'スキーマを変換してインポート。' },
  { term: 'impdp remap_tablespace', description: '表領域を変換してインポート。' },
  { term: 'impdp table_exists_action', description: 'テーブル存在時の動作。' },

  // === RMAN ===
  { term: 'rman', description: 'Recovery Manager。バックアップ/リカバリツール。' },
  { term: 'BACKUP DATABASE', description: 'データベースをバックアップ。' },
  { term: 'BACKUP TABLESPACE', description: '表領域をバックアップ。' },
  { term: 'BACKUP ARCHIVELOG', description: 'アーカイブログをバックアップ。' },
  { term: 'RESTORE DATABASE', description: 'データベースをリストア。' },
  { term: 'RECOVER DATABASE', description: 'データベースをリカバリ。' },
  { term: 'CROSSCHECK', description: 'バックアップの整合性チェック。' },
  { term: 'DELETE EXPIRED', description: '期限切れバックアップを削除。' },
  { term: 'DELETE OBSOLETE', description: '不要バックアップを削除。' },
  { term: 'VALIDATE', description: 'バックアップを検証。' },
  { term: 'LIST BACKUP', description: 'バックアップ一覧を表示。' },
  { term: 'REPORT SCHEMA', description: 'スキーマ情報を表示。' },

  // === ディクショナリビュー ===
  { term: 'DBA_TABLES', description: '全テーブル情報。' },
  { term: 'DBA_TAB_COLUMNS', description: '全列情報。' },
  { term: 'DBA_INDEXES', description: '全インデックス情報。' },
  { term: 'DBA_CONSTRAINTS', description: '全制約情報。' },
  { term: 'DBA_OBJECTS', description: '全オブジェクト情報。' },
  { term: 'DBA_USERS', description: '全ユーザー情報。' },
  { term: 'DBA_TABLESPACES', description: '全表領域情報。' },
  { term: 'DBA_DATA_FILES', description: '全データファイル情報。' },
  { term: 'DBA_FREE_SPACE', description: '空き領域情報。' },
  { term: 'DBA_SEGMENTS', description: 'セグメント情報。' },
  { term: 'DBA_EXTENTS', description: 'エクステント情報。' },
  { term: 'DBA_JOBS', description: 'ジョブ情報（旧）。' },
  { term: 'DBA_SCHEDULER_JOBS', description: 'スケジューラジョブ情報。' },
  { term: 'V$SESSION', description: '現在のセッション情報。' },
  { term: 'V$PROCESS', description: 'プロセス情報。' },
  { term: 'V$SQL', description: 'SQL情報。' },
  { term: 'V$SQLAREA', description: 'SQL領域情報。' },
  { term: 'V$LOCK', description: 'ロック情報。' },
  { term: 'V$LOCKED_OBJECT', description: 'ロックされたオブジェクト。' },
  { term: 'V$INSTANCE', description: 'インスタンス情報。' },
  { term: 'V$DATABASE', description: 'データベース情報。' },
  { term: 'V$PARAMETER', description: '初期化パラメータ。' },
  { term: 'V$SGA', description: 'SGA情報。' },
  { term: 'V$SGAINFO', description: 'SGA詳細情報。' },
  { term: 'V$PGA_TARGET_ADVICE', description: 'PGAアドバイス。' },
  { term: 'V$LOG', description: 'REDOログ情報。' },
  { term: 'V$LOGFILE', description: 'REDOログファイル情報。' },
  { term: 'V$ARCHIVED_LOG', description: 'アーカイブログ情報。' },
  { term: 'V$DATAFILE', description: 'データファイル情報。' },
  { term: 'V$TEMPFILE', description: '一時ファイル情報。' },
  { term: 'V$TABLESPACE', description: '表領域情報。' },
  { term: 'V$SYSTEM_EVENT', description: 'システムイベント統計。' },
  { term: 'V$SESSION_EVENT', description: 'セッションイベント統計。' },
  { term: 'V$WAITSTAT', description: '待機統計。' },
  { term: 'V$SYSSTAT', description: 'システム統計。' },
  { term: 'V$SESSTAT', description: 'セッション統計。' },

  // === 概念・用語 ===
  { term: 'SGA', description: 'System Global Area。共有メモリ領域。' },
  { term: 'PGA', description: 'Program Global Area。プロセス専用メモリ。' },
  { term: 'REDO', description: '変更履歴を記録するログ。' },
  { term: 'UNDO', description: 'ロールバック用のデータ。' },
  { term: 'ARCHIVELOG', description: 'アーカイブログモード。' },
  { term: 'NOARCHIVELOG', description: '非アーカイブログモード。' },
  { term: 'CDB', description: 'Container Database。マルチテナント用。' },
  { term: 'PDB', description: 'Pluggable Database。プラガブルDB。' },
  { term: 'RAC', description: 'Real Application Clusters。クラスタ構成。' },
  { term: 'Data Guard', description: 'スタンバイデータベース機能。' },
  { term: 'ASM', description: 'Automatic Storage Management。' },
  { term: 'AWR', description: 'Automatic Workload Repository。性能統計。' },
  { term: 'ADDM', description: 'Automatic Database Diagnostic Monitor。' },
  { term: 'OEM', description: 'Oracle Enterprise Manager。管理ツール。' },
  { term: 'TNS', description: 'Transparent Network Substrate。接続設定。' },
  { term: 'tnsnames.ora', description: 'TNS接続定義ファイル。' },
  { term: 'listener.ora', description: 'リスナー設定ファイル。' },
  { term: 'sqlnet.ora', description: 'SQL*Net設定ファイル。' },
  { term: 'init.ora', description: '初期化パラメータファイル。' },
  { term: 'spfile', description: 'サーバーパラメータファイル。' },
  { term: 'pfile', description: 'テキストパラメータファイル。' },
];
