/**
 * pip用語集
 * pipコマンド・サブコマンド・オプションの説明
 * Python関連ツール（venv、pipenv、poetry、uv等）も含む
 */

import { CliGlossaryEntry } from './gitGlossary';

export const PIP_GLOSSARY: ReadonlyArray<CliGlossaryEntry> = [
  // === pip基本 ===
  { term: 'pip', description: 'Pythonのパッケージインストーラー。PyPIからパッケージをインストール・管理。' },
  { term: 'pip3', description: 'Python 3用のpipコマンド。' },
  { term: 'python -m pip', description: 'モジュールとしてpipを実行。推奨される方法。' },

  // === インストール ===
  { term: 'pip install', description: 'パッケージをインストールする。' },
  { term: 'pip install <package>', description: '指定パッケージをインストール。' },
  { term: 'pip install <package>==<version>', description: '特定バージョンをインストール。' },
  { term: 'pip install <package>>=<version>', description: '指定バージョン以上をインストール。' },
  { term: 'pip install <package>~=<version>', description: '互換バージョンをインストール（~=1.4は>=1.4,<1.5）。' },
  { term: 'pip install -r', description: '要件ファイルからインストール。', aliases: ['pip install --requirement'] },
  { term: 'pip install -e', description: '編集可能モードでインストール（開発用）。', aliases: ['pip install --editable'] },
  { term: 'pip install --upgrade', description: 'パッケージを最新版に更新。', aliases: ['pip install -U'] },
  { term: 'pip install --user', description: 'ユーザーディレクトリにインストール。' },
  { term: 'pip install --no-deps', description: '依存パッケージをインストールしない。' },
  { term: 'pip install --pre', description: 'プレリリース版も含めてインストール。' },
  { term: 'pip install --force-reinstall', description: '強制的に再インストール。' },
  { term: 'pip install --ignore-installed', description: 'インストール済みパッケージを無視。', aliases: ['pip install -I'] },
  { term: 'pip install --no-cache-dir', description: 'キャッシュを使用しない。' },
  { term: 'pip install --target', description: 'インストール先ディレクトリを指定。', aliases: ['pip install -t'] },
  { term: 'pip install --index-url', description: 'パッケージインデックスURLを指定。', aliases: ['pip install -i'] },
  { term: 'pip install --extra-index-url', description: '追加のパッケージインデックスURL。' },
  { term: 'pip install --find-links', description: 'パッケージを検索するURLやディレクトリ。', aliases: ['pip install -f'] },
  { term: 'pip install --no-index', description: 'パッケージインデックスを使用しない。' },
  { term: 'pip install --trusted-host', description: '信頼するホストを指定。' },
  { term: 'pip install --proxy', description: 'プロキシを指定。' },
  { term: 'pip install --dry-run', description: '実際にはインストールせず確認。' },
  { term: 'pip install --quiet', description: '出力を抑制。', aliases: ['pip install -q'] },
  { term: 'pip install --verbose', description: '詳細な出力。', aliases: ['pip install -v'] },
  { term: 'pip install --no-binary', description: 'ソースからビルド（指定パッケージ）。' },
  { term: 'pip install --only-binary', description: 'バイナリのみ使用（指定パッケージ）。' },
  { term: 'pip install --require-hashes', description: 'ハッシュ検証を必須にする。' },
  { term: 'pip install --constraint', description: '制約ファイルを指定。', aliases: ['pip install -c'] },

  // === アンインストール ===
  { term: 'pip uninstall', description: 'パッケージをアンインストールする。' },
  { term: 'pip uninstall <package>', description: '指定パッケージをアンインストール。' },
  { term: 'pip uninstall -r', description: '要件ファイルのパッケージをアンインストール。' },
  { term: 'pip uninstall -y', description: '確認なしでアンインストール。', aliases: ['pip uninstall --yes'] },

  // === 情報表示 ===
  { term: 'pip list', description: 'インストール済みパッケージを一覧表示。' },
  { term: 'pip list --outdated', description: '更新可能なパッケージを表示。', aliases: ['pip list -o'] },
  { term: 'pip list --uptodate', description: '最新のパッケージを表示。', aliases: ['pip list -u'] },
  { term: 'pip list --editable', description: '編集可能インストールのみ表示。', aliases: ['pip list -e'] },
  { term: 'pip list --local', description: 'ローカルパッケージのみ表示。', aliases: ['pip list -l'] },
  { term: 'pip list --user', description: 'ユーザーパッケージのみ表示。' },
  { term: 'pip list --format', description: '出力形式を指定（columns/freeze/json）。' },
  { term: 'pip list --not-required', description: '他のパッケージに必要とされないパッケージを表示。' },

  { term: 'pip show', description: 'パッケージの詳細情報を表示。' },
  { term: 'pip show <package>', description: '指定パッケージの情報を表示。' },
  { term: 'pip show --files', description: 'インストールされたファイル一覧も表示。', aliases: ['pip show -f'] },

  { term: 'pip freeze', description: 'インストール済みパッケージをrequirements形式で出力。' },
  { term: 'pip freeze --local', description: 'ローカルパッケージのみ出力。', aliases: ['pip freeze -l'] },
  { term: 'pip freeze --user', description: 'ユーザーパッケージのみ出力。' },
  { term: 'pip freeze --exclude-editable', description: '編集可能パッケージを除外。' },
  { term: 'pip freeze --all', description: 'pip自身も含めて出力。' },

  // === 検索 ===
  { term: 'pip search', description: 'PyPIでパッケージを検索（現在は無効化）。' },
  { term: 'pip index versions', description: '利用可能なバージョンを表示。' },

  // === ダウンロード ===
  { term: 'pip download', description: 'パッケージをダウンロード（インストールしない）。' },
  { term: 'pip download <package>', description: '指定パッケージをダウンロード。' },
  { term: 'pip download -r', description: '要件ファイルのパッケージをダウンロード。' },
  { term: 'pip download -d', description: 'ダウンロード先を指定。', aliases: ['pip download --dest'] },
  { term: 'pip download --platform', description: 'プラットフォームを指定。' },
  { term: 'pip download --python-version', description: 'Pythonバージョンを指定。' },

  // === wheel ===
  { term: 'pip wheel', description: 'パッケージのwheelをビルド。' },
  { term: 'pip wheel <package>', description: '指定パッケージのwheelをビルド。' },
  { term: 'pip wheel -r', description: '要件ファイルのwheelをビルド。' },
  { term: 'pip wheel -w', description: 'wheel出力先を指定。', aliases: ['pip wheel --wheel-dir'] },

  // === キャッシュ ===
  { term: 'pip cache', description: 'pipキャッシュを管理する。' },
  { term: 'pip cache info', description: 'キャッシュの情報を表示。' },
  { term: 'pip cache list', description: 'キャッシュされたパッケージを表示。' },
  { term: 'pip cache dir', description: 'キャッシュディレクトリを表示。' },
  { term: 'pip cache purge', description: '全キャッシュを削除。' },
  { term: 'pip cache remove', description: '指定パッケージのキャッシュを削除。' },

  // === 設定 ===
  { term: 'pip config', description: 'pip設定を管理する。' },
  { term: 'pip config list', description: '現在の設定を表示。' },
  { term: 'pip config get', description: '指定した設定値を取得。' },
  { term: 'pip config set', description: '設定値を設定する。' },
  { term: 'pip config unset', description: '設定を削除する。' },
  { term: 'pip config edit', description: '設定ファイルを編集。' },
  { term: 'pip config debug', description: '設定のデバッグ情報を表示。' },

  // === その他 ===
  { term: 'pip check', description: '依存関係の整合性をチェック。' },
  { term: 'pip hash', description: 'パッケージファイルのハッシュを計算。' },
  { term: 'pip debug', description: 'pipのデバッグ情報を表示。' },
  { term: 'pip help', description: 'ヘルプを表示。' },
  { term: 'pip --version', description: 'pipのバージョンを表示。', aliases: ['pip -V'] },

  // === ファイル関連 ===
  { term: 'requirements.txt', description: '依存パッケージを記述するファイル。' },
  { term: 'constraints.txt', description: 'バージョン制約を記述するファイル。' },
  { term: 'setup.py', description: 'パッケージ設定ファイル（従来形式）。' },
  { term: 'setup.cfg', description: 'パッケージ設定ファイル（宣言的形式）。' },
  { term: 'pyproject.toml', description: 'PEP 518準拠のプロジェクト設定ファイル。' },
  { term: 'pip.conf', description: 'pip設定ファイル（Unix）。' },
  { term: 'pip.ini', description: 'pip設定ファイル（Windows）。' },
  { term: 'MANIFEST.in', description: 'ソース配布物に含めるファイルを指定。' },

  // === venv ===
  { term: 'venv', description: 'Python標準の仮想環境モジュール。' },
  { term: 'python -m venv', description: '仮想環境を作成する。' },
  { term: 'python -m venv <dir>', description: '指定ディレクトリに仮想環境を作成。' },
  { term: 'python -m venv --system-site-packages', description: 'システムパッケージにアクセス可能にする。' },
  { term: 'python -m venv --clear', description: '既存の仮想環境をクリアして再作成。' },
  { term: 'python -m venv --upgrade', description: 'Pythonバージョンを更新。' },
  { term: 'python -m venv --upgrade-deps', description: 'pipとsetuptoolsを更新。' },
  { term: 'python -m venv --without-pip', description: 'pipなしで仮想環境を作成。' },
  { term: 'source venv/bin/activate', description: '仮想環境を有効化（Unix）。' },
  { term: 'venv\\Scripts\\activate', description: '仮想環境を有効化（Windows）。' },
  { term: 'deactivate', description: '仮想環境を無効化。' },

  // === virtualenv ===
  { term: 'virtualenv', description: 'サードパーティの仮想環境ツール。venvより高機能。' },
  { term: 'virtualenv <dir>', description: '仮想環境を作成。' },
  { term: 'virtualenv --python', description: 'Pythonインタプリタを指定。', aliases: ['virtualenv -p'] },
  { term: 'virtualenv --system-site-packages', description: 'システムパッケージにアクセス可能にする。' },
  { term: 'virtualenv --clear', description: '既存の仮想環境をクリア。' },
  { term: 'virtualenv --no-pip', description: 'pipなしで作成。' },
  { term: 'virtualenv --no-setuptools', description: 'setuptoolsなしで作成。' },

  // === pipenv ===
  { term: 'pipenv', description: 'pip + virtualenvを統合したツール。PipfileとPipfile.lockを使用。' },
  { term: 'pipenv install', description: 'Pipfileに基づいてインストール。' },
  { term: 'pipenv install <package>', description: 'パッケージを追加してインストール。' },
  { term: 'pipenv install --dev', description: 'devパッケージとしてインストール。', aliases: ['pipenv install -d'] },
  { term: 'pipenv install -r', description: 'requirements.txtからインストール。' },
  { term: 'pipenv uninstall', description: 'パッケージをアンインストール。' },
  { term: 'pipenv update', description: 'パッケージを更新。' },
  { term: 'pipenv lock', description: 'Pipfile.lockを生成。' },
  { term: 'pipenv sync', description: 'Pipfile.lockに基づいてインストール。' },
  { term: 'pipenv shell', description: '仮想環境のシェルを開始。' },
  { term: 'pipenv run', description: '仮想環境でコマンドを実行。' },
  { term: 'pipenv graph', description: '依存グラフを表示。' },
  { term: 'pipenv check', description: 'セキュリティ脆弱性をチェック。' },
  { term: 'pipenv clean', description: '不要なパッケージを削除。' },
  { term: 'pipenv --venv', description: '仮想環境のパスを表示。' },
  { term: 'pipenv --where', description: 'プロジェクトのパスを表示。' },
  { term: 'pipenv --rm', description: '仮想環境を削除。' },
  { term: 'Pipfile', description: 'pipenvの依存定義ファイル。' },
  { term: 'Pipfile.lock', description: 'pipenvのロックファイル。' },

  // === poetry ===
  { term: 'poetry', description: 'Pythonの依存管理・パッケージングツール。pyproject.tomlを使用。' },
  { term: 'poetry init', description: 'pyproject.tomlを対話的に作成。' },
  { term: 'poetry new', description: '新しいプロジェクトを作成。' },
  { term: 'poetry install', description: '依存パッケージをインストール。' },
  { term: 'poetry install --no-dev', description: 'devパッケージを除いてインストール。' },
  { term: 'poetry install --only', description: '指定グループのみインストール。' },
  { term: 'poetry install --without', description: '指定グループを除いてインストール。' },
  { term: 'poetry install --with', description: '指定グループも含めてインストール。' },
  { term: 'poetry install --sync', description: 'ロックファイルと同期。' },
  { term: 'poetry add', description: 'パッケージを追加。' },
  { term: 'poetry add <package>', description: '指定パッケージを追加。' },
  { term: 'poetry add --group', description: '指定グループに追加。', aliases: ['poetry add -G'] },
  { term: 'poetry add --dev', description: 'devグループに追加。', aliases: ['poetry add -D'] },
  { term: 'poetry add --editable', description: '編集可能モードで追加。' },
  { term: 'poetry add --optional', description: 'オプショナルとして追加。' },
  { term: 'poetry remove', description: 'パッケージを削除。' },
  { term: 'poetry update', description: 'パッケージを更新。' },
  { term: 'poetry update --dry-run', description: '更新内容を確認（実行しない）。' },
  { term: 'poetry lock', description: 'poetry.lockを生成。' },
  { term: 'poetry lock --no-update', description: '更新せずにロックファイルを生成。' },
  { term: 'poetry show', description: 'パッケージ情報を表示。' },
  { term: 'poetry show --tree', description: '依存ツリーを表示。' },
  { term: 'poetry show --latest', description: '最新バージョンも表示。' },
  { term: 'poetry show --outdated', description: '更新可能なパッケージを表示。' },
  { term: 'poetry run', description: '仮想環境でコマンドを実行。' },
  { term: 'poetry shell', description: '仮想環境のシェルを開始。' },
  { term: 'poetry build', description: 'パッケージをビルド。' },
  { term: 'poetry build --format', description: 'ビルド形式を指定（wheel/sdist）。' },
  { term: 'poetry publish', description: 'PyPIに公開。' },
  { term: 'poetry publish --dry-run', description: '公開内容を確認（実行しない）。' },
  { term: 'poetry check', description: 'pyproject.tomlの整合性をチェック。' },
  { term: 'poetry search', description: 'パッケージを検索。' },
  { term: 'poetry export', description: 'requirements.txt形式で出力。' },
  { term: 'poetry export -f', description: '出力形式を指定。', aliases: ['poetry export --format'] },
  { term: 'poetry export --without-hashes', description: 'ハッシュなしで出力。' },
  { term: 'poetry config', description: 'poetry設定を管理。' },
  { term: 'poetry config --list', description: '設定一覧を表示。' },
  { term: 'poetry env', description: '仮想環境を管理。' },
  { term: 'poetry env info', description: '仮想環境の情報を表示。' },
  { term: 'poetry env list', description: '仮想環境一覧を表示。' },
  { term: 'poetry env use', description: '使用するPythonを指定。' },
  { term: 'poetry env remove', description: '仮想環境を削除。' },
  { term: 'poetry self', description: 'poetry自身を管理。' },
  { term: 'poetry self update', description: 'poetryを更新。' },
  { term: 'poetry.lock', description: 'poetryのロックファイル。' },

  // === uv ===
  { term: 'uv', description: 'Rustで書かれた高速なPythonパッケージマネージャー。' },
  { term: 'uv pip install', description: 'パッケージをインストール（pip互換）。' },
  { term: 'uv pip uninstall', description: 'パッケージをアンインストール。' },
  { term: 'uv pip freeze', description: 'インストール済みパッケージを出力。' },
  { term: 'uv pip list', description: 'インストール済みパッケージを表示。' },
  { term: 'uv pip show', description: 'パッケージ情報を表示。' },
  { term: 'uv pip compile', description: '要件をコンパイルしてロック。' },
  { term: 'uv pip sync', description: 'ロックファイルと同期。' },
  { term: 'uv venv', description: '仮想環境を作成。' },
  { term: 'uv cache', description: 'キャッシュを管理。' },
  { term: 'uv cache clean', description: 'キャッシュを削除。' },
  { term: 'uv self', description: 'uv自身を管理。' },
  { term: 'uv self update', description: 'uvを更新。' },

  // === 概念・用語 ===
  { term: 'PyPI', description: 'Python Package Index。Pythonパッケージの公式リポジトリ。' },
  { term: 'wheel', description: 'ビルド済みのPythonパッケージ形式（.whl）。' },
  { term: 'sdist', description: 'ソースディストリビューション。ソースコードのアーカイブ。' },
  { term: 'egg', description: '旧式のPythonパッケージ形式（非推奨）。' },
  { term: 'virtual environment', description: 'プロジェクト毎に独立したPython環境。', aliases: ['仮想環境'] },
  { term: 'site-packages', description: 'サードパーティパッケージのインストール先。' },
  { term: 'editable install', description: 'ソースコードを直接参照するインストール（開発用）。', aliases: ['開発モード'] },
  { term: 'extras', description: 'オプショナルな追加依存（package[extra]）。' },
  { term: 'PEP 517', description: 'ビルドシステム仕様。pyproject.tomlでビルドバックエンドを指定。' },
  { term: 'PEP 518', description: 'pyproject.tomlによるビルド依存の指定。' },
  { term: 'PEP 621', description: 'pyproject.tomlでプロジェクトメタデータを指定。' },
  { term: 'PEP 660', description: '編集可能インストールの標準化。' },
];
