// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: observabilitySre (2/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: 'インシデント対応フロー', aliases: ['incident response flow'], description: 'インシデント発生から復旧・報告までのフローです。初動対応の品質を安定させます。' },
  { term: 'データ保管期間定義', aliases: ['retention period definition'], description: 'データやログをどれだけの期間保管するかの定義書です。法規制や監査要件との整合が必要です。' },
  { term: 'データ廃棄ルール', aliases: ['disposal rules'], description: '不要なデータをいつどのように削除するかのルールです。削除漏れやデータ残留のリスクを低減します。' },
  { term: '運用受け入れ基準', aliases: ['operations acceptance criteria'], description: '開発チームから運用チームへ引き渡す条件を定めたものです。運用開始後の混乱を防ぎます。' },
  { term: '監視業務', aliases: ['monitoring operations'], description: 'システムやインフラの状態を継続的に確認する業務。' },
  { term: '構成管理', aliases: ['configuration management'], description: 'システムを構成する要素や設定を管理すること。' },
  { term: 'Zabbix', aliases: ['zabbix'], description: 'サーバやネットワーク機器の稼働監視に利用される監視ソフトウェア。' },
  { term: 'Arcserve UDP', aliases: ['arcserve udp'], description: 'バックアップと復旧を統合的に管理するための製品。' },
  { term: 'SiteScope', aliases: ['sitescope'], description: 'エージェントレス方式でサーバやサービスを監視する運用ツール。' },
  { term: 'Datadog', aliases: ['datadog'], description: '監視、ログ、APMを統合して扱える運用監視サービス。' },
  { term: '死活監視', description: 'システムが生きているか、応答するかを確認する監視。' },
  { term: 'メンテナンス', description: '更新、保守、修正などの維持作業。' },
  { term: 'cron', description: '定期実行ジョブを設定する仕組み。' },
  { term: 'オブザーバビリティ', description: 'システムの外部出力（メトリクス・ログ・トレース）から内部状態を推測できる性質。可観測性とも呼ぶ。' },
  { term: 'ジョブ管理', aliases: ['job management', 'ジョブスケジューラ'], description: 'バッチ処理などの定期実行ジョブをスケジュール管理・監視する仕組み。ジョブの実行順序や依存関係を定義し、成功・失敗を監視する。JP1やHINEOSが有名なツール。' },
  { term: 'バッチスケジューラ', aliases: ['batch scheduler', 'ジョブスケジューラー'], description: 'バッチ処理を自動的に指定した時刻や条件で実行するソフトウェア。「毎日深夜2時に請求データを集計する」などの定期処理を管理する。' },
  { term: '運用手順書', aliases: ['operations manual', '操作手順書', '手順書'], description: 'システムの日常的な運用・監視・障害対応の手順をまとめたドキュメント。誰でも同じ手順で作業できるように具体的な操作手順を記載する。' },
  { term: 'パッチ適用', aliases: ['patch application', 'セキュリティパッチ', 'patch'], description: 'ソフトウェアのバグ修正やセキュリティ対応のための更新プログラム（パッチ）を適用すること。OSやミドルウェアに定期的に適用することでセキュリティを維持する。' },
  { term: '定期メンテナンス', aliases: ['scheduled maintenance', '定期保守'], description: 'システムを安定稼働させるために定期的に行う保守作業。ログ削除、データバックアップ確認、OSアップデート適用、性能確認などが含まれる。' },
  { term: 'top', description: 'リアルタイムでシステムのCPU・メモリ使用状況とプロセス一覧を表示するインタラクティブなコマンド。システムの負荷監視に広く使用される。' },
  { term: 'htop', description: 'topの高機能版。カラー表示、マウス操作、ツリー表示などに対応したインタラクティブなプロセスビューア。' },
  { term: 'journalctl', description: 'systemdのジャーナルログを閲覧するコマンド。-u でユニット指定、-fでフォロー、--sinceで時間指定など柔軟なログ検索が可能。' },
  { term: 'rsyslog', description: 'Linuxシステムで広く使用される高機能ログデーモン。syslogプロトコルをサポートしフィルタリング、リモート転送、多様な出力形式を提供する。' },
  { term: 'journald', aliases: ['systemd-journald'], description: 'systemdが提供するシステムジャーナルデーモン。バイナリ形式でログを収集・管理し、journalctlコマンドで検索・フィルタリングができる。' },
  { term: '/var/log', description: 'Linuxシステムのログファイルが格納される標準ディレクトリ。/var/log/messages、/var/log/syslog、/var/log/secureなど多数のログファイルが置かれる。' },
  { term: 'logrotate', description: 'ログファイルの自動ローテーション（定期的な圧縮・保管・削除）を管理するツール。/etc/logrotate.confと/etc/logrotate.d/で設定する。' },
  { term: 'auditd', aliases: ['linux audit daemon'], description: 'Linuxのカーネル監査サブシステムのデーモン。ファイルアクセス、システムコール、ユーザー認証などのセキュリティイベントを記録する。' },
  { term: 'auditctl', description: 'Linux監査システムのルールを管理するコマンド。監視するシステムコールやファイルアクセスのルールを追加・削除・確認できる。' },
  { term: 'ausearch', description: 'Linux監査ログ（/var/log/audit/audit.log）を検索・フィルタリングするコマンド。イベントタイプ、ユーザー、時刻などで検索できる。' },
  { term: 'aureport', description: 'Linux監査ログから統計レポート（ログイン試行、特権使用、ファイルアクセスなど）を生成するコマンド。' },
  { term: 'sar', aliases: ['system activity reporter'], description: 'System Activity Reporterの略。CPU、メモリ、I/O、ネットワークなどのシステムリソース使用状況を収集・表示するコマンド。sysstatパッケージに含まれる。' },
  { term: 'vmstat', description: '仮想メモリ、プロセス、I/O、CPU統計を表示するコマンド。メモリ不足やI/Oボトルネックの診断に使用する。' },
  { term: 'iostat', description: 'CPUとデバイスI/Oの統計情報を表示するコマンド。ディスクのスループット、待機時間、使用率を監視してI/Oボトルネックを特定する。' },
  { term: 'mpstat', description: 'マルチプロセッサシステムの各CPUコアの統計情報を表示するコマンド。CPUの使用率、アイドル率、割り込み処理時間などを確認できる。' },
  { term: 'uptime', description: 'システムの稼働時間、ログインユーザー数、ロードアベレージ（1/5/15分）を表示するコマンド。システムの負荷状況の素早い把握に使用する。' },
  { term: 'w コマンド', aliases: ['w'], description: '現在ログイン中のユーザー一覧と各ユーザーが実行中のプロセス、ログイン時刻、アイドル時間を表示するコマンド。' },
  { term: 'last', description: '/var/log/wtmpを参照して過去のログイン・ログアウト履歴、システム再起動履歴を表示するコマンド。不正アクセスの調査に有用。' },
  { term: 'faillog', description: 'ユーザーのログイン失敗回数と最終失敗情報を表示・管理するコマンド。ブルートフォース攻撃の検出やアカウントロックポリシーの管理に使用する。' },
  { term: 'オペミス', aliases: ['オペレーションミス'], description: 'オペレーションミスの略。システム運用や操作における人為的なミス。rmなど取り消し不可のコマンドの誤実行が典型例。' },
  { term: '精神的ダメージ', description: '業務上の失敗やインシデント対応によって受ける心理的なショックや疲弊。深刻なオペミス後や長時間障害対応後に生じやすく、チームとしてのサポートが重要。' },
  { term: '俗言', description: 'エンジニアや運用者の間で非公式に使われる略語やスラング。「オペミス」「塩漬け」「爆速」など現場感を持つ表現が多い。' },
  { term: '危険な操作', description: '実行すると取り消せない可能性があるシステム操作。`rm -rf`や本番DBへの直接書き込みなどが該当し、実行前の確認や二重チェックが必須。' },
  { term: '一呼吸', description: '危険な操作や重要な判断を行う前に、意図的に間を置いて確認するという運用上の習慣。焦りによるオペミスを防ぐための心構えを指す。' },
  { term: '運用哲学', description: 'システム運用で大切にすべき考え方や教訓の体系。「危険な操作には一呼吸置く」「権限は最小限に」など現場で培われた知恵をまとめたもの。' },
  { term: '契約書案文', aliases: ['contract draft text', '案文', '草案'], description: '契約書に記載する文面や条項の案。正式な契約書として製本・押印する前に双方で内容を確認・修正するための原稿。交渉や確認・調整のプロセスで使われ、案文合意が得られた後に本紙として作成する。' },
  { term: '契約書案文登録', aliases: ['contract draft registration'], description: '契約書の標準文面や条項を登録・整理する機能または業務。よく使われる条項のテンプレートを蓄積して再利用性を高め、契約書作成の効率化を図る。案文ライブラリとして管理される。' },
  { term: '契約書出力', aliases: ['contract output', 'contract print'], description: '案文合意が得られた契約書を正式な文書として出力する処理。印刷や PDF 生成を含み、製本・押印のための原本を作成する。出力後は押印申請へ進むフローが多い。' },
  { term: '契約書製本', aliases: ['contract binding'], description: '出力した契約書をひとまとまりの書類として整える作業。ページの順番を確認し、割印や契印を押せるよう整理する。製本テープや綴じ方の規則は企業によって異なる。' },
  { term: '契約書加工', aliases: ['contract customization', 'contract modification'], description: '標準様式では対応できない契約書を個別に修正する作業。相手先の指定書式への変換、特殊条項の追加、非定型対応などを含む。加工が必要な案件は通常の承認フローとは別に管理されることが多い。' },
  { term: '契約一覧', aliases: ['contract list', 'contract index'], description: '契約情報を一覧で確認するための画面または資料。締結済・進行中・期限切れなどのステータスで絞り込み、担当者・相手先・期間などで検索できる。契約管理システムの主要画面のひとつ。' },
  { term: '契約相手先一覧', aliases: ['contract counterparty list'], description: '契約の相手先を一覧で確認するための画面または資料。相手先ごとの契約数・契約期間・担当者などを把握し、取引先管理に活用する。' },
  { term: '交渉', aliases: ['negotiation'], description: '条件や内容について相手と調整すること。契約では価格・納期・条項・責任範囲などを双方の利益が一致するよう話し合う。口頭合意・条件合意・案文合意という段階を経て締結へ進む。' },
  { term: '口頭合意', aliases: ['verbal agreement', 'oral agreement'], description: '書面化前に、条件について口頭で合意が成立した状態。法的拘束力は書面合意より弱いが、交渉の進捗を示す重要な節目。後から書面に落とす際に内容の確認・調整が必要になることがある。' },
  { term: '条件合意', aliases: ['condition agreement', 'terms agreement'], description: '主要な条件（価格・期間・責任範囲など）について関係者間で概ね合意した状態。口頭合意の次のステップで、この段階を経て案文作成・案文合意へ進む。' },
  { term: '案文合意', aliases: ['draft agreement', 'text agreement'], description: '文書の文面や条項について合意した状態。条件合意の後に契約書案文を作成し、双方でレビューして内容に同意した段階。案文合意後は正式な出力・押印フローに進む。' },
  { term: '確認・調整', aliases: ['confirmation and adjustment', 'review and adjustment'], description: '内容を確認し、必要な修正やすり合わせを行うこと。契約交渉における標準的なプロセスステップで、案文の読み合わせや誤字・条件の食い違いを解消する活動を指す。' },
  { term: '提示', aliases: ['presentation', 'offer', 'proposal'], description: '条件や資料を相手に示すこと。契約交渉では価格・条件・案文などを相手先に提示し、相手の反応を待つ。提示後は相手からの回答・交渉を経て合意へ進む。' },
  { term: '送付', aliases: ['sending', 'delivery', 'dispatch'], description: '文書や資料を相手へ送ること。郵送・メール・システム経由のファイル共有などを含む。送付した事実と日時を記録しておくことが証跡管理上重要。' },
  { term: '受領', aliases: ['receipt', 'receiving'], description: '文書や資料を受け取ること。受領日時・担当者を記録し、受領書を発行することで送付側の証跡にもなる。契約書の受け取りは締結プロセスの重要な工程。' },
  { term: '回収', aliases: ['document retrieval'], description: '相手へ渡した書類を受け戻すこと。押印済みの契約書を相手先から返送してもらう場面が典型例。回収期限を設定し、未回収を管理することが重要。' },
  { term: '提出', aliases: ['submission', 'filing'], description: '必要書類を関係先へ出すこと。申請書・報告書・契約書などを所定の窓口や担当部門へ届ける行為。提出期限・提出先・提出方法を確認して漏れなく実施する。' },
  { term: '本紙', aliases: ['original document', 'principal copy'], description: '控え・写し・案ではなく、文書本体を指す表現。契約書の文脈では、最終的に押印・交換する正式な書類を「本紙」と呼び、写しや案とは区別する。' },
  { term: '定型', aliases: ['standard form', 'template form', 'standard format'], description: 'あらかじめ定められた標準形式。定型契約書・定型フォームは内容が統一されており、変更なく使用できる。作成コストが低く承認も容易だが、特殊な条件には対応できない。' },
  { term: '非定型', aliases: ['non-standard form', 'custom format', 'irregular format'], description: '標準形式では対応できず、個別対応が必要な形式。相手先指定書式・特殊条項・複雑な構成などが理由となり、通常より時間・コスト・確認工数が多くかかる。' },
  { term: '申請書', aliases: ['application form', 'request form'], description: '登録・承認・変更などを依頼するための文書。押印申請書・変更申請書・発注申請書など業務種別ごとに書式が用意される。記入後は承認依頼フローに沿って決裁者へ回付する。' },
  { term: '承認依頼', aliases: ['approval request', 'approval workflow request'], description: '上位者や関係部門に承認を求めること。電子承認システムまたは紙の申請書を通じて承認者へ依頼し、承認後に次の業務ステップへ進める。期限内に承認が得られない場合はエスカレーションが必要。' },
  { term: '電子承認', aliases: ['electronic approval', 'digital approval', 'e-approval'], description: 'システム上で承認を行うこと。紙の押印・回付に代わり、ワークフローシステムや契約管理システム上で承認者が操作して承認を完結する。証跡が自動記録され、承認状況のリアルタイム確認が可能。' },
  { term: '請求書作成', aliases: ['invoice creation', 'invoice generation'], description: '請求内容に基づいて請求書を作成すること。取引金額・品目・振込先・支払期日などを記載し、会計システムや請求管理システムで生成することが多い。作成後は承認を経て相手先に送付する。' },
  { term: '請求書出力', aliases: ['invoice output', 'invoice print'], description: '請求書を文書として出力すること。PDF 形式での電子出力や印刷対応を含む。出力した請求書は送付や保管に使われる。' },
  { term: '請求書送付', aliases: ['invoice sending', 'invoice delivery'], description: '作成した請求書を相手へ送ること。郵送・メール・電子請求システム経由などの方法がある。送付日時・送付先・送付方法を記録し、未入金の場合の督促管理にも活用する。' },
  { term: '入出金伝票', aliases: ['payment slip', 'receipt slip', 'cash voucher'], description: '入金や支払の内容を記録するための伝票。入金伝票と出金伝票を合わせた総称。金額・日付・取引先・勘定科目などを記載し、会計処理の基礎資料となる。' },
  { term: '入金伝票作成', aliases: ['receipt voucher creation', 'payment receipt creation'], description: '入金内容を記録するための伝票を作成すること。入金確認後に金額・日付・取引先・勘定科目を記載した入金伝票を起票し、会計システムへ登録する。' },
  { term: '入出金伝票一覧', aliases: ['payment voucher list', 'cash voucher list'], description: '入出金伝票を一覧で確認するための画面または資料。期間・取引先・金額などで絞り込み、入出金の状況を把握・確認するために使う。' },
  { term: '相手先', aliases: ['counterparty', 'business partner', 'trading partner'], description: '契約や取引の相手となる個人、法人、または組織。顧客・仕入先・委託先などを含む広い概念で、契約管理システムでは相手先マスタとして管理する。' },
  { term: '新規相手先', aliases: ['new counterparty', 'new business partner'], description: 'まだ登録されていない新しい相手先。新規相手先との取引開始時は、相手先情報の収集・与信確認・マスタ登録が必要になる。' },
  { term: '相手先情報', aliases: ['counterparty information', 'partner information'], description: '相手先に関する基本情報。社名・住所・連絡先・担当者・振込先・与信限度額などを含む。契約管理・請求管理・与信管理で参照される基礎データ。' },
  { term: '相手先登録', aliases: ['counterparty registration', 'partner registration'], description: '相手先に関する情報を新たに登録すること。所定の申請書または相手先登録画面から情報を入力し、審査・承認を経てマスタに追加する。登録後は各種業務で相手先を参照できる。' },
  { term: '店舗', aliases: ['store', 'branch', 'location'], description: '【運用】商品の販売やサービス提供を行う場所。本社・支社・工場などの拠点とは区別して、顧客対応の場として管理される。契約管理では店舗ごとに担当・契約・請求を紐づけることが多い。 【OCI APEX】処理後の遷移先を決める定義。' },
  { term: '新規店舗', aliases: ['new store', 'new branch', 'new location'], description: 'まだ登録されていない新しい拠点。新規店舗の開設時は、店舗情報の登録・担当者割り当て・関連する契約の紐づけが必要になる。' },
  { term: '店舗情報', aliases: ['store information', 'branch information'], description: '店舗に関する基本情報。店舗名・住所・電話番号・担当者・営業時間などを含む。契約管理・請求管理・進捗管理で参照される。' },
  { term: '店舗登録', aliases: ['store registration', 'branch registration'], description: '店舗に関する情報を新たに登録すること。所定の申請書または登録画面から情報を入力し、審査を経てマスタに追加する。登録後は各種業務で店舗を参照できる。' },
  { term: '添付資料', aliases: ['attachment', 'supplementary material', 'enclosure'], description: '文書に添付する補足資料。契約書に添付する仕様書・見積書・図面など、本文を補完する資料全般を指す。添付資料は契約の一部を構成することがある。' },
  { term: '添付ファイル', aliases: ['attached file', 'email attachment', 'file attachment'], description: '文書や申請に添付する電子ファイル。メール送付・システムアップロードなどの形式で添付し、PDF・Excel・Word・画像などの形式が多い。ファイル名・バージョン・容量の管理が必要。' },
  { term: '図面一式', aliases: ['complete drawings', 'drawing set', 'blueprint set'], description: '図面類をまとめた資料一式。建設・設備・工事関連の契約では平面図・立面図・配管図などをまとめて添付し、工事範囲や仕様を明確にするために使う。' },
  { term: '工事区分表', aliases: ['construction division table', 'work scope table'], description: '工事の範囲、担当区分、費用負担区分などを整理した表。建設・リノベーション・設備工事の契約で使われ、発注者・施工者・テナントそれぞれの役割と負担を明確にする。' },
  { term: '経費一覧表', aliases: ['expense list', 'cost summary'], description: '費用項目や内容を一覧で整理した表。見積・精算・予算管理の文脈で使われ、項目名・単価・数量・金額を記載する。契約添付資料や申請書の付属資料として提出されることが多い。' },
  { term: '規則抜粋', aliases: ['rule excerpt', 'regulation extract'], description: '規則や規程のうち、必要な部分だけを抜き出して示した資料。契約の根拠となる社内規程・法令・業界ルールの関連箇所を提示する際に使い、全文でなく関係条文のみを共有する。' },
  { term: '謄本', aliases: ['certified copy', 'official transcript', '登記謄本'], description: '登記や登録の内容を証明するための書類。法人登記簿謄本（登記事項証明書）は法人との契約締結時に相手先の実在確認・代表者確認のために必要とされることが多い。' },
  { term: '印鑑証明', aliases: ['seal certificate', 'seal registration certificate'], description: '印鑑登録された印影を証明する書類。法人との正式な契約締結時に、押印された印鑑が登録印であることを証明するために添付が求められる。市区町村や法務局が発行する。' },
  { term: '押印申請', aliases: ['seal approval request', 'stamping request'], description: '文書に押印するための社内申請。代表印・角印・社印など重要な印鑑の使用は事前申請が必要な企業が多く、申請書に押印する文書・目的・相手先を記載して承認を得る。' },
  { term: '押印', aliases: ['stamping', 'sealing', 'signing with seal'], description: '文書に印を付すこと。契約書・申請書・請求書などの正式な文書に会社の印鑑を押すことで、内容への同意や権限の行使を示す。電子化が進む中でも法的効力の観点から押印が必要な場面は多い。' },
  { term: '印影印刷', aliases: ['seal impression printing', 'stamp image printing'], description: '印影を文書上に印字すること。電子契約や PDF 出力の際に、登録された印影画像を文書に埋め込む処理。電子印鑑とも呼ばれ、実印による押印の代替として使われることがある。' },
  { term: '押印済書類', aliases: ['stamped documents', 'sealed documents'], description: '押印が完了した文書。契約書・申請書など、必要な押印が全て終わった状態の書類を指す。押印済書類は原本として保管され、コピーは写しとして管理される。' },
  { term: 'PDF化', aliases: ['pdf化', 'pdf conversion', 'save as pdf'], description: '文書、帳票、画像などを PDF 形式に変換すること。契約書・請求書・申請書などを電子ファイルとして送付・保管するために行う。改ざん防止・閲覧の統一性・長期保存の観点から多くの業務で標準的に行われる。' },
  { term: '文書保管', aliases: ['document storage', 'document archiving', 'document retention'], description: '文書を保存・管理すること。法定保存期間・社内規程に基づき、電子ファイルまたは紙で文書を保存・管理する業務。検索性・アクセス管理・廃棄ルールも含む文書ライフサイクル管理の核心。' },
  { term: '文書登録', aliases: ['document registration', 'document filing'], description: '文書を所定の保管先や管理システムへ登録すること。押印済み契約書・申請書・承認書などを文書管理システムへ登録し、検索・参照できる状態にする。文書番号・分類・保存期限も合わせて設定する。' },
  { term: '登録期限', aliases: ['registration deadline', 'filing deadline'], description: '対象となる情報や文書を登録すべき期限。契約書・申請書・伝票などの登録期限を守ることで、業務の遅延や法的リスクを回避する。期限超過は督促・エスカレーション対象となる。' },
  { term: 'ステータス', aliases: ['status'], description: '対象の進捗や状態を表す管理項目。契約管理では「入力中」「条件提示」「条件合意」「案文合意」「決裁済」「締結済」などのステータスで各契約の進行状況を可視化する。ステータス管理により担当者全員が現状を共有できる。' },
  { term: '入力中', aliases: ['in progress', 'editing', 'draft'], description: '作成や編集の途中にある状態を示すステータス。契約書や申請書の入力が始まっているが、まだ提出・承認依頼には至っていない段階。担当者が内容を確認・修正している最中。' },
  { term: '条件提示', aliases: ['terms presented', 'offer made'], description: '条件を相手へ示した状態を示すステータス。自社が価格・条件などを相手先に提示し、相手からの回答を待っている段階。相手先の反応次第で条件合意または再交渉に進む。' },
  { term: '確定', aliases: ['confirmed', 'finalized', 'fixed'], description: '内容が固まった状態。交渉・確認・調整のプロセスを経て変更不要と判断された段階。確定後は押印申請・出力・送付などの次工程に進む。' },
  { term: '決裁済', aliases: ['approved', 'authorized', 'sanctioned'], description: '承認が完了した状態を示すステータス。決裁権者による最終承認が得られ、次の業務ステップ（押印・送付・締結など）に進める状態。承認日時・承認者が記録される。' },
  { term: '締結済', aliases: ['concluded', 'executed', 'signed'], description: '合意と必要な手続き（押印・署名・交換など）が完了し、契約が正式に成立した状態を示すステータス。締結日・相手先・担当者が記録され、以後は契約の履行管理フェーズに移行する。' },
  { term: 'ステータス更新', aliases: ['status update', 'state change'], description: '状態を次の段階へ変更すること。契約や申請の進行に合わせて担当者がステータスを更新し、関係者全員が最新の状況を把握できるようにする。更新時に通知・メール送信が行われる場合もある。' },
  { term: 'ステータス確認', aliases: ['status verification'], description: '現在の状態を確認すること。契約・申請・業務の現在のステータスを一覧や詳細画面で確認する行為。月例会議や日次チェックで進捗停滞案件を見つけるためにも行う。' },
  { term: '月例営業会議', aliases: ['monthly sales meeting', 'monthly business review'], description: '毎月定期的に実施する営業進捗確認の会議。契約・商談・パイプラインのステータスを共有し、滞留案件の対策や目標達成状況を議論する。進捗管理表・ヒアリング状況シートを資料として使うことが多い。' },
  { term: 'ヒアリング状況シート', aliases: ['hearing status sheet', 'interview tracking sheet'], description: 'ヒアリング結果や進捗状況を整理するための資料。対象相手先・ヒアリング日・担当者・確認項目・回答内容・次のアクションなどを記録し、関係者間で情報を共有する。' },
  { term: '対象相手先洗い出し', aliases: ['target counterparty extraction', 'candidate list identification'], description: '対象となる候補先を抽出し、整理すること。新規契約の締結や更新対応の際に、条件に合う相手先を一覧化・優先順位付けするプロセス。ヒアリング状況シートや進捗管理表の作成前提となる。' },
  { term: '変更通知', aliases: ['change notice', 'change notification'], description: '内容や条件の変更を関係者へ知らせる文書または連絡。契約条件・担当者・住所・価格などの変更を公式に通知する際に使われ、変更内容・有効日・署名を含むことが多い。' },
  { term: '確定通知', aliases: ['confirmation notice', 'finalization notice'], description: '内容や日程などが確定したことを関係者へ知らせる文書または連絡。交渉・調整の結果として合意内容が固まったことを公式に伝える。契約締結後の「締結確認通知」も確定通知のひとつ。' },
  { term: '通知書', aliases: ['notice', 'notification letter', 'official notice'], description: '一定の事項を関係者へ正式に知らせるための文書。変更通知書・督促通知書・解約通知書などがあり、送付日時・通知内容・通知先を記録する。法的効力を持つ場合は内容証明郵便で送ることもある。' },
  { term: '案内文', aliases: ['guidance letter', 'introductory text', 'notice letter'], description: '連絡事項や説明事項を伝えるための文書。正式な通知書よりも柔らかいトーンで、手続きの説明・スケジールのお知らせ・お礼・依頼などを記載する。メール本文・FAX・同封レターとして使われることが多い。' },
  { term: '一括送付', aliases: ['batch sending', 'bulk delivery'], description: '複数の対象へまとめて送付する運用。同じ文書を多数の相手先へ同時に送る場合や、複数の書類を一度にまとめて送る場合に使う。システムの一括送付機能を活用することで作業効率を高める。' },
  { term: '一括対応', aliases: ['bulk handling', 'bulk operation'], description: '個別ではなくまとめて処理する運用。複数の申請・登録・更新を一度に行うことで作業効率を高める。一括対応は個々の件数が多い更新業務や定期対応で特に有効。' },
  { term: '異動登録', aliases: ['transfer registration', 'change registration'], description: '変更内容を記録・反映すること。担当者の異動・部署変更・権限変更などをシステムに登録し、業務の継続性を確保する。異動発生時は速やかに登録して引継ぎを完了させる必要がある。' },
  { term: '運営引継ぎ', aliases: ['operational handover', 'operations transfer'], description: '業務運営に必要な情報や役割を引き継ぐこと。担当者交代・組織変更・プロジェクト移管の際に、業務内容・関係者・注意点・進行中の案件を次の担当者へ伝える。引継ぎ資料の整備と引継ぎ会の実施が重要。' },
  { term: '引継ぎ会', aliases: ['handover meeting', 'transition meeting'], description: '引継ぎ内容を共有・確認するための会議。前任者・後任者・関係者が集まり、業務の概要・進行中の案件・注意事項・連絡先などを確認する。引継ぎ会の内容を議事録として残すことが望ましい。' },
  { term: '手交', aliases: ['direct delivery', 'personal delivery', 'hand delivery'], description: '文書や物品を相手へ直接手渡しすること。郵送・メールとは異なり、担当者が相手先へ直接持参して渡す方法。重要な契約書・機密文書・押印済書類の受け渡しに使われ、受領の確実性を確保できる。' },
  { term: 'ピーク時', description: '利用量や負荷が最も高くなる時間帯や状態です。' },
  { term: '業務継続可能', description: '障害や負荷があっても業務を続けられる状態です。' },
  { term: '止まりにくさ', description: '障害や負荷があっても停止しにくい性質です。' },
  { term: '99.9%', description: '可用性や成功率の目標値として使われる三九の水準です。' },
  { term: '99.99%', description: '可用性や成功率の目標値として使われる四九の水準です。' },
  { term: '稼働率', description: '全時間のうちサービスが正常に使えた割合です。' },
  { term: '負荷増加', description: 'アクセス量や処理量が増えてシステム負荷が高まることです。' },
  { term: '異常の原因', description: '障害や不具合を引き起こした直接または根本の要因です。' },
  { term: '障害解析', description: '障害の発生条件や原因を調べて特定する作業です。' },
  { term: '非機能', description: '性能や可用性や運用性など機能以外の要求領域です。' },
  { term: '月間稼働率', description: '1か月のうちサービスが利用可能だった割合です。' },
  { term: '継続運転可能', description: '長時間停止せず運用を続けられる状態です。' },
  { term: '管理者機能', description: '管理者だけが使える設定や運用向けの機能です。' },
  { term: '障害調査', description: '障害の再現条件や影響範囲や原因を調べる活動です。' },
  { term: '障害時', description: 'システム障害やサービス停止などの異常が発生している場面を指す表現です。' },
  { term: '原因追跡不能', description: 'ログや証跡が不足していて、障害や不具合の原因をたどって特定できない状態です。' },
  { term: 'ファイル数', description: '対象範囲に含まれるソースコードや設定ファイルの総数です。' },
  { term: 'クラス行数', description: 'あるクラスの実装が何行で構成されているかを表す規模指標です。' },
  { term: 'DI数', aliases: ['di数'], description: '依存性注入で外部から渡している依存先の数や注入箇所の数です。' },
  { term: 'ログ出力箇所', description: 'アプリケーション内でログを書き出している場所や文の数です。' },
  { term: '本番', description: '実際の利用者が使う稼働中の環境やサービスを指します。' },
  { term: 'DEBUG', aliases: ['debug'], description: '詳細な調査用情報を出すためのデバッグ向けログレベルや設定値です。' },
  { term: 'パラメータダンプ', description: '受け取った引数や入力値を、そのままログや画面へ出力することです。' },
  { term: 'DEBUG出力', aliases: ['debug出力'], description: 'デバッグ目的でのみ出す詳細なログやコンソール出力です。' },
  { term: 'ボディ出力', description: 'リクエストやレスポンスの本文全体をログや標準出力へ書き出すことです。' },
  { term: 'トラブル削減', description: '障害、誤入力、運用ミス、問い合わせ増加などの問題を減らすことです。' },
  { term: 'monitor', aliases: ['モニタリング'], description: 'システムの稼働状況やパフォーマンスを継続的に観測し、異常を検知する仕組みです。' },
];
