// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: gcpServices (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // google-cloud (66)
  { term: 'Google Cloud', aliases: ['google cloud'], description: 'Googleのクラウドサービス群の総称です。' },
  { term: 'Google Cloud Project', aliases: ['google cloud project'], description: 'Google Cloud利用の基本単位です。' },
  { term: 'Folder', aliases: ['folder'], description: '複数プロジェクトをまとめて管理する階層です。' },
  { term: 'Organization', aliases: ['organization'], description: '企業や組織単位でGoogle Cloudを束ねる最上位階層です。' },
  { term: 'Virtual Private Cloud', aliases: ['virtual private cloud'], description: 'Google Cloudの論理ネットワークです。略してVPCと呼ばれます。' },
  { term: 'Subnet in Google Cloud', aliases: ['subnet in google cloud'], description: 'VPC内のネットワーク分割単位です。' },
  { term: 'Firewall Rules', aliases: ['firewall rules'], description: '通信の許可、拒否を制御するルールです。' },
  { term: 'Cloud Router', aliases: ['cloud router'], description: '動的ルーティングを支援するネットワークサービスです。' },
  { term: 'Cloud NAT', aliases: ['cloud nat'], description: '内部資源の外向き通信を支援するNATサービスです。' },
  { term: 'Cloud DNS', aliases: ['cloud dns'], description: 'Google CloudのDNSサービスです。' },
  { term: 'Cloud Interconnect', aliases: ['cloud interconnect'], description: 'Google Cloudとオンプレミスを専用線で接続するサービスです。' },
  { term: 'Cloud Load Balancing', aliases: ['cloud load balancing'], description: 'Google Cloudの負荷分散サービスです。' },
  { term: 'Cloud Armor', aliases: ['cloud armor'], description: 'Webアプリケーション保護やDDoS対策に使うサービスです。' },
  { term: 'Compute Engine', aliases: ['compute engine'], description: '仮想マシンを提供するサービスです。' },
  { term: 'Managed Instance Group', aliases: ['managed instance group'], description: '複数VMをまとめて運用するための仕組みです。' },
  { term: 'Persistent Disk', aliases: ['persistent disk'], description: 'Compute Engine向けの永続ディスクです。' },
  { term: 'Cloud Storage', aliases: ['cloud storage'], description: 'Google Cloudのオブジェクトストレージです。' },
  { term: 'Filestore', aliases: ['filestore'], description: 'マネージドファイルストレージサービスです。' },
  { term: 'Cloud Run', aliases: ['cloud run'], description: 'フルマネージドでコンテナアプリを実行するサービスです。' },
  { term: 'App Engine', aliases: ['app engine'], description: 'Google Cloudのアプリケーション実行サービスです。' },
  { term: 'Google Kubernetes Engine', aliases: ['google kubernetes engine'], description: 'Google CloudのマネージドKubernetesサービスです。略してGKEと呼ばれます。' },
  { term: 'GKE', aliases: ['gke'], description: 'Google Kubernetes Engineの略称です。' },
  { term: 'Artifact Registry', aliases: ['artifact registry'], description: 'コンテナイメージや成果物を保存するサービスです。' },
  { term: 'Cloud Build', aliases: ['cloud build'], description: 'ビルドと継続的インテグレーションを支援するサービスです。' },
  { term: 'Cloud Deploy', aliases: ['cloud deploy'], description: '継続的デリバリーを支援するサービスです。' },
  { term: 'Cloud Functions', aliases: ['cloud functions'], description: 'イベント駆動でコードを実行するサーバーレスサービスです。' },
  { term: 'Cloud SQL', aliases: ['cloud sql'], description: 'マネージドリレーショナルデータベースサービスです。' },
  { term: 'Firestore', aliases: ['firestore'], description: 'モバイルやWeb向けのNoSQLドキュメントデータベースです。' },
  { term: 'Bigtable', aliases: ['bigtable'], description: '大規模で低遅延なNoSQLデータベースです。' },
  { term: 'Spanner', aliases: ['spanner'], description: '水平分散可能なリレーショナルデータベースサービスです。' },
  { term: 'BigQuery', aliases: ['bigquery'], description: '分析向けのクラウドデータウェアハウスです。' },
  { term: 'Dataflow', aliases: ['dataflow'], description: 'ストリーム処理やバッチ処理を行うサービスです。' },
  { term: 'Dataproc', aliases: ['dataproc'], description: 'HadoopやSpark系の処理を支援するサービスです。' },
  { term: 'Pub/Sub', aliases: ['pub/sub'], description: '非同期メッセージングサービスです。' },
  { term: 'Cloud Tasks', aliases: ['cloud tasks'], description: '非同期タスク実行を管理するサービスです。' },
  { term: 'Workflows', aliases: ['workflows'], description: '複数サービス処理をつなぐワークフローサービスです。' },
  { term: 'Eventarc', aliases: ['eventarc'], description: 'イベント駆動連携を支援するサービスです。' },
  { term: 'Identity and Access Management', aliases: ['identity and access management'], description: 'Google Cloudの認証、権限管理基盤です。略してIAMと呼ばれます。' },
  { term: 'Service Account', aliases: ['service account'], description: 'アプリケーションやサービスが使う認証主体です。' },
  { term: 'Cloud KMS', aliases: ['cloud kms'], description: '暗号鍵を管理するサービスです。' },
  { term: 'Cloud Logging', aliases: ['cloud logging'], description: '中央集約ログサービスです。' },
  { term: 'Cloud Monitoring', aliases: ['cloud monitoring'], description: 'インフラやアプリの監視サービスです。' },
  { term: 'Error Reporting', aliases: ['error reporting'], description: 'アプリケーションエラーを集約、可視化する機能です。' },
  { term: 'Cloud Trace', aliases: ['cloud trace'], description: '遅延やリクエスト経路を追跡するサービスです。' },
  { term: 'Cloud Profiler', aliases: ['cloud profiler'], description: 'CPUやメモリ消費を継続分析するサービスです。' },
  { term: 'Google Cloud Observability', aliases: ['google cloud observability'], description: '監視とログの総合的な観測基盤です。' },
  { term: 'Memorystore', aliases: ['memorystore'], description: 'マネージドなインメモリデータストアサービスです。' },
  { term: 'AlloyDB for PostgreSQL', aliases: ['alloydb for postgresql'], description: 'PostgreSQL互換のマネージドデータベースです。' },
  { term: 'Cloud VPN', aliases: ['cloud vpn'], description: 'オンプレミスなどとVPN接続するサービスです。' },
  { term: 'Cloud CDN', aliases: ['cloud cdn'], description: 'Google CloudのCDNサービスです。' },
  { term: 'VPC Service Controls', aliases: ['vpc service controls'], description: 'データ境界保護を強化する仕組みです。' },
  { term: 'Access Context Manager', aliases: ['access context manager'], description: '属性ベースアクセス制御を支援するサービスです。' },
  { term: 'Cloud Asset Inventory', aliases: ['cloud asset inventory'], description: 'Google Cloud資産を一覧、検索できるサービスです。' },
  { term: 'Binary Authorization', aliases: ['binary authorization'], description: 'Kubernetesデプロイ時のイメージ検証を支援する仕組みです。' },
  { term: 'Cloud Scheduler', aliases: ['cloud scheduler'], description: '定期実行ジョブをトリガーするサービスです。' },
  { term: 'Cloud Run Jobs', aliases: ['cloud run jobs'], description: 'Cloud Runでバッチ的にジョブを実行する仕組みです。' },
  { term: 'Cloud SQL Auth Proxy', aliases: ['cloud sql auth proxy'], description: 'Cloud SQLへ安全に接続するための補助コンポーネントです。' },
  { term: 'Vertex AI', aliases: ['vertex ai'], description: 'Google CloudのAI、機械学習基盤です。' },
  { term: 'Sensitive Data Protection', aliases: ['sensitive data protection'], description: '機微データ検出や保護を支援するサービスです。' },
  { term: 'Cloud Endpoints', aliases: ['cloud endpoints'], description: 'API管理を支援するサービスです。' },
  { term: 'Firebase', aliases: ['firebase'], description: 'モバイル、Web開発向けの統合基盤です。' },
  { term: 'gcloud CLI', aliases: ['gcloud cli'], description: 'Google Cloudを操作するコマンドラインツールです。' },
  { term: 'Cloud Shell', aliases: ['cloud shell'], description: 'ブラウザから使えるコマンドライン環境です。' },
  { term: 'Organization Policy', aliases: ['organization policy'], description: '組織レベルで制約をかけるポリシー機能です。' },
  { term: 'Cloud Run Service Identity', aliases: ['cloud run service identity'], description: 'Cloud RunがGoogle Cloud APIを呼ぶときに使うサービスアカウントです。' },
  { term: 'Application Default Credentials', aliases: ['application default credentials'], description: 'Google Cloudクライアントライブラリが認証情報を見つける仕組みです。' },
];
