// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: architecturePatterns (1/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // architecture (148), design-document (69), Development (32), Design Document (15), Architecture (12), uml (8), UML (2)
  { term: 'テンプレート', aliases: ['template'], description: '文書の書き方や構成をそろえるためのひな形です。テンプレートがあると品質が安定し、新規参加者も書きやすくなります。' },
  { term: '拡張性', aliases: ['scalability'], description: '将来の機能追加や利用増加に対応しやすい性質です。今だけ最適な設計は短期的には楽でも、後で大きな負債になることがあります。' },
  { term: 'オーナー', aliases: ['owner', 'product owner'], description: 'ある機能、業務、製品、文書などの責任主体です。意思決定の窓口として明確にしておくと、変更時の混乱を減らせます。' },
  { term: 'アプリケーションアーキテクチャ', description: 'システム全体をどのような構造で組み立てるかという設計方針です。基本設計書ではこの考え方が全体の骨格になり、詳細設計書ではその骨格を各部品へ落とし込みます。' },
  { term: 'レイヤー構造', description: '役割ごとに層を分けてシステムを整理する考え方です。表示、業務処理、データアクセスを分けることで、見通しや保守性を高めやすくなります。' },
  { term: 'プレゼンテーション層', description: '画面表示や入力受付など、利用者と直接接する部分を担当する層です。UI変更の影響を業務ロジックへ広げにくくする目的があります。' },
  { term: 'アプリケーション層', description: '利用者の操作要求を受け取り、業務処理の流れを組み立てる層です。どの処理をどの順番で呼ぶかを制御する役割が中心です。' },
  { term: 'ドメイン層', description: '業務ルールや業務概念を表現する中心的な層です。単なる技術実装ではなく、業務の意味そのものをきれいに表すことが求められます。' },
  { term: 'インフラ層', description: 'DBアクセス、外部API呼び出し、ファイル操作など、技術依存の処理を受け持つ層です。業務ロジックと技術実装を分離するための重要な考え方です。' },
  { term: 'モノリス', description: 'システム全体が大きな一つのまとまりとして動く構成です。単純で管理しやすい反面、規模が大きくなると変更影響が広がりやすくなります。' },
  { term: 'モジュラーモノリス', description: 'ひとつのアプリとして動かしながら、内部は機能ごとに強く分離して整理する構成。マイクロサービスほど複雑にせず境界を明確にできる。ただし超巨大プロジェクトではビルドに数時間かかることもある。' },
  { term: 'マイクロサービス', description: 'システムを小さな独立サービス群に分けて構成する方式です。拡張性や独立デプロイの利点がある一方で、運用、監視、分散トランザクションは難しくなります。' },
  { term: 'DDD', aliases: ['ddd'], description: 'ドメイン駆動設計の略で、業務理解を中心にシステム設計を進める考え方です。言葉合わせ、モデル化、境界整理を重視するため、複雑な業務システムと相性がよいです。' },
  { term: 'CQRS', aliases: ['cqrs'], description: '更新処理と参照処理を分けて設計する考え方です。読み取り量が多い、または要求される構造が大きく異なる場合に有効です。' },
  { term: 'イベント駆動', description: '何かが起きたという出来事を起点に処理を進める設計です。疎結合にしやすい反面、処理の見通しや追跡性を確保する工夫が必要です。' },
  { term: 'コレオグラフィ', description: '中央司令塔を置かず、各サービスがイベントに反応して連携する方式です。疎結合になりやすいですが、全体の動きが見えにくくなることがあります。' },
  { term: 'Sagaパターン', aliases: ['sagaパターン'], description: '分散環境で一連の処理を整合的に進めるための考え方です。全体をひとつのDBトランザクションにできないときの代表的な方法です。' },
  { term: '疎結合', description: '部品同士が強く依存しすぎない状態です。変更影響を狭くできるため、長く運用するシステムでは非常に重要です。' },
  { term: '責務分離', description: '役割の異なる処理を別の場所へ切り分けることです。設計書でも「何をどこに置くか」を明確にする基準になります。' },
  { term: '分散トレーシング', description: '複数サービスをまたぐ処理を一連として追跡する仕組みです。マイクロサービスでは障害調査の生命線になりやすいです。' },
  { term: 'Zustand', aliases: ['zustand'], description: '比較的軽量な状態管理ライブラリです。シンプルな記述で導入しやすい点が評価されています。' },
  { term: 'コントローラー', description: 'リクエストを受けて入力を解釈し、適切な処理へつなぐ入口部品です。薄く保ち、業務判断は他層に寄せると見通しがよくなります。' },
  { term: '正規表現', description: '文字列パターンを表現して照合する方法です。便利ですが複雑にしすぎると保守性が落ちるため、用法には注意が必要です。' },
  { term: 'インフラストラクチャ層', aliases: ['infrastructure layer'], description: 'データベースアクセス・外部API呼び出し・ファイル操作などの技術依存な処理を担う層です。ビジネスロジックと技術実装を分離するための重要な概念です。' },
  { term: 'サービス分解', aliases: ['service decomposition'], description: '機能をどのような単位で独立性を持たせて分割するかを決めることです。技術的な関心だけでなく、ビジネス責務・変更頻度・チーム構造も考慮する必要があります。' },
  { term: 'サーガパターン', aliases: ['saga pattern'], description: '分散環境で複数の操作にまたがる整合性を保つアプローチです。単一のデータベーストランザクションにできない場合の代表的な手法です。' },
  { term: '補償トランザクション', aliases: ['compensating transaction'], description: '部分的に完了した処理を取り消すための逆操作です。分散処理ではロールバックの代替として使用されます。' },
  { term: '単一責任の原則', aliases: ['single responsibility principle'], description: 'コンポーネントが変更される理由を一つだけ持つべきという原則です。責務が混在すると修正が予期せぬ副作用を生みやすくなります。' },
  { term: 'KISSの原則', aliases: ['kissの原則', 'kiss principle'], description: 'Keep It Simple, Stupid：できる限りシンプルに設計する原則です。実際の現場では巧みな設計より理解しやすく堅牢な設計の方が強いことが多いです。' },
  { term: 'DRYの原則', aliases: ['dryの原則', 'dry principle'], description: 'Don\'t Repeat Yourself：同じ知識やロジックを重複させない原則です。ただし、早すぎる抽象化は逆に複雑性を高める場合があります。' },
  { term: '専用回線接続', aliases: ['dedicated connection'], description: '安定した専用線でクラウドやデータセンターに接続する方法です。品質は高いですがコストが高く、開通まで時間がかかります。' },
  { term: 'ページネーション', aliases: ['pagination'], description: 'リストデータをページ単位に分割して取得する手法です。大量データでのレスポンスパフォーマンスとUI使いやすさに直接影響します。' },
  { term: '検索設計', aliases: ['search design'], description: 'ユーザーがデータをどの軸で検索したいかを設計することです。条件を増やすことより、業務で実際に情報を探す軸に合っているかが重要です。' },
  { term: '監査コンプライアンス', aliases: ['audit compliance'], description: '外部または内部の監査に耐えられる証跡と手続きを確保することです。システム設計と運用設計の両方が関係します。' },
  { term: 'ユーザーマニュアル', description: '利用者向けに操作方法を説明する文書です。単なる機能説明ではなく、業務の流れに沿って書くと使われやすいです。' },
  { term: 'スケルトンスクリーン', description: '読み込み中に画面の骨組みだけ先に見せる表示方法です。単なる待機表示より体感をよくしやすいです。' },
  { term: 'アクセシブルネーム', description: 'スクリーンリーダーなどが認識する要素名です。見た目だけでなく、補助技術からどう見えるかが重要です。' },
  { term: 'ダークパターン', description: '利用者に不利な選択を誘導する設計です。短期的な成果が出ても、信頼を大きく損なうため避けるべきです。' },
  { term: 'MVCC', aliases: ['mvcc'], description: '複数版のデータを管理して読み取りと更新の競合を減らす仕組みです。多くのDBで採用され、並行性向上に役立っています。' },
  { term: '知識の見える化', description: '暗黙知を文書や図、テンプレートに落とし込むことです。AI活用や引継ぎにも大きく効きます。' },
  { term: '意思決定レイヤー', description: 'どの種類の判断をどの階層が行うかという整理です。現場判断と経営判断の境目を明確にすると、速度と統制を両立しやすくなります。' },
  { term: '注文書', description: '発注内容を記した文書です。契約成立の一部または証跡になる場合があるため、曖昧な表現は避けるべきです。' },
  { term: 'アンチコラプションレイヤー', description: '外部システムの概念や都合が内部設計を汚さないよう間に置く変換層です。レガシー連携で特に有効です。' },
  { term: 'ストラングラーパターン', description: '既存システムを一気に置き換えず、周辺から少しずつ新システムへ移していく考え方です。大規模刷新で現実的な方法です。' },
  { term: 'ブラウンフィールド刷新', description: '既存資産がある状態で改善や再構築を進めることです。現行影響を見ながら進める難しさがあります。' },
  { term: 'グリーンフィールド開発', description: '既存制約の少ない新規開発です。自由度は高いですが、既存知見が少ないこともあります。' },
  { term: 'ブラウンフィールドモダナイゼーション', aliases: ['brownfield modernization'], description: '既存資産がある環境内で改善や再構築を行うことです。現行システムへの影響を監視しながら進める課題があります。' },
  { term: 'CRUDマトリクス', aliases: ['crudマトリクス'], description: '業務や機能ごとに、どのデータを作成、参照、更新、削除するかを整理した表です。機能とデータの関係を一覧できるため、抜け漏れ確認に役立ちます。' },
  { term: 'CRUD図', aliases: ['crud図'], description: 'CRUDマトリクスを図的に表現したものです。表より直感的に関係性を把握しやすい場面があります。' },
  { term: 'データフロー図', aliases: ['dfd'], description: 'データがどこから来て、どこへ流れ、どこで加工されるかを示した図です。システム間連携や内部処理の流れを整理するのに有効です。' },
  { term: 'コンテキスト図', description: '対象システムと外部の関係だけを大きく示した図です。まず全体境界を把握したいときに使います。' },
  { term: 'ユースケース記述', description: '利用者がどの目的でどのようにシステムを使うかを文章で記述したものです。図だけでは伝わらない前提や流れを補えます。' },
  { term: 'アクティビティ図', description: '処理の流れや分岐、並行動作を表す図です。業務フローや処理フローの可視化に向いています。' },
  { term: 'シーケンス図', description: 'オブジェクトやシステム間のやり取りを時系列順で表す図です。API呼び出しや画面からDBまでの流れを追いやすくなります。' },
  { term: 'コミュニケーション図', description: '要素間の関係とメッセージのやり取りを重視した図です。シーケンス図より構造を見たいときに向きます。' },
  { term: 'ステートマシン図', description: 'ある対象がどの状態からどの状態へ移るかを表現した図です。状態遷移図をより形式的に扱うときに使います。' },
  { term: 'クラス図', description: 'クラス、属性、メソッド、関係を表した図です。オブジェクト指向設計の骨格を共有するのに役立ちます。' },
  { term: 'オブジェクト図', description: '特定時点でのオブジェクト同士の関係を表した図です。クラス図より具体的なインスタンス例を示せます。' },
  { term: 'コンポーネント図', description: 'システムを構成する部品とその依存関係を示す図です。論理構成を共有するのに適しています。' },
  { term: '配置図', description: 'サーバー、アプリ、ネットワーク機器などの配置関係を示す図です。インフラ設計や構成説明でよく使われます。' },
  { term: '論理構成図', description: '役割単位でシステム構造を表した図です。物理環境に依存しない全体像の共有に向いています。' },
  { term: '物理構成図', description: '実際のサーバー、ネットワーク、ミドルウェア配置を示した図です。構築や運用の実務に直結します。' },
  { term: 'ネットワーク構成図', description: '通信経路、セグメント、接続点を中心に示す構成図です。セキュリティや接続要件の確認に有効です。' },
  { term: 'システム関連図', description: '複数システムの関係性を俯瞰的に表す図です。連携対象の洗い出しに役立ちます。' },
  { term: '外部インターフェース一覧', description: '他システムや外部サービスとの接続点を一覧化した資料です。漏れなく連携を管理する基礎になります。' },
  { term: '内部インターフェース一覧', description: 'システム内部のモジュール間接続や呼び出しを整理した一覧です。構造把握や影響分析に使えます。' },
  { term: '画面一覧', description: 'システムに存在する画面を一覧化した資料です。画面数の把握や範囲確認に役立ちます。' },
  { term: '画面遷移図', description: 'どの画面からどの画面へ移るかを示した図です。利用者導線を共有するうえで基本資料になります。' },
  { term: '画面レイアウト図', description: '画面上の項目配置を示した図です。詳細設計でUIの共通認識を作るのに使います。' },
  { term: '画面項目一覧', description: '画面ごとの入力項目、表示項目を一覧化した資料です。項目定義との対応づけにも役立ちます。' },
  { term: '項目属性表', description: '項目名、型、桁数、必須、初期値などをまとめた表です。画面設計、API設計、DB設計をつなぐ資料になります。' },
  { term: '項目マッピング表', description: '画面、API、DBなどの項目対応を整理した表です。データ受け渡しのズレを防ぎます。' },
  { term: '帳票一覧', description: '出力対象となる帳票を一覧化した資料です。帳票要件の把握や優先度整理に使います。' },
  { term: '帳票レイアウト', description: '帳票の見た目や項目配置を示した設計です。印刷物やPDF出力の品質に直結します。' },
  { term: '帳票項目定義', description: '帳票に出す項目の意味や出力条件を整理した定義です。表示ルールや計算ロジックの明確化に役立ちます。' },
  { term: 'バッチ一覧', description: 'バッチ処理の種類、目的、実行タイミングを一覧化したものです。定期処理の全体像把握に向いています。' },
  { term: 'バッチフロー', description: '複数バッチの実行順や依存関係を示した流れです。夜間処理や締め処理の設計で重要になります。' },
  { term: '入出力定義', description: '処理に対して何を受け取り、何を返すかを定義したものです。画面、API、バッチすべてで重要です。' },
  { term: 'ファイルレイアウト定義', description: '連携ファイルの項目位置、型、長さなどを定義したものです。固定長やCSV連携で特に重要です。' },
  { term: 'コード体系', description: '業務コードや管理コードをどのような体系で持つかという設計です。将来の拡張性や検索性にも影響します。' },
  { term: '採番ルール', description: 'IDや番号をどの条件で付与するかのルールです。一意性だけでなく、業務運用との整合も大切です。' },
  { term: 'メッセージ一覧', description: '画面やAPIで表示、返却するメッセージを一覧化した資料です。文言の統一やテスト観点整理に役立ちます。' },
  { term: 'エラー一覧', description: '発生しうるエラーと、そのコードや内容を整理した一覧です。問い合わせ対応や障害解析の基礎になります。' },
  { term: 'メッセージ設計書', description: 'メッセージID、文言、表示条件、表示先を整理した設計書です。詳細設計で使いやすい形にすることが多いです。' },
  { term: 'バリデーション一覧', description: '各項目、各処理で行う妥当性確認を整理した一覧です。漏れなく入力制御を設計するのに有効です。' },
  { term: '例外一覧', description: '異常ケースを洗い出して一覧化した資料です。正常系だけでは見えない実務上の問題を拾えます。' },
  { term: '例外設計表', description: '例外発生時の振る舞い、返却値、ログ出力などを整理した表です。障害時品質を大きく左右します。' },
  { term: '状態一覧', description: '業務対象が持つ状態を一覧化した資料です。状態遷移図の前提となることが多いです。' },
  { term: '状態遷移表', description: 'どの条件でどの状態へ移るかを表形式で整理したものです。図だけでは表しにくい詳細条件を補えます。' },
  { term: 'イベント一覧', description: '処理開始のきっかけとなるイベントを一覧化した資料です。非同期処理や画面イベント整理で有効です。' },
  { term: '業務イベント定義', description: '申請、承認、取消など業務上の出来事を定義したものです。イベント駆動設計の土台になります。' },
  { term: '権限マトリクス', description: '役割ごとにどの操作が可能かを表にしたものです。認可設計の中核資料です。' },
  { term: '役割一覧', description: '利用者や管理者などの役割を整理した一覧です。権限設計や画面制御の前提になります。' },
  { term: '権限制御仕様', description: 'どの条件で閲覧、更新、削除、承認などを許可するかを決めた仕様です。内部統制やセキュリティにも関わります。' },
  { term: '業務ルール一覧', description: '業務上守るべきルールを整理した一覧です。要件と詳細設計の橋渡しになります。' },
  { term: '業務判定条件', description: '承認可否や登録可否などの判断条件です。曖昧だと実装や運用にばらつきが出やすくなります。' },
  { term: '計算式定義', description: '金額や点数などの算出式を明示した定義です。Excel依存の暗黙計算を脱却するのに有効です。' },
  { term: 'マスタ一覧', description: '業務で使う基準データを一覧化したものです。項目定義や保守範囲の整理に役立ちます。' },
  { term: 'マスタメンテナンス仕様', description: 'マスタを誰がどう更新するかの仕様です。整合性と運用性の両立が必要です。' },
  { term: 'コード変換表', description: 'システムごとに異なるコード値の対応表です。連携設計で非常に重要です。' },
  { term: '初期データ定義', description: '導入時にあらかじめ投入するデータを定義したものです。本番移行や初期セットアップで必要になります。' },
  { term: '非機能一覧', description: '性能、監視、可用性、セキュリティなどの要件を一覧化したものです。機能要件に埋もれがちな観点を整理できます。' },
  { term: '性能要件表', description: '応答時間、同時接続数、件数処理量などをまとめた表です。性能設計の前提になります。' },
  { term: '可用性要件表', description: '停止許容時間、冗長化要件、復旧目標などを整理した表です。運用設計と密接に関わります。' },
  { term: 'ログ出力設計', description: '何を、どの粒度で、どこへ、どの形式で出すかを定める設計です。障害解析や監査で効いてきます。' },
  { term: '監査ログ定義', description: '誰が何をしたかを残すログ定義です。内部統制や法令対応に関わります。' },
  { term: '差分一覧', description: '変更前後で何が変わったかを一覧化したものです。レビューや移行判断の材料になります。' },
  { term: '依存関係図', description: '部品、処理、システム間の依存を示した図です。影響分析に有効です。' },
  { term: '呼出関係図', description: 'どの処理がどの処理を呼ぶかを示す図です。内部構造の理解に役立ちます。' },
  { term: '機能関連図', description: '機能同士の関係やまとまりを可視化した図です。機能分割やメニュー設計に使えます。' },
  { term: '業務機能対応表', description: '業務活動とシステム機能の対応を整理した表です。要件漏れや過剰機能の確認に向いています。' },
  { term: 'トレーサビリティマトリクス', description: '要件、設計、実装、テストの対応関係を表にしたものです。変更時の追跡に非常に役立ちます。' },
  { term: '要件対応表', description: '各要件に対してどの設計や機能が対応するかを整理した表です。受入時の説明にも使えます。' },
  { term: 'データ辞書', description: '項目の意味、型、制約を体系的に整理した資料です。設計、運用、分析の共通基盤になります。' },
  { term: '業務用語集', description: '業務上の言葉の意味を整理した用語集です。部門ごとの解釈差を減らせます。' },
  { term: 'システム用語集', description: '技術用語やシステム内名称を整理した用語集です。設計書を読みやすくする補助資料です。' },
  { term: '凡例一覧', description: '図や表で使う記号や色の意味を整理した一覧です。複雑な資料ほど重要になります。' },
  { term: '設計判断記録', description: 'なぜその設計にしたかを残す記録です。将来の変更判断を楽にする重要資産になります。' },
  { term: '状態機械図', aliases: ['state machine diagram'], description: '対象がどの状態間を遷移するかを表す図です。状態遷移をより形式的に扱う場合に使用します。' },
  { term: 'デプロイメント図', aliases: ['deployment diagram'], description: 'サーバー・アプリケーション・ネットワーク機器の配置関係を示す図です。インフラ設計や構成ドキュメントによく使われます。' },
  { term: '論理アーキテクチャ図', aliases: ['logical architecture diagram'], description: '役割によってシステム構造を表す図です。物理環境に依存せず全体像を共有するのに適しています。' },
  { term: '物理アーキテクチャ図', aliases: ['physical architecture diagram'], description: 'サーバー・ネットワーク・ミドルウェアの実際の配置を示す図です。構築・運用作業に直結します。' },
  { term: 'ネットワークアーキテクチャ図', aliases: ['network architecture diagram'], description: '通信経路・セグメント・接続点に焦点を当てた構成図です。セキュリティや接続性の要件確認に役立ちます。' },
  { term: 'フィールド属性表', aliases: ['field attribute table'], description: 'フィールド名・型・桁数・必須フラグ・デフォルト値をまとめた表です。画面設計・API設計・DB設計をつなぐドキュメントになります。' },
  { term: 'フィールドマッピング表', aliases: ['field mapping table'], description: '画面・API・データベース間のフィールドの対応を整理した表です。データ受け渡しの齟齬を防ぎます。' },
  { term: 'バッチジョブ一覧', aliases: ['batch job list'], description: 'バッチ処理の種類・目的・実行タイミングを列挙したドキュメントです。定期処理の全体像の把握に適しています。' },
  { term: 'ロール一覧', aliases: ['role list'], description: 'ユーザーや管理者などのロールを整理した一覧です。権限設計や画面制御の前提条件になります。' },
  { term: 'ビジネスルール一覧', aliases: ['business rule list'], description: '業務で守らなければならないルールを整理した一覧です。要件と詳細設計をつなぐ橋渡しになります。' },
  { term: '業務判断基準', aliases: ['business decision criteria'], description: '承認可否や登録可否などの判断条件です。曖昧さが実装や運用での不整合を招くことがあります。' },
  { term: 'マスターデータ一覧', aliases: ['master data list'], description: '業務で参照される基準データを列挙したドキュメントです。フィールド定義やメンテナンス範囲の整理に役立ちます。' },
  { term: 'マスターデータメンテナンス仕様', aliases: ['master data maintenance specification'], description: 'マスターデータを誰がどのように更新するかの仕様書です。データ整合性と運用上の使いやすさのバランスが求められます。' },
  { term: '非機能要件一覧', aliases: ['non-functional requirements list'], description: 'パフォーマンス・監視・可用性・セキュリティなどの要件を列挙したドキュメントです。機能要件に埋もれがちな観点を整理します。' },
  { term: '差異一覧', aliases: ['difference list'], description: '変更前後で何が変わったかを列挙したドキュメントです。レビューや移行判断の材料になります。' },
  { term: '業務機能マッピング表', aliases: ['business-function mapping table'], description: '業務活動とシステム機能の対応を整理した表です。要件の抜けや過剰な機能の検証に適しています。' },
  { term: '要件マッピング表', aliases: ['requirements mapping table'], description: '各要件にどの設計要素や機能が対応するかを整理した表です。受け入れ時の説明にも活用できます。' },
  { term: '実際の貢献', aliases: ['actual contribution'], description: '発言だけでなく、成果物や改善を実際に生み出すこと。' },
  { term: '貢献', aliases: ['contribution'], description: 'プロジェクトや組織に価値を加える行為。' },
  { term: '決定権', aliases: ['decision authority'], description: '最終的に方向や方針を決める力。' },
  { term: '権威', aliases: ['authority'], description: '立場や肩書きによる影響力。' },
  { term: '肩書き', aliases: ['job title'], description: '役職や立場を表す名称。' },
  { term: '責任', aliases: ['responsibility'], description: '結果や問題に対して引き受ける義務。' },
  { term: '実装責任', aliases: ['implementation responsibility'], description: '作るだけでなく、品質や結果まで引き受ける責任。' },
  { term: '最終責任', aliases: ['ultimate responsibility'], description: '結果に対して最後に負う責任。' },
  { term: 'コミットメント', aliases: ['commitment'], description: 'やり切る意思や引き受ける覚悟。' },
  { term: '発言量', aliases: ['volume of remarks'], description: 'どれだけ多く話したかという量。' },
  { term: '現実主義', aliases: ['pragmatism'], description: '理想よりも、実際に機能するかを重視する考え方。' },
  { term: '動作', aliases: ['system behavior'], description: 'システムが期待どおりに機能すること。' },
  { term: '失敗のコスト', aliases: ['cost of failure'], description: '誤りや障害によって生じる損失や手戻り。' },
  { term: 'コードレビュー', aliases: ['code review'], description: 'コードを他者が確認し、品質や問題を見つけること。' },
  { term: 'ユーザー視点', aliases: ['user perspective'], description: '利用者にとっての価値や使いやすさを重視する見方。' },
  { term: '問題設定', aliases: ['problem definition'], description: '何を解くべきかを定義すること。' },
  { term: '基本設計', aliases: ['high-level design'], description: '画面、機能、データ構造などの大きな設計を決める工程。' },
  { term: '詳細設計', aliases: ['detailed design'], description: '実際に作れるレベルまで具体化する設計工程。' },
  { term: '仕様化', aliases: ['specification writing'], description: '要求や意図を実装できる形へ明確化すること。' },
  { term: '例外時の判断', aliases: ['exception handling decision'], description: '想定外の状況に対して行う判断。' },
  { term: '価値判断', aliases: ['value judgment'], description: '何を優先し、何を重視するかを決める判断。' },
  { term: '判断の質', aliases: ['quality of judgment'], description: '目的や責任を踏まえて適切に判断する力。' },
  { term: '評価軸', aliases: ['evaluation criteria (assessment)'], description: '人や成果を評価するときの観点。' },
  { term: '利害調整', aliases: ['stakeholder alignment (interest coordination)'], description: '関係者の要望や利益の違いを整えること。' },
  { term: '品質', aliases: ['quality'], description: '成果物の正しさ、安定性、使いやすさなどの総合的なよさ。' },
  { term: '品質水準', aliases: ['quality standard (acceptance level)'], description: 'どの完成度で公開・納品するかの基準。' },
  { term: '単体テスト', aliases: ['unit testing'], description: '小さな部品ごとに正しく動くか確認するテスト。' },
  { term: '結合テスト', aliases: ['integration testing'], description: '複数の部品をつないだときに正しく動くかを見るテスト。' },
  { term: 'システムテスト', aliases: ['system testing'], description: 'システム全体として要件どおり動くか確認するテスト。' },
  { term: '不具合', aliases: ['defect'], description: '本来あるべき動きや仕様と違っている問題。' },
  { term: 'ローコード開発', aliases: ['low-code development'], description: '最小限のコーディングでアプリを構築する方式。' },
  { term: 'ノーコード開発', aliases: ['no-code development'], description: 'コーディングをほとんど行わずにアプリを構築する方式。' },
  { term: 'Service Layer', aliases: ['service layer', 'サービス層'], description: 'アプリケーションのビジネスロジックをまとめ、UIとデータアクセス層の間に位置するアーキテクチャ層。' },
  { term: 'Application Service', aliases: ['application service'], description: 'ユースケースを調整・オーケストレーションし、ドメインオブジェクトに処理を委譲するDDDの層。' },
  { term: 'Domain Service', aliases: ['domain service'], description: '特定のエンティティや値オブジェクトに自然に属さないドメインロジックを担うDDDのサービス。' },
  { term: 'Entity', aliases: ['entity'], description: '一意の識別子（ID）で追跡され、時間とともに状態が変化するDDDのドメインオブジェクト。' },
  { term: 'Value Object', aliases: ['value object'], description: 'IDを持たず、属性の値によって同一性が決まるDDDのドメインオブジェクト。不変であるべき。' },
  { term: 'Aggregate', aliases: ['aggregate'], description: '関連するエンティティと値オブジェクトをひとまとまりとして扱うDDDの概念。外部からはAggregate Rootを通じてのみアクセスする。' },
  { term: 'Aggregate Root', aliases: ['aggregate root'], description: '集約の入口となるエンティティ。外部からは必ずAggregate Rootを経由して集約内のオブジェクトへアクセスする。' },
  { term: 'Bounded Context', aliases: ['bounded context'], description: '特定のドメインモデルが一貫して適用される境界領域。DDDの戦略的設計の核心概念。' },
  { term: 'ドメイン駆動設計', description: 'ドメインの複雑さに立ち向かうため、ドメインエキスパートと開発者がユビキタス言語を共有しながら設計・実装するアプローチ。' },
  { term: '戦術的DDD', aliases: ['戦術的ddd', 'tactical ddd'], description: 'DDDにおける実装レベルのパターン群。Entity・Value Object・Aggregate・Repository・Domain Serviceなどが含まれる。' },
  { term: '戦略的DDD', aliases: ['戦略的ddd', 'strategic ddd'], description: 'DDDにおける大局的な設計。Bounded Context・コンテキストマップ・ユビキタス言語などシステム全体の構造を扱う。' },
  { term: 'Clean Architecture', aliases: ['clean architecture', 'クリーンアーキテクチャ'], description: 'Robert C. Martinが提唱する、依存方向をドメイン中心に向けた同心円状のレイヤードアーキテクチャ。' },
  { term: 'Hexagonal Architecture', aliases: ['hexagonal architecture'], description: 'ポートとアダプターによってアプリケーションコアを外部システムから分離するアーキテクチャ。' },
  { term: 'Onion Architecture', aliases: ['onion architecture', 'オニオンアーキテクチャ'], description: 'ドメインモデルを中心に同心円状のレイヤーを重ね、依存方向を内側へ向けるアーキテクチャスタイル。' },
  { term: 'Ports and Adapters', aliases: ['ports and adapters'], description: 'アプリケーションをポート（インターフェース）とアダプター（実装）で外部と繋ぐHexagonal Architectureの別称。' },
  { term: 'Layered Architecture', aliases: ['layered architecture', 'レイヤードアーキテクチャ', '階層型アーキテクチャ'], description: 'プレゼンテーション・アプリケーション・ドメイン・インフラなど責任別の層に分割するアーキテクチャスタイル。' },
  { term: 'MVC', aliases: ['mvc', 'model-view-controller'], description: 'Model-View-Controllerの略。UIを持つアプリケーションをモデル・ビュー・コントローラーに分離するアーキテクチャパターン。' },
  { term: 'MVVM', aliases: ['mvvm', 'model-view-viewmodel'], description: 'Model-View-ViewModelの略。ViewとModelの間にViewModelを置き、データバインディングでUIロジックを分離するパターン。' },
  { term: 'VIPER', aliases: ['viper'], description: 'View・Interactor・Presenter・Entity・Routerから成るiOS向けクリーンアーキテクチャパターン。' },
  { term: 'Event Sourcing', aliases: ['event sourcing'], description: '状態を直接保存するのではなく、状態変化をイベントの列として永続化するアーキテクチャパターン。' },
  { term: 'Message Queue', aliases: ['message queue'], description: 'サービス間の非同期通信を実現するためのメッセージ一時保存機構。RabbitMQ・Kafkaなどが代表例。' },
  { term: 'イベント駆動アーキテクチャ', aliases: ['eda', 'event-driven architecture'], description: 'イベントの発生と受信を中心にコンポーネント間の通信を構成するアーキテクチャスタイル。' },
  { term: 'Anti-Corruption Layer', aliases: ['anti-corruption layer', 'acl', '腐敗防止層'], description: '【アーキテクチャ】異なるBounded Context間の変換・翻訳を担い、外部モデルの変化からドメインモデルを守るDDDパターン。 【OCI APEX】接続元や通信条件を絞るアクセス制御ルール。' },
  { term: 'Backend for Frontend', aliases: ['backend for frontend'], description: '特定のフロントエンド向けに最適化されたバックエンドAPIを用意するアーキテクチャパターン。' },
  { term: 'Strangler Fig Pattern', aliases: ['strangler fig pattern', 'strangler pattern', 'ストラングラーフィグパターン'], description: 'レガシーシステムを段階的に新システムへ置き換える移行パターン。既存機能を徐々に新実装で包み込む。' },
  { term: 'Facade Migration', aliases: ['facade migration', 'ファサード移行'], description: 'ファサードを使い、旧システムと新システムを共存させながら段階的に移行するパターン。' },
  { term: 'Saga', aliases: ['saga'], description: 'マイクロサービス間にまたがる長期トランザクションを、補償トランザクションで整合性を保ちながら管理するパターン。' },
  { term: '12-Factor App', aliases: ['12-factor app', 'twelve-factor app', '12ファクターアプリ'], description: 'クラウドネイティブなSaaSアプリケーションを構築するための12の方法論。Herokuが提唱。' },
  { term: 'ペースレイヤリング', aliases: ['pace layering'], description: 'GartnerのStu Turcotte提唱モデル。システムを変化速度（Systems of Record/Differentiation/Innovation）の層に分類する。' },
  { term: 'バイモーダルIT', aliases: ['バイモーダルit', 'bimodal it'], description: 'Gartnerが提唱したITの二形態論。安定性重視のMode1と俊敏性重視のMode2を並立させる戦略。' },
  { term: '関心事の分離', aliases: ['separation of concerns'], description: 'ソフトウェアをそれぞれ異なる関心事（責務）に基づいて分割する設計原則。Separation of Concernsとも呼ぶ。' },
  { term: 'コンテキスト境界', description: 'DDD（ドメイン駆動設計）においてドメインモデルの適用範囲を明示的に区切った境界。' },
  { term: '機能設計', description: 'システムが提供する機能の外部仕様を設計すること。画面・帳票・API仕様などを定義する。' },
  { term: '非機能設計', description: '可用性・性能・セキュリティなど非機能要件を満たすためのシステム設計。' },
  { term: 'Basic Design', aliases: ['basic design'], description: 'システムの基本的な外部仕様を定義する設計工程。画面・API・DBの概要を確定する。' },
  { term: 'Detail Design', aliases: ['detail design'], description: 'Basic Designを受けてモジュール内部のロジック・アルゴリズムを詳細に設計する工程。' },
  { term: 'Function Design', aliases: ['function design'], description: '各機能のI/F・処理フロー・業務ロジックを設計する工程。' },
  { term: 'External Specification', aliases: ['external specification'], description: '外部仕様書。システムが外部から見てどのように振る舞うかを定義したドキュメント。' },
  { term: 'Architecture Design', aliases: ['architecture design'], description: 'システム全体の構成・技術スタック・コンポーネント間の関係を設計する工程。' },
  { term: '構造化設計', description: 'DFDやモジュール分割を用いてシステムを階層的なモジュール構造に分解する伝統的な設計手法。' },
  { term: 'STS分割', aliases: ['sts分割'], description: 'Source-Transform-Sinkの略。データの入力・変換・出力の役割に基づいてシステムをモジュール分割する手法。' },
  { term: 'TR分割', aliases: ['tr分割'], description: 'Transaction（トランザクション）の種類に基づいてシステムをモジュール分割する手法。' },
  { term: '共通機能分割', description: '複数の処理で共有される共通機能を独立したモジュールとして分割する設計手法。' },
  { term: 'ジャクソン法', description: 'データ構造からプログラム構造を導出するJackson Structured Programming（JSP）設計手法。' },
  { term: 'ワーニエ法', description: 'Warnier-Orr記法を用いてデータ階層からプログラム構造を設計する手法。' },
  { term: 'CRUD表', aliases: ['crud表'], description: 'エンティティに対してCreate・Read・Update・Deleteのどの操作を行うかを一覧化したマトリクス。' },
  { term: 'J2EEデザインパターン', aliases: ['j2eeデザインパターン'], description: 'Java EE（J2EE）プラットフォーム向けに定義されたエンタープライズアプリケーションデザインパターン集。' },
  { term: 'Front Controller', aliases: ['front controller'], description: 'Webアプリケーションの全リクエストを単一のコントローラで受け付けるJ2EEデザインパターン。' },
  { term: 'サーバサイジング', description: '要件（TPS・データ量・ユーザー数など）に基づいてサーバのCPU・メモリ・ストレージを見積もること。' },
  { term: 'クラスタリング', description: '複数サーバを一つの論理的なシステムとして連携させ可用性・性能を向上させる技術。' },
  { term: 'ディスクサイジング', description: 'データ量・成長率・バックアップを考慮してストレージ容量を見積もること。' },
  { term: 'メモリサイジング', description: 'アプリケーション・DBMSのメモリ使用量を見積もりサーバメモリ容量を決定すること。' },
  { term: '非機能のレイヤ', aliases: ['non-functional layer'], description: 'ソフトウェアスタックにおいて性能・セキュリティ・可用性などの非機能要素を担うレイヤ。' },
  { term: 'レイヤ', aliases: ['layer'], description: 'ソフトウェアアーキテクチャにおいて役割・責務で分割した階層の単位。' },
  { term: 'APコンポーネント', aliases: ['apコンポーネント', 'ap component'], description: 'アプリケーション層を構成するビジネスロジック・サービスなどのコンポーネント群。' },
  { term: '外部仕様書', aliases: ['external specification document'], description: 'システムが外部に対してどのように振る舞うかを定義した仕様書。ユーザーや他システムとのI/Fを記述する。' },
  { term: 'ドメイン境界', aliases: ['domain boundary'], description: '特定のドメインモデルが有効な範囲の境界。Bounded Contextと同義で使われることが多い。' },
  { term: 'Data Mapper', aliases: ['data mapper'], description: 'オブジェクトとデータベース間のマッピングを担う独立した層を持つパターン。ドメインモデルをDBスキーマから分離する。' },
  { term: 'Active Record', aliases: ['active record'], description: 'オブジェクト自身がDB操作（CRUD）の責務を持つORMパターン。RailsのActiveRecordが代表例。' },
  { term: 'アプリケーション境界', aliases: ['application boundary'], description: 'アプリケーションの責務が及ぶ範囲の境界。外部システムや別アプリとのI/Fポイントを明示する。' },
  { term: '文脈', description: '用語やモデルが有効であるコンテキスト・状況。DDD Bounded Contextと関連する概念。' },
  { term: '記録システム', aliases: ['system of record'], description: '安定的・正確性を重視し業務記録を管理するシステム。ペースレイヤリングのSystems of Record層に対応。' },
  { term: '差別化システム', aliases: ['system of differentiation'], description: '業務の競争優位を実現するためのシステム。ペースレイヤリングのSystems of Differentiation層に対応。' },
  { term: '革新システム', aliases: ['system of innovation'], description: '新ビジネスモデルや実験的機能を素早く試すシステム。ペースレイヤリングのSystems of Innovation層に対応。' },
  { term: 'モード1', aliases: ['mode 1'], description: '安定・信頼性・コスト効率を重視するIT運用スタイル。バイモーダルITの一方の形態。' },
  { term: 'モード2', aliases: ['mode 2'], description: 'アジリティ・実験・スピードを重視するIT運用スタイル。バイモーダルITのもう一方の形態。' },
  { term: 'モノリシック', aliases: ['monolithic'], description: 'システム全体が単一のデプロイ単位として構築されたアーキテクチャスタイル。' },
  { term: '分散システム', aliases: ['distributed system'], description: '複数のノード・プロセスがネットワーク越しに協調して動作するシステムアーキテクチャ。' },
  { term: '非同期分散システム', aliases: ['asynchronous distributed system'], description: 'ノード間の通信が非同期メッセージングで行われる分散システム。結果整合性を採用することが多い。' },
  { term: 'メッセージング', aliases: ['messaging'], description: 'システム間でメッセージを非同期に送受信して連携するアーキテクチャパターン。' },
  { term: 'メッセージバス', aliases: ['message bus'], description: '複数のシステム・コンポーネントが接続して非同期メッセージを交換する共有通信基盤。' },
  { term: 'Publish/Subscribe', aliases: ['publish/subscribe'], description: 'メッセージを発行（Publish）するProducerと購読（Subscribe）するConsumerを分離するメッセージングパターン。' },
  { term: 'Enterprise Integration Patterns', aliases: ['enterprise integration patterns'], description: 'Gregor HohpeとBobby Woolfが定義したエンタープライズシステム統合のデザインパターン集。' },
  { term: '分散システムデザインパターン', aliases: ['distributed systems design patterns'], description: '分散システムの一般的な課題（サービス探索・サーキットブレーカーなど）を解決するパターン集。' },
  { term: '分散モノリス', aliases: ['distributed monolith'], description: 'コードは分散しているが実行時に強い依存関係を持つアンチパターン。マイクロサービスの失敗形態。' },
  { term: 'Webサービス', aliases: ['webサービス', 'web service'], description: 'HTTPベースのAPIを通じて機能を提供するSOAやWeb APIの総称。SOAP・RESTなどが含まれる。' },
  { term: 'Pragmatic REST', aliases: ['pragmatic rest'], description: 'RESTの原則を実用的な観点から適用するアプローチ。厳密なRESTより開発効率・利便性を優先する。' },
  { term: 'Thinサーバアーキテクチャ', aliases: ['thinサーバアーキテクチャ', 'thin server architecture'], description: 'サーバ側のロジックを最小化しクライアント（SPA）に処理を委譲するアーキテクチャスタイル。' },
  { term: 'メッセージ駆動', aliases: ['message-driven'], description: 'イベント・メッセージの受信を起点にシステムが動作するアーキテクチャスタイル。' },
  { term: 'リアクティブシステム', aliases: ['reactive system'], description: '応答性・回復性・弾力性・メッセージ駆動の特性を持つシステム。Reactive Manifesto定義。' },
  { term: 'ポートアンドアダプタ', description: 'Alistair Cockburnが提唱したアーキテクチャパターン。ドメインロジックをポートとアダプタで外部から隔離する。' },
  { term: 'ヘキサゴナルアーキテクチャ', description: 'ポートアンドアダプタパターンの別名。六角形を用いてドメインと外部システムの関係を表現する。' },
  { term: 'DDDドメインモデル', aliases: ['dddドメインモデル', 'ddd domain model'], description: 'Domain-Driven Designにおいてユビキタス言語でビジネスルールを表現したオブジェクトモデル。' },
];
