// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: cloud (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // cloud (159), storage (47), Cloud (16), infrastructure (13)
  { term: 'クラウド', aliases: ['cloud', 'cloud computing'], description: 'インターネット経由でサーバーやストレージ、アプリ実行環境などを利用する形態です。初期投資を抑えやすく、拡張しやすい点が大きな特徴です。' },
  { term: 'オンプレミス', aliases: ['on-premises', 'on-prem'], description: '自社設備内にサーバーやネットワーク機器を置いて運用する形態です。自由度は高い一方で、保守、更新、セキュリティ対応の負担が重くなりやすいです。' },
  { term: 'IaaS', aliases: ['iaas'], description: 'サーバー、ネットワーク、ストレージなどの基盤を提供するクラウド形態です。自由度は高いですが、OSやミドルウェアの管理責任も比較的多く残ります。' },
  { term: 'PaaS', aliases: ['paas'], description: 'アプリ実行に必要な基盤までまとめて提供される形態です。開発者はアプリに集中しやすく、運用負担を減らしやすいのが利点です。' },
  { term: 'SaaS', aliases: ['saas'], description: '完成したソフトウェアをサービスとして利用する形態です。自前開発より導入が早い反面、業務を製品に合わせる発想も必要になります。' },
  { term: 'CDN', aliases: ['cdn'], description: 'コンテンツを利用者に近い場所から配信して高速化する仕組みです。画像、静的ファイル、動画配信などで特に効果が高いです。' },
  { term: 'ベンダー', aliases: ['vendor'], description: '製品やサービスを提供する企業です。開発会社、クラウド提供会社、SaaS提供会社など、文脈により指す対象が変わります。' },
  { term: 'マルチAZ', aliases: ['マルチaz'], description: '複数の可用性ゾーンにまたがって構成することです。単一障害点を減らし、クラウド障害への耐性を高めます。' },
  { term: 'マルチリージョン', description: '複数の地域にまたがってシステムを構成することです。災害対策や全球展開に有効ですが、コストと複雑性は高くなります。' },
  { term: 'リージョン', description: 'クラウド提供者が定める地理的な提供単位です。データ所在地、遅延、法令対応の観点で選定が重要です。' },
  { term: 'アベイラビリティゾーン', description: '同一リージョン内で独立性を持たせた設備単位です。障害影響を分散するための基本単位として使われます。' },
  { term: 'SSG', aliases: ['ssg'], description: 'Static Site Generationの略で、事前に静的ページを生成して配信する方式です。高速で配信しやすく、更新頻度の低いページに向きます。' },
  { term: 'AGPL', aliases: ['agpl'], description: 'ネットワーク経由で利用される場合にも公開義務が及ぶことがあるライセンスです。SaaS提供との相性に注意が必要です。' },
  { term: 'サービスディスカバリ', description: '変動するサービスの場所を自動的に見つける仕組みです。動的なクラウド環境で重要になります。' },
  { term: 'クラウドコスト最適化', description: '必要性能を維持しつつ、無駄な費用を減らす活動です。単純な削減ではなく、性能劣化や運用負荷とのバランスが重要です。' },
  { term: 'タグ管理', description: 'クラウド資源に用途や部門などの情報を付けて管理することです。請求按分、資産棚卸し、統制で大きな効果があります。' },
  { term: 'ランディングゾーン', description: 'クラウド利用開始時に必要な標準構成一式です。ネットワーク、監視、セキュリティ、アカウント構造の共通土台として使われます。' },
  { term: 'クラウドセンターオブエクセレンス', description: 'クラウド利用の標準化や支援を行う専門組織です。各案件がばらばらに進まないよう、ガードレールを作る役割があります。' },
  { term: 'エッジコンピューティング', description: '利用者や機器の近くで処理する考え方です。低遅延が求められる用途で有効ですが、分散管理の難しさがあります。' },
  { term: '負荷分散アルゴリズム', aliases: ['load balancing algorithm'], description: 'ロードバランサーがリクエストをサーバー群に振り分ける方式です。ラウンドロビン・最小接続数・IPハッシュなどがあり用途に応じて選択します。' },
  { term: 'ヘルスチェックインターバル', aliases: ['health check interval'], description: 'ロードバランサーやオーケストレーターがサービスの死活確認を行う頻度です。短すぎると負荷が増し、長すぎると障害検知が遅れます。' },
  { term: 'リトライ設計', aliases: ['retry design'], description: '一時的な障害やタイムアウトに対して再試行する仕組みの設計です。べき等性の確保と上限回数・バックオフの設定がポイントです。' },
  { term: 'コネクションプール枯渇', aliases: ['connection pool exhaustion'], description: 'データベースや外部サービスへの接続数が上限に達しリクエストが処理できなくなる状態です。プールサイズの調整とタイムアウト設定で対処します。' },
  { term: 'キャパシティ閾値', aliases: ['capacity threshold'], description: 'リソース使用率がこれを超えたらスケールアウトやアラートを発動する境界値です。適切な値の設定がコストと可用性のバランスを決めます。' },
  { term: 'アセットインベントリ', aliases: ['asset inventory'], description: 'クラウドやオンプレミス上のリソースを一元的に台帳管理することです。未使用リソースの検出やセキュリティ監査の基盤となります。' },
  { term: '配信保証', description: 'メッセージや通知をどの程度確実に届けるかの設計です。最低一回、最大一回、厳密一回など考え方が分かれます。' },
  { term: 'iPaaS', aliases: ['ipaas'], description: 'クラウド上で複数サービスやシステムをつなぐための統合基盤です。ノーコードやローコードで連携しやすいのが特徴です。' },
  { term: 'FinOps', aliases: ['finops'], description: 'クラウド費用を技術、財務、事業の協働で最適化する考え方です。単なる節約ではなく、価値に対する費用最適化を目指します。' },
  { term: 'Rightsizing', aliases: ['rightsizing'], description: 'リソースを過不足ない大きさへ見直すことです。大きすぎても小さすぎても無駄や障害につながります。' },
  { term: 'Zombie Resources', aliases: ['zombie resources'], description: '使われていないのに残り続けているクラウド資源です。費用の無駄だけでなく、管理漏れリスクにもなります。' },
  { term: 'Orphaned Disk', aliases: ['orphaned disk'], description: '本体がなくなったのに残存しているストレージです。見えにくいコストと情報残留の原因になります。' },
  { term: 'Egress Cost', aliases: ['egress cost'], description: '外部へデータを出すときの通信費です。クラウド間連携や大量配信で大きな差が出ることがあります。' },
  { term: 'コールドスタート', description: 'サーバーレスや一時停止環境が初回起動時に遅くなる現象です。低頻度処理では許容できても、対話系では工夫が必要です。' },
  { term: 'ウォームスタート', description: 'すでに起動済み環境を再利用して速く処理を始める状態です。コールドスタート対策と対になる考え方です。' },
  { term: 'バーストキャパシティ', description: '短時間だけ通常以上の資源や性能を使える余力です。ピーク負荷対策として有効ですが、持続可能時間を理解する必要があります。' },
  { term: 'Self-Service Infrastructure', aliases: ['self-service infrastructure'], description: '開発者が承認範囲内で自分たちで必要資源を用意できる仕組みです。待ち時間を減らしつつ、標準も守りやすくします。' },
  { term: 'クラウドアカウント', description: 'クラウド利用の契約、請求、権限の基本単位です。組織設計やガバナンスの土台になります。' },
  { term: 'テナント', description: 'クラウドやSaaSにおける論理的な利用単位です。企業単位や組織単位で分かれることがあります。' },
  { term: 'サブスクリプション', description: '利用契約や課金単位として使われる概念です。クラウドによって意味合いが少し異なります。' },
  { term: 'リソースグループ', aliases: ['resource group'], description: '関連するクラウド資源をまとめて管理する単位です。整理、権限、削除管理に役立ちます。' },
  { term: 'コンパートメント', description: '資源を論理的に分けて管理する単位です。権限や請求の分離にも使えます。' },
  { term: '可用性ゾーン', description: '同一リージョン内で独立性を持たせた設備単位です。障害分散の基本要素になります。' },
  { term: '仮想ネットワーク', description: 'クラウド上で論理的に構築するネットワークです。ベンダーごとに呼び方が異なります。' },
  { term: 'セキュリティルール', description: 'どの通信を許可、拒否するかを定めたルールです。最小権限の考え方が重要です。' },
  { term: 'オブジェクトストレージ', description: 'ファイルや非構造データを大量に保存する仕組みです。各クラウドで中核ストレージとして提供されています。' },
  { term: 'ブロックストレージ', description: '仮想ディスクのように使うストレージです。OSディスクやDB向けによく使われます。' },
  { term: 'ファイルストレージ', description: 'ファイル共有方式で扱うストレージです。既存業務の移行先として使われることがあります。' },
  { term: 'マネージドデータベース', description: '運用の一部をクラウド側が担うDBサービスです。バックアップや監視負担を減らしやすくなります。' },
  { term: 'サーバーレス実行環境', description: 'サーバー管理を強く意識せずにコード実行できる環境です。イベント駆動処理と相性がよいです。' },
  { term: 'コンテナ実行基盤', description: 'コンテナ化したアプリを動かす基盤です。移植性と運用効率の両立に役立ちます。' },
  { term: 'Kubernetesマネージドサービス', aliases: ['kubernetesマネージドサービス'], description: 'Kubernetesの制御面などをクラウドが管理するサービスです。運用負担を減らしつつKubernetesを使えます。' },
  { term: 'ロール', description: '役割単位で権限をまとめたものです。利用者やサービスへ権限付与するときに使います。' },
  { term: 'ポリシー', description: '何を許可、禁止するかを記述したルールです。IAMやネットワーク制御で重要です。' },
  { term: 'サービスプリンシパル', description: 'アプリケーションや自動処理が使う認証主体です。人のアカウントとは分けて管理します。' },
  { term: 'マネージドアイデンティティ', description: 'クラウドが資格情報管理を担う認証方式です。秘密情報の埋め込みを減らしやすくなります。' },
  { term: 'シークレットマネージャ', description: '秘密情報を安全に保管、配布するサービスです。APIキーや接続情報の管理に使います。' },
  { term: '監視サービス', description: 'メトリクス、ログ、アラートを扱う基盤です。障害検知と可観測性に関わります。' },
  { term: 'ログ基盤', description: 'アプリやインフラのログを集約、検索する仕組みです。障害調査や監査で必須です。' },
  { term: 'メトリクス基盤', description: 'CPUや応答時間などの数値を集約する仕組みです。傾向把握やアラート設定に使います。' },
  { term: '分散トレース基盤', description: '複数サービスをまたぐ処理の流れを追跡する基盤です。マイクロサービスで特に重要です。' },
  { term: 'メッセージングサービス', description: '非同期にメッセージを受け渡すための基盤です。疎結合なシステム構築に役立ちます。' },
  { term: 'キューサービス', description: '処理待ちデータを順番にためるサービスです。負荷平準化や再試行設計に向いています。' },
  { term: 'イベントバス', description: 'イベントを発行、購読するための仕組みです。イベント駆動設計の土台になります。' },
  { term: 'マネージドDNS', aliases: ['マネージドdns'], description: 'DNS管理をクラウド側で提供するサービスです。名前解決の可用性や運用性を高めやすいです。' },
  { term: '専用線接続サービス', description: 'オンプレミスとクラウドを専用回線でつなぐ仕組みです。安定性や低遅延が求められる場面で使います。' },
  { term: 'NATサービス', aliases: ['natサービス'], description: '内部資源が外向き通信するときに中継する仕組みです。外からの直接接続を防ぎやすくなります。' },
  { term: 'ハイブリッド接続', description: 'オンプレミスとクラウドを組み合わせて使う構成です。移行途中や既存資産活用でよく出ます。' },
  { term: 'マルチクラウド', description: '複数クラウドを組み合わせて利用する考え方です。コスト、冗長性、得意分野の使い分けに活用されます。' },
  { term: 'コンテナ実行プラットフォーム', aliases: ['container execution platform'], description: 'コンテナ化されたアプリケーションを実行するプラットフォームです。ポータビリティと運用効率の両立を支援します。' },
  { term: 'マネージドKubernetesサービス', aliases: ['マネージドkubernetesサービス', 'managed kubernetes service'], description: 'クラウドがKubernetesのコントロールプレーンなどを管理するサービスです。運用負担を減らしながらKubernetesを利用できます。' },
  { term: 'IAMロール', aliases: ['iamロール', 'role (cloud iam)'], description: 'ロール別に権限をグループ化したものです。ユーザーやサービスへの権限付与に使用します。' },
  { term: 'マネージドID', aliases: ['マネージドid', 'managed identity'], description: 'クラウドが認証情報を管理する認証方式です。コードにシークレットを埋め込まずに済みやすくなります。' },
  { term: 'モニタリングサービス', aliases: ['monitoring service'], description: 'メトリクス・ログ・アラートを扱うプラットフォームです。障害検知とオブザーバビリティに関わります。' },
  { term: 'ログプラットフォーム', aliases: ['log platform'], description: 'アプリケーションやインフラのログを集約・検索する仕組みです。障害調査や監査に不可欠です。' },
  { term: 'メトリクスプラットフォーム', aliases: ['metrics platform'], description: 'CPU使用率や応答時間などの数値を集約する仕組みです。トレンド分析やアラート設定に使用されます。' },
  { term: '分散トレーシングプラットフォーム', aliases: ['distributed tracing platform'], description: '複数サービスにまたがる処理の流れを追跡するプラットフォームです。マイクロサービスにおいて特に重要です。' },
  { term: 'APIゲートウェイサービス', aliases: ['apiゲートウェイサービス', 'api gateway service'], description: 'APIのエントリーポイントを一元管理する仕組みです。認証・レート制限・ルーティングの統一を容易にします。' },
  { term: 'クラウドネイティブ', aliases: ['cloud native'], description: 'クラウドの特性を前提に設計・開発する考え方。' },
  { term: 'ハイブリッドクラウド', aliases: ['hybrid cloud'], description: 'オンプレミスとクラウドなど異なる環境を組み合わせる構成。' },
  { term: 'ゼロトラストセキュリティ', aliases: ['zero trust security'], description: 'すべてのアクセスを都度検証する前提のセキュリティ設計。' },
  { term: 'DB基盤', aliases: ['db基盤', 'database platform'], description: 'データベースを安定稼働させるための基盤。' },
  { term: 'インフラ', aliases: ['infrastructure'], description: 'システムを支える基盤となる設備や環境。' },
  { term: 'サーバ', aliases: ['server'], description: 'システムやデータを提供するコンピュータ。' },
  { term: 'データベース', aliases: ['database'], description: 'データを整理して保存・利用する仕組み。' },
  { term: '移行', description: '旧システムや旧環境から、新システムや新環境へデータ、設定、運用を切り替える作業。' },
  { term: '移行リハーサル', description: '本番移行と同じ手順を事前に実施し、所要時間、手順漏れ、障害時対応を確認する訓練。' },
  { term: '冗長構成', description: '障害発生時もサービス継続できるよう、機器や系統を複数用意しておく構成。' },
  { term: '運用保守性', description: '障害対応、設定変更、監視、更新などを継続的に実施しやすい性質。' },
  { term: 'ブロックボリューム', description: 'サーバにディスクとして接続して利用する単位のストレージ。' },
  { term: 'OCI', aliases: ['oci'], description: 'Oracle社が提供するクラウド基盤サービス群の総称。' },
  { term: 'EXE-Cloud', aliases: ['exe-cloud'], description: 'システムエグゼが提供するクラウド導入・運用支援を含むサービスまたは提供形態の呼称。' },
  { term: 'AWS', aliases: ['aws'], description: 'Amazon社が提供するクラウドサービス群の総称。' },
  { term: 'Nginx', aliases: ['nginx'], description: 'Webサーバやリバースプロキシとして使われる高性能なミドルウェア。' },
  { term: 'スケーリング', description: '負荷に応じて資源量を増減すること。' },
  { term: 'Amazon Bedrock', aliases: ['amazon bedrock'], description: 'AWSが提供するフルマネージド型の基盤モデルAPI。複数LLMをAPIで利用できるクラウドサービス。' },
  { term: 'DBaaS', aliases: ['dbaas'], description: 'Database as a Serviceの略。クラウドプロバイダが提供するマネージドデータベースサービス。' },
  { term: 'dbPaaS', aliases: ['dbpaas'], description: 'データベース機能に特化したPaaSサービス。管理・スケーリングをプロバイダが担当する。' },
  { term: 'サーバレス', aliases: ['faas', 'serverless'], description: 'サーバの管理を意識せず関数単位でコードを実行できるクラウドコンピューティングモデル。' },
  { term: 'クラウドデザインパターン', aliases: ['cloud design patterns'], description: 'クラウド環境特有の課題（スケーリング・耐障害性・コスト最適化）を解決するデザインパターン集。' },
  { term: 'inode', aliases: ['アイノード'], description: 'Unixファイルシステムでファイルのメタデータ（所有者、パーミッション、タイムスタンプ、データブロック位置）を格納するデータ構造。' },
  { term: 'ハードリンク', aliases: ['hard link'], description: '同じinodeを参照する複数のファイルシステムエントリ。実体のコピーを作らず同じデータを複数の名前で参照でき、同一ファイルシステム内でのみ作成可能。' },
  { term: 'シンボリックリンク', aliases: ['symlink', 'symbolic link', 'ソフトリンク'], description: '別のファイルやディレクトリへのパスを参照するポインタファイル。異なるファイルシステム間でも作成でき、ln -sコマンドで作成する。' },
  { term: 'マウント', aliases: ['mount'], description: 'ファイルシステムをディレクトリツリーの指定した位置（マウントポイント）に接続する操作。mountコマンドで実行し、/etc/fstabで永続設定できる。' },
  { term: 'アンマウント', aliases: ['umount'], description: 'マウントされたファイルシステムをディレクトリツリーから切り離す操作。umountコマンドで実行し、使用中のファイルシステムはアンマウントできない。' },
  { term: 'ループバックデバイス', aliases: ['loop device', 'loopback device'], description: 'ファイルをブロックデバイスとして扱うための仮想デバイス（/dev/loop*）。ISOイメージファイルなどをマウントする際に使用する。' },
  { term: 'tmpfs', description: 'メモリ上に構築される仮想ファイルシステム。非常に高速で、/run、/tmp、/dev/shmなどに使用される。再起動でデータは消える。' },
  { term: 'パーティション', aliases: ['partition'], description: '物理ストレージデバイスを論理的に分割した領域。fdiskやgdiskで管理し、各パーティションに独立したファイルシステムを作成できる。' },
  { term: 'fdisk', description: 'MBRパーティションテーブルを操作するLinuxのコマンドラインツール。パーティションの作成・削除・変更に使用するが、2TB超のディスクにはgdiskを使う。' },
  { term: 'gdisk', aliases: ['gpt fdisk'], description: 'GPTパーティションテーブルを操作するコマンドラインツール。fdiskのGPT版で、2TB超のディスクや多数のパーティションに対応する。' },
  { term: 'parted', aliases: ['gnu parted'], description: 'MBR・GPT両方のパーティションテーブルを操作できる高機能パーティション管理ツール。スクリプトモードもあり自動化に適している。' },
  { term: 'LVM', aliases: ['lvm', 'logical volume manager'], description: 'Linuxの論理ボリュームマネージャ。物理ディスクを抽象化し、柔軟なサイズ変更やスナップショットが可能なボリューム管理を実現する。' },
  { term: '物理ボリューム', aliases: ['pv', 'physical volume'], description: 'LVMで管理される最小単位の物理ストレージ（ディスクやパーティション）。pvcrateコマンドで初期化してボリュームグループに追加する。' },
  { term: 'ボリュームグループ', aliases: ['vg', 'volume group'], description: 'LVMで複数の物理ボリュームをまとめた論理的なストレージプール。この中から論理ボリュームを切り出して使用する。' },
  { term: '論理ボリューム', aliases: ['lv', 'logical volume'], description: 'LVMのボリュームグループから切り出した仮想ディスク領域。サイズの動的変更、スナップショット作成などが可能でファイルシステムを作成して使用する。' },
  { term: 'pvs', description: 'LVMの物理ボリュームの情報（デバイス名、サイズ、使用量など）を一覧表示するコマンド。' },
  { term: 'vgs', description: 'LVMのボリュームグループの情報（名前、物理ボリューム数、サイズなど）を一覧表示するコマンド。' },
  { term: 'lvs', description: 'LVMの論理ボリュームの情報（名前、サイズ、属性など）を一覧表示するコマンド。' },
  { term: 'pvcreate', description: 'ディスクやパーティションをLVMの物理ボリュームとして初期化するコマンド。LVM管理下に置くための最初のステップ。' },
  { term: 'vgcreate', description: 'LVMの物理ボリュームをまとめてボリュームグループを作成するコマンド。vgcreate vg_name /dev/sda1の形式で使用する。' },
  { term: 'lvcreate', description: 'LVMのボリュームグループから論理ボリュームを切り出して作成するコマンド。サイズ指定、スナップショット作成などのオプションがある。' },
  { term: 'mdadm', aliases: ['multiple device administration'], description: 'LinuxでソフトウェアRAIDアレイを管理するコマンドラインツール。RAID0/1/5/6などの作成・監視・修復・管理を行う。' },
  { term: 'RAID0', aliases: ['raid0', 'ストライピング'], description: '複数ディスクにデータをストライプ分散するRAID構成。高速だが冗長性がなく、1台故障でデータが全損する。' },
  { term: 'RAID1', aliases: ['raid1', 'ミラーリング'], description: '2台以上のディスクに同一データをミラーリングするRAID構成。1台故障してもデータが失われない高い冗長性を持つ。' },
  { term: 'RAID5', aliases: ['raid5'], description: '3台以上のディスクにデータとパリティを分散するRAID構成。1台の故障に耐えられ、ストレージ効率と冗長性のバランスが良い。' },
  { term: 'RAID6', aliases: ['raid6'], description: '4台以上のディスクに2重パリティを分散するRAID構成。2台同時故障まで耐えられる高い冗長性を持つが書き込みオーバーヘッドが大きい。' },
  { term: 'ext4', aliases: ['fourth extended filesystem'], description: 'Linuxで最も広く使われるジャーナリングファイルシステム。ext3の後継でエクステント管理、遅延割り当て、大ファイルサポートを追加している。' },
  { term: 'xfs', description: '高性能なジャーナリングファイルシステム。SGIが開発しRHELのデフォルトファイルシステムとして採用。大容量ファイル・大規模環境に適する。' },
  { term: 'btrfs', aliases: ['b-tree filesystem', 'butter fs'], description: 'Oracleが開発したコピーオンライトベースのLinuxファイルシステム。スナップショット、サブボリューム、組み込みRAIDなど高度な機能を持つ。' },
  { term: 'mkfs', aliases: ['make filesystem'], description: 'ブロックデバイスやパーティションにファイルシステムを作成するコマンド。mkfs.ext4やmkfs.xfsのように形式を指定して使用する。' },
  { term: 'fsck', aliases: ['filesystem check'], description: 'ファイルシステムの整合性チェックと修復を行うコマンド。起動時に自動実行されるほか、アンマウント状態のファイルシステムに手動で実行できる。' },
  { term: 'tune2fs', description: 'ext2/ext3/ext4ファイルシステムのパラメータ（マウント回数制限、チェック間隔、ラベルなど）を調整するコマンド。' },
  { term: 'ディスククォータ', aliases: ['disk quota'], description: 'ユーザーまたはグループごとにディスク使用量の上限を設定するファイルシステム機能。quotaパッケージを使用してソフト/ハードリミットを設定できる。' },
  { term: 'lsblk', description: 'ブロックデバイス（ディスク、パーティション、LVM等）の情報をツリー形式で表示するコマンド。デバイスの構成把握に便利。' },
  { term: 'blkid', description: 'ブロックデバイスのUUID、ファイルシステムタイプ、ラベルなどの属性情報を表示するコマンド。/etc/fstabでのUUID指定確認に使用する。' },
  { term: 'ストレージマルチパス', aliases: ['multipath', 'device-mapper-multipath'], description: 'サーバーとストレージを複数の物理パスで接続して冗長性と性能を向上させる技術。Linuxではdevice-mapper-multipathで実現する。' },
  { term: 'tar', aliases: ['tape archive'], description: '複数ファイルをアーカイブ（.tar）にまとめるコマンド。gzip（.tar.gz）やbzip2（.tar.bz2）と組み合わせて圧縮アーカイブも作成できる。' },
  { term: 'gzip', aliases: ['gnu zip'], description: 'GNU圧縮ツール。.gzファイルの圧縮・展開を行い、tarと組み合わせてtar.gzアーカイブを作成するのに広く使用される。' },
  { term: 'bzip2', description: 'ブロックソートアルゴリズムを使用する圧縮ツール。gzipより高い圧縮率を持つが処理速度は遅い。.bz2ファイルを扱う。' },
  { term: 'xz', aliases: ['xz utils'], description: 'LZMAアルゴリズムを使用する高圧縮ツール。gzip/bzip2より高い圧縮率を実現し、カーネルソースコードの配布などに使用される。' },
  { term: 'zstd', aliases: ['zstandard'], description: 'Facebookが開発した高速圧縮アルゴリズムZstandard。gzipに近い圧縮率でzipより数倍高速な圧縮・展開が特徴で、btrfsやRPMでも採用されている。' },
  { term: 'rsync', description: 'ファイルやディレクトリを効率的に同期・バックアップするコマンド。差分転送アルゴリズムで変更部分のみ転送し、SSH経由のリモート同期も可能。' },
  { term: 'dd', aliases: ['data duplicator'], description: 'ファイルや標準入出力をブロック単位でコピー・変換するコマンド。ディスクイメージの作成、MBRのバックアップ、デバイスの初期化などに使用する。' },
  { term: 'cpio', description: 'ファイルをアーカイブ・展開するコマンド。findコマンドと組み合わせてよく使用される。RPMパッケージの内部形式にも使われている。' },
  { term: 'Bacula', aliases: ['bacula'], description: 'エンタープライズ向けのオープンソースバックアップソフトウェア。クライアント・サーバー型でネットワーク経由の大規模バックアップ管理が可能。' },
  { term: 'Amanda', aliases: ['amanda', 'advanced maryland automatic network disk archiver'], description: 'Advanced Maryland Automatic Network Disk Archiverの略。クライアント・サーバー型のオープンソースバックアップシステム。テープやディスクへのバックアップをサポートする。' },
  { term: 'スナップショットバックアップ', aliases: ['snapshot backup'], description: 'ファイルシステムやボリュームの特定時点の状態を瞬時に記録するバックアップ手法。LVMスナップショットやbtrfsサブボリュームを利用して一貫した状態を保存できる。' },
  { term: 'Well-Architected Framework', aliases: ['well-architected framework', 'aws well-architected'], description: 'AWSが提供するクラウドアーキテクチャ設計のベストプラクティス集。運用上の優秀性・セキュリティ・信頼性・パフォーマンス効率・コスト最適化・サステナビリティの6本柱でシステムを評価・改善する。' },
  { term: 'リザーブドインスタンス', aliases: ['reserved instance'], description: 'AWSでEC2などを1年または3年単位でコミットすることで最大75%の割引を得るコスト削減手法。オンデマンドより大幅に安価だが、キャパシティを事前に確保する必要がある。' },
  { term: 'Savings Plans', aliases: ['savings plans', 'aws savings plans'], description: 'AWSで特定の使用量を1年または3年コミットすることで割引を受ける柔軟な料金モデル。コンピューティングSavings Plansは複数サービスに適用でき、リザーブドインスタンスより汎用性が高い。' },
  { term: 'オンデマンドインスタンス', aliases: ['on-demand instance'], description: 'AWSで事前コミットなしに必要な時だけ利用できるEC2の料金モデル。最も柔軟だが単価は最も高い。短期・不規則なワークロードに適し、リザーブドインスタンスやスポットと組み合わせてコスト最適化する。' },
  { term: 'タグベースコスト管理', aliases: ['tag-based cost management', 'コスト配分タグ'], description: 'AWSリソースにプロジェクト・チーム・環境などのタグを付与し、そのタグを基にコストを集計・分析・チャージバックする管理手法。FinOpsにおける可視化の基盤となる。' },
  { term: 'EBS', aliases: ['ebs', 'elastic block store'], description: 'AWSが提供するEC2インスタンス向けの永続的ブロックストレージサービス。gp3・io2などのボリュームタイプがあり、スナップショットによるバックアップやAZをまたぐ利用はできないが高I/Oが必要なワークロードに適する。' },
  { term: 'SQS', aliases: ['sqs', 'simple queue service'], description: 'AWSのフルマネージドメッセージキューサービス。プロデューサーとコンシューマーを非同期に疎結合し、スケーラブルなメッセージング基盤を提供する。標準キューとFIFOキューがあり、デッドレターキューで失敗メッセージを管理する。' },
  { term: 'CloudFront', aliases: ['cloudfront'], description: 'AWSのグローバルCDN（コンテンツデリバリーネットワーク）サービス。世界中のエッジロケーションからコンテンツを配信し、レイテンシを低減する。S3・ALB・カスタムオリジンと統合でき、WAFやOACでセキュリティを強化する。' },
  { term: 'SNS', aliases: ['sns', 'simple notification service'], description: 'AWSのフルマネージドパブリッシュ/サブスクライブ通知サービス。トピックを介してSQS・Lambda・メール・HTTPエンドポイントなどの複数サブスクライバーへメッセージをファンアウト配信する。' },
  { term: 'EKS', aliases: ['eks', 'elastic kubernetes service'], description: 'AWSのマネージドKubernetesサービス。コントロールプレーンの管理をAWSに委ねながらKubernetesクラスタを運用できる。FargateやEC2ノードグループを組み合わせてワークロードを実行する。' },
  { term: 'App Runner', aliases: ['app runner', 'aws app runner'], description: 'AWSがコンテナイメージやソースコードから自動的にWebアプリケーションとAPIをビルド・デプロイ・スケール・運用するフルマネージドサービス。インフラ管理不要でHTTPSエンドポイントを即座に提供する。' },
  { term: 'CloudTrail', aliases: ['cloudtrail'], description: 'AWSアカウント内のAPI呼び出しを記録する監査ログサービス。誰が・いつ・どのリソースに対して何の操作を行ったかをS3やCloudWatch Logsに保存し、セキュリティ調査・コンプライアンス対応に活用する。' },
  { term: 'X-Ray', aliases: ['x-ray', 'aws x-ray'], description: 'AWSの分散トレーシングサービス。マイクロサービスやサーバーレスアプリケーション間のリクエストフローを可視化し、ボトルネックやエラーの根本原因を特定するデバッグ・パフォーマンス分析に使用する。' },
  { term: 'Transit Gateway', aliases: ['transit gateway', 'tgw'], description: '複数のVPC・オンプレミスネットワーク・VPNをハブとして集中接続するAWSのネットワーク中継サービス。スター型トポロジーでルーティングを一元管理し、大規模マルチVPC環境の接続設計を簡素化する。' },
  { term: 'PrivateLink', aliases: ['privatelink'], description: 'VPC内のリソースとAWSサービスまたはサードパーティサービスをインターネットを経由せずプライベートに接続するAWSの技術。VPCエンドポイントを介してトラフィックをAWSネットワーク内に閉じる。' },
  { term: 'VPCエンドポイント', aliases: ['vpcエンドポイント', 'vpc endpoint'], description: 'インターネットゲートウェイやNATデバイスを使わずにVPCからAWSサービスへプライベートに接続するための入口。ゲートウェイ型（S3・DynamoDB）とインターフェース型（PrivateLink）の2種類がある。' },
  { term: 'IAMポリシー', aliases: ['iamポリシー', 'iam policy'], description: '【クラウド】AWSリソースへのアクセス権限をJSON形式で定義したドキュメント。管理ポリシー（AWS管理・カスタマー管理）とインラインポリシーがあり、ユーザー・グループ・ロールにアタッチして最小権限の原則を実装する。 【OCI APEX】誰が何に何をできるかを定義するアクセス制御ルール。' },
  { term: 'AWS Certificate Manager', aliases: ['aws certificate manager', 'acm'], description: 'AWS上でSSL/TLS証明書をプロビジョニング・管理・自動更新するマネージドサービス。ALB・CloudFront・API GatewayなどのAWSサービスと統合でき、証明書の手動更新作業を排除する。' },
  { term: 'AWS Global Accelerator', aliases: ['aws global accelerator', 'global accelerator'], description: 'AWSのグローバルネットワークを活用してアプリケーションのパフォーマンスと可用性を向上させるサービス。エニーキャストIPを使って最寄りのAWSエッジからトラフィックをルーティングし、レイテンシを低減する。' },
  { term: 'AWS SAM', aliases: ['aws sam', 'sam', 'serverless application model'], description: 'AWSサーバーレスアプリケーションを定義・テスト・デプロイするためのオープンソースフレームワーク。CloudFormationの拡張であり、Lambda・API Gateway・DynamoDBなどをシンプルなYAMLで記述できる。' },
  { term: 'AWS CDK', aliases: ['aws cdk', 'cdk', 'cloud development kit'], description: 'TypeScript・Python・Javaなどの一般的なプログラミング言語でAWSインフラをコードとして定義するフレームワーク。高レベルの抽象化（Construct）を通じてCloudFormationテンプレートを生成し、再利用可能なインフラコンポーネントを作成する。' },
  { term: 'スポットフリート', aliases: ['spot fleet'], description: '複数のインスタンスタイプとAZにまたがるスポットインスタンスの集合をターゲット容量で管理するAWSの機能。インスタンスの中断リスクを分散しながら大規模なコスト削減を実現するバッチ・HPC用途に適する。' },
  { term: 'クラウドガバナンス', aliases: ['cloud governance'], description: 'クラウドリソースの利用ポリシー・コンプライアンス・コスト・セキュリティを組織的に管理するフレームワーク。AWS ControlTower・Organizations・Configなどのサービスを使ってガードレールを自動適用する。' },
  { term: 'コスト異常検出', aliases: ['cost anomaly detection', 'aws cost anomaly detection'], description: '機械学習を使ってAWSの支出の異常なスパイクを自動検出する機能。通常の支出パターンと乖離した費用増加を早期に検知してアラートを送り、予期しないクラウドコストの増大を防ぐ。' },
  { term: 'バジェットアラート', aliases: ['aws budgets alert', '予算アラート'], description: 'AWS Budgetsで設定した予算閾値をコストや使用量が超過・接近した際にメール・SNSで通知するアラート機能。FinOpsにおけるコスト超過の早期発見と対応に不可欠な管理ツール。' },
  { term: 'AWS Budgets', aliases: ['aws budgets', 'budgets'], description: 'AWSの使用コスト・使用量・予約カバレッジに対して予算を設定し、閾値超過時にアラートを発するコスト管理サービス。FinOpsプロセスにおける予算策定とモニタリングの中核ツール。' },
  { term: 'マルチアカウント戦略', aliases: ['multi-account strategy'], description: '本番・開発・テスト・セキュリティなど目的別にAWSアカウントを分割して管理する組織設計パターン。アカウント間の爆発半径を最小化し、コスト・ガバナンス・セキュリティの分離を実現する。' },
  { term: 'リージョンフェイルオーバー', aliases: ['region failover', 'リージョン間フェイルオーバー'], description: 'プライマリリージョンで障害が発生した際にセカンダリリージョンへトラフィックを切り替える高可用性設計。Route 53のヘルスチェック・Global Accelerator・クロスリージョンレプリケーションと組み合わせて実装する。' },
  { term: 'クロスリージョンレプリケーション', aliases: ['cross-region replication', 'crr'], description: 'データやリソースを別のAWSリージョンに自動的に複製する機能。S3・RDS・DynamoDBなどがサポートし、DR（災害復旧）・法規制への対応・低レイテンシアクセスを実現するために使用する。' },
  { term: 'サーバーレスアーキテクチャ', aliases: ['serverless architecture'], description: 'サーバーのプロビジョニングや管理なしにアプリケーションを構築・実行するアーキテクチャスタイル。AWS LambdaやAPI Gatewayを中心に構成され、使った分だけ課金される従量制でインフラ管理のオーバーヘッドを排除する。' },
  { term: 'コンテナオーケストレーション', aliases: ['container orchestration'], description: '多数のコンテナのデプロイ・スケーリング・ヘルスチェック・ネットワーキングを自動管理する技術。KubernetesとAmazon ECSが代表的で、マイクロサービスアーキテクチャの運用基盤として広く採用されている。' },
  { term: 'セキュリティバイデザイン', aliases: ['security by design'], description: 'セキュリティ対策を後付けではなく設計・開発の初期段階から組み込む原則。IAMの最小権限・暗号化・ネットワーク分離などをアーキテクチャ設計時に考慮し、根本的なセキュリティリスクを低減する。' },
  { term: 'コンプライアンスアズコード', aliases: ['compliance as code', 'cac'], description: 'コンプライアンス要件をコードで定義し、自動的に検証・適用するアプローチ。AWS ConfigルールやOPA（Open Policy Agent）を使ってインフラのコンプライアンス状態を継続的に監視・矯正する。' },
  { term: 'クラウドネイティブセキュリティ', aliases: ['cloud native security'], description: 'クラウド環境の特性（スケール・動的性・マルチテナント）に最適化したセキュリティ手法の総称。ゼロトラスト・最小権限・自動化・コードとしてのセキュリティ（SaC）を組み合わせてクラウドワークロードを保護する。' },
  { term: 'カオスエンジニアリング', aliases: ['chaos engineering'], description: '本番またはステージング環境に意図的に障害を注入してシステムの回復力を検証するエンジニアリング手法。NetflixのChaos Monkeyが先駆けで、障害への耐性を事前に発見し改善することで信頼性を高める。' },
  { term: 'リトライ戦略', aliases: ['retry strategy', 'リトライポリシー'], description: '一時的な障害（ネットワークエラー・レートリミット超過）に対して一定の間隔でリクエストを再試行する設計パターン。指数バックオフとジッターを組み合わせてリトライストームを防ぎながら回復力を高める。' },
  { term: 'パブサブパターン', aliases: ['pub/sub pattern', 'パブリッシュ/サブスクライブ'], description: 'メッセージの送信者（パブリッシャー）と受信者（サブスクライバー）を直接結合せず、トピックやチャネルを介して非同期に通信するメッセージングパターン。Amazon SNSやEventBridgeがこのモデルを実装する。' },
  { term: 'コールドストレージ', aliases: ['cold storage', 'アーカイブストレージ'], description: 'アクセス頻度が極めて低いデータを低コストで長期保存するためのストレージ層。Amazon S3 Glacier・S3 Glacier Deep Archiveが代表例で、取り出しに時間（数分〜数時間）がかかる代わりに保存コストを大幅に削減できる。' },
  { term: 'データライフサイクル管理', aliases: ['data lifecycle management', 'dlm'], description: 'データを作成・保存・アーカイブ・削除までのライフサイクル全体を通じてコストと要件を最適化する管理手法。S3ライフサイクルポリシーやAWS DLMを使ってEBSスナップショットを自動管理する。' },
  { term: 'ストレージクラス', aliases: ['storage class', 's3ストレージクラス'], description: 'Amazon S3でアクセスパターンやコスト要件に応じてデータを分類する層。Standard・Standard-IA・One Zone-IA・Glacier・Glacier Deep Archiveなどがあり、Intelligent-Tieringは自動的に最適な層へ移動する。' },
  { term: 'データ転送コスト', aliases: ['data transfer cost'], description: 'AWSリソース間またはインターネットへのデータ転送に発生する料金。リージョン間・AZ間・インターネットへの出力（エグレス）で課金され、アーキテクチャ設計時にデータ転送パスを考慮することでコストを削減できる。' },
  { term: 'エッジロケーション', aliases: ['edge location', 'pop'], description: 'CloudFrontやGlobal AcceleratorがコンテンツをキャッシュしてユーザーへDNS・HTTPコンテンツを提供するAWSの世界中に点在するデータセンター拠点。ユーザーに地理的に近い場所からコンテンツを配信しレイテンシを低減する。' },
  { term: 'CDNオリジン', aliases: ['cdnオリジン', 'cdn origin', 'オリジンサーバー'], description: 'CDNがコンテンツをキャッシュする元となるサーバーやサービス。CloudFrontではS3バケット・ALB・EC2・カスタムHTTPエンドポイントをオリジンとして設定でき、キャッシュミス時にオリジンからコンテンツを取得する。' },
  { term: 'Cost Explorer', aliases: ['cost explorer', 'aws cost explorer'], description: 'AWSの過去13ヶ月のコストと使用状況を可視化・分析するツール。サービス別・アカウント別・タグ別のコスト内訳を確認でき、将来の支出を予測するとともにリザーブドインスタンスの購入推奨も提供する。' },
  { term: 'Trusted Advisor', aliases: ['trusted advisor', 'aws trusted advisor'], description: 'AWSアカウントのベストプラクティス遵守状況をコスト最適化・セキュリティ・耐障害性・パフォーマンス・サービス制限の5カテゴリで自動チェックするサービス。Business/Enterpriseサポートプランで全チェック項目にアクセスできる。' },
  { term: 'AWS Pricing Calculator', aliases: ['aws pricing calculator', 'pricing calculator', '料金計算ツール'], description: 'AWSサービスの見積もりコストを事前にシミュレーションするWebツール。移行前のTCO比較やアーキテクチャ変更のコスト影響を見積もり、FinOpsにおける計画段階で活用される。' },
  { term: 'コンバーティブルRI', aliases: ['コンバーティブルri', 'convertible reserved instance'], description: 'AWSリザーブドインスタンスのうち、コミット期間中にインスタンスファミリー・OS・テナンシーを変更できる柔軟なタイプ。スタンダードRIより割引率は低いが将来のワークロード変化に対応しやすい。' },
  { term: 'コスト最適化ハブ', aliases: ['cost optimization hub', 'aws cost optimization hub'], description: 'AWS全アカウントのコスト最適化推奨事項（未使用リソース削除・RI/Savings Plans購入提案など）を一元的に集約して表示するダッシュボード。FinOpsチームが優先度の高い削減施策を効率的に特定できる。' },
  { term: 'マネージドサービス', aliases: ['managed service'], description: 'クラウドプロバイダーがOS・ミドルウェア・パッチ適用・スケーリング・バックアップなどの運用を代行するサービスモデル。RDS・EKS・ElastiCacheなどが該当し、インフラ運用負荷を削減して開発に集中できる。' },
  { term: 'フルマネージドサービス', aliases: ['fully managed service'], description: 'ユーザーがインフラを一切管理せず、プロビジョニングからスケーリング・障害対応まですべてクラウドプロバイダーが担うサービス。DynamoDB・Lambda・S3などが該当し、運用オーバーヘッドを最小化する。' },
  { term: 'CloudFormationスタック', aliases: ['cloudformationスタック', 'cloudformation stack'], description: 'AWS CloudFormationテンプレートから作成されるAWSリソースの集合単位。スタック単位でリソースのライフサイクルを管理し、一括作成・更新・削除ができる。ネストされたスタックで大規模テンプレートを分割管理する。' },
  { term: 'CodeCommit', aliases: ['codecommit', 'aws codecommit'], description: 'AWSが提供するフルマネージドのGitリポジトリホスティングサービス。IAMで認証管理され、CodePipeline・CodeBuild・CodeDeployと統合してCI/CDパイプラインを構成できる。' },
  { term: 'Immutable Deployment', aliases: ['immutable deployment', 'イミュータブルデプロイ'], description: '既存のサーバーやコンテナを変更せずに新バージョンのインスタンスを別途作成して切り替えるデプロイ戦略。変更の副作用がなく一貫した環境を保証し、問題発生時は旧インスタンスへの即時ロールバックが容易。' },
  { term: 'セッションマネージャー', aliases: ['session manager', 'aws ssm session manager'], description: 'AWS Systems Managerの機能の一つで、SSHポートやキーペアなしにEC2インスタンスへブラウザまたはCLIから安全に接続できるサービス。踏み台サーバーが不要になり、接続ログをCloudTrailで記録できる。' },
  { term: 'パッチマネージャー', aliases: ['patch manager', 'aws patch manager'], description: 'AWS Systems Managerの機能でEC2インスタンスのOSパッチを自動適用・管理するサービス。パッチベースラインとメンテナンスウィンドウを定義して組織全体のパッチコンプライアンスを維持する。' },
  { term: 'オートメーションランブック', aliases: ['automation runbook', 'ssm automation'], description: 'AWS Systems Manager Automationで定義する手順書。AWSリソースの作成・設定・修復などの運用タスクを自動化するステップを記述し、人的ミスなく一貫した運用処理を実行できる。' },
  { term: 'マルチAZフェイルオーバー', aliases: ['マルチazフェイルオーバー', 'multi-az failover'], description: 'プライマリAZで障害が発生した際にスタンバイAZへ自動的に切り替わる高可用性設計。RDS Multi-AZやALBが代表例で、RPO約0・RTO数分の回復目標を達成しSLAを維持する。' },
  { term: 'クロスアカウントアクセス', aliases: ['cross-account access'], description: 'あるAWSアカウントのIAMエンティティが別のAWSアカウントのリソースにアクセスする仕組み。IAMロールのAssumeRoleを使い、マルチアカウント環境でセキュアなリソース共有を実現する。' },
  { term: 'リソースポリシー', aliases: ['resource policy', 'resource-based policy'], description: 'IAMアイデンティティではなくリソース側にアタッチするアクセス制御ポリシー。S3バケットポリシー・KMSキーポリシー・Lambda リソースポリシーが代表例で、クロスアカウントアクセスの制御にも使用する。' },
  { term: 'スイッチロール', aliases: ['switch role', 'assumerole'], description: 'AWSコンソールまたはCLIで別のIAMロールに切り替えてそのロールの権限で操作する機能。マルチアカウント環境でアカウントを行き来したり、クロスアカウントでのリソース管理に使用する。' },
  { term: 'インスタンスプロファイル', aliases: ['instance profile'], description: 'EC2インスタンスにIAMロールを関連付けるためのコンテナ。インスタンスプロファイルを通じてEC2上のアプリケーションはインスタンスメタデータからIAMロールの一時認証情報を取得し、AWSサービスへアクセスする。' },
  { term: 'サービスリンクドロール', aliases: ['service-linked role'], description: 'AWSサービスが自身の代わりに他のAWSリソースを呼び出すために事前定義されたIAMロール。ECSやRDSなどのマネージドサービスが必要なリソース操作を行うために自動作成され、ユーザーが直接変更することはできない。' },
  { term: 'パーミッションバウンダリー', aliases: ['permission boundary', '権限境界'], description: 'IAMエンティティが持てる最大権限の上限を定めるマネージドポリシー。管理者がデベロッパーにIAMロール作成を委譲する際に、デベロッパーが自分以上の権限を持つロールを作れないよう制限するガードレールとして機能する。' },
  { term: 'サービスコントロールポリシー', aliases: ['service control policy'], description: 'AWS Organizationsで管理単位（OU・アカウント）に適用してメンバーアカウントで実行可能なAWSサービスとアクションを制限するポリシー。IAMポリシーより上位のガードレールとして機能しマルチアカウント統制の要となる。' },
  { term: 'AWS Marketplace', aliases: ['aws marketplace'], description: 'サードパーティ企業がAWS上で動作するソフトウェア・SaaS・データ製品を提供するオンラインストア。既存のAWSアカウントで購入・デプロイでき、利用料はAWS請求に統合されてコスト管理を一元化できる。' },
  { term: 'タグポリシー', aliases: ['tag policy', 'aws tag policies'], description: 'AWS Organizations全体でリソースタグの命名規則を強制するガバナンス機能。許可されたタグキー・値を定義してコスト配分タグの一貫性を保ち、組織全体のFinOps施策を支える基盤となる。' },
  { term: 'コストと使用状況レポート', aliases: ['cost and usage report', 'cur'], description: 'AWSの最も詳細なコストデータをCSV形式でS3に配信するレポートサービス。使用量・料金・リソースタグをリソース単位で時間粒度で提供し、AthenやQuickSightと組み合わせてFinOps分析基盤を構築できる。' },
  { term: 'タグ付け戦略', aliases: ['tagging strategy', 'リソースタグ戦略'], description: 'クラウドリソースに付与するタグのキー・値の命名規則・必須タグセットを組織全体で標準化する取り組み。環境・プロジェクト・チーム・コストセンターなどの軸で統一することでコスト可視化と自動化を実現する。' },
  { term: 'FinOps成熟度', aliases: ['finops成熟度', 'finops maturity', 'finops maturity model'], description: 'FinOps Foundationが定義するFinOps実践の成熟度フレームワーク。クロール（基本的可視化）→ウォーク（最適化開始）→ラン（自動化・高度分析）の3段階で組織のFinOps能力を評価・向上させる。' },
  { term: 'ユニットエコノミクス', aliases: ['unit economics', 'クラウドユニットエコノミクス'], description: 'クラウドコストをビジネスの単位（ユーザー1人あたり・トランザクション1件あたりなど）に紐付けて効率性を測定するFinOps指標。クラウド支出がビジネス成長と比例しているか、または効率化されているかを評価する。' },
  { term: 'クラウドROI', aliases: ['クラウドroi', 'cloud roi', 'クラウド投資対効果'], description: 'クラウド投資から得られるビジネス価値（コスト削減・開発速度向上・売上寄与）と総費用を比較した投資対効果指標。FinOpsにおいてクラウド化の正当性を示しさらなる投資判断の根拠となる。' },
  { term: 'Total Cost of Ownership', aliases: ['total cost of ownership', '総所有コスト'], description: 'システムの購入・導入費用だけでなく運用・保守・廃棄まで含めた生涯コストの総計。オンプレミスからクラウドへの移行判断やプロバイダー比較において、隠れたコストを含めた真の費用対効果を評価するために使用する。' },
  { term: 'VPCフローログ', aliases: ['vpcフローログ', 'vpc flow logs'], description: 'VPC内のネットワークインターフェースを通過するIPトラフィック情報を記録するAWS機能。送信元/宛先IP・ポート・プロトコル・許可/拒否の結果をCloudWatch LogsまたはS3に出力し、ネットワーク監視・セキュリティ調査に活用する。' },
  { term: 'Lambda同時実行数', aliases: ['lambda同時実行数', 'lambda concurrency', '同時実行制限'], description: 'AWS Lambdaで同時に処理できる関数インスタンス数の上限。リージョンデフォルト制限とリザーブドコンカレンシー（特定関数用割り当て）があり、スロットリングによるリクエスト失敗を防ぐための管理が重要。' },
  { term: 'DynamoDB DAX', aliases: ['dynamodb dax', 'dax', 'dynamodb accelerator'], description: 'AmazonDynamoDBのためのフルマネージドインメモリキャッシュクラスター。マイクロ秒単位のレイテンシを実現し、読み取りヘビーなワークロードでDynamoDBへのリクエスト数を大幅に削減してコストとパフォーマンスを改善する。' },
  { term: 'SQSデッドレターキュー', aliases: ['sqsデッドレターキュー', 'dead letter queue', 'dlq'], description: 'SQSで処理に繰り返し失敗したメッセージを自動的に転送する専用キュー。失敗メッセージを隔離して調査・再処理を可能にし、メッセージの消失を防ぐ。LambdaのイベントソースにもDLQを設定できる。' },
  { term: 'Lambda レイヤー', aliases: ['lambda レイヤー', 'lambda layer'], description: 'Lambda関数間で共有するライブラリ・カスタムランタイム・設定ファイルをパッケージングする仕組み。関数コードとライブラリを分離して関数パッケージサイズを削減し、共通依存関係を複数関数で再利用できる。' },
  { term: 'Amazon Aurora Serverless', aliases: ['amazon aurora serverless', 'aurora serverless', 'aurora serverless v2'], description: 'Auroraをサーバーレスで提供する構成オプション。ワークロードに応じてキャパシティを自動でスケールアップ/ダウンし、アイドル時はコンピューティングを停止できる。変動の大きなトラフィックや開発環境のコスト最適化に適する。' },
  { term: 'データベースプロキシ', aliases: ['rds proxy', 'amazon rds proxy'], description: 'Lambda等のサーバーレスやマイクロサービスからRDS/Auroraへの接続をプールして管理するフルマネージドプロキシ。コネクション数の急増によるDB過負荷を防ぎ、フェイルオーバー時のアプリ影響を最小化する。' },
  { term: 'EBSスナップショット', aliases: ['ebsスナップショット', 'ebs snapshot'], description: 'Amazon EBSボリュームの特定時点のバックアップをS3に増分保存する機能。AMI作成の基盤となり、別AZやリージョンへのコピーを通じたDR戦略にも活用される。AWS Backupで自動化して保持ポリシーを管理する。' },
  { term: 'RI購入計画', aliases: ['ri購入計画', 'ri purchase planning', 'リザーブドインスタンス購入計画'], description: '安定したワークロードに対してリザーブドインスタンスを計画的に購入してコスト削減を最大化するFinOpsプロセス。Cost ExplorerのRI推奨レポートを分析し、カバレッジ率・使用率を継続的にモニタリングする。' },
  { term: 'プロビジョニング', aliases: ['provisioning'], description: 'クラウドリソース（サーバー・ネットワーク・データベースなど）をユーザーが利用できる状態に設定・割り当てるプロセス。IaCツールによる自動プロビジョニングは手動作業を排除し、一貫性のある環境を素早く構築する。' },
  { term: 'AWS Configルール', aliases: ['aws configルール', 'config rule'], description: 'AWS Configでリソースの設定が組織のポリシーに準拠しているかを評価するルール定義。AWSマネージドルールとカスタムLambdaルールがあり、非準拠リソースを検出してAuto Remediationで自動修復することもできる。' },
  { term: 'プロジェクト別コスト追跡', aliases: ['project-based cost tracking'], description: 'クラウドリソースにプロジェクトや製品を示すタグを付与し、プロジェクト単位でコストを集計・レポートするFinOps手法。エンジニアリングとファイナンスの協働でコストアカウンタビリティを各チームに持たせる。' },
  { term: 'クラウドコスト管理', aliases: ['cloud cost management', 'ccm'], description: 'クラウド支出の可視化・最適化・ガバナンスを継続的に行うプラクティスの総称。FinOpsの中核をなし、タグ戦略・予算アラート・RI/Savings Plans・不使用リソース削除などの施策を組み合わせてクラウド費用を管理する。' },
  { term: 'マイクロサービスメッシュ', aliases: ['microservice mesh'], description: 'サービスメッシュをマイクロサービスアーキテクチャに適用した構成。Envoyなどのサイドカープロキシが各サービスに注入され、サービス間のトラフィック管理・mTLS・サーキットブレーカー・可観測性を担う。' },
  { term: 'TCO分析', aliases: ['tco分析', 'tco analysis', 'total cost analysis'], description: 'オンプレミス環境とクラウド環境の総所有コストを比較分析する手法。ハードウェア・ライセンス・人件費・電力・スペースなどの全コストをクラウドの利用料と比較し、クラウド移行の経済的正当性を評価する。' },
  { term: '複数AZ配置', aliases: ['複数az配置'], description: '複数のアベイラビリティゾーンに分けてシステムを配置する構成です。' },
  { term: '複数AZ', aliases: ['複数az'], description: '複数のアベイラビリティゾーンを使って冗長化する構成です。' },
];
