// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: devopsCicd (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // devops (117), ci-cd (47), version-control (23), build (4), dependency-management (2), CI/CD (2), Dependency Management (2)
  { term: 'リリース管理', aliases: ['release management'], description: '本番反映の計画、承認、手順、切り戻しまで含めて管理することです。単にデプロイする作業ではなく、業務影響と復旧手段まで含めて考えます。' },
  { term: 'コンテナ', aliases: ['container'], description: 'アプリと必要な実行環境をひとまとめにして動かす仕組みです。開発環境と本番環境の差を小さくしやすいのが大きな利点です。' },
  { term: 'Kubernetes', aliases: ['kubernetes'], description: 'コンテナを大規模に運用管理するための仕組みです。高機能ですが学習コストも高く、必要性を見極めて採用することが重要です。' },
  { term: 'Docker', aliases: ['docker'], description: 'コンテナの作成、配布、実行を扱いやすくする代表的な技術です。開発現場ではローカル再現性の向上にもよく使われます。' },
  { term: 'ブルーグリーンデプロイ', description: '新旧二つの環境を用意して、切替でリリースする方法です。切り戻ししやすいのが大きな利点です。' },
  { term: 'カナリアリリース', description: '一部の利用者や一部の環境だけに新機能を先行適用する方法です。問題を小さな範囲で早期発見しやすくなります。' },
  { term: '切り戻し', description: 'リリース後に問題があれば、前の安定状態へ戻すことです。切り戻し手順を事前に持たないリリースは危険です。' },
  { term: 'IaC', aliases: ['iac'], description: 'Infrastructure as Codeの略で、インフラ設定をコードとして管理する考え方です。手作業より再現性が高く、レビューや履歴管理もしやすくなります。' },
  { term: 'Terraform', aliases: ['terraform'], description: 'IaCの代表的なツールのひとつです。複数クラウドをまたいで定義しやすいのが特徴です。' },
  { term: 'Ansible', aliases: ['ansible'], description: 'サーバー設定やアプリ展開を自動化するためのツールです。エージェントレスで扱いやすい点が特徴です。' },
  { term: 'CD', aliases: ['cd'], description: '継続的デリバリーまたは継続的デプロイの略です。変更を安全に届ける仕組みづくり全体を指します。' },
  { term: 'パイプライン', description: 'ビルド、テスト、デプロイなどを一連の流れで自動化したものです。工程の標準化と人的ミス削減に効果があります。' },
  { term: 'ブラックアウト期間', description: '【DevOps】重要な業務時期に変更やリリースを原則止める期間です。 【運用】重要業務時期のため変更を止める期間です。月末、決算期、商戦期などに設定されます。 【リリース】特定期間は変更を原則止める運用です。繁忙期や決算期などで使われます。' },
  { term: '自動化適性', description: 'その作業が自動化に向いているかを示す考え方です。繰り返し性、ルール明確性、例外率などが判断材料になります。' },
  { term: 'ステージング環境', description: '本番直前の確認用として使う環境です。最終リハーサルや受入確認に使われることが多いです。' },
  { term: '作業ブランチ自動化', description: 'タスクごとにブランチを切り、AIが安全に変更を積めるようにすることです。衝突や誤上書きの防止に役立ちます。' },
  { term: 'ビルド再現性', description: '同じ入力から同じ成果物を再び作れる性質です。検証、監査、供給網防御において重要です。' },
  { term: '再現可能ビルド', description: '環境差に左右されず、同一成果物を生成しやすいビルドの考え方です。意図しない差分混入を防ぎやすくなります。' },
  { term: '依存ピン留め', description: '外部部品のバージョンを明確に固定することです。意図しない更新混入を防ぐ一方、更新遅延とのバランスが必要です。' },
  { term: 'ロックファイル', description: '実際に解決された依存関係を固定するファイルです。開発環境差異を減らしやすくなります。' },
  { term: 'ビルド再現性確保', aliases: ['build reproducibility'], description: '同じ入力から同じ成果物を生成できる性質です。検証・監査・サプライチェーン防御のために重要です。' },
  { term: '再現可能なビルド', aliases: ['reproducible build'], description: '環境の差異に関わらず同一の成果物を生成するビルド手法です。意図しない差分混入を防ぐのに役立ちます。' },
  { term: '依存バージョン固定', aliases: ['dependency pinning'], description: '外部コンポーネントのバージョンを明示的に固定することです。意図しない更新による混入を防ぎますが、更新遅延とのバランスが必要です。' },
  { term: 'ロックファイル管理', aliases: ['lock file'], description: '実際に解決された依存関係を固定するファイルです。開発環境間の差異を減らすのに役立ちます。' },
  { term: 'リリーストレイン', description: '【DevOps】決まった周期でまとめてリリースしていく運用方式です。 【ソフトウェアエンジニアリング】決まった周期でまとめてリリースしていく運用方式です。個別最適より全体調整を重視したいときに有効です。 【リリース】決まった時刻表どおりにリリース便を出す考え方です。個別事情より全体運用の安定を重視したいときに向きます。' },
  { term: 'リリースエンジニアリング', aliases: ['release engineering'], description: '安全かつ再現可能に成果物を配布するための技術と運用全体です。開発と運用の橋渡しとして非常に重要です。' },
  { term: 'ビルドパイプライン', aliases: ['build pipeline'], description: 'ソースコードから成果物を生成する自動化の流れです。毎回同じ手順で作れることが品質の土台になります。' },
  { term: 'デプロイパイプライン', aliases: ['deploy pipeline'], description: '成果物を各環境へ展開する自動化の流れです。環境ごとの差分管理と承認プロセスを含めて設計する必要があります。' },
  { term: 'パイプライン失敗解析', aliases: ['pipeline failure analysis'], description: 'CI/CD途中で失敗した原因を追うことです。テスト失敗、依存取得失敗、環境差異など原因は多岐にわたります。' },
  { term: 'ビルドキャッシュ', aliases: ['build cache'], description: '前回結果を再利用してビルド時間を短縮する仕組みです。速度向上に有効ですが、汚染時の切り分けも考慮が必要です。' },
  { term: '増分ビルド', aliases: ['incremental build'], description: '変更部分だけを対象にビルドする方式です。大規模リポジトリで効果が高いですが、依存関係把握が重要です。' },
  { term: 'マトリクスビルド', aliases: ['matrix build'], description: '複数OS、複数バージョン、複数条件で並列にビルドやテストする方式です。互換性確認に役立ちます。' },
  { term: 'セルフホストランナー', description: '自前環境でCIジョブを実行する仕組みです。柔軟性は高いですが、管理責任も増えます。' },
  { term: '共有ランナー', aliases: ['shared runner'], description: '提供基盤上で共用されるCI実行環境です。準備が少なく始めやすい一方、制約や待ち時間が出ることがあります。' },
  { term: '環境昇格', aliases: ['environment promotion'], description: '開発、検証、本番など上位環境へ成果物を順に進めることです。同じものを昇格させる考え方が再現性を高めます。' },
  { term: 'アーティファクト昇格', aliases: ['artifact promotion'], description: '環境ごとに作り直さず、同一成果物を次環境へ進める方式です。本番との差異を減らしやすいです。' },
  { term: '環境プロモーション', aliases: ['environment promotion process'], description: '成果物や設定を段階的に上位環境へ進めることです。承認と検証を組み込むと統制しやすくなります。' },
  { term: '環境ロック', aliases: ['environment lock'], description: '同時に複数変更が入らないよう環境利用を制御する仕組みです。重要環境の競合反映を防ぎやすくなります。' },
  { term: 'デプロイウィンドウ', aliases: ['deploy window'], description: '反映を許可する時間帯や期間です。業務影響や監視体制に合わせて設計します。' },
  { term: 'リリースカット', aliases: ['release cut'], description: '今回リリースへ何を含め、何を外すかを決めることです。全部入れるより、リスクと価値のバランスで絞ることが多いです。' },
  { term: 'ブランチカット', aliases: ['branch cut'], description: 'リリース用ブランチを切ることです。以後の修正対象を安定化させやすくなります。' },
  { term: 'リリースブランチ', description: '本番へ出す候補を安定化するためのブランチです。新規開発と切り分けて最終調整しやすくなります。' },
  { term: 'ホットフィックス', description: '本番重大障害に対する緊急修正です。速さが重要ですが、通常品質確認をどこまで残すかの設計が必要です。' },
  { term: 'Cherry-pick', aliases: ['cherry-pick'], description: '特定コミットだけを別ブランチへ取り込む操作です。緊急対応では便利ですが、履歴複雑化に注意が必要です。' },
  { term: 'リリースタグ', aliases: ['release tag'], description: '特定バージョンを識別するためのラベルです。後から何を出したか追跡しやすくなります。' },
  { term: 'セマンティックバージョニング', aliases: ['semantic versioning'], description: '互換性の有無に応じて版番号の意味を持たせる考え方です。変更の重さが伝わりやすくなります。' },
  { term: 'メジャーバージョン', aliases: ['major version'], description: '破壊的変更を含む大きな版区切りです。利用者への周知と移行支援が重要になります。' },
  { term: 'マイナーバージョン', aliases: ['minor version'], description: '互換性を保ちつつ機能追加を行った版です。新価値追加の単位としてよく使われます。' },
  { term: 'パッチバージョン', aliases: ['patch version'], description: '主にバグ修正など小さな変更を示す版です。影響が小さいことを期待されますが、実際は検証が必要です。' },
  { term: 'ビルドメタデータ', aliases: ['build metadata'], description: 'どのコミット、どの環境で作られたかなど、成果物に付与する補足情報です。追跡性向上に役立ちます。' },
  { term: 'リリース候補版', aliases: ['release candidate'], description: '本番版に近い候補として扱う版です。最終確認や受入に使われることがあります。' },
  { term: 'ステージング検証', aliases: ['staging verification'], description: '本番に近い環境での最終確認です。ここを省くと、構成差異由来の事故が起こりやすくなります。' },
  { term: 'プレプロダクション環境', aliases: ['pre-production environment'], description: '本番直前の環境として使う準本番環境です。性能、権限、構成を本番へ近づけて確認する場になります。' },
  { term: 'インフラドリフト検知', aliases: ['infrastructure drift detection'], description: '定義と実環境のズレを見つけることです。手作業変更の放置を防ぐうえで重要です。' },
  { term: '構成差分比較', aliases: ['configuration diff comparison'], description: '環境間や定義間の違いを比較することです。開発では動くが本番で動かない問題の予防に役立ちます。' },
  { term: 'リリース監査証跡', aliases: ['release audit trail'], description: '誰が何をいつ出したか追える記録です。障害調査や監査で非常に重要です。' },
  { term: '変更セット', aliases: ['change set'], description: '一回の反映でまとめて扱う変更のまとまりです。粒度が大きすぎるとリスクが上がり、小さすぎると管理コストが増えます。' },
  { term: 'デプロイ健全性チェック', aliases: ['deploy health check'], description: '反映後に期待どおり立ち上がっているかを確認する自動または手動チェックです。単なる完了ログより実用的です。' },
  { term: 'ポストデプロイフック', aliases: ['post-deploy hook'], description: '反映後に自動で行う追加処理です。キャッシュクリア、通知、検証実行などに使えます。' },
  { term: 'プレビルド検証', aliases: ['pre-build verification'], description: '本格ビルド前に設定や依存関係の不備を確認することです。重い処理に入る前に落とせると効率がよくなります。' },
  { term: 'デプロイ頻度', aliases: ['deploy frequency'], description: 'どのくらいの頻度で本番へ変更を出せるかの指標です。高いほどよいとは限りませんが、変更の小ささと運用成熟度を示すことがあります。' },
  { term: '変更失敗率', aliases: ['change failure rate'], description: '反映した変更のうち、障害やロールバックにつながった割合です。速度だけでなく、安定性との両方を見るのに使われます。' },
  { term: 'デプロイメントヘルス', aliases: ['deployment health'], description: '今回の反映が健全に進んだかを示す概念です。成功ログだけでなく、遅延や警告も含めて見る必要があります。' },
  { term: 'ロールフォワード', aliases: ['roll forward'], description: '問題を戻すのではなく、さらに修正版を出して前へ進める対応です。構造的に戻しづらい変更で使われることがあります。' },
  { term: 'デプロイ凍結解除', aliases: ['deploy freeze lift'], description: '凍結していた変更制限を通常運用へ戻すことです。解除条件を明確にしておくと混乱を防ぎやすいです。' },
  { term: '継続的デリバリー成熟度', aliases: ['continuous delivery maturity'], description: 'どの程度安全かつ高速に継続配信できる状態かの度合いです。自動化だけでなく、レビューや運用文化も含まれます。' },
  { term: 'リリース準備完了', aliases: ['release readiness'], description: '本番へ出せる条件がそろった状態です。コード完成だけでなく、文書、運用、周知も含めて確認する必要があります。' },
  { term: '変更証明書', aliases: ['change certificate'], description: '変更内容、影響、承認、検証結果をまとめた証跡資料です。厳格な運用環境や規制業界で使われることがあります。' },
  { term: 'パイプラインテンプレート', aliases: ['pipeline template'], description: 'CI/CD定義を共通パターン化したものです。各案件の品質を底上げしやすくなります。' },
  { term: 'リリース標準化', aliases: ['release standardization'], description: '反映手順、承認、確認項目、記録形式をそろえることです。属人的な本番反映を減らし、事故を防ぎやすくします。' },
  { term: 'SVN', aliases: ['svn', 'subversion'], description: '中央集権型のバージョン管理システム。中央の1つのリポジトリを基準に更新していく方式。' },
  { term: 'Git', aliases: ['git'], description: '分散型バージョン管理システム。各開発者がリポジトリの完全な複製を持ち、ローカルでコミットやブランチ操作ができる。' },
  { term: 'git-svn', description: 'SVNリポジトリをGitとして操作したり、SVNからGitへ履歴付きで変換するためのコマンド。' },
  { term: 'Git LFS', aliases: ['git lfs', 'git large file storage'], description: '大容量ファイルをGitリポジトリ外で管理し、リポジトリの肥大化を防ぐ拡張機能。' },
  { term: 'Git Flow', aliases: ['git flow'], description: 'main、develop、feature、release、hotfixのブランチ構成で開発を進めるブランチ戦略。' },
  { term: 'ブランチ', description: 'コードの変更履歴を分岐させて、並行作業や機能開発を独立して進めるための仕組み。' },
  { term: 'タグ', description: '特定のコミットにバージョン番号やリリース名などの目印を付ける仕組み。' },
  { term: 'マージ', description: '分岐したブランチの変更を別のブランチに統合する操作。' },
  { term: 'feature branch', description: '新機能の開発を主系統と分離して進めるためのブランチ。' },
  { term: 'hotfix', description: '本番環境の緊急不具合を修正するために、リリース済みのコードから直接分岐して行う修正。' },
  { term: 'force push', description: 'リモートリポジトリの履歴を上書きして強制的に反映するpush操作。履歴改変のリスクがあるため、保護ブランチでは制限される。' },
  { term: '.gitkeep', description: 'Gitでは空ディレクトリを管理できないため、ディレクトリ構造を維持する目的で置かれる慣習的なファイル。' },
  { term: '.gitignore', description: 'Gitの追跡対象から除外するファイルやディレクトリのパターンを定義する設定ファイル。' },
  { term: 'コミット', description: 'ファイルの変更をリポジトリの履歴として記録する操作。' },
  { term: 'ブランチ戦略', description: 'チーム開発でブランチの作り方、命名、マージ方針を統一するための運用ルール。' },
  { term: '履歴', description: 'リポジトリに記録されたコミットの連なり。変更の追跡や復元に使う。' },
  { term: '差分', description: '変更前後の内容の違い。コードレビューやマージ判断の基礎情報になる。' },
  { term: '分散型バージョン管理', description: '各開発者が完全なリポジトリ複製を持ち、ネットワーク非接続でも作業できるバージョン管理方式。' },
  { term: '中央集権型', description: '1つの中央リポジトリを正とし、全員がそこに対して更新を行うバージョン管理方式。SVNが代表例。' },
  { term: '継続的インテグレーション', description: 'コードの変更をリポジトリに頻繁にマージし、自動ビルド・テストで品質を維持するプラクティス。' },
  { term: '継続的デリバリー', description: 'コードをいつでも本番リリースできる状態に保つプラクティス。テスト・ビルド・ステージングを自動化する。' },
  { term: '継続的デプロイ', aliases: ['continuous deployment'], description: 'テストを通過したコードを自動的に本番環境にデプロイするプラクティス。継続的デリバリーの上位概念。' },
  { term: 'Blue-Green Deployment', aliases: ['blue-green deployment'], description: '本番環境（Blue）と新バージョン環境（Green）を並行稼働させ、切り替えでゼロダウンタイムリリースを実現するデプロイ戦略。' },
  { term: 'Canary Release', aliases: ['canary release'], description: '新バージョンを少数のユーザーから段階的に展開し、問題がなければ全体に適用するリリース戦略。' },
  { term: 'ロールバック', aliases: ['rollback'], description: 'デプロイした変更に問題が発生した際、以前の安定バージョンに戻す操作。' },
  { term: 'Infrastructure as Code', aliases: ['infrastructure as code'], description: 'インフラの構成をコードとして記述・管理し、自動化・バージョン管理・再現性を実現する手法。' },
  { term: 'Platform Engineering', aliases: ['platform engineering', 'プラットフォームエンジニアリング'], description: '開発者が本番環境へのパスを自律的に利用できるよう内部開発者プラットフォーム（IDP）を構築・運用する規律。' },
  { term: 'Runbook', aliases: ['runbook'], description: '特定の運用手順・インシデント対応の手順書。自動化可能な手順をまとめたドキュメント。' },
  { term: 'Playbook', aliases: ['playbook'], description: '特定の状況や問題に対する対応手順・戦略をまとめた包括的な運用ドキュメント。Runbookより広い文脈で使われる。' },
  { term: 'Postmortem', aliases: ['postmortem'], description: 'インシデントや障害後に原因・影響・改善策を振り返るレポートと会議。' },
  { term: 'Blameless Postmortem', aliases: ['blameless postmortem', 'ブレームレスポストモーテム'], description: '個人を責めることなくシステムや手順の問題に焦点を当てるポストモーテム文化。心理的安全性を高め改善を促す。' },
  { term: 'ビルド設計', aliases: ['build design'], description: 'コンパイル・テスト・パッケージング・デプロイのビルドパイプラインを設計する活動。' },
  { term: 'パッケージング設計', aliases: ['packaging design'], description: 'アプリケーションをどのようなパッケージ・コンテナ・アーカイブ形式でリリースするかを設計する活動。' },
  { term: '観測容易性', aliases: ['observability'], description: 'システムの状態・動作をログ・メトリクス・トレースで外部から把握しやすい性質。Observabilityとも呼ぶ。' },
  { term: '監視設計', aliases: ['monitoring design'], description: '本番環境のメトリクス・ログ・アラートの収集・可視化・通知の仕組みを設計する活動。' },
  { term: 'バックアップ設計', aliases: ['backup design'], description: 'データ・システムの消失に備えたバックアップ方式・頻度・保管先・復元手順を設計する活動。' },
  { term: 'ArgoCD', aliases: ['argocd', 'argo cd'], description: 'Kubernetes向けのGitOpsベースの継続的デリバリーツール。GitリポジトリをSingle Source of Truthとして、クラスター上のアプリケーション状態を宣言的に管理・同期する。差分可視化と自動同期機能を持つ。' },
  { term: 'Jenkins', aliases: ['jenkins'], description: 'オープンソースの継続的インテグレーション/デリバリーサーバー。豊富なプラグインエコシステムを持ち、ビルド・テスト・デプロイのパイプラインを柔軟に構築できる。長年の実績を持つCI/CDの定番ツール。' },
  { term: 'CircleCI', aliases: ['circleci'], description: 'クラウドベースのCI/CDプラットフォーム。YAML設定ファイルでワークフローを定義し、Docker環境での高速なビルドとテスト実行を提供する。並列実行やキャッシュ機能でパイプラインを最適化できる。' },
  { term: 'GitLab CI', aliases: ['gitlab ci', 'gitlab ci/cd'], description: 'GitLabに統合されたCI/CDシステム。リポジトリ内の`.gitlab-ci.yml`でパイプラインを定義し、GitLab Runnerで実行する。コードホスティングからデプロイまでを一元管理できる。' },
  { term: 'Canary Deployment', aliases: ['canary deployment', 'カナリアデプロイ'], description: '新バージョンを全体の一部（カナリア）にのみ先行リリースし、問題がなければ段階的に展開するデプロイ手法。炭鉱のカナリアに由来し、リスクを最小化しながら本番環境での動作を検証できる。' },
  { term: 'Progressive Delivery', aliases: ['progressive delivery', 'プログレッシブデリバリー'], description: 'Feature Flag・カナリアデプロイ・A/Bテストなどを組み合わせ、新機能を段階的かつ制御された方法でリリースするデリバリー手法。リスクを分散しながら継続的にデプロイできる。' },
  { term: 'Pulumi', aliases: ['pulumi'], description: 'TypeScript・Python・Go・C#などの汎用プログラミング言語でインフラをコードとして定義するIaCツール。HCLではなく既存の言語スキルを活用でき、複雑なロジックや抽象化が書きやすい。' },
  { term: 'Chef', aliases: ['chef'], description: 'Rubyベースの構成管理ツール。サーバーの望ましい状態をRecipeとCookbookで記述し、Chef Clientが各ノードで実行して状態を収束させる。大規模インフラの自動化に使われる。' },
  { term: 'Puppet', aliases: ['puppet'], description: '宣言的な独自DSLでサーバー構成を記述する構成管理ツール。エージェントベースのアーキテクチャでPuppet Serverから各ノードに構成を配布する。エンタープライズ環境での実績が豊富。' },
  { term: '構成ドリフト', aliases: ['configuration drift', 'ドリフト検出'], description: 'サーバーや環境の実際の状態がIaCで定義された期待状態から乖離していく現象。手動変更や障害対応などで生じる。定期的なドリフト検出と修正によりインフラの一貫性を保つ必要がある。' },
  { term: 'プラン', aliases: ['terraform plan'], description: 'Terraformで`terraform plan`を実行した際に生成される、実際の変更を適用する前の差分プレビュー。追加・変更・削除されるリソースを確認でき、意図しない変更を防ぐ安全機構として機能する。' },
  { term: 'アプライ', aliases: ['terraform apply'], description: 'Terraformで`terraform apply`を実行して、プランで確認した変更を実際のインフラに適用する操作。プランを承認後に実行し、宣言的に定義されたインフラ状態を実現する。' },
  { term: 'Packer', aliases: ['packer'], description: 'HashiCorpが開発するマシンイメージ自動作成ツール。AMI・DockerイメージなどをコードのテンプレートとしてJSONまたはHCLで定義し、複数のプラットフォーム向けに一貫したイメージを生成できる。' },
  { term: 'AMI', aliases: ['ami'], description: 'Amazon Machine Imageの略。AWS EC2インスタンス起動に使用するマシンイメージ。OS・ミドルウェア・アプリケーションをあらかじめ含んだテンプレートで、イミュータブルインフラの基盤となる。' },
  { term: 'マシンイメージ', aliases: ['machine image'], description: '仮想マシンやクラウドインスタンス起動に使用するOSとソフトウェアを含んだテンプレートファイル。AMI・VMI・Docker imageなどが該当し、イミュータブルインフラにおける基本構成要素となる。' },
  { term: '環境変数管理', aliases: ['environment variable management'], description: 'APIキー・設定値などの環境変数を安全かつ一貫して管理する仕組み。ハードコードを避けてコードから設定を分離し、環境ごとに異なる値を提供する。Dotenv・クラウドシークレットストアなどで実装する。' },
  { term: '環境分離', aliases: ['environment isolation'], description: '開発・ステージング・本番などの異なる環境を論理的または物理的に分けて管理すること。設定・データ・インフラを環境ごとに独立させ、本番環境への影響を防ぎながら安全に開発・テストを行える。' },
  { term: 'プレビュー環境', aliases: ['preview environment', 'preview deploy'], description: 'プルリクエストやフィーチャーブランチごとに自動的に作成される一時的なデプロイ環境。実際のURLでコードレビューやQAを行えるため、マージ前の変更確認を効率化する。Vercel・Netlifyなどで標準的。' },
  { term: 'ephemeral環境', aliases: ['ephemeral environment', '一時環境'], description: '特定の目的（PRテスト・デモ・実験）のために短期間だけ作成され、不要になったら自動的に削除される一時的な環境。インフラコストを抑えながら独立したテスト環境を動的に提供する。' },
  { term: 'GitHub Flow', aliases: ['github flow'], description: 'GitHubが提唱するシンプルなブランチ戦略。mainブランチを常にデプロイ可能な状態に保ち、フィーチャーブランチからPRを経てmainにマージするシンプルなフロー。Git Flowより軽量で継続的デリバリーに向く。' },
  { term: 'Turborepo', aliases: ['turborepo'], description: 'Vercel製の高性能モノレポビルドシステム。タスクのキャッシュとリモートキャッシュ共有により、モノレポのビルドとCI時間を大幅に短縮する。パッケージ間の依存グラフを解析し並列実行を最適化する。' },
  { term: 'Nx', aliases: ['nx'], description: 'モノレポ向けのビルドシステム・CLIツール。依存グラフに基づく影響範囲分析で変更されたパッケージのみビルド・テストし、Nx Cloudによるリモートキャッシュで大規模モノレポのCI効率を最大化する。' },
  { term: 'Lerna', aliases: ['lerna'], description: 'JavaScriptモノレポの管理ツール。複数パッケージのバージョン管理・公開・依存関係のリンクを自動化する。npm workspacesやyarn workspacesと組み合わせて使われることが多く、monorepository管理の先駆けとなったツール。' },
  { term: 'changesets', description: 'モノレポにおけるバージョン管理とCHANGELOG生成を自動化するツール。PRに変更内容を記述したchangesetファイルを追加し、リリース時にsemverバージョンを自動計算してパッケージを公開する。' },
  { term: 'conventional commits', aliases: ['コンベンショナルコミット'], description: 'コミットメッセージの形式を`feat:`,`fix:`,`chore:`などのプレフィックスで統一する規約。CHANGELOG自動生成・semverバージョン自動計算・リリース自動化ツールと連携するための機械可読な形式を提供する。' },
  { term: 'release automation', aliases: ['リリース自動化'], description: 'バージョン計算・CHANGELOGの生成・タグ付け・パッケージ公開をCIパイプラインで自動化する仕組み。conventional commitsやchangesetsと組み合わせ、手動リリース作業を排除して一貫性のあるリリースを実現する。' },
  { term: 'デプロイゲート', aliases: ['deployment gate'], description: 'CI/CDパイプラインの特定ポイントに設けられた自動または手動のチェックポイント。品質チェック・セキュリティスキャン・承認などの条件をクリアしないと次のステージに進めず、不適切なデプロイを防ぐ。' },
  { term: 'デプロイ承認', aliases: ['manual approval'], description: '本番環境などへのデプロイ前に指定された承認者（人間）の明示的な許可を必要とするCI/CDの仕組み。GitHub ActionsのEnvironment保護ルールやGitLab CI のManual Approvalで実装される。' },
  { term: 'ワークフローエンジン', aliases: ['workflow engine'], description: 'タスクの実行順序・依存関係・スケジュールを管理し自動化するシステム。Apache Airflow・Temporal・AWS Step Functionsなどが代表例で、複雑な多段階処理を信頼性高く実行する基盤となる。' },
  { term: 'パイプラインオーケストレーション', aliases: ['pipeline orchestration'], description: 'CI/CDパイプライン内の複数ジョブやステージを、依存関係・条件分岐・並列実行を考慮して統合的に制御すること。複雑なデリバリープロセスを宣言的に定義し、信頼性と可視性を高める。' },
  { term: 'コンテナレジストリ', aliases: ['container registry', 'イメージレジストリ'], description: 'Dockerイメージなどのコンテナイメージを保存・管理・配布するリポジトリサービス。Docker Hub・Amazon ECR・GitHub Container Registryなどがあり、CI/CDパイプラインでビルドしたイメージを格納してデプロイで使用する。' },
  { term: 'ビルドトリガー', aliases: ['build trigger', 'pipeline trigger'], description: 'CI/CDパイプラインを起動させるイベント。コードのプッシュ・PRの作成・スケジュール・手動実行・Webhookなどが該当する。適切なトリガー設定によりビルドの頻度と目的を制御する。' },
  { term: 'エフェメラルランナー', aliases: ['ephemeral runner'], description: 'CI/CDのジョブを1回だけ実行して即座に廃棄される使い捨てのランナー（エージェント）。セキュリティとクリーンな実行環境を保証し、ジョブ間での状態汚染を防ぐ。GitHub ActionsのEphemeral Runnersが代表例。' },
  { term: 'シークレットスコープ', aliases: ['secret scope'], description: 'CI/CDシステムにおいてシークレット（APIキーや認証情報）が参照可能な範囲の定義。Organization・リポジトリ・環境（Environment）の3レベルで管理でき、最小権限の原則に基づいてアクセスを制限する。' },
  { term: 'environment protection rules', aliases: ['環境保護ルール', 'デプロイメント保護'], description: 'GitHub Actionsにおいて本番・ステージングなどの環境へのデプロイを保護するルール設定。承認者の指定・ブランチフィルター・待機時間などを設定でき、意図しないデプロイや不正アクセスを防ぐ。' },
  { term: 'デプロイメントロック', aliases: ['deployment lock', 'ステートロック'], description: 'デプロイ中に他のデプロイが同時実行されないようにロックする仕組み。競合するデプロイを防ぎ、環境の整合性を保つ。GitHub ActionsのConcurrencyグループやTerraformのステートロックが代表例。' },
  { term: 'Open Policy Agent', aliases: ['open policy agent', 'opa'], description: '汎用的なポリシーエンジン。RegoというDSLでポリシーを記述し、Kubernetes AdmissionController・Terraform・API認可など様々な場面でポリシーの評価・適用を一元化できる。CNCFの卒業プロジェクト。' },
  { term: 'Conftest', aliases: ['conftest'], description: 'TerraformのプランやKubernetesマニフェストなどの構造化データに対してOPA（Rego）ポリシーをテストするCLIツール。CI/CDパイプラインにポリシーチェックを組み込むことでガバナンスを自動化する。' },
  { term: 'Checkov', aliases: ['checkov'], description: 'Terraform・CloudFormation・Kubernetes・Dockerfileなどのインフラコードを静的解析してセキュリティとコンプライアンスの問題を検出するオープンソースツール。CI/CDパイプラインへの統合でDevSecOpsを推進する。' },
  { term: 'tfsec', description: 'TerraformコードのセキュリティリスクをCI段階で検出する静的解析ツール。AWSやGCPなどクラウドプロバイダーのベストプラクティスに基づくルールでS3バケットの公開設定ミスなどを検出する。' },
  { term: 'Trivy', aliases: ['trivy'], description: 'コンテナイメージ・ファイルシステム・Gitリポジトリ・IaCファイルの脆弱性やシークレット漏えいを包括的にスキャンするオープンソースのセキュリティスキャナー。CI/CDパイプラインへの統合が容易で幅広く採用されている。' },
  { term: 'SLSA', aliases: ['slsa', 'supply chain levels for software artifacts'], description: 'Supply chain Levels for Software Artifactsの略。Googleが提唱するソフトウェアサプライチェーンのセキュリティフレームワーク。ソースコード・ビルド・依存関係の整合性保証をレベル1〜4の段階で定義する。' },
  { term: 'スタック', aliases: ['stack', 'iacスタック'], description: 'Terraform・CloudFormationなどのIaCにおいて、一緒にデプロイ・管理されるリソースの集合単位。環境（dev/staging/prod）やサービスごとにスタックを分けることでリソース管理の境界を明確にする。' },
  { term: 'バックエンド設定', aliases: ['backend configuration', 'terraformバックエンド'], description: 'TerraformのステートファイルをどこにどのVように保存するかを定義する設定。S3+DynamoDBやTerraform Cloudなどのリモートバックエンドを使うことでチームでのステート共有とロック機能を実現する。' },
  { term: 'リモートステート', aliases: ['remote state'], description: 'Terraformのステートファイルをローカルではなくリモートストレージ（S3・GCS・Terraform Cloud）に保存する構成。チームでの同時作業時のステート競合を防ぎ、ステートのバックアップと共有を実現する。' },
  { term: 'モジュールレジストリ', aliases: ['module registry'], description: '再利用可能なTerraformモジュールを公開・共有するためのリポジトリ。Terraform Registryが公式で提供しており、VPCやEKSクラスターなどの実績あるモジュールを活用してインフラの標準化と再利用を促進できる。' },
  { term: 'プロビジョナー', aliases: ['provisioner'], description: 'TerraformでリソースのCREATEやDESTROY時にローカルやリモートマシン上でスクリプトを実行する仕組み。Terraform公式では最終手段として位置づけられており、可能な限りcloud-initやAnsibleで代替することが推奨される。' },
  { term: 'データソース', aliases: ['data source'], description: 'TerraformでIaC管理外の既存リソース情報を読み取るための宣言。`data`ブロックで定義し、他のリソースの設定値（VPC IDやAMI IDなど）を動的に参照するために使う。リソースを作成するのではなく読み取るだけ。' },
  { term: 'リソースグラフ', aliases: ['resource graph', '依存グラフ'], description: 'TerraformがHCLコードを解析して生成する、リソース間の依存関係を表す有向非循環グラフ（DAG）。このグラフに基づいて独立したリソースは並列に、依存するリソースは順次プロビジョニングされる。' },
  { term: 'ルートモジュール', aliases: ['root module'], description: 'Terraformを実行するディレクトリ内のHCLファイル群のこと。`terraform init`や`terraform plan`を実行するトップレベルのモジュールで、他のモジュールを呼び出してインフラ全体を構成する。' },
  { term: '本番環境', aliases: ['production environment', 'prod', 'production'], description: '実際のエンドユーザーが利用する本番稼働中の環境。他の環境と最も厳格に分離され、変更はCI/CDパイプラインを通じた承認フローを経てのみ適用される。可用性・セキュリティ・パフォーマンスが最優先される。' },
  { term: '開発環境', aliases: ['development environment', 'dev環境'], description: '開発者が機能開発やデバッグを行うための環境。本番と分離されており、試行錯誤やデータ汚染が許容される。ローカル環境・共有dev環境・クラウドdev環境などの形態があり、開発生産性を支える基盤となる。' },
  { term: 'カナリア分析', aliases: ['canary analysis', '自動カナリア分析'], description: 'カナリアデプロイ中に新旧バージョン間のエラー率・レイテンシ・ビジネス指標を自動的に比較分析する仕組み。Kayentaなどのツールで統計的に有意な差異を検出し、自動的にロールバックまたは展開継続を判断する。' },
  { term: 'デプロイ戦略', aliases: ['deployment strategy'], description: '新バージョンのアプリケーションをどのように本番環境に展開するかの方針。Recreate・Rolling Update・Blue-Green・Canaryなど複数の手法があり、ダウンタイム許容度・リスク・コストを考慮して選択する。' },
  { term: 'ゼロダウンタイムデプロイ', aliases: ['zero downtime deployment', 'ゼロダウンタイムリリース'], description: 'サービスを停止せずにアプリケーションの新バージョンをデプロイする手法の総称。Rolling Update・Blue-Green Deployment・Canary Deploymentなどの戦略によって実現し、ユーザー体験を損なわずにリリースを行う。' },
  { term: 'パッチリリース', aliases: ['patch release'], description: 'SemVerにおけるPATCH番号のインクリメント（例: 1.2.3→1.2.4）。後方互換性のあるバグ修正のみを含む小規模なリリース。ユーザーへの影響が最小限で、自動アップグレードが推奨されるリリース種別。' },
  { term: 'マイナーリリース', aliases: ['minor release'], description: 'SemVerにおけるMINOR番号のインクリメント（例: 1.2.0→1.3.0）。後方互換性を保ちながら新機能を追加するリリース。既存のAPIや動作は壊さず、新しい機能・改善・deprecation通知を含む。' },
  { term: 'メジャーリリース', aliases: ['major release'], description: 'SemVerにおけるMAJOR番号のインクリメント（例: 1.0.0→2.0.0）。後方互換性のない破壊的変更を含むリリース。API変更や動作変更を伴い、利用者は移行作業が必要になる可能性がある。' },
  { term: 'CHANGELOGの自動生成', aliases: ['changelogの自動生成', 'changelog生成', '自動changelog'], description: 'conventional commitsやchangesetsのデータをもとに、リリースごとの変更内容リストを自動的に生成する仕組み。手動での記述負荷をなくし、リリースノートを一貫したフォーマットで管理できる。' },
  { term: 'テストパイプライン', aliases: ['test pipeline'], description: 'CI/CDの中でテスト実行を担うパイプラインまたはステージ群。ユニットテスト・統合テスト・E2Eテスト・パフォーマンステストを自動実行し、品質ゲートとしてデプロイの可否を判断する。' },
  { term: 'ステージングパイプライン', aliases: ['staging pipeline'], description: '本番環境と同等の構成を持つステージング環境へのデプロイと検証を行うCI/CDパイプラインのフェーズ。本番前の最終確認環境として機能し、統合テスト・UAT・パフォーマンステストを実施する。' },
  { term: 'セキュリティスキャン', aliases: ['security scan', 'セキュリティチェック'], description: 'CI/CDパイプラインに組み込まれた自動セキュリティチェック。依存ライブラリの脆弱性・コンテナイメージのCVE・IaCの設定ミス・シークレット漏えいなどをビルド段階で検出してデプロイを阻止する。' },
  { term: 'SonarQube', aliases: ['sonarqube'], description: 'コードの静的解析プラットフォーム。バグ・コードスメル・セキュリティホットスポット・テストカバレッジを可視化し、品質ゲートを設定してCI/CDパイプラインで基準未満のコードのマージを防止する。' },
  { term: 'コードカバレッジゲート', aliases: ['coverage gate'], description: 'CI/CDパイプラインにおいてテストのコードカバレッジが設定した閾値（例: 80%）を下回った場合にビルドを失敗させる品質ゲート。カバレッジの低下を検知してテスト不足のコードのマージを防ぐ。' },
  { term: 'パフォーマンステスト', aliases: ['performance test'], description: 'システムの応答速度・スループット・リソース使用量などのパフォーマンス特性を計測するテスト。負荷テスト・ストレステスト・耐久テストなどを含み、CI/CDパイプラインに組み込んでパフォーマンス劣化を検出する。' },
  { term: 'サニティテスト', aliases: ['sanity test'], description: 'デプロイ直後や環境構築後に、システムの基本的な機能が正常に動作しているかを素早く確認する軽量なテスト。スモークテストに近いが、特定の機能が正常かの簡易確認に重点を置く点が異なる。' },
  { term: '回帰テスト自動化', aliases: ['regression test automation'], description: 'コード変更による既存機能の破損（デグレード）を検出するため、既存のテストスイートをCI/CDで自動実行する仕組み。デプロイのたびに全回帰テストが走ることで品質を継続的に担保する。' },
  { term: 'インフラテスト', aliases: ['infrastructure test', 'terratest'], description: 'IaCコードが意図したインフラを正しく構成するかを検証するテスト。Terratest・Kitchen-Terraform・Pulumi Testing APIなどを使い、実際にリソースをデプロイして動作を検証する統合テスト的アプローチ。' },
  { term: '内部開発者ポータル', aliases: ['idp', 'internal developer portal', 'backstage'], description: '開発者がサービス・APIドキュメント・インフラリソース・デプロイ履歴などを一か所から探せるセルフサービスの内部ポータル。BackstageなどのIDPにより、開発者の認知負荷を下げてゴールデンパスを提供する。' },
  { term: '平均復旧時間', aliases: ['mean time to recovery'], description: 'DORAメトリクスの一つ（MTTR）。本番環境で障害が発生してから復旧するまでにかかる平均時間。低いMTTRはインシデント対応能力と可観測性の高さを示し、ロールバックの自動化やカナリアデプロイが短縮に寄与する。' },
  { term: '変更リードタイム', aliases: ['lead time for changes', 'change lead time'], description: 'DORAメトリクスの一つ。コードのコミットから本番稼働までにかかる時間。エリートチームでは1時間未満を達成する。短いリードタイムはCI/CDパイプラインの効率と自動化の成熟度を反映する。' },
  { term: 'Kustomize', aliases: ['kustomize'], description: 'Kubernetesマニフェストを基本テンプレートに対するパッチや上書きで環境ごとにカスタマイズするツール。HelmのようなテンプレートエンジンではなくYAMLの差分合成で動作し、kubectl buildに統合されている。' },
  { term: 'Helmチャート', aliases: ['helmチャート', 'helm chart', 'helm'], description: 'Kubernetesアプリケーションのパッケージング形式。テンプレート化されたKubernetesマニフェストとデフォルト値（values.yaml）をまとめたもので、Helm CLIで管理・インストールする。複雑なK8sアプリの配布を標準化する。' },
  { term: 'Terraform Cloud', aliases: ['terraform cloud', 'hcp terraform'], description: 'HashiCorpが提供するTerraformのマネージドSaaS。リモートステート管理・リモート実行・VCS連携・コスト見積もり・Sentinelポリシー適用などを提供し、チームでのTerraform運用を一元化する。' },
  { term: 'DORAメトリクス', aliases: ['doraメトリクス', 'dora metrics'], description: 'DevOps Research and Assessmentが定義するソフトウェアデリバリーのパフォーマンス指標群。デプロイメント頻度・変更リードタイム・変更失敗率・平均復旧時間の4指標でエンジニアリング組織の成熟度を測る。' },
  { term: 'シフトレフト', aliases: ['shift left', 'シフトレフトテスト'], description: 'テスト・セキュリティ・品質チェックをソフトウェア開発ライフサイクルの早い段階（左側）に移動させるアプローチ。CI/CDパイプラインの早期段階でバグや脆弱性を発見することでコスト削減と品質向上を実現する。' },
  { term: 'Terragrunt', aliases: ['terragrunt'], description: 'TerraformのDRY（Don\'t Repeat Yourself）を実現するラッパーツール。複数環境・複数モジュール間でのバックエンド設定やプロバイダー設定の重複を排除し、大規模なTerraformコードベースの管理を容易にする。' },
  { term: 'Renovate', aliases: ['renovate', 'renovate bot'], description: '依存ライブラリのバージョンを自動的に更新するPRを作成するボット。Dependabotと並ぶ依存更新自動化ツールで、細かいスケジュール設定・自動マージルール・グループ更新など高度なカスタマイズが可能。' },
  { term: 'CHANGELOG自動生成', aliases: ['changelog自動生成', 'changelog auto-generation'], description: 'Gitコミット履歴やプルリクエスト情報から変更履歴ファイルを自動的に生成する機能です。リリースノートの作成を効率化します。' },
  { term: '手作業', description: '自動化せず人が直接実施する作業です。' },
  { term: 'SVN trunk 一本運用', aliases: ['svn trunk 一本運用'], description: 'ブランチをほとんど使わず、SVNのtrunkに変更を集中させて進める版管理運用です。' },
  { term: '依存管理', description: 'ライブラリやプラグインの追加、更新、削除、バージョン整合を管理することです。' },
  { term: 'ビルド', description: 'ソースコードから実行可能な成果物を生成する処理です。' },
  { term: 'マルチモジュール', description: '1つのリポジトリやビルド設定の中で、複数のモジュールに分けて管理する構成です。' },
  { term: 'バージョン散在', description: '依存ライブラリやプラグインのバージョン指定が複数箇所に散らばり、一元管理できていない状態です。' },
  { term: 'コンフリクト頻発構造', description: '同じファイルや同じ責務に変更が集中し、マージコンフリクトが起きやすい構造です。' },
  { term: 'DVCS', aliases: ['dvcs', '分散型バージョン管理システム', 'distributed version control system'], description: '各開発者がリポジトリの完全な履歴をローカルに保持する分散型の版管理システム。GitやMercurialが代表例で、オフライン作業・高速な履歴操作・中央サーバ障害耐性が特徴。集中型VCS（SVNなど）と対比される。' },
  { term: 'commit', description: '【バージョン管理】Gitでは変更内容を履歴として記録する操作です。データベースではトランザクションの結果を確定する操作です。 【データベース】データベーストランザクションの変更を確定し、永続化する操作です。' },
  { term: 'build', description: 'ソースコードをコンパイル・バンドルなどして実行可能な成果物を生成する工程です。' },
  { term: 'package manager', aliases: ['パッケージマネージャ'], description: 'ライブラリやパッケージのインストール・更新・削除を管理するツールです。npm、pip、Mavenなどがあります。' },
  { term: 'YAML', aliases: ['yaml', 'yaml ain\'t markup language'], description: 'インデントで階層を表す人間に読みやすいデータ記述形式です。設定ファイルやCI/CD定義でよく使われます。' },
];
