// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: awsServices (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // aws (239)
  { term: 'Amazon Web Services', aliases: ['amazon web services'], description: 'AWSのクラウドサービス群全体を指す名称です。' },
  { term: 'AWS Account', aliases: ['aws account'], description: 'AWS利用の基本単位となるアカウントです。' },
  { term: 'AWS Organizations', aliases: ['aws organizations'], description: '複数AWSアカウントをまとめて管理する仕組みです。' },
  { term: 'AWS Control Tower', aliases: ['aws control tower'], description: 'マルチアカウント環境を標準化して構築、統制しやすくする仕組みです。' },
  { term: 'Amazon VPC', aliases: ['amazon vpc'], description: 'AWS上の論理ネットワークを作るサービスです。' },
  { term: 'Subnet in AWS', aliases: ['subnet in aws'], description: 'VPC内を分割したネットワーク領域です。' },
  { term: 'Internet Gateway', aliases: ['internet gateway'], description: '【AWS】VPCをインターネットへ接続するためのゲートウェイです。 【OCI APEX】仮想ネットワークをインターネットへ接続する出口。' },
  { term: 'NAT Gateway', aliases: ['nat gateway'], description: '【AWS】プライベート側から外向き通信するための中継ゲートウェイです。 【OCI APEX】内部リソースが外向き通信のみ行うための中継装置。' },
  { term: 'AWS Transit Gateway', aliases: ['aws transit gateway'], description: '複数VPCやオンプレミス接続を集約するための中継基盤です。' },
  { term: 'AWS PrivateLink', aliases: ['aws privatelink'], description: 'プライベートネットワーク経由でサービスへ接続する仕組みです。' },
  { term: 'Elastic Load Balancing', aliases: ['elastic load balancing'], description: 'AWSのロードバランサー群の総称です。' },
  { term: 'Application Load Balancer', aliases: ['application load balancer'], description: 'L7で動作するロードバランサーです。' },
  { term: 'Network Load Balancer', aliases: ['network load balancer'], description: 'L4で動作する高性能なロードバランサーです。' },
  { term: 'Amazon Route 53', aliases: ['amazon route 53'], description: 'AWSのDNSサービスです。' },
  { term: 'Amazon CloudFront', aliases: ['amazon cloudfront'], description: 'AWSのCDNサービスです。' },
  { term: 'AWS WAF', aliases: ['aws waf'], description: 'Webアプリケーションを保護するためのファイアウォールサービスです。' },
  { term: 'AWS Shield', aliases: ['aws shield'], description: 'DDoS対策を支援するサービスです。' },
  { term: 'Amazon EC2', aliases: ['amazon ec2'], description: '仮想サーバーを提供するAWSの基本的なコンピュートサービスです。' },
  { term: 'Amazon Machine Image', aliases: ['amazon machine image'], description: 'EC2インスタンス作成の元になるイメージです。' },
  { term: 'Amazon EC2 Auto Scaling', aliases: ['amazon ec2 auto scaling'], description: 'EC2台数を自動で増減させる仕組みです。' },
  { term: 'AWS Lambda', aliases: ['aws lambda'], description: 'イベントに応じてコードを実行するサーバーレスサービスです。' },
  { term: 'Amazon ECS', aliases: ['amazon ecs'], description: 'コンテナを実行、管理するサービスです。' },
  { term: 'AWS Fargate', aliases: ['aws fargate'], description: 'サーバー管理なしでコンテナを実行できる基盤です。' },
  { term: 'Amazon EKS', aliases: ['amazon eks'], description: 'AWSのマネージドKubernetesサービスです。' },
  { term: 'Amazon ECR', aliases: ['amazon ecr'], description: 'コンテナイメージを保管するレジストリサービスです。' },
  { term: 'Amazon S3', aliases: ['amazon s3'], description: 'オブジェクトストレージサービスです。' },
  { term: 'Amazon S3 Glacier', aliases: ['amazon s3 glacier'], description: '長期保管向けのアーカイブストレージです。' },
  { term: 'Amazon EBS', aliases: ['amazon ebs'], description: 'EC2向けのブロックストレージです。' },
  { term: 'Amazon EFS', aliases: ['amazon efs'], description: '共有ファイルシステムを提供するサービスです。' },
  { term: 'Amazon RDS', aliases: ['amazon rds'], description: 'マネージドリレーショナルデータベースサービスです。' },
  { term: 'Amazon Aurora', aliases: ['amazon aurora'], description: 'RDS系の高性能マネージドリレーショナルデータベースです。' },
  { term: 'Amazon DynamoDB', aliases: ['amazon dynamodb'], description: 'マネージドNoSQLデータベースです。' },
  { term: 'Amazon ElastiCache', aliases: ['amazon elasticache'], description: 'インメモリキャッシュサービスです。' },
  { term: 'Amazon API Gateway', aliases: ['amazon api gateway'], description: 'APIの公開、制御、認証連携を行うサービスです。' },
  { term: 'Amazon SQS', aliases: ['amazon sqs'], description: 'メッセージキューサービスです。' },
  { term: 'Amazon SNS', aliases: ['amazon sns'], description: '通知配信を行うメッセージングサービスです。' },
  { term: 'Amazon EventBridge', aliases: ['amazon eventbridge'], description: 'イベント駆動連携を行うサービスです。' },
  { term: 'AWS Step Functions', aliases: ['aws step functions'], description: '複数処理をワークフローとして制御するサービスです。' },
  { term: 'Amazon Kinesis', aliases: ['amazon kinesis'], description: 'ストリーミングデータ処理のためのサービス群です。' },
  { term: 'Amazon Athena', aliases: ['amazon athena'], description: 'S3上のデータをSQLで分析するサービスです。' },
  { term: 'AWS Glue', aliases: ['aws glue'], description: 'データ統合やETLを支援するサービスです。' },
  { term: 'Amazon Redshift', aliases: ['amazon redshift'], description: 'データウェアハウスサービスです。' },
  { term: 'AWS IAM', aliases: ['aws iam'], description: '認証と権限管理の中核サービスです。' },
  { term: 'IAM Role', aliases: ['iam role'], description: '一時的に引き受ける権限のまとまりです。' },
  { term: 'AWS STS', aliases: ['aws sts'], description: '一時的な認証情報を発行するサービスです。' },
  { term: 'AWS Secrets Manager', aliases: ['aws secrets manager'], description: '秘密情報を安全に保管、取得するサービスです。' },
  { term: 'AWS KMS', aliases: ['aws kms'], description: '暗号鍵を管理するサービスです。' },
  { term: 'Amazon CloudWatch', aliases: ['amazon cloudwatch'], description: 'メトリクス、ログ、アラートを扱う監視サービスです。' },
  { term: 'AWS CloudTrail', aliases: ['aws cloudtrail'], description: 'AWS API操作の記録を残す監査サービスです。' },
  { term: 'AWS Config', aliases: ['aws config'], description: '設定状態や変更履歴を記録、評価するサービスです。' },
  { term: 'Amazon GuardDuty', aliases: ['amazon guardduty'], description: '脅威検知を支援するセキュリティサービスです。' },
  { term: 'AWS Security Hub', aliases: ['aws security hub'], description: 'セキュリティ検知結果を集約するサービスです。' },
  { term: 'AWS Systems Manager', aliases: ['aws systems manager'], description: '運用管理、設定、自動化を支援するサービス群です。' },
  { term: 'Parameter Store', aliases: ['parameter store'], description: 'Systems Managerの構成値、秘密情報の保管機能です。' },
  { term: 'AWS CloudFormation', aliases: ['aws cloudformation'], description: 'インフラをコードで定義、管理するサービスです。' },
  { term: 'AWS CodeBuild', aliases: ['aws codebuild'], description: 'ビルドを実行するCIサービスです。' },
  { term: 'AWS CodeDeploy', aliases: ['aws codedeploy'], description: 'アプリケーション配布を自動化するサービスです。' },
  { term: 'AWS CodePipeline', aliases: ['aws codepipeline'], description: 'ビルド、テスト、デプロイをつなぐパイプラインサービスです。' },
  { term: 'AWS Direct Connect', aliases: ['aws direct connect'], description: 'オンプレミスとAWSを専用線でつなぐサービスです。' },
  { term: 'AWS VPN', aliases: ['aws vpn'], description: 'オンプレミスや他環境とVPN接続するサービスです。' },
  { term: 'AWS Cloud Map', aliases: ['aws cloud map'], description: 'サービス検出を支援するサービスです。' },
  { term: 'AWS Backup', aliases: ['aws backup'], description: '各種AWS資源のバックアップを管理するサービスです。' },
  { term: 'AWS Well-Architected Framework', aliases: ['aws well-architected framework'], description: 'AWS上の設計をベストプラクティスで評価するための枠組みです。' },
  { term: 'ALB', aliases: ['alb'], description: 'HTTPやHTTPS通信を複数のアプリケーションへ振り分けるロードバランサー。' },
  { term: 'ECS', aliases: ['ecs', 'elastic container service'], description: 'コンテナ化したアプリケーションを実行・管理するサービス。' },
  { term: 'Fargate', aliases: ['fargate'], description: 'サーバ管理なしでコンテナを実行できるAWSの実行基盤。' },
  { term: 'RDS', aliases: ['rds', 'relational database service'], description: 'データベースの構築・運用を簡素化したマネージドDBサービス。' },
  { term: 'ElastiCache', aliases: ['elasticache'], description: '高速なキャッシュ領域を提供し、アプリケーション応答を改善するサービス。' },
  { term: 'CloudWatch', aliases: ['cloudwatch'], description: 'メトリクス、ログ、アラームを統合的に扱う監視サービス。' },
  { term: 'Cognito', aliases: ['cognito'], description: '利用者認証やID管理を行うためのサービス。' },
  { term: 'S3', aliases: ['s3', 'simple storage service'], description: '高い耐久性を持つオブジェクトストレージサービス。' },
  { term: 'EFS', aliases: ['efs', 'elastic file system'], description: '複数サーバから共有利用できるファイルストレージサービス。' },
  { term: 'Direct Connect', aliases: ['direct connect'], description: 'オンプレミスとAWSを専用線で接続するサービス。' },
  { term: 'Lambda', aliases: ['lambda'], description: 'サーバを意識せずにコードを実行できるサーバレスサービス。' },
  { term: 'Step Functions', aliases: ['step functions'], description: '複数処理の流れや分岐を定義して実行管理するワークフローサービス。' },
  { term: 'EventBridge', aliases: ['eventbridge'], description: 'イベントを契機に他サービス連携や処理起動を行うイベント連携基盤。' },
  { term: 'CodePipeline', aliases: ['codepipeline'], description: 'ビルド、テスト、デプロイの一連の流れを自動化するCI/CDサービス。' },
  { term: 'ECR', aliases: ['ecr', 'elastic container registry'], description: 'コンテナイメージを保管・管理するレジストリサービス。' },
  { term: 'ECS Fargate', aliases: ['ecs fargate'], description: 'AWSでサーバー管理を意識せずコンテナ実行できる仕組み。' },
  { term: 'EC2インスタンスタイプ', aliases: ['ec2インスタンスタイプ', 'ec2 instance type', 'instance type'], description: 'Amazon EC2で選択できるCPU・メモリ・ストレージ・ネットワーク帯域の組み合わせ仕様。汎用(M系)、コンピュート最適化(C系)、メモリ最適化(R系)、ストレージ最適化(I系)などファミリーが分かれており、ワークロードに応じて選択する。' },
  { term: 'EC2 Auto Scaling', aliases: ['ec2 auto scaling', 'auto scaling group', 'asg'], description: '負荷に応じてEC2インスタンス数を自動的に増減させるサービス。最小・希望・最大台数を設定し、CloudWatchメトリクスやスケジュールに基づいてスケールアウト/インを行い、可用性とコストを最適化する。' },
  { term: 'Lambda@Edge', aliases: ['lambda@edge', 'cloudfront lambda@edge'], description: 'Amazon CloudFrontのエッジロケーションでLambda関数を実行する機能。視聴者リクエスト・オリジンリクエスト・オリジンレスポンス・視聴者レスポンスの4フェーズで動作し、低レイテンシーなコンテンツカスタマイズやA/Bテストを実現する。' },
  { term: 'Amazon Lightsail', aliases: ['amazon lightsail', 'lightsail'], description: '仮想サーバー・ストレージ・データベース・ネットワークをまとめて提供するシンプルなクラウドサービス。月額固定料金で利用でき、WordPress等のウェブサイトや小規模アプリケーションを簡単に起動できる初心者向けサービス。' },
  { term: 'AWS Elastic Beanstalk', aliases: ['aws elastic beanstalk', 'elastic beanstalk', 'eb'], description: 'アプリケーションコードをアップロードするだけでEC2・ELB・Auto Scalingなどのインフラを自動的にプロビジョニングするPaaSサービス。Java、Python、Node.js等の主要言語をサポートし、インフラの詳細を意識せずにアプリを展開できる。' },
  { term: 'S3バケットポリシー', aliases: ['s3バケットポリシー', 's3 bucket policy', 'バケットポリシー'], description: 'Amazon S3バケットとそのオブジェクトへのアクセスをJSON形式で制御するリソースベースのポリシー。特定のAWSアカウント・IAMユーザー・IPアドレスからのアクセス許可・拒否を細かく設定でき、パブリックアクセスの制御にも使われる。' },
  { term: 'S3ライフサイクルポリシー', aliases: ['s3ライフサイクルポリシー', 's3 lifecycle policy', 'ライフサイクルルール'], description: 'Amazon S3オブジェクトの保存クラスを経過日数に応じて自動的に移行したり、期限切れオブジェクトを削除したりするルール。Standard→Standard-IA→Glacierという階層移行でコストを最適化できる。' },
  { term: 'S3 Glacier', aliases: ['s3 glacier', 'glacier'], description: '長期アーカイブ向けの低コストストレージサービス。Instant Retrieval・Flexible Retrieval・Deep Archiveの3ティアがあり、取り出し時間とコストのトレードオフで選択する。監査目的の長期データ保管に最適。' },
  { term: 'S3 Intelligent-Tiering', aliases: ['s3 intelligent-tiering', 's3 intelligent tiering', 'インテリジェントティアリング'], description: 'アクセスパターンを自動的に分析し、頻繁・低頻度・アーカイブの各ストレージクラスにオブジェクトを自動移動するS3ストレージクラス。アクセスパターンが予測できないデータのコスト最適化に有効。' },
  { term: 'S3 Transfer Acceleration', aliases: ['s3 transfer acceleration', 'transfer acceleration', '転送高速化'], description: 'CloudFrontのエッジロケーション経由でAmazon S3へのファイルアップロードを高速化する機能。地理的に離れたクライアントからの大容量データ転送を最適化されたネットワーク経路で行い、転送速度を大幅に改善する。' },
  { term: 'S3 Object Lock', aliases: ['s3 object lock', 'object lock', 'オブジェクトロック'], description: 'Amazon S3オブジェクトを指定期間または無期限に削除・上書きできないよう保護するWORM（Write Once Read Many）機能。金融・医療などの規制対応やランサムウェア対策に利用され、Governance・Complianceの2モードがある。' },
  { term: 'AWS Storage Gateway', aliases: ['aws storage gateway', 'storage gateway', 'ストレージゲートウェイ'], description: 'オンプレミスのアプリケーションとAWSクラウドストレージをシームレスに統合するハイブリッドクラウドストレージサービス。ファイルゲートウェイ・ボリュームゲートウェイ・テープゲートウェイの3種類があり、既存システムをクラウドに拡張する。' },
  { term: 'Amazon FSx', aliases: ['amazon fsx', 'fsx'], description: 'フルマネージドのサードパーティファイルシステムサービス。Windows File Server・Lustre・NetApp ONTAP・OpenZFSに対応しており、既存のワークロードやアプリケーションを最小限の変更でAWS上で実行できる。' },
  { term: 'RDSマルチAZ', aliases: ['rdsマルチaz', 'rds multi-az', 'multi-az配置'], description: 'Amazon RDSのプライマリDBインスタンスを別のアベイラビリティゾーンにスタンバイレプリカと同期させる高可用性構成。プライマリ障害時に自動フェイルオーバーが発生し、ダウンタイムを最小化する。' },
  { term: 'RDSリードレプリカ', aliases: ['rdsリードレプリカ', 'rds read replica'], description: 'Amazon RDSプライマリDBインスタンスから非同期レプリケーションで作成される読み取り専用のレプリカ。読み取りクエリをレプリカに分散させることでプライマリの負荷を軽減し、読み取りスループットをスケールさせる。' },
  { term: 'DynamoDBグローバルテーブル', aliases: ['dynamodbグローバルテーブル', 'dynamodb global tables', 'グローバルテーブル'], description: 'Amazon DynamoDBのテーブルを複数のAWSリージョンに自動レプリケーションする機能。各リージョンで読み書き可能なマルチアクティブ構成により、グローバルに低レイテンシーアクセスとディザスタリカバリを実現する。' },
  { term: 'Amazon MemoryDB', aliases: ['amazon memorydb', 'amazon memorydb for redis', 'memorydb'], description: 'Redisと互換性を持つ超高速でデュラブルなインメモリデータベースサービス。Redisと同じAPIを使いながらマルチAZトランザクションログで耐久性を保証し、プライマリデータベースとして利用できる。' },
  { term: 'Amazon Neptune', aliases: ['amazon neptune', 'neptune'], description: 'フルマネージドのグラフデータベースサービス。Property Graph（Gremlin）とRDF（SPARQL）の両方をサポートし、ソーシャルネットワーク・レコメンデーションエンジン・不正検出などの関係性が重要なユースケースに最適。' },
  { term: 'Amazon Timestream', aliases: ['amazon timestream', 'timestream', '時系列データベース'], description: 'IoTやアプリケーション監視向けのフルマネージド時系列データベースサービス。時系列データに最適化されたストレージと自動データ階層化により、リレーショナルDBの10倍以上の効率でデータを管理しコストを削減する。' },
  { term: 'Amazon QLDB', aliases: ['amazon qldb', 'qldb', 'quantum ledger database'], description: '改ざん防止の検証可能なトランザクション履歴を持つフルマネージド台帳データベース。暗号学的に検証可能なジャーナルにすべての変更を記録し、金融取引・サプライチェーン・保険など監査証跡が必要な用途に適する。' },
  { term: 'Amazon Keyspaces', aliases: ['amazon keyspaces', 'keyspaces', 'amazon keyspaces for apache cassandra'], description: 'Apache Cassandraと互換性を持つフルマネージドのワイドカラムデータベースサービス。既存のCassandraアプリケーションをコード変更なしに移行でき、自動スケーリングと高可用性を提供する。' },
  { term: 'Amazon DocumentDB', aliases: ['amazon documentdb', 'documentdb', 'amazon documentdb with mongodb compatibility'], description: 'MongoDBと互換性を持つフルマネージドのドキュメントデータベースサービス。JSON形式のデータを柔軟に保存・検索でき、既存のMongoDBドライバやツールをそのまま利用できる。ストレージは6つのコピーで自動レプリケーション。' },
  { term: 'Redshift Spectrum', aliases: ['redshift spectrum'], description: 'Amazon RedshiftからAmazon S3上のデータを直接クエリできる機能。データをRedshiftに取り込まずにS3のエクサバイト規模のデータを分析でき、データレイクとデータウェアハウスを統合したアーキテクチャを実現する。' },
  { term: 'Redshift Serverless', aliases: ['redshift serverless', 'amazon redshift serverless'], description: 'クラスターのプロビジョニング不要でRedshiftの分析機能を利用できるサーバーレスオプション。使用した分だけ課金されるため、断続的なワークロードやアドホッククエリに適しており、自動的にスケールする。' },
  { term: 'VPCピアリング', aliases: ['vpcピアリング', 'vpc peering', 'vpc peering connection'], description: '異なるVPC間をプライベートIPアドレスで通信させる接続方法。同一アカウント・異なるアカウント・異なるリージョン間でも設定可能だが、ルーティングは推移的ではなく直接接続したVPC間のみ通信できる。' },
  { term: 'CloudFrontオリジンアクセス', aliases: ['cloudfrontオリジンアクセス', 'origin access control', 'origin access identity', 'oai'], description: 'CloudFrontからS3バケットへのアクセスを制限し、CloudFront経由のみコンテンツを配信できるようにする仕組み。OAI（旧）とOAC（新）があり、S3バケットへの直接アクセスを防いでセキュリティを向上させる。' },
  { term: 'Route 53ヘルスチェック', aliases: ['route 53ヘルスチェック', 'route 53 health check', 'ヘルスチェック'], description: 'Amazon Route 53がエンドポイントの正常性を定期的に確認し、障害時に自動的にDNSフェイルオーバーを実行する機能。HTTP・HTTPS・TCPの各プロトコルに対応し、フェイルオーバーやレイテンシーベースルーティングと組み合わせて使用する。' },
  { term: 'NLB', aliases: ['nlb', 'nlb (network load balancer)'], description: 'レイヤー4（TCPおよびUDP）で動作するAWSのロードバランサー。超高スループットと低レイテンシーが特徴で、静的IPまたはElastic IPを割り当てられる。TCP・UDP・TLSトラフィックを処理し、ゲームや金融等のリアルタイムアプリに適する。' },
  { term: 'GLB', aliases: ['glb', 'gateway load balancer', 'gwlb'], description: 'サードパーティのネットワーク仮想アプライアンス（ファイアウォール・IDS/IPS等）をスケーラブルに展開するためのAWSロードバランサー。GENEVE プロトコルを使用してトラフィックをアプライアンスに透過的に転送し、ネットワークセキュリティを集中管理する。' },
  { term: 'Elastic IP', aliases: ['elastic ip', 'eip', 'elastic ip address'], description: 'AWSアカウントに割り当てられる静的なパブリックIPv4アドレス。インスタンスを停止・起動してもIPが変わらず、障害発生時に別インスタンスに即座に付け替えることで迅速なフェイルオーバーが可能。使用していない場合は課金される。' },
  { term: 'EC2スポットインスタンス', aliases: ['ec2スポットインスタンス', 'spot instance', 'ec2 spot'], description: 'AWSの余剰コンピューティング容量を最大90%割引で利用できるEC2インスタンス購入オプション。AWSがキャパシティを必要とする際に2分前通知で中断されるため、耐障害性のあるバッチ処理や機械学習トレーニングに適する。' },
  { term: 'EC2リザーブドインスタンス', aliases: ['ec2リザーブドインスタンス'], description: '1年または3年のコミットメントと引き換えにEC2インスタンスを最大72%割引で利用できる購入オプション。スタンダード型・コンバーティブル型・スケジュールド型があり、長期的に安定した需要のあるワークロードのコスト最適化に有効。' },
  { term: 'EC2専有ホスト', aliases: ['ec2専有ホスト', '専有ホスト'], description: '特定の顧客のみが使用する物理EC2サーバー。ソフトウェアライセンスのコンプライアンス要件（BYOL）や規制上の要件でハードウェアの占有が必要な場合に使用する。ソケット・コア・VM単位でのライセンス管理が可能。' },
  { term: 'AWS Batch', aliases: ['aws batch'], description: '数十万件規模のバッチコンピューティングジョブを効率的に実行するフルマネージドサービス。最適なコンピュートリソース量と種類を動的にプロビジョニングし、ジョブキューと依存関係管理によって大規模バッチ処理を自動化する。' },
  { term: 'Amazon WorkSpaces', aliases: ['amazon workspaces', 'workspaces', 'daas'], description: 'クラウド上でフルマネージドのWindows・Linuxデスクトップを提供するVDI（Desktop as a Service）サービス。物理PCの代わりにブラウザやクライアントアプリからデスクトップ環境にアクセスでき、リモートワーク環境の構築に利用される。' },
  { term: 'AWS Snowball', aliases: ['aws snowball', 'snowball', 'aws snow family'], description: 'ペタバイト規模のデータを物理デバイスを使ってAWSに移行するデータ転送サービス。インターネット経由での転送が困難な大量データをデバイスに書き込み、物理的にAWSデータセンターに送付することで高速にS3へ取り込める。' },
  { term: 'AWS DataSync', aliases: ['aws datasync', 'datasync'], description: 'オンプレミスやエッジのストレージとAWSストレージサービス間でデータを高速かつ自動的に転送・同期するサービス。NFS・SMB・S3互換ストレージをサポートし、帯域最適化・暗号化・整合性検証を自動で行う。' },
  { term: 'S3マルチパートアップロード', aliases: ['s3マルチパートアップロード', 'multipart upload', 'マルチパートアップロード'], description: '大容量ファイルを複数のパートに分割して並列アップロードするS3の機能。100MB以上のファイルに推奨され、転送失敗時に該当パートのみ再送できるため効率的。5MB以上のパートに分割して最大10,000パートまで並列転送できる。' },
  { term: 'S3レプリケーション', aliases: ['s3レプリケーション', 's3 replication', 'srr'], description: 'Amazon S3バケット間でオブジェクトを自動的にレプリケーションする機能。同一リージョン内のSRR（Same-Region Replication）と異なるリージョンへのCRR（Cross-Region Replication）があり、ディザスタリカバリやデータローカライゼーションに利用する。' },
  { term: 'EBSボリュームタイプ', aliases: ['ebsボリュームタイプ', 'ebs volume type', 'ボリュームタイプ'], description: 'Amazon EBSが提供するストレージ種別。汎用SSD（gp2/gp3）・プロビジョンドIOPS SSD（io1/io2）・スループット最適化HDD（st1）・コールドHDD（sc1）があり、IOPS・スループット・コストのバランスでワークロードに応じて選択する。' },
  { term: 'Aurora グローバルデータベース', aliases: ['aurora グローバルデータベース', 'aurora global database', 'auroraグローバルデータベース'], description: 'Amazon Auroraのプライマリリージョンから最大5つのセカンダリリージョンにデータをレプリケーションするグローバル展開機能。専用インフラでレプリケーションを行いラグを1秒未満に保ち、リージョン障害時のフェイルオーバーをサポートする。' },
  { term: 'DynamoDB オンデマンドモード', aliases: ['dynamodb オンデマンドモード', 'dynamodb on-demand', 'オンデマンドキャパシティモード'], description: '事前にキャパシティを設定せず実際のリクエスト数に応じて自動的にスケールし、処理したリクエスト数のみ課金されるDynamoDBの課金モード。トラフィックが予測困難なアプリや開発・テスト環境に適する。' },
  { term: 'ElastiCache Serverless', aliases: ['elasticache serverless', 'amazon elasticache serverless'], description: 'キャパシティのプロビジョニング不要でRedisおよびMemcachedキャッシュを即座に作成・スケールできるElastiCacheのサーバーレスオプション。数秒でキャッシュを作成でき、使用量に基づいて自動スケールと従量課金を実現する。' },
  { term: 'AWS Network Firewall', aliases: ['aws network firewall', 'network firewall'], description: 'VPCを保護するフルマネージドのネットワークファイアウォールサービス。ステートフルインスペクション・侵入検知・防止（IDS/IPS）・Webフィルタリングを提供し、Transit GatewayやGLBと組み合わせてセントラライズドネットワーク保護を実現する。' },
  { term: 'Route 53リゾルバー', aliases: ['route 53リゾルバー', 'route 53 resolver', 'amazon route 53 resolver'], description: 'VPCとオンプレミスネットワーク間のDNS解決を可能にするマネージドDNSリゾルバー。インバウンドエンドポイントとアウトバウンドエンドポイントを設定することでハイブリッド環境でのDNSクエリ転送を実現する。' },
  { term: 'ALB リスナールール', aliases: ['alb リスナールール', 'alb listener rule', 'リスナールール'], description: 'Application Load Balancerのリスナーに設定するルールで、HTTPリクエストのパス・ホスト・ヘッダー・クエリ文字列などの条件に応じてターゲットグループへのルーティングを制御する。パスベースルーティングやホストベースルーティングに利用される。' },
  { term: 'ターゲットグループ', aliases: ['target group'], description: 'ELBが受信したリクエストをルーティングするEC2インスタンス・コンテナ・Lambda関数などのエンドポイントのグループ。ヘルスチェックを設定して正常なターゲットのみにトラフィックを送り、負荷分散とヘルスモニタリングを行う。' },
  { term: 'コネクションドレイニング', aliases: ['connection draining', 'deregistration delay'], description: 'ロードバランサーからターゲットを登録解除する際、既存の接続が完了するまで待機する機能。デフォルト300秒のタイムアウト内に既存リクエストを処理し完了させてから、ターゲットを安全に取り外しダウンタイムを防ぐ。' },
  { term: 'クロスゾーン負荷分散', aliases: ['cross-zone load balancing'], description: 'ロードバランサーがすべてのアベイラビリティゾーンの登録済みターゲットにトラフィックを均等に分散する設定。ALBではデフォルト有効、NLBはデフォルト無効。複数AZにターゲット数の差異がある場合も均等にリクエストを配分できる。' },
  { term: 'CloudFront ディストリビューション', aliases: ['cloudfront ディストリビューション', 'cloudfront distribution'], description: 'Amazon CloudFrontのコンテンツ配信設定の単位。オリジン・キャッシュ動作・エラーページ・アクセス制限・SSL証明書などを設定し、固有のドメイン（xxx.cloudfront.net）でコンテンツを世界中のエッジロケーションから配信する。' },
  { term: 'CloudFront キャッシュポリシー', aliases: ['cloudfront キャッシュポリシー', 'cloudfront cache policy', 'キャッシュポリシー'], description: 'CloudFrontがコンテンツをキャッシュする際の動作を定義するポリシー。TTL・キャッシュキーに含めるヘッダー・クエリ文字列・Cookieを設定し、キャッシュヒット率の最適化とコンテンツの適切な差別化を実現する。' },
  { term: 'CloudFront 署名付きURL', aliases: ['cloudfront 署名付きurl', 'signed url', 'cloudfront signed url', '署名付きurl'], description: '特定のCloudFrontコンテンツへのアクセスを有効期限・IPアドレス・パス等で制限するURL。プレミアムコンテンツや一時的なファイル共有に使用し、署名付きCookieはサイト全体の保護に向く。' },
  { term: 'オリジンシールド', aliases: ['origin shield', 'cloudfront origin shield'], description: 'CloudFrontのキャッシュレイヤーとオリジン間に追加するキャッシュレイヤー。エッジロケーションからのリクエストをオリジンシールドに集約することでオリジンへのリクエスト数を削減し、オリジンの負荷とコストを最小化する。' },
  { term: 'VPC CIDRブロック', aliases: ['vpc cidrブロック', 'vpc cidr', 'cidr block', 'cidrブロック'], description: 'VPCに割り当てるIPアドレス範囲をCIDR表記で定義したもの。例えば10.0.0.0/16は65,536個のIPアドレスを表す。VPC作成後に変更できないため適切な範囲を設計段階で決定することが重要で、オンプレミスや他VPCとの重複を避ける必要がある。' },
  { term: 'AWS App Mesh', aliases: ['aws app mesh', 'app mesh'], description: 'マイクロサービス間の通信を可視化・制御するフルマネージドのサービスメッシュ。Envoyプロキシをサイドカーとして各サービスに付加し、トラフィックルーティング・ヘルスチェック・テレメトリーを一元管理する。' },
  { term: 'AWS Service Discovery', aliases: ['aws service discovery', 'service discovery', 'cloud map'], description: 'マイクロサービスがDNSまたはAPIを通じて動的に他のサービスを検索・接続できるようにするサービス検出機能。ECSやEKSのサービスを自動登録し、ヘルスチェックに連動して正常なエンドポイントのみを返す。' },
  { term: 'Amazon EC2 Image Builder', aliases: ['amazon ec2 image builder', 'ec2 image builder', 'image builder'], description: '安全で最新のAMI（Amazon Machine Image）やコンテナイメージを自動的に作成・テスト・配布するフルマネージドサービス。パイプラインで定義したコンポーネントを自動適用してイメージをビルドし、脆弱性スキャン後に配布できる。' },
  { term: 'AWS Outposts', aliases: ['aws outposts', 'outposts'], description: 'AWSのインフラ・サービス・API・ツールをオンプレミスのデータセンターや施設に拡張するフルマネージドサービス。低レイテンシー要件・データレジデンシー要件・ローカル処理が必要なワークロードをオンプレミスでAWS環境と統一的に管理できる。' },
  { term: 'Elastic Network Interface', aliases: ['elastic network interface', 'eni', '仮想ネットワークインターフェース'], description: 'VPC内の仮想ネットワークカード。プライマリプライベートIPv4アドレス・セカンダリIPアドレス・Elastic IP・MACアドレス・セキュリティグループを持ち、EC2インスタンスへのアタッチ・デタッチが可能。ネットワーク管理の柔軟性を高める。' },
  { term: 'プレイスメントグループ', aliases: ['placement group', '配置グループ'], description: 'EC2インスタンスの物理的な配置を制御する機能。クラスター（同一ラック内で低レイテンシー・高スループット）・パーティション（異なるハードウェアに分散）・スプレッド（個別ラックに分散して高可用性）の3種類がある。' },
  { term: 'AWS Local Zones', aliases: ['aws local zones', 'local zones'], description: '特定の都市圏でAWSの計算・ストレージ・データベースサービスをユーザーの近くで提供するインフラ拡張。主要リージョンから地理的に離れた場所でも1桁ミリ秒のレイテンシーが必要なアプリケーションに利用する。' },
  { term: 'S3バージョニング', aliases: ['s3バージョニング', 's3 versioning', 'バージョニング'], description: 'Amazon S3バケット内のオブジェクトの全バージョンを保持する機能。誤削除や上書きからデータを保護し、以前のバージョンに随時復元できる。MFADeleteと組み合わせることでセキュリティをさらに強化できる。' },
  { term: 'Amazon EBS最適化インスタンス', aliases: ['amazon ebs最適化インスタンス', 'ebs-optimized instance', 'ebs最適化'], description: 'EBSとEC2インスタンス間の通信に専用帯域幅を確保したインスタンスタイプ。通常のネットワーク帯域と分離された専用スループットでEBSボリュームにアクセスでき、I/Oパフォーマンスを最大化してレイテンシーを安定させる。' },
  { term: 'AWS Lambda関数URL', aliases: ['aws lambda関数url', 'lambda function url', '関数url'], description: 'Lambda関数にHTTPS専用エンドポイントを直接付与する機能。API Gatewayなしにブラウザやcurlから関数を呼び出せるようになり、シンプルなWebhookやAPIに適する。認証なし（NONE）またはAWS_IAM認証を選択できる。' },
  { term: 'プロビジョニングされた同時実行', aliases: ['provisioned concurrency', 'プロビジョニング済み同時実行'], description: 'AWS Lambda関数のコールドスタートを排除するために、関数インスタンスを事前に初期化済みの状態で維持する機能。レスポンスタイムの予測可能性が重要なユーザー向けAPIや低レイテンシーが要件のアプリケーションで使用する。' },
  { term: 'コンテナイメージLambda', aliases: ['コンテナイメージlambda', 'container image lambda', 'lambda container image'], description: 'DockerコンテナイメージとしてパッケージングしてAWS Lambdaにデプロイする方法。最大10GBのコンテナイメージをサポートし、既存のコンテナツールチェーンを活用しつつLambdaのサーバーレス実行モデルの恩恵を受けられる。' },
  { term: 'Amazon EC2ユーザーデータ', aliases: ['amazon ec2ユーザーデータ', 'ec2 user data', 'user data', 'ユーザーデータ'], description: 'EC2インスタンス起動時に自動実行されるスクリプトやデータ。シェルスクリプトやCloud-initディレクティブを渡してソフトウェアのインストールや設定を自動化するブートストラップに使用する。初回起動時のみ実行される。' },
  { term: 'EC2メタデータサービス', aliases: ['ec2メタデータサービス', 'instance metadata service', 'imds', 'ec2 metadata'], description: 'EC2インスタンスから169.254.169.254にHTTPアクセスしてインスタンス自身の情報（インスタンスID・タイプ・IAMロール認証情報等）を取得するサービス。IMDSv2ではセッショントークンが必要でSSRF攻撃への耐性が向上している。' },
  { term: 'AWS Graviton', aliases: ['aws graviton', 'graviton', 'arm-based processor'], description: 'AWSが独自設計したARMベースのプロセッサ。Graviton2・Graviton3・Graviton4と世代が進み、x86ベースインスタンスと比較して最大40%のコストパフォーマンス向上を実現。EC2・RDS・ElastiCache等で対応インスタンスを選択できる。' },
  { term: 'DynamoDB TTL', aliases: ['dynamodb ttl', 'dynamodb time to live', '有効期限'], description: 'Amazon DynamoDBのアイテムに有効期限（Unix時刻）を設定し、期限切れアイテムを自動削除する機能。追加コストなしで古いセッションデータや一時データを自動的にパージでき、テーブルのサイズとコストを管理する。' },
  { term: 'DynamoDB プロビジョンドスループット', aliases: ['dynamodb プロビジョンドスループット', 'provisioned throughput', 'プロビジョンドキャパシティ'], description: 'Amazon DynamoDBで事前に読み取りキャパシティユニット（RCU）と書き込みキャパシティユニット（WCU）を指定して確保するキャパシティモード。予測可能なトラフィックパターンのワークロードでコストを抑えるために使用する。' },
  { term: 'Aurora レプリカ', aliases: ['aurora レプリカ', 'aurora replica', 'auroraレプリカ', 'aurora read replica'], description: 'Amazon Aurora クラスター内でプライマリインスタンスと同一ストレージを共有する読み取り専用レプリカ。最大15個作成でき、プライマリ障害時のフェイルオーバーターゲットとしても機能する。レプリカへの読み取り分散でパフォーマンスを向上させる。' },
  { term: 'RDS スナップショット', aliases: ['rds スナップショット', 'rds snapshot', 'dbスナップショット'], description: 'Amazon RDSデータベースインスタンスの特定時点のバックアップ。手動スナップショットはユーザーが作成・管理し、自動スナップショットは保持期間（最大35日）内で任意の時点に復元（PITR）できる。スナップショットからリージョン間コピーも可能。' },
  { term: 'Amazon FSx for Windows', aliases: ['amazon fsx for windows', 'fsx for windows file server', 'fsx windows'], description: 'Windows Server上のSMBプロトコルに対応したフルマネージドWindowsファイルシステム。Active Directory統合・DFS・VSS（Volume Shadow Copy Service）をサポートし、Windowsワークロードのリフト&シフト移行に最適。' },
  { term: 'Amazon FSx for Lustre', aliases: ['amazon fsx for lustre', 'fsx for lustre', 'lustre'], description: '機械学習・HPC・メディア処理・ゲノム解析向けのフルマネージド高性能並列ファイルシステム。サブミリ秒レイテンシーと数百GB/sのスループットを提供し、S3と直接統合してデータを透過的に利用できる。' },
  { term: 'VPCフローログ分析', aliases: ['vpcフローログ分析', 'vpc flow logs analysis', 'フローログ分析'], description: 'VPCフローログをAthena・CloudWatch Logs Insights・Amazon OpenSearch Serviceで分析するプロセス。異常なIPアドレスからの接続・ポートスキャン・帯域異常などのセキュリティインシデントを検出し、ネットワーク最適化にも活用する。' },
  { term: 'CloudFront オリジングループ', aliases: ['cloudfront オリジングループ', 'origin group', 'cloudfront origin group'], description: 'CloudFrontで複数のオリジンをグループ化してフェイルオーバーを構成する機能。プライマリオリジンが特定のHTTPステータスコードを返した場合に自動的にセカンダリオリジンにフェイルオーバーし、高可用性のコンテンツ配信を実現する。' },
  { term: 'Route 53トラフィックポリシー', aliases: ['route 53トラフィックポリシー', 'route 53 traffic policy', 'トラフィックポリシー'], description: 'Amazon Route 53の高度なルーティング設定をビジュアルエディタや設定ファイルで定義するポリシー。レイテンシーベース・地理的・加重・フェイルオーバールーティングを組み合わせた複雑なトラフィック管理シナリオを再利用可能な形で構成できる。' },
  { term: 'AWS Wavelength', aliases: ['aws wavelength', 'wavelength'], description: '5G通信事業者のネットワーク内にAWSのコンピュート・ストレージを組み込むサービス。モバイルデバイスや5Gエンドポイントからのトラフィックがキャリアネットワーク外に出ることなくAWSサービスにアクセスでき、1桁ミリ秒の超低レイテンシーを実現する。' },
  { term: 'AWS Compute Optimizer', aliases: ['aws compute optimizer', 'compute optimizer'], description: '機械学習を使ってEC2・Lambda・ECS・EBSの使用状況を分析し、最適なリソース構成を推奨するサービス。過剰プロビジョニングや過少プロビジョニングを検出し、パフォーマンスとコストのバランスが取れた推奨インスタンスタイプを提示する。' },
  { term: 'Amazon Inspector', aliases: ['amazon inspector', 'inspector'], description: 'EC2インスタンス・コンテナイメージ・Lambda関数のソフトウェア脆弱性やネットワーク露出を自動的に継続スキャンするセキュリティサービス。CVEデータベースに基づいてリスクスコアを算出し、優先度の高い脆弱性を特定してセキュリティ態勢を改善する。' },
  { term: 'AWS CloudShell', aliases: ['aws cloudshell', 'cloudshell'], description: 'AWSマネジメントコンソールから直接起動できるブラウザベースのシェル環境。AWS CLIやよく使うツールがプリインストールされており、認証情報の設定なしに現在のコンソールセッションの権限でAWSコマンドを実行できる。' },
  { term: 'Amazon EC2 Savings Plans', aliases: ['amazon ec2 savings plans', 'ec2 savings plans', 'セイビングスプラン'], description: '1年または3年間の一定コンピュート使用量をコミットする代わりに最大66%割引を受けられるAWSの柔軟な料金モデル。リザーブドインスタンスより柔軟でインスタンスファミリー・リージョン・OSを問わず適用されるCompute Savings Plansもある。' },
  { term: 'Auroraクローン', aliases: ['auroraクローン', 'aurora clone', 'aurora fast clone', 'クローンデータベース'], description: 'Amazon Auroraのデータベースクラスターを実際のデータをコピーせずに即座に複製するコピーオンライト方式の機能。本番データのコピーを数秒で作成でき、開発・テスト・データ分析環境の迅速な構築に活用できる。' },
  { term: 'IAMユーザー', aliases: ['iamユーザー', 'iam user'], description: 'AWSアカウント内で作成する個人またはアプリケーションを表すエンティティ。長期的なアクセスキーやパスワードを持ち、ポリシーをアタッチして権限を付与する。人間のユーザーにはIAMロールやIAM Identity Centerの利用が推奨される。' },
  { term: 'IAMグループ', aliases: ['iamグループ', 'iam group'], description: '【AWS】複数のIAMユーザーをまとめて管理するためのコレクション。グループにポリシーをアタッチすることで、メンバー全員に同じ権限を一括付与・剥奪できる。グループはネストできない。 【OCI APEX】権限付与の対象となるユーザー集合。' },
  { term: 'AWS SSO', aliases: ['aws sso', 'aws single sign-on', 'iam identity center'], description: '複数のAWSアカウントやビジネスアプリケーションへのシングルサインオンアクセスを一元管理するサービス。現在はIAM Identity Centerに名称変更されており、SSOポータルから複数アカウントへのアクセスを提供する。' },
  { term: 'AWS GuardDuty', aliases: ['aws guardduty'], description: '機械学習とインテリジェンスフィードを使ってAWSアカウント・ワークロードへの脅威を継続的に検出するマネージド脅威検出サービス。VPCフローログ・DNS・CloudTrailを分析し、不審な活動を自動的にアラートする。' },
  { term: 'Amazon Macie', aliases: ['amazon macie', 'macie'], description: '機械学習を使ってS3バケット内の機密データ（個人情報・クレジットカード番号など）を自動検出・分類・保護するデータセキュリティサービス。データプライバシーリスクの可視化とコンプライアンス対応を支援する。' },
  { term: 'CloudWatch Logs', aliases: ['cloudwatch logs', 'amazon cloudwatch logs'], description: 'AWSリソースやアプリケーションからログデータを収集・保存・監視するサービス。Lambdaの実行ログ、EC2のシステムログ、カスタムアプリログをリアルタイムで収集し、Insights機能でクエリ分析が可能。' },
  { term: 'CloudWatch Alarms', aliases: ['cloudwatch alarms', 'amazon cloudwatch alarms'], description: 'CloudWatchメトリクスが閾値を超えた場合に通知やアクションを自動実行するアラーム機能。SNSによるメール通知、Auto ScalingアクションのトリガーやEC2インスタンスの自動停止・復旧に使用される。' },
  { term: 'CloudWatch Metrics', aliases: ['cloudwatch metrics', 'amazon cloudwatch metrics'], description: 'AWSサービスやカスタムアプリケーションから収集される時系列の監視データ。CPU使用率・リクエスト数・エラー率などの標準メトリクスと、PutMetricData APIで送信するカスタムメトリクスで構成される。' },
  { term: 'Kinesis Data Streams', aliases: ['kinesis data streams', 'amazon kinesis data streams', 'kds'], description: '大規模なリアルタイムデータストリームをミリ秒単位で収集・処理するAWSサービス。シャードという並列処理単位でスループットをスケールし、複数のコンシューマーが同一ストリームを並行処理できる。' },
  { term: 'Kinesis Data Firehose', aliases: ['kinesis data firehose', 'amazon kinesis data firehose'], description: 'ストリームデータをS3・Redshift・OpenSearch・Splunkなどに自動的にロードするフルマネージドETLサービス。バッファリング・圧縮・暗号化・変換を自動処理し、サーバーレスで運用負担なくデータレイクに配信する。' },
  { term: 'Kinesis Data Analytics', aliases: ['kinesis data analytics', 'amazon kinesis data analytics', 'amazon managed service for apache flink'], description: 'ストリーミングデータをSQLまたはApache Flinkを使用してリアルタイムに分析するマネージドサービス。集計・フィルタリング・異常検知をストリームデータに対してリアルタイム実行できる。' },
  { term: 'AWS Lake Formation', aliases: ['aws lake formation', 'lake formation'], description: 'データレイクの構築・保護・管理を簡素化するAWSサービス。S3上のデータカタログ管理、細かいアクセス制御（列・行レベル）、データ共有をGlueと連携して提供し、ガバナンスを強化する。' },
  { term: 'Amazon QuickSight', aliases: ['amazon quicksight', 'quicksight'], description: 'BIダッシュボードと分析レポートをブラウザやモバイルで提供するクラウドネイティブBIサービス。SPICE（インメモリエンジン）で高速クエリを実現し、ML洞察機能で異常検知や予測を自動提示する。' },
  { term: 'Amazon EMR', aliases: ['amazon emr', 'elastic mapreduce'], description: 'Apache Spark・Hadoop・HBase・Prestoなどのオープンソースビッグデータフレームワークをマネージドクラスターで実行するサービス。EC2・EKS・Serverlessの実行環境を選択でき、大規模データ処理を低コストで実現する。' },
  { term: 'AWS Data Pipeline', aliases: ['aws data pipeline'], description: 'オンプレミスとAWSサービス間でデータを定期的に移動・変換するワークフロー自動化サービス。S3・RDS・DynamoDB・Redshiftへのデータ転送をスケジュール実行し、依存関係を管理する。' },
  { term: 'Amazon SageMaker', aliases: ['amazon sagemaker', 'sagemaker'], description: '機械学習モデルの構築・トレーニング・デプロイをエンドツーエンドで支援するフルマネージドMLプラットフォーム。データ準備からモデル監視まで一貫したワークフローを提供し、MLOpsを加速する。' },
  { term: 'SageMaker Studio', aliases: ['sagemaker studio', 'amazon sagemaker studio'], description: '機械学習開発のためのウェブベース統合開発環境（IDE）。Jupyter Labをベースに、データ探索・実験管理・モデルデプロイ・MLパイプライン構築を一つのUIから操作できるSageMakerのフロントエンド。' },
  { term: 'SageMaker Endpoints', aliases: ['sagemaker endpoints', 'amazon sagemaker endpoints'], description: 'トレーニング済み機械学習モデルをリアルタイム推論または非同期推論として公開するRESTエンドポイント。オートスケーリング、マルチモデルエンドポイント、A/Bテスト用の本番バリアント機能を持つ。' },
  { term: 'Amazon Rekognition', aliases: ['amazon rekognition', 'rekognition'], description: '画像・動画から顔認識・物体検出・テキスト抽出・コンテンツモデレーションを行うAIサービス。事前トレーニング済みモデルをAPIで利用でき、顔コレクションを作成してカスタム顔検索も可能。' },
  { term: 'Amazon Comprehend', aliases: ['amazon comprehend', 'comprehend'], description: '自然言語処理（NLP）を使ってテキストからエンティティ・感情・キーフレーズ・言語・トピックを抽出するAIサービス。カスタム分類モデルのトレーニングにも対応し、大量テキスト分析を自動化する。' },
  { term: 'Amazon Polly', aliases: ['amazon polly', 'polly'], description: 'テキストを人間らしい音声に変換するテキスト読み上げ（TTS）サービス。多数の言語・音声に対応し、ニューラルTTSエンジンで自然な抑揚を実現する。音声ガイドやポッドキャスト自動生成に活用される。' },
  { term: 'Amazon Transcribe', aliases: ['amazon transcribe', 'transcribe'], description: '音声をテキストに自動変換する音声認識（ASR）サービス。話者識別・カスタム語彙・チャンネル識別・リアルタイム文字起こしをサポートし、コールセンター分析や会議議事録作成に活用される。' },
  { term: 'Amazon Translate', aliases: ['amazon translate', 'translate'], description: 'ニューラル機械翻訳を使ってテキストを75以上の言語間でリアルタイム・バッチ翻訳するサービス。カスタム用語集で専門用語の翻訳を制御でき、多言語コンテンツのローカライズを自動化する。' },
  { term: 'Amazon Lex', aliases: ['amazon lex', 'lex'], description: '音声とテキストを使った会話インターフェース（チャットボット・音声ボット）を構築するAIサービス。Alexaと同じエンジンを使い、インテント・スロット・フルフィルメントロジックでダイアログを設計する。' },
  { term: 'Amazon Textract', aliases: ['amazon textract', 'textract'], description: 'ドキュメント画像からテキスト・テーブル・フォームデータを自動抽出するAIサービス。OCRを超えてフォームのフィールドと値のペアやテーブル構造を認識し、請求書・申請書の処理自動化に活用される。' },
  { term: 'AWS CodeArtifact', aliases: ['aws codeartifact', 'codeartifact'], description: 'npm・PyPI・Maven・NuGetなどのパッケージをセキュアに保存・共有・配布するマネージドアーティファクトリポジトリ。社内パッケージの公開と外部リポジトリのプロキシ・キャッシュ機能を提供する。' },
  { term: 'CloudFormation StackSets', aliases: ['cloudformation stacksets', 'aws cloudformation stacksets'], description: '単一のCloudFormationテンプレートを複数のAWSアカウントおよびリージョンに一括デプロイする機能。AWS Organizationsと統合して組織全体への統一インフラ展開や、ガードレールの一括適用に使用される。' },
  { term: 'AWS Well-Architected Tool', aliases: ['aws well-architected tool', 'well-architected tool', 'wat'], description: 'AWS Well-Architectedフレームワークの質問に回答することでアーキテクチャのリスクを評価するセルフサービスツール。6つの柱（運用卓越性・セキュリティ・信頼性・パフォーマンス・コスト最適化・持続可能性）に基づいて改善点を特定する。' },
  { term: 'AWS Service Catalog', aliases: ['aws service catalog', 'service catalog'], description: 'ITサービスの承認済みカタログを作成・管理・配布するサービス。CloudFormationテンプレートを製品として登録し、エンドユーザーがセルフサービスで規定のリソースをプロビジョニングできる環境を構築する。' },
  { term: 'AWS Proton', aliases: ['aws proton', 'proton'], description: 'プラットフォームエンジニアリングチームがサービステンプレートを定義し、開発チームがそれを使って標準化されたマイクロサービスインフラを自律的にデプロイできる自動化サービス。' },
  { term: 'Amazon Connect', aliases: ['amazon connect', 'connect'], description: 'クラウドベースのコンタクトセンタープラットフォーム。音声通話・チャット・タスク管理を統合し、AIによる自動応答（Lex連携）・エージェント支援・通話分析を提供する従量課金型サービス。' },
  { term: 'Amazon Pinpoint', aliases: ['amazon pinpoint', 'pinpoint'], description: 'メール・SMS・プッシュ通知・音声メッセージを使ったユーザーエンゲージメントキャンペーンを管理するマーケティングコミュニケーションサービス。セグメンテーション・A/Bテスト・配信分析機能を備える。' },
  { term: 'AWS Amplify', aliases: ['aws amplify', 'amplify'], description: 'フロントエンド（React・Vue・Next.js・モバイル）からAWSバックエンドを素早く構築・デプロイするフルスタック開発プラットフォーム。認証・API・ストレージ・ホスティングをライブラリとCLIで抽象化する。' },
  { term: 'SageMaker Training', aliases: ['sagemaker training', 'amazon sagemaker training'], description: 'マネージドインフラ上で機械学習モデルのトレーニングジョブを実行するSageMakerの機能。組み込みアルゴリズム・独自スクリプト・分散トレーニング・スポットインスタンス活用による大規模トレーニングを支援する。' },
  { term: 'SageMaker Pipelines', aliases: ['sagemaker pipelines', 'amazon sagemaker pipelines'], description: '機械学習ワークフローをコードで定義・実行・追跡するMLOpsパイプラインサービス。データ処理・トレーニング・評価・デプロイの各ステップを有向非巡回グラフ（DAG）で管理し、実験の再現性を確保する。' },
  { term: 'Amazon Forecast', aliases: ['amazon forecast', 'forecast'], description: '機械学習を使って時系列データから高精度な需要予測・在庫予測を生成するフルマネージド予測サービス。DeepAR・NPTS・ETS・ARIMAなど複数アルゴリズムを自動選択し、外部変数（天候・休日）も考慮する。' },
  { term: 'Amazon Personalize', aliases: ['amazon personalize', 'personalize'], description: 'EC・メディア・広告向けのリアルタイムパーソナライズ推薦システムを構築するマネージドMLサービス。ユーザー行動データを学習してレコメンデーションAPIを提供し、MLの専門知識なしに実装できる。' },
  { term: 'Amazon Kendra', aliases: ['amazon kendra', 'kendra'], description: '機械学習を使った企業向けインテリジェント検索サービス。S3・SharePoint・Salesforceなど多様なデータソースから文書をインデックス化し、自然言語の質問に対して正確な回答と関連ドキュメントを返す。' },
  { term: 'Amazon CodeWhisperer', aliases: ['amazon codewhisperer', 'codewhisperer', 'amazon q developer'], description: 'AWSが提供するAIコードアシスタント。コードの文脈からリアルタイムに次のコード候補を提案し、セキュリティスキャン・オープンソースライセンスの帰属追跡も提供する。現在はAmazon Q Developerに統合されている。' },
  { term: 'Amazon Managed Workflows for Apache Airflow', aliases: ['amazon managed workflows for apache airflow', 'amazon mwaa', 'mwaa'], description: 'Apache AirflowをフルマネージドEnvironmentで実行するサービス。DagのS3格納・ワーカーのオートスケーリング・VPCネットワーク分離を提供し、データパイプラインのオーケストレーションをサーバーレスで運用できる。' },
  { term: 'Amazon Detective', aliases: ['amazon detective', 'detective'], description: 'VPCフローログ・CloudTrailログ・GuardDutyの検知結果を機械学習でグラフ分析し、セキュリティインシデントの根本原因調査を支援するサービス。関係するエンティティの行動パターンを時系列で可視化する。' },
  { term: 'AWS Firewall Manager', aliases: ['aws firewall manager', 'firewall manager'], description: 'AWS Organizations全体のWAF・Shield Advanced・セキュリティグループ・Network Firewallポリシーを一元管理・自動適用するセキュリティ管理サービス。新規アカウントにも自動でポリシーを適用してコンプライアンスを維持する。' },
  { term: 'AWS Resource Access Manager', aliases: ['aws resource access manager', 'resource access manager'], description: 'AWSリソースを複数アカウント間または組織内でセキュアに共有するサービス。VPCサブネット・Transit Gateway・Route 53 Resolver・License Managerライセンスなどを複製なしに共有できる。' },
  { term: 'AWS License Manager', aliases: ['aws license manager', 'license manager'], description: 'Microsoft・Oracle・SAPなどのソフトウェアライセンスをAWSおよびオンプレミスで一元追跡・管理するサービス。ライセンスルールを設定してコンプライアンス違反を防止し、使用状況レポートを生成する。' },
  { term: 'AWS Cost and Usage Report', aliases: ['aws cost and usage report'], description: 'AWSのコストと使用量の詳細データをCSVまたはParquet形式でS3に定期出力するレポートサービス。リソースレベルの時間単位コスト、タグ・Savings Plans・リザーブドインスタンスの適用情報を含む最詳細なコストデータ。' },
  { term: 'AWS Private CA', aliases: ['aws private ca', 'aws private certificate authority', 'acm pca'], description: '組織内部のプライベートPKIインフラを構築するマネージドプライベート認証局サービス。内部サービス間のTLS証明書・コード署名証明書・IoTデバイス証明書を発行・管理し、CAの運用負担を削減する。' },
  { term: 'AWS Signer', aliases: ['aws signer', 'signer'], description: 'Lambda関数パッケージとコンテナイメージのコード署名を管理するサービス。承認された署名プロファイルで署名されたコードのみをデプロイするポリシーを設定でき、サプライチェーン攻撃を防止する。' },
  { term: 'Amazon Security Lake', aliases: ['amazon security lake', 'security lake'], description: 'AWSサービス・SaaSアプリ・オンプレミスから収集したセキュリティログをOCSF（Open Cybersecurity Schema Framework）形式に正規化してS3に集約するセキュリティデータレイクサービス。' },
  { term: 'AWS Artifact', aliases: ['aws artifact'], description: 'AWSのコンプライアンスレポート（SOC・PCI DSS・ISO・FedRAMPなど）と契約書類をオンデマンドでダウンロードできるコンプライアンス文書ポータル。監査対応や規制要件の証拠収集に使用する。' },
  { term: 'AWS Audit Manager', aliases: ['aws audit manager', 'audit manager'], description: 'AWSの使用状況を継続的に評価し、PCI DSS・HIPAA・SOC2などのコンプライアンスフレームワークに対するエビデンスを自動収集するサービス。監査準備作業の工数を大幅に削減する。' },
  { term: 'AWS Health Dashboard', aliases: ['aws health dashboard', 'aws personal health dashboard', 'phd'], description: 'AWSサービスの障害・メンテナンス・アカウント固有のアラートをリアルタイムで通知するダッシュボード。EventBridgeと連携して自動復旧アクションをトリガーでき、影響を受けるリソースを特定できる。' },
  { term: 'Amazon Cognito', aliases: ['amazon cognito'], description: 'ウェブ・モバイルアプリにユーザー認証・認可・ユーザー管理機能を追加するAWSサービス。ユーザープール（認証）とIDプール（AWS認証情報の取得）の2つのコンポーネントで構成され、ソーシャルログインとSAMLフェデレーションに対応する。' },
  { term: 'Amazon Cognito User Pool', aliases: ['amazon cognito user pool', 'cognito user pool'], description: 'Amazon Cognitoのユーザーディレクトリ機能。ユーザー登録・サインイン・パスワード管理・多要素認証・カスタム認証フローを提供し、JWTトークンをアプリに返すOAuth 2.0/OpenID Connect準拠のIdP。' },
  { term: 'Amazon Cognito Identity Pool', aliases: ['amazon cognito identity pool', 'cognito identity pool', 'cognito federated identities'], description: 'Amazon Cognitoの認証情報ブローカー機能。認証済みユーザー（CognitoユーザープールやGoogle等）と未認証ゲストに一時的なAWS認証情報（IAMロール経由）を払い出し、S3やDynamoDBへの直接アクセスを実現する。' },
  { term: 'AWS IAM Access Analyzer', aliases: ['aws iam access analyzer', 'iam access analyzer', 'access analyzer'], description: 'S3・IAMロール・KMSキー・Lambdaなどのリソースポリシーを分析し、外部エンティティからアクセス可能なリソース（意図しない公開）を自動検出するセキュリティツール。最小権限ポリシーの生成も支援する。' },
  { term: 'Amazon Verified Permissions', aliases: ['amazon verified permissions', 'verified permissions', 'avp'], description: 'Cedar言語を使ってアプリケーション内のきめ細かい認可（AuthZ）ロジックを外部化・管理するポリシーエンジン。属性ベースアクセス制御（ABAC）を実装し、認可ロジックのコードからの分離を実現する。' },
  { term: 'AWS Resilience Hub', aliases: ['aws resilience hub', 'resilience hub'], description: 'アプリケーションの耐障害性を定義・検証・追跡するサービス。RTO/RPO目標を設定して現状のアーキテクチャを評価し、耐障害性スコアと改善推奨を提供してWell-Architectedの信頼性向上を支援する。' },
  { term: 'AWS Fault Injection Simulator', aliases: ['aws fault injection simulator', 'fis', 'aws fis'], description: '本番ライクな環境でCPUスパイク・ネットワーク遅延・インスタンス停止などの障害を意図的に注入してシステムの回復力を検証するカオスエンジニアリングサービス。実験テンプレートでセーフガードを設定できる。' },
  { term: 'Amazon DevOps Guru', aliases: ['amazon devops guru', 'devops guru'], description: '機械学習でアプリケーションの運用データを継続的に分析し、パフォーマンス問題・障害の予兆を自動検出するAIOpsサービス。CloudWatch・X-Ray・CloudTrailを横断分析して異常の根本原因と推奨アクションを提示する。' },
  { term: 'Amazon Fraud Detector', aliases: ['amazon fraud detector', 'fraud detector'], description: 'Amazonが培った機械学習モデルを使ってオンライン詐欺（不正アカウント登録・不正決済など）をリアルタイムで検出するマネージドサービス。過去の取引データを学習してカスタム詐欺検知ロジックを構築できる。' },
  { term: 'Amazon Comprehend Medical', aliases: ['amazon comprehend medical', 'comprehend medical'], description: '医療テキスト（カルテ・処方箋・臨床メモ）から疾患名・薬剤名・医療処置・解剖部位などの医療エンティティとその関係性を自動抽出するNLPサービス。ICD-10・RxNormとのマッピングも提供する。' },
  { term: 'AWS Application Composer', aliases: ['aws application composer', 'application composer'], description: 'サーバーレスアプリケーションのアーキテクチャをビジュアルキャンバスで設計し、SAM/CloudFormationテンプレートをリアルタイムで生成するドラッグ＆ドロップツール。LambdaやAPI GatewayをGUI操作で接続できる。' },
  { term: 'AWS Chatbot', aliases: ['aws chatbot', 'chatbot'], description: 'AWSの通知をSlackやAmazon Chimeのチャンネルに配信し、チャット経由でAWSリソースを操作できるChatOpsサービス。CloudWatchアラームやSecurity Hubの検知をチャンネルに自動投稿し、RunBookの実行もできる。' },
  { term: 'AWS Support', aliases: ['aws support', 'aws support plans'], description: 'AWSが提供する技術サポートプランの総称。Basic・Developer・Business・Enterprise On-Ramp・Enterpriseの5段階があり、上位プランほど応答時間・TAM対応・運用レビューなどのサポートレベルが向上する。' },
  { term: 'AWS Security Token Service', aliases: ['aws security token service', 'sts'], description: 'IAMユーザーやフェデレーションユーザーに一時的なセキュリティ認証情報を発行するウェブサービス。AssumeRole・AssumeRoleWithWebIdentity・GetFederationTokenなどのAPIで短期間有効なアクセスキーを取得できる。' },
  { term: 'AWS Directory Service', aliases: ['aws directory service', 'directory service'], description: 'AWS上でMicrosoft Active DirectoryをマネージドまたはAD Connectorで利用するサービス。WorkSpaces・RDS・FSx for Windowsとの統合や、オンプレミスADとの信頼関係構築でハイブリッド認証を実現する。' },
  { term: 'AWS Transfer Family', aliases: ['aws transfer family', 'transfer family'], description: 'SFTP・FTPS・FTP・AS2プロトコルを使ってファイルをS3またはEFSに転送するマネージドファイル転送サービス。既存のファイル転送ワークフローをコード変更なしにAWSへ移行でき、既存のIAM・Active Directory認証と統合する。' },
  { term: 'Amazon OpenSearch Service', aliases: ['amazon opensearch service', 'opensearch service', 'amazon elasticsearch service'], description: 'OpenSearch（Elasticsearch互換）クラスターをフルマネージドで提供するサービス。ログ分析・全文検索・リアルタイムアプリケーション監視に使用され、Dashboards（Kibana互換）で可視化できる。' },
  { term: 'Amazon DynamoDB Streams', aliases: ['amazon dynamodb streams'], description: 'DynamoDBテーブルのアイテム変更（追加・更新・削除）をリアルタイムにキャプチャして時系列で保持する変更データキャプチャ機能。Lambdaトリガーと組み合わせてイベント駆動アーキテクチャを実現する。' },
  { term: 'Amazon DynamoDB Accelerator', aliases: ['amazon dynamodb accelerator'], description: 'DynamoDBと互換性のあるインメモリキャッシュサービス。マイクロ秒レベルのレイテンシで読み取りを高速化し、DynamoDB APIをそのまま使用できる。読み取り集中型ワークロードのスループット向上に最適。' },
  { term: 'AWS Database Migration Service', aliases: ['aws database migration service', 'dms', 'database migration service'], description: 'Oracle・SQL Server・MySQL・PostgreSQLなどをAWSデータベースへ最小ダウンタイムで移行するマネージドサービス。継続的レプリケーション（CDC）で移行中もソースDBを稼働させ、異種DB間の変換にはSchema Conversion Toolと組み合わせる。' },
  { term: 'AWS Lambda Extensions', aliases: ['aws lambda extensions', 'lambda extensions'], description: 'Lambda実行環境に外部ツール（監視エージェント・セキュリティスキャナー・設定管理）をサイドカーとして統合するための拡張機構。Lambdaのライフサイクルイベントにフックして初期化・実行・シャットダウン処理を挿入できる。' },
  { term: 'AWS AppSync', aliases: ['aws appsync', 'appsync'], description: 'GraphQL APIをフルマネージドで構築・ホスティングするサービス。リアルタイムデータ同期・オフライン対応・複数データソース（DynamoDB・Lambda・RDS・HTTP）へのリゾルバー設定を提供し、モバイル・Webアプリに最適。' },
  { term: 'Amazon AppStream', aliases: ['amazon appstream', 'appstream 2.0'], description: 'デスクトップアプリケーションをAWSからHTML5ブラウザにストリーミング配信するフルマネージドサービス。CAD・医療画像・開発ツールなどインストール不要でどの端末からも利用でき、データはAWS側に保持される。' },
  { term: 'Amazon VPC Lattice', aliases: ['amazon vpc lattice', 'vpc lattice'], description: 'VPC・アカウント・オーバーレイネットワークの壁を越えてサービス間通信を簡素化するアプリケーションネットワーキングサービス。サービスディスカバリー・認証認可・観測性をVPCピアリングなしに実現する。' },
  { term: 'CodeBuild', aliases: ['codebuild'], description: 'AWSが提供するマネージドなビルド・テスト実行サービスです。' },
];
