// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: java (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // java (68), spring (29), spring-boot (20)
  { term: 'Java', aliases: ['java'], description: 'オブジェクト指向を基盤にしたプログラミング言語で、Java Platform 上で動くアプリケーション開発に使われます。' },
  { term: 'Java SE', aliases: ['java se'], description: 'Java Platform, Standard Edition の略で、標準的な Java 実行、開発、ライブラリ群を指します。' },
  { term: 'JDK', aliases: ['jdk'], description: 'Java Development Kit の略で、JRE に加えてコンパイラやデバッガーなど開発用ツールを含む一式です。' },
  { term: 'JRE', aliases: ['jre'], description: 'Java Runtime Environment の略で、Java アプリケーションを実行するためのライブラリ、JVM などを含む実行環境です。' },
  { term: 'JVM', aliases: ['jvm'], description: 'Java Virtual Machine の略で、Java バイトコードを実行する仮想マシンです。' },
  { term: 'Java HotSpot VM', aliases: ['java hotspot vm'], description: 'Oracle の JVM 実装で、JIT 最適化やガベージコレクションなどを提供します。' },
  { term: 'bytecode', description: 'javac が生成し、JVM が実行する中間コードです。' },
  { term: 'class file', description: 'Java ソースをコンパイルして得られる .class ファイルです。JVM が直接読み取ります。' },
  { term: 'javac', description: 'Java のコンパイラです。クラスやインターフェース定義を読み、バイトコードとクラスファイルへ変換します。' },
  { term: 'java command', description: 'Java アプリケーションを起動するランチャーです。' },
  { term: 'javadoc', description: 'Java ソースから API ドキュメントの HTML を生成するツールです。' },
  { term: 'jar', description: 'クラスやリソースをまとめた Java Archive を作成、管理するためのツールです。' },
  { term: 'JAR file', aliases: ['jar file'], description: 'クラスファイルやリソースをまとめたアーカイブ形式です。配布や再利用によく使われます。' },
  { term: 'classpath', description: 'JRE や JDK ツールがクラスやリソースを探す検索パスです。-classpath や CLASSPATH で指定できます。' },
  { term: 'package', description: '関連するクラスやインターフェースを整理する名前空間です。' },
  { term: 'API (Java)', aliases: ['api (java)'], description: 'Java Platform が提供するパッケージ、クラス、インターフェース、メソッドなどの利用可能な仕様群です。' },
  { term: 'class', description: 'オブジェクトを作るための設計図です。状態と振る舞いを定義します。' },
  { term: 'object', description: '【Java】状態と振る舞いを持つ実体で、クラスから生成されます。 【OCI APEX】Object Storageに保存される個別データ。' },
  { term: 'field', description: 'オブジェクトやクラスが保持するデータです。状態を表すのに使います。' },
  { term: 'method', description: 'クラスやオブジェクトが持つ振る舞いです。オブジェクト間の主要なやり取り手段になります。' },
  { term: 'interface', description: '関連するメソッド契約をまとめた型です。実装クラスに提供すべき振る舞いを要求できます。' },
  { term: 'implements', description: 'クラスがインターフェースを実装することを示す Java のキーワードです。' },
  { term: 'inheritance', description: '既存クラスの状態や振る舞いを継承して再利用する仕組みです。' },
  { term: 'extends', description: 'クラスが別のクラスを継承することを示すキーワードです。' },
  { term: 'superclass', description: '継承元となる親クラスです。共通の状態や振る舞いを定義します。' },
  { term: 'subclass', description: '別クラスを継承して作られる子クラスです。親クラスの機能を受け継ぎつつ拡張できます。' },
  { term: 'Object class', aliases: ['object class'], description: 'Java のすべてのクラスの最上位にある基本クラスです。toString や equals などの基本メソッドを持ちます。' },
  { term: 'single inheritance', description: 'Java では各クラスが直接継承できる親クラスは一つだけという性質です。' },
  { term: 'abstract class', description: '不完全実装を含められ、自身は通常インスタンス化せず、継承前提で使うクラスです。' },
  { term: 'final class', description: '継承を禁止したクラスです。拡張を意図しない設計に使われます。' },
  { term: 'exception', description: 'プログラム実行中に通常の流れを乱す異常事象です。Java はこれを例外として扱います。' },
  { term: 'checked exception', description: 'コンパイル時に捕捉または宣言が要求される例外です。' },
  { term: 'unchecked exception', description: 'RuntimeException 系など、捕捉や宣言が必須ではない例外です。' },
  { term: 'RuntimeException', aliases: ['runtimeexception'], description: 'API の誤用や前提違反を示すことが多い unchecked exception 系の基本クラスです。' },
  { term: 'try block', description: '例外が起こりうる処理を囲むブロックです。例外処理の起点になります。' },
  { term: 'catch block', description: '特定例外を受け止めて処理するブロックです。複数定義もできます。' },
  { term: 'finally block', description: '例外の有無に関わらず後始末を行うブロックです。' },
  { term: 'try-with-resources', description: 'リソースを自動的に close するための try 構文です。' },
  { term: 'throw statement', description: '例外を明示的に発生させるための文です。' },
  { term: 'throws clause', description: 'メソッドが送出しうる例外を宣言する部分です。' },
  { term: 'generics', description: '型をパラメータ化して、型安全で再利用しやすいコードを書く仕組みです。' },
  { term: 'type parameter', description: 'ジェネリクスでクラス、インターフェース、メソッドへ渡す型のパラメータです。' },
  { term: 'generic class', description: '型パラメータを宣言するクラスです。使用時に具体型を与えます。' },
  { term: 'generic method', description: 'メソッド単位で型パラメータを持つメソッドです。' },
  { term: 'type inference', description: 'コンパイラが引数や代入先を見て型引数を推論する仕組みです。' },
  { term: 'Collections Framework', aliases: ['collections framework'], description: 'Java のコレクション関連インターフェース、実装、アルゴリズム群です。' },
  { term: 'Collection', aliases: ['collection'], description: '要素集合を表す基本インターフェースです。List、Set、Queue などの基礎になります。' },
  { term: 'List', aliases: ['list'], description: '順序を持ち、重複を許すコレクションです。要素位置を制御したい場面に向きます。' },
  { term: 'Set', aliases: ['set'], description: '重複を許さないコレクションです。集合的な扱いに向きます。' },
  { term: 'Map', aliases: ['map'], description: 'キーと値を対応づけるコレクション系インターフェースです。Collection 系とは別の系統として整理されます。' },
  { term: 'Queue (Java)', aliases: ['queue (java)'], description: '順番に要素を処理するためのコレクションインターフェースです。' },
  { term: 'Deque', aliases: ['deque'], description: '両端から要素を追加、取得できる双方向キューです。' },
  { term: 'Iterator', aliases: ['iterator'], description: 'コレクション要素を順に走査するためのインターフェースです。' },
  { term: 'ListIterator', aliases: ['listiterator'], description: 'List 専用の反復子で、前後移動や要素変更をより柔軟に扱えます。' },
  { term: 'Spring Framework', aliases: ['spring framework'], description: 'モダンな Java エンタープライズアプリ向けの包括的なプログラミング、設定モデルを提供するフレームワークです。' },
  { term: 'Spring Core Technologies', aliases: ['spring core technologies'], description: 'Spring Framework の中核技術群で、IoC、AOP、validation、data binding などを含みます。' },
  { term: 'IoC', aliases: ['ioc'], description: 'Inversion of Control の略で、依存関係の生成と組み立てをフレームワーク側へ委ねる考え方です。' },
  { term: 'IoC Container', aliases: ['ioc container'], description: 'Spring が bean を生成、管理、注入する中核コンテナです。' },
  { term: 'BeanFactory', aliases: ['beanfactory'], description: 'Spring の基本的なコンテナインターフェースです。bean の取得や生成管理の基礎になります。' },
  { term: 'ApplicationContext', aliases: ['applicationcontext'], description: 'BeanFactory を拡張した、より高機能な Spring コンテナです。一般的な Spring アプリではこちらが中心です。' },
  { term: 'bean', description: 'Spring コンテナが生成、管理するオブジェクトです。依存注入の基本単位になります。' },
  { term: 'dependency injection', description: '必要な依存オブジェクトを外部から注入する考え方です。Spring の中心的な設計思想です。' },
  { term: '@Autowired', aliases: ['@autowired'], description: '型にもとづいて依存を自動注入するための代表的な Spring アノテーションです。' },
  { term: 'required=false in @Autowired', aliases: ['required=false in @autowired'], description: '依存が見つからない場合でも注入失敗にしないオプションです。任意依存を表すときに使います。' },
  { term: '@Qualifier', aliases: ['@qualifier'], description: '複数の候補 bean があるとき、絞り込み条件を与えるアノテーションです。' },
  { term: '@Primary', aliases: ['@primary'], description: '複数候補のうち、優先して注入される bean を示すアノテーションです。' },
  { term: 'type-driven injection', description: '型を基準に依存解決する Spring の注入方式です。@Autowired は基本的にこの考え方です。' },
  { term: '@Configuration', aliases: ['@configuration'], description: 'Spring へ bean 定義や設定を与える構成クラスを示すアノテーションです。' },
  { term: '@Bean', aliases: ['@bean'], description: '@Configuration クラス内で、生成したい bean をメソッド単位で定義するためのアノテーションです。' },
  { term: 'component scanning', description: '指定パッケージを走査し、Spring 管理対象コンポーネントを自動検出する仕組みです。' },
  { term: '@Component', aliases: ['@component'], description: 'Spring 管理対象の汎用コンポーネントを示すアノテーションです。' },
  { term: '@Service', aliases: ['@service'], description: 'サービス層の役割を持つコンポーネントを示すアノテーションで、@Component の特化形です。' },
  { term: '@Repository', aliases: ['@repository'], description: '永続化層や DAO 的役割を持つコンポーネントを示すアノテーションです。例外変換などの意味も持ちます。' },
  { term: '@Controller', aliases: ['@controller'], description: 'プレゼンテーション層のコントローラを示すアノテーションです。MVC 文脈で使われます。' },
  { term: '@RestController', aliases: ['@restcontroller'], description: '@Controller と @ResponseBody を組み合わせたメタアノテーションです。REST API 実装でよく使われます。' },
  { term: '@ResponseBody', aliases: ['@responsebody'], description: 'メソッド戻り値を HTTP レスポンスボディへシリアライズするためのアノテーションです。' },
  { term: 'HttpMessageConverter', aliases: ['httpmessageconverter'], description: 'Spring MVC がオブジェクトと HTTP ボディを相互変換する仕組みです。' },
  { term: 'Spring AOP', aliases: ['spring aop'], description: 'Spring の AOP フレームワークです。IoC を補完し、横断的関心事を分離しやすくします。' },
  { term: 'AOP (Spring)', aliases: ['aop (spring)'], description: 'Aspect-Oriented Programming の略で、クラス横断的な関心事を分離して扱う考え方です。' },
  { term: 'aspect', description: 'AOP におけるモジュール化単位です。トランザクションやログのような横断関心事を表現できます。' },
  { term: 'crosscutting concern', description: '複数クラスや層にまたがって現れる関心事です。AOP が対象とする代表概念です。' },
  { term: 'Spring Boot', aliases: ['spring boot'], description: '最小限の設定で stand-alone な production-grade Spring アプリを作りやすくする基盤です。' },
  { term: 'stand-alone application', description: '単独で起動できるアプリケーションです。Spring Boot はこれを作りやすいことを特徴にしています。' },
  { term: 'production-ready features', description: '本番運用向けの監視、管理、健全性確認などの機能群です。Spring Boot では Actuator が代表です。' },
  { term: 'Spring Initializr', aliases: ['spring initializr'], description: 'Spring Boot プロジェクトのひな形を生成する仕組みです。start.spring.io が代表的な入口です。' },
  { term: 'starter', description: '典型的な用途に必要な依存関係をまとめた Spring Boot 用パッケージ群です。' },
  { term: 'spring-boot-starter', description: 'Spring Boot のコアスターターで、自動設定やロギングなど基本機能を含みます。' },
  { term: 'spring-boot-starter-actuator', description: '運用監視、管理、メトリクス、ヘルスチェックなどを有効化する starter です。' },
  { term: 'auto-configuration', description: 'クラスパスや既存 bean を見て、必要な設定や bean を自動適用する Spring Boot の仕組みです。' },
  { term: '@AutoConfiguration', aliases: ['@autoconfiguration'], description: 'Spring Boot の自動設定クラスを表すアノテーションです。' },
  { term: '@ConditionalOnClass', aliases: ['@conditionalonclass'], description: '指定クラスが見つかる場合にだけ auto-configuration を適用する条件アノテーションです。' },
  { term: '@ConditionalOnMissingBean', aliases: ['@conditionalonmissingbean'], description: '利用者が同種 bean を定義していない場合にだけ自動設定を有効にする条件です。' },
  { term: 'externalized configuration', description: '設定値をコード外へ出し、環境ごとに切り替えやすくする考え方です。Spring Boot の特徴の一つです。' },
  { term: 'embedded server', description: 'アプリ内部へ組み込まれた Web サーバーです。Spring Boot では Tomcat、Jetty、Undertow を直接組み込めます。' },
  { term: 'java -jar deployment', description: '生成した JAR を java -jar でそのまま起動する配布方式です。Spring Boot の代表的な実行方法です。' },
  { term: 'Actuator', aliases: ['actuator'], description: 'Spring Boot の production-ready 機能群で、監視、管理、健全性確認を提供します。' },
  { term: 'actuator endpoint', description: 'Actuator が提供する各種管理用エンドポイントです。Spring Boot には組み込み endpoint が複数あります。' },
  { term: 'health endpoint (Spring Boot)', aliases: ['health endpoint (spring boot)'], description: 'アプリケーションの健全性を示す Actuator endpoint です。既定では /actuator/health にマップされます。' },
  { term: 'info endpoint', description: '任意のアプリケーション情報を返す Actuator endpoint です。' },
  { term: 'metrics endpoint', description: 'アプリが記録したメトリクス情報を確認するための Actuator endpoint です。' },
  { term: 'monitoring and management over HTTP', aliases: ['monitoring and management over http'], description: 'Spring Boot Actuator の有効 endpoint を HTTP 経由で公開する考え方です。Web アプリではこれが自動設定されます。' },
  { term: 'WebLogic', aliases: ['weblogic'], description: 'Oracleが提供するエンタープライズ向けJavaアプリケーションサーバ。' },
  { term: 'Apache Tomcat', aliases: ['apache tomcat'], description: 'Java系Webアプリケーションを実行するためのサーバソフトウェア。' },
  { term: 'JUnit', aliases: ['junit'], description: 'Javaプログラムの単体テストを自動化するための標準的なテストフレームワーク。' },
  { term: 'Apache POI', aliases: ['apache poi'], description: 'ExcelやWordなどのOfficeファイルをプログラムから操作するためのライブラリ。' },
  { term: 'Java Servlet', aliases: ['java servlet'], description: 'JavaでWebリクエストを処理する基本技術。' },
  { term: 'JSP', aliases: ['jsp', 'javaserver pages'], description: 'JavaベースでHTML画面を生成する古典的な技術。' },
  { term: 'Gradle', aliases: ['gradle'], description: 'JVM系プロジェクトでビルド、依存管理、テスト実行を自動化するツールです。' },
  { term: '@Getter', aliases: ['@getter'], description: 'Lombokでgetterメソッドを自動生成するためのアノテーションです。' },
  { term: '@Setter', aliases: ['@setter'], description: 'Lombokでsetterメソッドを自動生成するためのアノテーションです。' },
  { term: 'ServiceAspect', aliases: ['serviceaspect'], description: 'Serviceメソッドの前後で共通処理を差し込むためのAspectクラスやその実装です。' },
  { term: 'printStackTrace', aliases: ['printstacktrace'], description: 'Javaで例外のスタックトレースを標準エラー出力へ直接書き出すメソッドです。' },
  { term: 'ApiExceptionHandler', aliases: ['apiexceptionhandler'], description: 'API向けの例外をまとめて処理し、統一したエラーレスポンスへ変換するクラス名によく使われる名称です。' },
  { term: 'javax', description: 'Java EE時代から使われてきたJava系APIの名前空間プレフィックスです。' },
  { term: 'jakarta', description: 'Jakarta EEで採用されたJava系APIの新しい名前空間プレフィックスです。' },
  { term: 'Brian Goetz', aliases: ['brian goetz', 'ブライアン・ゲッツ'], description: 'Java並行処理の第一人者。著書『Java Concurrency in Practice』でスレッドセーフ設計のベストプラクティスを体系化した。OracleのJava言語アーキテクトを務める。' },
  { term: 'Java Concurrency in Practice', aliases: ['java concurrency in practice'], description: 'Brian Goetzらが著したJava並行処理の標準的教科書（2006年刊）。スレッドセーフ設計、不変オブジェクト、同期の最小化、高レベル並行ライブラリの活用などを体系的に解説する。並行処理を扱う開発者の必読書とされる。' },
];
