// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: tdd (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // junit (34), quality (24), tdd (18), Code Quality (15), jqwik (15), hypothesis (15), quality-management (8), pbt (8), Testing (2)
  { term: 'コード品質管理', aliases: ['code quality'], description: '動くだけでなく、読みやすさ・変更しやすさ・頑健性も含む品質です。システムを長く保守するほどその重要性が増します。' },
  { term: 'コード保守性', aliases: ['code maintainability'], description: '変更・調査・改善が容易な性質です。設計意図の明確さと関心事の分離が大きく影響します。' },
  { term: '変更容易性の確保', aliases: ['changeability'], description: '新しい要件や変更に対応しやすい性質です。将来の変化を見越して境界が引かれているかどうかが重要です。' },
  { term: '責務過多の解消', aliases: ['responsibility overload'], description: '単一のクラスや関数が多くの責任を持ちすぎた状態です。変更理由が増え、テストが難しくなります。' },
  { term: '長大関数の問題', aliases: ['long function'], description: '役割を持ちすぎて長くなりすぎた関数です。理解に時間がかかり、バグ混入率が高くなる傾向があります。' },
  { term: 'コードスメル除去', aliases: ['code smell remediation'], description: '将来問題になりうる兆候を早期に取り除くことです。バグになる前に対処することで将来のコストを下げます。' },
  { term: 'リファクタリング耐性の向上', aliases: ['refactoring resilience'], description: '改善時に壊れにくい状態です。しっかりとしたテストスイートがあるほど達成しやすくなります。' },
  { term: 'フラグ増殖問題', aliases: ['flag proliferation'], description: '条件フラグが多すぎて分岐が複雑になった状態です。状態遷移や責任分担の再設計が必要なサインである可能性があります。' },
  { term: '命名の品質', aliases: ['naming quality'], description: '名前が役割や意味を適切に表現している度合いです。良い命名はコメント以上に理解を助けることがあります。' },
  { term: '自己文書化コードの実践', aliases: ['self-documenting code'], description: '読むだけで理解しやすいコードです。コメントへの依存を減らし保守性を向上させます。' },
  { term: 'コメント負債の解消', aliases: ['comment debt'], description: '実装と合わなくなった古いコメントや説明が積み重なった状態です。コメントがない状態よりも危険なことがあります。' },
  { term: '設計実装乖離', aliases: ['design-implementation divergence'], description: 'ドキュメントの設計と実際のコードが一致しない状態です。時間が経つとどちらが正とするべきかわからなくなります。' },
  { term: 'コード生成負債の管理', aliases: ['code generation debt'], description: '自動生成コードへの過度な依存で人間が理解・変更しにくくなった状態です。生成コードのメンテナンス戦略が必要です。' },
  { term: 'ボイラープレートコード', aliases: ['boilerplate'], description: 'いたるところに現れる定型テンプレートコードです。生成や集約の候補ですが、意味ある重複を取り除かないよう注意が必要です。' },
  { term: 'メンテナンスコスト最適化', aliases: ['maintenance cost optimization'], description: '短期的な速さだけでなく将来の変更容易性も考慮して総コストを最適化することです。良い設計は初期開発より保守で真価を発揮します。' },
  { term: 'ビジュアルリグレッションテスト', aliases: ['visual regression testing'], description: '画面の視覚的差異を自動比較してレイアウト崩れを検出するテストです。UI変更の副作用を捕捉しやすくなります。' },
  { term: '非機能テスト項目表', aliases: ['non-functional test item table'], description: 'パフォーマンス・障害・監視の検証項目をまとめた表です。機能テストに埋もれがちな観点を捉えます。' },
  { term: '品質保証委員会', description: 'プロジェクト外部または横断視点で品質状態を点検し、必要な是正を求める組織。' },
  { term: '品質観点', description: 'テストやレビューで確認すべき着眼点。' },
  { term: 'Red-Green-Refactor', aliases: ['red-green-refactor'], description: '失敗するテストを書く、通す、整える、の反復サイクル。' },
  { term: 'Test case list', aliases: ['test case list'], description: 'TDDの最初に書き出しておくテスト候補一覧。' },
  { term: 'Failing test first', aliases: ['failing test first'], description: 'まず失敗するテストを用意してから実装へ進む考え方。' },
  { term: 'Make it work', aliases: ['make it work'], description: 'まずテストを通すことへ集中する段階。' },
  { term: 'Make it clean', aliases: ['make it clean'], description: 'テストが通った後に設計や構造を整える段階。' },
  { term: 'JUnit Jupiter', aliases: ['junit jupiter'], description: 'JUnit 5の中でテスト記述を担うプログラミングモデル。' },
  { term: 'Test class', aliases: ['test class'], description: '1つ以上のtest methodを含むJUnitのテストクラス。' },
  { term: 'Test method', aliases: ['test method'], description: '@Testや@ParameterizedTestなどで示される実行対象メソッド。' },
  { term: '@Test', aliases: ['@test'], description: '通常のテストメソッドを示すJUnit Jupiterアノテーション。' },
  { term: '@Disabled', aliases: ['@disabled'], description: 'そのテストを実行対象から外すアノテーション。' },
  { term: '@BeforeEach', aliases: ['@beforeeach'], description: '各テストメソッドの前に実行される初期化メソッド。' },
  { term: '@AfterEach', aliases: ['@aftereach'], description: '各テストメソッドの後に実行される後始末メソッド。' },
  { term: '@BeforeAll', aliases: ['@beforeall'], description: 'クラス全体のテスト前に一度だけ実行されるメソッド。' },
  { term: '@AfterAll', aliases: ['@afterall'], description: 'クラス全体のテスト後に一度だけ実行されるメソッド。' },
  { term: 'Aborted test', aliases: ['aborted test'], description: 'assumption不成立などで途中中止になるテスト。' },
  { term: 'Assumptions', aliases: ['assumptions'], description: '条件が成り立たなければテストを中止するための仕組み。' },
  { term: '@RepeatedTest', aliases: ['@repeatedtest'], description: '同じテストを複数回繰り返し実行するためのアノテーション。' },
  { term: 'Failure threshold', aliases: ['failure threshold'], description: '@RepeatedTestで、一定回数失敗したら残りを自動スキップする閾値。' },
  { term: '@ParameterizedTest', aliases: ['@parameterizedtest'], description: '複数の引数パターンで同じテストロジックを実行するためのアノテーション。' },
  { term: '@ValueSource', aliases: ['@valuesource'], description: '単純な値配列を@ParameterizedTestへ供給するアノテーション。' },
  { term: '@CsvSource', aliases: ['@csvsource'], description: 'CSV形式で引数を与えるparameterized test用アノテーション。' },
  { term: '@CsvFileSource', aliases: ['@csvfilesource'], description: 'CSVファイルから引数を読むparameterized test用アノテーション。' },
  { term: '@MethodSource', aliases: ['@methodsource'], description: 'メソッドが返す値列を引数ソースとして使うアノテーション。' },
  { term: 'Factory method convention', aliases: ['factory method convention'], description: '@MethodSourceでソース名を省略した場合、同名メソッドを探す規約。' },
  { term: 'ArgumentsAccessor', aliases: ['argumentsaccessor'], description: '@ParameterizedTestの引数へまとめてアクセスする補助型。' },
  { term: 'ArgumentsAggregator', aliases: ['argumentsaggregator'], description: '複数引数を1つのオブジェクトへまとめるための集約インターフェース。' },
  { term: '@AggregateWith', aliases: ['@aggregatewith'], description: 'ArgumentsAggregatorを@ParameterizedTest引数へ適用するアノテーション。' },
  { term: 'ParameterResolver', aliases: ['parameterresolver'], description: 'JUnit拡張としてテストメソッド引数を注入するための仕組み。' },
  { term: '@TestFactory', aliases: ['@testfactory'], description: '実行時にdynamic testsを生成するfactory methodを示すアノテーション。' },
  { term: 'DynamicTest', aliases: ['dynamictest'], description: '実行時に生成されるテストケース。display nameとexecutableを持つ。' },
  { term: 'DynamicNode', aliases: ['dynamicnode'], description: 'DynamicTestやDynamicContainerの共通上位概念。' },
  { term: 'DynamicContainer', aliases: ['dynamiccontainer'], description: 'DynamicNodeを階層構造でまとめるための実行時コンテナ。' },
  { term: '@TestTemplate', aliases: ['@testtemplate'], description: '拡張機構により複数回呼び出されるテンプレート型テスト。' },
  { term: '@Nested', aliases: ['@nested'], description: '入れ子のテストクラスを表すアノテーション。文脈ごとのグルーピングに使える。' },
  { term: '@Tag', aliases: ['@tag'], description: 'テストへ分類タグを付けるアノテーション。実行対象の絞り込みに使える。' },
  { term: 'Meta-annotation test', aliases: ['meta-annotation test'], description: '@Tagと@Testをまとめた独自アノテーションを作る使い方。' },
  { term: 'Display name generation', aliases: ['display name generation'], description: 'Parameterized testやrepeated testの表示名を規則で生成する仕組み。' },
  { term: 'Dynamic test lifecycle', aliases: ['dynamic test lifecycle'], description: 'Dynamic testは通常の@Testとライフサイクルが異なる。' },
  { term: 'No lifecycle callbacks for dynamic tests', aliases: ['no lifecycle callbacks for dynamic tests'], description: 'Dynamic testでは@BeforeEachや@AfterEachが各DynamicTestごとには実行されない。' },
  { term: 'jqwik', description: 'Java向けのproperty-based testingフレームワーク。' },
  { term: '@Property', aliases: ['@property'], description: 'jqwikでproperty-based testを示すアノテーション。' },
  { term: '@ForAll', aliases: ['@forall'], description: 'jqwikで生成値をpropertyへ注入するためのアノテーション。' },
  { term: 'Arbitrary', aliases: ['arbitrary'], description: 'jqwikにおける値生成戦略の基本型。' },
  { term: 'Arbitraries', aliases: ['arbitraries'], description: '文字列、整数などの基本Arbitraryを作るためのファクトリ群。' },
  { term: 'Domain Arbitrary', aliases: ['domain arbitrary'], description: '自分のドメイン型専用に作るArbitrary。' },
  { term: 'Combinators.combine', aliases: ['combinators.combine'], description: '複数Arbitraryを組み合わせて複雑なドメインオブジェクトを作るjqwikの機能。' },
  { term: 'Shrinking', aliases: ['shrinking'], description: '失敗例が見つかったときに、より小さく単純な失敗例へ縮めていく処理。' },
  { term: 'Integrated shrinking', aliases: ['integrated shrinking'], description: 'jqwikが採用しているshrinking方式。' },
  { term: 'Shrunk Sample', aliases: ['shrunk sample'], description: 'Shrinkingの結果として得られる、最小化された失敗入力例。' },
  { term: 'ShrinkingMode.OFF', aliases: ['shrinkingmode.off'], description: 'jqwikでshrinkingを無効化する設定。' },
  { term: 'ShrinkingMode.FULL', aliases: ['shrinkingmode.full'], description: 'jqwikでより徹底的にshrinkingする設定。' },
  { term: 'shrinking bound reached', description: 'jqwikが一定回数shrinkingしても最終候補へ収束しきれなかったことを示すメッセージ。' },
  { term: 'shrinkTowards', aliases: ['shrinktowards'], description: '数値などのshrinking先を0以外へ寄せるjqwikの指定。' },
  { term: 'flat mapping Arbitraries', aliases: ['flat mapping arbitraries'], description: '先に生成した値に依存して次のArbitraryを決める作り方。' },
  { term: 'unshrinkable permutations', description: 'jqwikのshuffleが返す、縮小しない並び替え生成。' },
  { term: 'stateful testing', description: '操作列全体がシステムを壊すかを検証するtestingスタイル。' },
  { term: 'invariant', description: 'どの状態でも成り立つべき性質。stateful testingの中心概念。' },
  { term: 'InvariantFailedError', aliases: ['invariantfailederror'], description: 'jqwikのstateful testingでinvariantが破られたことを示すエラー。' },
  { term: 'ServiceLoader-based Arbitrary registration', aliases: ['serviceloader-based arbitrary registration'], description: 'jqwikでdomain Arbitraryを全propertyから使えるようにするための登録方式。' },
  { term: 'Hypothesis', aliases: ['hypothesis'], description: 'Python向けのproperty-based testingライブラリ。' },
  { term: '@given', description: 'Hypothesisでtest関数へ生成値を与えるデコレータ。' },
  { term: 'strategies as st', description: 'Hypothesisで生成戦略群をstとして使う慣用的インポート。' },
  { term: '@settings', description: 'Hypothesisテストごとの挙動を調整するデコレータ。' },
  { term: 'settings profile', description: 'Hypothesisの共通設定を名前付きで登録、読み込む仕組み。' },
  { term: 'max_examples', description: 'Hypothesisが生成して試す例の上限設定。' },
  { term: 'replaying failures', description: '過去に失敗した例を再利用して再現確認する機能。' },
  { term: '@example', description: '生成例に加えて明示的な例を追加するHypothesisのデコレータ。' },
  { term: 'explicit example', description: '@exampleで与える手書きの具体例。' },
  { term: 'explicit examples do not shrink', description: '@exampleで与えた失敗例は自動shrinkingの対象にならない。' },
  { term: 'example database', description: '失敗例や有用な例を保存し、次回以降に再利用するHypothesisの仕組み。' },
  { term: 'database key', description: 'どのテストへ保存例をひもづけるかを決める識別。' },
  { term: 'HealthCheck', aliases: ['healthcheck'], description: 'テストが非効率、遅い、生成品質が悪いなどを知らせるHypothesisの警告機構。' },
  { term: 'suppress_health_check', description: '特定のHealthCheckを抑制するための設定。' },
  { term: 'deadline', description: '1テストケースあたりの実行時間目安を制御するHypothesisの設定。' },
  { term: 'verbosity', description: 'Hypothesisの出力詳細度を調整する設定。' },
  { term: 'falsifying example', description: 'Propertyを破る具体的な反例。' },
  { term: 'shrinker performance', description: '失敗例をどれだけ効率よく小さくできるかという観点。' },
  { term: 'QA', aliases: ['qa', 'quality assurance'], description: 'Quality Assuranceの略。品質保証のこと。テストや検査を通じてシステムの品質を確認・保証する活動・部門。QAエンジニアはテスト設計・実行・品質管理を担当する。' },
  { term: '指摘', aliases: ['レビュー指摘', 'コメント', '指摘事項'], description: 'レビューやテストで発見した問題点や改善点を伝えること。設計書レビューやコードレビューでの「この部分は修正が必要」という意見を指摘と呼ぶ。' },
  { term: '不具合票', aliases: ['バグ票', '障害票', 'defect ticket'], description: 'テストで発見したバグ・不具合を記録する票（チケット）。発見日、重要度、再現手順、担当者などを記載する。バグ管理ツール（Redmine、JIRAなど）で管理することが多い。' },
  { term: 'バグ管理', aliases: ['defect management', '不具合管理', 'バグトラッキング'], description: 'テストで発見したバグの登録・優先度付け・修正・検証・クローズまでのライフサイクルを管理すること。JIRAやRedmineなどのツールを使って管理する。' },
  { term: '原因分析', aliases: ['root cause analysis', 'rca', 'なぜなぜ分析'], description: '発生した不具合やインシデントの根本的な原因を特定する活動。「なぜなぜ分析」（なぜを5回繰り返す）がよく使われる手法。再発防止策の前提となる。' },
  { term: '再発防止', aliases: ['recurrence prevention'], description: '同じ問題が再度起きないための対策を立てること。原因分析の後に行い、プロセス改善・テスト強化・教育など具体的な対策を実施する。' },
  { term: 'テスト駆動開発', description: 'テストコードを先に書き、そのテストをパスするプロダクションコードを実装し、リファクタリングするサイクルを繰り返す開発手法。設計の改善と品質の内部化を促す。' },
  { term: 'レッドグリーンリファクタ', description: 'TDDの基本サイクル。まず失敗するテストを書き（レッド）、最小限のコードでパスさせ（グリーン）、コードを整理する（リファクタ）。' },
  { term: 'テストファースト', aliases: ['test first'], description: '実装コードより先にテストコードを書くアプローチ。TDDの根幹をなす原則で、テストが設計を駆動し、実装の意図を明確にする効果がある。' },
  { term: '仮実装', aliases: ['fake it', '仮の実装'], description: 'TDDでテストをグリーンにするため、ハードコードした値など最小限の偽の実装を行うこと。次のステップで正しい実装に置き換えることを前提とする。' },
  { term: '三角測量', aliases: ['triangulation'], description: 'TDDで汎用的な実装を引き出すため、複数の具体的なテストケースから共通のアルゴリズムを導く手法。1つのテストだけでは仮実装で済んでしまう場合に使う。' },
  { term: '明白な実装', aliases: ['obvious implementation'], description: 'TDDで実装が明らかな場合に仮実装を経ず直接正しいコードを書くアプローチ。三角測量や仮実装と並ぶTDDの実装戦略の一つ。' },
  { term: 'ベイビーステップ', aliases: ['baby steps'], description: 'TDDで非常に小さな変更を一歩ずつ積み重ねて進む開発スタイル。各ステップでテストが通る状態を維持し、フィードバックを素早く得る。' },
  { term: 'テストリスト', aliases: ['test list'], description: 'TDDを開始する前に実装すべきテストケースを書き出したリスト。これからやるべきことを整理し、一度に一つのテストに集中するための道具。' },
  { term: 'フェイクオブジェクト', aliases: ['fake object'], description: 'テスト用に本物の依存コンポーネントの動作を模倣する軽量な実装。インメモリDBなど実際に動作するが本番環境では使わない代替実装。' },
  { term: 'ダミー', aliases: ['dummy object', 'dummy'], description: 'テストに必要なメソッドシグネチャを満たすが、実際には使用されないオブジェクト。引数として渡すだけで動作は呼び出されない。' },
  { term: 'マイクロテスト', aliases: ['micro test'], description: '非常に小さなコード単位を対象とする高速なユニットテスト。外部依存を排除し、ミリ秒単位で実行できる粒度のテストを指す。' },
  { term: 'ソシアブルテスト', aliases: ['sociable test'], description: 'テスト対象が実際の依存コンポーネントと協調して動作することを検証するユニットテスト。モックを使わず実際の依存を含めてテストする。' },
  { term: 'ソリタリーテスト', aliases: ['solitary test'], description: 'テスト対象を外部依存から完全に分離し、モックやスタブで置き換えてテストするユニットテスト。依存のある孤立した単体テスト。' },
  { term: '回帰不具合の量産', description: '改修のたびに既存機能を壊し、多数の回帰不具合を繰り返し発生させる状態です。' },
  { term: '再現可能', description: '同じ条件をそろえると、同じ不具合や現象を繰り返し確認できる状態です。' },
  { term: '不整合', description: '関連する定義、実装、設定、データの間で内容が食い違っている状態です。' },
  { term: 'レビュー体制', description: '成果物や設計内容を確認し、問題を早期に見つけるための仕組みです。オフショア開発では認識差を減らす重要な要素です。' },
  { term: '品質の見える化', description: '不具合件数、テスト実施状況、レビュー結果などを可視化し、品質状態を把握しやすくすることです。' },
  { term: '品質管理プロセス', description: '品質を保つための手順や確認方法、レビューや指標管理の仕組みを指します。' },
  { term: '品質のばらつき', description: '担当者や時期によって成果物の品質が不安定になることです。チーム交代や標準不足で起こりやすくなります。' },
  { term: '品質方針', description: '組織としてどのような品質を目指し、どのように品質向上に取り組むかを示した基本方針です。' },
  { term: '品質向上', description: '現在の品質水準をさらに高めるための継続的な改善活動です。標準化、教育、レビュー、指標分析などが含まれます。' },
  { term: 'EXE品質', aliases: ['exe品質'], description: 'システムエグゼ独自の高品質・高付加価値を目指す品質観の表現です。' },
  { term: '品質保証責任者', description: '各開発本部に置かれ、品質管理業務を適正かつ円滑に進める責任を担う役割です。局面レビューや他本部との相互チェックにも関与します。' },
  { term: 'SQA', aliases: ['sqa'], description: 'Software Quality Assuranceの略です。プロジェクトで使われるプロセスや手順を監視し、適切な品質確保を支える役割です。' },
  { term: 'SEPG', aliases: ['sepg'], description: 'Software Engineering Process Groupの略です。組織のプロセス企画・構築・改善を担う役割で、品質改善担当として機能します。' },
  { term: '局面レビュー', description: 'プロジェクトの各工程ごとに、品質保証責任者などが成果物や進め方を確認するレビューです。工程ごとの問題を早期に発見する目的があります。' },
  { term: '相互チェック', description: '他本部や別組織の立場から活動状況を確認・評価することです。内輪の見落としを防ぎ、客観性を高めます。' },
  { term: '品質指標', description: '品質状態を定量的または定性的に把握するための尺度です。不具合件数やレビュー指摘数、テスト進捗などが該当します。' },
  { term: '定着度チェック', description: '決めたルールや活動が現場に実際に根付いているかを確認することです。制度だけ作って終わらせないための確認です。' },
  { term: '品質指標検証', description: '設定した品質指標が妥当か、目標達成や改善につながっているかを確認する活動です。' },
  { term: '品質推進体制', description: '組織的に品質を高めるための役割分担、責任範囲、会議体、報告ルートなどを含む体制のことです。' },
  { term: '高品質', description: '要求された品質を十分に満たし、信頼性や完成度が高い状態を指します。' },
  { term: 'プロジェクト品質向上委員会', description: '活動の定着度や品質指標の検証を行い、改善につなげる組織・会議体です。' },
  { term: '実効性', description: '仕組みやルールが実際に機能し、成果を生んでいる度合いです。ExecTORAの運用では特に重視されている観点です。' },
  { term: '品質保証体系', description: 'プロジェクト企画段階から出荷までの品質保証の流れを整理した枠組みです。' },
  { term: '入力精度向上', description: 'データ入力の誤りやばらつきを減らし、正確性を高めることです。' },
];
