// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: backend (1/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // backend (141), api (77), web-api (72)
  { term: 'API', aliases: ['api'], description: 'システム同士がデータや処理をやり取りするための窓口です。画面とサーバーの通信、他システム連携、外部サービス利用などで広く使われます。' },
  { term: 'エンドポイント', aliases: ['endpoint'], description: 'APIの接続先や呼び出し先を表す単位です。どのURLに、どの方式でアクセスすれば何ができるかを整理する中心要素になります。' },
  { term: 'リクエスト', aliases: ['request'], description: '【バックエンド】APIに送る要求データです。検索条件や登録内容だけでなく、認証情報や操作対象のIDも含まれることがあります。 【プロダクト】ユーザーやステークホルダーが求めること・望みです。整理されていない希望や不満を含むため、そのまま要件になるとは限りません。' },
  { term: 'レスポンス', aliases: ['response'], description: 'APIが返す結果データです。正常時の値だけでなく、エラーコードやメッセージもレスポンス設計の重要な対象です。' },
  { term: '冪等性', description: '同じ処理を複数回実行しても結果が変わらない性質です。二重送信や再試行が起こる環境では特に重要で、API設計でよく登場します。' },
  { term: '排他制御', aliases: ['concurrency control', 'exclusive control'], description: '同じデータを同時に更新して不整合が起きないように制御することです。業務特性に応じてロック方法や衝突時の扱いを決めます。' },
  { term: '楽観ロック', aliases: ['optimistic locking'], description: '競合はそれほど多くない前提で、更新時に衝突を検知する方式です。利用者の待ち時間を抑えやすい一方、衝突時の再入力や再試行設計が必要になります。' },
  { term: '悲観ロック', aliases: ['pessimistic locking'], description: '最初から他者の更新を防ぎ、競合を避ける方式です。整合性を守りやすい反面、待ちやすくなったり、長時間ロックの問題が出たりします。' },
  { term: 'サーバーレス', description: 'サーバー管理を強く意識せず、必要な処理だけを実行できる形態です。小さな機能を素早く作りやすい一方、長時間処理や密な制御には向き不向きがあります。' },
  { term: 'トレース', aliases: ['trace', 'distributed tracing'], description: '1つのリクエストが複数システムをどう通ったかを追跡する情報です。マイクロサービスやAPI連携が多い構成で原因調査に役立ちます。' },
  { term: 'APIキー', aliases: ['apiキー', 'api key'], description: 'API利用者を識別するための秘密情報です。漏えいすると不正利用や課金事故につながるため、厳重な管理が必要です。' },
  { term: 'キューイング', description: '処理待ちのデータを順番にためて、後続処理へ流すことです。急な負荷増加をならしたり、非同期化したりするのに役立ちます。' },
  { term: 'メッセージキュー', description: 'メッセージを一時的に蓄積して順次処理する仕組みです。バースト耐性や再試行設計と相性がよいです。' },
  { term: 'ステートレス', description: '個々の処理が前回の状態を内部に持たず、外部に依存して動く考え方です。スケールしやすく、クラウド環境と相性がよいです。' },
  { term: 'ステートフル', description: '処理途中の状態や接続状態を保持しながら動く設計です。機能によっては必要ですが、可用性やスケーリングの難易度は上がります。' },
  { term: 'スケールアウト', description: 'サーバー台数を増やして性能を上げる方法です。クラウドでは比較的取りやすい手段で、可用性向上にもつながります。' },
  { term: 'NAT', aliases: ['nat'], description: 'プライベート側のサーバーが外部へ通信するときに中継する仕組みです。外からは直接入れず、中からだけ出られる構成でよく使われます。' },
  { term: 'API Gateway', aliases: ['api gateway', 'apiゲートウェイ'], description: 'APIへの入口を一元化して制御する仕組みです。認証、制限、ログ、ルーティングなどを集中管理できます。' },
  { term: 'ヘルスエンドポイント', description: 'システムの稼働状態を確認するための専用APIです。監視やロードバランサーの判定に使われます。' },
  { term: 'バックエンド', description: '画面の裏で業務処理やデータ保存を担う部分です。フロントエンドの見た目に対し、こちらは意味や整合性を支えます。' },
  { term: 'サーバーサイドバリデーション', description: 'サーバー側で行う妥当性確認です。セキュリティや整合性を守るため、こちらを本命と考えるのが原則です。' },
  { term: 'プリフライトリクエスト', description: '本番の通信前に、ブラウザが事前確認として送る問い合わせです。CORS設計時に見落としやすいポイントです。' },
  { term: 'TanStack Query', aliases: ['tanstack query'], description: 'サーバーから取得したデータの取得、再取得、キャッシュ管理を支援するライブラリです。API連携が多い画面で非常に有効です。' },
  { term: 'SSE', aliases: ['sse'], description: 'Server-Sent Eventsの略で、サーバーからクライアントへ一方向に継続送信する仕組みです。リアルタイム通知を比較的シンプルに実現できます。' },
  { term: 'OpenAPI', aliases: ['openapi'], description: 'API仕様を機械可読な形で記述するための標準です。設計、ドキュメント生成、モック生成、テスト自動化までつなげやすくなります。' },
  { term: '推論API', aliases: ['推論api'], description: '学習済みモデルへ入力を渡し、結果を受け取るためのAPIです。AI機能を業務システムへ組み込む際の入口になります。' },
  { term: 'レスポンス品質', description: 'AI出力の正確さ、一貫性、役立ち度、読みやすさなどを含む概念です。単純な正解率では測りきれないため、評価設計が必要です。' },
  { term: 'バッチ分析', description: '一定期間分をまとめて処理する分析方式です。即時性より安定性やコスト効率を重視する場面に向きます。' },
  { term: 'モックサーバー', description: '本物の代わりに決まった応答を返す擬似サーバーです。外部連携先が未完成でもテストを進められる利点があります。' },
  { term: 'パブリックサブネット', description: '外部インターネットへ直接出入りしやすいネットワーク領域です。公開Webサーバーやゲートウェイなどが置かれることが多いです。' },
  { term: 'デッドレターキュー', description: '処理に何度も失敗したメッセージを隔離する場所です。失敗データを消さずに保ち、後で調査や再処理を行えます。' },
  { term: '時刻同期', description: '各サーバーや機器の時計をそろえることです。ログ相関や証跡の信頼性に直結するため、地味ですが非常に重要です。' },
  { term: 'レイテンシ最適化', description: 'AI応答を体感上速くする工夫です。短い回答を先に出す、非同期化する、部分表示するなどの設計が使われます。' },
  { term: 'API契約', aliases: ['api契約'], description: 'エンドポイント、入力、出力、エラー、認証方式などを含む取り決めです。単なるURL一覧ではなく、連携の約束事全体です。' },
  { term: '後方互換性', description: '新しいバージョンでも古い利用者がそのまま使える性質です。API公開では非常に重要で、安易な破壊的変更は避けるべきです。' },
  { term: '破壊的変更', description: '既存利用者の実装を壊してしまう変更です。必須項目追加やレスポンス形式変更などは典型例です。' },
  { term: 'APIバージョニング', aliases: ['apiバージョニング'], description: 'API仕様の変化を安全に管理するための版管理です。URL、ヘッダー、クエリなど複数の方式があります。' },
  { term: '廃止告知', description: 'APIや機能をいつ止めるかを正式に通知することです。利用者影響が大きいため、十分な周知と代替手段が必要です。' },
  { term: 'アイドポテンシーキー', description: '同じ要求の重複実行を避けるための識別子です。決済、申込、注文のような二重登録が危険なAPIで特に有効です。' },
  { term: 'At least once', aliases: ['at least once'], description: '少なくとも一回は届くことを重視する考え方です。重複受信の可能性があるため、受信側の冪等性が重要です。' },
  { term: 'スタブAPI', aliases: ['スタブapi'], description: '本物の代わりに決まった応答だけ返すAPIです。並行開発や障害切り分けで役立ちます。' },
  { term: 'APIモック', aliases: ['apiモック'], description: '本物に近い振る舞いを模した疑似APIです。フロント開発や連携前検証でよく使われます。' },
  { term: 'クォータ管理', description: '利用量上限を契約や利用者ごとに管理することです。SaaSや公開APIでよく使われます。' },
  { term: 'APIキー認証', aliases: ['apiキー認証'], description: 'APIキーを使って利用者や契約単位を識別する認証方式です。簡単ですが、権限粒度や漏えい対策に限界もあります。' },
  { term: 'BFF', aliases: ['bff'], description: 'Backend for Frontendの略で、フロントごとに最適化したバックエンド層です。モバイルとWebで必要なAPI構造が違う場合に有効です。' },
  { term: 'API集約', aliases: ['api集約'], description: '複数バックエンドをまとめて利用しやすい形にすることです。フロントの呼び出し回数削減や責務整理に役立ちます。' },
  { term: 'オーケストレーションAPI', aliases: ['オーケストレーションapi'], description: '複数内部処理をまとめて一つの利用者操作に見せるAPIです。便利ですが、責務が膨らみすぎないよう注意が必要です。' },
  { term: 'コントラクト駆動開発', aliases: ['contract-driven development'], description: 'API仕様を先に合意・文書化し、その契約に基づいて開発を進める手法です。チーム間の並行開発や誤解の防止に効果的です。' },
  { term: 'Webhookリトライ', aliases: ['webhookリトライ', 'webhook retry'], description: 'Webhookの配信が失敗した場合に自動的に再送する仕組みです。冪等性を考慮した受信側設計が必要です。' },
  { term: '冪等性キー', aliases: ['idempotency key'], description: '同じリクエストを複数回送っても結果が重複しないようにするためのキーです。ネットワーク障害やリトライ時の二重処理防止に使われます。' },
  { term: '相関ID', aliases: ['相関id', 'correlation id'], description: '複数のサービスやログをまたぐリクエストを追跡するための一意な識別子です。分散システムのデバッグやトレーシングに不可欠です。' },
  { term: 'リトライ制御', aliases: ['retry control'], description: '失敗したリクエストを再試行する回数・間隔・条件を管理する仕組みです。指数バックオフとジッターを組み合わせることが一般的です。' },
  { term: '最低1回配信', aliases: ['at-least-once delivery'], description: 'メッセージが少なくとも1回は届くことを保証する配信方式です。重複受信が発生し得るため、受信側で冪等性を担保する必要があります。' },
  { term: '最大1回配信', aliases: ['at-most-once delivery'], description: 'メッセージが最大1回だけ配信される方式です。重複は発生しませんが、障害時にメッセージが失われる可能性があります。' },
  { term: '正確に1回配信', aliases: ['exactly-once delivery'], description: 'メッセージがちょうど1回だけ処理されることを保証する配信方式です。実装コストが最も高く、分散トランザクションや冪等性キーを駆使して実現します。' },
  { term: '確認応答', aliases: ['acknowledgment'], description: 'メッセージやリクエストを受信・処理したことを送信側へ通知することです。ACKとも呼ばれ、配信保証の基盤となります。' },
  { term: '接続テスト', aliases: ['connectivity test'], description: 'ネットワークやAPIエンドポイントへの接続可否を検証するテストです。設定誤りや証明書の問題を早期に発見するために行います。' },
  { term: 'リポジトリ層', aliases: ['repository layer', 'daoパターン'], description: 'データベースへのアクセス処理をまとめた層。データの取得・保存・削除などDB操作を集約する。ビジネスロジックとDBの分離により、テストや変更がしやすくなる。' },
  { term: '非同期処理', aliases: ['asynchronous processing', 'async', '非同期'], description: '処理の完了を待たずに次の処理を進める方式。時間のかかる処理（ファイルダウンロード、API呼び出しなど）を非同期にすることで、画面の応答性を保つことができる。' },
  { term: 'キュー', description: '処理を順番に待つ仕組み。先に入れたものが先に処理される（FIFO）。大量のリクエストが来たときに順番に処理したり、後で処理したい仕事を一時的にためておくのに使う。' },
  { term: 'Canvas API', aliases: ['canvas api', 'canvas 2d api', 'canvasrenderingcontext2d'], description: 'HTMLの`<canvas>`要素上でJavaScriptを使って2Dグラフィックスを描画するAPI。図形・画像合成・ピクセル操作が可能で、ゲームやデータビジュアライゼーションに広く利用される。' },
  { term: 'Web Workers', aliases: ['web workers', 'ウェブワーカー', 'dedicated worker'], description: 'ブラウザのメインスレッドとは別のバックグラウンドスレッドでJavaScriptを実行する仕組み。UIをブロックせずに重い計算処理を行え、postMessageでメインスレッドと通信する。' },
  { term: 'localStorage', aliases: ['localstorage', 'local storage'], description: 'ブラウザが提供するキーバリュー型のクライアントサイドストレージ。オリジンごとに永続的にデータを保存でき、タブやウィンドウ間で共有される。容量は通常5〜10MB程度。' },
  { term: 'Fetch API', aliases: ['fetch api', 'フェッチapi'], description: 'ブラウザ標準のHTTPリクエストAPI。XMLHttpRequestの後継で、Promiseベースのインターフェースを持ち、リクエストとレスポンスをRequestオブジェクトとResponseオブジェクトで表現する。' },
  { term: 'History API', aliases: ['history api', 'history interface', 'web history api'], description: 'ブラウザの閲覧履歴を操作するWeb API。`pushState`・`replaceState`でURLを変更しページ遷移なしに履歴エントリを追加でき、SPAのルーティング実装の基盤となる。' },
  { term: 'Geolocation API', aliases: ['geolocation api', 'ジオロケーション api', 'geolocation interface'], description: 'ユーザーの現在位置（緯度・経度）をブラウザから取得するWeb API。デバイスのGPSやWi-Fi位置情報を利用し、ユーザーの許可を得た後に位置データを提供する。' },
  { term: 'Web Audio API', aliases: ['web audio api', 'ウェブオーディオapi', 'audiocontext'], description: 'ブラウザでオーディオを生成・処理・分析するための高度なAPI。AudioContextを中心にオーディオノードを接続するグラフ構造でエフェクト処理や音楽生成、波形解析が可能。' },
  { term: 'WebGL', aliases: ['webgl', 'web graphics library', 'webgl 2.0'], description: 'ブラウザ上でOpenGL ES 2.0/3.0ベースの3DグラフィックスをGPUを用いてレンダリングするWeb API。`<canvas>`要素と組み合わせてゲームや3Dビジュアライゼーションを実現する。' },
  { term: 'Intersection Observer', aliases: ['intersection observer', 'intersectionobserver', '交差オブザーバー'], description: '対象要素がビューポートや指定コンテナと交差した際に非同期でコールバックを呼び出すWeb API。スクロール連動のアニメーションや遅延読み込みを効率よく実装できる。' },
  { term: 'Mutation Observer', aliases: ['mutation observer', 'mutationobserver', 'ミューテーションオブザーバー'], description: 'DOMツリーへの変更（要素の追加・削除・属性変更など）を非同期で監視するWeb API。deprecated になった MutationEvent の代替で、パフォーマンスへの影響が小さい。' },
  { term: 'ResizeObserver', aliases: ['resizeobserver', 'リサイズオブザーバー'], description: 'DOM要素のサイズ変化を効率的に監視するWeb API。ウィンドウのresizeイベントと違い要素単位で変化を検知でき、レスポンシブなコンポーネント実装に利用される。' },
  { term: 'requestAnimationFrame', aliases: ['requestanimationframe', 'raf', 'アニメーションフレーム'], description: 'ブラウザの次の描画フレームに合わせてコールバックを実行するWeb API。`setInterval`より滑らかなアニメーションを実現でき、非表示タブでは自動的に停止してCPU消費を抑える。' },
  { term: 'Web Animations API', aliases: ['web animations api', 'waapi', 'ウェブアニメーションapi'], description: 'CSSアニメーションをJavaScriptで生成・制御するブラウザ標準API。`element.animate()`でキーフレームを指定し、再生速度や逆再生、一時停止をプログラムから操作できる。' },
  { term: 'Clipboard API', aliases: ['clipboard api', 'クリップボードapi'], description: 'クリップボードへの読み書きをブラウザから行うWeb API。`navigator.clipboard.writeText()`などを使い、テキストや画像をコピー・ペーストできる。ユーザー操作または権限許可が必要。' },
  { term: 'Drag and Drop API', aliases: ['drag and drop api', 'html drag and drop api', 'ドラッグアンドドロップ'], description: 'HTMLのドラッグ＆ドロップ操作をネイティブに扱うブラウザAPI。`draggable`属性と`dragstart`・`drop`などのイベントを組み合わせ、要素の並べ替えやファイル投入を実装する。' },
  { term: 'File API', aliases: ['file api', 'file web api', 'ファイルapi'], description: 'ユーザーが選択したファイルをJavaScriptで読み取るWeb API。FileオブジェクトとFileReaderを使い、テキスト・バイナリ・DataURLとしてファイルの内容にアクセスできる。' },
  { term: 'FormData', aliases: ['formdata', 'formdata api'], description: 'HTMLフォームのデータをキーバリュー形式で表すオブジェクト。ファイルを含むマルチパートデータを簡単に構築でき、Fetch APIと組み合わせてファイルアップロードを実装する。' },
  { term: 'Blob', aliases: ['blob', 'binary large object', 'ブロブ'], description: 'Binary Large Objectの略。ブラウザで任意のバイナリデータを表すオブジェクト。画像・動画・テキストなどのデータをメモリ上で扱い、URL.createObjectURL()でURLに変換して利用できる。' },
  { term: 'URL API', aliases: ['url api', 'url interface', 'urlsearchparams'], description: 'URLを解析・構築するブラウザ標準API。`new URL()`でURLオブジェクトを生成し、`searchParams`でクエリパラメータをセーフに操作できる。`URL.createObjectURL()`でBlobをURLに変換する機能も持つ。' },
  { term: 'SharedArrayBuffer', aliases: ['sharedarraybuffer', '共有配列バッファ'], description: '複数のWeb Workerやメインスレッドでゼロコピーのバイナリデータを共有するためのブラウザAPI。Atomicsと組み合わせてスレッド間の同期処理を実装できる。Cross-Origin Isolationが必要。' },
  { term: 'Performance API', aliases: ['performance api', 'navigation timing api', 'user timing api'], description: 'ページ読み込みやユーザーマーク、リソース取得のタイミングをブラウザから計測するWeb API。`performance.now()`や`PerformanceObserver`でRUM(リアルユーザーモニタリング)データを収集できる。' },
  { term: 'Navigation API', aliases: ['navigation api', 'navigation interface', 'app history api'], description: 'SPAでの画面遷移をネイティブにインターセプト・制御する比較的新しいWeb API。`navigation.navigate()`や`navigate`イベントで遷移をキャッチし、ブラウザの戻る・進むボタンと統合した履歴管理ができる。' },
  { term: 'View Transitions API', aliases: ['view transitions api', 'ビュートランジションapi'], description: 'ページ遷移や状態変化時にスムーズなクロスフェードなどのアニメーションを実現するブラウザAPI。`document.startViewTransition()`でDOM更新を包むだけでアニメーションが適用される。' },
  { term: 'Popover API', aliases: ['popover api', 'popover', 'ポップオーバーapi'], description: 'ツールチップやドロップダウンなどのポップオーバーUIをHTMLネイティブで実装するブラウザAPI。`popover`属性と`popovertarget`属性を使いJavaScript最小限でLight dismiss挙動を実現できる。' },
  { term: 'Web Storage', aliases: ['web storage', 'web storage api', 'ウェブストレージ'], description: 'ブラウザがクライアント側にデータを永続または一時的に保存するためのAPIの総称。localStorageとsessionStorageの2種類があり、どちらも文字列のキーバリュー形式でデータを管理する。' },
  { term: 'Broadcast Channel', aliases: ['broadcast channel', 'broadcastchannel', 'broadcastchannel api'], description: '同じオリジンの複数のブラウザコンテキスト（タブ、ウィンドウ、iframe）間でメッセージをブロードキャストするWeb API。タブ間の状態同期やサインアウト伝播などに利用する。' },
  { term: 'MessageChannel', aliases: ['messagechannel', 'messagechannel api', 'メッセージチャンネル'], description: '2つのポートを持つ双方向通信チャンネルを作成するWeb API。iframeや別のWorkerとpostMessageで専用の通信路を確立する際に使い、メッセージの混線を防げる。' },
  { term: 'postMessage', aliases: ['postmessage', 'window.postmessage', 'postmessage api'], description: '異なるオリジンのウィンドウ、iframe、Web Worker間でメッセージを安全に送受信するブラウザAPI。送信先のオリジンを明示的に指定することでセキュリティを確保する。' },
  { term: 'CustomEvent', aliases: ['customevent', 'カスタムイベント', 'customevent api'], description: '開発者が独自の型名とカスタムデータ（`detail`プロパティ）を持つDOMイベントを作成するインターフェース。コンポーネント間の疎結合な通信やカスタムDOM通知に利用する。' },
  { term: 'EventSource', aliases: ['eventsource', 'sse client', 'eventsource api'], description: 'サーバーからクライアントへのServer-Sent Events（SSE）を受信するためのブラウザAPI。HTTPコネクションを維持してサーバーからのプッシュ型テキストイベントをリアルタイムに受け取れる。' },
  { term: 'MediaDevices API', aliases: ['mediadevices api', 'getusermedia', 'mediadevices interface'], description: 'カメラ・マイク・画面などのメディアデバイスにアクセスするWeb API。`navigator.mediaDevices.getUserMedia()`でストリームを取得し、WebRTCや録音・録画アプリを構築できる。' },
  { term: 'Notifications API', aliases: ['notifications api', 'web notifications api', '通知api'], description: 'Webアプリからオペレーティングシステムのネイティブ通知を表示するブラウザAPI。ユーザーの許可を取得後にService Workerと組み合わせてバックグラウンド通知を実現できる。' },
  { term: 'Push API', aliases: ['push api', 'web push api', 'プッシュapi'], description: 'Service Workerと連携してサーバーからブラウザへプッシュメッセージを送受信するWeb API。アプリが非アクティブなときもプッシュサーバー経由で通知を受け取れ、PWAのエンゲージメント向上に使われる。' },
  { term: 'Cache API', aliases: ['cache api', 'cachestorage', 'cache storage api'], description: 'Service Workerが使用するネットワークリクエストとレスポンスのペアを保存・管理するストレージAPI。オフライン対応やキャッシュ戦略(Cache-First、Network-Firstなど)の実装基盤となる。' },
  { term: 'Payment Request API', aliases: ['payment request api', 'payment request', '決済api'], description: 'ブラウザネイティブの支払いUIを通じてチェックアウトフローを標準化するWeb API。クレジットカード情報やApple Pay・Google Payなどのデジタルウォレットを統一インターフェースで扱える。' },
  { term: 'Web Share API', aliases: ['web share api', 'web share', 'シェアapi'], description: 'WebアプリからネイティブのOS共有シートを呼び出してURLやテキスト・ファイルを他のアプリと共有するブラウザAPI。モバイルSNSシェアボタンなどをネイティブ連携で実装できる。' },
  { term: 'Vibration API', aliases: ['vibration api', 'vibration', 'バイブレーションapi'], description: 'デバイスのバイブレーション機能をWebアプリから制御するブラウザAPI。`navigator.vibrate()`でバイブレーションのパターンを指定し、ゲームやフォームバリデーションの触覚フィードバックに使う。' },
  { term: 'Fullscreen API', aliases: ['fullscreen api', 'fullscreen', 'フルスクリーンapi'], description: 'Webアプリの特定要素をフルスクリーン表示に切り替えるブラウザAPI。`element.requestFullscreen()`で動画プレーヤーやゲームキャンバスをフルスクリーン化し、ユーザー操作をトリガーにする必要がある。' },
  { term: 'Pointer Events', aliases: ['pointer events', 'pointer events api', 'ポインターイベント'], description: 'マウス・タッチ・スタイラスなど複数の入力デバイスを統一的に処理するWeb標準のイベントモデル。`pointerdown`・`pointermove`・`pointerup`でデバイス種別を問わず入力を扱える。' },
  { term: 'Touch Events', aliases: ['touch events', 'touch api', 'タッチイベント'], description: 'タッチスクリーン入力をブラウザで処理するイベントAPI。`touchstart`・`touchmove`・`touchend`でマルチタッチジェスチャーを実装できる。モバイルブラウザで広くサポートされている。' },
  { term: 'Gamepad API', aliases: ['gamepad api', 'gamepad interface', 'ゲームパッドapi'], description: 'ゲームパッドやジョイスティックのボタン・軸の状態をブラウザから読み取るWeb API。`navigator.getGamepads()`でデバイス一覧を取得し、requestAnimationFrameのループ内でポーリングして使う。' },
  { term: 'Web Bluetooth', aliases: ['web bluetooth', 'web bluetooth api', 'ウェブブルートゥース'], description: 'WebアプリからBluetoothデバイスと通信するブラウザAPI。HTTPS環境でユーザーの許可後にBLEデバイスとGATTプロファイル経由でデータを読み書きできる。ChromeおよびChromiumベースブラウザが主なサポート。' },
  { term: 'Web USB', aliases: ['web usb', 'webusb api', 'ウェブusb'], description: 'WebアプリからUSBデバイスと直接通信するブラウザAPI。HTTPS環境でユーザー許可のもとマイコンやカスタムデバイスとデータを交換でき、ドライバ不要のデバイス連携を実現する。' },
  { term: 'Web Serial', aliases: ['web serial', 'webserial api', 'ウェブシリアル'], description: 'WebアプリからシリアルポートやUSB-シリアル変換アダプタと通信するブラウザAPI。Arduinoなどのマイコンとのシリアル通信をブラウザだけで実現でき、IoTプロトタイピングに活用される。' },
  { term: 'File System Access API', aliases: ['file system access api', 'file system access', 'ファイルシステムアクセスapi'], description: 'ユーザーのローカルファイルシステムへのアクセスをブラウザから可能にするWeb API。ファイルを選択・読み書き・ディレクトリを開く操作をネイティブダイアログ経由で安全に実行できる。' },
  { term: 'Origin Private File System', aliases: ['origin private file system', 'opfs', 'プライベートファイルシステム'], description: 'ブラウザがオリジンごとに提供するサンドボックス化されたファイルシステム領域。File System Access APIの一部で、ユーザーには見えないがSQLiteデータベースファイルなどの高速なファイル操作に使われる。' },
  { term: 'Streams API', aliases: ['streams api', 'streams', 'readablestream'], description: 'データを小さなチャンクに分けて逐次処理するブラウザのストリーミングAPI。ReadableStream・WritableStream・TransformStreamで大容量データや継続的なデータを効率的に扱う。Fetch APIのレスポンスボディもReadableStreamで提供される。' },
  { term: 'CompressionStream', aliases: ['compressionstream', 'decompressionstream', 'compressionstream api'], description: 'ブラウザ標準のデータ圧縮・展開TransformStream。gzipやdeflateアルゴリズムでデータをストリーム形式で圧縮・解凍でき、サードパーティライブラリなしに圧縮処理を実装できる。' },
  { term: 'TextEncoder', aliases: ['textencoder', 'textencoder api'], description: '文字列をUTF-8のバイト列（Uint8Array）にエンコードするブラウザ標準API。バイナリ処理やStreams APIとの連携でテキストデータを効率的に変換する際に使用する。' },
  { term: 'TextDecoder', aliases: ['textdecoder', 'textdecoder api'], description: 'バイト列（ArrayBuffer・Uint8Array）を文字列にデコードするブラウザ標準API。UTF-8以外のエンコーディング指定も可能で、バイナリプロトコルやファイル解析時のテキスト変換に利用する。' },
  { term: 'PerformanceObserver', aliases: ['performanceobserver', 'performance observer'], description: 'ブラウザのパフォーマンスタイムラインエントリ（ナビゲーション・リソース・ペイント・レイアウトシフトなど）を非同期で監視するAPI。Core Web Vitalsの計測に使われる。' },
  { term: 'AbortController', aliases: ['abortcontroller', 'abortcontroller api', 'アボートコントローラー'], description: '非同期処理（Fetch APIなど）をキャンセルするためのシグナルを生成・送信するブラウザAPI。`controller.abort()`を呼ぶとAbortSignalに紐付いたリクエストが中断される。' },
  { term: 'AbortSignal', aliases: ['abortsignal', 'abort signal'], description: 'AbortControllerから生成されるシグナルオブジェクト。FetchリクエストやReact Query、その他の非同期処理に渡すことでキャンセル通知を受け取る仕組みを提供する。' },
  { term: 'queueMicrotask', aliases: ['queuemicrotask', 'queuemicrotask api', 'マイクロタスクキュー'], description: 'マイクロタスクキューにコールバックをスケジュールするブラウザAPIとNode.js API。現在のタスク完了直後・次のマクロタスク前に実行されるため、Promise.resolve().then()より明示的なマイクロタスク挿入手段として使われる。' },
  { term: 'structuredClone', aliases: ['structuredclone', 'structured clone algorithm', 'ストラクチャードクローン'], description: 'JavaScriptオブジェクトのディープクローンを作成するブラウザ・Node.js標準関数。JSON.parse(JSON.stringify())と違い、Date・Map・Set・ArrayBufferなど多様な型を正確に複製できる。' },
  { term: 'Web Crypto API', aliases: ['web crypto api', 'web cryptography api', 'subtlecrypto'], description: '暗号化・復号・ハッシュ・電子署名・鍵生成などの暗号処理をブラウザネイティブで実行するAPI。SubtleCryptoインターフェースを通じてAES・RSA・ECDSAなどのアルゴリズムを利用できる。' },
  { term: 'Selection API', aliases: ['selection api', 'selection interface', 'テキスト選択api'], description: 'ユーザーがページ上で選択したテキスト範囲を取得・操作するブラウザAPI。`window.getSelection()`でSelectionオブジェクトを取得し、選択範囲のテキスト抽出やプログラムによる選択変更が可能。' },
  { term: 'Range API', aliases: ['range api', 'range interface', 'dom range'], description: 'ドキュメント内の任意のコンテンツ範囲を表し操作するブラウザAPI。`document.createRange()`で生成し、テキスト範囲の選択・コピー・変更をプログラムで行うリッチテキストエディタ実装などに使う。' },
  { term: 'EventTarget', aliases: ['eventtarget', 'eventtarget interface', 'イベントターゲット'], description: 'DOMイベントを受信・送信するオブジェクトの基底インターフェース。`addEventListener`・`removeEventListener`・`dispatchEvent`を持ち、Element・Window・WorkerなどほぼすべてのDOM APIがこれを継承する。' },
  { term: 'addEventListener', aliases: ['addeventlistener', 'addeventlistener api', 'イベントリスナー登録'], description: 'EventTargetにイベントハンドラを登録するDOMメソッド。第3引数でオプション（capture・passive・once）を指定でき、passiveオプションをtrueにするとスクロールパフォーマンスが向上する。' },
  { term: 'dispatchEvent', aliases: ['dispatchevent', 'dispatchevent api', 'イベント発火'], description: 'EventTargetに対して指定したEventオブジェクトを同期的に発火するDOMメソッド。CustomEventと組み合わせてコンポーネント間の通知やテストでのイベントシミュレーションに利用する。' },
  { term: 'querySelector', aliases: ['queryselector', 'queryselector api', 'dom selector'], description: 'CSSセレクタを使ってドキュメントまたは要素ツリー内の最初にマッチする要素を取得するDOMメソッド。`document.querySelector(\'.btn\')`のように直感的に要素を取得でき、モダンなDOM操作の標準的な手段。' },
  { term: 'innerHTML', aliases: ['innerhtml', 'innerhtml プロパティ'], description: '要素のHTMLコンテンツを文字列として取得または設定するDOMプロパティ。設定時は文字列がHTMLとしてパースされ既存の子要素を置き換える。ユーザー入力をそのまま設定するとXSSリスクがあるため注意が必要。' },
  { term: 'textContent', aliases: ['textcontent', 'textcontent プロパティ'], description: '要素内のすべてのテキストノードを連結した文字列を取得または設定するDOMプロパティ。innerHTMLと違いHTMLタグを解釈せずテキストとして扱うため、XSSリスクがなくテキスト操作に適する。' },
  { term: 'Express', aliases: ['express', 'express.js', 'expressjs'], description: 'Node.js向けの軽量Webフレームワーク。最小限のAPIでHTTPサーバーを構築でき、ミドルウェアチェーンによるリクエスト処理が特徴。長年Node.jsのデファクトスタンダードとして広く採用されている。' },
  { term: 'Fastify', aliases: ['fastify'], description: '高パフォーマンスなNode.js Webフレームワーク。JSON Schemaを使ったルート定義と高速なシリアライゼーションにより、Expressより大幅に高いスループットを実現する。プラグインシステムによる拡張性も優れる。' },
  { term: 'NestJS', aliases: ['nestjs', 'nest'], description: 'TypeScriptファーストのNode.js Webフレームワーク。Angular風のデコレータベースアーキテクチャを採用し、DIコンテナ、モジュール分割、ガード、インターセプタなどエンタープライズ向け機能を標準提供する。' },
  { term: 'Koa', aliases: ['koa', 'koa.js'], description: 'Expressの後継として設計されたNode.js向けWebフレームワーク。コールバック地獄を排除するためasync/awaitを前提とした設計で、コアは最小限にとどめミドルウェアで機能を拡張する。' },
  { term: 'Hono', aliases: ['hono'], description: 'エッジランタイム（Cloudflare Workers、Deno、Bun等）向けに設計された超軽量Webフレームワーク。Web Standards APIに準拠しており、Node.jsを含む多様なランタイムで動作する高速なルーターを持つ。' },
  { term: 'リクエストハンドラ', aliases: ['request handler', 'ルートハンドラ'], description: '特定のHTTPルートとメソッドの組み合わせに対応する処理関数。リクエストオブジェクトからパラメータやボディを取得し、処理を行ってレスポンスを返す役割を担う。コントローラメソッドとも呼ばれる。' },
  { term: 'データアクセス層', aliases: ['data access layer', 'dal'], description: 'データベースやストレージへのアクセスをカプセル化するレイヤー。サービス層からデータの永続化の詳細を隠蔽し、リポジトリパターンやActiveRecordパターンで実装されることが多い。' },
  { term: 'Prisma', aliases: ['prisma'], description: 'TypeScript向けの次世代ORM。スキーマファイルからDBマイグレーションと型付きクライアントコードを自動生成する。型安全なクエリAPIにより実行時エラーを防ぎ、開発体験を大幅に向上させる。' },
  { term: 'Drizzle', aliases: ['drizzle', 'drizzle orm', 'drizzle-orm'], description: 'TypeScriptファーストの軽量ORM。SQLに近い直感的なAPIでクエリを記述でき、SQLiteからPostgreSQLまで対応。バンドルサイズが小さくエッジランタイムとの相性が良い。' },
  { term: 'TypeORM', aliases: ['typeorm'], description: 'TypeScript/JavaScript向けのORM。Active RecordとData Mapperの両パターンをサポートし、デコレータによるエンティティ定義とマイグレーション管理機能を持つ。NestJSとの組み合わせで広く使われる。' },
  { term: 'クエリビルダ', aliases: ['query builder'], description: '【バックエンド】生のSQLを文字列で記述せずに、メソッドチェーンやAPIを使ってプログラム的にSQLクエリを構築する仕組み。SQLインジェクション防止と動的クエリ生成の両立を助ける。 【OCI APEX】ドラッグ操作でSQLを組み立てる支援機能。' },
  { term: 'BullMQ', aliases: ['bullmq', 'bull'], description: 'RedisをバックエンドとするNode.js向けの高機能ジョブキューライブラリ。優先度付きキュー、遅延ジョブ、繰り返しスケジュール、進捗追跡、ジョブ間依存関係などを備える。' },
  { term: 'Worker Threads', aliases: ['worker threads', 'worker_threads'], description: 'Node.jsのビルトインモジュールで、CPUバウンドな処理をメインスレッドから切り離した別スレッドで実行する機能。SharedArrayBufferを介したスレッド間データ共有も可能で、並列計算の性能を改善する。' },
  { term: 'Cluster', aliases: ['cluster', 'cluster module'], description: 'Node.jsのビルトインモジュールで、マルチコアCPUを活用するためにマスタープロセスが複数のワーカープロセスをフォークする仕組み。各ワーカーは同じポートを共有してリクエストを並列処理できる。' },
  { term: 'child_process', aliases: ['child process'], description: 'Node.jsのビルトインモジュールで、子プロセスを生成して外部コマンドやスクリプトを実行する機能。exec/spawn/forkなどのAPIがあり、標準入出力のストリームを通じて親子プロセス間でデータをやり取りする。' },
  { term: 'Node.js Stream', aliases: ['node.js stream', 'readable stream', 'writable stream', 'transform stream'], description: 'Node.jsにおけるデータを逐次的に処理するための抽象インターフェース。大きなファイルやネットワークデータをメモリに全部読み込まずチャンク単位で処理できる。Readable、Writable、Transform等の種類がある。' },
  { term: 'EventEmitter', aliases: ['eventemitter', 'events module'], description: 'Node.jsの組み込みイベントシステムの基底クラス。on/emitメソッドで任意のイベントをリスナーに伝達するPub/Subパターンを提供し、HTTPサーバーやStreamなどNode.jsコアAPIの多くがこれを継承する。' },
  { term: 'fs/promises', aliases: ['fs.promises', 'filesystem api'], description: 'Node.jsのファイルシステム操作をPromiseベースで提供するAPIセット。コールバックスタイルのfsモジュールとは異なり、async/awaitで直感的にファイルの読み書き・ディレクトリ操作が記述できる。' },
  { term: 'process.env', aliases: ['environment object'], description: 'Node.jsプロセスが起動時に受け取った環境変数へのアクセスオブジェクト。APIキーや接続文字列などの秘匿情報をソースコードに埋め込まずに外部から注入するために利用する。dotenvと組み合わせて使われる。' },
  { term: 'dotenv', aliases: ['.env file'], description: '.envファイルに記述したキーバリューペアをprocess.envに読み込むNode.jsライブラリ。開発環境での設定管理を簡素化し、本番環境との設定分離を促す。.envファイルはgitignoreで管理する。' },
  { term: 'helmet', aliases: ['helmet.js'], description: 'Express/Fastify向けのセキュリティヘッダー設定ミドルウェア。Content-Security-Policy、X-Frame-Options、X-XSS-Protectionなど複数のHTTPセキュリティヘッダーを適切に設定し、一般的なWeb攻撃を軽減する。' },
  { term: 'CORS設定', aliases: ['cors設定', 'cross-origin resource sharing設定', 'cors middleware'], description: '異なるオリジン（ドメイン・ポート・プロトコル）からのHTTPリクエストを許可・制限するサーバーサイドの設定。許可するオリジン、メソッド、ヘッダーを明示的に指定し、ブラウザのセキュリティポリシーと連携する。' },
  { term: 'セッション管理', aliases: ['session management'], description: 'ステートレスなHTTPプロトコル上でユーザーの状態を保持する仕組み。セッションIDをCookieで管理し、サーバー側またはRedisなどの外部ストアにセッションデータを保存する。スケールアウト時はセッションの共有が課題になる。' },
  { term: 'JWT認証', aliases: ['jwt認証', 'jwt authentication', 'json web token認証'], description: 'JSON Web Tokenを使ったステートレスな認証方式。ヘッダー・ペイロード・署名の3部構成で、サーバーはトークン検証のみで認証でき状態保持が不要。アクセストークンとリフレッシュトークンの組み合わせが一般的。' },
  { term: 'Passport.js', aliases: ['passport.js', 'passport', 'passport strategy'], description: 'Node.js向けの認証ミドルウェア。Strategy パターンを採用し、Local Strategy（ユーザー名/パスワード）やOAuth Strategy（Google、GitHubなど）など多様な認証方式をプラグイン形式で切り替えられる。' },
  { term: 'bcrypt', aliases: ['bcryptjs'], description: 'パスワードのハッシュ化アルゴリズムおよびNode.jsライブラリ。ソルトとコストファクター（ストレッチング回数）により、ブルートフォース攻撃やレインボーテーブル攻撃に対して堅牢なパスワード保存を実現する。' },
  { term: 'GraphQL Resolver', aliases: ['graphql resolver', 'resolver', 'リゾルバ'], description: 'GraphQLスキーマの各フィールドに対してデータを取得・加工して返す関数。クエリ・ミューテーション・サブスクリプションそれぞれにResolverを定義し、データソース（DB、外部API等）から値を解決する。' },
  { term: 'WebSocket Server', aliases: ['websocket server', 'websocketサーバー', 'ws library'], description: 'WebSocketプロトコルを実装したサーバーコンポーネント。クライアントと双方向の持続的な接続を確立し、リアルタイムな双方向データ通信を実現する。Node.jsではwsライブラリやSocket.IOが代表的。' },
  { term: 'SSEサーバー', aliases: ['sseサーバー', 'sse server', 'server-sent eventsサーバー'], description: 'Server-Sent Events（SSE）プロトコルを実装したサーバー。text/event-streamコンテントタイプのHTTPレスポンスを使ってサーバーからクライアントへ単方向のストリーミングデータを送り続ける。AIチャットのストリーミングに多用される。' },
  { term: 'multer', aliases: ['multer middleware'], description: 'multipart/form-dataを扱うExpress向けのミドルウェア。ファイルアップロードをハンドリングし、アップロードされたファイルをメモリまたはディスクに保存する。保存先・ファイルサイズ制限・ファイル名の設定が可能。' },
  { term: 'formidable', aliases: ['node-formidable'], description: 'Node.js向けのフォームデータおよびファイルアップロードパーサーライブラリ。大容量ファイルをストリームベースで処理し、multerよりフレームワーク非依存でありNext.jsのAPIルートなどでも利用される。' },
  { term: 'compression', aliases: ['gzip middleware', 'brotli compression'], description: 'HTTPレスポンスボディをgzipやBrotliで圧縮して転送量を削減するミドルウェア。ネットワーク帯域の節約とページロード速度の改善に効果的で、テキスト系コンテンツ（HTML/JSON/CSS）で特に有効。' },
  { term: 'ETag', aliases: ['etag', 'entity tag'], description: 'HTTPレスポンスのコンテンツを一意に識別するためのヘッダー値。リソースが変更されていなければクライアントはキャッシュを再利用でき、304 Not Modifiedを返すことで不要なデータ転送を省く条件付きリクエストに使われる。' },
  { term: '条件付きリクエスト', aliases: ['conditional request', 'if-none-match', 'if-modified-since'], description: 'クライアントが保持するキャッシュの鮮度をサーバーに問い合わせるHTTPリクエスト。ETagを使うIf-None-Matchや最終更新日時を使うIf-Modified-Sinceヘッダーで条件を指定し、変更なければ304で返す。' },
  { term: 'コンテントネゴシエーション', aliases: ['content negotiation'], description: 'HTTPリクエストのAcceptヘッダーに基づきサーバーが最適なレスポンス形式（JSON、XML、HTML等）を選択するメカニズム。同一エンドポイントで複数のメディアタイプに対応する際に使われる。' },
  { term: 'ミドルウェアパターン', aliases: ['middleware pattern', 'パイプラインパターン'], description: 'HTTPリクエストとレスポンスの処理を複数の独立した関数（ミドルウェア）のチェーンとして構成するパターン。各ミドルウェアはリクエストを受け取り、処理を行い、次のミドルウェアへ渡すか、レスポンスを完了させる。' },
  { term: 'インターセプタ', aliases: ['interceptor', 'nestjs interceptor'], description: 'NestJSなどのフレームワークでメソッド実行の前後に追加処理を差し込む仕組み。ロギング、レスポンス変換、キャッシュ、タイムアウト処理などを横断的に適用するアスペクト指向的なアプローチ。' },
  { term: 'バリデーションパイプ', aliases: ['validation pipe', 'nestjs pipe'], description: 'NestJSにおいてルートハンドラへの入力データを変換・検証するコンポーネント。class-validatorと組み合わせてDTOのバリデーションを自動化し、型変換やデータ整形も担う。' },
  { term: 'ルートガード', aliases: ['route guard', 'nestjs guard'], description: 'NestJSにおいてルートハンドラの実行可否を制御するコンポーネント。認証・認可チェックに使われ、canActivate()メソッドでリクエストを許可するか拒否するかを返す。ロールベースの認可実装に多用される。' },
  { term: 'データ転送オブジェクト', aliases: ['data transfer object'], description: 'レイヤー間でデータを転送するために使うオブジェクト。HTTPリクエストボディやレスポンスの形状を型安全に定義し、余分なフィールドの混入を防ぐ。class-validatorデコレータと組み合わせてバリデーションにも使う。' },
  { term: 'データベースマイグレーション', aliases: ['migration', 'db migration'], description: 'データベーススキーマの変更をバージョン管理されたスクリプトで管理する仕組み。カラム追加・テーブル変更などをコードで定義し、適用・ロールバックを制御可能にする。PrismaやFlyway、Liquibaseが代表的ツール。' },
  { term: 'シード', aliases: ['seeding', 'db seed', 'データシード'], description: '開発・テスト環境のデータベースに初期データや参照データを投入するスクリプトや処理。本番データのサブセットやダミーデータを使って開発環境を再現性高くセットアップする。' },
  { term: 'トランザクション管理', aliases: ['transaction management', 'db transaction'], description: '複数のDB操作をひとまとまりとして、すべて成功するかすべて失敗する（原子性）ように制御する仕組み。ACID特性を保証し、部分的更新によるデータ不整合を防ぐ。サービス層やORMのトランザクションAPIで管理する。' },
  { term: 'グレースフルシャットダウン', aliases: ['graceful shutdown', '優雅な終了'], description: 'サーバーがシャットダウン要求を受けた際、処理中のリクエストを完了してから安全に終了する仕組み。進行中のリクエストを強制切断するのを避け、データ損失やユーザー向けエラーを防ぐ。' },
  { term: '環境変数', aliases: ['environment variable', 'env var'], description: 'プロセスの実行環境に設定されるキーバリューペア。APIキー、DB接続文字列、フィーチャーフラグなど環境依存の設定値をコードに埋め込まずに外部から注入する標準的な手法。12ファクターアプリの原則の一つ。' },
  { term: 'cronジョブ', aliases: ['cron job', 'スケジュールジョブ', 'node-cron'], description: 'cron形式の時刻表現（例: 0 9 * * 1-5）でスケジュール実行するバックグラウンドジョブ。定期的なデータ集計、バッチ処理、キャッシュ更新などに使われる。Node.jsではnode-cronやBullMQのrepeat機能で実装する。' },
  { term: 'バックプレッシャー制御', aliases: ['backpressure control', 'flow control'], description: 'ストリームやキューでデータの生産速度が消費速度を超えるときに生産側を制御する仕組み。Node.js Streamではwriteが`false`を返した場合に`drain`イベントを待って送信を再開することでメモリ溢れを防ぐ。' },
  { term: 'Webhook', aliases: ['webhook'], description: '特定のイベント発生時に登録されたURLへHTTP POSTリクエストを送信するコールバック機構。GitHubやStripeなど外部サービスが自サービスにイベントをプッシュ通知するために広く使われる。' },
  { term: 'カーソルページネーション', aliases: ['cursor-based pagination', 'cursor pagination'], description: '前ページの最後のアイテムを示すカーソル（opaque token）を使って次ページを取得するページネーション方式。行のオフセット計算をしないため、データ挿入があってもページ飛びが発生せず大規模データに適する。' },
  { term: 'OpenAPI仕様', aliases: ['openapi仕様', 'openapi specification', 'oas'], description: 'REST APIの仕様を機械可読なYAML/JSON形式で記述する標準仕様。エンドポイント、パラメータ、レスポンススキーマを定義し、Swagger UIによるドキュメント生成やコード生成ツールと連携できる。' },
  { term: 'Swagger UI', aliases: ['swagger ui', 'swagger-ui', 'swagger editor'], description: 'OpenAPI仕様を視覚的にレンダリングし、ブラウザ上でAPIエンドポイントを試せるインタラクティブドキュメントツール。NestJSでは@nestjs/swaggerモジュールで自動生成できる。' },
  { term: 'プロキシサーバー', aliases: ['proxy server', 'reverse proxy'], description: 'クライアントとバックエンドサービスの間に位置するサーバー。リバースプロキシはSSL終端、ロードバランシング、静的ファイル配信、キャッシュを担う。NginxやCaddyが代表的な実装。' },
  { term: 'スティッキーセッション', aliases: ['sticky session'], description: 'ロードバランサーが同一クライアントのリクエストを常に同じサーバーインスタンスへ送る機能。インメモリセッションを使うアプリのスケールアウトを可能にするが、特定インスタンスへの集中リスクがある。' },
  { term: 'Prismaスキーマ', aliases: ['prismaスキーマ', 'prisma schema', 'schema.prisma'], description: 'Prisma ORMのデータモデル定義ファイル。モデル、フィールド、リレーション、データソース接続を1つのschema.prismaに記述し、prisma generateでクライアントを、prisma migrateでマイグレーションを生成する。' },
  { term: 'GraphQL Federation', aliases: ['graphql federation', 'apollo federation', 'スキーマフェデレーション'], description: '複数のGraphQLサービスのスキーマを単一のスーパーグラフとして統合するアーキテクチャ。各サービスが独自のスキーマを所有しつつ、Apolloゲートウェイが統合されたAPIを公開する。マイクロサービスとGraphQLを組み合わせる際の標準アプローチ。' },
  { term: 'tRPC', aliases: ['trpc'], description: 'TypeScriptの型推論を活用してAPIクライアントとサーバーの型を共有するRPCフレームワーク。OpenAPIのようなスキーマ定義なしにエンドツーエンドの型安全を実現し、Next.jsと組み合わせて特に普及している。' },
  { term: 'HTTPキャッシュ制御', aliases: ['httpキャッシュ制御', 'http cache-control', 'cache-control header'], description: 'HTTPレスポンスのCache-Controlヘッダーを使ってキャッシュの動作を制御する仕組み。max-age、no-cache、s-maxage、stale-while-revalidateなどのディレクティブでクライアントとCDNのキャッシュ戦略を細かく制御する。' },
  { term: 'OWASP Top 10', aliases: ['owasp top 10', 'owasp', 'owaspトップ10'], description: 'Webアプリケーションに対する最も重大な10種のセキュリティリスクをまとめたOWASPが公表するリスト。インジェクション、認証の不備、XSS、IDOR、セキュリティの設定ミスなどが含まれ、セキュリティ対策の標準的な参照先となる。' },
  { term: 'プリペアドステートメント', aliases: ['prepared statement', 'パラメータ化クエリ'], description: 'SQLクエリのテンプレートを事前にDBにコンパイルし、実行時にパラメータを別チャネルで渡す仕組み。ユーザー入力がSQLとして解釈されずSQLインジェクションを根本的に防げる。' },
  { term: 'CSRFトークン', aliases: ['csrfトークン', 'csrf token', 'cross-site request forgery token'], description: 'クロスサイトリクエストフォージェリ（CSRF）攻撃を防ぐためにフォームやAPIリクエストに含める秘密トークン。サーバーが発行し、リクエストに同じ値が含まれるかを検証することで、悪意あるサイトからの偽リクエストを排除する。' },
  { term: 'HMAC', aliases: ['hmac', 'hash-based message authentication code'], description: '秘密鍵を使ったハッシュ関数によりメッセージの完全性と真正性を検証する認証コード。Webhookの署名検証（GitHub WebhookのX-Hub-Signature）やJWTのHS256署名などに使われる。' },
  { term: 'Pino', aliases: ['pino', 'pino logger'], description: '高速なNode.js向け構造化ロガー。JSON形式でログを出力し、最小限のオーバーヘッドで高スループットなロギングを実現する。非同期ログ書き込みとpino-prettyによる開発時の整形表示が特徴。' },
  { term: 'Winston', aliases: ['winston', 'winston logger'], description: 'Node.js向けの多機能ロギングライブラリ。複数のトランスポート（コンソール、ファイル、HTTP、外部サービス等）へ同時に出力でき、ログレベルとフォーマットを柔軟に設定できる。' },
  { term: 'マルチテナンシー', aliases: ['multi-tenancy', 'マルチテナント'], description: '単一のアプリケーションインスタンスで複数のテナント（顧客・組織）のデータを分離して扱うアーキテクチャ。スキーマ分離、DB分離、行レベル分離など分離レベルのトレードオフを設計する必要がある。' },
  { term: '行レベルセキュリティ', aliases: ['row level security', 'rls'], description: 'DBテーブルの行単位でアクセス制御を行うPostgreSQLの機能。テナントIDカラムに基づいてSQLに自動でWHERE句を付加し、アプリケーション層でのフィルタリングなしにデータ分離を保証する。' },
  { term: 'gRPCストリーミング', aliases: ['grpcストリーミング', 'grpc streaming', '双方向ストリーミングrpc'], description: 'gRPCが提供するストリーミングRPCモード。サーバーストリーミング、クライアントストリーミング、双方向ストリーミングの3種類があり、HTTP/2の多重化を活かしてリアルタイムデータ配信や大量データ転送を効率化する。' },
  { term: 'Redis', aliases: ['redis'], description: 'インメモリのKey-Valueストア。文字列、リスト、セット、ソート済みセット、ハッシュなど多様なデータ構造をサポートし、セッションストア、キャッシュ、ジョブキュー（BullMQ）、Pub/Subブローカーとしてバックエンドで広く利用される。' },
  { term: 'シャーディング', aliases: ['sharding', '水平分割'], description: 'データベースのデータを複数のノード（シャード）に水平分割して分散させるスケーリング手法。各シャードがデータの一部を担当することでI/Oを分散し、単一ノードに収まらない大規模データを扱える。' },
  { term: 'レプリケーション', aliases: ['replication', 'db replication'], description: 'データベースのデータを複数のノード間で同期コピーする仕組み。プライマリからレプリカへの変更伝播により読み取りスケールアウトと高可用性を実現する。同期レプリケーションは一貫性、非同期は可用性を優先する。' },
  { term: 'CI/CDパイプライン', aliases: ['ci/cdパイプライン', 'ci/cd pipeline'], description: 'コードのプッシュからビルド・テスト・デプロイまでを自動化したパイプライン。GitHub Actions、GitLab CI、CircleCIなどで構成し、品質ゲートをパスしたコードのみを自動的に本番環境へ届ける。' },
  { term: 'DDDアグリゲート', aliases: ['dddアグリゲート', 'ddd aggregate'], description: 'DDDにおいて一貫性の境界を形成するオブジェクトの集まり。アグリゲートルートを通じてのみ内部オブジェクトにアクセス・変更でき、アグリゲート全体の不変条件を保証する。' },
  { term: 'マイクロサービスアーキテクチャ', aliases: ['microservices architecture', 'msa'], description: 'アプリケーションを独立してデプロイ可能な小さなサービス群に分割するアーキテクチャスタイル。各サービスが単一の責務を持ち、APIを通じて協調する。独立したデプロイと技術選択の自由度が高い反面、分散システムの複雑さが増す。' },
  { term: 'REST成熟度モデル', aliases: ['rest成熟度モデル', 'richardson maturity model', 'rest maturity model'], description: 'RichardsonによるRESTful APIの成熟度を4段階（レベル0-3）で評価するモデル。レベル3はHATEOAS（Hypermedia as the Engine of Application State）を実装した最も成熟したREST。' },
  { term: 'Gitflow', aliases: ['gitflow', 'gitflow workflow'], description: 'main/develop/feature/release/hotfixブランチを使う体系的なGitブランチ戦略。リリース管理が明確な一方、ブランチが多く複雑になりやすい。小規模チームやCI/CD重視チームではトランクベース開発が代替として使われる。' },
  { term: 'サーバーサイドレンダリング', aliases: ['server-side rendering'], description: 'HTTPリクエストを受けるたびにサーバー側でHTMLを生成して返すレンダリング方式。SEOとFCPの改善に有効だが、サーバーの計算負荷が高い。Next.jsのgetServerSidePropsが代表的な実装方法。' },
  { term: 'データベースインデックス', aliases: ['database index', 'dbインデックス'], description: 'テーブルの特定カラムに作成されクエリ検索を高速化するデータ構造。B-Treeインデックスが最も一般的で、WHERE句やJOIN条件・ORDER BYに使われるカラムに付与する。過剰なインデックスは書き込みパフォーマンスを低下させる。' },
  { term: 'キャッシュ戦略', aliases: ['cache strategy', 'キャッシング戦略'], description: 'データのキャッシュ方針を定める設計。Cache-Aside（アプリが明示的に制御）、Read-Through（キャッシュが透過的にDBを参照）、Write-Through/Write-Behindなどのパターンがあり、一貫性とパフォーマンスのトレードオフを考慮して選択する。' },
  { term: 'GraphQLクエリ', aliases: ['graphqlクエリ', 'graphql query'], description: 'GraphQLでクライアントがサーバーから必要なデータを宣言的に取得するための操作。RESTと異なりフィールドを指定して過不足なくデータを取得でき、アンダーフェッチやオーバーフェッチを防ぐ。' },
  { term: 'GraphQLミューテーション', aliases: ['graphqlミューテーション', 'graphql mutation'], description: 'GraphQLでデータの作成・更新・削除などの副作用を伴う操作を行うための操作タイプ。クエリと区別することでAPIの意図を明確にし、クライアントが変更結果を受け取れる。' },
  { term: 'GraphQLサブスクリプション', aliases: ['graphqlサブスクリプション', 'graphql subscription'], description: 'GraphQLでリアルタイムデータ更新を実現する操作タイプ。WebSocketなどの持続的接続を使いサーバーからクライアントへイベント発生時にデータをプッシュする。' },
  { term: 'GraphQLフラグメント', aliases: ['graphqlフラグメント', 'graphql fragment'], description: 'GraphQLで再利用可能なフィールド選択セットを定義する仕組み。複数のクエリやミューテーションで共通のフィールド群を使い回し、コードの重複を排除して保守性を高める。' },
  { term: 'GraphQLディレクティブ', aliases: ['graphqlディレクティブ', 'graphql directive'], description: 'GraphQLのスキーマやクエリに付加情報や実行制御を加えるアノテーション機能。@include、@skipなどの組み込みディレクティブや、カスタムディレクティブを定義して認可や変換処理を実装できる。' },
  { term: 'DataLoader', aliases: ['dataloader', 'graphql dataloader'], description: 'GraphQLにおけるN+1問題を解決するバッチ処理ライブラリ。複数の個別リクエストをまとめて一括取得し、キャッシュと組み合わせてデータベースへのクエリ数を大幅に削減する。' },
  { term: 'Schema Stitching', aliases: ['schema stitching', 'graphql schema stitching'], description: '複数のGraphQLスキーマをプログラム的に結合して単一のAPIエンドポイントを提供する手法。Federationの前身として使われ、異なるGraphQLサービスを透過的に統合する。' },
  { term: 'Protocol Buffers', aliases: ['protocol buffers', 'protobuf', 'proto'], description: 'Googleが開発したバイナリシリアライゼーション形式とIDL。gRPCのデフォルトシリアライザとして使われ、.protoファイルにスキーマを定義すると複数言語のコードを自動生成できる。JSONより高速かつコンパクト。' },
  { term: 'unary RPC', aliases: ['unary rpc', '単項rpc'], description: 'gRPCの最も基本的な通信パターン。クライアントが単一のリクエストを送信し、サーバーが単一のレスポンスを返す従来のリクエスト/レスポンス型のRPC呼び出し形式。REST APIの1回の呼び出しに相当する。' },
  { term: 'サーバーストリーミングRPC', aliases: ['サーバーストリーミングrpc', 'server streaming rpc', 'grpc server streaming'], description: 'gRPCの通信パターンの一つ。クライアントが1件のリクエストを送信し、サーバーが複数のレスポンスをストリームで返す方式。大量データの逐次配信やリアルタイムイベント更新に適している。' },
  { term: 'gRPCインターセプター', aliases: ['grpcインターセプター', 'grpc interceptor'], description: 'gRPCのリクエスト/レスポンスパイプラインに挿入されるミドルウェア的な仕組み。認証トークン付与、ログ記録、メトリクス収集、リトライ処理などを横断的に実装するために使用する。' },
  { term: 'WebSocketハンドシェイク', aliases: ['websocketハンドシェイク', 'websocket handshake', 'websocket upgrade'], description: 'WebSocket接続を確立するためのHTTPアップグレード手続き。クライアントがUpgrade: websocketヘッダーを含むHTTPリクエストを送り、サーバーが101 Switching Protocolsで応答して持続的双方向接続を開始する。' },
  { term: 'WebSocketフレーム', aliases: ['websocketフレーム', 'websocket frame'], description: 'WebSocket通信における最小データ転送単位。テキスト、バイナリ、制御フレーム（ping/pong/close）などのタイプがあり、ヘッダーにオペコードとマスクフラグを含む軽量なプロトコル構造を持つ。' },
  { term: 'ping/pong', aliases: ['websocket ping/pong', 'heartbeat'], description: 'WebSocket接続の生存確認に使う制御フレーム。サーバーまたはクライアントがpingフレームを送り、相手がpongで応答することで接続が維持されていることを確認する。ハートビートとも呼ばれる。' },
  { term: 'WebSocket再接続', aliases: ['websocket再接続', 'websocket reconnection', 'reconnect logic'], description: 'WebSocket接続が切断された際に自動的に再接続を試みる実装パターン。指数バックオフを用いた再試行間隔の制御、接続状態管理、再接続時のメッセージ再送処理が必要となる。' },
  { term: 'HATEOAS', aliases: ['hateoas', 'hypermedia as the engine of application state'], description: 'RESTfulアーキテクチャの制約の一つ。APIレスポンスに次に実行可能な操作へのリンクを含め、クライアントがAPIドキュメントを事前に知らなくてもAPIを探索・利用できるようにする設計原則。' },
  { term: 'APIバージョニング戦略', aliases: ['apiバージョニング戦略', 'api versioning strategy', 'api version management'], description: 'APIの後方互換性を維持しながら変更を管理するための手法。URLパス（/v1/）、クエリパラメータ（?version=1）、カスタムヘッダー、Content-Typeなど複数のアプローチがある。' },
  { term: 'APIキー管理', aliases: ['apiキー管理', 'api key management', 'api key rotation'], description: 'APIキーのライフサイクルを安全に管理する一連の実践。発行、スコープ制限、ローテーション、失効処理を含み、キーの漏洩リスクを最小化する。シークレットマネージャーでの安全な保管が推奨される。' },
  { term: 'Authorization Code Flow', aliases: ['authorization code flow', '認可コードフロー', 'oauth authorization code'], description: 'OAuth 2.0の認可フローの一つ。ブラウザベースのアプリで利用され、認可サーバーから認可コードを受け取りサーバーサイドでアクセストークンと交換する。コードの傍受を防ぐためPKCEと組み合わせて使う。' },
  { term: 'PKCE', aliases: ['pkce', 'proof key for code exchange', 'コード検証鍵'], description: 'OAuth 2.0の認可コードフローを強化する拡張機能。クライアントシークレットを安全に保持できないSPA・モバイルアプリのために認可コード横取り攻撃を防ぐ。code_verifierとcode_challengeのペアを使う。' },
  { term: 'Client Credentials Flow', aliases: ['client credentials flow', 'client credentials', 'クライアント認証フロー'], description: 'OAuth 2.0のフローの一つ。ユーザーが介在しないサービス間通信（M2M）で使用する。クライアントID・シークレットを認可サーバーに送り、直接アクセストークンを取得する最もシンプルなフロー。' },
  { term: 'OAuthスコープ', aliases: ['oauthスコープ', 'oauth scope', 'scope'], description: 'OAuth 2.0でアクセストークンが持つ権限の範囲を定義するパラメータ。read、write、admin などのスコープをスペース区切りで指定し、最小権限の原則に基づいてトークンのアクセス範囲を制限する。' },
  { term: 'Bearer Token', aliases: ['bearer token', 'ベアラートークン', 'bearer認証'], description: 'HTTPの認証スキームの一つ。AuthorizationヘッダーにBearer プレフィックスとトークンを含めて送信する方式。OAuth 2.0やJWTと組み合わせて使われ、トークン所持者に対してアクセスを許可する。' },
  { term: 'JWTクレーム', aliases: ['jwtクレーム', 'jwt claims', 'jwtペイロード'], description: 'JSON Web Tokenのペイロードに含まれるキーバリューペア。sub（主体）、exp（有効期限）、iss（発行者）などの標準クレームと、アプリケーション固有のカスタムクレームでユーザー情報や権限を表現する。' },
  { term: 'JWKS', aliases: ['jwks', 'json web key set', 'jwkエンドポイント'], description: 'JWTの署名検証に使う公開鍵の集合をJSON形式で公開するエンドポイントの仕様。認証プロバイダが/.well-known/jwks.jsonで公開し、リソースサーバーが動的に公開鍵を取得してトークンを検証する。' },
  { term: 'オフセットページネーション', aliases: ['offset pagination', 'offset-based pagination'], description: 'APIページネーションの手法の一つ。skip/limit またはpage/per_pageパラメータで取得位置を指定する。実装が簡単だがデータ変更時に重複や欠損が発生しやすく、大量データでは性能が低下する。' },
  { term: 'APIフィルタリング', aliases: ['apiフィルタリング', 'api filtering', 'query filtering'], description: 'APIで返すリソースの絞り込み条件をクライアントから指定できる機能。クエリパラメータ（?status=active）やフィルタ専用パラメータ構文（?filter[status]=active）で実装し、不要なデータ転送を削減する。' },
  { term: 'APIソート', aliases: ['apiソート', 'api sorting', 'sort parameter'], description: 'REST APIで返すリソースの並び順をクライアントから指定できる機能。?sort=created_at&order=descのようなクエリパラメータや?sort=-created_atの短縮記法で昇順・降順を指定する。' },
  { term: 'Sparse Fieldsets', aliases: ['sparse fieldsets', 'スパースフィールドセット', '部分レスポンス'], description: 'REST APIでクライアントが必要なフィールドのみ選択して取得できる機能。JSON:APIなどで?fields[article]=title,bodyのように指定する。不要フィールドの転送を省きパフォーマンスを向上させる。' },
  { term: 'Acceptヘッダー', aliases: ['acceptヘッダー', 'accept header', 'httpアクセプト'], description: 'HTTPリクエストでクライアントが受け入れ可能なメディアタイプを指定するヘッダー。Accept: application/json, text/htmlのように複数指定でき、q値で優先度を示す。コンテントネゴシエーションの基盤となる。' },
  { term: 'ポーリング', aliases: ['polling', 'short polling'], description: 'クライアントが一定間隔でAPIにリクエストを繰り返し送ってリソースの変化を確認する方式。実装が簡単だがリアルタイム性が低く不要なリクエストが発生する。Long PollingやWebSocketで改善できる。' },
  { term: 'Request ID', aliases: ['request id', 'リクエストid', 'x-request-id'], description: '個々のHTTPリクエストを一意に識別するためにヘッダーに付与するID。X-Request-IDヘッダーで送受信され、ログの照合やデバッグ、サポート問い合わせ時の問題追跡に活用される。' },
  { term: 'APIドキュメント', aliases: ['apiドキュメント', 'api documentation', 'apiリファレンス'], description: 'APIの利用方法をエンドポイント、パラメータ、レスポンス形式、認証方法などとともに記述した文書。OpenAPI仕様から自動生成したり、インタラクティブなサンドボックスを提供することで開発者体験を向上させる。' },
  { term: 'SDK自動生成', aliases: ['sdk自動生成', 'sdk generation', 'code generation', 'openapi generator'], description: 'OpenAPI仕様などのAPIスキーマ定義から複数プログラミング言語のクライアントSDKを自動的に生成する手法。手動実装の手間を省き、型安全なAPIクライアントを一貫して提供できる。' },
  { term: 'APIゲートウェイパターン', aliases: ['apiゲートウェイパターン', 'api gateway pattern'], description: 'クライアントとバックエンドマイクロサービスの間に単一のエントリポイントを置くアーキテクチャパターン。認証、レート制限、ルーティング、プロトコル変換、レスポンス集約を一元管理する。' },
  { term: 'GraphQLN+1問題', aliases: ['graphqln+1問題', 'graphql n+1', 'n+1クエリ問題'], description: 'GraphQLリゾルバが親リソース1件につき子リソース取得のクエリをN回発行してしまう性能問題。DataLoaderによるバッチ処理とキャッシュを使ってN+1をN回のクエリを1回にまとめることで解決する。' },
  { term: 'gRPCサービス定義', aliases: ['grpcサービス定義', 'grpc service definition', 'proto service'], description: 'Protocol Buffersの.protoファイルにgRPCのサービスとRPCメソッドを定義する仕組み。serviceブロックにrpc宣言を記述し、protoc ツールでサーバー・クライアントのスタブコードを生成する。' },
  { term: 'クライアントストリーミングRPC', aliases: ['クライアントストリーミングrpc', 'client streaming rpc', 'grpc client streaming'], description: 'gRPCの通信パターンの一つ。クライアントが複数のリクエストをストリームで送信し、サーバーが全て受信後に1つのレスポンスを返す。ファイルアップロードや大量データの一括送信に適する。' },
  { term: 'GraphQLスキーマ設計', aliases: ['graphqlスキーマ設計', 'graphql schema design', 'sdl', 'schema definition language'], description: 'GraphQL APIの型システムとデータ構造をSDL（Schema Definition Language）で定義する設計作業。type、query、mutation、subscriptionを定義しAPIの契約をコードとして表現する。' },
  { term: 'APIコントラクトファースト', aliases: ['apiコントラクトファースト', 'contract-first api', 'api-first design', 'design first'], description: '実装前にAPIの仕様（OpenAPIなど）を先に定義するアプローチ。チームがAPIを合意してから実装を開始するため、フロントエンドとバックエンドの並行開発が可能になり齟齬を防げる。' },
  { term: 'GraphQL変数', aliases: ['graphql変数', 'graphql variables', 'クエリ変数'], description: 'GraphQLクエリにおいて動的な値をハードコードせず外部から注入する仕組み。クエリ文字列内で$variableName: Typeと宣言し、リクエスト時にJSONで値を渡す。SQLインジェクション防止にも有効。' },
  { term: 'APIセキュリティテスト', aliases: ['apiセキュリティテスト', 'api security testing', 'owasp api security'], description: 'APIの脆弱性を検出するためのテスト活動。OWASP API Security Top 10に基づき、認可バイパス、過剰データ露出、レート制限欠如、インジェクションなどの問題を体系的に確認する。' },
  { term: 'HTTPステータスコード設計', aliases: ['httpステータスコード設計', 'http status code', 'httpレスポンスコード'], description: 'REST APIで操作結果を伝えるためのHTTPステータスコードの適切な使用。200 OK、201 Created、204 No Content、400 Bad Request、401、403、404、409 Conflict、422、429、500などの意味を正確に使い分ける。' },
  { term: 'APIエラーレスポンス', aliases: ['apiエラーレスポンス', 'api error response', 'problem details', 'rfc 7807'], description: 'APIがエラーを返す際のレスポンス形式の標準化。RFC 7807（Problem Details for HTTP APIs）ではtype、title、status、detail、instanceフィールドを持つJSON形式でエラー情報を一貫して表現する。' },
  { term: 'WebhookシグネチャVerification', aliases: ['webhookシグネチャverification', 'webhook signature verification', 'webhook secret'], description: 'WebhookのペイロードにHMAC署名を付与し受信側で検証することで正規の送信者からのリクエストかを確認するセキュリティ手法。X-Hub-Signatureヘッダーなどで署名を渡し、シークレットキーで検証する。' },
  { term: 'APIレートリミットヘッダー', aliases: ['apiレートリミットヘッダー', 'rate limit headers', 'x-ratelimit'], description: 'APIのレート制限状態をクライアントに通知するHTTPレスポンスヘッダー群。X-RateLimit-Limit（上限）、X-RateLimit-Remaining（残数）、X-RateLimit-Reset（リセット時刻）でクライアントが制限状況を把握できる。' },
  { term: 'GraphQLイントロスペクション', aliases: ['graphqlイントロスペクション', 'graphql introspection'], description: 'GraphQL APIがスキーマ情報自身をクエリで提供する機能。__schemaや__typeフィールドでスキーマの全型・フィールドを動的に取得でき、GraphiQLなどのツールがAPIを自動探索するために利用する。' },
  { term: 'GraphQLパーシスティッドクエリ', aliases: ['graphqlパーシスティッドクエリ', 'graphql persisted queries', 'automatic persisted queries', 'apq'], description: 'GraphQLクエリをサーバー側に事前登録し、リクエスト時にクエリ全文の代わりにハッシュIDを送る最適化手法。ペイロードサイズを削減しCDNキャッシュを可能にする。Apolloのは自動化されAPQと呼ばれる。' },
  { term: 'APIゲートウェイ認証', aliases: ['apiゲートウェイ認証', 'api gateway auth', 'gateway authentication'], description: 'API GatewayでJWT検証やAPIキー確認などの認証処理を一元的に行いバックエンドサービスの負担を軽減するパターン。各マイクロサービスが個別に認証を実装せず済み、セキュリティポリシーを集約管理できる。' },
];
