// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: git (2/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_002: ReadonlyArray<GlossaryEntry> = [
  { term: 'Codespaces Prebuilds', aliases: ['codespaces prebuilds', 'コードスペースプレビルド'], description: 'GitHub Codespaceの起動を高速化するため、リポジトリのDevContainerイメージを事前にビルドしてキャッシュする機能。ブランチやリージョンごとに設定でき、初回起動時間を大幅に短縮する。' },
  { term: 'Codespaces Dev Container', aliases: ['codespaces dev container', '開発コンテナ'], description: 'GitHub Codespacesが使用する開発環境の定義コンテナ。`devcontainer.json`でOSイメージ・拡張機能・ポートフォワード・初期化スクリプトを宣言的に設定し、チーム全員が同一環境を使用できる。' },
  { term: 'GitHub Webhooks', aliases: ['github webhooks'], description: 'GitHubのイベント（push・PR・Issue等）発生時に指定URLへHTTP POSTリクエストを送信する仕組み。外部サービスとのリアルタイム連携・自動化ワークフローのトリガーに利用される。' },
  { term: 'GitHub OAuth Apps', aliases: ['github oauth apps'], description: 'GitHubユーザーに代わってAPIアクセスを行うOAuth 2.0ベースのアプリ。ユーザーが認可したスコープで動作し、アクセストークンを発行してGitHub APIを呼び出す。GitHub Appsに比べ権限が粗い。' },
  { term: 'GitHub Personal Access Token', aliases: ['github personal access token'], description: 'GitHubユーザーがAPIやGit操作に使用する認証トークン。クラシック版とFine-grained版があり、スコープ（権限）を設定して発行する。パスワードの代替として使用され、有効期限の設定を推奨。' },
  { term: 'GitHub Fine-grained PAT', aliases: ['github fine-grained pat', 'きめ細かいpat'], description: '特定のリポジトリ・特定の権限に限定できる次世代のPersonal Access Token。従来のクラシックPATより最小権限の原則を適用でき、有効期限・対象リポジトリ・細粒度の権限設定が可能。' },
  { term: 'GitHub SSH Keys', aliases: ['github ssh keys', 'ssh key'], description: 'GitHubへのGit操作をパスワードなしで行うためのSSH公開鍵。アカウント設定に登録した公開鍵と対応する秘密鍵で認証し、`git@github.com`形式のURLでリポジトリを操作する。' },
  { term: 'GitHub GPG Keys', aliases: ['github gpg keys', 'コミット署名'], description: 'GitHubアカウントに登録するGPG公開鍵。コミットやタグにGPG署名を付与し、GitHub.com上で「Verified」バッジを表示させるために使用する。なりすまし防止とコード改ざん検知に有効。' },
  { term: 'GitHub Deploy Keys', aliases: ['github deploy keys'], description: '特定のリポジトリへのアクセスに限定したSSH鍵。CI/CDサーバーやデプロイスクリプトからリポジトリをクローン・プッシュするために使用し、個人アカウントのSSH鍵とは独立して管理できる。' },
  { term: 'GitHub Advanced Security', aliases: ['github advanced security', 'ghas'], description: 'コードスキャン・シークレットスキャン・依存関係レビューを含むGitHubのセキュリティ機能セット。GitHub Enterprise Cloud/Server向けのアドオンライセンスで提供され、開発プロセスにセキュリティを組み込む。' },
  { term: 'CodeQL', aliases: ['codeql'], description: 'GitHubが開発したコード解析エンジン・クエリ言語。コードをデータベースとして扱いSQLライクなクエリで脆弱性パターンを検索できる。GitHub Code ScanningのデフォルトSASTエンジンとして使用される。' },
  { term: 'GitHub Secret Scanning', aliases: ['github secret scanning'], description: 'リポジトリのコミット・Issue・PRからAPIキーやパスワード等の機密情報を自動検出するGitHub機能。検出時はアラートを発行し、一部のパートナーサービスと連携してトークンを即座に無効化する。' },
  { term: 'Dependabot Security Updates', aliases: ['dependabot security updates', 'dependabotセキュリティアップデート'], description: 'Dependabot Alertsが検出した脆弱性を修正するため、影響ライブラリを安全なバージョンへ更新するPRをDependabotが自動作成する機能。脆弱性の修正を迅速に適用するための自動化手段。' },
  { term: 'Dependabot Version Updates', aliases: ['dependabot version updates', 'dependabotバージョンアップデート'], description: 'セキュリティに関係なく定期的に依存ライブラリの最新バージョンへの更新PRをDependabotが作成する機能。`dependabot.yml`でスケジュール・対象エコシステム・無視ルールを設定できる。' },
  { term: 'GitHub Dependency Graph', aliases: ['github dependency graph', '依存関係グラフ'], description: 'リポジトリの依存ライブラリとその依存ライブラリを可視化するGitHub機能。package.json・Gemfile・requirements.txt等のマニフェストを解析し、Dependabot AlertsやSBOM生成の基盤となる。' },
  { term: 'GitHub Advisory Database', aliases: ['github advisory database', 'advisory database', 'セキュリティアドバイザリdb'], description: 'GitHubが管理するオープンソースソフトウェアのセキュリティ脆弱性データベース。CVEと独自のGHSA識別子でエントリを管理し、Dependabot AlertsやCode Scanningの脆弱性情報源として使用される。' },
  { term: 'GitHub SBOM', aliases: ['github sbom', 'software bill of materials'], description: 'GitHubのDependency GraphからSPDX形式のSBOM（ソフトウェア部品表）を生成・エクスポートできる機能。コンプライアンス・ライセンス管理・サプライチェーンセキュリティの証跡として使用する。' },
  { term: 'GitHub Attestations', aliases: ['github attestations', 'build provenance', 'ビルドプロバナンス'], description: 'GitHub Actionsでビルドされたアーティファクトのビルドプロセスを暗号署名付きで記録するサプライチェーンセキュリティ機能。SigstoreとOIDCを利用し、成果物の出所と改ざん有無を検証可能にする。' },
  { term: 'GitHub Actions OIDC', aliases: ['github actions oidc', 'oidc', 'workload identity'], description: 'GitHub ActionsワークフローがOIDCトークンを用いてAWS・Azure・GCP等のクラウドに長期シークレットなしで認証できる仕組み。Workload Identity Federationと組み合わせて一時的な認証情報を取得する。' },
  { term: 'GitHub Audit Log', aliases: ['github audit log'], description: 'GitHubのOrganizationやEnterpriseで発生した操作（設定変更・メンバー変更・リポジトリ操作等）を記録するログ機能。コンプライアンス監査・インシデント調査・不正アクセス検知に使用する。' },
  { term: 'GitHub Enterprise Managed Users', aliases: ['github enterprise managed users', 'emu', 'enterprise managed users'], description: '企業のIdP（AzureAD・Okta等）でGitHubユーザーアカウントを完全管理するGitHub Enterpriseの機能。SCIM/SAMLで自動プロビジョニングし、個人の既存GitHubアカウントと分離された管理アカウントを使用する。' },
  { term: 'GitHub SCIM', aliases: ['github scim', 'scim', 'scimプロビジョニング'], description: 'GitHubのOrganizationやEnterpriseにおいてIdP（AzureAD・Okta等）からSCIM 2.0プロトコルでユーザーのプロビジョニング・デプロビジョニングを自動化する機能。SAML SSOと組み合わせて使用される。' },
  { term: 'GitHub SAML SSO', aliases: ['github saml sso', 'saml sso'], description: 'GitHubのOrganizationやEnterpriseでSAML 2.0を用いてIdPによるシングルサインオン認証を強制する機能。メンバーはIdPのアカウントでGitHubにアクセスし、組織の認証ポリシーに従った管理が可能。' },
  { term: 'GitHub IP Allow List', aliases: ['github ip allow list', 'ipアローリスト', 'ip許可リスト'], description: 'GitHubのOrganizationやEnterpriseへのアクセスを特定のIPアドレス・CIDRブロックに制限するセキュリティ機能。社内ネットワークやVPNからのみアクセスを許可するゼロトラスト施策として利用される。' },
  { term: 'GitHub Repository Rules', aliases: ['github repository rules', 'rulesets', 'リポジトリルールセット'], description: 'ブランチやタグへの操作を制御するルールを柔軟に定義できるGitHub機能。プッシュ制限・PRレビュー必須・ステータスチェック・署名必須等をOrganization/リポジトリレベルで階層管理できる。' },
  { term: 'GitHub Forks', aliases: ['github forks'], description: '他人のGitHubリポジトリを自分のアカウントにコピーを作成する操作。OSS貢献のワークフローで使用し、フォーク先でブランチを作りPull Requestで元リポジトリへ変更を提案する。' },
  { term: 'GitHub Stars', aliases: ['github stars', 'スター', 'star'], description: 'GitHubリポジトリに「お気に入り」や「いいね」として付けられる評価機能。スター数はリポジトリの人気や信頼度の指標として使われ、後で参照したいリポジトリをブックマークする用途にも利用する。' },
  { term: 'GitHub Watch', aliases: ['github watch', 'ウォッチ', 'リポジトリ購読'], description: 'GitHubリポジトリの活動（Issue・PR・リリース等）を購読してNotificationsで受け取る設定。Watching（全通知）・Releases only・Ignoring・Participating only の4段階で通知量を調整できる。' },
  { term: 'GitHub Notifications', aliases: ['github notifications', '通知'], description: 'GitHubがIssue・PR・コメント・@メンション・セキュリティアラート等のイベントをユーザーに届ける通知機能。Webインボックス・メール・モバイルアプリで受け取れ、Watchや参加状況でフィルタリングできる。' },
  { term: 'GitHub Education', aliases: ['github education'], description: '教育機関の学生・教員・学校に対してGitHubの有料機能を無償または割引で提供するプログラム。Student Developer Pack・GitHub Classroom・Campus Expertプログラム等を含む教育支援の総称。' },
  { term: 'GitHub Student Developer Pack', aliases: ['github student developer pack', 'student developer pack', '学生開発者パック'], description: '在学中の学生に対してGitHub ProやJetBrains・Namecheap・DigitalOcean等100以上のサービスを無償提供するGitHub Educationの特典パック。学籍メールや学生証で資格を確認して申請する。' },
  { term: 'GitHub Classroom', aliases: ['github classroom', 'クラスルーム'], description: '教師がGitHubを使ったプログラミング課題の配布・収集・自動採点を管理できる教育向けツール。課題をテンプレートリポジトリから学生ごとに自動生成し、GitHub Actionsで自動採点を実行できる。' },
  { term: 'GitHub Community', aliases: ['github community', 'コミュニティフォーラム'], description: 'GitHub公式の質問・情報共有フォーラム。GitHub製品への質問・フィードバック・活用事例の共有が行われるオンラインコミュニティで、GitHub Discussions機能を使って運営されている。' },
  { term: 'GitHub README', aliases: ['github readme', 'readme.md'], description: 'GitHubリポジトリのルートに置くと自動表示されるMarkdownファイル。プロジェクトの概要・インストール手順・使い方・コントリビューション方法を記載し、リポジトリの「玄関」として機能する。' },
  { term: 'GitHub Profile README', aliases: ['github profile readme', 'profile readme', 'プロフィールreadme'], description: 'GitHubユーザー名と同名のリポジトリに作成したREADMEがプロフィールページに表示される機能。Markdownやバッジ・統計ウィジェットを使って自己紹介・スキル・活動をビジュアルに表現できる。' },
  { term: 'GitHub Social Preview', aliases: ['github social preview', 'social preview', 'ogp画像'], description: 'SNSやチャットでGitHubリポジトリのURLを共有した際にリンクカードとして表示されるプレビュー画像。リポジトリのSettings > Social previewからカスタム画像をアップロードして設定する。' },
  { term: 'GitHub Topics', aliases: ['github topics', 'topics', 'リポジトリトピック'], description: 'GitHubリポジトリに付与するタグ・カテゴリラベル。`react`・`machine-learning`等のトピックを設定するとExplore検索でリポジトリが発見されやすくなり、類似リポジトリとの関連付けに使われる。' },
  { term: 'GitHub Explore', aliases: ['github explore', 'explore', 'githubエクスプロア'], description: 'GitHubがユーザーの興味・アクティビティに基づいてリポジトリ・トピック・コレクション・トレンドを推薦するディスカバリーページ。新しいOSSプロジェクトや開発トレンドを発見するポータル。' },
  { term: 'GitHub Trending', aliases: ['github trending', 'trending', 'トレンド'], description: '日・週・月単位でスター獲得数が多いリポジトリや開発者をランキング表示するGitHubページ。プログラミング言語でフィルタリングでき、注目されているOSSプロジェクトや技術トレンドの把握に使われる。' },
  { term: 'GitHub Archive Program', aliases: ['github archive program', 'arctic code vault', 'アークティックコードボルト'], description: '重要なOSSコードを長期保存するGitHubの取り組み。北極圏の廃炭鉱に21mm厚のフィルムとしてコードを保存するArctic Code Vault（1000年保存）や複数データセンターへのバックアップを含む。' },
  { term: 'GitHub Status', aliases: ['github status', 'githubステータスページ', 'githubstatus.com'], description: 'GitHubのサービス稼働状況をリアルタイムで確認できる公式ステータスページ（githubstatus.com）。各コンポーネント（Git操作・API・Actions・Pages等）の状態と過去のインシデント履歴を公開している。' },
  { term: 'GitHub Changelog', aliases: ['github changelog', 'changelog', 'changelog.github.blog'], description: 'GitHubが新機能・改善・廃止機能を公式発表するブログ（changelog.github.blog）。日々のリリースノートが掲載され、GitHub Actionsの新機能やAPI変更、UIのアップデートを追うために利用される。' },
  { term: 'GitHub Feature Flags', aliases: ['github feature flags', 'feature flags', '機能フラグ', 'github feature preview'], description: 'GitHubが段階的に新機能をユーザーへロールアウトするための仕組み。アカウント設定のFeature Previewから実験的機能を有効化できる一般ユーザー向け機能プレビューとしても知られている。' },
  { term: 'GitHub Mobile', aliases: ['github mobile', 'githubモバイルアプリ'], description: 'iOS・Android向けのGitHub公式モバイルアプリ。通知管理・Issue/PRのレビューとコメント・コード閲覧・マージ操作・GitHub Copilot Chatへのアクセスをスマートフォンやタブレットからできるようにするアプリ。' },
  { term: 'GitHub Desktop', aliases: ['github desktop', 'githubデスクトップ'], description: 'Windows・macOS向けのGitHub公式GUIクライアント。コマンドラインなしにリポジトリのクローン・コミット・ブランチ管理・PRの作成・差分確認ができ、Git初学者やGUIを好む開発者向けツール。' },
  { term: 'GitHub Models', aliases: ['github models', 'モデルプレイグラウンド'], description: 'GitHub Marketplaceに統合されたAIモデルのプレイグラウンドとAPIアクセスサービス。GPT-4o・Llama・Mistral・Phi等のモデルをブラウザ上でテストしたりGitHub Personal Access Tokenで呼び出したりできる。' },
  { term: 'GitHub Spark', aliases: ['github spark'], description: '自然言語でマイクロアプリ（Spark）を作成・共有・実行できるGitHubのAIネイティブ開発ツール（プレビュー）。コーディング不要でWebアプリを生成し、GitHub Modelsのバックエンドで動作するノーコード/ローコード環境。' },
  { term: 'GitHub Wiki', aliases: ['github wiki', 'リポジトリwiki'], description: 'GitHubリポジトリに付属するMarkdown形式のドキュメントサイト機能。サイドバーでページを階層整理でき、Gitリポジトリとして管理されるためバージョン管理可能。READMEより詳細なドキュメントの置き場として使う。' },
  { term: 'GitHub CODEOWNERS', aliases: ['github codeowners'], description: 'リポジトリ内のファイル・ディレクトリごとに責任者（オーナー）を宣言するファイル（`CODEOWNERS`）。PR作成時にオーナーが自動でレビュアーに追加され、ブランチ保護ルールと組み合わせてオーナーのレビューを必須化できる。' },
  { term: 'GitHub Actions Reusable Workflows', aliases: ['github actions reusable workflows'], description: 'GitHub ActionsのWorkflowを`workflow_call`イベントで他のWorkflowから呼び出せる再利用機能。CI/CDの共通ロジックをDRY化し、Organizationリポジトリ間で標準化されたパイプラインを共有できる。' },
  { term: 'GitHub Actions Composite Actions', aliases: ['github actions composite actions'], description: '複数のステップをひとつのアクションとして再利用可能にするGitHub Actionsの機能。シェルスクリプトや他のアクション呼び出しをまとめてActionとしてパッケージ化し、ワークフローをシンプルに保てる。' },
  { term: 'GitHub Dependency Review', aliases: ['github dependency review', 'dependency review', '依存関係レビュー'], description: 'PRで追加・変更される依存パッケージにCVEが含まれていないかをレビュー画面でインライン表示するGitHub機能。`dependency-review-action`を使いCI上で脆弱な依存追加をブロックできる。' },
  { term: 'GitHub Branch Protection', aliases: ['github branch protection'], description: '特定のブランチへの直接プッシュ・強制プッシュ・削除を制限し、PRレビュー・ステータスチェック合格・署名付きコミットを必須化できるGitHub機能。mainブランチを保護するための重要な設定。' },
  { term: 'GitHub Repository Insights', aliases: ['github repository insights', 'insights', 'リポジトリ統計'], description: 'GitHubリポジトリの活動統計を表示するページ。コントリビューター数・コミット頻度・コードの増減・フォーク数・依存関係ネットワーク・IssueとPRのフローなどをグラフで可視化する。' },
  { term: 'GitHub Traffic Analytics', aliases: ['github traffic analytics', 'traffic', 'トラフィック分析'], description: 'GitHubリポジトリへのアクセス数（ビュー・ユニーク訪問者）・クローン数・参照元を14日間分表示するInsightsの一機能。リポジトリがどこから発見されているか・どの程度利用されているかを把握できる。' },
  { term: 'GitHub Actions Job', aliases: ['github actions job', 'ワークフロージョブ'], description: 'GitHub Actionsワークフロー内の実行単位。各ジョブは独立したランナー上で実行されデフォルトで並列に動作する。`needs`キーワードで依存関係を定義し順次実行や成果物の受け渡しができる。' },
  { term: 'GitHub Actions Step', aliases: ['github actions step', 'ワークフローステップ'], description: 'GitHub ActionsのJob内の最小実行単位。シェルコマンド（`run`）またはアクション（`uses`）のいずれかで定義し、同一ランナー上で順次実行される。前のステップの成果物や環境変数を引き継げる。' },
  { term: 'GitHub Packages Registry', aliases: ['github packages registry', 'パッケージレジストリ'], description: 'npm・Maven・NuGet・PyPI・RubyGems・Docker等のパッケージをGitHubリポジトリに紐付けてホストできるパッケージ管理サービス。GitHub Actionsと統合してCI/CDからの自動パブリッシュが容易。' },
  { term: 'GitHub Deployment Protection Rules', aliases: ['github deployment protection rules'], description: 'GitHub EnvironmentsにおいてGitHub Appsによるカスタム承認ロジックをデプロイゲートとして挿入できる機能。外部のITSMシステムや変更管理ツールとデプロイ承認フローを統合する際に使用する。' },
  { term: 'GitHub Release Notes', aliases: ['github release notes', '自動リリースノート', 'release notes'], description: 'GitHubのリリース機能でPRのタイトルやラベルを元にリリースノートを自動生成する機能。`.github/release.yml`でカテゴリ・除外ラベルを設定し、CHANGELOG的な文書を自動作成できる。' },
  { term: 'GitHub Pull Request Review', aliases: ['github pull request review', 'prレビュー'], description: 'GitHubのPull RequestでコードをレビューしてApprove・Request Changes・Commentを行う機能。行レベルのコメント・サジェスチョン（提案編集）・レビューグループによる承認ルールを組み合わせてコードレビューを体系化できる。' },
  { term: 'GitHub Copilot Instructions', aliases: ['github copilot instructions', 'copilot-instructions.md', 'カスタム指示'], description: 'リポジトリの`.github/copilot-instructions.md`に記述するGitHub Copilot向けカスタム指示ファイル。コーディング規約・技術スタック・禁止パターン等を自然言語で定義し、Copilotの補完やChatの回答を組織のガイドラインに合わせる。' },
  { term: 'GitHub Actions Self-hosted Runner', aliases: ['github actions self-hosted runner'], description: 'GitHub Actionsのジョブを自社管理のサーバー・VM・コンテナで実行するランナー。特定ハードウェア・ネットワーク要件やGitHub-hosted Runnerにない環境（GPUやオンプレDB接続等）が必要な場合に使用する。' },
  { term: 'repository', aliases: ['リポ', 'repo'], description: 'ソースコードとその変更履歴を保存・管理する場所です。GitHubやGitLabでホスティングされることが多いです。' },
  { term: 'merge', description: '別々のブランチで行われた変更を1つに統合する操作です。コンフリクトが発生する場合があります。' },
  { term: 'conflict', description: '同じファイルの同じ箇所を異なるブランチで別々に変更したとき、マージ時に発生する衝突です。手動で解決する必要があります。' },
];
