// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: git (1/2)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // github (219), github-actions (36), github-codespaces (28), git (19), github-projects (13), svn (1)
  { term: 'GitHub Issue', aliases: ['github issue'], description: 'GitHub上でタスク、バグ、アイデア、フィードバックを追跡するための基本単位。' },
  { term: 'Assignee', aliases: ['assignee'], description: 'IssueやPull Requestの担当者として割り当てられる人。' },
  { term: 'Label', aliases: ['label'], description: 'IssueやPull Requestを分類するためのタグ。' },
  { term: 'Milestone', aliases: ['milestone'], description: '関連するIssueやPull Requestを特定の期限や目標へまとめる単位。' },
  { term: 'Issue type', aliases: ['issue type'], description: 'Issueを種類ごとに整理するためのメタデータ。' },
  { term: 'Issue template', aliases: ['issue template'], description: 'Issue作成時の定型入力を提供するテンプレート。' },
  { term: 'Issue form', aliases: ['issue form'], description: 'フォーム形式で入力させるIssueテンプレート。' },
  { term: 'Sub-issue', aliases: ['sub-issue'], description: '親Issueにぶら下がる下位のIssue。作業分解に使う。' },
  { term: 'Parent issue', aliases: ['parent issue'], description: 'Sub-issueを束ねる親となるIssue。' },
  { term: 'Sub-issue progress', aliases: ['sub-issue progress'], description: '親Issueに対して、Sub-issueがどの程度完了しているかを示す進捗項目。' },
  { term: 'Issue dependency', aliases: ['issue dependency'], description: 'Issue同士の依存関係。どれが他の作業にブロックされているかを示せる。' },
  { term: 'Blocking issue', aliases: ['blocking issue'], description: '他のIssueを先に進められなくしている側のIssue。' },
  { term: 'Blocked issue', aliases: ['blocked issue'], description: '他のIssueが終わるまで進められない側のIssue。' },
  { term: 'Project view', aliases: ['project view'], description: 'Project内での見え方を切り替える表示単位。' },
  { term: 'Table layout', aliases: ['table layout'], description: 'Projectを表形式で見るレイアウト。' },
  { term: 'Board layout', aliases: ['board layout'], description: 'Projectをカンバン形式で見るレイアウト。' },
  { term: 'Roadmap layout', aliases: ['roadmap layout'], description: 'Projectをタイムライン形式で見るレイアウト。' },
  { term: 'Custom field', aliases: ['custom field'], description: 'Projectに独自の属性列を追加するための項目。' },
  { term: 'Iteration field', aliases: ['iteration field'], description: '繰り返し期間を表すProjectのフィールド。ロードマップ配置にも使える。' },
  { term: 'Date field', aliases: ['date field'], description: '開始日や目標日などを持つProjectフィールド。' },
  { term: 'Grouping', aliases: ['grouping'], description: 'Projectの項目を特定フィールド値でまとめて表示する機能。' },
  { term: 'Sorting', aliases: ['sorting'], description: 'Projectの項目順を特定フィールドで並べ替える機能。' },
  { term: 'Filtering', aliases: ['filtering'], description: '条件に合う項目だけをProject上へ表示する機能。' },
  { term: 'Slicing', aliases: ['slicing'], description: 'Projectのロードマップなどでフィールド値ごとに分けて見る操作。' },
  { term: 'Saved view', aliases: ['saved view'], description: 'フィルターや表示設定を保存したProjectビュー。' },
  { term: 'Draft issue', aliases: ['draft issue'], description: 'まだ正式なIssueにしていないProject内の下書き項目。' },
  { term: 'Pull request', aliases: ['pull request'], description: '変更を取り込んでもらうための提案単位。レビューとマージの中心になる。' },
  { term: 'Draft pull request', aliases: ['draft pull request'], description: 'まだレビュー準備が整っていないPull Request。' },
  { term: 'Review request', aliases: ['review request'], description: '特定の人やteamにレビューを依頼すること。' },
  { term: 'Review comment', aliases: ['review comment'], description: 'Pull Request上のコードや差分に対して付けるコメント。' },
  { term: 'Approving review', aliases: ['approving review'], description: 'マージ可能と判断したレビュー。保護ルールで必須にできる。' },
  { term: 'CODEOWNERS', aliases: ['codeowners'], description: 'パスごとに責任者やレビュー担当を定義するためのファイル。' },
  { term: 'Code owner', aliases: ['code owner'], description: '特定ファイルやディレクトリのレビュー責任を持つ人やteam。' },
  { term: 'Protected branch', aliases: ['protected branch'], description: '直接pushや自由なmergeを制限する保護付きブランチ。' },
  { term: 'Branch protection rule', aliases: ['branch protection rule'], description: 'どのブランチにどんな制約をかけるか定義するルール。' },
  { term: 'Required status checks', aliases: ['required status checks'], description: 'Merge前に必ず成功していなければならないCIなどのチェック。' },
  { term: 'Strict status checks', aliases: ['strict status checks'], description: 'ベースブランチへ最新状態で追従していることまで要求するrequired status check。' },
  { term: 'Loose status checks', aliases: ['loose status checks'], description: 'ベースブランチへの最新追従までは要求しないrequired status check。' },
  { term: 'Ruleset', aliases: ['ruleset'], description: 'ブランチやタグへ適用する統制ルール集合。ブランチ保護より柔軟に扱える。' },
  { term: 'Merge queue', aliases: ['merge queue'], description: '複数Pull Requestを安全に順番マージするための仕組み。' },
  { term: 'Code scanning merge protection', aliases: ['code scanning merge protection'], description: 'code scanningの結果をルールセットでmerge条件にする保護。' },
  { term: 'Status check', aliases: ['status check'], description: 'CIやデプロイなどが成功したかを示す判定。保護ブランチの重要条件になる。' },
  { term: 'Branch up-to-date requirement', aliases: ['branch up-to-date requirement'], description: 'マージ前にhead branchをbase branch最新へ追従させる要求。' },
  { term: 'Secret scanning', aliases: ['secret scanning'], description: 'リポジトリ内の秘密情報漏えいを検出する機能。履歴全体も対象にできる。' },
  { term: 'Secret scanning alert', aliases: ['secret scanning alert'], description: 'Secret scanningが秘密情報を検知したときに生成されるアラート。' },
  { term: 'Push protection', aliases: ['push protection'], description: 'Push時点で秘密情報を検出し、漏えい前にブロックする仕組み。' },
  { term: 'Push protection bypass', aliases: ['push protection bypass'], description: '正当な理由を付けてpush protectionを回避する操作。' },
  { term: 'Push protection for users', aliases: ['push protection for users'], description: '公開リポジトリへのpushを個人単位で自動保護する機能。既定で有効。' },
  { term: 'Secret scanning detection scope', aliases: ['secret scanning detection scope'], description: 'Secret scanningやpush protectionがどこまで検知対象にするかの範囲。' },
  { term: 'Dependency graph', aliases: ['dependency graph'], description: 'リポジトリが依存するパッケージやワークフロー依存を可視化する仕組み。' },
  { term: 'Dependabot alert', aliases: ['dependabot alert'], description: '依存関係に脆弱性が見つかったときの警告。' },
  { term: 'Dependabot security update', aliases: ['dependabot security update'], description: '脆弱性修正のための自動Pull Request。' },
  { term: 'Dependabot version update', aliases: ['dependabot version update'], description: '依存パッケージを新しい通常版へ上げる自動Pull Request。' },
  { term: 'dependabot.yml', description: 'Dependabotの更新対象や頻度を定義する設定ファイル。' },
  { term: 'Auto-triage rule', aliases: ['auto-triage rule'], description: 'Dependabotやセキュリティ通知を自動分類するためのルール。' },
  { term: 'GitHub Importer', aliases: ['github importer'], description: '他のバージョン管理サービスからGitHubへリポジトリを移行するためのWebツール。SVNの直接取り込みには非対応。' },
  { term: 'GitHub Team', aliases: ['github team'], description: '組織内で権限やアクセスをまとめて管理するためのGitHubのチーム機能。' },
  { term: 'trunk', description: 'SVNにおける開発の主系統。Gitのmainブランチに相当する。' },
  { term: 'clone', description: 'リモートリポジトリの完全な複製をローカルに作成する操作。' },
  { term: 'push', description: 'ローカルのコミットをリモートリポジトリへ送信する操作。' },
  { term: 'pull', description: 'リモートリポジトリの変更をローカルに取得して統合する操作。' },
  { term: 'fetch', description: 'リモートリポジトリの変更をローカルに取得するが、統合はしない操作。' },
  { term: 'checkout', description: 'ブランチの切り替えや特定のコミット状態への移動を行う操作。' },
  { term: 'rebase', description: 'コミット履歴を別のブランチの先端に付け替えて、履歴を直線的に整理する操作。' },
  { term: 'stash', description: '作業中の変更を一時的に退避させ、後から復元できるようにする機能。' },
  { term: 'diff', description: 'ファイルやコミット間の差分を表示する操作。' },
  { term: 'HEAD', aliases: ['head'], description: '現在チェックアウトしているブランチやコミットを指すポインタ。' },
  { term: 'コンフリクト', description: '同じ箇所を複数人が変更した場合に、自動統合できず手動解決が必要になる状態。' },
  { term: 'マージコンフリクト', description: 'マージ時に同一箇所の変更が競合し、手動で解決が必要になる状態。' },
  { term: 'リモートリポジトリ', description: 'ネットワーク上に配置され、チームで共有するリポジトリ。' },
  { term: 'ローカルリポジトリ', description: '開発者の手元にある、リモートリポジトリの複製。' },
  { term: 'main', description: 'リリース可能な状態を維持する主ブランチ。旧称master。' },
  { term: 'develop', description: '次回リリースに向けた開発の統合先となるブランチ。' },
  { term: 'release branch', description: 'リリース準備のために作成するブランチ。最終的な修正やバージョン番号付与を行う。' },
  { term: 'GitHub Actions', aliases: ['github actions'], description: 'GitHubに組み込まれたCI/CD基盤。pushやPRをトリガーにワークフローを自動実行できる。' },
  { term: 'GitHub Pages', aliases: ['github pages'], description: 'GitHubリポジトリから静的Webサイトを公開できるホスティング機能。' },
  { term: 'GitHub Packages', aliases: ['github packages'], description: 'GitHubに統合されたパッケージレジストリ。npm、Maven、Dockerイメージなどを管理できる。' },
  { term: 'GitHub CLI', aliases: ['github cli'], description: 'ターミナルからGitHubの操作を行うコマンドラインツール。ghコマンドで利用する。' },
  { term: 'Fork', aliases: ['fork'], description: '他人のリポジトリを自分のアカウントに複製し、独立して変更を加えられるようにする機能。' },
  { term: 'Collaborator', aliases: ['collaborator'], description: 'リポジトリへの書き込み権限を持つ共同作業者。' },
  { term: 'Release', aliases: ['release', 'リリース（github）'], description: '特定のタグに対してバイナリやリリースノートを添付して公開する機能。' },
  { term: 'Wiki', aliases: ['wiki'], description: 'リポジトリに付属するドキュメント管理機能。Markdown形式で記述できる。' },
  { term: 'README', aliases: ['readme'], description: 'リポジトリの概要、セットアップ手順、使い方などを記載するファイル。' },
  { term: 'Workflow', aliases: ['workflow', 'わーくふろー（github actions）'], description: 'GitHub Actionsで定義する自動処理全体。YAMLで記述する。' },
  { term: 'Workflow run', aliases: ['workflow run'], description: 'あるworkflowが一度実行された単位。' },
  { term: 'Event trigger', aliases: ['event trigger'], description: 'Workflow実行のきっかけとなるイベント。' },
  { term: 'repository_dispatch', description: '外部からREST API経由でworkflowを起動できるイベント。' },
  { term: 'workflow_dispatch', description: '手動実行のためのトリガー。' },
  { term: 'Scheduled workflow', aliases: ['scheduled workflow'], description: '定期時刻で実行されるworkflow。' },
  { term: 'Job', aliases: ['job'], description: 'Workflow内でrunner上に実行される処理単位。複数stepを含む。' },
  { term: 'Job dependency', aliases: ['job dependency'], description: 'あるjobが別job完了を待つ依存関係。' },
  { term: 'Step', aliases: ['step'], description: 'Jobの中で順番に実行される最小処理単位。scriptかactionを実行する。' },
  { term: 'Action', aliases: ['action'], description: 'Workflow内で再利用できる処理単位。繰り返し処理を簡潔に書ける。' },
  { term: 'Composite action', aliases: ['composite action'], description: '複数stepをまとめて一つのactionのように再利用できる形式。' },
  { term: 'Reusable workflow', aliases: ['reusable workflow'], description: 'Workflow全体を別workflowから呼び出して再利用する仕組み。' },
  { term: 'Caller workflow', aliases: ['caller workflow'], description: 'Reusable workflowを呼び出す側のworkflow。' },
  { term: 'Called workflow', aliases: ['called workflow'], description: 'Reusable workflowとして呼ばれる側のworkflow。' },
  { term: 'Runner', aliases: ['runner'], description: 'GitHub Actionsのjobを実行するサーバー。各jobはrunner上で動く。' },
  { term: 'GitHub-hosted runner', aliases: ['github-hosted runner'], description: 'GitHubが提供する標準runner。新しい仮想マシンで実行される。' },
  { term: 'Self-hosted runner', aliases: ['self-hosted runner'], description: '自分たちで用意、管理するrunner。ハードウェアやOSを自由に選べる。' },
  { term: 'Runner label', aliases: ['runner label'], description: 'Self-hosted runnerを特性ごとに指定するためのラベル。' },
  { term: 'Runner group', aliases: ['runner group'], description: 'Self-hosted runnerをまとめてアクセス制御する単位。' },
  { term: 'Matrix strategy', aliases: ['matrix strategy'], description: '複数条件の組み合わせでjobを並列展開する方式。' },
  { term: 'Concurrency', aliases: ['concurrency'], description: '同時実行の衝突を避けるためworkflowやjobを制御する仕組み。' },
  { term: 'Artifact', aliases: ['artifact'], description: 'Workflow実行中に生成、保存、受け渡しされる成果物。' },
  { term: 'Workflow template', aliases: ['workflow template'], description: '新しいworkflow作成を簡単にするためのひな形。' },
  { term: 'GITHUB_TOKEN', aliases: ['github_token'], description: 'Workflow実行時に自動付与されるトークン。' },
  { term: 'Repository secret', aliases: ['repository secret'], description: 'リポジトリ単位で管理するGitHub Actions用の秘密情報。' },
  { term: 'Organization secret', aliases: ['organization secret'], description: '組織単位で複数リポジトリへ共有できる秘密情報。' },
  { term: 'Environment secret', aliases: ['environment secret'], description: 'Environmentにひもづく秘密情報。job開始時に読み込まれる。' },
  { term: 'Secret precedence', aliases: ['secret precedence'], description: '同名secretが複数レベルにある場合、environment secretが優先されるルール。' },
  { term: 'Secret redaction', aliases: ['secret redaction'], description: 'ログ中の秘密情報をGitHubが自動で伏せる仕組み。' },
  { term: 'Secret size limit', aliases: ['secret size limit'], description: 'GitHub secretsのサイズ上限。1件あたり48KB。' },
  { term: 'Secrets not passed from forks', aliases: ['secrets not passed from forks'], description: 'GITHUB_TOKENを除き、fork由来workflowにはsecretsが渡らない制約。' },
  { term: 'Environment', aliases: ['environment'], description: 'デプロイや保護ルール、secretを束ねるGitHubの単位。' },
  { term: 'Environment protection rule', aliases: ['environment protection rule'], description: 'Environmentを使うjobに対して承認や条件を要求するルール。' },
  { term: 'GitHub Codespaces', aliases: ['github codespaces'], description: 'GitHub上で使えるクラウド開発環境。' },
  { term: 'Codespace', aliases: ['codespace'], description: '実際に起動した1つのクラウド開発環境インスタンス。' },
  { term: 'Codespace lifecycle', aliases: ['codespace lifecycle'], description: 'codespaceの作成、停止、再開、破棄を通じたライフサイクル全体。' },
  { term: 'Dev container', aliases: ['dev container'], description: '開発環境の定義と実行に使うコンテナ構成。' },
  { term: 'devcontainer.json', description: 'dev containerの設定ファイル。' },
  { term: 'Prebuild', aliases: ['prebuild'], description: 'Codespacesを事前構築して起動を速くする仕組み。' },
  { term: 'Prebuild ready', aliases: ['prebuild ready'], description: '指定branch、dev container、regionでprebuildが用意済みであることを示す表示。' },
  { term: 'Temporary codespace', aliases: ['temporary codespace'], description: 'Prebuild作成時にGitHubが一時的に作るcodespace。' },
  { term: 'onCreateCommand', aliases: ['oncreatecommand'], description: 'devcontainer.jsonでcodespace作成時に実行するコマンド。' },
  { term: 'updateContentCommand', aliases: ['updatecontentcommand'], description: 'コンテンツ更新時に実行するdev container設定コマンド。' },
  { term: 'Machine type', aliases: ['machine type'], description: 'Codespaceに割り当てるCPU、メモリ構成の種類。' },
  { term: 'Port forwarding', aliases: ['port forwarding'], description: 'Codespace内で動くTCPポートをローカルから使えるようにする仕組み。' },
  { term: 'Forwarded port', aliases: ['forwarded port'], description: '外部へ公開されたcodespace内ポート。' },
  { term: 'Automatic port forwarding', aliases: ['automatic port forwarding'], description: 'localhost:PORTのような出力を検知してGitHubが自動で転送する仕組み。' },
  { term: 'forwardPorts property', aliases: ['forwardports property'], description: 'devcontainer.jsonで自動転送したいポートを定義する設定。' },
  { term: 'portsAttributes', aliases: ['portsattributes'], description: '転送ポートのラベルなどをdevcontainer.jsonで定義する設定。' },
  { term: 'Port label', aliases: ['port label'], description: '転送ポートへ付ける名前。PORTSタブで識別しやすくなる。' },
  { term: 'Public port visibility', aliases: ['public port visibility'], description: '転送ポートを公開アクセス可能にする可視性設定。' },
  { term: 'Organization-restricted port visibility', aliases: ['organization-restricted port visibility'], description: 'ポートを組織内だけに共有させる制御。' },
  { term: 'Development environment secret', aliases: ['development environment secret'], description: 'Codespacesで使うための秘密情報。' },
  { term: 'Repository-level development secret', aliases: ['repository-level development secret'], description: '特定リポジトリ向けに設定するCodespaces secret。' },
  { term: 'Organization-level development secret', aliases: ['organization-level development secret'], description: '組織単位で共有できるCodespaces secret。' },
  { term: 'Account-specific Codespaces secret', aliases: ['account-specific codespaces secret'], description: '個人アカウント単位で管理するCodespaces secret。' },
  { term: 'Dotfiles', aliases: ['dotfiles'], description: 'Codespaces起動時に自分のシェル設定などを反映する個人設定ファイル群。' },
  { term: 'GitHub CLI for Codespaces', aliases: ['github cli for codespaces'], description: 'ghコマンドでcodespaceの作成、接続、一覧、ポート確認などを行う使い方。' },
  { term: 'gh codespace ports', description: 'Codespaceの転送ポート情報を確認するGitHub CLIコマンド。' },
  { term: 'gh codespace ssh', description: 'CodespaceへSSH接続するGitHub CLIコマンド。' },
  { term: 'X-GitHub-Token header', aliases: ['x-github-token header'], description: 'Private portへcurlやPostmanで接続するときに使う認証ヘッダー。' },
  { term: 'Workflow dependency graph entry', aliases: ['workflow dependency graph entry'], description: 'Reusable workflowはdependency graph上で依存先として見えることがある。' },
  { term: 'Four-level reusable workflow limit', aliases: ['four-level reusable workflow limit'], description: 'Reusable workflowは最大4階層まで接続できる。' },
  { term: 'Twenty unique reusable workflow limit', aliases: ['twenty unique reusable workflow limit'], description: '1つのworkflow fileから参照できるunique reusable workflow数には上限がある。' },
  { term: 'GitHubリポジトリ', aliases: ['githubリポジトリ', 'github repository'], description: 'GitHubでコードやファイルをGit管理するプロジェクトの保存場所。Issue・PR・Actions・Wikiなどの機能が統合されており、公開・非公開・内部の3種の可視性を選択できる。' },
  { term: 'GitHub Organization', aliases: ['github organization', 'github org'], description: '企業やOSSプロジェクトが複数のリポジトリとメンバーをまとめて管理するGitHubのアカウント単位。チーム・権限・ポリシー・支払いを一元管理でき、個人アカウントとは独立して運用する。' },
  { term: 'GitHub Enterprise', aliases: ['github enterprise', 'ghe', 'github enterprise cloud', 'github enterprise server'], description: '大規模企業向けのGitHubプラン。SAML SSO・監査ログ・SCIM・Enterpriseポリシー・IPホワイトリストなどを提供する。クラウド版とオンプレミスのServer版がある。' },
  { term: 'GitHub Gist', aliases: ['github gist', 'gist'], description: 'GitHubが提供するコードスニペットやテキストを共有するサービス。単一ファイルから複数ファイルのセットを公開・非公開で保存でき、各GistはGitリポジトリとして管理されバージョン履歴も持つ。' },
  { term: 'GitHub Discussions', aliases: ['github discussions', 'discussions'], description: 'GitHubリポジトリやOrganization内でコミュニティの会話・Q&A・アイデア共有を行うフォーラム機能。Issueと異なり具体的なタスクではなくオープンな議論や情報共有を目的とする。' },
  { term: 'GitHub Issues', aliases: ['github issues', 'issues', 'issue tracker'], description: 'バグ報告・機能要望・タスク管理などをリポジトリ単位で追跡するGitHubの課題管理機能。ラベル・マイルストーン・アサイニー・プロジェクトと連携して進捗を管理する。' },
  { term: 'GitHub Projects', aliases: ['github projects', 'projects', 'github projects v2'], description: 'GitHub IssueやPRをボード・テーブル・ロードマップなど複数ビューで管理するプロジェクト管理ツール。カスタムフィールドや自動化ワークフローを持ち、Organizationをまたいで利用できる。' },
  { term: 'GitHubマイルストーン', aliases: ['githubマイルストーン', 'github milestones', 'sprint milestone'], description: '特定のリリースや期限に向けてIssueやPRをグループ化するGitHubの機能。オープン/クローズ数から進捗率が可視化され、バージョン計画やスプリント管理に活用される。' },
  { term: 'GitHubラベル', aliases: ['githubラベル', 'github labels', 'issue label'], description: 'IssueやPRを分類・フィルタリングするためにリポジトリ単位で設定するタグ。bug・enhancementなどデフォルトラベルのほかカスタムラベルを色付きで定義でき、自動化トリガーにも使われる。' },
  { term: 'GitHubアサイニー', aliases: ['githubアサイニー', 'github assignees', 'pr assignee'], description: 'IssueやPRの担当者として設定されるGitHubユーザー。1件につき複数人を割り当て可能で、作業の責任者を明確にしてチームの進捗管理やレビュー依頼に役立てる仕組み。' },
  { term: 'プルリクエストレビュー', aliases: ['pull request review', 'pr review'], description: 'PRに対してレビュアーがコメント・変更要求・承認を行う仕組み。Approve・Request changes・Commentの3種類があり、ブランチ保護ルールと組み合わせてマージ前の品質ゲートとして機能する。' },
  { term: 'プルリクエストテンプレート', aliases: ['pull request template', 'pr template'], description: '新規PR作成時の説明欄に自動入力されるMarkdownテンプレート。`.github/pull_request_template.md`に配置し、変更内容・テスト手順・チェックリストなどを記述して標準化する。' },
  { term: '自動マージ', aliases: ['auto-merge', 'github auto-merge'], description: 'すべての必須ステータスチェックとレビューが通過した時点でPRを自動的にマージするGitHubの機能。手動マージの待ち時間を削減し、マージキューと組み合わせて競合を防ぐことができる。' },
  { term: 'ブランチ保護ルール', aliases: ['branch protection rules', 'branch protection'], description: '特定ブランチへの直接プッシュ禁止・必須レビュー数・必須ステータスチェックなどを強制するGitHub設定。mainブランチなどを誤操作から保護し、チームのコード品質ポリシーを強制する。' },
  { term: '必須レビュー', aliases: ['required reviews', 'required pull request reviews'], description: 'PRをマージするために必要な承認レビュー数を強制するブランチ保護の設定項目。最低承認数・コードオーナーによるレビュー必須・強制プッシュ後の承認リセットなどを細かく設定できる。' },
  { term: 'CODEOWNERSファイル', aliases: ['codeownersファイル', 'codeowners file', '.github/codeowners'], description: 'リポジトリ内のファイルやディレクトリのオーナーを指定するファイル。`.github/CODEOWNERS`に配置し、該当パスを変更するPRが作成されると指定ユーザー・チームが自動でレビュアーに追加される。' },
  { term: 'GitHub Actions ワークフロー', aliases: ['github actions ワークフロー', 'actions workflow'], description: 'GitHub Actionsの実行単位。YAMLファイルで定義し、トリガー（push・PR・スケジュールなど）とジョブのステップを記述する。`.github/workflows/`ディレクトリに配置して動作する。' },
  { term: 'ワークフロー・ディスパッチ', aliases: ['workflow dispatch', 'workflow_dispatch event'], description: 'GitHub ActionsワークフローをUIまたはAPIから手動でトリガーするイベント。入力パラメータを定義でき、任意のタイミングでデプロイやバッチ処理を実行する際に活用される。' },
  { term: '再利用可能ワークフロー', aliases: ['reusable workflows', 'workflow_call'], description: '他のワークフローから呼び出して利用できるGitHub Actionsのワークフロー。`workflow_call`トリガーで定義し、共通CI処理をDRY原則に従って一元管理することができる。' },
  { term: 'コンポジットアクション', aliases: ['composite actions'], description: '複数のステップをひとつのカスタムActionとしてまとめるGitHub Actionsの仕組み。`action.yml`にcompositeタイプで定義し、シェルスクリプトや他のActionを組み合わせてワークフロー間で再利用できる。' },
  { term: 'GitHub ホステッドランナー', aliases: ['github ホステッドランナー', 'github-hosted runners', 'github hosted runner'], description: 'GitHubが管理・提供する仮想マシン上で動作するGitHub Actionsの実行環境。ubuntu-latest・windows-latest・macos-latestなどOSを選択でき、毎回クリーンな状態で起動する。' },
  { term: 'ラージャーランナー', aliases: ['larger runners', 'github larger runners'], description: '標準より多くのCPU・メモリ・ストレージを持つGitHubホステッドランナー。大規模ビルドやテストを高速化するために使用し、TeamおよびEnterpriseプランで利用可能なオプション。' },
  { term: 'Actionsマーケットプレイス', aliases: ['actionsマーケットプレイス', 'actions marketplace', 'github marketplace'], description: 'コミュニティや企業が公開するGitHub Actionsのアクションを検索・利用できるプラットフォーム。`uses:`キーワードでワークフローに組み込み、多様なCI/CD処理を手軽に追加できる。' },
  { term: 'GitHub Actionsキャッシュ', aliases: ['github actionsキャッシュ', 'github actions cache', 'actions/cache'], description: 'ワークフロー実行間でnode_modulesやビルド成果物などを保存・再利用するGitHub Actionsの機能。`actions/cache`アクションで制御し、依存関係のダウンロード時間を削減してビルドを高速化する。' },
  { term: 'GitHub Actionsアーティファクト', aliases: ['github actionsアーティファクト', 'github actions artifacts', 'actions/upload-artifact'], description: 'ワークフロー実行後にビルド成果物やテストレポートをGitHubに保存・ダウンロードするための仕組み。`actions/upload-artifact`と`actions/download-artifact`アクションで操作する。' },
  { term: 'Actionsマトリックス', aliases: ['actionsマトリックス', 'github actions matrix'], description: '複数のOSやNode.jsバージョンなどの組み合わせで同一ジョブを並列実行するGitHub Actionsの`strategy.matrix`機能。クロスプラットフォームテストを効率よく行えるようになる。' },
  { term: 'Actionsコンカレンシー', aliases: ['actionsコンカレンシー', 'github actions concurrency', 'concurrency group'], description: '同一グループのワークフロー実行をキャンセルまたは待機させるGitHub Actionsの`concurrency`設定。古いデプロイジョブを自動キャンセルし最新コードのみをデプロイするために多用される。' },
  { term: 'GitHub Actionsシークレット', aliases: ['github actionsシークレット', 'github actions secrets', 'actions secrets'], description: 'APIキーやパスワードなどの機密情報をGitHub Actionsのワークフローに安全に渡すための暗号化変数。Organization・リポジトリ・環境レベルで設定でき、ログにはマスクされて表示される。' },
  { term: 'GitHub Actions変数', aliases: ['github actions変数', 'github actions variables', 'actions variables'], description: '機密ではない設定値をワークフロー間で共有するためのGitHub Actionsの変数機能。Secretsとは異なりログに値が表示される。Organization・リポジトリ・環境レベルで管理できる。' },
  { term: 'GitHub環境', aliases: ['github環境', 'github environments', 'deployment environment'], description: 'production・stagingなどのデプロイ先環境をGitHubで管理する仕組み。環境ごとにシークレット・変数・保護ルールを設定でき、ワークフローのジョブに`environment:`キーで紐付ける。' },
  { term: 'デプロイ保護ルール', aliases: ['deployment protection rules'], description: 'GitHub環境へのデプロイ前に承認・待機・カスタムチェックを要求するルール。特定レビュアーによる手動承認やタイマー待機を設定して本番環境への誤デプロイを防ぐことができる。' },
  { term: 'GitHub コンテナレジストリ', aliases: ['github コンテナレジストリ', 'github container registry', 'ghcr', 'ghcr.io'], description: 'GitHubが提供するDockerコンテナイメージのホスティングサービス。`ghcr.io`ドメインでアクセスし、GitHub Packagesの一部としてリポジトリやOrganizationに紐付けて管理できる。' },
  { term: 'GitHub npm レジストリ', aliases: ['github npm レジストリ', 'npm registry (github)', 'github npm registry'], description: 'GitHub Packagesでnpmパッケージをホストするサービス。`@scope/package`形式で公開・インストールでき、プライベートパッケージをOrganization内で安全に共有する際に使われる。' },
  { term: 'GitHub Releases', aliases: ['github releases', 'releases', 'github release'], description: 'タグに基づいてリリースバイナリ・リリースノート・アセットをGitHub上で公開する仕組み。ユーザーへの配布ページとして機能し、GitHub Actions経由で自動作成することも多い。' },
  { term: '自動生成リリースノート', aliases: ['release notes (auto-generated)', 'auto-generated release notes'], description: 'GitHubがPRのタイトルやラベルをもとにリリースノートを自動生成する機能。`.github/release.yml`で貢献者・変更カテゴリの表示形式をカスタマイズして整ったChangelogを作成できる。' },
  { term: 'Gitタグ', aliases: ['gitタグ', 'git tag', 'version tag'], description: '特定のコミットに付ける名前付き参照でバージョン番号（v1.0.0など）の記録に使われる。軽量タグと、署名付きメタデータを持つ注釈付きタグ（git tag -a）の2種類がある。' },
  { term: '注釈付きタグ', aliases: ['annotated tag', 'git tag -a'], description: '作成者・日時・GPG署名・メッセージを持つGitタグ。`git tag -a`で作成し、リリースなど公式なバージョニングに推奨される。軽量タグと異なりGitオブジェクトとして個別に保存される。' },
  { term: 'Gitブランチ', aliases: ['gitブランチ', 'git branch', 'branch pointer'], description: 'Gitの特定コミットを指す軽量な可動ポインタ。並行開発に使われ、featureブランチ・mainブランチなどを使い分ける。コミットのたびにブランチ先端のポインタが前方に移動する。' },
  { term: 'Gitコミット', aliases: ['gitコミット', 'git commit', 'commit object'], description: '変更内容のスナップショットをリポジトリの歴史に記録するGitの基本操作。SHA-1ハッシュで一意に識別され、作成者・コミッタ・メッセージ・親コミットへの参照を持つ。' },
  { term: 'Gitマージ', aliases: ['gitマージ', 'git merge', 'branch merge'], description: '2つのブランチの変更履歴を統合するGit操作。Fast-forwardマージとマージコミットを作るthree-way mergeがある。競合が発生した場合はコンフリクト箇所の手動解消が必要となる。' },
  { term: 'Git チェリーピック', aliases: ['git チェリーピック', 'git cherry-pick', 'cherry-pick command'], description: '特定のコミットを別のブランチに個別に適用するGit操作。`git cherry-pick <hash>`で実行し、hotfixのbackportや特定変更の選択的な取り込みに使われる。' },
  { term: 'Gitリセット', aliases: ['gitリセット', 'git reset'], description: 'HEADや作業ツリーの状態を指定コミットに戻すGit操作。`--soft`（インデックス保持）・`--mixed`（デフォルト）・`--hard`（全変更破棄）の3モードがあり使い分ける。' },
  { term: 'Gitリバート', aliases: ['gitリバート', 'git revert'], description: '特定コミットの変更を打ち消す新しいコミットを作成するGit操作。履歴を書き換えないため共有ブランチで安全に変更を取り消せる。`git reset`の代わりに本番ブランチで推奨される。' },
  { term: 'Git バイセクト', aliases: ['git バイセクト', 'git bisect'], description: '二分探索で不具合を導入したコミットを特定するGitコマンド。良好と不良なコミットを指定すると自動的に中間コミットをチェックアウトし、原因コミットを効率よく絞り込める。' },
  { term: 'Gitワークツリー', aliases: ['gitワークツリー', 'git worktree'], description: '1つのGitリポジトリから複数の作業ツリーをチェックアウトして同時に操作できる機能。`git worktree add`で追加し、ブランチ切り替えなしに異なるブランチを並行して作業できる。' },
  { term: 'Gitサブモジュール', aliases: ['gitサブモジュール', 'git submodule', 'submodule'], description: 'あるGitリポジトリを別のリポジトリのサブディレクトリとして埋め込む仕組み。`.gitmodules`ファイルでURLとパスを管理し、共通ライブラリを外部リポジトリとして参照する場合に使う。' },
  { term: 'Git サブツリー', aliases: ['git サブツリー', 'git subtree'], description: '外部リポジトリの内容を別リポジトリのサブディレクトリに統合するGitの仕組み。サブモジュールと異なりファイルが直接リポジトリに含まれるため、クローン時に追加の初期化手順が不要。' },
  { term: 'Git フック', aliases: ['git フック', 'git hooks', 'pre-commit hook'], description: 'コミット・プッシュ・マージなどのGitイベント発生時に自動実行されるスクリプト。`pre-commit`でlint実行、`commit-msg`でメッセージ検証などに使われ、`.git/hooks/`ディレクトリに配置する。' },
  { term: '.gitattributes', aliases: ['gitattributes', 'git attributes file'], description: 'ファイルパスごとにGitの振る舞いを設定するファイル。改行コード正規化（eol）・diff設定・マージ戦略・言語統計の除外（linguist-vendored）などをパスパターンで指定できる。' },
  { term: 'ホットフィックスブランチ', aliases: ['hotfix branch'], description: '本番環境の緊急バグを修正するためにmain（またはproduction）ブランチから直接分岐するブランチ。修正後にmainとdevelopの両方へマージしてバージョンタグを付けるのが標準的な運用。' },
  { term: 'developブランチ', aliases: ['develop branch', 'integration branch'], description: 'Git Flowにおける統合ブランチ。完了したfeatureブランチをマージして次回リリースの内容を蓄積する役割を持ち、リリース準備が整ったらreleaseブランチに分岐する。' },
  { term: 'リモートリポジトリ管理', aliases: ['remote management', 'git remote'], description: 'ネットワーク越しにアクセスするGitリポジトリを`git remote`コマンドで管理すること。originやupstreamとして複数のリモートを登録でき、fetch・push・pullの対象を柔軟に切り替えられる。' },
  { term: 'アップストリームリモート', aliases: ['upstream remote'], description: 'フォーク元の本家リポジトリを指すGitの慣習的なリモート名。`git remote add upstream <url>`で登録し、本家の変更を`git fetch upstream`で取り込んで自分のフォークに同期する。' },
  { term: 'オリジンリモート', aliases: ['origin remote', 'origin'], description: '`git clone`時に自動設定されるデフォルトのリモートリポジトリ名。自分のフォークまたはプロジェクトのリモートを指し、`git push origin`や`git pull origin`の操作対象となる。' },
  { term: 'Git reflog', aliases: ['git reflog', 'reflog'], description: 'HEADや各ブランチ参照の変更履歴をローカルに記録するGitのログ。誤ったリセットやブランチ削除後でも`git reflog`で過去のコミットSHAを確認し、`git reset`で復元できる。' },
  { term: 'Git diff', aliases: ['git diff', 'git diff command'], description: '作業ツリー・インデックス・コミット間の差分を表示するGitコマンド。`git diff HEAD`で未コミット変更、`git diff branch1..branch2`でブランチ間差分を確認できる。' },
  { term: 'Git blame', aliases: ['git blame', 'blame view'], description: 'ファイルの各行が最後に変更されたコミットと変更者を表示するGitコマンド。バグの原因コミットや変更理由を追跡するときに使い、GitHub UIのBlameビューでも確認できる。' },
  { term: 'スカッシュマージ', aliases: ['squash merge', 'squash and merge'], description: 'PRのすべてのコミットを1つのコミットにまとめてmainブランチにマージするGitHubのマージ方式。mainブランチの履歴を簡潔に保てるが、個別コミットの詳細な経緯は失われる。' },
  { term: 'ファストフォワードマージ', aliases: ['fast-forward merge', 'ff merge'], description: 'マージ先ブランチがマージ元の祖先の場合にマージコミットを作成せずポインタを先端に移動するマージ方式。余分なコミットが不要で履歴が線形に保たれるため、履歴を整然と保ちたい場合に有効。' },
  { term: 'マージコミット', aliases: ['merge commit', 'three-way merge'], description: '2つのブランチを統合するために自動生成される親コミットを2つ持つ特別なコミット。マージ履歴が明確に残る反面、履歴が複雑になる。`--no-ff`オプションで強制的に作成できる。' },
  { term: 'Git fetch', aliases: ['git fetch', 'fetch command'], description: 'リモートリポジトリの最新変更をローカルにダウンロードするが作業ツリーには反映しないGit操作。`git fetch origin`でリモート追跡ブランチを更新し、内容確認後にmergeかrebaseする。' },
  { term: 'Git pull', aliases: ['git pull', 'pull command'], description: 'リモートリポジトリの変更をfetchしてローカルブランチにマージまたはrebaseするGit操作。`git fetch`＋`git merge`の短縮形で、`--rebase`オプションで線形履歴を保つことができる。' },
  { term: 'Git push', aliases: ['git push', 'push command'], description: 'ローカルブランチの変更をリモートリポジトリに送信するGit操作。`--force-with-lease`は他者の変更を上書きしない安全な強制プッシュで、rebase後のブランチ更新に推奨される。' },
  { term: 'ステージングエリア', aliases: ['staging area', 'git index area'], description: 'コミット前に変更をまとめるGitの中間領域。`git add`でファイルをインデックスに追加し、`git commit`でインデックスの内容をリポジトリに記録する。ワーキングツリーとリポジトリの橋渡し役。' },
  { term: 'ワーキングツリー', aliases: ['working tree', 'working directory'], description: '現在チェックアウトされているコミットのファイル群が展開されたディレクトリ。編集・削除・追加した変更は`git status`で確認でき、ステージングエリアに追加するまでは未追跡の状態。' },
  { term: 'デタッチドHEAD', aliases: ['デタッチドhead', 'detached head', 'detached head state'], description: 'HEADがブランチではなく特定のコミットSHAを直接指している状態。`git checkout <hash>`で発生し、この状態でのコミットはブランチに属さないため新たなブランチを作成して保存する必要がある。' },
  { term: 'Git config', aliases: ['git config', '.gitconfig'], description: 'Gitの動作設定を管理するコマンドおよびファイル。`--global`でユーザー全体、`--local`でリポジトリ固有の設定を管理し、ユーザー名・メール・エディタ・エイリアスなどを設定する。' },
  { term: 'GitHub REST API', aliases: ['github rest api', 'github api'], description: 'GitHubのリソースをHTTP経由で操作するREST形式のAPI。リポジトリ・Issue・PR・Actionsなどを操作でき、`Authorization: Bearer <token>`ヘッダーによるトークン認証を使用する。' },
  { term: 'GitHub GraphQL API', aliases: ['github graphql api', 'github graphql', 'graphql api'], description: 'GitHubが提供するGraphQL形式のAPI。必要なフィールドのみを1リクエストで取得できるためREST APIより効率的なデータ取得が可能。`api.github.com/graphql`エンドポイントで利用する。' },
  { term: 'Octokit', aliases: ['octokit', '@octokit/rest', 'octokit sdk'], description: 'GitHub公式が提供するGitHub API用のSDK。JavaScript/TypeScript向けの`@octokit/rest`が広く使われ、GitHub Actionsのカスタムアクション開発やCI/CDスクリプトでの自動化に活用される。' },
  { term: 'パーソナルアクセストークン', aliases: ['personal access token', 'pat'], description: 'GitHubのAPIやgit操作でパスワードの代わりに使用する認証トークン。クラシックPATとFine-grained PATの2種類があり、スコープや有効期限を設定して発行・管理する。' },
  { term: 'きめ細かいパーソナルアクセストークン', aliases: ['fine-grained personal access token', 'fine-grained pat'], description: '特定のリポジトリと詳細な権限スコープを個別に指定できる新世代のGitHub PAT。クラシックPATより最小権限の原則に従った設定が可能で、有効期限の設定も必須となっている。' },
  { term: 'GitHub App', aliases: ['github app', 'github apps', 'github application'], description: 'Organization・リポジトリ単位でインストールして使うGitHub統合アプリ。JWT認証でインストールトークンを取得し、CIボット・レビューボットなどに使われる。OAuthアプリより細かい権限設定が可能。' },
  { term: 'OAuthアプリ', aliases: ['oauthアプリ', 'oauth app', 'github oauth app'], description: 'OAuthフローを通じてユーザーの代理でGitHub APIを操作するアプリケーション。ユーザーが権限を付与するとアクセストークンを取得し、アプリがそのユーザーとして各種操作を行う。' },
  { term: 'デプロイキー', aliases: ['deploy key', 'ssh deploy key'], description: '特定リポジトリへのSSHアクセスを許可するためにリポジトリに登録するSSH公開鍵。読み取り専用または読み書き権限を付与でき、CIサーバーからのclone・pushなどの認証に使われる。' },
  { term: 'GitHub Webhook', aliases: ['github webhook', 'repository webhook'], description: 'GitHubのイベント（push・PR作成・Issueコメントなど）発生時に指定URLへHTTP POSTリクエストを送信する仕組み。外部サービスとのリアルタイム連携やCI起動に使われる。' },
  { term: 'リポジトリディスパッチ', aliases: ['repository dispatch', 'repository_dispatch event'], description: 'GitHub APIを通じて外部からGitHub Actionsワークフローをトリガーするイベント。`event_type`と`client_payload`でデータを渡せ、外部システムからCI/CDパイプラインを起動する際に使う。' },
  { term: 'アウトサイドコラボレーター', aliases: ['outside collaborator', 'external collaborator'], description: 'Organizationのメンバーではないが特定リポジトリへのアクセスが付与されているユーザー。外部委託先や一時的な貢献者に限定したリポジトリアクセスを与える際に利用される仕組み。' },
  { term: 'リポジトリ可視性', aliases: ['repository visibility', 'public private internal'], description: 'GitHubリポジトリのアクセス範囲設定。Public（全員閲覧可）・Private（招待者のみ）・Internal（Enterpriseメンバーのみ）の3種類があり、リポジトリ設定からいつでも変更できる。' },
  { term: 'GITHUB_TOKENシークレット', aliases: ['github_tokenシークレット', 'github_token secret', 'actions token'], description: 'GitHub Actionsワークフロー実行時に自動生成されるアクセストークン。実行中のリポジトリへのアクセス権を持ち、別途PATを発行せずにAPIやgit操作が行えるセキュリティ上の仕組み。' },
  { term: 'Dependabot', aliases: ['dependabot', 'github dependabot', 'dependabot alerts'], description: '依存パッケージのセキュリティ脆弱性や新バージョンを検知して自動でPRを作成するGitHub機能。`dependabot.yml`で更新スケジュールやターゲットエコシステムを設定する。' },
  { term: 'コードスキャニング', aliases: ['code scanning', 'github code scanning'], description: 'CodeQLなどの静的解析エンジンでリポジトリのコードセキュリティ脆弱性を自動検出するGitHub機能。プッシュやPR作成時にActionsで実行し、検出結果をセキュリティタブに表示する。' },
  { term: 'GitHub Copilot', aliases: ['github copilot', 'copilot', 'ai coding assistant'], description: 'OpenAIのモデルを基盤とするGitHubのAIコーディング支援ツール。IDE内でコードの補完・チャット・コードレビューを提供し、個人・Business・Enterpriseの各プランで利用できる。' },
  { term: 'GitHub Sponsors', aliases: ['github sponsors', 'sponsors', 'github sponsoring'], description: 'OSSメンテナーや開発者を金銭的に支援するGitHubのプラットフォーム。月額または一回払いで支援でき、GitHubは手数料を徴収しない。スポンサーバッジがプロフィールに表示される。' },
  { term: 'GitHub セキュリティアドバイザリ', aliases: ['github セキュリティアドバイザリ', 'github security advisories', 'security advisory'], description: 'リポジトリに影響する脆弱性をプライベートで調査・公開するためのGitHub機能。CVE番号の取得・非公開での協力者招待・修正完了後の公開までを一連のフローで管理できる。' },
  { term: 'git log', aliases: ['git log command'], description: 'リポジトリのコミット履歴を一覧表示するGitコマンド。`--oneline`・`--graph`・`--author`・`--since`など豊富なオプションで絞り込みやグラフ形式の表示が可能。' },
  { term: 'リベースマージ', aliases: ['rebase merge', 'rebase and merge'], description: 'PRのコミットをmainブランチの先端にrebaseしてからマージするGitHubの選択肢。マージコミットを作らず線形な履歴を維持しつつ各コミットの詳細も保持できる中間的なマージ方式。' },
  { term: 'インタラクティブリベース', aliases: ['interactive rebase', 'git rebase -i'], description: 'コミット履歴を対話的に書き換えるGit操作。`git rebase -i HEAD~N`でNコミット分を対象に、pick・squash・edit・dropなどでコミットの順番・統合・削除を行える強力な機能。' },
  { term: 'git stash', aliases: ['stash push'], description: 'コミットしていない変更を一時的に退避させるGit操作。`git stash push`で退避し`git stash pop`で復元する。ブランチ切り替え前に未完了の作業を安全に保存するために使われる。' },
  { term: 'Git rebase', aliases: ['git rebase', 'rebase operation'], description: 'あるブランチのコミット列を別のコミットの上に再適用するGit操作。マージと異なり線形な履歴を作れるが共有ブランチでは履歴書き換えとなるため、個人ブランチのみで行うのが原則。' },
  { term: 'アーカイブリポジトリ', aliases: ['archived repository', 'read-only archive'], description: '読み取り専用状態に設定されたGitHubリポジトリ。IssueやPRの作成・コードのプッシュが禁止され、過去プロジェクトの参照目的で公開・保存する場合に使用する設定。' },
  { term: 'テンプレートリポジトリ', aliases: ['template repository', 'repository template'], description: '新しいリポジトリを作成するひな型として使えるGitHubリポジトリ。コード・ディレクトリ構造・Actionsワークフローなどを含む標準構成を素早く展開でき、プロジェクト初期化を効率化する。' },
  { term: 'GitHub Codespaces 環境', aliases: ['github codespaces 環境', 'codespaces', 'cloud dev environment'], description: 'GitHubが提供するブラウザまたはVS Code経由でアクセスできるクラウド開発環境。`devcontainer.json`で環境を定義し、どこからでも同一の開発環境を即座に再現できる。' },
  { term: 'Shallow Clone', aliases: ['shallow clone', 'git clone --depth', 'shallow checkout'], description: '全履歴ではなく最新N件のコミットのみを取得する浅いクローン操作。`git clone --depth 1`でCI/CDのクローン時間を大幅に短縮でき、GitHub Actionsの`actions/checkout`でも利用される。' },
  { term: 'GitHub Copilot Chat', aliases: ['github copilot chat', 'copilot chat'], description: 'GitHub CopilotのチャットインターフェースでIDEやGitHub.com上で自然言語によりコードの説明・生成・デバッグを対話的に行える機能。コンテキストを認識して的確な回答を提供する。' },
  { term: 'GitHub Copilot Workspace', aliases: ['github copilot workspace', 'copilot workspace'], description: 'GitHub Issueから出発してコード変更の計画・実装・テストをAIが支援するタスク指向の開発環境。Issue→計画→コード→PRの一連のフローをCopilotが補助するプレビュー機能。' },
  { term: 'GitHub Copilot for CLI', aliases: ['github copilot for cli', 'gh copilot'], description: 'ターミナル上でシェルコマンドやGitコマンドをAIが提案・説明するGitHub Copilotの拡張機能。`gh copilot suggest`でコマンド提案、`gh copilot explain`でコマンド解説が利用できる。' },
  { term: 'Copilot Suggestions', aliases: ['copilot suggestions', 'インラインサジェスト', 'コード候補'], description: 'GitHub Copilotがエディタ上でリアルタイムに提示するコード補完候補。コメントや関数シグネチャを元に数行から数十行のコードをゴースト表示し、Tabキーで受け入れられる。' },
  { term: 'Copilot Context', aliases: ['copilot context', 'コパイロットコンテキスト'], description: 'GitHub Copilotが回答生成に利用するコードや情報の範囲。開いているファイル・関連ファイル・リポジトリのコードベース・カスタム指示（copilot-instructions.md）などが含まれる。' },
  { term: 'GitHub Copilot Enterprise', aliases: ['github copilot enterprise', 'copilot enterprise'], description: 'GitHub Enterprise Cloud向けの最上位Copilotプラン。組織のコードベースに基づくパーソナライズ提案・Copilot Chat on GitHub.com・ドキュメント検索・Pull Request要約・Fine-tuningなどのエンタープライズ機能を提供する。' },
  { term: 'GitHub Copilot Business', aliases: ['github copilot business', 'copilot business'], description: '組織向けGitHub Copilotのビジネスプラン。管理者によるポリシー管理・コンテンツ除外設定・使用状況レポートを提供しつつ、全開発者にCopilot補完とChatを展開できるプラン。' },
  { term: 'GitHub Code Search', aliases: ['github code search', 'コード検索'], description: 'GitHubのリポジトリを横断してコードを高精度に検索できる機能。正規表現・言語フィルタ・リポジトリ指定に対応し、シンボルやパスで絞り込めるIndexed検索エンジンを採用する。' },
  { term: 'GitHub Code Navigation', aliases: ['github code navigation', 'コードナビゲーション'], description: 'GitHub.com上でコードを閲覧する際に定義ジャンプや参照検索ができる機能。`Go to definition`・`Find all references`を使い、ブラウザ上でIDEに近いコード探索が可能になる。' },
];
