// このファイルは自動生成です。手動で編集しないでください。
// 生成元: ja.json (9552 エントリ, 226 ドメイン)
// カテゴリ: nextjs (1/1)
// 生成コマンド: npx ts-node scripts/generate-glossary-from-json.ts

import { GlossaryEntry } from '../../glossaryTypes';

export const GLOSSARY_ENTRIES_PART_001: ReadonlyArray<GlossaryEntry> = [
  // nextjs (51)
  { term: 'Next.js (framework)', aliases: ['next.js (framework)'], description: 'React を土台にフルスタック Web アプリを構築するためのフレームワークです。下位ツール設定を自動化して開発を進めやすくします。' },
  { term: 'React framework', aliases: ['react framework'], description: 'Next.js は公式 docs で React framework として位置づけられています。React Components で UI を作り、Next.js が追加機能を担います。' },
  { term: 'App Router', aliases: ['app router'], description: 'Next.js の新しいルーターで、React Server Components、Suspense、Server Functions などの最新機能を使います。' },
  { term: 'Pages Router', aliases: ['pages router'], description: 'Next.js の従来ルーターです。現在もサポートされていますが、最新機能には App Router が推奨されています。' },
  { term: 'file-system based router', description: 'ファイルやフォルダ構造からルートが決まる方式です。App Router も Pages Router もこの考え方を採用しています。' },
  { term: 'app directory', description: 'App Router のルートやレイアウト、ルートハンドラなどを置くディレクトリです。' },
  { term: 'pages directory', description: 'Pages Router でファイルごとにルートを作るためのディレクトリです。' },
  { term: 'create-next-app', description: 'Next.js アプリを作成する公式 CLI です。TypeScript や ESLint なども初期設定できます。' },
  { term: 'Layout', aliases: ['layout'], description: '【Next.js】複数ページで共有される UI 構造です。App Router ではレイアウトがルート設計の重要要素になります。 【OCI APEX】配置を視覚的に確認するタブ。' },
  { term: 'Page', aliases: ['page'], description: 'ルートに対応する表示単位です。App Router と Pages Router のどちらでも中心概念です。' },
  { term: 'Link component', aliases: ['link component'], description: 'next/link が提供するリンク用コンポーネントで、prefetching と client-side navigation を提供します。' },
  { term: 'client-side navigation', description: 'ブラウザ全体再読込なしに、クライアント側でルート遷移する方式です。Next.js の Link がこれを支えます。' },
  { term: 'prefetching', description: 'ユーザーが遷移する前にルート資産やデータを先読みする仕組みです。Next.js は Link で自動 prefetch を行います。' },
  { term: 'automatic prefetch', description: 'Link がビューポートへ入ったときなどに自動で行われる prefetch です。' },
  { term: 'manual prefetch', description: '自動ではなく、明示的に prefetch を制御するパターンです。' },
  { term: 'hover-triggered prefetch', description: 'ホバー時だけ prefetch する方式です。大きなリンク一覧で無駄な先読みを減らすのに役立ちます。' },
  { term: 'prefetch={false}', description: 'Link の自動 prefetch を無効化する指定です。リソース節約目的で使います。' },
  { term: 'Server Components', aliases: ['server components'], description: 'サーバー側でレンダリングされる React コンポーネントです。App Router はこれを前提にしています。' },
  { term: 'Client Components', aliases: ['client components'], description: 'ブラウザ側で動作する React コンポーネントです。インタラクションや Hook 使用で必要になります。' },
  { term: 'Server Rendering', aliases: ['server rendering'], description: 'ルートやページをサーバー側で生成してからクライアントへ送ることです。App Router では基本動作の一部です。' },
  { term: 'Static Rendering', aliases: ['static rendering'], description: 'ビルド時または再検証時に生成され、結果がキャッシュされるレンダリング方式です。' },
  { term: 'Dynamic Rendering', aliases: ['dynamic rendering'], description: 'リクエスト時にサーバー側で生成されるレンダリング方式です。動的ルートや変動データで使われます。' },
  { term: 'streaming (Next.js)', aliases: ['streaming (next.js)'], description: '画面生成結果を部分的に先に返し、待ち時間を感じにくくする仕組みです。Next.js は navigation 最適化文脈で説明しています。' },
  { term: 'client-side transition', description: '新しいページへ遷移するとき、全ページ再読込ではなくクライアント遷移にすることです。Next.js はこれで体感速度を高めます。' },
  { term: 'dynamic route', description: 'URL パラメータを含むルートです。App Router でも Pages Router でも対応しています。' },
  { term: 'dynamic segment', description: 'ルートパスの可変部分です。App Router では route handlers にも使えます。' },
  { term: 'loading.tsx', description: '動的ルートや遅い画面で loading UI を出すための特別ファイルです。部分 prefetch や即時遷移の体感改善に役立ちます。' },
  { term: 'error.tsx', description: 'ルート単位のエラー UI を定義するための特別ファイルです。App Router のエラーハンドリングで重要です。' },
  { term: 'generateStaticParams', aliases: ['generatestaticparams'], description: '動的セグメントの静的生成対象をビルド時に列挙するための関数です。' },
  { term: 'Route Handlers', aliases: ['route handlers'], description: 'App Router の app ディレクトリ内で custom request handlers を作る仕組みです。Web Request/Response API を使います。' },
  { term: 'route.ts / route.js', description: 'Route Handlers を定義する特別ファイルです。app ディレクトリ内で使います。' },
  { term: 'supported HTTP methods in Route Handlers', aliases: ['supported http methods in route handlers'], description: 'Route Handlers では GET、POST、PUT、PATCH、DELETE、HEAD、OPTIONS を扱えます。' },
  { term: 'API Routes', aliases: ['api routes'], description: 'Pages Router 側で API を作るための仕組みです。App Router では Route Handlers が相当機能になります。' },
  { term: 'middleware (Next.js)', aliases: ['middleware (next.js)'], description: 'リクエスト処理の前段で共通制御を行うための仕組みです。App Router の route handlers and middleware docs で案内されています。' },
  { term: 'file-system conventions', description: 'page、layout、route、loading など特別ファイル名に意味を持たせる Next.js の規約です。' },
  { term: 'partial prefetching', description: '動的ルートで loading.tsx を使うことで、全部ではなく一部だけ先読みする考え方です。' },
  { term: 'partial rendering', description: 'Next.js App Router で、変わったセグメントだけ再レンダーする考え方です。' },
  { term: 'soft navigation', description: 'App Router で shared layout を保持しつつ、必要部分だけ更新する遷移方式です。' },
  { term: 'shared layout preservation', description: '兄弟ルート間遷移でも共有レイアウトを保つ App Router の挙動です。' },
  { term: 'next/image', description: 'Next.js の組み込み画像コンポーネントです。サイズ最適化、lazy loading、layout shift 防止を提供します。' },
  { term: 'image optimization', description: 'Next.js が画像サイズ最適化、WebP 活用、lazy loading などを行う仕組みです。' },
  { term: 'visual stability', description: 'next/image が画像読み込み時の layout shift を防ぐことで得られる表示安定性です。' },
  { term: 'remotePatterns', aliases: ['remotepatterns'], description: '外部画像を安全に許可するため next.config で指定する URL パターンです。' },
  { term: 'Link viewport prefetch', aliases: ['link viewport prefetch'], description: 'Link がビューポートへ入ったときに route を自動 prefetch する挙動です。' },
  { term: 'useLinkStatus', aliases: ['uselinkstatus'], description: '遷移待ち状態を UI へ反映するための hook 的機能です。遅いネットワーク時のフィードバックに使えます。' },
  { term: 'slow network navigation feedback', description: 'prefetch が間に合わないときに、useLinkStatus などで即時ヒントを出す設計です。' },
  { term: 'bundle analyzer for Next.js', aliases: ['bundle analyzer for next.js'], description: '大きな JavaScript bundle を見つけ、削減するための分析補助です。Next.js docs では @next/bundle-analyzer に触れています。' },
  { term: 'TypeScript in App Router', aliases: ['typescript in app router'], description: 'Next.js App Router は型安全性強化を案内しており、TypeScript と組み合わせて使いやすくなっています。' },
  { term: 'App Router and React version handling', aliases: ['app router and react version handling'], description: 'Next.js docs では App Router が React の built-in canary releases を扱うと説明されています。' },
  { term: 'full-stack web applications in Next.js', aliases: ['full-stack web applications in next.js'], description: 'Next.js は公式 docs で full-stack web applications を構築するための React framework として案内されています。' },
  { term: '画像最適化（Next.js）', aliases: ['画像最適化（next.js）', 'image optimization (next.js)', 'next.js image'], description: 'Next.jsのImageコンポーネントが提供する自動画像最適化機能です。WebPへの変換やリサイズ、遅延読み込みを自動で行い表示速度を向上させます。' },
];
